INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification) VALUES
('XM6MF9', 'Coco', 'category', false, false, 'CIE-11'),
('XM9JG2', 'Álamo', 'category', false, false, 'CIE-11'),
('XM2044', 'Polen de nuez inglesa', 'category', false, false, 'CIE-11'),
('XM2EQ3', 'Anacardo', 'category', false, false, 'CIE-11'),
('XM7QD6', 'Aliso gris', 'category', false, false, 'CIE-11'),
('XM7L19', 'Avellana', 'category', false, false, 'CIE-11'),
('XM4WW3', 'Ciprés italiano', 'category', false, false, 'CIE-11'),
('XM3940', 'Cedro japonés', 'category', false, false, 'CIE-11'),
('XM8QG1', 'Ciprés japonés', 'category', false, false, 'CIE-11'),
('XM9AZ7', 'Macadamia', 'category', false, false, 'CIE-11'),
('XM0QL5', 'Mezquite', 'category', false, false, 'CIE-11'),
('XM7G21', 'Enebro de montaña', 'category', false, false, 'CIE-11'),
('XM8K37', 'Morera de papel', 'category', false, false, 'CIE-11'),
('XM6Q82', 'Maní', 'category', false, false, 'CIE-11'),
('XM1QN3', 'árbol de nuez o nogal', 'category', false, false, 'CIE-11'),
('XM7833', 'Piñón', 'category', false, false, 'CIE-11'),
('XM2B46', 'Pistache', 'category', false, false, 'CIE-11'),
('XM34T8', 'Arce rojo', 'category', false, false, 'CIE-11'),
('XM03B3', 'Morera roja', 'category', false, false, 'CIE-11'),
('XM1L09', 'Semillas de sésamo', 'category', false, false, 'CIE-11'),
('XM30J5', 'Abedul plateado', 'category', false, false, 'CIE-11'),
('XM3DB3', 'Nogal', 'category', false, false, 'CIE-11'),
('XM5VB3', 'Acacia', 'category', false, false, 'CIE-11'),
('XM3ZG1', 'Pino blanco occidental', 'category', false, false, 'CIE-11'),
('XM3DL1', 'Ceniza blanca', 'category', false, false, 'CIE-11'),
('XM3VX2', 'Abedul blanco', 'category', false, false, 'CIE-11'),
('XM6V15', 'Nogal blanco', 'category', false, false, 'CIE-11'),
('XM5AD4', 'Morera blanca', 'category', false, false, 'CIE-11'),
('XM4YR5', 'Sauce', 'category', false, false, 'CIE-11'),
('XM8SV5', 'Hierba roja', 'category', false, false, 'CIE-11'),
('XM6SX5', 'Calamares del Pacífico', 'category', false, false, 'CIE-11'),
('XM7AS2', 'Limón', 'category', false, false, 'CIE-11'),
('XM2YD2', 'Semilla de girasol', 'category', false, false, 'CIE-11'),
('XM2XV2', 'Garbanzo', 'category', false, false, 'CIE-11'),
('XM1FG7', 'Chicle dulce', 'category', false, false, 'CIE-11'),
('XM1A07', 'Goma de árbol', 'category', false, false, 'CIE-11'),
('XM0885', 'Cereza', 'category', false, false, 'CIE-11'),
('XM0RZ0', 'Plasma seminal humano', 'category', false, false, 'CIE-11'),
('XM7FG4', 'Toluidina', 'category', false, false, 'CIE-11'),
('XM7S87', 'Vapor de toluidina', 'category', false, false, 'CIE-11'),
('XM5NA2', 'Triortocresil fosfato', 'category', false, false, 'CIE-11'),
('XM90U0', 'Fosfato de trifenilo', 'category', false, false, 'CIE-11'),
('XM3FJ3', 'Acetato de vinilo', 'category', false, false, 'CIE-11'),
('XM6A87', 'Bromuro de vinilo', 'category', false, false, 'CIE-11'),
('XM23X0', 'Resina epoxi, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM9MV5', 'Butil glicidil éter', 'category', false, false, 'CIE-11'),
('XM87D3', 'Sesquióxido de cromo', 'category', false, false, 'CIE-11'),
('XM83G3', 'Borato buffer', 'category', false, false, 'CIE-11'),
('XM1FY5', 'Ciclamato', 'category', false, false, 'CIE-11'),
('XM7CN5', 'Sacarina', 'category', false, false, 'CIE-11'),
('XM5567', 'Hidroxibenzoato de propilo de sodio', 'category', false, false, 'CIE-11'),
('XM16M4', 'Barbiturato Sódico', 'category', false, false, 'CIE-11'),
('XM6DJ2', 'Iminostilbene', 'category', false, false, 'CIE-11'),
('XM45E1', 'N-ciclohexil benzotiazol sulfenamida', 'category', false, false, 'CIE-11'),
('XM90X8', 'Disulfuro dibenzotiacil', 'category', false, false, 'CIE-11'),
('XM2RH1', 'Disulfuro de dipentametilenetiuram', 'category', false, false, 'CIE-11'),
('XM3BY9', 'Monosulfuro de tetrametiltiuram', 'category', false, false, 'CIE-11'),
('XM1A88', 'Morfolinil mercaptobenzotiazol', 'category', false, false, 'CIE-11'),
('XM0XA8', 'Detergente no medicinal, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM7DD6', 'Desinfectante, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM5151', 'Polvo limpiador, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM8VR0', 'Champú, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM8B44', 'Jabón, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM5FV8', 'Líquido limpiador de ventanas, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM6PY1', 'Para terciario butifenol', 'category', false, false, 'CIE-11'),
('XM6000', '6-Metilcumarina', 'category', false, false, 'CIE-11'),
('XM2EK8', '4,4’-Diaminodifenil metano', 'category', false, false, 'CIE-11'),
('XM7N15', 'Hidroxi-isohexil 3 ciclohexano carboxaldehido', 'category', false, false, 'CIE-11'),
('XM2TV3', 'Farnesol', 'category', false, false, 'CIE-11'),
('XM3MM6', 'Bisfenol A-glicidil metacrilato', 'category', false, false, 'CIE-11'),
('XM0BY4', '2-Hidroxietilmetacrilato', 'category', false, false, 'CIE-11'),
('XM90H5', 'Dimetacrilato de diuretano', 'category', false, false, 'CIE-11'),
('XM49C3', 'Metacrilato de metilo', 'category', false, false, 'CIE-11'),
('XM58E5', 'Dietanolamina', 'category', false, false, 'CIE-11'),
('XM0L39', 'Dietilentriamina', 'category', false, false, 'CIE-11'),
('XM2TA7', 'Hexametilentetramina', 'category', false, false, 'CIE-11'),
('XM7QN7', 'Trietilentetramina', 'category', false, false, 'CIE-11'),
('XM1GH9', 'Bisfenol A', 'category', false, false, 'CIE-11'),
('XM7AX9', 'Cresil glicidil éter', 'category', false, false, 'CIE-11'),
('XM1AH4', '2-bromo-2-nitropropano-1,3-diol.', 'category', false, false, 'CIE-11'),
('XM3TN8', 'Mercaptobenzotiazol', 'category', false, false, 'CIE-11'),
('XM2ZT3', 'Metoxicinamato de etilhexilo', 'category', false, false, 'CIE-11'),
('XM63U8', 'Octocrileno', 'category', false, false, 'CIE-11'),
('XM3YZ8', 'Octiltriazona', 'category', false, false, 'CIE-11'),
('XM8VV3', 'Aminoetilisotiourio', 'category', false, false, 'CIE-11'),
('XM7W63', 'Cacodilato de sodio (no medicinal)', 'category', false, false, 'CIE-11'),
('XM6GU7', 'Hidroxianisola butilatada', 'category', false, false, 'CIE-11'),
('XM2YA2', 'Coenzima A', 'category', false, false, 'CIE-11'),
('XM4S70', 'Cogalactoisomerasa', 'category', false, false, 'CIE-11'),
('XM1X04', 'Lactosa (como excipiente)', 'category', false, false, 'CIE-11'),
('XM82Y6', 'Metiletilcelulosa', 'category', false, false, 'CIE-11'),
('XM39E8', 'Pentano', 'category', false, false, 'CIE-11'),
('XM2RB2', 'Benzisotiazolinona', 'category', false, false, 'CIE-11'),
('XM6XV7', 'Metilenbis(metiloxazolidina)', 'category', false, false, 'CIE-11'),
('XM88M1', 'DMDM hidantoína', 'category', false, false, 'CIE-11'),
('XM8DV5', 'Metilcloroisotiazolinona y metilisotiazolinona (3:1)', 'category', false, false, 'CIE-11'),
('XM87J0', 'Metilisotiazolinona', 'category', false, false, 'CIE-11'),
('XM9NB7', 'Metildibromo glutaronitrilo y fenoxietanol', 'category', false, false, 'CIE-11'),
('XM04A1', 'Metil parahidroxibenzoato', 'category', false, false, 'CIE-11'),
('XM1CG8', 'Etil parahidroxibenzoato', 'category', false, false, 'CIE-11'),
('XM0XV1', 'propil parahidroxibenzoato', 'category', false, false, 'CIE-11'),
('XM38K5', 'Butil parahidroxibenzoato', 'category', false, false, 'CIE-11'),
('XM51H6', 'Diazolidinil urea', 'category', false, false, 'CIE-11'),
('XM5TQ9', 'Imidazolidinil urea', 'category', false, false, 'CIE-11'),
('XM0562', 'Fenticlor', 'category', false, false, 'CIE-11'),
('XM6F66', 'Líquido de soldadura, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM44A4', 'Harina de hueso', 'category', false, false, 'CIE-11'),
('XM77G6', 'Hongos ingeridos como alimento, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XM00E5', 'Claviceps purpurea', 'category', false, false, 'CIE-11'),
('XM4L77', 'Carne nociva, no bacteriana, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM3825', 'Proteína animal', 'category', false, false, 'CIE-11'),
('XM9Y41', 'Pollo', 'category', false, false, 'CIE-11'),
('XM4500', 'pluma de pollo', 'category', false, false, 'CIE-11'),
('XM66A9', 'Excrementos de cacatúa', 'category', false, false, 'CIE-11'),
('XM9LW5', 'pluma de cacatúa', 'category', false, false, 'CIE-11'),
('XM9JZ2', 'Suero de cacatúa', 'category', false, false, 'CIE-11'),
('XM6AD6', 'Clara de huevo', 'category', false, false, 'CIE-11'),
('XM2E06', 'Huevo entero', 'category', false, false, 'CIE-11'),
('XM9CD1', 'Yema', 'category', false, false, 'CIE-11'),
('XM2PB2', 'Pluma de ganso', 'category', false, false, 'CIE-11'),
('XM3LH5', 'Pluma de pato', 'category', false, false, 'CIE-11'),
('XM95M8', 'Pescado', 'category', false, false, 'CIE-11'),
('XM6BL6', 'Bacalao', 'category', false, false, 'CIE-11'),
('XM8Q65', 'Salmón', 'category', false, false, 'CIE-11'),
('XM3QU9', 'Atún', 'category', false, false, 'CIE-11'),
('XM31E6', 'Hipogloso', 'category', false, false, 'CIE-11'),
('XM8Y82', 'Sardina', 'category', false, false, 'CIE-11'),
('XM64N8', 'Trucha', 'category', false, false, 'CIE-11'),
('XM5MB3', 'Cangrejo', 'category', false, false, 'CIE-11'),
('XM9JT3', 'Langosta', 'category', false, false, 'CIE-11'),
('XM7E84', 'Camarón', 'category', false, false, 'CIE-11'),
('XM55Z4', 'Ostra', 'category', false, false, 'CIE-11'),
('XM66P3', 'Pulpo', 'category', false, false, 'CIE-11'),
('XM6ZC1', 'Blomia tropicalis', 'category', false, false, 'CIE-11'),
('XM5AK3', 'Ácaro americano del polvo doméstico', 'category', false, false, 'CIE-11'),
('XM8BV4', 'Dermatophagoides pteronyssinus', 'category', false, false, 'CIE-11'),
('XM99T8', 'polvo de ácaros', 'category', false, false, 'CIE-11'),
('XM0B91', 'Mosquito', 'category', false, false, 'CIE-11'),
('XM95T4', 'Aedes', 'category', false, false, 'CIE-11'),
('XM7VF0', 'Anopheles', 'category', false, false, 'CIE-11'),
('XM0ZZ8', 'Culex', 'category', false, false, 'CIE-11'),
('XM3WD1', 'Polilla', 'category', false, false, 'CIE-11'),
('XM0K01', 'Cucaracha', 'category', false, false, 'CIE-11'),
('XM27E1', 'Cucaracha americana', 'category', false, false, 'CIE-11'),
('XM8RU4', 'Leche', 'category', false, false, 'CIE-11'),
('XM6RB2', 'Leche de vaca', 'category', false, false, 'CIE-11'),
('XM4Y68', 'Leche de cabra', 'category', false, false, 'CIE-11'),
('XM4JV9', 'Queso', 'category', false, false, 'CIE-11'),
('XM5GA5', 'Queso tipo cheddar', 'category', false, false, 'CIE-11'),
('XM3FK1', 'Queso tipo con moho', 'category', false, false, 'CIE-11'),
('XM5T39', 'Dihidrocloruro de etilendiamina', 'category', false, false, 'CIE-11'),
('XM15W5', 'Barniz, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM6MC4', 'Hollín, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM4VX8', 'Amina aromática', 'category', false, false, 'CIE-11'),
('XM6ZV1', 'Antiséptico, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM60L2', 'Beta-naftilamina', 'category', false, false, 'CIE-11'),
('XM76S9', 'polvo de la casa', 'category', false, false, 'CIE-11'),
('XM7XM0', 'polvo de trigo', 'category', false, false, 'CIE-11'),
('XY0Y', 'Afección principal', 'category', false, false, 'CIE-11'),
('XY7B', 'Enfermedad recurso principal', 'category', false, false, 'CIE-11'),
('XY6E', 'Motivo inicial para el encuentro o admisión', 'category', false, false, 'CIE-11'),
('XY6M', 'Presente en la admisión', 'category', false, false, 'CIE-11'),
('XY69', 'Desarrollado después de la admisión', 'category', false, false, 'CIE-11'),
('XY85', 'Cronometraje incierto de inicio relativo a la admisión', 'category', false, false, 'CIE-11'),
('XY9U', 'Preoperatorio', 'category', false, false, 'CIE-11'),
('XY9N', 'Intraoperatorio', 'category', false, false, 'CIE-11'),
('XY7V', 'Posoperatorio', 'category', false, false, 'CIE-11'),
('XY3B', 'Diagnóstico confirmado por exámenes de laboratorio', 'category', false, false, 'CIE-11'),
('XY0E', 'Diagnóstico confirmado por serología', 'category', false, false, 'CIE-11'),
('XY9Q', 'Diagnóstico confirmado por histología', 'category', false, false, 'CIE-11'),
('XY8K', 'Diagnóstico confirmado por estudio genético', 'category', false, false, 'CIE-11'),
('XY9R', 'Diagnóstico confirmado por imágenes', 'category', false, false, 'CIE-11'),
('XY19', 'Diagnóstico confirmado por microscopía', 'category', false, false, 'CIE-11'),
('XY0K', 'Diagnóstico confirmado por cultivo', 'category', false, false, 'CIE-11'),
('XY7Z', 'Diagnóstico provisional', 'category', false, false, 'CIE-11'),
('XY75', 'Diagnóstico diferencial', 'category', false, false, 'CIE-11'),
('XY3K', 'Parto con o sin mención de la condición anteparto', 'category', false, false, 'CIE-11'),
('XY8Q', 'Parto con o sin mención de la condición postparto', 'category', false, false, 'CIE-11'),
('XY8U', 'Condición o complicación anteparto', 'category', false, false, 'CIE-11'),
('XY9P', 'Condición o complicación postparto', 'category', false, false, 'CIE-11'),
('XY9S', 'No especificado , o no se aplicable como a episodio de atención', 'category', false, false, 'CIE-11'),
('XY18', 'Contacto inicial', 'category', false, false, 'CIE-11'),
('XY8S', 'Encuentro subsecuente', 'category', false, false, 'CIE-11'),
('XX2QG9', 'Condición del feto y del recién nacido informado en el contexto de la madre', 'category', false, false, 'CIE-11'),
('XX2V25', 'Femenino', 'category', false, false, 'CIE-11'),
('XX2UQ8', 'Masculino', 'category', false, false, 'CIE-11'),
('XX45B7', 'Intersexo', 'category', false, false, 'CIE-11'),
('XX2PX3', 'Sexo biológico no especificado', 'category', false, false, 'CIE-11'),
('XD7FF9', 'Catéteres venosos centrales', 'category', false, false, 'CIE-11'),
('XD4ZY0', 'Estetoscopios', 'category', false, false, 'CIE-11'),
('XD8DB0', 'Estetoscopio, binaural', 'category', false, false, 'CIE-11'),
('XD04L8', 'Estetoscopios, MRI', 'category', false, false, 'CIE-11'),
('XD8V84', 'Filtros de diálisis', 'category', false, false, 'CIE-11'),
('XD8DD4', 'Filtros de hemodiálisis, hemofiltración, hemodiafiltración', 'category', false, false, 'CIE-11'),
('XD2KJ5', 'Dializadores - UHF <18 ml / h / mmHg', 'category', false, false, 'CIE-11'),
('XD2N29', 'Dializadores - UHF <18 ml / h / mmHg membranas de celulosa', 'category', false, false, 'CIE-11'),
('XD6QR4', 'Dializadores - UHF <18 ml / h / mmHg, membranas de celulosa sustituidas', 'category', false, false, 'CIE-11'),
('XD5S48', 'Dializadores - UHF <18 ml / h / mmHg, membranas sintéticas', 'category', false, false, 'CIE-11'),
('XD2DL2', 'Dializadores - UHF <18 ml / h / mmHg, Otros', 'category', false, false, 'CIE-11'),
('XD4WX5', 'Dializadores - UHF = 18-35 ml / h / mmHg', 'category', false, false, 'CIE-11'),
('XD9RP1', 'Dializadores - UHF = 18-35 ml / h / mmHg, membranas de celulosa', 'category', false, false, 'CIE-11'),
('XD0XB0', 'Dializadores - UHF = 18-35 ml / h / mmHg, membranas de celulosa sustituidas', 'category', false, false, 'CIE-11'),
('XD2KD5', 'Dializadores - UHF = 18-35 ml / h / mmHg, membranas sintéticas', 'category', false, false, 'CIE-11'),
('XD7ZP1', 'Dializadores - UHF = 18-35 ml / h / mmHg, Otros', 'category', false, false, 'CIE-11'),
('XD1904', 'Dializadores - UHF> 35 ml / h / mmHg', 'category', false, false, 'CIE-11'),
('XD2T66', 'Dializadores - UHF> 35 ml / h / mmHg membranas de celulosa', 'category', false, false, 'CIE-11'),
('XD4S95', 'Dializadores - UHF> 35 ml / h / mmHg membranas de celulosa sustituidas', 'category', false, false, 'CIE-11'),
('XD4379', 'Dializadores - UHF> 35 ml / h / mmHg membranas sintéticas', 'category', false, false, 'CIE-11'),
('XD8UZ1', 'Dializadores - UHF> 35 ml / h / mmHg Otros', 'category', false, false, 'CIE-11'),
('XD8VS0', 'Dializadores para hemodiafiltración especial y otras terapias', 'category', false, false, 'CIE-11'),
('XD1V74', 'Filtros de hemoperfusión', 'category', false, false, 'CIE-11'),
('XD27T5', 'Filtros de carbón de hemoperfusión', 'category', false, false, 'CIE-11'),
('XD2RV2', 'Filtros de resina de hemoperfusión', 'category', false, false, 'CIE-11'),
('XD9GN2', 'Filtros de hemoperfusión - Otros', 'category', false, false, 'CIE-11'),
('XD5TA3', 'Filtros y columnas de absorción', 'category', false, false, 'CIE-11'),
('XD8NE7', 'Filtros y columnas de inmuno - absorción', 'category', false, false, 'CIE-11'),
('XD0TG6', 'Filtros de inmuno - absorción', 'category', false, false, 'CIE-11'),
('XD6RX5', 'Columnas de inmuno - absorción', 'category', false, false, 'CIE-11'),
('XD3RD1', 'Filtros y columnas para eliminación de endotoxinas', 'category', false, false, 'CIE-11'),
('XD5SV0', 'Filtros para eliminación de endotoxinas', 'category', false, false, 'CIE-11'),
('XD6KC0', 'Columnas para eliminación de endotoxinas', 'category', false, false, 'CIE-11'),
('XD5DX9', 'Filtros de hemodiálisis - otros', 'category', false, false, 'CIE-11'),
('XD6F86', 'Líneas de diálisis', 'category', false, false, 'CIE-11'),
('XD12J0', 'Líneas de diálisis - hemodiálisis-hemofiltración-hemodiafiltración', 'category', false, false, 'CIE-11'),
('XD5BR1', 'Líneas de diálisis arteriovenosa, una aguja', 'category', false, false, 'CIE-11'),
('XD0B51', 'Líneas de diálisis arteriovenosa, dos agujas', 'category', false, false, 'CIE-11'),
('XD5ED6', 'Líneas de diálisis de reinfusión', 'category', false, false, 'CIE-11'),
('XD8QE4', 'Líneas de diálisis arteriovenosa - accesorios', 'category', false, false, 'CIE-11'),
('XD0270', 'Líneas de diálisis arteriovenosa - Otras', 'category', false, false, 'CIE-11'),
('XD65W3', 'Líneas de diálisis peritoneal', 'category', false, false, 'CIE-11'),
('XD51F1', 'Líneas permanentes de diálisis peritoneal', 'category', false, false, 'CIE-11'),
('XD65K8', 'Líneas de diálisis peritoneal permanente, una bolsa (CAPD)', 'category', false, false, 'CIE-11'),
('XD6QD1', 'Líneas de diálisis peritoneal permanente, dos bolsas (CAPD)', 'category', false, false, 'CIE-11'),
('XD0DE3', 'Líneas de diálisis peritoneal permanente, Otras', 'category', false, false, 'CIE-11'),
('XD8H28', 'Líneas de diálisis peritoneal temporales', 'category', false, false, 'CIE-11'),
('XD6606', 'Líneas de diálisis peritoneal temporales, gravimétricas (APD)', 'category', false, false, 'CIE-11'),
('XD89M1', 'Líneas de diálisis peritoneal temporales, gravimétricas, con bomba (APD)', 'category', false, false, 'CIE-11'),
('XD2M70', 'Líneas de diálisis peritoneal temporales - Otras', 'category', false, false, 'CIE-11'),
('XD4SJ0', 'Líneas de diálisis peritoneal - accesorios', 'category', false, false, 'CIE-11'),
('XD2WX9', 'Líneas de diálisis peritoneal - Otros', 'category', false, false, 'CIE-11'),
('XD0ZQ3', 'Líneas de diálisis - Otras', 'category', false, false, 'CIE-11'),
('XD83M2', 'Equipo de diálisis', 'category', false, false, 'CIE-11'),
('XD0KV9', 'Equipos de hemofiltración-hemodiafiltración', 'category', false, false, 'CIE-11'),
('XD0R67', 'Equipos de biofiltración', 'category', false, false, 'CIE-11'),
('XD6TC6', 'Equipos de hemodiálisis', 'category', false, false, 'CIE-11'),
('XD80S8', 'Equipos de diálisis, lavado / llenado', 'category', false, false, 'CIE-11'),
('XD2QE7', 'Equipos de hemoperfusión', 'category', false, false, 'CIE-11'),
('XD7QD7', 'Equipos de diálisis continua', 'category', false, false, 'CIE-11'),
('XD5KR3', 'Equipos de ultrafiltración', 'category', false, false, 'CIE-11'),
('XD9Z50', 'Equipos de diálisis - Otros', 'category', false, false, 'CIE-11'),
('XD5C20', 'Dializado', 'category', false, false, 'CIE-11'),
('XD62N1', 'Dializante, soluciones ácidas', 'category', false, false, 'CIE-11'),
('XD3V66', 'Dializado, soluciones ácidas, no estériles', 'category', false, false, 'CIE-11'),
('XD1KF2', 'Dializado, soluciones ácidas, estériles', 'category', false, false, 'CIE-11'),
('XD0UL9', 'Dializado, soluciones básicas', 'category', false, false, 'CIE-11'),
('XD2JY9', 'Dializados, soluciones básicas, polvo', 'category', false, false, 'CIE-11'),
('XD5240', 'Dializados, soluciones básicas, líquido', 'category', false, false, 'CIE-11'),
('XD6LX2', 'Dializados, sin acetato buffer', 'category', false, false, 'CIE-11'),
('XD9594', 'Dializados, sin acetato buffer - AFB', 'category', false, false, 'CIE-11'),
('XD6W13', 'Dializados, sin acetato buffer - Otros tratamientos', 'category', false, false, 'CIE-11'),
('XD7157', 'Procedimientos de diálisis, sales', 'category', false, false, 'CIE-11'),
('XD67E6', 'Dializados - Otros', 'category', false, false, 'CIE-11'),
('XD8VC9', 'Dispositivos de diálisis: varios', 'category', false, false, 'CIE-11'),
('XD18U5', 'Dispositivos de diálisis peritoneal (no en otros grupos)', 'category', false, false, 'CIE-11'),
('XD7RE0', 'Diálisis peritoneal, catéteres', 'category', false, false, 'CIE-11'),
('XD47T0', 'Diálisis peritoneal - otros', 'category', false, false, 'CIE-11'),
('XD8689', 'Dispositivos de acceso vascular (solo para hemodiálisis)', 'category', false, false, 'CIE-11'),
('XD9YY6', 'Hemodiálisis temporal, catéteres', 'category', false, false, 'CIE-11'),
('XD3AU4', 'Hemodiálisis permanente, catéteres', 'category', false, false, 'CIE-11'),
('XD3297', 'Dispositivos de acceso vascular (solo para hemodiálisis) - otros', 'category', false, false, 'CIE-11'),
('XD2EM7', 'Diálisis, adaptadores', 'category', false, false, 'CIE-11'),
('XD8Q72', 'Hemodiálisis, adaptadores', 'category', false, false, 'CIE-11'),
('XD39M3', 'Diálisis peritoneal, adaptadores', 'category', false, false, 'CIE-11'),
('XD25C5', 'Tanques del dializado, recolección y reinfusión', 'category', false, false, 'CIE-11'),
('XD6LH4', 'Tanques de dializado, recolección', 'category', false, false, 'CIE-11'),
('XD6MC0', 'Tanques de hemodiálisis, recolección', 'category', false, false, 'CIE-11'),
('XD22A9', 'Tanques de dializado peritoneal, colección', 'category', false, false, 'CIE-11'),
('XD1ZR7', 'Tanques de dializado, reinfusión', 'category', false, false, 'CIE-11'),
('XD8A37', 'Dispositivos de diálisis extracorpórea', 'category', false, false, 'CIE-11'),
('XD9KW0', 'Dispositivos de diálisis - otros accesorios', 'category', false, false, 'CIE-11'),
('XD46Z0', 'Dispositivos de diálisis - otros', 'category', false, false, 'CIE-11'),
('XD53A5', 'Sonda nasogástrica', 'category', false, false, 'CIE-11'),
('XD9246', 'Tubos nasofaríngeos', 'category', false, false, 'CIE-11'),
('XD2M69', 'Cánulas de Guedel de las vías respiratorias', 'category', false, false, 'CIE-11'),
('XD78N3', 'Mascarillas laríngeas', 'category', false, false, 'CIE-11'),
('XD0T92', 'Cánulas endotraqueales, sin manguito', 'category', false, false, 'CIE-11'),
('XD37X2', 'Tubos endotraqueales, con balón', 'category', false, false, 'CIE-11'),
('XD3UM6', 'Cánulas endotraqueales . accesorios', 'category', false, false, 'CIE-11'),
('XD2MG6', 'Cánulas y equipo de traqueolaringostomía, con manguito', 'category', false, false, 'CIE-11'),
('XD7EB1', 'Circuitos Bipap / CPAP', 'category', false, false, 'CIE-11'),
('XD5GF6', 'Mascarillas y globos respiratorios, de un solo uso y reutilizables', 'category', false, false, 'CIE-11'),
('XD3W67', 'Máscaras y cánulas nasales de aire / oxígeno', 'category', false, false, 'CIE-11'),
('XD0VQ3', 'Máscaras de aire/ oxígeno', 'category', false, false, 'CIE-11'),
('XD5RM4', 'Mascarillas venturi', 'category', false, false, 'CIE-11'),
('XD61Z5', 'Cánulas nasales de aire / oxígeno', 'category', false, false, 'CIE-11'),
('XD5AL4', 'Tubos de administración de oxígeno', 'category', false, false, 'CIE-11'),
('XD51T0', 'Globos de ventilación manuales', 'category', false, false, 'CIE-11'),
('XD9AF0', 'Filtros de ventilación, antibacterianos y antivirales, humectantes', 'category', false, false, 'CIE-11'),
('XD35D5', 'Sistemas y catéteres, succión respiratoria,', 'category', false, false, 'CIE-11'),
('XD76M0', 'Sistemas de humidificación, administración de oxígeno', 'category', false, false, 'CIE-11'),
('XD3ZH8', 'Guantes para examen / tratamiento, nitrilo', 'category', false, false, 'CIE-11'),
('XD3LV8', 'Cortinas quirúrgicas', 'category', false, false, 'CIE-11'),
('XD4E80', 'Batas quirúrgicas, estándar', 'category', false, false, 'CIE-11'),
('XD9LJ2', 'Máscaras faciales quirúrgicas estándar', 'category', false, false, 'CIE-11'),
('XD1ZP3', 'Catéteres urológicos permanentes', 'category', false, false, 'CIE-11'),
('XD2AJ4', 'Termómetros electrónicos y tapas para extremos', 'category', false, false, 'CIE-11'),
('XD97L1', 'Bandejas y tazones clínicos', 'category', false, false, 'CIE-11'),
('XD5GV0', 'Proteína C reactiva', 'category', false, false, 'CIE-11'),
('XD9YL7', 'Medios de transporte', 'category', false, false, 'CIE-11'),
('XD9S44', 'Reactivos de coronavirus-NA', 'category', false, false, 'CIE-11'),
('XD9N16', 'Coronavirus (diagnóstico)', 'category', false, false, 'CIE-11'),
('XD7M68', 'Otra virología - RT y POC', 'category', false, false, 'CIE-11'),
('XD1C76', 'Reactivos para extracción y preparación de ADN y / o ARN: bacterias y / o virus', 'category', false, false, 'CIE-11'),
('XD6EG0', 'Analizadores portátiles de gases en sangre', 'category', false, false, 'CIE-11'),
('XD80L4', 'Recipientes de transporte de muestras - otros', 'category', false, false, 'CIE-11'),
('XD6EX8', 'Ecógrafo', 'category', false, false, 'CIE-11'),
('XD89G9', 'Ecógrafo, móvil', 'category', false, false, 'CIE-11'),
('XD7FU9', 'Ecógrafos portátiles', 'category', false, false, 'CIE-11'),
('XD4T57', 'Ecógrafos portables', 'category', false, false, 'CIE-11'),
('XD8DR8', 'Unidades de esterilización por vapor a granel', 'category', false, false, 'CIE-11'),
('XD0U91', 'Laringoscopios', 'category', false, false, 'CIE-11'),
('XD3JX1', 'Videolaringoscopios', 'category', false, false, 'CIE-11'),
('XD7EC8', 'Unidades de presión positiva continua en las vías respiratorias (CPAP)', 'category', false, false, 'CIE-11'),
('XD60Z6', 'Ventiladores transportables', 'category', false, false, 'CIE-11'),
('XD3SM4', 'Ventiladores de cuidados intensivos', 'category', false, false, 'CIE-11'),
('XD4KU3', 'Monitores de paciente multiparamétricos portátiles', 'category', false, false, 'CIE-11'),
('XD66D8', 'Oxímetros de Pulso', 'category', false, false, 'CIE-11'),
('XD8QN4', 'Oxímetros de Pulso, de Mesa', 'category', false, false, 'CIE-11'),
('XD4U89', 'Oxímetros de Pulso, de Mano', 'category', false, false, 'CIE-11'),
('XD5QV8', 'Oxímetros de Pulso, de Punta de Dedo', 'category', false, false, 'CIE-11'),
('XD8QY1', 'Bombas de Infusión', 'category', false, false, 'CIE-11'),
('XD4CT3', 'Bombas de Infusión, Volumétricas', 'category', false, false, 'CIE-11'),
('XD52M6', 'Bombas de infusión, Volumétricas, Resonancia Magnética Nuclear', 'category', false, false, 'CIE-11'),
('XD8DH3', 'Bombas de Infusión, Nutrición Enteral', 'category', false, false, 'CIE-11'),
('XD36Q1', 'Bombas de Infusión, Jeringa', 'category', false, false, 'CIE-11'),
('XD1N14', 'Bombas de infusión, Jeringa, Resonancia Magnética Nuclear', 'category', false, false, 'CIE-11'),
('XD80Z7', 'Sistemas de gases médicos / medicinales y accesorios relacionados', 'category', false, false, 'CIE-11'),
('XD4U38', 'Electrocardiógrafos de uso general', 'category', false, false, 'CIE-11'),
('XD6UU3', 'Concentradores de oxigeno', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
