-- CIE11 Import Part 43
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XA3GZ6', 'Vena digital palmar propia', 'category', false, false, 'CIE-11'),
('XA32L8', 'Vena renal', 'category', false, false, 'CIE-11'),
('XA7HM9', 'Arco venoso palmar superficial', 'category', false, false, 'CIE-11'),
('XA8CK3', 'Vena cubital', 'category', false, false, 'CIE-11'),
('XA2Y72', 'Vena digital palmar', 'category', false, false, 'CIE-11'),
('XA2C08', 'Vena inteósea palmar', 'category', false, false, 'CIE-11'),
('XA13N1', 'Vena metacarpiana palmar', 'category', false, false, 'CIE-11'),
('XA76A3', 'Vena de la extremidad inferior', 'category', false, false, 'CIE-11'),
('XA8WJ3', 'Vena safena accesoria', 'category', false, false, 'CIE-11'),
('XA4CQ8', 'Vena tibial anterior', 'category', false, false, 'CIE-11'),
('XA23R2', 'Vena digital común', 'category', false, false, 'CIE-11'),
('XA3E41', 'Vena femoral profunda', 'category', false, false, 'CIE-11'),
('XA8RN9', 'Arco venoso plantar profundo', 'category', false, false, 'CIE-11'),
('XA3QX9', 'Vena femoral', 'category', false, false, 'CIE-11'),
('XA59H1', 'Gran vena safena', 'category', false, false, 'CIE-11'),
('XA74K2', 'Vena circunfleja femoral lateral', 'category', false, false, 'CIE-11'),
('XA4L08', 'Vena marginal lateral', 'category', false, false, 'CIE-11'),
('XA0L88', 'Vena plantar lateral', 'category', false, false, 'CIE-11'),
('XA8PZ9', 'Vena circunfleja femoral medial', 'category', false, false, 'CIE-11'),
('XA1XM3', 'Vena marginal medial', 'category', false, false, 'CIE-11'),
('XA85B7', 'Vena plantar medial', 'category', false, false, 'CIE-11'),
('XA7ND7', 'Vena metatarsal', 'category', false, false, 'CIE-11'),
('XA4EV7', 'Arco venoso cutáneo plantar', 'category', false, false, 'CIE-11'),
('XA8657', 'Vena digital plantar', 'category', false, false, 'CIE-11'),
('XA08Q1', 'Vena poplítea', 'category', false, false, 'CIE-11'),
('XA5D60', 'Vena tibial posterior', 'category', false, false, 'CIE-11'),
('XA2073', 'Vena safena pequeña', 'category', false, false, 'CIE-11'),
('XA8HR9', 'Vena circunfleja ilíaca superficial', 'category', false, false, 'CIE-11'),
('XA4930', 'Vena peronea', 'category', false, false, 'CIE-11'),
('XA8LE8', 'Vena femoral cutánea anterior', 'category', false, false, 'CIE-11'),
('XA60H0', 'Vena cava', 'category', false, false, 'CIE-11'),
('XA21T7', 'Vaso sanguíneo', 'category', false, false, 'CIE-11'),
('XA6943', 'Vaso sanguíneo del dedo', 'category', false, false, 'CIE-11'),
('XA7SM4', 'Vaso sanguíneo del pulgar', 'category', false, false, 'CIE-11'),
('XA6Y60', 'Vasos sanguíneos a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('XA08R7', 'Vaso sanguíneo del riñón', 'category', false, false, 'CIE-11'),
('XA5K61', 'Vaso sanguíneo del pulmón', 'category', false, false, 'CIE-11'),
('XA9AN5', 'Vaso sanguíneo del cuello', 'category', false, false, 'CIE-11'),
('XA8N71', 'Vaso sanguíneo del tórax', 'category', false, false, 'CIE-11'),
('XA7P54', 'Vaso sanguíneo de la cadera', 'category', false, false, 'CIE-11'),
('XA9M17', 'Vasos sanguíneos a nivel de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('XA2769', 'Capilar, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA5TF7', 'Circulación cerebral', 'category', false, false, 'CIE-11'),
('XA4H19', 'Vasos sanguíneos intracraneales, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XA1SX5', 'Vasos sanguíneos extracraneales, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XA6H07', 'Corazón', 'category', false, false, 'CIE-11'),
('XA6548', 'Aurícula izquierda', 'category', false, false, 'CIE-11'),
('XA7V72', 'Válvula mitral', 'category', false, false, 'CIE-11'),
('XA3GE9', 'Cúspides de la válvula mitral', 'category', false, false, 'CIE-11'),
('XA69W6', 'Cuerdas tendinosas de la válvula mitral', 'category', false, false, 'CIE-11'),
('XA78X5', 'Tabique interauricular', 'category', false, false, 'CIE-11'),
('XA6T92', 'Aurícula derecha', 'category', false, false, 'CIE-11'),
('XA6FF2', 'Válvula tricúspide', 'category', false, false, 'CIE-11'),
('XA19H9', 'Cúspides de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('XA4LY3', 'Cuerdas tendinosas de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('XA8FJ7', 'Ventrículo izquierdo', 'category', false, false, 'CIE-11'),
('XA19J4', 'Válvula aórtica', 'category', false, false, 'CIE-11'),
('XA2QK7', 'Cúspides de la válvula aórtica', 'category', false, false, 'CIE-11'),
('XA7S34', 'Músculos papilares del ventrículo izquierdo', 'category', false, false, 'CIE-11'),
('XA5651', 'Tabique interventricular', 'category', false, false, 'CIE-11'),
('XA9HH8', 'Ventrículo derecho', 'category', false, false, 'CIE-11'),
('XA5Y16', 'Músculos papilares del ventrículo derecho', 'category', false, false, 'CIE-11'),
('XA6WC4', 'Válvula pulmonar', 'category', false, false, 'CIE-11'),
('XA1403', 'Cúspides de la válvula pulmonar', 'category', false, false, 'CIE-11'),
('XA3B03', 'Arterias coronarias', 'category', false, false, 'CIE-11'),
('XA0F62', 'Arteria coronaria principal izquierda', 'category', false, false, 'CIE-11'),
('XA9FX9', 'Arteria circunfleja izquierda', 'category', false, false, 'CIE-11'),
('XA7NQ7', 'Arteria coronaria descendente anterior izquierda', 'category', false, false, 'CIE-11'),
('XA2N78', 'Ramas diagonales de la arteria coronaria descendente anterior izquierda', 'category', false, false, 'CIE-11'),
('XA20E5', 'D1 - primera rama diagonal', 'category', false, false, 'CIE-11'),
('XA86J1', 'D2 - segunda rama diagonal', 'category', false, false, 'CIE-11'),
('XA5SR3', 'D3 - tercera rama diagonal', 'category', false, false, 'CIE-11'),
('XA1SH6', 'Arteria marginal obtusa izquierda', 'category', false, false, 'CIE-11'),
('XA3QP2', 'Rama de la arteria intermedia', 'category', false, false, 'CIE-11'),
('XA5LW8', 'Arteria septal', 'category', false, false, 'CIE-11'),
('XA2QX7', 'Arteria coronaria derecha', 'category', false, false, 'CIE-11'),
('XA1LL7', 'Arteria marginal aguda derecha', 'category', false, false, 'CIE-11'),
('XA81T7', 'arteria interventricular posterior', 'category', false, false, 'CIE-11'),
('XA8PS0', 'arteria posterolateral', 'category', false, false, 'CIE-11'),
('XA7TB5', 'Arteria nodal sinoauricular', 'category', false, false, 'CIE-11'),
('XA9FK9', 'Venas cardíacas', 'category', false, false, 'CIE-11'),
('XA6YW4', 'Vena oblicua de la aurícula izquierda', 'category', false, false, 'CIE-11'),
('XA0HP7', 'Vena marginal izquierda del corazón', 'category', false, false, 'CIE-11'),
('XA38Z5', 'Vena cardíaca magna', 'category', false, false, 'CIE-11'),
('XA8HT6', 'Vena posterior del ventrículo izquierdo', 'category', false, false, 'CIE-11'),
('XA3UN3', 'Vena cardíaca media', 'category', false, false, 'CIE-11'),
('XA6QD7', 'Vena cardíaca menor', 'category', false, false, 'CIE-11'),
('XA16E4', 'Seno coronario', 'category', false, false, 'CIE-11'),
('XA4TZ2', 'Vena cardíaca anterior', 'category', false, false, 'CIE-11'),
('XA9498', 'Vena cardíaca menor', 'category', false, false, 'CIE-11'),
('XA2KE8', 'Vena marginal derecha del corazón', 'category', false, false, 'CIE-11'),
('XA4366', 'Vena pericárdica', 'category', false, false, 'CIE-11'),
('XA10E0', 'Cámara del corazón', 'category', false, false, 'CIE-11'),
('XA91S4', 'Aurícula cardíaca', 'category', false, false, 'CIE-11'),
('XA7XU8', 'Ventrículo cardíaco', 'category', false, false, 'CIE-11'),
('XA3113', 'Tejido conectivo y tejido blando del corazón', 'category', false, false, 'CIE-11'),
('XA42G7', 'Arterias del corazón', 'category', false, false, 'CIE-11'),
('XA9X98', 'Arteria pericardiofrénica', 'category', false, false, 'CIE-11'),
('XA2XU0', 'Pericardio', 'category', false, false, 'CIE-11'),
('XA8RK9', 'Pericardio parietal', 'category', false, false, 'CIE-11'),
('XA48H9', 'Cavidad pericárdica', 'category', false, false, 'CIE-11'),
('XA37Q8', 'Epicardio', 'category', false, false, 'CIE-11'),
('XA3227', 'Endocardio', 'category', false, false, 'CIE-11'),
('XA81Z5', 'Tabique cardíaco', 'category', false, false, 'CIE-11'),
('XA2DC8', 'Músculo papilar', 'category', false, false, 'CIE-11'),
('XA6CK2', 'Pared del corazón', 'category', false, false, 'CIE-11'),
('XA7RE3', 'Pared anterior del corazón', 'category', false, false, 'CIE-11'),
('XA5W05', 'Pared anterolateral del corazón', 'category', false, false, 'CIE-11'),
('XA2RT9', 'Pared anteroseptal del corazón', 'category', false, false, 'CIE-11'),
('XA4U99', 'Pared anteroapical del corazón', 'category', false, false, 'CIE-11'),
('XA3RM8', 'Pared inferior del corazón', 'category', false, false, 'CIE-11'),
('XA61Y9', 'Pared inferolateral del corazón', 'category', false, false, 'CIE-11'),
('XA2H88', 'Pared posteroinferior del corazón', 'category', false, false, 'CIE-11'),
('XA8ZQ8', 'Pared apical lateral del corazón', 'category', false, false, 'CIE-11'),
('XA6GR4', 'Pared basal lateral del corazón', 'category', false, false, 'CIE-11'),
('XA1HH6', 'Pares lateral alta del corazón', 'category', false, false, 'CIE-11'),
('XA3XS7', 'Pared lateral del corazón', 'category', false, false, 'CIE-11'),
('XA01U7', 'Pared posterior verdadera del corazón', 'category', false, false, 'CIE-11'),
('XA7D76', 'Pared postero basal del corazón', 'category', false, false, 'CIE-11'),
('XA4RC1', 'Pared posterolateral del corazón', 'category', false, false, 'CIE-11'),
('XA60V2', 'Pared posteroseptal del corazón', 'category', false, false, 'CIE-11'),
('XA83Q5', 'Pared septal del corazón', 'category', false, false, 'CIE-11'),
('XA79Z5', 'Sistema de conducción eléctrica cardíaca', 'category', false, false, 'CIE-11'),
('XA1UE3', 'Nódulo sinoauricular', 'category', false, false, 'CIE-11'),
('XA4359', 'Nódulo aurículoventricular', 'category', false, false, 'CIE-11'),
('XA7J11', 'Haz de His', 'category', false, false, 'CIE-11'),
('XA0QB6', 'Válvula cardíaca', 'category', false, false, 'CIE-11'),
('XA8SK6', 'Miocardio', 'category', false, false, 'CIE-11'),
('XA10P2', 'Sistema linfático de la cabeza y del cuello', 'category', false, false, 'CIE-11'),
('XA0LH6', 'Tronco linfático yugular', 'category', false, false, 'CIE-11'),
('XA6TY4', 'Vaso linfático de la oreja', 'category', false, false, 'CIE-11'),
('XA02Y8', 'Vaso linfático de la aurícula del meato acústico externo', 'category', false, false, 'CIE-11'),
('XA1EC8', 'Vaso linfático de la cara', 'category', false, false, 'CIE-11'),
('XA0167', 'Vaso linfático de la amígdala palatina', 'category', false, false, 'CIE-11'),
('XA4QZ6', 'Vaso linfático del cuero cabelludo', 'category', false, false, 'CIE-11'),
('XA9FT5', 'Vaso linfático de la lengua', 'category', false, false, 'CIE-11'),
('XA1G40', 'Vaso linfático de la piel y los músculos del cuello', 'category', false, false, 'CIE-11'),
('XA23Z9', 'Sistema linfático de las extremidades superiores', 'category', false, false, 'CIE-11'),
('XA05S0', 'Vaso linfático profundo', 'category', false, false, 'CIE-11'),
('XA6D43', 'Vaso linfático interóseo dorsal', 'category', false, false, 'CIE-11'),
('XA7FS7', 'Vaso linfático mediano', 'category', false, false, 'CIE-11'),
('XA3HQ3', 'Vaso linfático radial', 'category', false, false, 'CIE-11'),
('XA12G8', 'Vaso linfático superficial', 'category', false, false, 'CIE-11'),
('XA4UB1', 'Vaso linfático cubital', 'category', false, false, 'CIE-11'),
('XA5SZ5', 'Vaso linfático palmar', 'category', false, false, 'CIE-11'),
('XA52C3', 'Sistema linfático del tórax', 'category', false, false, 'CIE-11'),
('XA94Z9', 'Tronco broncomediastinal', 'category', false, false, 'CIE-11'),
('XA7474', 'Saco linfático cisterna del quilo', 'category', false, false, 'CIE-11'),
('XA1VK9', 'Vasos linfáticos profundos de la pared torácica', 'category', false, false, 'CIE-11'),
('XA9D98', 'Tronco linfático intestinal', 'category', false, false, 'CIE-11'),
('XA8JF4', 'Saco linfático yugular', 'category', false, false, 'CIE-11'),
('XA1SQ2', 'Saco linfático', 'category', false, false, 'CIE-11'),
('XA8YM1', 'Vaso linfático del diafragma', 'category', false, false, 'CIE-11'),
('XA4RC7', 'Vaso linfático de la mama', 'category', false, false, 'CIE-11'),
('XA3SY2', 'Vaso linfático de las vísceras torácicas', 'category', false, false, 'CIE-11'),
('XA55B8', 'Vaso linfático del corazón', 'category', false, false, 'CIE-11'),
('XA3EB8', 'Vaso linfático de los pulmones', 'category', false, false, 'CIE-11'),
('XA8QZ0', 'Vaso linfático del esófago', 'category', false, false, 'CIE-11'),
('XA6J62', 'Vaso linfático del pericardio', 'category', false, false, 'CIE-11'),
('XA4QL2', 'Vaso linfático de la pleura', 'category', false, false, 'CIE-11'),
('XA3JF4', 'Vaso linfático del timo', 'category', false, false, 'CIE-11'),
('XA4J10', 'Saco linfático posterior', 'category', false, false, 'CIE-11'),
('XA8MX8', 'Saco linfático retroperitoneal', 'category', false, false, 'CIE-11'),
('XA3ER1', 'Conducto linfático derecho', 'category', false, false, 'CIE-11'),
('XA3TX9', 'Vaso linfático superficial de la pared torácica', 'category', false, false, 'CIE-11'),
('XA8A74', 'Conducto torácico', 'category', false, false, 'CIE-11'),
('XA81G2', 'Sistema linfático del abdomen', 'category', false, false, 'CIE-11'),
('XA07V7', 'Tronco lumbar intestinal', 'category', false, false, 'CIE-11'),
('XA6R71', 'Tronco linfático lumbar', 'category', false, false, 'CIE-11'),
('XA9XL5', 'Vasos linfáticos del ciego', 'category', false, false, 'CIE-11'),
('XA1BU5', 'Vasos linfáticos del colon', 'category', false, false, 'CIE-11'),
('XA92E5', 'Vasos linfáticos del duodeno', 'category', false, false, 'CIE-11'),
('XA6VD0', 'Vasos linfáticos de la vesícula biliar', 'category', false, false, 'CIE-11'),
('XA55Y5', 'Vasos linfáticos del íleon', 'category', false, false, 'CIE-11'),
('XA4CQ1', 'Vasos linfáticos del yeyuno', 'category', false, false, 'CIE-11'),
('XA3610', 'Vasos linfáticos del riñón', 'category', false, false, 'CIE-11'),
('XA0WY9', 'Vasos linfáticos del hígado', 'category', false, false, 'CIE-11'),
('XA9YZ4', 'Vasos linfáticos del páncreas', 'category', false, false, 'CIE-11'),
('XA5LE6', 'Vasos linfáticos del bazo', 'category', false, false, 'CIE-11'),
('XA1599', 'Vasos linfáticos del estómago', 'category', false, false, 'CIE-11'),
('XA3RD0', 'Vasos linfáticos de la porción subdiafragmática del tubo digestivo', 'category', false, false, 'CIE-11'),
('XA21T8', 'Vaso linfático del ganglio linfático suprarrenal', 'category', false, false, 'CIE-11'),
('XA29U5', 'Vaso linfático del apéndice', 'category', false, false, 'CIE-11'),
('XA6709', 'Sistema linfático de la pelvis y del perineo', 'category', false, false, 'CIE-11'),
('XA9H16', 'Vaso linfático vesical anterior de la vejiga', 'category', false, false, 'CIE-11'),
('XA28F6', 'Vaso linfático lateral de la vejiga', 'category', false, false, 'CIE-11'),
('XA4LM3', 'Vaso linfático del canal anal', 'category', false, false, 'CIE-11'),
('XA5C29', 'Vaso linfätico del ano', 'category', false, false, 'CIE-11'),
('XA1UK6', 'Vaso linfático de la vejiga', 'category', false, false, 'CIE-11'),
('XA16J8', 'Vaso linfático del conducto deferente', 'category', false, false, 'CIE-11'),
('XA4229', 'Vaso linfático del ovario', 'category', false, false, 'CIE-11'),
('XA1SS8', 'Vaso linfático de la próstata', 'category', false, false, 'CIE-11'),
('XA6DH7', 'Vaso linfático del recto', 'category', false, false, 'CIE-11'),
('XA2XZ6', 'Vaso linfático de los órganos reproductores', 'category', false, false, 'CIE-11'),
('XA1UA0', 'Vaso linfático del testículo', 'category', false, false, 'CIE-11'),
('XA6324', 'Vaso linfático del ureter', 'category', false, false, 'CIE-11'),
('XA6HM6', 'Vaso linfático de la uretra', 'category', false, false, 'CIE-11'),
('XA7JY4', 'Vaso linfático de órgano urinario', 'category', false, false, 'CIE-11'),
('XA5755', 'Vaso linfático de la trompa de Falopio', 'category', false, false, 'CIE-11'),
('XA9PA3', 'Vaso linfático del útero', 'category', false, false, 'CIE-11'),
('XA1ZK1', 'Vaso linfático de la vagina', 'category', false, false, 'CIE-11'),
('XA0GB7', 'Vasos linfáticos de las vesículas seminales', 'category', false, false, 'CIE-11'),
('XA0Z86', 'Sistema linfático de las extremidades inferiores', 'category', false, false, 'CIE-11'),
('XA6UC7', 'Tronco linfático tibial anterior', 'category', false, false, 'CIE-11'),
('XA8Z63', 'Tracto respiratorio superior', 'category', false, false, 'CIE-11'),
('XA43C9', 'Cavidad nasal', 'category', false, false, 'CIE-11'),
('XA53X2', 'Vestíbulo nasal', 'category', false, false, 'CIE-11'),
('XA8D47', 'Tabique nasal', 'category', false, false, 'CIE-11'),
('XA8817', 'Cornete nasal', 'category', false, false, 'CIE-11'),
('XA7WQ4', 'Cartílago nasal', 'category', false, false, 'CIE-11'),
('XA4CN5', 'Mucosa nasal', 'category', false, false, 'CIE-11'),
('XA6YH7', 'Tejido conectivo, subcutáneo y otros tejidos blandos de la cavidad nasal', 'category', false, false, 'CIE-11'),
('XA3HQ4', 'Vena del arco nasal', 'category', false, false, 'CIE-11'),
('XA3523', 'Senos accesorios', 'category', false, false, 'CIE-11'),
('XA1R64', 'Seno maxilar', 'category', false, false, 'CIE-11'),
('XA58F6', 'Seno etmoidal', 'category', false, false, 'CIE-11'),
('XA91G8', 'Seno frontal', 'category', false, false, 'CIE-11'),
('XA4U67', 'Seno esfenoidal', 'category', false, false, 'CIE-11'),
('XA9AZ1', 'Nasofaringe', 'category', false, false, 'CIE-11'),
('XA0659', 'Pared superior de la nasofaringe', 'category', false, false, 'CIE-11'),
('XA21P9', 'Pared anterior de la nasofaringe', 'category', false, false, 'CIE-11'),
('XA4BR4', 'Pared posterior de la nasofaringe', 'category', false, false, 'CIE-11'),
('XA5AS8', 'Adenoide', 'category', false, false, 'CIE-11'),
('XA7PX5', 'Pared lateral de la nasofaringe', 'category', false, false, 'CIE-11'),
('XA7W35', 'Receso faríngeo', 'category', false, false, 'CIE-11'),
('XA9P89', 'Receso retrofaríngeo', 'category', false, false, 'CIE-11'),
('XA6QY3', 'Receso parafaríngeo', 'category', false, false, 'CIE-11'),
('XA2RH5', 'Laringe', 'category', false, false, 'CIE-11'),
('XA1PB3', 'Laringe supraglótica', 'category', false, false, 'CIE-11'),
('XA9ZY9', 'Epiglotis', 'category', false, false, 'CIE-11'),
('XA4DV7', 'Superficie anterior de la epiglotis', 'category', false, false, 'CIE-11'),
('XA8U54', 'Superficie posterior de la epiglotis', 'category', false, false, 'CIE-11'),
('XA9907', 'Pliegue ariepiglótico', 'category', false, false, 'CIE-11'),
('XA8N50', 'Aspecto laríngeo del pliegue arilepiglótico', 'category', false, false, 'CIE-11'),
('XA7AE7', 'Glotis', 'category', false, false, 'CIE-11'),
('XA3299', 'Cuerda vocal', 'category', false, false, 'CIE-11'),
('XA25B1', 'Laringe subglótica', 'category', false, false, 'CIE-11'),
('XA0NK8', 'Cartílago laríngeo', 'category', false, false, 'CIE-11'),
('XA0AF3', 'Cartílago aritenoide', 'category', false, false, 'CIE-11'),
('XA7S05', 'Cartílago cricoide', 'category', false, false, 'CIE-11'),
('XA2383', 'Articulación cricoaritenoidea', 'category', false, false, 'CIE-11'),
('XA73G2', 'Articulación cricotiroidea', 'category', false, false, 'CIE-11'),
('XA7SZ3', 'Cartílago cuneiforme', 'category', false, false, 'CIE-11'),
('XA2716', 'Cartílago tiroideo', 'category', false, false, 'CIE-11'),
('XA07R2', 'Vías respiratorias inferiores', 'category', false, false, 'CIE-11'),
('XA26H1', 'Tráquea', 'category', false, false, 'CIE-11'),
('XA7SG3', 'Tráquea cervical', 'category', false, false, 'CIE-11'),
('XA4RN3', 'Tráquea torácica', 'category', false, false, 'CIE-11'),
('XA57M6', 'Pulmón', 'category', false, false, 'CIE-11'),
('XA9TC5', 'Bronquio principal', 'category', false, false, 'CIE-11'),
('XA3L52', 'Bronquio principal derecho', 'category', false, false, 'CIE-11'),
('XA5FV2', 'Bronquio superior izquierdo', 'category', false, false, 'CIE-11'),
('XA4JA0', 'Carina', 'category', false, false, 'CIE-11'),
('XA7EZ3', 'Pulmón derecho', 'category', false, false, 'CIE-11'),
('XA29Y4', 'Hilio del pulmón derecho', 'category', false, false, 'CIE-11'),
('XA8Z30', 'Bronquio lobular superior derecho', 'category', false, false, 'CIE-11'),
('XA41Z3', 'Bronquio lobular inferior derecho', 'category', false, false, 'CIE-11'),
('XA1QM3', 'Bronquio lobular medio derecho', 'category', false, false, 'CIE-11'),
('XA2UD3', 'Pulmón izquierdo', 'category', false, false, 'CIE-11'),
('XA6VA2', 'Hilio del pulmón izquierdo', 'category', false, false, 'CIE-11'),
('XA6F58', 'Bronquio lobular superior izquierdo', 'category', false, false, 'CIE-11'),
('XA4565', 'Língula del pulmón', 'category', false, false, 'CIE-11'),
('XA2XH5', 'Bronquio logular inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA90M2', 'Lóbulo del pulmón', 'category', false, false, 'CIE-11'),
('XA9HN5', 'Lóbulo superior del pulmón', 'category', false, false, 'CIE-11'),
('XA1N36', 'Lóbulo medio del pulmón', 'category', false, false, 'CIE-11'),
('XA7L34', 'Lóbulo inferior del pulmón', 'category', false, false, 'CIE-11'),
('XA37W0', 'Bronquio lobular superior', 'category', false, false, 'CIE-11'),
('XA1K94', 'Bronquio lobular medio', 'category', false, false, 'CIE-11'),
('XA8JM5', 'Bronquio lobular inferior', 'category', false, false, 'CIE-11'),
('XA2PV7', 'Tejido conectivo y otros tejidos blandos del pulmón', 'category', false, false, 'CIE-11'),
('XA61M6', 'Bronquio', 'category', false, false, 'CIE-11'),
('XA8Z62', 'Parénquima pulmonar', 'category', false, false, 'CIE-11'),
('XA5772', 'Alvéolos', 'category', false, false, 'CIE-11'),
('XA4646', 'Vasculatura pulmonar', 'category', false, false, 'CIE-11'),
('XA8FY4', 'Vena pulmonar', 'category', false, false, 'CIE-11'),
('XA1WN5', 'Vena pulmonar izquierda', 'category', false, false, 'CIE-11'),
('XA9941', 'Vena pulmonar superior izquierda', 'category', false, false, 'CIE-11'),
('XA8TW3', 'Vena pulmonar inferior izquierda', 'category', false, false, 'CIE-11'),
('XA86L0', 'Vena pulmonar derecha', 'category', false, false, 'CIE-11'),
('XA05T2', 'Vena pulmonar superior derecha', 'category', false, false, 'CIE-11'),
('XA41F3', 'Vena pulmonar inferior derecha', 'category', false, false, 'CIE-11'),
('XA4530', 'Vena pulmonar accesoria derecha', 'category', false, false, 'CIE-11'),
('XA1SF4', 'Tronco común de las venas pulmonares del lado izquierdo', 'category', false, false, 'CIE-11'),
('XA0F36', 'Capilares pulmonares', 'category', false, false, 'CIE-11'),
('XA5TT2', 'Pleura', 'category', false, false, 'CIE-11'),
('XA1B59', 'Pleura visceral', 'category', false, false, 'CIE-11'),
('XA7RC6', 'Pleura parietal', 'category', false, false, 'CIE-11'),
('XA4U64', 'Arteria del pulmón', 'category', false, false, 'CIE-11'),
('XA2AT1', 'Arteriola eferente de la arteria interlobular', 'category', false, false, 'CIE-11'),
('XA6WT9', 'Arteria interlobar', 'category', false, false, 'CIE-11'),
('XA2S57', 'Arteria interlobular', 'category', false, false, 'CIE-11'),
('XA3713', 'Tronco pulmonar', 'category', false, false, 'CIE-11'),
('XA5437', 'Bronquiolos', 'category', false, false, 'CIE-11'),
('XA8182', 'Boca', 'category', false, false, 'CIE-11'),
('XA5TW5', 'Vestíbulo de la boca', 'category', false, false, 'CIE-11'),
('XA9072', 'Mucosa labial del labio superior', 'category', false, false, 'CIE-11'),
('XA72W2', 'Mucosa labial del labio inferior', 'category', false, false, 'CIE-11'),
('XA8WB3', 'Mucosa bucal', 'category', false, false, 'CIE-11'),
('XA0S17', 'Región retromolar', 'category', false, false, 'CIE-11'),
('XA44M8', 'Surco labial', 'category', false, false, 'CIE-11'),
('XA2151', 'Surco labial superior', 'category', false, false, 'CIE-11'),
('XA52Q7', 'Surco labial inferior', 'category', false, false, 'CIE-11'),
('XA6A73', 'Surco bucal', 'category', false, false, 'CIE-11'),
('XA6WJ3', 'Surco bucal superolateral', 'category', false, false, 'CIE-11'),
('XA5MG3', 'Surco bucal inferolateral', 'category', false, false, 'CIE-11'),
('XA54T3', 'Encía', 'category', false, false, 'CIE-11'),
('XA6743', 'Encía superior', 'category', false, false, 'CIE-11'),
('XA2C94', 'Mucosa alveolar superior', 'category', false, false, 'CIE-11'),
('XA7DA0', 'Mucosa de la cresta alveolar superior', 'category', false, false, 'CIE-11'),
('XA9303', 'Encía inferior', 'category', false, false, 'CIE-11'),
('XA96F2', 'Mucosa alveolar inferior', 'category', false, false, 'CIE-11'),
('XA8C21', 'Mucosa de la cresta alveolar inferior', 'category', false, false, 'CIE-11'),
('XA3SP9', 'Mucosa alveolar', 'category', false, false, 'CIE-11'),
('XA6CZ2', 'Dientes', 'category', false, false, 'CIE-11'),
('XA4GG3', 'Dentición permanente', 'category', false, false, 'CIE-11'),
('XA5306', 'Tercer molar superior derecho', 'category', false, false, 'CIE-11'),
('XA0BR9', 'Segundo molar superior derecho', 'category', false, false, 'CIE-11'),
('XA0TL3', 'Primer molar superior derecho', 'category', false, false, 'CIE-11'),
('XA45K9', 'Segundo premolar superior derecho', 'category', false, false, 'CIE-11'),
('XA64J5', 'Primer premolar superior derecho', 'category', false, false, 'CIE-11'),
('XA0LE1', 'Canino superior derecho', 'category', false, false, 'CIE-11'),
('XA3QH3', 'Incisivo lateral superior derecho', 'category', false, false, 'CIE-11'),
('XA43X2', 'Incisivo central superior derecho', 'category', false, false, 'CIE-11'),
('XA8328', 'Tercer molar superior izquierdo', 'category', false, false, 'CIE-11'),
('XA1YK1', 'Segundo molar superior izquierdo', 'category', false, false, 'CIE-11'),
('XA2GW7', 'Primer molar superior izquierdo', 'category', false, false, 'CIE-11'),
('XA5Z15', 'Segundo premolar superior izquierdo', 'category', false, false, 'CIE-11'),
('XA3EF6', 'Primer premolar superior izquierdo', 'category', false, false, 'CIE-11'),
('XA2LF2', 'Canino superior izquierdo', 'category', false, false, 'CIE-11'),
('XA0MG2', 'Incisivo lateral superior izquierdo', 'category', false, false, 'CIE-11'),
('XA9P69', 'Incisivo central superior izquierdo', 'category', false, false, 'CIE-11'),
('XA8YF6', 'Tercer molar inferior derecho', 'category', false, false, 'CIE-11'),
('XA5CA4', 'Segundo molar inferior derecho', 'category', false, false, 'CIE-11'),
('XA5M57', 'Primer molar inferior derecho', 'category', false, false, 'CIE-11'),
('XA26X2', 'Segundo premolar inferior derecho', 'category', false, false, 'CIE-11'),
('XA47C4', 'Primer premolar inferior derecho', 'category', false, false, 'CIE-11'),
('XA95A1', 'Canino inferior derecho', 'category', false, false, 'CIE-11'),
('XA8660', 'Incisivo lateral inferior derecho', 'category', false, false, 'CIE-11'),
('XA5NT8', 'Incisivo central inferior derecho', 'category', false, false, 'CIE-11'),
('XA0XB1', 'Tercer molar inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA8YV5', 'Segundo molar inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA6R23', 'Primer molar inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA80S2', 'Segundo premolar inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA1SQ7', 'Primer premolar inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA8P88', 'Canino inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA4B13', 'Incisivo lateral inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA7B54', 'Incisivo central inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA7675', 'Dentición decidua', 'category', false, false, 'CIE-11'),
('XA2GE5', 'Segundo molar superior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA7ZT9', 'Primer molar superior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA06P0', 'Canino superior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA2XZ5', 'Incisivo lateral superior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA3BG3', 'Incisivo central superior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA2BD4', 'Segundo molar superior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA85K7', 'Primer molar superior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA98V8', 'Canino superior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA9QP7', 'Incisivo lateral superior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA4ZQ5', 'Incisivo central superior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA6F50', 'Segundo molar inferior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA36B2', 'Primer molar inferior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA8KQ7', 'Canino inferior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA1W31', 'Incisivo lateral inferior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA6TB6', 'Incisivo central inferior derecho, deciduo', 'category', false, false, 'CIE-11'),
('XA8NE2', 'Segundo molar inferior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA55D8', 'Primer molar inferior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA8QV7', 'Canino inferior izquierdo, deciduo', 'category', false, false, 'CIE-11'),
('XA8MH6', 'Incisivo lateral inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA2RW5', 'Incisivo central inferior izquierdo', 'category', false, false, 'CIE-11'),
('XA1PT3', 'Partes del diente', 'category', false, false, 'CIE-11'),
('XA5B71', 'Pulpa', 'category', false, false, 'CIE-11'),
('XA6FX3', 'Dentina', 'category', false, false, 'CIE-11'),
('XA5R09', 'Esmalte', 'category', false, false, 'CIE-11'),
('XA4KC7', 'Cemento', 'category', false, false, 'CIE-11'),
('XA2CA1', 'Tejido periapical', 'category', false, false, 'CIE-11'),
('XA2US1', 'Superficie de los dientes', 'category', false, false, 'CIE-11'),
('XA5ML5', 'Superficie distal del diente', 'category', false, false, 'CIE-11'),
('XA4UP2', 'Superficie labial del diente', 'category', false, false, 'CIE-11'),
('XA6DE2', 'Superficie bucal del diente', 'category', false, false, 'CIE-11'),
('XA3W20', 'Superficie incisal del diente', 'category', false, false, 'CIE-11'),
('XA8M68', 'Superficie lingual del diente', 'category', false, false, 'CIE-11'),
('XA5Z48', 'Superficie mesial del diente', 'category', false, false, 'CIE-11'),
('XA5DM8', 'Superficie oclusal del diente', 'category', false, false, 'CIE-11'),
('XA3HD5', 'Superficie proximal del diente', 'category', false, false, 'CIE-11'),
('XA1WN1', 'Cavidad oral', 'category', false, false, 'CIE-11'),
('XA7ZA6', 'Paladar', 'category', false, false, 'CIE-11'),
('XA4527', 'Paladar duro', 'category', false, false, 'CIE-11'),
('XA8HL5', 'Paladar blando', 'category', false, false, 'CIE-11'),
('XA2993', 'Úvula', 'category', false, false, 'CIE-11'),
('XA00H5', 'Mucosa palatina', 'category', false, false, 'CIE-11'),
('XA1T19', 'Lengua', 'category', false, false, 'CIE-11'),
('XA8Q87', 'Cuerpo de la lengua', 'category', false, false, 'CIE-11'),
('XA65E9', 'Línea media de la lengua', 'category', false, false, 'CIE-11'),
('XA8SX3', 'Zona de unión de la lengua', 'category', false, false, 'CIE-11'),
('XA25G3', 'Base de la lengua', 'category', false, false, 'CIE-11'),
('XA2B11', 'Porción posterior de la lengua', 'category', false, false, 'CIE-11'),
('XA1V27', 'Superficie dorsal de la lengua', 'category', false, false, 'CIE-11'),
('XA8YB9', 'Superficie dorsal del cuerpo de la lengua', 'category', false, false, 'CIE-11'),
('XA0HQ3', 'Superficie dorsal de la base de la lengua', 'category', false, false, 'CIE-11'),
('XA9RP1', 'Otras partes de la lengua y partes no especificadas', 'category', false, false, 'CIE-11'),
('XA8FK4', 'Superficie ventral de la lengua', 'category', false, false, 'CIE-11'),
('XA9YA2', 'Frenillo lingual', 'category', false, false, 'CIE-11'),
('XA4DB6', 'Borde de la lengua', 'category', false, false, 'CIE-11'),
('XA49C6', 'Margen lateral de la lengua', 'category', false, false, 'CIE-11'),
('XA1WZ8', 'Punta de la lengua', 'category', false, false, 'CIE-11'),
('XA8EY7', 'Piso de la boca', 'category', false, false, 'CIE-11'),
('XA69M6', 'Surco alveololingual', 'category', false, false, 'CIE-11'),
('XA8CF9', 'Mucosa del piso de la boca', 'category', false, false, 'CIE-11'),
('XA29D3', 'Región tonsilar', 'category', false, false, 'CIE-11'),
('XA9A13', 'Arco glosopalatino', 'category', false, false, 'CIE-11'),
('XA2JB0', 'Pilar tonsilar anterior', 'category', false, false, 'CIE-11'),
('XA46Z4', 'Fosa amigdalina', 'category', false, false, 'CIE-11'),
('XA3021', 'Arco faringopalatino', 'category', false, false, 'CIE-11'),
('XA0X58', 'Pilar amigdalino posterior', 'category', false, false, 'CIE-11'),
('XA15G1', 'Arco palatino', 'category', false, false, 'CIE-11'),
('XA6NQ7', 'Mucosa oral', 'category', false, false, 'CIE-11'),
('XA2KN0', 'Otras partes y las no especificadas de la boca', 'category', false, false, 'CIE-11'),
('XA5T23', 'Aparato de glándula salival', 'category', false, false, 'CIE-11'),
('XA07S5', 'Glándula parótida', 'category', false, false, 'CIE-11'),
('XA9Q61', 'Glándula submandibular', 'category', false, false, 'CIE-11'),
('XA0CS1', 'Glándula submandibular izquierda', 'category', false, false, 'CIE-11'),
('XA8GQ5', 'Glándula submandibular derecha', 'category', false, false, 'CIE-11'),
('XA7GY0', 'Conducto de la glándula submandibular', 'category', false, false, 'CIE-11'),
('XA51Q9', 'Glándula sublingual', 'category', false, false, 'CIE-11'),
('XA30Q1', 'Glándula salivar menor', 'category', false, false, 'CIE-11'),
('XA5CM1', 'Conducto salival', 'category', false, false, 'CIE-11'),
('XA44X8', 'Conducto de la glándula parótida', 'category', false, false, 'CIE-11'),
('XA1J93', 'Conducto de la glándula sublingual', 'category', false, false, 'CIE-11'),
('XA93V5', 'Faringe', 'category', false, false, 'CIE-11'),
('XA4J67', 'Orofaringe', 'category', false, false, 'CIE-11'),
('XA8RX5', 'Pared lateral de la orofaringe', 'category', false, false, 'CIE-11'),
('XA8659', 'Pared posterior de la orofaringe', 'category', false, false, 'CIE-11'),
('XA88V4', 'Vallécula', 'category', false, false, 'CIE-11'),
('XA60Q5', 'Hendidura branquial', 'category', false, false, 'CIE-11'),
('XA2J67', 'Hipofaringe', 'category', false, false, 'CIE-11'),
('XA3MZ0', 'Receso piriforme', 'category', false, false, 'CIE-11'),
('XA4NZ9', 'Región postcricoidea', 'category', false, false, 'CIE-11'),
('XA0XK1', 'Pared hipofaríngea', 'category', false, false, 'CIE-11'),
('XA9607', 'Aparato gastrointestinal', 'category', false, false, 'CIE-11'),
('XA0828', 'Esófago', 'category', false, false, 'CIE-11'),
('XA1180', 'Tercio superior del esófago', 'category', false, false, 'CIE-11'),
('XA2BY3', 'Tercio medio del esófago', 'category', false, false, 'CIE-11'),
('XA9CB6', 'Tercio inferior del esófago', 'category', false, false, 'CIE-11'),
('XA0N03', 'Esófago cervical', 'category', false, false, 'CIE-11'),
('XA8JT3', 'Esófago torácico', 'category', false, false, 'CIE-11'),
('XA0TN5', 'Esófago abdominal', 'category', false, false, 'CIE-11'),
('XA4YW8', 'Sitios contiguos del esófago', 'category', false, false, 'CIE-11'),
('XA7SR6', 'Unión cardioesofágica', 'category', false, false, 'CIE-11'),
('XA7MC7', 'Estómago', 'category', false, false, 'CIE-11'),
('XA2828', 'Cardias gástrico', 'category', false, false, 'CIE-11'),
('XA7UE1', 'Cuerpo gástrico', 'category', false, false, 'CIE-11'),
('XA56K7', 'Fondo gástrico', 'category', false, false, 'CIE-11'),
('XA6P89', 'Píloro gástrico', 'category', false, false, 'CIE-11'),
('XA4EC5', 'Antro pilórico', 'category', false, false, 'CIE-11'),
('XA7WQ5', 'Curvatura mayor de estómago', 'category', false, false, 'CIE-11'),
('XA4ML9', 'Curvatura menor del estómago', 'category', false, false, 'CIE-11'),
('XA6452', 'Intestino delgado', 'category', false, false, 'CIE-11'),
('XA9780', 'Duodeno', 'category', false, false, 'CIE-11'),
('XA8UM1', 'Yeyuno', 'category', false, false, 'CIE-11'),
('XA0QT6', 'Ileon', 'category', false, false, 'CIE-11'),
('XA1B13', 'Intestino grueso', 'category', false, false, 'CIE-11'),
('XA6J68', 'Ciego', 'category', false, false, 'CIE-11'),
('XA03U9', 'Colon', 'category', false, false, 'CIE-11'),
('XA3AL5', 'Colon ascendente', 'category', false, false, 'CIE-11'),
('XA95L3', 'Flexión hepática del colon', 'category', false, false, 'CIE-11'),
('XA49U1', 'Colon transverso', 'category', false, false, 'CIE-11'),
('XA1PY9', 'Flexión esplénica del colon', 'category', false, false, 'CIE-11'),
('XA2G13', 'Colon descendente', 'category', false, false, 'CIE-11'),
('XA8YJ9', 'Colon sigmoide', 'category', false, false, 'CIE-11'),
('XA33J5', 'Unión rectosigmoidea', 'category', false, false, 'CIE-11'),
('XA7177', 'Colon descendente y ángulo esplénico del colon', 'category', false, false, 'CIE-11'),
('XA25P9', 'Colon ascendente y ángulo derecho del colon', 'category', false, false, 'CIE-11'),
('XA4KU2', 'Recto', 'category', false, false, 'CIE-11'),
('XA0D34', 'Ano', 'category', false, false, 'CIE-11'),
('XA39S6', 'Conducto anal', 'category', false, false, 'CIE-11'),
('XA8QB7', 'Zona cloacogénica', 'category', false, false, 'CIE-11'),
('XA28R6', 'Tracto gastrointestinal superior, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA8PW4', 'Apéndice', 'category', false, false, 'CIE-11'),
('XA0W19', 'Sistema hepatobiliar', 'category', false, false, 'CIE-11'),
('XA5DY0', 'Hígado', 'category', false, false, 'CIE-11'),
('XA5766', 'Lóbulo izquierdo del hígado', 'category', false, false, 'CIE-11'),
('XA2KG6', 'Lóbulo derecho del hígado', 'category', false, false, 'CIE-11'),
('XA3278', 'Lóbulo caudado del hígado', 'category', false, false, 'CIE-11'),
('XA13D3', 'Lóbulo cuadrado del hígado', 'category', false, false, 'CIE-11'),
('XA0KT3', 'Tracto biliar', 'category', false, false, 'CIE-11'),
('XA4415', 'Conductos biliares hepáticos', 'category', false, false, 'CIE-11'),
('XA89K4', 'Conducto hepático izquierdo', 'category', false, false, 'CIE-11'),
('XA6M95', 'Conducto hepático derecho', 'category', false, false, 'CIE-11'),
('XA96K1', 'Conducto hepático común', 'category', false, false, 'CIE-11'),
('XA0077', 'Conducto cístico', 'category', false, false, 'CIE-11'),
('XA8KL9', 'Vesícula biliar', 'category', false, false, 'CIE-11'),
('XA6R80', 'Coducto biliar común', 'category', false, false, 'CIE-11'),
('XA6WA8', 'esfínter de Oddi', 'category', false, false, 'CIE-11'),
('XA7QA8', 'Ampolla de Vater', 'category', false, false, 'CIE-11'),
('XA9HM5', 'Conducto biliar extrahepático', 'category', false, false, 'CIE-11'),
('XA3QC5', 'Páncreas', 'category', false, false, 'CIE-11'),
('XA1412', 'Cabeza del páncreas', 'category', false, false, 'CIE-11'),
('XA8LA4', 'Cuello del páncreas', 'category', false, false, 'CIE-11'),
('XA6ZE4', 'Cuerpo del páncreas', 'category', false, false, 'CIE-11'),
('XA0CX6', 'Cola de páncreas', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
