-- CIE11 Import Part 15
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('DA01.2Z', 'Granulomas o lesiones granulomatoides de la mucosa bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA01.3', 'Infecciones de los labios o de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.30', 'Celulitis o absceso de los tejidos blandos de la boca', 'category', false, false, 'CIE-11'),
('DA01.3Y', 'Otras infecciones especificadas de los labios o de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.3Z', 'Infecciones de los labios o de la mucosa bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA01.4', 'Hiperplasia irritativa de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.40', 'Hiperplasia papilar de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.41', 'Hiperplasia debida a una prótesis dental', 'category', false, false, 'CIE-11'),
('DA01.42', 'Pólipo fibroepitelial bucal', 'category', false, false, 'CIE-11'),
('DA01.4Z', 'Hiperplasia irritativa de la mucosa bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA01.Y', 'Otros trastornos especificados de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.Z', 'Trastornos de la mucosa bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA02', 'Diversos trastornos especificados de los labios o de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA02.0', 'Trastornos genéticos o congénitos de los labios o la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA02.1', 'Xerostomía', 'category', false, false, 'CIE-11'),
('DA02.2', 'Fibrosis de la submucosa bucal', 'category', false, false, 'CIE-11'),
('DA02.3', 'Gingivoestomatitis de contacto', 'category', false, false, 'CIE-11'),
('DA02.30', 'Gingivoestomatitis alérgica de contacto', 'category', false, false, 'CIE-11'),
('DA02.31', 'Gingivoestomatitis de contacto irritativa', 'category', false, false, 'CIE-11'),
('DA03', 'Enfermedades de la lengua', 'category', false, false, 'CIE-11'),
('DA03.0', 'Glositis', 'category', false, false, 'CIE-11'),
('DA03.1', 'Lengua geográfica', 'category', false, false, 'CIE-11'),
('DA03.2', 'Atrofia de las papilas linguales', 'category', false, false, 'CIE-11'),
('DA03.3', 'Glositis romboidal mediana', 'category', false, false, 'CIE-11'),
('DA03.4', 'Hipertrofia de las papilas linguales', 'category', false, false, 'CIE-11'),
('DA03.5', 'Macroglosia', 'category', false, false, 'CIE-11'),
('DA03.Y', 'Otras enfermedades especificadas de la lengua', 'category', false, false, 'CIE-11'),
('DA03.Z', 'Enfermedades de la lengua, sin especificación', 'category', false, false, 'CIE-11'),
('DA04', 'Enfermedades de las glándulas salivales', 'category', false, false, 'CIE-11'),
('DA04.0', 'Atrofia de glándula salival', 'category', false, false, 'CIE-11'),
('DA04.1', 'Hipertrofia de glándula salival', 'category', false, false, 'CIE-11'),
('DA04.2', 'Sialoadenitis', 'category', false, false, 'CIE-11'),
('DA04.3', 'Absceso de glándula salival', 'category', false, false, 'CIE-11'),
('DA04.4', 'Sialolitiasis', 'category', false, false, 'CIE-11'),
('DA04.5', 'Mucocele de glándula salival', 'category', false, false, 'CIE-11'),
('DA04.6', 'Alteraciones de la secreción salival', 'category', false, false, 'CIE-11'),
('DA04.7', 'Sialofagia', 'category', false, false, 'CIE-11'),
('DA04.8', 'Sialosquesis', 'category', false, false, 'CIE-11'),
('DA04.Y', 'Otras enfermedades especificadas de las glándulas salivales', 'category', false, false, 'CIE-11'),
('DA04.Z', 'Enfermedades de las glándulas salivales, sin especificación', 'category', false, false, 'CIE-11'),
('DA05', 'Quistes de la boca, la cara o el cuello', 'category', false, false, 'CIE-11'),
('DA05.0', 'Quistes odontógenos congénitos', 'category', false, false, 'CIE-11'),
('DA05.1', 'Quistes no odontógenos congénitos de la región bucal', 'category', false, false, 'CIE-11'),
('DA05.Y', 'Otros quistes especificados de la boca, la cara o el cuello', 'category', false, false, 'CIE-11'),
('DA05.Z', 'Quistes de la boca, la cara o el cuello, sin especificación', 'category', false, false, 'CIE-11'),
('DA06', 'Algunas enfermedades especificadas de los maxilares', 'category', false, false, 'CIE-11'),
('DA06.0', 'Afecciones inflamatorias de los maxilares', 'category', false, false, 'CIE-11'),
('DA06.1', 'Alveolitis de los maxilares', 'category', false, false, 'CIE-11'),
('DA06.2', 'Exostosis de la mandíbula', 'category', false, false, 'CIE-11'),
('DA06.3', 'Cavidad ósea mandibular de Stafne', 'category', false, false, 'CIE-11'),
('DA06.Y', 'Otro(a)(s) algunas enfermedades especificadas de los maxilares especificado(a)(s)', 'category', false, false, 'CIE-11'),
('DA06.Z', 'Algunas enfermedades especificadas de los maxilares, sin especificación', 'category', false, false, 'CIE-11'),
('DA07', 'Trastornos de la formación o erupción de los dientes', 'category', false, false, 'CIE-11'),
('DA07.0', 'Opacidades o lesiones por fluoruro', 'category', false, false, 'CIE-11'),
('DA07.1', 'Opacidades del esmalte dental que no se deben al fluoruro', 'category', false, false, 'CIE-11'),
('DA07.3', 'Defectos de la odontogénesis', 'category', false, false, 'CIE-11'),
('DA07.4', 'Anomalía de la raíz del diente', 'category', false, false, 'CIE-11'),
('DA07.5', 'Displasia del cemento dental', 'category', false, false, 'CIE-11'),
('DA07.6', 'trastornos de la erupción dentaria', 'category', false, false, 'CIE-11'),
('DA07.60', 'Síndrome de la dentición', 'category', false, false, 'CIE-11'),
('DA07.61', 'Anquilosis dental', 'category', false, false, 'CIE-11'),
('DA07.6Y', 'Otros trastornos especificados de la dentición', 'category', false, false, 'CIE-11'),
('DA07.6Z', 'Trastornos de la dentición, sin especificación', 'category', false, false, 'CIE-11'),
('DA07.7', 'Dientes retenidos', 'category', false, false, 'CIE-11'),
('DA07.8', 'Dientes impactados', 'category', false, false, 'CIE-11'),
('DA07.Y', 'Otros trastornos especificados de la formación o erupción de los dientes', 'category', false, false, 'CIE-11'),
('DA07.Z', 'Trastornos de la formación o erupción de los dientes, sin especificación', 'category', false, false, 'CIE-11'),
('DA08', 'Enfermedades de los tejidos duros de los dientes', 'category', false, false, 'CIE-11'),
('DA08.0', 'Caries dental', 'category', false, false, 'CIE-11'),
('DA08.1', 'Algunas enfermedades especificadas de los tejidos duros de los dientes', 'category', false, false, 'CIE-11'),
('DA08.10', 'Erosión excesiva de los dientes', 'category', false, false, 'CIE-11'),
('DA08.11', 'Abrasión de los dientes', 'category', false, false, 'CIE-11'),
('DA08.12', 'Erosión de los dientes', 'category', false, false, 'CIE-11'),
('DA08.13', 'Abfracción', 'category', false, false, 'CIE-11'),
('DA08.14', 'Reabsorción patológica de los dientes', 'category', false, false, 'CIE-11'),
('DA08.15', 'Cambios de color posteruptivos de los tejidos dentales duros', 'category', false, false, 'CIE-11'),
('DA08.2', 'Lesiones dentales crónicas', 'category', false, false, 'CIE-11'),
('DA08.3', 'Fractura no traumática de diente', 'category', false, false, 'CIE-11'),
('DA08.4', 'Depósitos en los dientes', 'category', false, false, 'CIE-11'),
('DA08.Y', 'Otras enfermedades especificadas de los tejidos duros de los dientes', 'category', false, false, 'CIE-11'),
('DA08.Z', 'Enfermedades de los tejidos duros de los dientes, sin especificación', 'category', false, false, 'CIE-11'),
('DA09', 'Enfermedades de la pulpa o de los tejidos periapicales', 'category', false, false, 'CIE-11'),
('DA09.0', 'Pulpitis', 'category', false, false, 'CIE-11'),
('DA09.1', 'Necrosis de la pulpa', 'category', false, false, 'CIE-11'),
('DA09.2', 'Absceso de la pulpa', 'category', false, false, 'CIE-11'),
('DA09.3', 'Absceso fénix', 'category', false, false, 'CIE-11'),
('DA09.4', 'Degeneración de la pulpa', 'category', false, false, 'CIE-11'),
('DA09.5', 'Formación anormal de tejido duro en la pulpa', 'category', false, false, 'CIE-11'),
('DA09.6', 'Absceso periapical', 'category', false, false, 'CIE-11'),
('DA09.60', 'Absceso periapical con afectación facial', 'category', false, false, 'CIE-11'),
('DA09.61', 'Absceso periapical con fístula', 'category', false, false, 'CIE-11'),
('DA09.62', 'Absceso periapical sin fístula', 'category', false, false, 'CIE-11'),
('DA09.6Y', 'Otro absceso periapical especificado', 'category', false, false, 'CIE-11'),
('DA09.6Z', 'Absceso periapical, sin especificación', 'category', false, false, 'CIE-11'),
('DA09.7', 'Periodontitis periapical', 'category', false, false, 'CIE-11'),
('DA09.70', 'Periodontitis apical aguda originada en la pulpa', 'category', false, false, 'CIE-11'),
('DA09.71', 'Periodontitis apical crónica', 'category', false, false, 'CIE-11'),
('DA09.7Y', 'Otra periodontitis periapical especificada', 'category', false, false, 'CIE-11'),
('DA09.7Z', 'Periodontitis periapical, sin especificación', 'category', false, false, 'CIE-11'),
('DA09.8', 'Quiste radicular', 'category', false, false, 'CIE-11'),
('DA09.Y', 'Otras enfermedades especificadas de la pulpa o de los tejidos periapicales', 'category', false, false, 'CIE-11'),
('DA09.Z', 'Enfermedades de la pulpa o de los tejidos periapicales, sin especificación', 'category', false, false, 'CIE-11'),
('DA0A', 'Algunos trastornos especificados de los dientes o de las estructuras de sostén', 'category', false, false, 'CIE-11'),
('DA0A.0', 'Exfoliación de los dientes por causas sistémicas', 'category', false, false, 'CIE-11'),
('DA0A.1', 'Pérdida de dientes por traumatismo, extracción o enfermedad periodontal focal', 'category', false, false, 'CIE-11'),
('DA0A.2', 'Atrofia del reborde alveolar desdentado', 'category', false, false, 'CIE-11'),
('DA0A.3', 'Raíz dental retenida', 'category', false, false, 'CIE-11'),
('DA0A.Y', 'Otros trastornos especificados de los dientes o de las estructuras de sostén', 'category', false, false, 'CIE-11'),
('DA0A.Z', 'Trastornos de los dientes o de las estructuras de sostén, sin especificación', 'category', false, false, 'CIE-11'),
('DA0B', 'Enfermedades gingivales', 'category', false, false, 'CIE-11'),
('DA0B.0', 'Gingivitis alérgica', 'category', false, false, 'CIE-11'),
('DA0B.1', 'Gingivitis catarral', 'category', false, false, 'CIE-11'),
('DA0B.2', 'Gingivitis eruptiva', 'category', false, false, 'CIE-11'),
('DA0B.3', 'Gingivitis atrófica senil', 'category', false, false, 'CIE-11'),
('DA0B.4', 'Abscesos gingivales agudos múltiples', 'category', false, false, 'CIE-11'),
('DA0B.5', 'Deformidades o afecciones congénitas o adquiridas de las encías', 'category', false, false, 'CIE-11'),
('DA0B.6', 'Pericoronitis', 'category', false, false, 'CIE-11'),
('DA0B.Y', 'Otras enfermedades gingivales especificadas', 'category', false, false, 'CIE-11'),
('DA0B.Z', 'Enfermedades gingivales, sin especificación', 'category', false, false, 'CIE-11'),
('DA0C', 'Enfermedad periodontal', 'category', false, false, 'CIE-11'),
('DA0C.0', 'Periodontitis aguda', 'category', false, false, 'CIE-11'),
('DA0C.1', 'Periodontitis agresiva', 'category', false, false, 'CIE-11'),
('DA0C.2', 'Periodontosis', 'category', false, false, 'CIE-11'),
('DA0C.3', 'Enfermedades periodontales necrosantes', 'category', false, false, 'CIE-11'),
('DA0C.30', 'Periodontitis ulcerativa necrosante', 'category', false, false, 'CIE-11'),
('DA0C.31', 'Noma', 'category', false, false, 'CIE-11'),
('DA0C.3Y', 'Otras enfermedades periodontales necrosantes especificadas', 'category', false, false, 'CIE-11'),
('DA0C.3Z', 'Enfermedades periodontales necrosantes, sin especificación', 'category', false, false, 'CIE-11'),
('DA0C.4', 'Absceso del periodonto', 'category', false, false, 'CIE-11'),
('DA0C.5', 'Eritema gingival lineal', 'category', false, false, 'CIE-11'),
('DA0C.Y', 'Otra enfermedad periodontal especificada', 'category', false, false, 'CIE-11'),
('DA0C.Z', 'Enfermedad periodontal, sin especificación', 'category', false, false, 'CIE-11'),
('DA0D', 'Algunos trastornos especificados del reborde gingival o alveolar desdentado', 'category', false, false, 'CIE-11'),
('DA0D.0', 'Retracción gingival', 'category', false, false, 'CIE-11'),
('DA0D.1', 'Agrandamiento gingival', 'category', false, false, 'CIE-11'),
('DA0D.2', 'Lesiones del reborde gingival o alveolar desdentado con traumatismo', 'category', false, false, 'CIE-11'),
('DA0D.3', 'Hipoplasminogenemia', 'category', false, false, 'CIE-11'),
('DA0D.4', 'Gingivitis por algodón', 'category', false, false, 'CIE-11'),
('DA0D.5', 'Úlcera gingival', 'category', false, false, 'CIE-11'),
('DA0D.Y', 'Otros trastornos especificados de la cresta gingival o alveolar desdentado', 'category', false, false, 'CIE-11'),
('DA0E', 'Anomalías dentofaciales', 'category', false, false, 'CIE-11'),
('DA0E.0', 'Anomalías mayores del tamaño de la mandíbula', 'category', false, false, 'CIE-11'),
('DA0E.00', 'Micrognatia', 'category', false, false, 'CIE-11'),
('DA0E.0Y', 'Anomalías mayores especificadas del tamaño de la mandíbula', 'category', false, false, 'CIE-11'),
('DA0E.0Z', 'Anomalías mayores del tamaño de la mandíbula, sin especificación', 'category', false, false, 'CIE-11'),
('DA0E.1', 'Anomalías de la relación maxilobasilar', 'category', false, false, 'CIE-11'),
('DA0E.2', 'Anomalías de la relación entre las arcadas dentales', 'category', false, false, 'CIE-11'),
('DA0E.3', 'Anomalías de la posición del diente', 'category', false, false, 'CIE-11'),
('DA0E.4', 'Impactación de comida', 'category', false, false, 'CIE-11'),
('DA0E.5', 'Disoclusión', 'category', false, false, 'CIE-11'),
('DA0E.50', 'Mala oclusión de clase II, división 2', 'category', false, false, 'CIE-11'),
('DA0E.51', 'Disoclusión de clase I de Angle', 'category', false, false, 'CIE-11'),
('DA0E.5Y', 'Otra disoclusión especificada', 'category', false, false, 'CIE-11'),
('DA0E.5Z', 'Disoclusión, sin especificación', 'category', false, false, 'CIE-11'),
('DA0E.6', 'Anomalías dentofaciales funcionales', 'category', false, false, 'CIE-11'),
('DA0E.7', 'Trastornos dentofaciales parafuncionales', 'category', false, false, 'CIE-11'),
('DA0E.8', 'Trastornos de la articulación temporomandibular', 'category', false, false, 'CIE-11'),
('DA0E.Y', 'Otras anomalías dentofaciales especificadas', 'category', false, false, 'CIE-11'),
('DA0E.Z', 'Anomalías dentofaciales, sin especificación', 'category', false, false, 'CIE-11'),
('DA0F', 'Trastornos sensitivos que afectan al complejo bucofacial', 'category', false, false, 'CIE-11'),
('DA0F.0', 'Síndrome de la boca ardiente', 'category', false, false, 'CIE-11'),
('DA0F.Y', 'Trastornos sensitivos especificados que afectan al complejo bucofacial', 'category', false, false, 'CIE-11'),
('DA0F.Z', 'Trastornos sensitivos que afectan al complejo bucofacial, sin especificación', 'category', false, false, 'CIE-11'),
('DA0Y', 'Otras enfermedades y trastornos especificados del complejo bucofacial', 'category', false, false, 'CIE-11'),
('DA0Z', 'Enfermedades y trastornos del complejo bucofacial, sin especificación', 'category', false, false, 'CIE-11'),
('DA20', 'Alteraciones anatómicas adquiridas del esófago', 'category', false, false, 'CIE-11'),
('DA20.0', 'Obstrucción del esófago', 'category', false, false, 'CIE-11'),
('DA20.1', 'Divertículo del esófago, adquirido', 'category', false, false, 'CIE-11'),
('DA20.2', 'Membrana del esófago', 'category', false, false, 'CIE-11'),
('DA20.3', 'Perforación del esófago', 'category', false, false, 'CIE-11'),
('DA20.30', 'Ruptura espontánea del esófago', 'category', false, false, 'CIE-11'),
('DA20.3Y', 'Otra perforación especificada del esófago', 'category', false, false, 'CIE-11'),
('DA20.3Z', 'Perforación del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('DA20.Y', 'Otras alteraciones anatómicas adquiridas especificadas del esófago', 'category', false, false, 'CIE-11'),
('DA20.Z', 'Alteraciones anatómicas adquiridas del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('DA21', 'Trastornos de la motilidad del esófago', 'category', false, false, 'CIE-11'),
('DA21.0', 'Acalasia', 'category', false, false, 'CIE-11'),
('DA21.1', 'Trastorno de la motilidad de la porción cervical o superior del esófago', 'category', false, false, 'CIE-11'),
('DA21.2', 'Trastorno del peristaltismo esofágico', 'category', false, false, 'CIE-11'),
('DA21.20', 'Peristaltismo hipertensivo', 'category', false, false, 'CIE-11'),
('DA21.21', 'Peristaltismo hipotensivo', 'category', false, false, 'CIE-11'),
('DA21.22', 'Peristaltismo espástico', 'category', false, false, 'CIE-11'),
('DA21.2Y', 'Otro trastorno especificado del peristaltismo esofágico', 'category', false, false, 'CIE-11'),
('DA21.2Z', 'Trastorno del peristaltismo esofágico, sin especificación', 'category', false, false, 'CIE-11'),
('DA21.3', 'Trastorno de la función del esfínter esofágico inferior', 'category', false, false, 'CIE-11'),
('DA21.Y', 'Otros trastornos especificados de la motilidad del esófago', 'category', false, false, 'CIE-11'),
('DA21.Z', 'Trastornos de la motilidad del esófago, sin especificar', 'category', false, false, 'CIE-11'),
('DA22', 'Enfermedad por reflujo gastroesofágico', 'category', false, false, 'CIE-11'),
('DA22.0', 'Enfermedad por reflujo gastroesofágico no erosiva', 'category', false, false, 'CIE-11'),
('DA22.1', 'Enfermedad por reflujo gastroesofágico erosiva', 'category', false, false, 'CIE-11'),
('DA22.Z', 'Enfermedad por reflujo gastroesofágico, sin especificación', 'category', false, false, 'CIE-11'),
('DA23', 'Epitelio cilíndrico metaplásico del esófago', 'category', false, false, 'CIE-11'),
('DA23.0', 'Epitelio de Barrett', 'category', false, false, 'CIE-11'),
('DA23.1', 'Displasia del epitelio de Barrett', 'category', false, false, 'CIE-11'),
('DA23.2', 'Úlcera de Barrett', 'category', false, false, 'CIE-11'),
('DA23.Y', 'Otro epitelio cilíndrico metaplásico especificado del esófago', 'category', false, false, 'CIE-11'),
('DA23.Z', 'Epitelio cilíndrico metaplásico del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('DA24', 'Esofagitis', 'category', false, false, 'CIE-11'),
('DA24.0', 'Esofagitis infecciosa', 'category', false, false, 'CIE-11'),
('DA24.00', 'Flemón esofágico', 'category', false, false, 'CIE-11'),
('DA24.0Y', 'Otra esofagitis infecciosa especificada', 'category', false, false, 'CIE-11'),
('DA24.0Z', 'Esofagitis infecciosa, sin especificación', 'category', false, false, 'CIE-11'),
('DA24.1', 'Esofagitis eosinofílica', 'category', false, false, 'CIE-11'),
('DA24.2', 'Esofagitis por causas externas', 'category', false, false, 'CIE-11'),
('DA24.20', 'Esofagitis química', 'category', false, false, 'CIE-11'),
('DA24.21', 'Esofagitis provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA24.22', 'Esofagitis por radiación', 'category', false, false, 'CIE-11'),
('DA24.2Z', 'Esofagitis por causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA24.Y', 'Otras esofagitis especificadas', 'category', false, false, 'CIE-11'),
('DA24.Z', 'Esofagitis, sin especificación', 'category', false, false, 'CIE-11'),
('DA25', 'Úlcera esofágica', 'category', false, false, 'CIE-11'),
('DA25.0', 'Erosión esofágica', 'category', false, false, 'CIE-11'),
('DA25.1', 'Úlcera esofágica infecciosa', 'category', false, false, 'CIE-11'),
('DA25.10', 'Úlcera esofágica bacteriana', 'category', false, false, 'CIE-11'),
('DA25.11', 'Úlcera esofágica micótica', 'category', false, false, 'CIE-11'),
('DA25.12', 'Úlcera esofágica parasitaria', 'category', false, false, 'CIE-11'),
('DA25.13', 'Úlcera esofágica viral', 'category', false, false, 'CIE-11'),
('DA25.1Y', 'Otra úlcera esofágica infecciosa especificada', 'category', false, false, 'CIE-11'),
('DA25.1Z', 'Úlcera esofágica infecciosa, sin especificación', 'category', false, false, 'CIE-11'),
('DA25.2', 'Úlcera esofágica de origen alérgico o inmunitario', 'category', false, false, 'CIE-11'),
('DA25.3', 'Úlcera esofágica debida a causas externas', 'category', false, false, 'CIE-11'),
('DA25.30', 'Úlcera esofágica química', 'category', false, false, 'CIE-11'),
('DA25.31', 'Úlcera esofágica provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA25.32', 'Úlcera esofágica por radiación', 'category', false, false, 'CIE-11'),
('DA25.3Y', 'Otra úlcera esofágica especificada debida a causas externas', 'category', false, false, 'CIE-11'),
('DA25.3Z', 'Úlcera esofágica debida a causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA25.Y', 'Otra úlcera esofágica especificada', 'category', false, false, 'CIE-11'),
('DA25.Z', 'Úlcera esofágica, sin especificación', 'category', false, false, 'CIE-11'),
('DA26', 'Trastornos vasculares del esófago', 'category', false, false, 'CIE-11'),
('DA26.0', 'Várices esofágicas', 'category', false, false, 'CIE-11'),
('DA26.00', 'Várices esofágicas sangrantes', 'category', false, false, 'CIE-11'),
('DA26.01', 'Várices esofágicas sin hemorragia', 'category', false, false, 'CIE-11'),
('DA26.0Z', 'Várices esofágicas, sin especificación', 'category', false, false, 'CIE-11'),
('DA26.1', 'Angiodisplasia o malformación arteriovenosa del esófago', 'category', false, false, 'CIE-11'),
('DA26.2', 'Hemorragia intramural del esófago', 'category', false, false, 'CIE-11'),
('DA26.3', 'Síndrome de laceración y hemorragia gastroesofágica', 'category', false, false, 'CIE-11'),
('DA26.Y', 'Otros trastornos vasculares especificados del esófago', 'category', false, false, 'CIE-11'),
('DA26.Z', 'Trastornos vasculares del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('DA2Y', 'Otras enfermedades especificadas del esófago', 'category', false, false, 'CIE-11'),
('DA2Z', 'Enfermedades del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('DA40', 'Alteraciones anatómicas adquiridas del estómago', 'category', false, false, 'CIE-11'),
('DA40.0', 'Obstrucción de la salida gástrica', 'category', false, false, 'CIE-11'),
('DA40.1', 'Fístula gástrica adquirida', 'category', false, false, 'CIE-11'),
('DA40.2', 'Vólvulo gástrico', 'category', false, false, 'CIE-11'),
('DA40.3', 'Divertículo gástrico', 'category', false, false, 'CIE-11'),
('DA40.4', 'Estenosis y estrechez del estómago en reloj de arena', 'category', false, false, 'CIE-11'),
('DA40.5', 'Gastroptosis', 'category', false, false, 'CIE-11'),
('DA40.Y', 'Otras alteraciones anatómicas adquiridas del estómago especificadas', 'category', false, false, 'CIE-11'),
('DA40.Z', 'Alteraciones anatómicas adquiridas del estómago, sin especificación', 'category', false, false, 'CIE-11'),
('DA41', 'Trastornos motores o secretores gastroduodenales', 'category', false, false, 'CIE-11'),
('DA41.0', 'Motilidad gástrica anormal', 'category', false, false, 'CIE-11'),
('DA41.00', 'Gastroparesia', 'category', false, false, 'CIE-11'),
('DA41.0Y', 'Otra motilidad gástrica anormal especificada', 'category', false, false, 'CIE-11'),
('DA41.0Z', 'Motilidad gástrica anormal, no especificada', 'category', false, false, 'CIE-11'),
('DA41.1', 'Dilatación aguda del estómago', 'category', false, false, 'CIE-11'),
('DA41.2', 'Hipersecreción de ácido', 'category', false, false, 'CIE-11'),
('DA41.3', 'Aclorhidria', 'category', false, false, 'CIE-11'),
('DA41.Y', 'Otros trastornos motores o secretores gastroduodenales especificados', 'category', false, false, 'CIE-11'),
('DA41.Z', 'Trastornos motores o secretores gastroduodenales, sin especificación', 'category', false, false, 'CIE-11'),
('DA42', 'Gastritis', 'category', false, false, 'CIE-11'),
('DA42.0', 'Gastritis autoinmunitaria', 'category', false, false, 'CIE-11'),
('DA42.1', 'Gastritis por Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA42.2', 'Gastritis eosinofílica', 'category', false, false, 'CIE-11'),
('DA42.3', 'Gastritis linfocítica', 'category', false, false, 'CIE-11'),
('DA42.4', 'Gastritis alérgica', 'category', false, false, 'CIE-11'),
('DA42.40', 'Gastritis alérgica por hipersensibilidad mediada por IgE', 'category', false, false, 'CIE-11'),
('DA42.41', 'Gastritis alérgica por hipersensibilidad sin mediación de IgE', 'category', false, false, 'CIE-11'),
('DA42.4Y', 'Otra gastritis alérgica especificada', 'category', false, false, 'CIE-11'),
('DA42.4Z', 'Gastritis alérgica, sin especificación', 'category', false, false, 'CIE-11'),
('DA42.5', 'Gastritis por reflujo duodenogástrico', 'category', false, false, 'CIE-11'),
('DA42.6', 'Enfermedad de Ménétrier', 'category', false, false, 'CIE-11'),
('DA42.7', 'Gastritis de etiología desconocida con características endoscópicas o patológicas especificadas', 'category', false, false, 'CIE-11'),
('DA42.70', 'Gastritis superficial aguda de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.71', 'Gastritis superficial crónica de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.72', 'Gastritis hemorrágica aguda de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.73', 'Gastritis atrófica crónica de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.74', 'Gastritis metaplásica de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.75', 'Gastritis granulomatosa de causa desconocida', 'category', false, false, 'CIE-11'),
('DA42.76', 'Gastritis hipertrófica de etiología desconocida', 'category', false, false, 'CIE-11'),
('DA42.7Y', 'Otra gastritis especificada de etiología desconocida con características endoscópicas o patológicas especificadas', 'category', false, false, 'CIE-11'),
('DA42.8', 'Gastritis por causas externas', 'category', false, false, 'CIE-11'),
('DA42.80', 'Gastritis alcohólica', 'category', false, false, 'CIE-11'),
('DA42.81', 'Gastritis por radiación', 'category', false, false, 'CIE-11'),
('DA42.82', 'Gastritis química', 'category', false, false, 'CIE-11'),
('DA42.83', 'Gastritis provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA42.8Z', 'Gastritis por causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA42.9', 'Flemón gástrico', 'category', false, false, 'CIE-11'),
('DA42.Y', 'Otra gastritis especificada', 'category', false, false, 'CIE-11'),
('DA42.Z', 'Gastritis, sin especificación', 'category', false, false, 'CIE-11'),
('DA43', 'Trastornos vasculares del estómago', 'category', false, false, 'CIE-11'),
('DA43.0', 'Várices gástricas', 'category', false, false, 'CIE-11'),
('DA43.1', 'Angiodisplasia del estómago', 'category', false, false, 'CIE-11'),
('DA43.2', 'Malformación arteriovenosa del estómago', 'category', false, false, 'CIE-11'),
('DA43.3', 'Gastropatía portal hipertensiva', 'category', false, false, 'CIE-11'),
('DA43.4', 'Ectasia vascular difusa del estómago', 'category', false, false, 'CIE-11'),
('DA43.Y', 'Otros trastornos vasculares especificados del estómago', 'category', false, false, 'CIE-11'),
('DA43.Z', 'Trastornos vasculares del estómago, sin especificación', 'category', false, false, 'CIE-11'),
('DA44', 'Pólipo gástrico', 'category', false, false, 'CIE-11'),
('DA44.0', 'Pólipo hiperplásico del estómago', 'category', false, false, 'CIE-11'),
('DA44.1', 'Pólipo de las glándulas fúndicas del estómago', 'category', false, false, 'CIE-11'),
('DA44.2', 'Pólipo hamartomatoso del estómago', 'category', false, false, 'CIE-11'),
('DA44.Y', 'Otro pólipo gástrico especificado', 'category', false, false, 'CIE-11'),
('DA44.Z', 'Pólipo gástrico, sin especificación', 'category', false, false, 'CIE-11'),
('DA4Y', 'Otras enfermedades especificadas del estómago', 'category', false, false, 'CIE-11'),
('DA4Z', 'Enfermedades del estómago, sin especificación', 'category', false, false, 'CIE-11'),
('DA50', 'Alteraciones anatómicas adquiridas del duodeno', 'category', false, false, 'CIE-11'),
('DA50.0', 'Obstrucción del duodeno', 'category', false, false, 'CIE-11'),
('DA50.1', 'Divertículo del duodeno', 'category', false, false, 'CIE-11'),
('DA50.2', 'Fístula del duodeno', 'category', false, false, 'CIE-11'),
('DA50.3', 'Deformidad del duodeno, adquirida', 'category', false, false, 'CIE-11'),
('DA50.Y', 'Otras alteraciones anatómicas adquiridas especificadas del duodeno', 'category', false, false, 'CIE-11'),
('DA50.Z', 'Alteraciones anatómicas adquiridas del duodeno, sin especificación', 'category', false, false, 'CIE-11'),
('DA51', 'Duodenitis', 'category', false, false, 'CIE-11'),
('DA51.0', 'Duodenitis asociada a Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA51.1', 'Duodenitis eosinofílica', 'category', false, false, 'CIE-11'),
('DA51.2', 'Duodenitis linfocítica', 'category', false, false, 'CIE-11'),
('DA51.3', 'Duodenitis alérgica', 'category', false, false, 'CIE-11'),
('DA51.4', 'Duodenitis de causa desconocida con características endoscópicas o histopatológicas específicas', 'category', false, false, 'CIE-11'),
('DA51.40', 'Duodenitis hemorrágica aguda de causa desconocida', 'category', false, false, 'CIE-11'),
('DA51.41', 'Duodenitis granulomatosa de causa desconocida', 'category', false, false, 'CIE-11'),
('DA51.4Z', 'Duodenitis de causa desconocida con características endoscópicas o histopatológicas específicas, sin especificación', 'category', false, false, 'CIE-11'),
('DA51.5', 'Duodenitis debida a causas externas', 'category', false, false, 'CIE-11'),
('DA51.50', 'Duodenitis alcohólica', 'category', false, false, 'CIE-11'),
('DA51.51', 'Duodenitis provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA51.52', 'Duodenitis química', 'category', false, false, 'CIE-11'),
('DA51.53', 'Duodenitis por radiación', 'category', false, false, 'CIE-11'),
('DA51.5Y', 'Otras duodenitis por causas externas', 'category', false, false, 'CIE-11'),
('DA51.5Z', 'Duodenitis por causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA51.6', 'Duodenitis infecciosa', 'category', false, false, 'CIE-11'),
('DA51.60', 'Flemón duodenal', 'category', false, false, 'CIE-11'),
('DA51.6Y', 'Otra duodenitis infecciosa especificada', 'category', false, false, 'CIE-11'),
('DA51.6Z', 'Duodenitis infecciosa, sin especificación', 'category', false, false, 'CIE-11'),
('DA51.Y', 'Otra duodenitis especificada', 'category', false, false, 'CIE-11'),
('DA51.Z', 'Duodenitis, no especificada', 'category', false, false, 'CIE-11'),
('DA52', 'Trastornos vasculares del duodeno', 'category', false, false, 'CIE-11'),
('DA52.0', 'Várices duodenales', 'category', false, false, 'CIE-11'),
('DA52.1', 'Angiodisplasia del duodeno', 'category', false, false, 'CIE-11'),
('DA52.2', 'Malformación arteriovenosa del duodeno', 'category', false, false, 'CIE-11'),
('DA52.Y', 'Otros trastornos vasculares especificados del duodeno', 'category', false, false, 'CIE-11'),
('DA52.Z', 'Trastornos vasculares del duodeno, sin especificación', 'category', false, false, 'CIE-11'),
('DA53', 'Pólipo duodenal', 'category', false, false, 'CIE-11'),
('DA53.0', 'Pólipos hiperplásicos del duodeno', 'category', false, false, 'CIE-11'),
('DA53.Y', 'Otro pólipo duodenal especificado', 'category', false, false, 'CIE-11'),
('DA53.Z', 'Pólipo duodenal, sin especificación', 'category', false, false, 'CIE-11'),
('DA5Y', 'Otras enfermedades especificadas del duodeno', 'category', false, false, 'CIE-11'),
('DA5Z', 'Enfermedades del duodeno, sin especificación', 'category', false, false, 'CIE-11'),
('DA60', 'Úlcera gástrica', 'category', false, false, 'CIE-11'),
('DA60.0', 'Erosión gástrica', 'category', false, false, 'CIE-11'),
('DA60.1', 'Úlcera gástrica por Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA60.2', 'Úlcera gástrica provocada por medicamentos y asociada a Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA60.3', 'Úlcera de estrés del estómago', 'category', false, false, 'CIE-11'),
('DA60.4', 'Úlcera gástrica eosinofílica', 'category', false, false, 'CIE-11'),
('DA60.5', 'Úlcera gástrica linfocítica', 'category', false, false, 'CIE-11'),
('DA60.6', 'Úlcera gástrica por causas externas', 'category', false, false, 'CIE-11'),
('DA60.60', 'Úlcera gástrica provocada por el alcohol', 'category', false, false, 'CIE-11'),
('DA60.61', 'Úlcera gástrica por agente químico', 'category', false, false, 'CIE-11'),
('DA60.62', 'Úlcera gástrica provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA60.63', 'Úlcera gástrica por radiación', 'category', false, false, 'CIE-11'),
('DA60.6Y', 'Otra úlcera gástrica especificada por causas externas', 'category', false, false, 'CIE-11'),
('DA60.6Z', 'Úlcera gástrica por causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA60.7', 'Úlcera gástrica secundaria a infección', 'category', false, false, 'CIE-11'),
('DA60.Y', 'Otra úlcera gástrica especificada', 'category', false, false, 'CIE-11'),
('DA60.Z', 'Úlcera gástrica, sin especificación', 'category', false, false, 'CIE-11'),
('DA61', 'Úlcera péptica de localización no especificada', 'category', false, false, 'CIE-11'),
('DA62', 'Úlcera anastomótica', 'category', false, false, 'CIE-11'),
('DA62.0', 'Erosión anastomósica', 'category', false, false, 'CIE-11'),
('DA62.1', 'Úlcera anastomósica asociada a Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA62.2', 'Úlcera anastomósica provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA62.3', 'Úlcera péptica anastomósica', 'category', false, false, 'CIE-11'),
('DA62.Y', 'Otra úlcera anastomótica especificada', 'category', false, false, 'CIE-11'),
('DA62.Z', 'Úlcera anastomótica sin especificación', 'category', false, false, 'CIE-11'),
('DA63', 'Úlcera duodenal', 'category', false, false, 'CIE-11'),
('DA63.0', 'Erosión duodenal', 'category', false, false, 'CIE-11'),
('DA63.1', 'Úlcera duodenal asociada a Helicobacter pylori', 'category', false, false, 'CIE-11'),
('DA63.2', 'Úlcera duodenal asociada a Helicobacter pylori y provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA63.3', 'Úlcera de estrés del duodeno', 'category', false, false, 'CIE-11'),
('DA63.4', 'Úlcera duodenal eosinofílica', 'category', false, false, 'CIE-11'),
('DA63.5', 'Úlcera duodenal debida a causas externas', 'category', false, false, 'CIE-11'),
('DA63.50', 'Úlcera duodenal provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA63.51', 'Úlcera duodenal por radiación', 'category', false, false, 'CIE-11'),
('DA63.52', 'Úlcera duodenal química', 'category', false, false, 'CIE-11'),
('DA63.5Y', 'Otra úlcera duodenal especificada debida a causas externas', 'category', false, false, 'CIE-11'),
('DA63.5Z', 'Úlcera duodenal debida a causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA63.6', 'Úlcera duodenal infecciosa', 'category', false, false, 'CIE-11'),
('DA63.60', 'Úlcera duodenal bacteriana', 'category', false, false, 'CIE-11'),
('DA63.61', 'Úlcera duodenal viral', 'category', false, false, 'CIE-11'),
('DA63.62', 'Úlcera duodenal micótica', 'category', false, false, 'CIE-11'),
('DA63.63', 'Úlcera parasitaria duodenal', 'category', false, false, 'CIE-11'),
('DA63.6Z', 'Úlcera duodenal infecciosa, sin especificación', 'category', false, false, 'CIE-11'),
('DA63.Y', 'Otra úlcera duodenal especificada', 'category', false, false, 'CIE-11'),
('DA63.Z', 'Úlcera duodenal, sin especificación', 'category', false, false, 'CIE-11'),
('DA7Z', 'Enfermedades del estómago o del duodeno, sin especificar', 'category', false, false, 'CIE-11'),
('DA90', 'Anomalías congénitas no estructurales del intestino delgado', 'category', false, false, 'CIE-11'),
('DA90.0', 'Síndrome diarreico', 'category', false, false, 'CIE-11'),
('DA90.1', 'Defecto congénito del transporte intestinal', 'category', false, false, 'CIE-11'),
('DA90.2', 'Trastornos congénitos de la motilidad intestinal', 'category', false, false, 'CIE-11'),
('DA90.Y', 'Otras anomalías congénitas no estructurales especificadas del intestino delgado', 'category', false, false, 'CIE-11'),
('DA90.Z', 'Anomalías congénitas no estructurales del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA91', 'Obstrucción del intestino delgado', 'category', false, false, 'CIE-11'),
('DA91.0', 'Invaginación del intestino delgado', 'category', false, false, 'CIE-11'),
('DA91.1', 'Vólvulo del intestino delgado', 'category', false, false, 'CIE-11'),
('DA91.2', 'Adherencias o bandas de intestino delgado con obstrucción', 'category', false, false, 'CIE-11'),
('DA91.3', 'Íleo obstructivo del intestino delgado por impactación', 'category', false, false, 'CIE-11'),
('DA91.30', 'Íleo del intestino delgado debido a cálculo biliar', 'category', false, false, 'CIE-11'),
('DA91.31', 'Enterolito del intestino delgado', 'category', false, false, 'CIE-11'),
('DA91.3Y', 'Otro íleo obstructivo del intestino delgado especificado por impactación', 'category', false, false, 'CIE-11'),
('DA91.3Z', 'Íleo obstructivo del intestino delgado por impactación, sin especificación', 'category', false, false, 'CIE-11'),
('DA91.Y', 'Otra obstrucción del intestino delgado especificada', 'category', false, false, 'CIE-11'),
('DA91.Z', 'Obstrucción del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA92', 'Otras alteraciones anatómicas adquiridas del intestino delgado', 'category', false, false, 'CIE-11'),
('DA92.0', 'Fístula del intestino delgado', 'category', false, false, 'CIE-11'),
('DA92.1', 'Neumatosis del intestino delgado', 'category', false, false, 'CIE-11'),
('DA92.Y', 'Otras alteraciones anatómicas adquiridas especificadas del intestino delgado', 'category', false, false, 'CIE-11'),
('DA92.Z', 'Otras alteraciones anatómicas adquiridas del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA93', 'Trastornos de la motilidad del intestino delgado', 'category', false, false, 'CIE-11'),
('DA93.0', 'Íleo paralítico', 'category', false, false, 'CIE-11'),
('DA93.Y', 'Otros trastornos especificados de la motilidad del intestino delgado', 'category', false, false, 'CIE-11'),
('DA93.Z', 'Trastornos de la motilidad del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA94', 'Enteritis o úlcera no infecciosa del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.0', 'Úlcera primaria del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.00', 'Úlcera primaria inespecífica del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.01', 'Úlceras crónicas múltiples inespecíficas del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.02', 'Enteritis estenosante ulcerativa multifocal criptogénica', 'category', false, false, 'CIE-11'),
('DA94.0Y', 'Otra úlcera primaria especificada del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.0Z', 'Úlcera primaria del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA94.1', 'Enteritis del intestino delgado provocada por medicamentos o sustancias tóxicas', 'category', false, false, 'CIE-11'),
('DA94.2', 'Enteritis alérgica o alimentaria del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.20', 'Enteritis alérgica del intestino delgado mediada por IgE', 'category', false, false, 'CIE-11'),
('DA94.21', 'Enteritis eosinofílica', 'category', false, false, 'CIE-11'),
('DA94.22', 'Síndrome de enterocolitis provocado por proteínas alimentarias', 'category', false, false, 'CIE-11'),
('DA94.2Y', 'Otra enteritis alimentaria o alérgica especificada del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.2Z', 'Enteritis alimentaria o alérgica del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA94.3', 'Enteritis o úlcera del intestino delgado debidas a otras causas externas', 'category', false, false, 'CIE-11'),
('DA94.30', 'Enteritis o úlcera del intestino delgado debida a un cuerpo extraño', 'category', false, false, 'CIE-11'),
('DA94.31', 'Enteritis o úlcera del intestino delgado debida a radiación', 'category', false, false, 'CIE-11'),
('DA94.32', 'Enteritis o úlcera del intestino delgado debida a un traumatismo', 'category', false, false, 'CIE-11'),
('DA94.3Z', 'Enteritis o úlcera del intestino delgado debidas a otras causas externas, sin especificación', 'category', false, false, 'CIE-11'),
('DA94.Y', 'Otra enteritis o úlcera no infecciosa especificada del intestino delgado', 'category', false, false, 'CIE-11'),
('DA94.Z', 'Enteritis o úlcera no infecciosa del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA95', 'Enfermedad celíaca', 'category', false, false, 'CIE-11'),
('DA96', 'Malabsorción intestinal o enteropatía proteinorreica', 'category', false, false, 'CIE-11'),
('DA96.0', 'Malabsorción intestinal', 'category', false, false, 'CIE-11'),
('DA96.00', 'Síndrome de crecimiento excesivo de bacterias', 'category', false, false, 'CIE-11'),
('DA96.01', 'Esprúe tropical', 'category', false, false, 'CIE-11'),
('DA96.02', 'Malabsorción o intolerancia de nutrientes específicos', 'category', false, false, 'CIE-11'),
('DA96.04', 'Síndrome del intestino corto', 'category', false, false, 'CIE-11'),
('DA96.05', 'Insuficiencia intestinal', 'category', false, false, 'CIE-11'),
('DA96.0Y', 'Otra malabsorción intestinal especificada', 'category', false, false, 'CIE-11'),
('DA96.0Z', 'Malabsorción intestinal sin especificación', 'category', false, false, 'CIE-11'),
('DA96.1', 'Enteropatía perdedora de proteínas', 'category', false, false, 'CIE-11'),
('DA96.Y', 'Otra malabsorción intestinal o enteropatía proteinorreica especificada', 'category', false, false, 'CIE-11'),
('DA96.Z', 'Malabsorción intestinal o enteropatía proteinorreica, sin especificación', 'category', false, false, 'CIE-11'),
('DA97', 'Algunos trastornos vasculares del intestino delgado', 'category', false, false, 'CIE-11'),
('DA97.0', 'Angiodisplasia del intestino delgado', 'category', false, false, 'CIE-11'),
('DA97.1', 'Malformación arteriovenosa del intestino delgado', 'category', false, false, 'CIE-11'),
('DA97.2', 'Vasculitis de las arterias mesentéricas', 'category', false, false, 'CIE-11'),
('DA97.3', 'Várices del intestino delgado', 'category', false, false, 'CIE-11'),
('DA97.Z', 'Algunos trastornos vasculares del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA98', 'Pólipos de intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.0', 'Hamartoma del intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.1', 'Pólipo hiperplásico del intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.2', 'Pólipo fibroide inflamatorio del intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.3', 'Hiperplasia linfoide del intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.Y', 'Otros pólipos especificados del intestino delgado', 'category', false, false, 'CIE-11'),
('DA98.Z', 'Pólipos del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DA9Y', 'Otras enfermedades especificadas del intestino delgado', 'category', false, false, 'CIE-11'),
('DA9Z', 'Enfermedades del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DB10', 'Apendicitis', 'category', false, false, 'CIE-11'),
('DB10.0', 'Apendicitis aguda', 'category', false, false, 'CIE-11'),
('DB10.00', 'Apendicitis aguda con peritonitis generalizada', 'category', false, false, 'CIE-11'),
('DB10.01', 'Apendicitis aguda con peritonitis localizada', 'category', false, false, 'CIE-11'),
('DB10.02', 'Apendicitis aguda sin peritonitis localizada o generalizada', 'category', false, false, 'CIE-11'),
('DB10.1', 'Apendicitis crónica', 'category', false, false, 'CIE-11'),
('DB10.Y', 'Otra apendicitis especificada', 'category', false, false, 'CIE-11'),
('DB10.Z', 'Apendicitis, sin especificación', 'category', false, false, 'CIE-11'),
('DB11', 'Algunas enfermedades especificadas del apéndice', 'category', false, false, 'CIE-11'),
('DB11.0', 'Megaloapéndice', 'category', false, false, 'CIE-11'),
('DB11.1', 'Hiperplasia del apéndice', 'category', false, false, 'CIE-11'),
('DB11.2', 'Concreciones apendiculares', 'category', false, false, 'CIE-11'),
('DB11.3', 'Divertículo adquirido del apéndice', 'category', false, false, 'CIE-11'),
('DB11.4', 'Fístula del apéndice', 'category', false, false, 'CIE-11'),
('DB11.5', 'Intususcepción del apéndice', 'category', false, false, 'CIE-11'),
('DB11.6', 'Mucocele del apéndice', 'category', false, false, 'CIE-11'),
('DB1Y', 'Otro(a)(s) enfermedades del apéndice especificado(a)(s)', 'category', false, false, 'CIE-11'),
('DB1Z', 'Enfermedades del apéndice, sin especificación', 'category', false, false, 'CIE-11'),
('DB30', 'Obstrucción del intestino grueso', 'category', false, false, 'CIE-11'),
('DB30.0', 'Intususcepción del intestino grueso', 'category', false, false, 'CIE-11'),
('DB30.1', 'Vólvulo del intestino grueso', 'category', false, false, 'CIE-11'),
('DB30.2', 'Adherencias del intestino grueso con obstrucción', 'category', false, false, 'CIE-11'),
('DB30.3', 'Impactación del intestino grueso', 'category', false, false, 'CIE-11'),
('DB30.4', 'Estenosis del recto', 'category', false, false, 'CIE-11'),
('DB30.Y', 'Otra obstrucción especificada del intestino grueso', 'category', false, false, 'CIE-11'),
('DB30.Z', 'Obstrucción del intestino grueso, sin especificación', 'category', false, false, 'CIE-11'),
('DB31', 'Otra alteración anatómica adquirida del intestino grueso', 'category', false, false, 'CIE-11'),
('DB31.0', 'Fístula del intestino grueso', 'category', false, false, 'CIE-11'),
('DB31.1', 'Neumatosis del intestino grueso', 'category', false, false, 'CIE-11'),
('DB31.2', 'Prolapso rectal', 'category', false, false, 'CIE-11'),
('DB31.Y', 'Otra alteración anatómica adquirida especificada del intestino grueso', 'category', false, false, 'CIE-11'),
('DB31.Z', 'Otra alteración anatómica adquirida del intestino grueso, sin especificación', 'category', false, false, 'CIE-11'),
('DB32', 'Trastornos de la motilidad del intestino grueso', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
