-- CIE11 Import Part 65
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XM96M0', 'Safrazina', 'category', false, false, 'CIE-11'),
('XM1023', 'Tranilcipromina', 'category', false, false, 'CIE-11'),
('XM2NP3', 'Antidepresivo selectivo inhibidor de la recaptación de laserotonina', 'category', false, false, 'CIE-11'),
('XM6WT9', 'Citalopram', 'category', false, false, 'CIE-11'),
('XM24M0', 'Femoxetina', 'category', false, false, 'CIE-11'),
('XM7LE6', 'Fluoxetina', 'category', false, false, 'CIE-11'),
('XM64L1', 'Fluvoxamina', 'category', false, false, 'CIE-11'),
('XM5R26', 'Indalpina', 'category', false, false, 'CIE-11'),
('XM3PJ6', 'Paroxetina', 'category', false, false, 'CIE-11'),
('XM6WB9', 'Zimelidina', 'category', false, false, 'CIE-11'),
('XM5TZ9', 'Sertralina', 'category', false, false, 'CIE-11'),
('XM7ZN2', 'Alaproclate', 'category', false, false, 'CIE-11'),
('XM4MF4', 'Etoperidona', 'category', false, false, 'CIE-11'),
('XM7PX8', 'Escitalopram', 'category', false, false, 'CIE-11'),
('XM0HR7', 'Cianopramina', 'category', false, false, 'CIE-11'),
('XM0PE4', 'Antidepresivo inhibidor selectivo de la recaptación de serotonina norepinefrina', 'category', false, false, 'CIE-11'),
('XM8D31', 'Antidepresivo triazolopiridina', 'category', false, false, 'CIE-11'),
('XM10Q5', 'Duloxetina', 'category', false, false, 'CIE-11'),
('XM3KS5', 'Desvenlafaxina', 'category', false, false, 'CIE-11'),
('XM6J21', 'Milnacipran', 'category', false, false, 'CIE-11'),
('XM17Z4', 'Levomilnacipran', 'category', false, false, 'CIE-11'),
('XM36V6', 'Venlafaxina', 'category', false, false, 'CIE-11'),
('XM03J9', 'Bifemelano', 'category', false, false, 'CIE-11'),
('XM03E6', 'Bupropion', 'category', false, false, 'CIE-11'),
('XM7U12', 'Diclofensina', 'category', false, false, 'CIE-11'),
('XM78C1', 'Otros antidepresivos especificados', 'category', false, false, 'CIE-11'),
('XM0T46', 'Mianserina', 'category', false, false, 'CIE-11'),
('XM5QV7', 'Minaprina', 'category', false, false, 'CIE-11'),
('XM6X89', 'Nomifensina', 'category', false, false, 'CIE-11'),
('XM6AP8', 'Oxitriptan', 'category', false, false, 'CIE-11'),
('XM4WM9', 'Prazitona', 'category', false, false, 'CIE-11'),
('XM0ST5', 'Tiazesima', 'category', false, false, 'CIE-11'),
('XM5DV5', 'Tianeptina', 'category', false, false, 'CIE-11'),
('XM5L45', 'Viloxazina', 'category', false, false, 'CIE-11'),
('XM62E7', 'Trazodona', 'category', false, false, 'CIE-11'),
('XM0B23', 'Mirtazapina', 'category', false, false, 'CIE-11'),
('XM54Q7', 'Triptófano', 'category', false, false, 'CIE-11'),
('XM85H1', 'Nefazodona', 'category', false, false, 'CIE-11'),
('XM4ML8', 'Oxaflozano', 'category', false, false, 'CIE-11'),
('XM80H8', 'Medifoxamina', 'category', false, false, 'CIE-11'),
('XM4ZF1', 'Pivagabina', 'category', false, false, 'CIE-11'),
('XM70H2', 'Reboxetina', 'category', false, false, 'CIE-11'),
('XM5KP8', 'Gepirona', 'category', false, false, 'CIE-11'),
('XM5F11', 'Agomelatina', 'category', false, false, 'CIE-11'),
('XM7T91', 'Vilazodona', 'category', false, false, 'CIE-11'),
('XM4230', 'Hyperici herba', 'category', false, false, 'CIE-11'),
('XM0EP0', 'Vortioxetina', 'category', false, false, 'CIE-11'),
('XM8FB6', 'Serotonina', 'category', false, false, 'CIE-11'),
('XM0227', 'Metapramina', 'category', false, false, 'CIE-11'),
('XM9KG1', 'Inhibidores no selectivos de la recaptación de monoaminas', 'category', false, false, 'CIE-11'),
('XM6FC9', 'Desipramina', 'category', false, false, 'CIE-11'),
('XM6PZ9', 'Imipramina', 'category', false, false, 'CIE-11'),
('XM76Z6', 'Clomipramina', 'category', false, false, 'CIE-11'),
('XM37K4', 'Opipramol', 'category', false, false, 'CIE-11'),
('XM9WZ5', 'Trimipramina', 'category', false, false, 'CIE-11'),
('XM7T42', 'Lofepramina', 'category', false, false, 'CIE-11'),
('XM6H22', 'Dibenzepina', 'category', false, false, 'CIE-11'),
('XM7BL0', 'Amitriptilina', 'category', false, false, 'CIE-11'),
('XM79G5', 'Nortriptilina', 'category', false, false, 'CIE-11'),
('XM2WA4', 'Protriptilina', 'category', false, false, 'CIE-11'),
('XM1LC7', 'Doxepina', 'category', false, false, 'CIE-11'),
('XM24M7', 'Iprindole', 'category', false, false, 'CIE-11'),
('XM1575', 'Melitraceno', 'category', false, false, 'CIE-11'),
('XM8QA6', 'Butriptilina', 'category', false, false, 'CIE-11'),
('XM2T20', 'Dosulepina', 'category', false, false, 'CIE-11'),
('XM8TQ9', 'Amoxapina', 'category', false, false, 'CIE-11'),
('XM1190', 'Amineptina', 'category', false, false, 'CIE-11'),
('XM41L8', 'Maprotilina', 'category', false, false, 'CIE-11'),
('XM34S5', 'Quinupramina', 'category', false, false, 'CIE-11'),
('XM4SZ9', 'Óxido de imipramina', 'category', false, false, 'CIE-11'),
('XM3MV6', 'Dimetacrina', 'category', false, false, 'CIE-11'),
('XM5RG3', 'Oxaprotilina', 'category', false, false, 'CIE-11'),
('XM7GY1', 'Noxiptilina', 'category', false, false, 'CIE-11'),
('XM1UL5', 'Inhibidores de la monoaminooxidasa A', 'category', false, false, 'CIE-11'),
('XM14X9', 'Mioclobemida', 'category', false, false, 'CIE-11'),
('XM1TG1', 'Toloxatona', 'category', false, false, 'CIE-11'),
('XM2PL7', 'Cannabinoides', 'category', false, false, 'CIE-11'),
('XM3UF9', 'Nabilona', 'category', false, false, 'CIE-11'),
('XM4HM2', 'Tetrahidrocannabinol', 'category', false, false, 'CIE-11'),
('XM5B55', 'Cannabidiol', 'category', false, false, 'CIE-11'),
('XM1W83', 'Dronabinol', 'category', false, false, 'CIE-11'),
('XM4SV9', 'Alucinógenos', 'category', false, false, 'CIE-11'),
('XM5JH5', 'Psilocina', 'category', false, false, 'CIE-11'),
('XM7642', 'Psilocibina', 'category', false, false, 'CIE-11'),
('XM0T53', 'Mescalina', 'category', false, false, 'CIE-11'),
('XM78V1', 'Aeruginascina', 'category', false, false, 'CIE-11'),
('XM9WX3', 'Bufotenina', 'category', false, false, 'CIE-11'),
('XM9T61', 'N, N-dimetiltriptamina', 'category', false, false, 'CIE-11'),
('XM9CL3', 'Amida de ácido lisérgico', 'category', false, false, 'CIE-11'),
('XM5M84', 'Fenilciclidina', 'category', false, false, 'CIE-11'),
('XM50E4', 'Muscimol', 'category', false, false, 'CIE-11'),
('XM1PJ8', 'Ácido iboténico', 'category', false, false, 'CIE-11'),
('XM5SB5', 'Salvinorina A', 'category', false, false, 'CIE-11'),
('XM3C53', 'Anfetaminil', 'category', false, false, 'CIE-11'),
('XM3E65', 'Benzedrina (anfetamina)', 'category', false, false, 'CIE-11'),
('XM1NA8', 'Anfetaminas estimulantes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM1WW4', 'Dexedrina', 'category', false, false, 'CIE-11'),
('XM6LD5', 'Dextroanfetamina', 'category', false, false, 'CIE-11'),
('XM07Y4', 'Extasis', 'category', false, false, 'CIE-11'),
('XM5B49', 'Metanfetamina', 'category', false, false, 'CIE-11'),
('XM3WD9', 'Metedrina', 'category', false, false, 'CIE-11'),
('XM3Q37', 'Metilanfetamina', 'category', false, false, 'CIE-11'),
('XM9932', 'Cafeína psicostimulante', 'category', false, false, 'CIE-11'),
('XM6RB6', 'Psicoestimulante anfetamina', 'category', false, false, 'CIE-11'),
('XM6V10', 'Tenanfetamina', 'category', false, false, 'CIE-11'),
('XM12M9', 'Psicoestimulantes, TDAH y agentes nootrópicos', 'category', false, false, 'CIE-11'),
('XM7LR7', 'Simpaticomiméticos de acción central', 'category', false, false, 'CIE-11'),
('XM1NX2', 'Metilfenidato', 'category', false, false, 'CIE-11'),
('XM52S5', 'Pemolina', 'category', false, false, 'CIE-11'),
('XM75Z6', 'Modafinilo', 'category', false, false, 'CIE-11'),
('XM5921', 'Fenozolona', 'category', false, false, 'CIE-11'),
('XM9DQ5', 'Atomoxetina', 'category', false, false, 'CIE-11'),
('XM5288', 'Dexmetilfenidato', 'category', false, false, 'CIE-11'),
('XM3ZW9', 'Armodafinilo', 'category', false, false, 'CIE-11'),
('XM9FY1', 'Etriptamina', 'category', false, false, 'CIE-11'),
('XM3K58', 'Levo propilhexedrina', 'category', false, false, 'CIE-11'),
('XM2XU4', 'Derivados de xantina', 'category', false, false, 'CIE-11'),
('XM0NG8', 'Cafeína', 'category', false, false, 'CIE-11'),
('XM3Y68', 'Propentofilina', 'category', false, false, 'CIE-11'),
('XM1SE2', 'Meclofenoxato', 'category', false, false, 'CIE-11'),
('XM8QG2', 'Nizofenona', 'category', false, false, 'CIE-11'),
('XM84X9', 'Prolintano', 'category', false, false, 'CIE-11'),
('XM8EX0', 'Pipradrol', 'category', false, false, 'CIE-11'),
('XM8029', 'Vinpocetina', 'category', false, false, 'CIE-11'),
('XM37E2', 'Tipepidina', 'category', false, false, 'CIE-11'),
('XM1LB1', 'Piritinol', 'category', false, false, 'CIE-11'),
('XM5207', 'Piracetam', 'category', false, false, 'CIE-11'),
('XM3HZ4', 'Deanol', 'category', false, false, 'CIE-11'),
('XM2AB6', 'Fipexide', 'category', false, false, 'CIE-11'),
('XM5TT1', 'Citicolina', 'category', false, false, 'CIE-11'),
('XM5N75', 'Oxiracetam', 'category', false, false, 'CIE-11'),
('XM6EM2', 'Pirisudanol', 'category', false, false, 'CIE-11'),
('XM1MZ1', 'Linopirdina', 'category', false, false, 'CIE-11'),
('XM0Z60', 'Aniracetam', 'category', false, false, 'CIE-11'),
('XM77H2', 'Acetilcarnitina', 'category', false, false, 'CIE-11'),
('XM5CY6', 'Idebenona', 'category', false, false, 'CIE-11'),
('XM59Z4', 'Pramiracetam', 'category', false, false, 'CIE-11'),
('XM3WZ9', 'Adrafinil', 'category', false, false, 'CIE-11'),
('XM94C0', 'Mebicar', 'category', false, false, 'CIE-11'),
('XM3J14', 'Fenibut', 'category', false, false, 'CIE-11'),
('XM45U3', 'Aceglumato de deanol', 'category', false, false, 'CIE-11'),
('XM9DQ3', 'Dietiltriptamina (DET)', 'category', false, false, 'CIE-11'),
('XM6LV4', 'Dimetil triptamina', 'category', false, false, 'CIE-11'),
('XM9438', 'Semillas de madera de Hawai', 'category', false, false, 'CIE-11'),
('XM52J2', 'Azul celestial ( gloria de la mañana)', 'category', false, false, 'CIE-11'),
('XM79N5', 'Hongo mágico', 'category', false, false, 'CIE-11'),
('XM0169', 'Botones de mescal', 'category', false, false, 'CIE-11'),
('XM32H5', 'Semillas de gloria de la mañana', 'category', false, false, 'CIE-11'),
('XM4B51', 'Pearly Gates (semillas de gloria de la mañana)', 'category', false, false, 'CIE-11'),
('XM0QA2', 'Peyote', 'category', false, false, 'CIE-11'),
('XM0075', 'Ácido yohimbico', 'category', false, false, 'CIE-11'),
('XM8E16', 'Canabinol', 'category', false, false, 'CIE-11'),
('XM0XQ5', 'Alucinógenos depresores del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM31A7', 'Droga psicodisléptica', 'category', false, false, 'CIE-11'),
('XM3Z58', 'Agentes psicomiméticos', 'category', false, false, 'CIE-11'),
('XM8X97', 'Alucinógeno', 'category', false, false, 'CIE-11'),
('XM7DW4', 'Megalucinógeno', 'category', false, false, 'CIE-11'),
('XM05B3', 'Diamorfina', 'category', false, false, 'CIE-11'),
('XM69R4', 'Morfina, derivados y metabolitos de la morfina', 'category', false, false, 'CIE-11'),
('XM39E2', '14-hidroxidihidro-morfinona', 'category', false, false, 'CIE-11'),
('XM5CY8', 'Acemorfano', 'category', false, false, 'CIE-11'),
('XM0E25', 'Benzomorfano', 'category', false, false, 'CIE-11'),
('XM8YM7', 'Bencil morfina', 'category', false, false, 'CIE-11'),
('XM0BB1', 'Terciopelo azul', 'category', false, false, 'CIE-11'),
('XM45R8', 'Desomorfina', 'category', false, false, 'CIE-11'),
('XM4T95', 'Dihidromorfina', 'category', false, false, 'CIE-11'),
('XM3473', 'Hidromorfinol', 'category', false, false, 'CIE-11'),
('XM8SD7', 'Hidromorfona', 'category', false, false, 'CIE-11'),
('XM78E0', 'Metopon', 'category', false, false, 'CIE-11'),
('XM7VL7', 'Morfonileniletilmorfina', 'category', false, false, 'CIE-11'),
('XM7W06', 'Nicomorfina', 'category', false, false, 'CIE-11'),
('XM9BE3', 'Normorfina', 'category', false, false, 'CIE-11'),
('XM64M0', 'Oximorfona', 'category', false, false, 'CIE-11'),
('XM1KZ5', 'Morfina', 'category', false, false, 'CIE-11'),
('XM0P98', 'Benzilmorfina', 'category', false, false, 'CIE-11'),
('XM7ZJ1', 'Mirofina', 'category', false, false, 'CIE-11'),
('XM4ES0', 'Opio', 'category', false, false, 'CIE-11'),
('XM2T93', 'Alcaloides del opio (total)', 'category', false, false, 'CIE-11'),
('XM69X3', 'Alcaloides de opio estandarizados en polvo', 'category', false, false, 'CIE-11'),
('XM91H1', 'Tintura de alcaloides del opio (alcanforado)', 'category', false, false, 'CIE-11'),
('XM1EE2', 'Laúdano', 'category', false, false, 'CIE-11'),
('XM1YK2', 'Papaveretum', 'category', false, false, 'CIE-11'),
('XM1LB8', 'Paregórico', 'category', false, false, 'CIE-11'),
('XM4SL9', 'Oxicodona', 'category', false, false, 'CIE-11'),
('XM79K2', 'Acetildihidrocodeinona', 'category', false, false, 'CIE-11'),
('XM7HX3', 'Eucodal', 'category', false, false, 'CIE-11'),
('XM9UH3', 'Nalfurafina', 'category', false, false, 'CIE-11'),
('XM4587', 'Codeína, derivados de codeína y otros opioides utilizados en la supresión de la tos', 'category', false, false, 'CIE-11'),
('XM3DS6', 'Acetildihidrocodeina', 'category', false, false, 'CIE-11'),
('XM05R0', 'Mezcla de codeína antitusivo', 'category', false, false, 'CIE-11'),
('XM3YP8', 'Cliradon', 'category', false, false, 'CIE-11'),
('XM4046', 'Desocodeína', 'category', false, false, 'CIE-11'),
('XM06K5', 'Dihidrocodeína', 'category', false, false, 'CIE-11'),
('XM77C9', 'Dihidroisocodeina', 'category', false, false, 'CIE-11'),
('XM9UN6', 'Hycodan', 'category', false, false, 'CIE-11'),
('XM0YG5', 'Hidroxidihidrocodeinona', 'category', false, false, 'CIE-11'),
('XM07U7', 'Percodan', 'category', false, false, 'CIE-11'),
('XM5NP7', 'Piminodina', 'category', false, false, 'CIE-11'),
('XM3WN9', 'Etilmorfina', 'category', false, false, 'CIE-11'),
('XM8E09', 'Hidrocodona', 'category', false, false, 'CIE-11'),
('XM6RX7', 'Noscapina', 'category', false, false, 'CIE-11'),
('XM4QV7', 'Folcodina', 'category', false, false, 'CIE-11'),
('XM9UV0', 'Dextrometorfan', 'category', false, false, 'CIE-11'),
('XM2358', 'Tebacon', 'category', false, false, 'CIE-11'),
('XM7V96', 'Dimemorfano', 'category', false, false, 'CIE-11'),
('XM5PZ4', 'Normetadona', 'category', false, false, 'CIE-11'),
('XM1ZY9', 'Metadona, derivados de la metadona y otros fármacos utilizados para tratar los trastornos adictivos a los opioides', 'category', false, false, 'CIE-11'),
('XM7XP1', 'Metadona', 'category', false, false, 'CIE-11'),
('XM9RG7', 'Levo-iso-metadona', 'category', false, false, 'CIE-11'),
('XM4MV8', 'Anestésicos opioides', 'category', false, false, 'CIE-11'),
('XM4G88', 'Alfentanilo', 'category', false, false, 'CIE-11'),
('XM1EF3', 'Sufentanil', 'category', false, false, 'CIE-11'),
('XM7YQ6', 'Anilerdina', 'category', false, false, 'CIE-11'),
('XM0YQ0', 'Remifentanilo', 'category', false, false, 'CIE-11'),
('XM7TT0', 'Antagonista de analgésico narcótico', 'category', false, false, 'CIE-11'),
('XM0850', 'Ciclazocina', 'category', false, false, 'CIE-11'),
('XM65J2', 'Levalorfano', 'category', false, false, 'CIE-11'),
('XM4HP3', 'Antagonista de la morfina', 'category', false, false, 'CIE-11'),
('XM14T9', 'Naloxona', 'category', false, false, 'CIE-11'),
('XM2M16', 'Naltrexona', 'category', false, false, 'CIE-11'),
('XM9BM4', 'Antagonista de los narcóticos', 'category', false, false, 'CIE-11'),
('XM5DJ2', 'Antagonistas de opiáceos', 'category', false, false, 'CIE-11'),
('XM3TK0', 'Bromuro de metilnaltrexona', 'category', false, false, 'CIE-11'),
('XM4GP3', 'Alvimopan', 'category', false, false, 'CIE-11'),
('XM93Z3', 'Naloxegol', 'category', false, false, 'CIE-11'),
('XM6KY8', 'Antagonista opioide', 'category', false, false, 'CIE-11'),
('XM4S22', 'Otros opioides analgésicos naturales, sintéticos y semisintéticos', 'category', false, false, 'CIE-11'),
('XM30T6', 'Prodine', 'category', false, false, 'CIE-11'),
('XM9907', 'Opiáceos antitusivos', 'category', false, false, 'CIE-11'),
('XM6C31', 'Mezcla para la tos que contiene opiaceos', 'category', false, false, 'CIE-11'),
('XM8ZF5', 'Dextrorfano', 'category', false, false, 'CIE-11'),
('XM1K75', 'Difencloxacina', 'category', false, false, 'CIE-11'),
('XM9SW6', 'Dipipanona', 'category', false, false, 'CIE-11'),
('XM81P5', 'Dromoran', 'category', false, false, 'CIE-11'),
('XM4EW3', 'Eptazocina', 'category', false, false, 'CIE-11'),
('XM6CK0', 'Etoheptacina', 'category', false, false, 'CIE-11'),
('XM35C1', 'Heptalgin', 'category', false, false, 'CIE-11'),
('XM5F21', 'Levo-dromoran', 'category', false, false, 'CIE-11'),
('XM4P40', 'Levopropoxifeno', 'category', false, false, 'CIE-11'),
('XM1R71', 'Levorfanol', 'category', false, false, 'CIE-11'),
('XM0GS3', 'Meperidina', 'category', false, false, 'CIE-11'),
('XM8PP7', 'Narcótico sintético', 'category', false, false, 'CIE-11'),
('XM8MP5', 'Nisentilo', 'category', false, false, 'CIE-11'),
('XM7S23', 'Opioide', 'category', false, false, 'CIE-11'),
('XM04Z5', 'Fenadoxona', 'category', false, false, 'CIE-11'),
('XM2542', 'Fenazocina', 'category', false, false, 'CIE-11'),
('XM9B34', 'Fenomorfano', 'category', false, false, 'CIE-11'),
('XM72D5', 'Pipadona', 'category', false, false, 'CIE-11'),
('XM39L3', 'Profadol', 'category', false, false, 'CIE-11'),
('XM9AZ5', 'Promedol', 'category', false, false, 'CIE-11'),
('XM3E08', 'Propoxifeno', 'category', false, false, 'CIE-11'),
('XM6625', 'Racemoramida', 'category', false, false, 'CIE-11'),
('XM8804', 'Tebaína', 'category', false, false, 'CIE-11'),
('XM09H6', 'Tilidina', 'category', false, false, 'CIE-11'),
('XM7KC0', 'Tramadol', 'category', false, false, 'CIE-11'),
('XM5UK3', 'Viminol', 'category', false, false, 'CIE-11'),
('XM9Y28', 'Difenoxilato', 'category', false, false, 'CIE-11'),
('XM86N4', 'Loperamida', 'category', false, false, 'CIE-11'),
('XM9NL3', 'Derivados de fenilpiperidina', 'category', false, false, 'CIE-11'),
('XM9HP7', 'Quetobemidona', 'category', false, false, 'CIE-11'),
('XM76M8', 'Fentanil', 'category', false, false, 'CIE-11'),
('XM8286', 'Derivados de difenilpropilamina', 'category', false, false, 'CIE-11'),
('XM3246', 'Dextromoramida', 'category', false, false, 'CIE-11'),
('XM55Z5', 'Piritramida', 'category', false, false, 'CIE-11'),
('XM8GB8', 'Dextropropoxifeno', 'category', false, false, 'CIE-11'),
('XM5GN5', 'Becitramida', 'category', false, false, 'CIE-11'),
('XM1QE0', 'Derivados del benzomorfano', 'category', false, false, 'CIE-11'),
('XM9K14', 'Pentazocina', 'category', false, false, 'CIE-11'),
('XM09R6', 'Derivados de morfinano', 'category', false, false, 'CIE-11'),
('XM1682', 'Butorfanol', 'category', false, false, 'CIE-11'),
('XM4P05', 'Nalbufina', 'category', false, false, 'CIE-11'),
('XM9Z94', 'Buprenorfina', 'category', false, false, 'CIE-11'),
('XM02X7', 'Etorfina', 'category', false, false, 'CIE-11'),
('XM3PK7', 'Acetorfina', 'category', false, false, 'CIE-11'),
('XM0K66', 'Fenopiridina', 'category', false, false, 'CIE-11'),
('XM40T9', 'Meptazinol', 'category', false, false, 'CIE-11'),
('XM0GU8', 'Drotebanol', 'category', false, false, 'CIE-11'),
('XM7VK6', 'Óxido de loperamida', 'category', false, false, 'CIE-11'),
('XM13Q9', 'Dezocina', 'category', false, false, 'CIE-11'),
('XM25Z3', 'Tapentadol', 'category', false, false, 'CIE-11'),
('XM1G85', 'Oliceridina', 'category', false, false, 'CIE-11'),
('XM4PD9', 'Nalmefeno', 'category', false, false, 'CIE-11'),
('XM4M74', 'Difelikefalin', 'category', false, false, 'CIE-11'),
('XM0VG7', 'Catha (edulis) (té)', 'category', false, false, 'CIE-11'),
('XM0238', 'Khat', 'category', false, false, 'CIE-11'),
('XM3GQ0', 'Estimulantes del sistema nervioso central, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XM0854', 'Estimulantes cerebrales psicoterapeúticos', 'category', false, false, 'CIE-11'),
('XM93X4', 'Estimulantes cerebrales', 'category', false, false, 'CIE-11'),
('XM7125', 'Estimulantes psicoterapeúticos del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM8T75', 'Anestésicos inhalados', 'category', false, false, 'CIE-11'),
('XM4VX3', 'Éteres', 'category', false, false, 'CIE-11'),
('XM3J00', 'Éter dietílico', 'category', false, false, 'CIE-11'),
('XM7UB3', 'Éter vinílico', 'category', false, false, 'CIE-11'),
('XM0TE1', 'Hidrocarburos halogenados', 'category', false, false, 'CIE-11'),
('XM2FH0', 'Halotano', 'category', false, false, 'CIE-11'),
('XM7MX5', 'Cloroformo', 'category', false, false, 'CIE-11'),
('XM1GP5', 'Vapor de cloroformo', 'category', false, false, 'CIE-11'),
('XM35M6', 'Enflurano', 'category', false, false, 'CIE-11'),
('XM1E91', 'Gas anestésico de tricloroetileno', 'category', false, false, 'CIE-11'),
('XM9HY9', 'Isoflurano', 'category', false, false, 'CIE-11'),
('XM0ZA2', 'Anestesia endotraqueal', 'category', false, false, 'CIE-11'),
('XM05Z8', 'Anestésico gaseoso', 'category', false, false, 'CIE-11'),
('XM8V73', 'Anestésicos derivados de hidrocarburos halogenados', 'category', false, false, 'CIE-11'),
('XM5UK1', 'Gases anestésicos depresores del sistema nervioso central.', 'category', false, false, 'CIE-11'),
('XM42D4', 'Anestésico cloroformo', 'category', false, false, 'CIE-11'),
('XM2DK4', 'Agua de cloroformo, concentrada', 'category', false, false, 'CIE-11'),
('XM9TE3', 'Divinil éter', 'category', false, false, 'CIE-11'),
('XM3EA4', 'Anestésico bromuro de etilo', 'category', false, false, 'CIE-11'),
('XM2D90', 'Anestésico cloruro de etilo', 'category', false, false, 'CIE-11'),
('XM6WF0', 'Anestésico etileno', 'category', false, false, 'CIE-11'),
('XM9K99', 'Fluroxeno', 'category', false, false, 'CIE-11'),
('XM73B5', 'Óxido nitroso', 'category', false, false, 'CIE-11'),
('XM9NP2', 'Trifluoroetil vinil éter', 'category', false, false, 'CIE-11'),
('XM7Q24', 'Vinesteno', 'category', false, false, 'CIE-11'),
('XM1C44', 'Desflurano', 'category', false, false, 'CIE-11'),
('XM07G7', 'Sevoflurano', 'category', false, false, 'CIE-11'),
('XM8X62', 'Xenon', 'category', false, false, 'CIE-11'),
('XM7D47', 'Anestésicos intravenosos', 'category', false, false, 'CIE-11'),
('XM14F2', 'Alfadolona', 'category', false, false, 'CIE-11'),
('XM4PF7', 'Alfaxalona', 'category', false, false, 'CIE-11'),
('XM59B1', 'Anestésicos barbitúricos, intravenosos', 'category', false, false, 'CIE-11'),
('XM9CB4', 'Brevital sodio', 'category', false, false, 'CIE-11'),
('XM6LE6', 'Butalitone sodio', 'category', false, false, 'CIE-11'),
('XM5K69', 'Butil tiobarbital sódico', 'category', false, false, 'CIE-11'),
('XM9SR9', 'Anestésicos depresores del sistema nervioso central, intravenosos', 'category', false, false, 'CIE-11'),
('XM5MB2', 'Etomidato', 'category', false, false, 'CIE-11'),
('XM93E9', 'Evipal sódico', 'category', false, false, 'CIE-11'),
('XM5ZF4', 'Sernil', 'category', false, false, 'CIE-11'),
('XM4XN0', 'Tialbarbital', 'category', false, false, 'CIE-11'),
('XM66H8', 'Tiamilal', 'category', false, false, 'CIE-11'),
('XM8UK0', 'Tiamilal sodico', 'category', false, false, 'CIE-11'),
('XM4NL3', 'Tiobarbital sodico', 'category', false, false, 'CIE-11'),
('XM1QW9', 'Anestésico tiobarbiturato', 'category', false, false, 'CIE-11'),
('XM72F2', 'Tiobutabarbital sodico', 'category', false, false, 'CIE-11'),
('XM7JR4', 'Metohexital', 'category', false, false, 'CIE-11'),
('XM08U4', 'Hexobarbital', 'category', false, false, 'CIE-11'),
('XM0EL8', 'Tiopental sódico', 'category', false, false, 'CIE-11'),
('XM7C11', 'Ketamina', 'category', false, false, 'CIE-11'),
('XM4BS0', 'Propanidid', 'category', false, false, 'CIE-11'),
('XM1903', 'Propofol', 'category', false, false, 'CIE-11'),
('XM2W08', 'Esketamina', 'category', false, false, 'CIE-11'),
('XM7T11', 'Ciclopropano', 'category', false, false, 'CIE-11'),
('XM9MS5', 'Gammahidroxibutirato', 'category', false, false, 'CIE-11'),
('XM5C03', 'Hexobarbital rectal', 'category', false, false, 'CIE-11'),
('XM20X3', 'Minaxolona', 'category', false, false, 'CIE-11'),
('XM2MR8', 'Tiletamina', 'category', false, false, 'CIE-11'),
('XM8DR0', 'Tribromoetanol rectal', 'category', false, false, 'CIE-11'),
('XM7Y85', 'Anestésicos locales', 'category', false, false, 'CIE-11'),
('XM1FJ6', 'Amilocaína, regional', 'category', false, false, 'CIE-11'),
('XM1H49', 'Amilocaína, infiltración regional', 'category', false, false, 'CIE-11'),
('XM7CH6', 'Amilocaína, bloqueo nervioso regional', 'category', false, false, 'CIE-11'),
('XM37J6', 'Amilocaína, espinal regional', 'category', false, false, 'CIE-11'),
('XM5JY6', 'Amilocaína, tópica regional', 'category', false, false, 'CIE-11'),
('XM5R82', 'Anestesia, caudal', 'category', false, false, 'CIE-11'),
('XM8MY3', 'Anestesia, epidural', 'category', false, false, 'CIE-11'),
('XM25C7', 'Anestesia de la mucosa', 'category', false, false, 'CIE-11'),
('XM0D14', 'Anestesia rectal local', 'category', false, false, 'CIE-11'),
('XM0FJ3', 'Anestesia regional', 'category', false, false, 'CIE-11'),
('XM0LM0', 'Infiltración anestésica', 'category', false, false, 'CIE-11'),
('XM7EC3', 'Anestesia espinal', 'category', false, false, 'CIE-11'),
('XM8E23', 'Anestésico tópico', 'category', false, false, 'CIE-11'),
('XM3S41', 'Anestésico con relajante muscular local', 'category', false, false, 'CIE-11'),
('XM5ZK7', 'Aptocaína', 'category', false, false, 'CIE-11'),
('XM52S4', 'Articaína', 'category', false, false, 'CIE-11'),
('XM4YN0', 'Benzamina', 'category', false, false, 'CIE-11'),
('XM8KD9', 'Benzocaína', 'category', false, false, 'CIE-11'),
('XM1604', 'Betoxicaína', 'category', false, false, 'CIE-11'),
('XM5YL1', 'Bupivacaína', 'category', false, false, 'CIE-11'),
('XM7WQ7', 'Infiltración con bupivacaína', 'category', false, false, 'CIE-11'),
('XM4216', 'Bloqueo de nervio con bupivacaína', 'category', false, false, 'CIE-11'),
('XM46M2', 'Bupivacaína espinal', 'category', false, false, 'CIE-11'),
('XM3781', 'Butacaína', 'category', false, false, 'CIE-11'),
('XM7MD5', 'Butamben', 'category', false, false, 'CIE-11'),
('XM9VA7', 'Butanilicaína', 'category', false, false, 'CIE-11'),
('XM0HA0', 'Aminobenzoato de butilo', 'category', false, false, 'CIE-11'),
('XM5NW5', 'Butin', 'category', false, false, 'CIE-11'),
('XM2YU2', 'Infiltración con carbocaína', 'category', false, false, 'CIE-11'),
('XM8C65', 'Bloqueo nervioso con carbocaína', 'category', false, false, 'CIE-11'),
('XM2DT1', 'Carbocaína tópica', 'category', false, false, 'CIE-11'),
('XM6HZ0', 'Cloroprocaína', 'category', false, false, 'CIE-11'),
('XM8XD3', 'Infiltración de cloroprocaína', 'category', false, false, 'CIE-11'),
('XM0GC2', 'Bloqueo nervioso con cloroprocaína', 'category', false, false, 'CIE-11'),
('XM94U2', 'Cloroprocaína espinal', 'category', false, false, 'CIE-11'),
('XM0L28', 'Cincocaína', 'category', false, false, 'CIE-11'),
('XM5Y10', 'Cincocaína tópica', 'category', false, false, 'CIE-11'),
('XM7FD6', 'Ciclaína', 'category', false, false, 'CIE-11'),
('XM41W7', 'Ciclometicaína', 'category', false, false, 'CIE-11'),
('XM3BB4', 'Dimetocaína', 'category', false, false, 'CIE-11'),
('XM8UZ3', 'Diperodona', 'category', false, false, 'CIE-11'),
('XM23R3', 'Dorsacaína', 'category', false, false, 'CIE-11'),
('XM5601', 'Diclona', 'category', false, false, 'CIE-11'),
('XM3QB4', 'Diclonina', 'category', false, false, 'CIE-11'),
('XM20M0', 'Endocaína', 'category', false, false, 'CIE-11'),
('XM0P92', 'EPAB', 'category', false, false, 'CIE-11'),
('XM2H77', 'Infiltración con etocaína', 'category', false, false, 'CIE-11'),
('XM6585', 'Bloqueo de nervio con etocaína', 'category', false, false, 'CIE-11'),
('XM7217', 'Etocaína espinal', 'category', false, false, 'CIE-11'),
('XM1WJ3', 'Aminobenzoato de etilo', 'category', false, false, 'CIE-11'),
('XM87H9', 'Cloruro de etilo como anestésico local', 'category', false, false, 'CIE-11'),
('XM8X57', 'Etidocaína', 'category', false, false, 'CIE-11'),
('XM8013', 'Infiltración con etidocaína', 'category', false, false, 'CIE-11'),
('XM8RU6', 'Bloqueo de nervio con etidocaína', 'category', false, false, 'CIE-11'),
('XM2F20', 'Eucaína', 'category', false, false, 'CIE-11'),
('XM76M6', 'Hexilcaína', 'category', false, false, 'CIE-11'),
('XM5863', 'Leucinocaína', 'category', false, false, 'CIE-11'),
('XM1MK4', 'Mepivacaina', 'category', false, false, 'CIE-11'),
('XM0EH7', 'Mepivacaína epidural', 'category', false, false, 'CIE-11'),
('XM9DE9', 'Meprilcaina', 'category', false, false, 'CIE-11'),
('XM7CG8', 'Metabutetamina', 'category', false, false, 'CIE-11'),
('XM68T6', 'Nesacaina', 'category', false, false, 'CIE-11'),
('XM6AA0', 'Infiltración con nesacaína', 'category', false, false, 'CIE-11'),
('XM4148', 'Bloqueo del nervio con nesacaína', 'category', false, false, 'CIE-11'),
('XM38C9', 'Novocaína infiltrada', 'category', false, false, 'CIE-11'),
('XM6R58', 'Novocaína tópica', 'category', false, false, 'CIE-11'),
('XM6NN7', 'Nupercaína, espinal', 'category', false, false, 'CIE-11'),
('XM8739', 'Nupercaína tópica', 'category', false, false, 'CIE-11'),
('XM0QU2', 'Ortocaina', 'category', false, false, 'CIE-11'),
('XM5HP0', 'Oxetacaina', 'category', false, false, 'CIE-11'),
('XM6V01', 'Oxetazina', 'category', false, false, 'CIE-11'),
('XM6RN9', 'Oxibuprocaina', 'category', false, false, 'CIE-11'),
('XM7H65', 'Percaína, espinal', 'category', false, false, 'CIE-11'),
('XM7EK6', 'Percaína tópica', 'category', false, false, 'CIE-11'),
('XM6Z26', 'Fenacaina', 'category', false, false, 'CIE-11'),
('XM2ZH3', 'Piperocaina', 'category', false, false, 'CIE-11'),
('XM7UW6', 'Piperocaína por infiltración', 'category', false, false, 'CIE-11'),
('XM8J09', 'Bloqueo de nervio con piperocaína', 'category', false, false, 'CIE-11'),
('XM40M8', 'Piperocaína tópica', 'category', false, false, 'CIE-11'),
('XM8AE6', 'Solución de Pitkin', 'category', false, false, 'CIE-11'),
('XM2X66', 'Prilocaina', 'category', false, false, 'CIE-11'),
('XM9NH0', 'Prilocaína por infiltración', 'category', false, false, 'CIE-11'),
('XM85Q7', 'Bloqueo de nervio con prilocaína', 'category', false, false, 'CIE-11'),
('XM4EE1', 'Prilocaína regional', 'category', false, false, 'CIE-11'),
('XM5L66', 'Procaina', 'category', false, false, 'CIE-11'),
('XM05Z5', 'Bloqueo de nervio con procaína', 'category', false, false, 'CIE-11'),
('XM1CG3', 'Procaína regional', 'category', false, false, 'CIE-11'),
('XM8KS3', 'Procaína espinal', 'category', false, false, 'CIE-11'),
('XM97J9', 'Proparacaina', 'category', false, false, 'CIE-11'),
('XM72A2', 'Propoxicaina', 'category', false, false, 'CIE-11'),
('XM9BY7', 'Propoxicaína por infiltración', 'category', false, false, 'CIE-11'),
('XM2DT4', 'Bloqueo de nervio con propoxicaína', 'category', false, false, 'CIE-11'),
('XM0BG4', 'Propoxicaína tópica', 'category', false, false, 'CIE-11'),
('XM87E0', 'Quotane', 'category', false, false, 'CIE-11'),
('XM2MX6', 'Estovaina', 'category', false, false, 'CIE-11'),
('XM79W4', 'Estovaína por infiltración (subcutánea)', 'category', false, false, 'CIE-11'),
('XM08B5', 'Bloqueo delnervio con estovaína', 'category', false, false, 'CIE-11'),
('XM9657', 'Estovaína espinal', 'category', false, false, 'CIE-11'),
('XM3MW8', 'Estovaína tópica', 'category', false, false, 'CIE-11'),
('XM6392', 'Surfacaina', 'category', false, false, 'CIE-11'),
('XM1HW1', 'Tetracaina', 'category', false, false, 'CIE-11'),
('XM32E4', 'Bloqueo de nervio con tetracaína', 'category', false, false, 'CIE-11'),
('XM9H96', 'Tetracaína regional', 'category', false, false, 'CIE-11'),
('XM9CQ9', 'Tetracaína espinal', 'category', false, false, 'CIE-11'),
('XM3QD1', 'Trimecaina', 'category', false, false, 'CIE-11'),
('XM2FR2', 'Tronotano', 'category', false, false, 'CIE-11'),
('XM7771', 'Xylocaina por infiltración', 'category', false, false, 'CIE-11'),
('XM18M2', 'Bloqueo de nervio con xilocaína', 'category', false, false, 'CIE-11'),
('XM5K48', 'Xylocaina espinal', 'category', false, false, 'CIE-11'),
('XM5G11', 'Xilocaína tópica', 'category', false, false, 'CIE-11'),
('XM1030', 'Alprazolan', 'category', false, false, 'CIE-11'),
('XM4R58', 'Bentazepam', 'category', false, false, 'CIE-11'),
('XM2GL0', 'Benzodiapina', 'category', false, false, 'CIE-11'),
('XM9JC7', 'Bromazepan', 'category', false, false, 'CIE-11'),
('XM2S43', 'Brotizolam', 'category', false, false, 'CIE-11'),
('XM5133', 'Camazepam', 'category', false, false, 'CIE-11'),
('XM9S41', 'Carpipramina', 'category', false, false, 'CIE-11'),
('XM1J81', 'Benzodiacepinas depresoras del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM5JC4', 'Clordiazepoxido', 'category', false, false, 'CIE-11'),
('XM43U0', 'Clobazam', 'category', false, false, 'CIE-11'),
('XM3C29', 'Clorazepato dipotásico', 'category', false, false, 'CIE-11'),
('XM0A75', 'Clotiazepam', 'category', false, false, 'CIE-11'),
('XM5M11', 'Cloxazolam', 'category', false, false, 'CIE-11'),
('XM0GD3', 'Delorazepam', 'category', false, false, 'CIE-11'),
('XM8P99', 'Diazepam', 'category', false, false, 'CIE-11'),
('XM9YX9', 'Estazolam', 'category', false, false, 'CIE-11'),
('XM54N1', 'Loflazepato de etilo', 'category', false, false, 'CIE-11'),
('XM9DN9', 'Etizolam', 'category', false, false, 'CIE-11'),
('XM8NC2', 'Fludiazepam', 'category', false, false, 'CIE-11'),
('XM9W71', 'Flunitrazepam', 'category', false, false, 'CIE-11'),
('XM73H1', 'Flurazepam', 'category', false, false, 'CIE-11'),
('XM68Z6', 'Flutazolam', 'category', false, false, 'CIE-11'),
('XM81V7', 'Flutoprazepam', 'category', false, false, 'CIE-11'),
('XM3FR2', 'Halazepam', 'category', false, false, 'CIE-11'),
('XM86G3', 'Haloxazolam', 'category', false, false, 'CIE-11'),
('XM5WE7', 'Ketazolam', 'category', false, false, 'CIE-11'),
('XM6KW2', 'Loprazolam', 'category', false, false, 'CIE-11'),
('XM85H7', 'Lorazepam', 'category', false, false, 'CIE-11'),
('XM1EE3', 'Lormetazepam', 'category', false, false, 'CIE-11'),
('XM9KN4', 'Medazepam', 'category', false, false, 'CIE-11'),
('XM7QC1', 'Mexazolam', 'category', false, false, 'CIE-11'),
('XM9PG6', 'Midazolan', 'category', false, false, 'CIE-11'),
('XM8TH1', 'Nimetazepam', 'category', false, false, 'CIE-11'),
('XM4TR7', 'Nitrazepam', 'category', false, false, 'CIE-11'),
('XM4FQ9', 'Nordazepam', 'category', false, false, 'CIE-11'),
('XM1A29', 'Oxazepam', 'category', false, false, 'CIE-11'),
('XM62U2', 'Oxazolam', 'category', false, false, 'CIE-11'),
('XM3LR9', 'Perlapine', 'category', false, false, 'CIE-11'),
('XM0GW7', 'Pinazepam', 'category', false, false, 'CIE-11'),
('XM4M86', 'Prazepam', 'category', false, false, 'CIE-11'),
('XM42F4', 'Quazepam', 'category', false, false, 'CIE-11'),
('XM3215', 'Temazepam', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
