-- CIE11 Import Part 52
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XE23P', 'Bate, palo de hockey', 'category', false, false, 'CIE-11'),
('XE9MP', 'Raqueta', 'category', false, false, 'CIE-11'),
('XE1HX', 'Picahielo', 'category', false, false, 'CIE-11'),
('XE0AQ', 'Equipamiento o estructura para practicar deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE2EM', 'Red para deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE9R3', 'Poste de rugby, poste de red, poste de meta (arco)', 'category', false, false, 'CIE-11'),
('XE6HE', 'Trampolín para practicar deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE8C0', 'Equipamiento de gimnasia', 'category', false, false, 'CIE-11'),
('XE76Q', 'Colchoneta de deportes para jugar deportes o ejercicio,', 'category', false, false, 'CIE-11'),
('XE9TW', 'Tabla de buceo, plataforma', 'category', false, false, 'CIE-11'),
('XE1EH', 'Ejercicio, equipamiento de fitness - móvil', 'category', false, false, 'CIE-11'),
('XE6G9', 'Aparatos de gimnasia, ejercicios - fijos (portátiles)', 'category', false, false, 'CIE-11'),
('XE70Q', 'Equipamiento con ruedas o diseñados para movimiento, principalmente para uso en deportes o actividad recreativa', 'category', false, false, 'CIE-11'),
('XE38Q', 'Patines de ruedas, esquís de rodillos, patines en línea, patines de cuchilla', 'category', false, false, 'CIE-11'),
('XE7TJ', 'Monopatín', 'category', false, false, 'CIE-11'),
('XE06X', 'Scooter plegable', 'category', false, false, 'CIE-11'),
('XE9XZ', 'Esquí acuático', 'category', false, false, 'CIE-11'),
('XE5W5', 'Esquí de nieve', 'category', false, false, 'CIE-11'),
('XE6DZ', 'Tabla de nieve', 'category', false, false, 'CIE-11'),
('XE2AY', 'Patín de hielo', 'category', false, false, 'CIE-11'),
('XE0AR', 'Deslizador, tobogán, trineo, disco de nieve, gomón de nieve', 'category', false, false, 'CIE-11'),
('XE9TA', 'Equipo de submarinismo', 'category', false, false, 'CIE-11'),
('XE1WX', 'Escafandra autónoma', 'category', false, false, 'CIE-11'),
('XE85D', 'Cinturón de buceo, pesa', 'category', false, false, 'CIE-11'),
('XE8X8', 'Traje de neopreno', 'category', false, false, 'CIE-11'),
('XE3NW', 'Gafas o máscara, ala o aleta, tubo respirador', 'category', false, false, 'CIE-11'),
('XE8FX', 'Ciertos equipamiento especificado para deportes o actividad recreacional', 'category', false, false, 'CIE-11'),
('XE92X', 'Equipo de protección personal (EPP) diseñado para el uso en deportes', 'category', false, false, 'CIE-11'),
('XE0P3', 'Herramienta, máquina, aparatos usados principalmente para trabajos relacionados con la actividad', 'category', false, false, 'CIE-11'),
('XE6TZ', 'Maquinaria o planta fija', 'category', false, false, 'CIE-11'),
('XE43P', 'Maquina cortadora o rebanadora o planta fija', 'category', false, false, 'CIE-11'),
('XE0VT', 'Máquinaria trituradora o de prensado o planta fija', 'category', false, false, 'CIE-11'),
('XE1WC', 'Maquinaria de calefacción o cocción o planta fija', 'category', false, false, 'CIE-11'),
('XE76C', 'Planta fija o maquinaria de refrigeración', 'category', false, false, 'CIE-11'),
('XE14G', 'Maquinaria de elevación', 'category', false, false, 'CIE-11'),
('XE77A', 'Maquinaria para izar', 'category', false, false, 'CIE-11'),
('XE3BT', 'Maquinaria grúa o planta fija', 'category', false, false, 'CIE-11'),
('XE9U1', 'Plataforma de trabajo elevada', 'category', false, false, 'CIE-11'),
('XE6T6', 'Transportadoras', 'category', false, false, 'CIE-11'),
('XE99N', 'Redes-gas, agua, alcantarillado, vapor, agua caliente,|electricidad', 'category', false, false, 'CIE-11'),
('XE8FD', 'Planta de cizallamiento', 'category', false, false, 'CIE-11'),
('XE6VH', 'Lechería o planta de ordeño', 'category', false, false, 'CIE-11'),
('XE6AF', 'Prensa', 'category', false, false, 'CIE-11'),
('XE0JX', 'Compactador de basura', 'category', false, false, 'CIE-11'),
('XE02Q', 'Máquina trilladora', 'category', false, false, 'CIE-11'),
('XE8KN', 'Cortadora de bagazo, cortadora de forraje', 'category', false, false, 'CIE-11'),
('XE5WX', 'Equipamiento o herramienta manual motorizada', 'category', false, false, 'CIE-11'),
('XE88U', 'Taladro', 'category', false, false, 'CIE-11'),
('XE8MJ', 'Motosierra', 'category', false, false, 'CIE-11'),
('XE66P', 'Otra sierra eléctrica', 'category', false, false, 'CIE-11'),
('XE0TD', 'Soldador, equipo de soldadura', 'category', false, false, 'CIE-11'),
('XE3E3', 'Pistola de clavos, remachador', 'category', false, false, 'CIE-11'),
('XE3UP', 'Amoladora, amortiguador, pulidor, lijadora', 'category', false, false, 'CIE-11'),
('XE8T6', 'Herramienta de jardín motorizada', 'category', false, false, 'CIE-11'),
('XE89A', 'Cortacésped con empuje motorizado', 'category', false, false, 'CIE-11'),
('XE0N1', 'Aspiradora industrial', 'category', false, false, 'CIE-11'),
('XE16F', 'Equipamiento o herramienta manual sin motor', 'category', false, false, 'CIE-11'),
('XE8P1', 'Cortadora de césped de empuje sin motor', 'category', false, false, 'CIE-11'),
('XE0VV', 'Martillo, maza', 'category', false, false, 'CIE-11'),
('XE56E', 'Herramienta de corte', 'category', false, false, 'CIE-11'),
('XE9CU', 'Herramientas de corte', 'category', false, false, 'CIE-11'),
('XE9GT', 'Herramienta para labrar o excavar', 'category', false, false, 'CIE-11'),
('XE3KL', 'Herramienta de elevación', 'category', false, false, 'CIE-11'),
('XE7VR', 'Clavo, tornillo, tachuela', 'category', false, false, 'CIE-11'),
('XE3W7', 'Anzuelo utilizado para actividades relacionadas con el trabajo', 'category', false, false, 'CIE-11'),
('XE8KL', 'Trampa de rata o ratón utilizada para actividades relacionadas con el trabajo', 'category', false, false, 'CIE-11'),
('XE9N7', 'Equipo basado en la presión', 'category', false, false, 'CIE-11'),
('XE5VQ', 'Cilindro de gas', 'category', false, false, 'CIE-11'),
('XE974', 'Manguera presurizada, tubería', 'category', false, false, 'CIE-11'),
('XE3RZ', 'Cierto equipamiento sin motor', 'category', false, false, 'CIE-11'),
('XE9P7', 'Escalera, paso movible', 'category', false, false, 'CIE-11'),
('XE7RK', 'Andamio', 'category', false, false, 'CIE-11'),
('XE5F6', 'Casco', 'category', false, false, 'CIE-11'),
('XE67K', 'Tapones para los aídos', 'category', false, false, 'CIE-11'),
('XE2PS', 'Máscara de soldadura', 'category', false, false, 'CIE-11'),
('XE7RJ', 'Equipo de protección personal, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE7HB', 'Extintor de incendios', 'category', false, false, 'CIE-11'),
('XE505', 'Dispositivo de transmisión mecánica de potencia', 'category', false, false, 'CIE-11'),
('XE4BU', 'Objeto punzante', 'category', false, false, 'CIE-11'),
('XE3KV', 'Lanza, jabalina diseñada como arma', 'category', false, false, 'CIE-11'),
('XE9PM', 'Flecha o perno diseñado como arma', 'category', false, false, 'CIE-11'),
('XE174', 'Cuchillo diseñado como arma', 'category', false, false, 'CIE-11'),
('XE598', 'Espada, daga, bayoneta, machete, panga, cutlass', 'category', false, false, 'CIE-11'),
('XE04A', 'Arma de fuego o elemento relacionado', 'category', false, false, 'CIE-11'),
('XE4KC', 'Bala, perdigón', 'category', false, false, 'CIE-11'),
('XE72J', 'Pistola', 'category', false, false, 'CIE-11'),
('XE0Q9', 'Rifle', 'category', false, false, 'CIE-11'),
('XE32H', 'Escopeta', 'category', false, false, 'CIE-11'),
('XE6YZ', 'Pistola de aire', 'category', false, false, 'CIE-11'),
('XE1XM', 'Cierta arma especificada', 'category', false, false, 'CIE-11'),
('XE61H', 'Mazo, garrote, barra, mazo africano', 'category', false, false, 'CIE-11'),
('XE9F9', 'Productos eléctricos, pistola paralizante', 'category', false, false, 'CIE-11'),
('XE203', 'Aerosol de capsicum, mazo, aerosol de pimienta', 'category', false, false, 'CIE-11'),
('XE3C1', 'Planta', 'category', false, false, 'CIE-11'),
('XE9CV', 'Arbol, planta', 'category', false, false, 'CIE-11'),
('XE2ZX', 'Hojas, flores', 'category', false, false, 'CIE-11'),
('XE4DN', 'Setas, setas venenosas, hongos', 'category', false, false, 'CIE-11'),
('XE8XA', 'Semilla de planta', 'category', false, false, 'CIE-11'),
('XE4KB', 'Fruta de la planta', 'category', false, false, 'CIE-11'),
('XE8SV', 'Planta espinosa', 'category', false, false, 'CIE-11'),
('XE50M', 'Rama o palo separado de la rama o árbol', 'category', false, false, 'CIE-11'),
('XE2PR', 'Planta venenosa o tóxica no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE6L5', 'Ave', 'category', false, false, 'CIE-11'),
('XE99A', 'Avestruz, emú', 'category', false, false, 'CIE-11'),
('XE69N', 'Loro, perico, cacatúa', 'category', false, false, 'CIE-11'),
('XE1Q3', 'Cuervo, grajo, urraca', 'category', false, false, 'CIE-11'),
('XE6UV', 'Insecto, invertebrado', 'category', false, false, 'CIE-11'),
('XE4D9', 'Abeja', 'category', false, false, 'CIE-11'),
('XE6LT', 'Avispa', 'category', false, false, 'CIE-11'),
('XE322', 'Avispón', 'category', false, false, 'CIE-11'),
('XE7WQ', 'Avispón amarillo', 'category', false, false, 'CIE-11'),
('XE7TV', 'Avispón cara blanca', 'category', false, false, 'CIE-11'),
('XE4YS', 'Hormiga', 'category', false, false, 'CIE-11'),
('XE75L', 'Araña', 'category', false, false, 'CIE-11'),
('XE2EP', 'Escorpión', 'category', false, false, 'CIE-11'),
('XE779', 'garrapata', 'category', false, false, 'CIE-11'),
('XE11M', 'Cienpies, milpies', 'category', false, false, 'CIE-11'),
('XM6QA5', 'Cochinilla', 'category', false, false, 'CIE-11'),
('XE813', 'Mamífero terrestre', 'category', false, false, 'CIE-11'),
('XE33Q', 'Perro', 'category', false, false, 'CIE-11'),
('XE0W5', 'Caspa de perro', 'category', false, false, 'CIE-11'),
('XE3GM', 'Epitelio del perro', 'category', false, false, 'CIE-11'),
('XE4V0', 'Gato', 'category', false, false, 'CIE-11'),
('XE896', 'Caspa de gato', 'category', false, false, 'CIE-11'),
('XE8X3', 'Rata, conejillo de indias, ratón', 'category', false, false, 'CIE-11'),
('XE3UD', 'Cerdo, jabalí', 'category', false, false, 'CIE-11'),
('XE25P', 'Oveja, cabra', 'category', false, false, 'CIE-11'),
('XE257', 'Vaca, toro, animales bovinos', 'category', false, false, 'CIE-11'),
('XE1LR', 'Carne de res', 'category', false, false, 'CIE-11'),
('XE5NG', 'Caspa de vaca', 'category', false, false, 'CIE-11'),
('XE5VC', 'Caballo, poni, burro, mula,asno', 'category', false, false, 'CIE-11'),
('XE7NS', 'Babuino, mono, chimpancé, gorila', 'category', false, false, 'CIE-11'),
('XE4TZ', 'Marsupiales', 'category', false, false, 'CIE-11'),
('XE1MH', 'Ciervo, alce, antílope, cebra, ñu', 'category', false, false, 'CIE-11'),
('XE37L', 'Hipopótamo', 'category', false, false, 'CIE-11'),
('XE82S', 'León, pantera, puma, león de montaña, tigre', 'category', false, false, 'CIE-11'),
('XE7UA', 'Oso, oso pardo, oso polar', 'category', false, false, 'CIE-11'),
('XE2Q6', 'Elefante', 'category', false, false, 'CIE-11'),
('XE96F', 'Búfalo, , bisonte, búfalo Africano', 'category', false, false, 'CIE-11'),
('XE08V', 'Epitelio de hámster', 'category', false, false, 'CIE-11'),
('XE09T', 'Caspa de caballo', 'category', false, false, 'CIE-11'),
('XE7CQ', 'Epitelio de raton', 'category', false, false, 'CIE-11'),
('XE43Q', 'Proteínas de orina de ratón', 'category', false, false, 'CIE-11'),
('XE7TQ', 'Epitelio de conejo', 'category', false, false, 'CIE-11'),
('XE9BL', 'Cerdo', 'category', false, false, 'CIE-11'),
('XE6T4', 'Mejillón azul', 'category', false, false, 'CIE-11'),
('XE6WA', 'Callo de hacha', 'category', false, false, 'CIE-11'),
('XE5ZB', 'Epitelio de cobaya', 'category', false, false, 'CIE-11'),
('XE2AH', 'Animal marino', 'category', false, false, 'CIE-11'),
('XE765', 'Tiburón', 'category', false, false, 'CIE-11'),
('XE71F', 'Otros peces', 'category', false, false, 'CIE-11'),
('XE48L', 'Serpiente de mar', 'category', false, false, 'CIE-11'),
('XE3UQ', 'Mamífero marino', 'category', false, false, 'CIE-11'),
('XE8BW', 'Medusa', 'category', false, false, 'CIE-11'),
('XE40R', 'Nematocistos', 'category', false, false, 'CIE-11'),
('XE75E', 'Coral', 'category', false, false, 'CIE-11'),
('XE6ZA', 'Erizo de mar', 'category', false, false, 'CIE-11'),
('XE45C', 'Anemona de mar', 'category', false, false, 'CIE-11'),
('XE43L', 'Pepino de mar', 'category', false, false, 'CIE-11'),
('XE1PT', 'Reptil o anfibio', 'category', false, false, 'CIE-11'),
('XE44L', 'Víbora no venenosa', 'category', false, false, 'CIE-11'),
('XE9H6', 'Serpiente venenosa', 'category', false, false, 'CIE-11'),
('XE9X2', 'Cobra', 'category', false, false, 'CIE-11'),
('XE5N3', 'Serpiente de terciopelo', 'category', false, false, 'CIE-11'),
('XE2RM', 'Serpiente de cascabel', 'category', false, false, 'CIE-11'),
('XE8LD', 'Víbora', 'category', false, false, 'CIE-11'),
('XE2UZ', 'Bungaro', 'category', false, false, 'CIE-11'),
('XE11V', 'Serpiente no especificada si es venenosa o no', 'category', false, false, 'CIE-11'),
('XE6A7', 'Lagarto, geco, iguana', 'category', false, false, 'CIE-11'),
('XE65X', 'Monstruo de Gila', 'category', false, false, 'CIE-11'),
('XE4YK', 'Sapo, rana', 'category', false, false, 'CIE-11'),
('XE4FD', 'Cocodrilo, caimán', 'category', false, false, 'CIE-11'),
('XE653', 'Persona', 'category', false, false, 'CIE-11'),
('XE70B', 'Persona, sí mismo', 'category', false, false, 'CIE-11'),
('XE0TZ', 'Multitud de personas', 'category', false, false, 'CIE-11'),
('XE1P6', 'Edificio adecuado', 'category', false, false, 'CIE-11'),
('XE766', 'Inodoro', 'category', false, false, 'CIE-11'),
('XE429', 'Letrina de pozo', 'category', false, false, 'CIE-11'),
('XE2C6', 'Bañera, bañera de hidromasaje, cubículo de ducha', 'category', false, false, 'CIE-11'),
('XE78X', 'Bañera', 'category', false, false, 'CIE-11'),
('XE5T1', 'Bañera de hidromasaje', 'category', false, false, 'CIE-11'),
('XE5RW', 'Cabina con regadera', 'category', false, false, 'CIE-11'),
('XE31Q', 'Ducha', 'category', false, false, 'CIE-11'),
('XE8P0', 'Mostrador empotrado, encimera, encimera de cocina', 'category', false, false, 'CIE-11'),
('XE2AC', 'Puerta, ventana, característica o propósito relacionado', 'category', false, false, 'CIE-11'),
('XE68A', 'Puerta, alfeizar de la puerta', 'category', false, false, 'CIE-11'),
('XE4YT', 'Puerta de vidrio', 'category', false, false, 'CIE-11'),
('XE4NX', 'Puerta o salida de seguridad, puerta de escape', 'category', false, false, 'CIE-11'),
('XE6FE', 'Barras en las ventanas', 'category', false, false, 'CIE-11'),
('XE4BD', 'Ventana', 'category', false, false, 'CIE-11'),
('XE5B1', 'Contraventanas (postigos) exteriores', 'category', false, false, 'CIE-11'),
('XE7SG', 'Piso o accesorio o característica relacionada', 'category', false, false, 'CIE-11'),
('XE0SK', 'Piso - alfombrado', 'category', false, false, 'CIE-11'),
('XE19Z', 'Piso - azulejo, ladrillo, hormigón', 'category', false, false, 'CIE-11'),
('XE6M6', 'Piso - de madera', 'category', false, false, 'CIE-11'),
('XE6ZE', 'Piso - adobe, arcilla, estiércol de animal', 'category', false, false, 'CIE-11'),
('XE4ZE', 'Pared o accesorio o característica relacionada', 'category', false, false, 'CIE-11'),
('XE19W', 'Chimenea', 'category', false, false, 'CIE-11'),
('XE1B2', 'Parrilla incorporada', 'category', false, false, 'CIE-11'),
('XE0WS', 'Pared - ladrillo, hormigón, azulejo', 'category', false, false, 'CIE-11'),
('XE7CH', 'Pared - madera', 'category', false, false, 'CIE-11'),
('XE3GJ', 'Wall - mud, clay, animal dung', 'category', false, false, 'CIE-11'),
('XE3PF', 'Cierto edificio específico, componente de construcción o accesorio', 'category', false, false, 'CIE-11'),
('XE39L', 'Piscina en terreno', 'category', false, false, 'CIE-11'),
('XE4PB', 'Piscina sobre el suelo, spa externo o bañera de hidromasaje', 'category', false, false, 'CIE-11'),
('XE5PL', 'Piscina sobre el suelo', 'category', false, false, 'CIE-11'),
('XE3PX', 'spa externo', 'category', false, false, 'CIE-11'),
('XE8AX', 'Jacuzzi externo', 'category', false, false, 'CIE-11'),
('XE7FP', 'Puerta de la cerca', 'category', false, false, 'CIE-11'),
('XE3BP', 'Cerca', 'category', false, false, 'CIE-11'),
('XE3GT', 'Puerta', 'category', false, false, 'CIE-11'),
('XE9QW', 'Rampa móvil, escalera mecánica', 'category', false, false, 'CIE-11'),
('XE0KF', 'Rampa móvil', 'category', false, false, 'CIE-11'),
('XE73T', 'Escalera mecánica', 'category', false, false, 'CIE-11'),
('XE8PC', 'Ascensor, elevador', 'category', false, false, 'CIE-11'),
('XE3HC', 'Escaleras, escalones', 'category', false, false, 'CIE-11'),
('XE2VG', 'Pasamano, baranda, barandilla', 'category', false, false, 'CIE-11'),
('XE6T1', 'Línea de transmisión eléctrica dentro o alrededor del edificio', 'category', false, false, 'CIE-11'),
('XE7UU', 'Accesorios o tuberías para gas, vapor o agua caliente', 'category', false, false, 'CIE-11'),
('XE171', 'Racores o tuberías para gas', 'category', false, false, 'CIE-11'),
('XE2BH', 'Racores o tuberías para vapor', 'category', false, false, 'CIE-11'),
('XE48P', 'Racores o tuberías para agua caliente', 'category', false, false, 'CIE-11'),
('XE871', 'Accesorio eléctrico', 'category', false, false, 'CIE-11'),
('XE9HH', 'Unidad de aire acondicionado con conductos o accesorios relacionados', 'category', false, false, 'CIE-11'),
('XE58F', 'Superficie del terreno', 'category', false, false, 'CIE-11'),
('XE1AK', 'Acantilado', 'category', false, false, 'CIE-11'),
('XE94G', 'Pendiente, rampa', 'category', false, false, 'CIE-11'),
('XE3EC', 'Trinchera, zanja, foso', 'category', false, false, 'CIE-11'),
('XE5Y0', 'alcantarilla', 'category', false, false, 'CIE-11'),
('XE2G4', 'Desagüe abierto, canal', 'category', false, false, 'CIE-11'),
('XE7K9', 'Masa de agua', 'category', false, false, 'CIE-11'),
('XE9TJ', 'Masa de agua, bien hecha por el hombre, bien cavado para aguas subterráneas', 'category', false, false, 'CIE-11'),
('XE40U', 'Masa de agua, reservorio de agua', 'category', false, false, 'CIE-11'),
('XE64D', 'Masa de agua, charco', 'category', false, false, 'CIE-11'),
('XE285', 'Masa de agua, represa, lago', 'category', false, false, 'CIE-11'),
('XE1CZ', 'Masa de agua, río , arroyo', 'category', false, false, 'CIE-11'),
('XE57J', 'Masa de agua, pantano, ciénaga, estuario', 'category', false, false, 'CIE-11'),
('XE636', 'Masa de agua, playa, costa', 'category', false, false, 'CIE-11'),
('XE5N4', 'Masa de agua, mar abierto', 'category', false, false, 'CIE-11'),
('XE0CX', 'Masa de agua, agua de inundación', 'category', false, false, 'CIE-11'),
('XE2QX', 'Masa de agua, canal, o canal de irrigación', 'category', false, false, 'CIE-11'),
('XE7CY', 'Cierta conformación de superficie especificada', 'category', false, false, 'CIE-11'),
('XE45P', 'Superficie inclinada, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE9CC', 'Superficie uniforme, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE1DA', 'Superficie irregular, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE4BY', 'Material natural', 'category', false, false, 'CIE-11'),
('XE3LV', 'Nieve, hielo,', 'category', false, false, 'CIE-11'),
('XE233', 'Hierba natural', 'category', false, false, 'CIE-11'),
('XE83R', 'Roca, piedra, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE2JN', 'Madera - viga, tabla, astilla, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE9D4', 'Grava, tierra, arena, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XE36E', 'Heno, paja', 'category', false, false, 'CIE-11'),
('XE410', 'Grano a granel', 'category', false, false, 'CIE-11'),
('XE4Y6', 'Material industrial o manufacturado', 'category', false, false, 'CIE-11'),
('XE59G', 'Césped artificial', 'category', false, false, 'CIE-11'),
('XE6MG', 'Ladrillo, hormigón, bloque de hormigón', 'category', false, false, 'CIE-11'),
('XE983', 'Metal fundido', 'category', false, false, 'CIE-11'),
('XE1FP', 'Metal- chapa, parte, pieza, etc.', 'category', false, false, 'CIE-11'),
('XE1LM', 'Cerámica vitrificada, hojas de cerámica , parte, pieza', 'category', false, false, 'CIE-11'),
('XE57U', 'Vidrio fundido', 'category', false, false, 'CIE-11'),
('XE4KU', 'Hoja de vidrio, pieza, fragmento', 'category', false, false, 'CIE-11'),
('XE7K4', 'Plástico', 'category', false, false, 'CIE-11'),
('XE63Q', 'Papel, cartón', 'category', false, false, 'CIE-11'),
('XE7CA', 'Betún', 'category', false, false, 'CIE-11'),
('XE16B', 'Material no mencionado en otra parte', 'category', false, false, 'CIE-11'),
('XE5XN', 'Textiles', 'category', false, false, 'CIE-11'),
('XE3NR', 'Fuego, llama o humo que causa lesiones', 'category', false, false, 'CIE-11'),
('XE9DT', 'Lesión causada por por llama , fuego', 'category', false, false, 'CIE-11'),
('XE7PM', 'Aceite ardiendo', 'category', false, false, 'CIE-11'),
('XE73M', 'Otro líquido ardiente', 'category', false, false, 'CIE-11'),
('XE3K6', 'Gas ardiente, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE27S', 'Fuego controlado, llama en el edificio o estructura', 'category', false, false, 'CIE-11'),
('XE7W8', 'Fuego controlado, llama, no en edificio o estructura', 'category', false, false, 'CIE-11'),
('XE87S', 'Fuego incontrolado, llama, en edificio o estructura', 'category', false, false, 'CIE-11'),
('XE7V9', 'Fuego incontrolado, llama, no en edificio o estructura', 'category', false, false, 'CIE-11'),
('XE4F3', 'Lesión causada por humo', 'category', false, false, 'CIE-11'),
('XE63H', 'Objeto o sustancia caliente no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE4VA', 'Líquido caliente', 'category', false, false, 'CIE-11'),
('XE396', 'Agua caliente del grifo', 'category', false, false, 'CIE-11'),
('XE4WG', 'Agua hirviendo que no sea agua corriente', 'category', false, false, 'CIE-11'),
('XE3BS', 'Aire caliente o gas', 'category', false, false, 'CIE-11'),
('XE77R', 'Vapor, vapor caliente', 'category', false, false, 'CIE-11'),
('XE3FD', 'Comida, bebida o producto relacionado', 'category', false, false, 'CIE-11'),
('XE5VU', 'Aceite de cocina caliente o grasa', 'category', false, false, 'CIE-11'),
('XE3KH', 'Comida sólida caliente', 'category', false, false, 'CIE-11'),
('XE36T', 'Bebida caliente', 'category', false, false, 'CIE-11'),
('XE3VM', 'Comida sólida fría', 'category', false, false, 'CIE-11'),
('XE6SF', 'Bebida fría, sin alcohol', 'category', false, false, 'CIE-11'),
('XE4QT', 'Equipos para cumplimiento de la ley', 'category', false, false, 'CIE-11'),
('XE8YS', 'Esposas', 'category', false, false, 'CIE-11'),
('XE5TH', 'Elemento de uso público', 'category', false, false, 'CIE-11'),
('XE6KX', 'Boca de incendio', 'category', false, false, 'CIE-11'),
('XE0MT', 'Poste de teléfono, poste de Stobie', 'category', false, false, 'CIE-11'),
('XE35R', 'Línea eléctrica aérea de alta tensión', 'category', false, false, 'CIE-11'),
('XE63M', 'Equipo de campamento', 'category', false, false, 'CIE-11'),
('XE14D', 'Carpa', 'category', false, false, 'CIE-11'),
('XE11D', 'Fijación, atadura o amarre de un artículo, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE4H9', 'Soga, cuerda, o torzal', 'category', false, false, 'CIE-11'),
('XE3U7', 'Alambre de púas', 'category', false, false, 'CIE-11'),
('XE1PL', 'Otro alambre', 'category', false, false, 'CIE-11'),
('XE18Y', 'Cadena', 'category', false, false, 'CIE-11'),
('XE3WL', 'Material explosivo u objeto inflamable, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE6KQ', 'Fuegos artificiales', 'category', false, false, 'CIE-11'),
('XE59Q', 'Explosivo', 'category', false, false, 'CIE-11'),
('XE908', 'Otro cierto objeto especificado o cosa viva involucrada en causar lesiones', 'category', false, false, 'CIE-11'),
('XE2JA', 'Chorro de alta presión', 'category', false, false, 'CIE-11'),
('XE5DQ', 'Equipamiento y luz láser', 'category', false, false, 'CIE-11'),
('XE9AP', 'Puntero láse', 'category', false, false, 'CIE-11'),
('XE6UH', 'Objeto punzante, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE9GE', 'Objeto contundente, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE98K', 'Motor, máquina, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE8AE', 'Pila seca', 'category', false, false, 'CIE-11'),
('XE8H0', 'Batería de disco', 'category', false, false, 'CIE-11'),
('XE72W', 'Batería, no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE146', 'Jaula para animal', 'category', false, false, 'CIE-11'),
('XE12Z', 'Contenido gástrico', 'category', false, false, 'CIE-11'),
('XE8FT', 'Excremento, humano o animal', 'category', false, false, 'CIE-11'),
('XE08P', 'Sangre, cadáver, cuerpo, hueso, no clasificado en otra parte, humano o animal', 'category', false, false, 'CIE-11'),
('XE2DW', 'Bolsa plastica', 'category', false, false, 'CIE-11'),
('XE2AU', 'Basura , desperdicios , residuos', 'category', false, false, 'CIE-11'),
('XE2VX', 'Polución ambiental, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE6QS', 'Dispositivo médico o quirúrgico que no está en uso terapéutico', 'category', false, false, 'CIE-11'),
('XE47R', 'Uso de alcohol, sin información disponible', 'category', false, false, 'CIE-11'),
('XE08X', 'Uso de alcohol, sin sospecha o evidencia de uso de alcohol por cualquier persona involucrada en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE1G3', 'Uso de alcohol, sospecha o evidencia de consumo de alcohol por parte de la persona lesionada', 'category', false, false, 'CIE-11'),
('XE15H', 'Uso de alcohol, sospecha o evidencia de consumo de alcohol por otras personas involucradas en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE3JF', 'Uso de alcohol, sospecha o evidencia de uso de alcohol por parte de la persona lesionada y otras personas involucradas en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE43G', 'Uso de drogas psicoactivas, sin información disponible', 'category', false, false, 'CIE-11'),
('XE5TU', 'Consumo de drogas psicoactivas, sin sospecha o evidencia de uso de drogas psicoactivas por parte de cualquier persona involucrada en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE5VY', 'Cosumo de drogas psicoactivas, sospecha o evidencia del uso de drogas psicoactivas por parte de cualquier persona involucrada en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE8GW', 'Cosumo de drogas psicoactivas, sospecha o evidencia del uso de drogas psicoactivas por otras personas involucrada en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE28E', 'Consumo de drogas, sospecha o evidencia de uso de drogas psicoactivas por ambas la persona lesionada y otras personas involucradas en el evento de lesión', 'category', false, false, 'CIE-11'),
('XE88K', 'Peatón como modo de transporte de la persona lesionada en un evento de transporte', 'category', false, false, 'CIE-11'),
('XE645', 'Persona de a pie lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE0HE', 'Persona de a pie estando parada, caminando o corriendo en el momento del choque', 'category', false, false, 'CIE-11'),
('XE7ZY', 'Transporte peatonal como modo de transporte de la persona lesionada en un evento de transporte', 'category', false, false, 'CIE-11'),
('XE0TE', 'Escúter para movilidad como modo de transporte de persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE80N', 'Silla de ruedas motorizada como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE08H', 'Patines de hielo como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE0FX', 'Esquíes como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3JS', 'Snowboard como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE036', 'Trineo como medio de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE96G', 'Patineta como medio de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2PW', 'Patines como modo de transporte de la persona herida en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4HS', 'Scooter como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7RL', 'Cochecito de bebé como medio de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1BH', 'Cochecito como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9SV', 'Silla de empuje como medio de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7KT', 'Paseante como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE71D', 'Ciclo pedal como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2BW', 'Remolque o sidecar anexado a un ciclo de pedal como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE6R4', 'Bicitaxi o triciclo como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7NK', 'Motocicleta como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2J1', 'Ciclomotor como medio de transporte de la persona herida en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE39A', 'Motocicleta básica como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9BU', 'scooter de motor como modo de transporte de la persona lesionada en el evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9RC', 'Bicicleta motorizada como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1ZG', 'Bicicleta Ag como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2W4', 'Automóvil como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE0V3', 'Vehículo 4X4 como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2TP', 'Vehículo de transporte ligero con cuatro o más ruedas utilizadas en actividades deportivas y de ocio como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9K7', 'Microcoche como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE62M', 'Automóvil como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE85J', 'Station wagon como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7LL', 'Minivan como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1CK', 'Jeep como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5X0', 'Vehículo utilitario deportivo como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2RA', 'Autobús o autocar como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9JB', 'Vehículo de mercancías ligeras como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE6PF', 'Minibús o camioneta de pasajeros como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE165', 'Camioneta pick-up, furgoneta de trabajo o mercancías, ambulancia, casa rodante como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1PH', 'Vehículo de mercancías pesado como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE10A', 'Camiones, van y otros vehículos de mercancías pesados como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1VN', 'Vehículo bomba de bombero como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7XM', 'Tractor de carretera con o sin semirremolque como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5ET', 'Camión con remolque como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE41E', 'Tranvía o trole como medio de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5WB', 'Vehículo de pasajeros de baja potencia como modo de transporte de la persona lesionada en el evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE8DK', 'tuk-tuk como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1DF', 'Mototaxi como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4SA', 'Auto rickshaw de tres ruedas como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE35C', 'Vehículo especial usado principalmente en agricultura como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3WV', 'Máquina agrícola autopropulsada como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3QK', 'Cosechadora como modo de transporte de la persona herida en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE872', 'Tractor agrícola como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE885', 'Vehículo especial usado principalmente en locales industriales como modo de transporte de personas heridas en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE31K', 'Carretilla elevadora como modo de transporte de la persona herida en el evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE312', 'Vehículo de construcción especial como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5RK', 'Vehículo especial todo terreno como modo de transporte de la persona lesionada en un evento de transporte', 'category', false, false, 'CIE-11'),
('XE63N', 'Moto de nieve como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5U7', 'Aerodeslizador que opera en tierra o pantano como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4MT', 'Vehículo anfibio en tierra como modo de transporte de una persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3SA', 'Cuatriciclo como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE940', 'Montar animal como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1ZJ', 'Caballo como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4ZZ', 'Vehículo tirado por animal como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE8YD', 'Vehículo ferroviario como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1KN', 'Tren ferroviario como modo de transporte de persona lesionada en un evento relacionado con transporte', 'category', false, false, 'CIE-11'),
('XE3NY', 'Funicular o monocarril como modo de transporte de persona lesionada en un evento relacionado con transporte', 'category', false, false, 'CIE-11'),
('XE27K', 'Moto acuática como modo de transporte de persona lesionada en un evento relacionado con transporte', 'category', false, false, 'CIE-11'),
('XE4FF', 'Submarino como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3QY', 'Barco mercante como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9YQ', 'Barco de pasajeros como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9PA', 'Barco de pesca o barco de jabeguero como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE0L4', 'Velero, yate sin motor como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4AK', 'Aerodeslizadores y vehículos anfibios cuando están dentro o sobre un cuerpo de agua como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5WL', 'Otra embarcación motorizada o potencia especificadas como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE36L', 'Otra embarcación sin potencia especificada como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1JR', 'Aeronave como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3J3', 'Globos y otros dispositivos más ligeros que el aire como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE2UU', 'Aeronave propulsada como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE6SQ', 'Aviones sin motor como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4VS', 'Paracaídas utilizados en descenso desde aviones dañados como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE08L', 'Paracaídas utilizados en descenso desde aviones no-dañados como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE33H', 'Planeador como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE48X', 'Helicóptero como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE0VS', 'Nave espacial como modo de transporte de la persona lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE82G', 'Dispositivos o partes de dispositivos diseñados para ascender y aterrizar en la tierra o la superficie de otros cuerpos como modo de transporte de la persona lesionada en el evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE42A', 'Conductor del vehículo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE8ZW', 'Persona conduciendo un vehículo de motor lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE65U', 'Persona que conduce, opera o controla una motocicleta o vehículo a pedales lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE3WH', 'Persona responsable de reanudar el control manual de un vehículo con autonomía o control parcialmente autónomo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE8SZ', 'Persona con control de dirección y frenado en el caso de una bicicleta tándem o vehículo similar lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE302', 'Persona que dirige o intenta dirigir a un animal lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE1LZ', 'Pasajero del vehículo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE5X3', 'Ocupante de vehículo no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE3FA', 'Ocupante de la posición prevista para el paciente en una ambulancia', 'category', false, false, 'CIE-11'),
('XE9FE', 'Ocupantes de silla de ruedas o scooter de movilidad ubicados en una posición en un vehículo de motor provisto para llevar tales dispositivos', 'category', false, false, 'CIE-11'),
('XE9CP', 'Ocupantes del área en un autobús provisto para estar de pie', 'category', false, false, 'CIE-11'),
('XE9Y1', 'Persona abordando o bajándose de un vehículo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE76V', 'Persona entrando o saliendo de un vehículo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE6LC', 'Persona que aborda o baja de un autobús, tranvía, trole bús o vehículo ferroviario lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE166', 'Persona fuera del vehículo o en el espacio de carga lesionada en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7FA', 'Persona transportada por un vehículo y ocupando un espacio destinado para el transporte de bienes o cargas lesionados en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE4CZ', 'Persona transportada por un vehículo y ocupando un espacio en el techo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE9X1', 'Persona transportada por un vehículo y ocupando un espacio en un estribo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE7PL', 'Persona transportada por un vehículo y ocupando un espacio fuera de la cabina sosteniendo sobre el vehículo lesionado en un evento relacionado con el transporte', 'category', false, false, 'CIE-11'),
('XE6R5', 'Persona montada en un animal lesionada en un evento de transporte', 'category', false, false, 'CIE-11'),
('XE6K0', 'Peatón como contraparte en un choque con un transporte terrestre', 'category', false, false, 'CIE-11'),
('XE57K', 'Persona de a pie como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE2ZK', 'Persona que utiliza un medio de transporte de peatones como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE3NU', 'Transporte peatonal como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE93R', 'Scooter de movilidad como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE3XF', 'Silla de ruedas como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1TJ', 'Patines de hielo como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE5XW', 'Esquís como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE4NZ', 'Tabla de nieve como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE5D9', 'Trineo como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE5H4', 'Monopatín como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9J0', 'Patines como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE28X', 'Patineta como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE5SX', 'Carro de bebé como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1ZX', 'Carriola como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE168', 'Silla de empuje como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE2JL', 'Cochecito como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE7ZZ', 'Ciclo de pedal como contraparte en el choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE5GG', 'Remolque o sidecar conectado a un ciclo de pedal como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE2PY', 'Bicicleta o triciclo con carro de culi como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE8XQ', 'Ciclomotor como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1SA', 'Bicicleta motorizada como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0V4', 'Biciclo motorizado como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE4C1', 'Motocicleta básica como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9FR', 'Motoneta como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE59J', 'Bicicleta Ag como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0JH', 'Automóvil como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0LP', 'Automóvil como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0HH', 'Camioneta como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0T7', 'Minivan como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE38X', '4X4 como contraparte de un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6G7', 'Vehículo utilitario deportivo como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE3BW', 'Jeep como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0ZR', 'Microauto como contraparte en un choque de transporte terretre', 'category', false, false, 'CIE-11'),
('XE5LJ', 'Autobús o autocar como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6UN', 'Vehículo de mercancías livianas como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0ZL', 'Minibús o camioneta de pasajeros como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE4DB', 'Camioneta pickup, camioneta de trabajo o de mercancía, ambulancia o autocaravana como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0MB', 'Vehículo de transporte liviano con cuatro o más ruedas utilizado en actividades deportivas y de ocio como contrapartida en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE854', 'Vehículo de transporte pesado como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE590', 'Camiones y otros vehículos de carga pesada como contrapartida en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE4Q6', 'Camión con remolque como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE45E', 'Tractor de carretera con o sin semirremolque como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE3M3', 'Vehículo autobomba como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE8UX', 'Autobús o tranvía como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE90S', 'Vehículo de pasajeros de baja potencia como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9VV', 'Tuk-tuk (en Tailandia) como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9ML', 'Mototaxi como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE73V', 'Vehículo de tres ruedas auto rickshaw (Asia) como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9HB', 'Vehículo especial usado principalmente en la agricultura como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9HZ', 'Máquina agrícola autopropulsada como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6W7', 'Cosechadora como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9GD', 'Tractor agrícola como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9DQ', 'Vehículo especial usado principalmente en instalaciones industriales como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1U3', 'Carretilla elevadora como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1YW', 'Vehículo de construcción especial como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE23Q', 'Vehículo especial todoterreno como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE60L', 'Moto de nieve como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE28S', 'Aerodeslizador que opera en tierra o pantano como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE8AH', 'Vehículo anfibio en tierra como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9KN', 'Cuadriciclo como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6QK', 'Animal como contraparte en un un choque de trasporte terrestre', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
