-- CIE11 Import Part 3
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('1G0Z', 'Infestaciones por ectoparásitos, sin especificación', 'category', false, false, 'CIE-11'),
('1G2Y', 'Otras enfermedades parasitarias especificadas', 'category', false, false, 'CIE-11'),
('1G2Z', 'Enfermedades parasitarias, sin especificación', 'category', false, false, 'CIE-11'),
('1G40', 'Sepsis sin choque séptico', 'category', false, false, 'CIE-11'),
('1G41', 'Sepsis con choque séptico', 'category', false, false, 'CIE-11'),
('1G60', 'Algunos otros trastornos de origen infeccioso', 'category', false, false, 'CIE-11'),
('1G60.0', 'Micetoma de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('1G60.1', 'Pitiosis', 'category', false, false, 'CIE-11'),
('1G60.2', 'Prototecosis', 'category', false, false, 'CIE-11'),
('1G60.3', '', 'category', false, false, 'CIE-11'),
('1G60.Y', 'Algunos otros trastornos especificados de origen infeccioso no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('1G80', 'Secuelas de la tuberculosis', 'category', false, false, 'CIE-11'),
('1G81', 'Secuelas del tracoma', 'category', false, false, 'CIE-11'),
('1G82', 'Secuelas de la lepra', 'category', false, false, 'CIE-11'),
('1G83', 'Secuelas de la poliomielitis', 'category', false, false, 'CIE-11'),
('1G84', 'Secuelas de la encefalitis viral', 'category', false, false, 'CIE-11'),
('1G85', 'Secuelas de la difteria', 'category', false, false, 'CIE-11'),
('1G8Y', 'Secuelas de otras enfermedades infecciosas especificadas', 'category', false, false, 'CIE-11'),
('1G8Z', 'Secuelas de enfermedades infecciosas, sin especificación', 'category', false, false, 'CIE-11'),
('1H0Z', 'Algunas enfermedades infecciosas o parasitarias, sin especificación', 'category', false, false, 'CIE-11'),
('2A00', 'Neoplasias primarias de cerebro', 'category', false, false, 'CIE-11'),
('2A00.0', 'Gliomas de cerebro', 'category', false, false, 'CIE-11'),
('2A00.00', 'Glioblastoma de cerebro', 'category', false, false, 'CIE-11'),
('2A00.0Y', 'Otros gliomas especificados del cerebro', 'category', false, false, 'CIE-11'),
('2A00.0Z', 'Gliomas de cerebro, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.1', 'Tumores embrionarios del cerebro', 'category', false, false, 'CIE-11'),
('2A00.10', 'Meduloblastoma del cerebro', 'category', false, false, 'CIE-11'),
('2A00.11', 'Tumor neuroectodérmico primitivo central', 'category', false, false, 'CIE-11'),
('2A00.1Y', 'Otros tumores embrionarios especificados del cerebro', 'category', false, false, 'CIE-11'),
('2A00.1Z', 'Tumores embrionarios del cerebro, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.2', 'Tumores del tejido neuroepitelial del encéfalo', 'category', false, false, 'CIE-11'),
('2A00.20', 'Tumores de la glándula pineal o de la región pineal', 'category', false, false, 'CIE-11'),
('2A00.21', 'Tumores mixtos gliales-neuronales', 'category', false, false, 'CIE-11'),
('2A00.22', 'Tumores de los plexos coroideos', 'category', false, false, 'CIE-11'),
('2A00.2Y', 'Otros tumores especificados del tejido neuroepitelial del encéfalo', 'category', false, false, 'CIE-11'),
('2A00.2Z', 'Tumores del tejido neuroepitelial del encéfalo, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.3', 'Neurocitoma central del cerebro', 'category', false, false, 'CIE-11'),
('2A00.4', 'Astroblastoma de cerebro', 'category', false, false, 'CIE-11'),
('2A00.5', 'Neoplasia primaria de cerebro de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A01', 'Neoplasias primarias de las meninges', 'category', false, false, 'CIE-11'),
('2A01.0', 'Meningiomas', 'category', false, false, 'CIE-11'),
('2A01.00', 'Meningioma primario maligno', 'category', false, false, 'CIE-11'),
('2A01.0Y', 'Otros meningeomas especificados', 'category', false, false, 'CIE-11'),
('2A01.0Z', 'Meningiomas, sin especificación', 'category', false, false, 'CIE-11'),
('2A01.1', 'Tumores mesenquimatosos de las meninges', 'category', false, false, 'CIE-11'),
('2A01.2', 'Neoplasia primaria de las meninges de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A02', 'Neoplasia primaria de la médula espinal, de los nervios craneales o de otras partes remanentes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A02.0', 'Gliomas de la médula espinal, de los pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.00', 'Glioblastoma de médula espinal, pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.0Y', 'Otros gliomas especificados de médula espinal, pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.0Z', 'Gliomas de médula espinal, pares craneales o de nervios paraespinales, sin especificación', 'category', false, false, 'CIE-11'),
('2A02.1', 'Tumores de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.10', 'Tumor maligno de la vaina del nervio periférico de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.11', 'Neuroblastoma paravertebral', 'category', false, false, 'CIE-11'),
('2A02.12', 'Neoplasia maligna del nervio óptico', 'category', false, false, 'CIE-11'),
('2A02.1Y', 'Otros tumores especificados de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.1Z', 'Tumores de los nervios craneales o paraespinales, sin especificación', 'category', false, false, 'CIE-11'),
('2A02.2', 'Neoplasia primaria de médula espinal de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A02.3', 'Neoplasia benigna de los nervios craneales', 'category', false, false, 'CIE-11'),
('2A02.4', 'Neoplasia benigna de la médula espinal', 'category', false, false, 'CIE-11'),
('2A02.Z', 'Neoplasia primaria de la médula espinal, de los nervios craneales o de otras partes remanentes del sistema nervioso central, sin especificación', 'category', false, false, 'CIE-11'),
('2A0Z', 'Otras neoplasias y las no especificadas del cerebro o del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A20', 'Neoplasias mieloproliferativas no mastocíticas', 'category', false, false, 'CIE-11'),
('2A20.0', 'Leucemia mielógena crónica, BCR-ABL1 positivo', 'category', false, false, 'CIE-11'),
('2A20.00', 'Leucemia mielógena crónica con crisis blástica', 'category', false, false, 'CIE-11'),
('2A20.01', 'Leucemia mielógena crónica, positiva al cromosoma de Filadelfia (Ph1)', 'category', false, false, 'CIE-11'),
('2A20.02', 'Leucemia mielógena crónica, t(9:22)(q34;q11)', 'category', false, false, 'CIE-11'),
('2A20.03', 'Leucemia monocítica de tipo Naegeli', 'category', false, false, 'CIE-11'),
('2A20.0Y', 'Otra leucemia mielógena crónica especificada, BCR-ABL1 positivo', 'category', false, false, 'CIE-11'),
('2A20.0Z', 'Leucemia mielógena crónica BCR-ABL1 positivo, sin especificación', 'category', false, false, 'CIE-11'),
('2A20.1', 'Leucemia neutrofílica crónica', 'category', false, false, 'CIE-11'),
('2A20.2', 'Mielofibrosis primaria', 'category', false, false, 'CIE-11'),
('2A20.3', 'Leucemia eosinofílica crónica, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2A20.4', 'Policitemia vera', 'category', false, false, 'CIE-11'),
('2A20.5', 'Neoplasia mieloproliferativa no mastocítica, no clasificable', 'category', false, false, 'CIE-11'),
('2A20.Y', 'Otras neoplasias mieloproliferativas no mastocíticas especificadas', 'category', false, false, 'CIE-11'),
('2A20.Z', 'Neoplasias mieloproliferativas no mastocíticas, sin especificación', 'category', false, false, 'CIE-11'),
('2A21', 'Mastocitosis', 'category', false, false, 'CIE-11'),
('2A21.0', 'Mastocitosis sistémica', 'category', false, false, 'CIE-11'),
('2A21.00', 'Leucemia mastocítica', 'category', false, false, 'CIE-11'),
('2A21.0Y', 'Otra mastocitosis sistémica especificada', 'category', false, false, 'CIE-11'),
('2A21.0Z', 'Mastocitosis sistémica, sin especificación', 'category', false, false, 'CIE-11'),
('2A21.1', 'Mastocitosis cutánea', 'category', false, false, 'CIE-11'),
('2A21.10', 'Urticaria pigmentosa', 'category', false, false, 'CIE-11'),
('2A21.1Y', 'Otra mastocitosis cutánea especificada', 'category', false, false, 'CIE-11'),
('2A21.1Z', 'Mastocitosis cutánea, sin especificación', 'category', false, false, 'CIE-11'),
('2A21.2', 'Sarcoma de mastocitos', 'category', false, false, 'CIE-11'),
('2A21.3', 'Mastocitoma extracutáneo', 'category', false, false, 'CIE-11'),
('2A21.Y', 'Otra mastocitosis especificada', 'category', false, false, 'CIE-11'),
('2A21.Z', 'Mastocitosis, sin especificación', 'category', false, false, 'CIE-11'),
('2A2Y', 'Otro(a)(s) neoplasias mieloproliferativas especificado(a)(s)', 'category', false, false, 'CIE-11'),
('2A2Z', 'Neoplasias mieloproliferativas, sin especificación', 'category', false, false, 'CIE-11'),
('2A30', 'Anemia refractaria', 'category', false, false, 'CIE-11'),
('2A31', 'Neutropenia refractaria', 'category', false, false, 'CIE-11'),
('2A32', 'Trombocitopenia refractaria', 'category', false, false, 'CIE-11'),
('2A33', 'Anemia refractaria con sideroblastos en anillo', 'category', false, false, 'CIE-11'),
('2A34', 'Citopenia refractaria con displasia multilinaje', 'category', false, false, 'CIE-11'),
('2A35', 'Anemia refractaria con exceso de blastocitos', 'category', false, false, 'CIE-11'),
('2A36', 'Síndrome mielodisplásico con deletion (5q) aislada', 'category', false, false, 'CIE-11'),
('2A37', 'Síndrome mielodisplásico, no clasificable', 'category', false, false, 'CIE-11'),
('2A38', 'Citopenia refractaria de la infancia', 'category', false, false, 'CIE-11'),
('2A3Y', 'Otros síndromes mielodisplásicos especificados', 'category', false, false, 'CIE-11'),
('2A3Z', 'Síndromes mielodisplásicos, sin especificación', 'category', false, false, 'CIE-11'),
('2A40', 'Leucemia mielomonocítica crónica', 'category', false, false, 'CIE-11'),
('2A41', 'Leucemia mieloide crónica atípica, BCR-ABL1-negativo', 'category', false, false, 'CIE-11'),
('2A42', 'Leucemia mielomonocítica juvenil', 'category', false, false, 'CIE-11'),
('2A42.0', 'Leucemia mielomonocítica juvenil en remisión completa', 'category', false, false, 'CIE-11'),
('2A42.Y', 'Otra leucemia mielomonocítica juvenil especificada', 'category', false, false, 'CIE-11'),
('2A42.Z', 'Leucemia mielomonocítica juvenil, sin especificación', 'category', false, false, 'CIE-11'),
('2A43', 'Anemia resistente con sideroblastos en anillo y trombocitosis intensa', 'category', false, false, 'CIE-11'),
('2A44', 'Enfermedad mielodisplásica y mieloproliferativa, no clasificable', 'category', false, false, 'CIE-11'),
('2A4Y', 'Otras neoplasias mielodisplásicas y mieloproliferativas especificadas', 'category', false, false, 'CIE-11'),
('2A4Z', 'Neoplasias mielodisplásicas y mieloproliferativas, sin especificación', 'category', false, false, 'CIE-11'),
('2A50', 'Neoplasia mieloide/linfoide con reestructuración de PDGFRA', 'category', false, false, 'CIE-11'),
('2A51', 'Neoplasia mielógena asociada con reestructuración de PDGFRB', 'category', false, false, 'CIE-11'),
('2A52', 'Neoplasias linfoides y mieloides con anomalías de FGFR1', 'category', false, false, 'CIE-11'),
('2A5Z', 'Neoplasias linfocíticas y mielocíticas con eosinofilia y anomalías de PDGFRA, PDGFRB o FGFR1, sin especificación', 'category', false, false, 'CIE-11'),
('2A60', 'Leucemias mieloides agudas y neoplasias precursoras relacionadas', 'category', false, false, 'CIE-11'),
('2A60.0', 'Leucemia mielógena aguda con anomalías genéticas recurrentes', 'category', false, false, 'CIE-11'),
('2A60.1', 'Leucemia mielógena aguda con alteraciones mielodisplásicas', 'category', false, false, 'CIE-11'),
('2A60.2', 'Neoplasias mielógenas relacionadas con el tratamiento', 'category', false, false, 'CIE-11'),
('2A60.20', 'Leucemia mielógena aguda o síndrome mielodisplásico relacionados con el tratamiento', 'category', false, false, 'CIE-11'),
('2A60.2Y', 'Otras neoplasias mielógenas relacionadas con el tratamiento especificadas', 'category', false, false, 'CIE-11'),
('2A60.2Z', 'Neoplasias mielógenas relacionadas con el tratamiento, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.3', 'Leucemia mielógena aguda, no especificada en otra parte según los criterios de otros tipos', 'category', false, false, 'CIE-11'),
('2A60.30', 'Leucemia mieloide aguda con mínima diferenciación', 'category', false, false, 'CIE-11'),
('2A60.31', 'Leucemia mieloide aguda sin maduración', 'category', false, false, 'CIE-11'),
('2A60.32', 'Leucemia mieloide aguda con maduración', 'category', false, false, 'CIE-11'),
('2A60.33', 'Leucemia mielomonocítica aguda', 'category', false, false, 'CIE-11'),
('2A60.34', 'Leucemia monocítica o monoblástica aguda', 'category', false, false, 'CIE-11'),
('2A60.35', 'Leucemia eritroide aguda', 'category', false, false, 'CIE-11'),
('2A60.36', 'Leucemia megacarioblástica aguda', 'category', false, false, 'CIE-11'),
('2A60.37', 'Leucemia basofílica aguda', 'category', false, false, 'CIE-11'),
('2A60.38', 'Panmielosis aguda con mielofibrosis', 'category', false, false, 'CIE-11'),
('2A60.39', 'Sarcoma mieloide', 'category', false, false, 'CIE-11'),
('2A60.3Y', 'Otra leucemia mieloide aguda especificada, no clasificado en otra parte por criterios de otros tipos', 'category', false, false, 'CIE-11'),
('2A60.3Z', 'Leucemia mielógena aguda, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.4', 'Proliferación mieloide en el síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.40', 'Mielopoyesis anormal transitoria', 'category', false, false, 'CIE-11'),
('2A60.41', 'Leucemia mieloide asociada con síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.4Y', 'Otra proliferación mieloide especificada en el síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.4Z', 'Proliferación mieloide en el síndrome Down, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.5', 'Neoplasia blástica de células dendríticas plasmacitoides', 'category', false, false, 'CIE-11'),
('2A60.Y', 'Otras leucemias mieloides agudas y neoplasias precursoras relacionadas especificadas', 'category', false, false, 'CIE-11'),
('2A60.Z', 'Leucemias mieloides agudas y neoplasias precursoras relacionadas, sin especificación', 'category', false, false, 'CIE-11'),
('2A61', 'Leucemias agudas de linaje ambiguo', 'category', false, false, 'CIE-11'),
('2A70', 'Neoplasias de precursores B linfoblásticas', 'category', false, false, 'CIE-11'),
('2A70.0', 'Linfoma o leucemia linfoblástica B, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2A70.1', 'Linfoma o leucemia linfoblástica de precursores B con t(9:22) (q34;q11.2); BCR-ABL1', 'category', false, false, 'CIE-11'),
('2A70.Y', 'Otro linfoma o leucemia linfoblástica B con anomalías genéticas recurrentes', 'category', false, false, 'CIE-11'),
('2A71', 'Neoplasias linfoblásticas de precursores T', 'category', false, false, 'CIE-11'),
('2A7Z', 'Neoplasias de linfocitos precursores, sin especificación', 'category', false, false, 'CIE-11'),
('2A80', 'Linfoma folicular', 'category', false, false, 'CIE-11'),
('2A80.0', 'Linfoma folicular de grado 1', 'category', false, false, 'CIE-11'),
('2A80.1', 'Linfoma folicular de grado 2', 'category', false, false, 'CIE-11'),
('2A80.2', 'Linfoma folicular de grado 3', 'category', false, false, 'CIE-11'),
('2A80.3', 'Linfoma cutáneo primario centrofolicular', 'category', false, false, 'CIE-11'),
('2A80.4', 'Linfoma folicular de tipo pediátrico', 'category', false, false, 'CIE-11'),
('2A80.5', 'Linfoma folicular in situ', 'category', false, false, 'CIE-11'),
('2A80.6', 'Linfoma folicular del intestino delgado', 'category', false, false, 'CIE-11'),
('2A80.Y', 'Otro linfoma folicular especificado', 'category', false, false, 'CIE-11'),
('2A80.Z', 'Linfoma folicular, sin especificación', 'category', false, false, 'CIE-11'),
('2A81', 'Linfomas difusos de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.0', 'Linfoma mediastínico primario de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.1', 'Linfoma de linfocitos B grandes intravascular', 'category', false, false, 'CIE-11'),
('2A81.2', 'Linfoma plasmablástico', 'category', false, false, 'CIE-11'),
('2A81.3', 'Granulomatosis linfomatoide', 'category', false, false, 'CIE-11'),
('2A81.4', 'Linfoma de linfocitos B grandes rico en histocitos o linfocitos T', 'category', false, false, 'CIE-11'),
('2A81.5', 'Linfoma difuso primario de linfocitos B grandes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A81.6', 'Linfoma difuso de células B grandes positivo para el virus de Epstein-Barr en ancianos', 'category', false, false, 'CIE-11'),
('2A81.7', 'Linfoma difuso de linfocitos B grandes asociados a inflamación crónica', 'category', false, false, 'CIE-11'),
('2A81.8', 'Linfoma de linfocitos B grandes con positividad a ALK', 'category', false, false, 'CIE-11'),
('2A81.9', 'Linfoma primario con derrame', 'category', false, false, 'CIE-11'),
('2A81.A', 'Linfoma cutáneo primario difuso de linfocitos B grandes, tipo de la pierna', 'category', false, false, 'CIE-11'),
('2A81.Y', 'Otros linfomas difusos especificados de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.Z', 'Linfoma difuso de linfocitos B grandes, sin otra especificación', 'category', false, false, 'CIE-11'),
('2A82', 'Neoplasia de linfocitos B maduros con comportamiento leucémico', 'category', false, false, 'CIE-11'),
('2A82.0', 'Leucemia linfocítica crónica o linfoma de linfocitos pequeños', 'category', false, false, 'CIE-11'),
('2A82.00', 'Leucemia linfocítica crónica de linfocitos B', 'category', false, false, 'CIE-11'),
('2A82.0Y', 'Leucemia linfocítica crónica o linfoma linfocítico pequeño especificado', 'category', false, false, 'CIE-11'),
('2A82.0Z', 'Leucemia linfocítica crónica o linfoma linfocítico pequeño, sin especificación', 'category', false, false, 'CIE-11'),
('2A82.1', 'Leucemia prolinfocítica de linfocitos B', 'category', false, false, 'CIE-11'),
('2A82.10', 'Leucemia prolinfocítica de linfocitos B en remisión completa', 'category', false, false, 'CIE-11'),
('2A82.1Y', 'Otra leucemia prolinfocítica de linfocitos B especificadas', 'category', false, false, 'CIE-11'),
('2A82.1Z', 'Leucemia prolinfocítica de linfocitos B, sin especificación', 'category', false, false, 'CIE-11'),
('2A82.2', 'Leucemia de células pilosas', 'category', false, false, 'CIE-11'),
('2A82.3', 'Leucemia o linfoma de linfocitos B esplénicos, no clasificable', 'category', false, false, 'CIE-11'),
('2A82.Y', 'Neoplasia de linfocitos B maduros especificada con comportamiento leucémico', 'category', false, false, 'CIE-11'),
('2A82.Z', 'Neoplasia de linfocitos B maduros con comportamiento leucémico, sin especificación', 'category', false, false, 'CIE-11'),
('2A83', 'Neoplasias de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.0', 'Gammapatía monoclonal de significado incierto', 'category', false, false, 'CIE-11'),
('2A83.1', 'Mieloma de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.2', 'Plasmocitoma solitario', 'category', false, false, 'CIE-11'),
('2A83.3', 'Plasmocitoma extraóseo', 'category', false, false, 'CIE-11'),
('2A83.4', 'Leucemia de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.5', 'Enfermedad por depósito de inmunoglobulinas monoclonales', 'category', false, false, 'CIE-11'),
('2A83.50', 'Enfermedad por depósito de cadena pesada', 'category', false, false, 'CIE-11'),
('2A83.51', 'Enfermedad por depósito de cadenas pesadas y ligeras', 'category', false, false, 'CIE-11'),
('2A83.52', 'Enfermedad por depósito de cadena ligera', 'category', false, false, 'CIE-11'),
('2A83.Y', 'Otras neoplasias de células plasmáticas especificadas', 'category', false, false, 'CIE-11'),
('2A83.Z', 'Neoplasia de células plasmáticas, sin especificación', 'category', false, false, 'CIE-11'),
('2A84', 'Enfermedades de la cadena pesada o enfermedades inmunoproliferativas malignas', 'category', false, false, 'CIE-11'),
('2A84.0', 'Enfermedad de la cadena pesada alfa', 'category', false, false, 'CIE-11'),
('2A84.1', 'Enfermedad de la cadena pesada gamma', 'category', false, false, 'CIE-11'),
('2A84.2', 'Enfermedad de la cadena pesada mu', 'category', false, false, 'CIE-11'),
('2A84.Y', 'Otras enfermedades inmunoproliferativas malignas especificadas', 'category', false, false, 'CIE-11'),
('2A84.Z', 'Enfermedades de la cadena pesada, sin especificación', 'category', false, false, 'CIE-11'),
('2A85', 'Otras neoplasias o linfomas de células B maduras especificadas', 'category', false, false, 'CIE-11'),
('2A85.0', 'Linfoma de la zona marginal ganglionar', 'category', false, false, 'CIE-11'),
('2A85.1', 'Linfoma de linfocitos B de la zona marginal extraganglionar del tejido linfático de la mucosa del estómago', 'category', false, false, 'CIE-11'),
('2A85.2', 'Linfoma de linfocitos B de la zona marginal extraganglionar, localización primaria en la piel', 'category', false, false, 'CIE-11'),
('2A85.3', 'Linfoma de células B de la zona marginal extraganglionar, cualquier localización primaria excluyendo el estómago y la piel', 'category', false, false, 'CIE-11'),
('2A85.4', 'Linfoma linfoplasmocítico', 'category', false, false, 'CIE-11'),
('2A85.5', 'Linfoma de células del manto', 'category', false, false, 'CIE-11'),
('2A85.6', 'Linfoma de Burkitt, incluida la leucemia de Burkitt', 'category', false, false, 'CIE-11'),
('2A85.Y', 'Otras neoplasias o linfomas de células B maduras especificadas', 'category', false, false, 'CIE-11'),
('2A86', 'Linfoma de linfocitos B, características mixtas', 'category', false, false, 'CIE-11'),
('2A86.0', 'Linfoma maligno de linfocitos B, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('2A86.1', 'Linfoma de linfocitos B no clasificable con características intermedias entre el linfoma de Burkitt y el linfoma difuso de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A86.2', 'Linfoma de linfocitos B, no clasificable, con características intermedias entre el linfoma de Hodgkin clásico y el linfoma difuso de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A86.Y', 'Otro linfoma de linfocitos B de características mixtas especificado', 'category', false, false, 'CIE-11'),
('2A86.Z', 'Linfoma de linfocitos B de características mixtas, sin especificación', 'category', false, false, 'CIE-11'),
('2A8Z', 'Neoplasias de células B maduras, sin especificación', 'category', false, false, 'CIE-11'),
('2A90', 'Linfoma de linfocitos T maduros, de tipos especificados, sistémicas o ganglionares', 'category', false, false, 'CIE-11'),
('2A90.0', 'Leucemia prolinfocítica de linfocitos T', 'category', false, false, 'CIE-11'),
('2A90.1', 'Leucemia linfocítica de linfocitos T granulares grandes', 'category', false, false, 'CIE-11'),
('2A90.2', 'Trastornos linfoproliferativos crónicos de linfocitos NK', 'category', false, false, 'CIE-11'),
('2A90.3', 'Leucemia muy maligna de linfocitos NK', 'category', false, false, 'CIE-11'),
('2A90.4', 'Linfoma de linfocitos T positivos-con virus de Epstein-Barr sistémico en la infancia', 'category', false, false, 'CIE-11'),
('2A90.5', 'Leucemia o linfoma de linfocitos T adultos asociado al virus linfotrópico humano de los linfocitos T de tipo 1', 'category', false, false, 'CIE-11'),
('2A90.6', 'Linfoma de células NK y linfocitos T extraganglionar, tipo nasal', 'category', false, false, 'CIE-11'),
('2A90.7', 'Enteropatía asociada a linfoma de linfocitos T', 'category', false, false, 'CIE-11'),
('2A90.8', 'Linfoma hepatoesplénico de células T', 'category', false, false, 'CIE-11'),
('2A90.9', 'Linfoma de linfocitos T angioinmunoblástico', 'category', false, false, 'CIE-11'),
('2A90.A', 'Linfoma de linfocitos grandes anaplásicos, ALK positivo', 'category', false, false, 'CIE-11'),
('2A90.B', 'Linfoma anaplásico de linfocitos grandes, ALK negativo', 'category', false, false, 'CIE-11'),
('2A90.C', 'Linfoma de linfocitos T periférico, no especificado en otra parte', 'category', false, false, 'CIE-11'),
('2B00', 'Linfoma subcutáneo de linfocitos T parecido a la paniculitis', 'category', false, false, 'CIE-11'),
('2B01', 'Micosis fungoide', 'category', false, false, 'CIE-11'),
('2B02', 'Síndrome de Sézary', 'category', false, false, 'CIE-11'),
('2B03', 'Trastornos linfoproliferativos cutáneos primarios de células T CD30 positivas', 'category', false, false, 'CIE-11'),
('2B03.0', 'Linfoma anaplásico cutáneo primario de linfocitos T grandes CD30+', 'category', false, false, 'CIE-11'),
('2B03.1', 'Papulosis linfomatoide', 'category', false, false, 'CIE-11'),
('2B0Y', 'Otros Linfomas de células T maduras o células NK y trastornos linfoproliferativos, tipos cutáneos primarios especificados', 'category', false, false, 'CIE-11'),
('2B0Z', 'Linfoma cutáneo primario de linfocitos T, tipo indeterminado o no especificado', 'category', false, false, 'CIE-11'),
('2B2Y', 'Otras neoplasias de linfocitos NK o linfocitos T maduros especificadas', 'category', false, false, 'CIE-11'),
('2B2Z', 'Neoplasias de linfocitos NK o linfocitos T maduros, sin especificación', 'category', false, false, 'CIE-11'),
('2B30', 'Linfoma de Hodgkin', 'category', false, false, 'CIE-11'),
('2B30.0', 'Linfoma de Hodgkin nodular de predominio linfocítico', 'category', false, false, 'CIE-11'),
('2B30.1', 'Linfoma de Hodgkin clásico', 'category', false, false, 'CIE-11'),
('2B30.10', 'Linfoma de Hodgkin clásico con esclerosis nodular', 'category', false, false, 'CIE-11'),
('2B30.11', 'Linfoma de Hodgkin clásico rico en linfocitos', 'category', false, false, 'CIE-11'),
('2B30.12', 'Linfoma de Hodgkin clásico de celularidad mixta', 'category', false, false, 'CIE-11'),
('2B30.13', 'Linfoma de Hodgkin clásico con depleción de linfocitos', 'category', false, false, 'CIE-11'),
('2B30.1Z', 'Linfoma de Hodgkin clásico, sin especificación', 'category', false, false, 'CIE-11'),
('2B30.Z', 'Linfoma de Hodgkin, sin especificación', 'category', false, false, 'CIE-11'),
('2B31', 'Neoplasias de células histiocíticas o dendríticas', 'category', false, false, 'CIE-11'),
('2B31.0', 'Xantogranuloma juvenil', 'category', false, false, 'CIE-11'),
('2B31.1', 'Sarcoma histiocítico', 'category', false, false, 'CIE-11'),
('2B31.2', 'Histiocitosis de células de Langerhans', 'category', false, false, 'CIE-11'),
('2B31.20', 'Histiocitosis de células de Langerhans que afecta a la piel', 'category', false, false, 'CIE-11'),
('2B31.2Y', 'Otra histiocitosis de células de Langerhans especificadas', 'category', false, false, 'CIE-11'),
('2B31.2Z', 'Histiocitosis de células de Langerhans, sin especificación', 'category', false, false, 'CIE-11'),
('2B31.3', 'Sarcoma de células de Langerhans', 'category', false, false, 'CIE-11'),
('2B31.4', 'Sarcoma de células dendríticas interdigitantes', 'category', false, false, 'CIE-11'),
('2B31.5', 'Sarcoma de células dendríticas folicular', 'category', false, false, 'CIE-11'),
('2B31.6', 'Histiocitosis de células indeterminadas', 'category', false, false, 'CIE-11'),
('2B31.7', 'Tumor de células reticulares fibroblásticas', 'category', false, false, 'CIE-11'),
('2B31.Y', 'Otras neoplasias de células histiocíticas o dendríticas especificadas', 'category', false, false, 'CIE-11'),
('2B31.Z', 'Neoplasias de células histiocíticas o dendríticas, sin especificación', 'category', false, false, 'CIE-11'),
('2B32', 'Trastornos linfoproliferativos asociados a la inmunodeficiencia', 'category', false, false, 'CIE-11'),
('2B32.0', 'Trastorno linfoproliferativo postrasplante, lesión temprana', 'category', false, false, 'CIE-11'),
('2B32.1', 'Hiperplasia plasmacítica reactiva', 'category', false, false, 'CIE-11'),
('2B32.2', 'Trastorno linfoproliferativo postrasplante, parecido a la mononucleosis infecciosa', 'category', false, false, 'CIE-11'),
('2B32.3', 'Trastorno linfoproliferativo polimorfo postrasplante', 'category', false, false, 'CIE-11'),
('2B32.Y', 'Otros trastornos linfoproliferativos asociados a la inmunodeficiencia especificados', 'category', false, false, 'CIE-11'),
('2B32.Z', 'Trastornos linfoproliferativos asociados a la inmunodeficiencia, sin especificación', 'category', false, false, 'CIE-11'),
('2B33', 'Neoplasias hematopoyéticas malignas sin otra especificación', 'category', false, false, 'CIE-11'),
('2B33.0', 'Leucemia aguda, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2B33.1', 'leucemia mielógena', 'category', false, false, 'CIE-11'),
('2B33.2', 'Leucemia mielógena crónica, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2B33.3', 'Leucemia linfoide, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2B33.4', 'Leucemia, no especificada', 'category', false, false, 'CIE-11'),
('2B33.5', 'Linfoma maligno, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('2B33.Y', 'Otras neoplasias hematopoyéticas malignas especificadas sin otra especificación', 'category', false, false, 'CIE-11'),
('2B3Z', 'Neoplasias de los tejidos hematopoyéticos o linfáticos, sin especificación', 'category', false, false, 'CIE-11'),
('2B50', 'Condrosarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B50.0', 'Condrosarcoma de hueso o cartílago articular de las extremidades', 'category', false, false, 'CIE-11'),
('2B50.1', 'Condrosarcoma de hueso o cartílago articular de la pelvis', 'category', false, false, 'CIE-11'),
('2B50.2', 'Condrosarcoma de hueso o cartílago articular de las costillas, esternón o clavícula', 'category', false, false, 'CIE-11'),
('2B50.Y', 'Condrosarcoma de hueso y cartílago articular de otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B50.Z', 'Condrosarcoma de sitio primario de hueso y cartílago articular, sin especificación', 'category', false, false, 'CIE-11'),
('2B51', 'Osteosarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B51.0', 'Osteosarcoma de hueso o cartílago articular del hueso maxilar', 'category', false, false, 'CIE-11'),
('2B51.1', 'Osteosarcoma de hueso o cartilago articular de las extremidades', 'category', false, false, 'CIE-11'),
('2B51.2', 'Osteosarcoma de hueso o cartílago articular de la pelvis', 'category', false, false, 'CIE-11'),
('2B51.Y', 'Osteosarcoma de hueso y cartílago articular de otros sitios especificados', 'category', false, false, 'CIE-11'),
('2B51.Z', 'Osteosarcoma de hueso y cartílago articular de sitios no especificados', 'category', false, false, 'CIE-11'),
('2B52', 'Sarcoma de Ewing, sitio primario', 'category', false, false, 'CIE-11'),
('2B52.0', 'Sarcoma de Ewing de hueso o cartílago articular de las extremidades', 'category', false, false, 'CIE-11'),
('2B52.1', 'Sarcoma de Ewing de hueso o cartílago articular de la pelvis', 'category', false, false, 'CIE-11'),
('2B52.2', 'Sarcoma de Ewing de hueso o cartílago articular de las costillas', 'category', false, false, 'CIE-11'),
('2B52.3', 'Sarcoma de Ewing de tejidos blandos', 'category', false, false, 'CIE-11'),
('2B52.Y', 'Sarcoma de Ewing de hueso y cartílago articular de otros sitios primarios', 'category', false, false, 'CIE-11'),
('2B52.Z', 'Sarcoma de Ewing de hueso y cartílago articular de sitios sin especificación', 'category', false, false, 'CIE-11'),
('2B53', 'Tumor fibroblástico o miofibroblástico, sitio primario', 'category', false, false, 'CIE-11'),
('2B53.0', 'Mixofibrosarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B53.1', 'Tumor miofibroblástico o fibroblástico de la piel', 'category', false, false, 'CIE-11'),
('2B53.Y', 'Otro tumor fibroblástico o miofibroblástico especificado, de sitio primario', 'category', false, false, 'CIE-11'),
('2B53.Z', 'Tumor fibroblástico o miofibroblástico, de sitio primario, sin especificación', 'category', false, false, 'CIE-11'),
('2B54', 'Sarcoma pleomórfico indiferenciado, sitio primario', 'category', false, false, 'CIE-11'),
('2B54.0', 'Sarcoma pleomórfico indiferenciado de piel', 'category', false, false, 'CIE-11'),
('2B54.1', 'Sarcoma pleomórfico indiferenciado del retroperitoneo o peritoneo', 'category', false, false, 'CIE-11'),
('2B54.Y', 'Sarcoma pleomórfico indiferenciado, otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B54.Z', 'Sarcoma pleomórfico indiferenciado, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B55', 'Rabdomiosarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B55.0', 'Rabdomiosarcoma de la cavidad bucal o la faringe', 'category', false, false, 'CIE-11'),
('2B55.1', 'Rabdomiosarcoma de órganos respiratorios o intratorácicos', 'category', false, false, 'CIE-11'),
('2B55.2', 'Rabdomiosarcoma de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('2B55.Y', 'Rabdomiosarcoma, otro sitio primario especificada', 'category', false, false, 'CIE-11'),
('2B55.Z', 'Rabdomiosarcoma, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B56', 'Angiosarcoma, localización primaria', 'category', false, false, 'CIE-11'),
('2B56.0', 'Angiosarcoma del corazón', 'category', false, false, 'CIE-11'),
('2B56.1', 'Angiosarcoma de la piel', 'category', false, false, 'CIE-11'),
('2B56.2', 'Angiosarcoma de la mama', 'category', false, false, 'CIE-11'),
('2B56.3', 'Angiosarcoma del hígado', 'category', false, false, 'CIE-11'),
('2B56.Y', 'Angiosarcoma, otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B56.Z', 'Angiosarcoma, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B57', 'Sarcoma de Kaposi, sitio primario', 'category', false, false, 'CIE-11'),
('2B57.0', 'Sarcoma de Kaposi del pulmón', 'category', false, false, 'CIE-11'),
('2B57.1', 'Sarcoma de Kaposi de la piel', 'category', false, false, 'CIE-11'),
('2B57.2', 'Sarcoma de Kaposi de sitios gastrointestinales', 'category', false, false, 'CIE-11'),
('2B57.Y', 'Sarcoma de Kaposi de otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B57.Z', 'Sarcoma de Kaposi de sitio primario, sin especificación', 'category', false, false, 'CIE-11'),
('2B58', 'Leiomiosarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B58.0', 'Leiomiosarcoma del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('2B58.1', 'Leiomiosarcoma del útero', 'category', false, false, 'CIE-11'),
('2B58.2', 'Leiomiosarcoma del estómago', 'category', false, false, 'CIE-11'),
('2B58.Y', 'Leiomiosarcoma, otro sitio primario especificada', 'category', false, false, 'CIE-11'),
('2B58.Z', 'Leiomiosarcoma, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B59', 'Liposarcoma, sitio primario', 'category', false, false, 'CIE-11'),
('2B59.0', 'Liposarcoma de los tejidos blandos de las extremidades', 'category', false, false, 'CIE-11'),
('2B59.1', 'Liposarcoma del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('2B59.2', 'Liposarcoma de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('2B59.Y', 'Liposarcoma, otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B59.Z', 'Liposarcoma, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B5A', 'Sarcoma sinovial, sitio primario', 'category', false, false, 'CIE-11'),
('2B5A.0', 'Sarcoma sinovial de los tejidos blandos de las extremidades', 'category', false, false, 'CIE-11'),
('2B5A.1', 'Sarcoma sinovial de los órganos respiratorios o intratorácicos', 'category', false, false, 'CIE-11'),
('2B5A.Y', 'Sarcoma sinovial, otro sitio primario especificado', 'category', false, false, 'CIE-11'),
('2B5A.Z', 'Sarcoma sinovial, sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B5B', 'Tumor del estroma gastrointestinal, sitio primario', 'category', false, false, 'CIE-11'),
('2B5B.0', 'Tumor del estroma gastrointestinal de estómago', 'category', false, false, 'CIE-11'),
('2B5B.1', 'Tumor del estroma gastrointestinal del intestino delgado', 'category', false, false, 'CIE-11'),
('2B5B.Y', 'Tumor del estroma gastrointestinal especificado de otros sitios primarios', 'category', false, false, 'CIE-11'),
('2B5B.Z', 'Tumor del estroma gastrointestinal de sitio primario sin especificación', 'category', false, false, 'CIE-11'),
('2B5C', 'Sarcoma del estroma endometrial sitio primario', 'category', false, false, 'CIE-11'),
('2B5D', 'Tumor maligno mesenquimal y epitelial mixto, localización primaria', 'category', false, false, 'CIE-11'),
('2B5D.0', 'Tumor maligno mesenquimatoso y epitelial mixto del ovario', 'category', false, false, 'CIE-11'),
('2B5D.1', 'Tumor maligno mixto mesenquimatoso y epitelial del cuerpo del útero', 'category', false, false, 'CIE-11'),
('2B5D.Y', 'Tumor maligno mesenquimatoso y epitelial mixto, otra localización primaria especificada', 'category', false, false, 'CIE-11'),
('2B5D.Z', 'Tumor maligno mesenquimatoso y epitelial mixto, localización primaria, sin especificación', 'category', false, false, 'CIE-11'),
('2B5E', 'Tumor maligno de la vaina de los nervios periféricos o del sistema nervioso autónomo, sitio primario', 'category', false, false, 'CIE-11'),
('2B5F', 'Sarcoma, no clasificado en otra parte, localización primaria', 'category', false, false, 'CIE-11'),
('2B5F.0', 'Sarcoma del útero, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('2B5F.1', 'Sarcoma, no clasificado en otra parte, del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('2B5F.10', 'Miosarcomas de epiplón', 'category', false, false, 'CIE-11'),
('2B5F.1Y', 'Otro sarcoma especificado, no clasificado en otra parte, del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('2B5F.1Z', 'Sarcoma, no clasificado en otra parte, del peritoneo o retroperitoneo, sin especificación', 'category', false, false, 'CIE-11'),
('2B5F.2', 'Sarcoma, no clasificado en otra parte, de otras localizaciones especificadas', 'category', false, false, 'CIE-11'),
('2B5F.3', 'Sarcoma, no clasificado en otra parte, sitio primario desconocida', 'category', false, false, 'CIE-11'),
('2B5G', 'Miosarcoma de útero, parte no especificada', 'category', false, false, 'CIE-11'),
('2B5H', 'Tumor lipomatoso bien diferenciado, sitio primario', 'category', false, false, 'CIE-11'),
('2B5J', 'Tumores malignos diversos de hueso o de cartílago articular de otros sitios o de los no especificados', 'category', false, false, 'CIE-11'),
('2B5K', 'Tumores malignos de tejidos blandos no especificados o sarcomas de hueso o cartílago articular de otros sitios o de los no especificados', 'category', false, false, 'CIE-11'),
('2B5Y', 'Otras neoplasias mesenquimales malignas especificadas', 'category', false, false, 'CIE-11'),
('2B5Z', 'Neoplasia mesenquimal maligna, sin especificación', 'category', false, false, 'CIE-11'),
('2B60', 'Neoplasias malignas del labio', 'category', false, false, 'CIE-11'),
('2B60.0', 'Carcinoma de células basales del labio', 'category', false, false, 'CIE-11'),
('2B60.1', 'Carcinoma de células escamosas del labio', 'category', false, false, 'CIE-11'),
('2B60.Y', 'Otra neoplasias malignas del labio especificadas', 'category', false, false, 'CIE-11'),
('2B60.Z', 'Neoplasias malignas del labio, sin especificación', 'category', false, false, 'CIE-11'),
('2B61', 'Neoplasias malignas de la base de la lengua', 'category', false, false, 'CIE-11'),
('2B61.0', 'Carcinoma de células escamosas de la base de la lengua', 'category', false, false, 'CIE-11'),
('2B61.Y', 'Otras neoplasias malignas especificadas de la base de la lengua', 'category', false, false, 'CIE-11'),
('2B61.Z', 'Neoplasias malignas de la base de la lengua, sin especificación', 'category', false, false, 'CIE-11'),
('2B62', 'Neoplasias malignas de otros sitios y sitios no especificados de la lengua', 'category', false, false, 'CIE-11'),
('2B62.0', 'Carcinoma de células escamosas de otras partes o de partes no especificadas de la lengua', 'category', false, false, 'CIE-11'),
('2B62.1', 'Neoplasias malignas de la amígdala lingual', 'category', false, false, 'CIE-11'),
('2B62.10', 'Carcinoma de células escamosas de la amígdala lingual', 'category', false, false, 'CIE-11'),
('2B62.1Z', 'Neoplasias malignas de la amígdala lingual, sin especificación', 'category', false, false, 'CIE-11'),
('2B62.Y', 'Otras neoplasias malignas especificadas de otras partes o de partes no especificadas de la lengua', 'category', false, false, 'CIE-11'),
('2B62.Z', 'Neoplasias malignas de otras partes o de partes no especificadas de la lengua, sin especificación', 'category', false, false, 'CIE-11'),
('2B63', 'Neoplasias malignas de la encía', 'category', false, false, 'CIE-11'),
('2B63.0', 'Carcinoma de células escamosas de la encía', 'category', false, false, 'CIE-11'),
('2B63.Y', 'Otras neoplasias malignas especificadas de la encía', 'category', false, false, 'CIE-11'),
('2B63.Z', 'Neoplasias malignas de la encía, sin especificación', 'category', false, false, 'CIE-11'),
('2B64', 'Neoplasias malignas del piso de la boca', 'category', false, false, 'CIE-11'),
('2B64.0', 'Carcinoma de células escamosas del piso de la boca', 'category', false, false, 'CIE-11'),
('2B64.Y', 'Otra neoplasia maligna especificada del piso de la boca', 'category', false, false, 'CIE-11'),
('2B64.Z', 'Neoplasias malignas del piso de la boca, sin especificación', 'category', false, false, 'CIE-11'),
('2B65', 'Neoplasias malignas del paladar', 'category', false, false, 'CIE-11'),
('2B65.0', 'Adenocarcinoma del paladar', 'category', false, false, 'CIE-11'),
('2B65.1', 'Carcinoma de células escamosas del paladar', 'category', false, false, 'CIE-11'),
('2B65.Y', 'Otra neoplasia maligna especificada del paladar', 'category', false, false, 'CIE-11'),
('2B65.Z', 'Neoplasias malignas del paladar, sin especificación', 'category', false, false, 'CIE-11'),
('2B66', 'Neoplasias malignas de otras partes o de partes no especificadas de la boca', 'category', false, false, 'CIE-11'),
('2B66.0', 'Carcinoma de células escamosas de otras partes o de partes no especificadas de la boca', 'category', false, false, 'CIE-11'),
('2B66.Y', 'Otras neoplasias malignas especificadas de otras partes o de partes no especificadas de la boca', 'category', false, false, 'CIE-11'),
('2B66.Z', 'Neoplasias malignas de otras partes o de partes no especificadas de la boca, sin especificación', 'category', false, false, 'CIE-11'),
('2B67', 'Neoplasias malignas de la glándula parótida', 'category', false, false, 'CIE-11'),
('2B67.0', 'Adenocarcinoma de la glándula parótida', 'category', false, false, 'CIE-11'),
('2B67.1', 'Carcinoma de células escamosas de la glándula parótida', 'category', false, false, 'CIE-11'),
('2B67.Y', 'Otras neoplasias malignas especificadas de la glándula parótida', 'category', false, false, 'CIE-11'),
('2B67.Z', 'Neoplasias malignas de la glándula parótida, sin especificación', 'category', false, false, 'CIE-11'),
('2B68', 'Neoplasias malignas de las glándulas submaxilares o sublinguales', 'category', false, false, 'CIE-11'),
('2B68.0', 'Adenocarcinoma de glándulas submaxilares o sublinguales', 'category', false, false, 'CIE-11'),
('2B68.1', 'Carcinoma de células escamosas de las glándulas submaxilares o sublinguales', 'category', false, false, 'CIE-11'),
('2B68.2', 'Otras neoplasias malignas especificadas de las glándulas submaxilares o sublinguales', 'category', false, false, 'CIE-11'),
('2B68.Z', 'Neoplasias malignas de las glándulas submaxilares o sublinguales, sin especificación', 'category', false, false, 'CIE-11'),
('2B69', 'Neoplasias malignas de la amígdala', 'category', false, false, 'CIE-11'),
('2B69.0', 'Carcinoma de células escamosas de la amígdala', 'category', false, false, 'CIE-11'),
('2B69.1', 'Otras neoplasias malignas especificadas de la amígdala', 'category', false, false, 'CIE-11'),
('2B69.Z', 'Neoplasias malignas de la amígdala, sin especificación', 'category', false, false, 'CIE-11'),
('2B6A', 'Neoplasias malignas de la orofaringe', 'category', false, false, 'CIE-11'),
('2B6A.0', 'Carcinoma de células escamosas de la orofaringe', 'category', false, false, 'CIE-11'),
('2B6A.Y', 'Otras neoplasias malignas especificadas de la orofaringe', 'category', false, false, 'CIE-11'),
('2B6A.Z', 'Neoplasias malignas de la orofaringe, sin especificación', 'category', false, false, 'CIE-11'),
('2B6B', 'Neoplasias malignas de la nasofaringe', 'category', false, false, 'CIE-11'),
('2B6B.0', 'Carcinoma de células escamosas de la nasofaringe', 'category', false, false, 'CIE-11'),
('2B6B.1', 'Neoplasias epiteliales malignas de la nasofaringe, tipo no especificado', 'category', false, false, 'CIE-11'),
('2B6B.2', 'Neoplasias malignas de la amígdala faríngea', 'category', false, false, 'CIE-11'),
('2B6B.20', 'Carcinoma de células escamosas de la amígdala faríngea', 'category', false, false, 'CIE-11'),
('2B6B.21', 'Neoplasia epitelial maligna de la amígdala faríngea, de otros tipos y de tipo no especificado', 'category', false, false, 'CIE-11'),
('2B6B.2Y', 'Otras neoplasias malignas especificadas de la amígdala faríngea', 'category', false, false, 'CIE-11'),
('2B6B.2Z', 'Neoplasias malignas de la amígdala faríngea, sin especificación', 'category', false, false, 'CIE-11'),
('2B6B.Y', 'Otras neoplasias malignas especificadas de la nasofaringe', 'category', false, false, 'CIE-11'),
('2B6B.Z', 'Neoplasia malignas de la nasofaringe, sin especificación', 'category', false, false, 'CIE-11'),
('2B6C', 'Neoplasias malignas del seno piriforme', 'category', false, false, 'CIE-11'),
('2B6C.0', 'Carcinoma de células escamosas del seno piriforme', 'category', false, false, 'CIE-11'),
('2B6C.Y', 'Otras neoplasias malignas especificadas del seno piriforme', 'category', false, false, 'CIE-11'),
('2B6C.Z', 'Neoplasias malignas del seno piriforme, sin especificación', 'category', false, false, 'CIE-11'),
('2B6D', 'Neoplasia malignas de la hipofaringe', 'category', false, false, 'CIE-11'),
('2B6D.0', 'Carcinoma de células escamosas de la hipofaringe y variantes', 'category', false, false, 'CIE-11'),
('2B6D.Y', 'Otras neoplasia malignas especificadas de la hipofaringe', 'category', false, false, 'CIE-11'),
('2B6D.Z', 'Neoplasia malignas de la hipofaringe, sin especificación', 'category', false, false, 'CIE-11'),
('2B6E', 'Neoplasias malignas de los labios, la cavidad bucal o la faringe, otras localizaciones o localizaciones mal definidas', 'category', false, false, 'CIE-11'),
('2B6E.0', 'Carcinoma de células escamosas del labio, la cavidad bucal o la faringe, otras localizaciones o localizaciones mal definidas', 'category', false, false, 'CIE-11'),
('2B6E.Y', 'Otras neoplasias malignas especificadas de los labios, la cavidad bucal o la faringe, otras localizaciones o localizaciones mal definidas', 'category', false, false, 'CIE-11'),
('2B6E.Z', 'Neoplasias malignas de los labios, la cavidad bucal o la faringe, otras localizaciones o localizaciones mal definidas, sin especificación', 'category', false, false, 'CIE-11'),
('2B6Y', 'Otras neoplasias malignas especificadas del labio, la cavidad bucal o la faringe', 'category', false, false, 'CIE-11'),
('2B70', 'Neoplasias malignas del esófago', 'category', false, false, 'CIE-11'),
('2B70.0', 'Adenocarcinoma del esófago', 'category', false, false, 'CIE-11'),
('2B70.00', 'Adenocarcinoma de Barrett', 'category', false, false, 'CIE-11'),
('2B70.0Y', 'Otro adenocarcinoma especificado del esófago', 'category', false, false, 'CIE-11'),
('2B70.0Z', 'Adenocarcinoma del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('2B70.1', 'Carcinoma de células escamosas del esófago', 'category', false, false, 'CIE-11'),
('2B70.Y', 'Otras neoplasias malignas especificadas del esófago', 'category', false, false, 'CIE-11'),
('2B70.Z', 'Neoplasias malignas del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('2B71', 'Neoplasias malignas de la unión esofagogástrica', 'category', false, false, 'CIE-11'),
('2B71.0', 'Adenocarcinoma de la unión esofagogástrica', 'category', false, false, 'CIE-11'),
('2B71.Y', 'Otra neoplasia maligna específicada de la unión esofagogástrica', 'category', false, false, 'CIE-11'),
('2B71.Z', 'Neoplasia maligna de la unión esofagogástrica, sin especificación', 'category', false, false, 'CIE-11'),
('2B72', 'Neoplasias malignas del estómago', 'category', false, false, 'CIE-11'),
('2B72.0', 'Adenocarcinoma de estómago', 'category', false, false, 'CIE-11'),
('2B72.1', 'Neoplasia neuroendocrina maligna del estómago', 'category', false, false, 'CIE-11'),
('2B72.Y', 'Otras neoplasias malignas especificadas del estómago', 'category', false, false, 'CIE-11'),
('2B72.Z', 'Neoplasias malignas del estómago, sin especificación', 'category', false, false, 'CIE-11'),
('2B80', 'Neoplasias malignas de intestino delgado', 'category', false, false, 'CIE-11'),
('2B80.0', 'Neoplasias malignas de duodeno', 'category', false, false, 'CIE-11'),
('2B80.00', 'Adenocarcinoma del duodeno', 'category', false, false, 'CIE-11'),
('2B80.01', 'Neoplasia neuroendocrina de duodeno', 'category', false, false, 'CIE-11'),
('2B80.0Y', 'Otras neoplasias malignas especificadas de duodeno', 'category', false, false, 'CIE-11'),
('2B80.0Z', 'Neoplasias malignas de duodeno, sin especificación', 'category', false, false, 'CIE-11'),
('2B80.1', 'Neoplasias malignas del yeyuno o del íleon', 'category', false, false, 'CIE-11'),
('2B80.10', 'Adenocarcinoma del yeyuno o del íleon', 'category', false, false, 'CIE-11'),
('2B80.11', 'Neoplasias neuroendocrinas del yeyuno o del íleon', 'category', false, false, 'CIE-11'),
('2B80.1Y', 'Otras neoplasias malignas del yeyuno o del íleon', 'category', false, false, 'CIE-11'),
('2B80.1Z', 'Neoplasias malignas del yeyuno o del íleon, sin especificación', 'category', false, false, 'CIE-11'),
('2B80.2', 'Neoplasia maligna del intestino delgado, sitio no especificado', 'category', false, false, 'CIE-11'),
('2B80.20', 'Adenocarcinoma del intestino delgado, sitio no especificado', 'category', false, false, 'CIE-11'),
('2B80.21', 'Neoplasia neuroendocrina del intestino delgado, sitio no especificado', 'category', false, false, 'CIE-11'),
('2B80.2Y', 'Otra neoplasia maligna especificada del intestino delgado, localización no especificada', 'category', false, false, 'CIE-11'),
('2B80.Y', 'Otras neoplasias malignas especificadas de intestino delgado', 'category', false, false, 'CIE-11'),
('2B80.Z', 'Neoplasias malignas de intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('2B81', 'Neoplasias malignas del apéndice', 'category', false, false, 'CIE-11'),
('2B81.0', 'Adenocarcinoma del apéndice', 'category', false, false, 'CIE-11'),
('2B81.00', 'Adenocarcinoma mucinoso del apéndice', 'category', false, false, 'CIE-11'),
('2B81.2', 'Neoplasias neuroendocrinas del apéndice', 'category', false, false, 'CIE-11'),
('2B81.Y', 'Otras neoplasias malignas especificadas del apéndice', 'category', false, false, 'CIE-11'),
('2B81.Z', 'Neoplasias malignas del apéndice, sin especificación', 'category', false, false, 'CIE-11'),
('2B90', 'Neoplasias malignas del colon', 'category', false, false, 'CIE-11'),
('2B90.0', 'Neoplasia maligna de colon ascendente y del ángulo derecho del colon', 'category', false, false, 'CIE-11'),
('2B90.00', 'Adenocarcinoma del colon ascendente o del ángulo cólico derecho', 'category', false, false, 'CIE-11'),
('2B90.0Y', 'Otra neoplasia maligna especificada del colon ascendente y del ángulo cólico derecho', 'category', false, false, 'CIE-11'),
('2B90.0Z', 'Neoplasia maligna especificada del colon ascendente y del ángulo cólico derecho, sin especificación', 'category', false, false, 'CIE-11'),
('2B90.1', 'Neoplasia maligna del colon descendente y del ángulo esplénico del colon', 'category', false, false, 'CIE-11'),
('2B90.10', 'Adenocarcinoma del colon descendente o del ángulo cólico izquierdo', 'category', false, false, 'CIE-11'),
('2B90.1Y', 'Otra neoplasia maligna especificada del colon descendente y del ángulo esplénico del colon', 'category', false, false, 'CIE-11'),
('2B90.1Z', 'Neoplasia maligna del colon descendente y del ángulo esplénico del colon, sin especificación', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
