-- CIE11 Import Part 20
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('GB5Z', 'Nefropatías tubulointersticiales, sin especificación', 'category', false, false, 'CIE-11'),
('GB60', 'Insuficiencia renal aguda', 'category', false, false, 'CIE-11'),
('GB60.0', 'Insuficiencia renal aguda de grado 1', 'category', false, false, 'CIE-11'),
('GB60.1', 'Insuficiencia renal aguda de grado 2', 'category', false, false, 'CIE-11'),
('GB60.2', 'Insuficiencia renal aguda de grado 3', 'category', false, false, 'CIE-11'),
('GB60.Y', 'Otra insuficiencia renal aguda especificada', 'category', false, false, 'CIE-11'),
('GB60.Z', 'Insuficiencia renal aguda, sin especificación', 'category', false, false, 'CIE-11'),
('GB61', 'Enfermedad renal crónica', 'category', false, false, 'CIE-11'),
('GB61.0', 'Enfermedad renal crónica de grado 1', 'category', false, false, 'CIE-11'),
('GB61.1', 'Insuficiencia renal crónica de grado 2', 'category', false, false, 'CIE-11'),
('GB61.2', 'Insuficiencia renal crónica de grado 3a', 'category', false, false, 'CIE-11'),
('GB61.3', 'Insuficiencia renal crónica de grado 3b', 'category', false, false, 'CIE-11'),
('GB61.4', 'Insuficiencia renal crónica de grado 4', 'category', false, false, 'CIE-11'),
('GB61.5', 'Enfermedad renal crónica de grado 5', 'category', false, false, 'CIE-11'),
('GB61.Z', 'Enfermedad renal crónica, sin especificación de grado', 'category', false, false, 'CIE-11'),
('GB6Z', 'Insuficiencia renal, sin especificación', 'category', false, false, 'CIE-11'),
('GB70', 'Cálculo en las vías urinarias altas', 'category', false, false, 'CIE-11'),
('GB70.0', 'Cálculo en el riñón', 'category', false, false, 'CIE-11'),
('GB70.00', 'cálculo coraliforme del riñón', 'category', false, false, 'CIE-11'),
('GB70.0Y', 'Otro cálculo especificado del riñón', 'category', false, false, 'CIE-11'),
('GB70.0Z', 'Cálculo del riñón, sin especificación', 'category', false, false, 'CIE-11'),
('GB70.1', 'Cálculo en el uréter', 'category', false, false, 'CIE-11'),
('GB70.Z', 'Cálculo en las vías urinarias altas, sin especificación', 'category', false, false, 'CIE-11'),
('GB71', 'Cálculo en las vías urinarias bajas', 'category', false, false, 'CIE-11'),
('GB71.0', 'Cálculo en la vejiga', 'category', false, false, 'CIE-11'),
('GB71.1', 'Cálculo en la uretra', 'category', false, false, 'CIE-11'),
('GB71.2', 'Cálculo en segmento intestinal para derivación urinaria', 'category', false, false, 'CIE-11'),
('GB71.Z', 'Cálculo en las vías urinarias bajas, sin especificación', 'category', false, false, 'CIE-11'),
('GB7Z', 'Urolitiasis, sin especificación', 'category', false, false, 'CIE-11'),
('GB80', 'Nefropatía quística no genética ni familiar', 'category', false, false, 'CIE-11'),
('GB80.0', 'Quiste renal simple', 'category', false, false, 'CIE-11'),
('GB80.1', 'Quiste renal complejo', 'category', false, false, 'CIE-11'),
('GB80.2', 'Urinoma subescapular o perirrenal', 'category', false, false, 'CIE-11'),
('GB80.Y', 'Otra nefropatía quística no genética ni familiar especificada', 'category', false, false, 'CIE-11'),
('GB80.Z', 'Nefropatía quística no genética ni familiar, sin especificación', 'category', false, false, 'CIE-11'),
('GB81', 'Poliquistosis renal autosómica dominante', 'category', false, false, 'CIE-11'),
('GB82', 'Enfermedad tubulointersticial autosómica dominante', 'category', false, false, 'CIE-11'),
('GB83', 'Nefronoptisis', 'category', false, false, 'CIE-11'),
('GB8Y', 'Otra nefropatía quística o displásica especificada', 'category', false, false, 'CIE-11'),
('GB8Z', 'Nefropatía quística o displásica, sin especificación', 'category', false, false, 'CIE-11'),
('GB90', 'Algunos trastornos especificados del riñón o del uréter', 'category', false, false, 'CIE-11'),
('GB90.0', 'Nefroptosis', 'category', false, false, 'CIE-11'),
('GB90.1', 'Hidrouréter', 'category', false, false, 'CIE-11'),
('GB90.2', 'Torsión o desviación ureteral sin obstrucción', 'category', false, false, 'CIE-11'),
('GB90.3', 'Isquemia o infarto de riñón', 'category', false, false, 'CIE-11'),
('GB90.4', 'Trastornos funcionales de los túbulos renales', 'category', false, false, 'CIE-11'),
('GB90.40', 'Hipotonía y cistinuria de tipo 1', 'category', false, false, 'CIE-11'),
('GB90.41', 'Seudohipoaldosteronismo de tipo 1', 'category', false, false, 'CIE-11'),
('GB90.42', 'Síndrome de Fanconi', 'category', false, false, 'CIE-11'),
('GB90.43', 'Síndrome de Bartter', 'category', false, false, 'CIE-11'),
('GB90.44', 'Acidosis tubular renal', 'category', false, false, 'CIE-11'),
('GB90.45', 'Glucosuria renal', 'category', false, false, 'CIE-11'),
('GB90.46', 'Trastornos tubulares del transporte de sodio o potasio', 'category', false, false, 'CIE-11'),
('GB90.47', 'Aminoaciduria', 'category', false, false, 'CIE-11'),
('GB90.48', 'Trastornos de la excreción de calcio o fosfato', 'category', false, false, 'CIE-11'),
('GB90.49', 'Hipocalciuria renal', 'category', false, false, 'CIE-11'),
('GB90.4A', 'Diabetes insípida nefrógena', 'category', false, false, 'CIE-11'),
('GB90.4Y', 'Otros trastornos funcionales especificados de los túbulos renales', 'category', false, false, 'CIE-11'),
('GB90.4Z', 'Trastornos funcionales de los túbulos renales, sin especificación', 'category', false, false, 'CIE-11'),
('GB90.Y', 'Algunos otros trastornos especificados del riñón o del uréter', 'category', false, false, 'CIE-11'),
('GC00', 'Cistitis', 'category', false, false, 'CIE-11'),
('GC00.0', 'Trigonitis', 'category', false, false, 'CIE-11'),
('GC00.1', 'Cistitis infecciosa', 'category', false, false, 'CIE-11'),
('GC00.2', 'Vejiga urinaria contraída', 'category', false, false, 'CIE-11'),
('GC00.3', 'Cistitis intersticial', 'category', false, false, 'CIE-11'),
('GC00.Y', 'Otra cistitis especificada', 'category', false, false, 'CIE-11'),
('GC00.Z', 'Cistitis, sin especificación', 'category', false, false, 'CIE-11'),
('GC01', 'Otros trastornos de la vejiga urinaria', 'category', false, false, 'CIE-11'),
('GC01.0', 'Obstrucción del cuello vesical', 'category', false, false, 'CIE-11'),
('GC01.1', 'Fístula vesical, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('GC01.2', 'Divertículo vesical', 'category', false, false, 'CIE-11'),
('GC01.3', 'Rotura de la vejiga urinaria no traumática', 'category', false, false, 'CIE-11'),
('GC01.4', 'Disfunción neuromuscular de la vejiga urinaria, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('GC01.Y', 'Otros trastornos especificados de la vejiga urinaria', 'category', false, false, 'CIE-11'),
('GC01.Z', 'Otros trastornos de la vejiga urinaria, sin especificación', 'category', false, false, 'CIE-11'),
('GC02', 'Uretritis o síndrome uretral', 'category', false, false, 'CIE-11'),
('GC02.0', 'Absceso uretral', 'category', false, false, 'CIE-11'),
('GC02.1', 'Uretritis inespecífica', 'category', false, false, 'CIE-11'),
('GC02.Y', 'Otra uretritis o síndrome uretral especificados', 'category', false, false, 'CIE-11'),
('GC02.Z', 'Uretritis o síndrome uretral, sin especificación', 'category', false, false, 'CIE-11'),
('GC03', 'Estenosis uretral', 'category', false, false, 'CIE-11'),
('GC04', 'Fístula del tracto genitourinario', 'category', false, false, 'CIE-11'),
('GC04.0', 'Fístula uretral', 'category', false, false, 'CIE-11'),
('GC04.1', 'Fístulas del aparato genital femenino', 'category', false, false, 'CIE-11'),
('GC04.10', 'Fístula vesicovaginal', 'category', false, false, 'CIE-11'),
('GC04.11', 'Fístula del intestino delgado a la vagina', 'category', false, false, 'CIE-11'),
('GC04.12', 'Fístula del intestino grueso a la vagina', 'category', false, false, 'CIE-11'),
('GC04.13', 'Fístulas del aparato genital femenino a la piel', 'category', false, false, 'CIE-11'),
('GC04.14', 'Fístula uretrovaginal', 'category', false, false, 'CIE-11'),
('GC04.15', 'Fístula uretrovesicovaginal combinada', 'category', false, false, 'CIE-11'),
('GC04.16', 'Fístula rectovaginal', 'category', false, false, 'CIE-11'),
('GC04.17', 'Fístula vesicouterina con cicatrización importante o pérdida tisular extensa', 'category', false, false, 'CIE-11'),
('GC04.18', 'Otra fístula urinaria combinada con cicatrización importante o pérdida tisular extensa', 'category', false, false, 'CIE-11'),
('GC04.19', 'Fístula combinada urinaria y rectal (cloaca incluida), con cicatrización importante o pérdida tisular extensa', 'category', false, false, 'CIE-11'),
('GC04.1A', 'Estenosis vaginal o ginatresia relacionada con fístula obstétrica', 'category', false, false, 'CIE-11'),
('GC04.1Y', 'Otras fístulas del aparato genital femenino', 'category', false, false, 'CIE-11'),
('GC04.1Z', 'Fístulas del aparato genital femenino, sin especificación', 'category', false, false, 'CIE-11'),
('GC04.2', 'Fístula ureteral', 'category', false, false, 'CIE-11'),
('GC04.Y', 'Otra fístula especificada del tracto genitourinario', 'category', false, false, 'CIE-11'),
('GC04.Z', 'Fístula del tracto genitourinario, sin especificación', 'category', false, false, 'CIE-11'),
('GC05', 'Prolapso de mucosa uretral', 'category', false, false, 'CIE-11'),
('GC06', 'Divertículo uretral', 'category', false, false, 'CIE-11'),
('GC07', 'Carúncula uretral', 'category', false, false, 'CIE-11'),
('GC08', 'Infección urinaria, localización no especificada', 'category', false, false, 'CIE-11'),
('GC08.0', 'Infección urinaria por Escherichia coli, localización no especificada', 'category', false, false, 'CIE-11'),
('GC08.1', 'Infección urinaria por Klebsiella pneumoniae, localización no especificada', 'category', false, false, 'CIE-11'),
('GC08.2', 'Infección urinaria por Proteus, localización no especificada', 'category', false, false, 'CIE-11'),
('GC08.Y', 'Infección urinaria por otro microbio patógeno, localización no especificada', 'category', false, false, 'CIE-11'),
('GC08.Z', 'Infección urinaria, localización y microbio patógeno no especificados', 'category', false, false, 'CIE-11'),
('GC0Y', 'Otras enfermedades del sistema urinario', 'category', false, false, 'CIE-11'),
('GC2Z', 'Enfermedades del sistema urinario, sin especificación', 'category', false, false, 'CIE-11'),
('GC40', 'Prolapso de órgano pélvico', 'category', false, false, 'CIE-11'),
('GC40.0', 'Prolapso de pared anterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.00', 'Prolapso incompleto de pared anterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.01', 'Prolapso completo de pared anterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.0Z', 'Prolapso de pared anterior de la vagina, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.1', 'Prolapso de pared posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.10', 'Prolapso incompleto de pared posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.11', 'Prolapso completo de pared posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.1Z', 'Prolapso de pared posterior de la vagina, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.2', 'Prolapso de cúpula vaginal', 'category', false, false, 'CIE-11'),
('GC40.20', 'Prolapso incompleto de cúpula vaginal', 'category', false, false, 'CIE-11'),
('GC40.21', 'Prolapso completo de cúpula vaginal', 'category', false, false, 'CIE-11'),
('GC40.2Z', 'Prolapso de cúpula vaginal, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.3', 'Prolapso uterovaginal', 'category', false, false, 'CIE-11'),
('GC40.30', 'Prolapso uterovaginal incompleto', 'category', false, false, 'CIE-11'),
('GC40.31', 'Prolapso uterino incompleto con prolapso de la pared anterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.32', 'Prolapso uterino incompleto con prolapso de la pared posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.33', 'Prolapso uterino incompleto con prolapso de las paredes anterior y posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.34', 'Prolapso uterovaginal completo', 'category', false, false, 'CIE-11'),
('GC40.35', 'Prolapso uterino completo con prolapso de la pared anterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.36', 'Prolapso uterino completo con prolapso de la pared posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.37', 'Prolapso uterino completo con prolapso de las paredes anterior y posterior de la vagina', 'category', false, false, 'CIE-11'),
('GC40.3Z', 'Prolapso uterovaginal, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.4', 'Alteración muscular del suelo de la pelvis', 'category', false, false, 'CIE-11'),
('GC40.40', 'Avulsión del elevador del ano en la sínfisis púbica', 'category', false, false, 'CIE-11'),
('GC40.4Y', 'Otra alteración muscular especificada del suelo de la pelvis', 'category', false, false, 'CIE-11'),
('GC40.4Z', 'Alteración muscular del suelo de la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.5', 'Incontinencia urinaria asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.50', 'Incontinencia urinaria de esfuerzo asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.51', 'Incontinencia urinaria de urgencia asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.52', 'Incontinencia urinaria mixta asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.53', 'Incontinencia urinaria por rebosamiento asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.54', 'Incontinencia urinaria SAI con prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.6', 'Trastornos funcionales de la vejiga asociados a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.60', 'Vejiga hiperactiva asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.6Y', 'Otros trastornos funcionales especificados de la vejiga asociados a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC40.6Z', 'Trastornos funcionales de la vejiga asociados a prolapso de órganos pélvicos, sin especificación', 'category', false, false, 'CIE-11'),
('GC40.Z', 'Prolapso de órgano pélvico, sin especificación', 'category', false, false, 'CIE-11'),
('GC41', 'Disfunción anorrectal asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC42', 'Disfunción sexual asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC42.0', 'Disminución de la sensibilidad por laxitud de la vagina o del orificio vaginal', 'category', false, false, 'CIE-11'),
('GC42.1', 'Coito obstruido', 'category', false, false, 'CIE-11'),
('GC4Z', 'Disfunción del suelo pélvico femenino, sin especificación', 'category', false, false, 'CIE-11'),
('GC50', 'Trastornos funcionales de la vejiga SAI', 'category', false, false, 'CIE-11'),
('GC50.0', 'Vejiga hiperactiva', 'category', false, false, 'CIE-11'),
('GC50.1', 'Sensibilidad vesical ausente o disminuida', 'category', false, false, 'CIE-11'),
('GC50.10', 'Sensibilidad vesical ausente o disminuida asociada a prolapso de órganos pélvicos', 'category', false, false, 'CIE-11'),
('GC50.1Y', 'Otra sensibilidad vesical ausente o disminuida especificada', 'category', false, false, 'CIE-11'),
('GC50.1Z', 'Sensibilidad vesical ausente o disminuida, sin especificación', 'category', false, false, 'CIE-11'),
('GC50.Y', 'Otros trastornos funcionales especificados de la vejiga SAI', 'category', false, false, 'CIE-11'),
('GC50.Z', 'Trastornos funcionales de la vejiga SAI, sin especificación', 'category', false, false, 'CIE-11'),
('GC51', 'Mutilación genital femenina', 'category', false, false, 'CIE-11'),
('GC51.0', 'Mutilación genital femenina de tipo 1', 'category', false, false, 'CIE-11'),
('GC51.00', 'Mutilación genital femenina de tipo 1a', 'category', false, false, 'CIE-11'),
('GC51.01', 'Mutilación genital femenina de tipo 1b', 'category', false, false, 'CIE-11'),
('GC51.0Z', 'Mutilación genital femenina de tipo 1, sin especificación', 'category', false, false, 'CIE-11'),
('GC51.1', 'Mutilación genital femenina de tipo 2', 'category', false, false, 'CIE-11'),
('GC51.10', 'Mutilación genital femenina de tipo 2a', 'category', false, false, 'CIE-11'),
('GC51.11', 'Mutilación genital femenina de tipo 2b', 'category', false, false, 'CIE-11'),
('GC51.12', 'Mutilación genital femenina de tipo 2c', 'category', false, false, 'CIE-11'),
('GC51.1Z', 'Mutilación genital femenina de tipo 2, sin especificación', 'category', false, false, 'CIE-11'),
('GC51.2', 'Mutilación genital femenina de tipo 3', 'category', false, false, 'CIE-11'),
('GC51.20', 'Mutilación genital femenina de tipo 3a', 'category', false, false, 'CIE-11'),
('GC51.21', 'Mutilación genital femenina de tipo 3b', 'category', false, false, 'CIE-11'),
('GC51.2Z', 'Mutilación genital femenina de tipo 3, sin especificación', 'category', false, false, 'CIE-11'),
('GC51.3', 'Mutilación genital femenina de tipo 4', 'category', false, false, 'CIE-11'),
('GC51.Z', 'Mutilación genital femenina, sin especificación', 'category', false, false, 'CIE-11'),
('GC70', 'Adherencias vaginales postoperatorias', 'category', false, false, 'CIE-11'),
('GC71', 'Prolapso de la cúpula vaginal tras histerectomía', 'category', false, false, 'CIE-11'),
('GC72', 'Estenosis uretral tras un procedimiento', 'category', false, false, 'CIE-11'),
('GC73', 'Adherencias peritoneales pélvicas tras un procedimiento', 'category', false, false, 'CIE-11'),
('GC74', 'Funcionamiento inadecuado o complicación de estoma externo de vías urinarias', 'category', false, false, 'CIE-11'),
('GC75', 'Funcionamiento inadecuado del segmento aferente de un reservorio urinario continente', 'category', false, false, 'CIE-11'),
('GC76', 'Funcionamiento inadecuado del segmento eferente de un reservorio urinario continente', 'category', false, false, 'CIE-11'),
('GC77', 'Metrorragia tras un procedimiento', 'category', false, false, 'CIE-11'),
('GC78', 'Enfermedad inflamatoria pélvica femenina aguda tras un procedimiento', 'category', false, false, 'CIE-11'),
('GC79', 'Trastornos de reducción mamaria', 'category', false, false, 'CIE-11'),
('GC7A', 'Trastornos de aumento mamario', 'category', false, false, 'CIE-11'),
('GC7B', 'Isquemia o infarto renal tras un procedimiento', 'category', false, false, 'CIE-11'),
('GC7C', 'Defecto de la cicatriz de la cesárea en el útero', 'category', false, false, 'CIE-11'),
('GC8Y', 'Otras enfermedades especificadas del sistema genitourinario', 'category', false, false, 'CIE-11'),
('GC8Z', 'Enfermedades del sistema genitourinario, sin especificación', 'category', false, false, 'CIE-11'),
('HA00', 'Disfunción por deseo sexual hipoactivo', 'category', false, false, 'CIE-11'),
('HA00.0', 'Disfunción por deseo sexual hipoactivo, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA00.1', 'Disfunción por deseo sexual hipoactivo, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA00.2', 'Disfunción por deseo sexual hipoactivo, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA00.3', 'Disfunción por deseo sexual hipoactivo, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA00.Z', 'Disfunción por deseo sexual hipoactivo, sin especificación', 'category', false, false, 'CIE-11'),
('HA01', 'Disfunciones de la excitación sexual', 'category', false, false, 'CIE-11'),
('HA01.0', 'Disfunción de la excitación sexual femenina', 'category', false, false, 'CIE-11'),
('HA01.00', 'Disfunción de la excitación sexual femenina, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA01.01', 'Disfunción de la excitación sexual femenina, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA01.02', 'Disfunción de la excitación sexual femenina, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA01.03', 'Disfunción de la excitación sexual femenina, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA01.0Z', 'Disfunción de la excitación sexual femenina, sin especificación', 'category', false, false, 'CIE-11'),
('HA01.1', 'Disfunción eréctil masculina', 'category', false, false, 'CIE-11'),
('HA01.10', 'Disfunción eréctil masculina, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA01.11', 'Disfunción eréctil masculina, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA01.12', 'Disfunción eréctil masculina, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA01.13', 'Disfunción eréctil masculina, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA01.1Z', 'Disfunción eréctil masculina, sin especificación', 'category', false, false, 'CIE-11'),
('HA01.Y', 'Otras disfunciones especificadas de la excitación sexual', 'category', false, false, 'CIE-11'),
('HA01.Z', 'Disfunciones de la excitación sexual, sin especificación', 'category', false, false, 'CIE-11'),
('HA02', 'Disfunciones orgásmicas', 'category', false, false, 'CIE-11'),
('HA02.0', 'Anorgasmia', 'category', false, false, 'CIE-11'),
('HA02.00', 'Anorgasmia, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA02.01', 'Anorgasmia, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA02.02', 'Anorgasmia, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA02.03', 'Anorgasmia, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA02.0Z', 'Anorgasmia, no especificada', 'category', false, false, 'CIE-11'),
('HA02.Y', 'Otras disfunciones orgásmicas especificadas', 'category', false, false, 'CIE-11'),
('HA02.Z', 'Disfunciones orgásmicas, no especificadas', 'category', false, false, 'CIE-11'),
('HA03', 'Disfunciones eyaculatorias', 'category', false, false, 'CIE-11'),
('HA03.0', 'Eyaculación precoz masculina', 'category', false, false, 'CIE-11'),
('HA03.00', 'Eyaculación precoz masculina, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA03.01', 'Eyaculación precoz masculina, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA03.02', 'Eyaculación precoz masculina, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA03.03', 'Eyaculación precoz masculina, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA03.0Z', 'Eyaculación precoz, sin especificación', 'category', false, false, 'CIE-11'),
('HA03.1', 'Eyaculación retardada masculina', 'category', false, false, 'CIE-11'),
('HA03.10', 'Eyaculación retardada masculina, de toda la vida, generalizada', 'category', false, false, 'CIE-11'),
('HA03.11', 'Eyaculación retardada masculina, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA03.12', 'Eyaculación retardada masculina, adquirida, generalizada', 'category', false, false, 'CIE-11'),
('HA03.13', 'Eyaculación retardada masculina, adquirida, situacional', 'category', false, false, 'CIE-11'),
('HA03.1Z', 'Eyaculación retardada masculina, sin especificación', 'category', false, false, 'CIE-11'),
('HA03.Y', 'Otras disfunciones eyaculatorias especificadas', 'category', false, false, 'CIE-11'),
('HA03.Z', 'Disfunciones eyaculatorias, sin especificación', 'category', false, false, 'CIE-11'),
('HA0Y', 'Otras disfunciones sexuales especificadas', 'category', false, false, 'CIE-11'),
('HA0Z', 'Disfunciones sexuales, sin especificación', 'category', false, false, 'CIE-11'),
('HA20', 'Trastorno sexual por dolor asociado a la penetración', 'category', false, false, 'CIE-11'),
('HA20.0', 'Trastorno sexual por dolor asociado a la penetración, de toda la vida, generalizado', 'category', false, false, 'CIE-11'),
('HA20.1', 'Trastorno sexual por dolor asociado a la penetración, de toda la vida, situacional', 'category', false, false, 'CIE-11'),
('HA20.2', 'Trastorno sexual por dolor asociado a la penetración, adquirido, generalizado', 'category', false, false, 'CIE-11'),
('HA20.3', 'Trastorno sexual por dolor asociado a la penetración, adquirido, situacional', 'category', false, false, 'CIE-11'),
('HA20.Z', 'Trastorno sexual por dolor asociado a la penetración, sin especificación', 'category', false, false, 'CIE-11'),
('HA2Y', 'Otros trastornos sexuales por dolor especificados', 'category', false, false, 'CIE-11'),
('HA2Z', 'Trastornos sexuales por dolor, sin especificación', 'category', false, false, 'CIE-11'),
('HA40', 'Consideraciones etiológicas en las disfunciones sexuales y los trastornos sexuales por dolor', 'category', false, false, 'CIE-11'),
('HA40.0', 'Consideraciones etiológicas asociadas con una afección médica, una lesión o los efectos de una intervención quirúrgica o radioterapia', 'category', false, false, 'CIE-11'),
('HA40.1', 'Consideraciones etiológicas asociadas con factores psicológicos o de comportamiento, incluidos los trastornos mentales', 'category', false, false, 'CIE-11'),
('HA40.2', 'Consideraciones etiológicas asociadas con el consumo de medicamentos o sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('HA40.3', 'Consideraciones etiológicas asociadas con la falta de conocimiento o experiencia', 'category', false, false, 'CIE-11'),
('HA40.4', 'Consideraciones etiológicas asociadas con factores de la relación de pareja', 'category', false, false, 'CIE-11'),
('HA40.5', 'Consideraciones etiológicas asociadas con factores culturales', 'category', false, false, 'CIE-11'),
('HA40.Y', 'Otras consideraciones etiológicas especificadas en las disfunciones sexuales y los trastornos sexuales por dolor', 'category', false, false, 'CIE-11'),
('HA60', 'Discordancia de género en la adolescencia o adultez', 'category', false, false, 'CIE-11'),
('HA61', 'Discordancia de género en la infancia', 'category', false, false, 'CIE-11'),
('HA6Z', 'Discordancia de género, sin especificación', 'category', false, false, 'CIE-11'),
('HA8Y', 'Otras condiciones especificadas relacionadas con la salud sexual', 'category', false, false, 'CIE-11'),
('HA8Z', 'Condiciones relacionadas con la salud sexual, sin especificación', 'category', false, false, 'CIE-11'),
('JA00', 'Aborto', 'category', false, false, 'CIE-11'),
('JA00.0', 'Aborto espontáneo', 'category', false, false, 'CIE-11'),
('JA00.00', 'Aborto espontáneo, incompleto, complicado por infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.01', 'Aborto espontáneo incompleto, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.02', 'Aborto espontáneo incompleto, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.03', 'Aborto espontáneo incompleto, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.04', 'Aborto espontáneo incompleto sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.05', 'Aborto espontáneo, completo o no especificado, con infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.06', 'Aborto espontáneo, completo o no especificado, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.07', 'Aborto espontáneo, completo o no especificado, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.08', 'Aborto espontáneo, completo o no especificado, con otras complicaciones o las no especificadas', 'category', false, false, 'CIE-11'),
('JA00.09', 'Aborto espontáneo, completo o no especificado, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.1', 'Aborto provocado', 'category', false, false, 'CIE-11'),
('JA00.10', 'Aborto provocado incompleto, complicado por infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.11', 'Aborto provocado incompleto, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.12', 'Aborto provocado incompleto, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.13', 'Aborto provocado incompleto, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.14', 'Aborto provocado incompleto, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.15', 'Aborto provocado, completo o no especificado, complicado por infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.16', 'Aborto provocado, completo o no especificado complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.17', 'Aborto provocado, completo o no especificado, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.18', 'Aborto inducido, completo o no especificado, con otra complicación', 'category', false, false, 'CIE-11'),
('JA00.19', 'Aborto inducido, completo o no especificado, sin complicación', 'category', false, false, 'CIE-11'),
('JA00.2', 'Aborto no especificado', 'category', false, false, 'CIE-11'),
('JA00.20', 'Aborto no especificado, incompleto, con infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.21', 'Aborto no especificado, incompleto, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.22', 'Aborto no especificado, incompleto, complicado por embolia', 'category', false, false, 'CIE-11'),
('JA00.23', 'Aborto no especificado, incompleto, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.24', 'Aborto no especificado, incompleto, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.25', 'Aborto no especificado, completo o sin especificación, con infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.26', 'Aborto no especificado, completo o sin especificación, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.27', 'Aborto no especificado, completo o sin especificación, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.28', 'Aborto no especificado, completo o sin especificación, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.29', 'Aborto no especificado, completo o sin especificación, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.3', 'Intento de aborto fallido', 'category', false, false, 'CIE-11'),
('JA00.30', 'Aborto médico fallido, complicado por infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.31', 'Aborto médico fallido, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.32', 'Aborto médico fallido, complicado por una embolia', 'category', false, false, 'CIE-11'),
('JA00.33', 'Aborto médico fallido, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.34', 'Intento de aborto médico fallido, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA00.35', 'Otro intento de aborto fallido o no especificado, complicado por una infección pélvica o de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA00.36', 'Otro intento de aborto fallido o no especificado, complicado por hemorragia prolongada o excesiva', 'category', false, false, 'CIE-11'),
('JA00.37', 'Otro intento de aborto fallido o no especificado, complicado por embolia', 'category', false, false, 'CIE-11'),
('JA00.38', 'Otro intento de aborto fallido o no especificado, con complicaciones de otro tipo o no especificadas', 'category', false, false, 'CIE-11'),
('JA00.39', 'Otro intento de aborto fallido o no especificado, sin complicaciones', 'category', false, false, 'CIE-11'),
('JA01', 'Embarazo ectópico', 'category', false, false, 'CIE-11'),
('JA01.0', 'Embarazo abdominal', 'category', false, false, 'CIE-11'),
('JA01.1', 'Embarazo tubárico', 'category', false, false, 'CIE-11'),
('JA01.2', 'Embarazo ovárico', 'category', false, false, 'CIE-11'),
('JA01.Y', 'Otro embarazo ectópico especificado', 'category', false, false, 'CIE-11'),
('JA01.Z', 'Embarazo ectópico, sin especificación', 'category', false, false, 'CIE-11'),
('JA02', 'Embarazo molar', 'category', false, false, 'CIE-11'),
('JA02.0', 'Mola hidatiforme completa', 'category', false, false, 'CIE-11'),
('JA02.1', 'Mola hidatiforme incompleta o parcial', 'category', false, false, 'CIE-11'),
('JA02.Y', 'Otro embarazo molar especificado', 'category', false, false, 'CIE-11'),
('JA02.Z', 'Embarazo molar, sin especificación', 'category', false, false, 'CIE-11'),
('JA03', 'Aborto retenido', 'category', false, false, 'CIE-11'),
('JA04', 'Óvulo sin desarrollo embrionario o mola no hidatiforme', 'category', false, false, 'CIE-11'),
('JA05', 'Complicaciones después de un aborto, embarazo ectópico o molar', 'category', false, false, 'CIE-11'),
('JA05.0', 'Infección pélvica o del aparato genital después de un aborto, embarazo ectópico o molar', 'category', false, false, 'CIE-11'),
('JA05.1', 'Hemorragia prolongada o excesiva tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.2', 'Embolia después de un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.3', 'Choque tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.4', 'Insuficiencia renal tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.5', 'Trastornos metabólicos tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.6', 'Lesión de los órganos y tejidos genitales tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.7', 'Otras complicaciones venosas tras un aborto, embarazo ectópico o embarazo molar', 'category', false, false, 'CIE-11'),
('JA05.Y', 'Otras complicaciones especificadas después de un aborto, embarazo ectópico o molar', 'category', false, false, 'CIE-11'),
('JA05.Z', 'Complicaciones después de un aborto, embarazo ectópico o molar, sin especificación', 'category', false, false, 'CIE-11'),
('JA0Z', 'Embarazo que finaliza en aborto, sin especificación', 'category', false, false, 'CIE-11'),
('JA20', 'Hipertensión preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.0', 'Hipertensión esencial preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.1', 'Cardiopatía hipertensiva preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.2', 'Nefropatía hipertensiva preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.3', 'Enfermedad cardíaca o renal hipertensiva preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.4', 'Hipertensión secundaria preexistente que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.Y', 'Otro tipo de hipertensión preexistente especificada que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA20.Z', 'Hipertensión preexistente que complica el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JA21', 'Preeclampsia añadida a hipertensión crónica', 'category', false, false, 'CIE-11'),
('JA22', 'Edema o proteinuria gestacional sin hipertensión', 'category', false, false, 'CIE-11'),
('JA22.0', 'Proteinuria gestacional sin hipertensión', 'category', false, false, 'CIE-11'),
('JA22.1', 'Edema gestacional sin hipertensión', 'category', false, false, 'CIE-11'),
('JA22.2', 'Edema gestacional con proteinuria sin hipertensión', 'category', false, false, 'CIE-11'),
('JA23', 'Hipertensión gestacional', 'category', false, false, 'CIE-11'),
('JA24', 'Preeclampsia', 'category', false, false, 'CIE-11'),
('JA24.0', 'Preeclampsia leve a moderada', 'category', false, false, 'CIE-11'),
('JA24.1', 'Preeclampsia severa', 'category', false, false, 'CIE-11'),
('JA24.2', 'Síndrome HELLP', 'category', false, false, 'CIE-11'),
('JA24.Z', 'Preeclampsia, sin especificación', 'category', false, false, 'CIE-11'),
('JA25', 'Eclampsia', 'category', false, false, 'CIE-11'),
('JA25.0', 'Eclampsia en el embarazo', 'category', false, false, 'CIE-11'),
('JA25.1', 'Eclampsia durante el trabajo de parto', 'category', false, false, 'CIE-11'),
('JA25.2', 'Eclampsia en el puerperio', 'category', false, false, 'CIE-11'),
('JA25.3', 'Eclampsia, momento no especificado', 'category', false, false, 'CIE-11'),
('JA2Z', 'Edema, proteinuria o trastornos hipertensivos en el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JA40', 'Hemorragia al comienzo del embarazo', 'category', false, false, 'CIE-11'),
('JA40.0', 'Amenaza de aborto', 'category', false, false, 'CIE-11'),
('JA40.Y', 'Otra hemorragia especificada al comienzo del embarazo', 'category', false, false, 'CIE-11'),
('JA40.Z', 'Hemorragia al comienzo del embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA41', 'Hemorragia antes del parto', 'category', false, false, 'CIE-11'),
('JA41.0', 'Hemorragia antes del parto con defecto de coagulación', 'category', false, false, 'CIE-11'),
('JA41.Y', 'Otra hemorragia antes del parto especificada', 'category', false, false, 'CIE-11'),
('JA41.Z', 'Hemorragia antes del parto, sin especificación', 'category', false, false, 'CIE-11'),
('JA42', 'Hemorragia intraparto', 'category', false, false, 'CIE-11'),
('JA42.0', 'Hemorragia intraparto con coagulopatía', 'category', false, false, 'CIE-11'),
('JA42.1', 'Hemorragia intraparto por obstrucción del parto con ruptura uterina', 'category', false, false, 'CIE-11'),
('JA42.2', 'Hemorragia intraparto debida al cese de las contracciones uterinas, sin mención de ruptura uterina', 'category', false, false, 'CIE-11'),
('JA42.Y', 'Otra hemorragia intraparto especificada', 'category', false, false, 'CIE-11'),
('JA42.Z', 'Hemorragia intraparto, sin especificación', 'category', false, false, 'CIE-11'),
('JA43', 'Hemorragia postparto', 'category', false, false, 'CIE-11'),
('JA43.0', 'Hemorragia durante el alumbramiento', 'category', false, false, 'CIE-11'),
('JA43.1', 'Otra hemorragia inmediatamente después del parto', 'category', false, false, 'CIE-11'),
('JA43.2', 'Hemorragia tardía o secundaria después del parto', 'category', false, false, 'CIE-11'),
('JA43.3', 'Trastornos de la coagulación después del parto', 'category', false, false, 'CIE-11'),
('JA43.4', 'Hemorragia tras un parto obstruido, con ruptura uterina', 'category', false, false, 'CIE-11'),
('JA43.5', 'Hemorragia postparto después de un parto obstruido, sin mención de ruptura uterina', 'category', false, false, 'CIE-11'),
('JA43.Y', 'Otra hemorragia postparto especificada', 'category', false, false, 'CIE-11'),
('JA43.Z', 'Hemorragia postparto, sin especificación', 'category', false, false, 'CIE-11'),
('JA4Z', 'Hemorragia obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('JA60', 'Vómitos excesivos en el embarazo', 'category', false, false, 'CIE-11'),
('JA60.0', 'Hiperemesis gravídica leve', 'category', false, false, 'CIE-11'),
('JA60.1', 'Hiperémesis gravídica con trastorno metabólico', 'category', false, false, 'CIE-11'),
('JA60.2', 'Vómitos tardíos del embarazo', 'category', false, false, 'CIE-11'),
('JA60.Y', 'Otros vómitos excesivos en el embarazo especificados', 'category', false, false, 'CIE-11'),
('JA60.Z', 'Vómitos excesivos en el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA61', 'Complicaciones venosas en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.0', 'Venas varicosas de las extremidades inferiores en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.1', 'Várices genitales en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.2', 'Tromboflebitis superficial en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.3', 'Flebotrombosis profunda en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.4', 'Hemorroides en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.5', 'Trombosis venosa cerebral en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.Y', 'Otras complicaciones venosas especificadas en el embarazo', 'category', false, false, 'CIE-11'),
('JA61.Z', 'Complicaciones venosas en el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA62', 'Infección del aparato genitourinario en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.0', 'Infección del riñón en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.1', 'Infección de la vejiga en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.2', 'Infección de la uretra en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.3', 'Infección de otras partes del aparato urinario en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.4', 'Infección del aparato genital en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.Y', 'Otra infección especificada del aparato genitourinario en el embarazo', 'category', false, false, 'CIE-11'),
('JA62.Z', 'Infección del aparato genitourinario en el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA63', 'Diabetes mellitus en el embarazo', 'category', false, false, 'CIE-11'),
('JA63.0', 'Diabetes mellitus de tipo 1 preexistente, en el embarazo', 'category', false, false, 'CIE-11'),
('JA63.1', 'Diabetes mellitus de tipo 2 preexistente, en el embarazo', 'category', false, false, 'CIE-11'),
('JA63.2', 'Diabetes mellitus que aparece por primera vez en el embarazo', 'category', false, false, 'CIE-11'),
('JA63.Y', 'Otras diabetes mellitus especificadas en el embarazo', 'category', false, false, 'CIE-11'),
('JA63.Z', 'Diabetes mellitus en el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA64', 'Desnutrición en el embarazo', 'category', false, false, 'CIE-11'),
('JA65', 'Atención materna por otros trastornos relacionados principalmente con el embarazo', 'category', false, false, 'CIE-11'),
('JA65.0', 'Hepatopatías en el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA65.1', 'Dermatosis del embarazo', 'category', false, false, 'CIE-11'),
('JA65.10', 'Penfigoide gestacional', 'category', false, false, 'CIE-11'),
('JA65.11', 'Prurito del embarazo', 'category', false, false, 'CIE-11'),
('JA65.12', 'Erupción polimorfa del embarazo', 'category', false, false, 'CIE-11'),
('JA65.1Y', 'Otra dermatosis especificada del embarazo', 'category', false, false, 'CIE-11'),
('JA65.1Z', 'Dermatosis del embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA65.2', 'Aumento excesivo de peso en el embarazo', 'category', false, false, 'CIE-11'),
('JA65.3', 'Poco aumento de peso en el embarazo', 'category', false, false, 'CIE-11'),
('JA65.4', 'Atención del embarazo en una abortadora habitual', 'category', false, false, 'CIE-11'),
('JA65.5', 'Dispositivo anticonceptivo intrauterino retenido durante el embarazo', 'category', false, false, 'CIE-11'),
('JA65.6', 'Síndrome de hipotensión materna', 'category', false, false, 'CIE-11'),
('JA65.7', 'Subluxación de la sínfisis púbica en el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JA65.Y', 'Otra atención materna especificada por otros trastornos relacionados principalmente con el embarazo', 'category', false, false, 'CIE-11'),
('JA65.Z', 'Atención materna por otros trastornos relacionados principalmente con el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA66', 'Problemas médicos detectados en el examen prenatal de la madre', 'category', false, false, 'CIE-11'),
('JA66.0', 'Resultado hematológico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.1', 'Resultado bioquímico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.2', 'Resultado citológico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.3', 'Resultado ecográfico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.4', 'Resultado radiológico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.5', 'Resultado genético o cromosómico anormal en el examen prenatal materno', 'category', false, false, 'CIE-11'),
('JA66.Y', 'Otros problemas médicos especificados detectados en el examen prenatal de la madre', 'category', false, false, 'CIE-11'),
('JA66.Z', 'Problemas médicos detectados en el examen prenatal de la madre, sin especificación', 'category', false, false, 'CIE-11'),
('JA67', 'Complicaciones de la anestesia durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.0', 'Complicaciones pulmonares de la anestesia durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.1', 'Complicaciones cardíacas de la anestesia durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.2', 'Complicaciones del sistema nervioso central por efecto de la anestesia durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.3', 'Reacción tóxica a la anestesia local durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.4', 'Cefalea provocada por la anestesia epidural o espinal durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.5', 'Intubación fallida o difícil durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.50', 'Intubación fallida durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.51', 'Dificultad en la intubación durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.5Y', 'Otro(a)(s) intubación fallida o difícil durante el embarazo especificado(a)(s)', 'category', false, false, 'CIE-11'),
('JA67.5Z', 'Intubación fallida o difícil durante el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA67.6', 'Conciencia bajo anestesia general durante el embarazo.', 'category', false, false, 'CIE-11'),
('JA67.Y', 'Otras complicaciones especificadas de la anestesia durante el embarazo', 'category', false, false, 'CIE-11'),
('JA67.Z', 'Complicaciones de la anestesia durante el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA6Z', 'Trastornos maternos relacionados principalmente con el embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('JA80', 'Atención materna relacionada con embarazo múltiple', 'category', false, false, 'CIE-11'),
('JA80.0', 'Embarazo gemelar', 'category', false, false, 'CIE-11'),
('JA80.1', 'Embarazo triple', 'category', false, false, 'CIE-11'),
('JA80.2', 'Embarazo cuádruple', 'category', false, false, 'CIE-11'),
('JA80.Y', 'Otra atención materna especificada relacionada con embarazo múltiple', 'category', false, false, 'CIE-11'),
('JA80.Z', 'Atención materna relacionada con embarazo múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('JA81', 'Atención materna relacionada con complicaciones propias de un embarazo múltiple', 'category', false, false, 'CIE-11'),
('JA81.0', 'Feto papiráceo', 'category', false, false, 'CIE-11'),
('JA81.1', 'Embarazo que continúa después del aborto de uno o varios fetos', 'category', false, false, 'CIE-11'),
('JA81.2', 'Embarazo que continúa tras la muerte intrauterina de un feto o varios', 'category', false, false, 'CIE-11'),
('JA81.3', 'Pérdida del embarazo tras el aborto o la muerte intrauterina de uno o varios fetos', 'category', false, false, 'CIE-11'),
('JA81.Y', 'Otra atención materna especificada relacionada con complicaciones propias de un embarazo múltiple', 'category', false, false, 'CIE-11'),
('JA81.Z', 'Atencion materna relacionada con complicaciones propias de un embarazo múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('JA82', 'Atención materna debida a la presentación anormal del feto', 'category', false, false, 'CIE-11'),
('JA82.0', 'Atención materna por situación fetal inestable', 'category', false, false, 'CIE-11'),
('JA82.1', 'Atención materna por presentación fetal de nalgas', 'category', false, false, 'CIE-11'),
('JA82.2', 'Atención materna por sitiuación fetal transversa u oblicua', 'category', false, false, 'CIE-11'),
('JA82.3', 'Atención materna por presentación fetal de cara, frente o mentón', 'category', false, false, 'CIE-11'),
('JA82.4', 'Atención materna por posición alta de la cabeza fetal a término', 'category', false, false, 'CIE-11'),
('JA82.5', 'Atención materna por embarazo múltiple con presentación anormal de un feto o varios', 'category', false, false, 'CIE-11'),
('JA82.6', 'Atención materna por presentación fetal compuesta', 'category', false, false, 'CIE-11'),
('JA82.Y', 'Atención materna debida a la presentación anormal especificada del feto', 'category', false, false, 'CIE-11'),
('JA82.Z', 'Atención materna debida a la presentación anormal del feto, sin especificación', 'category', false, false, 'CIE-11'),
('JA83', 'Atención materna por desproporción', 'category', false, false, 'CIE-11'),
('JA83.0', 'Atención materna por desproporción debida a una deformidad de la pelvis ósea materna', 'category', false, false, 'CIE-11'),
('JA83.1', 'Atención materna por desproporción debida a la estrechez de toda la pelvis ósea', 'category', false, false, 'CIE-11'),
('JA83.2', 'Atención materna por desproporción debida a un estrecho pélvico superior pequeño', 'category', false, false, 'CIE-11'),
('JA83.3', 'Atención materna por desproporción debida a un estrecho pélvico inferior pequeño', 'category', false, false, 'CIE-11'),
('JA83.4', 'Atención materna por desproporción fetopélvica de origen mixto, materno y fetal', 'category', false, false, 'CIE-11'),
('JA83.5', 'Atención materna por desproporción debida a un feto demasiado grande', 'category', false, false, 'CIE-11'),
('JA83.6', 'Atención materna por desproporción fetopélvica debida a un feto hidrocefálico', 'category', false, false, 'CIE-11'),
('JA83.Y', 'Atención materna por otra desproporción especificada', 'category', false, false, 'CIE-11'),
('JA83.Z', 'Atención materna por desproporción, sin especificación', 'category', false, false, 'CIE-11'),
('JA84', 'Atención materna por anomalía de los órganos reproductores', 'category', false, false, 'CIE-11'),
('JA84.0', 'Atención materna por anomalía congénita del útero', 'category', false, false, 'CIE-11'),
('JA84.1', 'Atención materna por tumor del cuerpo del útero', 'category', false, false, 'CIE-11'),
('JA84.2', 'Atención materna por cicatriz uterina de una operación previa', 'category', false, false, 'CIE-11'),
('JA84.3', 'Atención materna por insuficiencia cervicouterina', 'category', false, false, 'CIE-11'),
('JA84.4', 'Atención materna por anomalía de la vagina', 'category', false, false, 'CIE-11'),
('JA84.5', 'Atención materna por anomalía de la vulva o del perineo', 'category', false, false, 'CIE-11'),
('JA84.Y', 'Atención materna por otra anomalía especificada de los órganos genitales', 'category', false, false, 'CIE-11'),
('JA84.Z', 'Atención materna por anomalía de los órganos genitales, sin especificación', 'category', false, false, 'CIE-11'),
('JA85', 'Atención materna por anomalía o lesión fetal', 'category', false, false, 'CIE-11'),
('JA85.0', 'Atención materna por malformación del sistema nervioso central del feto', 'category', false, false, 'CIE-11'),
('JA85.1', 'Atención materna por anomalía cromosómica del feto', 'category', false, false, 'CIE-11'),
('JA85.2', 'Atención materna por enfermedad hereditaria en el feto', 'category', false, false, 'CIE-11'),
('JA85.3', 'Atención materna por daño fetal debido a enfermedad viral de la madre', 'category', false, false, 'CIE-11'),
('JA85.Y', 'Atención materna por anomalía o lesión fetal especificada', 'category', false, false, 'CIE-11'),
('JA85.Z', 'Atención materna por anomalía o lesión fetal, sin especificación', 'category', false, false, 'CIE-11'),
('JA86', 'Atención materna por otros problemas fetales', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
