-- CIE11 Import Part 27
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('ME92', 'Resultados clínicos anormales en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor', 'category', false, false, 'CIE-11'),
('ME92.0', 'Acuñamiento vertebral', 'category', false, false, 'CIE-11'),
('ME92.1', 'Erosión ósea', 'category', false, false, 'CIE-11'),
('ME92.Y', 'Otros resultados clínicos anormales especificados en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor', 'category', false, false, 'CIE-11'),
('ME92.Z', 'Resultados clínicos anormales en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor, sin especificación', 'category', false, false, 'CIE-11'),
('ME93', 'Lesiones biomecánicas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('ME93.0', 'Disfunción segmentaria y somática', 'category', false, false, 'CIE-11'),
('ME93.1', 'Estenosis del conducto vertebral por subluxación', 'category', false, false, 'CIE-11'),
('ME93.2', 'Estenosis ósea del canal neural', 'category', false, false, 'CIE-11'),
('ME93.3', 'Estenosis del conducto vertebral por tejido conjuntivo', 'category', false, false, 'CIE-11'),
('ME93.4', 'Estenosis del conducto vertebral por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.40', 'Estenosis del conducto vertebral por disco intervertebral, región de la cabeza', 'category', false, false, 'CIE-11'),
('ME93.41', 'Estenosis del conducto vertebral por disco intervertebral, región cervical', 'category', false, false, 'CIE-11'),
('ME93.42', 'Estenosis del conducto vertebral por disco intervertebral, región torácica', 'category', false, false, 'CIE-11'),
('ME93.43', 'Estenosis del conducto vertebral por disco intervertebral, región lumbar', 'category', false, false, 'CIE-11'),
('ME93.44', 'Estenosis del conducto vertebral por disco intervertebral, región sacra', 'category', false, false, 'CIE-11'),
('ME93.4Y', 'Otra estenosis especificada del conducto vertebral por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.4Z', 'Estenosis del conducto vertebral por disco intervertebral, sin especificación', 'category', false, false, 'CIE-11'),
('ME93.5', 'Estenosis ósea y subluxación de los agujeros intervertebrales', 'category', false, false, 'CIE-11'),
('ME93.6', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.Y', 'Otras lesiones biomecánicas especificadas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('ME93.Z', 'Lesiones biomecánicas, no clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('ME9Y', 'Otros hallazgos clínicos especificados en el sistema músculo esquelético', 'category', false, false, 'CIE-11'),
('MF1Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al aparato locomotor', 'category', false, false, 'CIE-11'),
('MF30', 'Tumor o masa en el seno femenino', 'category', false, false, 'CIE-11'),
('MF31', 'Síntoma o molestia relativa a la mama o la lactancia materna', 'category', false, false, 'CIE-11'),
('MF32', 'Síntoma o molestia relativa a la menopausia', 'category', false, false, 'CIE-11'),
('MF33', 'Síntoma o molestia premenstrual', 'category', false, false, 'CIE-11'),
('MF34', 'Síntoma o molestia relativa al embarazo', 'category', false, false, 'CIE-11'),
('MF35', 'Síntoma o molestia puerperal', 'category', false, false, 'CIE-11'),
('MF36', 'Otro síntoma o molestia relativa a la vagina', 'category', false, false, 'CIE-11'),
('MF37', 'Síntoma o molestia relativa al pezón femenino', 'category', false, false, 'CIE-11'),
('MF38', 'Síntoma o molestia relativa a los órganos pélvicos femeninos', 'category', false, false, 'CIE-11'),
('MF39', 'Síntoma o molestia de la vulva', 'category', false, false, 'CIE-11'),
('MF3A', 'Flujo vaginal', 'category', false, false, 'CIE-11'),
('MF3Y', 'Otros síntomas, signos o resultados clínicos anormales del aparato genital femenino', 'category', false, false, 'CIE-11'),
('MF40', 'Problemas de los órganos genitales masculinos en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.0', 'Síntoma o molestia en el pene', 'category', false, false, 'CIE-11'),
('MF40.00', 'Dolor en el pene', 'category', false, false, 'CIE-11'),
('MF40.0Y', 'Síntoma o molestia especificada del pene', 'category', false, false, 'CIE-11'),
('MF40.0Z', 'Síntoma o molestia del pene, sin especificación', 'category', false, false, 'CIE-11'),
('MF40.1', 'Trastornos de la próstata en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.2', 'Síntoma o molestia del escroto o testículo', 'category', false, false, 'CIE-11'),
('MF40.20', 'Dolor escrotal agudo', 'category', false, false, 'CIE-11'),
('MF40.21', 'Dolor testicular', 'category', false, false, 'CIE-11'),
('MF40.2Y', 'Otro síntoma o molestia especificada del escroto o testículo', 'category', false, false, 'CIE-11'),
('MF40.2Z', 'Síntoma o molestia del escroto o testículo, sin especificación', 'category', false, false, 'CIE-11'),
('MF40.3', 'Eyaculación retrógrada', 'category', false, false, 'CIE-11'),
('MF40.Y', 'Otros problemas especificados de los órganos genitales masculinos en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.Z', 'Problemas de los órganos genitales masculinos en enfermedades clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MF41', 'Síntoma o molestia relativa a la función sexual masculina', 'category', false, false, 'CIE-11'),
('MF42', 'Testículo migratorio retráctil', 'category', false, false, 'CIE-11'),
('MF4Y', 'Otros síntomas, signos o resultados clínicos anormales relativos al aparato genital masculino', 'category', false, false, 'CIE-11'),
('MF50', 'Anomalía de la micción', 'category', false, false, 'CIE-11'),
('MF50.0', 'Micción frecuente', 'category', false, false, 'CIE-11'),
('MF50.1', 'Polaquiuria', 'category', false, false, 'CIE-11'),
('MF50.2', 'Incontinencia urinaria', 'category', false, false, 'CIE-11'),
('MF50.20', 'Incontinencia urinaria de esfuerzo', 'category', false, false, 'CIE-11'),
('MF50.21', 'Incontinencia de urgencia', 'category', false, false, 'CIE-11'),
('MF50.22', 'Incontinencia mixta', 'category', false, false, 'CIE-11'),
('MF50.23', 'Incontinencia urinaria funcional', 'category', false, false, 'CIE-11'),
('MF50.24', 'Incontinencia refleja', 'category', false, false, 'CIE-11'),
('MF50.2Y', 'Otra incontinencia urinaria especificada', 'category', false, false, 'CIE-11'),
('MF50.2Z', 'Incontinencia urinaria, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.3', 'Retención de orina', 'category', false, false, 'CIE-11'),
('MF50.4', 'Hematuria', 'category', false, false, 'CIE-11'),
('MF50.40', 'Hematuria macroscópica', 'category', false, false, 'CIE-11'),
('MF50.41', 'Hematuria microscópica', 'category', false, false, 'CIE-11'),
('MF50.4Z', 'Hematuria, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.5', 'Extravasación de la orina', 'category', false, false, 'CIE-11'),
('MF50.6', 'Otras dificultades con la micción', 'category', false, false, 'CIE-11'),
('MF50.60', 'Retardo miccional', 'category', false, false, 'CIE-11'),
('MF50.61', 'Chorro de orina pobre', 'category', false, false, 'CIE-11'),
('MF50.62', 'División del chorro urinario', 'category', false, false, 'CIE-11'),
('MF50.63', 'Necesidad urgente de orinar', 'category', false, false, 'CIE-11'),
('MF50.64', 'Sensación de vaciamiento incompleto de la vejiga', 'category', false, false, 'CIE-11'),
('MF50.65', 'Micción con esfuerzo', 'category', false, false, 'CIE-11'),
('MF50.6Y', 'Otras dificultades con la micción especificadas', 'category', false, false, 'CIE-11'),
('MF50.6Z', 'Otras dificultades con la micción, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.7', 'Disuria', 'category', false, false, 'CIE-11'),
('MF50.8', 'Tenesmo vesical', 'category', false, false, 'CIE-11'),
('MF50.Y', 'Otra anomalía especificada de la micción', 'category', false, false, 'CIE-11'),
('MF50.Z', 'Anomalía de la micción, sin especificación', 'category', false, false, 'CIE-11'),
('MF51', 'Anuria u oliguria', 'category', false, false, 'CIE-11'),
('MF52', 'Dolor de la vejiga', 'category', false, false, 'CIE-11'),
('MF53', 'Uremia extrarrenal', 'category', false, false, 'CIE-11'),
('MF54', 'Cambios macroscópicos del tamaño del riñón', 'category', false, false, 'CIE-11'),
('MF54.0', 'Riñón contraído y liso', 'category', false, false, 'CIE-11'),
('MF54.1', 'Riñón contraído de forma irregular', 'category', false, false, 'CIE-11'),
('MF54.2', 'Riñón pequeño', 'category', false, false, 'CIE-11'),
('MF54.Y', 'Otros cambios macroscópicos especificados del tamaño del riñón', 'category', false, false, 'CIE-11'),
('MF54.Z', 'Cambios macroscópicos del tamaño del riñón, sin especificación', 'category', false, false, 'CIE-11'),
('MF55', 'Poliuria', 'category', false, false, 'CIE-11'),
('MF56', 'Cólico nefrítico', 'category', false, false, 'CIE-11'),
('MF57', 'Síntoma o molestia de la vejiga urinaria', 'category', false, false, 'CIE-11'),
('MF58', 'Secreción uretral', 'category', false, false, 'CIE-11'),
('MF59', 'Síntoma o molestia urinaria', 'category', false, false, 'CIE-11'),
('MF5Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al aparato urinario', 'category', false, false, 'CIE-11'),
('MF60', 'Concentración anormal de enzimas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF61', 'Concentración anormal de hormonas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF62', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF63', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF64', 'Resultados inmunológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF65', 'Resultados microbiológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66', 'Resultados citopatológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66.0', 'Frotis de cuello uterino anormal', 'category', false, false, 'CIE-11'),
('MF66.Y', 'Resultados citopatológicos anormales especificados en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66.Z', 'Resultados citopatológicos anormales en muestras de los órganos genitales femeninos, sin especificación', 'category', false, false, 'CIE-11'),
('MF67', 'Resultados histopatológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF68', 'Resultados cromosómicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF6Y', 'Otros resultados clínicos especificados en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF6Z', 'Resultados clínicos en muestras de los órganos genitales femeninos, sin especificación', 'category', false, false, 'CIE-11'),
('MF70', 'Concentración anormal de enzimas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF71', 'Concentración anormal de hormonas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF72', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF73', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF74', 'Resultados inmunológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF75', 'Resultados microbiológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF76', 'Resultados citopatológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF77', 'Resultados histopatológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF78', 'Resultados cromosómicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF7Y', 'Resultados clínicos anormales especificados en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF7Z', 'Resultados clínicos anormales en muestras de los órganos genitales masculinos, sin especificación', 'category', false, false, 'CIE-11'),
('MF80', 'Esclerosis mesangial difusa', 'category', false, false, 'CIE-11'),
('MF81', 'Glomerulopatía por fibronectina', 'category', false, false, 'CIE-11'),
('MF82', 'Glomerulopatía lipoproteínica', 'category', false, false, 'CIE-11'),
('MF83', 'Alteraciones glomerulares diabéticas', 'category', false, false, 'CIE-11'),
('MF84', 'Glomerulonefritis proliferativa pauciinmunitaria', 'category', false, false, 'CIE-11'),
('MF85', 'Enfermedad mediada por anticuerpos contra la membrana basal glomerular', 'category', false, false, 'CIE-11'),
('MF8Y', 'Resultados clínicos anormales especificados en muestras obtenidas del aparato urinario', 'category', false, false, 'CIE-11'),
('MF8Z', 'Resultados clínicos anormales en muestras obtenidas del aparato urinario, sin especificación', 'category', false, false, 'CIE-11'),
('MF90', 'Cetonuria', 'category', false, false, 'CIE-11'),
('MF91', 'Bilirrubinuria', 'category', false, false, 'CIE-11'),
('MF92', 'Quiluria', 'category', false, false, 'CIE-11'),
('MF93', 'Glucosuria', 'category', false, false, 'CIE-11'),
('MF94', 'Hemoglobinuria', 'category', false, false, 'CIE-11'),
('MF95', 'Mioglobinuria', 'category', false, false, 'CIE-11'),
('MF96', 'Proteinuria', 'category', false, false, 'CIE-11'),
('MF96.0', 'Proteinuria ortostática', 'category', false, false, 'CIE-11'),
('MF96.1', 'Proteinuria de Bence Jones', 'category', false, false, 'CIE-11'),
('MF96.Y', 'Otra proteinuria especificada', 'category', false, false, 'CIE-11'),
('MF96.Z', 'Proteinuria, sin especificación', 'category', false, false, 'CIE-11'),
('MF97', 'Piuria', 'category', false, false, 'CIE-11'),
('MF98', 'Concentraciones anormales de electrolitos séricos en la orina', 'category', false, false, 'CIE-11'),
('MF98.0', 'Hipercalciuria', 'category', false, false, 'CIE-11'),
('MF98.1', 'Hipercaliuria', 'category', false, false, 'CIE-11'),
('MF98.2', 'Hipermagnesuria', 'category', false, false, 'CIE-11'),
('MF98.3', 'Hipocalciuria', 'category', false, false, 'CIE-11'),
('MF98.4', 'Hipocaliuria', 'category', false, false, 'CIE-11'),
('MF98.5', 'Hipomagnesuria', 'category', false, false, 'CIE-11'),
('MF98.6', 'Hipofosfaturia', 'category', false, false, 'CIE-11'),
('MF98.Y', 'Concentraciones anormales especificados de electrolitos séricos en la orina', 'category', false, false, 'CIE-11'),
('MF98.Z', 'Concentraciones anormales de electrolitos séricos en la orina, sin especificación', 'category', false, false, 'CIE-11'),
('MF99', 'Concentraciones elevadas de drogas, medicamentos y sustancias biológicas en la orina', 'category', false, false, 'CIE-11'),
('MF9A', 'Niveles anormales en orina de sustancias principalmente no medicinales según la fuente', 'category', false, false, 'CIE-11'),
('MF9B', 'Resultados anormales en el análisis microbiológico de la orina', 'category', false, false, 'CIE-11'),
('MF9C', 'Resultados anormales en el estudio citopatológico e histopatológico de la orina', 'category', false, false, 'CIE-11'),
('MF9Y', 'Otros resultados anormales especificados en análisis de orina, sin diagnóstico', 'category', false, false, 'CIE-11'),
('MG00', 'Resultados anormales en las pruebas de diagnóstico por la imagen de la mama', 'category', false, false, 'CIE-11'),
('MG01', 'Resultados anormales en las pruebas de diagnóstico por la imagen de los órganos urinarios', 'category', false, false, 'CIE-11'),
('MG02', 'Resultados de pruebas funcionales renales', 'category', false, false, 'CIE-11'),
('MG0Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al sistema genitourinario', 'category', false, false, 'CIE-11'),
('MG20', 'Caquexia', 'category', false, false, 'CIE-11'),
('MG20.0', 'Caquexia maligna', 'category', false, false, 'CIE-11'),
('MG20.Z', 'Caquexia, sin especificación', 'category', false, false, 'CIE-11'),
('MG21', 'Escalofríos', 'category', false, false, 'CIE-11'),
('MG22', 'Cansancio', 'category', false, false, 'CIE-11'),
('MG23', 'Miedo a la muerte o a morir', 'category', false, false, 'CIE-11'),
('MG24', 'Temor a la enfermedad', 'category', false, false, 'CIE-11'),
('MG24.0', 'Temor al cáncer', 'category', false, false, 'CIE-11'),
('MG24.00', 'Temor a los cánceres del aparato digestivo', 'category', false, false, 'CIE-11'),
('MG24.01', 'Temor al cáncer de mama femenino', 'category', false, false, 'CIE-11'),
('MG24.02', 'Temor al cáncer de los genitales masculinos', 'category', false, false, 'CIE-11'),
('MG24.0Y', 'Otro temor especificado al cáncer', 'category', false, false, 'CIE-11'),
('MG24.0Z', 'Temor al cáncer, sin especificación', 'category', false, false, 'CIE-11'),
('MG24.1', 'Temor al virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('MG24.2', 'Temor a una enfermedad hematológica', 'category', false, false, 'CIE-11'),
('MG24.3', 'Temor a la enfermedad digestiva', 'category', false, false, 'CIE-11'),
('MG24.4', 'Temor a la enfermedad de los ojos', 'category', false, false, 'CIE-11'),
('MG24.5', 'Temor a la enfermedad cardíaca', 'category', false, false, 'CIE-11'),
('MG24.6', 'Temor a la hipertensión arterial', 'category', false, false, 'CIE-11'),
('MG24.7', 'Miedo a la enfermedad cardiovascular', 'category', false, false, 'CIE-11'),
('MG24.8', 'Temor a la enfermedad del aparato locomotor', 'category', false, false, 'CIE-11'),
('MG24.9', 'Temor a la enfermedad neurológica', 'category', false, false, 'CIE-11'),
('MG24.A', 'Temor a la enfermedad respiratoria', 'category', false, false, 'CIE-11'),
('MG24.B', 'Temor a la enfermedad endocrina, metabólica o nutricional', 'category', false, false, 'CIE-11'),
('MG24.C', 'Temor a la enfermedad urinaria', 'category', false, false, 'CIE-11'),
('MG24.D', 'Temor a las complicaciones del embarazo', 'category', false, false, 'CIE-11'),
('MG24.E', 'Temor a la enfermedad de transmisión sexual femenina', 'category', false, false, 'CIE-11'),
('MG24.F', 'Temor a la enfermedad de la mama o de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MG24.G', 'Temor a la enfermedad de transmisión sexual masculina', 'category', false, false, 'CIE-11'),
('MG24.H', 'Temor a la enfermedad de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MG24.J', 'Temor a la enfermedad mental', 'category', false, false, 'CIE-11'),
('MG24.Y', 'Temor de otra enfermedad especificada', 'category', false, false, 'CIE-11'),
('MG24.Z', 'Temor a la enfermedad, sin especificación', 'category', false, false, 'CIE-11'),
('MG25', 'Sentirse enfermo', 'category', false, false, 'CIE-11'),
('MG26', 'Fiebre de otro origen o de origen desconocido', 'category', false, false, 'CIE-11'),
('MG27', 'Hemorragia, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG28', 'Hipotermia, no asociada a una temperatura ambiental baja', 'category', false, false, 'CIE-11'),
('MG29', 'Edema', 'category', false, false, 'CIE-11'),
('MG29.0', 'Edema localizado', 'category', false, false, 'CIE-11'),
('MG29.00', 'Edema del tobillo', 'category', false, false, 'CIE-11'),
('MG29.01', 'Edema de las piernas', 'category', false, false, 'CIE-11'),
('MG29.02', 'Fosas en el labio', 'category', false, false, 'CIE-11'),
('MG29.0Y', 'Otro edema localizado especificado', 'category', false, false, 'CIE-11'),
('MG29.1', 'Edema generalizado', 'category', false, false, 'CIE-11'),
('MG29.10', 'Edema por aumento de la presión capilar', 'category', false, false, 'CIE-11'),
('MG29.1Y', 'Otro edema generalizado especificado', 'category', false, false, 'CIE-11'),
('MG29.2', 'Edema infeccioso', 'category', false, false, 'CIE-11'),
('MG29.3', 'Edema con fóvea', 'category', false, false, 'CIE-11'),
('MG29.Z', 'Edema, sin especificación', 'category', false, false, 'CIE-11'),
('MG2A', 'Disminución de la capacidad intrínseca asociada al envejecimiento', 'category', false, false, 'CIE-11'),
('MG30', 'Dolor crónico', 'category', false, false, 'CIE-11'),
('MG30.0', 'Dolor crónico primario', 'category', false, false, 'CIE-11'),
('MG30.00', 'Dolor visceral crónico primario', 'category', false, false, 'CIE-11'),
('MG30.01', 'Dolor generalizado crónico', 'category', false, false, 'CIE-11'),
('MG30.02', 'Dolor músculo esquelético crónico primario', 'category', false, false, 'CIE-11'),
('MG30.03', 'Cefalea crónica o dolor bucofacial crónico primario', 'category', false, false, 'CIE-11'),
('MG30.04', 'Síndrome de dolor regional complejo', 'category', false, false, 'CIE-11'),
('MG30.0Y', 'Otro dolor crónico primario especificado', 'category', false, false, 'CIE-11'),
('MG30.0Z', 'Dolor crónico primario, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.1', 'Dolor crónico por cáncer', 'category', false, false, 'CIE-11'),
('MG30.10', 'Dolor crónico del cáncer', 'category', false, false, 'CIE-11'),
('MG30.11', 'Dolor crónico posterior al tratamiento de cáncer', 'category', false, false, 'CIE-11'),
('MG30.1Y', 'Otro dolor crónico especificado por cáncer', 'category', false, false, 'CIE-11'),
('MG30.1Z', 'Dolor crónico por cáncer, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.2', 'Dolor crónico posquirúrgico o postraumático', 'category', false, false, 'CIE-11'),
('MG30.20', 'Dolor crónico postraumático', 'category', false, false, 'CIE-11'),
('MG30.21', 'Dolor posquirúrgico crónico', 'category', false, false, 'CIE-11'),
('MG30.2Y', 'Otro dolor crónico especificado posquirúrgico o postraumático', 'category', false, false, 'CIE-11'),
('MG30.2Z', 'Dolor crónico posquirúrgico o postraumatico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.3', 'Dolor musculoesquelético secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.30', 'Dolor musculoesquelético secundario crónico por inflamación persistente', 'category', false, false, 'CIE-11'),
('MG30.31', 'Dolor musculoesquelético secundario crónico asociado a alteraciones estructurales', 'category', false, false, 'CIE-11'),
('MG30.32', 'Dolor musculoesquelético secundario crónico por enfermedad del sistema nervioso', 'category', false, false, 'CIE-11'),
('MG30.3Y', 'Otro dolor musculoesquelético secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.3Z', 'Dolor musculoesquelético secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.4', 'Dolor visceral secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.40', 'Dolor visceral crónico por factores mecánicos', 'category', false, false, 'CIE-11'),
('MG30.41', 'Dolor visceral crónico por mecanismos vasculares', 'category', false, false, 'CIE-11'),
('MG30.42', 'Dolor visceral crónico por inflamación persistente', 'category', false, false, 'CIE-11'),
('MG30.4Y', 'Otro dolor visceral secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.4Z', 'Dolor visceral secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.5', 'Dolor neuropático crónico', 'category', false, false, 'CIE-11'),
('MG30.50', 'Dolor neuropático central crónico', 'category', false, false, 'CIE-11'),
('MG30.51', 'Dolor neuropático periférico crónico', 'category', false, false, 'CIE-11'),
('MG30.5Y', 'Otro dolor neuropático crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.5Z', 'Dolor neuropático crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.6', 'Cefalea o dolor bucofacial secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.61', 'Dolor dental crónico', 'category', false, false, 'CIE-11'),
('MG30.62', 'Dolor orofacial neuropático crónico', 'category', false, false, 'CIE-11'),
('MG30.63', 'Dolor de cabeza u orofacial asociado con trastornos temporomandibulares secundarios crónicos', 'category', false, false, 'CIE-11'),
('MG30.64', 'Cefalea crónica o dolor orofacial asociado a trastornos de la homeostasis o su tratamiento no farmacológico', 'category', false, false, 'CIE-11'),
('MG30.65', 'Cefalea crónica o dolor orofacial asociado con trastorno vascular craneal o cervical', 'category', false, false, 'CIE-11'),
('MG30.66', 'Cefalea crónica o dolor orofacial asociado a trastorno intracraneal no vascular', 'category', false, false, 'CIE-11'),
('MG30.67', 'Cefalea crónica asociada a una sustancia o a su abstinencia', 'category', false, false, 'CIE-11'),
('MG30.6Y', 'Otra cefalea o dolor bucofacial secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.6Z', 'Cefalea o dolor bucofacial secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.Y', 'Otro dolor crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.Z', 'Dolor crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG31', 'Dolor agudo', 'category', false, false, 'CIE-11'),
('MG31.0', 'Dolor agudo en la cara, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG31.1', 'Cefalea aguda, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG31.2', 'Dolor postoperatorio agudo, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG31.Y', 'Otro dolor agudo especificado', 'category', false, false, 'CIE-11'),
('MG31.Z', 'Dolor agudo, sin especificación', 'category', false, false, 'CIE-11'),
('MG3Z', 'Dolor, sin especificación', 'category', false, false, 'CIE-11'),
('MG40', 'Choque', 'category', false, false, 'CIE-11'),
('MG40.0', 'Choque cardiogénico', 'category', false, false, 'CIE-11'),
('MG40.1', 'Choque hipovolémico', 'category', false, false, 'CIE-11'),
('MG40.Y', 'Otro choque especificado', 'category', false, false, 'CIE-11'),
('MG40.Z', 'Choque, sin especificación', 'category', false, false, 'CIE-11'),
('MG41', 'Trastornos del sueño', 'category', false, false, 'CIE-11'),
('MG42', 'Somnolencia, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG43', 'Síntomas y signos relativos a la ingesta de alimentos o líquidos', 'category', false, false, 'CIE-11'),
('MG43.0', 'Polidipsia', 'category', false, false, 'CIE-11'),
('MG43.1', 'Hiperfagia', 'category', false, false, 'CIE-11'),
('MG43.2', 'Abulia', 'category', false, false, 'CIE-11'),
('MG43.3', 'Dificultades de la alimentación', 'category', false, false, 'CIE-11'),
('MG43.30', 'Problema con la alimentación del lactante', 'category', false, false, 'CIE-11'),
('MG43.31', 'Problema de alimentación del niño', 'category', false, false, 'CIE-11'),
('MG43.32', 'Problema con la alimentación del adulto', 'category', false, false, 'CIE-11'),
('MG43.3Z', 'Dificultades de la alimentación, sin especificación', 'category', false, false, 'CIE-11'),
('MG43.4', 'Ingesta insuficiente de alimentos o de agua por negligencia personal', 'category', false, false, 'CIE-11'),
('MG43.40', 'Rechazo al alimento, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG43.41', 'Rechazo de líquidos, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG43.4Y', 'Otra ingesta insuficiente de alimentos o de agua especificada, por negligencia personal', 'category', false, false, 'CIE-11'),
('MG43.4Z', 'Ingesta insuficiente de alimentos o de agua por negligencia personal, sin especificación', 'category', false, false, 'CIE-11'),
('MG43.5', 'Adelgazamiento excesivo', 'category', false, false, 'CIE-11'),
('MG43.6', 'Aumento de peso excesivo', 'category', false, false, 'CIE-11'),
('MG43.7', 'Anorexia', 'category', false, false, 'CIE-11'),
('MG43.8', 'Disminución del apetito', 'category', false, false, 'CIE-11'),
('MG43.9', 'Aumento del apetito', 'category', false, false, 'CIE-11'),
('MG43.Y', 'Otros síntomas y signos especificados relativos a la alimentación e ingesta de líquidos', 'category', false, false, 'CIE-11'),
('MG44', 'Síntomas propios del lactante', 'category', false, false, 'CIE-11'),
('MG44.0', 'Llanto excesivo en el lactante', 'category', false, false, 'CIE-11'),
('MG44.1', 'Falta del desarrollo fisiológico normal esperado', 'category', false, false, 'CIE-11'),
('MG44.10', 'Retraso del desarrollo del niño', 'category', false, false, 'CIE-11'),
('MG44.11', 'Retraso ponderal en un lactante o niño', 'category', false, false, 'CIE-11'),
('MG44.12', 'Niño de talla baja', 'category', false, false, 'CIE-11'),
('MG44.13', 'Retraso constitucional del crecimiento y la pubertad', 'category', false, false, 'CIE-11'),
('MG44.14', 'Estatura baja familiar', 'category', false, false, 'CIE-11'),
('MG44.1Y', 'Otra falta del desarrollo fisiológico normal esperado especificado', 'category', false, false, 'CIE-11'),
('MG44.1Z', 'Falta del desarrollo fisiológico normal esperado, sin especificación', 'category', false, false, 'CIE-11'),
('MG44.Y', 'Otros síntomas propios del lactante especificados', 'category', false, false, 'CIE-11'),
('MG44.Z', 'Síntomas propios del lactante, sin especificación', 'category', false, false, 'CIE-11'),
('MG45', 'Síncope y colapso', 'category', false, false, 'CIE-11'),
('MG45.0', 'Síncope cardíaco', 'category', false, false, 'CIE-11'),
('MG45.Y', 'Otro síncope y colapso especificado', 'category', false, false, 'CIE-11'),
('MG45.Z', 'Síncope y colapso, sin especificación', 'category', false, false, 'CIE-11'),
('MG46', 'Síndrome de respuesta inflamatoria sistémica de origen no infeccioso', 'category', false, false, 'CIE-11'),
('MG47', 'Toxicosis sin otra especificación', 'category', false, false, 'CIE-11'),
('MG48', 'Causas de enfermedad desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('MG49', 'Resaca', 'category', false, false, 'CIE-11'),
('MG4A', 'Insuficiencia multiorgánica', 'category', false, false, 'CIE-11'),
('MG4Y', 'Otros síntomas generales especificados', 'category', false, false, 'CIE-11'),
('MG50', 'Detección de bacterias gramnegativas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG50.0', 'Acinetobacter baumannii resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.00', 'Acinetobacter baumannii resistente a las tetraciclinas', 'category', false, false, 'CIE-11'),
('MG50.01', 'Acinetobacter baumannii resistente a los aminoglucósidos', 'category', false, false, 'CIE-11'),
('MG50.02', 'Acinetobacter baumannii resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.03', 'Acinetobacter baumannii resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.0Y', 'Acinetobacter baumannii resistente a otro antibiótico', 'category', false, false, 'CIE-11'),
('MG50.0Z', 'Acinetobacter baumannii resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.1', 'Campylobacter resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.10', 'Campylobacter resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.1Y', 'Campylobacter resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.1Z', 'Campylobacter resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.2', 'Escherichia coli resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.20', 'Escherichia coli resistente a las sulfonamidas o al trimetoprim', 'category', false, false, 'CIE-11'),
('MG50.21', 'Escherichia coli resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.22', 'Escherichia coli resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.23', 'Escherichia coli resistente a las cefalosporinas de cuarta generación', 'category', false, false, 'CIE-11'),
('MG50.24', 'Escherichia coli resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.25', 'Escherichia coli resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.26', 'Escherichia coli resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG50.27', 'Escherichia coli productora de betalactamasas de espectro extendido', 'category', false, false, 'CIE-11'),
('MG50.2Y', 'Escherichia coli resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.2Z', 'Escherichia coli resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.3', 'Haemophilus influenzae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.30', 'Haemophilus influenzae resistente a la ampicilina', 'category', false, false, 'CIE-11'),
('MG50.3Y', 'Haemophilus influenza resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.3Z', 'Haemophilus influenzae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.4', 'Helicobacter pylori resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.40', 'Helicobacter pylori resistente a la claritromicina', 'category', false, false, 'CIE-11'),
('MG50.4Y', 'Helicobacter pylori resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.4Z', 'Helicobacter pylori resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.5', 'Klebsiella pneumoniae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.50', 'Klebsiella pneumoniae resistente a las sulfonamidas o al trimetoprim', 'category', false, false, 'CIE-11'),
('MG50.51', 'Klebsiella pneumoniae resistente a las fluoroquinonas', 'category', false, false, 'CIE-11'),
('MG50.52', 'Klebsiella pneumoniae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.53', 'Klebsiella pneumoniae resistente a las cefalosporinas de cuarta generación', 'category', false, false, 'CIE-11'),
('MG50.54', 'Klebsiella pneumoniae resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.55', 'Klebsiella pneumoniae resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.56', 'Klebsiella pneumoniae productora de betalactamasas de espectro extendido', 'category', false, false, 'CIE-11'),
('MG50.5Y', 'Klebsiella pneumoniae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.5Z', 'Klebsiella pneumoniae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.6', 'Neisseria gonorrhoeae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.60', 'Neisseria gonorrhoeae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.61', 'Neisseria gonorrhoeae resistente a los macrólidos', 'category', false, false, 'CIE-11'),
('MG50.62', 'Neisseria gonorrhoeae resistente al aminociclitol', 'category', false, false, 'CIE-11'),
('MG50.63', 'Neisseria gonorrhoeae resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.64', 'Neisseria gonorrhoeae resistente a los aminoglucósidos', 'category', false, false, 'CIE-11'),
('MG50.6Y', 'Neisseria gonorrhoeae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.6Z', 'Neisseria gonorrhoeae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.7', 'Neisseria meningitidis resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.70', 'Neisseria meningitidis resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG50.7Y', 'Neisseria meningitidis resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.7Z', 'Neisseria meningitidis resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.8', 'Pseudomonas aeruginosa resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.80', 'Pseudomonas aeruginosa resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.81', 'Pseudomonas aeruginosa resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.8Y', 'Pseudomonas aeruginosa resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.8Z', 'Pseudomonas aeruginosa resistente a os antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.9', 'Salmonella resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.90', 'Salmonella resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.91', 'Salmonella resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.92', 'Salmonella resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.9Y', 'Salmonella resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.9Z', 'Salmonella resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.A', 'Shigella resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.A0', 'Shigella resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.A1', 'Shigella resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.A2', 'Shigella resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.A3', 'Shigella resistente a los macrólidos', 'category', false, false, 'CIE-11'),
('MG50.AY', 'Shigella resistente a otro antibiótico', 'category', false, false, 'CIE-11'),
('MG50.AZ', 'Shigella resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.B', 'Vibrio resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.B0', 'Vibrio resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.BY', 'Vibrio resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.BZ', 'Vibrio resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.C', 'Otras enterobacterias resistentes a antibióticos', 'category', false, false, 'CIE-11'),
('MG50.C0', 'Otras enterobacterias resistentes a carbapenem', 'category', false, false, 'CIE-11'),
('MG50.C1', 'Otras enterobacterias resistentes a cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.CY', 'Enterobacteriaceae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.CZ', 'Enterobacteriaceae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.Y', 'Otra detección de bacterias gramnegativas resistentes a los antimicrobianos especificada', 'category', false, false, 'CIE-11'),
('MG50.Z', 'Detección de bacterias gramnegativas resistente a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51', 'Detección de bacterias grampositivas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG51.0', 'Staphylococcus aureus resistente a antibióticos', 'category', false, false, 'CIE-11'),
('MG51.00', 'Staphylococcus aureus resistente a la meticilina', 'category', false, false, 'CIE-11'),
('MG51.01', 'Staphylococcus aureus resistente a la vancomicina', 'category', false, false, 'CIE-11'),
('MG51.02', 'Staphylococcus aureus resistente a los betalactámicos estables frente a las penicilinasas', 'category', false, false, 'CIE-11'),
('MG51.0Y', 'Staphylococcus aureus resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG51.0Z', 'Staphylococcus aureus resistente a antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51.1', 'Streptococcus pneumoniae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG51.10', 'Streptococcus pneumoniae resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG51.11', 'Streptococcus pneumoniae resistente a la sulfonamida y la trimetoprima', 'category', false, false, 'CIE-11'),
('MG51.12', 'Streptococcus pneumoniae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG51.1Y', 'Streptococcus pneumoniae resistente a otros antibióticos', 'category', false, false, 'CIE-11'),
('MG51.1Z', 'Streptococcus pneumoniae resistente a antibiótico no especificado', 'category', false, false, 'CIE-11'),
('MG51.2', 'Enterococcus resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG51.20', 'Enterococcus resistente a la vancomicina', 'category', false, false, 'CIE-11'),
('MG51.2Y', 'Enterococcus resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG51.2Z', 'Enterococcus resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51.Y', 'Otra detección de bacterias grampositivas especificadas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG51.Z', 'Detección de bacterias grampositivas resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG52', 'Detección de bacterias, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG52.0', 'Mycobacterium resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG52.00', 'Mycobacterium tuberculosis multirresistente a farmacos', 'category', false, false, 'CIE-11'),
('MG52.01', 'Mycobacterium no tuberculoso resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG52.02', 'Mycobacterium tuberculosis extensamente resistente a los medicamentos', 'category', false, false, 'CIE-11'),
('MG52.0Y', 'Mycobacterium resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG52.0Z', 'Mycobacterium resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG52.Y', 'Otra detección de bacterias especificadas, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG52.Z', 'Detección de bacterias, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG53', 'Detección de virus resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG53.0', 'Virus de la inmunodeficiencia humana resistente al tratamiento antirretroviral', 'category', false, false, 'CIE-11'),
('MG53.Y', 'Detección de otro virus especificado resistente a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG53.Z', 'Detección de virus resistente a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG54', 'Detección de hongos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55', 'Detección de parásitos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55.0', 'Plasmodium falciparum resistente a la artemisinina', 'category', false, false, 'CIE-11'),
('MG55.Y', 'Otra detección especificada de parásitos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55.Z', 'Detección de parásitos resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG56', 'Detección de microorganismo resistente a varios antimicrobianos de otro tipo', 'category', false, false, 'CIE-11'),
('MG5Y', 'Detección de otros microorganismos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG5Z', 'Detección de microorganismos resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG60', 'Concentración anormal de enzimas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG61', 'Concentración anormal de hormonas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG62', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG63', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG64', 'Resultados inmunológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG65', 'Resultado microbiológico anormal en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG66', 'Resultados citopatológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG67', 'Resultados histopatológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG6Y', 'Otros resultados anormales especificados en muestras de otros órganos, aparatos y tejidos especificados', 'category', false, false, 'CIE-11'),
('MG70', 'Resultados anormales en pruebas de diagnóstico por la imagen, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71', 'Resultados de laboratorio anormales, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71.0', 'Resultados anormales en el cribado neonatal', 'category', false, false, 'CIE-11'),
('MG71.Y', 'Otros resultados de laboratorio anormales especificados, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71.Z', 'Resultados de laboratorio anormales, no clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MG72', 'Resultados anormales en estudios funcionales de otros órganos y aparatos', 'category', false, false, 'CIE-11'),
('MG7Y', 'Otros resultados anormales especificados, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG7Z', 'Resultados anormales, no clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MH10', 'Muerte cerebral', 'category', false, false, 'CIE-11'),
('MH11', 'Síndrome de muerte súbita del lactante', 'category', false, false, 'CIE-11'),
('MH11.0', 'Síndrome de muerte súbita del lactante con mención de una autopsia', 'category', false, false, 'CIE-11'),
('MH11.1', 'Síndrome de muerte súbita del lactante sin autopsia', 'category', false, false, 'CIE-11'),
('MH11.Z', 'Síndrome de muerte súbita del lactante, sin especificación', 'category', false, false, 'CIE-11'),
('MH12', 'Otra muerte súbita, de causa desconocida', 'category', false, false, 'CIE-11'),
('MH12.0', 'Muerte instantánea', 'category', false, false, 'CIE-11'),
('MH12.1', 'Muerte que ocurre menos de 24 horas después del comienzo de los síntomas, sin otra explicación', 'category', false, false, 'CIE-11'),
('MH12.Y', 'Otra muerte repentina especificada, de causa desconocida', 'category', false, false, 'CIE-11'),
('MH13', 'Muerte sin asistencia', 'category', false, false, 'CIE-11'),
('MH14', 'Otras causas de muerte mal definidas o no especificadas', 'category', false, false, 'CIE-11'),
('MH15', 'Muerte súbita inesperada en paciente con epilepsia', 'category', false, false, 'CIE-11'),
('MH2Y', 'Otros síntomas, signos o hallazgos clínicos especificados no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('NA00', 'Traumatismo superficial en la cabeza', 'category', false, false, 'CIE-11'),
('NA00.0', 'Traumatismo superficial en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.00', 'Excoriación en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.01', 'Contusión de cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.02', 'Cuerpo extraño superficial en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.0Y', 'Otro traumatismo superficial especificado en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.0Z', 'Traumatismo superficial en el cuero cabelludo, sin especificación', 'category', false, false, 'CIE-11'),
('NA00.1', 'Traumatismo superficial en el párpado o el área periocular', 'category', false, false, 'CIE-11'),
('NA00.10', 'Excoriación en el párpado o el área periocular', 'category', false, false, 'CIE-11'),
('NA00.11', 'Contusión en el párpado o el área periocular', 'category', false, false, 'CIE-11'),
('NA00.1Y', 'Otro traumatismo superficial especificado en el párpado o el área periocular', 'category', false, false, 'CIE-11'),
('NA00.1Z', 'Traumatismo superficial en el párpado o el área periocular, sin especificación', 'category', false, false, 'CIE-11'),
('NA00.2', 'Traumatismo superficial en la oreja o el oído', 'category', false, false, 'CIE-11'),
('NA00.3', 'Traumatismo superficial en la nariz', 'category', false, false, 'CIE-11'),
('NA00.4', 'Traumatismo superficial en el labio o la cavidad bucal', 'category', false, false, 'CIE-11'),
('NA00.5', 'Múltiples traumatismos superficiales en la cabeza', 'category', false, false, 'CIE-11'),
('NA00.6', 'Excoriación en otros sitios no especificados de la cabeza', 'category', false, false, 'CIE-11'),
('NA00.7', 'Contusión en otros sitios o en sitios no especificados de la cabeza', 'category', false, false, 'CIE-11'),
('NA00.Y', 'Otro traumatismo superficial especificado en la cabeza', 'category', false, false, 'CIE-11'),
('NA00.Z', 'Traumatismo superficial en la cabeza, sin especificación', 'category', false, false, 'CIE-11'),
('NA01', 'Herida abierta de cabeza', 'category', false, false, 'CIE-11'),
('NA01.2', 'Laceración en la cabeza, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NA01.3', 'Laceración en la cabeza, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NA01.4', 'Herida punzante en la cabeza, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NA01.5', 'Herida punzante con cuerpo extraño en la cabeza', 'category', false, false, 'CIE-11'),
('NA01.6', 'Mordedura abierta en la cabeza', 'category', false, false, 'CIE-11'),
('NA01.7', 'Heridas abiertas múltiples en la cabeza', 'category', false, false, 'CIE-11'),
('NA01.Y', 'Otra herida abierta especificada de cabeza', 'category', false, false, 'CIE-11'),
('NA01.Z', 'Herida abierta de cabeza, sin especificación', 'category', false, false, 'CIE-11'),
('NA02', 'Fractura del cráneo o de los huesos faciales', 'category', false, false, 'CIE-11'),
('NA02.0', 'Fractura de la bóveda del cráneo', 'category', false, false, 'CIE-11'),
('NA02.00', 'Fractura de la escama del hueso frontal del cráneo', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
