-- CIE11 Import Part 32
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('PA2E', 'Evento no intencional en transporte terrestre que causa traumatismo a persona montada en un animal y se desconoce si ocurrió en el tránsito', 'category', false, false, 'CIE-11'),
('PA2F', 'Evento no intencional en transporte terrestre que causa traumatismo a ocupante de vehículo de tracción animal y se desconoce si ocurrió en el tránsito', 'category', false, false, 'CIE-11'),
('PA2Y', 'Evento de lesión no intencional por transporte terrestre que se desconoce si es de tránsito o no, que lesiona a un usuario de otro transporte especificado', 'category', false, false, 'CIE-11'),
('PA2Z', 'Evento de lesión no intencional por transporte terrestre, se desconoce si es de tránsito o no, y lesiona a un usuario de un transporte, sin especificación', 'category', false, false, 'CIE-11'),
('PA30', 'Evento no intencional en transporte ferroviario que causa traumatismo con colisión o descarrilamiento', 'category', false, false, 'CIE-11'),
('PA31', 'Evento no intencional en transporte ferroviario que causa traumatismo sin colisión ni descarrilamiento', 'category', false, false, 'CIE-11'),
('PA3Z', 'Evento no intencional en transporte ferroviario que causa traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('PA40', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PA40.0', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, que causa sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PA40.1', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, que causa otra lesión', 'category', false, false, 'CIE-11'),
('PA40.Z', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida que causa traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('PA41', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida', 'category', false, false, 'CIE-11'),
('PA41.0', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida, que causa sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PA41.Z', 'Evento no intencional en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida, sin especificación', 'category', false, false, 'CIE-11'),
('PA4Z', 'Evento no intencional que causa lesión en transporte acuático, sin especificación', 'category', false, false, 'CIE-11'),
('PA50', 'Evento no intencional en transporte aéreo o espacial que causa traumatismo', 'category', false, false, 'CIE-11'),
('PA50.0', 'Evento no intencional en transporte aéreo o espacial que causa traumatismo con avión o vehículo espacial no dañado, averiado ni destruido', 'category', false, false, 'CIE-11'),
('PA50.1', 'Evento no intencional en transporte aéreo o espacial que causa traumatismo con avión o vehículo espacial dañado, averiado o destruido', 'category', false, false, 'CIE-11'),
('PA50.Z', 'Evento no intencional en transporte espacial o aéreo, sin especificación', 'category', false, false, 'CIE-11'),
('PA5Y', 'Otro evento no intencional especificado en transporte que causa traumatismo', 'category', false, false, 'CIE-11'),
('PA5Z', 'Evento no intencional en transporte que causa traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('PA60', 'Caída no intencional desde el mismo nivel o desde menos de 1 metro', 'category', false, false, 'CIE-11'),
('PA61', 'Caída no intencional desde de 1 metro de altura o más', 'category', false, false, 'CIE-11'),
('PA6Z', 'Caída no intencional desde altura, sin especificación', 'category', false, false, 'CIE-11'),
('PA70', 'Golpe, patada o empujón no intencional por una persona', 'category', false, false, 'CIE-11'),
('PA71', 'Golpe, patada o empujón no intencional por un animal', 'category', false, false, 'CIE-11'),
('PA72', 'Persona pisoteada o aplastada de manera no intencional por una persona', 'category', false, false, 'CIE-11'),
('PA73', 'Persona pisoteada o aplastada de manera no intencional por un animal', 'category', false, false, 'CIE-11'),
('PA74', 'Mordedura no intencional por una persona', 'category', false, false, 'CIE-11'),
('PA75', 'Mordedura no intencional por un animal', 'category', false, false, 'CIE-11'),
('PA76', 'Arañazo o rasguño no intencional por una persona', 'category', false, false, 'CIE-11'),
('PA77', 'Arañazo o rasguño no intencional por un animal', 'category', false, false, 'CIE-11'),
('PA78', 'Picadura o envenenamiento no intencional por un animal', 'category', false, false, 'CIE-11'),
('PA79', 'Lesión no intencional por contacto con una planta', 'category', false, false, 'CIE-11'),
('PA7Y', 'Otro contacto no intencional especificado con persona, animal o planta', 'category', false, false, 'CIE-11'),
('PA7Z', 'Contacto no intencional con persona, animal o planta, sin especificación', 'category', false, false, 'CIE-11'),
('PA80', 'Impacto no intencional por proyectil de arma de fuego', 'category', false, false, 'CIE-11'),
('PA80.0', 'Impacto no intencional por proyectil de arma corta', 'category', false, false, 'CIE-11'),
('PA80.1', 'Impacto no intencional por proyectil de rifle, escopeta o arma de fuego más grande', 'category', false, false, 'CIE-11'),
('PA80.Y', 'Otro(a)(s) impacto no intencional por proyectil de arma de fuego especificado(a)(s)', 'category', false, false, 'CIE-11'),
('PA80.Z', 'Impacto no intencional por proyectil de arma de fuego, sin especificación', 'category', false, false, 'CIE-11'),
('PA81', 'Golpe no intencional por objeto en movimiento', 'category', false, false, 'CIE-11'),
('PA82', 'Golpe no intencional contra objeto estacionario', 'category', false, false, 'CIE-11'),
('PA83', 'Cortadura o perforación no intencional por objeto punzante', 'category', false, false, 'CIE-11'),
('PA83.0', 'Cortadura o penetración no intencional por cuchillo, espada o puñal', 'category', false, false, 'CIE-11'),
('PA83.1', 'Cortadura o penetración no intencional por vidrio cortante', 'category', false, false, 'CIE-11'),
('PA83.2', 'Cortadura o penetración no intencional por objeto punzante de otro tipo o no especificado', 'category', false, false, 'CIE-11'),
('PA84', 'Golpe no intencional por objeto contundente o romo', 'category', false, false, 'CIE-11'),
('PA85', 'Persona atrapada, aplastada, atascada o apretada de manera no intencional entre objetos', 'category', false, false, 'CIE-11'),
('PA8Y', 'Exposición no intencional a un objeto especificado, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('PA8Z', 'Exposición no intencional a un objeto, no clasificado en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('PA90', 'Ahogamiento o sumersión no intencionales que ocurre mientras la persona está en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PA91', 'Ahogamiento o sumersión no intencionales, posterior a caída en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PA92', 'Traumatismo no intencional posterior a caída a cuerpo de agua sin ahogamiento', 'category', false, false, 'CIE-11'),
('PA9Z', 'Inmersión, sumersión o caída al agua no intencional, sin especificación', 'category', false, false, 'CIE-11'),
('PB00', 'Amenaza no intencional a la respiración por asfixia causada por objeto que cubre la boca o la nariz', 'category', false, false, 'CIE-11'),
('PB01', 'Amenaza no intencional a la respiración por ahorcamiento', 'category', false, false, 'CIE-11'),
('PB02', 'Amenaza no intencional a la respiración por estrangulamiento', 'category', false, false, 'CIE-11'),
('PB03', 'Amenaza no intencional a la respiración por compresión externa de la vía aérea o el tórax', 'category', false, false, 'CIE-11'),
('PB04', 'Amenaza no intencional a la respiración por inhalación o ingestión de contenidos gástricos', 'category', false, false, 'CIE-11'),
('PB05', 'Amenaza no intencional a la respiración por inhalación o ingestión de líquidos', 'category', false, false, 'CIE-11'),
('PB06', 'Amenaza no intencional a la respiración por inhalación o aspiración de alimentos', 'category', false, false, 'CIE-11'),
('PB07', 'Amenaza no intencional a la respiración por inhalación o ingestión de otros objetos o materiales', 'category', false, false, 'CIE-11'),
('PB08', 'Amenaza no intencional a la respiración por entorno con poco oxigeno', 'category', false, false, 'CIE-11'),
('PB0Y', 'Amenaza no intencional a la respiración por otro medio especificado', 'category', false, false, 'CIE-11'),
('PB0Z', 'Amenaza no intencional a la respiración por medio, sin especificación', 'category', false, false, 'CIE-11'),
('PB10', 'Exposición no intencional a fuego no controlado', 'category', false, false, 'CIE-11'),
('PB11', 'Exposición no intencional a fuego controlado', 'category', false, false, 'CIE-11'),
('PB12', 'Exposición no intencional a la ignición o la fundición de material', 'category', false, false, 'CIE-11'),
('PB13', 'Contacto no intencional con objeto o líquido caliente', 'category', false, false, 'CIE-11'),
('PB14', 'Exposición no intencional a vapor, aire o gases calientes', 'category', false, false, 'CIE-11'),
('PB15', 'Exposición no intencional a calor excesivo', 'category', false, false, 'CIE-11'),
('PB16', 'Exposición no intencional a frío excesivo', 'category', false, false, 'CIE-11'),
('PB1Y', 'Exposición no intencional a otro mecanismo térmico especificado', 'category', false, false, 'CIE-11'),
('PB1Z', 'Exposición no intencional a mecanismo térmico, sin especificación', 'category', false, false, 'CIE-11'),
('PB20', 'Exposición no intencional a opioides o analgésicos relacionados o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB21', 'Exposición no intencional a sedantes hipnóticos u otros depresores del sistema nervioso central o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB22', 'Exposición no intencional a psicoestimulantes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB23', 'Exposición no intencional a canabinoides o alucinógenos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB24', 'Exposición no intencional a analgésicos, antipiréticos o antiinflamatorios no esteroideos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB25', 'Exposición no intencional a antidepresivos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB26', 'Exposición no intencional a antipsicóticos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB27', 'Exposición no intencional a fármacos antiepilépticos o antiparkinsonianos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB28', 'Exposición no intencional a fármacos, medicamentos o sustancias biológicas de otro tipo o no especificados, o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB29', 'Exposición no intencional a múltiples fármacos, medicamentos o sustancias biológicas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB30', 'Exposición no intencional a alcoholes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB31', 'Exposición no intencional a disolventes orgánicos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB32', 'Exposición no intencional al monóxido de carbono o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB33', 'Exposición no intencional a plaguicidas y a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB34', 'Exposición no intencional a sustancias corrosivas o sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB35', 'Exposición no intencional a los derivados halogenados de los hidrocarburos alifáticos o aromáticos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB36', 'Exposición no intencional a sustancias de otro tipo o no especificadas de procedencia principalmente no medicinal o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PB50', 'Exposición no intencional a cuerpo extraño en orificio corporal', 'category', false, false, 'CIE-11'),
('PB51', 'Exposición no intencional a corriente eléctrica', 'category', false, false, 'CIE-11'),
('PB52', 'Exposición no intencional a la luz solar', 'category', false, false, 'CIE-11'),
('PB53', 'Exposición no intencional a radiación', 'category', false, false, 'CIE-11'),
('PB54', 'Exposición no intencional a presión del aire alta o baja o cambios en la presión del aire', 'category', false, false, 'CIE-11'),
('PB55', 'Exposición no intencional a explosión', 'category', false, false, 'CIE-11'),
('PB55.0', 'Exposición no intencional a explosión química', 'category', false, false, 'CIE-11'),
('PB55.1', 'Exposición no intencional a explosión o rotura de materiales u objetos presurizados', 'category', false, false, 'CIE-11'),
('PB55.Y', 'Otra exposición no intencional a explosión especificada', 'category', false, false, 'CIE-11'),
('PB55.Z', 'Exposición no intencional a explosión, sin especificación', 'category', false, false, 'CIE-11'),
('PB56', 'Exposición no intencional a esfuerzo físico excesivo', 'category', false, false, 'CIE-11'),
('PB57', 'Privación no intencional de alimentos', 'category', false, false, 'CIE-11'),
('PB58', 'Privación no intencional de agua', 'category', false, false, 'CIE-11'),
('PB59', 'Otra privación no intencional especificada', 'category', false, false, 'CIE-11'),
('PB5A', 'Abandono no intencional', 'category', false, false, 'CIE-11'),
('PB5B', 'Negligencia no intencional', 'category', false, false, 'CIE-11'),
('PB6Y', 'Otras causas no intencionales de morbilidad y mortalidad especificadas', 'category', false, false, 'CIE-11'),
('PB6Z', 'Causas no intencionales de morbilidad y mortalidad, sin especificación', 'category', false, false, 'CIE-11'),
('PB80', 'Lesión autoinfligida intencionalmente por medio de evento de transporte terrestre en el tránsito', 'category', false, false, 'CIE-11'),
('PB81', 'Lesión autoinfligida intencionalmente por medio de evento en transporte terrestre que ocurre fuera del tránsito y de la vía pública', 'category', false, false, 'CIE-11'),
('PB82', 'Lesión autoinfligida intencionalmente por medio de evento en transporte terrestre y se desconoce si ocurrió en el tránsito', 'category', false, false, 'CIE-11'),
('PB83', 'Lesión autoinfligida intencionalmente por medio de evento en transporte ferroviario', 'category', false, false, 'CIE-11'),
('PB90', 'Lesión autoinfligida intencionadamente por medio de evento en transporte marítimo o fluvial con embarcación dañada, averiada o destruida', 'category', false, false, 'CIE-11'),
('PB91', 'Lesión autoinfligida intencionalmente por medio de evento en transporte marítimo o fluvial con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PB91.0', 'Lesión autoinfligida intencionalmente por medio de evento en transporte marítimo o fluvial que causa sumersión o ahogamiento y con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PB91.1', 'Lesión autoinfligida intencionalmente por medio de evento en transporte marítimo que causa otra lesión y con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PB91.Z', 'Lesión autoinfligida intencionalmente por medio de evento en transporte marítimo o fluvial con embarcación no dañada, averiada ni destruida, sin especificar', 'category', false, false, 'CIE-11'),
('PB9Z', 'Lesión autoinfligida intencionalmente por medio de evento en transporte marítimo o fluvial no especificado', 'category', false, false, 'CIE-11'),
('PC00', 'Lesión autoinfligida intencionalmente en evento en transporte aéreo o espacial con vehículo aéreo o espacial dañado, averiado o destruido', 'category', false, false, 'CIE-11'),
('PC01', 'Lesión autoinfligida intencionalmente en evento en transporte aéreo o espacial con vehículo aéreo o espacial no dañado, averiado ni destruido', 'category', false, false, 'CIE-11'),
('PC0Z', 'Lesión autoinfligida intencionadamente en transporte aéreo o espacial, sin especificar', 'category', false, false, 'CIE-11'),
('PC2Y', 'Lesión autoinfligida intencionalmente por medio de evento de transporte especificado', 'category', false, false, 'CIE-11'),
('PC2Z', 'Lesión autoinfligida intencionalmente por medio de evento de transporte, sin especificación', 'category', false, false, 'CIE-11'),
('PC30', 'Lesión autoinfligida intencionalmente por caída o salto desde el mismo nivel o desde menos de 1 metro', 'category', false, false, 'CIE-11'),
('PC31', 'Autolesión intencional por caída o salto desde una altura de 1 metro o más', 'category', false, false, 'CIE-11'),
('PC3Y', 'Otra lesión autoinfligida intencionalmente por caída o salto', 'category', false, false, 'CIE-11'),
('PC3Z', 'Lesión autoinfligida intencionalmente por caída o salto, sin especificación', 'category', false, false, 'CIE-11'),
('PC40', 'Lesión autoinfligida intencionalmente por golpe, patada o empujón por una persona', 'category', false, false, 'CIE-11'),
('PC41', 'Lesión autoinfligida intencionalmente por medio de golpe, patada o empujón de un animal', 'category', false, false, 'CIE-11'),
('PC42', 'Lesión autoinfligida intencionalmente al ser pisoteado o aplastado por una persona', 'category', false, false, 'CIE-11'),
('PC43', 'Lesión autoinfligida intencionalmente al ser pisoteado o aplastado por un animal', 'category', false, false, 'CIE-11'),
('PC44', 'Lesión autoinfligida intencionalmente al ser mordido por un animal', 'category', false, false, 'CIE-11'),
('PC45', 'Lesión autoinfligida intencionalmente al ser rasguñado o arañado por una persona', 'category', false, false, 'CIE-11'),
('PC46', 'Lesión autoinfligida intencionalmente al ser rasguñado o arañado por un animal', 'category', false, false, 'CIE-11'),
('PC47', 'Lesión autoinfligida intencionalmente al ser picado o envenenado por un animal', 'category', false, false, 'CIE-11'),
('PC48', 'Lesión autoinfligida intencionalmente por contacto con una planta', 'category', false, false, 'CIE-11'),
('PC4Y', 'Otra lesión especificada autoinfligida intencionalmente por contacto con persona, animal o planta', 'category', false, false, 'CIE-11'),
('PC4Z', 'Lesión autoinfligida intencionalmente por contacto con persona, animal o planta, sin especificación', 'category', false, false, 'CIE-11'),
('PC50', 'Lesión autoinfligida intencionalmente por impacto de proyectil de arma de fuego', 'category', false, false, 'CIE-11'),
('PC50.0', 'Lesión autoinfligida intencionalmente por proyectil de arma corta', 'category', false, false, 'CIE-11'),
('PC50.1', 'Lesión autoinfligida intencionalmente por proyectil de rifle, escopeta o arma larga', 'category', false, false, 'CIE-11'),
('PC50.Y', 'Otra lesión especificada autoinfligida intencionalmente por impacto de proyectil de arma de fuego', 'category', false, false, 'CIE-11'),
('PC50.Z', 'Lesión autoinfligida intencionalmente por impacto de proyectil de arma de fuego, sin especificar', 'category', false, false, 'CIE-11'),
('PC51', 'Lesión autoinfligida intencionalmente por golpe de objeto en movimiento, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('PC52', 'Lesión autoinfligida intencionalmente por golpe contra objeto estacionario', 'category', false, false, 'CIE-11'),
('PC53', 'Lesión autoinfligida intencionalmente por cortadura o perforación con objeto punzante', 'category', false, false, 'CIE-11'),
('PC53.0', 'Lesión autoinfligida intencionalmente por cortadura o perforación con cuchillo, espada o puñal', 'category', false, false, 'CIE-11'),
('PC53.1', 'Lesión autoinfligida intencionalmente por cortadura o perforación con vidrio cortante', 'category', false, false, 'CIE-11'),
('PC53.Y', 'Lesión especificada autoinfligida intencionalmente por cortadura o perforación con objeto punzante', 'category', false, false, 'CIE-11'),
('PC53.Z', 'Lesión autoinfligida intencionalmente por cortadura o perforación con objeto punzante, sin especificación', 'category', false, false, 'CIE-11'),
('PC54', 'Lesión autoinfligida intencionalmente por golpe por un objeto contundente o romo', 'category', false, false, 'CIE-11'),
('PC55', 'Lesión autoinfligida intencionalmente al estar atrapado, aplastado, trabado o apretado entre objetos', 'category', false, false, 'CIE-11'),
('PC5Y', 'Lesión autoinfligida intencionalmente por contacto con otro tipo de arma especificada', 'category', false, false, 'CIE-11'),
('PC5Z', 'Lesión autoinfligida intencionalmente por contacto con arma, de tipo no especificado', 'category', false, false, 'CIE-11'),
('PC60', 'Lesión autoinfligida intencionalmente por ahogamiento o sumersión mientras la persona está en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PC61', 'Lesión autoinfligida intencionalmente por ahogamiento o sumersión posteriores a caída en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PC62', 'Lesión autoinfligida intencionalmente por traumatismo que ocurre mientras la persona está en un cuerpo de agua, sin ahogamiento', 'category', false, false, 'CIE-11'),
('PC63', 'Lesión autoinfligida intencionalmente por traumatismo posterior a caída a cuerpo de agua sin ahogamiento', 'category', false, false, 'CIE-11'),
('PC6Z', 'Lesión autoinfligida intencionalmente por inmersión, sumersión o caída al agua, sin especificación', 'category', false, false, 'CIE-11'),
('PC70', 'Lesión autoinfligida intencionalmente por medio de amenaza a la respiración por asfixia causada con objeto que cubre la boca o la nariz', 'category', false, false, 'CIE-11'),
('PC71', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por ahorcamiento', 'category', false, false, 'CIE-11'),
('PC72', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por estrangulamiento', 'category', false, false, 'CIE-11'),
('PC73', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por compresión externa de las vías respiratorias y el tórax', 'category', false, false, 'CIE-11'),
('PC74', 'Lesión autoinfligida intencionalmente por inhalación o ingestión de contenidos gástricos', 'category', false, false, 'CIE-11'),
('PC75', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por inhalación o ingestión de líquidos', 'category', false, false, 'CIE-11'),
('PC76', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por inhalación o ingestión de alimentos', 'category', false, false, 'CIE-11'),
('PC77', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por inhalación o ingestión de otros objetos o materiales', 'category', false, false, 'CIE-11'),
('PC78', 'Lesión autoinfligida intencionalmente por amenaza a la respiración por entorno con poco oxígeno', 'category', false, false, 'CIE-11'),
('PC7Y', 'Lesión especificada autoinfligida intencionalmente por amenaza a la respiración', 'category', false, false, 'CIE-11'),
('PC7Z', 'Lesión autoinfligida intencionalmente por amenaza a la respiración, sin especificación', 'category', false, false, 'CIE-11'),
('PC80', 'Lesión autoinfligida intencionalmente por exposición a fuego controlado', 'category', false, false, 'CIE-11'),
('PC81', 'Lesión autoinfligida intencionalmente por exposición a fuego no controlado', 'category', false, false, 'CIE-11'),
('PC82', 'Lesión autoinfligida intencionalmente por ignición o fusión de materiales', 'category', false, false, 'CIE-11'),
('PC83', 'Lesión autoinfligida intencionalmente por contacto con objeto o líquido caliente', 'category', false, false, 'CIE-11'),
('PC84', 'Lesión autoinfligida intencionalmente por exposición a vapor, aire o gases calientes', 'category', false, false, 'CIE-11'),
('PC85', 'Lesión autoinfligida intencionalmente por medio de exposición a calor excesivo', 'category', false, false, 'CIE-11'),
('PC86', 'Lesión autoinfligida intencionalmente por medio de exposición a frío excesivo', 'category', false, false, 'CIE-11'),
('PC8Y', 'Lesión autoinfligida intencionalmente por exposición a otro mecanismo térmico especificado', 'category', false, false, 'CIE-11'),
('PC8Z', 'Lesión autoinfligida intencionalmente por mecanismo térmico, sin especificación', 'category', false, false, 'CIE-11'),
('PC90', 'Lesión autoinfligida intencionalmente por exposición a opioides o analgésicos relacionados o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC91', 'Lesión autoinfligida intencionalmente de exposición a sedantes hipnóticos u otros depresores del sistema nervioso central o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC92', 'Lesión autoinfligida intencionalmente por exposición a psicoestimulantes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC93', 'Lesión autoinfligida intencionalmente por exposición a canabinoides o alucinógenos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC94', 'Lesión autoinfligida intencionalmente por exposición a analgésicos, antipiréticos o antiinflamatorios no esteroideos', 'category', false, false, 'CIE-11'),
('PC95', 'Lesión autoinfligida intencionalmente por exposición a antidepresivos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC96', 'Lesión autoinfligida intencionalmente por exposición a antipsicóticos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC97', 'Lesión autoinfligida intencionalmente por exposición a fármacos antiepilépticos o antiparkinsonianos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PC98', 'Lesión autoinfligida intencionalmente por exposición a otras drogas, medicamentos o sustancias biológicas y las no especificados', 'category', false, false, 'CIE-11'),
('PC99', 'Lesión autoinfligida intencionalmente por exposición a múltiples fármacos, medicamentos o sustancias biológicas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD00', 'Lesión autoinfligida intencionalmente por exposición a alcoholes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD01', 'Lesión autoinfligida intencionalmente por medio de exposición a disolventes orgánicos y a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD02', 'Lesión autoinfligida intencionalmente por medio de exposición al monóxido de carbono o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD03', 'Lesión autoinfligida intencionalmente por medio de exposición a plaguicidas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD04', 'Lesión autoinfligida intencionalmente por medio de exposición a sustancias corrosivas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD05', 'Lesión autoinfligida intencionalmente por medio de exposición a sustancias de otro tipo o no especificadas cuyo origen no es principalmente medicinal o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PD20', 'Lesión autoinfligida intencionalmente por medio de cuerpo extraño en orificio corporal', 'category', false, false, 'CIE-11'),
('PD21', 'Lesión autoinfligida intencionalmente por exposición a corriente eléctrica', 'category', false, false, 'CIE-11'),
('PD22', 'Lesión autoinfligida intencionalmente por exposición a la luz solar', 'category', false, false, 'CIE-11'),
('PD23', 'Lesión autoinfligida intencionalmente por exposición a radiación', 'category', false, false, 'CIE-11'),
('PD24', 'Lesión autoinfligida intencionalmente por exposición a presión de aire alta o baja o cambios en la presión del aire', 'category', false, false, 'CIE-11'),
('PD25', 'Lesión autoinfligida intencionalmente por explosión o rotura de materiales u objetos presurizados', 'category', false, false, 'CIE-11'),
('PD26', 'Lesión autoinfligida intencionalmente por esfuerzo físico excesivo', 'category', false, false, 'CIE-11'),
('PD27', 'Lesión autoinfligida intencionalmente por privación de alimentos', 'category', false, false, 'CIE-11'),
('PD28', 'Lesión autoinfligida intencionalmente por privación de agua', 'category', false, false, 'CIE-11'),
('PD29', 'Lesión autoinfligida intencionalmente por otra privación especificada', 'category', false, false, 'CIE-11'),
('PD3Y', 'Otra lesión autoinfligida intencionalmente, especificada', 'category', false, false, 'CIE-11'),
('PD3Z', 'Lesión autoinfligida intencionalmente, sin especificación', 'category', false, false, 'CIE-11'),
('PD50', 'Agresión por evento en transporte terrestre en el tránsito que ocurre en la vía pública y causa traumatismo', 'category', false, false, 'CIE-11'),
('PD51', 'Agresión por evento en transporte terrestre que causa traumatismo y que ocurre fuera del tránsito y de la vía pública', 'category', false, false, 'CIE-11'),
('PD52', 'Agresión por evento en transporte terrestre que causa traumatismo y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PD53', 'Agresión por medio de evento en transporte ferroviario que causa traumatismo', 'category', false, false, 'CIE-11'),
('PD60', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida', 'category', false, false, 'CIE-11'),
('PD60.0', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida, que causa sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PD60.1', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida, que causa otra lesión', 'category', false, false, 'CIE-11'),
('PD60.Z', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo no especificado con embarcación dañada, averiada o destruida', 'category', false, false, 'CIE-11'),
('PD61', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PD61.0', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, que causa sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PD61.1', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, que causa otra lesión', 'category', false, false, 'CIE-11'),
('PD61.Y', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo no especificado con embarcación no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PD61.Z', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, sin especificación', 'category', false, false, 'CIE-11'),
('PD6Z', 'Agresión por medio de evento en transporte marítimo o fluvial que causa traumatismo, sin especificar', 'category', false, false, 'CIE-11'),
('PD70', 'Agresión por medio de evento en transporte aéreo o espacial que causa traumatismo con aeronave o nave espacial dañada, averiada o destruida', 'category', false, false, 'CIE-11'),
('PD71', 'Agresión por medio de evento en transporte aéreo o espacial que causa traumatismo con aeronave o nave espacial no dañada, averiada ni destruida', 'category', false, false, 'CIE-11'),
('PD7Z', 'Agresión por medio de evento en transporte aéreo o espacial que causa traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('PD9Y', 'Otra agresión especificada por evento en transporte', 'category', false, false, 'CIE-11'),
('PD9Z', 'Agresión por evento de transporte, sin especificación', 'category', false, false, 'CIE-11'),
('PE00', 'Agresión al causar caída o salto desde el mismo nivel o desde menos de 1 metro', 'category', false, false, 'CIE-11'),
('PE01', 'Agresión al causar una caída o salto desde una altura de 1 metro o más', 'category', false, false, 'CIE-11'),
('PE0Z', 'Agresión al causar caída o salto desde una altura no especificada', 'category', false, false, 'CIE-11'),
('PE10', 'Agresión al ser golpeado, pateado o empujado por una persona', 'category', false, false, 'CIE-11'),
('PE11', 'Agresión al ser golpeado, pateado o empujado por un animal', 'category', false, false, 'CIE-11'),
('PE12', 'Agresión al ser aplastado o pisoteado por una persona', 'category', false, false, 'CIE-11'),
('PE13', 'Agresión al ser aplastado o pisoteado por un animal', 'category', false, false, 'CIE-11'),
('PE14', 'Agresión al ser mordido por una persona', 'category', false, false, 'CIE-11'),
('PE15', 'Agresión por mordida de un animal', 'category', false, false, 'CIE-11'),
('PE16', 'Agresión al ser arañado o rasguñado por una persona', 'category', false, false, 'CIE-11'),
('PE17', 'Agresión al ser arañado o rasguñado por un animal', 'category', false, false, 'CIE-11'),
('PE18', 'Agresión al ser picado o envenenado por un animal', 'category', false, false, 'CIE-11'),
('PE19', 'Agresión por medio de contacto con planta', 'category', false, false, 'CIE-11'),
('PE1Y', 'Otro tipo de agresión especificada por contacto con persona, animal o planta', 'category', false, false, 'CIE-11'),
('PE1Z', 'Agresión por contacto con persona, animal o planta, sin especificación', 'category', false, false, 'CIE-11'),
('PE20', 'Agresión con proyectil de arma de fuego', 'category', false, false, 'CIE-11'),
('PE20.0', 'Agresión por proyectil de arma corta', 'category', false, false, 'CIE-11'),
('PE20.1', 'Agresión por proyectil de rifle, escopeta o arma larga', 'category', false, false, 'CIE-11'),
('PE20.Y', 'Agresión por impacto con proyectil de otra arma de fuego especificada', 'category', false, false, 'CIE-11'),
('PE20.Z', 'Agresión por impacto con proyectil de arma de fuego, sin especificación', 'category', false, false, 'CIE-11'),
('PE21', 'Agresión por golpe con objeto en movimiento, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('PE22', 'Agresión por medio de golpe contra un objeto estacionario', 'category', false, false, 'CIE-11'),
('PE30', 'Agresión por medio de cortadura o perforación con un cuchillo, espada o puñal', 'category', false, false, 'CIE-11'),
('PE31', 'Agresión por medio de cortadura o perforación por un vidrio cortante', 'category', false, false, 'CIE-11'),
('PE3Z', 'Agresión por medio de cortadura o perforación con un objeto punzante de otro tipo o no especificado', 'category', false, false, 'CIE-11'),
('PE40', 'Agresión por medio de golpe por un objeto contundente o romo', 'category', false, false, 'CIE-11'),
('PE41', 'Agresión al ser atrapado, aplastado, atascado o apretado entre objetos', 'category', false, false, 'CIE-11'),
('PE4Y', 'Agresión por exposición a objeto especificado, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('PE4Z', 'Agresión por exposición a objeto no clasificado en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('PE50', 'Agresión por ahogamiento o sumersión que ocurre mientras la persona está en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PE51', 'Agresión por ahogamiento o sumersión posterior a caída en cuerpo de agua', 'category', false, false, 'CIE-11'),
('PE52', 'Agresión por medio de traumatismo mientras la persona está en un cuerpo de agua, sin ahogamiento', 'category', false, false, 'CIE-11'),
('PE53', 'Agresión por otra lesión que no sea por ahogamiento después de una caída al agua', 'category', false, false, 'CIE-11'),
('PE5Y', 'Otra agresión especificada por inmersión, sumersión o caída en el agua', 'category', false, false, 'CIE-11'),
('PE5Z', 'Agresión por inmersión, sumersión o caída en el agua, sin especificación', 'category', false, false, 'CIE-11'),
('PE60', 'Agresión por medio de amenaza a la respiración por asfixia por objeto que cubre la boca y la nariz', 'category', false, false, 'CIE-11'),
('PE61', 'Agresión por medio de amenaza a la respiración por ahorcamiento', 'category', false, false, 'CIE-11'),
('PE62', 'Agresión por medio de amenaza a la respiración por estrangulamiento', 'category', false, false, 'CIE-11'),
('PE63', 'Agresión por medio de amenaza a la respiración por compresión externa de las vías respiratorias', 'category', false, false, 'CIE-11'),
('PE64', 'Agresión por medio de amenaza a la respiración por inhalación o ingestión de líquidos', 'category', false, false, 'CIE-11'),
('PE65', 'Agresión por medio de amenaza a la respiración por inhalación o ingestión de alimentos', 'category', false, false, 'CIE-11'),
('PE66', 'Agresión por amenaza a la respiración por inhalación o ingestión de otros objetos o materiales', 'category', false, false, 'CIE-11'),
('PE67', 'Agresión por medio de amenaza a la respiración por entorno con poco oxígeno', 'category', false, false, 'CIE-11'),
('PE6Y', 'Otra agresión especificada por obstrucción a la respiración', 'category', false, false, 'CIE-11'),
('PE6Z', 'Agresión por obstrucción a la respiración, sin especificar', 'category', false, false, 'CIE-11'),
('PE70', 'Agresión por exposición a fuego no controlado', 'category', false, false, 'CIE-11'),
('PE71', 'Agresión por exposición a fuego controlado', 'category', false, false, 'CIE-11'),
('PE72', 'Agresión por exposición a la ignición o la fundición de materiales', 'category', false, false, 'CIE-11'),
('PE73', 'Agresión por contacto con objeto o líquido caliente', 'category', false, false, 'CIE-11'),
('PE74', 'Agresión por medio de contacto con vapor, aire o gases calientes', 'category', false, false, 'CIE-11'),
('PE75', 'Agresión por exposición a calor excesivo', 'category', false, false, 'CIE-11'),
('PE76', 'Agresión por medio de exposición a frío excesivo', 'category', false, false, 'CIE-11'),
('PE7Y', 'Agresión por exposición a otro mecanismo térmico especificado', 'category', false, false, 'CIE-11'),
('PE7Z', 'Agresión por exposición a mecanismo térmico, sin especificación', 'category', false, false, 'CIE-11'),
('PE80', 'Agresión por exposición a opioides o analgésicos relacionados o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE81', 'Agresión por exposición a o efectos adversos de sedantes, fármacos hipnóticos u otros depresores del sistema nervioso central', 'category', false, false, 'CIE-11'),
('PE82', 'Agresión por medio de exposición a psicoestimulantes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE83', 'Agresión por exposición a canabinoides o alucinógenos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE84', 'Agresión por exposición a o por efectos nocivos de analgésicos, antipiréticos o anti inflamatorios no esteroideos', 'category', false, false, 'CIE-11'),
('PE85', 'Agresión por exposición a antidepresivos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE86', 'Agresión por exposición a antipsicóticos o a sus posibles efectos nocivos', 'category', false, false, 'CIE-11'),
('PE87', 'Agresión por exposición a fármacos antiepilépticos o antiparkinsonianos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE88', 'Agresión por exposición a fármaco, medicamento o sustancia biológica de otro tipo o de un tipo no especificado, o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE89', 'Agresión por exposición a múltiples fármacos, medicamentos o sustancias biológicas, o por sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE8Y', 'Otra agresión por exposición a fármacos, medicamentos y sustancias biológicas o sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE8Z', 'Agresión por exposición a fármacos, medicamentos y sustancias biológicas o sus efectos nocivos, sin especificación', 'category', false, false, 'CIE-11'),
('PE90', 'Agresión por exposición a alcoholes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE91', 'Agresión por medio de exposición a disolventes orgánicos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE92', 'Agresión por medio de exposición al monóxido de carbono o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE93', 'Agresión por medio de exposición a plaguicidas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE94', 'Agresión por exposición a substancias corrosivas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PE95', 'Agresión por medio de exposición a sustancias de otro tipo o no especificadas cuyo origen no es principalmente medicinal', 'category', false, false, 'CIE-11'),
('PF10', 'Agresión por cuerpo extraño en orificio corporal o en un ojo', 'category', false, false, 'CIE-11'),
('PF11', 'Agresión por exposición a corriente eléctrica', 'category', false, false, 'CIE-11'),
('PF12', 'Agresión por exposición a la luz solar', 'category', false, false, 'CIE-11'),
('PF13', 'Agresión por exposición a radiación', 'category', false, false, 'CIE-11'),
('PF14', 'Agresión por exposición a presión de aire alta o baja o a cambios en la presión del aire', 'category', false, false, 'CIE-11'),
('PF15', 'Agresión por exposición a explosión', 'category', false, false, 'CIE-11'),
('PF15.0', 'Agresión por medio de exposición a explosión química', 'category', false, false, 'CIE-11'),
('PF15.1', 'Agresión por medio de explosión o rotura de materiales u objetos', 'category', false, false, 'CIE-11'),
('PF15.Y', 'Otra agresión por exposición a explosión', 'category', false, false, 'CIE-11'),
('PF15.Z', 'Agresión por exposición a explosión, no especificada', 'category', false, false, 'CIE-11'),
('PF16', 'Agresión por esfuerzo físico excesivo', 'category', false, false, 'CIE-11'),
('PF17', 'Agresión por privación de alimentos', 'category', false, false, 'CIE-11'),
('PF18', 'Agresión por privación de agua', 'category', false, false, 'CIE-11'),
('PF19', 'Agresión por otra privación especificada', 'category', false, false, 'CIE-11'),
('PF1A', 'Agresión por abandono', 'category', false, false, 'CIE-11'),
('PF1B', 'Agresión por negligencia', 'category', false, false, 'CIE-11'),
('PF2Y', 'Otra agresión especificada', 'category', false, false, 'CIE-11'),
('PF2Z', 'Agresión, sin especificación', 'category', false, false, 'CIE-11'),
('PF40', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a peatón', 'category', false, false, 'CIE-11'),
('PF41', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a usuario de medio de locomoción para peatones', 'category', false, false, 'CIE-11'),
('PF42', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ciclista', 'category', false, false, 'CIE-11'),
('PF43', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a motociclista', 'category', false, false, 'CIE-11'),
('PF44', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de automóvil', 'category', false, false, 'CIE-11'),
('PF45', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de autobús o autocar', 'category', false, false, 'CIE-11'),
('PF46', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo de carga liviana', 'category', false, false, 'CIE-11'),
('PF47', 'Evento de intención no determinada en transporte terrestre en el tránsito que lesiona a ocupante de vehículo de carga pesada', 'category', false, false, 'CIE-11'),
('PF48', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de tranvía', 'category', false, false, 'CIE-11'),
('PF49', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo de pasajeros de baja potencia', 'category', false, false, 'CIE-11'),
('PF4A', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo especial usado principalmente en agricultura', 'category', false, false, 'CIE-11'),
('PF4B', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo especial usado principalmente en plantas industriales', 'category', false, false, 'CIE-11'),
('PF4C', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo especial usado en construcción', 'category', false, false, 'CIE-11'),
('PF4D', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo para todo terreno', 'category', false, false, 'CIE-11'),
('PF4E', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a persona montada en un animal', 'category', false, false, 'CIE-11'),
('PF4F', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a ocupante de vehículo de tracción animal', 'category', false, false, 'CIE-11'),
('PF4Y', 'Evento de intención no determinada en transporte terrestre en el tránsito que causa traumatismo a usuario de otro transporte terrestre especificado', 'category', false, false, 'CIE-11'),
('PF4Z', 'Evento de intención no determinada en transporte terrestre que ocurre en el tránsito y que causa traumatismo a usuario de otro transporte terrestre, sin especificar', 'category', false, false, 'CIE-11'),
('PF50', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a peatón', 'category', false, false, 'CIE-11'),
('PF51', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a usuario de medio de locomoción para peatones', 'category', false, false, 'CIE-11'),
('PF52', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a un ciclista', 'category', false, false, 'CIE-11'),
('PF53', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a un motociclista', 'category', false, false, 'CIE-11'),
('PF54', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de automóvil', 'category', false, false, 'CIE-11'),
('PF55', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de autobús o autocar', 'category', false, false, 'CIE-11'),
('PF56', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de vehículo de carga liviana', 'category', false, false, 'CIE-11'),
('PF57', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de vehículo de carga pesada', 'category', false, false, 'CIE-11'),
('PF58', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de tranvía', 'category', false, false, 'CIE-11'),
('PF59', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de vehículo de pasajeros de baja potencia', 'category', false, false, 'CIE-11'),
('PF5A', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a usuario de vehículo especial usado principalmente en agricultura', 'category', false, false, 'CIE-11'),
('PF5B', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a usuario de vehículo especial usado en plantas industriales', 'category', false, false, 'CIE-11'),
('PF5C', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a usuario de vehículo especial usado en construcción', 'category', false, false, 'CIE-11'),
('PF5D', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a usuario de vehículo para todo terreno', 'category', false, false, 'CIE-11'),
('PF5E', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a persona montada en un animal', 'category', false, false, 'CIE-11'),
('PF5F', 'Evento de intención no determinada en transporte terrestre fuera del tránsito que causa traumatismo a ocupante de vehículo de tracción animal', 'category', false, false, 'CIE-11'),
('PF5Y', 'Evento de intención no determinada en transporte terrestre que ocurre fuera del tránsito y que causa traumatismo a usuario de otro transporte terrestre especificado', 'category', false, false, 'CIE-11'),
('PF5Z', 'Evento de intención no determinada en transporte terrestre que ocurre fuera del tránsito y que causa traumatismo a usuario de transporte terrestre no conocido o no especificado', 'category', false, false, 'CIE-11'),
('PF60', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a peatón y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF61', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a usuario de medio de locomoción para peatones y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF62', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a un ciclista y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF63', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a un motociclista y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF64', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de automóvil y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF65', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de autobús o autocar y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF66', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo de carga liviana y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF67', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo de carga pesada y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF68', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de tranvía y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF69', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo de pasajeros de baja potencia y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6A', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo especial usado principalmente en agricultura y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6B', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo especial usado principalmente en plantas industriales y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6C', 'Evento traumático en transporte terrestre de intención no determinada se desconoce si ocurrió en el tránsito por carretera o fuera de la carretera hiriendo a un usuario de un vehículo de construcción especial', 'category', false, false, 'CIE-11'),
('PF6D', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo para todo terreno y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6E', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a persona montada en un animal y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6F', 'Evento de intención no determinada en transporte terrestre que causa traumatismo a ocupante de vehículo de tracción animal y se desconoce si ocurrió en el tránsito y en la vía pública', 'category', false, false, 'CIE-11'),
('PF6Y', 'Evento de intención no determinada en transporte terrestre que se desconoce si ocurrió en el tránsito y en la vía pública y causa traumatismo a usuario de otro vehículo especificado', 'category', false, false, 'CIE-11'),
('PF6Z', 'Evento de intención no determinada en transporte terrestre que se desconoce si ocurrió en el tránsito y en la vía pública y causa traumatismo a usuario de otro vehículo de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('PF70', 'Evento de intención no determinada en transporte ferroviario que causa traumatismo con colisión o descarrilamiento', 'category', false, false, 'CIE-11'),
('PF71', 'Evento de intención no determinada en transporte ferroviario que causa traumatismo sin colisión o descarrilamiento', 'category', false, false, 'CIE-11'),
('PF7Z', 'Evento de intención no determinada en transporte ferroviario que causa traumatismo y es de tipo no especificado', 'category', false, false, 'CIE-11'),
('PF80', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida causante de sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PF8Y', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida causante de otro traumatismo', 'category', false, false, 'CIE-11'),
('PF8Z', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación dañada, averiada o destruida causante de traumatismo no especificado', 'category', false, false, 'CIE-11'),
('PF90', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida causante de sumersión o ahogamiento', 'category', false, false, 'CIE-11'),
('PF9Y', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, causante de otro traumatismo', 'category', false, false, 'CIE-11'),
('PF9Z', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo con embarcación no dañada, averiada ni destruida, causante de traumatismo no especificado', 'category', false, false, 'CIE-11'),
('PG1Z', 'Evento de intención no determinada en transporte marítimo o fluvial que causa traumatismo; daño a embarcación no especificado', 'category', false, false, 'CIE-11'),
('PG20', 'Evento de intención no determinada en transporte aéreo o espacial que causa traumatismo con aeronave o vehículo espacial dañado, averiado o destruido', 'category', false, false, 'CIE-11'),
('PG21', 'Evento de intención no determinada en transporte aéreo o espacial que causa traumatismo con aeronave o vehículo espacial no dañado, averiado ni destruido', 'category', false, false, 'CIE-11'),
('PG2Z', 'Evento de intención no determinada en transporte aéreo o espacial que causa traumatismo; daño a aeronave o vehículo espacial no especificado', 'category', false, false, 'CIE-11'),
('PG4Y', 'Otro evento especificado de intención no determinada en transporte que causa traumatismo', 'category', false, false, 'CIE-11'),
('PG4Z', 'Evento de intención no determinada en transporte que causa traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('PG50', 'Caída o salto de intención no determinada desde el mismo nivel o desde 1 metro de altura o menos', 'category', false, false, 'CIE-11'),
('PG51', 'Caída o salto de intención no determinada desde 1 metro de altura o más', 'category', false, false, 'CIE-11'),
('PG5Z', 'Caída o salto de intención no determinada, altura no especificada', 'category', false, false, 'CIE-11'),
('PG60', 'Golpe, patada o empujón de intención no determinada por una persona', 'category', false, false, 'CIE-11'),
('PG61', 'Golpe, patada o empujón de intención no determinada por un animal', 'category', false, false, 'CIE-11'),
('PG62', 'Persona pisoteada o aplastada con intención no determinada por una persona', 'category', false, false, 'CIE-11'),
('PG63', 'Persona pisoteada o aplastada con intención no determinada por un animal', 'category', false, false, 'CIE-11'),
('PG64', 'Mordedura de intención no determinada por una persona', 'category', false, false, 'CIE-11'),
('PG65', 'Mordedura de intención no determinada por un animal', 'category', false, false, 'CIE-11'),
('PG66', 'Arañazo o rasguño de intención no determinada por una persona', 'category', false, false, 'CIE-11'),
('PG67', 'Arañazo o rasguño de intención no determinada por un animal', 'category', false, false, 'CIE-11'),
('PG68', 'Picadura o envenenamiento de intención no determinada por un animal', 'category', false, false, 'CIE-11'),
('PG69', 'Contacto con planta de intención no determinada', 'category', false, false, 'CIE-11'),
('PG6Y', 'Otro contacto de intención no determinada con persona, animal o planta', 'category', false, false, 'CIE-11'),
('PG6Z', 'Contacto de intención no determinada con persona, animal o planta, sin especificación', 'category', false, false, 'CIE-11'),
('PG70', 'Impacto con intención no determinada por proyectil de arma corta', 'category', false, false, 'CIE-11'),
('PG71', 'Impacto de intención no determinada por proyectil de rifle, escopeta o arma larga', 'category', false, false, 'CIE-11'),
('PG7Y', 'Lesionado por proyectil de otra arma de fuego especificada de intención no determinada', 'category', false, false, 'CIE-11'),
('PG7Z', 'Lesionado por proyectil de arma de fuego no especificada de intención, no determinada', 'category', false, false, 'CIE-11'),
('PG80', 'Golpe con intención no determinada por objeto en movimiento, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('PG81', 'Golpe con intención no determinada contra objeto estacionario', 'category', false, false, 'CIE-11'),
('PG90', 'Cortadura o perforación con intención no determinada por cuchillo, espada o puñal', 'category', false, false, 'CIE-11'),
('PG91', 'Cortadura o perforación con intención no determinada por vidrio cortante', 'category', false, false, 'CIE-11'),
('PG9Z', 'Corte o perforación con otro objeto punzante o no especificado, de intención no determinada', 'category', false, false, 'CIE-11'),
('PH00', 'Golpe con intención no determinada por objeto contundente o romo', 'category', false, false, 'CIE-11'),
('PH01', 'Persona atrapada, aplastada, atascada o apretada con intención no determinada entre objetos', 'category', false, false, 'CIE-11'),
('PH0Y', 'Contacto con otro objeto especificado no clasificado en otra parte con intención no determinada', 'category', false, false, 'CIE-11'),
('PH0Z', 'Exposición a objeto no especificado, no clasificado en otra parte con intención no determinada', 'category', false, false, 'CIE-11'),
('PH10', 'Ahogamiento o sumersión con intención no determinada mientras la persona está en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PH11', 'Ahogamiento o sumersión con intención no determinada posterior a caída en cuerpo de agua', 'category', false, false, 'CIE-11'),
('PH12', 'Traumatismo o lesión de intención no determinada sin ahogamiento que ocurre mientras la persona está en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PH13', 'Traumatismo o lesión de intención no determinada sin ahogamiento posterior a caída en un cuerpo de agua', 'category', false, false, 'CIE-11'),
('PH1Z', 'Inmersión, sumersión o caída al agua con intención no determinada, sin especificar', 'category', false, false, 'CIE-11'),
('PH20', 'Amenaza de intención no determinada a la respiración por asfixia causada por objeto que cubre la boca o la nariz', 'category', false, false, 'CIE-11'),
('PH21', 'Amenaza de intención no determinada a la respiración por ahorcamiento', 'category', false, false, 'CIE-11'),
('PH22', 'Amenaza de intención no determinada a la respiración por estrangulamiento', 'category', false, false, 'CIE-11'),
('PH23', 'Amenaza de intención no determinada a la respiración por comprensión externa de las vías respiratorias o el tórax', 'category', false, false, 'CIE-11'),
('PH24', 'Amenaza de intención no determinada a la respiración por inhalación o ingestión de líquidos', 'category', false, false, 'CIE-11'),
('PH25', 'Amenaza de intención no determinada a la respiración por inhalación o ingestión de alimentos', 'category', false, false, 'CIE-11'),
('PH26', 'Amenaza de intención no determinada a la respiración por inhalación o ingestión de otros objetos o materiales', 'category', false, false, 'CIE-11'),
('PH27', 'Amenaza de intención no determinada a la respiración por entorno con poco oxígeno', 'category', false, false, 'CIE-11'),
('PH2Y', 'Otra amenaza especificada de intención no determinada a la respiración', 'category', false, false, 'CIE-11'),
('PH2Z', 'Amenaza de intención no determinada a la respiración, sin especificación', 'category', false, false, 'CIE-11'),
('PH30', 'Exposición de intención no determinada a fuego no controlado', 'category', false, false, 'CIE-11'),
('PH31', 'Exposición de intención no determinada a fuego controlado', 'category', false, false, 'CIE-11'),
('PH32', 'Exposición de intención no determinada a la ignición o la fundición de materiales', 'category', false, false, 'CIE-11'),
('PH33', 'Contacto de intención no determinada con objeto o liquido caliente', 'category', false, false, 'CIE-11'),
('PH34', 'Contacto de intención no determinada con vapor aire o gases calientes', 'category', false, false, 'CIE-11'),
('PH35', 'Exposición de intención no determinada a calor excesivo', 'category', false, false, 'CIE-11'),
('PH36', 'Exposición de intención no determinada a frío excesivo', 'category', false, false, 'CIE-11'),
('PH3Y', 'Exposición de intención no determinada a otro mecanismo térmico especificado', 'category', false, false, 'CIE-11'),
('PH3Z', 'Exposición de intención no determinada a mecanismo térmico, sin especificación', 'category', false, false, 'CIE-11'),
('PH40', 'Exposición de intención no determinada a opioides o analgésicos relacionados o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH41', 'Exposición de intención no determinada a sedantes hipnóticos u otros depresores del sistema nervioso central o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH42', 'Exposición de intención no determinada a psicoestimulantes o sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH43', 'Exposición no determinada a canabinoides o alucinógenos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH44', 'Exposición a o efectos adversos con intención no determinada de analgésicos, antipiréticos o medicamentos anti inflamatorios no esteroideos', 'category', false, false, 'CIE-11'),
('PH45', 'Exposición de intención no determinada a antidepresivos o sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH46', 'Exposición de intención no determinada a antipsicóticos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH47', 'Exposición de intención no determinada a antiepilépticos o antiparkinsonianos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH47.0', 'Exposición de intención no determinada a antiepilépticos mixtos no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('PH47.Z', 'Intención no determinada: exposición a sustancias nocivas o sus efectos dañinos: fármacos, medicamentos o sustancias biológicas: antiepilépticos o antiparkinsonianos no especificados', 'category', false, false, 'CIE-11'),
('PH48', 'Exposición de intención no determinada a fármacos, medicamentos o sustancias biológicas de otro tipo o no especificados', 'category', false, false, 'CIE-11'),
('PH49', 'Exposición a o efectos adversos de intención no determinada de múltiples drogas, medicamentos o sustancias biológicas', 'category', false, false, 'CIE-11'),
('PH50', 'Exposición de intención no determinada a alcoholes o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH51', 'Exposición de intención no determinada a disolventes orgánicos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH52', 'Exposición de intención no determinada al monóxido de carbono y a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH53', 'Exposición de intención no determinada a plaguicidas o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH54', 'Exposición de intención no determinada a sustancias corrosivas', 'category', false, false, 'CIE-11'),
('PH55', 'Exposición de intención no determinada a derivados halogenados de los hidrocarburos alifáticos o aromáticos o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH56', 'Exposición de intención no determinada a sustancias de otro tipo o no especificadas de procedencia principalmente no medicinal o a sus efectos nocivos', 'category', false, false, 'CIE-11'),
('PH70', 'Exposición de intención no determinada a cuerpo extraño en orificio corporal o en un ojo', 'category', false, false, 'CIE-11'),
('PH71', 'Exposición a corriente eléctrica con intención no determinada', 'category', false, false, 'CIE-11'),
('PH72', 'Exposición de intención no determinada a la luz solar', 'category', false, false, 'CIE-11'),
('PH73', 'Exposición de intención no determinada a la radiación', 'category', false, false, 'CIE-11'),
('PH74', 'Exposición de intención no determinada a presión de aire alta o baja o a cambios en la presión del aire', 'category', false, false, 'CIE-11'),
('PH75', 'Exposición de intención no determinada a explosión', 'category', false, false, 'CIE-11'),
('PH75.0', 'Exposición de intención no determinada a explosión química', 'category', false, false, 'CIE-11'),
('PH75.1', 'Exposición de intención no determinada a explosión o ruptura de materiales u objetos presurizados', 'category', false, false, 'CIE-11'),
('PH75.Y', 'Otra exposición especificada de intención no determinada a explosión', 'category', false, false, 'CIE-11'),
('PH75.Z', 'Exposición de intención no determinada a explosión, sin especificación', 'category', false, false, 'CIE-11'),
('PH76', 'Esfuerzo físico excesivo de intención no determinada', 'category', false, false, 'CIE-11'),
('PH77', 'Privación de alimentos de intención no determinada', 'category', false, false, 'CIE-11'),
('PH78', 'Privación de agua de intención no determinada', 'category', false, false, 'CIE-11'),
('PH79', 'Otra privación especificada con intención no determinada', 'category', false, false, 'CIE-11'),
('PH7A', 'Abandono con intención no determinada', 'category', false, false, 'CIE-11'),
('PH7B', 'Negligencia con intención no determinada', 'category', false, false, 'CIE-11'),
('PH8Y', 'Otra lesión especificada de intención no determinada', 'category', false, false, 'CIE-11'),
('PH8Z', 'Lesión de intención no determinada, sin especificación', 'category', false, false, 'CIE-11'),
('PJ00', 'Víctima de rayo', 'category', false, false, 'CIE-11'),
('PJ01', 'Víctima de terremoto', 'category', false, false, 'CIE-11'),
('PJ02', 'Víctima de movimientos catastróficos de tierra causados por terremoto', 'category', false, false, 'CIE-11'),
('PJ03', 'Víctima de tsunami', 'category', false, false, 'CIE-11'),
('PJ04', 'Victima de erupción volcánica', 'category', false, false, 'CIE-11'),
('PJ05', 'Víctima de avalancha, derrumbe u otro movimiento de tierra', 'category', false, false, 'CIE-11'),
('PJ06', 'Víctima de tormenta cataclísmica', 'category', false, false, 'CIE-11'),
('PJ07', 'Víctima de inundación', 'category', false, false, 'CIE-11'),
('PJ0Y', 'Exposición a otras fuerzas especificadas de la naturaleza', 'category', false, false, 'CIE-11'),
('PJ0Z', 'Exposición a fuerzas de la naturaleza, sin especificación', 'category', false, false, 'CIE-11'),
('PJ20', 'Maltrato físico', 'category', false, false, 'CIE-11'),
('PJ21', 'Maltrato sexual', 'category', false, false, 'CIE-11'),
('PJ22', 'Maltrato psicológico', 'category', false, false, 'CIE-11'),
('PJ2Y', 'Otro maltrato especificado', 'category', false, false, 'CIE-11'),
('PJ2Z', 'Maltrato, sin especificación', 'category', false, false, 'CIE-11'),
('PJ40', 'Intervención legal con proyectil de arma de fuego', 'category', false, false, 'CIE-11'),
('PJ41', 'Intervención legal con otro proyectil', 'category', false, false, 'CIE-11'),
('PJ42', 'Intervención legal con objeto contundente', 'category', false, false, 'CIE-11'),
('PJ43', 'Intervención legal con objeto punzante', 'category', false, false, 'CIE-11'),
('PJ44', 'Intervención legal con arma eléctrica', 'category', false, false, 'CIE-11'),
('PJ45', 'Intervención legal con explosivo', 'category', false, false, 'CIE-11'),
('PJ46', 'Intervención legal con gas', 'category', false, false, 'CIE-11'),
('PJ47', 'Intervención legal con aplicación de la fuerza física', 'category', false, false, 'CIE-11'),
('PJ4Y', 'Otra intervención legal especificada', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
