-- CIE11 Import Part 29
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('NB32.Z', 'Traumatismo no especificado de órganos intratorácicos no especificados', 'category', false, false, 'CIE-11'),
('NB33', 'Traumatismo por aplastamiento del tórax o amputación traumática de parte del tórax', 'category', false, false, 'CIE-11'),
('NB33.0', 'Aplastamiento torácico', 'category', false, false, 'CIE-11'),
('NB33.1', 'Amputación traumática de mama', 'category', false, false, 'CIE-11'),
('NB33.10', 'Amputación traumática de parte de la mama', 'category', false, false, 'CIE-11'),
('NB33.11', 'Amputación traumática de toda la mama', 'category', false, false, 'CIE-11'),
('NB33.1Z', 'Amputación traumática de mama, sin especificación', 'category', false, false, 'CIE-11'),
('NB33.2', 'Amputación traumática de otra parte del tórax o una parte del tórax no especificada', 'category', false, false, 'CIE-11'),
('NB34', 'Traumatismo en tendón, fascia o músculo a nivel del tórax', 'category', false, false, 'CIE-11'),
('NB34.0', 'Distensión o esguince de tendón, fascia o músculo a nivel del tórax', 'category', false, false, 'CIE-11'),
('NB34.1', 'Desgarro de tendón, fascia o músculo a nivel del tórax', 'category', false, false, 'CIE-11'),
('NB34.Y', 'Otra lesión traumática especificada de músculo, fascia o tendón a nivel del tórax', 'category', false, false, 'CIE-11'),
('NB34.Z', 'Lesión traumática de músculo, fascia o tendón a nivel del tórax, sin especificación', 'category', false, false, 'CIE-11'),
('NB35', 'Traumatismos múltiples en el tórax', 'category', false, false, 'CIE-11'),
('NB3Y', 'Otros traumatismos especificados en el tórax', 'category', false, false, 'CIE-11'),
('NB3Z', 'Traumatismos en el tórax, sin especificación', 'category', false, false, 'CIE-11'),
('NB50', 'Traumatismo superficial en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB50.0', 'Excoriación en la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB50.1', 'Contusión en la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB50.2', 'Excoriación en la pared abdominal', 'category', false, false, 'CIE-11'),
('NB50.3', 'Contusión en la pared abdominal', 'category', false, false, 'CIE-11'),
('NB50.4', 'Excoriación en los órganos genitales externos', 'category', false, false, 'CIE-11'),
('NB50.5', 'Contusión en los órganos genitales externos', 'category', false, false, 'CIE-11'),
('NB50.6', 'Traumatismos superficiales múltiples en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB50.Y', 'Otro traumatismo superficial especificado en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB50.Z', 'Traumatismo superficial en el abdomen, la zona lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB51', 'Herida abierta en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.0', 'Laceración en el abdomen, la zona lumbar o la pelvis, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NB51.1', 'Laceración en el abdomen, la zona lumbar o la pelvis, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NB51.2', 'Herida punzante sin cuerpo extraño en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.3', 'Herida punzante con cuerpo extraño en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.4', 'Mordedura o picadura abierta en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.5', 'Heridas abiertas múltiples en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.Y', 'Otra herida abierta especificada del abdomen, la espalda baja o la pelvis', 'category', false, false, 'CIE-11'),
('NB51.Z', 'Herida abierta del abdomen, la espalda baja o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB52', 'Fractura de la columna lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB52.0', 'Fractura de vértebra lumbar', 'category', false, false, 'CIE-11'),
('NB52.1', 'Fractura de hueso pélvico sin interrupción del arco posterior del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.10', 'Fractura del hueso sacro sin interrupción de anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.11', 'Fractura del cóccix', 'category', false, false, 'CIE-11'),
('NB52.12', 'Fractura del hueso ilíaco sin interrupción del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.13', 'Fractura del acetábulo sin interrupción de anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.14', 'Fractura del pubis sin interrupción del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.15', 'Fractura del isquion sin interrupción del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.1Y', 'Otra fractura de hueso pélvico especificado sin interrupción del arco posterior del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB52.1Z', 'Fractura de hueso pélvico sin interrupción del arco posterior del anillo pélvico, sin especificación', 'category', false, false, 'CIE-11'),
('NB52.2', 'Fractura del anillo pélvico con interrupción incompleta del arco posterior', 'category', false, false, 'CIE-11'),
('NB52.3', 'Fractura del anillo pélvico con interrupción completa del arco posterior', 'category', false, false, 'CIE-11'),
('NB52.4', 'Fracturas múltiples de la columna lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB52.Y', 'Otra fractura especificada de la columna lumbar o de la pelvis', 'category', false, false, 'CIE-11'),
('NB52.Z', 'Fractura de la columna lumbar o de la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB53', 'Luxación, distensión o esguince de articulaciones o ligamentos de la columna lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB53.0', 'Ruptura traumática de disco intervertebral lumbar', 'category', false, false, 'CIE-11'),
('NB53.1', 'Luxación de vértebra lumbar', 'category', false, false, 'CIE-11'),
('NB53.2', 'Luxación de articulación sacrococcígea o sacroilíaca sin interrupción del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB53.3', 'Luxación de otras partes o de partes no especificadas de la columna lumbar o la pelvis sin alteración del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB53.4', 'Ruptura traumática de la sínfisis del pubis sin alteración del anillo pélvico', 'category', false, false, 'CIE-11'),
('NB53.5', 'Distensión o esguince de la columna lumbar', 'category', false, false, 'CIE-11'),
('NB53.6', 'Distensión o esguince de la articulación sacroilíaca', 'category', false, false, 'CIE-11'),
('NB53.Y', 'Otra luxación, distensión o esguince especificado de articulaciones o ligamentos de la columna lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB53.Z', 'Luxación, distensión o esguince de articulaciones o ligamentos de la columna lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB60', 'Conmoción o edema en la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB61', 'Conmoción o edema en la médula espinal sacra', 'category', false, false, 'CIE-11'),
('NB62', 'Algunos traumatismos especificados de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.0', 'Traumatismo completo en la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.1', 'Síndrome de contusión centromedular de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.2', 'Síndrome del cordón anterior de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.3', 'Síndrome del cordón posterior de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.4', 'Síndrome Brown-Séquard de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.5', 'Otro síndrome de cordón incompleto de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB62.6', 'Herida punzante o desgarro de la duramadre de la médula espinal lumbar', 'category', false, false, 'CIE-11'),
('NB63', 'Algunos traumatismos especificados en la médula espinal sacra', 'category', false, false, 'CIE-11'),
('NB63.0', 'Lesión completa de la médula espinal sacra', 'category', false, false, 'CIE-11'),
('NB63.1', 'Lesión incompleta de la médula espinal sacra', 'category', false, false, 'CIE-11'),
('NB63.Z', 'Traumatismos en la médula espinal sacra, sin especificación', 'category', false, false, 'CIE-11'),
('NB6Z', 'Traumatismo en la médula espinal en el abdomen, la zona lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB70', 'Traumatismo en la raíz nerviosa de la columna lumbar', 'category', false, false, 'CIE-11'),
('NB71', 'Traumatismo en la raíz nerviosa de la columna sacra', 'category', false, false, 'CIE-11'),
('NB72', 'Traumatismo en la cola de caballo', 'category', false, false, 'CIE-11'),
('NB73', 'Traumatismo en el plexo lumbosacro', 'category', false, false, 'CIE-11'),
('NB74', 'Traumatismo en los nervios simpáticos lumbares, sacros o pélvicos', 'category', false, false, 'CIE-11'),
('NB75', 'Traumatismo en los nervios periféricos del abdomen, la región lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB7Y', 'Otro traumatismo especificado de los nervios a nivel del abdomen, la parte inferior de la espalda o la pelvis', 'category', false, false, 'CIE-11'),
('NB7Z', 'Traumatismo en los nervios a nivel del abdomen, la parte inferior de la espalda o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB90', 'Traumatismos en los vasos sanguíneos a nivel del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB90.0', 'Traumatismo en la aorta abdominal', 'category', false, false, 'CIE-11'),
('NB90.00', 'Desgarro menor en la aorta abdominal', 'category', false, false, 'CIE-11'),
('NB90.01', 'Desgarro mayor en la aorta abdominal', 'category', false, false, 'CIE-11'),
('NB90.0Y', 'Otro traumatismo especificado en la aorta abdominal', 'category', false, false, 'CIE-11'),
('NB90.0Z', 'Traumatismo en la aorta abdominal, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.1', 'Traumatismo en la vena cava inferior', 'category', false, false, 'CIE-11'),
('NB90.10', 'Desgarro menor en la vena cava inferior', 'category', false, false, 'CIE-11'),
('NB90.11', 'Desgarro mayor en la vena cava inferior', 'category', false, false, 'CIE-11'),
('NB90.1Y', 'Otro traumatismo especificado en la vena cava inferior', 'category', false, false, 'CIE-11'),
('NB90.1Z', 'Traumatismo en la vena cava inferior, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.2', 'Traumatismo en la arteria celíaca', 'category', false, false, 'CIE-11'),
('NB90.20', 'Desgarro menor en la arteria celíaca', 'category', false, false, 'CIE-11'),
('NB90.21', 'Desgarro mayor en la arteria celíaca', 'category', false, false, 'CIE-11'),
('NB90.2Y', 'Otro traumatismo especificado en la arteria celíaca', 'category', false, false, 'CIE-11'),
('NB90.2Z', 'Traumatismo en la arteria celíaca, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.3', 'Traumatismo en la arteria mesentérica', 'category', false, false, 'CIE-11'),
('NB90.30', 'Desgarro menor en la arteria mesentérica', 'category', false, false, 'CIE-11'),
('NB90.31', 'Desgarrol mayor en la arteria mesentérica', 'category', false, false, 'CIE-11'),
('NB90.3Y', 'Otro traumatismo especificado en la arteria mesentérica', 'category', false, false, 'CIE-11'),
('NB90.3Z', 'Traumatismo en la arteria mesentérica, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.4', 'Traumatismo en las venas porta y esplénica', 'category', false, false, 'CIE-11'),
('NB90.40', 'Desgarro menor en la vena porta o esplénica', 'category', false, false, 'CIE-11'),
('NB90.41', 'Desgarro mayor en la vena porta o esplénica', 'category', false, false, 'CIE-11'),
('NB90.4Y', 'Otro traumatismo especificado en las venas porta y esplénica', 'category', false, false, 'CIE-11'),
('NB90.4Z', 'Traumatismo en las venas porta y esplénica, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.5', 'Traumatismo en los vasos sanguíneos renales', 'category', false, false, 'CIE-11'),
('NB90.50', 'Desgarro menor en los vasos sanguíneos renales', 'category', false, false, 'CIE-11'),
('NB90.51', 'Desgarro mayor en los vasos sanguíneos renales', 'category', false, false, 'CIE-11'),
('NB90.5Y', 'Otro traumatismo especificado en los vasos sanguíneos renales', 'category', false, false, 'CIE-11'),
('NB90.5Z', 'Traumatismo en los vasos sanguíneos renales, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.6', 'Traumatismo en los vasos sanguíneos iliacos', 'category', false, false, 'CIE-11'),
('NB90.60', 'Desgarro menor en los vasos sanguíneos ilíacos', 'category', false, false, 'CIE-11'),
('NB90.61', 'Desgarro mayor en los vasos sanguíneos ilíacos', 'category', false, false, 'CIE-11'),
('NB90.6Y', 'Otro traumatismo especificado en los vasos sanguíneos iliacos', 'category', false, false, 'CIE-11'),
('NB90.6Z', 'Traumatismo en los vasos sanguíneos iliacos, sin especificación', 'category', false, false, 'CIE-11'),
('NB90.7', 'Traumatismo en múltiples vasos sanguíneos a nivel del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB90.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB90.Z', 'Traumatismo en los vasos sanguíneos a nivel del abdomen, la zona lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB91', 'Traumatismo en los órganos intrabdominales', 'category', false, false, 'CIE-11'),
('NB91.0', 'Traumatismo en el bazo', 'category', false, false, 'CIE-11'),
('NB91.00', 'Contusión en el bazo, menor', 'category', false, false, 'CIE-11'),
('NB91.01', 'Contusión en el bazo, mayor', 'category', false, false, 'CIE-11'),
('NB91.02', 'Desgarro del bazo, menor', 'category', false, false, 'CIE-11'),
('NB91.03', 'Desgarro del bazo, moderado', 'category', false, false, 'CIE-11'),
('NB91.04', 'Desgarro del bazo, mayor', 'category', false, false, 'CIE-11'),
('NB91.05', 'Avulsión del bazo', 'category', false, false, 'CIE-11'),
('NB91.0Y', 'Otra lesión traumática especificada del bazo', 'category', false, false, 'CIE-11'),
('NB91.0Z', 'Lesión traumática del bazo, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.1', 'Traumatismo hepático', 'category', false, false, 'CIE-11'),
('NB91.10', 'Contusión hepática', 'category', false, false, 'CIE-11'),
('NB91.11', 'Desgarro hepático menor', 'category', false, false, 'CIE-11'),
('NB91.12', 'Desgarro hepático moderado', 'category', false, false, 'CIE-11'),
('NB91.13', 'Desgarro hepático mayor', 'category', false, false, 'CIE-11'),
('NB91.14', 'Traumatismo en el conducto hepático', 'category', false, false, 'CIE-11'),
('NB91.1Y', 'Otro traumatismo hepático especificado', 'category', false, false, 'CIE-11'),
('NB91.1Z', 'Traumatismo hepático, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.2', 'Traumatismo en la vesícula biliar', 'category', false, false, 'CIE-11'),
('NB91.3', 'Traumatismo en el conducto biliar', 'category', false, false, 'CIE-11'),
('NB91.4', 'Traumatismo en el páncreas', 'category', false, false, 'CIE-11'),
('NB91.40', 'Contusión pancreática', 'category', false, false, 'CIE-11'),
('NB91.41', 'Desgarro pancreático menor', 'category', false, false, 'CIE-11'),
('NB91.42', 'Desgarro pancreático moderado', 'category', false, false, 'CIE-11'),
('NB91.43', 'Desgarro pancreático mayor', 'category', false, false, 'CIE-11'),
('NB91.4Y', 'Otro traumatismo especificado en el páncreas', 'category', false, false, 'CIE-11'),
('NB91.4Z', 'Traumatismo en el páncreas, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.5', 'Traumatismo gástrico', 'category', false, false, 'CIE-11'),
('NB91.50', 'Contusión gástrica', 'category', false, false, 'CIE-11'),
('NB91.51', 'Desgarro gástrico, sin perforación', 'category', false, false, 'CIE-11'),
('NB91.52', 'Desgarro gástrico, con perforación, avulsión o daño masivo', 'category', false, false, 'CIE-11'),
('NB91.53', 'Traumatismo en el estómago por ingestión, sin perforación', 'category', false, false, 'CIE-11'),
('NB91.54', 'Traumatismo en el estómago por ingestión, con perforación', 'category', false, false, 'CIE-11'),
('NB91.5Y', 'Otro traumatismo gástrico especificado', 'category', false, false, 'CIE-11'),
('NB91.5Z', 'Traumatismo gástrico, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.6', 'Traumatismo duodenal', 'category', false, false, 'CIE-11'),
('NB91.60', 'Contusión duodenal', 'category', false, false, 'CIE-11'),
('NB91.61', 'Desgarro duodenal', 'category', false, false, 'CIE-11'),
('NB91.62', 'Traumatismo duodenal primario por onda expansiva', 'category', false, false, 'CIE-11'),
('NB91.63', 'Perforación traumática del duodeno', 'category', false, false, 'CIE-11'),
('NB91.6Y', 'Otro traumatismo duodenal especificado', 'category', false, false, 'CIE-11'),
('NB91.6Z', 'Traumatismo duodenal, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.7', 'Traumatismo en el intestino delgado', 'category', false, false, 'CIE-11'),
('NB91.70', 'Contusión en el intestino delgado', 'category', false, false, 'CIE-11'),
('NB91.71', 'Laceración del intestino delgado', 'category', false, false, 'CIE-11'),
('NB91.72', 'Traumatismo primario en el intestino delgado por onda expansiva', 'category', false, false, 'CIE-11'),
('NB91.7Y', 'Otro traumatismo especificado en el intestino delgado', 'category', false, false, 'CIE-11'),
('NB91.7Z', 'Traumatismo en el intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.8', 'Traumatismo en el colon', 'category', false, false, 'CIE-11'),
('NB91.80', 'Contusión en el colon', 'category', false, false, 'CIE-11'),
('NB91.81', 'Desgarro en el colon', 'category', false, false, 'CIE-11'),
('NB91.82', 'Traumatismo primario en el colon por onda expansiva', 'category', false, false, 'CIE-11'),
('NB91.8Y', 'Otro traumatismo especificado en el colon', 'category', false, false, 'CIE-11'),
('NB91.8Z', 'Traumatismo en el colon, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.9', 'Traumatismo en el recto', 'category', false, false, 'CIE-11'),
('NB91.90', 'Contusión en el recto', 'category', false, false, 'CIE-11'),
('NB91.91', 'Desgarro en el recto', 'category', false, false, 'CIE-11'),
('NB91.92', 'Traumatismo primario en el recto por onda expansiva', 'category', false, false, 'CIE-11'),
('NB91.9Y', 'Otro traumatismo especificado en el recto', 'category', false, false, 'CIE-11'),
('NB91.9Z', 'Traumatismo en el recto, sin especificación', 'category', false, false, 'CIE-11'),
('NB91.A', 'Traumatismo en el mesenterio', 'category', false, false, 'CIE-11'),
('NB91.B', 'Traumatismo en múltiples órganos intrabdominales', 'category', false, false, 'CIE-11'),
('NB91.Y', 'Traumatismo en otros órganos intrabdominales especificados', 'category', false, false, 'CIE-11'),
('NB91.Z', 'Traumatismo en los órganos intrabdominales, sin especificación', 'category', false, false, 'CIE-11'),
('NB92', 'Traumatismo en los órganos urinarios o pélvicos', 'category', false, false, 'CIE-11'),
('NB92.0', 'Traumatismo renal', 'category', false, false, 'CIE-11'),
('NB92.00', 'Contusión renal menor', 'category', false, false, 'CIE-11'),
('NB92.01', 'Contusión renal mayor', 'category', false, false, 'CIE-11'),
('NB92.02', 'Desgarro renal menor', 'category', false, false, 'CIE-11'),
('NB92.03', 'Desgarro renal moderado', 'category', false, false, 'CIE-11'),
('NB92.04', 'Desgarro renal mayor', 'category', false, false, 'CIE-11'),
('NB92.0Y', 'Otro traumatismo renal especificado', 'category', false, false, 'CIE-11'),
('NB92.0Z', 'Traumatismo renal, sin especificación', 'category', false, false, 'CIE-11'),
('NB92.1', 'Traumatismo en el uréter', 'category', false, false, 'CIE-11'),
('NB92.10', 'Contusión en el uréter', 'category', false, false, 'CIE-11'),
('NB92.11', 'Desgarro en el uréter', 'category', false, false, 'CIE-11'),
('NB92.1Y', 'Otro traumatismo especificado en el uréter', 'category', false, false, 'CIE-11'),
('NB92.1Z', 'Traumatismo en el uréter, sin especificación', 'category', false, false, 'CIE-11'),
('NB92.2', 'Traumatismo en la vejiga', 'category', false, false, 'CIE-11'),
('NB92.20', 'Contusión en la vejiga', 'category', false, false, 'CIE-11'),
('NB92.21', 'Desgarro en la vejiga', 'category', false, false, 'CIE-11'),
('NB92.2Y', 'Otro traumatismo especificado en la vejiga', 'category', false, false, 'CIE-11'),
('NB92.2Z', 'Traumatismo en la vejiga, sin especificación', 'category', false, false, 'CIE-11'),
('NB92.3', 'Traumatismo de uretra', 'category', false, false, 'CIE-11'),
('NB92.30', 'Contusión en la uretra', 'category', false, false, 'CIE-11'),
('NB92.31', 'Desgarro en la uretra', 'category', false, false, 'CIE-11'),
('NB92.3Y', 'Otro traumatismo especificado de uretra', 'category', false, false, 'CIE-11'),
('NB92.3Z', 'Traumatismo de uretra, sin especificación', 'category', false, false, 'CIE-11'),
('NB92.4', 'Traumatismo en el ovario', 'category', false, false, 'CIE-11'),
('NB92.40', 'Contusión en el ovario', 'category', false, false, 'CIE-11'),
('NB92.41', 'Desgarro en el ovario', 'category', false, false, 'CIE-11'),
('NB92.4Y', 'Otro traumatismo especificado en el ovario', 'category', false, false, 'CIE-11'),
('NB92.4Z', 'Traumatismo en el ovario, sin especificación', 'category', false, false, 'CIE-11'),
('NB92.5', 'Traumatismo en la trompa de Falopio', 'category', false, false, 'CIE-11'),
('NB92.6', 'Traumatismo uterino', 'category', false, false, 'CIE-11'),
('NB92.7', 'Lesión en las vías urinarias', 'category', false, false, 'CIE-11'),
('NB92.8', 'Traumatismo en múltiples órganos pélvicos', 'category', false, false, 'CIE-11'),
('NB92.Y', 'Otro traumatismo en órganos pélvicos especificados', 'category', false, false, 'CIE-11'),
('NB92.Z', 'Traumatismo en otros órganos pélvicos, sin especificación', 'category', false, false, 'CIE-11'),
('NB93', 'Traumatismo por aplastamiento o amputación traumática de parte del abdomen, la zona lumbar y la pelvis', 'category', false, false, 'CIE-11'),
('NB93.0', 'Traumatismo por aplastamiento de órganos genitales externos', 'category', false, false, 'CIE-11'),
('NB93.00', 'Traumatismo por aplastamiento del pene', 'category', false, false, 'CIE-11'),
('NB93.01', 'Traumatismo por aplastamiento de los testículos o el escroto', 'category', false, false, 'CIE-11'),
('NB93.02', 'Traumatismo por aplastamiento de la vulva', 'category', false, false, 'CIE-11'),
('NB93.0Z', 'Traumatismo por aplastamiento de órganos genitales externos, sin especificación', 'category', false, false, 'CIE-11'),
('NB93.1', 'Traumatismo por aplastamiento de otras partes o de partes no especificadas del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB93.2', 'Amputación traumática de órganos genitales externos', 'category', false, false, 'CIE-11'),
('NB93.20', 'Amputación traumática completa del pene', 'category', false, false, 'CIE-11'),
('NB93.21', 'Amputación traumática de parte del pene', 'category', false, false, 'CIE-11'),
('NB93.22', 'Amputación traumática completa de los testículos o del escroto', 'category', false, false, 'CIE-11'),
('NB93.23', 'Amputación traumática de una parte de los testículos o del escroto', 'category', false, false, 'CIE-11'),
('NB93.24', 'Amputación traumática completa de la vulva', 'category', false, false, 'CIE-11'),
('NB93.25', 'Amputación traumática de parte de la vulva', 'category', false, false, 'CIE-11'),
('NB93.2Z', 'Amputación traumática de órganos genitales externos, sin especificación', 'category', false, false, 'CIE-11'),
('NB93.3', 'Amputación traumática de otras partes o de partes no especificadas del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB94', 'Traumatismo en tendón, fascia o músculo del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB94.0', 'Esguince o desgarro de tendón, fascia o músculo del abdomen', 'category', false, false, 'CIE-11'),
('NB94.1', 'Esguince o desgarro de tendón, fascia o músculo de la zona lumbar', 'category', false, false, 'CIE-11'),
('NB94.2', 'Esguince o desgarro de tendón, fascia o músculo de la pelvis', 'category', false, false, 'CIE-11'),
('NB94.3', 'Desgarro de tendón, fascia o músculo del abdomen', 'category', false, false, 'CIE-11'),
('NB94.4', 'Desgarro de tendón, fascia o músculo de la región lumbosacra', 'category', false, false, 'CIE-11'),
('NB94.5', 'Desgarro de tendón, fascia o músculo de la pelvis', 'category', false, false, 'CIE-11'),
('NB94.Y', 'Otro traumatismo en tendón, fascia o músculo del abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB94.Z', 'Traumatismo en tendón, fascia o músculo del abdomen, la zona lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NB95', 'Traumatismo en órgano intrabdominal y órgano pélvico', 'category', false, false, 'CIE-11'),
('NB96', 'Otros traumatismos múltiples en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB97', 'Otros traumatismos especificados en el abdomen, la zona lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB97.0', 'Hemorragia o hematoma retroperitoneal', 'category', false, false, 'CIE-11'),
('NB97.1', 'Pene fracturado', 'category', false, false, 'CIE-11'),
('NB98', 'Traumatismo en los órganos genitales femeninos sin especificación del tipo', 'category', false, false, 'CIE-11'),
('NB99', 'Traumatismo en los genitales masculinos sin especificación del tipo', 'category', false, false, 'CIE-11'),
('NB9Y', 'Otros traumatismos especificados en el abdomen, la zona lumbar, la columna lumbar o la pelvis', 'category', false, false, 'CIE-11'),
('NB9Z', 'Traumatismos en el abdomen, la zona lumbar, la columna lumbar o la pelvis, sin especificación', 'category', false, false, 'CIE-11'),
('NC10', 'Traumatismo superficial del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC10.0', 'Excoriación en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC10.1', 'Contusión del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC10.2', 'Traumatismos superficiales múltiples en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC10.Y', 'Otro traumatismo superficial especificado del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC10.Z', 'Traumatismo superficial del hombro o de la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC11', 'Herida abierta en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.0', 'Desgarro sin cuerpo extraño en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.1', 'Desgarro con cuerpo extraño en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.2', 'Herida punzante sin cuerpo extraño en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.3', 'Herida punzante con cuerpo extraño en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.4', 'Mordedura o picadura abierta en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.5', 'Heridas abiertas múltiples en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.Y', 'Otra herida abierta especificada en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC11.Z', 'Herida abierta en el hombro o la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC12', 'Fractura del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC12.0', 'Fractura de la clavícula', 'category', false, false, 'CIE-11'),
('NC12.00', 'Fractura del extremo esternal de la clavícula', 'category', false, false, 'CIE-11'),
('NC12.01', 'Fractura del eje de la clavícula', 'category', false, false, 'CIE-11'),
('NC12.02', 'Fractura del extremo acromial de la clavícula', 'category', false, false, 'CIE-11'),
('NC12.03', 'Fracturas múltiples en la clavícula solamente', 'category', false, false, 'CIE-11'),
('NC12.0Y', 'Otra fractura especificada de la clavícula', 'category', false, false, 'CIE-11'),
('NC12.0Z', 'Fractura de la clavícula, sin especificación', 'category', false, false, 'CIE-11'),
('NC12.1', 'Fractura del omóplato', 'category', false, false, 'CIE-11'),
('NC12.10', 'Fracturas múltiples en el omóplato', 'category', false, false, 'CIE-11'),
('NC12.1Y', 'Otra fractura especificada del omóplato', 'category', false, false, 'CIE-11'),
('NC12.1Z', 'Fractura del omóplato, sin especificación', 'category', false, false, 'CIE-11'),
('NC12.2', 'Fractura de la epífisis superior del húmero', 'category', false, false, 'CIE-11'),
('NC12.20', 'Fractura de la epífisis superior del húmero, cabeza', 'category', false, false, 'CIE-11'),
('NC12.21', 'Fractura del cuello quirúrgico del húmero', 'category', false, false, 'CIE-11'),
('NC12.22', 'Fractura del cuello anatómico del húmero', 'category', false, false, 'CIE-11'),
('NC12.23', 'Fractura de la tuberosidad mayor del húmero', 'category', false, false, 'CIE-11'),
('NC12.24', 'Fractura de la tuberosidad menor del húmero', 'category', false, false, 'CIE-11'),
('NC12.2Z', 'Fractura de la epífisis superior del húmero, sin especificación', 'category', false, false, 'CIE-11'),
('NC12.3', 'Fractura de la diáfisis del húmero', 'category', false, false, 'CIE-11'),
('NC12.4', 'Fractura de la epífisis inferior del húmero', 'category', false, false, 'CIE-11'),
('NC12.40', 'Fractura supracondílea del húmero', 'category', false, false, 'CIE-11'),
('NC12.41', 'Fractura del epicóndilo lateral del húmero', 'category', false, false, 'CIE-11'),
('NC12.42', 'Fractura del epicóndilo medial del húmero', 'category', false, false, 'CIE-11'),
('NC12.43', 'Fractura del cóndilo lateral del húmero', 'category', false, false, 'CIE-11'),
('NC12.44', 'Fractura del cóndilo medial del húmero', 'category', false, false, 'CIE-11'),
('NC12.4Y', 'Otra fractura especificada de la epífisis inferior del húmero', 'category', false, false, 'CIE-11'),
('NC12.4Z', 'Fractura de la epífisis inferior del húmero, sin especificación', 'category', false, false, 'CIE-11'),
('NC12.5', 'Fracturas múltiples en la clavícula, el omóplato o el húmero', 'category', false, false, 'CIE-11'),
('NC12.Y', 'Otro(a)(s) fractura del hombro o de la parte superior del brazo especificado(a)(s)', 'category', false, false, 'CIE-11'),
('NC12.Z', 'Fractura del hombro o de la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC13', 'Luxación, distensión o esguince de las articulaciones o ligamentos de la cintura escapular', 'category', false, false, 'CIE-11'),
('NC13.0', 'Luxación de la articulación del hombro', 'category', false, false, 'CIE-11'),
('NC13.1', 'Luxación de la articulación acromioclavicular', 'category', false, false, 'CIE-11'),
('NC13.2', 'Luxación de la articulación esternoclavicular', 'category', false, false, 'CIE-11'),
('NC13.3', 'Luxación de la escápula', 'category', false, false, 'CIE-11'),
('NC13.4', 'Luxación de otras partes o de partes no especificadas de la cintura escapular', 'category', false, false, 'CIE-11'),
('NC13.5', 'Distensión o esguince de la articulación del hombro', 'category', false, false, 'CIE-11'),
('NC13.6', 'Distensión o esguince de la articulación acromioclavicular', 'category', false, false, 'CIE-11'),
('NC13.7', 'Distensión o esguince de la articulación esternoclavicular', 'category', false, false, 'CIE-11'),
('NC13.8', 'Distensión o esguince de otras partes o de partes no especificadas de la cintura escapular', 'category', false, false, 'CIE-11'),
('NC13.Y', 'Otra luxación, distensión o esguince de las articulaciones o ligamentos especificados de la cintura escapular', 'category', false, false, 'CIE-11'),
('NC13.Z', 'Luxación, distensión o esguince de las articulaciones o ligamentos de la cintura escapular, sin especificación', 'category', false, false, 'CIE-11'),
('NC14', 'Traumatismo en los nervios a nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.0', 'Traumatismo en el nervio cubital a nivel de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.1', 'Traumatismo en el nervio mediano a nivel de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.2', 'Traumatismo en el nervio radial a nivel de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.3', 'Traumatismo en el nervio circunflejo', 'category', false, false, 'CIE-11'),
('NC14.4', 'Traumatismo en el nervio musculocutáneo', 'category', false, false, 'CIE-11'),
('NC14.5', 'Traumatismo en el nervio sensitivo cutáneo a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.6', 'Traumatismo en múltiples nervios a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.Y', 'Traumatismo en otros nervios especificados a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC14.Z', 'Traumatismo en los nervios a nivel del hombro o la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC15', 'Traumatismo en los vasos sanguíneos a nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC15.0', 'Traumatismo en la arteria axilar', 'category', false, false, 'CIE-11'),
('NC15.00', 'Desgarro en la arteria axilar', 'category', false, false, 'CIE-11'),
('NC15.0Y', 'Otro traumatismo especificado en la arteria axilar', 'category', false, false, 'CIE-11'),
('NC15.0Z', 'Traumatismo en la arteria axilar, sin especificación', 'category', false, false, 'CIE-11'),
('NC15.1', 'Traumatismo en la arteria braquial', 'category', false, false, 'CIE-11'),
('NC15.10', 'Desgarro en la arteria braquial', 'category', false, false, 'CIE-11'),
('NC15.1Y', 'Otro traumatismo especificado en la arteria braquial', 'category', false, false, 'CIE-11'),
('NC15.1Z', 'Traumatismo en la arteria braquial, sin especificación', 'category', false, false, 'CIE-11'),
('NC15.2', 'Traumatismo en la vena axilar o braquial', 'category', false, false, 'CIE-11'),
('NC15.20', 'Desgarro en la vena axilar o braquial', 'category', false, false, 'CIE-11'),
('NC15.2Y', 'Otro traumatismo especificado en la vena axilar o braquial', 'category', false, false, 'CIE-11'),
('NC15.2Z', 'Traumatismo en la vena axilar o braquial, sin especificación', 'category', false, false, 'CIE-11'),
('NC15.3', 'Traumatismo en la vena superficial a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC15.30', 'Laceración en la vena superficial a nivel del hombro o a nivel del brazo', 'category', false, false, 'CIE-11'),
('NC15.3Y', 'Otro traumatismo especificado en la vena superficial a nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC15.3Z', 'Traumatismo en la vena superficial a nivel del hombro o de la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC15.4', 'Traumatismo en múltiples vasos sanguíneos a nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC15.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC15.Z', 'Traumatismo en los vasos sanguíneos a nivel del hombro o la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC16', 'Traumatismo de músculo, fascia, tendón o bursa al nivel del hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.0', 'Traumatismo en músculo o tendón del manguito de rotador del hombro', 'category', false, false, 'CIE-11'),
('NC16.00', 'Esguince o distensión del tendón o del músculo del manguito de los rotadores del hombro', 'category', false, false, 'CIE-11'),
('NC16.01', 'Desgarro del tendón o del músculo del manguito de los rotadores del hombro', 'category', false, false, 'CIE-11'),
('NC16.0Y', 'Otro traumatismo especificado en músculo o tendón del manguito de rotador del hombro', 'category', false, false, 'CIE-11'),
('NC16.0Z', 'Traumatismo en músculo o tendón del manguito de rotador del hombro, sin especificación', 'category', false, false, 'CIE-11'),
('NC16.1', 'Traumatismo en tendón, fascia o músculo de la cabeza larga del bíceps', 'category', false, false, 'CIE-11'),
('NC16.10', 'Esguince o distensión de tendón, fascia o músculo de la cabeza larga del bíceps', 'category', false, false, 'CIE-11'),
('NC16.11', 'Desgarro de tendón, fascia o músculo de la cabeza larga del bíceps', 'category', false, false, 'CIE-11'),
('NC16.1Y', 'Otro traumatismo especificado en tendón, fascia o músculo de la cabeza larga del bíceps', 'category', false, false, 'CIE-11'),
('NC16.1Z', 'Traumatismo en tendón, fascia o músculo de la cabeza larga del bíceps, sin especificación', 'category', false, false, 'CIE-11'),
('NC16.2', 'Traumatismo en tendón, fascia o músculo de otra parte del bíceps', 'category', false, false, 'CIE-11'),
('NC16.20', 'Esguince o distensión de tendón, fascia o músculo de otra parte del bíceps', 'category', false, false, 'CIE-11'),
('NC16.21', 'Desgarro de tendón, fascia o músculo de otra parte del bíceps', 'category', false, false, 'CIE-11'),
('NC16.2Y', 'Otro traumatismo especificado en tendón, fascia o músculo de otra parte del bíceps', 'category', false, false, 'CIE-11'),
('NC16.2Z', 'Traumatismo en tendón, fascia o músculo de otra parte del bíceps, sin especificación', 'category', false, false, 'CIE-11'),
('NC16.3', 'Traumatismo en tendón, fascia o músculo del tríceps', 'category', false, false, 'CIE-11'),
('NC16.30', 'Esguince o distensión de tendón, fascia o músculo del tríceps', 'category', false, false, 'CIE-11'),
('NC16.31', 'Desgarro de tendón, fascia o músculo del tríceps', 'category', false, false, 'CIE-11'),
('NC16.3Y', 'Otra lesión traumática especificada de músculo, fascia o tendón del tríceps', 'category', false, false, 'CIE-11'),
('NC16.3Z', 'Lesión traumática de músculo, fascia o tendón del tríceps, sin especificación', 'category', false, false, 'CIE-11'),
('NC16.4', 'Traumatismo en múltiples músculos o tendones en el nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.40', 'Esguince o distensión de múltiples músculos o tendones a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.41', 'Desgarro de múltiples músculos o tendones a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.4Y', 'Otro traumatismo especificado de múltiples músculos o tendones en el hombro o el nivel superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.4Z', 'Traumatismo de múltiples músculos o tendones en el hombro o el nivel superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC16.5', 'Traumatismo en la bolsa sinovial del hombro', 'category', false, false, 'CIE-11'),
('NC16.Y', 'Otro traumatismo en tendón, fascia, músculo o bolsa sinovial a nivel del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC16.Z', 'Traumatismo de músculo, fascia, tendón o bursa al nivel del hombro o la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC17', 'Traumatismo por aplastamiento del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC18', 'Amputación traumática del hombro o de la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC18.0', 'Amputación traumática en la articulación del hombro derecho', 'category', false, false, 'CIE-11'),
('NC18.1', 'Amputación traumática en la articulación del hombro izquierdo', 'category', false, false, 'CIE-11'),
('NC18.2', 'Amputación traumática en la articulación del hombro, bilateral', 'category', false, false, 'CIE-11'),
('NC18.3', 'Amputación traumática entre el hombro y el codo derechos', 'category', false, false, 'CIE-11'),
('NC18.4', 'Amputación traumática entre el hombro y codo izquierdos', 'category', false, false, 'CIE-11'),
('NC18.5', 'Amputación traumática entre el hombro y el codo, bilateral', 'category', false, false, 'CIE-11'),
('NC18.Z', 'Amputación traumática del hombro o de la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC19', 'Traumatismos múltiples en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC1Y', 'Otros traumatismos especificados en el hombro o la parte superior del brazo', 'category', false, false, 'CIE-11'),
('NC1Z', 'Traumatismos en el hombro o la parte superior del brazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC30', 'Traumatismo superficial en el antebrazo', 'category', false, false, 'CIE-11'),
('NC30.0', 'Excoriación en el codo', 'category', false, false, 'CIE-11'),
('NC30.1', 'Contusión del codo', 'category', false, false, 'CIE-11'),
('NC30.2', 'Excoriación en otras partes o partes no especificadas del antebrazo', 'category', false, false, 'CIE-11'),
('NC30.3', 'Contusión de otras partes o de partes no especificadas del antebrazo', 'category', false, false, 'CIE-11'),
('NC30.4', 'Traumatismos superficiales múltiples en el antebrazo', 'category', false, false, 'CIE-11'),
('NC30.Y', 'Otro traumatismo superficial especificado en el antebrazo', 'category', false, false, 'CIE-11'),
('NC30.Z', 'Lesión superficial del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC31', 'Herida abierta en el antebrazo', 'category', false, false, 'CIE-11'),
('NC31.0', 'Desgarro en el antebrazo, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC31.1', 'Desgarro en el antebrazo, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC31.2', 'Herida punzante en el antebrazo, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC31.3', 'Herida punzante en el antebrazo, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC31.4', 'Mordedura o picadura abierta en el antebrazo', 'category', false, false, 'CIE-11'),
('NC31.5', 'Heridas abiertas múltiples en el antebrazo', 'category', false, false, 'CIE-11'),
('NC31.Y', 'Otra herida abierta especificada en el antebrazo', 'category', false, false, 'CIE-11'),
('NC31.Z', 'Herida abierta en el antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC32', 'Fractura del antebrazo', 'category', false, false, 'CIE-11'),
('NC32.0', 'Fractura en el extremo superior del cúbito', 'category', false, false, 'CIE-11'),
('NC32.1', 'Fractura en el extremo superior del radio', 'category', false, false, 'CIE-11'),
('NC32.2', 'Fractura de la diáfisis del cúbito', 'category', false, false, 'CIE-11'),
('NC32.3', 'Fractura de la diáfisis del radio', 'category', false, false, 'CIE-11'),
('NC32.4', 'Fractura de las diáfisis del cúbito y el radio', 'category', false, false, 'CIE-11'),
('NC32.5', 'Fractura de la epífisis distal del radio', 'category', false, false, 'CIE-11'),
('NC32.50', 'Fractura de la epífisis distal del radio, inclinación dorsal', 'category', false, false, 'CIE-11'),
('NC32.51', 'Fractura de la epífisis distal del radio, inclinación volar', 'category', false, false, 'CIE-11'),
('NC32.5Y', 'Otra fractura especificada de la epífisis distal del radio', 'category', false, false, 'CIE-11'),
('NC32.5Z', 'Fractura de la epífisis distal del radio, sin especificación', 'category', false, false, 'CIE-11'),
('NC32.6', 'Fractura de la epífisis distal del cúbito y el radio', 'category', false, false, 'CIE-11'),
('NC32.7', 'Fracturas múltiples del antebrazo', 'category', false, false, 'CIE-11'),
('NC32.Y', 'Otra fractura especificada en el antebrazo', 'category', false, false, 'CIE-11'),
('NC32.Z', 'Fractura en el antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC33', 'Luxación, esguince o distensión de articulaciones o ligamentos del codo', 'category', false, false, 'CIE-11'),
('NC33.0', 'Luxación de la cabeza del radio', 'category', false, false, 'CIE-11'),
('NC33.1', 'Luxación del codo', 'category', false, false, 'CIE-11'),
('NC33.2', 'Ruptura traumática del ligamento lateral del radio', 'category', false, false, 'CIE-11'),
('NC33.3', 'Ruptura traumática del ligamento lateral del cúbito', 'category', false, false, 'CIE-11'),
('NC33.4', 'Distensión o esguince del codo', 'category', false, false, 'CIE-11'),
('NC33.Y', 'Otra dislocación o esguince o distensión especificada de articulaciones o ligamentos del codo', 'category', false, false, 'CIE-11'),
('NC33.Z', 'Dislocación o esguince o distensión de articulaciones o ligamentos del codo, sin especificación', 'category', false, false, 'CIE-11'),
('NC34', 'Traumatismo en los nervios a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.0', 'Traumatismo en el nervio cubital a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.1', 'Traumatismo en el nervio mediano a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.2', 'Traumatismo en el nervio radial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.3', 'Traumatismo en el nervio sensorio cutáneo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.4', 'Traumatismo en múltiples nervios a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.Y', 'Otro traumatismo especificado de los nervios a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC34.Z', 'Traumatismo en los nervios a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC35', 'Traumatismo en los vasos sanguíneos a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.0', 'Traumatismo en la arteria cubital a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.00', 'Laceración de la arteria cubital a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.0Y', 'Otro traumatismo especificado en la arteria cubital a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.0Z', 'Traumatismo en la arteria cubital a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC35.1', 'Traumatismo en la arteria radial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.10', 'Laceración de la arteria radial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.1Y', 'Otro traumatismo especificado en la arteria radial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.1Z', 'Traumatismo en la arteria radial a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC35.2', 'Traumatismo en una vena a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.20', 'Desgarro en una vena a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.2Y', 'Otro traumatismo especificado en una vena a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.2Z', 'Traumatismo en una vena a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC35.3', 'Traumatismo en múltiples vasos sanguíneos a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC35.Z', 'Traumatismo en los vasos sanguíneos a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36', 'Traumatismo en tendón, fascia, músculo o bolsa sinovial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.0', 'Traumatismo en tendón, fascia o músculo flexor del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.00', 'Esguince o distensión de tendón, fascia o músculo flexor del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.01', 'Desgarro de tendón, fascia o músculo flexor del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.0Y', 'Otra lesión traumática especificada del músculo, fascia o tendón del flexor del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.0Z', 'Lesión traumática del músculo, fascia o tendón del flexor del pulgar a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.1', 'Traumatismo en el músculo flexor largo, la fascia o el tendón de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.10', 'Esguince o distensión del músculo flexor largo, fascia o tendón de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.11', 'Desgarro del músculo flexor largo, fascia o tendón de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.1Y', 'Otro traumatismo especificado en el músculo flexor largo, la fascia o el tendón de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.1Z', 'Traumatismo en el músculo flexor largo, la fascia o el tendón de otro dedo a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.2', 'Traumatismo en otro tendón, fascia o músculo flexor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.20', 'Esguince o distensión de otro tendón, fascia o músculo flexor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.21', 'Desgarro de otro tendón, fascia o músculo flexor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.2Y', 'Otro traumatismo especificado en otro tendón, fascia o músculo flexor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.2Z', 'Traumatismo en otro tendón, fascia o músculo flexor a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.3', 'Traumatismo en tendones y músculos abductores o extensores del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.30', 'Esguince o distensión de tendones o músculos extensores o abductores del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.31', 'Laceración de tendones y músculos abductores o extensores del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.3Y', 'Otro traumatismo especificado en tendones y músculos abductores o extensores del pulgar a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.3Z', 'Traumatismo en tendones y músculos abductores o extensores del pulgar a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.4', 'Traumatismo en tendón, fascia o músculo extensor de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.40', 'Esguince o distensión de tendón, fascia o músculo extensor de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.41', 'Desgarro de tendón, fascia o músculo extensor de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.4Y', 'Otro traumatismo especificado en tendón, fascia o músculo extensor de otro dedo a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.4Z', 'Traumatismo en tendón, fascia o músculo extensor de otro dedo a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.5', 'Traumatismo en otro tendón, fascia o músculo extensor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.50', 'Esguince o distensión de otro tendón, fascia o músculo extensor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.51', 'Desgarro de otro tendón, fascia o músculo extensor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.5Y', 'Otra lesión traumática especificada de otro músculo, fascia o tendón extensor a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.5Z', 'Lesión traumática de otro músculo, fascia o tendón extensor a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC36.6', 'Traumatismo en múltiples tendones o músculos a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.7', 'Traumatismo en la bolsa sinovial del codo', 'category', false, false, 'CIE-11'),
('NC36.Y', 'Otro traumatismo especificado del músculo, fascia, tendón o bolsa sinovial a nivel del antebrazo', 'category', false, false, 'CIE-11'),
('NC36.Z', 'Traumatismo del músculo, fascia, tendón o bolsa sinovial a nivel del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC37', 'Traumatismo por aplastamiento del antebrazo', 'category', false, false, 'CIE-11'),
('NC37.0', 'Traumatismo por aplastamiento del codo', 'category', false, false, 'CIE-11'),
('NC37.Y', 'Traumatismo por aplastamiento de otra parte especificada del antebrazo', 'category', false, false, 'CIE-11'),
('NC37.Z', 'Traumatismo por aplastamiento del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC38', 'Amputación traumática del antebrazo', 'category', false, false, 'CIE-11'),
('NC38.0', 'Amputación traumática a nivel del codo derecho', 'category', false, false, 'CIE-11'),
('NC38.1', 'Amputación traumática a nivel del codo izquierdo', 'category', false, false, 'CIE-11'),
('NC38.2', 'Amputación traumática a nivel del codo, bilateral', 'category', false, false, 'CIE-11'),
('NC38.3', 'Amputación traumática entre el codo y la muñeca derecha', 'category', false, false, 'CIE-11'),
('NC38.4', 'Amputación traumática entre el codo y la muñeca izquierda', 'category', false, false, 'CIE-11'),
('NC38.5', 'Amputación traumática entre el codo y la muñeca, bilateral', 'category', false, false, 'CIE-11'),
('NC38.Z', 'Amputación traumática del antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC39', 'Traumatismos múltiples en el antebrazo', 'category', false, false, 'CIE-11'),
('NC3Y', 'Otros traumatismos especificados en el codo o el antebrazo', 'category', false, false, 'CIE-11'),
('NC3Z', 'Traumatismos en el codo o el antebrazo, sin especificación', 'category', false, false, 'CIE-11'),
('NC50', 'Traumatismo en la uña', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
