-- CIE11 Import Part 14
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('BD53.Z', 'Trastornos secundarios de arterias y arteriolas, sin especificación', 'category', false, false, 'CIE-11'),
('BD54', 'Úlcera del pie diabético', 'category', false, false, 'CIE-11'),
('BD55', 'Estenosis asintomática de arteria intracraneal o extracraneal', 'category', false, false, 'CIE-11'),
('BD56', 'Oclusión asintomática de arteria intracraneal o extracraneal', 'category', false, false, 'CIE-11'),
('BD5Y', 'Otras enfermedades especificadas de las arterias o arteriolas', 'category', false, false, 'CIE-11'),
('BD5Z', 'Enfermedades de las arterias y arteriolas, sin especificación', 'category', false, false, 'CIE-11'),
('BD70', 'Tromboflebitis superficial', 'category', false, false, 'CIE-11'),
('BD70.0', 'Tromboflebitis superficial de extremidades inferiores', 'category', false, false, 'CIE-11'),
('BD70.1', 'Tromboflebitis superficial de extremidades superiores', 'category', false, false, 'CIE-11'),
('BD70.2', 'Tromboflebitis migratoria', 'category', false, false, 'CIE-11'),
('BD70.3', 'Enfermedad de Mondor', 'category', false, false, 'CIE-11'),
('BD70.Y', 'Otra tromboflebitis superficial especificada', 'category', false, false, 'CIE-11'),
('BD70.Z', 'Tromboflebitis superficial, sin especificación', 'category', false, false, 'CIE-11'),
('BD71', 'Trombosis venosa profunda', 'category', false, false, 'CIE-11'),
('BD71.0', 'Trombosis venosa profunda de la extremidad superior', 'category', false, false, 'CIE-11'),
('BD71.1', 'Trombosis de la vena cava', 'category', false, false, 'CIE-11'),
('BD71.2', 'Trombosis de la vena renal', 'category', false, false, 'CIE-11'),
('BD71.3', 'Trombosis de las venas ilíacas', 'category', false, false, 'CIE-11'),
('BD71.4', 'Trombosis venosa profunda de la extremidad inferior', 'category', false, false, 'CIE-11'),
('BD71.Y', 'Otras trombosis venosas profundas especificadas', 'category', false, false, 'CIE-11'),
('BD72', 'Tromboembolia venosa', 'category', false, false, 'CIE-11'),
('BD73', 'Anomalía venosa sistémica adquirida', 'category', false, false, 'CIE-11'),
('BD73.0', 'Anomalía adquirida de la vena cava inferior', 'category', false, false, 'CIE-11'),
('BD73.1', 'Anomalía adquirida de la vena cava superior', 'category', false, false, 'CIE-11'),
('BD73.2', 'Obstrucción venosa sistémica', 'category', false, false, 'CIE-11'),
('BD73.20', 'Obstrucción de una vena periférica', 'category', false, false, 'CIE-11'),
('BD73.21', 'Obstrucción de una vena visceral', 'category', false, false, 'CIE-11'),
('BD73.2Y', 'Otra obstrucción venosa sistémica especificada', 'category', false, false, 'CIE-11'),
('BD73.2Z', 'Obstrucción venosa sistémica, sin especificación', 'category', false, false, 'CIE-11'),
('BD73.3', 'Anomalía adquirida del seno coronario', 'category', false, false, 'CIE-11'),
('BD73.Y', 'Otra anomalía venosa sistémica adquirida especificada', 'category', false, false, 'CIE-11'),
('BD73.Z', 'Anomalía venosa sistémica adquirida, sin especificación', 'category', false, false, 'CIE-11'),
('BD74', 'Insuficiencia venosa periférica crónica de las extremidades inferiores', 'category', false, false, 'CIE-11'),
('BD74.0', 'Hipertensión venosa de las extremidades inferiores sin complicaciones', 'category', false, false, 'CIE-11'),
('BD74.1', 'Várices de las extremidades inferiores', 'category', false, false, 'CIE-11'),
('BD74.10', 'Várices con reflujo de la vena safena interna', 'category', false, false, 'CIE-11'),
('BD74.11', 'Várices con reflujo de la vena safena externa', 'category', false, false, 'CIE-11'),
('BD74.12', 'Várices con reflujo no troncal', 'category', false, false, 'CIE-11'),
('BD74.1Z', 'Venas varicosas de las extremidades inferiores, sin otra especificación', 'category', false, false, 'CIE-11'),
('BD74.2', 'Lipodermatoesclerosis', 'category', false, false, 'CIE-11'),
('BD74.3', 'Úlcera venosa de la pierna', 'category', false, false, 'CIE-11'),
('BD74.30', 'Úlcera venosa primaria de la pierna', 'category', false, false, 'CIE-11'),
('BD74.31', 'Úlcera venosa recurrente de la pierna', 'category', false, false, 'CIE-11'),
('BD74.32', 'Úlcera venosa curada de la pierna', 'category', false, false, 'CIE-11'),
('BD74.3Z', 'Úlcera venosa de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('BD74.Z', 'Insuficiencia venosa periférica crónica de las extremidades inferiores, sin especificación', 'category', false, false, 'CIE-11'),
('BD75', 'Varicosidades venosas en otros sitios distintos de las extremidades inferiores', 'category', false, false, 'CIE-11'),
('BD75.0', 'Várices sublinguales', 'category', false, false, 'CIE-11'),
('BD75.1', 'Várices escrotales', 'category', false, false, 'CIE-11'),
('BD75.2', 'Várices vulvares', 'category', false, false, 'CIE-11'),
('BD75.3', 'Várices pélvicas', 'category', false, false, 'CIE-11'),
('BD75.Y', 'Varicosidades venosas en otras localizaciones especificadas', 'category', false, false, 'CIE-11'),
('BD75.Z', 'Varicosidades en otras localizaciones. sin especificación', 'category', false, false, 'CIE-11'),
('BD7Y', 'Otras enfermedades especificadas de las venas', 'category', false, false, 'CIE-11'),
('BD7Z', 'Enfermedades de las venas, sin especificación', 'category', false, false, 'CIE-11'),
('BD90', 'Linfadenitis', 'category', false, false, 'CIE-11'),
('BD90.0', 'Linfadenitis aguda', 'category', false, false, 'CIE-11'),
('BD90.1', 'Linfadenitis mesentérica inespecífica', 'category', false, false, 'CIE-11'),
('BD90.2', 'Linfadenitis crónica', 'category', false, false, 'CIE-11'),
('BD90.20', 'Linfadenitis cervical crónica', 'category', false, false, 'CIE-11'),
('BD90.21', 'Linfadenitis axilar crónica', 'category', false, false, 'CIE-11'),
('BD90.22', 'Linfadenitis inguinal crónica', 'category', false, false, 'CIE-11'),
('BD90.2Y', 'Otra linfadenitis crónica especificada', 'category', false, false, 'CIE-11'),
('BD90.2Z', 'Linfadenitis crónica, sin especificación', 'category', false, false, 'CIE-11'),
('BD90.Y', 'Otra linfadenitis especificada', 'category', false, false, 'CIE-11'),
('BD90.Z', 'Linfadenitis, sin especificación', 'category', false, false, 'CIE-11'),
('BD91', 'Linfangitis', 'category', false, false, 'CIE-11'),
('BD92', 'Linfangiectasia', 'category', false, false, 'CIE-11'),
('BD92.0', 'Linfangiectasia intestinal', 'category', false, false, 'CIE-11'),
('BD92.1', 'Linfangiectasia cutánea', 'category', false, false, 'CIE-11'),
('BD92.Z', 'Linfangiectasia, sin especificación', 'category', false, false, 'CIE-11'),
('BD93', 'Linfedema', 'category', false, false, 'CIE-11'),
('BD93.0', 'Linfedema primario', 'category', false, false, 'CIE-11'),
('BD93.1', 'Linfedema secundario', 'category', false, false, 'CIE-11'),
('BD93.10', 'linfedema secundario a insuficiencia venosa', 'category', false, false, 'CIE-11'),
('BD93.11', 'Linfedema postural por inmovilidad', 'category', false, false, 'CIE-11'),
('BD93.12', 'Linfedema por obesidad', 'category', false, false, 'CIE-11'),
('BD93.13', 'Linfedema por filariosis linfática', 'category', false, false, 'CIE-11'),
('BD93.14', 'Linfedema por podoconiosis', 'category', false, false, 'CIE-11'),
('BD93.15', 'Linfedema por infiltración maligna', 'category', false, false, 'CIE-11'),
('BD93.1Y', 'Linfedema secundario especificado', 'category', false, false, 'CIE-11'),
('BD93.1Z', 'Linfedema secundario, sin especificación', 'category', false, false, 'CIE-11'),
('BD93.Y', 'Otras formas especificadas de linfedema', 'category', false, false, 'CIE-11'),
('BD93.Z', 'Linfedema, sin especificación', 'category', false, false, 'CIE-11'),
('BD9Y', 'Otros trastornos especificados de los vasos y ganglios linfáticos', 'category', false, false, 'CIE-11'),
('BD9Z', 'Trastornos de los vasos y ganglios linfáticos, sin especificación', 'category', false, false, 'CIE-11'),
('BE10', 'Síndrome de poscardiotomía', 'category', false, false, 'CIE-11'),
('BE11', 'Otras alteraciones funcionales tras cirugía cardíaca', 'category', false, false, 'CIE-11'),
('BE12', 'Valvulopatías tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.0', 'Estenosis de la válvula mitral tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.1', 'Insuficiencia de la válvula mitral tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.2', 'Estenosis de la válvula aórtica tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.3', 'Insuficiencia de la válvula aórtica tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.4', 'Estenosis de la válvula tricúspide tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.5', 'Insuficiencia de la válvula tricúspide tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.6', 'Estenosis de la válvula pulmonar tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE12.7', 'Insuficiencia de la válvula pulmonar tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE13', 'Aneurisma aórtico verdadero o falso tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE14', 'Trastorno del sistema circulatorio posprocedimiento de reparación de una anomalía congénita del corazón o de los grandes vasos', 'category', false, false, 'CIE-11'),
('BE14.4', 'Anomalía adquirida de la válvula neopulmonar', 'category', false, false, 'CIE-11'),
('BE14.40', 'Estenosis de la válvula neopulmonar', 'category', false, false, 'CIE-11'),
('BE14.41', 'insuficiencia de válvula neopulmonar', 'category', false, false, 'CIE-11'),
('BE14.5', 'Anomalía valvular auriculoventricular derecha en ventrículo con doble entrada tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE14.6', 'Anomalía valvular auriculoventricular izquierda en ventrículo con doble entrada tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE14.7', 'Anomalía adquirida de la válvula auriculoventricular común en ventrículo con doble entrada tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE14.8', 'Trastorno de defecto septal ventricular posprocedimiento', 'category', false, false, 'CIE-11'),
('BE14.9', 'Trastorno aórtico posprocedimiento relacionado con anomalía cardíaca congénita', 'category', false, false, 'CIE-11'),
('BE14.A', 'Trastorno en el conducto arterioso tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE14.B', 'Trastorno posprocedimiento que sigue a un procedimiento de derivación o de conducto cardiovascular', 'category', false, false, 'CIE-11'),
('BE15', 'Trastorno del árbol arterial pulmonar tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE15.0', 'Estenosis del tronco pulmonar tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE15.1', 'Estenosis de la arteria pulmonar derecha tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE16', 'Trastorno venoso pulmonar postprocedimiento', 'category', false, false, 'CIE-11'),
('BE17', 'Comunicación interauricular residual o recurrente tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE19', 'Anomalía ventricular tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE1A', 'Trasplante cardíaco asociado con vasculopatía coronaria del aloinjerto', 'category', false, false, 'CIE-11'),
('BE1B', 'Linfedema por cirugía o radioterapia', 'category', false, false, 'CIE-11'),
('BE1B.0', 'Síndrome de linfedema tras mastectomía', 'category', false, false, 'CIE-11'),
('BE1B.1', 'Linfedema debido a otros procedimientos médicos o quirúrgicos.', 'category', false, false, 'CIE-11'),
('BE1C', 'Obstrucción de vena cava inferior por cuerpo extraño', 'category', false, false, 'CIE-11'),
('BE1D', 'Obstrucción de vena cava superior por cuerpo extraño', 'category', false, false, 'CIE-11'),
('BE1E', 'Complicación auricular derecha tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE1E.0', 'Perforación auricular derecha tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE1E.1', 'Erosión auricular derecha debida a dispositivo implantado', 'category', false, false, 'CIE-11'),
('BE1F', 'Complicación auricular izquierda tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE1F.0', 'Perforación auricular izquierda tras un procedimiento', 'category', false, false, 'CIE-11'),
('BE1F.1', 'Erosión auricular izquierda por un dispositivo implantado', 'category', false, false, 'CIE-11'),
('BE2Y', 'Otras enfermedades especificadas del sistema circulatorio', 'category', false, false, 'CIE-11'),
('BE2Z', 'Enfermedades del sistema circulatorio, sin especificación', 'category', false, false, 'CIE-11'),
('CA00', 'Nasofaringitis aguda', 'category', false, false, 'CIE-11'),
('CA01', 'Sinusitis aguda', 'category', false, false, 'CIE-11'),
('CA02', 'Faringitis aguda', 'category', false, false, 'CIE-11'),
('CA02.0', 'Faringitis bacteriana aguda', 'category', false, false, 'CIE-11'),
('CA02.1', 'Faringitis viral aguda', 'category', false, false, 'CIE-11'),
('CA02.10', 'Faringitis por adenovirus', 'category', false, false, 'CIE-11'),
('CA02.1Y', 'Otra faringitis viral aguda especificada', 'category', false, false, 'CIE-11'),
('CA02.1Z', 'Faringitis viral aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CA02.Y', 'Otra faringitis aguda especificada', 'category', false, false, 'CIE-11'),
('CA02.Z', 'Faringitis aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CA03', 'Amigdalitis aguda', 'category', false, false, 'CIE-11'),
('CA03.0', 'Amigdalitis estreptocócica', 'category', false, false, 'CIE-11'),
('CA03.Y', 'Otra amigdalitis aguda especificada', 'category', false, false, 'CIE-11'),
('CA03.Z', 'Amigdalitis aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CA04', 'Laringofaringitis aguda', 'category', false, false, 'CIE-11'),
('CA05', 'Laringitis o traqueítis aguda', 'category', false, false, 'CIE-11'),
('CA05.0', 'Laringitis aguda', 'category', false, false, 'CIE-11'),
('CA05.1', 'Traqueítis aguda', 'category', false, false, 'CIE-11'),
('CA05.2', 'Laringotraqueítis aguda', 'category', false, false, 'CIE-11'),
('CA06', 'Laringitis obstructiva aguda o epiglotitis', 'category', false, false, 'CIE-11'),
('CA06.0', 'Laringitis obstructiva aguda', 'category', false, false, 'CIE-11'),
('CA06.1', 'Epiglotitis aguda', 'category', false, false, 'CIE-11'),
('CA06.Z', 'Laringitis obstructiva aguda o epiglotitis, sin especificación', 'category', false, false, 'CIE-11'),
('CA07', 'Infecciones respiratorias agudas de vías altas, en localizaciones múltiples y no especificadas', 'category', false, false, 'CIE-11'),
('CA07.0', 'Infección respiratoria aguda de las vías altas, sitio no especificado', 'category', false, false, 'CIE-11'),
('CA07.1', 'Infecciones respiratorias agudas de vías altas, de múltiples sitios', 'category', false, false, 'CIE-11'),
('CA08', 'Rinitis alérgica o vasomotora', 'category', false, false, 'CIE-11'),
('CA08.0', 'Rinitis alérgica', 'category', false, false, 'CIE-11'),
('CA08.00', 'Rinitis alérgica debida al polen', 'category', false, false, 'CIE-11'),
('CA08.01', 'Rinitis alérgica por otros alérgenos estacionales', 'category', false, false, 'CIE-11'),
('CA08.02', 'Rinitis alérgica por ácaros del polvo doméstico', 'category', false, false, 'CIE-11'),
('CA08.03', 'Otra rinitis alérgica', 'category', false, false, 'CIE-11'),
('CA08.0Z', 'Rinitis alérgica, sin especificación', 'category', false, false, 'CIE-11'),
('CA08.1', 'Rinitis no alérgica', 'category', false, false, 'CIE-11'),
('CA08.10', 'Rinitis no alérgica con eosinófilos', 'category', false, false, 'CIE-11'),
('CA08.1Y', 'Otra rinitis no alérgica especificada', 'category', false, false, 'CIE-11'),
('CA08.1Z', 'Rinitis no alérgica, sin especificación', 'category', false, false, 'CIE-11'),
('CA08.2', 'Rinitis mixta', 'category', false, false, 'CIE-11'),
('CA08.3', 'Rinitis vasomotora', 'category', false, false, 'CIE-11'),
('CA09', 'Rinitis, nasofaringitis o faringitis crónica', 'category', false, false, 'CIE-11'),
('CA09.0', 'Rinitis crónica', 'category', false, false, 'CIE-11'),
('CA09.1', 'Nasofaringitis crónica', 'category', false, false, 'CIE-11'),
('CA09.2', 'Faringitis crónica', 'category', false, false, 'CIE-11'),
('CA0A', 'Sinusitis crónica', 'category', false, false, 'CIE-11'),
('CA0A.0', 'Síndrome de Samter', 'category', false, false, 'CIE-11'),
('CA0A.Y', 'Otra rinosinusitis crónica especificada', 'category', false, false, 'CIE-11'),
('CA0A.Z', 'Rinosinusitis crónica, sin especificación', 'category', false, false, 'CIE-11'),
('CA0B', 'Síndrome del seno silencioso', 'category', false, false, 'CIE-11'),
('CA0C', 'Quiste o mucocele de nariz o seno paranasal', 'category', false, false, 'CIE-11'),
('CA0D', 'Desviación del tabique nasal', 'category', false, false, 'CIE-11'),
('CA0E', 'Hipertrofia de los cornetes nasales', 'category', false, false, 'CIE-11'),
('CA0F', 'Enfermedades crónicas de las amígdalas palatinas o faríngeas', 'category', false, false, 'CIE-11'),
('CA0F.0', 'Hipertrofia de amígdalas', 'category', false, false, 'CIE-11'),
('CA0F.1', 'Hipertrofia de adenoides', 'category', false, false, 'CIE-11'),
('CA0F.3', 'Hipertrofia de las amígdalas con hipertrofia de los adenoides', 'category', false, false, 'CIE-11'),
('CA0F.Y', 'Otras enfermedades crónicas especificadas de las amígdalas palatinas o faríngeas', 'category', false, false, 'CIE-11'),
('CA0F.Z', 'Enfermedades crónicas de las amígdalas palatinas o faríngeas, sin especificación', 'category', false, false, 'CIE-11'),
('CA0G', 'Laringitis crónica o laringotraqueítis', 'category', false, false, 'CIE-11'),
('CA0H', 'Enfermedades de las cuerdas vocales o de la laringe, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('CA0H.0', 'Parálisis de las cuerdas vocales o de la laringe', 'category', false, false, 'CIE-11'),
('CA0H.1', 'Pólipo de cuerda vocal o de laringe', 'category', false, false, 'CIE-11'),
('CA0H.2', 'Nódulos de las cuerdas vocales', 'category', false, false, 'CIE-11'),
('CA0H.3', 'Edema de laringe', 'category', false, false, 'CIE-11'),
('CA0H.4', 'Espasmo laríngeo', 'category', false, false, 'CIE-11'),
('CA0H.5', 'Estenosis de laringe', 'category', false, false, 'CIE-11'),
('CA0H.Y', 'Otras enfermedades especificadas de las cuerdas vocales o de la laringe, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('CA0H.Z', 'Enfermedades de las cuerdas vocales o de la laringe, no clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('CA0J', 'Pólipo nasal', 'category', false, false, 'CIE-11'),
('CA0J.0', 'Degeneración polipoidea de senos paranasales', 'category', false, false, 'CIE-11'),
('CA0J.Y', 'Otro pólipo nasal especificado', 'category', false, false, 'CIE-11'),
('CA0J.Z', 'Pólipo nasal, sin especificación', 'category', false, false, 'CIE-11'),
('CA0K', 'Absceso de vías respiratorias altas', 'category', false, false, 'CIE-11'),
('CA0K.0', 'Absceso retrofaríngeo o parafaríngeo', 'category', false, false, 'CIE-11'),
('CA0K.1', 'Absceso periamigdalino', 'category', false, false, 'CIE-11'),
('CA0K.Y', 'Otro absceso especificado de vías respiratorias altas', 'category', false, false, 'CIE-11'),
('CA0K.Z', 'Absceso de vías respiratorias altas, sin especificación', 'category', false, false, 'CIE-11'),
('CA0Y', 'Otros trastornos especificados las vías respiratorias superiores', 'category', false, false, 'CIE-11'),
('CA0Z', 'Trastornos de las vías respiratorias superiores, sin especificación', 'category', false, false, 'CIE-11'),
('CA20', 'Bronquitis', 'category', false, false, 'CIE-11'),
('CA20.0', 'Bronquitis no infecciosa aguda', 'category', false, false, 'CIE-11'),
('CA20.1', 'Bronquitis crónica', 'category', false, false, 'CIE-11'),
('CA20.10', 'Bronquitis crónica simple', 'category', false, false, 'CIE-11'),
('CA20.11', 'Bronquitis crónica mucopurulenta', 'category', false, false, 'CIE-11'),
('CA20.12', 'Bronquitis crónica mixta (simple y mucopurulenta)', 'category', false, false, 'CIE-11'),
('CA20.13', 'Bronquitis bacteriana persistente', 'category', false, false, 'CIE-11'),
('CA20.1Y', 'Otra bronquitis crónica especificada', 'category', false, false, 'CIE-11'),
('CA20.1Z', 'Bronquitis crónica, sin especificación', 'category', false, false, 'CIE-11'),
('CA20.Y', 'Otra bronquitis especificada', 'category', false, false, 'CIE-11'),
('CA20.Z', 'Bronquitis, sin especificación', 'category', false, false, 'CIE-11'),
('CA21', 'Enfisema', 'category', false, false, 'CIE-11'),
('CA21.0', 'Síndrome de MacLeod', 'category', false, false, 'CIE-11'),
('CA21.1', 'Enfisema panlobulillar', 'category', false, false, 'CIE-11'),
('CA21.2', 'Enfisema centrolobulillar', 'category', false, false, 'CIE-11'),
('CA21.Y', 'Otro enfisema especificado', 'category', false, false, 'CIE-11'),
('CA21.Z', 'Enfisema, sin especificación', 'category', false, false, 'CIE-11'),
('CA22', 'Enfermedad pulmonar obstructiva crónica', 'category', false, false, 'CIE-11'),
('CA22.0', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada', 'category', false, false, 'CIE-11'),
('CA22.1', 'Alguna enfermedad pulmonar obstructiva crónica especificada', 'category', false, false, 'CIE-11'),
('CA22.Z', 'Enfermedad pulmonar obstructiva crónica, sin especificación', 'category', false, false, 'CIE-11'),
('CA23', 'Asma', 'category', false, false, 'CIE-11'),
('CA23.0', 'Asma alérgica', 'category', false, false, 'CIE-11'),
('CA23.00', 'Asma alérgica con exacerbación', 'category', false, false, 'CIE-11'),
('CA23.01', 'Asma alérgica con estado asmático', 'category', false, false, 'CIE-11'),
('CA23.02', 'Asma alérgica sin complicaciones', 'category', false, false, 'CIE-11'),
('CA23.1', 'Asma no alérgica', 'category', false, false, 'CIE-11'),
('CA23.10', 'Asma no alérgica con exacerbación', 'category', false, false, 'CIE-11'),
('CA23.11', 'Asma no alérgica con estado asmático', 'category', false, false, 'CIE-11'),
('CA23.12', 'Asma no alérgica sin complicaciones', 'category', false, false, 'CIE-11'),
('CA23.2', 'Otras formas especificadas de asma o de broncoespasmo', 'category', false, false, 'CIE-11'),
('CA23.20', 'Asma inducida por la aspirina', 'category', false, false, 'CIE-11'),
('CA23.21', 'Broncoespasmo inducido por el ejercicio', 'category', false, false, 'CIE-11'),
('CA23.22', 'Tos como variante del asma', 'category', false, false, 'CIE-11'),
('CA23.3', 'Asma no especificada', 'category', false, false, 'CIE-11'),
('CA23.30', 'Asma no especificada con exacerbación', 'category', false, false, 'CIE-11'),
('CA23.31', 'Asma no especificada con estado asmático', 'category', false, false, 'CIE-11'),
('CA23.32', 'Asma no especificada sin complicaciones', 'category', false, false, 'CIE-11'),
('CA24', 'Bronquiectasia', 'category', false, false, 'CIE-11'),
('CA25', 'Fibrosis quística', 'category', false, false, 'CIE-11'),
('CA25.0', 'Fibrosis quística clásica', 'category', false, false, 'CIE-11'),
('CA25.1', 'Fibrosis quística atípica', 'category', false, false, 'CIE-11'),
('CA25.2', 'Fibrosis quística subclínica', 'category', false, false, 'CIE-11'),
('CA25.Z', 'Fibrosis quística, sin especificación', 'category', false, false, 'CIE-11'),
('CA26', 'Bronquiolitis crónica', 'category', false, false, 'CIE-11'),
('CA26.0', 'Bronquiolitis obliterante crónica', 'category', false, false, 'CIE-11'),
('CA26.1', 'Panbroquiolitis difusa', 'category', false, false, 'CIE-11'),
('CA26.Y', 'Otra bronquiolitis crónica especificada', 'category', false, false, 'CIE-11'),
('CA26.Z', 'Bronquiolitis crónica, sin especificación', 'category', false, false, 'CIE-11'),
('CA27', 'Traqueobronquitis', 'category', false, false, 'CIE-11'),
('CA27.0', 'Traqueobroncopatía osteocondroplásica', 'category', false, false, 'CIE-11'),
('CA27.1', 'Traqueobroncomegalia', 'category', false, false, 'CIE-11'),
('CA27.Y', 'Otra traqueobronquitis especificada', 'category', false, false, 'CIE-11'),
('CA27.Z', 'Traqueobronquitis, sin especificación', 'category', false, false, 'CIE-11'),
('CA2Y', 'Otra enfermedad especificada de las vías respiratorias bajas', 'category', false, false, 'CIE-11'),
('CA2Z', 'Enfermedad de las vías respiratorias bajas, sin especificación', 'category', false, false, 'CIE-11'),
('CA40', 'Neumonía', 'category', false, false, 'CIE-11'),
('CA40.0', 'Neumonía bacteriana', 'category', false, false, 'CIE-11'),
('CA40.00', 'Neumonía por Chlamydophila pneumoniae', 'category', false, false, 'CIE-11'),
('CA40.01', 'Neumonía por Escherichia coli', 'category', false, false, 'CIE-11'),
('CA40.02', 'Neumonía por Haemophilus influenzae', 'category', false, false, 'CIE-11'),
('CA40.03', 'Neumonía por Klebsiella pneumoniae', 'category', false, false, 'CIE-11'),
('CA40.04', 'Neumonía por Mycoplasma pneumoniae', 'category', false, false, 'CIE-11'),
('CA40.05', 'Neumonía por Pseudomonas aeruginosa', 'category', false, false, 'CIE-11'),
('CA40.06', 'Neumonía por estafilococos', 'category', false, false, 'CIE-11'),
('CA40.07', 'Neumonía por Streptococcus pneumoniae', 'category', false, false, 'CIE-11'),
('CA40.08', 'Neumonía por especies betahemolíticas de Streptococcus', 'category', false, false, 'CIE-11'),
('CA40.0Y', 'Otra neumonía bacteriana especificada', 'category', false, false, 'CIE-11'),
('CA40.0Z', 'Neumonía bacteriana, sin especificación', 'category', false, false, 'CIE-11'),
('CA40.1', 'Bronconeumonía viral', 'category', false, false, 'CIE-11'),
('CA40.10', 'Neumonía por adenovirus', 'category', false, false, 'CIE-11'),
('CA40.11', 'Neumonía por virus respiratorio sincicial', 'category', false, false, 'CIE-11'),
('CA40.12', 'Neumonía por virus de parainfluenza', 'category', false, false, 'CIE-11'),
('CA40.13', 'Neumonía por metaneumovirus humano', 'category', false, false, 'CIE-11'),
('CA40.1Y', 'Neumonía por otro virus especificado', 'category', false, false, 'CIE-11'),
('CA40.1Z', 'Neumonía viral, sin especificación', 'category', false, false, 'CIE-11'),
('CA40.2', 'Neumonía micótica', 'category', false, false, 'CIE-11'),
('CA40.20', 'Neumonía por Pneumocystis', 'category', false, false, 'CIE-11'),
('CA40.2Y', 'Otra neumonía micótica especificada', 'category', false, false, 'CIE-11'),
('CA40.2Z', 'Neumonía micótica, sin especificación', 'category', false, false, 'CIE-11'),
('CA40.Y', 'Otra neumonía especificada', 'category', false, false, 'CIE-11'),
('CA40.Z', 'Neumonía, organismo sin especificación', 'category', false, false, 'CIE-11'),
('CA41', 'Bronquiolitis aguda', 'category', false, false, 'CIE-11'),
('CA41.0', 'Bronquiolitis aguda por virus respiratorio sincitial', 'category', false, false, 'CIE-11'),
('CA41.Y', 'Otra bronquiolitis aguda especificada', 'category', false, false, 'CIE-11'),
('CA41.Z', 'Bronquiolitis aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CA42', 'Bronquitis aguda', 'category', false, false, 'CIE-11'),
('CA42.0', 'Bronquitis aguda por Streptococcus', 'category', false, false, 'CIE-11'),
('CA42.1', 'Bronquitis aguda por rinovirus', 'category', false, false, 'CIE-11'),
('CA42.2', 'Bronquitis aguda por virus respiratorio sincitial', 'category', false, false, 'CIE-11'),
('CA42.3', 'Bronquitis aguda por virus de parainfluenza', 'category', false, false, 'CIE-11'),
('CA42.4', 'Bronquitis aguda por Haemophilus influenzae', 'category', false, false, 'CIE-11'),
('CA42.5', 'Bronquitis aguda por virus Coxsackie', 'category', false, false, 'CIE-11'),
('CA42.Y', 'Otra bronquitis aguda especificada', 'category', false, false, 'CIE-11'),
('CA42.Z', 'Bronquitis aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CA43', 'Absceso pulmonar o mediastínico', 'category', false, false, 'CIE-11'),
('CA43.0', 'Gangrena o necrosis pulmonar', 'category', false, false, 'CIE-11'),
('CA43.1', 'Absceso pulmonar con neumonía', 'category', false, false, 'CIE-11'),
('CA43.2', 'Absceso pulmonar sin neumonía', 'category', false, false, 'CIE-11'),
('CA43.3', 'absceso mediastínico', 'category', false, false, 'CIE-11'),
('CA43.Y', 'Otro absceso pulmonar o mediastínico especificado', 'category', false, false, 'CIE-11'),
('CA43.Z', 'Absceso pulmonar o mediastínico, sin especificación', 'category', false, false, 'CIE-11'),
('CA44', 'Piotórax', 'category', false, false, 'CIE-11'),
('CA45', 'Infecciones respiratorias no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('CA4Y', 'Otras infecciones pulmonares especificadas', 'category', false, false, 'CIE-11'),
('CA4Z', 'Infecciones pulmonares, sin especificación', 'category', false, false, 'CIE-11'),
('CA60', 'Neumoconiosis', 'category', false, false, 'CIE-11'),
('CA60.0', 'Neumoconiosis por polvo de sílice', 'category', false, false, 'CIE-11'),
('CA60.00', 'Neumoconiosis por polvo de talco', 'category', false, false, 'CIE-11'),
('CA60.0Y', 'Otra neumoconiosis especificada por polvo de sílice', 'category', false, false, 'CIE-11'),
('CA60.0Z', 'Neumoconiosis por polvo de sílice, sin especificación', 'category', false, false, 'CIE-11'),
('CA60.1', 'antracosis', 'category', false, false, 'CIE-11'),
('CA60.2', 'Neumoconiosis por fibras minerales, incluyendo asbestos (amianto)', 'category', false, false, 'CIE-11'),
('CA60.3', 'Neumoconiosis asociada con tuberculosis', 'category', false, false, 'CIE-11'),
('CA60.4', 'Aluminosis pulmonar', 'category', false, false, 'CIE-11'),
('CA60.5', 'Fibrosis pulmonar por bauxita', 'category', false, false, 'CIE-11'),
('CA60.6', 'Beriliosis', 'category', false, false, 'CIE-11'),
('CA60.7', 'Fibrosis pulmonar por grafito', 'category', false, false, 'CIE-11'),
('CA60.8', 'Siderosis', 'category', false, false, 'CIE-11'),
('CA60.9', 'Estañosis', 'category', false, false, 'CIE-11'),
('CA60.Y', 'Otra neumoconiosis especificada', 'category', false, false, 'CIE-11'),
('CA60.Z', 'Neumoconiosis, sin especificación', 'category', false, false, 'CIE-11'),
('CA70', 'Neumonitis por hipersensibilidad a polvos orgánicos', 'category', false, false, 'CIE-11'),
('CA70.0', 'Pulmón de granjero', 'category', false, false, 'CIE-11'),
('CA70.1', 'Bagazosis', 'category', false, false, 'CIE-11'),
('CA70.2', 'Pulmón del avicultor', 'category', false, false, 'CIE-11'),
('CA70.3', 'Suberosis', 'category', false, false, 'CIE-11'),
('CA70.4', 'Pulmón de los manipuladores de la malta', 'category', false, false, 'CIE-11'),
('CA70.5', 'Pulmón del trabajador con setas, hongos o champiñones', 'category', false, false, 'CIE-11'),
('CA70.6', 'Pulmón del descortezador de arce', 'category', false, false, 'CIE-11'),
('CA70.7', 'Pulmón del aire acondicionado o de los humidificadores', 'category', false, false, 'CIE-11'),
('CA70.Y', 'Otra neumonitis especificada por hipersensibilidad a polvos orgánicos', 'category', false, false, 'CIE-11'),
('CA70.Z', 'Neumonitis por hipersensibilidad a polvos orgánicos, sin especificación', 'category', false, false, 'CIE-11'),
('CA71', 'Neumonitis debida a sólidos o líquidos', 'category', false, false, 'CIE-11'),
('CA71.0', 'Neumonitis por inhalación de comida o vómito', 'category', false, false, 'CIE-11'),
('CA71.1', 'Neumonitis por aceites o esencias', 'category', false, false, 'CIE-11'),
('CA71.2', 'Neumonitis por aspiración de sangre', 'category', false, false, 'CIE-11'),
('CA71.3', 'Neumonitis lipoidea', 'category', false, false, 'CIE-11'),
('CA71.Y', 'Otra neumonitis especificada debida a sólidos o líquidos', 'category', false, false, 'CIE-11'),
('CA71.Z', 'Neumonitis debida a sólidos o líquidos, sin especificación', 'category', false, false, 'CIE-11'),
('CA72', 'Síndrome de Mendelson', 'category', false, false, 'CIE-11'),
('CA7Y', 'Otra neumonitis especificada', 'category', false, false, 'CIE-11'),
('CA7Z', 'Neumonitis, sin especificación', 'category', false, false, 'CIE-11'),
('CA80', 'Enfermedades de las vías aéreas por polvos orgánicos específicos', 'category', false, false, 'CIE-11'),
('CA80.0', 'Bisinosis debida a exposición al algodón', 'category', false, false, 'CIE-11'),
('CA80.1', 'Enfermedad de los rastrilladores de lino', 'category', false, false, 'CIE-11'),
('CA80.2', 'Bisinosis debida a exposición a Cannabis', 'category', false, false, 'CIE-11'),
('CA80.Y', 'Otras enfermedades especificadas de las vías aéreas por polvos orgánicos específicos', 'category', false, false, 'CIE-11'),
('CA80.Z', 'Enfermedades de las vías aéreas por polvos orgánicos específicos, sin especificación', 'category', false, false, 'CIE-11'),
('CA81', 'Enfermedades respiratorias por inhalación de sustancias químicas, gases, humos o vapores', 'category', false, false, 'CIE-11'),
('CA81.0', 'Bronquitis o neumonitis por sustancias químicas, gases, humos o vapores', 'category', false, false, 'CIE-11'),
('CA81.1', 'Edema pulmonar por sustancias químicas, gases, humos o vapores', 'category', false, false, 'CIE-11'),
('CA81.2', 'Inflamación de vías respiratorias altas por sustancias químicas, gases, humos o vapores, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('CA81.Y', 'Otras enfermedades respiratorias especificadas por inhalación de sustancias químicas, gases, humos o vapores', 'category', false, false, 'CIE-11'),
('CA81.Z', 'Enfermedades respiratorias por inhalación de sustancias químicas, gases, humos o vapores, sin especificación', 'category', false, false, 'CIE-11'),
('CA82', 'Enfermedades respiratorias por otros agentes externos', 'category', false, false, 'CIE-11'),
('CA82.0', 'Manifestaciones pulmonares agudas por radiación', 'category', false, false, 'CIE-11'),
('CA82.1', 'Manifestaciones pulmonares crónicas o de otro tipo por radiación', 'category', false, false, 'CIE-11'),
('CA82.2', 'Trastornos pulmonares intersticiales agudos provocados por medicamentos', 'category', false, false, 'CIE-11'),
('CA82.3', 'Trastornos pulmonares intersticiales crónicos provocados por medicamentos', 'category', false, false, 'CIE-11'),
('CA82.4', 'Afecciones alérgicas o de hipersensibilidad por Aspergillus', 'category', false, false, 'CIE-11'),
('CA82.Y', 'Otras enfermedades respiratorias especificadas por otros agentes externos', 'category', false, false, 'CIE-11'),
('CA82.Z', 'Enfermedades respiratorias por otros agentes externos, sin especificación', 'category', false, false, 'CIE-11'),
('CA8Y', 'Otras enfermedades pulmonares especificadas por agentes externos', 'category', false, false, 'CIE-11'),
('CA8Z', 'Enfermedades pulmonares por agentes externos, sin especificación', 'category', false, false, 'CIE-11'),
('CB00', 'Síndrome de dificultad respiratoria aguda', 'category', false, false, 'CIE-11'),
('CB01', 'Edema pulmonar', 'category', false, false, 'CIE-11'),
('CB02', 'Eosinofilia pulmonar', 'category', false, false, 'CIE-11'),
('CB02.0', 'Eosinofilia pulmonar asmática', 'category', false, false, 'CIE-11'),
('CB02.1', 'Neumonitis eosinofílica idiopática', 'category', false, false, 'CIE-11'),
('CB02.10', 'Neumonitis eosinofílica idiopática aguda', 'category', false, false, 'CIE-11'),
('CB02.11', 'Neumonitis eosinofílica idiopática crónica', 'category', false, false, 'CIE-11'),
('CB02.1Y', 'Otra neumonitis eosinofílica idiopática especificada', 'category', false, false, 'CIE-11'),
('CB02.1Z', 'Neumonitis eosinofílica idiopática, sin especificación', 'category', false, false, 'CIE-11'),
('CB02.2', 'Eosinofilia pulmonar tropical', 'category', false, false, 'CIE-11'),
('CB02.Y', 'Otra eosinofilia pulmonar especificada', 'category', false, false, 'CIE-11'),
('CB02.Z', 'Eosinofilia pulmonar, sin especificación', 'category', false, false, 'CIE-11'),
('CB03', 'Neumonitis intersticial idiopática', 'category', false, false, 'CIE-11'),
('CB03.0', 'Neumonitis intersticial aguda', 'category', false, false, 'CIE-11'),
('CB03.1', 'síndrome combinado de fibrosis pulmonar y enfisema', 'category', false, false, 'CIE-11'),
('CB03.2', 'Neumonitis organizada criptogénica', 'category', false, false, 'CIE-11'),
('CB03.3', 'Neumonitis intersticial descamativa', 'category', false, false, 'CIE-11'),
('CB03.4', 'Fibrosis pulmonar idiopática', 'category', false, false, 'CIE-11'),
('CB03.5', 'Neumonía intersticial linfoidea', 'category', false, false, 'CIE-11'),
('CB03.6', 'Bronquiolitis respiratoria y enfermedad pulmonar intersticial', 'category', false, false, 'CIE-11'),
('CB03.Y', 'Otra neumonitis intersticial idiopática especificada', 'category', false, false, 'CIE-11'),
('CB03.Z', 'Neumonitis intersticial idiopática, sin especificación', 'category', false, false, 'CIE-11'),
('CB04', 'Enfermedades pulmonares intersticiales primarias específicas de la lactancia o la niñez', 'category', false, false, 'CIE-11'),
('CB04.0', 'Trastornos del desarrollo pulmonar difusos', 'category', false, false, 'CIE-11'),
('CB04.1', 'Síndromes de displasia linfática pulmonar', 'category', false, false, 'CIE-11'),
('CB04.2', 'Trastornos del metabolismo del surfactante', 'category', false, false, 'CIE-11'),
('CB04.3', 'Enfermedades alveolares o perialveolares', 'category', false, false, 'CIE-11'),
('CB04.30', 'Hemosiderosis pulmonar idiopática', 'category', false, false, 'CIE-11'),
('CB04.31', 'Proteinosis alveolar pulmonar', 'category', false, false, 'CIE-11'),
('CB04.3Y', 'Otras enfermedades alveolares o perialveolares especificadas', 'category', false, false, 'CIE-11'),
('CB04.3Z', 'Enfermedades alveolares o perialveolares, sin especificación', 'category', false, false, 'CIE-11'),
('CB04.4', 'Capilaritis pulmonar', 'category', false, false, 'CIE-11'),
('CB04.5', 'Síndrome de cerebro, pulmón, y tiroides', 'category', false, false, 'CIE-11'),
('CB04.6', 'Neumonitis crónica del lactante', 'category', false, false, 'CIE-11'),
('CB04.7', 'Hiperplasia de células neuroendocrinas del lactante', 'category', false, false, 'CIE-11'),
('CB04.Y', 'Otras enfermedades pulmonares intersticiales primarias especificadas específicas de la lactancia o la niñez', 'category', false, false, 'CIE-11'),
('CB04.Z', 'Enfermedades pulmonares intersticiales primarias específicas de la lactancia o la niñez, sin especificación', 'category', false, false, 'CIE-11'),
('CB05', 'Enfermedades pulmonares intersticiales asociadas a enfermedades sistémicas', 'category', false, false, 'CIE-11'),
('CB05.0', 'Daño alveolar difuso', 'category', false, false, 'CIE-11'),
('CB05.1', 'Enfermedades pulmonares intersticiales asociadas a enfermedades del tejido conjuntivo', 'category', false, false, 'CIE-11'),
('CB05.2', 'Enfermedades pulmonares intersticiales asociadas a enfermedades granulomatosas', 'category', false, false, 'CIE-11'),
('CB05.3', 'Enfermedades pulmonares intersticiales asociadas a enfermedades metabólicas', 'category', false, false, 'CIE-11'),
('CB05.4', 'Enfermedades pulmonares intersticiales asociadas a vasculitis sistémicas', 'category', false, false, 'CIE-11'),
('CB05.40', 'Trastornos respiratorios en el síndrome de Churg-Strauss', 'category', false, false, 'CIE-11'),
('CB05.41', 'Trastornos respiratorios en poliangitis microscópica', 'category', false, false, 'CIE-11'),
('CB05.4Y', 'Otras enfermedades pulmonares intersticiales especificadas asociadas a vasculitis sistémicas', 'category', false, false, 'CIE-11'),
('CB05.4Z', 'Enfermedades pulmonares intersticiales asociadas a vasculitis sistémicas, sin especificación', 'category', false, false, 'CIE-11'),
('CB05.5', 'Hemosiderosis pulmonar secundaria', 'category', false, false, 'CIE-11'),
('CB05.Y', 'Otras enfermedades pulmonares intersticiales especificadas asociadas a enfermedades sistémicas', 'category', false, false, 'CIE-11'),
('CB05.Z', 'Enfermedades pulmonares intersticiales asociadas a enfermedades sistémicas, sin especificación', 'category', false, false, 'CIE-11'),
('CB06', 'Microlitiasis alveolar pulmonar', 'category', false, false, 'CIE-11'),
('CB07', 'Linfangioliomiomatosis', 'category', false, false, 'CIE-11'),
('CB07.0', 'Linfangioliomiomatosis asociada al complejo de esclerosis tuberosa', 'category', false, false, 'CIE-11'),
('CB07.1', 'Linfangioliomiomatosis esporádica', 'category', false, false, 'CIE-11'),
('CB07.Y', 'Otra linfangioliomiomatosis especificada', 'category', false, false, 'CIE-11'),
('CB07.Z', 'Linfangioliomiomatosis, sin especificación', 'category', false, false, 'CIE-11'),
('CB0Y', 'Otras enfermedades respiratorias especificadas que afectan principalmente el intersticio pulmonar', 'category', false, false, 'CIE-11'),
('CB0Z', 'Enfermedades respiratorias que afectan principalmente el intersticio pulmonar, sin especificación', 'category', false, false, 'CIE-11'),
('CB20', 'Paquipleuritis', 'category', false, false, 'CIE-11'),
('CB21', 'Neumotórax', 'category', false, false, 'CIE-11'),
('CB21.0', 'Neumotórax espontáneo a tensión', 'category', false, false, 'CIE-11'),
('CB21.1', 'Otros tipos de neumotórax espontáneo', 'category', false, false, 'CIE-11'),
('CB21.Y', 'Otro neumotórax especificado', 'category', false, false, 'CIE-11'),
('CB21.Z', 'Neumotórax, sin especificación', 'category', false, false, 'CIE-11'),
('CB22', 'Enfermedades del mediastino, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('CB22.0', 'Mediastinitis fibrosante', 'category', false, false, 'CIE-11'),
('CB22.Y', 'Otras enfermedades especificadas del mediastino, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('CB22.Z', 'Enfermedades del mediastino, no clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('CB23', 'Trastornos del diafragma', 'category', false, false, 'CIE-11'),
('CB24', 'Quilotórax', 'category', false, false, 'CIE-11'),
('CB25', 'Fibrotórax', 'category', false, false, 'CIE-11'),
('CB26', 'Hemotórax', 'category', false, false, 'CIE-11'),
('CB27', 'Derrame pleural', 'category', false, false, 'CIE-11'),
('CB2Y', 'Otros trastornos pleurales, diafragmáticos o mediastínicos especificados', 'category', false, false, 'CIE-11'),
('CB2Z', 'Trastornos pleurales, diafragmáticos o mediastínicos, sin especificación', 'category', false, false, 'CIE-11'),
('CB40', 'Algunas enfermedades del sistema respiratorio', 'category', false, false, 'CIE-11'),
('CB40.0', 'Disquinesia ciliar', 'category', false, false, 'CIE-11'),
('CB40.1', 'Síndrome de Young', 'category', false, false, 'CIE-11'),
('CB40.2', 'Atelectasia', 'category', false, false, 'CIE-11'),
('CB40.3', 'Enfisema intersticial', 'category', false, false, 'CIE-11'),
('CB40.4', 'Enfisema compensatorio', 'category', false, false, 'CIE-11'),
('CB40.Y', 'Algunas otras enfermedades especificadas del sistema respiratorio', 'category', false, false, 'CIE-11'),
('CB41', 'Insuficiencia respiratoria', 'category', false, false, 'CIE-11'),
('CB41.0', 'Insuficiencia respiratoria aguda', 'category', false, false, 'CIE-11'),
('CB41.00', 'Insuficiencia respiratoria aguda de tipo I', 'category', false, false, 'CIE-11'),
('CB41.01', 'Insuficiencia respiratoria aguda de tipo II', 'category', false, false, 'CIE-11'),
('CB41.0Z', 'Insuficiencia respiratoria aguda, sin especificación', 'category', false, false, 'CIE-11'),
('CB41.1', 'Insuficiencia respiratoria crónica', 'category', false, false, 'CIE-11'),
('CB41.10', 'Insuficiencia respiratoria crónica de tipo I', 'category', false, false, 'CIE-11'),
('CB41.11', 'Insuficiencia respiratoria crónica de tipo II', 'category', false, false, 'CIE-11'),
('CB41.1Z', 'Insuficiencia respiratoria crónica, sin especificación', 'category', false, false, 'CIE-11'),
('CB41.2', 'Insuficiencia respiratoria, no especificada como aguda o crónica', 'category', false, false, 'CIE-11'),
('CB41.20', 'Insuficiencia respiratoria de tipo I, no especificada como aguda o crónica', 'category', false, false, 'CIE-11'),
('CB41.21', 'Insuficiencia respiratoria de tipo II, no especificada como aguda o crónica', 'category', false, false, 'CIE-11'),
('CB41.2Z', 'Insuficiencia respiratoria, sin especificación', 'category', false, false, 'CIE-11'),
('CB60', 'Funcionamiento defectuoso de traqueostomía', 'category', false, false, 'CIE-11'),
('CB61', 'Insuficiencia pulmonar crónica tras cirugía', 'category', false, false, 'CIE-11'),
('CB62', 'Estenosis subglótica tras un procedimiento', 'category', false, false, 'CIE-11'),
('CB63', 'Estenosis traqueal tras un procedimiento', 'category', false, false, 'CIE-11'),
('CB64', 'Lesión pulmonar aguda relacionada con una transfusión', 'category', false, false, 'CIE-11'),
('CB7Z', 'Enfermedades del sistema respiratorio, sin especificación', 'category', false, false, 'CIE-11'),
('DA00', 'Afecciones de los labios', 'category', false, false, 'CIE-11'),
('DA00.0', 'Queilitis', 'category', false, false, 'CIE-11'),
('DA00.1', 'Traumatismo autoinfligido del labio', 'category', false, false, 'CIE-11'),
('DA00.2', 'Anomalías pigmentarias de los labios', 'category', false, false, 'CIE-11'),
('DA00.3', 'Fisura de labio', 'category', false, false, 'CIE-11'),
('DA00.Y', 'Otras afecciones especificadas de los labios', 'category', false, false, 'CIE-11'),
('DA00.Z', 'Afecciones de los labios, sin especificación', 'category', false, false, 'CIE-11'),
('DA01', 'Trastornos de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.0', 'Alteraciones del epitelio bucal', 'category', false, false, 'CIE-11'),
('DA01.00', 'Leucoplasia bucal', 'category', false, false, 'CIE-11'),
('DA01.01', 'Leucoplasia pilosa', 'category', false, false, 'CIE-11'),
('DA01.02', 'Salpullido migrante de la boca', 'category', false, false, 'CIE-11'),
('DA01.0Y', 'Otras alteraciones del epitelio bucal especificadas', 'category', false, false, 'CIE-11'),
('DA01.0Z', 'Alteraciones del epitelio bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA01.1', 'Afecciones erosivas o ulcerativas no infecciosas de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.10', 'Aftas o úlceras aftoides de la boca', 'category', false, false, 'CIE-11'),
('DA01.11', 'Mucositis bucal', 'category', false, false, 'CIE-11'),
('DA01.12', 'Estomatitis ulcerativa crónica', 'category', false, false, 'CIE-11'),
('DA01.13', 'Eritema multiforme con úlceras bucales', 'category', false, false, 'CIE-11'),
('DA01.14', 'Úlcera bucal provocada por medicamentos', 'category', false, false, 'CIE-11'),
('DA01.15', 'Úlceras en la boca', 'category', false, false, 'CIE-11'),
('DA01.1Y', 'Otras afecciones erosivas o ulcerativas no infecciosas especificadas de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.1Z', 'Afecciones erosivas o ulcerativas no infecciosas de la mucosa bucal, sin especificación', 'category', false, false, 'CIE-11'),
('DA01.2', 'Granulomas o lesiones granulomatoides de la mucosa bucal', 'category', false, false, 'CIE-11'),
('DA01.20', 'Granuloma de células gigantes, central', 'category', false, false, 'CIE-11'),
('DA01.21', 'Granulomatosis bucofacial', 'category', false, false, 'CIE-11'),
('DA01.2Y', 'Otros granulomas o lesiones granulomatoides especificados de la mucosa bucal', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
