-- CIE11 Import Part 53
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XE7A0', 'Animal suelto como contraparte en un choque con transporte terrestre', 'category', false, false, 'CIE-11'),
('XE22V', 'Animal acorralado como contraparte en un choque de transporte terrestre.', 'category', false, false, 'CIE-11'),
('XE756', 'Animal montado como contraparte en un choque con un transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6X8', 'Vehículo de tracción animal como contraparte en un choque con un transporte terrestre', 'category', false, false, 'CIE-11'),
('XE6DQ', 'Vehículo ferroviario como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE320', 'Tren ferroviario como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1W8', 'Funicular o monorriel como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE98X', 'Objeto fijo o estacionario como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE3KY', 'Vehículo estacionado al costado de una carretera o en un estacionamiento como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE1RC', 'Pequeño objeto suelto como contraparte en un choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE9KG', 'Objeto fijado liviano o pequeño como contraparte en un choque con transporte terrestre', 'category', false, false, 'CIE-11'),
('XE43C', 'Objeto fijado pesado o grande como contraparte en choque de transporte terrestre', 'category', false, false, 'CIE-11'),
('XE0JJ', 'Caída en medio de transporte sin contraparte', 'category', false, false, 'CIE-11'),
('XE3M5', 'Caída de un medio de transporte sin contraparte', 'category', false, false, 'CIE-11'),
('XE64P', 'Caída del caballo sin contraparte', 'category', false, false, 'CIE-11'),
('XE20L', 'Caída de un vehículo de motor sin contraparte', 'category', false, false, 'CIE-11'),
('XE7JA', 'Caída de una motocicleta sin contraparte', 'category', false, false, 'CIE-11'),
('XE2K7', 'Caída del ciclo de pedal sin contraparte', 'category', false, false, 'CIE-11'),
('XE929', 'Caída del transporte peatonal sin contraparte', 'category', false, false, 'CIE-11'),
('XE5XB', 'Otro mecanismo especificado sin contraparte', 'category', false, false, 'CIE-11'),
('XE5FP', 'Movimiento repentino del vehículo, sin colisión, que resulta en una lesión', 'category', false, false, 'CIE-11'),
('XE9K8', 'Vehículo volcado sin contraparte', 'category', false, false, 'CIE-11'),
('XE5YL', 'Vehículo fuera de control sin mención de colisión con otro vehículo u objeto fijo', 'category', false, false, 'CIE-11'),
('XE3GK', 'Equipo de deportes de pelota', 'category', false, false, 'CIE-11'),
('XE9UG', 'tipo de deporte o actividad de ejercicio, baloncesto', 'category', false, false, 'CIE-11'),
('XE3T2', 'Tipo de deporte o actividad de ejercicio, fútbol- tackle Americano', 'category', false, false, 'CIE-11'),
('XE31W', 'Tipo de deporte o actividad de ejercicio, fútbol - bandera o toque Americano', 'category', false, false, 'CIE-11'),
('XE72L', 'Tipo de deporte o actividad de ejercicio, fútbol con reglas Australianas', 'category', false, false, 'CIE-11'),
('XE3BA', 'Tipo de deporte o actividad de ejercicio, fútbol no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE7D6', 'Tipo de deporte o actividad de ejercicio, equipo de balón mano', 'category', false, false, 'CIE-11'),
('XE510', 'Tipo de deporte o actividad de ejercicio, baloncesto', 'category', false, false, 'CIE-11'),
('XE9RW', 'Tipo de deporte o actividad de ejercicio, unión de rugby', 'category', false, false, 'CIE-11'),
('XE5XZ', 'Tipo de deporte o actividad de ejercicio, liga de rugby', 'category', false, false, 'CIE-11'),
('XE1XR', 'Tipo de deporte o actividad de ejercicio, rugby no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE5EU', 'Tipo de deporte o actividad de ejercicio, fútbol al aire libre', 'category', false, false, 'CIE-11'),
('XE0TN', 'Tipo de deporte o actividad de ejercicio, fútbol de interior', 'category', false, false, 'CIE-11'),
('XE8WP', 'Tipo de deporte o actividad de ejercicio, fútbol no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE79M', 'Tipo de deporte o actividad de ejercicio, voleibol', 'category', false, false, 'CIE-11'),
('XE0JP', 'Tipo de deporte o actividad de ejercicio, wallyball', 'category', false, false, 'CIE-11'),
('XE2BF', 'Deporte de equipo de bate o palo', 'category', false, false, 'CIE-11'),
('XE84M', 'Tipo de deporte o actividad de ejercicio, béisbol', 'category', false, false, 'CIE-11'),
('XE5M7', 'Tipo de deporte o actividad de ejercicio, criquet', 'category', false, false, 'CIE-11'),
('XE2UD', 'Tipo de deporte o actividad de ejercicio, hockey sobre hielo', 'category', false, false, 'CIE-11'),
('XE6B7', 'Tipo de deporte o actividad de ejercicio, hockey de calle o bola', 'category', false, false, 'CIE-11'),
('XE8HB', 'Tipo de deporte o actividad de ejercicio, campo de hockey', 'category', false, false, 'CIE-11'),
('XE9N5', 'Tipo de deporte o actividad de ejercicio, hockey sobre piso', 'category', false, false, 'CIE-11'),
('XE02P', 'Tipo de deporte o actividad de ejercicio, hockey - no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE8M1', 'Tipo de deporte o actividad de ejercicio, ringette', 'category', false, false, 'CIE-11'),
('XE63E', 'Tipo de deporte o actividad de ejercicio, softball', 'category', false, false, 'CIE-11'),
('XE5WM', 'Tipo de deporte o actividad de ejercicio, t-ball', 'category', false, false, 'CIE-11'),
('XE2BG', 'Deportes acuáticos de equipo', 'category', false, false, 'CIE-11'),
('XE8KM', 'Tipo de deporte o actividad de ejercicio, rescate y resucitación', 'category', false, false, 'CIE-11'),
('XE6Y2', 'Tipo de deporte o actividad de ejercicio, natación sincronizada', 'category', false, false, 'CIE-11'),
('XE323', 'Tipo de deporte o actividad de ejercicio, hockey subacuático', 'category', false, false, 'CIE-11'),
('XE2YS', 'Tipo de deporte o actividad de ejercicio, waterpolo', 'category', false, false, 'CIE-11'),
('XE85T', 'Deportes náuticos', 'category', false, false, 'CIE-11'),
('XE1LG', 'Tipo de deporte o actividad de ejercicio, canotaje', 'category', false, false, 'CIE-11'),
('XE7BZ', 'Tipo de deporte o actividad de ejercicio, jet sky', 'category', false, false, 'CIE-11'),
('XE99V', 'Tipo de deporte o actividad de ejercicio, kayak o rafting de agua blanca', 'category', false, false, 'CIE-11'),
('XE4LT', 'Tipo de deporte o actividad de ejercicio, carreras de botes de motor', 'category', false, false, 'CIE-11'),
('XE4XV', 'Tipo de deporte o actividad de ejercicio, remo o impulso con remo', 'category', false, false, 'CIE-11'),
('XE0XD', 'Tipo de deporte o actividad de ejercicio, navegación de surf', 'category', false, false, 'CIE-11'),
('XE0G3', 'Tipo de deporte o actividad de ejercicio, yate o vela', 'category', false, false, 'CIE-11'),
('XE6W9', 'Deportes acuáticos individuales', 'category', false, false, 'CIE-11'),
('XE3R2', 'Tipo de deporte o actividad de ejercicio, plataforma de buceo', 'category', false, false, 'CIE-11'),
('XE7S0', 'Tipo de deporte o actividad de ejercicio, trampolín de buceo', 'category', false, false, 'CIE-11'),
('XE5UC', 'Tipo de deporte o actividad de ejercicio, buceo no especificado', 'category', false, false, 'CIE-11'),
('XE5FN', 'Tipo de deporte o actividad de ejercicio, pesca', 'category', false, false, 'CIE-11'),
('XE1TE', 'Tipo de deporte o actividad de ejercicio, submarinismo', 'category', false, false, 'CIE-11'),
('XE1ZK', 'Tipo de deporte o actividad de ejercicio, buceo con tubo (snorkel)', 'category', false, false, 'CIE-11'),
('XE48G', 'Tipo de deporte o actividad de ejercicio, surf o boogie boarding', 'category', false, false, 'CIE-11'),
('XE84Q', 'Tipo de deporte o actividad de ejercicio, salvando la vida en el surf', 'category', false, false, 'CIE-11'),
('XE1FN', 'Tipo de deporte o actividad de ejercicio, natación competitiva', 'category', false, false, 'CIE-11'),
('XE167', 'Tipo de deporte o actividad de ejercicio, esquí acuático', 'category', false, false, 'CIE-11'),
('XE92F', 'Tipo de deporte o actividad de ejercicio, tubería de agua', 'category', false, false, 'CIE-11'),
('XE7PV', 'Tipo de deporte o actividad de ejercicio, wind surf', 'category', false, false, 'CIE-11'),
('XE5RZ', 'Tipo de deporte o actividad de ejercicio, buceo en acantilado', 'category', false, false, 'CIE-11'),
('XE6P1', 'Tipo de deporte o actividad de ejercicio, natación recreativa', 'category', false, false, 'CIE-11'),
('XE9DF', 'Deportes de hielo o nieve', 'category', false, false, 'CIE-11'),
('XE225', 'Tipo de deporte o actividad de ejercicio, bobsledding', 'category', false, false, 'CIE-11'),
('XE7J1', 'Tipo de deporte o actividad de ejercicio, curling', 'category', false, false, 'CIE-11'),
('XE1SZ', 'Tipo de deporte o actividad de ejercicio, patinaje sobre hielo o baile sobre hielo', 'category', false, false, 'CIE-11'),
('XE9KF', 'Tipo de deporte o actividad de ejercicio, luge', 'category', false, false, 'CIE-11'),
('XE7E1', 'Tipo de deporte o actividad de ejercicio, patrullaje de esquí', 'category', false, false, 'CIE-11'),
('XE9X7', 'Tipo de deporte o actividad de ejercicio, esquí - alpino o cuesta abajo', 'category', false, false, 'CIE-11'),
('XE8CR', 'Tipo de deporte o actividad de ejercicio, esquí - campo de cross nórdico', 'category', false, false, 'CIE-11'),
('XE8UF', 'Tipo de deporte o actividad de ejercicio, esquí de estilo libre', 'category', false, false, 'CIE-11'),
('XE471', 'Tipo de deporte o actividad de ejercicio, salto de esquí de nieve', 'category', false, false, 'CIE-11'),
('XE240', 'Tipo de deporte o actividad de ejercicio, motos de nieve', 'category', false, false, 'CIE-11'),
('XE7J0', 'Tipo de deporte o actividad de ejercicio, snow boarding', 'category', false, false, 'CIE-11'),
('XE6RE', 'Tipo de deporte o actividad de ejercicio, patinaje de velocidad', 'category', false, false, 'CIE-11'),
('XE8G0', 'Tipo de deporte o actividad de ejercicio, tobogganing', 'category', false, false, 'CIE-11'),
('XE3L1', 'Actividades atléticas individuales', 'category', false, false, 'CIE-11'),
('XE286', 'Tipo de deporte o actividad de ejercicio, aeróbica o calisténica', 'category', false, false, 'CIE-11'),
('XE5KC', 'Tipo de deporte o actividad de ejercicio, trotar o correr', 'category', false, false, 'CIE-11'),
('XE05C', 'Tipo de deporte o actividad de ejercicio, tai chi', 'category', false, false, 'CIE-11'),
('XE1SW', 'Tipo de deporte o actividad de ejercicio, atletismo - carreras por obstáculos o vallas', 'category', false, false, 'CIE-11'),
('XE02A', 'Tipo de deporte o actividad de ejercicio, atletismo-carreras de velocidad (1-400 metros)', 'category', false, false, 'CIE-11'),
('XE2RC', 'Tipo de deporte o actividad de ejercicio, atletismo-carrera de distancias medias (401-1,500 metros)', 'category', false, false, 'CIE-11'),
('XE4Y7', 'Tipo de deporte o actividad de ejercicio, atletismo- carrera de larga distancia (más de 1,500 metros)', 'category', false, false, 'CIE-11'),
('XE1X1', 'Tipo de deporte o actividad de ejercicio,atletismo - salto en alto', 'category', false, false, 'CIE-11'),
('XE10W', 'Tipo de deporte o actividad de ejercicio, atletismo - salto en largo', 'category', false, false, 'CIE-11'),
('XE8YM', 'Tipo de deporte o actividad de ejercicio, atletismo -salto con pértiga', 'category', false, false, 'CIE-11'),
('XE5X4', 'Tipo de deporte o actividad de ejercicio, atletismo -triple salto', 'category', false, false, 'CIE-11'),
('XE4C5', 'Tipo de deporte o actividad de ejercicio, atletismo -disco', 'category', false, false, 'CIE-11'),
('XE037', 'Tipo de deporte o actividad de ejercicio, atletismo -javalina', 'category', false, false, 'CIE-11'),
('XE1FT', 'Tipo de deporte o actividad de ejercicio, atletismo-lanzamiento de martillo', 'category', false, false, 'CIE-11'),
('XE3M7', 'Tipo de deporte o actividad de ejercicio, atletismo-tiro al blanco', 'category', false, false, 'CIE-11'),
('XE2TV', 'Tipo de actividad deportiva o de ejercicio, caminata', 'category', false, false, 'CIE-11'),
('XE7F9', 'Tipo de actividad deportiva o de ejercicios, yoga o Pilates', 'category', false, false, 'CIE-11'),
('XE9V7', 'Tipo de actividad deportiva o de ejercicios, ejercicio aeróbico estacionario con equipo', 'category', false, false, 'CIE-11'),
('XE4HZ', 'Deportes acrobáticos', 'category', false, false, 'CIE-11'),
('XE2T9', 'Tipo de deporte o actividad de ejercicio, porristas', 'category', false, false, 'CIE-11'),
('XE65D', 'Tipo de deporte o actividad de ejercicio, gimnasia - barra de equilibrio', 'category', false, false, 'CIE-11'),
('XE5WY', 'Tipo de deporte o actividad de ejercicio,gimnasia - ejercicio en el piso o volteando', 'category', false, false, 'CIE-11'),
('XE69D', 'Tipo de deporte o actividad de ejercicio, gimnasia - barra alta', 'category', false, false, 'CIE-11'),
('XE6R6', 'Tipo de deporte o actividad de ejercicio, gimnasia - barras paralelas', 'category', false, false, 'CIE-11'),
('XE4YF', 'Tipo de deporte o actividad de ejercicio, Gimnasia- rítmica con o sin accesorios', 'category', false, false, 'CIE-11'),
('XE8WK', 'Tipo de deporte o actividad de ejercicio, gimnasia - anillos', 'category', false, false, 'CIE-11'),
('XE802', 'Tipo de deporte o actividad de ejercicio, gimnasia - caballo lateral o caballo con arcos', 'category', false, false, 'CIE-11'),
('XE8V7', 'Tipo de deporte o actividad de ejercicio, gimnasia - trampolín o mini-trampolín', 'category', false, false, 'CIE-11'),
('XE5KU', 'Tipo de deporte o actividad de ejercicio, gimnasia - barras paralelas desiguales', 'category', false, false, 'CIE-11'),
('XE7PU', 'Tipo de deporte o actividad de ejercicio, gimnasia -salto con base', 'category', false, false, 'CIE-11'),
('XE9SK', 'Actividades estéticas', 'category', false, false, 'CIE-11'),
('XE6H2', 'Tipo de deporte o actividad de ejercicio, baile', 'category', false, false, 'CIE-11'),
('XE0R2', 'Tipo de deporte o actividad de ejercicio, marcha', 'category', false, false, 'CIE-11'),
('XE0KE', 'Deportes de raqueta', 'category', false, false, 'CIE-11'),
('XE3SV', 'Tipo de deporte o actividad de ejercicio, bádminton', 'category', false, false, 'CIE-11'),
('XE5Z7', 'Tipo de deporte o actividad de ejercicio, racquetball', 'category', false, false, 'CIE-11'),
('XE629', 'Tipo de deporte o actividad de ejercicio, squash', 'category', false, false, 'CIE-11'),
('XE5JM', 'Tipo de deporte o actividad de ejercicio, tenis de mesa o ping- pong', 'category', false, false, 'CIE-11'),
('XE97B', 'Tipo de deporte o actividad de ejercicio, tenis', 'category', false, false, 'CIE-11'),
('XE2NY', 'Target o deportes de precisión', 'category', false, false, 'CIE-11'),
('XE0KA', 'Tipo de deporte o actividad de ejercicio, tiro con arco', 'category', false, false, 'CIE-11'),
('XE760', 'Tipo de deporte o actividad de ejercicio, bochas, bolos o petancas', 'category', false, false, 'CIE-11'),
('XE5XX', 'Tipo de deporte o actividad de ejercicio, billar, pool o snooker', 'category', false, false, 'CIE-11'),
('XE5VJ', 'Tipo de deporte o actividad de ejercicio, bolos de césped', 'category', false, false, 'CIE-11'),
('XE8AU', 'Tipo de deporte o actividad de ejercicio, croquet', 'category', false, false, 'CIE-11'),
('XE7NG', 'Tipo de deporte o actividad de ejercicio, dardos', 'category', false, false, 'CIE-11'),
('XE416', 'Tipo de deporte o actividad de ejercicio, golf', 'category', false, false, 'CIE-11'),
('XE6YY', 'Tipo de deporte o actividad de ejercicio, bolos', 'category', false, false, 'CIE-11'),
('XE08Q', 'Tipo de deporte o actividad física, tiro con arma de fuego', 'category', false, false, 'CIE-11'),
('XE0HX', 'Tipo de actividad deportiva o de ejercicio, bb o disparo con pistola de perdigones', 'category', false, false, 'CIE-11'),
('XE1N9', 'Tipo de deporte o actividad física, tiro con pistola de paintball', 'category', false, false, 'CIE-11'),
('XE3E4', 'Deportes de combate', 'category', false, false, 'CIE-11'),
('XE7K5', 'Tipo de deporte o actividad de ejercicio, aikido', 'category', false, false, 'CIE-11'),
('XE8AB', 'Tipo de deporte o actividad de ejercicio, boxeo', 'category', false, false, 'CIE-11'),
('XE4E3', 'Tipo de deporte o actividad de ejercicio, esgrima', 'category', false, false, 'CIE-11'),
('XE6B1', 'Tipo de deporte o actividad de ejercicio, yudo', 'category', false, false, 'CIE-11'),
('XE0U2', 'Tipo de deporte o actividad de ejercicio, jujitsu', 'category', false, false, 'CIE-11'),
('XE567', 'Tipo de deporte o actividad de ejercicio, karate', 'category', false, false, 'CIE-11'),
('XE8WT', 'Tipo de deporte o actividad de ejercicio, kendo', 'category', false, false, 'CIE-11'),
('XE0Y9', 'Tipo de deporte o actividad de ejercicio, kick- boxing', 'category', false, false, 'CIE-11'),
('XE5QV', 'Tipo de deporte o actividad de ejercicio, fung fu', 'category', false, false, 'CIE-11'),
('XE7RA', 'Tipo de deporte o actividad de ejercicio, tae kwon do', 'category', false, false, 'CIE-11'),
('XE0CG', 'Tipo de deporte o actividad de ejercicio, lucha libre', 'category', false, false, 'CIE-11'),
('XE8M6', 'Tipo de deporte o actividad de ejercicio, lucha Greco- Romana', 'category', false, false, 'CIE-11'),
('XE4QQ', 'Tipo de deporte o actividad de ejercicio, lucha libre profesional- estilo entretenimiento', 'category', false, false, 'CIE-11'),
('XE75J', 'Tipo de deporte o actividad de ejercicio, entrenamiento en defensa personal', 'category', false, false, 'CIE-11'),
('XE1EU', 'Deportes de potencia', 'category', false, false, 'CIE-11'),
('XE7QE', 'Tipo de deporte o actividad de ejercicio, levantamiento de pesas', 'category', false, false, 'CIE-11'),
('XE6RQ', 'Tipo de deporte o actividad de ejercicio, levantamiento de pesas, levantamiento de pesas Olímpico', 'category', false, false, 'CIE-11'),
('XE0N6', 'Tipo de deporte o actividad de ejercicio, entrenamiento de fuerza o fisicoculturismo', 'category', false, false, 'CIE-11'),
('XE3PG', 'Tipo de deporte o actividad de ejercicio, deportes relacionados con la madera', 'category', false, false, 'CIE-11'),
('XE42Q', 'Actividades ecuestres', 'category', false, false, 'CIE-11'),
('XE6DF', 'Tipo de deporte o actividad de ejercicio, doma ecuestre', 'category', false, false, 'CIE-11'),
('XE75K', 'Tipo de deporte o actividad de ejercicio, equitación de resistencia', 'category', false, false, 'CIE-11'),
('XE8JM', 'Tipo de actividad deportiva o de ejercicio, eventos ecuestres', 'category', false, false, 'CIE-11'),
('XE0BK', 'Tipo de actividad deportiva o de ejercicio, concentración o trabajo de serie', 'category', false, false, 'CIE-11'),
('XE6PK', 'Tipo de deporte o actividad de ejercicio, polo o polocrosse ecuestre', 'category', false, false, 'CIE-11'),
('XE4GZ', 'Tipo de deporte o actividad de ejercicio, pony club', 'category', false, false, 'CIE-11'),
('XE0P4', 'Tipo de deporte o actividad de ejercicio, carreras de caballos', 'category', false, false, 'CIE-11'),
('XE56X', 'Tipo de deporte o actividad de ejercicio, rodeo', 'category', false, false, 'CIE-11'),
('XE7X5', 'Tipo de deporte o actividad de ejercicio, salto de obstáculos', 'category', false, false, 'CIE-11'),
('XE7MC', 'Tipo de deporte o actividad de ejercicio, carrera de obstáculos ecuestre', 'category', false, false, 'CIE-11'),
('XE1LH', 'Tipo de deporte o actividad de ejercicio, sendero o montar a caballo en general', 'category', false, false, 'CIE-11'),
('XE2LJ', 'Tipo de deporte o actividad de ejercicio, trote o arnés ecuestre', 'category', false, false, 'CIE-11'),
('XE3T3', 'Deportes de aventura', 'category', false, false, 'CIE-11'),
('XE08U', 'Tipo de deporte o actividad de ejercicio, rapel o abseiling', 'category', false, false, 'CIE-11'),
('XE5BS', 'Tipo de deporte o actividad de ejercicio, excursionismo', 'category', false, false, 'CIE-11'),
('XE79W', 'Tipo de deporte o actividad de ejercicio, montañismo', 'category', false, false, 'CIE-11'),
('XE8WG', 'Tipo de deporte o actividad de ejercicio, orientación o rumbo', 'category', false, false, 'CIE-11'),
('XE2J8', 'Tipo de deporte o actividad de ejercicio, rafting en río', 'category', false, false, 'CIE-11'),
('XE6Z2', 'Tipo de actividad deportiva o de ejercicio, escalada en roca', 'category', false, false, 'CIE-11'),
('XE74G', 'Tipo de deporte o actividad de ejercicio, puentismo', 'category', false, false, 'CIE-11'),
('XE85A', 'Deportes de motor con ruedas', 'category', false, false, 'CIE-11'),
('XE7HV', 'Tipo de deporte o actividad de ejercicio, conducir un vehículo todoterreno (VTT)', 'category', false, false, 'CIE-11'),
('XE1R5', 'Tipo de deporte o actividad de ejercicio, motociclismo', 'category', false, false, 'CIE-11'),
('XE26F', 'Tipo de deporte o actividad de ejercicio, carrera de coche de motor', 'category', false, false, 'CIE-11'),
('XE46F', 'Tipo de actividad deportiva o de ejercicio, go-karting o karting', 'category', false, false, 'CIE-11'),
('XE1MM', 'Tipo de actividad deportiva o de ejercicio, scooter motorizado', 'category', false, false, 'CIE-11'),
('XE4DA', 'Deportes con ruedas no motorizados', 'category', false, false, 'CIE-11'),
('XE5UJ', 'Tipo de actividad deportiva o de ejercicio, ciclismo BMX', 'category', false, false, 'CIE-11'),
('XE4SS', 'Tipo de deporte o actividad de ejercicio, ciclismo de montaña', 'category', false, false, 'CIE-11'),
('XE87G', 'Tipo de deporte o actividad de ejercicio, ciclismo de ruta', 'category', false, false, 'CIE-11'),
('XE8U6', 'Tipo de deporte o actividad de ejercicio, ciclismo en pista o veldromo', 'category', false, false, 'CIE-11'),
('XE7MG', 'Tipo de deporte o actividad de ejercicio, ciclismo no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE5V9', 'Tipo de deporte o actividad de ejercicio, ciclismo patinaje en línea / patinaje en roller', 'category', false, false, 'CIE-11'),
('XE2DY', 'Tipo de deporte o actividad de ejercicio,patín sobre ruedas', 'category', false, false, 'CIE-11'),
('XE1AS', 'Tipo de deporte o actividad de ejercicio, monopatín', 'category', false, false, 'CIE-11'),
('XE6X9', 'Tipo de deporte o actividad de ejercicio, scootering', 'category', false, false, 'CIE-11'),
('XE72X', 'Tipo de deporte o actividad de ejercicio, giro o bicicleta fija', 'category', false, false, 'CIE-11'),
('XE78K', 'Tipo de deporte o actividad de ejercicio, trineo de asfalto', 'category', false, false, 'CIE-11'),
('XE7BS', 'Deportes multidisciplinarios', 'category', false, false, 'CIE-11'),
('XE3BK', 'Tipo de deporte o actividad de ejercicio, biatlón: evento de esquí de fondo', 'category', false, false, 'CIE-11'),
('XE05T', 'Tipo de deporte o actividad de ejercicio, biatlón - evento de tiro', 'category', false, false, 'CIE-11'),
('XE7ZX', 'Tipo de deporte o actividad de ejercicio, biatlón: de evento no especificado', 'category', false, false, 'CIE-11'),
('XE5PT', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de 100 metros', 'category', false, false, 'CIE-11'),
('XE7ND', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de 400 metros', 'category', false, false, 'CIE-11'),
('XE9AM', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de 1500 metros', 'category', false, false, 'CIE-11'),
('XE5C1', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de 110 metros con vallas', 'category', false, false, 'CIE-11'),
('XE6CK', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de salto en largo', 'category', false, false, 'CIE-11'),
('XE331', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de salto en alto', 'category', false, false, 'CIE-11'),
('XE6GN', 'Tipo de deporte o ejercicio, decatlón- evento de lanzamiento de bola', 'category', false, false, 'CIE-11'),
('XE11Q', 'Tipo de deporte o actividad de ejercicio, decatlón- evento de lanzamiento del disco', 'category', false, false, 'CIE-11'),
('XE37C', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de lanzamiento de jabalina', 'category', false, false, 'CIE-11'),
('XE7LJ', 'Tipo de deporte o actividad de ejercicio, decatlón - evento de salto con pértiga', 'category', false, false, 'CIE-11'),
('XE48E', 'Tipo de deporte o actividad de ejercicio, decatlón - de evento no especificado', 'category', false, false, 'CIE-11'),
('XE4LW', 'Tipo de deporte o actividad de ejercicio, heptatlón - evento de 200 metros', 'category', false, false, 'CIE-11'),
('XE9EF', 'Tipo de deporte o actividad de ejercicio, heptatlón: evento de 100 metros con vallas', 'category', false, false, 'CIE-11'),
('XE90J', 'Tipo de deporte o actividad de ejercicio, heptatlón - evento de salto en alto', 'category', false, false, 'CIE-11'),
('XE8WE', 'Tipo de deporte o actividad de ejercicio, heptatlón - evento de salto de longitud', 'category', false, false, 'CIE-11'),
('XE7TG', 'Tipo de deporte o actividad de ejercicio, heptatlón - evento de jabalina', 'category', false, false, 'CIE-11'),
('XE294', 'Tipo de actividad deportiva o de ejercicio, heptatlon: evento de lanzamiento de bala', 'category', false, false, 'CIE-11'),
('XE4CW', 'Tipo de deporte o actividad de ejercicio, heptatlón - evento de 800 metros', 'category', false, false, 'CIE-11'),
('XE1JE', 'Tipo de deporte o actividad de ejercicio, heptatlon - evento no especificado', 'category', false, false, 'CIE-11'),
('XE3GA', 'Tipo de deporte o actividad de ejercicio, pentatlón moderno - evento de tiro', 'category', false, false, 'CIE-11'),
('XE758', 'Tipo de deporte o actividad de ejercicio, pentatlon moderno- evento de esgrima', 'category', false, false, 'CIE-11'),
('XE7GA', 'Tipo de deporte o actividad de ejercicio, pentatlón moderno: evento de natación', 'category', false, false, 'CIE-11'),
('XE8KQ', 'Tipo de deporte o actividad de ejercicio, pentatlón: evento ecuestre', 'category', false, false, 'CIE-11'),
('XE84E', 'Tipo de deporte o actividad de ejercicio, pentatlón moderno- evento de carrera', 'category', false, false, 'CIE-11'),
('XE2B4', 'Tipo de deporte o actividad de ejercicio,pentatlón moderno evento no especificado', 'category', false, false, 'CIE-11'),
('XE2XU', 'Tipo de deporte o actividad de ejercicio, triatlón: evento de ciclismo', 'category', false, false, 'CIE-11'),
('XE0J9', 'Tipo de deporte o actividad de ejercicio, triatlón: evento de carrera', 'category', false, false, 'CIE-11'),
('XE8ZK', 'Tipo de deporte o actividad de ejercicio, triatlón: evento de natación', 'category', false, false, 'CIE-11'),
('XE01T', 'Tipo de deporte o actividad de ejercicio, triatlón: evento no especificado', 'category', false, false, 'CIE-11'),
('XE03W', 'Deportes aéreos (sin- motor)', 'category', false, false, 'CIE-11'),
('XE34L', 'Tipo de deporte o actividad de ejercicio, acrobacia aérea', 'category', false, false, 'CIE-11'),
('XE88Y', 'Tipo de deporte o actividad de ejercicio, planeo', 'category', false, false, 'CIE-11'),
('XE3VS', 'Tipo de deporte o actividad de ejercicio, ala delta', 'category', false, false, 'CIE-11'),
('XE0JU', 'Tipo de deporte o actividad de ejercicio, paracaidismo/ salto con paracaídas', 'category', false, false, 'CIE-11'),
('XE06C', 'Tipo de deporte o actividad de ejercicio, parapente y parasailing', 'category', false, false, 'CIE-11'),
('XE99S', 'Tipo de deporte o actividad de ejercicio, globo aerostático', 'category', false, false, 'CIE-11'),
('XE68C', 'Otras actividades recreativas relacionadas con la escuela', 'category', false, false, 'CIE-11'),
('XE49T', 'Tipo de deporte o actividad de ejercicio, clase de educación física escolar', 'category', false, false, 'CIE-11'),
('XE67P', 'Tipo de deporte o actividad de ejercicio, juego libre en la escuela', 'category', false, false, 'CIE-11'),
('XE9ET', 'Fase del deporte o actividad de ejercicio-Entrenamiento o práctica', 'category', false, false, 'CIE-11'),
('XE1U5', 'fase de actividad, práctica de habilidad específica o de deporte específico', 'category', false, false, 'CIE-11'),
('XE07B', 'fase de actividad, competencia', 'category', false, false, 'CIE-11'),
('XE0BT', 'Fase de actividad, fuerza y acondicionamiento o entrenamiento con pesas', 'category', false, false, 'CIE-11'),
('XE945', 'fase de actividad, entrenamiento cardiovascular', 'category', false, false, 'CIE-11'),
('XE583', 'Fase de actividad, no especificada en otra parte entrenamiento o práctica especificada', 'category', false, false, 'CIE-11'),
('XE8MZ', 'fase de actividad, pre-evento', 'category', false, false, 'CIE-11'),
('XE2D1', 'fase de actividad, calentamiento', 'category', false, false, 'CIE-11'),
('XE5TJ', 'Fase del deporte o actividad de ejercicio-Competición o participación', 'category', false, false, 'CIE-11'),
('XE66C', 'Fase de actividad, competencia o participación, primer 25% de la duración del evento esperado', 'category', false, false, 'CIE-11'),
('XE0QY', 'Fase de actividad, competencia o participación, medio 50% de la duración del evento esperado', 'category', false, false, 'CIE-11'),
('XE2CG', 'Fase de actividad, competencia o participación, último 25% de la duración del evento esperado', 'category', false, false, 'CIE-11'),
('XE20Y', 'Fase de actividad, competencia o participación, eventos cuyo curso temporal no puede anticiparse', 'category', false, false, 'CIE-11'),
('XE4ZN', 'Fase de actividad, competencia o participación, etapa no especificada del evento', 'category', false, false, 'CIE-11'),
('XE1P9', 'fase de actividad, enfriamiento', 'category', false, false, 'CIE-11'),
('XE2BD', 'fase de actividad, post evento', 'category', false, false, 'CIE-11'),
('XE49R', 'fase de actividad, participación recreativa', 'category', false, false, 'CIE-11'),
('XE0QV', 'Fase de actividad, otra fase de actividad especificada', 'category', false, false, 'CIE-11'),
('XE8ZT', 'Fase de actividad no especificada', 'category', false, false, 'CIE-11'),
('XE4K4', 'Contramedidas personales, sin uso de medidas de protección', 'category', false, false, 'CIE-11'),
('XE8Z8', 'Contramedidas personales, aparatos ortopédicos, protectores u ortesis', 'category', false, false, 'CIE-11'),
('XE75U', 'Contramedidas personales, cinta rígida de articulación', 'category', false, false, 'CIE-11'),
('XE9TY', 'Contramedidas personales, acolchado de la articulación, prominencia ósea o músculo', 'category', false, false, 'CIE-11'),
('XE10N', 'Contramedidas personales, dispositivos térmicos', 'category', false, false, 'CIE-11'),
('XE0LS', 'Contramedidas personales, férulas', 'category', false, false, 'CIE-11'),
('XE16J', 'Contramedidas personales, suspensor o copa protectora', 'category', false, false, 'CIE-11'),
('XE4RU', 'Contramedidas personales, guantes', 'category', false, false, 'CIE-11'),
('XE49L', 'Contramedidas personales, protector bucal', 'category', false, false, 'CIE-11'),
('XE338', 'Contramedidas personales, anteojos de protección o gafas protectoras', 'category', false, false, 'CIE-11'),
('XE2ZG', 'Contramedidas personales, casco', 'category', false, false, 'CIE-11'),
('XE3RM', 'Contramedidas personales, máscara protectora o protector', 'category', false, false, 'CIE-11'),
('XE7K8', 'Contramedidas personales, calzado', 'category', false, false, 'CIE-11'),
('XE26E', 'Contramedidas personales, dispositivo de flotación personal', 'category', false, false, 'CIE-11'),
('XE3U8', 'Contramedidas ambientales, no se usaron dispositivos de protección', 'category', false, false, 'CIE-11'),
('XE0DA', 'Contramedidas ambientales, relleno protector en la superficie de competición', 'category', false, false, 'CIE-11'),
('XE0W0', 'Contramedidas ambientales, postes de meta acolchados o marcadores de esquina', 'category', false, false, 'CIE-11'),
('XE8UC', 'Contramedidas ambientales, barrera entre el área de actividad y los espectadores o los alrededores', 'category', false, false, 'CIE-11'),
('XE0LL', 'Contramedidas ambientales, restricciones de seguridad o restricciones del vehículo', 'category', false, false, 'CIE-11'),
('XE7J2', 'Actividad económica, agricultura, caza y silvicultura', 'category', false, false, 'CIE-11'),
('XE227', 'Actividad económica, pesca', 'category', false, false, 'CIE-11'),
('XE45Q', 'Actividad económica, minería, canteras o extracción', 'category', false, false, 'CIE-11'),
('XE13G', 'Actividad económica, fabricación', 'category', false, false, 'CIE-11'),
('XE6WE', 'Actividad económica, electricidad, gas o suministro de agua', 'category', false, false, 'CIE-11'),
('XE0SE', 'Actividad económica, construcción', 'category', false, false, 'CIE-11'),
('XE139', 'Actividad económica, comercio mayorista o minorista', 'category', false, false, 'CIE-11'),
('XE6J4', 'Actividad económica, reparación de vehículos de motor, motocicletas o bienes personales y domésticos', 'category', false, false, 'CIE-11'),
('XE4JS', 'Actividad económica, hoteles o restaurantes', 'category', false, false, 'CIE-11'),
('XE5JN', 'Actividad económica, transporte, almacenamiento o comunicaciones', 'category', false, false, 'CIE-11'),
('XE8A7', 'actividad económica, intermediación financiera', 'category', false, false, 'CIE-11'),
('XE3YF', 'Actividad económica, bienes raíces, alquiler o actividades comerciales', 'category', false, false, 'CIE-11'),
('XE3K1', 'Actividad económica, administración pública, defensa o seguridad social obligatoria', 'category', false, false, 'CIE-11'),
('XE54F', 'Actividad económica, proporcionar educación', 'category', false, false, 'CIE-11'),
('XE0G4', 'Actividad económica, salud o trabajo social', 'category', false, false, 'CIE-11'),
('XE7X1', 'Actividad económica, otras actividades de servicio comunitario, social o personal', 'category', false, false, 'CIE-11'),
('XE2PM', 'Actividad económica, hogares privados con personas empleadas', 'category', false, false, 'CIE-11'),
('XE6N7', 'Actividad económica, organizaciones o cuerpos extraterritoriales', 'category', false, false, 'CIE-11'),
('XE3TU', 'Ocupación- legisladores, altos funcionarios, gerentes', 'category', false, false, 'CIE-11'),
('XE59Y', 'Ocupación- profesionales', 'category', false, false, 'CIE-11'),
('XE558', 'Ocupación- técnicos o profesionales asociados', 'category', false, false, 'CIE-11'),
('XE17U', 'Ocupación- oficinistas, secretarias', 'category', false, false, 'CIE-11'),
('XE1CA', 'Ocupación- trabajadores de servicios, trabajadores de ventas de tiendas y mercados', 'category', false, false, 'CIE-11'),
('XE6TG', 'Ocupación,-agricultura especializada y trabajadores de la pesca', 'category', false, false, 'CIE-11'),
('XE0VC', 'Ocupación- artesanos o trabajadores de oficios relacionados', 'category', false, false, 'CIE-11'),
('XE37Y', 'Ocupación- operadores de planta / máquina o ensambladores', 'category', false, false, 'CIE-11'),
('XE4EE', 'Ocupación- ocupaciones elementales', 'category', false, false, 'CIE-11'),
('XE5G8', 'Ocupación- fuerzas armadas', 'category', false, false, 'CIE-11'),
('XE454', 'Cónyuge o pareja', 'category', false, false, 'CIE-11'),
('XE041', 'Relación entre el perpetrador y la victima, cónyuge legal', 'category', false, false, 'CIE-11'),
('XE8JN', 'Relación entre el perpetrador y la víctima, compañero de convivencia', 'category', false, false, 'CIE-11'),
('XE8GZ', 'Relación entre el perpetrador y la víctima, pareja no cohabitante', 'category', false, false, 'CIE-11'),
('XE6Q9', 'Relación entre el perpetrador y la víctima, Ex cónyuge', 'category', false, false, 'CIE-11'),
('XE8TC', 'Relación entre el perpetrador y la víctima, Ex pareja', 'category', false, false, 'CIE-11'),
('XE8AA', 'Padres', 'category', false, false, 'CIE-11'),
('XE8QX', 'Relación entre el perpetrador y la víctima, padre o madre', 'category', false, false, 'CIE-11'),
('XE9FD', 'Relación entre el perpetrador y la víctima, padrastro o madrastra', 'category', false, false, 'CIE-11'),
('XE5WN', 'Otro pariente', 'category', false, false, 'CIE-11'),
('XE9JY', 'Relación entre el perpetrador y la víctima, hermano directo', 'category', false, false, 'CIE-11'),
('XE9RK', 'Relación entre el perpetrador y la víctima, hermano parcial o medio hermano', 'category', false, false, 'CIE-11'),
('XE4KJ', 'Relación entre el perpetrador y la víctima, hermanastro', 'category', false, false, 'CIE-11'),
('XE9S0', 'Relación entre el perpetrador y la víctima, abuelo', 'category', false, false, 'CIE-11'),
('XE10C', 'Relación entre el perpetrador y la víctima, descendencia', 'category', false, false, 'CIE-11'),
('XE8EU', 'Relación entre el perpetrador y la víctima, otro pariente de sangre', 'category', false, false, 'CIE-11'),
('XE8FS', 'Relación entre el perpetrador y la víctima, parientes políticos', 'category', false, false, 'CIE-11'),
('XE4BG', 'Cuidador no relacionado', 'category', false, false, 'CIE-11'),
('XE4BZ', 'Relación entre el perpetrador y la víctima, padre adoptivo', 'category', false, false, 'CIE-11'),
('XE670', 'Relación entre el perpetrador y la víctima, cuidador en la institución', 'category', false, false, 'CIE-11'),
('XE02B', 'Relación entre el perpetrador y la víctima, proveedor de cuidado de la salud', 'category', false, false, 'CIE-11'),
('XE270', 'Conocido o amigo', 'category', false, false, 'CIE-11'),
('XE1X5', 'Relación entre el perpetrador y la víctima, pareja de los padres', 'category', false, false, 'CIE-11'),
('XE7GT', 'Relación entre el perpetrador y la víctima, acompañante', 'category', false, false, 'CIE-11'),
('XE6WK', 'Relación entre el perpetrador y la víctima, compañero de cuarto', 'category', false, false, 'CIE-11'),
('XE6P9', 'Relación entre el perpetrador y la víctima, relación de negocios', 'category', false, false, 'CIE-11'),
('XE32X', 'Relación entre el perpetrador y la víctima, vecino', 'category', false, false, 'CIE-11'),
('XE80F', 'Relación entre el perpetrador y la víctima, co-miembro institucional', 'category', false, false, 'CIE-11'),
('XE5MH', 'Relación entre el perpetrador y la víctima, amigo no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE39B', 'Relación entre el perpetrador y la víctima, conocido no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE2HC', 'Autoridad oficial o legal', 'category', false, false, 'CIE-11'),
('XE6AM', 'Relación entre el perpetrador y la víctima, autoridad oficial o legal, militar', 'category', false, false, 'CIE-11'),
('XE2Z7', 'Relación entre el perpetrador y la víctima, autoridad oficial o legal, policía', 'category', false, false, 'CIE-11'),
('XE5ZT', 'Relación entre el perpetrador y la víctima, autoridad oficial o nacional no especificada en otra parte', 'category', false, false, 'CIE-11'),
('XE8PB', 'Relación entre el perpetrador y la víctima, grupo de seguridad no especificado', 'category', false, false, 'CIE-11'),
('XE59K', 'Relación entre el perpetrador y la víctima, autoridad oficial o legal, autoridad civil', 'category', false, false, 'CIE-11'),
('XE4WS', 'Extraño', 'category', false, false, 'CIE-11'),
('XE0CA', 'Relación entre el perpetrador y la víctima, extraño en grupo vigilante', 'category', false, false, 'CIE-11'),
('XE7XG', 'Relación entre el perpetrador y la víctima, extraño en la mafia', 'category', false, false, 'CIE-11'),
('XE2XY', 'Relación entre el perpetrador y la víctima, extraño no especificado en otra parte', 'category', false, false, 'CIE-11'),
('XE0H2', 'Relación entre el perpetrador y la víctima, prisionero o detenido', 'category', false, false, 'CIE-11'),
('XE3FJ', 'Relación entre el perpetrador y la víctima, persona ejecutando un delito o crimen', 'category', false, false, 'CIE-11'),
('XE388', 'Relación entre el perpetrador y la víctima, persona intercediendo en un crimen', 'category', false, false, 'CIE-11'),
('XE5YG', 'Género del perpetrador, masculino', 'category', false, false, 'CIE-11'),
('XE56C', 'Género del perpetrador, femenino', 'category', false, false, 'CIE-11'),
('XE9SL', 'Género del perpetrador, desconocido', 'category', false, false, 'CIE-11'),
('XE6W8', 'Género del perpetrador, otro', 'category', false, false, 'CIE-11'),
('XE0UM', 'Altercado', 'category', false, false, 'CIE-11'),
('XE591', 'Acerca de las cuestiones familiares', 'category', false, false, 'CIE-11'),
('XE2RR', 'contexto de agresión, altercado acerca de los problemas de la familia, los niños', 'category', false, false, 'CIE-11'),
('XE37R', 'contexto de agresión, altercado acerca de los problemas de la familia, suegros', 'category', false, false, 'CIE-11'),
('XE1B3', 'contexto de agresión, altercado acerca de los problemas familiares, problemas de dote', 'category', false, false, 'CIE-11'),
('XE1F9', 'contexto de agresión, altercado acerca de asuntos familiares, honor familiar', 'category', false, false, 'CIE-11'),
('XE9SP', 'Acerca de asuntos personales', 'category', false, false, 'CIE-11'),
('XE1XB', 'Contexto de agresión, altercado sobre una relación de amor actual', 'category', false, false, 'CIE-11'),
('XE3YH', 'Contexto de agresión, altercado sobre una relación de amor terminada', 'category', false, false, 'CIE-11'),
('XE6DB', 'Contexto de agresión, altercado sobre el sexo', 'category', false, false, 'CIE-11'),
('XE4H5', 'Acerca de puntos de vista personales', 'category', false, false, 'CIE-11'),
('XE03X', 'Contexto de agresión, altercado sobre opiniones personales con respecto a la política', 'category', false, false, 'CIE-11'),
('XE860', 'Contexto de agresión, altercado sobre opiniones personales con respecto asuntos religiosos o espirituales', 'category', false, false, 'CIE-11'),
('XE1RW', 'Contexto de agresión, altercado sobre opiniones personales con respecto asuntos culturales', 'category', false, false, 'CIE-11'),
('XE6YL', 'Contexto de agresión, altercado sobre opiniones personales con respecto asuntos raciales o etnicos', 'category', false, false, 'CIE-11'),
('XE1Q8', 'Contexto de agresión, altercado sobre opiniones personales con respecto asuntos de género u orientación sexual', 'category', false, false, 'CIE-11'),
('XE0Z5', 'Acerca de negocios o asuntos financieros', 'category', false, false, 'CIE-11'),
('XE4ML', 'Contexto de agresión, altercado sobre la pérdida de empleo', 'category', false, false, 'CIE-11'),
('XE00W', 'Contexto de agresión, altercado sobre otras pérdidas financieras relacionadas con empleo o negocios', 'category', false, false, 'CIE-11'),
('XE05L', 'Contexto de agresión, otras disputas laborales', 'category', false, false, 'CIE-11'),
('XE62S', 'Contexto de agresión, altercado sobre dinero o propiedad', 'category', false, false, 'CIE-11'),
('XE6VD', 'Acerca de los deportes y otros ocios', 'category', false, false, 'CIE-11'),
('XE81U', 'Contexto de agresión, altercado sobre el juego de apuestas', 'category', false, false, 'CIE-11'),
('XE47F', 'Contexto de agresión, altercado sobre deportes', 'category', false, false, 'CIE-11'),
('XE8NL', 'Contexto de agresión, altercado sobre el tráfico', 'category', false, false, 'CIE-11'),
('XE4XA', 'Contexto de agresión, mala conducta maliciosa', 'category', false, false, 'CIE-11'),
('XE4P2', 'Contexto de agresión, acoso, intimidación', 'category', false, false, 'CIE-11'),
('XE3KE', 'Contexto de agresión, altercado sobre altercados pasados', 'category', false, false, 'CIE-11'),
('XE91G', 'Adquisición ilegal o intento de adquisición ilegal de dinero o propiedad', 'category', false, false, 'CIE-11'),
('XE0LR', 'Contexto de agresión, robo con lesión', 'category', false, false, 'CIE-11'),
('XE6PL', 'Robo', 'category', false, false, 'CIE-11'),
('XE6YM', 'Contexto de agresión, robo sin armas', 'category', false, false, 'CIE-11'),
('XE989', 'Contexto de agresión, robo armado', 'category', false, false, 'CIE-11'),
('XE933', 'Incidente relacionado con drogas', 'category', false, false, 'CIE-11'),
('XE5AY', 'Contexto de agresión, venta de drogas o negocios de drogas', 'category', false, false, 'CIE-11'),
('XE0Z6', 'Contexto de agresión, discusión sobre posesión, uso o costo de las drogas', 'category', false, false, 'CIE-11'),
('XE1GC', 'Contexto de agresión, falta de pago de una deuda de drogas', 'category', false, false, 'CIE-11'),
('XE1LL', 'Contexto de agresión, probable participación de drogas, pero sin evidencia positiva', 'category', false, false, 'CIE-11'),
('XE213', 'Contexto de agresión, ataque sexual', 'category', false, false, 'CIE-11'),
('XE6U2', 'Contexto de agresión, violación o intento de violación', 'category', false, false, 'CIE-11'),
('XE85Q', 'Contexto de agresión, sodomía o intento de sodomía', 'category', false, false, 'CIE-11'),
('XE29Q', 'Contexto de agresión, tocar o acariciar los genitales', 'category', false, false, 'CIE-11'),
('XE18N', 'Contexto de agresión, sexo oral', 'category', false, false, 'CIE-11'),
('XE8DB', 'Incidente relacionado con pandillas', 'category', false, false, 'CIE-11'),
('XE3QM', 'Contexto de agresión, iniciación de pandillas', 'category', false, false, 'CIE-11'),
('XE2A5', 'Contexto de agresión, rivalidad de pandillas', 'category', false, false, 'CIE-11'),
('XE3V7', 'Otra actividad criminal', 'category', false, false, 'CIE-11'),
('XE2QF', 'Contexto de agresión, chantaje', 'category', false, false, 'CIE-11'),
('XE1N7', 'Contexto de agresión, secuestro', 'category', false, false, 'CIE-11'),
('XE0NB', 'Contexto de agresión, lesión o muerte por contrato', 'category', false, false, 'CIE-11'),
('XE5A7', 'contexto de agresión,', 'category', false, false, 'CIE-11'),
('XE5QX', 'Otro contexto especificado de agresión', 'category', false, false, 'CIE-11'),
('XE6FN', 'Contexto de agresión, represalia o venganza', 'category', false, false, 'CIE-11'),
('XE3G0', 'Contexto de agresión, muerte por misericordia o eutanasia', 'category', false, false, 'CIE-11'),
('XE90G', 'contexto de agresión, Negligencia', 'category', false, false, 'CIE-11'),
('XE580', 'contexto de agresión, Tortura', 'category', false, false, 'CIE-11'),
('XE92U', 'contexto de agresión, contexto adicional, Identidad errónea', 'category', false, false, 'CIE-11'),
('XE17Z', 'Conflicto en la relación con miembro de la familia, pareja, o amigo', 'category', false, false, 'CIE-11'),
('XE9SZ', 'Factores de riesgo proximal para autolesión intencional, Conflicto en la relación con el cónyuge, pareja, novio / novia', 'category', false, false, 'CIE-11'),
('XE6QA', 'Factores de riesgo proximal para autolesión intencional, Conflicto en la relación con los padres', 'category', false, false, 'CIE-11'),
('XE1A1', 'Factores de riesgo proximal para autolesión intencional, Conflicto en la relación con la descendencia', 'category', false, false, 'CIE-11'),
('XE3GP', 'Muerte de pariente, pareja o amigo', 'category', false, false, 'CIE-11'),
('XE19R', 'Factores de riesgo proximal para autolesión intencional, Suicidio de un familiar, pareja o amigo', 'category', false, false, 'CIE-11'),
('XE8T3', 'Factores de riesgo proximal para autolesión intencional, Otra forma de muerte de un familiar, pareja o amigo', 'category', false, false, 'CIE-11'),
('XE2FT', 'Factores de riesgo proximal para autolesión intencional, Manera no especificada de muerte de un pariente, pareja o amigo', 'category', false, false, 'CIE-11'),
('XE97R', 'Problema físico', 'category', false, false, 'CIE-11'),
('XE5CU', 'Factores de riesgo proximal para autolesión intencional, VIH o sida', 'category', false, false, 'CIE-11'),
('XE3AG', 'Factores de riesgo proximal para la autolesión intencional, Embarazo no deseado', 'category', false, false, 'CIE-11'),
('XE6XD', 'Condición mental', 'category', false, false, 'CIE-11'),
('XE2Q7', 'Factores de riesgo proximal para la autolesión intencional, Abuso de sustancias', 'category', false, false, 'CIE-11'),
('XE79G', 'Factores de riesgo proximal para la autolesión intencional, Depresión postparto', 'category', false, false, 'CIE-11'),
('XE3U9', 'Problema financiero o relacionado con los ingresos', 'category', false, false, 'CIE-11'),
('XE70C', 'Factores de riesgo proximal para la autolesión intencional, Relacionados con el trabajo', 'category', false, false, 'CIE-11'),
('XE4UX', 'Factores de riesgo proximal para la autolesión intencional, Dote', 'category', false, false, 'CIE-11'),
('XE5J3', 'Abuso', 'category', false, false, 'CIE-11'),
('XE8HX', 'Factores de riesgo proximal para la autolesión intencional, Abuso sexual', 'category', false, false, 'CIE-11'),
('XE8ND', 'Factores de riesgo proximal para la autolesión intencional, Abuso físico', 'category', false, false, 'CIE-11'),
('XE2RX', 'Factores de riesgo proximal para la autolesión intencional, Negligencia', 'category', false, false, 'CIE-11'),
('XE31V', 'Factores de riesgo proximal para la autolesión intencional, Encuentros del sistema legal', 'category', false, false, 'CIE-11'),
('XE8MK', 'Factores de riesgo proximal para la autolesión intencional, Problema relacionado con la escuela', 'category', false, false, 'CIE-11'),
('XE98Q', 'Factores de riesgo proximal para la autolesión intencional, Creencia religiosa o afiliación', 'category', false, false, 'CIE-11'),
('XE6TW', 'Factores de riesgo proximal para la autolesión intencional, Problema cultural', 'category', false, false, 'CIE-11'),
('XE76W', 'intento de suicidio previo, No', 'category', false, false, 'CIE-11'),
('XE3YR', 'intento de suicidio previo, Si', 'category', false, false, 'CIE-11'),
('XE97V', 'Autolesión intencional, persona con intención de morir', 'category', false, false, 'CIE-11'),
('XE5D6', 'Autolesión intencional, la persona no tenía la intención de morir', 'category', false, false, 'CIE-11'),
('XE2SF', 'Autolesión intencional, desconocida o no determinada si la persona tenía la intención de morir', 'category', false, false, 'CIE-11'),
('XE2RB', 'Tipo de conflicto, guerra civil u operación de guerrilla', 'category', false, false, 'CIE-11'),
('XE324', 'tipo de conflicto, guerra', 'category', false, false, 'CIE-11'),
('XE4RJ', 'tipo de conflicto, terrorismo declarado', 'category', false, false, 'CIE-11'),
('XE0EG', 'tipo de conflicto, insurrección civil', 'category', false, false, 'CIE-11'),
('XE7HW', 'tipo de conflicto, incidente posterior al conflicto', 'category', false, false, 'CIE-11'),
('XE42H', 'Personal militar', 'category', false, false, 'CIE-11'),
('XE2WZ', 'Civil', 'category', false, false, 'CIE-11'),
('XE3P0', 'Papel de la persona lesionada en conflicto armado desconocido', 'category', false, false, 'CIE-11'),
('XE52B', 'Situación de arresto potencial', 'category', false, false, 'CIE-11'),
('XE9JF', 'tipo de intervención legal, potencial detención relacionada con el tráfico', 'category', false, false, 'CIE-11'),
('XE25D', 'tipo de intervención legal, potencial detención relacionada con la investigación de una persona sospechosa o incidente', 'category', false, false, 'CIE-11'),
('XE3XD', 'tipo de intervención legal, potencial detención relacionada con la ejecución de un arresto', 'category', false, false, 'CIE-11'),
('XE8Z9', 'Respuesta a una llamada por disturbios', 'category', false, false, 'CIE-11'),
('XE84H', 'tipo de intervención legal, respuesta a una llamada por disturbio debida a una disputa familiar', 'category', false, false, 'CIE-11'),
('XE8WD', 'tipo de intervención legal, respuesta a una llamada por disturbio debida a una persona que se comporta de forma aberrante', 'category', false, false, 'CIE-11'),
('XE3FV', 'tipo de intervención legal,Respuesta a otra llamada de perturbación especificada', 'category', false, false, 'CIE-11'),
('XE439', 'tipo de intervención legal, Respuesta a una llamada de perturbación no especificada', 'category', false, false, 'CIE-11'),
('XE8M2', 'tipo de intervención legal, situación de emboscada', 'category', false, false, 'CIE-11'),
('XE1DD', 'tipo de intervención legal, Desorden civil', 'category', false, false, 'CIE-11'),
('XE0RZ', 'Tipo de intervención legal, manipulación, transporte o custodia del prisionero', 'category', false, false, 'CIE-11'),
('XE7AT', 'tipo de intervención legal, Ejecución de sentencia legal', 'category', false, false, 'CIE-11'),
('XE4HK', 'Problema de interacción con el dispositivo del paciente', 'category', false, false, 'CIE-11'),
('XE6GS', 'Incompatibilidad paciente-dispositivo', 'category', false, false, 'CIE-11'),
('XE7ZE', 'Biocompatibilidad', 'category', false, false, 'CIE-11'),
('XE2CL', 'El dispositivo parece desencadenar el rechazo', 'category', false, false, 'CIE-11'),
('XE584', 'Inadecuación de la forma o el tamaño del dispositivo', 'category', false, false, 'CIE-11'),
('XE7JV', 'Problema de osteointegración', 'category', false, false, 'CIE-11'),
('XE94Z', 'Falla en la osteointegración', 'category', false, false, 'CIE-11'),
('XE0Z9', 'Carencia de osteointegración', 'category', false, false, 'CIE-11'),
('XE2K9', 'Aflojamiento del implante no relacionado con el crecimiento óseo', 'category', false, false, 'CIE-11'),
('XE0VD', 'Migración o expulsión de dispositivo', 'category', false, false, 'CIE-11'),
('XE763', 'Migración del dispositivo', 'category', false, false, 'CIE-11'),
('XE1FH', 'Expulsión de dispositivo', 'category', false, false, 'CIE-11'),
('XE7Q8', 'Problema de fabricación, embalaje o envío', 'category', false, false, 'CIE-11'),
('XE5Y1', 'Problema de calidad del producto', 'category', false, false, 'CIE-11'),
('XE4UR', 'Romo o contundente', 'category', false, false, 'CIE-11'),
('XE46G', 'Dispositivo no estándar', 'category', false, false, 'CIE-11'),
('XE1K1', 'Componente defectuoso', 'category', false, false, 'CIE-11'),
('XE9CD', 'Dispositivo defectuoso', 'category', false, false, 'CIE-11'),
('XE12L', 'Dispositivo dañado antes de su uso', 'category', false, false, 'CIE-11'),
('XE8RY', 'Problema de empaque', 'category', false, false, 'CIE-11'),
('XE01Z', 'Difícil de abrir o quitar el material de empaque', 'category', false, false, 'CIE-11'),
('XE5YH', 'Empaque incompleto o faltante', 'category', false, false, 'CIE-11'),
('XE4VM', 'Empaque del dispositivo sin sellar', 'category', false, false, 'CIE-11'),
('XE2AN', 'Desgarro, rasgado o agujero en el empaque del dispositivo', 'category', false, false, 'CIE-11'),
('XE151', 'Dispositivo mal ensamblado durante su fabricación o su envío', 'category', false, false, 'CIE-11'),
('XE9R8', 'Componente mal ensamblado', 'category', false, false, 'CIE-11'),
('XE89V', 'Componente faltante', 'category', false, false, 'CIE-11'),
('XE8ZA', 'Daños o problemas durante el envío', 'category', false, false, 'CIE-11'),
('XE78P', 'Entregado como producto sin esterilizar', 'category', false, false, 'CIE-11'),
('XE52X', 'Problema químico', 'category', false, false, 'CIE-11'),
('XE9AC', 'El dispositivo emite olor', 'category', false, false, 'CIE-11'),
('XE3E0', 'Problema con el reactivo o ingrediente del dispositivo', 'category', false, false, 'CIE-11'),
('XE4BC', 'La formación de grumos en el dispositivo o en los ingredientes del dispositivo', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
