-- CIE11 Import Part 47
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XA2XE0', 'Lámina ungueal del dedo índice', 'category', false, false, 'CIE-11'),
('XA6TA9', 'Yema del dedo índice', 'category', false, false, 'CIE-11'),
('XA0Y38', 'Dedo medio', 'category', false, false, 'CIE-11'),
('XA1FY2', 'Perioniquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA8YE5', 'Pliegue ungueal proximal del dedo medio', 'category', false, false, 'CIE-11'),
('XA13L6', 'Eponiquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA2N38', 'Pliegue ungueal lateral del dedo medio', 'category', false, false, 'CIE-11'),
('XA8KX8', 'Hiponiquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA9YZ9', 'Uña del dedo medio', 'category', false, false, 'CIE-11'),
('XA8VS0', 'Lúnula del dedo medio', 'category', false, false, 'CIE-11'),
('XA2A53', 'Matriz del dedo medio', 'category', false, false, 'CIE-11'),
('XA10T8', 'Lámina ungueal del dedo medio', 'category', false, false, 'CIE-11'),
('XA79X0', 'Yema del dedo medio', 'category', false, false, 'CIE-11'),
('XA06X8', 'Dedo anular', 'category', false, false, 'CIE-11'),
('XA7K11', 'Perioniquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA1F61', 'Pliegue ungueal proximal del dedo anular', 'category', false, false, 'CIE-11'),
('XA8L06', 'Eponiquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA3HG9', 'Pliegue ungueal lateral del dedo anular', 'category', false, false, 'CIE-11'),
('XA1W89', 'Hiponiquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA6Y59', 'Uña del anular', 'category', false, false, 'CIE-11'),
('XA4P58', 'Lúnula del dedo anular', 'category', false, false, 'CIE-11'),
('XA3MW5', 'Matriz de la uña del dedo anular', 'category', false, false, 'CIE-11'),
('XA3PS0', 'Lámina ungueal del dedo anular', 'category', false, false, 'CIE-11'),
('XA6C72', 'Yema del dedo anular', 'category', false, false, 'CIE-11'),
('XA5EN3', 'Dedo meñique', 'category', false, false, 'CIE-11'),
('XA89P0', 'Perioniquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4KU5', 'Pliegue ungueal proximal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA2AV8', 'Eponiquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA3LC5', 'Pliegue ungueal lateral del dedo meñique', 'category', false, false, 'CIE-11'),
('XA1C10', 'Hiponiquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4WN3', 'Yema del dedo meñique', 'category', false, false, 'CIE-11'),
('XA29K9', 'Uña del dedo meñique', 'category', false, false, 'CIE-11'),
('XA3R66', 'Lúnula del dedo meñique', 'category', false, false, 'CIE-11'),
('XA6HB9', 'Lecho de la uña del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4A79', 'Lámina ungueal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4HZ3', 'Lateral del dedo', 'category', false, false, 'CIE-11'),
('XA7GT9', 'Puntas de los dedos', 'category', false, false, 'CIE-11'),
('XA41X5', 'Punta del dedo índice', 'category', false, false, 'CIE-11'),
('XA9Y99', 'Punta del dedo medio', 'category', false, false, 'CIE-11'),
('XA91S7', 'Punta del dedo anular', 'category', false, false, 'CIE-11'),
('XA8QW7', 'Punta del dedo meñique', 'category', false, false, 'CIE-11'),
('XA0EH9', 'Uñas', 'category', false, false, 'CIE-11'),
('XA66R9', 'Piel del codo', 'category', false, false, 'CIE-11'),
('XA45A6', 'Extremidad inferior', 'category', false, false, 'CIE-11'),
('XA3VA7', 'Nalga', 'category', false, false, 'CIE-11'),
('XA5UE3', 'Pliegue glúteo', 'category', false, false, 'CIE-11'),
('XA5S78', 'Muslo', 'category', false, false, 'CIE-11'),
('XA98B3', 'Superficie anterior del muslo', 'category', false, false, 'CIE-11'),
('XA8RH9', 'Superficie lateral del muslo', 'category', false, false, 'CIE-11'),
('XA4TQ2', 'Región trocantérica', 'category', false, false, 'CIE-11'),
('XA0183', 'Superficie posterior del muslo', 'category', false, false, 'CIE-11'),
('XA1YQ6', 'Superficie medial del muslo', 'category', false, false, 'CIE-11'),
('XA9ZB4', 'Superficie medial superior del muslo', 'category', false, false, 'CIE-11'),
('XA8KL5', 'Rodilla', 'category', false, false, 'CIE-11'),
('XA9L17', 'Región patelar', 'category', false, false, 'CIE-11'),
('XA77E9', 'Superficie lateral de la rodilla', 'category', false, false, 'CIE-11'),
('XA9S09', 'Superficie medial de la rodilla', 'category', false, false, 'CIE-11'),
('XA4DM3', 'Fosa poplítea', 'category', false, false, 'CIE-11'),
('XA3YG1', 'Parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('XA33X4', 'Superficie anterior de la pierna inferior', 'category', false, false, 'CIE-11'),
('XA4K86', 'Pantorrilla', 'category', false, false, 'CIE-11'),
('XA4RR4', 'Superficie lateral de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('XA0LQ2', 'Superficie posterior de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('XA15P0', 'Superficie medial de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('XA5U49', 'Pierna distal', 'category', false, false, 'CIE-11'),
('XA90X0', 'Pierna proximal', 'category', false, false, 'CIE-11'),
('XA67V4', 'Tobillo', 'category', false, false, 'CIE-11'),
('XA2V14', 'Superficie anterior del tobillo', 'category', false, false, 'CIE-11'),
('XA7AM4', 'Superficie lateral del tobillo', 'category', false, false, 'CIE-11'),
('XA1D83', 'Región supramaleolar lateral', 'category', false, false, 'CIE-11'),
('XA41K4', 'Región retromaleolar lateral', 'category', false, false, 'CIE-11'),
('XA7P78', 'Superficie medial del tobillo', 'category', false, false, 'CIE-11'),
('XA87M9', 'Región supramaleolar medial', 'category', false, false, 'CIE-11'),
('XA1SM7', 'Región retromaleolar medial', 'category', false, false, 'CIE-11'),
('XA6AP4', 'Superficie posterior del tobillo', 'category', false, false, 'CIE-11'),
('XA47V8', 'Pie', 'category', false, false, 'CIE-11'),
('XA99M7', 'Retropié', 'category', false, false, 'CIE-11'),
('XA5HK0', 'Talón', 'category', false, false, 'CIE-11'),
('XA5ZE2', 'Superficie posterior del talón', 'category', false, false, 'CIE-11'),
('XA1QH8', 'Superficie medial del talón', 'category', false, false, 'CIE-11'),
('XA3R99', 'Superficie lateral del talón', 'category', false, false, 'CIE-11'),
('XA2N02', 'Superficie plantar del talón', 'category', false, false, 'CIE-11'),
('XA5151', 'Parte media del pie', 'category', false, false, 'CIE-11'),
('XA02P2', 'Superficie dorsal de la parte media del pie', 'category', false, false, 'CIE-11'),
('XA5YL1', 'Antepié', 'category', false, false, 'CIE-11'),
('XA81Z3', 'Superficie dorsal del antepié', 'category', false, false, 'CIE-11'),
('XA1FL5', 'Espacio de membrana interdigital del pie', 'category', false, false, 'CIE-11'),
('XA81N1', 'Primer espacio membranoso interdigital del pie', 'category', false, false, 'CIE-11'),
('XA8HC5', 'Segundo espacio membranoso interdigital del pie', 'category', false, false, 'CIE-11'),
('XA9LB9', 'Tercer espacio membranoso interdigital del pie', 'category', false, false, 'CIE-11'),
('XA2A07', 'Cuarto espacio membranoso interdigital del pie', 'category', false, false, 'CIE-11'),
('XA6KE9', 'Superficie plantar del antepié', 'category', false, false, 'CIE-11'),
('XA6V29', 'Región de la cabeza del primer metatarsiano', 'category', false, false, 'CIE-11'),
('XA2P22', 'Región de la cabeza del segundo metatarsiano', 'category', false, false, 'CIE-11'),
('XA0HX4', 'Región de la cabeza del tercer metatarsiano', 'category', false, false, 'CIE-11'),
('XA86J0', 'Región de la cabeza del cuarto metatarsiano', 'category', false, false, 'CIE-11'),
('XA05N7', 'Región de la cabeza del quinto metatarsiano', 'category', false, false, 'CIE-11'),
('XA8BE2', 'Dorso del pie', 'category', false, false, 'CIE-11'),
('XA1XM4', 'Planta del pie', 'category', false, false, 'CIE-11'),
('XA9Y82', 'Borde lateral del pie', 'category', false, false, 'CIE-11'),
('XA3WM8', 'Borde interno del pie', 'category', false, false, 'CIE-11'),
('XA3T29', 'Arco del pie', 'category', false, false, 'CIE-11'),
('XA4LC9', 'Dedos del pie', 'category', false, false, 'CIE-11'),
('XA2RP7', 'Dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA4774', 'Perioniquio del dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA8L19', 'Pliegue ungueal proximal del dedo', 'category', false, false, 'CIE-11'),
('XA7WP9', 'Eponiquio del dedo gordo', 'category', false, false, 'CIE-11'),
('XA7GD8', 'Pliegue ungueal lateral del dedo gordo', 'category', false, false, 'CIE-11'),
('XA2F64', 'Hiponiquio de dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA1RE3', 'Uña del dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA64R9', 'Lúnula del dedo gordo', 'category', false, false, 'CIE-11'),
('XA0HX8', 'Lecho ungueal del dedo gordo', 'category', false, false, 'CIE-11'),
('XA47T1', 'Lámina ungueal del dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA6VJ2', 'Almohadilla del dedo gordo del pie', 'category', false, false, 'CIE-11'),
('XA8ZZ3', 'Segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA5446', 'Perioniquio del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA1ED1', 'Pliegue ungueal proximal del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA0SL7', 'Eponiquio del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA7003', 'Pliegue ungueal lateral del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA2ZJ7', 'Hiponiquio del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA7GG3', 'Uña del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA9439', 'Lúnula del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA7B22', 'Lecho ungueal del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA1WQ6', 'Lámina ungueal del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA3626', 'Almohadilla del segundo dedo del pie', 'category', false, false, 'CIE-11'),
('XA0SP3', 'Tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA3UC8', 'Perioniquio del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA2484', 'Pliegue ungueal proximal del tercer dedo', 'category', false, false, 'CIE-11'),
('XA8DQ2', 'Eponiquio del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA1MM3', 'Pliegue ungueal lateral del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA2H72', 'Hiponiquio de tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA5JP9', 'Almohadilla del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA3D73', 'Uña del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA9UL1', 'Lúnula del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA6189', 'Lecho ungueal del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA3LW9', 'Lámina ungueal del tercer dedo del pie', 'category', false, false, 'CIE-11'),
('XA4KK7', 'Cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA40R3', 'Perioniquio del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA2Y79', 'Pliegue ungueal proximal del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA0XZ8', 'Eponiquio del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA0PV4', 'Pliegue ungueal lateral del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA4ZB3', 'Hiponiquio del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA9316', 'Almohadilla del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA6TS5', 'Uña del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA2PD3', 'Lúnula del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA65U3', 'Lecho ungueal del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA8F87', 'Lámina ungueal del cuarto dedo del pie', 'category', false, false, 'CIE-11'),
('XA42W4', 'Quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA1AV3', 'Perioniquio del quinto dedo', 'category', false, false, 'CIE-11'),
('XA43K6', 'Pliegue ungueal proximal del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA2W24', 'Eponiquio del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA38J0', 'Pliegue ungueal lateral del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA0DD8', 'Hiponiquio del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA3C43', 'Almohadilla del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA3VM6', 'Uña del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA1PK7', 'Lúnula del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA9L52', 'Lecho ungueal del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA4U10', 'Lámina ungueal del quinto dedo del pie', 'category', false, false, 'CIE-11'),
('XA9LJ5', 'Superficie plantar del dedo del pie', 'category', false, false, 'CIE-11'),
('XA7J49', 'Superficie dorsal del pie', 'category', false, false, 'CIE-11'),
('XA14Y9', 'Lateral del dedo del pie', 'category', false, false, 'CIE-11'),
('XA9E36', 'Uña de dedo del pie', 'category', false, false, 'CIE-11'),
('XA4UM2', 'Pared alveolar', 'category', false, false, 'CIE-11'),
('XA5UL3', 'Pared celular', 'category', false, false, 'CIE-11'),
('XA3JR1', 'Pared intestinal', 'category', false, false, 'CIE-11'),
('XA37C7', 'piso oral', 'category', false, false, 'CIE-11'),
('XA9KX3', 'pared parietal', 'category', false, false, 'CIE-11'),
('XA5CW9', 'Piso pélvico', 'category', false, false, 'CIE-11'),
('XA29C1', 'Pared pélvica', 'category', false, false, 'CIE-11'),
('XA60B5', 'septum rectovaginal', 'category', false, false, 'CIE-11'),
('XA37K5', 'Septo rectovesical', 'category', false, false, 'CIE-11'),
('XA1DP8', 'Pared uterina', 'category', false, false, 'CIE-11'),
('XA57Q2', 'Pared vaginal', 'category', false, false, 'CIE-11'),
('XA06R8', 'Fluido corporal', 'category', false, false, 'CIE-11'),
('XA1N55', 'Líquido cefalorraquídeo', 'category', false, false, 'CIE-11'),
('XA08M4', 'Líquido intersticial', 'category', false, false, 'CIE-11'),
('XA2L90', 'Líquido seroso', 'category', false, false, 'CIE-11'),
('XA0518', 'Líquido sinovial', 'category', false, false, 'CIE-11'),
('XA0UK0', 'Tejido óseo', 'category', false, false, 'CIE-11'),
('XA7YJ2', 'fibras colágenas', 'category', false, false, 'CIE-11'),
('XA5A05', 'Tejido conectivo', 'category', false, false, 'CIE-11'),
('XA6R65', 'tejido adiposo', 'category', false, false, 'CIE-11'),
('XA0FR0', 'Fascia', 'category', false, false, 'CIE-11'),
('XA51U1', 'tejido conectivo laxo', 'category', false, false, 'CIE-11'),
('XA53R0', 'Pericondrio', 'category', false, false, 'CIE-11'),
('XA7YP0', 'periodoncio', 'category', false, false, 'CIE-11'),
('XA6FQ2', 'Periostio', 'category', false, false, 'CIE-11'),
('XA3G85', 'Membrana sinovial', 'category', false, false, 'CIE-11'),
('XA8SZ4', 'Tejido linfático', 'category', false, false, 'CIE-11'),
('XA97C4', 'Tejido blando, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA5P05', 'Tejido blando de la extremidad, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA56S9', 'Epitelio', 'category', false, false, 'CIE-11'),
('XA0PT3', 'Mucosa', 'category', false, false, 'CIE-11'),
('XA0182', 'Mesotelio', 'category', false, false, 'CIE-11'),
('XA1922', 'Gameto', 'category', false, false, 'CIE-11'),
('XA95A3', 'Gameto femenino', 'category', false, false, 'CIE-11'),
('XA2470', 'Gameto masculino', 'category', false, false, 'CIE-11'),
('XA39T1', 'Tejido muscular', 'category', false, false, 'CIE-11'),
('XA6283', 'Músculo cardíaco', 'category', false, false, 'CIE-11'),
('XA0DD5', 'Músculo esquelético', 'category', false, false, 'CIE-11'),
('XA0JY3', 'Músculo liso', 'category', false, false, 'CIE-11'),
('XA5B23', 'Tejido nervioso', 'category', false, false, 'CIE-11'),
('XA1J91', 'Neuroglia', 'category', false, false, 'CIE-11'),
('XA1413', 'Neurona', 'category', false, false, 'CIE-11'),
('XA5BW5', 'Interneurona', 'category', false, false, 'CIE-11'),
('XA5DJ5', 'Neurona motora', 'category', false, false, 'CIE-11'),
('XA2LT7', 'Neurona sensitiva', 'category', false, false, 'CIE-11'),
('XA1ZV6', 'Cavidad Craneal', 'category', false, false, 'CIE-11'),
('XA1XM6', 'Espacio subaracnoideo', 'category', false, false, 'CIE-11'),
('XA1FQ8', 'Espacio subdural', 'category', false, false, 'CIE-11'),
('XA9QA7', 'Cavidad corporal dorsal', 'category', false, false, 'CIE-11'),
('XA1GB6', 'Espacio perineural', 'category', false, false, 'CIE-11'),
('XA2N82', 'Cavidad corporal ventral', 'category', false, false, 'CIE-11'),
('XA34B0', 'Cavidad abdominopélvica', 'category', false, false, 'CIE-11'),
('XA9M74', 'Cavidad abdominal', 'category', false, false, 'CIE-11'),
('XA25Q2', 'Cavidad pélvica', 'category', false, false, 'CIE-11'),
('XA9CK0', 'Fosa isquiorectal', 'category', false, false, 'CIE-11'),
('XA53A7', 'Región presacra', 'category', false, false, 'CIE-11'),
('XA2EG4', 'Región perirectal', 'category', false, false, 'CIE-11'),
('XA0GN7', 'Región inguinal', 'category', false, false, 'CIE-11'),
('XA7WA2', 'Mediastino', 'category', false, false, 'CIE-11'),
('XA5UF8', 'Mediastino anterior', 'category', false, false, 'CIE-11'),
('XA99Z0', 'Mediastino medio', 'category', false, false, 'CIE-11'),
('XA1FD0', 'Mediastino posterior', 'category', false, false, 'CIE-11'),
('XA8607', 'Tejidos conectivo y otros tejidos blandos del mediastino', 'category', false, false, 'CIE-11'),
('XA8YW7', 'Cavidad vertebral', 'category', false, false, 'CIE-11'),
('XA8SS8', 'Espacio epidural', 'category', false, false, 'CIE-11'),
('XA4LQ4', 'Espacio intramedular', 'category', false, false, 'CIE-11'),
('XA1XJ5', 'Cavidad torácica', 'category', false, false, 'CIE-11'),
('XA3LX5', 'Cavidad pleural', 'category', false, false, 'CIE-11'),
('XA2RT1', 'Región precordial', 'category', false, false, 'CIE-11'),
('XH96Q1', 'Adenoma de células acinares', 'category', false, false, 'CIE-11'),
('XH3PG9', 'Carcinoma de células acinosas', 'category', false, false, 'CIE-11'),
('XH99S4', 'Cistadenocarcinoma de células acinosas', 'category', false, false, 'CIE-11'),
('XH9B93', 'Carcinoma acinar- ductal mixto', 'category', false, false, 'CIE-11'),
('XH0F68', 'Adenocarcinoma acinar de pulmón', 'category', false, false, 'CIE-11'),
('XH2SK9', 'Tumor de células acinosas', 'category', false, false, 'CIE-11'),
('XH9574', 'Adenoma acidófilo', 'category', false, false, 'CIE-11'),
('XH3DV3', 'Adenoma, SAI', 'category', false, false, 'CIE-11'),
('XH1CV4', 'Poliposis adenomatosa coli', 'category', false, false, 'CIE-11'),
('XH1YP0', 'Adenoma cortical suprarrenal, de células claras', 'category', false, false, 'CIE-11'),
('XH2CT2', 'Adenoma cortical suprarrenal, de células compactas', 'category', false, false, 'CIE-11'),
('XH60N5', 'Adenoma cortical suprarrenal, de células glomerulosas', 'category', false, false, 'CIE-11'),
('XH2VZ8', 'Adenoma cortical suprarrenal, de células mixtas', 'category', false, false, 'CIE-11'),
('XH2FJ6', 'Adenoma cortical suprarrenal, pigmentado', 'category', false, false, 'CIE-11'),
('XH9356', 'Adenoma alveolar', 'category', false, false, 'CIE-11'),
('XH60D1', 'Adenoma de células basales', 'category', false, false, 'CIE-11'),
('XH3AH8', 'Adenoma basófilo', 'category', false, false, 'CIE-11'),
('XH6KR6', 'Adenoma del conducto biliar', 'category', false, false, 'CIE-11'),
('XH0778', 'Citoadenoma del conducto biliar', 'category', false, false, 'CIE-11'),
('XH7BS0', 'Neoplasia intraepitelial biliar, de bajo grado', 'category', false, false, 'CIE-11'),
('XH5YG5', 'Papilomatosis biliar', 'category', false, false, 'CIE-11'),
('XH1TD7', 'Adenoma canalicular', 'category', false, false, 'CIE-11'),
('XH6WK1', 'Adenoma de células pincipales', 'category', false, false, 'CIE-11'),
('XH7475', 'Adenoma cromófobo', 'category', false, false, 'CIE-11'),
('XH9JJ4', 'Adenofibroma de células claras', 'category', false, false, 'CIE-11'),
('XH8R87', 'Adenoma de células claras', 'category', false, false, 'CIE-11'),
('XH6J91', 'Cilindroma de la piel', 'category', false, false, 'CIE-11'),
('XH5GN1', 'Cilindroma dérmico ecrino', 'category', false, false, 'CIE-11'),
('XH6685', 'Adenoma embrionario', 'category', false, false, 'CIE-11'),
('XH3K13', 'Displasia esofágica glandular (neoplasia intraepitelial) de bajo grado', 'category', false, false, 'CIE-11'),
('XH83X4', 'Adenoma plana', 'category', false, false, 'CIE-11'),
('XH0LM0', 'Adenoma folicular', 'category', false, false, 'CIE-11'),
('XH5SM2', 'Adenoma folicular, de células oxifílicas', 'category', false, false, 'CIE-11'),
('XH6AF9', 'Neoplasia intraepitelial glandular de grado bajo', 'category', false, false, 'CIE-11'),
('XH3BK2', 'Papiloma glandular', 'category', false, false, 'CIE-11'),
('XH6PG8', 'Adenoma de células de Hurthle', 'category', false, false, 'CIE-11'),
('XH5X53', 'Tumor de células de Hürthle', 'category', false, false, 'CIE-11'),
('XH6M13', 'Tumor yuxtaglomerular', 'category', false, false, 'CIE-11'),
('XH0W31', 'Adenoma de la lactancia', 'category', false, false, 'CIE-11'),
('XH8P28', 'Lipoadenoma', 'category', false, false, 'CIE-11'),
('XH68V1', 'Adenoma de células hepáticas', 'category', false, false, 'CIE-11'),
('XH19E3', 'Adenoma macrofolicular', 'category', false, false, 'CIE-11'),
('XH0JC7', 'Adenoma metanefrico', 'category', false, false, 'CIE-11'),
('XH3DH3', 'Adenoma microquístico', 'category', false, false, 'CIE-11'),
('XH5LD9', 'Adenoma acidófilo-basófilo mixto', 'category', false, false, 'CIE-11'),
('XH0WV8', 'Pólipo hiperplásico y adenomatoso mixto', 'category', false, false, 'CIE-11'),
('XH1XU4', 'Adenoma de células mixtas', 'category', false, false, 'CIE-11'),
('XH2CQ8', 'Adenoma monomórfico', 'category', false, false, 'CIE-11'),
('XH6CZ4', 'Pólipos adenomatosos múltiples', 'category', false, false, 'CIE-11'),
('XH9Z86', 'Adenoma oxifílico', 'category', false, false, 'CIE-11'),
('XH0BF2', 'Neoplasia pancreatobiliar, no invasiva', 'category', false, false, 'CIE-11'),
('XH6GG6', 'Microadenoma pancreatico', 'category', false, false, 'CIE-11'),
('XH1BH4', 'Papilomatosis, glandular', 'category', false, false, 'CIE-11'),
('XH6EJ4', 'Adenoma papilotubular', 'category', false, false, 'CIE-11'),
('XH1QS0', 'Adenoma lactotrofo', 'category', false, false, 'CIE-11'),
('XH5903', 'Adenoma serrado', 'category', false, false, 'CIE-11'),
('XH9G87', 'Adenoma trabecular', 'category', false, false, 'CIE-11'),
('XH8T50', 'Tumor de Turban', 'category', false, false, 'CIE-11'),
('XH0731', 'Papiloma velloso', 'category', false, false, 'CIE-11'),
('XH8UC1', 'Adenoma de células en aguas claras', 'category', false, false, 'CIE-11'),
('XH28X1', 'Cilindroma de mama', 'category', false, false, 'CIE-11'),
('XH8MU5', 'Pólipo adenomatoso,SAI', 'category', false, false, 'CIE-11'),
('XH7SY6', 'Adenoma tubular, SAI', 'category', false, false, 'CIE-11'),
('XH2F06', 'Adenoma serrado sésil', 'category', false, false, 'CIE-11'),
('XH63V9', 'Pólipo serrado sésil', 'category', false, false, 'CIE-11'),
('XH9PD9', 'Adenoma serrado sésil tradicional', 'category', false, false, 'CIE-11'),
('XH5QL3', 'Hiperplasia adenomatosa atípica', 'category', false, false, 'CIE-11'),
('XH09B0', 'Adenoma papilar, SAI', 'category', false, false, 'CIE-11'),
('XH90D6', 'Adenoma velloso, SAI', 'category', false, false, 'CIE-11'),
('XH10B0', 'Adenoma tubulovelloso, SAI', 'category', false, false, 'CIE-11'),
('XH94U0', 'Adenoma pituitario, SAI', 'category', false, false, 'CIE-11'),
('XH26P7', 'Oncocitoma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH52F6', 'Adenoma cortical adrenal, SAI', 'category', false, false, 'CIE-11'),
('XH6ZD0', 'Adenoma endometroide, SAI', 'category', false, false, 'CIE-11'),
('XH1CX5', 'Adenofibroma endometroide, SAI', 'category', false, false, 'CIE-11'),
('XH2H83', 'Adenoma microfolicular, SAI', 'category', false, false, 'CIE-11'),
('XH7DU3', 'Adenoma tipo intestinal', 'category', false, false, 'CIE-11'),
('XH1Q16', 'Microadenoma neuroendocrino pancreático', 'category', false, false, 'CIE-11'),
('XH8NK5', 'Cistadenoma papilar oncocítico', 'category', false, false, 'CIE-11'),
('XH8Y40', 'Adenoma de células nulas', 'category', false, false, 'CIE-11'),
('XH1JL3', 'Adenoma plurihormonal', 'category', false, false, 'CIE-11'),
('XH50K4', 'Adenoma gonadotropo', 'category', false, false, 'CIE-11'),
('XH4HE3', 'Adenoma somatótrofo', 'category', false, false, 'CIE-11'),
('XH0MY4', 'Adenoma tirótrofo', 'category', false, false, 'CIE-11'),
('XH5RH2', 'Adenoma hipofisario ectópico', 'category', false, false, 'CIE-11'),
('XH1C58', 'Adenoma corticotropo', 'category', false, false, 'CIE-11'),
('XH7743', 'Adenoma bronquiolar / Tumor papilar muconodular ciliado', 'category', false, false, 'CIE-11'),
('XH2L30', 'Adenocarcinoma in situ, SAI', 'category', false, false, 'CIE-11'),
('XH4J07', 'Adenocarcinoma in situ en pólipo adenomatoso', 'category', false, false, 'CIE-11'),
('XH3770', 'Adenocarcinoma in situ en adenoma tubovelloso', 'category', false, false, 'CIE-11'),
('XH8TV2', 'Adenocarcinoma in situ en adenoma velloso', 'category', false, false, 'CIE-11'),
('XH5U91', 'Neoplasia intraepiteliai biliar, de alto grado', 'category', false, false, 'CIE-11'),
('XH7Y32', 'Carcinoma cribiforme in situ', 'category', false, false, 'CIE-11'),
('XH0557', 'Carcinoma ductal in situ, tipo sólido', 'category', false, false, 'CIE-11'),
('XH36M5', 'Displasia glandular esofágica (neoplasia intraepitelial) de alto grado', 'category', false, false, 'CIE-11'),
('XH5161', 'Neoplasia glandular intraepitelial plano, de alto grado', 'category', false, false, 'CIE-11'),
('XH28N7', 'Neoplasia intraepitelial glandular, de alto grado', 'category', false, false, 'CIE-11'),
('XH26M2', 'Neoplasia papilar, tipo pancreatobiliar, conneoplasia intraepitelial de alto grado', 'category', false, false, 'CIE-11'),
('XH5C49', 'Neoplasia intraepitelial prostática, grado III', 'category', false, false, 'CIE-11'),
('XH1FR9', 'Adenocarcinoma in situ de pulmón, no mucinoso', 'category', false, false, 'CIE-11'),
('XH6BU6', 'Adenocarcinoma in situ de pulmón mucinoso', 'category', false, false, 'CIE-11'),
('XH4Z68', 'Neoplasia intraepitelial endometroide', 'category', false, false, 'CIE-11'),
('XH2QZ6', 'Carcinoma acidófilo', 'category', false, false, 'CIE-11'),
('XH5LA4', 'Tumor adenocarcinoide', 'category', false, false, 'CIE-11'),
('XH74S1', 'Adenocarcinoma, SAI', 'category', false, false, 'CIE-11'),
('XH7QZ0', 'Adenocarcinoma en pólipo adenomatoso', 'category', false, false, 'CIE-11'),
('XH2ZH8', 'Adenocarcinoma en poliposis adenomatosa coli', 'category', false, false, 'CIE-11'),
('XH9YR3', 'Adenocarcinoma en múltiples pólipos adenomatosos', 'category', false, false, 'CIE-11'),
('XH7QB1', 'Adenocarcinoma en adenoma túbulovelloso', 'category', false, false, 'CIE-11'),
('XH6DA5', 'Adenocarcinoma en adenoma velloso', 'category', false, false, 'CIE-11'),
('XH5RE1', 'Adenocarcinoma de las glándulas anales', 'category', false, false, 'CIE-11'),
('XH2ZQ0', 'Adenocarcinoma con subtipos mixtos', 'category', false, false, 'CIE-11'),
('XH0349', 'Adenocarcinoma, tipo intestinal', 'category', false, false, 'CIE-11'),
('XH8B45', 'Carcinoma sólido, SAI', 'category', false, false, 'CIE-11'),
('XH8DS0', 'Tumor neuroendocrino, SAI', 'category', false, false, 'CIE-11'),
('XH8LX8', 'Carcinoma neuroendocrino, de bajo grado', 'category', false, false, 'CIE-11'),
('XH55D7', 'Carcinoma neuroendócrino, bien diferenciado', 'category', false, false, 'CIE-11'),
('XH9LV8', 'Tumor neuroendocrino, grado 1', 'category', false, false, 'CIE-11'),
('XH7NM1', 'Carcinoides de células enterocromafines', 'category', false, false, 'CIE-11'),
('XH0U20', 'Carcinoma neuroendócrino, SAI', 'category', false, false, 'CIE-11'),
('XH7F73', 'Carcinoma neuroendócrino, moderadamente diferenciado', 'category', false, false, 'CIE-11'),
('XH24W2', 'Adenocarcinoma lepídico', 'category', false, false, 'CIE-11'),
('XH3QM0', 'Adenocarcinoma mínimamente invasivo, No mucinoso', 'category', false, false, 'CIE-11'),
('XH4302', 'Carcinoma quístico adenoide', 'category', false, false, 'CIE-11'),
('XH2098', 'Adenocarcinoma mínimamente invasivo, Mucinoso', 'category', false, false, 'CIE-11'),
('XH6LV9', 'Adenocarcinoma papilar, SAI', 'category', false, false, 'CIE-11'),
('XH95U1', 'Carcinoma villoglandular', 'category', false, false, 'CIE-11'),
('XH6QG3', 'Carcinoma micropapilar, SAI', 'category', false, false, 'CIE-11'),
('XH4MW7', 'Adenocarcinoma micropapilar', 'category', false, false, 'CIE-11'),
('XH7KL6', 'Carcinoma hipofisatio, SAI', 'category', false, false, 'CIE-11'),
('XH6L02', 'Adenocarcinoma de células claras, SAI', 'category', false, false, 'CIE-11'),
('XH5085', 'Leiomiomatosis hereditaria y carcinoma de células renales (LHCCR) síndrome asociado con carcinoma de células renales', 'category', false, false, 'CIE-11'),
('XH1442', 'Carcinomas de traslocación familiar MiT', 'category', false, false, 'CIE-11'),
('XH8EN1', 'Carcinoma de células renales deficiente en succinato deshidrogenasa', 'category', false, false, 'CIE-11'),
('XH07X3', 'Adenocarcinoma alveolar', 'category', false, false, 'CIE-11'),
('XH05V6', 'Carcinoma de células renales, SAI', 'category', false, false, 'CIE-11'),
('XH3Z08', 'Carcinoma de células renales, sin clasificar', 'category', false, false, 'CIE-11'),
('XH0RU3', 'Carcinoma de células renales asociada a enfermedad quística adquirida', 'category', false, false, 'CIE-11'),
('XH7K79', 'Carcinoma de células renales tubuloquística', 'category', false, false, 'CIE-11'),
('XH1VB1', 'Tumor cromófobo oncocítico híbrido', 'category', false, false, 'CIE-11'),
('XH3Z50', 'Carcinoma folicular, SAI', 'category', false, false, 'CIE-11'),
('XH9508', 'Adenocarcinoma endometrioide, variante de células ciliadas', 'category', false, false, 'CIE-11'),
('XH0718', 'Adenocarcinoma endometrioide, variante secretoria', 'category', false, false, 'CIE-11'),
('XH4KH2', 'Carcinoma cortical adrenal', 'category', false, false, 'CIE-11'),
('XH0SD2', 'Adenocarcinoma endometrioide, SAI', 'category', false, false, 'CIE-11'),
('XH51K1', 'Tumor neuroendocrino, grado 2', 'category', false, false, 'CIE-11'),
('XH09B7', 'Cistoadenocarcinoma endometrioide', 'category', false, false, 'CIE-11'),
('XH6KR7', 'Adenofibroma endometrioide, maligno', 'category', false, false, 'CIE-11'),
('XH0GS9', 'Adenocarcinoma, tipo endocervical', 'category', false, false, 'CIE-11'),
('XH8SF8', 'Adenomatosis de células de los islotes', 'category', false, false, 'CIE-11'),
('XH43E4', 'Colangiocarcinoma perihiliar', 'category', false, false, 'CIE-11'),
('XH4BY1', 'Adenoma de células del islote', 'category', false, false, 'CIE-11'),
('XH3CU4', 'Variante villoglandular del adenocarcinoma endometrioide', 'category', false, false, 'CIE-11'),
('XH5QV8', 'Blastoma pituitario', 'category', false, false, 'CIE-11'),
('XH0Y80', 'Carcinoma folicular, encapsulado, angioinvasivo', 'category', false, false, 'CIE-11'),
('XH46F1', 'Carcinoma renal de células claras, SAI', 'category', false, false, 'CIE-11'),
('XH9SA7', 'Adenocarcinoma de células basales', 'category', false, false, 'CIE-11'),
('XH85C2', 'Tumor del saco endolinfático', 'category', false, false, 'CIE-11'),
('XH4PB1', 'Adenocarcinoma acinar de próstata', 'category', false, false, 'CIE-11'),
('XH8E54', 'Neoplasia mixta neuroendocrina no neuroendocrina (MMiNEN)', 'category', false, false, 'CIE-11'),
('XH5QW8', 'Tumor neuroendocrino, grado 3', 'category', false, false, 'CIE-11'),
('XH1NL5', 'Nesidioblastoma', 'category', false, false, 'CIE-11'),
('XH5XB7', 'Carcinoma de células de los islotes', 'category', false, false, 'CIE-11'),
('XH2ST7', 'Tumor de células de los islotes, SAI', 'category', false, false, 'CIE-11'),
('XH4SH8', 'Insulinoma, SAI', 'category', false, false, 'CIE-11'),
('XH93H8', 'Gastrinoma', 'category', false, false, 'CIE-11'),
('XH7JQ0', 'Carcinoma de paratiroides', 'category', false, false, 'CIE-11'),
('XH9LV7', 'Carcinoma basófilo', 'category', false, false, 'CIE-11'),
('XH7152', 'Tumor productor de péptido similar al glucagón', 'category', false, false, 'CIE-11'),
('XH7LW9', 'Tumor de células -L', 'category', false, false, 'CIE-11'),
('XH9ZS8', 'Péptido pancreático y péptido similar al péptido pancreático dentro del tumor productor de tirosina amida terminal', 'category', false, false, 'CIE-11'),
('XH4NQ8', 'Glucagonoma', 'category', false, false, 'CIE-11'),
('XH2PF0', 'Enteroglucagonoma', 'category', false, false, 'CIE-11'),
('XH72E5', 'Vipoma', 'category', false, false, 'CIE-11'),
('XH5VH0', 'Somatostatinoma', 'category', false, false, 'CIE-11'),
('XH41P2', 'Tumor endocrino funcionante, SAI', 'category', false, false, 'CIE-11'),
('XH7AG8', 'Tumor productor de ACTH [hormona adrenocorticotrópica]', 'category', false, false, 'CIE-11'),
('XH60V1', 'Carcinoma medular de tiroides', 'category', false, false, 'CIE-11'),
('XH3BU6', 'Cistoadenocarcinoma del conducto biliar', 'category', false, false, 'CIE-11'),
('XH2MW1', 'Carcinoma medular con estroma amiloide', 'category', false, false, 'CIE-11'),
('XH8VU6', 'Carcinoma de tiroides pobremente diferenciado', 'category', false, false, 'CIE-11'),
('XH4NH4', 'Tumor neuroendocrino hipofisario', 'category', false, false, 'CIE-11'),
('XH2ZA2', 'Adenoma bronquial, carcinoide', 'category', false, false, 'CIE-11'),
('XH5TR7', 'Carcinoma de pulmón, mixto mucinoso y no- mucinoso', 'category', false, false, 'CIE-11'),
('XH7GY6', 'Adenocarcinoma de pulmón, mucinoso', 'category', false, false, 'CIE-11'),
('XH2035', 'Carcinoma bronquiolo-alveolar, no mucinoso', 'category', false, false, 'CIE-11'),
('XH6LF9', 'Carcinoma simple', 'category', false, false, 'CIE-11'),
('XH0XL5', 'Carcinoma, de tipo difuso', 'category', false, false, 'CIE-11'),
('XH7M15', 'Colangiocarcinoma', 'category', false, false, 'CIE-11'),
('XH7SS7', 'Carcinoma cromófobo', 'category', false, false, 'CIE-11'),
('XH2Q13', 'Adenocarcinofibroma de células claras', 'category', false, false, 'CIE-11'),
('XH6YS0', 'Adenocarcinoma de células claras, mesonefroide', 'category', false, false, 'CIE-11'),
('XH4SQ4', 'Carcinoma del ducto colector', 'category', false, false, 'CIE-11'),
('XH7QJ6', 'Carcinoma hepatocelular y colangiocarcinoma combinado', 'category', false, false, 'CIE-11'),
('XH4KK0', 'Quistes asociados con carcinoma de células renales', 'category', false, false, 'CIE-11'),
('XH0LH8', 'Tumor de células similares a enterocromafines', 'category', false, false, 'CIE-11'),
('XH5P16', 'Adenocarcinoma fetal', 'category', false, false, 'CIE-11'),
('XH7TE3', 'Adenocarcinoma folicular, moderadamente diferenciado', 'category', false, false, 'CIE-11'),
('XH0VD1', 'Adenocarcinoma folicular, trabecular', 'category', false, false, 'CIE-11'),
('XH8FK7', 'Adenocarcinoma folicular, bien diferenciado', 'category', false, false, 'CIE-11'),
('XH3DN7', 'Carcinoma folicular, mínimamente invasivo', 'category', false, false, 'CIE-11'),
('XH90N9', 'Carcinoma folicular, de células oxifílicas', 'category', false, false, 'CIE-11'),
('XH3XT5', 'Carcinoma rico en glicógeno', 'category', false, false, 'CIE-11'),
('XH4262', 'Tumor carcinoide de células caliciformes', 'category', false, false, 'CIE-11'),
('XH2EH4', 'Carcinoma de células granulares', 'category', false, false, 'CIE-11'),
('XH4T58', 'Carcinoma hepatocelular, tipo células claras', 'category', false, false, 'CIE-11'),
('XH9Q35', 'Carcinoma hepatocelular, fibrolamelar', 'category', false, false, 'CIE-11'),
('XH0G90', 'Hepatocellular carcinoma, tipo pleomórfico', 'category', false, false, 'CIE-11'),
('XH5761', 'Carcinoma hepatocelular, escirroso', 'category', false, false, 'CIE-11'),
('XH3T17', 'Carcinoma hepatocelular, variante de células fusiformes', 'category', false, false, 'CIE-11'),
('XH6YH5', 'Adenocarcinoma de células de Hürthle', 'category', false, false, 'CIE-11'),
('XH8MQ3', 'Carcinoma de células Hürthle', 'category', false, false, 'CIE-11'),
('XH8WM4', 'Linitis plástica', 'category', false, false, 'CIE-11'),
('XH6TK0', 'Carcinoma rico en lípidos', 'category', false, false, 'CIE-11'),
('XH81N8', 'Carcinoma de las células de Merkel', 'category', false, false, 'CIE-11'),
('XH7019', 'Carcinoma acidófilo-basófilo mixto', 'category', false, false, 'CIE-11'),
('XH8EZ3', 'Carcinoma mixto acinar-endocrino', 'category', false, false, 'CIE-11'),
('XH74Y9', 'Carcinoma acinar-endocrino-ductal mixto', 'category', false, false, 'CIE-11'),
('XH6H10', 'Carcinoma adenoneuroendocrino mixto', 'category', false, false, 'CIE-11'),
('XH2AM6', 'Adenocarcinoma de células mixtas', 'category', false, false, 'CIE-11'),
('XH7CY5', 'Carcinoma mixto ductal-endocrino', 'category', false, false, 'CIE-11'),
('XH6UP4', 'Adenocarcinoma exocrino y endocrino mixto', 'category', false, false, 'CIE-11'),
('XH7DG7', 'Carcinoma medular-folicular mixto', 'category', false, false, 'CIE-11'),
('XH3340', 'Carcinoma medular-papilar mixto', 'category', false, false, 'CIE-11'),
('XH9LZ7', 'Tumor mixto exocrino y endocrino pancreático , maligno', 'category', false, false, 'CIE-11'),
('XH1108', 'Carcinoma esclerosante no encapsulado', 'category', false, false, 'CIE-11'),
('XH09D6', 'Adenocarcinoma oxifílico', 'category', false, false, 'CIE-11'),
('XH3614', 'Adenocarcinoma de células de los islotes (Langerhans)', 'category', false, false, 'CIE-11'),
('XH3709', 'Tumor neuroendocrino pancreático, no funcional', 'category', false, false, 'CIE-11'),
('XH6XY9', 'Carcinoma tipo- pancreatobiliar', 'category', false, false, 'CIE-11'),
('XH1ND9', 'Carcinoma papilar de tiroides', 'category', false, false, 'CIE-11'),
('XH85E5', 'Carcinoma papilar, de células columnares', 'category', false, false, 'CIE-11'),
('XH0426', 'Carcinoma papilar, esclerosante difuso', 'category', false, false, 'CIE-11'),
('XH0Q59', 'Carcinoma papilar, encapsulado de tiroides', 'category', false, false, 'CIE-11'),
('XH29M4', 'Carcinoma papilar, variante folicular', 'category', false, false, 'CIE-11'),
('XH5YT2', 'Carcinoma papilar, variante oncocítico', 'category', false, false, 'CIE-11'),
('XH2AW7', 'Microcarcinoma papilar', 'category', false, false, 'CIE-11'),
('XH1D07', 'Carcinoma de células renales papilares', 'category', false, false, 'CIE-11'),
('XH4Q20', 'Adenocarcinoma papilar tubular', 'category', false, false, 'CIE-11'),
('XH1JZ0', 'Carcinoma de células parietales', 'category', false, false, 'CIE-11'),
('XH6153', 'Carcinoma de células renales, de tipo cromófobo', 'category', false, false, 'CIE-11'),
('XH9DH7', 'Carcinoma de células renales, sarcomatoides', 'category', false, false, 'CIE-11'),
('XH4FS4', 'Adenocarcinoma escirroso', 'category', false, false, 'CIE-11'),
('XH34G3', 'Carcinoma sólido con formación de mucina', 'category', false, false, 'CIE-11'),
('XH0JE3', 'Adenocarcinoma de extensión superficial', 'category', false, false, 'CIE-11'),
('XH7EX3', 'Adenocarcinoma trabecular', 'category', false, false, 'CIE-11'),
('XH4TA4', 'Adenocarcinoma tubular', 'category', false, false, 'CIE-11'),
('XH1Z69', 'Carcinoide típico', 'category', false, false, 'CIE-11'),
('XH22Z8', 'Carcinoma de glándulas de Skene, de Cowper y de Littre', 'category', false, false, 'CIE-11'),
('XH0X20', 'Adenocarcinoma velloso', 'category', false, false, 'CIE-11'),
('XH0A57', 'Adenocarcinoma de células claras del agua', 'category', false, false, 'CIE-11'),
('XH8UE4', 'Adenocarcinoma, metastático, SAI', 'category', false, false, 'CIE-11'),
('XH4ZC3', 'Carcinoma de células basales de la próstata', 'category', false, false, 'CIE-11'),
('XH4W48', 'Carcinoma hepatocelular, SAI', 'category', false, false, 'CIE-11'),
('XH81Q9', 'Adenoma bronquial, cilindroide', 'category', false, false, 'CIE-11'),
('XH92Y9', 'Carcinoma tímico con características de carcinoma adenoide quístico', 'category', false, false, 'CIE-11'),
('XH1YZ3', 'Carcinoma cribiforme, SAI', 'category', false, false, 'CIE-11'),
('XH4YG1', 'Carcinoma tipo comedo-cribiforme', 'category', false, false, 'CIE-11'),
('XH74B2', 'Adenocarcinoma serrado', 'category', false, false, 'CIE-11'),
('XH6770', 'Apudoma', 'category', false, false, 'CIE-11'),
('XH6VL9', 'Adenoma atípico', 'category', false, false, 'CIE-11'),
('XH3T38', 'Adenoma folicular atípico', 'category', false, false, 'CIE-11'),
('XH0S86', 'Adenofibroma de células claras de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH5DQ2', 'Adenoma endometroide, de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH76W6', 'Adenomas endocrinos múltiples', 'category', false, false, 'CIE-11'),
('XH8468', 'Adenomatosis pulmonar', 'category', false, false, 'CIE-11'),
('XH54H3', 'Tumor hipernefroide', 'category', false, false, 'CIE-11'),
('XH7PR9', 'Neoplasia renal quística multilocular de bajo potencial de malignidad', 'category', false, false, 'CIE-11'),
('XH9DS4', 'Adenofibroma endometrioide, de malignidad borderline', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
