-- CIE11 Import Part 64
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XM6A32', 'Tartrato de antimonio (anti infeccioso)', 'category', false, false, 'CIE-11'),
('XM9KU4', 'Tiobismol', 'category', false, false, 'CIE-11'),
('XM9UP9', 'Tiocarbarsona', 'category', false, false, 'CIE-11'),
('XM5VM3', 'Tin anti-infecciosos', 'category', false, false, 'CIE-11'),
('XM2SB0', 'Antiinfeccioso urinario', 'category', false, false, 'CIE-11'),
('XM2HD6', 'Emetina', 'category', false, false, 'CIE-11'),
('XM5GF4', 'Fanquinona', 'category', false, false, 'CIE-11'),
('XM9VB9', 'Mepacrina', 'category', false, false, 'CIE-11'),
('XM5RX3', 'Tenonitrozol', 'category', false, false, 'CIE-11'),
('XM28N6', 'Dehidroemetina', 'category', false, false, 'CIE-11'),
('XM5WJ8', 'Fumagilina', 'category', false, false, 'CIE-11'),
('XM84S6', 'Nitazoxanida', 'category', false, false, 'CIE-11'),
('XM9JL2', 'Eflornitina', 'category', false, false, 'CIE-11'),
('XM2NT3', 'Alantolactona', 'category', false, false, 'CIE-11'),
('XM1PP4', 'Anfotalida', 'category', false, false, 'CIE-11'),
('XM8LU8', 'Antiolimina', 'category', false, false, 'CIE-11'),
('XM95R7', 'Antihelmíntico antiinfeccioso', 'category', false, false, 'CIE-11'),
('XM43K9', 'Medicamento antifilaria', 'category', false, false, 'CIE-11'),
('XM4EC0', 'Antihelmínticos', 'category', false, false, 'CIE-11'),
('XM9637', 'Medicamento anti anquilostoma', 'category', false, false, 'CIE-11'),
('XM16G5', 'Medicamento anti nematodes', 'category', false, false, 'CIE-11'),
('XM2078', 'Medicamento anti platelmintos', 'category', false, false, 'CIE-11'),
('XM60W7', 'Medicamento anti esquistosomas', 'category', false, false, 'CIE-11'),
('XM6500', 'Medicamento anti tenias', 'category', false, false, 'CIE-11'),
('XM5273', 'Medicamento anti gusanos látigo', 'category', false, false, 'CIE-11'),
('XM7QL4', 'Ascaridol', 'category', false, false, 'CIE-11'),
('XM9GK4', 'Aspidio (oleorresina)', 'category', false, false, 'CIE-11'),
('XM3JR4', 'Derivados de bencimidazol', 'category', false, false, 'CIE-11'),
('XM3GX0', 'Mebendazol', 'category', false, false, 'CIE-11'),
('XM0CU8', 'Tiabendazol', 'category', false, false, 'CIE-11'),
('XM79J1', 'Albendazol', 'category', false, false, 'CIE-11'),
('XM8RG6', 'Flubendazol', 'category', false, false, 'CIE-11'),
('XM5XC2', 'Fenbendazol', 'category', false, false, 'CIE-11'),
('XM7982', 'Ciclobendazol', 'category', false, false, 'CIE-11'),
('XM3667', 'Befenio', 'category', false, false, 'CIE-11'),
('XM6FY4', 'Bitionol antihelmíntico', 'category', false, false, 'CIE-11'),
('XM5L27', 'Bitoscanato', 'category', false, false, 'CIE-11'),
('XM4WY5', 'Chenopodium', 'category', false, false, 'CIE-11'),
('XM0ZD3', 'Diclorofeno', 'category', false, false, 'CIE-11'),
('XM8C12', 'Yoduro de ditiazanina', 'category', false, false, 'CIE-11'),
('XM2RX7', 'Filix mas', 'category', false, false, 'CIE-11'),
('XM05F2', 'Ivermectina', 'category', false, false, 'CIE-11'),
('XM5W42', 'Levamisol', 'category', false, false, 'CIE-11'),
('XM9Z70', 'Lucantona', 'category', false, false, 'CIE-11'),
('XM4SZ4', 'Extracto de helecho macho', 'category', false, false, 'CIE-11'),
('XM2034', 'Niclosamida', 'category', false, false, 'CIE-11'),
('XM2WY0', 'Niridazol', 'category', false, false, 'CIE-11'),
('XM7NR1', 'Nitrotiazol', 'category', false, false, 'CIE-11'),
('XM5JZ6', 'Oxamniquina', 'category', false, false, 'CIE-11'),
('XM9FH0', 'Tanato de peletierina', 'category', false, false, 'CIE-11'),
('XM5ZH0', 'Percloroetileno medicinal', 'category', false, false, 'CIE-11'),
('XM3T27', 'Pink root', 'category', false, false, 'CIE-11'),
('XM8205', 'Pracicuantel', 'category', false, false, 'CIE-11'),
('XM7SZ5', 'Extracto de semilla de calabaza', 'category', false, false, 'CIE-11'),
('XM5PX0', 'Pirvinio', 'category', false, false, 'CIE-11'),
('XM9KL1', 'Santonina', 'category', false, false, 'CIE-11'),
('XM3FE9', 'Spigelia (raíz)', 'category', false, false, 'CIE-11'),
('XM5VV1', 'Estibofeno', 'category', false, false, 'CIE-11'),
('XM4GA8', 'Teroxaleno', 'category', false, false, 'CIE-11'),
('XM7PN4', 'Tetracloroetileno medicinal', 'category', false, false, 'CIE-11'),
('XM93X2', 'Tetramisol', 'category', false, false, 'CIE-11'),
('XM2621', 'Estibamina de urea', 'category', false, false, 'CIE-11'),
('XM5C18', 'Veroxil', 'category', false, false, 'CIE-11'),
('XM3AT4', 'Viprinio', 'category', false, false, 'CIE-11'),
('XM4555', 'Epazote, americana', 'category', false, false, 'CIE-11'),
('XM6U56', 'Derivados de tetrahidropirimidina', 'category', false, false, 'CIE-11'),
('XM90N4', 'Pirantel', 'category', false, false, 'CIE-11'),
('XM05V2', 'Oxantel', 'category', false, false, 'CIE-11'),
('XM9H59', 'Metrifonato', 'category', false, false, 'CIE-11'),
('XM7VW8', 'Triclabendazol', 'category', false, false, 'CIE-11'),
('XM7F99', 'Moxidectina', 'category', false, false, 'CIE-11'),
('XM0399', 'Desaspidina', 'category', false, false, 'CIE-11'),
('XM9DZ4', 'Tetrabenacina', 'category', false, false, 'CIE-11'),
('XM3BR4', 'Memantina', 'category', false, false, 'CIE-11'),
('XM1CG4', 'Hoja de Ginkgo', 'category', false, false, 'CIE-11'),
('XM9VG8', 'Tirilazad', 'category', false, false, 'CIE-11'),
('XM9Z74', 'Riluzol', 'category', false, false, 'CIE-11'),
('XM4ER7', 'Xaliproden', 'category', false, false, 'CIE-11'),
('XM5PS1', 'Fampridina', 'category', false, false, 'CIE-11'),
('XM2AL2', 'Tafamidis', 'category', false, false, 'CIE-11'),
('XM1LU9', 'Laquinimod', 'category', false, false, 'CIE-11'),
('XM3QR7', 'Pitolisant', 'category', false, false, 'CIE-11'),
('XM3FT2', 'Patisiran', 'category', false, false, 'CIE-11'),
('XM1KZ8', 'Edaravone', 'category', false, false, 'CIE-11'),
('XM7DT3', 'Inotersen', 'category', false, false, 'CIE-11'),
('XM8MX8', 'Valbenazina', 'category', false, false, 'CIE-11'),
('XM87M0', 'Aducanumab', 'category', false, false, 'CIE-11'),
('XM5UK9', 'Deutetrabenazina', 'category', false, false, 'CIE-11'),
('XM4F26', 'Arimoclomol', 'category', false, false, 'CIE-11'),
('XM4KS4', 'Agentes antiinflamatorios y antirreumáticos no esteroides', 'category', false, false, 'CIE-11'),
('XM7W23', 'Butilpirazolidinas', 'category', false, false, 'CIE-11'),
('XM8HN0', 'Fenilbutazona', 'category', false, false, 'CIE-11'),
('XM8P27', 'Mofebutazonea', 'category', false, false, 'CIE-11'),
('XM12M5', 'Oxifenbutazona', 'category', false, false, 'CIE-11'),
('XM8X86', 'Clofezona', 'category', false, false, 'CIE-11'),
('XM4H41', 'Kebuzona', 'category', false, false, 'CIE-11'),
('XM74U4', 'Derivados del ácido acético y sustancias afines', 'category', false, false, 'CIE-11'),
('XM7497', 'Indometacina', 'category', false, false, 'CIE-11'),
('XM24W2', 'Sulindac', 'category', false, false, 'CIE-11'),
('XM97N5', 'Tolmetina', 'category', false, false, 'CIE-11'),
('XM92G8', 'Zomepirac', 'category', false, false, 'CIE-11'),
('XM2AU1', 'Diclofenac', 'category', false, false, 'CIE-11'),
('XM2186', 'Etodolac', 'category', false, false, 'CIE-11'),
('XM8M52', 'Ketorolac', 'category', false, false, 'CIE-11'),
('XM6KJ8', 'Bumadizona', 'category', false, false, 'CIE-11'),
('XM12Q6', 'Lonazolac', 'category', false, false, 'CIE-11'),
('XM2AX1', 'Fentiazaco', 'category', false, false, 'CIE-11'),
('XM3458', 'Acemetacina', 'category', false, false, 'CIE-11'),
('XM7K80', 'Difenpiramida', 'category', false, false, 'CIE-11'),
('XM7CA3', 'Oxametacina', 'category', false, false, 'CIE-11'),
('XM2P51', 'Proglumetacina', 'category', false, false, 'CIE-11'),
('XM5W40', 'Aceclofenaco', 'category', false, false, 'CIE-11'),
('XM7AB1', 'Bufexamac', 'category', false, false, 'CIE-11'),
('XM9S89', 'Alclofenaco', 'category', false, false, 'CIE-11'),
('XM8G95', 'Ibufenac', 'category', false, false, 'CIE-11'),
('XM0UL8', 'Oxicams', 'category', false, false, 'CIE-11'),
('XM9MD6', 'Piroxican', 'category', false, false, 'CIE-11'),
('XM7WP9', 'Droxicam', 'category', false, false, 'CIE-11'),
('XM3X14', 'Lornoxicam', 'category', false, false, 'CIE-11'),
('XM1XY0', 'Meloxicam', 'category', false, false, 'CIE-11'),
('XM83U4', 'Isoxicam', 'category', false, false, 'CIE-11'),
('XM1867', 'Tenoxicam', 'category', false, false, 'CIE-11'),
('XM2S54', 'Derivados del ácido propiónico', 'category', false, false, 'CIE-11'),
('XM2RR6', 'Ibuprofeno', 'category', false, false, 'CIE-11'),
('XM1KL8', 'Naproxeno', 'category', false, false, 'CIE-11'),
('XM63J5', 'Ketoprofeno', 'category', false, false, 'CIE-11'),
('XM7BS7', 'Fenoprofeno', 'category', false, false, 'CIE-11'),
('XM2N63', 'Suprofeno', 'category', false, false, 'CIE-11'),
('XM8VP8', 'Flurbiprofeno', 'category', false, false, 'CIE-11'),
('XM0WQ1', 'Ácido tiaprofénico', 'category', false, false, 'CIE-11'),
('XM9694', 'Oxaprozina', 'category', false, false, 'CIE-11'),
('XM1918', 'Ibuproxam', 'category', false, false, 'CIE-11'),
('XM4W51', 'Fenbufeno', 'category', false, false, 'CIE-11'),
('XM7F06', 'Benoxaprofeno', 'category', false, false, 'CIE-11'),
('XM4KX7', 'Pirprofeno', 'category', false, false, 'CIE-11'),
('XM3G14', 'Indoprofeno', 'category', false, false, 'CIE-11'),
('XM32V2', 'Dexibuprofeno', 'category', false, false, 'CIE-11'),
('XM4FK3', 'Flunoxaprofeno', 'category', false, false, 'CIE-11'),
('XM1W06', 'Alminoprofeno', 'category', false, false, 'CIE-11'),
('XM1ZF2', 'Dexketoprofeno', 'category', false, false, 'CIE-11'),
('XM9ES5', 'Naproxcinod', 'category', false, false, 'CIE-11'),
('XM8GM3', 'Carprofeno', 'category', false, false, 'CIE-11'),
('XM9DC7', 'Fenamatos', 'category', false, false, 'CIE-11'),
('XM6Q83', 'Ácido mefenámico', 'category', false, false, 'CIE-11'),
('XM31G8', 'Ácido flufenámico', 'category', false, false, 'CIE-11'),
('XM3W40', 'Ácido meclofenámico', 'category', false, false, 'CIE-11'),
('XM9WQ9', 'Ácido tolfenámico', 'category', false, false, 'CIE-11'),
('XM16D6', 'Coxibs', 'category', false, false, 'CIE-11'),
('XM63D2', 'Celecoxib', 'category', false, false, 'CIE-11'),
('XM70K9', 'Rofecoxib', 'category', false, false, 'CIE-11'),
('XM4SK9', 'Valdecoxib', 'category', false, false, 'CIE-11'),
('XM96Q4', 'Parecoxib', 'category', false, false, 'CIE-11'),
('XM2W58', 'Etoricoxib', 'category', false, false, 'CIE-11'),
('XM0BC7', 'Lumiracoxib', 'category', false, false, 'CIE-11'),
('XM1N20', 'Polmacoxib', 'category', false, false, 'CIE-11'),
('XM7AM9', 'Glafenina', 'category', false, false, 'CIE-11'),
('XM3WB0', 'Floctafenina', 'category', false, false, 'CIE-11'),
('XM8WS4', 'Nabumetona', 'category', false, false, 'CIE-11'),
('XM6SW5', 'Azapropazona', 'category', false, false, 'CIE-11'),
('XM6SR1', 'Glucosamina', 'category', false, false, 'CIE-11'),
('XM73Q0', 'Benzidamina', 'category', false, false, 'CIE-11'),
('XM8GX7', 'Proquazona', 'category', false, false, 'CIE-11'),
('XM5C49', 'Nimesulida', 'category', false, false, 'CIE-11'),
('XM37T1', 'Feprazona', 'category', false, false, 'CIE-11'),
('XM4KV5', 'Ácido niflúmico', 'category', false, false, 'CIE-11'),
('XM5Z51', 'Polisulfato de glucosaminoglicano', 'category', false, false, 'CIE-11'),
('XM9Z19', 'Orgoteína', 'category', false, false, 'CIE-11'),
('XM51H0', 'Diacereína', 'category', false, false, 'CIE-11'),
('XM1019', 'Morniflumato', 'category', false, false, 'CIE-11'),
('XM7Z95', 'Tenidap', 'category', false, false, 'CIE-11'),
('XM4L54', 'Oxaceprol', 'category', false, false, 'CIE-11'),
('XM9352', 'Sulfato de condroitina', 'category', false, false, 'CIE-11'),
('XM0H27', 'Aguacate y aceite de soya, insaponificables', 'category', false, false, 'CIE-11'),
('XM9C36', 'Etoxazeno', 'category', false, false, 'CIE-11'),
('XM85Z4', 'Fenflumizol', 'category', false, false, 'CIE-11'),
('XM46B3', 'Antirreumático analgésico', 'category', false, false, 'CIE-11'),
('XM8DE1', 'Antiflogístico', 'category', false, false, 'CIE-11'),
('XM95N2', 'Antireumáticos', 'category', false, false, 'CIE-11'),
('XM8526', 'Aurotioglicanida', 'category', false, false, 'CIE-11'),
('XM4XH9', 'Farnesil', 'category', false, false, 'CIE-11'),
('XM4DJ6', 'Aurotiosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM3LE3', 'Preparaciones de oro', 'category', false, false, 'CIE-11'),
('XM9ZC2', 'Aurotiomalato de sodio', 'category', false, false, 'CIE-11'),
('XM5HT1', 'Auranofin', 'category', false, false, 'CIE-11'),
('XM1MX1', 'Aurotioglucosa', 'category', false, false, 'CIE-11'),
('XM28Y9', 'Aurotioprol', 'category', false, false, 'CIE-11'),
('XM8CF5', 'Aurotiosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM0VQ7', 'Bucilamina', 'category', false, false, 'CIE-11'),
('XM5L52', 'Oxicincofeno', 'category', false, false, 'CIE-11'),
('XM1QA0', 'Penicillamina', 'category', false, false, 'CIE-11'),
('XM4G06', 'Acido acetilsalicílico', 'category', false, false, 'CIE-11'),
('XM0XT0', 'Carbaspirina', 'category', false, false, 'CIE-11'),
('XM0GX7', 'Salicilato de colina', 'category', false, false, 'CIE-11'),
('XM72N6', 'Fiorinal', 'category', false, false, 'CIE-11'),
('XM6PW4', 'Salicilato de sodio', 'category', false, false, 'CIE-11'),
('XM4WV7', 'Salicilamida', 'category', false, false, 'CIE-11'),
('XM68K3', 'Salsalato', 'category', false, false, 'CIE-11'),
('XM5UX6', 'Diflunisal', 'category', false, false, 'CIE-11'),
('XM2JA1', 'Aloxiprina', 'category', false, false, 'CIE-11'),
('XM3ZP5', 'Etenzamida', 'category', false, false, 'CIE-11'),
('XM49Y6', 'Salicilato de morfolina', 'category', false, false, 'CIE-11'),
('XM9TC0', 'Dipirocetilo', 'category', false, false, 'CIE-11'),
('XM1UA7', 'Benorilato', 'category', false, false, 'CIE-11'),
('XM2CV1', 'Salicilato de potasio', 'category', false, false, 'CIE-11'),
('XM1DD2', 'Guacetisal', 'category', false, false, 'CIE-11'),
('XM4TV1', 'Carbasalato de calcio', 'category', false, false, 'CIE-11'),
('XM5UF9', 'Salicilato de imidazol', 'category', false, false, 'CIE-11'),
('XM8F16', 'Salicilato de calcio', 'category', false, false, 'CIE-11'),
('XM5X48', 'Salicilato de carbetilo', 'category', false, false, 'CIE-11'),
('XM6M40', 'Salicilato de magnesio', 'category', false, false, 'CIE-11'),
('XM8FA6', 'Tiosalicilato de sodio', 'category', false, false, 'CIE-11'),
('XM7045', 'Aminofenazona', 'category', false, false, 'CIE-11'),
('XM7840', 'Pirosol analgésico', 'category', false, false, 'CIE-11'),
('XM22E9', 'Antipirina', 'category', false, false, 'CIE-11'),
('XM60M2', 'Analgésicos medicinales de alquitrán de hulla', 'category', false, false, 'CIE-11'),
('XM4T98', 'Dipirona', 'category', false, false, 'CIE-11'),
('XM2FJ5', 'Isopropil aminofenazona', 'category', false, false, 'CIE-11'),
('XM8762', 'Miocrisina', 'category', false, false, 'CIE-11'),
('XM4YB4', 'Nifenazona', 'category', false, false, 'CIE-11'),
('XM53Q3', 'Noramidopirina', 'category', false, false, 'CIE-11'),
('XM6GV7', 'Propifenazona', 'category', false, false, 'CIE-11'),
('XM5H28', 'Derivados de la pirazolona', 'category', false, false, 'CIE-11'),
('XM5L33', 'Pirazolona analgesico', 'category', false, false, 'CIE-11'),
('XM0K68', 'Ramifenazona', 'category', false, false, 'CIE-11'),
('XM1SG0', 'Sulfamidopirina', 'category', false, false, 'CIE-11'),
('XM9CV5', 'Suxibuzona', 'category', false, false, 'CIE-11'),
('XM5DJ7', 'Acetaminofeno', 'category', false, false, 'CIE-11'),
('XM75Y5', 'Derivados del para-aminofenol', 'category', false, false, 'CIE-11'),
('XM43A6', 'Fenacetina', 'category', false, false, 'CIE-11'),
('XM7HP8', 'Bucetina', 'category', false, false, 'CIE-11'),
('XM8QF6', 'Propacetamol', 'category', false, false, 'CIE-11'),
('XM24R8', 'Acetaminosalol', 'category', false, false, 'CIE-11'),
('XM45S5', 'Acetanilida', 'category', false, false, 'CIE-11'),
('XM4T97', 'Bromo-seltzer', 'category', false, false, 'CIE-11'),
('XM2XD8', 'Acetilfenilhidrazina', 'category', false, false, 'CIE-11'),
('XM3J63', 'Clonixina', 'category', false, false, 'CIE-11'),
('XM1LX8', 'Cropropamida', 'category', false, false, 'CIE-11'),
('XM0LT4', 'Crotetamida', 'category', false, false, 'CIE-11'),
('XM0M53', 'Ciclopirabital', 'category', false, false, 'CIE-11'),
('XM3YJ4', 'Darvon', 'category', false, false, 'CIE-11'),
('XM7K04', 'Diclonixin', 'category', false, false, 'CIE-11'),
('XM2PY3', 'Doloxen', 'category', false, false, 'CIE-11'),
('XM7SA1', 'Emorfazona', 'category', false, false, 'CIE-11'),
('XM9455', 'Etomida', 'category', false, false, 'CIE-11'),
('XM5YR6', 'Fluradolina', 'category', false, false, 'CIE-11'),
('XM7983', 'Cornejo de Jamaica (corteza)', 'category', false, false, 'CIE-11'),
('XM6233', 'Lefetamina', 'category', false, false, 'CIE-11'),
('XM03M0', 'Metofolina', 'category', false, false, 'CIE-11'),
('XM4WT5', 'Nefopam', 'category', false, false, 'CIE-11'),
('XM8QV3', 'Perisoxal', 'category', false, false, 'CIE-11'),
('XM0D38', 'Fenicarbazida', 'category', false, false, 'CIE-11'),
('XM2DH4', 'Feniramidol', 'category', false, false, 'CIE-11'),
('XM0X95', 'Complejo piroxicam beta- ciclodextrina', 'category', false, false, 'CIE-11'),
('XM63V3', 'Piscidia (eritrina)(corteza)', 'category', false, false, 'CIE-11'),
('XM49C9', 'Pirabital', 'category', false, false, 'CIE-11'),
('XM3WM4', 'Pyridium', 'category', false, false, 'CIE-11'),
('XM4PW4', 'Metilsulfato de rimazolio', 'category', false, false, 'CIE-11'),
('XM3375', 'Tiaramida', 'category', false, false, 'CIE-11'),
('XM9YA8', 'Tinoridina', 'category', false, false, 'CIE-11'),
('XM0794', 'Zactano', 'category', false, false, 'CIE-11'),
('XM3P63', 'Metoxiflurano', 'category', false, false, 'CIE-11'),
('XM6Z00', 'Rimazolium', 'category', false, false, 'CIE-11'),
('XM5WQ7', 'Flupirtina', 'category', false, false, 'CIE-11'),
('XM5XN0', 'Ziconotida', 'category', false, false, 'CIE-11'),
('XM70Q6', 'Tanezumab', 'category', false, false, 'CIE-11'),
('XM6HK1', 'Medicamentos contra la migraña', 'category', false, false, 'CIE-11'),
('XM6FB9', 'Triptanos', 'category', false, false, 'CIE-11'),
('XM9AV2', 'Sumatriptan', 'category', false, false, 'CIE-11'),
('XM8BC6', 'Naratriptán', 'category', false, false, 'CIE-11'),
('XM06P8', 'Zolmitriptán', 'category', false, false, 'CIE-11'),
('XM6W13', 'Rizatriptán', 'category', false, false, 'CIE-11'),
('XM92S7', 'Almotriptán', 'category', false, false, 'CIE-11'),
('XM7YU2', 'Eletriptán', 'category', false, false, 'CIE-11'),
('XM4WN0', 'Frovatriptán', 'category', false, false, 'CIE-11'),
('XM7P17', 'Lasmiditan', 'category', false, false, 'CIE-11'),
('XM81Q8', 'Dimetotiazina', 'category', false, false, 'CIE-11'),
('XM7N03', 'Oxetorona', 'category', false, false, 'CIE-11'),
('XM4WH4', 'Pizotifeno', 'category', false, false, 'CIE-11'),
('XM2G27', 'Iprazocromo', 'category', false, false, 'CIE-11'),
('XM63D6', 'Antiepilépticos', 'category', false, false, 'CIE-11'),
('XM52B4', 'Albutoina', 'category', false, false, 'CIE-11'),
('XM9QF8', 'Ácido amino (difenilhidantoína) valérico', 'category', false, false, 'CIE-11'),
('XM55H4', 'Hidantoína anticonvulsivante', 'category', false, false, 'CIE-11'),
('XM08H9', 'Dilantina', 'category', false, false, 'CIE-11'),
('XM45R0', 'Epanutin', 'category', false, false, 'CIE-11'),
('XM8MV0', 'Etotoina', 'category', false, false, 'CIE-11'),
('XM4A36', 'Mefentoina', 'category', false, false, 'CIE-11'),
('XM02E9', 'Metetoina', 'category', false, false, 'CIE-11'),
('XM0RY4', 'Fenitoína', 'category', false, false, 'CIE-11'),
('XM4DR6', 'Derivados de oxazolidina', 'category', false, false, 'CIE-11'),
('XM7N89', 'Parametadiona', 'category', false, false, 'CIE-11'),
('XM31H5', 'Trimetadiona', 'category', false, false, 'CIE-11'),
('XM9993', 'Etadiona', 'category', false, false, 'CIE-11'),
('XM1535', 'Aloxidona', 'category', false, false, 'CIE-11'),
('XM4521', 'Derivados de ácidos grasos', 'category', false, false, 'CIE-11'),
('XM29Q3', 'Ácido valproico', 'category', false, false, 'CIE-11'),
('XM71X1', 'Valpromida', 'category', false, false, 'CIE-11'),
('XM5G31', 'Vigabatrina', 'category', false, false, 'CIE-11'),
('XM2HC7', 'Progabida', 'category', false, false, 'CIE-11'),
('XM5ZT1', 'Ácido aminobutírico', 'category', false, false, 'CIE-11'),
('XM8HQ0', 'Tiagabina', 'category', false, false, 'CIE-11'),
('XM3C23', 'Derivados de succinimida', 'category', false, false, 'CIE-11'),
('XM1K85', 'Etosuccimida', 'category', false, false, 'CIE-11'),
('XM9E68', 'Fensuximida', 'category', false, false, 'CIE-11'),
('XM2KZ3', 'Mesuximida', 'category', false, false, 'CIE-11'),
('XM6421', 'Morsuximida', 'category', false, false, 'CIE-11'),
('XM9GA9', 'Otros antiepilépticos', 'category', false, false, 'CIE-11'),
('XM1RS9', 'Sultiame', 'category', false, false, 'CIE-11'),
('XM7BQ9', 'Fenacemida', 'category', false, false, 'CIE-11'),
('XM4RJ7', 'Feneturide', 'category', false, false, 'CIE-11'),
('XM6KR2', 'Beclamide', 'category', false, false, 'CIE-11'),
('XM6FN4', 'Lamotrigina', 'category', false, false, 'CIE-11'),
('XM15W2', 'Felbamato', 'category', false, false, 'CIE-11'),
('XM2103', 'Topiramato', 'category', false, false, 'CIE-11'),
('XM0J96', 'Gabapentina', 'category', false, false, 'CIE-11'),
('XM9326', 'Levetiracetam', 'category', false, false, 'CIE-11'),
('XM0SP9', 'Zonisamida', 'category', false, false, 'CIE-11'),
('XM0AK1', 'Pregabalina', 'category', false, false, 'CIE-11'),
('XM34S0', 'Estiripentol', 'category', false, false, 'CIE-11'),
('XM30R8', 'Lacosamida', 'category', false, false, 'CIE-11'),
('XM7PP9', 'Carisbamato', 'category', false, false, 'CIE-11'),
('XM1P90', 'Retigabina', 'category', false, false, 'CIE-11'),
('XM46J5', 'Perampanel', 'category', false, false, 'CIE-11'),
('XM78C3', 'Brivaracetam', 'category', false, false, 'CIE-11'),
('XM7QW2', 'Ganaxolona', 'category', false, false, 'CIE-11'),
('XM70W8', 'Derivados de carboxamida', 'category', false, false, 'CIE-11'),
('XM3D95', 'Carbamazepina', 'category', false, false, 'CIE-11'),
('XM69D6', 'Oxcarbazepina', 'category', false, false, 'CIE-11'),
('XM6BU4', 'Rufinamida', 'category', false, false, 'CIE-11'),
('XM5HL7', 'Eslicarbazepina', 'category', false, false, 'CIE-11'),
('XM2909', 'Clonazepan', 'category', false, false, 'CIE-11'),
('XM9G63', 'Fármacos antiparkinsonianos', 'category', false, false, 'CIE-11'),
('XM5Y20', 'Agentes dopaminérgicos', 'category', false, false, 'CIE-11'),
('XM1Z60', 'Carbidopa', 'category', false, false, 'CIE-11'),
('XM7SN1', 'Dopa y derivados de la Dopa', 'category', false, false, 'CIE-11'),
('XM2WU7', 'Levodopa', 'category', false, false, 'CIE-11'),
('XM7RF5', 'Difluorometildopa', 'category', false, false, 'CIE-11'),
('XM3MW1', 'Levodopa con carbidopa', 'category', false, false, 'CIE-11'),
('XM7ZB9', 'Inhibidor de levodopa y descarboxilasa', 'category', false, false, 'CIE-11'),
('XM3PK3', 'Levodopa, inhibidor de descarboxilasa e inhibidor de COMT', 'category', false, false, 'CIE-11'),
('XM1JZ7', 'Melevodopa', 'category', false, false, 'CIE-11'),
('XM0D22', 'Melevodopa e inhibidor y descarboxilasa', 'category', false, false, 'CIE-11'),
('XM6R13', 'Etilevodopa e inhibidor y descarboxilasa', 'category', false, false, 'CIE-11'),
('XM5QR9', 'Bromocriptina', 'category', false, false, 'CIE-11'),
('XM1GL7', 'Pergolida', 'category', false, false, 'CIE-11'),
('XM5PE4', 'Apomorfina', 'category', false, false, 'CIE-11'),
('XM2QX7', 'Piribedil', 'category', false, false, 'CIE-11'),
('XM5DT8', 'Mesilato de dihidroergocriptina', 'category', false, false, 'CIE-11'),
('XM9D35', 'Ropinirol', 'category', false, false, 'CIE-11'),
('XM5YJ4', 'Pramipexol', 'category', false, false, 'CIE-11'),
('XM7B98', 'Rotigotina', 'category', false, false, 'CIE-11'),
('XM50V4', 'Mesulergina', 'category', false, false, 'CIE-11'),
('XM9GG4', 'Inhibidores de la monoaminooxidasa B', 'category', false, false, 'CIE-11'),
('XM8FH5', 'Selegilina', 'category', false, false, 'CIE-11'),
('XM6XW7', 'Rasagilina', 'category', false, false, 'CIE-11'),
('XM8H59', 'Safinamida', 'category', false, false, 'CIE-11'),
('XM2H09', 'Amantadina', 'category', false, false, 'CIE-11'),
('XM0BA4', 'Tolcapona', 'category', false, false, 'CIE-11'),
('XM07G6', 'Entacapona', 'category', false, false, 'CIE-11'),
('XM0K96', 'Budipina', 'category', false, false, 'CIE-11'),
('XM6TZ5', 'Opicapona', 'category', false, false, 'CIE-11'),
('XM7KE0', 'Carfenazina', 'category', false, false, 'CIE-11'),
('XM83L8', 'Compazina', 'category', false, false, 'CIE-11'),
('XM7WF8', 'Dioxoprometazina', 'category', false, false, 'CIE-11'),
('XM5EP8', 'Etil aminofenotiazina', 'category', false, false, 'CIE-11'),
('XM9C32', 'Isoprometazina', 'category', false, false, 'CIE-11'),
('XM2WD3', 'Meleril®', 'category', false, false, 'CIE-11'),
('XM2VU6', 'Mepazina', 'category', false, false, 'CIE-11'),
('XM8ZW1', 'Metoxypromazina', 'category', false, false, 'CIE-11'),
('XM4TX5', 'Metofenazato', 'category', false, false, 'CIE-11'),
('XM52V9', 'Fenotiazina (psicotrópico)', 'category', false, false, 'CIE-11'),
('XM0F82', 'Piperacetazina', 'category', false, false, 'CIE-11'),
('XM6GY2', 'Propilaminofeno-tiazina', 'category', false, false, 'CIE-11'),
('XM2XX6', 'Esparina', 'category', false, false, 'CIE-11'),
('XM5JH1', 'Stelazine', 'category', false, false, 'CIE-11'),
('XM9Q32', 'Stemetil', 'category', false, false, 'CIE-11'),
('XM5Z28', 'Sulforidazina', 'category', false, false, 'CIE-11'),
('XM6YW4', 'Metilsulfato de tiazinamio', 'category', false, false, 'CIE-11'),
('XM87F3', 'Tindal', 'category', false, false, 'CIE-11'),
('XM0EE9', 'Tranquilizante dimetilamina', 'category', false, false, 'CIE-11'),
('XM9B27', 'Tranquilizante etialmina', 'category', false, false, 'CIE-11'),
('XM1QV8', 'Tranquilizante fenotiazina', 'category', false, false, 'CIE-11'),
('XM7057', 'Tranquilizante piperazina', 'category', false, false, 'CIE-11'),
('XM5KD3', 'Tranquilizante piperidina', 'category', false, false, 'CIE-11'),
('XM3Z20', 'Tranquilizante propilamina', 'category', false, false, 'CIE-11'),
('XM4SG0', 'Fenotiazinas con cadena lateral alifática', 'category', false, false, 'CIE-11'),
('XM4U75', 'Clorpromazina', 'category', false, false, 'CIE-11'),
('XM61Z1', 'Levomepromazina', 'category', false, false, 'CIE-11'),
('XM3CL7', 'Promacina', 'category', false, false, 'CIE-11'),
('XM8LW2', 'Acepromacina', 'category', false, false, 'CIE-11'),
('XM1TZ3', 'Trifluoperazina', 'category', false, false, 'CIE-11'),
('XM3AU5', 'Ciamemazina', 'category', false, false, 'CIE-11'),
('XM6WY7', 'Clorproetazina', 'category', false, false, 'CIE-11'),
('XM1YC7', 'Fenotiazinas con estructura de piperazina', 'category', false, false, 'CIE-11'),
('XM75P4', 'Dixyrazina', 'category', false, false, 'CIE-11'),
('XM6Z10', 'Flufenezina', 'category', false, false, 'CIE-11'),
('XM5Z27', 'Perfenazina', 'category', false, false, 'CIE-11'),
('XM84U4', 'Proclorperazina', 'category', false, false, 'CIE-11'),
('XM0PU2', 'Tiopropasato', 'category', false, false, 'CIE-11'),
('XM18F5', 'Trifluoperazina', 'category', false, false, 'CIE-11'),
('XM3EY1', 'Acetofenazina', 'category', false, false, 'CIE-11'),
('XM1V98', 'Tioproperazina', 'category', false, false, 'CIE-11'),
('XM5JD6', 'Butaperazina', 'category', false, false, 'CIE-11'),
('XM0TU3', 'Perazina', 'category', false, false, 'CIE-11'),
('XM9HH5', 'Fenotiazinas con estructura de piperidina', 'category', false, false, 'CIE-11'),
('XM5664', 'Periciazina', 'category', false, false, 'CIE-11'),
('XM4DG6', 'Tioridazina', 'category', false, false, 'CIE-11'),
('XM6447', 'Mesoridazina', 'category', false, false, 'CIE-11'),
('XM0168', 'Pipotiazina', 'category', false, false, 'CIE-11'),
('XM12B1', 'Benperidol', 'category', false, false, 'CIE-11'),
('XM4QG3', 'Bromperidol', 'category', false, false, 'CIE-11'),
('XM2HT3', 'Butirofenona (tranquilizantes a base de)', 'category', false, false, 'CIE-11'),
('XM6FV0', 'Droperidol', 'category', false, false, 'CIE-11'),
('XM0FM0', 'Fluanisona', 'category', false, false, 'CIE-11'),
('XM9580', 'Haloperidol', 'category', false, false, 'CIE-11'),
('XM6E81', 'Lemperona', 'category', false, false, 'CIE-11'),
('XM26W9', 'Melperona', 'category', false, false, 'CIE-11'),
('XM7DW6', 'Moperona', 'category', false, false, 'CIE-11'),
('XM5AB4', 'Pipamperona', 'category', false, false, 'CIE-11'),
('XM1UG0', 'Espiperona', 'category', false, false, 'CIE-11'),
('XM7RP6', 'Timiperona', 'category', false, false, 'CIE-11'),
('XM5NL7', 'Butirofenona tranquilizante', 'category', false, false, 'CIE-11'),
('XM4U52', 'Trifluperidol', 'category', false, false, 'CIE-11'),
('XM9NX2', 'Lumateperona', 'category', false, false, 'CIE-11'),
('XM1QY7', 'Derivados del indol', 'category', false, false, 'CIE-11'),
('XM84W2', 'Oxypertina', 'category', false, false, 'CIE-11'),
('XM61G1', 'Molindona', 'category', false, false, 'CIE-11'),
('XM69Z2', 'Sertindol', 'category', false, false, 'CIE-11'),
('XM8YM0', 'Ziprasidona', 'category', false, false, 'CIE-11'),
('XM9EW5', 'Lurasidona', 'category', false, false, 'CIE-11'),
('XM8X87', 'Derivados del tioxanteno', 'category', false, false, 'CIE-11'),
('XM4EY8', 'Flupentixol', 'category', false, false, 'CIE-11'),
('XM87S1', 'Clopentixol', 'category', false, false, 'CIE-11'),
('XM2H35', 'Cloroprotixeno', 'category', false, false, 'CIE-11'),
('XM6B79', 'Tiotixeno', 'category', false, false, 'CIE-11'),
('XM3MW6', 'Zuclopentixol', 'category', false, false, 'CIE-11'),
('XM2NF9', 'Derivados de difenilbutilpiperidina', 'category', false, false, 'CIE-11'),
('XM0Q81', 'Fluspirileno', 'category', false, false, 'CIE-11'),
('XM1FB1', 'Pimozida', 'category', false, false, 'CIE-11'),
('XM5SZ6', 'Penfluridol', 'category', false, false, 'CIE-11'),
('XM12F2', 'Diazepinas, oxazepinas, tiazepinas y oxepinas', 'category', false, false, 'CIE-11'),
('XM8FG8', 'Loxapina', 'category', false, false, 'CIE-11'),
('XM8UG6', 'Clozapina', 'category', false, false, 'CIE-11'),
('XM6GK7', 'Olanzapina', 'category', false, false, 'CIE-11'),
('XM4G70', 'Quetiapina', 'category', false, false, 'CIE-11'),
('XM90C7', 'Asenapina', 'category', false, false, 'CIE-11'),
('XM9DC4', 'Clotiapina', 'category', false, false, 'CIE-11'),
('XM9Q20', 'Veraliprida', 'category', false, false, 'CIE-11'),
('XM0624', 'Levosulpirida', 'category', false, false, 'CIE-11'),
('XM1W79', 'Benzamidas', 'category', false, false, 'CIE-11'),
('XM7Z05', 'Sulpirida', 'category', false, false, 'CIE-11'),
('XM9G21', 'Sultoprida', 'category', false, false, 'CIE-11'),
('XM8KD4', 'Tiaprida', 'category', false, false, 'CIE-11'),
('XM3WA3', 'Remoxiprida', 'category', false, false, 'CIE-11'),
('XM1DG3', 'Amisulprida', 'category', false, false, 'CIE-11'),
('XM0W09', 'Gluconato de litio', 'category', false, false, 'CIE-11'),
('XM5C35', 'Sales de litio (carbonato)', 'category', false, false, 'CIE-11'),
('XM4GQ2', 'Amperozida', 'category', false, false, 'CIE-11'),
('XM3JM5', 'Amfenidona', 'category', false, false, 'CIE-11'),
('XM7AA5', 'Droga antipsicótica especificada', 'category', false, false, 'CIE-11'),
('XM23M7', 'Azaciclonol', 'category', false, false, 'CIE-11'),
('XM56Y5', 'Benzperidine', 'category', false, false, 'CIE-11'),
('XM9VY2', 'Benzperidol', 'category', false, false, 'CIE-11'),
('XM3KB9', 'Empiprazol', 'category', false, false, 'CIE-11'),
('XM9097', 'Hidroxyfenamato', 'category', false, false, 'CIE-11'),
('XM7EB1', 'Mebutamato', 'category', false, false, 'CIE-11'),
('XM88L2', 'Mosapramina', 'category', false, false, 'CIE-11'),
('XM7B44', 'Nemonaprida', 'category', false, false, 'CIE-11'),
('XM5F36', 'Oxanamida', 'category', false, false, 'CIE-11'),
('XM9799', 'Fenaglicodol', 'category', false, false, 'CIE-11'),
('XM3BH3', 'Protipendil', 'category', false, false, 'CIE-11'),
('XM7L04', 'Racloprida', 'category', false, false, 'CIE-11'),
('XM7KX5', 'Setoperona', 'category', false, false, 'CIE-11'),
('XM6YS4', 'Spirilene', 'category', false, false, 'CIE-11'),
('XM0ES8', 'Carbamato tranquilizante', 'category', false, false, 'CIE-11'),
('XM7Z64', 'Hidroxicina tranquilizante', 'category', false, false, 'CIE-11'),
('XM3ES1', 'Tranquilizante especificado', 'category', false, false, 'CIE-11'),
('XM0GN3', 'Tioxanteno tranquilizante', 'category', false, false, 'CIE-11'),
('XM06W2', 'Tybamato', 'category', false, false, 'CIE-11'),
('XM4EU4', 'Zotepina', 'category', false, false, 'CIE-11'),
('XM1Z15', 'Risperidona', 'category', false, false, 'CIE-11'),
('XM67P4', 'Aripiprazol', 'category', false, false, 'CIE-11'),
('XM7H28', 'Paliperidona', 'category', false, false, 'CIE-11'),
('XM0FR9', 'Iloperidona', 'category', false, false, 'CIE-11'),
('XM1SS2', 'Cariprazina', 'category', false, false, 'CIE-11'),
('XM8504', 'Brexpiprazol', 'category', false, false, 'CIE-11'),
('XM0715', 'Pimavanserina', 'category', false, false, 'CIE-11'),
('XM3533', 'Amiflamina', 'category', false, false, 'CIE-11'),
('XM8CW9', 'Antidepresivo inhibido de la monoamino oxidasa', 'category', false, false, 'CIE-11'),
('XM9VZ7', 'Clorgilina', 'category', false, false, 'CIE-11'),
('XM2WY9', 'Iproclozida', 'category', false, false, 'CIE-11'),
('XM6DW5', 'Iproniazida', 'category', false, false, 'CIE-11'),
('XM4T23', 'Isocarboxazida', 'category', false, false, 'CIE-11'),
('XM2K50', 'Mebanazina', 'category', false, false, 'CIE-11'),
('XM2GX9', 'Hidrazina inhibidor de la monoamino oxidasa', 'category', false, false, 'CIE-11'),
('XM6944', 'Inhibidor de la monoamino oxidasa', 'category', false, false, 'CIE-11'),
('XM0158', 'Nialamida', 'category', false, false, 'CIE-11'),
('XM3KZ3', 'Parnate', 'category', false, false, 'CIE-11'),
('XM4S21', 'Fenelzina', 'category', false, false, 'CIE-11'),
('XM4A50', 'Feniprazina', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
