-- CIE11 Import Part 55
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XE9W2', 'Vulnerabilidad de la seguridad del software del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1KR', 'Transferencia errónea de datos en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2A7', 'Problema de almacenamiento de datos o pérdida de datos en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8XM', 'Problema térmico con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE62G', 'Sobrecalentamiento del problema del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9HT', 'Problema de calentamiento excesivo del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE7A1', 'Problema de enfriamiento inadecuado del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5HU', 'Problema del sistema de protección con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE0WJ', 'Problema de prueba de fallas con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4JQ', 'Problema del sistema de alarma con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE7ZT', 'Problema para la autocomprobación del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1JG', 'Problema para detener automáticamente el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9AV', 'Problema con el restablecimiento del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2FY', 'Problema con el indicador de activación prematura identificado', 'category', false, false, 'CIE-11'),
('XE3BG', 'Problema de blindaje con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE0M6', 'Medidas de seguridad faltantes o inadecuadas del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE82X', 'Problema operativo con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5RS', 'Dispositivo reprocesado incorrectamente', 'category', false, false, 'CIE-11'),
('XE2RQ', 'Dispositivo limpiado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE63T', 'Dispositivo desinfectado o esterilizado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE0TU', 'Dispositivo ensamblado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE15Q', 'Problema de error al calibrar identificado', 'category', false, false, 'CIE-11'),
('XE3W1', 'Problema de dificultad para operar el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2QD', 'Interpretación incorrecta de resultados o problema de datos identificado', 'category', false, false, 'CIE-11'),
('XE2YD', 'Problema de la muestra del paciente con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8DL', 'Problema de interferencia nuevo o desconocido con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9C0', 'Problema de interferencia conocido con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE83B', 'Problema de manipulación preanalítica con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3AL', 'Problema ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5K2', 'Problema de temperatura ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9HK', 'Problema de polvo o suciedad con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2VF', 'Contaminación del medio ambiente por el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE6QW', 'Problema de presión ambiental con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5SF', 'Problema de luz ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4V1', 'Problema de humedad ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE205', 'Problema del proceso de fabricación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3NF', 'Problema de montaje con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE00F', 'Problema de esterilización con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1PG', 'Problema de instalación con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE843', 'Problema de mantenimiento de maquinaria de fabricación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE278', 'Problema de empaquetado con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9F7', 'Problema con el empaquetado del dispositivo comprometido identificado', 'category', false, false, 'CIE-11'),
('XE0KG', 'Problema con los materiales de embalaje del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8S1', 'Problema con el embalaje del dispositivo que contiene un material no deseado identificado', 'category', false, false, 'CIE-11'),
('XE8TA', 'Problema porque el paquete contiene un dispositivo incorrecto identificado', 'category', false, false, 'CIE-11'),
('XE6LZ', 'Problema de mantenimiento con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9VK', 'Problema de transporte o almacenamiento con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE32G', 'Problema de almacenamiento del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE41R', 'No se encontró problema en el dispositivo', 'category', false, false, 'CIE-11'),
('XE587', 'Ningún hallazgo disponible', 'category', false, false, 'CIE-11'),
('XE3PA', 'Resultados pendientes de completar en la investigación', 'category', false, false, 'CIE-11'),
('XE3WR', 'Término o código apropiado para la investigación de dispositivo no disponible', 'category', false, false, 'CIE-11'),
('XE9HD', 'Prueba de dispositivo real o sospechoso', 'category', false, false, 'CIE-11'),
('XE7XH', 'Prueba del dispositivo del mismo lote o lote retenido por el fabricante', 'category', false, false, 'CIE-11'),
('XE4S0', 'Prueba del dispositivo del mismo lote devuelto por el usuario', 'category', false, false, 'CIE-11'),
('XE2ZR', 'Prueba del dispositivo de otro lote retenido por el fabricante', 'category', false, false, 'CIE-11'),
('XE4X1', 'Prueba de dispositivo de otro lote o lote devuelto por el usuario', 'category', false, false, 'CIE-11'),
('XE1XT', 'Prueba de variante del modelo', 'category', false, false, 'CIE-11'),
('XE8XV', 'Pruebas de materias primas o de partida', 'category', false, false, 'CIE-11'),
('XE6FS', 'Prueba de muestra del paciente o material de referencia utilizando el dispositivo del fabricante', 'category', false, false, 'CIE-11'),
('XE9MY', 'Prueba de la muestra del paciente o material de referencia utilizando el método de referencia', 'category', false, false, 'CIE-11'),
('XE89L', 'Prueba de la muestra del paciente o material de referencia utilizando un dispositivo de la competencia', 'category', false, false, 'CIE-11'),
('XE8UH', 'Análisis de datos históricos', 'category', false, false, 'CIE-11'),
('XE8BM', 'Análisis de tendencia', 'category', false, false, 'CIE-11'),
('XE7GK', 'Comunicación o entrevistas', 'category', false, false, 'CIE-11'),
('XE4KV', 'Análisis de registros de producción', 'category', false, false, 'CIE-11'),
('XE59M', 'Análisis de datos proporcionados por el usuario o terceras partes', 'category', false, false, 'CIE-11'),
('XE8FB', 'Dispositivo no fabricado por el fabricante reportado', 'category', false, false, 'CIE-11'),
('XE970', 'Dispositivo no devuelto', 'category', false, false, 'CIE-11'),
('XE18W', 'Dispositivo descartado', 'category', false, false, 'CIE-11'),
('XE5AN', 'Dispositivo devuelto pero incompleto', 'category', false, false, 'CIE-11'),
('XE53L', 'Dispositivo no accesible para pruebas', 'category', false, false, 'CIE-11'),
('XE6Q2', 'Tipo de investigación aún no determinado', 'category', false, false, 'CIE-11'),
('XE3TW', 'Información disponible insuficiente', 'category', false, false, 'CIE-11'),
('XE8XD', 'Componente absorbente de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6Z7', 'Componente de punta del cauterio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7JR', 'Ingrediente del dispositivo o componente reactivo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8HT', 'Componente de captación de gases del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4VK', 'Componente monómero líquido de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE68H', 'Componente de la tira reactiva del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7WP', 'Componente de polvo de polímero de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE321', 'Componente de antena del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3WM', 'Componente de batería del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE80Z', 'Componente cargador de batería del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7JQ', 'Cable, componente eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE77B', 'Componente de agarre de cable del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2BS', 'Componente de funda (aislante) de cable de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2WY', 'Componente de la placa de circuito del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5BT', 'Componente del interruptor eléctrico automático del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2ZE', 'Componente de hardware informático del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3Q8', 'Componente procesador de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1JS', 'Componente de memoria o almacenamiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2YC', 'Componente de interfaz de red del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8UU', 'Componente de software de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE59Z', 'Componente de controlador de software de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2JQ', 'Componente de interfaz de software del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8V6', 'Componente de interfaz de usuario del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7P0', 'Componente del módulo de enfriamiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8UV', 'Componente programador de dispositivo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE033', 'Componente lector de dispositivo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6UE', 'Componente eléctrico discreto del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE845', 'Componente de condensador eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE38E', 'Componente fusible eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1UQ', 'Componente inductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2AJ', 'Componente de resistencia eléctrica del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4VJ', 'Componente de solenoide eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE018', 'Componente transductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE27R', 'Componente semiconductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9ZW', 'Componente de chip de circuito integrado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8GY', 'Componente de visualización del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4YD', 'Componente indicador de pantalla del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2JV', 'Componente de pantalla de visualización del dispositivo médico.', 'category', false, false, 'CIE-11'),
('XE59E', 'Cable eléctrico o componente de cable del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5U9', 'Componente de electrodo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE561', 'Cable o componente de alambre para conexión a tierra del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE753', 'Componente del arnés de cableado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6S4', 'Componente de mezclador eléctrico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0Y5', 'Componente de puerto eléctrico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2PX', 'Componente emisor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5GC', 'Componente de auriculares o cascos de un dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9TB', 'Componente calefactor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE713', 'Componente central del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8JV', 'Componente inversor de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BN', 'Componente magnético del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7YS', 'Componente oscilador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE525', 'Componente cable conductor del paciente a un dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7F1', 'Componente cable conductor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE25C', 'Componente de electrodo de dispositivo médico para el paciente', 'category', false, false, 'CIE-11'),
('XE4XJ', 'Componente del cable de alimentación del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4Q4', 'Componente de fuente de alimentación del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7EJ', 'Componente de la sonda del transductor de presión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE062', 'Componente de impresión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2KA', 'Componente receptor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6SG', 'Componente de la unidad del estimulador del receptor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4TH', 'Componente de escáner de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0ST', 'Altavoz o componente acústico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5R5', 'Interruptor o componente de relé del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1EF', 'Componente del interruptor de encendido del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4QR', 'Componente de relé (interruptor) de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE884', 'Componente de telemetría del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE30P', 'Componente compensador de temperatura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE56F', 'Componente del termostato del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE256', 'Componente transformador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE579', 'Componente transmisor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5A0', 'Componente de dispositivo de entrada de usuario del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9TZ', 'Componente de control (joystick) de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6CN', 'Teclado o componente de teclado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9FY', 'Componente de micrófono de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9ZJ', 'Componente de pantalla táctil del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE37A', 'Componente analizador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0A7', 'Componente analizador de oxígeno del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6E8', 'Componente de apertura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE34X', 'Componente calibrador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE06B', 'Componente de reloj del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9NB', 'Componente contador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE20X', 'Componente Curvette (frasco o tubo de ensayo transparente) del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00B', 'Medidor o componentes de medidores de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE1WJ', 'Componente de fluxómetro de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6V2', 'Componente de manómetro del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE019', 'Componente termómetro del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8RD', 'Componente marcador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7MS', 'Componente de pipeta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5UB', 'Componente puntero del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2MH', 'Componente de escala del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8GP', 'Componente sensor de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5Q2', 'Componente del sensor de burbujas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5ZD', 'Componente del sensor de oxígeno del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9G5', 'Componente fotodetector del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5WR', 'Componente sensor de presión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7Q4', 'Componente de la sonda del sensor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3W9', 'Componente del sensor de temperatura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3R3', 'Componente temporizador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3UX', 'Componente del puerto de acceso del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0WZ', 'Componente actuador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0SV', 'Componente adaptador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6D6', 'Componente eliminador de aire del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4F2', 'Componente de anclaje del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE94Y', 'Componente aplicador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE968', 'Componente del sistema de inyección automática del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7E4', 'Componente de bolsa de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0HN', 'Componente esférico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5AV', 'Componente de globo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1G8', 'Componente de cojinetes de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0Y2', 'Componente de encapsulado de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE46S', 'Componente de sonda del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE23M', 'Componente procesador (de material) del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9DJ', 'Componente de polea de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0K1', 'Componente de bomba del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8RF', 'Componente empujador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE76K', 'Componente de trinquete del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4JZ', 'Componente de carril del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0KN', 'Componente de riel lateral del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6YN', 'Componente regulador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE65T', 'Componente depósito del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1XK', 'Componente de fuelle de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7DG', 'Componente de anillo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE017', 'Componente de varilla o eje del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BJ', 'Componente de sellado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7N2', 'Componente amortiguador de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE7ZG', 'Componente de manga de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6VJ', 'Componente laminilla de vidrio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE740', 'Componente de enchufe del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4DU', 'Componente espaciador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7QZ', 'Componente de resorte del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4K0', 'Componente de soporte del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9CF', 'Componente de cinturón de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE82E', 'Componente del cable de dirección del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7UE', 'Componente stent de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8M4', 'Componente de la llave de paso del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00C', 'Componente de tapón del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4E4', 'Componente de alivio de tensión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3GN', 'Componente de estilete del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE05P', 'Componente de jeringa de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3ED', 'Componente de mesa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE06W', 'Componente de punta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6GE', 'Componente de herramienta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7G4', 'Componente de botella de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0UG', 'Componente de movimiento traslacional del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2FM', 'Componente de trampa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4M3', 'Componente de trocar del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8TY', 'Componente de tubo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2PZ', 'Componente del tubo capilar del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE01P', 'Componente de válvula de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3YJ', 'Componente de la válvula de control del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE229', 'Componente de la válvula conector Luer del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2LS', 'Componente de válvula unidireccional de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6MT', 'Componente vaporizador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0FP', 'Componente vibrador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE83A', 'Componente de arandela de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1PW', 'Componente de soldadura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6HA', 'Componente de rueda de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0C3', 'Componente del circuito respiratorio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE99Z', 'Componente de ventana del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2Q3', 'Componente del obturador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5YT', 'Componente de cepillo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0AX', 'Componente de cepillado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4NU', 'Cable, componente estructural mecánico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2UB', 'Componente de cánula del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9FK', 'Componente del cubo de la cánula del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE44H', 'Componente de tapa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00E', 'Componente transportador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3K0', 'Componente de rueda de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE088', 'Componente catéter de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8NS', 'Componente del conector de catéter del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1TF', 'Componente celular del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE65A', 'Componente de cadena de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6N0', 'Componente de la cámara del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BK', 'Chasis o componente del marco del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5CL', 'Componente de embrague de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3C8', 'Componente de material de revestimiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1S0', 'Componente de bobina de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8AQ', 'Componente de bobina helifix de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0YX', 'Componente colimador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7YF', 'Componente concentrador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5TK', 'Componente de cono de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7EE', 'Conector o componente acoplador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4T6', 'Componente de clavija del conector del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE83L', 'Componente controlador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE46J', 'Componente compresor de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1S2', 'Componente de la cubierta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8LZ', 'Componente de manguito del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8YR', 'Componente de copa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8T8', 'Componente de cúspide y hojuela del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3LB', 'Componente cortador o cuchilla de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9WL', 'Componente cilíndrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3CX', 'Componente de colapsador de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE8J5', 'Componente de despliegue de dispositivo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1KD', 'Componente de diafragma de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE85G', 'Componente de cúpula de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5K4', 'Componente eyector del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1VC', 'Componente de poste de equipo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8ZU', 'Componente extensor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE026', 'Componente de tela del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8VD', 'Ventilador o componente soplador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5DL', 'Componente sujetador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1A5', 'Componente adhesivo de fijación de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE4V8', 'Componente de cierre de perno de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4PG', 'Componente sujetador de abrazadera de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3VN', 'Componente sujetador de clip de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9KR', 'Componente de fijación de alambre del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6R2', 'Componente de cierre de pestillo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7GP', 'Componente sujetador de clavo o alfiler del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0F0', 'Componente de fijación de tuerca de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6A2', 'Componente de fijación tipo pasador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE059', 'Componente sujetador tipo clavija del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE33C', 'Componente de cierre de retención del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9MM', 'Componente de sujetador de remache de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3NX', 'Componente de sujetador de tornillo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2HY', 'Componente sujetador de grapas de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE0NL', 'Componente fijador de hilo de sutura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8MX', 'Cinta para componente de fijación de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE15J', 'Componente de fibra de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE65M', 'Componente de filtro del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE10F', 'Componente de brida del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4PC', 'Componente de lámina del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3HQ', 'Componente intercambiador de gas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3QZ', 'Componente de empaque de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5M6', 'Componente de engranajes del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0RK', 'Componente generador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1ND', 'Componente guía del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE64H', 'Componente de alambre guía del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE11W', 'Componente de la pieza de mano del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE37B', 'Componente de encabezado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2AL', 'Componente de anillo de sutura de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE12Q', 'Componente del intercambiador de calor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5ZS', 'Componente de bisagra del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4FZ', 'Componente para sostener del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3A4', 'Componente de manguera de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5S9', 'Componente de carcasa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0YE', 'Componente humidificador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1TK', 'Componente del sistema hidráulico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4NN', 'Componente impulsor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3WA', 'Componente insertador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1Y2', 'Componente de aislamiento de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7JF', 'Componente aislante del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7N3', 'Componente de mandíbula del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7GQ', 'Componente de unión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3AW', 'Componente de perilla del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6R7', 'Componente de etiqueta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1VQ', 'Componente de hojuelas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5XR', 'Componente de palanca del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE08E', 'Componente del pedal del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE80W', 'Componente de revestimiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE17E', 'Componente de cargador o casete del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE87E', 'Colector múltiple del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE26U', 'Componente de mascarilla de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE74K', 'Componente mezclador mecánico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9VQ', 'Componente de membrana del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8R6', 'Componente de malla de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0R5', 'Componente motor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8X1', 'Componente para unir del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BH', 'Componente de aguja del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE78G', 'Componente de boquilla del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7C4', 'Componente de embalaje del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5AR', 'Componente de almohadilla del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE080', 'Componente de panel del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE965', 'Componente de placa de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE09R', 'Componente de enchufe del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9R2', 'Componente del émbolo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE25A', 'Componente posterior del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE120', 'Componente de cámara del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5CR', 'Componente de película de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7NH', 'Componente generador de imágenes del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6GJ', 'Componente láser de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6QH', 'Componente de diodo emisor de luz del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE616', 'Componente de lentes de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE5LN', 'Componente de fuente de luz del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5G9', 'Componente de bombilla de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9EM', 'Componente espejo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7A6', 'Componente de fibras ópticas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE28G', 'Componente de alarma del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5DW', 'Componente de alarma del dispositivo médico, audible', 'category', false, false, 'CIE-11'),
('XE3WT', 'Componente de alarma del dispositivo médico, visual', 'category', false, false, 'CIE-11'),
('XE2N6', 'Botón de emergencia o componente de interruptor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE37H', 'Componente del sistema a prueba de fallas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE51V', 'Componente del mecanismo de bloqueo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8RN', 'Componente protector o escudo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0ZU', 'Componente de bloqueo de seguridad del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4HV', 'Mecanismo de prevención de pinchazos de aguja', 'category', false, false, 'CIE-11'),
('XE58K', 'Componente de válvula de seguridad del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE27U', 'Término no aplicable de la parte, componente o subensamblaje', 'category', false, false, 'CIE-11'),
('XE8NG', 'Término o código apropiado no disponible para componente de dispositivo médico', 'category', false, false, 'CIE-11'),
('XC3W', 'Uno o ambos ojos se abren espontaneamente', 'category', false, false, 'CIE-11'),
('XC5L', 'Uno o ambos ojos abiertos por estimulación verbal', 'category', false, false, 'CIE-11'),
('XC3H', 'Uno o ambos ojos se abren a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC87', 'Sin ojos abiertos incluso con estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC2N', '', 'category', false, false, 'CIE-11'),
('XC4L', 'Obedecer órdenes', 'category', false, false, 'CIE-11'),
('XC6J', 'Respuesta localizada a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC8Q', 'Respuesta de retirada a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC8W', 'Respuesta de flexión anormal a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC8H', 'Respuesta de extensión a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC34', 'Sin movimiento, incluso con estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC3S', '', 'category', false, false, 'CIE-11'),
('XC2X', 'Lenguaje normal, orientado', 'category', false, false, 'CIE-11'),
('XC4Y', 'Discurso desorientado, confuso', 'category', false, false, 'CIE-11'),
('XC4A', 'Expresiones del lenguaje', 'category', false, false, 'CIE-11'),
('XC7U', 'Expresiones no idiomáticas (sonidos incomprensibles) a estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC8U', 'Incluso sin expresión verbal a la estimulación dolorosa o nociva', 'category', false, false, 'CIE-11'),
('XC03', '', 'category', false, false, 'CIE-11'),
('XC5Y', 'Ninguna reacción de la pupila', 'category', false, false, 'CIE-11'),
('XC16', 'Una pupila reacciona', 'category', false, false, 'CIE-11'),
('XC5K', 'Reacción de ambas pupilas', 'category', false, false, 'CIE-11'),
('XC85', 'Dato no disponible', 'category', false, false, 'CIE-11'),
('XM1349', 'Antiácidos', 'category', false, false, 'CIE-11'),
('XM7GM7', 'Compuestos de magnesio', 'category', false, false, 'CIE-11'),
('XM39M3', 'Hidróxido de magnesio', 'category', false, false, 'CIE-11'),
('XM35X7', 'Aluminio, silicato de aluminio y magnesio', 'category', false, false, 'CIE-11'),
('XM3JP8', 'Compuestos de aluminio', 'category', false, false, 'CIE-11'),
('XM9N47', 'Algeldrato', 'category', false, false, 'CIE-11'),
('XM2VU8', 'Aluminio, fosfato de aluminio', 'category', false, false, 'CIE-11'),
('XM4NY5', 'Aloglutamol', 'category', false, false, 'CIE-11'),
('XM7DC3', 'Aluminio, glicinato de aluminio', 'category', false, false, 'CIE-11'),
('XM9PG0', 'Carbonato sódico de dihidroxialuminio', 'category', false, false, 'CIE-11'),
('XM38T8', 'Hidróxido de aluminio (gel)', 'category', false, false, 'CIE-11'),
('XM0SA0', 'Compuestos de calcio', 'category', false, false, 'CIE-11'),
('XM9003', 'Carbonato de calcio', 'category', false, false, 'CIE-11'),
('XM8EF6', 'Silicato de calcio', 'category', false, false, 'CIE-11'),
('XM0D52', 'Combinaciones y complejos de compuestos de aluminio, calcio y magnesio', 'category', false, false, 'CIE-11'),
('XM5R16', 'Magaldrato', 'category', false, false, 'CIE-11'),
('XM8J56', 'Almagato', 'category', false, false, 'CIE-11'),
('XM3EB6', 'Hidrotalcita', 'category', false, false, 'CIE-11'),
('XM9Y49', 'Almasilato', 'category', false, false, 'CIE-11'),
('XM9YL4', 'Cimetidina', 'category', false, false, 'CIE-11'),
('XM6441', 'Famotidina', 'category', false, false, 'CIE-11'),
('XM9ZP3', 'Nizatidina', 'category', false, false, 'CIE-11'),
('XM6WY8', 'Ranitidina', 'category', false, false, 'CIE-11'),
('XM0SH0', 'Roxatidina', 'category', false, false, 'CIE-11'),
('XM08A8', 'Niperotidina', 'category', false, false, 'CIE-11'),
('XM1ZT1', 'Citrato de bismuto ranitidina', 'category', false, false, 'CIE-11'),
('XM0Q37', 'Lafutidina', 'category', false, false, 'CIE-11'),
('XM2WX5', 'Inhibidores de la bomba de protones', 'category', false, false, 'CIE-11'),
('XM8X45', 'Omeprazol', 'category', false, false, 'CIE-11'),
('XM86M3', 'Pantoprazol', 'category', false, false, 'CIE-11'),
('XM39X4', 'Lansoprazol', 'category', false, false, 'CIE-11'),
('XM3M01', 'Rabeprazol', 'category', false, false, 'CIE-11'),
('XM8YE1', 'Esomeprazol', 'category', false, false, 'CIE-11'),
('XM5RA0', 'Dexlansoprazol', 'category', false, false, 'CIE-11'),
('XM1J18', 'Dexrabeprazol', 'category', false, false, 'CIE-11'),
('XM3MK2', 'Tegoprazán', 'category', false, false, 'CIE-11'),
('XM4ML1', 'Prostaglandinas', 'category', false, false, 'CIE-11'),
('XM28N9', 'Misoprostol', 'category', false, false, 'CIE-11'),
('XM4GD1', 'Enprostil', 'category', false, false, 'CIE-11'),
('XM1CF2', 'Alprostadil', 'category', false, false, 'CIE-11'),
('XM3Q43', 'Dinoprost', 'category', false, false, 'CIE-11'),
('XM5VF9', 'Dinoprostona', 'category', false, false, 'CIE-11'),
('XM2L11', 'Gemeprost', 'category', false, false, 'CIE-11'),
('XM8XM0', 'Carboprost', 'category', false, false, 'CIE-11'),
('XM9BJ7', 'Sulprostona', 'category', false, false, 'CIE-11'),
('XM2H82', 'Carbenoxolona', 'category', false, false, 'CIE-11'),
('XM0044', 'Sucralfato', 'category', false, false, 'CIE-11'),
('XM6690', 'Pirenzepina', 'category', false, false, 'CIE-11'),
('XM6WX3', 'Proglumida', 'category', false, false, 'CIE-11'),
('XM0HB8', 'Gefarnato', 'category', false, false, 'CIE-11'),
('XM2689', 'Sulglicotida', 'category', false, false, 'CIE-11'),
('XM4H50', 'Ácido algínico', 'category', false, false, 'CIE-11'),
('XM2891', 'Rebamipide', 'category', false, false, 'CIE-11'),
('XM1F15', 'Cloruro de metiosulfonio', 'category', false, false, 'CIE-11'),
('XM1BG6', 'Subcitrato de bismuto', 'category', false, false, 'CIE-11'),
('XM1LT9', 'Acetoxolona', 'category', false, false, 'CIE-11'),
('XM9SW3', 'Zolimidine', 'category', false, false, 'CIE-11'),
('XM1Y11', 'Troxipida', 'category', false, false, 'CIE-11'),
('XM84X1', 'Subnitrato de bismutilo', 'category', false, false, 'CIE-11'),
('XM1364', 'Combinaciones fijas para la erradicación de Helicobacter pylori', 'category', false, false, 'CIE-11'),
('XM4S40', 'Antagonistas del receptor de serotonina', 'category', false, false, 'CIE-11'),
('XM7423', 'Ondansetron', 'category', false, false, 'CIE-11'),
('XM8123', 'Granisetrón', 'category', false, false, 'CIE-11'),
('XM3X37', 'Cilansetron (calmactin)', 'category', false, false, 'CIE-11'),
('XM2493', 'Diisopromina', 'category', false, false, 'CIE-11'),
('XM30Q8', 'Clorbenzoxamina', 'category', false, false, 'CIE-11'),
('XM2GC8', 'Pinaverio', 'category', false, false, 'CIE-11'),
('XM3CZ9', 'Fenoverina', 'category', false, false, 'CIE-11'),
('XM5RS2', 'Alverina', 'category', false, false, 'CIE-11'),
('XM27M9', 'Isometepteno', 'category', false, false, 'CIE-11'),
('XM6UH6', 'Migalastat', 'category', false, false, 'CIE-11'),
('XM49K4', 'Fenpiprane', 'category', false, false, 'CIE-11'),
('XM7F16', 'Idanpramine', 'category', false, false, 'CIE-11'),
('XM8N97', 'Proxazole', 'category', false, false, 'CIE-11'),
('XM2SK3', 'Trepibutone', 'category', false, false, 'CIE-11'),
('XM3R36', 'Caroverine', 'category', false, false, 'CIE-11'),
('XM66E5', 'Floroglucinol', 'category', false, false, 'CIE-11'),
('XM7ZC5', 'Trimetildifenilpropilamina', 'category', false, false, 'CIE-11'),
('XM9K48', 'Bromuro de valetamato', 'category', false, false, 'CIE-11'),
('XM6Q06', 'Aluminio, tanato de aluminio', 'category', false, false, 'CIE-11'),
('XM62S7', 'Amilopectina', 'category', false, false, 'CIE-11'),
('XM8A95', 'Medicamento antidiarreico absorbente', 'category', false, false, 'CIE-11'),
('XM6V74', 'Atapulgita', 'category', false, false, 'CIE-11'),
('XM4SG9', 'Bacillus subtilis', 'category', false, false, 'CIE-11'),
('XM98L3', 'Sales de subcarbonato de bismuto', 'category', false, false, 'CIE-11'),
('XM5U61', 'Sales de bismuto', 'category', false, false, 'CIE-11'),
('XM3962', 'Carbón medicinal', 'category', false, false, 'CIE-11'),
('XM0S42', 'Carbón', 'category', false, false, 'CIE-11'),
('XM46T5', 'Carbón activado', 'category', false, false, 'CIE-11'),
('XM2269', 'Carbón medicinal (activado)', 'category', false, false, 'CIE-11'),
('XM8D61', 'Carbón medicinal antidiarreico', 'category', false, false, 'CIE-11'),
('XM8ET0', 'Difenoxina', 'category', false, false, 'CIE-11'),
('XM15K3', 'Fetoxilato', 'category', false, false, 'CIE-11'),
('XM3ZU0', 'Medicamento para el control de la motilidad intestinal.', 'category', false, false, 'CIE-11'),
('XM7CN8', 'Caolinita', 'category', false, false, 'CIE-11'),
('XM2GB1', 'Caolin liviano', 'category', false, false, 'CIE-11'),
('XM1N12', 'Compuesto de Lactobacillus acidophilus', 'category', false, false, 'CIE-11'),
('XM0EB5', 'Lactobacillus acidophilus', 'category', false, false, 'CIE-11'),
('XM0QG1', 'Lactobacillus acidophilus, liofilizado', 'category', false, false, 'CIE-11'),
('XM1TF2', 'Lactobacillus bulgaricus', 'category', false, false, 'CIE-11'),
('XM4KH7', 'Lactobacillus sporogenes', 'category', false, false, 'CIE-11'),
('XM48X2', 'hemicelulosa lignina', 'category', false, false, 'CIE-11'),
('XM8683', 'Lomotil', 'category', false, false, 'CIE-11'),
('XM2UP7', 'Bacteria miyari', 'category', false, false, 'CIE-11'),
('XM2HR7', 'Pectina', 'category', false, false, 'CIE-11'),
('XM4X08', 'Saccharomyces boulardii', 'category', false, false, 'CIE-11'),
('XM2663', 'Aceite de anís', 'category', false, false, 'CIE-11'),
('XM8A26', 'Antiflatulento', 'category', false, false, 'CIE-11'),
('XM0090', 'Betaína', 'category', false, false, 'CIE-11'),
('XM0TD5', 'Sales biliares', 'category', false, false, 'CIE-11'),
('XM5TC9', 'Carminativo', 'category', false, false, 'CIE-11'),
('XM5QD3', 'Colagogo', 'category', false, false, 'CIE-11'),
('XM6RN6', 'Colerético', 'category', false, false, 'CIE-11'),
('XM5CH0', 'Citocromo C', 'category', false, false, 'CIE-11'),
('XM00U8', 'Ácido dehidrocólico', 'category', false, false, 'CIE-11'),
('XM0365', 'Eneldo', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
