-- CIE11 Import Part 42
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XA13U3', 'Arteria auricular posterior', 'category', false, false, 'CIE-11'),
('XA0SB1', 'Arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7WG0', 'Rama frontal de la arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7K29', 'Arteria tiroidea superior', 'category', false, false, 'CIE-11'),
('XA0FT7', 'Arteria cricotiroidea', 'category', false, false, 'CIE-11'),
('XA2V10', 'Arteria tiroidea inferior', 'category', false, false, 'CIE-11'),
('XA77C5', 'Arteria esternocleidomastoidea', 'category', false, false, 'CIE-11'),
('XA00E5', 'Arteria faríngea ascendente', 'category', false, false, 'CIE-11'),
('XA53A8', 'Arteria carótida común derecha', 'category', false, false, 'CIE-11'),
('XA6X36', 'Arteria temporal media', 'category', false, false, 'CIE-11'),
('XA3TE9', 'Arteria milohioidea de la arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA6XV2', 'Rama parietal de la arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7U73', 'Arteria comunicante posterior', 'category', false, false, 'CIE-11'),
('XA5881', 'Arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA7561', 'Ramas nasales de la arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA7945', 'Rama meningeas de la arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA8RM9', 'Arteria cerebelosa inferior posterior', 'category', false, false, 'CIE-11'),
('XA9VV0', 'Ramas nasales laterales posteriores de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA8FA1', 'Arteria meningea posterior', 'category', false, false, 'CIE-11'),
('XA4Q78', 'Ramas septales posteriores de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA1K74', 'Ramas pterigoideas', 'category', false, false, 'CIE-11'),
('XA1BZ0', 'Rama terminal de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA90T0', 'Arteria submentoniana de la arteria cervical', 'category', false, false, 'CIE-11'),
('XA6FR0', 'Rama superficial de la arteria submentoniana', 'category', false, false, 'CIE-11'),
('XA0898', 'Rama superficial de la arteria cervical transversa', 'category', false, false, 'CIE-11'),
('XA82P9', 'Rama petrosa superficial de la arteria meningea posterior y anterior', 'category', false, false, 'CIE-11'),
('XA7423', 'Arteria cerebelosa superior', 'category', false, false, 'CIE-11'),
('XA9GU1', 'Arteria laríngea superior', 'category', false, false, 'CIE-11'),
('XA50Q9', 'Arteria timpánica superior', 'category', false, false, 'CIE-11'),
('XA6W31', 'Arteria supratroclear', 'category', false, false, 'CIE-11'),
('XA65G3', 'Ramas temporales de la arteria meningea anterior y posterior', 'category', false, false, 'CIE-11'),
('XA9XH0', 'Tronco tirocervical', 'category', false, false, 'CIE-11'),
('XA2E78', 'Rama tonsilar de la arteria cervical', 'category', false, false, 'CIE-11'),
('XA6142', 'Arteria cervical transversa', 'category', false, false, 'CIE-11'),
('XA9M59', 'Arteria facial transversa', 'category', false, false, 'CIE-11'),
('XA5D86', 'Rama pequeña a la parte superior del saco lagrimal de la arteria nasal dorsal', 'category', false, false, 'CIE-11'),
('XA1XP6', 'Arteria vertebral', 'category', false, false, 'CIE-11'),
('XA3NW4', 'Ramas meníngeas de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA6TE8', 'Rama ascendente de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA3R20', 'Rama descendente de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA1C15', 'Arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA6503', 'Rama superficial de la arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA8BL5', 'Rama profunda de la arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA34H5', 'Ramas orbitarias de la arteria meníngea anterior y posterior', 'category', false, false, 'CIE-11'),
('XA5C33', 'Arteria infraorbitaria', 'category', false, false, 'CIE-11'),
('XA05E9', 'Ramas orbitarias de la arteria infraorbitaria', 'category', false, false, 'CIE-11'),
('XA9RA2', 'Arteria ciliar posterior larga', 'category', false, false, 'CIE-11'),
('XA04E2', 'Arteria ciliar posterior corta', 'category', false, false, 'CIE-11'),
('XA94Y6', 'Arteria ciliar anterior', 'category', false, false, 'CIE-11'),
('XA5RB0', 'Arteria central de la retina', 'category', false, false, 'CIE-11'),
('XA22D8', 'Círculo arterioso de la arteria mayor', 'category', false, false, 'CIE-11'),
('XA8T70', 'Círculo arterioso de la arteria menor', 'category', false, false, 'CIE-11'),
('XA5P69', 'Arteria lagrimal', 'category', false, false, 'CIE-11'),
('XA00Q9', 'Arteria palpebral lateral', 'category', false, false, 'CIE-11'),
('XA8VA1', 'Arteria palpebral media', 'category', false, false, 'CIE-11'),
('XA35L5', 'Arteria del arco palpebral superior', 'category', false, false, 'CIE-11'),
('XA1Q49', 'Ramas cigomáticas de la arteria lagrimal', 'category', false, false, 'CIE-11'),
('XA4KE1', 'Ramas a la encía', 'category', false, false, 'CIE-11'),
('XA9UT1', 'Arteria del tórax', 'category', false, false, 'CIE-11'),
('XA4TH8', 'Ramas al diafragma de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA1PX4', 'Ramas a la parte inferior del pericardio de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA2KA0', 'Tronco braquiocefálico', 'category', false, false, 'CIE-11'),
('XA3M86', 'Rama profunda de la arteria escapular dorsal', 'category', false, false, 'CIE-11'),
('XA7KK5', 'Arteria intercostal', 'category', false, false, 'CIE-11'),
('XA0T62', 'Ramas intercostales de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA9S49', 'Arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA4XE2', 'Arteria mediastínica', 'category', false, false, 'CIE-11'),
('XA3DE1', 'Arteria torácica lateral', 'category', false, false, 'CIE-11'),
('XA09J9', 'Arteria pulmonar', 'category', false, false, 'CIE-11'),
('XA1EE3', 'Arteria intercostal posterior inferior (de la III a la XI)', 'category', false, false, 'CIE-11'),
('XA0QG6', 'Ramas inferiores de las anastomosis espaciales de las seis ramas intercostales anteriores de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA7EC2', 'Arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA1190', 'Ramas perforantes de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA0WT1', 'Arteria intercostal posterior', 'category', false, false, 'CIE-11'),
('XA14K0', 'Seis ramas intercostales anteriores de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA6UQ6', 'Ramos esternales de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA3311', 'Arteria subcostal', 'category', false, false, 'CIE-11'),
('XA9J15', 'Arteria frénica superior', 'category', false, false, 'CIE-11'),
('XA8M67', 'Arteria torácica superior', 'category', false, false, 'CIE-11'),
('XA7TT5', 'Arteria intercostal suprema', 'category', false, false, 'CIE-11'),
('XA79X5', 'Arteria toracoacromial', 'category', false, false, 'CIE-11'),
('XA99C2', 'Ramas anteriores de las seis ramas intercostales anteriores de arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA8ES3', 'Arteria esófagica', 'category', false, false, 'CIE-11'),
('XA8K52', 'Aorta del tórax', 'category', false, false, 'CIE-11'),
('XA75Z8', 'Arco de la aorta', 'category', false, false, 'CIE-11'),
('XA01A6', 'Aorta ascendente', 'category', false, false, 'CIE-11'),
('XA5H34', 'Aorta descendente', 'category', false, false, 'CIE-11'),
('XA6E07', 'Arteria bronquial', 'category', false, false, 'CIE-11'),
('XA5D68', 'Arteria subclavia', 'category', false, false, 'CIE-11'),
('XA9JK8', 'Arteria del abdomen', 'category', false, false, 'CIE-11'),
('XA7TZ1', 'Arteria suprarrenal anterior', 'category', false, false, 'CIE-11'),
('XA82R7', 'Rama ascendente de la arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA8BY2', 'Ramas a los músculos abdominales de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA8577', 'Arteria celíaca', 'category', false, false, 'CIE-11'),
('XA26R6', 'Arteria hepática común', 'category', false, false, 'CIE-11'),
('XA0JE4', 'Arteria cística', 'category', false, false, 'CIE-11'),
('XA6NY6', 'Rama descendente de la arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA1VJ7', 'Vasos rectos descendentes', 'category', false, false, 'CIE-11'),
('XA1QB0', 'Arteria pancreática dorsal', 'category', false, false, 'CIE-11'),
('XA0NN4', 'Arteria gastroduodenal', 'category', false, false, 'CIE-11'),
('XA5AP2', 'Arteria hepática', 'category', false, false, 'CIE-11'),
('XA2LQ8', 'Rama hepática de la arteria gástrica izquierda', 'category', false, false, 'CIE-11'),
('XA2Z43', 'Arteria ileocólica', 'category', false, false, 'CIE-11'),
('XA3F13', 'Arteria epigástrica inferior', 'category', false, false, 'CIE-11'),
('XA2N15', 'Arteria mesentérica inferior', 'category', false, false, 'CIE-11'),
('XA6358', 'Arteria pancreaticoduodenal inferior', 'category', false, false, 'CIE-11'),
('XA2LL9', 'Arteria frénica inferior', 'category', false, false, 'CIE-11'),
('XA68L7', 'Arteria intestinal', 'category', false, false, 'CIE-11'),
('XA6WR7', 'Arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA0LL0', 'Arteria gástrica izquierda', 'category', false, false, 'CIE-11'),
('XA9AQ6', 'Arteria gastroepiploica izquierda', 'category', false, false, 'CIE-11'),
('XA4UK9', 'Arteria lumbar', 'category', false, false, 'CIE-11'),
('XA6CA5', 'Arteria mesentérica', 'category', false, false, 'CIE-11'),
('XA1Z62', 'Arteria cólica media', 'category', false, false, 'CIE-11'),
('XA1GQ7', 'Arteria suprarrenal media', 'category', false, false, 'CIE-11'),
('XA00T1', 'Arteria suprarrenal posterior', 'category', false, false, 'CIE-11'),
('XA8C72', 'Arteria hepática propia', 'category', false, false, 'CIE-11'),
('XA69V9', 'Arteria renal', 'category', false, false, 'CIE-11'),
('XA6GC2', 'Arteria cólica derecha', 'category', false, false, 'CIE-11'),
('XA9HE0', 'Arteria gástrica derecha', 'category', false, false, 'CIE-11'),
('XA8V02', 'Arteria gastroepiploica derecha', 'category', false, false, 'CIE-11'),
('XA02A2', 'Arteria sigmoidea', 'category', false, false, 'CIE-11'),
('XA0R02', 'Arteria esplénica', 'category', false, false, 'CIE-11'),
('XA2870', 'Arteria pancreatoduodenal superior', 'category', false, false, 'CIE-11'),
('XA51U4', 'Ramas terminales de la arteria hepática propia', 'category', false, false, 'CIE-11'),
('XA0VZ0', 'Arteria umbilical', 'category', false, false, 'CIE-11'),
('XA3VR0', 'Arteria mesentérica superior', 'category', false, false, 'CIE-11'),
('XA4GP1', 'Arteria de la pelvis', 'category', false, false, 'CIE-11'),
('XA5PV1', 'Arteria del bulbo del pene', 'category', false, false, 'CIE-11'),
('XA30X9', 'Arteria del bulbo del vestíbulo', 'category', false, false, 'CIE-11'),
('XA4XP0', 'Arteria profunda del clítoris', 'category', false, false, 'CIE-11'),
('XA7AM0', 'Arteria profunda del pene', 'category', false, false, 'CIE-11'),
('XA14N2', 'Rama profunda de la arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA4AP3', 'Arteria pudenda externa profunda', 'category', false, false, 'CIE-11'),
('XA27B8', 'Arteria del conducto deferente', 'category', false, false, 'CIE-11'),
('XA4FK8', 'Arteria dorsal del clítoris', 'category', false, false, 'CIE-11'),
('XA4X54', 'Arteria dorsal del pene', 'category', false, false, 'CIE-11'),
('XA5GV0', 'Rama ilíaca de la arteria iliolumbar', 'category', false, false, 'CIE-11'),
('XA7D46', 'Arteria iliolumbar', 'category', false, false, 'CIE-11'),
('XA3XS2', 'Rama inferior de la arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA0G82', 'Arteria glútea inferior', 'category', false, false, 'CIE-11'),
('XA2QX3', 'Arteria vesical inferior', 'category', false, false, 'CIE-11'),
('XA7FK7', 'Arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA5Y50', 'Arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA82V4', 'Arteria sacra mediana', 'category', false, false, 'CIE-11'),
('XA8X93', 'Arteria rectal media', 'category', false, false, 'CIE-11'),
('XA69V8', 'Arteria obturatriz', 'category', false, false, 'CIE-11'),
('XA1MF5', 'Arteria ovárica en las mujeres', 'category', false, false, 'CIE-11'),
('XA5MN1', 'Arteria perineal', 'category', false, false, 'CIE-11'),
('XA34Z7', 'Ramas labiales posteriores de la arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA2025', 'Ramas escrotales posteriores de la arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA2TT0', 'Rama superficial de la arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA0AZ8', 'Rama superior de la arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA26E6', 'Arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA1426', 'Arteria vesical superior', 'category', false, false, 'CIE-11'),
('XA0UK9', 'Arteria testicular en varones', 'category', false, false, 'CIE-11'),
('XA85K8', 'Arteria uretral', 'category', false, false, 'CIE-11'),
('XA0610', 'Arteria uterina', 'category', false, false, 'CIE-11'),
('XA47A2', 'Arteria vaginal', 'category', false, false, 'CIE-11'),
('XA83D6', 'Arteria ilíaca', 'category', false, false, 'CIE-11'),
('XA6PZ8', 'Arteria ilíaca común', 'category', false, false, 'CIE-11'),
('XA9MJ1', 'Arteria ilíaca circunfleja profunda', 'category', false, false, 'CIE-11'),
('XA4HL2', 'Arteria ilíaca interna', 'category', false, false, 'CIE-11'),
('XA53T4', 'Arteria ilíaca externa', 'category', false, false, 'CIE-11'),
('XA9QC3', 'Arteria suprarrenal inferior', 'category', false, false, 'CIE-11'),
('XA81N7', 'Arteria de la extremidad superior', 'category', false, false, 'CIE-11'),
('XA0H14', 'Arteria circunfleja humeral anterior', 'category', false, false, 'CIE-11'),
('XA7U09', 'Arteria recurrente cubital anterior', 'category', false, false, 'CIE-11'),
('XA2PP8', 'Arteria interósea anterior', 'category', false, false, 'CIE-11'),
('XA8ZA6', 'Ramas ascendentes de la arteria colateral cubital inferior', 'category', false, false, 'CIE-11'),
('XA38W3', 'Arteria axilar', 'category', false, false, 'CIE-11'),
('XA1138', 'Arteria braquial', 'category', false, false, 'CIE-11'),
('XA5RC6', 'Rama de la red carpiana palmar de la arteria interósea anterior', 'category', false, false, 'CIE-11'),
('XA91T8', 'Ramas al músculo deltoides de la arteria braquial profunda', 'category', false, false, 'CIE-11'),
('XA4RU3', 'Arteria interósea común', 'category', false, false, 'CIE-11'),
('XA3M37', 'Arco palmar profundo', 'category', false, false, 'CIE-11'),
('XA1ES5', 'Ramas descendentes de la arteria colateral cubital Inferior', 'category', false, false, 'CIE-11'),
('XA2UT9', 'Primera arteria metacarpiana dorsal', 'category', false, false, 'CIE-11'),
('XA9F90', 'Arteria cubital inferior colateral', 'category', false, false, 'CIE-11'),
('XA9179', 'Arteria interósea recurrente', 'category', false, false, 'CIE-11'),
('XA2722', 'Arteria colateral medial', 'category', false, false, 'CIE-11'),
('XA8LL2', 'Ramos musculares de la arteria interósea anterior', 'category', false, false, 'CIE-11'),
('XA0GZ0', 'Arco palmar del carpo', 'category', false, false, 'CIE-11'),
('XA2F13', 'Rama palmar de la muñeca de la arteria radial', 'category', false, false, 'CIE-11'),
('XA51P8', 'Arteria interósea posterior', 'category', false, false, 'CIE-11'),
('XA8JY7', 'Arteria recurrente cubital posterior', 'category', false, false, 'CIE-11'),
('XA05L5', 'Arteria principal del pulgar', 'category', false, false, 'CIE-11'),
('XA2PP0', 'Arteria braquial profunda', 'category', false, false, 'CIE-11'),
('XA8RG5', 'Arteria radial', 'category', false, false, 'CIE-11'),
('XA9W25', 'Ramas radiales de la muñeca de la arteria radial', 'category', false, false, 'CIE-11'),
('XA91J7', 'Ramas radiales de la mano de la arteria radial', 'category', false, false, 'CIE-11'),
('XA3SL1', 'Ramas radiales en el antebrazo de la arteria radial', 'category', false, false, 'CIE-11'),
('XA3PZ4', 'Arteria colateral radial', 'category', false, false, 'CIE-11'),
('XA3H61', 'Arteria recurrente radial', 'category', false, false, 'CIE-11'),
('XA62C1', 'Arteria radial del índice', 'category', false, false, 'CIE-11'),
('XA5AG1', 'Arco palmar superficial', 'category', false, false, 'CIE-11'),
('XA5BG5', 'Rama palmar superficial de la arteria radial', 'category', false, false, 'CIE-11'),
('XA0JA6', 'Arteria colateral cubital superior', 'category', false, false, 'CIE-11'),
('XA23B7', 'Arteria cubital', 'category', false, false, 'CIE-11'),
('XA90B4', 'Red arterial carpiana palmar', 'category', false, false, 'CIE-11'),
('XA1VB5', 'Rama palmar profunda de la arteria cubital', 'category', false, false, 'CIE-11'),
('XA9ZJ6', 'Arco dorsal del carpo', 'category', false, false, 'CIE-11'),
('XA44C1', 'Rama carpal dorsal de la arteria radial', 'category', false, false, 'CIE-11'),
('XA7M90', 'Red arterial dorsal del carpo', 'category', false, false, 'CIE-11'),
('XA2YJ5', 'Arteria subescapular', 'category', false, false, 'CIE-11'),
('XA0882', 'Arteria circunfleja humeral posterior', 'category', false, false, 'CIE-11'),
('XA8DW5', 'Arteria de la extremidad inferior', 'category', false, false, 'CIE-11'),
('XA61E8', 'Rama acetabular', 'category', false, false, 'CIE-11'),
('XA91J1', 'Arteria maleolar lateral anterior', 'category', false, false, 'CIE-11'),
('XA4K68', 'Arteria maleolar medial anterior', 'category', false, false, 'CIE-11'),
('XA6CN3', 'Arteria tibial anterior', 'category', false, false, 'CIE-11'),
('XA7BL5', 'Arteria recurrente tibial anterior', 'category', false, false, 'CIE-11'),
('XA5BU3', 'Rama ascendente de la arteria circunfleja femoral lateral', 'category', false, false, 'CIE-11'),
('XA0DB6', 'Rama ascendente de la arteria circunfleja femoral medial', 'category', false, false, 'CIE-11'),
('XA42R8', 'Rama de la arteria genicular inferior medial a poplítea', 'category', false, false, 'CIE-11'),
('XA7WF1', 'Rama de la arteria genicular superiores medial al vasto medial', 'category', false, false, 'CIE-11'),
('XA2DD1', 'Rama de la arteria genicular superior medial a la superficie del fémur y la articulación de la rodilla', 'category', false, false, 'CIE-11'),
('XA4VS8', 'Rama comunicante de la arteria peronea a la arteria tibial anterior', 'category', false, false, 'CIE-11'),
('XA7DF6', 'Rama profunda de la rama descendente de la arteria circunfleja femoral medial', 'category', false, false, 'CIE-11'),
('XA19F5', 'Rama profunda de la arteria genicular superior lateral', 'category', false, false, 'CIE-11'),
('XA3KL5', 'Arteria femoral profunda', 'category', false, false, 'CIE-11'),
('XA3SV6', 'Rama descendente de la arteria circunfleja femoral lateral', 'category', false, false, 'CIE-11'),
('XA15J8', 'Rama descendente de la arteria circunfleja femoral medial', 'category', false, false, 'CIE-11'),
('XA3CV5', 'Arteria descendente de la rodilla', 'category', false, false, 'CIE-11'),
('XA41L4', 'Arteria dorsal del pie', 'category', false, false, 'CIE-11'),
('XA2JF3', 'arteria femoral', 'category', false, false, 'CIE-11'),
('XA9GM6', 'Arteria peroneal', 'category', false, false, 'CIE-11'),
('XA2GU0', 'primera arteria perforante', 'category', false, false, 'CIE-11'),
('XA9EP9', 'Arteria circunfleja fe moral lateral', 'category', false, false, 'CIE-11'),
('XA4B67', 'Arteria genicular inferior lateral', 'category', false, false, 'CIE-11'),
('XA6920', 'Arteria circunfleja femoral medial', 'category', false, false, 'CIE-11'),
('XA1QB3', 'arteria genicular inferior medial', 'category', false, false, 'CIE-11'),
('XA7PN1', 'Arteria plantar medial', 'category', false, false, 'CIE-11'),
('XA5LB1', 'Arteria genicular media', 'category', false, false, 'CIE-11'),
('XA0PT7', 'Ramas musculares de la arteria tibial anterior', 'category', false, false, 'CIE-11'),
('XA9TP5', 'Rama músculo-articular de arteria genicular Descendente', 'category', false, false, 'CIE-11'),
('XA0GA4', 'Arteria perforante', 'category', false, false, 'CIE-11'),
('XA1YF2', 'Rama perforante de la arteria peronea de la arteria tibial posterior', 'category', false, false, 'CIE-11'),
('XA44K1', 'Arteria poplitea', 'category', false, false, 'CIE-11'),
('XA6LK2', 'Arteria tibial posterior', 'category', false, false, 'CIE-11'),
('XA33D9', 'Arteria recurrente tibial posterior', 'category', false, false, 'CIE-11'),
('XA09P5', 'Rama safena de la arteria genicular Descendente', 'category', false, false, 'CIE-11'),
('XA2Z59', 'Segunda arteria perforante', 'category', false, false, 'CIE-11'),
('XA7W56', 'Rama superficial del ramo descendente de la arteria circunfleja femoral Medial', 'category', false, false, 'CIE-11'),
('XA5687', 'Rama superficial de la arteria genicular superior lateral', 'category', false, false, 'CIE-11'),
('XA08Q7', 'Arteria sural', 'category', false, false, 'CIE-11'),
('XA8J55', 'Tercera o cuarta arteria perforante', 'category', false, false, 'CIE-11'),
('XA4XR2', 'Rama transversa de la arteria circunfleja femoral lateral', 'category', false, false, 'CIE-11'),
('XA6QR6', 'Arteria plantar lateral', 'category', false, false, 'CIE-11'),
('XA8YC8', 'Arteria femoral común', 'category', false, false, 'CIE-11'),
('XA5PP5', 'Arteria femoral superficial', 'category', false, false, 'CIE-11'),
('XA9PU5', 'Arteriola aferente de la arteria interlobular', 'category', false, false, 'CIE-11'),
('XA6Y34', 'Aorta', 'category', false, false, 'CIE-11'),
('XA9NQ2', 'Aorta toracoabdominal', 'category', false, false, 'CIE-11'),
('XA5Z66', 'Aorta abdominal', 'category', false, false, 'CIE-11'),
('XA5EX6', 'Aorta abdominal suprarrenal', 'category', false, false, 'CIE-11'),
('XA2LN9', 'Aorta abdominal infrarrenal', 'category', false, false, 'CIE-11'),
('XA5J49', 'Venas', 'category', false, false, 'CIE-11'),
('XA59M2', 'Venas de la cabeza, la cara y el cuello', 'category', false, false, 'CIE-11'),
('XA9TJ8', 'Vena cortical', 'category', false, false, 'CIE-11'),
('XA8ZU5', 'Vena basal', 'category', false, false, 'CIE-11'),
('XA37J7', 'Vena alveolar', 'category', false, false, 'CIE-11'),
('XA8ZS9', 'Vena angular', 'category', false, false, 'CIE-11'),
('XA6HG4', 'Vena temporal', 'category', false, false, 'CIE-11'),
('XA1GE4', 'Vena temporal anterior profunda', 'category', false, false, 'CIE-11'),
('XA8SD6', 'Vena temporal media', 'category', false, false, 'CIE-11'),
('XA30B2', 'Vena temporal posterior profunda', 'category', false, false, 'CIE-11'),
('XA2NX9', 'Vena temporal superficial', 'category', false, false, 'CIE-11'),
('XA6SL1', 'Plexo basilar', 'category', false, false, 'CIE-11'),
('XA5SG1', 'Vena del buccinador', 'category', false, false, 'CIE-11'),
('XA91N0', 'Vena cerebelosa', 'category', false, false, 'CIE-11'),
('XA93W0', 'Vena cerebelosa inferior', 'category', false, false, 'CIE-11'),
('XA2Z35', 'Vena cerebelosa superior', 'category', false, false, 'CIE-11'),
('XA2LX2', 'Vena cerebral', 'category', false, false, 'CIE-11'),
('XA6DC3', 'Vena cerebral interna', 'category', false, false, 'CIE-11'),
('XA1MX7', 'Vena cerebral media profunda', 'category', false, false, 'CIE-11'),
('XA0U80', 'Vena cerebral inferior', 'category', false, false, 'CIE-11'),
('XA43H1', 'Vena cerebral media', 'category', false, false, 'CIE-11'),
('XA4WV6', 'Vena cerebral media superficial', 'category', false, false, 'CIE-11'),
('XA0E47', 'Vena cerebral superior', 'category', false, false, 'CIE-11'),
('XA7VW1', 'Vena cerebral anterior pequeña', 'category', false, false, 'CIE-11'),
('XA18W3', 'Gran vena cerebral', 'category', false, false, 'CIE-11'),
('XA49Y4', 'Vena coroidea', 'category', false, false, 'CIE-11'),
('XA7C08', 'Vena cricotiroidea', 'category', false, false, 'CIE-11'),
('XA9U81', 'Vena cervical profunda', 'category', false, false, 'CIE-11'),
('XA2QB0', 'Vena diploica', 'category', false, false, 'CIE-11'),
('XA6VQ5', 'Vena diploica frontal', 'category', false, false, 'CIE-11'),
('XA6694', 'Vena diploica temporal anterior', 'category', false, false, 'CIE-11'),
('XA5AY0', 'Vena diploica temporal posterior', 'category', false, false, 'CIE-11'),
('XA2HM1', 'Vena diploica occipital', 'category', false, false, 'CIE-11'),
('XA12G2', 'Vena emisaria del agujero de Vesalio', 'category', false, false, 'CIE-11'),
('XA14M4', 'Vena emisaria', 'category', false, false, 'CIE-11'),
('XA6BA1', 'Vena emisaria del cóndilo', 'category', false, false, 'CIE-11'),
('XA4K04', 'Vena emisaria occipital', 'category', false, false, 'CIE-11'),
('XA8C81', 'Vena emisaria mastoidea', 'category', false, false, 'CIE-11'),
('XA0T02', 'Vena emisaria parietal', 'category', false, false, 'CIE-11'),
('XA74U9', 'Vena frontal', 'category', false, false, 'CIE-11'),
('XA0CA3', 'laguna venosa frontal', 'category', false, false, 'CIE-11'),
('XA3DS7', 'Gran vena anastomótica de Trolard', 'category', false, false, 'CIE-11'),
('XA9GT2', 'Vena estriada inferior', 'category', false, false, 'CIE-11'),
('XA4ZZ3', 'Vena maxilar', 'category', false, false, 'CIE-11'),
('XA23C4', 'Vena laríngea', 'category', false, false, 'CIE-11'),
('XA2JH6', 'Vena laríngea inferior', 'category', false, false, 'CIE-11'),
('XA3XZ1', 'Vena laríngea superior', 'category', false, false, 'CIE-11'),
('XA8Z61', 'Vena masetérica', 'category', false, false, 'CIE-11'),
('XA8NY9', 'Vena lingual', 'category', false, false, 'CIE-11'),
('XA4105', 'Vena meníngea', 'category', false, false, 'CIE-11'),
('XA8D07', 'Vena meníngea anterior', 'category', false, false, 'CIE-11'),
('XA5600', 'Vena meníngea media', 'category', false, false, 'CIE-11'),
('XA73V2', 'Vena meníngea posterior', 'category', false, false, 'CIE-11'),
('XA01E7', 'Vena occipital', 'category', false, false, 'CIE-11'),
('XA7AS3', 'Laguna venosa occipital', 'category', false, false, 'CIE-11'),
('XA0X91', 'Vena oftálmica', 'category', false, false, 'CIE-11'),
('XA6C95', 'Vena oftálmica superior', 'category', false, false, 'CIE-11'),
('XA8M04', 'Vena oftálmica inferior', 'category', false, false, 'CIE-11'),
('XA1SM5', 'Vena palatina', 'category', false, false, 'CIE-11'),
('XA4HX4', 'Laguna venosa parietal', 'category', false, false, 'CIE-11'),
('XA91G2', 'Vena parótida', 'category', false, false, 'CIE-11'),
('XA98C1', 'Vena faríngea', 'category', false, false, 'CIE-11'),
('XA2NF3', 'Vena anastomótica posterior de Labbé', 'category', false, false, 'CIE-11'),
('XA0QP2', 'Plexo venoso pterigoideo', 'category', false, false, 'CIE-11'),
('XA0M51', 'Vena esfenopalatina', 'category', false, false, 'CIE-11'),
('XA4XY4', 'Vena estilomastoidea', 'category', false, false, 'CIE-11'),
('XA7K99', 'Vena sublingual', 'category', false, false, 'CIE-11'),
('XA7ZY4', 'Vena submaxilar', 'category', false, false, 'CIE-11'),
('XA1LD6', 'Vena submentoniana', 'category', false, false, 'CIE-11'),
('XA8680', 'Vena terminal', 'category', false, false, 'CIE-11'),
('XA7F45', 'Vena traqueal', 'category', false, false, 'CIE-11'),
('XA6945', 'Vena cervical transversa', 'category', false, false, 'CIE-11'),
('XA22T9', 'Vena de la cavidad timpánica', 'category', false, false, 'CIE-11'),
('XA21F0', 'Vena del ala de la nariz', 'category', false, false, 'CIE-11'),
('XA9914', 'Vena del canal pterigoideo', 'category', false, false, 'CIE-11'),
('XA1RH4', 'Vena satélite del nervio hipogloso', 'category', false, false, 'CIE-11'),
('XA1K34', 'Vena del arco yugular', 'category', false, false, 'CIE-11'),
('XA1VJ8', 'Senos venosos', 'category', false, false, 'CIE-11'),
('XA5WN3', 'Seno cavernoso', 'category', false, false, 'CIE-11'),
('XA4NJ4', 'Confluencia de los senos', 'category', false, false, 'CIE-11'),
('XA6ZV2', 'Seno petroso inferior', 'category', false, false, 'CIE-11'),
('XA9ED6', 'Seno sagital inferior', 'category', false, false, 'CIE-11'),
('XA2SC7', 'Seno occipital', 'category', false, false, 'CIE-11'),
('XA4041', 'Seno sigmoideo', 'category', false, false, 'CIE-11'),
('XA03D2', 'Seno recto', 'category', false, false, 'CIE-11'),
('XA81R3', 'Seno sagital superior', 'category', false, false, 'CIE-11'),
('XA1YP1', 'Seno petroso superior', 'category', false, false, 'CIE-11'),
('XA4289', 'Seno transverso', 'category', false, false, 'CIE-11'),
('XA5255', 'Seno esfenoparietal', 'category', false, false, 'CIE-11'),
('XA3U52', 'Seno intercavernoso', 'category', false, false, 'CIE-11'),
('XA8P44', 'Seno intercavernoso anterior', 'category', false, false, 'CIE-11'),
('XA7QE4', 'Seno intercavernoso posterior', 'category', false, false, 'CIE-11'),
('XA9JS4', 'Seno circular', 'category', false, false, 'CIE-11'),
('XA6UW5', 'Seno petroescamoso', 'category', false, false, 'CIE-11'),
('XA6HK7', 'Seno de la duramadre', 'category', false, false, 'CIE-11'),
('XA5UX2', 'Seno venoso craneal', 'category', false, false, 'CIE-11'),
('XA9VA8', 'Vena tiroidea', 'category', false, false, 'CIE-11'),
('XA2KJ8', 'Vena tiroidea inferior', 'category', false, false, 'CIE-11'),
('XA2DN0', 'Vena tiroidea media', 'category', false, false, 'CIE-11'),
('XA9BZ3', 'Vena tiroidea superior', 'category', false, false, 'CIE-11'),
('XA9SD5', 'Vena palpebral', 'category', false, false, 'CIE-11'),
('XA9K84', 'Vena palpebral inferior', 'category', false, false, 'CIE-11'),
('XA9T11', 'Vena palpebral superior', 'category', false, false, 'CIE-11'),
('XA0Z20', 'Vena palpebral lateral', 'category', false, false, 'CIE-11'),
('XA52V8', 'Vena labial', 'category', false, false, 'CIE-11'),
('XA5DP6', 'Vena labial inferior', 'category', false, false, 'CIE-11'),
('XA4AG1', 'Vena labial superior', 'category', false, false, 'CIE-11'),
('XA97T8', 'Vena auricular', 'category', false, false, 'CIE-11'),
('XA46F3', 'Vena auricular anterior', 'category', false, false, 'CIE-11'),
('XA67N9', 'Vena auricular posterior', 'category', false, false, 'CIE-11'),
('XA0BP3', 'Vena facial', 'category', false, false, 'CIE-11'),
('XA7WC0', 'Vena facial anterior', 'category', false, false, 'CIE-11'),
('XA2681', 'Vena facial profunda', 'category', false, false, 'CIE-11'),
('XA3LQ0', 'Vena facial común', 'category', false, false, 'CIE-11'),
('XA4NP1', 'Vena facial posterior', 'category', false, false, 'CIE-11'),
('XA5GY9', 'Vena facial transversa', 'category', false, false, 'CIE-11'),
('XA4582', 'Vena yugular', 'category', false, false, 'CIE-11'),
('XA9U48', 'Vena yugular anterior', 'category', false, false, 'CIE-11'),
('XA46B9', 'Vena yugular interna', 'category', false, false, 'CIE-11'),
('XA99S7', 'vena yugular externa', 'category', false, false, 'CIE-11'),
('XA31W7', 'Vena yugular externa posterior', 'category', false, false, 'CIE-11'),
('XA9XW7', 'Vena orbital', 'category', false, false, 'CIE-11'),
('XA73J2', 'Vena del pericráneo', 'category', false, false, 'CIE-11'),
('XA0ET2', 'Vena vertebral anterior', 'category', false, false, 'CIE-11'),
('XA1LU7', 'Vena temporal profunda', 'category', false, false, 'CIE-11'),
('XA2L55', 'Vena extraespinal', 'category', false, false, 'CIE-11'),
('XA5YM5', 'Vena auditiva interna', 'category', false, false, 'CIE-11'),
('XA5TG4', 'Plexo pterigoideo', 'category', false, false, 'CIE-11'),
('XA1VP6', 'Vena pterigoidea', 'category', false, false, 'CIE-11'),
('XA1RV1', 'Vena sagital superior', 'category', false, false, 'CIE-11'),
('XA7QR6', 'Vena vertebral', 'category', false, false, 'CIE-11'),
('XA0BP6', 'Plexo venoso vertebral anterior', 'category', false, false, 'CIE-11'),
('XA8CT1', 'Vena del tórax', 'category', false, false, 'CIE-11'),
('XA6DM9', 'Vena hemiácigos accesoria', 'category', false, false, 'CIE-11'),
('XA7AN5', 'Vena ácigos', 'category', false, false, 'CIE-11'),
('XA57F8', 'Vena braquiocefálica', 'category', false, false, 'CIE-11'),
('XA1GY9', 'Vena bronquial', 'category', false, false, 'CIE-11'),
('XA9NE2', 'Vena diafragmática', 'category', false, false, 'CIE-11'),
('XA3VU3', 'Vena esofágica', 'category', false, false, 'CIE-11'),
('XA4GF1', 'Vena hemiácigos', 'category', false, false, 'CIE-11'),
('XA27D1', 'Vena innominada', 'category', false, false, 'CIE-11'),
('XA9HG3', 'Vena intercostal', 'category', false, false, 'CIE-11'),
('XA6JE5', 'Vena mediastinal', 'category', false, false, 'CIE-11'),
('XA6YT2', 'Vena subclavia', 'category', false, false, 'CIE-11'),
('XA3568', 'Vena subcostal', 'category', false, false, 'CIE-11'),
('XA4VD1', 'Vena epigástrica superior', 'category', false, false, 'CIE-11'),
('XA5WA4', 'Vena cava superior', 'category', false, false, 'CIE-11'),
('XA4DR2', 'Vena intercostal suprema', 'category', false, false, 'CIE-11'),
('XA3V69', 'Vena mamaria interna', 'category', false, false, 'CIE-11'),
('XA2DL5', 'Vena escapular transversa', 'category', false, false, 'CIE-11'),
('XA8WJ4', 'Vena subescapular', 'category', false, false, 'CIE-11'),
('XA2YF2', 'Vena tímica', 'category', false, false, 'CIE-11'),
('XA0RA8', 'Vena del abdomen', 'category', false, false, 'CIE-11'),
('XA4DQ4', 'Vena lumbar ascendente', 'category', false, false, 'CIE-11'),
('XA9PF5', 'Vena cabeza de medusa', 'category', false, false, 'CIE-11'),
('XA1MQ4', 'Vena cística', 'category', false, false, 'CIE-11'),
('XA95M2', 'Vena ileocólica', 'category', false, false, 'CIE-11'),
('XA7UV5', 'Vena cava inferior', 'category', false, false, 'CIE-11'),
('XA2UD7', 'Vena hepática', 'category', false, false, 'CIE-11'),
('XA52L9', 'Vena lumbar', 'category', false, false, 'CIE-11'),
('XA3X37', 'Vena pancreática', 'category', false, false, 'CIE-11'),
('XA4XM0', 'Vena pancreática duodenal', 'category', false, false, 'CIE-11'),
('XA0N54', 'Vena paraumbilical', 'category', false, false, 'CIE-11'),
('XA1E17', 'Vena porta', 'category', false, false, 'CIE-11'),
('XA5JV6', 'Plexo venoso rectal', 'category', false, false, 'CIE-11'),
('XA0J33', 'Vena esplénica', 'category', false, false, 'CIE-11'),
('XA46Q0', 'Vena toracoepigástrica', 'category', false, false, 'CIE-11'),
('XA2DK6', 'Vena cólica', 'category', false, false, 'CIE-11'),
('XA2UN4', 'Vena cólica derecha', 'category', false, false, 'CIE-11'),
('XA49E0', 'Vena cólica media', 'category', false, false, 'CIE-11'),
('XA2WF1', 'Vena cólica izquierda', 'category', false, false, 'CIE-11'),
('XA5T10', 'Vena rectal', 'category', false, false, 'CIE-11'),
('XA6NJ4', 'Vena rectal media', 'category', false, false, 'CIE-11'),
('XA80L8', 'Vena rectal inferior', 'category', false, false, 'CIE-11'),
('XA30C9', 'Vena hemorroidal superior', 'category', false, false, 'CIE-11'),
('XA34F0', 'Vena hemorroidal perineal', 'category', false, false, 'CIE-11'),
('XA1EK8', 'Vena frénica', 'category', false, false, 'CIE-11'),
('XA27Y3', 'Vena frénica superior', 'category', false, false, 'CIE-11'),
('XA0EZ6', 'Vena frénica inferior', 'category', false, false, 'CIE-11'),
('XA5KA1', 'Vena mesentérica', 'category', false, false, 'CIE-11'),
('XA4DA7', 'Vena mesentérica superior', 'category', false, false, 'CIE-11'),
('XA4EK2', 'Vena mesentérica inferior', 'category', false, false, 'CIE-11'),
('XA04Q7', 'Vena epigástrica', 'category', false, false, 'CIE-11'),
('XA8WC0', 'Vena epigástrica superficial', 'category', false, false, 'CIE-11'),
('XA30F2', 'Vena epigástrica inferior', 'category', false, false, 'CIE-11'),
('XA1C53', 'Vena del estómago', 'category', false, false, 'CIE-11'),
('XA7CB3', 'vena gástrica', 'category', false, false, 'CIE-11'),
('XA73S8', 'vena gástrica izquierda', 'category', false, false, 'CIE-11'),
('XA23Q4', 'vena gástrica derecha', 'category', false, false, 'CIE-11'),
('XA5QC9', 'vena gástrica corta', 'category', false, false, 'CIE-11'),
('XA2R35', 'vena gastroepiploica', 'category', false, false, 'CIE-11'),
('XA55H2', 'Vena intestinal', 'category', false, false, 'CIE-11'),
('XA26H2', 'Vena de la pelvis', 'category', false, false, 'CIE-11'),
('XA3200', 'Vena renal', 'category', false, false, 'CIE-11'),
('XA6YL8', 'Cuerpo cavernoso del pene', 'category', false, false, 'CIE-11'),
('XA03F7', 'Vena dorsal profunda del pene', 'category', false, false, 'CIE-11'),
('XA9X28', 'Vena iliolumbar', 'category', false, false, 'CIE-11'),
('XA7U63', 'Vena profunda del pene', 'category', false, false, 'CIE-11'),
('XA5AH6', 'Vena obturadora', 'category', false, false, 'CIE-11'),
('XA4PC3', 'Vena ovárica', 'category', false, false, 'CIE-11'),
('XA05M3', 'Plexo pampiniforme', 'category', false, false, 'CIE-11'),
('XA1W18', 'Vena perineal', 'category', false, false, 'CIE-11'),
('XA8WY0', 'Vena prostática', 'category', false, false, 'CIE-11'),
('XA0GG0', 'Vena púbica', 'category', false, false, 'CIE-11'),
('XA8HY5', 'Vena sigmoidea', 'category', false, false, 'CIE-11'),
('XA4TQ4', 'Vena dorsal superficial del pene', 'category', false, false, 'CIE-11'),
('XA2WW4', 'Vena suprarrenal', 'category', false, false, 'CIE-11'),
('XA7AB3', 'Plexo uterino', 'category', false, false, 'CIE-11'),
('XA8M77', 'Vena uterina', 'category', false, false, 'CIE-11'),
('XA1MK5', 'Vena vaginal', 'category', false, false, 'CIE-11'),
('XA0DB7', 'Plexo vesical', 'category', false, false, 'CIE-11'),
('XA7GN4', 'Vena vesical', 'category', false, false, 'CIE-11'),
('XA9GG9', 'Vena vulvar', 'category', false, false, 'CIE-11'),
('XA8GA3', 'Vena glútea', 'category', false, false, 'CIE-11'),
('XA3HW8', 'Vena glútea inferior', 'category', false, false, 'CIE-11'),
('XA47S7', 'Vena glútea superior', 'category', false, false, 'CIE-11'),
('XA03Q4', 'Vena ilíaca', 'category', false, false, 'CIE-11'),
('XA3EG0', 'Vena ilíaca interna', 'category', false, false, 'CIE-11'),
('XA49T5', 'Vena ilíaca externa', 'category', false, false, 'CIE-11'),
('XA7W40', 'Vena ilíaca común', 'category', false, false, 'CIE-11'),
('XA3H93', 'Vena circunfleja ilíaca profunda', 'category', false, false, 'CIE-11'),
('XA71Q4', 'Vena sacra', 'category', false, false, 'CIE-11'),
('XA4PJ8', 'Vena sacra lateral', 'category', false, false, 'CIE-11'),
('XA9Z04', 'Vena sacra media', 'category', false, false, 'CIE-11'),
('XA5KK7', 'Vena espermática', 'category', false, false, 'CIE-11'),
('XA3F81', 'Vena pudenda', 'category', false, false, 'CIE-11'),
('XA7XD2', 'Vena pudenda interna', 'category', false, false, 'CIE-11'),
('XA6NF9', 'Vena pudenda externa superficial', 'category', false, false, 'CIE-11'),
('XA1ET7', 'Vena pudenda externa profunda', 'category', false, false, 'CIE-11'),
('XA6TQ3', 'Vena suprarrenal', 'category', false, false, 'CIE-11'),
('XA9WN7', 'Vena de la extremidad superior', 'category', false, false, 'CIE-11'),
('XA0QT1', 'Vena cefálica accesoria', 'category', false, false, 'CIE-11'),
('XA3EY8', 'Vena axilar', 'category', false, false, 'CIE-11'),
('XA6JD7', 'Vena basílica', 'category', false, false, 'CIE-11'),
('XA43Q5', 'Vena braquial', 'category', false, false, 'CIE-11'),
('XA4YQ8', 'Vena cefálica', 'category', false, false, 'CIE-11'),
('XA7FD2', 'Vena digital palmar común', 'category', false, false, 'CIE-11'),
('XA7902', 'Arco venoso palmar profundo', 'category', false, false, 'CIE-11'),
('XA6NS3', 'Vena interósea dorsal', 'category', false, false, 'CIE-11'),
('XA9886', 'Vena metacarpiana dorsal', 'category', false, false, 'CIE-11'),
('XA4A41', 'Vena torácica lateral', 'category', false, false, 'CIE-11'),
('XA3TW9', 'Vena mediana antebraquial', 'category', false, false, 'CIE-11'),
('XA1YZ7', 'Vena mediana basílica', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
