-- CIE11 Import Part 56
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XM4RK4', 'Elastasa', 'category', false, false, 'CIE-11'),
('XM5H83', 'Enzima intestinal', 'category', false, false, 'CIE-11'),
('XM2Q01', 'Florantirona', 'category', false, false, 'CIE-11'),
('XM5BH7', 'Enzimas gástricas', 'category', false, false, 'CIE-11'),
('XM63F8', 'Genciana', 'category', false, false, 'CIE-11'),
('XM1TN8', 'Jengibre', 'category', false, false, 'CIE-11'),
('XM0994', 'Ácido glutámico', 'category', false, false, 'CIE-11'),
('XM15D5', 'Ácido clorhídrico medicinal (digestivo)', 'category', false, false, 'CIE-11'),
('XM2702', 'Extracto de bilis buey', 'category', false, false, 'CIE-11'),
('XM6HM1', 'Pancreatina', 'category', false, false, 'CIE-11'),
('XM9Z07', 'Pancreolipasa', 'category', false, false, 'CIE-11'),
('XM6DW4', 'Papaina', 'category', false, false, 'CIE-11'),
('XM72V4', 'Digestivo de papaína', 'category', false, false, 'CIE-11'),
('XM1XP0', 'Hierbabuena (aceite)', 'category', false, false, 'CIE-11'),
('XM17U7', 'Digestivo de la pepsina', 'category', false, false, 'CIE-11'),
('XM7L34', 'Fenilpropanol', 'category', false, false, 'CIE-11'),
('XM4U70', 'Tilactasa', 'category', false, false, 'CIE-11'),
('XM4H25', 'Oxalato de cerio', 'category', false, false, 'CIE-11'),
('XM3ME7', 'Cobre emético', 'category', false, false, 'CIE-11'),
('XM9FG8', 'Sulfato de cobre medicinal emético', 'category', false, false, 'CIE-11'),
('XM2WE8', 'Mostaza negra', 'category', false, false, 'CIE-11'),
('XM5SW7', 'Clorobutanol', 'category', false, false, 'CIE-11'),
('XM8SN3', 'Trimetobenzamida', 'category', false, false, 'CIE-11'),
('XM46N1', 'Metopimazine', 'category', false, false, 'CIE-11'),
('XM1DC1', 'Aprepitant', 'category', false, false, 'CIE-11'),
('XM2633', 'Casopitant', 'category', false, false, 'CIE-11'),
('XM41Y6', 'Rolapitant', 'category', false, false, 'CIE-11'),
('XM2170', 'Pipamazina', 'category', false, false, 'CIE-11'),
('XM9FU8', 'Piratiazina', 'category', false, false, 'CIE-11'),
('XM3KJ5', 'Resina de sulfonato de amonio', 'category', false, false, 'CIE-11'),
('XM4KK2', 'Bacilos lactobacilos', 'category', false, false, 'CIE-11'),
('XM4663', 'Carragenano', 'category', false, false, 'CIE-11'),
('XM8NM7', 'Control de veneno con carbón medicinal', 'category', false, false, 'CIE-11'),
('XM4GA5', 'Carbón vegetal para otro uso medicinal especificado distinto que para la diarrea', 'category', false, false, 'CIE-11'),
('XM7ER1', 'Dimetil polisiloxano', 'category', false, false, 'CIE-11'),
('XM30A7', 'Medicamento gastrointestinal biológico', 'category', false, false, 'CIE-11'),
('XM0KJ8', 'Medicamento gastrointestinal especificado', 'category', false, false, 'CIE-11'),
('XM7L13', 'Glucurolactona', 'category', false, false, 'CIE-11'),
('XM9Q94', 'Estimulante de la secreción hepática', 'category', false, false, 'CIE-11'),
('XM7EV4', 'Medicamento de control biológico de la motilidad intestinal', 'category', false, false, 'CIE-11'),
('XM9S11', 'Resina aniónica de intercambio iónico', 'category', false, false, 'CIE-11'),
('XM1AX0', 'Resina de intercambio iónico intestinal', 'category', false, false, 'CIE-11'),
('XM0UP4', 'Extracto de regaliz', 'category', false, false, 'CIE-11'),
('XM8UW6', 'Mesalazina', 'category', false, false, 'CIE-11'),
('XM0TN5', 'Olsalazina', 'category', false, false, 'CIE-11'),
('XM73P5', 'Estimulante de la secreción digestiva pancreática', 'category', false, false, 'CIE-11'),
('XM0EK0', 'Polisilano', 'category', false, false, 'CIE-11'),
('XM2K96', 'Alginato de sodio', 'category', false, false, 'CIE-11'),
('XM7M46', 'Amilosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM7AL9', 'Amilopectina sulfatada', 'category', false, false, 'CIE-11'),
('XM6347', 'Alexitol sódico', 'category', false, false, 'CIE-11'),
('XM8YP0', 'Aluminio, carbonato de aluminio (gel, básico)', 'category', false, false, 'CIE-11'),
('XM3Q55', 'Aluminio, complejo de clorhidróxido de aluminio', 'category', false, false, 'CIE-11'),
('XM9DS4', 'Aluminio, hidróxido de aluminio-magnesio carb. gel', 'category', false, false, 'CIE-11'),
('XM8FL6', 'Aluminio, silicato de aluminio.', 'category', false, false, 'CIE-11'),
('XM0BM4', 'Aluminio, silicato de sodio y aluminio', 'category', false, false, 'CIE-11'),
('XM37S3', 'Antiácido', 'category', false, false, 'CIE-11'),
('XM5XT4', 'Medicamento anti-secreción gástrica', 'category', false, false, 'CIE-11'),
('XM9KD3', 'Benexato', 'category', false, false, 'CIE-11'),
('XM1F19', 'Aluminato de sales de bismuto', 'category', false, false, 'CIE-11'),
('XM5R07', 'Burimamida', 'category', false, false, 'CIE-11'),
('XM7Y04', 'Cetraxato', 'category', false, false, 'CIE-11'),
('XM1WQ5', 'Carbonato de calcio, precipitado', 'category', false, false, 'CIE-11'),
('XM1622', 'Aminoacetato de dihidroxialuminio', 'category', false, false, 'CIE-11'),
('XM9BS9', 'Dimeticona', 'category', false, false, 'CIE-11'),
('XM6YR9', 'Magma de magnesia', 'category', false, false, 'CIE-11'),
('XM7V20', 'Carbonato de magnesio', 'category', false, false, 'CIE-11'),
('XM8L43', 'Trisilicato de magnesio', 'category', false, false, 'CIE-11'),
('XM1EN3', 'Metilpolisiloxano', 'category', false, false, 'CIE-11'),
('XM9414', 'Metiamida', 'category', false, false, 'CIE-11'),
('XM7SH2', 'Leche de magnesia', 'category', false, false, 'CIE-11'),
('XM01K0', 'Ornoprostil', 'category', false, false, 'CIE-11'),
('XM7K87', 'Pepstatina', 'category', false, false, 'CIE-11'),
('XM7W08', 'Glucaldrato de potasio', 'category', false, false, 'CIE-11'),
('XM7Z18', 'Rolaids', 'category', false, false, 'CIE-11'),
('XM87Z0', 'Rosaprostol', 'category', false, false, 'CIE-11'),
('XM64X9', 'Simaldrato', 'category', false, false, 'CIE-11'),
('XM38C5', 'Simeticona', 'category', false, false, 'CIE-11'),
('XM0QL9', 'Bicarbonato de soda', 'category', false, false, 'CIE-11'),
('XM43U8', 'Glucaldrato de sodio', 'category', false, false, 'CIE-11'),
('XM7M59', 'Polihidroxialuminio monocarbonato de sodio', 'category', false, false, 'CIE-11'),
('XM38H3', 'Carbonato triple', 'category', false, false, 'CIE-11'),
('XM5QM5', 'Vitamina ulceroprotectora', 'category', false, false, 'CIE-11'),
('XM8K92', 'Agar', 'category', false, false, 'CIE-11'),
('XM5FL6', 'Aceite de arachis catártico', 'category', false, false, 'CIE-11'),
('XM5993', 'Medicamento para la atonía, intestinal', 'category', false, false, 'CIE-11'),
('XM9281', 'Salvado (trigo)', 'category', false, false, 'CIE-11'),
('XM21B3', 'Volumen de relleno catártico', 'category', false, false, 'CIE-11'),
('XM0ML8', 'Dioctil sulfosuccinato de calcio', 'category', false, false, 'CIE-11'),
('XM0HS3', 'Carboximetil-celulosa', 'category', false, false, 'CIE-11'),
('XM3EV1', 'Carmelosa', 'category', false, false, 'CIE-11'),
('XM99E9', 'Volumen catártico', 'category', false, false, 'CIE-11'),
('XM4DA2', 'Emoliente catártico', 'category', false, false, 'CIE-11'),
('XM2Y48', 'Mucílago catártico', 'category', false, false, 'CIE-11'),
('XM3000', 'Celulosa catártica', 'category', false, false, 'CIE-11'),
('XM22V5', 'Hidroxietil celulosa', 'category', false, false, 'CIE-11'),
('XM6ZN5', 'Dioctil sulfosuccinato (calcio) (sodio)', 'category', false, false, 'CIE-11'),
('XM2UB3', 'Etilhidroxicelulosa', 'category', false, false, 'CIE-11'),
('XM6CL0', 'Ablandador fecal', 'category', false, false, 'CIE-11'),
('XM1RJ7', 'Fibra, dietética', 'category', false, false, 'CIE-11'),
('XM4A22', 'Cáscara de Ispágula', 'category', false, false, 'CIE-11'),
('XM1J98', 'Karaya (goma)', 'category', false, false, 'CIE-11'),
('XM5CR2', 'Konsyl', 'category', false, false, 'CIE-11'),
('XM2J55', 'Metamucil', 'category', false, false, 'CIE-11'),
('XM0X73', 'Laxante de metilcelulosa', 'category', false, false, 'CIE-11'),
('XM5VW0', 'Mucílago, planta', 'category', false, false, 'CIE-11'),
('XM1VV2', 'Aceite de oliva (medicinal)', 'category', false, false, 'CIE-11'),
('XM3CM0', 'Aceite de melocotón (emulsión)', 'category', false, false, 'CIE-11'),
('XM85Z3', 'Aceite de maní (emulsión)', 'category', false, false, 'CIE-11'),
('XM4PD5', 'Fosfato laxante', 'category', false, false, 'CIE-11'),
('XM95P7', 'Poloxámero', 'category', false, false, 'CIE-11'),
('XM9PF1', 'Policarbofilo', 'category', false, false, 'CIE-11'),
('XM4YU2', 'Psyllium hydrophilic mucilloid', 'category', false, false, 'CIE-11'),
('XM0ZU4', 'Enema de jabón', 'category', false, false, 'CIE-11'),
('XM6J59', 'Dioctil sulfosuccinato de sodio', 'category', false, false, 'CIE-11'),
('XM3DH4', 'Tartrato, laxante', 'category', false, false, 'CIE-11'),
('XM69K0', 'Catártico salino', 'category', false, false, 'CIE-11'),
('XM40M7', 'Sal de Epsom', 'category', false, false, 'CIE-11'),
('XM4WX6', 'Laxante osmótico', 'category', false, false, 'CIE-11'),
('XM5NK8', 'Laxante salino', 'category', false, false, 'CIE-11'),
('XM06D3', 'Bisulfato de potasio', 'category', false, false, 'CIE-11'),
('XM9P20', 'Aloes', 'category', false, false, 'CIE-11'),
('XM6UQ2', 'Aloína', 'category', false, false, 'CIE-11'),
('XM9N98', 'Brionia', 'category', false, false, 'CIE-11'),
('XM9YN3', 'Pequeñas píldoras de Carter', 'category', false, false, 'CIE-11'),
('XM2632', 'Derivado de antraceno catártico', 'category', false, false, 'CIE-11'),
('XM3W96', 'Catártico de contacto', 'category', false, false, 'CIE-11'),
('XM53Q7', 'Catártico irritante', 'category', false, false, 'CIE-11'),
('XM6LH5', 'Catártico vegetal', 'category', false, false, 'CIE-11'),
('XM0JN3', 'Colocinta', 'category', false, false, 'CIE-11'),
('XM4217', 'Crotón (aceite)', 'category', false, false, 'CIE-11'),
('XM4C29', 'Diamtona', 'category', false, false, 'CIE-11'),
('XM8PF5', 'Dihidroxiantraquinona', 'category', false, false, 'CIE-11'),
('XM77A6', 'Dulcolax', 'category', false, false, 'CIE-11'),
('XM9KZ8', 'Elaterio', 'category', false, false, 'CIE-11'),
('XM6CR4', 'Ex-Lax (fenolftaleína)', 'category', false, false, 'CIE-11'),
('XM7XD6', 'Frángula', 'category', false, false, 'CIE-11'),
('XM6L10', 'Extracto de frángula', 'category', false, false, 'CIE-11'),
('XM1L58', 'Gamboge', 'category', false, false, 'CIE-11'),
('XM1RP5', 'Píldoras de HInKle', 'category', false, false, 'CIE-11'),
('XM6XG3', 'Jalapa', 'category', false, false, 'CIE-11'),
('XM9DZ3', 'Emulsión de aceite mineral', 'category', false, false, 'CIE-11'),
('XM4CS7', 'Fenisatina', 'category', false, false, 'CIE-11'),
('XM5042', 'Sulfato de potasio', 'category', false, false, 'CIE-11'),
('XM14Q1', 'Extracto seco de ruibarbo', 'category', false, false, 'CIE-11'),
('XM40D1', 'Tintura de ruibarbo, compuesto', 'category', false, false, 'CIE-11'),
('XM38T6', 'Escamonea', 'category', false, false, 'CIE-11'),
('XM91P4', 'Senósido A + B', 'category', false, false, 'CIE-11'),
('XM9ML9', 'Fosfato de sodio dibásico', 'category', false, false, 'CIE-11'),
('XM38A9', 'Fosfato de sodio monobásico', 'category', false, false, 'CIE-11'),
('XM7XV5', 'Pepino squirting (catártico)', 'category', false, false, 'CIE-11'),
('XM8WQ0', 'Sulisatina', 'category', false, false, 'CIE-11'),
('XM69R3', 'Fenolftaleina amarilla', 'category', false, false, 'CIE-11'),
('XM1NY1', 'Suavizantes o emolientes', 'category', false, false, 'CIE-11'),
('XM8UE2', 'Parafina líquida', 'category', false, false, 'CIE-11'),
('XM59Z2', 'Docusato de sodio', 'category', false, false, 'CIE-11'),
('XM5CM0', 'Laxantes de contacto', 'category', false, false, 'CIE-11'),
('XM5E72', 'Oxifenisatina', 'category', false, false, 'CIE-11'),
('XM14G1', 'Bisacodilo', 'category', false, false, 'CIE-11'),
('XM86Q2', 'Dantron', 'category', false, false, 'CIE-11'),
('XM30Q0', 'Fenolftaleína', 'category', false, false, 'CIE-11'),
('XM7G77', 'Aceite castor', 'category', false, false, 'CIE-11'),
('XM9LC4', 'Glucósidos de sen', 'category', false, false, 'CIE-11'),
('XM8YN7', 'Picosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM00W5', 'Bisoxatina', 'category', false, false, 'CIE-11'),
('XM8N88', 'Cascara', 'category', false, false, 'CIE-11'),
('XM42M0', 'Laxantes formadores de masa', 'category', false, false, 'CIE-11'),
('XM9JR8', 'Esterculia', 'category', false, false, 'CIE-11'),
('XM3VP9', 'Linaza', 'category', false, false, 'CIE-11'),
('XM5DN2', 'Metilcelulosa', 'category', false, false, 'CIE-11'),
('XM3JB5', 'Ispágula (plantago ovata)', 'category', false, false, 'CIE-11'),
('XM0LV6', 'Ethulose', 'category', false, false, 'CIE-11'),
('XM4SJ2', 'Triticum (fibra de trigo)', 'category', false, false, 'CIE-11'),
('XM5BR4', 'Calcio policarbofilo', 'category', false, false, 'CIE-11'),
('XM2806', 'Laxantes de acción osmótica', 'category', false, false, 'CIE-11'),
('XM7G33', 'Óxido de magnesio', 'category', false, false, 'CIE-11'),
('XM6EC7', 'Sulfato de magnesio', 'category', false, false, 'CIE-11'),
('XM3CD3', 'Peróxido de magnesio', 'category', false, false, 'CIE-11'),
('XM7W31', 'Lactulosa', 'category', false, false, 'CIE-11'),
('XM6AX9', 'Sulfato de sodio', 'category', false, false, 'CIE-11'),
('XM6FQ8', 'Macrogol', 'category', false, false, 'CIE-11'),
('XM9YJ1', 'Sorbitol', 'category', false, false, 'CIE-11'),
('XM4RE1', 'Lactitol', 'category', false, false, 'CIE-11'),
('XM7RN6', 'Pentaeritritilo', 'category', false, false, 'CIE-11'),
('XM5348', 'Glicerol', 'category', false, false, 'CIE-11'),
('XM7DT2', 'Fármacos productores de dióxido de carbono', 'category', false, false, 'CIE-11'),
('XM4U05', 'Lubiprostona', 'category', false, false, 'CIE-11'),
('XM3086', 'Linaclotida', 'category', false, false, 'CIE-11'),
('XM2396', 'Prucaloprida', 'category', false, false, 'CIE-11'),
('XM2SC1', 'Tegaserod', 'category', false, false, 'CIE-11'),
('XM78V7', 'Plecanatida', 'category', false, false, 'CIE-11'),
('XM6DL1', 'Aceite', 'category', false, false, 'CIE-11'),
('XM3XX3', 'Metoclopramida', 'category', false, false, 'CIE-11'),
('XM3346', 'Cisaprida', 'category', false, false, 'CIE-11'),
('XM3GF5', 'Domperidona', 'category', false, false, 'CIE-11'),
('XM2Q19', 'Bromoprida', 'category', false, false, 'CIE-11'),
('XM6AH6', 'Alizaprida', 'category', false, false, 'CIE-11'),
('XM4GL7', 'Cleboprida', 'category', false, false, 'CIE-11'),
('XM2KJ6', 'Itoprida', 'category', false, false, 'CIE-11'),
('XM1W04', 'Cinitaprida', 'category', false, false, 'CIE-11'),
('XM6ZM7', 'Mosaprida', 'category', false, false, 'CIE-11'),
('XM8136', 'Eluxadolina', 'category', false, false, 'CIE-11'),
('XM09D9', 'Agentes alquilantes', 'category', false, false, 'CIE-11'),
('XM06G0', 'Análogos de la mostaza nitrogenada', 'category', false, false, 'CIE-11'),
('XM7SY9', 'Ciclofosfamida', 'category', false, false, 'CIE-11'),
('XM5TX7', 'Clorambucilo', 'category', false, false, 'CIE-11'),
('XM2VC7', 'Melfalan', 'category', false, false, 'CIE-11'),
('XM9W18', 'Clormetina', 'category', false, false, 'CIE-11'),
('XM7FY4', 'Ifosfamida', 'category', false, false, 'CIE-11'),
('XM4EP0', 'Trofosfamida', 'category', false, false, 'CIE-11'),
('XM4NR8', 'Prednimustina', 'category', false, false, 'CIE-11'),
('XM45K9', 'Bendamustina', 'category', false, false, 'CIE-11'),
('XM0DA1', 'Melfalán flufenamida', 'category', false, false, 'CIE-11'),
('XM3WS2', 'Alquilsulfonatos', 'category', false, false, 'CIE-11'),
('XM7WX6', 'Busulfan', 'category', false, false, 'CIE-11'),
('XM9CR4', 'Treosulfan', 'category', false, false, 'CIE-11'),
('XM4TU0', 'Manosulfan', 'category', false, false, 'CIE-11'),
('XM66A3', 'Etileniminas', 'category', false, false, 'CIE-11'),
('XM8QS9', 'Tiotepa', 'category', false, false, 'CIE-11'),
('XM2RU1', 'Triaziquona', 'category', false, false, 'CIE-11'),
('XM8A50', 'Carboquone', 'category', false, false, 'CIE-11'),
('XM9708', 'Nitrosoureas', 'category', false, false, 'CIE-11'),
('XM82H4', 'Carmustina', 'category', false, false, 'CIE-11'),
('XM2G49', 'Lomustina', 'category', false, false, 'CIE-11'),
('XM0VS7', 'Semustina', 'category', false, false, 'CIE-11'),
('XM5GB0', 'Estreptozocina', 'category', false, false, 'CIE-11'),
('XM1KF0', 'Nimustina', 'category', false, false, 'CIE-11'),
('XM9KU3', 'Uramustina', 'category', false, false, 'CIE-11'),
('XM5RH5', 'Fotemustina', 'category', false, false, 'CIE-11'),
('XM64P5', 'Ranimustina', 'category', false, false, 'CIE-11'),
('XM4KL3', 'Etoglucid', 'category', false, false, 'CIE-11'),
('XM31W0', 'MItobronitol', 'category', false, false, 'CIE-11'),
('XM0MB5', 'Pipobroman', 'category', false, false, 'CIE-11'),
('XM3VF4', 'Temozolomida', 'category', false, false, 'CIE-11'),
('XM32Y8', 'Dacarbazina', 'category', false, false, 'CIE-11'),
('XM7Y28', 'Éter Bis (clorometílico)', 'category', false, false, 'CIE-11'),
('XM4DQ8', 'Análogos de ácido fólico', 'category', false, false, 'CIE-11'),
('XM7KT0', 'Metotrexato', 'category', false, false, 'CIE-11'),
('XM1SK9', 'Mercaptopurina', 'category', false, false, 'CIE-11'),
('XM3FP5', 'Tioguanina', 'category', false, false, 'CIE-11'),
('XM5NF9', 'Raltitrexed', 'category', false, false, 'CIE-11'),
('XM16W8', 'Pemetrexed', 'category', false, false, 'CIE-11'),
('XM06R0', 'Pralatrexate', 'category', false, false, 'CIE-11'),
('XM71S1', 'Análogo de la purina', 'category', false, false, 'CIE-11'),
('XM3ZN1', 'Citarabina', 'category', false, false, 'CIE-11'),
('XM55V5', 'Fluorouracilo', 'category', false, false, 'CIE-11'),
('XM10L4', 'Tegafur', 'category', false, false, 'CIE-11'),
('XM6CQ5', 'Carmofur', 'category', false, false, 'CIE-11'),
('XM92X1', 'Azacitidina', 'category', false, false, 'CIE-11'),
('XM1055', 'Cladribina', 'category', false, false, 'CIE-11'),
('XM9RH9', 'Fludarabina', 'category', false, false, 'CIE-11'),
('XM2YA3', 'Clofarabina', 'category', false, false, 'CIE-11'),
('XM6079', 'Nelarabina', 'category', false, false, 'CIE-11'),
('XM9584', 'Análogos de pirimidina', 'category', false, false, 'CIE-11'),
('XM0YN9', 'Trifluridina, combinaciones', 'category', false, false, 'CIE-11'),
('XM8GX9', 'Gemcitabina', 'category', false, false, 'CIE-11'),
('XM40Y4', 'Capecitabina', 'category', false, false, 'CIE-11'),
('XM1458', 'Decitabina', 'category', false, false, 'CIE-11'),
('XM7GE5', 'Aminopterina de sodio', 'category', false, false, 'CIE-11'),
('XM3264', 'Antibiótico anti cáncer', 'category', false, false, 'CIE-11'),
('XM8T13', 'Antimetabolito', 'category', false, false, 'CIE-11'),
('XM9D05', 'Antibióticos antineoplásicos', 'category', false, false, 'CIE-11'),
('XM4TR6', 'Azaribina', 'category', false, false, 'CIE-11'),
('XM3HR8', 'Broxuridina', 'category', false, false, 'CIE-11'),
('XM3A97', 'Cloropurina', 'category', false, false, 'CIE-11'),
('XM1BL2', 'Doxifluridina', 'category', false, false, 'CIE-11'),
('XM5ZK1', 'Enocitabina', 'category', false, false, 'CIE-11'),
('XM2SL0', 'Antagonista del ácido fólico', 'category', false, false, 'CIE-11'),
('XM0KZ3', 'Mopidamol', 'category', false, false, 'CIE-11'),
('XM2FK2', 'Antagonista de pirimidina', 'category', false, false, 'CIE-11'),
('XM6137', 'Alcaloides y análogos de la vinca', 'category', false, false, 'CIE-11'),
('XM0BG8', 'Vinblastina', 'category', false, false, 'CIE-11'),
('XM82R6', 'Vincristina', 'category', false, false, 'CIE-11'),
('XM59U2', 'Vindesina', 'category', false, false, 'CIE-11'),
('XM1Y07', 'Vinorelbina', 'category', false, false, 'CIE-11'),
('XM9QY3', 'Vinflunina', 'category', false, false, 'CIE-11'),
('XM9DS3', 'Vintafolide', 'category', false, false, 'CIE-11'),
('XM3SH7', 'Derivados de podofilotoxina', 'category', false, false, 'CIE-11'),
('XM9VL7', 'Etopósido', 'category', false, false, 'CIE-11'),
('XM4565', 'Teniposido', 'category', false, false, 'CIE-11'),
('XM05L1', 'Taxanos', 'category', false, false, 'CIE-11'),
('XM5TC8', 'Paclitaxel', 'category', false, false, 'CIE-11'),
('XM5U86', 'Docetaxel', 'category', false, false, 'CIE-11'),
('XM9NR6', 'Paclitaxel poliglumex', 'category', false, false, 'CIE-11'),
('XM50E3', 'Cabazitaxel', 'category', false, false, 'CIE-11'),
('XM6F82', 'Actinomicina C', 'category', false, false, 'CIE-11'),
('XM7K70', 'Demecolcina', 'category', false, false, 'CIE-11'),
('XM3F90', 'Trabectedina', 'category', false, false, 'CIE-11'),
('XM4DQ7', 'Antibióticos citotóxicos y sustancias relacionadas', 'category', false, false, 'CIE-11'),
('XM5GC9', 'Antraciclinas y sustancias afines', 'category', false, false, 'CIE-11'),
('XM7JU8', 'Doxorubicina', 'category', false, false, 'CIE-11'),
('XM0031', 'Daunorubicina', 'category', false, false, 'CIE-11'),
('XM6LT8', 'Epirubicina', 'category', false, false, 'CIE-11'),
('XM1VB7', 'Aclarubicina', 'category', false, false, 'CIE-11'),
('XM9R95', 'Zorubicina', 'category', false, false, 'CIE-11'),
('XM3PF9', 'Idarubicina', 'category', false, false, 'CIE-11'),
('XM26H0', 'Mitoxantrona', 'category', false, false, 'CIE-11'),
('XM4AY9', 'Pirarubicina', 'category', false, false, 'CIE-11'),
('XM9CA4', 'Valrubicina', 'category', false, false, 'CIE-11'),
('XM3J03', 'Amrubicina', 'category', false, false, 'CIE-11'),
('XM8ZP9', 'Pixantrona', 'category', false, false, 'CIE-11'),
('XM0VU1', 'Bleomicina', 'category', false, false, 'CIE-11'),
('XM3JL4', 'Plicamicina', 'category', false, false, 'CIE-11'),
('XM21Z8', 'Mitomicina', 'category', false, false, 'CIE-11'),
('XM65P2', 'Ixabepilona', 'category', false, false, 'CIE-11'),
('XM4RQ4', 'Inhibidores de la tirosina quinasa del receptor del factor de crecimiento de fibroblastos', 'category', false, false, 'CIE-11'),
('XM52L2', 'Edrecolomab', 'category', false, false, 'CIE-11'),
('XM3AY3', 'Rituximab', 'category', false, false, 'CIE-11'),
('XM2FU8', 'Trastuzumab', 'category', false, false, 'CIE-11'),
('XM1WL2', 'Gemtuzumab ozogamicina', 'category', false, false, 'CIE-11'),
('XM3VL3', 'Cetuximab', 'category', false, false, 'CIE-11'),
('XM5ST9', 'Bevacizumab', 'category', false, false, 'CIE-11'),
('XM1GA2', 'Panitumumab', 'category', false, false, 'CIE-11'),
('XM9P40', 'Catumaxomab', 'category', false, false, 'CIE-11'),
('XM2KB4', 'Ofatumumab', 'category', false, false, 'CIE-11'),
('XM5JH7', 'Ipilimumab', 'category', false, false, 'CIE-11'),
('XM5VT7', 'Brentuximab vedotin', 'category', false, false, 'CIE-11'),
('XM6618', 'Pertuzumab', 'category', false, false, 'CIE-11'),
('XM6H29', 'Trastuzumab emtansina', 'category', false, false, 'CIE-11'),
('XM6ES5', 'Obinutuzumab', 'category', false, false, 'CIE-11'),
('XM74W8', 'Dinutuximab', 'category', false, false, 'CIE-11'),
('XM6M26', 'Nivolumab', 'category', false, false, 'CIE-11'),
('XM8UG5', 'Pembrolizumab', 'category', false, false, 'CIE-11'),
('XM9BU9', 'Blinatumomab', 'category', false, false, 'CIE-11'),
('XM6Y05', 'Ramucirumab', 'category', false, false, 'CIE-11'),
('XM5WX4', 'Necitumumab', 'category', false, false, 'CIE-11'),
('XM10Z6', 'Elotuzumab', 'category', false, false, 'CIE-11'),
('XM4ES5', 'Daratumumab', 'category', false, false, 'CIE-11'),
('XM3JP4', 'Mogamulizumab', 'category', false, false, 'CIE-11'),
('XM8648', 'Inotuzumab ozogamicina', 'category', false, false, 'CIE-11'),
('XM3DU2', 'Olaratumab', 'category', false, false, 'CIE-11'),
('XM7NY5', 'Durvalumab', 'category', false, false, 'CIE-11'),
('XM6PT2', 'Ermekumab', 'category', false, false, 'CIE-11'),
('XM2065', 'Avelumab', 'category', false, false, 'CIE-11'),
('XM8SU2', 'Atezolizumab', 'category', false, false, 'CIE-11'),
('XM9Z80', 'Cemiplimab', 'category', false, false, 'CIE-11'),
('XM5WX2', 'Alemtuzumab', 'category', false, false, 'CIE-11'),
('XM8LF5', 'Erenumab', 'category', false, false, 'CIE-11'),
('XM4XM4', 'Galcanezumab', 'category', false, false, 'CIE-11'),
('XM47L7', 'Fremanezumab', 'category', false, false, 'CIE-11'),
('XM46X2', 'Ubrogepant', 'category', false, false, 'CIE-11'),
('XM1D23', 'Eptinezumab', 'category', false, false, 'CIE-11'),
('XM8C95', 'Rimegepant', 'category', false, false, 'CIE-11'),
('XM4W34', 'Atogepant', 'category', false, false, 'CIE-11'),
('XM3T47', 'Sensibilizadores utilizados en terapia por radiación o fotodinámica', 'category', false, false, 'CIE-11'),
('XM8EW4', 'Porfímero de sodio', 'category', false, false, 'CIE-11'),
('XM5GF8', 'Aminolevulinato de metilo', 'category', false, false, 'CIE-11'),
('XM40J3', 'Ácido aminolevulínico', 'category', false, false, 'CIE-11'),
('XM04X3', 'Temoporfin', 'category', false, false, 'CIE-11'),
('XM2BE2', 'Efaproxiral', 'category', false, false, 'CIE-11'),
('XM1ER6', 'Padeliporfina', 'category', false, false, 'CIE-11'),
('XM40B7', 'Compuestos de platino', 'category', false, false, 'CIE-11'),
('XM05M0', 'Cisplatino', 'category', false, false, 'CIE-11'),
('XM6Z30', 'Carboplatino', 'category', false, false, 'CIE-11'),
('XM2LX1', 'Oxaliplatino', 'category', false, false, 'CIE-11'),
('XM86Z5', 'Satraplatino', 'category', false, false, 'CIE-11'),
('XM0FB2', 'Polyplatillen', 'category', false, false, 'CIE-11'),
('XM1MP7', 'Procarbazina', 'category', false, false, 'CIE-11'),
('XM8307', 'Amsacrina', 'category', false, false, 'CIE-11'),
('XM4LJ7', 'Asparaginasa', 'category', false, false, 'CIE-11'),
('XM9YD3', 'Altretamina', 'category', false, false, 'CIE-11'),
('XM7SD2', 'Hidroxicarbamida', 'category', false, false, 'CIE-11'),
('XM3R45', 'Lonidamina', 'category', false, false, 'CIE-11'),
('XM9JX7', 'Estramustina', 'category', false, false, 'CIE-11'),
('XM9DB5', 'Tretinoína', 'category', false, false, 'CIE-11'),
('XM9T72', 'Pentostatina', 'category', false, false, 'CIE-11'),
('XM2Q11', 'Mitoguazona', 'category', false, false, 'CIE-11'),
('XM7PT2', 'Venetoclax', 'category', false, false, 'CIE-11'),
('XM1NF7', 'Vosaroxin', 'category', false, false, 'CIE-11'),
('XM1DL2', 'Niraparib', 'category', false, false, 'CIE-11'),
('XM2G84', 'Rucaparib', 'category', false, false, 'CIE-11'),
('XM0569', 'Etirinotecan pegol', 'category', false, false, 'CIE-11'),
('XM8UF4', 'Plitidepsin', 'category', false, false, 'CIE-11'),
('XM8QL8', 'Epacadostat', 'category', false, false, 'CIE-11'),
('XM8NP2', 'Enasidenib', 'category', false, false, 'CIE-11'),
('XM5QR0', 'Talazoparib', 'category', false, false, 'CIE-11'),
('XM44N1', 'Copanlisib', 'category', false, false, 'CIE-11'),
('XM10P3', 'Mitotano', 'category', false, false, 'CIE-11'),
('XM56L5', 'Ivosidenib', 'category', false, false, 'CIE-11'),
('XM6038', 'Glasdegib', 'category', false, false, 'CIE-11'),
('XM7FX3', 'Entinostat', 'category', false, false, 'CIE-11'),
('XM3BC1', 'Alpelisib', 'category', false, false, 'CIE-11'),
('XM1840', 'Selinexor', 'category', false, false, 'CIE-11'),
('XM4MB0', 'Tagraxofusp', 'category', false, false, 'CIE-11'),
('XM7RN1', 'Belotecan', 'category', false, false, 'CIE-11'),
('XM5A01', 'Holmium-166', 'category', false, false, 'CIE-11'),
('XM2HS5', 'Trióxido de arsénico', 'category', false, false, 'CIE-11'),
('XM3ST0', 'Medicamento alquilante antimieloproliferativo', 'category', false, false, 'CIE-11'),
('XM9DP5', 'Medicamento alquilante linfático', 'category', false, false, 'CIE-11'),
('XM6AB6', 'Droga alquilante', 'category', false, false, 'CIE-11'),
('XM0JA8', 'Hexaleno', 'category', false, false, 'CIE-11'),
('XM07W3', 'Antramicina', 'category', false, false, 'CIE-11'),
('XM9F82', 'Agentes anticancerígenos', 'category', false, false, 'CIE-11'),
('XM3MH4', 'Agentes antimicóticos', 'category', false, false, 'CIE-11'),
('XM6Q44', 'Antineoplástico sin especificación adicional.', 'category', false, false, 'CIE-11'),
('XM0V25', 'Alcaloide antineoplásico', 'category', false, false, 'CIE-11'),
('XM4DV2', 'Combinación antineoplásica', 'category', false, false, 'CIE-11'),
('XM1Q78', 'Azaserina', 'category', false, false, 'CIE-11'),
('XM0TE5', 'Azatepa', 'category', false, false, 'CIE-11'),
('XM7WD3', 'Benzcarbimina', 'category', false, false, 'CIE-11'),
('XM3WB5', 'Cactinomicina', 'category', false, false, 'CIE-11'),
('XM7RS5', 'Régimen de quimioterapia contra el cáncer', 'category', false, false, 'CIE-11'),
('XM6Z55', 'Clorhexamida', 'category', false, false, 'CIE-11'),
('XM3ZJ5', 'Fosfato crómico F-32', 'category', false, false, 'CIE-11'),
('XM5VY1', 'Cromomicina A3', 'category', false, false, 'CIE-11'),
('XM6ZM0', 'Corynebacterium parvum', 'category', false, false, 'CIE-11'),
('XM8C02', 'Cicloleucina', 'category', false, false, 'CIE-11'),
('XM7L47', 'Dactinomicina', 'category', false, false, 'CIE-11'),
('XM0HK3', 'Acetato de Eliptinio', 'category', false, false, 'CIE-11'),
('XM32L4', 'CAF ( ciclofosfamida + doxorubicin +fluorouracilo)', 'category', false, false, 'CIE-11'),
('XM8NR1', 'Floxuridina', 'category', false, false, 'CIE-11'),
('XM9FT7', 'Terapia hormonal del cáncer', 'category', false, false, 'CIE-11'),
('XM5UH8', 'Imidazol-4-carboxamida', 'category', false, false, 'CIE-11'),
('XM2D46', 'Improquona', 'category', false, false, 'CIE-11'),
('XM5DL7', 'Iproplatino', 'category', false, false, 'CIE-11'),
('XM8C52', 'M-vac', 'category', false, false, 'CIE-11'),
('XM8XQ7', 'Manomustina', 'category', false, false, 'CIE-11'),
('XM33V8', 'Matulane', 'category', false, false, 'CIE-11'),
('XM1NW0', 'Metoprina', 'category', false, false, 'CIE-11'),
('XM6VK8', 'Mitolactol', 'category', false, false, 'CIE-11'),
('XM3A89', 'Mitopodozida', 'category', false, false, 'CIE-11'),
('XM3L39', 'MOPP (mecloret-amina + vincristina + prednisona + procarbazina)', 'category', false, false, 'CIE-11'),
('XM4582', 'Mostaza (emético)', 'category', false, false, 'CIE-11'),
('XM6MP1', 'Mielobromal', 'category', false, false, 'CIE-11'),
('XM5C25', 'Mileran', 'category', false, false, 'CIE-11'),
('XM5MX5', 'Olivomicina', 'category', false, false, 'CIE-11'),
('XM9TL3', 'Oncovin', 'category', false, false, 'CIE-11'),
('XM7TK6', 'Paroxipropiona', 'category', false, false, 'CIE-11'),
('XM7040', 'Peplomicina', 'category', false, false, 'CIE-11'),
('XM7NL0', 'Fenil hidrazina antineoplásica', 'category', false, false, 'CIE-11'),
('XM03S1', 'Mostaza fenilalanina', 'category', false, false, 'CIE-11'),
('XM7S82', 'Porfiromicina', 'category', false, false, 'CIE-11'),
('XM6QJ7', 'Pteroiltriglutamato', 'category', false, false, 'CIE-11'),
('XM2CG3', 'Razoxano', 'category', false, false, 'CIE-11'),
('XM9TR7', 'Rufocromomicina', 'category', false, false, 'CIE-11'),
('XM4ZA6', 'Sarcolisina', 'category', false, false, 'CIE-11'),
('XM1TG4', 'Sarkomicina', 'category', false, false, 'CIE-11'),
('XM5FB8', 'Tauromustina', 'category', false, false, 'CIE-11'),
('XM0L32', 'TEFA', 'category', false, false, 'CIE-11'),
('XM3SV7', 'Triclormetina', 'category', false, false, 'CIE-11'),
('XM5FH3', 'Triclorotrietilamina', 'category', false, false, 'CIE-11'),
('XM7TR9', 'Trietanomelamina', 'category', false, false, 'CIE-11'),
('XM9T22', 'Trietilenemelamina', 'category', false, false, 'CIE-11'),
('XM6NM1', 'Trietilenefosforamida', 'category', false, false, 'CIE-11'),
('XM5GV6', 'Trietilenetiofosforamida', 'category', false, false, 'CIE-11'),
('XM4J62', 'Trimustina', 'category', false, false, 'CIE-11'),
('XM6A19', 'Uracil mostaza', 'category', false, false, 'CIE-11'),
('XM9AV3', 'Uretano', 'category', false, false, 'CIE-11'),
('XM1DU5', 'Cinostatina', 'category', false, false, 'CIE-11'),
('XM4KU8', 'Masoprocol', 'category', false, false, 'CIE-11'),
('XM7ST9', 'Topotecán', 'category', false, false, 'CIE-11'),
('XM3ZR1', 'Tiazofurine', 'category', false, false, 'CIE-11'),
('XM0992', 'Irinotecan', 'category', false, false, 'CIE-11'),
('XM8200', 'Alitretinoina', 'category', false, false, 'CIE-11'),
('XM6AL6', 'Pegaspargase', 'category', false, false, 'CIE-11'),
('XM3NJ7', 'Bexarotene', 'category', false, false, 'CIE-11'),
('XM6027', 'Denileukin diftitox', 'category', false, false, 'CIE-11'),
('XM5Z86', 'Bortezomib', 'category', false, false, 'CIE-11'),
('XM2PZ5', 'Anagrelide', 'category', false, false, 'CIE-11'),
('XM1NQ8', 'Oblimersen', 'category', false, false, 'CIE-11'),
('XM3VC2', 'Sitimagene ceradenovec', 'category', false, false, 'CIE-11'),
('XM7R04', 'Vorinostat', 'category', false, false, 'CIE-11'),
('XM91S2', 'Romidepsin', 'category', false, false, 'CIE-11'),
('XM3RX2', 'Omacetaxina mepesuccinato', 'category', false, false, 'CIE-11'),
('XM3BC3', 'Eribulina', 'category', false, false, 'CIE-11'),
('XM96L9', 'Panobinostat', 'category', false, false, 'CIE-11'),
('XM0N96', 'Vismodegib', 'category', false, false, 'CIE-11'),
('XM4XD1', 'Aflibercept', 'category', false, false, 'CIE-11'),
('XM0A07', 'Carfilzomib', 'category', false, false, 'CIE-11'),
('XM7202', 'Olaparib', 'category', false, false, 'CIE-11'),
('XM8F40', 'Idelalisib', 'category', false, false, 'CIE-11'),
('XM9E27', 'Sonidegib', 'category', false, false, 'CIE-11'),
('XM0Y26', 'Belinostat', 'category', false, false, 'CIE-11'),
('XM3753', 'Ixazomib', 'category', false, false, 'CIE-11'),
('XM1BM0', 'Talimogene laherparepvec', 'category', false, false, 'CIE-11'),
('XM1CT6', 'Inhibidores de la proteína quinasa', 'category', false, false, 'CIE-11'),
('XM5W30', 'Imatinib', 'category', false, false, 'CIE-11'),
('XM3A37', 'Gefitinib', 'category', false, false, 'CIE-11'),
('XM3420', 'Erlotinib', 'category', false, false, 'CIE-11'),
('XM1982', 'Sunitinib', 'category', false, false, 'CIE-11'),
('XM4A57', 'Sorafenib', 'category', false, false, 'CIE-11'),
('XM50U1', 'Dasatinib', 'category', false, false, 'CIE-11'),
('XM1FM4', 'Lapatinib', 'category', false, false, 'CIE-11'),
('XM6BP0', 'Nilotinib', 'category', false, false, 'CIE-11'),
('XM93U4', 'Temsirolimus', 'category', false, false, 'CIE-11'),
('XM69S5', 'Everolimus', 'category', false, false, 'CIE-11'),
('XM4FT3', 'Pazopanib', 'category', false, false, 'CIE-11'),
('XM3W52', 'Vandetanib', 'category', false, false, 'CIE-11'),
('XM7917', 'Afatinib', 'category', false, false, 'CIE-11'),
('XM60L5', 'Bosutinib', 'category', false, false, 'CIE-11'),
('XM55B8', 'Vemurafenib', 'category', false, false, 'CIE-11'),
('XM2U80', 'Crizotinib', 'category', false, false, 'CIE-11'),
('XM6JL9', 'Axitinib', 'category', false, false, 'CIE-11'),
('XM0853', 'Ruxolitinib', 'category', false, false, 'CIE-11'),
('XM0SL6', 'Ridaforolimus', 'category', false, false, 'CIE-11'),
('XM0601', 'Regorafenib', 'category', false, false, 'CIE-11'),
('XM0JZ7', 'Masitinib', 'category', false, false, 'CIE-11'),
('XM1HB8', 'Dabrafenib', 'category', false, false, 'CIE-11'),
('XM70G2', 'Ponatinib', 'category', false, false, 'CIE-11'),
('XM7VJ9', 'Trametinib', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
