-- CIE11 Import Part 21
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('JA86.0', 'Atención materna por anticuerpos antieritrocitarios', 'category', false, false, 'CIE-11'),
('JA86.1', 'Atención materna por hidropesía fetal', 'category', false, false, 'CIE-11'),
('JA86.2', 'Atención materna por signos de hipoxia fetal', 'category', false, false, 'CIE-11'),
('JA86.3', 'Atención materna por muerte intrauterina', 'category', false, false, 'CIE-11'),
('JA86.4', 'Atención materna por retraso del crecimiento fetal', 'category', false, false, 'CIE-11'),
('JA86.5', 'Atención materna por sospecha de macrosomía', 'category', false, false, 'CIE-11'),
('JA86.6', 'Atención materna por feto viable en embarazo abdominal', 'category', false, false, 'CIE-11'),
('JA86.Y', 'Atención materna por otros problemas fetales especificados', 'category', false, false, 'CIE-11'),
('JA86.Z', 'Atención materna por otros problemas fetales, sin especificación', 'category', false, false, 'CIE-11'),
('JA87', 'Atención materna relacionada con polihidramnios', 'category', false, false, 'CIE-11'),
('JA88', 'Atención materna relacionada con ciertos trastornos especificados del líquido o de las membranas amnióticas', 'category', false, false, 'CIE-11'),
('JA88.0', 'Oligohidramnios', 'category', false, false, 'CIE-11'),
('JA88.1', 'Infección de la bolsa amniótica o de las membranas amnióticas', 'category', false, false, 'CIE-11'),
('JA88.Y', 'Otra atención materna especificada relacionada con ciertos trastornos especificados del líquido o de las membranas amnióticas', 'category', false, false, 'CIE-11'),
('JA88.Z', 'Atención materna relacionada con ciertos trastornos especificados del líquido o de las membranas amnióticas, sin especificación', 'category', false, false, 'CIE-11'),
('JA89', 'Atención materna por ruptura prematura de membranas', 'category', false, false, 'CIE-11'),
('JA89.0', 'Ruptura prematura de membranas, con inicio del parto dentro de las siguientes 24 horas', 'category', false, false, 'CIE-11'),
('JA89.1', 'Ruptura prematura de membranas, presentación del trabajo de parto después de 24 horas', 'category', false, false, 'CIE-11'),
('JA89.2', 'Ruptura prematura de las membranas, con retraso terapéutico del trabajo de parto', 'category', false, false, 'CIE-11'),
('JA89.3', 'Ruptura prematura de membranas antes del término del embarazo', 'category', false, false, 'CIE-11'),
('JA89.Y', 'Otra ruptura prematura de membranas especificada', 'category', false, false, 'CIE-11'),
('JA89.Z', 'Ruptura prematura de membranas, sin especificación', 'category', false, false, 'CIE-11'),
('JA8A', 'Atención materna por trastornos placentarios', 'category', false, false, 'CIE-11'),
('JA8A.0', 'Síndromes de transfusión placentaria', 'category', false, false, 'CIE-11'),
('JA8A.1', 'Deformidad de la placenta', 'category', false, false, 'CIE-11'),
('JA8A.2', 'Adhesión anormal de la placenta', 'category', false, false, 'CIE-11'),
('JA8A.Y', 'Otra atención materna por otros trastornos placentarios especificados', 'category', false, false, 'CIE-11'),
('JA8A.Z', 'Atención materna por trastornos placentarios, sin especificación', 'category', false, false, 'CIE-11'),
('JA8B', 'Atención materna relacionada con placenta previa o placenta con inserción baja', 'category', false, false, 'CIE-11'),
('JA8B.0', 'Placenta previa con especificación de que no hubo hemorragia', 'category', false, false, 'CIE-11'),
('JA8B.1', 'Placenta previa con hemorragia', 'category', false, false, 'CIE-11'),
('JA8B.Z', 'Placenta previa, sin especificación', 'category', false, false, 'CIE-11'),
('JA8C', 'Atención materna por desprendimiento prematuro de la placenta', 'category', false, false, 'CIE-11'),
('JA8C.0', 'Desprendimiento prematuro de la placenta con coagulopatía', 'category', false, false, 'CIE-11'),
('JA8C.Y', 'Otro desprendimiento prematuro de la placenta especificado', 'category', false, false, 'CIE-11'),
('JA8C.Z', 'Desprendimiento prematuro de la placenta, sin especificación', 'category', false, false, 'CIE-11'),
('JA8D', 'Atención materna por trabajo de parto falso', 'category', false, false, 'CIE-11'),
('JA8D.0', 'Trabajo de parto falso antes de las 37 semanas completas de gestación', 'category', false, false, 'CIE-11'),
('JA8D.1', 'Trabajo de parto falso a las 37 o más semanas completas de gestación', 'category', false, false, 'CIE-11'),
('JA8D.Z', 'Trabajo de parto falso, sin especificación', 'category', false, false, 'CIE-11'),
('JA8E', 'Atención materna por embarazo prolongado', 'category', false, false, 'CIE-11'),
('JA8Y', 'Atención materna relacionada con otros trastornos especificados del feto, la cavidad amniótica o con posibles problemas en el parto', 'category', false, false, 'CIE-11'),
('JA8Z', 'Atención materna relacionada al feto, cavidad amniótica o con posibles problemas en el parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB00', 'Trabajo de parto o parto prematuro', 'category', false, false, 'CIE-11'),
('JB00.0', 'Trabajo de parto prematuro sin parto', 'category', false, false, 'CIE-11'),
('JB00.1', 'Trabajo de parto prematuro espontáneo con parto prematuro', 'category', false, false, 'CIE-11'),
('JB00.2', 'Trabajo de parto prematuro con parto a término', 'category', false, false, 'CIE-11'),
('JB00.3', 'Parto prematuro tras inducción yatrógena del trabajo de parto o cesárea', 'category', false, false, 'CIE-11'),
('JB00.Y', 'Otro trabajo de parto o parto prematuro especificado', 'category', false, false, 'CIE-11'),
('JB00.Z', 'Trabajo de parto o parto pretérmino, sin especificación', 'category', false, false, 'CIE-11'),
('JB01', 'Fracaso de la inducción del parto', 'category', false, false, 'CIE-11'),
('JB01.0', 'Fracaso de la inducción médica del trabajo de parto', 'category', false, false, 'CIE-11'),
('JB01.1', 'Fracaso de la inducción del trabajo de parto con instrumentos', 'category', false, false, 'CIE-11'),
('JB01.Z', 'Fracaso de la inducción del trabajo de parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB02', 'Anomalías de la dinámica del trabajo de parto', 'category', false, false, 'CIE-11'),
('JB02.0', 'Inercia primaria uterina', 'category', false, false, 'CIE-11'),
('JB02.1', 'Inercia uterina secundaria', 'category', false, false, 'CIE-11'),
('JB02.2', 'Otros tipos de inercia uterina', 'category', false, false, 'CIE-11'),
('JB02.3', 'Trabajo de parto precipitado', 'category', false, false, 'CIE-11'),
('JB02.4', 'Contracciones uterinas hipertónicas, incoordinadas o prolongadas', 'category', false, false, 'CIE-11'),
('JB02.Y', 'Otras anomalías especificadas de la dinámica del trabajo de parto', 'category', false, false, 'CIE-11'),
('JB02.Z', 'Anomalías de la dinámica del trabajo de parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB03', 'Trabajo de parto prolongado', 'category', false, false, 'CIE-11'),
('JB03.0', 'Prolongación del primer período del parto', 'category', false, false, 'CIE-11'),
('JB03.1', 'Prolongación del segundo período del trabajo de parto', 'category', false, false, 'CIE-11'),
('JB03.2', 'Rretraso del nacimiento de neonatos sucesivos', 'category', false, false, 'CIE-11'),
('JB03.Z', 'Trabajo de parto prolongado, sin especificación', 'category', false, false, 'CIE-11'),
('JB04', 'Trabajo de parto obstruido debido a mala posición o presentación del feto', 'category', false, false, 'CIE-11'),
('JB04.0', 'Trabajo de parto obstruido debido a la rotación incompleta de la cabeza del feto', 'category', false, false, 'CIE-11'),
('JB04.1', 'Trabajo de parto obstruido debido a presentación de nalgas', 'category', false, false, 'CIE-11'),
('JB04.2', 'Trabajo de parto obstruido debido a presentación de cara', 'category', false, false, 'CIE-11'),
('JB04.3', 'Trabajo de parto obstruido debido a presentación de frente', 'category', false, false, 'CIE-11'),
('JB04.4', 'Trabajo de parto obstruido debido a presentación de hombro', 'category', false, false, 'CIE-11'),
('JB04.5', 'Trabajo de parto obstruido debido a presentación compuesta', 'category', false, false, 'CIE-11'),
('JB04.Y', 'Trabajo de parto obstruido debido a otra mala posición o presentación del feto', 'category', false, false, 'CIE-11'),
('JB04.Z', 'Trabajo de parto obstruido debido a mala posición o presentación del feto, sin especificación', 'category', false, false, 'CIE-11'),
('JB05', 'Trabajo de parto obstruido debido a una anomalía de la pelvis ósea materna', 'category', false, false, 'CIE-11'),
('JB05.0', 'Trabajo de parto obstruido debido a una pelvis ósea materna deforme', 'category', false, false, 'CIE-11'),
('JB05.1', 'Trabajo de parto obstruido debido a estrechez general de la pelvis ósea materna', 'category', false, false, 'CIE-11'),
('JB05.2', 'Trabajo de parto obstruido debido a estrechez del agujero superior de la pelvis ósea', 'category', false, false, 'CIE-11'),
('JB05.3', 'Trabajo de parto obstruido debido a estrechez del agujero inferior o del estrecho medio de la cavidad pélvica', 'category', false, false, 'CIE-11'),
('JB05.4', 'Trabajo de parto obstruido debido a desproporción fetopélvica, sin especificación', 'category', false, false, 'CIE-11'),
('JB05.5', 'Trabajo de parto obstruido debido a anomalía de los órganos genitales maternos', 'category', false, false, 'CIE-11'),
('JB05.Y', 'Trabajo de parto obstruido debido a otras anomalías de la pelvis ósea materna', 'category', false, false, 'CIE-11'),
('JB05.Z', 'Trabajo de parto obstruido debido a una anomalía de la pelvis ósea materna, sin especificación', 'category', false, false, 'CIE-11'),
('JB06', 'Trabajo de parto obstruido debido a otras causas', 'category', false, false, 'CIE-11'),
('JB06.0', 'Trabajo de parto obstruido debido a distocia de hombro', 'category', false, false, 'CIE-11'),
('JB06.1', 'Trabajo de parto obstruido debido a gemelos entrelazados', 'category', false, false, 'CIE-11'),
('JB06.2', 'Trabajo de parto obstruido debido a feto más grande de lo normal', 'category', false, false, 'CIE-11'),
('JB06.3', 'Trabajo de parto obstruido debido a otras anomalías del feto', 'category', false, false, 'CIE-11'),
('JB06.Y', 'Trabajo de parto obstruido debido a otras causas especificadas', 'category', false, false, 'CIE-11'),
('JB06.Z', 'Trabajo de parto obstruido debido a otras causas, sin especificación', 'category', false, false, 'CIE-11'),
('JB07', 'Trabajo de parto o período expulsivo complicado debido a sufrimiento fetal', 'category', false, false, 'CIE-11'),
('JB07.0', 'Trabajo de parto o período expulsivo complicado debido a una frecuencia cardíaca fetal anormal', 'category', false, false, 'CIE-11'),
('JB07.1', 'Trabajo de parto o período expulsivo complicado por meconio en el líquido amniótico', 'category', false, false, 'CIE-11'),
('JB07.2', 'Trabajo de parto o período expulsivo complicado debido a pruebas bioquímicas de sufrimiento fetal', 'category', false, false, 'CIE-11'),
('JB07.Y', 'Otro trabajo de parto o período expulsivo especificado complicado por sufrimiento fetal', 'category', false, false, 'CIE-11'),
('JB07.Z', 'Trabajo de parto o período expulsivo complicado por sufrimiento fetal, sin especificación', 'category', false, false, 'CIE-11'),
('JB08', 'Trabajo de parto o período expulsivo complicado debido a problemas del cordón umbilical', 'category', false, false, 'CIE-11'),
('JB08.0', 'Trabajo de parto o período expulsivo complicado debido a prolapso del cordón umbilical', 'category', false, false, 'CIE-11'),
('JB08.1', 'Trabajo de parto o período expulsivo complicado debido a cordón umbilical enrollado alrededor del cuello, con compresión', 'category', false, false, 'CIE-11'),
('JB08.2', 'Trabajo de parto o período expulsivo complicado por cordón umbilical demasiado corto', 'category', false, false, 'CIE-11'),
('JB08.3', 'Trabajo de parto o expulsión fetal complicado debido a vasa previa', 'category', false, false, 'CIE-11'),
('JB08.4', 'Trabajo de parto o período expulsivo complicado debido a lesión vascular del cordón umbilical', 'category', false, false, 'CIE-11'),
('JB08.5', 'Trabajo de parto o período expulsivo complicado debido a otro enredo del cordón, con compresión', 'category', false, false, 'CIE-11'),
('JB08.Y', 'Trabajo de parto y período expulsivo complicados por otros problemas especificados del cordón umbilical', 'category', false, false, 'CIE-11'),
('JB08.Z', 'Trabajo de parto y período expulsivo complicados por problemas del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('JB09', 'Desgarro perineal durante el parto', 'category', false, false, 'CIE-11'),
('JB09.0', 'Desgarro perineal de primer grado durante el parto', 'category', false, false, 'CIE-11'),
('JB09.1', 'Desgarro perineal de segundo grado durante el parto', 'category', false, false, 'CIE-11'),
('JB09.2', 'Desgarro perineal de tercer grado durante el parto', 'category', false, false, 'CIE-11'),
('JB09.3', 'Desgarro perineal de cuarto grado durante el parto', 'category', false, false, 'CIE-11'),
('JB09.Z', 'Desgarro perineal durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB0A', 'Algunos traumatismos obstétricos especificados', 'category', false, false, 'CIE-11'),
('JB0A.0', 'Ruptura del útero antes del inicio del trabajo de parto', 'category', false, false, 'CIE-11'),
('JB0A.1', 'Ruptura del útero durante el parto', 'category', false, false, 'CIE-11'),
('JB0A.2', 'Inversión del útero tras el parto', 'category', false, false, 'CIE-11'),
('JB0A.3', 'Desgarro obstétrico del cuello uterino', 'category', false, false, 'CIE-11'),
('JB0A.4', 'Desgarro vaginal obstétrico alto', 'category', false, false, 'CIE-11'),
('JB0A.5', 'Laceración o desgarro uterino obstétrico', 'category', false, false, 'CIE-11'),
('JB0A.6', 'Otro traumatismo obstétrico de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('JB0A.7', 'Daño obstétrico de las articulaciones o ligamentos pélvicos', 'category', false, false, 'CIE-11'),
('JB0A.8', 'Hematoma obstétrico de la pelvis', 'category', false, false, 'CIE-11'),
('JB0A.Y', 'Otro traumatismo obstétrico especificado', 'category', false, false, 'CIE-11'),
('JB0A.Z', 'Traumatismo obstétrico, sin especificación', 'category', false, false, 'CIE-11'),
('JB0B', 'Retención de la placenta o de las membranas, sin hemorragia', 'category', false, false, 'CIE-11'),
('JB0B.0', 'Retención de la placenta sin hemorragia', 'category', false, false, 'CIE-11'),
('JB0B.1', 'Retención de fragmentos de la placenta o las membranas, sin hemorragia', 'category', false, false, 'CIE-11'),
('JB0C', 'Complicaciones de la anestesia durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.0', 'Neumonitis por aspiración debida a la anestesia durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.1', 'Otras complicaciones pulmonares de la anestesia durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.2', 'Complicaciones cardíacas de la anestesia durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.3', 'Complicaciones del sistema nervioso central debidas a la anestesia durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.4', 'Reacción tóxica a la anestesia local durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.5', 'Cefalea provocada por la anestesia raquídea o epidural durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.6', 'Otras complicaciones de la anestesia raquídea o epidural durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.7', 'Intubación fallida o difícil durante el parto', 'category', false, false, 'CIE-11'),
('JB0C.70', 'Intubación fallida durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.71', 'Dificultad en la intubación durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.7Y', 'Otro(a)(s) intubación fallida o difícil durante el parto especificado(a)(s)', 'category', false, false, 'CIE-11'),
('JB0C.7Z', 'Intubación fallida o difícil durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB0C.8', 'Conciencia bajo anestesia general durante el trabajo de parto o el parto.', 'category', false, false, 'CIE-11'),
('JB0C.Y', 'Otras complicaciones especificadas de la anestesia durante el trabajo de parto o el parto', 'category', false, false, 'CIE-11'),
('JB0C.Z', 'Complicaciones de la anestesia durante el trabajo de parto o el parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB0D', 'Algunas complicaciones especificadas del parto, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('JB0D.0', 'Sufrimiento materno durante el trabajo de parto y el parto', 'category', false, false, 'CIE-11'),
('JB0D.1', 'Choque cardiocirculatorio durante el parto o inmediatamente después', 'category', false, false, 'CIE-11'),
('JB0D.2', 'Pirexia durante el trabajo de parto, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('JB0D.3', 'Otras complicaciones de los procedimientos obstétricos, quirúrgicos o de otro tipo', 'category', false, false, 'CIE-11'),
('JB0D.4', 'Retraso del parto después de la ruptura artificial de las membranas', 'category', false, false, 'CIE-11'),
('JB0D.5', 'Retraso del parto después de la ruptura de membranas espontánea o no especificada', 'category', false, false, 'CIE-11'),
('JB0D.6', 'Parto vaginal tras una cesárea previa', 'category', false, false, 'CIE-11'),
('JB0D.7', 'Aplicación fallida de un extractor al vacío o fórceps, sin especificación', 'category', false, false, 'CIE-11'),
('JB0D.8', 'Intento de parto fallido, no especificado', 'category', false, false, 'CIE-11'),
('JB0D.Y', 'Otras complicaciones especificadas del trabajo del parto, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('JB0Y', 'Otras complicaciones especificadas del trabajo de parto o del parto', 'category', false, false, 'CIE-11'),
('JB0Z', 'Complicaciones del trabajo de parto o del parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB20', 'Parto único espontáneo', 'category', false, false, 'CIE-11'),
('JB20.0', 'Parto espontáneo de vértice', 'category', false, false, 'CIE-11'),
('JB20.1', 'Parto espontáneo de nalgas', 'category', false, false, 'CIE-11'),
('JB20.Y', 'Parto único espontáneo con otra presentación especificada', 'category', false, false, 'CIE-11'),
('JB20.Z', 'Parto único espontáneo, sin especificación', 'category', false, false, 'CIE-11'),
('JB21', 'Parto único con fórceps o extractor al vacío', 'category', false, false, 'CIE-11'),
('JB22', 'Parto único por cesárea', 'category', false, false, 'CIE-11'),
('JB22.0', 'Parto por cesárea electiva', 'category', false, false, 'CIE-11'),
('JB22.1', 'Parto por cesárea de emergencia', 'category', false, false, 'CIE-11'),
('JB22.2', 'Parto único por cesárea con histerectomía', 'category', false, false, 'CIE-11'),
('JB22.Z', 'Parto único por cesárea, sin especificación', 'category', false, false, 'CIE-11'),
('JB23', 'Otro parto único asistido', 'category', false, false, 'CIE-11'),
('JB23.0', 'Extracción de nalgas', 'category', false, false, 'CIE-11'),
('JB23.1', 'Otros partos únicos asistidos, de nalgas', 'category', false, false, 'CIE-11'),
('JB23.2', 'Otro parto único asistido por manipulación obstétrica', 'category', false, false, 'CIE-11'),
('JB23.3', 'Extracción de un feto viable en un embarazo abdominal', 'category', false, false, 'CIE-11'),
('JB23.4', 'Operación destructiva para facilitar el parto', 'category', false, false, 'CIE-11'),
('JB23.Z', 'Otro parto único asistido, sin especificación', 'category', false, false, 'CIE-11'),
('JB24', 'Parto múltiple', 'category', false, false, 'CIE-11'),
('JB24.0', 'Parto múltiple, todos espontáneos', 'category', false, false, 'CIE-11'),
('JB24.1', 'Parto múltiple, todos por fórceps o extractor al vacío', 'category', false, false, 'CIE-11'),
('JB24.2', 'Parto múltiple, todos por cesárea', 'category', false, false, 'CIE-11'),
('JB24.3', 'Parto múltiple mediante una combinación de métodos, con cesárea', 'category', false, false, 'CIE-11'),
('JB24.Y', 'Otro parto múltiple especificado', 'category', false, false, 'CIE-11'),
('JB24.Z', 'Parto múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('JB2Z', 'Parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB40', 'Infecciones en el puerperio', 'category', false, false, 'CIE-11'),
('JB40.0', 'Sepsis puerperal', 'category', false, false, 'CIE-11'),
('JB40.1', 'Infección de herida quirúrgica obstétrica', 'category', false, false, 'CIE-11'),
('JB40.2', 'Otra infección del aparato genital después del parto', 'category', false, false, 'CIE-11'),
('JB40.3', 'Infección del aparato urinario después del parto', 'category', false, false, 'CIE-11'),
('JB40.4', 'Pirexia de origen desconocido después del parto', 'category', false, false, 'CIE-11'),
('JB40.Y', 'Otras infecciones especificadas en el puerperio', 'category', false, false, 'CIE-11'),
('JB40.Z', 'Infecciones en el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB41', 'Complicaciones venosas en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.0', 'Tromboflebitis superficial en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.1', 'Flebotrombosis profunda en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.2', 'Hemorroides en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.3', 'Trombosis venosa cerebral en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.Y', 'Otras complicaciones venosas en el puerperio especificadas', 'category', false, false, 'CIE-11'),
('JB41.Z', 'Complicaciones venosas en el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB42', 'Embolia obstétrica', 'category', false, false, 'CIE-11'),
('JB42.0', 'Embolia gaseosa obstétrica', 'category', false, false, 'CIE-11'),
('JB42.1', 'Embolia de líquido amniótico', 'category', false, false, 'CIE-11'),
('JB42.2', 'Tromboembolia obstétrica', 'category', false, false, 'CIE-11'),
('JB42.3', 'Embolia piémica o séptica obstétrica', 'category', false, false, 'CIE-11'),
('JB42.Y', 'Otra embolia obstétrica especificada', 'category', false, false, 'CIE-11'),
('JB42.Z', 'Embolia obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('JB43', 'Complicaciones de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.0', 'Complicaciones pulmonares de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.1', 'Complicaciones cardíacas de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.2', 'Complicaciones del sistema nervioso central durante el puerperio debidas a la anestesia', 'category', false, false, 'CIE-11'),
('JB43.3', 'Cefalea inducida por la anestesia raquídea o epidural durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.4', 'Otras complicaciones de la anestesia raquídea o epidural durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.5', 'Intubación fallida o difícil durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.50', 'Intubación fallida durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.51', 'Intubación difícil durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.5Y', 'Otro(a)(s) intubación fallida o difícil durante el puerperio especificado(a)(s)', 'category', false, false, 'CIE-11'),
('JB43.5Z', 'Intubación fallida o difícil durante el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB43.6', 'Conciencia bajo anestesia general durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.Y', 'Otras complicaciones especificadas de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.Z', 'Complicaciones de la anestesia durante el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB44', 'Algunas complicaciones del puerperio especificadas', 'category', false, false, 'CIE-11'),
('JB44.0', 'Deshiscencia de la herida de la cesárea', 'category', false, false, 'CIE-11'),
('JB44.1', 'Dehiscencia de la herida obstétrica perineal', 'category', false, false, 'CIE-11'),
('JB44.2', 'Hematoma de herida obstétrica', 'category', false, false, 'CIE-11'),
('JB44.3', 'Cardiomiopatía en el puerperio', 'category', false, false, 'CIE-11'),
('JB44.4', 'Insuficiencia renal aguda postparto', 'category', false, false, 'CIE-11'),
('JB44.5', 'Tiroiditis posparto', 'category', false, false, 'CIE-11'),
('JB44.6', 'Osteomalacia puerperal', 'category', false, false, 'CIE-11'),
('JB44.Y', 'Otras complicaciones especificadas del puerperio', 'category', false, false, 'CIE-11'),
('JB44.Z', 'Complicaciones del puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB45', 'Infecciones de la mama asociadas con el parto', 'category', false, false, 'CIE-11'),
('JB45.0', 'Absceso de la mama asociado con el parto', 'category', false, false, 'CIE-11'),
('JB45.1', 'Mastitis no purulenta asociada con el parto', 'category', false, false, 'CIE-11'),
('JB45.Y', 'Otras infecciones de la mama especificadas asociadas con la maternidad', 'category', false, false, 'CIE-11'),
('JB45.Z', 'Infecciones de la mama asociadas con la maternidad, sin especificación', 'category', false, false, 'CIE-11'),
('JB46', 'Algunos trastornos especificados de la mama o la lactancia asociados con el parto', 'category', false, false, 'CIE-11'),
('JB46.0', 'Retracción del pezón asociada con el parto', 'category', false, false, 'CIE-11'),
('JB46.1', 'Pezón agrietado asociado con el parto', 'category', false, false, 'CIE-11'),
('JB46.2', 'Trastornos mamarios de otro tipo o no especificados asociados con el parto', 'category', false, false, 'CIE-11'),
('JB46.3', 'Agalactia', 'category', false, false, 'CIE-11'),
('JB46.4', 'Hipogalactia', 'category', false, false, 'CIE-11'),
('JB46.5', 'Lactancia suprimida', 'category', false, false, 'CIE-11'),
('JB46.6', 'Galactorrea', 'category', false, false, 'CIE-11'),
('JB46.7', 'Otros trastornos de la lactancia o los no especificados', 'category', false, false, 'CIE-11'),
('JB4Z', 'Complicaciones principalmente relacionadas con el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB60', 'Muerte obstétrica de causa no especificada', 'category', false, false, 'CIE-11'),
('JB61', 'Muerte materna debida a cualquier causa obstétrica que ocurre más de 42 días pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.0', 'Muerte por causa obstétrica directa que ocurre más de 42 días, pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.1', 'Muerte por causa obstétrica indirecta que ocurre más de 42 días, pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.Z', 'Muerte por cualquier causa obstétrica que tiene lugar después de 42 días pero no más de un año después del parto o aborto, sin especificación', 'category', false, false, 'CIE-11'),
('JB62', 'Muerte debida a las secuelas de causas obstétricas', 'category', false, false, 'CIE-11'),
('JB62.0', 'Muerte por secuelas de causas obstétricas directas', 'category', false, false, 'CIE-11'),
('JB62.1', 'Muerte por secuelas de causas obstétricas indirectas', 'category', false, false, 'CIE-11'),
('JB62.Z', 'Muerte debida a las secuelas de una causa obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('JB63', 'Enfermedades infecciosas maternas clasificables en otra parte que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.0', 'Tuberculosis que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.00', 'Tuberculosis de la placenta', 'category', false, false, 'CIE-11'),
('JB63.0Y', 'Otra tuberculosis especificada que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.0Z', 'Tuberculosis que complica el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB63.1', 'Sífilis que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.2', 'Gonorrea que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.3', 'Otras infecciones con modo de transmisión predominantemente sexual que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.4', 'Hepatitis viral que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.5', 'Otras enfermedades virales que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6', 'Enfermedades causadas por protozoarios que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.60', 'Paludismo que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6Y', 'Otras enfermedades especificadas causadas por protozoarios que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6Z', 'Enfermedades causadas por protozoarios que complican el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB63.7', 'Enfermedad por virus de la inmunodeficiencia humana que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.Y', 'Otras enfermedades infecciosas maternas especificadas clasificables en otra parte que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.Z', 'Enfermedades infecciosas maternas clasificables en otra parte que complican el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB64', 'Algunas enfermedades maternas clasificables en otra parte pero que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.0', 'Anemia que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.1', 'Otras enfermedades de la sangre o de los órganos hematopoyéticos, o algunos trastornos de la función inmunitaria, que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.2', 'Enfermedades endocrinas, nutricionales o metabólicas que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.3', 'Enfermedades del sistema nervioso que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.4', 'Enfermedades del aparato circulatorio que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.5', 'Enfermedades del aparato respiratorio que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.6', 'Enfermedades del aparato digestivo que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.7', 'Enfermedades de la piel que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.8', 'Anomalía congénita que complica el embarazo', 'category', false, false, 'CIE-11'),
('JB64.Y', 'Otras enfermedades maternas especificadas clasificables en otra parte pero que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB65', 'Secuelas de complicación del embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB6Y', 'Algunas otras condiciones obstétricas especificadas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('JB6Z', 'Condición obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('KA00', 'Feto o recién nacido afectado por condiciones de la madre que pueden no estar relacionadas con el embarazo en curso', 'category', false, false, 'CIE-11'),
('KA00.0', 'Feto o recién nacido afectado por trastornos hipertensivos de la madre', 'category', false, false, 'CIE-11'),
('KA00.1', 'Feto o recién nacido afectado por edema o proteinuria gestacional sin hipertensión', 'category', false, false, 'CIE-11'),
('KA00.2', 'Feto o recién nacido afectado por enfermedades del riñón o las vías urinarias en la madre', 'category', false, false, 'CIE-11'),
('KA00.3', 'Feto o recién nacido afectado por enfermedades |infecciosas de la madre', 'category', false, false, 'CIE-11'),
('KA00.4', 'Feto o recién nacido afectado por una enfermedad periodontal de la madre', 'category', false, false, 'CIE-11'),
('KA00.5', 'Feto o recién nacido afectado por una enfermedad respiratoria en la madre', 'category', false, false, 'CIE-11'),
('KA00.6', 'Feto o recién nacido afectado por un trastorno nutricional en la madre', 'category', false, false, 'CIE-11'),
('KA00.60', 'Feto o recién nacido afectado por desnutrición materna', 'category', false, false, 'CIE-11'),
('KA00.61', 'Feto o recién nacido afectado por sobrepeso u obesidad materna', 'category', false, false, 'CIE-11'),
('KA00.6Y', 'Feto o recién nacido afectado por otro trastorno nutricional especificado en la madre', 'category', false, false, 'CIE-11'),
('KA00.6Z', 'Feto o recién nacido afectado por un trastorno nutricional en la madre, sin especificación', 'category', false, false, 'CIE-11'),
('KA00.7', 'Feto o recién nacido afectado por un trastorno en la madre detectado en el análisis bioquímico de la sangre', 'category', false, false, 'CIE-11'),
('KA00.8', 'Feto o recién nacido afectado por una lesión traumática en la madre', 'category', false, false, 'CIE-11'),
('KA00.9', 'Feto o recién nacido afectado por quimioterapia de la madre', 'category', false, false, 'CIE-11'),
('KA00.A', 'Feto o recién nacido afectado por un procedimiento quirúrgico en la madre', 'category', false, false, 'CIE-11'),
('KA00.B', 'Feto o recién nacido afectado por anemia materna', 'category', false, false, 'CIE-11'),
('KA00.Y', 'Feto o recién nacido afectado por otros trastornos especificados de la madre que pueden no estar relacionados con el embarazo en curso', 'category', false, false, 'CIE-11'),
('KA00.Z', 'Feto o recién nacido afectado por trastornos de la madre que pueden no estar relacionados con el embarazo en curso, sin especificación', 'category', false, false, 'CIE-11'),
('KA01', 'Feto o recién nacido afectado por complicaciones maternas del embarazo', 'category', false, false, 'CIE-11'),
('KA01.0', 'Feto o recién nacido afectado por incompetencia del cuello uterino', 'category', false, false, 'CIE-11'),
('KA01.1', 'Feto o recién nacido afectado por ruptura prematura de membranas', 'category', false, false, 'CIE-11'),
('KA01.2', 'Feto o recién nacido afectado por oligohidramnios', 'category', false, false, 'CIE-11'),
('KA01.3', 'Feto o recién nacido afectado por polihidramnios', 'category', false, false, 'CIE-11'),
('KA01.4', 'Feto o recién nacido afectado por embarazo ectópico', 'category', false, false, 'CIE-11'),
('KA01.5', 'Feto o recién nacido afectado por un embarazo múltiple', 'category', false, false, 'CIE-11'),
('KA01.6', 'Feto o recién nacido afectado por la muerte de la madre', 'category', false, false, 'CIE-11'),
('KA01.7', 'Feto o recién nacido afectado por una presentación anormal antes del parto', 'category', false, false, 'CIE-11'),
('KA01.8', 'Feto o recién nacido afectado por pérdida de sangre materna', 'category', false, false, 'CIE-11'),
('KA01.Y', 'Feto o recién nacido afectado por otra complicación materna especificada del embarazo', 'category', false, false, 'CIE-11'),
('KA01.Z', 'Feto o recién nacido afectado por complicación materna del embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('KA02', 'Feto o recién nacido afectado por complicaciones de la placenta', 'category', false, false, 'CIE-11'),
('KA02.0', 'Feto o recién nacido afectado por placenta previa', 'category', false, false, 'CIE-11'),
('KA02.1', 'Feto o recién nacido afectado por edema placentario o una placenta grande', 'category', false, false, 'CIE-11'),
('KA02.2', 'Feto o recién nacido afectado por infarto placentario', 'category', false, false, 'CIE-11'),
('KA02.3', 'Feto o recién nacido afectado por insuficiencia placentaria o placenta pequeña', 'category', false, false, 'CIE-11'),
('KA02.4', 'Feto o recién nacido afectado por síndromes de transfusión placentaria', 'category', false, false, 'CIE-11'),
('KA02.Y', 'Feto o recién nacido afectado por otra complicación especificada de la placenta', 'category', false, false, 'CIE-11'),
('KA02.Z', 'Feto o recién nacido afectado por complicación de la placenta, sin especificación', 'category', false, false, 'CIE-11'),
('KA03', 'Feto o recién nacido afectado por complicaciones del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.0', 'Feto o recién nacido afectado por prolapso del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.1', 'Feto o recién nacido afectado por otro tipo de compresión del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.2', 'Feto o recién nacido afectado por una anomalía de la longitud del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.20', 'Feto o recién nacido afectado por cordón umbilical corto', 'category', false, false, 'CIE-11'),
('KA03.21', 'Feto o recién nacido afectado por cordón umbilical largo', 'category', false, false, 'CIE-11'),
('KA03.2Y', 'Feto o recién nacido afectado por otra anomalía especificada de la longitud del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.2Z', 'Feto y recién nacido afectado por una anomalía de la longitud del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('KA03.3', 'Feto o recién nacido afectado por vasa previa', 'category', false, false, 'CIE-11'),
('KA03.4', 'Feto o recién nacido afectado por una lesión traumática del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.Y', 'Feto o recién nacido afectado por otra complicación especificada del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.Z', 'Feto y recién nacido afectado por complicación del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('KA04', 'Feto o recién nacido afectado por otras anormalidades de las membranas', 'category', false, false, 'CIE-11'),
('KA04.0', 'Feto o recién nacido afectado por corioamnionitis', 'category', false, false, 'CIE-11'),
('KA04.1', 'Feto o recién nacido afectado por el síndrome de banda amniótica', 'category', false, false, 'CIE-11'),
('KA04.Y', 'Feto o recién nacido afectado por otras anormalidades especificadas de las membranas', 'category', false, false, 'CIE-11'),
('KA04.Z', 'Feto o recién nacido afectado por otras anormalidades de las membranas, sin especificación', 'category', false, false, 'CIE-11'),
('KA05', 'Feto o recién nacido afectado por ciertas complicaciones del trabajo de parto y el período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.0', 'Feto o recién nacido afectado por un parto o una extracción de nalgas', 'category', false, false, 'CIE-11'),
('KA05.1', 'Feto o recién nacido afectado por otra mala presentación, mala posición o desproporción durante el trabajo de parto y el período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.2', 'Feto o recién nacido afectado por parto con fórceps', 'category', false, false, 'CIE-11'),
('KA05.3', 'Feto o recién nacido afectado por parto asistido con extractor al vacío', 'category', false, false, 'CIE-11'),
('KA05.4', 'Feto o recién nacido afectado por cesárea', 'category', false, false, 'CIE-11'),
('KA05.5', 'Feto o recién nacido afectado por un parto precipitado', 'category', false, false, 'CIE-11'),
('KA05.6', 'Feto o recién nacido afectado por contracciones uterinas anormales', 'category', false, false, 'CIE-11'),
('KA05.7', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino', 'category', false, false, 'CIE-11'),
('KA05.70', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino antes del parto', 'category', false, false, 'CIE-11'),
('KA05.71', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino durante el parto', 'category', false, false, 'CIE-11'),
('KA05.7Z', 'Feto o recién nacido que está afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino, sin especificación', 'category', false, false, 'CIE-11'),
('KA05.8', 'Expulsión de meconio durante el parto', 'category', false, false, 'CIE-11'),
('KA05.Y', 'Feto o recién nacido que efectiva o presuntamente está afectado por otras complicaciones especificadas durante el trabajo de parto y período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.Z', 'Feto y recién nacido que efectiva o presuntamente está afectado por otras complicaciones durante el trabajo de parto y período expulsivo, sin especificación', 'category', false, false, 'CIE-11'),
('KA06', 'Feto o recién nacido afectado por sustancias nocivas transmitidas por la placenta o la leche materna', 'category', false, false, 'CIE-11'),
('KA06.0', 'Feto o recién nacido afectado por anestesia o analgesia materna durante el embarazo, el trabajo de parto o el período expulsivo', 'category', false, false, 'CIE-11'),
('KA06.1', 'Feto o recién nacido afectado por el tabaquismo de la madre', 'category', false, false, 'CIE-11'),
('KA06.2', 'Feto o recién nacido afectado por el consumo de alcohol de la madre', 'category', false, false, 'CIE-11'),
('KA06.3', 'Feto o recién nacido afectado por el consumo de drogas de la madre', 'category', false, false, 'CIE-11'),
('KA06.4', 'Feto o recién nacido afectado por el consumo materno de nutrientes químicos', 'category', false, false, 'CIE-11'),
('KA06.5', 'Feto o recién nacido afectado por la exposición materna a sustancias químicas ambientales', 'category', false, false, 'CIE-11'),
('KA06.Y', 'Feto o recién nacido afectado por otro efecto nocivo transmitido a través de la placenta o de la leche materna', 'category', false, false, 'CIE-11'),
('KA06.Z', 'Feto o recién nacido afectado por un efecto nocivo transmitido a través de la placenta o de la leche materna, sin especificación', 'category', false, false, 'CIE-11'),
('KA07', 'Dermatosis neonatal debida a anticuerpos maternos', 'category', false, false, 'CIE-11'),
('KA07.0', 'Lupus eritematoso neonatal', 'category', false, false, 'CIE-11'),
('KA07.1', 'Pénfigo neonatal', 'category', false, false, 'CIE-11'),
('KA07.Y', 'Otra dermatosis neonatal especificada debida a anticuerpos maternos', 'category', false, false, 'CIE-11'),
('KA0Z', 'Feto o recién nacido afectado por factores maternos o por complicaciones del embarazo, el trabajo de parto o el parto, no especificados', 'category', false, false, 'CIE-11'),
('KA20', 'Trastornos del recién nacido relacionados con el retraso del crecimiento o desnutrición fetal', 'category', false, false, 'CIE-11'),
('KA20.0', 'Pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.00', 'Pequeño para la edad gestacional, simétrico', 'category', false, false, 'CIE-11'),
('KA20.01', 'Pequeño para la edad gestacional, con asimetría', 'category', false, false, 'CIE-11'),
('KA20.0Z', 'Pequeño para la edad gestacional, sin especificación', 'category', false, false, 'CIE-11'),
('KA20.1', 'Restricción del crecimiento intrauterino', 'category', false, false, 'CIE-11'),
('KA20.10', 'Retraso del crecimiento intrauterino asimétrico', 'category', false, false, 'CIE-11'),
('KA20.11', 'Retraso del crecimiento intrauterino simétrico', 'category', false, false, 'CIE-11'),
('KA20.12', 'Niño con retraso del crecimiento intrauterino y pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.1Y', 'Otro retraso del crecimiento intrauterino especificado', 'category', false, false, 'CIE-11'),
('KA20.1Z', 'Retraso del crecimiento intrauterino, sin especificación', 'category', false, false, 'CIE-11'),
('KA20.2', 'Desnutrición fetal intrauterina, sin mención de pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.Y', 'Otros trastornos especificados del recién nacido relacionados con el retraso del crecimiento o desnutrición del feto', 'category', false, false, 'CIE-11'),
('KA20.Z', 'Trastornos del recién nacido relacionados con el retraso del crecimiento o desnutrición del feto, sin especificación', 'category', false, false, 'CIE-11'),
('KA21', 'Trastornos del recién nacido relacionados con gestación corta o con bajo peso al nacer, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('KA21.0', 'Recién nacido con un peso al nacer extremadamente bajo', 'category', false, false, 'CIE-11'),
('KA21.00', 'Recién nacido con un peso al nacer extremadamente bajo, de 499 gramos o menos', 'category', false, false, 'CIE-11'),
('KA21.01', 'Recién nacido con un peso al nacer extremadamente bajo, de 500 a 749 gramos', 'category', false, false, 'CIE-11'),
('KA21.02', 'Recién nacido con un peso al nacer extremadamente bajo, de 750 a 999 gramos.', 'category', false, false, 'CIE-11'),
('KA21.0Z', 'Recién nacido con un peso al nacer extremadamente bajo, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.1', 'Recién nacido con un peso muy bajo al nacer', 'category', false, false, 'CIE-11'),
('KA21.10', 'Recién nacido con peso muy bajo al nacer, de 1000 a 1249 gramos', 'category', false, false, 'CIE-11'),
('KA21.11', 'Recién nacido con peso muy bajo al nacer, de 1250 a 1499 gramos', 'category', false, false, 'CIE-11'),
('KA21.1Z', 'Recién nacido con un peso muy bajo al nacer, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.2', 'Recién nacido con peso bajo al nacer', 'category', false, false, 'CIE-11'),
('KA21.20', 'Recién nacido con peso bajo al nacer, de 1500 a 1999 gramos', 'category', false, false, 'CIE-11'),
('KA21.21', 'Recién nacido con peso bajo al nacer, de 2000 a 2499 gramos', 'category', false, false, 'CIE-11'),
('KA21.2Z', 'Recién nacido con peso bajo al nacer, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.3', 'Prematuridad extrema del recién nacido', 'category', false, false, 'CIE-11'),
('KA21.30', 'Prematuridad extrema del recién nacido, edad gestacional de menos de 22 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.31', 'Prematuridad extrema del recién nacido, edad gestacional de 22 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.32', 'Prematuridad extrema del recién nacido, 23 semanas de gestación completas', 'category', false, false, 'CIE-11'),
('KA21.33', 'Prematuridad extrema del recién nacido, edad gestacional de 24 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.34', 'Prematuridad extrema del recién nacido, edad gestacional de 25 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.35', 'Prematuridad extrema del recién nacido, edad gestacional de 26 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.36', 'Prematuridad extrema del recién nacido, edad gestacional de 27 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.3Z', 'Prematuridad extrema del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.4', 'Recién nacido prematuro', 'category', false, false, 'CIE-11'),
('KA21.40', 'Recién nacido prematuro, edad gestacional de 28 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.41', 'Recién nacido prematuro, edad gestacional de 29 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.42', 'Recién nacido prematuro, edad gestacional de 30 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.43', 'Recién nacido prematuro, edad gestacional de 31 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.44', 'Recién nacido prematuro, edad gestacional de 32 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.45', 'Recién nacido prematuro, edad gestacional de 33 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.46', 'Recién nacido prematuro, edad gestacional de 34 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.47', 'Recién nacido prematuro, edad gestacional de 35 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.48', 'Recién nacido prematuro, edad gestacional de 36 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.4Z', 'Recién nacido prematuro, sin especificación', 'category', false, false, 'CIE-11'),
('KA22', 'Trastornos del recién nacido relacionados con una gestación prolongada o peso elevado al nacer', 'category', false, false, 'CIE-11'),
('KA22.0', 'Recién nacido excepcionalmente grande', 'category', false, false, 'CIE-11'),
('KA22.1', 'Recién nacido grande para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA22.2', 'Recién nacido posmaduro', 'category', false, false, 'CIE-11'),
('KA22.3', 'Síndrome de posmadurez', 'category', false, false, 'CIE-11'),
('KA2Y', 'Otros trastornos especificados en el recién nacido relacionados con la duración de la gestación y el crecimiento fetal', 'category', false, false, 'CIE-11'),
('KA2Z', 'Trastornos en el recién nacido relacionados con la duración de la gestación y el crecimiento fetal, sin especificación', 'category', false, false, 'CIE-11'),
('KA40', 'Lesión traumática del sistema nervioso central durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0', 'Hemorragia o laceración intracraneal por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.00', 'Hemorragia subdural por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.01', 'Hemorragia cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.02', 'Hemorragia cerebelosa por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.03', 'Hemorragia intraventricular por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.04', 'Hemorragia subaracnoidea por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.05', 'Desgarro tentorial por traumatismo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.06', 'Contusión cerebelosa por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.07', 'Contusión cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.08', 'Hemorragia extradural o epidural por lesión traumática durante el durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0Y', 'Otra hemorragia o laceración intracraneal especificada por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0Z', 'Hemorragia o laceración intracraneal por lesión traumática durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA40.1', 'Edema cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.2', 'Lesión traumática de la columna vertebral o médula espinal durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.3', 'Lesión traumática del tronco encefálico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.Y', 'Otra lesión traumática especificada del sistema nervioso central durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.Z', 'Lesión traumática del sistema nervioso central durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA41', 'Lesión traumática en el ojo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42', 'Lesión traumática del cuero cabelludo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.0', 'Equimosis del cuero cabelludo por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.1', 'Cefalohematoma por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.2', 'Chichón del recién nacido por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.3', 'Traumatismo en el cuero cabelludo por monitoreo del recién nacido', 'category', false, false, 'CIE-11'),
('KA42.4', 'Hemorragia subaponeurótica epicraneal subgaleal por lesión durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.Y', 'Otra lesión traumática especificada del cuero cabelludo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.Z', 'Lesión traumática del cuero cabelludo durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA43', 'Lesión traumática de la piel o de los tejidos blandos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.0', 'Lesión traumática del músculo esternocleidomastoideo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.1', 'Lesión traumática de los genitales externos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.2', 'Necrosis de la grasa subcutánea del recién nacido por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.3', 'Lesión traumática en la cara del neonato durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.Y', 'Otra lesión traumática especificada de la piel o de los tejidos blandos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.Z', 'Lesión traumática de la piel o de los tejidos blandos durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA44', 'Lesión traumática del sistema nervioso periférico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.0', 'Traumatismo de los pares craneales durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.00', 'Lesión del nervio facial durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.0Y', 'Traumatismo durante el nacimiento de otro par craneal especificado', 'category', false, false, 'CIE-11'),
('KA44.0Z', 'Traumatismo durante el nacimiento de un par craneal, sin especificación', 'category', false, false, 'CIE-11'),
('KA44.1', 'Parálisis del plexo braquial en el recién nacido', 'category', false, false, 'CIE-11'),
('KA44.10', 'Parálisis de Erb', 'category', false, false, 'CIE-11'),
('KA44.11', 'Parálisis de Klumpke', 'category', false, false, 'CIE-11'),
('KA44.1Z', 'Parálisis del plexo braquial en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA44.2', 'Parálisis del nervio frénico debido a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA44.Y', 'Otra lesión traumática especificada del sistema nervioso periférico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.Z', 'Lesión traumática del sistema nervioso periférico durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA45', 'Lesión traumática del esqueleto durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0', 'Fractura de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.00', 'Fractura lineal de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.01', 'Fractura deprimida de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0Y', 'Otra fractura de cráneo especificada debida a traumatismo durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0Z', 'Fractura del cráneo debida a traumatismo durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('KA45.1', 'Osteodiastasis occipital debido a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.2', 'Lesión traumática de los huesos faciales durante el parto', 'category', false, false, 'CIE-11'),
('KA45.20', 'Fractura del hueso mandibular debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.21', 'Fractura de huesos nasales debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.2Y', 'Otra lesión traumática especificada de los huesos faciales durante el parto', 'category', false, false, 'CIE-11'),
('KA45.2Z', 'Lesión traumática de los huesos faciales durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('KA45.3', 'Lesión traumática del tórax durante el parto', 'category', false, false, 'CIE-11'),
('KA45.4', 'Fractura, luxación o subluxación de las vértebras debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.5', 'Fractura de la clavícula debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.6', 'Lesión traumática de los huesos largos durante el parto', 'category', false, false, 'CIE-11'),
('KA45.Y', 'Otra lesión traumática especificada del esqueleto durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA45.Z', 'Lesión traumática del esqueleto durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('KA46', 'Lesión traumática de otros órganos durante el parto', 'category', false, false, 'CIE-11'),
('KA46.0', 'Lesión traumática del hígado durante el parto', 'category', false, false, 'CIE-11'),
('KA46.1', 'Lesión traumática del bazo durante el parto', 'category', false, false, 'CIE-11'),
('KA46.2', 'Hemorragia adrenal debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA46.Y', 'Otra lesión lesión traumática especificada de otros órganos durante el parto', 'category', false, false, 'CIE-11'),
('KA4Z', 'Traumatismo durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA60', 'Sepsis del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA61', 'Otras infecciones bacterianas del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA61.0', 'Tuberculosis congénita', 'category', false, false, 'CIE-11'),
('KA61.1', 'Listeriosis neonatal', 'category', false, false, 'CIE-11'),
('KA61.Z', 'Infección bacteriana del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA62', 'Infección viral del feto o del recién nacido', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
