-- CIE11 Import Part 9
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('6C4C.71', 'Trastorno de ansiedad inducido por MDMA o drogas relacionadas', 'category', false, false, 'CIE-11'),
('6C4C.Y', 'Otros trastornos especificados debidos al consumo de [metilendioximetanfetamina] MDMA o drogas relacionadas, incluida la MDA', 'category', false, false, 'CIE-11'),
('6C4C.Z', 'Trastornos debidos al uso de MDMA [metilendioximetanfetamina] o drogas relacionadas, incluida la MDA, sin especificación', 'category', false, false, 'CIE-11'),
('6C4D', 'Trastornos debidos al uso de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.0', 'Episodio de uso nocivo de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.1', 'Patrón nocivo de consumo de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.10', 'Patrón nocivo de consumo de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], episódico', 'category', false, false, 'CIE-11'),
('6C4D.11', 'Patrón nocivo de consumo de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], continuo', 'category', false, false, 'CIE-11'),
('6C4D.1Z', 'Patrón nocivo de consumo de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], sin especificación', 'category', false, false, 'CIE-11'),
('6C4D.2', 'Dependencia de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.20', 'Dependencia de las drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], consumo actual', 'category', false, false, 'CIE-11'),
('6C4D.21', 'Dependencia de las drogas disociativas, incluidas la ketamina o la fenciclidina [PCP], remisión completa temprana', 'category', false, false, 'CIE-11'),
('6C4D.22', 'Dependencia de las drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], remisión parcial prolongada', 'category', false, false, 'CIE-11'),
('6C4D.23', 'Dependencia de las drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], remisión completa prolongada', 'category', false, false, 'CIE-11'),
('6C4D.2Z', 'Dependencia de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], sin especificación', 'category', false, false, 'CIE-11'),
('6C4D.3', 'Intoxicación por drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.4', 'Delirium inducido por drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.5', 'Trastorno psicótico inducido por drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.6', 'Ciertos trastornos mentales o del comportamiento inducidos por fármacos disociativos especificados, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.60', 'Trastorno del estado de ánimo inducido por drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.61', 'Trastorno de ansiedad inducido por drogas disociativas, incluidas la ketamina o la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.Y', 'Otros trastornos especificados debidos al uso de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP]', 'category', false, false, 'CIE-11'),
('6C4D.Z', 'Trastornos especificados debidos al uso de drogas disociativas, incluidas la ketamina y la fenciclidina [PCP], sin especificación', 'category', false, false, 'CIE-11'),
('6C4E', 'Trastornos debidos al uso de otras sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4E.0', 'Episodio de uso nocivo de otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.1', 'Patrón nocivo de consumo de otra sustancia psicoactiva especificada', 'category', false, false, 'CIE-11'),
('6C4E.10', 'Patrón nocivo de consumo de otra sustancia psicoactiva especificada, episódico', 'category', false, false, 'CIE-11'),
('6C4E.11', 'Patrón nocivo de consumo de otra sustancia psicoactiva especificada, continuo', 'category', false, false, 'CIE-11'),
('6C4E.1Z', 'Patrón nocivo de consumo de otra sustancia psicoactiva especificada, sin especificación', 'category', false, false, 'CIE-11'),
('6C4E.2', 'Dependencia de otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.20', 'Dependencia de otras sustancias psicoactivas especificadas, consumo actual', 'category', false, false, 'CIE-11'),
('6C4E.21', 'Dependencia de otras sustancias psicoactivas especificadas, remisión completa temprana', 'category', false, false, 'CIE-11'),
('6C4E.22', 'Dependencia de otras sustancias psicoactivas especificadas, remisión parcial prolongada', 'category', false, false, 'CIE-11'),
('6C4E.23', 'Dependencia de otras sustancias psicoactivas especificadas, remisión completa prolongada', 'category', false, false, 'CIE-11'),
('6C4E.2Z', 'Dependencia de otras sustancias psicoactivas especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4E.3', 'Intoxicación por otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.4', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.40', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas, sin complicaciones', 'category', false, false, 'CIE-11'),
('6C4E.41', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas, con alteraciones perceptuales', 'category', false, false, 'CIE-11'),
('6C4E.42', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas, con convulsiones', 'category', false, false, 'CIE-11'),
('6C4E.43', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas, con alteraciones perceptuales y convulsiones', 'category', false, false, 'CIE-11'),
('6C4E.4Z', 'Síndrome de abstinencia de otras sustancias psicoactivas especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4E.5', 'Delirium inducido por otras sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4E.6', 'Trastorno psicótico inducido por otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.7', 'Otros ciertos trastornos mentales o del comportamiento especificados inducidos por sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('6C4E.70', 'Trastorno del estado de ánimo inducido por otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.71', 'Trastorno de ansiedad inducido por otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4E.72', 'Trastorno obsesivo-compulsivo u otro trastorno relacionado inducido por otra sustancia psicoactiva especificada', 'category', false, false, 'CIE-11'),
('6C4E.73', 'Trastorno del control de los impulsos inducido por otra sustancia psicoactiva especificada', 'category', false, false, 'CIE-11'),
('6C4E.Y', 'Otros trastornos especificados debidos al uso de otras sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4E.Z', 'Trastornos debidos al uso de otras sustancias psicoactivas especificadas, incluidos los medicamentos, sin especificación', 'category', false, false, 'CIE-11'),
('6C4F', 'Trastornos debidos al uso de múltiples sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4F.0', 'Episodio de uso nocivo de múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.1', 'Patrón de uso nocivo de múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.10', 'Patrón de uso nocivo de múltiples sustancias psicoactivas especificadas, episódico', 'category', false, false, 'CIE-11'),
('6C4F.11', 'Patrón de uso nocivo de múltiples sustancias psicoactivas especificadas, continuo', 'category', false, false, 'CIE-11'),
('6C4F.1Z', 'Patrón de uso nocivo de múltiples sustancias psicoactivas específicas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4F.2', 'Dependencia de múltiples sustancias psicoactivas especificadas.', 'category', false, false, 'CIE-11'),
('6C4F.20', 'Dependencia de múltiples sustancias psicoactivas especificadas, uso actual.', 'category', false, false, 'CIE-11'),
('6C4F.21', 'Dependencia múltiple especificada de sustancias psicoactivas, remisión completa temprana', 'category', false, false, 'CIE-11'),
('6C4F.22', 'Dependencia múltiple especificada de sustancias psicoactivas, remisión parcial sostenida', 'category', false, false, 'CIE-11'),
('6C4F.23', 'Dependencia múltiple especificada de sustancias psicoactivas, remisión completa sostenida', 'category', false, false, 'CIE-11'),
('6C4F.2Z', 'Dependencia de múltiples sustancias psicoactivas especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4F.3', 'Intoxicación por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.4', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.40', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas, sin complicaciones', 'category', false, false, 'CIE-11'),
('6C4F.41', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas, con trastornos de la percepción', 'category', false, false, 'CIE-11'),
('6C4F.42', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas, con convulsiones', 'category', false, false, 'CIE-11'),
('6C4F.43', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas, con trastornos de la percepción y convulsiones', 'category', false, false, 'CIE-11'),
('6C4F.4Y', 'Otro síndrome especificado de abstinencia de múltiples sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('6C4F.4Z', 'Síndrome de abstinencia de múltiples sustancias psicoactivas especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4F.5', 'Delirium inducido por múltiples sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4F.6', 'Trastorno psicótico inducido por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.7', 'Ciertos trastornos mentales o del comportamiento múltiples especificadas inducidos por sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('6C4F.70', 'Trastorno del estado de ánimo inducido por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.71', 'Trastorno de ansiedad inducido por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.72', 'Trastorno obsesivo-compulsivo u otro trastorno relacionado inducido por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.73', 'Síndrome del control de los impulsos inducido por múltiples sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6C4F.Y', 'Otros trastornos especificados debidos al consumo de múltiples sustancias psicoactivas especificadas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6C4F.Z', 'Trastornos debidos al consumo de múltiples sustancias psicoactivas especificadas, incluidos los medicamentos, sin especificación', 'category', false, false, 'CIE-11'),
('6C4G', 'Trastornos debidos al uso de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.0', 'Episodio de uso nocivo de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.1', 'Patrón de uso nocivo de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.10', 'Patrón de uso nocivo de sustancias psicoactivas desconocidas o no especificadas, episódico', 'category', false, false, 'CIE-11'),
('6C4G.11', 'Patrón de uso nocivo de sustancias psicoactivas desconocidas o no especificadas, continuo', 'category', false, false, 'CIE-11'),
('6C4G.1Z', 'Patrón de uso nocivo de sustancias psicoactivas desconocidas o no especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4G.2', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.20', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas, consumo actual', 'category', false, false, 'CIE-11'),
('6C4G.21', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas, remisión completa temprana', 'category', false, false, 'CIE-11'),
('6C4G.22', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas, remisión parcial prolongada', 'category', false, false, 'CIE-11'),
('6C4G.23', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas, remisión completa prolongada', 'category', false, false, 'CIE-11'),
('6C4G.2Z', 'Dependencia de sustancias psicoactivas desconocidas o no especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4G.3', 'Intoxicación por sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.4', 'Síndrome de abstinencia de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.40', 'Síndrome de abstinencia de una sustancia psicoactiva desconocida o no especificada, sin complicaciones', 'category', false, false, 'CIE-11'),
('6C4G.41', 'Síndrome de abstiencia por sustancia psicoactiva desconocida o no especificada, con trastornos perceptivos', 'category', false, false, 'CIE-11'),
('6C4G.42', 'Síndrome de abstinencia por sustancia psicoactiva desconocida o no especificada, con convulsiones', 'category', false, false, 'CIE-11'),
('6C4G.43', 'Síndrome de abstinencia por sustancias psicoactivas desconocidas o sin especificación, con trastornos perceptivos y convulsiones', 'category', false, false, 'CIE-11'),
('6C4G.4Z', 'Síndrome de abstinencia de sustancias psicoactivas desconocidas o no especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4G.5', 'Delirium inducido por sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.6', 'Trastorno psicótico inducido por sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.7', 'Ciertos trastornos mentales o del comportamiento inducidos por sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.70', 'Trastorno del estado de ánimo provocado por sustancia psicoactiva desconocida o no especificada', 'category', false, false, 'CIE-11'),
('6C4G.71', 'Trastorno de ansiedad inducido por sustancias psicoactivas desconocidas o sin especificación', 'category', false, false, 'CIE-11'),
('6C4G.72', 'Trastorno obsesivo-compulsivo o trastorno inducido relacionado por una sustancia psicoactiva desconocida o no especificada', 'category', false, false, 'CIE-11'),
('6C4G.73', 'Trastorno de control de los impulsos inducido por una sustancia psicoactiva desconocida o no especificada', 'category', false, false, 'CIE-11'),
('6C4G.Y', 'Otros trastornos especificados debidos al uso de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('6C4G.Z', 'Trastornos debidos al uso de sustancias psicoactivas desconocidas o no especificadas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4H', 'Trastornos debidos al consumo de sustancias no psicoactivas', 'category', false, false, 'CIE-11'),
('6C4H.0', 'Episodio de uso nocivo de sustancias no psicoactivas', 'category', false, false, 'CIE-11'),
('6C4H.1', 'Patrón de uso nocivo de sustancias no psicoactivas', 'category', false, false, 'CIE-11'),
('6C4H.10', 'Patrón de uso nocivo de sustancias no psicoactivas, episódico', 'category', false, false, 'CIE-11'),
('6C4H.11', 'Patrón de uso nocivo de sustancias no psicoactivas, continuo', 'category', false, false, 'CIE-11'),
('6C4H.1Z', 'Patrón nocivo de uso de sustancias no psicoactivas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4H.Y', 'Otros trastornos especificados debidos al consumo de sustancias no psicoactivas', 'category', false, false, 'CIE-11'),
('6C4H.Z', 'Trastornos debidos al consumo de sustancias no psicoactivas, sin especificación', 'category', false, false, 'CIE-11'),
('6C4Y', 'Otros trastornos específicos debidos al uso de sustancias', 'category', false, false, 'CIE-11'),
('6C4Z', 'Trastornos por uso de sustancias, sin especificación', 'category', false, false, 'CIE-11'),
('6C50', 'Trastorno por juego de apuestas', 'category', false, false, 'CIE-11'),
('6C50.0', 'Trastorno por juego de apuestas, predominantemente fuera de línea', 'category', false, false, 'CIE-11'),
('6C50.1', 'Trastorno por juego de apuestas, predominantemente en línea', 'category', false, false, 'CIE-11'),
('6C50.Z', 'Trastorno por juego de apuestas, sin especificación', 'category', false, false, 'CIE-11'),
('6C51', 'Trastorno por uso de videojuegos', 'category', false, false, 'CIE-11'),
('6C51.0', 'Trastorno por uso de videojuegos, predominantemente en línea', 'category', false, false, 'CIE-11'),
('6C51.1', 'Trastorno por uso de videojuegos, predominantemente fuera de línea', 'category', false, false, 'CIE-11'),
('6C51.Z', 'Trastorno por uso de videojuegos, sin especificación', 'category', false, false, 'CIE-11'),
('6C5Y', 'Otros trastornos especificados debidos a comportamientos adictivos', 'category', false, false, 'CIE-11'),
('6C5Z', 'Trastornos debidos a comportamientos adictivos, sin especificación', 'category', false, false, 'CIE-11'),
('6C70', 'Piromanía', 'category', false, false, 'CIE-11'),
('6C71', 'Cleptomanía', 'category', false, false, 'CIE-11'),
('6C72', 'Trastorno por comportamiento sexual compulsivo', 'category', false, false, 'CIE-11'),
('6C73', 'Trastorno explosivo intermitente', 'category', false, false, 'CIE-11'),
('6C7Y', 'Otros trastornos especificados del control de los impulsos', 'category', false, false, 'CIE-11'),
('6C7Z', 'Trastornos del control de los impulsos, sin especificación', 'category', false, false, 'CIE-11'),
('6C90', 'Trastorno desafiante y oposicionista', 'category', false, false, 'CIE-11'),
('6C90.0', 'Trastorno desafiante y oposicionista con irritabilidad o enojo crónicos', 'category', false, false, 'CIE-11'),
('6C90.00', 'Trastorno desafiante y oposicionista con irritabilidad o enojo crónicos, con emociones prosociales limitadas', 'category', false, false, 'CIE-11'),
('6C90.01', 'Trastorno desafiante y oposicionista con irritabilidad o enojo crónicos, con emociones prosociales normales', 'category', false, false, 'CIE-11'),
('6C90.0Z', 'Trastorno desafiante y oposicionista con irritabilidad o enojo crónicos, sin especificación', 'category', false, false, 'CIE-11'),
('6C90.1', 'Trastorno desafiante y oposicionista sin irritabilidad o enojo crónicos', 'category', false, false, 'CIE-11'),
('6C90.10', 'Trastorno desafiante y oposicionista sin irritabilidad o enojo crónicos, con emociones prosociales limitadas', 'category', false, false, 'CIE-11'),
('6C90.11', 'Trastorno desafiante y oposicionista sin irritabilidad o enojo crónicos, con emociones prosociales normales', 'category', false, false, 'CIE-11'),
('6C90.1Z', 'Trastorno desafiante y oposicionista sin irritabilidad o enojo crónicos, sin especificación', 'category', false, false, 'CIE-11'),
('6C90.Z', 'Trastorno desafiante y oposicionista, sin especificación', 'category', false, false, 'CIE-11'),
('6C91', 'Trastorno de comportamiento disocial', 'category', false, false, 'CIE-11'),
('6C91.0', 'Trastorno de comportamiento disocial, inicio en la infancia', 'category', false, false, 'CIE-11'),
('6C91.00', 'Trastorno de comportamiento disocial, inicio en la infancia, con emociones prosociales limitadas', 'category', false, false, 'CIE-11'),
('6C91.01', 'Trastorno de comportamiento disocial, inicio en la infancia, con emociones prosociales normales', 'category', false, false, 'CIE-11'),
('6C91.0Z', 'Trastorno de comportamiento disocial, inicio en la infancia, sin especificación', 'category', false, false, 'CIE-11'),
('6C91.1', 'Trastorno de comportamiento disocial, inicio en la adolescencia', 'category', false, false, 'CIE-11'),
('6C91.10', 'Trastorno de comportamiento disocial, inicio en la adolescencia, con emociones prosociales limitadas', 'category', false, false, 'CIE-11'),
('6C91.11', 'Trastorno de comportamiento disocial, inicio en la adolescencia, con emociones prosociales normales', 'category', false, false, 'CIE-11'),
('6C91.1Y', 'Otros trastornos especificados de comportamiento disocial, inicio en la adolescencia', 'category', false, false, 'CIE-11'),
('6C91.Z', 'Trastorno de comportamiento disocial, sin especificación', 'category', false, false, 'CIE-11'),
('6C9Y', 'Otros trastornos de comportamiento disruptivo y disocial especificado', 'category', false, false, 'CIE-11'),
('6C9Z', 'Trastornos de comportamiento disruptivo y disocial, sin especificación', 'category', false, false, 'CIE-11'),
('6D10', 'Trastorno de personalidad', 'category', false, false, 'CIE-11'),
('6D10.0', 'Trastorno de personalidad leve', 'category', false, false, 'CIE-11'),
('6D10.1', 'Trastorno de personalidad moderado', 'category', false, false, 'CIE-11'),
('6D10.2', 'Trastorno de personalidad grave', 'category', false, false, 'CIE-11'),
('6D10.Z', 'Trastorno de personalidad, sin especificación', 'category', false, false, 'CIE-11'),
('6D11', 'Rasgos o patrones de personalidad prominentes', 'category', false, false, 'CIE-11'),
('6D11.0', 'Afectividad negativa en los trastornos o dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('6D11.1', 'Desapego en los trastornos o dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('6D11.2', 'Comportamiento disocial en los trastornos o dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('6D11.3', 'Desinhibición en los trastornos o dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('6D11.4', 'Características anancásticas en los trastornos o las dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('6D11.5', 'Patrón límite', 'category', false, false, 'CIE-11'),
('6D30', 'Trastorno exhibicionista', 'category', false, false, 'CIE-11'),
('6D31', 'Trastorno voyeurista', 'category', false, false, 'CIE-11'),
('6D32', 'Trastorno pedofílico', 'category', false, false, 'CIE-11'),
('6D33', 'Trastorno por sadismo sexual coercitivo', 'category', false, false, 'CIE-11'),
('6D34', 'Frotismo', 'category', false, false, 'CIE-11'),
('6D35', 'Otros trastornos parafílicos que involucran a personas sin su consentimiento', 'category', false, false, 'CIE-11'),
('6D36', 'Trastorno parafílico que involucra comportamientos en solitario o individuos que dieron su consentimiento', 'category', false, false, 'CIE-11'),
('6D3Z', 'Trastornos parafílicos, sin especificación', 'category', false, false, 'CIE-11'),
('6D50', 'Trastorno facticio impuesto a uno mismo', 'category', false, false, 'CIE-11'),
('6D51', 'Trastorno facticio impuesto a otro', 'category', false, false, 'CIE-11'),
('6D5Z', 'Trastornos facticios, sin especificación', 'category', false, false, 'CIE-11'),
('6D70', 'Delirium', 'category', false, false, 'CIE-11'),
('6D70.0', 'Delirio por enfermedad clasificada en otra parte', 'category', false, false, 'CIE-11'),
('6D70.1', 'Delirium debido a sustancias psicoactivas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D70.2', 'Delirium debido a factores etiológicos múltiples', 'category', false, false, 'CIE-11'),
('6D70.Y', 'Delirium, otra causa especificada', 'category', false, false, 'CIE-11'),
('6D70.Z', 'Delirium, de causa no especificada o desconocida', 'category', false, false, 'CIE-11'),
('6D71', 'Trastorno neurocognitivo leve', 'category', false, false, 'CIE-11'),
('6D72', 'Trastorno amnésico', 'category', false, false, 'CIE-11'),
('6D72.0', 'Trastorno amnésico por enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('6D72.1', 'Trastorno amnésico debido a sustancias psicoactivas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D72.10', 'Trastorno amnésico debido al uso de alcohol', 'category', false, false, 'CIE-11'),
('6D72.11', 'Trastorno amnésico debido al uso de sedantes, hipnóticos o ansiolíticos', 'category', false, false, 'CIE-11'),
('6D72.12', 'Trastorno amnésico debido a otra sustancia psicoactiva especificada, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D72.13', 'Trastorno amnésico por uso de inhalantes volátiles', 'category', false, false, 'CIE-11'),
('6D72.Y', 'Trastorno amnésico, otra causa especificada', 'category', false, false, 'CIE-11'),
('6D72.Z', 'Trastorno amnésico, causa desconocida o no especificada', 'category', false, false, 'CIE-11'),
('6D80', 'Demencia debida a la enfermedad de Alzheimer', 'category', false, false, 'CIE-11'),
('6D80.0', 'Demencia debida a la enfermedad de Alzheimer de inicio temprano', 'category', false, false, 'CIE-11'),
('6D80.1', 'Demencia debida a la enfermedad de Alzheimer de inicio tardío', 'category', false, false, 'CIE-11'),
('6D80.2', 'Demencia debida a la enfermedad de Alzheimer, de tipo mixto, con enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('6D80.3', 'Demencia debida a la enfermedad de Alzheimer, de tipo mixto, con otras etiologías no vasculares', 'category', false, false, 'CIE-11'),
('6D80.Z', 'Demencia debida a la enfermedad de Alzheimer, inicio desconocido o no especificado', 'category', false, false, 'CIE-11'),
('6D81', 'Demencia debida a una enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('6D82', 'Demencia debida a la enfermedad por cuerpos de Lewy', 'category', false, false, 'CIE-11'),
('6D83', 'Demencia frontotemporal', 'category', false, false, 'CIE-11'),
('6D84', 'Demencia por sustancias psicoactivas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D84.0', 'Demencia por uso de alcohol', 'category', false, false, 'CIE-11'),
('6D84.1', 'Demencia por uso de sedantes, hipnóticos o ansiolíticos', 'category', false, false, 'CIE-11'),
('6D84.2', 'Demencia por uso de inhalantes volátiles', 'category', false, false, 'CIE-11'),
('6D84.Y', 'Demencia debida otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6D85', 'Demencia debida a enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('6D85.0', 'Demencia debida a la enfermedad de Parkinson', 'category', false, false, 'CIE-11'),
('6D85.1', 'Demencia debida a la enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('6D85.2', 'Demencia por exposición a metales pesados y otras toxinas', 'category', false, false, 'CIE-11'),
('6D85.3', 'Demencia por el virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('6D85.4', 'Demencia debida a esclerosis múltiple', 'category', false, false, 'CIE-11'),
('6D85.5', 'Demencia debida a enfermedades priónicas', 'category', false, false, 'CIE-11'),
('6D85.6', 'Demencia debida a hidrocefalia de presión normal', 'category', false, false, 'CIE-11'),
('6D85.7', 'Demencia debida a un traumatismo en la cabeza', 'category', false, false, 'CIE-11'),
('6D85.8', 'Demencia debida a pelagra', 'category', false, false, 'CIE-11'),
('6D85.9', 'Demencia debida al síndrome de Down', 'category', false, false, 'CIE-11'),
('6D85.Y', 'Demencia debida a otras enfermedades especificadas clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('6D86', 'Trastornos psicológicos o del comportamiento en la demencia', 'category', false, false, 'CIE-11'),
('6D86.0', 'Síntomas psicóticos en la demencia', 'category', false, false, 'CIE-11'),
('6D86.1', 'Síntomas del estado de ánimo en la demencia', 'category', false, false, 'CIE-11'),
('6D86.2', 'Síntomas de ansiedad en la demencia', 'category', false, false, 'CIE-11'),
('6D86.3', 'Apatía en la demencia', 'category', false, false, 'CIE-11'),
('6D86.4', 'Agitación o agresión en la demencia', 'category', false, false, 'CIE-11'),
('6D86.5', 'Desinhibición en la demencia', 'category', false, false, 'CIE-11'),
('6D86.6', 'Persona vagabunda con demencia', 'category', false, false, 'CIE-11'),
('6D86.Y', 'Otros trastornos psicológicos o del comportamiento especificados en la demencia', 'category', false, false, 'CIE-11'),
('6D86.Z', 'Trastornos psicológicos o del comportamiento en la demencia, sin especificación', 'category', false, false, 'CIE-11'),
('6D8Y', 'Demencia, otra causa especificada', 'category', false, false, 'CIE-11'),
('6D8Z', 'Demencia, causa desconocida o sin especificación', 'category', false, false, 'CIE-11'),
('6E0Y', 'Otros trastornos neurocognitivos especificados', 'category', false, false, 'CIE-11'),
('6E0Z', 'Trastornos neurocognitivos, sin especificación', 'category', false, false, 'CIE-11'),
('6E20', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, sin síntomas psicóticos', 'category', false, false, 'CIE-11'),
('6E21', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, con síntomas psicóticos', 'category', false, false, 'CIE-11'),
('6E2Z', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('6E40', 'Factores psicológicos o del comportamiento que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.0', 'Trastorno mental que afecta a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.1', 'Síntomas psicológicos que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.2', 'Rasgos de personalidad o estilo de afrontamiento que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.3', 'Comportamientos de salud inadaptados que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.4', 'Respuesta fisiológica relacionada con el estrés que afecta a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.Y', 'Otros factores psicológicos o del comportamiento especificados que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.Z', 'Factores psicológicos o del comportamiento que afectan a enfermedades o trastornos clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('6E60', 'Síndrome de neurodesarrollo secundario', 'category', false, false, 'CIE-11'),
('6E60.0', 'Síndrome secundario del habla o lenguaje', 'category', false, false, 'CIE-11'),
('6E60.Y', 'Otro síndrome secundario del neurodesarrollo especificado', 'category', false, false, 'CIE-11'),
('6E60.Z', 'Síndrome secundario del neurodesarrollo, sin especificación', 'category', false, false, 'CIE-11'),
('6E61', 'Síndrome psicótico secundario', 'category', false, false, 'CIE-11'),
('6E61.0', 'Síndrome psicótico secundario, con alucinaciones', 'category', false, false, 'CIE-11'),
('6E61.1', 'Síndrome psicótico secundario, con delirios', 'category', false, false, 'CIE-11'),
('6E61.2', 'Síndrome psicótico secundario, con alucinaciones y delirios', 'category', false, false, 'CIE-11'),
('6E61.3', 'Síndrome psicótico secundario, con síntomas no especificados', 'category', false, false, 'CIE-11'),
('6E62', 'Síndrome secundario del estado del ánimo', 'category', false, false, 'CIE-11'),
('6E62.0', 'Síndrome secundario del estado del ánimo, con síntomas depresivos', 'category', false, false, 'CIE-11'),
('6E62.1', 'Síndrome secundario afectivo, con síntomas maníacos', 'category', false, false, 'CIE-11'),
('6E62.2', 'Síndrome secundario del estado del ánimo, con síntomas mixtos', 'category', false, false, 'CIE-11'),
('6E62.3', 'Síndrome secundario del estado del ánimo, con síntomas no especificados', 'category', false, false, 'CIE-11'),
('6E63', 'Síndrome de ansiedad secundario', 'category', false, false, 'CIE-11'),
('6E64', 'Síndrome secundario obsesivo-compulsivo o relacionado', 'category', false, false, 'CIE-11'),
('6E65', 'Síndrome disociativo secundario', 'category', false, false, 'CIE-11'),
('6E66', 'Síndrome secundario de control de los impulsos', 'category', false, false, 'CIE-11'),
('6E67', 'Síndrome neurocognitivo secundario', 'category', false, false, 'CIE-11'),
('6E68', 'Cambio secundario de la personalidad', 'category', false, false, 'CIE-11'),
('6E69', 'Síndrome de catatonia secundaria', 'category', false, false, 'CIE-11'),
('6E6Y', 'Síndromes secundarios mentales o del comportamiento especificados asociados con enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E6Z', 'Síndromes secundarios mentales o del comportamiento asociados con enfermedades o trastornos clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('6E8Y', 'Otros trastornos mentales, del comportamiento o del neurodesarrollo especificados', 'category', false, false, 'CIE-11'),
('6E8Z', 'Trastornos mentales, del comportamiento o del neurodesarrollo, sin especificación', 'category', false, false, 'CIE-11'),
('7A00', 'Insomnio crónico', 'category', false, false, 'CIE-11'),
('7A01', 'Insomnio de corta duración', 'category', false, false, 'CIE-11'),
('7A0Z', 'Trastornos de insomnio, sin especificación', 'category', false, false, 'CIE-11'),
('7A20', 'Narcolepsia', 'category', false, false, 'CIE-11'),
('7A20.0', 'Narcolepsia, tipo 1', 'category', false, false, 'CIE-11'),
('7A20.1', 'Narcolepsia, tipo 2', 'category', false, false, 'CIE-11'),
('7A20.Z', 'Narcolepsia, sin especificación', 'category', false, false, 'CIE-11'),
('7A21', 'Hipersomnia idiopática', 'category', false, false, 'CIE-11'),
('7A22', 'Síndrome de Kleine-Levin', 'category', false, false, 'CIE-11'),
('7A23', 'Hipersomnia debida a un problema médico', 'category', false, false, 'CIE-11'),
('7A24', 'Hipersomnia debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A25', 'Hipersomnia asociada con un trastorno mental', 'category', false, false, 'CIE-11'),
('7A26', 'Síndrome de sueño insuficiente', 'category', false, false, 'CIE-11'),
('7A2Y', 'Otros trastornos de hipersomnolencia especificados', 'category', false, false, 'CIE-11'),
('7A2Z', 'Trastornos de hipersomnolencia, sin especificación', 'category', false, false, 'CIE-11'),
('7A40', 'Apneas centrales del sueño', 'category', false, false, 'CIE-11'),
('7A40.0', 'Apnea central primaria del sueño', 'category', false, false, 'CIE-11'),
('7A40.1', 'Apnea central del sueño primaria de la infancia', 'category', false, false, 'CIE-11'),
('7A40.2', 'Apnea central del sueño primaria de la prematuridad', 'category', false, false, 'CIE-11'),
('7A40.3', 'Apnea central del sueño debida a respiración de Cheyne-Stokes', 'category', false, false, 'CIE-11'),
('7A40.4', 'Apnea central del sueño debida a un problema médico sin respiración de Cheyne-Stokes', 'category', false, false, 'CIE-11'),
('7A40.5', 'Apnea central del sueño debida a respiración periódica a grandes alturas', 'category', false, false, 'CIE-11'),
('7A40.6', 'Apnea central del sueño debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A40.7', 'Apnea central del sueño que aparece durante un tratamiento', 'category', false, false, 'CIE-11'),
('7A40.Y', 'Otras apneas centrales del sueño especificadas', 'category', false, false, 'CIE-11'),
('7A40.Z', 'Apneas centrales del sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A41', 'Apnea obstructiva del sueño', 'category', false, false, 'CIE-11'),
('7A42', 'Trastornos de hipoventilación o hipoxemia relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A42.0', 'Síndrome de hipoventilación en la obesidad', 'category', false, false, 'CIE-11'),
('7A42.1', 'Hipoventilación central alveolar congénita relacionada con el sueño', 'category', false, false, 'CIE-11'),
('7A42.2', 'Hipoventilación central no congénita con anomalías hipotalámicas', 'category', false, false, 'CIE-11'),
('7A42.3', 'Hipoventilación alveolar central idiopática', 'category', false, false, 'CIE-11'),
('7A42.4', 'Hipoventilación relacionada con el sueño debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A42.5', 'Hipoventilación durante el sueño debida a un problema médico', 'category', false, false, 'CIE-11'),
('7A42.6', 'Hipoxemia relacionada con el sueño debida a una afección médica', 'category', false, false, 'CIE-11'),
('7A42.Y', 'Otros trastornos especificados de hipoventilación o hipoxemia relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A42.Z', 'Trastornos de hipoventilación o hipoxemia relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A4Y', 'Otros trastornos respiratorios especificados relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A4Z', 'Trastornos respiratorios relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A60', 'Trastorno por retraso de la fase del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A61', 'Trastorno por adelanto de la fase del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A62', 'Trastorno por ritmo irregular del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A63', 'Trastorno por ritmo del sueño y la vigilia distinto de 24 horas', 'category', false, false, 'CIE-11'),
('7A64', 'Trastorno del ritmo circadiano del sueño y la vigilia debido al trabajo por turnos', 'category', false, false, 'CIE-11'),
('7A65', 'Trastorno del ritmo circadiano del sueño y la vigilia, del tipo por cambio de zona horaria', 'category', false, false, 'CIE-11'),
('7A6Z', 'Trastornos del ciclo circadiano del sueño y la vigilia, sin especificación', 'category', false, false, 'CIE-11'),
('7A80', 'Síndrome de las piernas inquietas', 'category', false, false, 'CIE-11'),
('7A81', 'Trastorno por movimientos periódicos de las extremidades', 'category', false, false, 'CIE-11'),
('7A82', 'Calambres en las piernas durante el sueño', 'category', false, false, 'CIE-11'),
('7A83', 'Bruxismo durante el sueño', 'category', false, false, 'CIE-11'),
('7A84', 'Movimientos rítmicos durante el sueño', 'category', false, false, 'CIE-11'),
('7A85', 'Mioclonías benignas del sueño en la lactancia', 'category', false, false, 'CIE-11'),
('7A86', 'Mioclonía propioespinal al inicio del sueño', 'category', false, false, 'CIE-11'),
('7A87', 'Movimientos anormales durante el sueño debido a un problema médico', 'category', false, false, 'CIE-11'),
('7A88', 'Trastorno del movimiento relacionado con el sueño debido a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A8Y', 'Otros trastornos especificados del movimiento relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A8Z', 'Trastornos del movimiento relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7B00', 'Trastornos del despertar del sueño no REM', 'category', false, false, 'CIE-11'),
('7B00.0', 'Despertares confusionales', 'category', false, false, 'CIE-11'),
('7B00.1', 'Trastorno de sonambulismo', 'category', false, false, 'CIE-11'),
('7B00.2', 'Terror del sueño', 'category', false, false, 'CIE-11'),
('7B00.3', 'Trastorno de la conducta alimentaria relacionado con el sueño', 'category', false, false, 'CIE-11'),
('7B00.Y', 'Otros trastornos del despertar del sueño no REM', 'category', false, false, 'CIE-11'),
('7B00.Z', 'Trastornos del despertar del sueño no REM, sin especificación', 'category', false, false, 'CIE-11'),
('7B01', 'Parasomnias relacionadas con el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.0', 'Trastorno del comportamiento durante el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.1', 'Parálisis del sueño aislada recurrente', 'category', false, false, 'CIE-11'),
('7B01.2', 'Pesadillas', 'category', false, false, 'CIE-11'),
('7B01.Y', 'Otras parasomnias especificadas relacionadas con el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.Z', 'Parasomnias relacionadas con el sueño REM, sin especificación', 'category', false, false, 'CIE-11'),
('7B02', 'Otras parasomnias', 'category', false, false, 'CIE-11'),
('7B02.0', 'Síndrome hipnagógico de la cabeza explosiva', 'category', false, false, 'CIE-11'),
('7B02.1', 'Alucinaciones durante el sueño', 'category', false, false, 'CIE-11'),
('7B02.2', 'Trastorno de parasomnia debido a un problema médico', 'category', false, false, 'CIE-11'),
('7B02.3', 'Trastorno de parasomnia debido a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7B0Y', 'Otros trastornos especificados de parasomnia', 'category', false, false, 'CIE-11'),
('7B0Z', 'Trastornos de parasomnia, sin especificación', 'category', false, false, 'CIE-11'),
('7B2Y', 'Otros trastornos especificados del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7B2Z', 'Trastornos del sueño y la vigilia, sin especificación', 'category', false, false, 'CIE-11'),
('8A00', 'Parkinsonismo', 'category', false, false, 'CIE-11'),
('8A00.0', 'Enfermedad de Parkinson', 'category', false, false, 'CIE-11'),
('8A00.00', 'Enfermedad de Parkinson esporádica', 'category', false, false, 'CIE-11'),
('8A00.01', 'Enfermedad de Parkinson familiar', 'category', false, false, 'CIE-11'),
('8A00.0Y', 'Otra enfermedad de Parkinson especificada', 'category', false, false, 'CIE-11'),
('8A00.0Z', 'Enfermedad de Parkinson, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.1', 'Parkinsonismo atípico', 'category', false, false, 'CIE-11'),
('8A00.10', 'Parálisis supranuclear progresiva', 'category', false, false, 'CIE-11'),
('8A00.1Y', 'Otro parkinsonismo atípico especificado', 'category', false, false, 'CIE-11'),
('8A00.1Z', 'Parkinsonismo atípico, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.2', 'Parkinsonismo secundario', 'category', false, false, 'CIE-11'),
('8A00.20', 'Parkinsonismo debido a trastornos degenerativos hereditarios', 'category', false, false, 'CIE-11'),
('8A00.21', 'Síndrome de hemiatrofia con hemiparkinsonismo', 'category', false, false, 'CIE-11'),
('8A00.22', 'Parkinsonismo infeccioso o post infeccioso', 'category', false, false, 'CIE-11'),
('8A00.23', 'Parkinsonismo vascular', 'category', false, false, 'CIE-11'),
('8A00.24', 'Parkinsonismo provocado por medicamentos', 'category', false, false, 'CIE-11'),
('8A00.25', 'Parkinsonismo postraumático', 'category', false, false, 'CIE-11'),
('8A00.26', 'Parkinsonismo por lesiones estructurales', 'category', false, false, 'CIE-11'),
('8A00.2Y', 'Otro parkinsonismo secundario especificado', 'category', false, false, 'CIE-11'),
('8A00.2Z', 'Parkinsonismo secundario, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.3', 'Parkinsonismo funcional', 'category', false, false, 'CIE-11'),
('8A00.Y', 'Otro parkinsonismo especificado', 'category', false, false, 'CIE-11'),
('8A00.Z', 'Parkinsonismo, sin especificación', 'category', false, false, 'CIE-11'),
('8A01', 'Trastornos coreiformes', 'category', false, false, 'CIE-11'),
('8A01.0', 'Corea hereditaria benigna', 'category', false, false, 'CIE-11'),
('8A01.1', 'Corea secundaria', 'category', false, false, 'CIE-11'),
('8A01.10', 'Enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('8A01.11', 'Corea por afecciones similares a la enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('8A01.12', 'Corea debida a atrofia dentato-rubro-pálido-luisiana', 'category', false, false, 'CIE-11'),
('8A01.13', 'Corea por enfermedad de Wilson', 'category', false, false, 'CIE-11'),
('8A01.14', 'Corea por causas infecciosas o parainfecciosas', 'category', false, false, 'CIE-11'),
('8A01.15', 'Corea por lupus eritematoso sistémico', 'category', false, false, 'CIE-11'),
('8A01.16', 'Corea provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8A01.1Y', 'Otra corea secundaria especificada', 'category', false, false, 'CIE-11'),
('8A01.1Z', 'Corea secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A01.2', 'Hemicorea o hemibalismo', 'category', false, false, 'CIE-11'),
('8A01.20', 'Hemicorea', 'category', false, false, 'CIE-11'),
('8A01.21', 'Balismo', 'category', false, false, 'CIE-11'),
('8A01.22', 'Hemibalismo', 'category', false, false, 'CIE-11'),
('8A01.Y', 'Otros trastornos coreiformes especificados', 'category', false, false, 'CIE-11'),
('8A01.Z', 'Trastornos coreiformes, sin especificación', 'category', false, false, 'CIE-11'),
('8A02', 'Distonías', 'category', false, false, 'CIE-11'),
('8A02.0', 'Distonía primaria', 'category', false, false, 'CIE-11'),
('8A02.00', 'Blefaroespasmo esencial benigno', 'category', false, false, 'CIE-11'),
('8A02.0Y', 'Otra distonía primaria especificada', 'category', false, false, 'CIE-11'),
('8A02.0Z', 'Distonía primaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A02.1', 'Distonía secundaria', 'category', false, false, 'CIE-11'),
('8A02.10', 'Distonía provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8A02.11', 'Distonía combinada', 'category', false, false, 'CIE-11'),
('8A02.12', 'Distonía asociada a trastornos degenerativos hereditarios', 'category', false, false, 'CIE-11'),
('8A02.1Y', 'Otra distonía secundaria especificada', 'category', false, false, 'CIE-11'),
('8A02.1Z', 'Distonía secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A02.2', 'Distonía paroxística', 'category', false, false, 'CIE-11'),
('8A02.3', 'Distonía o espasmos funcionales', 'category', false, false, 'CIE-11'),
('8A02.Y', 'Otros trastornos distónicos especificados', 'category', false, false, 'CIE-11'),
('8A02.Z', 'Trastornos distónicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A03', 'Trastornos atáxicos', 'category', false, false, 'CIE-11'),
('8A03.0', 'Ataxia congénita', 'category', false, false, 'CIE-11'),
('8A03.1', 'Ataxia hereditaria', 'category', false, false, 'CIE-11'),
('8A03.10', 'Ataxia de Friedreich', 'category', false, false, 'CIE-11'),
('8A03.11', 'Ataxia por xantomatosis cerebrotendinosa', 'category', false, false, 'CIE-11'),
('8A03.12', 'Ataxia por enfermedad de Refsum', 'category', false, false, 'CIE-11'),
('8A03.13', 'Ataxia por abetalipoproteinemia', 'category', false, false, 'CIE-11'),
('8A03.14', 'Ataxia episódica hereditaria', 'category', false, false, 'CIE-11'),
('8A03.15', 'Ataxia debido a mutaciones mitocondriales', 'category', false, false, 'CIE-11'),
('8A03.16', 'Ataxia espinocerebelosa', 'category', false, false, 'CIE-11'),
('8A03.1Y', 'Otra ataxia hereditaria especificada', 'category', false, false, 'CIE-11'),
('8A03.1Z', 'Ataxia hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.2', 'Ataxia degenerativa no hereditaria', 'category', false, false, 'CIE-11'),
('8A03.20', 'atrofia corticocerebelosa de aparición tardía', 'category', false, false, 'CIE-11'),
('8A03.2Y', 'Otra ataxia degenerativa no hereditaria especificada', 'category', false, false, 'CIE-11'),
('8A03.2Z', 'Ataxia degenerativa no hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.3', 'Ataxia adquirida', 'category', false, false, 'CIE-11'),
('8A03.30', 'Ataxia por degeneración cerebelosa alcohólica', 'category', false, false, 'CIE-11'),
('8A03.3Y', 'Otra ataxia adquirida especificada', 'category', false, false, 'CIE-11'),
('8A03.3Z', 'Ataxia adquirida, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.Y', 'Otros trastornos atáxicos especificados', 'category', false, false, 'CIE-11'),
('8A03.Z', 'Trastornos atáxicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A04', 'Trastornos asociados con temblor', 'category', false, false, 'CIE-11'),
('8A04.0', 'Temblor fisiológico intensificado', 'category', false, false, 'CIE-11'),
('8A04.1', 'Temblor esencial o temblores afines', 'category', false, false, 'CIE-11'),
('8A04.2', 'Temblor de reposo', 'category', false, false, 'CIE-11'),
('8A04.3', 'Temblor secundario', 'category', false, false, 'CIE-11'),
('8A04.30', 'Temblor por trastornos metabólicos', 'category', false, false, 'CIE-11'),
('8A04.31', 'Temblor debido al uso agudo o crónico de sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('8A04.32', 'Temblor por abstinencia de drogas', 'category', false, false, 'CIE-11'),
('8A04.33', 'Temblor debido a ciertas enfermedades especificadas del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A04.3Y', 'Otro temblor secundario especificado', 'category', false, false, 'CIE-11'),
('8A04.3Z', 'Temblor secundario, sin especificación', 'category', false, false, 'CIE-11'),
('8A04.4', 'Temblor funcional', 'category', false, false, 'CIE-11'),
('8A04.Y', 'Otros trastornos asociados con temblor especificados', 'category', false, false, 'CIE-11'),
('8A04.Z', 'Trastornos asociados con temblor, sin especificación', 'category', false, false, 'CIE-11'),
('8A05', 'Trastornos por tics', 'category', false, false, 'CIE-11'),
('8A05.0', 'Tics o trastornos por tics primarios', 'category', false, false, 'CIE-11'),
('8A05.00', 'Síndrome de Tourette', 'category', false, false, 'CIE-11'),
('8A05.01', 'Trastorno por tic motor crónico', 'category', false, false, 'CIE-11'),
('8A05.02', 'Trastorno por tic fónico crónico', 'category', false, false, 'CIE-11'),
('8A05.03', 'Tics motores transitorios', 'category', false, false, 'CIE-11'),
('8A05.0Y', 'Otros tics o trastornos por tics primarios especificados', 'category', false, false, 'CIE-11'),
('8A05.0Z', 'Tics o trastornos por tics primarios, sin especificación', 'category', false, false, 'CIE-11'),
('8A05.1', 'Tics nerviosos secundarios', 'category', false, false, 'CIE-11'),
('8A05.10', 'Tics infecciosos o postinfecciosos', 'category', false, false, 'CIE-11'),
('8A05.11', 'Tics debidos a trastornos del desarrollo', 'category', false, false, 'CIE-11'),
('8A05.1Y', 'Otros tics nerviosos secundarios especificados', 'category', false, false, 'CIE-11'),
('8A05.1Z', 'Tics nerviosos secundarios, sin especificación', 'category', false, false, 'CIE-11'),
('8A05.Y', 'Otros trastornos especificados por tics', 'category', false, false, 'CIE-11'),
('8A05.Z', 'Trastornos por tics, sin especificación', 'category', false, false, 'CIE-11'),
('8A06', 'Trastornos mioclónicos', 'category', false, false, 'CIE-11'),
('8A06.0', 'Mioclono esencial', 'category', false, false, 'CIE-11'),
('8A06.1', 'Mioclono segmentario', 'category', false, false, 'CIE-11'),
('8A06.2', 'Mioclono focal', 'category', false, false, 'CIE-11'),
('8A06.20', 'Mioclono del paladar', 'category', false, false, 'CIE-11'),
('8A06.21', 'Hipo crónico', 'category', false, false, 'CIE-11'),
('8A06.2Y', 'Otro mioclono focal especificado', 'category', false, false, 'CIE-11'),
('8A06.2Z', 'Mioclono focal, sin especificación', 'category', false, false, 'CIE-11'),
('8A06.Y', 'Otros trastornos mioclónicos especificados', 'category', false, false, 'CIE-11'),
('8A06.Z', 'Trastornos mioclónicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A07', 'Algunos trastornos del movimiento especificados', 'category', false, false, 'CIE-11'),
('8A07.0', 'Estereotipias', 'category', false, false, 'CIE-11'),
('8A07.00', 'Estereotipia primaria', 'category', false, false, 'CIE-11'),
('8A07.01', 'Estereotipia secundaria', 'category', false, false, 'CIE-11'),
('8A07.0Y', 'Otras estereotipias especificadas', 'category', false, false, 'CIE-11'),
('8A07.0Z', 'Estereotipias, sin especificación', 'category', false, false, 'CIE-11'),
('8A07.1', 'Acatisia', 'category', false, false, 'CIE-11'),
('8A07.2', 'Reflejo de sobresalto excesivo', 'category', false, false, 'CIE-11'),
('8A0Y', 'Otro trastorno especificado del movimiento', 'category', false, false, 'CIE-11'),
('8A0Z', 'Trastornos del movimiento, sin especificación', 'category', false, false, 'CIE-11'),
('8A20', 'Enfermedad de Alzheimer', 'category', false, false, 'CIE-11'),
('8A21', 'Atrofias corticales focales progresivas', 'category', false, false, 'CIE-11'),
('8A21.0', 'Atrofia cortical posterior', 'category', false, false, 'CIE-11'),
('8A21.Y', 'Otras atrofias corticales focales progresivas especificadas', 'category', false, false, 'CIE-11'),
('8A21.Z', 'Atrofias corticales focales progresivas, sin especificación', 'category', false, false, 'CIE-11'),
('8A22', 'Enfermedad de cuerpos de Lewy', 'category', false, false, 'CIE-11'),
('8A23', 'Degeneración lobular frontotemporal', 'category', false, false, 'CIE-11'),
('8A2Y', 'Otros trastornos especificados con deterioro neurocognitivo como característica destacada', 'category', false, false, 'CIE-11'),
('8A2Z', 'Trastornos con deterioro neurocognitivo como característica destacada, sin especificación', 'category', false, false, 'CIE-11'),
('8A40', 'Esclerosis múltiple', 'category', false, false, 'CIE-11'),
('8A40.0', 'Esclerosis múltiple recurrente- remitente', 'category', false, false, 'CIE-11'),
('8A40.1', 'Esclerosis múltiple progresiva primaria', 'category', false, false, 'CIE-11'),
('8A40.2', 'Esclerosis múltiple progresiva secundaria', 'category', false, false, 'CIE-11'),
('8A40.Y', 'Otra esclerosis múltiple especificada', 'category', false, false, 'CIE-11'),
('8A40.Z', 'Esclerosis múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('8A41', 'Síndromes desmielinizantes del sistema nervioso central aislados', 'category', false, false, 'CIE-11'),
('8A41.0', 'Mielitis transversa', 'category', false, false, 'CIE-11'),
('8A41.1', 'Neuromielitis óptica con positividad a anticuerpos contra la glicoproteína oligodentrocitaria de mielina', 'category', false, false, 'CIE-11'),
('8A41.Y', 'Otros síndromes desmielinizantes aislados especificados del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A41.Z', 'Síndromes desmielinizantes aislados del sistema nervioso central, sin especificación', 'category', false, false, 'CIE-11'),
('8A42', 'Encefalomielitis aguda diseminada', 'category', false, false, 'CIE-11'),
('8A42.0', 'Leucoencefalitis hemorrágica aguda', 'category', false, false, 'CIE-11'),
('8A42.Y', 'Otra encefalomielitis diseminada aguda especificada', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
