-- CIE11 Import Part 66
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XM79N8', 'Tofisopam', 'category', false, false, 'CIE-11'),
('XM9X46', 'Benzodiazepina tranquilizante', 'category', false, false, 'CIE-11'),
('XM1VC3', 'Triazolam', 'category', false, false, 'CIE-11'),
('XM36R8', 'Clorazepato de potasio', 'category', false, false, 'CIE-11'),
('XM94Z2', 'Adinazolam', 'category', false, false, 'CIE-11'),
('XM66N4', 'Doxefazepam', 'category', false, false, 'CIE-11'),
('XM4BU2', 'Cinolazepam', 'category', false, false, 'CIE-11'),
('XM8CM3', 'Derivados de difenilmetano', 'category', false, false, 'CIE-11'),
('XM8CV8', 'Hidroxicina', 'category', false, false, 'CIE-11'),
('XM70L1', 'Captodiame', 'category', false, false, 'CIE-11'),
('XM96H3', 'Carbamatos', 'category', false, false, 'CIE-11'),
('XM3MX1', 'Meprobamato', 'category', false, false, 'CIE-11'),
('XM8G67', 'Emilcamato', 'category', false, false, 'CIE-11'),
('XM3XU7', 'Aldehídos y derivados', 'category', false, false, 'CIE-11'),
('XM8AH5', 'Hidrato de cloral', 'category', false, false, 'CIE-11'),
('XM8D85', 'Cloralodol', 'category', false, false, 'CIE-11'),
('XM0ZC2', 'Paracetilaldehído', 'category', false, false, 'CIE-11'),
('XM46J8', 'Hidrato de cloral acetilglicinamida', 'category', false, false, 'CIE-11'),
('XM9V32', 'Dicloralfenazona', 'category', false, false, 'CIE-11'),
('XM0V58', 'Cinamaldehído', 'category', false, false, 'CIE-11'),
('XM37U9', 'Hexil cinamal', 'category', false, false, 'CIE-11'),
('XM5TZ2', 'Amilo cinamaldehído', 'category', false, false, 'CIE-11'),
('XM9J50', 'Hidrato de buticloral', 'category', false, false, 'CIE-11'),
('XM6R00', 'Derivados de piperidinediona', 'category', false, false, 'CIE-11'),
('XM5S80', 'Glutetimida', 'category', false, false, 'CIE-11'),
('XM2MN1', 'Metiprilona', 'category', false, false, 'CIE-11'),
('XM2MC9', 'Piritildiona', 'category', false, false, 'CIE-11'),
('XM4YG0', 'Barbitúricos y derivados', 'category', false, false, 'CIE-11'),
('XM3Z73', 'Narcobarbital', 'category', false, false, 'CIE-11'),
('XM01Z3', 'Pentobarbital', 'category', false, false, 'CIE-11'),
('XM01F5', 'Amobarbital', 'category', false, false, 'CIE-11'),
('XM8TB8', 'Butobarbital', 'category', false, false, 'CIE-11'),
('XM2B90', 'Barbital', 'category', false, false, 'CIE-11'),
('XM6QG0', 'Secobarbital', 'category', false, false, 'CIE-11'),
('XM28V1', 'Talbutal', 'category', false, false, 'CIE-11'),
('XM6NX3', 'Vinilbital', 'category', false, false, 'CIE-11'),
('XM9VX7', 'Vinbarbital', 'category', false, false, 'CIE-11'),
('XM89L9', 'Ciclobarbital', 'category', false, false, 'CIE-11'),
('XM7ZK9', 'Heptabarbital', 'category', false, false, 'CIE-11'),
('XM8FN0', 'Alobarbital', 'category', false, false, 'CIE-11'),
('XM8C15', 'Proxibarbal', 'category', false, false, 'CIE-11'),
('XM60H4', 'Metilfenobarbital', 'category', false, false, 'CIE-11'),
('XM2605', 'Fenobarbital', 'category', false, false, 'CIE-11'),
('XM5J41', 'Primidona', 'category', false, false, 'CIE-11'),
('XM45T7', 'Barbexaclone', 'category', false, false, 'CIE-11'),
('XM64T5', 'Metarbital', 'category', false, false, 'CIE-11'),
('XM1ZM1', 'Reposal', 'category', false, false, 'CIE-11'),
('XM1WN6', 'Etallobarbital', 'category', false, false, 'CIE-11'),
('XM8YV1', 'Aprobarbital', 'category', false, false, 'CIE-11'),
('XM50Q3', 'Bralobarbital', 'category', false, false, 'CIE-11'),
('XM3UQ5', 'Butalbital', 'category', false, false, 'CIE-11'),
('XM6XH1', 'Butalilonal', 'category', false, false, 'CIE-11'),
('XM4C65', 'Difebarbamato', 'category', false, false, 'CIE-11'),
('XM8DQ9', 'Metobarbital, metobarbitona', 'category', false, false, 'CIE-11'),
('XM3YG4', 'Nealbarbital', 'category', false, false, 'CIE-11'),
('XM6F85', 'Probarbital', 'category', false, false, 'CIE-11'),
('XM37N4', 'Propalilonal', 'category', false, false, 'CIE-11'),
('XM81J9', 'Secbutabarbital', 'category', false, false, 'CIE-11'),
('XM4843', 'Fármacos Z', 'category', false, false, 'CIE-11'),
('XM8LM1', 'Zopiclona', 'category', false, false, 'CIE-11'),
('XM8188', 'Zolpidem', 'category', false, false, 'CIE-11'),
('XM0UU3', 'zaleplon', 'category', false, false, 'CIE-11'),
('XM4DP1', 'Eszopiclona', 'category', false, false, 'CIE-11'),
('XM0GA0', 'Agonistas del receptor de melatonina', 'category', false, false, 'CIE-11'),
('XM7R38', 'Melatonina', 'category', false, false, 'CIE-11'),
('XM4Y11', 'Ramelteon', 'category', false, false, 'CIE-11'),
('XM0DX1', 'Tasimelteon', 'category', false, false, 'CIE-11'),
('XM93J2', 'Sales de bromuro', 'category', false, false, 'CIE-11'),
('XM5V35', 'Acecarbromale', 'category', false, false, 'CIE-11'),
('XM3260', 'Bromisoval', 'category', false, false, 'CIE-11'),
('XM7XH5', 'Bromoformo', 'category', false, false, 'CIE-11'),
('XM68H5', 'Carbromal', 'category', false, false, 'CIE-11'),
('XM4JD8', 'Acetilfeneturida', 'category', false, false, 'CIE-11'),
('XM0Y74', 'Alilisopropilacetilurea', 'category', false, false, 'CIE-11'),
('XM2MT0', 'Aliltribromide', 'category', false, false, 'CIE-11'),
('XM0FX2', 'Bromuro de amonio', 'category', false, false, 'CIE-11'),
('XM2P06', 'Anticonvulsivo hipnótico', 'category', false, false, 'CIE-11'),
('XM4LR0', 'Anticonvulsivo pirimidinediona', 'category', false, false, 'CIE-11'),
('XM80V1', 'Anticonvulsivo especificado', 'category', false, false, 'CIE-11'),
('XM2851', 'Apronal', 'category', false, false, 'CIE-11'),
('XM8WF0', 'Avomine', 'category', false, false, 'CIE-11'),
('XM34M8', 'Beta- Clor', 'category', false, false, 'CIE-11'),
('XM2S35', 'Bromal (hidrato)', 'category', false, false, 'CIE-11'),
('XM16D8', 'Compuestos de bromo (medicinal)', 'category', false, false, 'CIE-11'),
('XM0JD2', 'Bromo sedante', 'category', false, false, 'CIE-11'),
('XM14P7', 'Bromisovalum', 'category', false, false, 'CIE-11'),
('XM0L99', 'Bromural', 'category', false, false, 'CIE-11'),
('XM7Q19', 'bromuro de calcio', 'category', false, false, 'CIE-11'),
('XM44G1', 'Bromuros', 'category', false, false, 'CIE-11'),
('XM6Z70', 'Hidrato de cloral depresores del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM4A26', 'Depresores del sistema nervioso central hipnóticos especificados', 'category', false, false, 'CIE-11'),
('XM0MP0', 'Paraldehído depresores del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM2PX1', 'Derivado de cloral', 'category', false, false, 'CIE-11'),
('XM5HQ1', 'Cloramida', 'category', false, false, 'CIE-11'),
('XM1XU2', 'Cloretone', 'category', false, false, 'CIE-11'),
('XM7N56', 'Clorhexadol', 'category', false, false, 'CIE-11'),
('XM7GE6', 'Clometiazol', 'category', false, false, 'CIE-11'),
('XM58S5', 'Cloral Croton', 'category', false, false, 'CIE-11'),
('XM1L51', 'Dietilsulfona-dietilmetano', 'category', false, false, 'CIE-11'),
('XM5P16', 'Divalproex', 'category', false, false, 'CIE-11'),
('XM2ML0', 'Doriden', 'category', false, false, 'CIE-11'),
('XM0YS0', 'Dormison', 'category', false, false, 'CIE-11'),
('XM76A5', 'Ectilurea', 'category', false, false, 'CIE-11'),
('XM4SW2', 'Etclorvinol', 'category', false, false, 'CIE-11'),
('XM8HM5', 'Etinamato', 'category', false, false, 'CIE-11'),
('XM0959', 'Etifoxina', 'category', false, false, 'CIE-11'),
('XM5084', 'Hexapropimato', 'category', false, false, 'CIE-11'),
('XM3GR8', 'Medicamento hipnótico especificado', 'category', false, false, 'CIE-11'),
('XM1H40', 'Lactuca (virosa) (extracto)', 'category', false, false, 'CIE-11'),
('XM7EA2', 'Lactucario', 'category', false, false, 'CIE-11'),
('XM2447', 'Lechuga de opio', 'category', false, false, 'CIE-11'),
('XM1SJ9', 'Levanil', 'category', false, false, 'CIE-11'),
('XM9S20', 'Levoproma', 'category', false, false, 'CIE-11'),
('XM3C52', 'Metacualona', 'category', false, false, 'CIE-11'),
('XM8UW8', 'Metil sulfonal', 'category', false, false, 'CIE-11'),
('XM79Y3', 'Metilpentinol', 'category', false, false, 'CIE-11'),
('XM9L86', 'Niaprazina', 'category', false, false, 'CIE-11'),
('XM67F2', 'Noludar', 'category', false, false, 'CIE-11'),
('XM41Z4', 'Periclor', 'category', false, false, 'CIE-11'),
('XM7865', 'Petricloral', 'category', false, false, 'CIE-11'),
('XM8U36', 'Fenergán', 'category', false, false, 'CIE-11'),
('XM3YQ0', 'Bromuro de potasio', 'category', false, false, 'CIE-11'),
('XM23J2', 'Propionaldehido (medicinal)', 'category', false, false, 'CIE-11'),
('XM5KU5', 'Quaalude', 'category', false, false, 'CIE-11'),
('XM5YQ4', 'Sedativo mixto', 'category', false, false, 'CIE-11'),
('XM53R6', 'Sedormid', 'category', false, false, 'CIE-11'),
('XM5BF2', 'Serenesil', 'category', false, false, 'CIE-11'),
('XM8SU3', 'Bromuro de sodio', 'category', false, false, 'CIE-11'),
('XM9F88', 'Valproato de sodio', 'category', false, false, 'CIE-11'),
('XM4ZG6', 'Somno', 'category', false, false, 'CIE-11'),
('XM1BT3', 'Sopor', 'category', false, false, 'CIE-11'),
('XM2N03', 'Fármaco soporífero tipo especificado', 'category', false, false, 'CIE-11'),
('XM81Z5', 'Sulfonal', 'category', false, false, 'CIE-11'),
('XM9QV2', 'Sulfonetilmetano', 'category', false, false, 'CIE-11'),
('XM4YF8', 'Sulfonmetano', 'category', false, false, 'CIE-11'),
('XM8296', 'Tetronal', 'category', false, false, 'CIE-11'),
('XM6WP4', 'Tranquilizante con hipnótico o sedativo', 'category', false, false, 'CIE-11'),
('XM9XF5', 'Tribromacetaldehido', 'category', false, false, 'CIE-11'),
('XM1DU6', 'Tricloroetanol', 'category', false, false, 'CIE-11'),
('XM4236', 'Tricloroetil fosfato', 'category', false, false, 'CIE-11'),
('XM68E8', 'Triclofosa', 'category', false, false, 'CIE-11'),
('XM2334', 'Trional', 'category', false, false, 'CIE-11'),
('XM16S3', 'Triple bromuro', 'category', false, false, 'CIE-11'),
('XM3PP3', 'Raíz de valeriana', 'category', false, false, 'CIE-11'),
('XM0MV0', 'Tintura valeriana', 'category', false, false, 'CIE-11'),
('XM1WZ4', 'Valmid', 'category', false, false, 'CIE-11'),
('XM2TP4', 'Valnoctamida', 'category', false, false, 'CIE-11'),
('XM2AQ9', 'Weldorm', 'category', false, false, 'CIE-11'),
('XM1ZF1', 'Buspirona', 'category', false, false, 'CIE-11'),
('XM01J5', 'Mefenoxalona', 'category', false, false, 'CIE-11'),
('XM9TL2', 'Propiomazina', 'category', false, false, 'CIE-11'),
('XM15N4', 'Oxibato de sodio', 'category', false, false, 'CIE-11'),
('XM3EH5', 'Benzoctamina', 'category', false, false, 'CIE-11'),
('XM9727', 'Gedocarnil', 'category', false, false, 'CIE-11'),
('XM5928', 'Fabomotizol', 'category', false, false, 'CIE-11'),
('XM4DF5', 'Lavandulae aetheroleum', 'category', false, false, 'CIE-11'),
('XM8488', 'Valerianae radix', 'category', false, false, 'CIE-11'),
('XM2HN6', 'Suvorexant', 'category', false, false, 'CIE-11'),
('XM2AY7', 'Dipiperonil aminoetanol', 'category', false, false, 'CIE-11'),
('XM9235', 'Lemborexant', 'category', false, false, 'CIE-11'),
('XM1VL2', 'Hexetal (sódico)', 'category', false, false, 'CIE-11'),
('XM7MG1', 'Mefebarbital', 'category', false, false, 'CIE-11'),
('XM0217', 'Metitural', 'category', false, false, 'CIE-11'),
('XM2XY6', 'Acido 4- aminobutírico', 'category', false, false, 'CIE-11'),
('XM3XY4', 'Disuasivo del alcohol', 'category', false, false, 'CIE-11'),
('XM2XV6', 'Antabus', 'category', false, false, 'CIE-11'),
('XM1S43', 'Antídoto', 'category', false, false, 'CIE-11'),
('XM65Y8', 'Agente quelante', 'category', false, false, 'CIE-11'),
('XM68U2', 'Reactivador de la colinesterasa', 'category', false, false, 'CIE-11'),
('XM81B1', 'Cisteamina', 'category', false, false, 'CIE-11'),
('XM9M46', 'Agente desintoxicante', 'category', false, false, 'CIE-11'),
('XM0ZM0', 'Edetato de disodio', 'category', false, false, 'CIE-11'),
('XM1V56', 'EDTA', 'category', false, false, 'CIE-11'),
('XM0FL5', 'Ácido fítico, nonasodio', 'category', false, false, 'CIE-11'),
('XM7SW5', 'Glutation', 'category', false, false, 'CIE-11'),
('XM1YY3', 'Cloruro de metiltioninio', 'category', false, false, 'CIE-11'),
('XM7Z31', 'Nitrefazol', 'category', false, false, 'CIE-11'),
('XM7HV6', 'Cloruro de obidoxima', 'category', false, false, 'CIE-11'),
('XM2ZD4', 'Pralidoxima', 'category', false, false, 'CIE-11'),
('XM6TE9', 'Hexacianoferrato férrico del potasio (medicinal)', 'category', false, false, 'CIE-11'),
('XM7K47', 'Yoduro de pralidoxima', 'category', false, false, 'CIE-11'),
('XM6BZ5', 'Cloruro de pralidoxima', 'category', false, false, 'CIE-11'),
('XM8P25', 'Azul de Prusia terapeútico', 'category', false, false, 'CIE-11'),
('XM6DU2', 'Piridina aldoxima metiodida', 'category', false, false, 'CIE-11'),
('XM6043', 'Cloruro de metilo piridina aldoxima', 'category', false, false, 'CIE-11'),
('XM3810', 'Nitrito de sodio', 'category', false, false, 'CIE-11'),
('XM7LV6', 'Fitato de sodio', 'category', false, false, 'CIE-11'),
('XM6NW5', 'Tiosulfato', 'category', false, false, 'CIE-11'),
('XM2KC9', 'Versenato de sodio', 'category', false, false, 'CIE-11'),
('XM99S5', 'Disulfuro de tetraetiltiuram', 'category', false, false, 'CIE-11'),
('XM6GP9', 'Trientina', 'category', false, false, 'CIE-11'),
('XM2U68', 'Edetato de hidrógeno trisódico', 'category', false, false, 'CIE-11'),
('XM7KV3', 'Versenato', 'category', false, false, 'CIE-11'),
('XM4UW9', 'Nalorfina', 'category', false, false, 'CIE-11'),
('XM89R9', 'Dimercaprol', 'category', false, false, 'CIE-11'),
('XM1260', 'Yoduro de potasio', 'category', false, false, 'CIE-11'),
('XM7372', 'Acetilcisteína', 'category', false, false, 'CIE-11'),
('XM5MC0', 'Metionina', 'category', false, false, 'CIE-11'),
('XM28B1', 'Triacetato de uridina', 'category', false, false, 'CIE-11'),
('XM0588', 'Edetato', 'category', false, false, 'CIE-11'),
('XM5VJ5', 'Prednisolona y prometazina', 'category', false, false, 'CIE-11'),
('XM8ET8', 'Obidoxima', 'category', false, false, 'CIE-11'),
('XM2GR4', 'Protamina', 'category', false, false, 'CIE-11'),
('XM4JM7', 'Sulfato de cobre', 'category', false, false, 'CIE-11'),
('XM9AD6', 'Antitoxina digital', 'category', false, false, 'CIE-11'),
('XM2UQ5', 'Flumazenil', 'category', false, false, 'CIE-11'),
('XM2H17', '4-dimetilaminofenol', 'category', false, false, 'CIE-11'),
('XM8ZA0', 'Colinesterasa', 'category', false, false, 'CIE-11'),
('XM62Q3', 'Azul de Prusia', 'category', false, false, 'CIE-11'),
('XM7LQ9', 'Fomepizol', 'category', false, false, 'CIE-11'),
('XM9NQ8', 'Sugammadex', 'category', false, false, 'CIE-11'),
('XM0666', 'Idarucizumab', 'category', false, false, 'CIE-11'),
('XM01C9', 'Andexanet alfa', 'category', false, false, 'CIE-11'),
('XM5A41', 'Deferoxamina', 'category', false, false, 'CIE-11'),
('XM03A5', 'Deferiprona', 'category', false, false, 'CIE-11'),
('XM12X8', 'Deferasirox', 'category', false, false, 'CIE-11'),
('XM3B07', 'Sulfonato de poliestireno', 'category', false, false, 'CIE-11'),
('XM8NS1', 'Citrato férrico', 'category', false, false, 'CIE-11'),
('XM1AY3', 'Fosfato de sodio celulosa', 'category', false, false, 'CIE-11'),
('XM6Q80', 'Sevelamero', 'category', false, false, 'CIE-11'),
('XM22K8', 'Carbonato de lantano', 'category', false, false, 'CIE-11'),
('XM4MP9', 'Acetato de calcio y carbonato de magnesio', 'category', false, false, 'CIE-11'),
('XM9188', 'Oxihidróxido sucroférrico', 'category', false, false, 'CIE-11'),
('XM4C26', 'Colestilano', 'category', false, false, 'CIE-11'),
('XM1JB5', 'Mesna', 'category', false, false, 'CIE-11'),
('XM7BJ9', 'Folinato calcico', 'category', false, false, 'CIE-11'),
('XM45R5', 'Dexrazoxano', 'category', false, false, 'CIE-11'),
('XM2852', 'Levofolinato de calcio', 'category', false, false, 'CIE-11'),
('XM5GF2', 'Amifostina', 'category', false, false, 'CIE-11'),
('XM61A6', 'Folinato de sodio', 'category', false, false, 'CIE-11'),
('XM4NB1', 'Rasburicasa', 'category', false, false, 'CIE-11'),
('XM8J47', 'Palifermina', 'category', false, false, 'CIE-11'),
('XM8L87', 'Glucarpidasa', 'category', false, false, 'CIE-11'),
('XM1EU2', 'Levofolinato de sodio', 'category', false, false, 'CIE-11'),
('XM0MC0', 'Arginina y Lisina', 'category', false, false, 'CIE-11'),
('XM7PK0', 'Trilaciclib', 'category', false, false, 'CIE-11'),
('XM0LA6', 'Afamelanotida', 'category', false, false, 'CIE-11'),
('XM8337', 'Cantaxantina', 'category', false, false, 'CIE-11'),
('XM3GF4', 'Retinoides', 'category', false, false, 'CIE-11'),
('XM0Z07', 'Etretinato', 'category', false, false, 'CIE-11'),
('XM2M63', 'Acitretina', 'category', false, false, 'CIE-11'),
('XM4RP3', 'Trioxisaleno', 'category', false, false, 'CIE-11'),
('XM47G3', 'Metoxsaleno', 'category', false, false, 'CIE-11'),
('XM1G69', 'Bergapteno', 'category', false, false, 'CIE-11'),
('XM7WA3', 'Ácido fumárico', 'category', false, false, 'CIE-11'),
('XM98J9', 'Isotretinoína', 'category', false, false, 'CIE-11'),
('XM9FP6', 'Ichtasol', 'category', false, false, 'CIE-11'),
('XM4CF3', 'Coccidioidina', 'category', false, false, 'CIE-11'),
('XM1V31', 'Rojo Congo', 'category', false, false, 'CIE-11'),
('XM34X2', 'Azul de evans', 'category', false, false, 'CIE-11'),
('XM5618', 'Fluoresceína', 'category', false, false, 'CIE-11'),
('XM3Y60', 'Histoplasmina', 'category', false, false, 'CIE-11'),
('XM2818', 'Verde de indocianina', 'category', false, false, 'CIE-11'),
('XM3WZ1', 'Antígeno de linfogranuloma venéreo', 'category', false, false, 'CIE-11'),
('XM1VN8', 'Antígeno de prueba de la piel para Paperas', 'category', false, false, 'CIE-11'),
('XM3Q40', 'Peniciloil polilisina', 'category', false, false, 'CIE-11'),
('XM36R6', 'Metrizoato de sodio', 'category', false, false, 'CIE-11'),
('XM1QL6', 'Sulfonftaleína, sulfonftol', 'category', false, false, 'CIE-11'),
('XM8478', 'Reactivo de Sulkowitch', 'category', false, false, 'CIE-11'),
('XM4DA3', 'Toxina, difteria (Test de Schick )', 'category', false, false, 'CIE-11'),
('XM0EK6', 'Tuberculina, derivado proteico purificado (PPD)', 'category', false, false, 'CIE-11'),
('XM6XX8', 'Glucosa', 'category', false, false, 'CIE-11'),
('XM53M3', 'Sincalida', 'category', false, false, 'CIE-11'),
('XM0D92', 'Ceruletida', 'category', false, false, 'CIE-11'),
('XM5GR6', 'Metirapona', 'category', false, false, 'CIE-11'),
('XM7E13', 'Somatorelina', 'category', false, false, 'CIE-11'),
('XM1UJ0', 'Corticorelina', 'category', false, false, 'CIE-11'),
('XM5AM6', 'Macimorelina', 'category', false, false, 'CIE-11'),
('XM60V4', 'Pruebas de capacidad funcional hepática', 'category', false, false, 'CIE-11'),
('XM9ZW8', 'Galactosa', 'category', false, false, 'CIE-11'),
('XM1XE0', 'Sulfobromoftaleína', 'category', false, false, 'CIE-11'),
('XM0N95', 'Metacetina (13C)', 'category', false, false, 'CIE-11'),
('XM90L9', 'Iprofenina', 'category', false, false, 'CIE-11'),
('XM3114', 'Lidofenina', 'category', false, false, 'CIE-11'),
('XM2PX0', 'Rosa de bengala de sodio (I131)', 'category', false, false, 'CIE-11'),
('XM9H30', 'Pruebas de secreción gástrica', 'category', false, false, 'CIE-11'),
('XM44K8', 'Resina de intercambio catiónico', 'category', false, false, 'CIE-11'),
('XM1MP2', 'Betazol', 'category', false, false, 'CIE-11'),
('XM1286', 'Fosfato de histamina', 'category', false, false, 'CIE-11'),
('XM9AU1', 'Pentagastrina', 'category', false, false, 'CIE-11'),
('XM1Q27', 'Cafeína y benzoato de sodio', 'category', false, false, 'CIE-11'),
('XM1F97', 'Azuresina', 'category', false, false, 'CIE-11'),
('XM4E68', 'Pruebas de función renal y lesiones ureterales.', 'category', false, false, 'CIE-11'),
('XM9RK1', 'Índigo carmín', 'category', false, false, 'CIE-11'),
('XM3G67', 'Alisactida', 'category', false, false, 'CIE-11'),
('XM27H8', 'Ácido aminohipúrico', 'category', false, false, 'CIE-11'),
('XM87Y9', 'Para-aminohipurato de sodio', 'category', false, false, 'CIE-11'),
('XM2JZ2', 'Inulina y otros polifructosanos', 'category', false, false, 'CIE-11'),
('XM7M20', 'Fenolsulfonftaleína', 'category', false, false, 'CIE-11'),
('XM0N07', 'Pruebas para función tiroidea', 'category', false, false, 'CIE-11'),
('XM7R30', 'Protirelina', 'category', false, false, 'CIE-11'),
('XM76Z9', 'Pruebas de función pancreática', 'category', false, false, 'CIE-11'),
('XM3L99', 'Secretina', 'category', false, false, 'CIE-11'),
('XM7A79', 'Bentiromida', 'category', false, false, 'CIE-11'),
('XM6014', 'Pancreozimina-colecistoquinina', 'category', false, false, 'CIE-11'),
('XM24K5', 'Selenometionina (Se 75)', 'category', false, false, 'CIE-11'),
('XM8B05', 'Edrofonio', 'category', false, false, 'CIE-11'),
('XM3YJ9', 'Metacolina', 'category', false, false, 'CIE-11'),
('XM5K20', 'Fructosa', 'category', false, false, 'CIE-11'),
('XM9258', 'Concentrados de vitamina A', 'category', false, false, 'CIE-11'),
('XM7PF6', 'Tuberculina', 'category', false, false, 'CIE-11'),
('XM9QZ5', '13C-urea', 'category', false, false, 'CIE-11'),
('XM0UW4', 'Hexaminolevulinato', 'category', false, false, 'CIE-11'),
('XM02S2', 'Azul patente', 'category', false, false, 'CIE-11'),
('XM9Y95', 'Reactivo azul de bromofenol', 'category', false, false, 'CIE-11'),
('XM5PT0', 'Diacetil monoxima', 'category', false, false, 'CIE-11'),
('XM8M78', 'Reactivo de guayaco', 'category', false, false, 'CIE-11'),
('XM3385', 'Sal de amonio de ácido oxálico', 'category', false, false, 'CIE-11'),
('XM74W0', 'Reactivo de fenaftazina', 'category', false, false, 'CIE-11'),
('XM4SZ3', 'Oxígeno', 'category', false, false, 'CIE-11'),
('XM6NZ1', 'Dióxido de carbono medicinal', 'category', false, false, 'CIE-11'),
('XM3K31', 'Nitrógeno', 'category', false, false, 'CIE-11'),
('XM7EZ9', 'Aire medicinal', 'category', false, false, 'CIE-11'),
('XM2S71', 'Medio de contraste para rayos X, yodado', 'category', false, false, 'CIE-11'),
('XM7YS2', 'Medios de contraste de rayos X de alta osmolaridad, nefrotrópicos y solubles en agua', 'category', false, false, 'CIE-11'),
('XM7PH4', 'Ácido metrizoico', 'category', false, false, 'CIE-11'),
('XM6583', 'Iodamida', 'category', false, false, 'CIE-11'),
('XM8XV8', 'Ácido iotalámico', 'category', false, false, 'CIE-11'),
('XM34M9', 'Ácido ioxitalamico', 'category', false, false, 'CIE-11'),
('XM50Y6', 'Ácido acetrizoico', 'category', false, false, 'CIE-11'),
('XM7ZV2', 'Ácido iocármico', 'category', false, false, 'CIE-11'),
('XM2DC4', 'Diodone', 'category', false, false, 'CIE-11'),
('XM8KK9', 'Ácido diatrizoico', 'category', false, false, 'CIE-11'),
('XM50U3', 'Ácido Ioglícico', 'category', false, false, 'CIE-11'),
('XM9C52', 'Metiodal', 'category', false, false, 'CIE-11'),
('XM4AG5', 'Medios de contraste de rayos X de baja osmolaridad, nefrotrópicos y solubles en agua', 'category', false, false, 'CIE-11'),
('XM3WB6', 'Metrizamida', 'category', false, false, 'CIE-11'),
('XM3R65', 'Iohexol', 'category', false, false, 'CIE-11'),
('XM5EP5', 'Ácido Ioxáglico', 'category', false, false, 'CIE-11'),
('XM8C50', 'Iopamidol', 'category', false, false, 'CIE-11'),
('XM4UK7', 'Iopromida', 'category', false, false, 'CIE-11'),
('XM8VT7', 'Iotrolan', 'category', false, false, 'CIE-11'),
('XM5LW4', 'Ácido iotróxico', 'category', false, false, 'CIE-11'),
('XM6227', 'Iopentol', 'category', false, false, 'CIE-11'),
('XM8NA7', 'Iodixanol', 'category', false, false, 'CIE-11'),
('XM75B4', 'Iomeprol', 'category', false, false, 'CIE-11'),
('XM79B6', 'Iobitridol', 'category', false, false, 'CIE-11'),
('XM6VV1', 'Ioxilan', 'category', false, false, 'CIE-11'),
('XM0KA6', 'Medios de contraste de rayos X hepatotrópicos, solubles en agua', 'category', false, false, 'CIE-11'),
('XM2VE6', 'Ácido iodoxámico', 'category', false, false, 'CIE-11'),
('XM8411', 'Ácido ioglicámico', 'category', false, false, 'CIE-11'),
('XM7QU5', 'Adipiodona', 'category', false, false, 'CIE-11'),
('XM1QH8', 'Ácido iobenzámico', 'category', false, false, 'CIE-11'),
('XM2NU7', 'Ácido iopanoico', 'category', false, false, 'CIE-11'),
('XM8PW2', 'Ácido iocetámico', 'category', false, false, 'CIE-11'),
('XM4ZU7', 'Iopodato de sodio', 'category', false, false, 'CIE-11'),
('XM8WD0', 'Ácido tiropanoico', 'category', false, false, 'CIE-11'),
('XM6TF5', 'Iopodato de calcio', 'category', false, false, 'CIE-11'),
('XM0LK3', 'Medios de contraste de rayos X no solubles en agua', 'category', false, false, 'CIE-11'),
('XM1AX3', 'Iopidol', 'category', false, false, 'CIE-11'),
('XM1YV8', 'Propliodona', 'category', false, false, 'CIE-11'),
('XM1R87', 'Iofendilato', 'category', false, false, 'CIE-11'),
('XM6SE3', 'Ésteres etílicos de ácidos grasos yodados', 'category', false, false, 'CIE-11'),
('XM6XU2', 'Diatrizoato', 'category', false, false, 'CIE-11'),
('XM8QZ2', 'Yodoftaleína sódica', 'category', false, false, 'CIE-11'),
('XM0L44', 'Amidotrizoato', 'category', false, false, 'CIE-11'),
('XM80W7', 'Bunamiodilo', 'category', false, false, 'CIE-11'),
('XM5NA9', 'Iodipamida', 'category', false, false, 'CIE-11'),
('XM4E01', 'Ácido o-iodohipúrico', 'category', false, false, 'CIE-11'),
('XM9402', 'Ácido iofenoico', 'category', false, false, 'CIE-11'),
('XM7S30', 'Ácido iopódico', 'category', false, false, 'CIE-11'),
('XM4R74', 'Iotroxato', 'category', false, false, 'CIE-11'),
('XM44B9', 'Ioxaglato', 'category', false, false, 'CIE-11'),
('XM5N73', 'Metiodal sódico', 'category', false, false, 'CIE-11'),
('XM96Q8', 'Fenobutiodil', 'category', false, false, 'CIE-11'),
('XM3E15', 'Suspensión de dióxido de torio', 'category', false, false, 'CIE-11'),
('XM90A9', 'Tiropanoato', 'category', false, false, 'CIE-11'),
('XM2MR0', 'Sulfato de bario con agentes de suspensión', 'category', false, false, 'CIE-11'),
('XM1FW7', 'Sulfato de bario sin agentes de suspensión', 'category', false, false, 'CIE-11'),
('XM05Z9', 'Medios de contraste para resonancia magnética', 'category', false, false, 'CIE-11'),
('XM2LS2', 'Medios de contraste paramagnéticos', 'category', false, false, 'CIE-11'),
('XM7CY5', 'Ácido gadopentético', 'category', false, false, 'CIE-11'),
('XM4UX1', 'Ácido gadotérico', 'category', false, false, 'CIE-11'),
('XM1564', 'Gadodiamida', 'category', false, false, 'CIE-11'),
('XM0FN2', 'Gadoteridol', 'category', false, false, 'CIE-11'),
('XM73Z5', 'Mangafodipir', 'category', false, false, 'CIE-11'),
('XM3BF7', 'Gadoversetamida', 'category', false, false, 'CIE-11'),
('XM29E1', 'Citrato de amonio férrico', 'category', false, false, 'CIE-11'),
('XM0XE4', 'Ácido gadobénico', 'category', false, false, 'CIE-11'),
('XM3VG2', 'Gadobutrol', 'category', false, false, 'CIE-11'),
('XM7W85', 'Ácido gadoxético', 'category', false, false, 'CIE-11'),
('XM6GF6', 'Gadofosveset', 'category', false, false, 'CIE-11'),
('XM8966', 'Medios de contraste superparamagnéticos', 'category', false, false, 'CIE-11'),
('XM33C2', 'ferumoxsil', 'category', false, false, 'CIE-11'),
('XM84N5', 'ferristene', 'category', false, false, 'CIE-11'),
('XM2945', 'Óxido de hierro, nanopartículas', 'category', false, false, 'CIE-11'),
('XM2666', 'Perflubron', 'category', false, false, 'CIE-11'),
('XM5TN4', 'Medios de contraste para ultrasonidos', 'category', false, false, 'CIE-11'),
('XM40N1', 'Microesferas de albúmina humana', 'category', false, false, 'CIE-11'),
('XM3PF3', 'Micropartículas de galactosa', 'category', false, false, 'CIE-11'),
('XM7S16', 'Perflenapent', 'category', false, false, 'CIE-11'),
('XM4VR4', 'Microesferas de fosfolípidos', 'category', false, false, 'CIE-11'),
('XM8169', 'Hexafloruro de azufre', 'category', false, false, 'CIE-11'),
('XM8G80', 'Microesferas de polímero de perflubutano', 'category', false, false, 'CIE-11'),
('XM9320', 'Radiofármacos de diagnóstico', 'category', false, false, 'CIE-11'),
('XM8ZM1', 'Compuestos de tecnecio (99mTc)', 'category', false, false, 'CIE-11'),
('XM5VK7', 'Pertecnetato de sodio Tc 99m', 'category', false, false, 'CIE-11'),
('XM9YB1', 'Compuestos de yodo (123I)', 'category', false, false, 'CIE-11'),
('XM2R88', 'Yoduro de sodio (131i)', 'category', false, false, 'CIE-11'),
('XM6941', 'Cloruro de rubidio Rb 82', 'category', false, false, 'CIE-11'),
('XM3GL6', 'Citrato de Galio', 'category', false, false, 'CIE-11'),
('XM8SB4', 'Citrato de galio (67Ga)', 'category', false, false, 'CIE-11'),
('XM3WK3', 'Fludeoxiglucosa (F18)', 'category', false, false, 'CIE-11'),
('XM4ML0', 'Iodocolesterol (I131)', 'category', false, false, 'CIE-11'),
('XM6Z69', 'Gas Xenon (127Xe)', 'category', false, false, 'CIE-11'),
('XM6EQ3', 'Xenon (133Xe)', 'category', false, false, 'CIE-11'),
('XM39A6', 'Yoduro de sodio (124I)', 'category', false, false, 'CIE-11'),
('XM9F18', 'Anticuerpos maternos', 'category', false, false, 'CIE-11'),
('XM3HU5', 'Citrato férrico (59Fe)', 'category', false, false, 'CIE-11'),
('XM1899', 'Yoduro de sodio (123I)', 'category', false, false, 'CIE-11'),
('XM9063', 'Yodohipurato de sodio (123I)', 'category', false, false, 'CIE-11'),
('XM60X3', 'Iobenguano (131I)', 'category', false, false, 'CIE-11'),
('XM1QL4', 'Iobenguano (123I)', 'category', false, false, 'CIE-11'),
('XM6UT0', 'Fluoroetil-L-tirosina (18F)', 'category', false, false, 'CIE-11'),
('XM80F7', 'Fluoroestradiol (18F)', 'category', false, false, 'CIE-11'),
('XM5G08', 'Fluciclovina (18F)', 'category', false, false, 'CIE-11'),
('XM3LK2', 'Fluorodopa (18F)', 'category', false, false, 'CIE-11'),
('XM1N90', 'Fluorometilcolina (18F)', 'category', false, false, 'CIE-11'),
('XM5XR7', 'Fluoroetilcolina (18F)', 'category', false, false, 'CIE-11'),
('XM5EC5', 'Galio (68Ga) edotreótida', 'category', false, false, 'CIE-11'),
('XM7VT3', 'Cobalto (57 Co) cianocobalamina', 'category', false, false, 'CIE-11'),
('XM8YZ3', 'Cobalto (58 Co) cianocobalamina', 'category', false, false, 'CIE-11'),
('XM5FA9', 'Ácido tauroselcólico', 'category', false, false, 'CIE-11'),
('XM42A5', 'Selenio (75Se) norcolesterol', 'category', false, false, 'CIE-11'),
('XM2MJ2', 'Albúmina humana sérica yodada Yodo (131i)', 'category', false, false, 'CIE-11'),
('XM2YP2', 'Yodo 125', 'category', false, false, 'CIE-11'),
('XM8YZ7', 'Yodo 131', 'category', false, false, 'CIE-11'),
('XM0RB0', 'Yodohipurato de sodio (I131)', 'category', false, false, 'CIE-11'),
('XM15W7', 'Iotalamato de sodio (I125)', 'category', false, false, 'CIE-11'),
('XM5674', 'Amonio (13N)', 'category', false, false, 'CIE-11'),
('XM05N6', 'Gozetotida de galio (68Ga)', 'category', false, false, 'CIE-11'),
('XM45C8', 'Radiofármacos terapéuticos', 'category', false, false, 'CIE-11'),
('XM6RC9', 'Yoduro de sodio I-131 terapéutico', 'category', false, false, 'CIE-11'),
('XM01S1', 'Isoaminilo (citrato)', 'category', false, false, 'CIE-11'),
('XM9XW5', 'Sulfuro antimónico', 'category', false, false, 'CIE-11'),
('XM8Z31', 'Coloide de ferrihidróxido de itrio (90Y)', 'category', false, false, 'CIE-11'),
('XM0JJ4', 'Coloide de hidroxiapatita de samario (153Sm)', 'category', false, false, 'CIE-11'),
('XM56F9', 'Disprosio coloidal (165Dy)', 'category', false, false, 'CIE-11'),
('XM10B1', 'Coloide de citrato de itrio (90Y)', 'category', false, false, 'CIE-11'),
('XM3MD6', 'Coloide de citrato de erbio (169Er)', 'category', false, false, 'CIE-11'),
('XM5ZE8', 'Dicloruro de amileno', 'category', false, false, 'CIE-11'),
('XM1WG6', 'Aceite etiodizado (i131)', 'category', false, false, 'CIE-11'),
('XM7MV3', 'Yodo (131I) omburtamab', 'category', false, false, 'CIE-11'),
('XM32B6', 'b-eucaina', 'category', false, false, 'CIE-11'),
('XM79Q0', 'Lactato de benzamina', 'category', false, false, 'CIE-11'),
('XM8MM9', 'Alquitrán de hulla', 'category', false, false, 'CIE-11'),
('XM96H7', 'Destilado de alquitrán soluble en éter', 'category', false, false, 'CIE-11'),
('XM6PP6', 'Alquitrán de enebro', 'category', false, false, 'CIE-11'),
('XM8YS8', 'Fenol medicinal', 'category', false, false, 'CIE-11'),
('XM96T6', 'Preparación fenólica', 'category', false, false, 'CIE-11'),
('XM8485', 'Pramoxina', 'category', false, false, 'CIE-11'),
('XM6A20', 'Quinisocaina', 'category', false, false, 'CIE-11'),
('XM8W74', 'Destilado de alquitrán', 'category', false, false, 'CIE-11'),
('XM8WM2', 'Pomada de alquitrán', 'category', false, false, 'CIE-11'),
('XM4543', 'Tolpropamina', 'category', false, false, 'CIE-11'),
('XM2833', 'Mepiramina tópica', 'category', false, false, 'CIE-11'),
('XM29P8', 'Metilbromuro de difenhidramina', 'category', false, false, 'CIE-11'),
('XM9UN5', 'Thonzylamine tópico', 'category', false, false, 'CIE-11'),
('XM7JY5', 'Thenalidine tópico', 'category', false, false, 'CIE-11'),
('XM6WM2', 'Prometazina tópica', 'category', false, false, 'CIE-11'),
('XM4B01', 'Ácido acético con acetato de sodio (ungüento)', 'category', false, false, 'CIE-11'),
('XM7MV6', 'Resina acrílica', 'category', false, false, 'CIE-11'),
('XM8U60', 'Aliltiourea', 'category', false, false, 'CIE-11'),
('XM06X6', 'Aluminio, ungüento de aluminio (quirúrgico) (tópico)', 'category', false, false, 'CIE-11'),
('XM1S82', 'Ácido aminobenzoico (-p)', 'category', false, false, 'CIE-11'),
('XM3VB3', 'Aceite de arachis', 'category', false, false, 'CIE-11'),
('XM8SU9', 'Crema protectora', 'category', false, false, 'CIE-11'),
('XM5L08', 'Bentonita', 'category', false, false, 'CIE-11'),
('XM7D95', 'Benzofenonas', 'category', false, false, 'CIE-11'),
('XM6F99', 'Benzofenona-3', 'category', false, false, 'CIE-11'),
('XM4DT5', 'Benzofenona-4', 'category', false, false, 'CIE-11'),
('XM08U7', 'Aceite Betula', 'category', false, false, 'CIE-11'),
('XM7K00', 'Calamina (loción)', 'category', false, false, 'CIE-11'),
('XM2EP3', 'Nitratos de celulosa (tópico)', 'category', false, false, 'CIE-11'),
('XM9ZA9', 'Clorodietil benzamida', 'category', false, false, 'CIE-11'),
('XM88R8', 'Cold cream', 'category', false, false, 'CIE-11'),
('XM7033', 'Maicena', 'category', false, false, 'CIE-11'),
('XM38M3', 'Loción de corn husker', 'category', false, false, 'CIE-11'),
('XM8P34', 'Aceite de algodón', 'category', false, false, 'CIE-11'),
('XM5PK1', 'Demulcente (externo)', 'category', false, false, 'CIE-11'),
('XM0XB3', 'Dietil toluamida medicinal', 'category', false, false, 'CIE-11'),
('XM9U76', 'Ftalato de dimetilo', 'category', false, false, 'CIE-11'),
('XM8KY4', 'Linaza (medicinal)', 'category', false, false, 'CIE-11'),
('XM6694', 'Homosalato', 'category', false, false, 'CIE-11'),
('XM8M74', 'Loción hidrofílica', 'category', false, false, 'CIE-11'),
('XM8WH4', 'Lanolina', 'category', false, false, 'CIE-11'),
('XM4HE0', 'Alcohol de lanolina', 'category', false, false, 'CIE-11'),
('XM7TK2', 'Mecrilato', 'category', false, false, 'CIE-11'),
('XM7VP7', 'Agentes melanizantes', 'category', false, false, 'CIE-11'),
('XM8EY7', 'Mexenona', 'category', false, false, 'CIE-11'),
('XM9TZ7', 'Aceite mineral tópico', 'category', false, false, 'CIE-11'),
('XM3214', 'Cloruro de octafonio', 'category', false, false, 'CIE-11'),
('XM66S8', 'Aceite de gaulteria (amargo)', 'category', false, false, 'CIE-11'),
('XM9CQ4', 'Metoxsalen tópico', 'category', false, false, 'CIE-11'),
('XM0VT0', 'Padimato', 'category', false, false, 'CIE-11'),
('XM9AG3', 'Ácido para- amino benzoico', 'category', false, false, 'CIE-11'),
('XM1U48', 'Tópico de aceite de maní', 'category', false, false, 'CIE-11'),
('XM8PB6', 'Petrolato', 'category', false, false, 'CIE-11'),
('XM8J96', 'Vendaje de yeso', 'category', false, false, 'CIE-11'),
('XM9V04', 'Vendaje plástico', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
