-- CIE11 Import Part 10
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('8A42.Z', 'Otra encefalomielitis diseminada aguda, sin especificación', 'category', false, false, 'CIE-11'),
('8A43', 'Neuromielitis óptica', 'category', false, false, 'CIE-11'),
('8A43.0', 'Neuromielitis óptica positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.1', 'Neuromielitis óptica negativa a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.2', 'Mielitis transversa única positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.3', 'Mielitis transversa recurrente positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.4', 'Neuritis óptica única positiva para anticuerpos contra acuaporina-4', 'category', false, false, 'CIE-11'),
('8A43.5', 'Neuritis óptica recurrente positiva para anticuerpos contra acuaporina-4', 'category', false, false, 'CIE-11'),
('8A43.Y', 'Otra neuromielitis óptica especificada', 'category', false, false, 'CIE-11'),
('8A43.Z', 'Neuromielitis óptica, sin especificación', 'category', false, false, 'CIE-11'),
('8A44', 'Leucodistrofias', 'category', false, false, 'CIE-11'),
('8A44.0', 'Enfermedad de Pelizaeus-Merzbacher', 'category', false, false, 'CIE-11'),
('8A44.1', 'Adrenoleucodistrofia', 'category', false, false, 'CIE-11'),
('8A44.2', 'Enfermedad de Alexander', 'category', false, false, 'CIE-11'),
('8A44.3', 'Algunas leucodistrofias especificadas', 'category', false, false, 'CIE-11'),
('8A44.4', 'Enfermedad de Krabbe', 'category', false, false, 'CIE-11'),
('8A44.Z', 'Leucodistrofias, sin especificación', 'category', false, false, 'CIE-11'),
('8A45', 'Trastornos secundarios de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A45.0', 'Trastornos de la sustancia blanca debidos a infecciones', 'category', false, false, 'CIE-11'),
('8A45.00', 'Mielopatía debida al virus linfotrópico de linfocitos T humanos', 'category', false, false, 'CIE-11'),
('8A45.01', 'Panencefalitis esclerosante subaguda', 'category', false, false, 'CIE-11'),
('8A45.02', 'Leucoencefalopatía progresiva multifocal', 'category', false, false, 'CIE-11'),
('8A45.0Y', 'Otros trastornos de la sustancia blanca especificados debidos a infecciones', 'category', false, false, 'CIE-11'),
('8A45.0Z', 'Trastornos de la sustancia blanca debidos a infecciones, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.1', 'Trastornos de la sustancia blanca por toxicidad', 'category', false, false, 'CIE-11'),
('8A45.2', 'Trastornos de la sustancia blanca debidos a anomalías vasculares o isquemia', 'category', false, false, 'CIE-11'),
('8A45.20', 'Trastorno de la sustancia blanca debido a arteriopatía cerebral autosómica dominante con infartos subcorticales y leucoencefalopatía', 'category', false, false, 'CIE-11'),
('8A45.21', 'Mielitis necrosante subaguda', 'category', false, false, 'CIE-11'),
('8A45.2Y', 'Otros trastornos de la sustancia blanca especificados debidos a anomalías vasculares o isquemia', 'category', false, false, 'CIE-11'),
('8A45.2Z', 'Trastornos de la sustancia blanca debidos a anomalías vasculares o isquemia, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.3', 'Trastornos de la sustancia blanca por deficiencia nutricional', 'category', false, false, 'CIE-11'),
('8A45.30', 'Trastorno de la sustancia blanca por deficiencia de vitamina B12', 'category', false, false, 'CIE-11'),
('8A45.31', 'Mielinólisis central pontina', 'category', false, false, 'CIE-11'),
('8A45.3Y', 'Otros trastornos de la sustancia blanca especificados por deficiencia nutricional', 'category', false, false, 'CIE-11'),
('8A45.3Z', 'Trastornos de la sustancia blanca por deficiencia nutricional, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.4', 'Trastornos de la sustancia blanca debidos a una enfermedad sistémica especificada', 'category', false, false, 'CIE-11'),
('8A45.40', 'Desmielinización por sarcoidosis', 'category', false, false, 'CIE-11'),
('8A45.41', 'Desmielinización por lupus eritematoso sistémico', 'category', false, false, 'CIE-11'),
('8A45.42', 'Desmielinización debida a la enfermedad de Sjögren', 'category', false, false, 'CIE-11'),
('8A45.43', 'Desmielinización debida a la enfermedad de Behçet', 'category', false, false, 'CIE-11'),
('8A45.44', 'Desmielinización por vasculitis sistémica', 'category', false, false, 'CIE-11'),
('8A45.45', 'Desmielinización por enfermedad mitocondrial', 'category', false, false, 'CIE-11'),
('8A45.4Z', 'Trastornos de la sustancia blanca debidos a una enfermedad sistémica, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.Y', 'Otros trastornos secundarios especificados de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A45.Z', 'Trastornos secundarios de la sustancia blanca, sin especificación', 'category', false, false, 'CIE-11'),
('8A46', 'Desmielinización central del cuerpo calloso', 'category', false, false, 'CIE-11'),
('8A4Y', 'Otra esclerosis múltiple especificada u otros trastornos de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A4Z', 'Esclerosis múltiple u otros trastornos de la sustancia blanca, sin especificación', 'category', false, false, 'CIE-11'),
('8A60', 'Epilepsia debida a enfermedades o afecciones metabólicas o estructurales', 'category', false, false, 'CIE-11'),
('8A60.0', 'Epilepsia por daño cerebral prenatal o perinatal', 'category', false, false, 'CIE-11'),
('8A60.00', 'Epilepsia debida a las lesiones vasculares prenatales o perinatales', 'category', false, false, 'CIE-11'),
('8A60.01', 'Epilepsia por encefalopatía isquémica hipóxica neonatal', 'category', false, false, 'CIE-11'),
('8A60.0Y', 'Epilepsia por otros daños cerebrales prenatales o perinatales', 'category', false, false, 'CIE-11'),
('8A60.0Z', 'Epilepsia por daño cerebral prenatal o perinatal, sin especificación', 'category', false, false, 'CIE-11'),
('8A60.1', 'Epilepsia por trastornos cerebrovasculares', 'category', false, false, 'CIE-11'),
('8A60.2', 'Epilepsia por trastornos cerebrales degenerativos', 'category', false, false, 'CIE-11'),
('8A60.3', 'Epilepsia por demencia', 'category', false, false, 'CIE-11'),
('8A60.4', 'Epilepsia por infección o infestación del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A60.5', 'Epilepsia por traumatismo encefálico', 'category', false, false, 'CIE-11'),
('8A60.6', 'Epilepsia por tumor del sistema nervioso', 'category', false, false, 'CIE-11'),
('8A60.7', 'Epilepsia con esclerosis temporal mesial', 'category', false, false, 'CIE-11'),
('8A60.8', 'Epilepsia por trastornos inmunitarios', 'category', false, false, 'CIE-11'),
('8A60.9', 'Epilepsia por anomalías del desarrollo encefálico', 'category', false, false, 'CIE-11'),
('8A60.A', 'Epilepsia debida a síndromes genéticos con efectos generalizados o progresivos', 'category', false, false, 'CIE-11'),
('8A60.B', 'Epilepsia por esclerosis múltiple u otros trastornos desmielinizantes', 'category', false, false, 'CIE-11'),
('8A60.Y', 'Epilepsia debida a otra enfermedad o afección metabólica o estructural', 'category', false, false, 'CIE-11'),
('8A60.Z', 'Epilepsia debida a una enfermedad o afección metabólica o estructural, sin especificación', 'category', false, false, 'CIE-11'),
('8A61', 'Síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A61.0', 'Síndromes epilépticos genéticos de comienzo en el período neonatal', 'category', false, false, 'CIE-11'),
('8A61.00', 'Epilepsia dependiente del piridoxal', 'category', false, false, 'CIE-11'),
('8A61.0Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en el período neonatal', 'category', false, false, 'CIE-11'),
('8A61.0Z', 'Síndromes epilépticos genéticos especificados de comienzo en el período neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.1', 'Síndromes epilépticos genéticos de comienzo en la primera infancia', 'category', false, false, 'CIE-11'),
('8A61.10', 'Epilepsia primoinfantil familiar benigna', 'category', false, false, 'CIE-11'),
('8A61.11', 'Síndrome de Dravet', 'category', false, false, 'CIE-11'),
('8A61.12', 'Epilepsia de la primera infancia con convulsiones focales migratorias', 'category', false, false, 'CIE-11'),
('8A61.1Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en la primera infancia', 'category', false, false, 'CIE-11'),
('8A61.1Z', 'Síndromes epilépticos genéticos de comienzo en la primera infancia, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.2', 'Síndromes epilépticos genéticos de comienzo en la niñez', 'category', false, false, 'CIE-11'),
('8A61.20', 'Epilepsia benigna de la niñez con puntas centrotemporales', 'category', false, false, 'CIE-11'),
('8A61.21', 'Epilepsia del tipo ausencia de la niñez', 'category', false, false, 'CIE-11'),
('8A61.22', 'Epilepsia con convulsiones mioclónicas astáticas', 'category', false, false, 'CIE-11'),
('8A61.23', 'Ausencias mioclónicas o ausencias con mioclonías', 'category', false, false, 'CIE-11'),
('8A61.2Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en la niñez', 'category', false, false, 'CIE-11'),
('8A61.2Z', 'Síndromes epilépticos genéticos especificados de comienzo en la niñez, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.3', 'Síndrome epiléptico genético de comienzo en la adolescencia o en la edad adulta', 'category', false, false, 'CIE-11'),
('8A61.30', 'Epilepsia mioclónica juvenil', 'category', false, false, 'CIE-11'),
('8A61.31', 'Epilepsia familiar con ausencias', 'category', false, false, 'CIE-11'),
('8A61.32', 'Epilepsia mioclónica familiar benigna del adulto', 'category', false, false, 'CIE-11'),
('8A61.3Y', 'Otro síndrome epiléptico genético especificado de comienzo en la adolescencia o en la edad adulta', 'category', false, false, 'CIE-11'),
('8A61.3Z', 'Síndrome epiléptico genético de comienzo en el adolescente o el adulto, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.4', 'Síndromes epilépticos genéticos de comienzo a distintas edades', 'category', false, false, 'CIE-11'),
('8A61.40', 'Epilepsias reflejas', 'category', false, false, 'CIE-11'),
('8A61.41', 'Epilepsia mioclónica progresiva', 'category', false, false, 'CIE-11'),
('8A61.4Y', 'Otros síndromes epilépticos genéticos especificados de comienzo a distintas edades', 'category', false, false, 'CIE-11'),
('8A61.4Z', 'Síndromes epilépticos genéticos de comienzo a distintas edades, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.Y', 'Otros síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A61.Z', 'Síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A62', 'Encefalopatías epilépticas', 'category', false, false, 'CIE-11'),
('8A62.0', 'Espasmos infantiles', 'category', false, false, 'CIE-11'),
('8A62.1', 'Síndrome de Lennox-Gastaut', 'category', false, false, 'CIE-11'),
('8A62.2', 'Afasia epiléptica adquirida', 'category', false, false, 'CIE-11'),
('8A62.Y', 'Otras encefalopatías epilépticas especificadas', 'category', false, false, 'CIE-11'),
('8A62.Z', 'Encefalopatías epilépticas, sin especificación', 'category', false, false, 'CIE-11'),
('8A63', 'Convulsión de causa aguda', 'category', false, false, 'CIE-11'),
('8A63.0', 'Convulsiones febriles', 'category', false, false, 'CIE-11'),
('8A63.00', 'Convulsiones febriles simples', 'category', false, false, 'CIE-11'),
('8A63.01', 'Convulsiones febriles complejas', 'category', false, false, 'CIE-11'),
('8A63.0Y', 'Otras convulsiones febriles especificadas', 'category', false, false, 'CIE-11'),
('8A63.0Z', 'Convulsiones febriles, sin especificación', 'category', false, false, 'CIE-11'),
('8A63.Y', 'Otra convulsión especificada por causas agudas', 'category', false, false, 'CIE-11'),
('8A63.Z', 'Convulsión por causas agudas, sin especificación', 'category', false, false, 'CIE-11'),
('8A64', 'Convulsión aislada debida a una causa remota', 'category', false, false, 'CIE-11'),
('8A65', 'Convulsión única no provocada', 'category', false, false, 'CIE-11'),
('8A66', 'Estado epiléptico', 'category', false, false, 'CIE-11'),
('8A66.0', 'Estado epiléptico convulsivo', 'category', false, false, 'CIE-11'),
('8A66.1', 'Estado epiléptico no convulsivo', 'category', false, false, 'CIE-11'),
('8A66.10', 'Estado epiléptico de ausencia', 'category', false, false, 'CIE-11'),
('8A66.1Y', 'Otro estado epiléptico no convulsivo especificado', 'category', false, false, 'CIE-11'),
('8A66.1Z', 'Estado epiléptico no convulsivo, sin especificación', 'category', false, false, 'CIE-11'),
('8A66.Y', 'Otro estado epiléptico especificado', 'category', false, false, 'CIE-11'),
('8A66.Z', 'Estado epiléptico, sin especificación', 'category', false, false, 'CIE-11'),
('8A67', 'Convulsiones agudas repetitivas', 'category', false, false, 'CIE-11'),
('8A68', 'Tipos de convulsiones', 'category', false, false, 'CIE-11'),
('8A68.0', 'Convulsión inconsciente focal', 'category', false, false, 'CIE-11'),
('8A68.1', 'Ausencias, atípicas', 'category', false, false, 'CIE-11'),
('8A68.2', 'Ausencias, típicas', 'category', false, false, 'CIE-11'),
('8A68.3', 'Convulsión focal sin pérdida del conocimiento', 'category', false, false, 'CIE-11'),
('8A68.4', 'Convulsión tonicoclónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.5', 'Convulsión mioclónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.6', 'Convulsión tónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.7', 'Convulsión atónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.Y', 'Otro tipo especificado de convulsión', 'category', false, false, 'CIE-11'),
('8A68.Z', 'Tipo de convulsión, sin especificación', 'category', false, false, 'CIE-11'),
('8A6Y', 'Otra epilepsia o convulsiones especificadas', 'category', false, false, 'CIE-11'),
('8A6Z', 'Epilepsia o convulsiones, sin especificación', 'category', false, false, 'CIE-11'),
('8A80', 'Migraña', 'category', false, false, 'CIE-11'),
('8A80.0', 'Migraña sin aura', 'category', false, false, 'CIE-11'),
('8A80.1', 'Migraña con aura', 'category', false, false, 'CIE-11'),
('8A80.10', 'Migraña hemipléjica', 'category', false, false, 'CIE-11'),
('8A80.1Y', 'Otra migraña especificada con aura', 'category', false, false, 'CIE-11'),
('8A80.1Z', 'Migraña con aura, sin especificación', 'category', false, false, 'CIE-11'),
('8A80.2', 'Migraña crónica', 'category', false, false, 'CIE-11'),
('8A80.3', 'Complicaciones relacionadas con la migraña', 'category', false, false, 'CIE-11'),
('8A80.30', 'Estado migrañoso', 'category', false, false, 'CIE-11'),
('8A80.3Y', 'Otras complicaciones especificadas relacionadas con la migraña', 'category', false, false, 'CIE-11'),
('8A80.3Z', 'Complicaciones relacionadas con la migraña, sin especificación', 'category', false, false, 'CIE-11'),
('8A80.4', 'Síndrome de vómitos cíclicos', 'category', false, false, 'CIE-11'),
('8A80.Y', 'Otra migraña especificada', 'category', false, false, 'CIE-11'),
('8A80.Z', 'Migraña, sin especificación', 'category', false, false, 'CIE-11'),
('8A81', 'Cefalea tensional', 'category', false, false, 'CIE-11'),
('8A81.0', 'Cefalea tensional episódica infrecuente', 'category', false, false, 'CIE-11'),
('8A81.1', 'Cefalea tensional episódica frecuente', 'category', false, false, 'CIE-11'),
('8A81.2', 'Cefalea tensional crónica', 'category', false, false, 'CIE-11'),
('8A81.Y', 'Otra cefalea tensional especificada', 'category', false, false, 'CIE-11'),
('8A81.Z', 'Cefalea tensional, sin especificación', 'category', false, false, 'CIE-11'),
('8A82', 'Cefaleas autonómicas del trigémino', 'category', false, false, 'CIE-11'),
('8A83', 'Otro trastorno de cefalea primaria', 'category', false, false, 'CIE-11'),
('8A84', 'Cefalea secundaria', 'category', false, false, 'CIE-11'),
('8A84.0', 'Cefalea aguda asociada con un traumatismo cefálico', 'category', false, false, 'CIE-11'),
('8A84.1', 'Cefalea persistente asociada con un traumatismo cefálico', 'category', false, false, 'CIE-11'),
('8A84.Y', 'Otra cefalea secundaria especificada', 'category', false, false, 'CIE-11'),
('8A84.Z', 'Cefalea secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A85', 'Neuropatías craneanas dolorosas u otros dolores faciales', 'category', false, false, 'CIE-11'),
('8A8Y', 'Otros trastornos especificados de cefalea', 'category', false, false, 'CIE-11'),
('8A8Z', 'Trastornos de cefalea, sin especificación', 'category', false, false, 'CIE-11'),
('8B00', 'Hemorragia intracerebral', 'category', false, false, 'CIE-11'),
('8B00.0', 'Hemorragia hemisférica profunda', 'category', false, false, 'CIE-11'),
('8B00.1', 'Hemorragia lobular', 'category', false, false, 'CIE-11'),
('8B00.2', 'Hemorragia troncoencefálica', 'category', false, false, 'CIE-11'),
('8B00.3', 'Hemorragia cerebelosa', 'category', false, false, 'CIE-11'),
('8B00.4', 'Hemorragia intraventricular sin hemorragia parenquimatosa', 'category', false, false, 'CIE-11'),
('8B00.5', 'hemorragia cerebral en varias localizaciones', 'category', false, false, 'CIE-11'),
('8B00.Z', 'Hemorragia intracerebral, sin especificación', 'category', false, false, 'CIE-11'),
('8B01', 'Hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B01.0', 'Hemorragia subaracnoidea aneurismática', 'category', false, false, 'CIE-11'),
('8B01.1', 'Hemorragia subaracnoidea no aneurismática', 'category', false, false, 'CIE-11'),
('8B01.2', 'Hemorragia subaracnoidea, sin saber si es aneurismática o no', 'category', false, false, 'CIE-11'),
('8B02', 'Hemorragia subdural sin causa traumática', 'category', false, false, 'CIE-11'),
('8B03', 'Hemorragia epidural no traumática', 'category', false, false, 'CIE-11'),
('8B0Z', 'Hemorragia intracraneal, sin especificación', 'category', false, false, 'CIE-11'),
('8B10', 'Accidente cerebral isquémico transitorio', 'category', false, false, 'CIE-11'),
('8B10.0', 'Amaurosis fugaz', 'category', false, false, 'CIE-11'),
('8B10.Y', 'Otro accidente cerebral isquémico transitorio especificado', 'category', false, false, 'CIE-11'),
('8B10.Z', 'Accidente cerebral isquémico transitorio, sin especificación', 'category', false, false, 'CIE-11'),
('8B11', 'Accidente cerebrovascular isquémico', 'category', false, false, 'CIE-11'),
('8B11.0', 'Accidente cerebrovascular isquémico debido a ateroesclerosis de arteria extracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.1', 'Accidente cerebrovascular isquémico por ateroesclerosis de arteria intracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.2', 'Accidente cerebrovascular isquémico por oclusión embólica', 'category', false, false, 'CIE-11'),
('8B11.20', 'Accidente cerebrovascular isquémico por embolia cardíaca', 'category', false, false, 'CIE-11'),
('8B11.21', 'Accidente cerebrovascular isquémico por embolia del cayado aórtico', 'category', false, false, 'CIE-11'),
('8B11.22', 'Accidente cerebrovascular isquémico por embolismo paradójico', 'category', false, false, 'CIE-11'),
('8B11.2Y', 'Otro accidente cerebrovascular isquémico especificado por oclusión embólica', 'category', false, false, 'CIE-11'),
('8B11.2Z', 'Accidente cerebrovascular isquémico por oclusión embólica, sin especificación', 'category', false, false, 'CIE-11'),
('8B11.3', 'Accidente cerebrovascular isquémico por oclusión de una arteria pequeña', 'category', false, false, 'CIE-11'),
('8B11.4', 'Accidente cerebrovascular isquémico por otra causa conocida', 'category', false, false, 'CIE-11'),
('8B11.40', 'Accidente cerebrovascular isquémico por hipoperfusión general debida a un infarto de la zona marginal', 'category', false, false, 'CIE-11'),
('8B11.41', 'Accidente cerebrovascular isquémico por otra arteriopatía no ateroesclerótica', 'category', false, false, 'CIE-11'),
('8B11.42', 'Accidente cerebrovascular isquémico por hipercoagulabilidad sanguínea', 'category', false, false, 'CIE-11'),
('8B11.43', 'Accidente cerebrovascular isquémico asociado a hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B11.44', 'Accidente cerebrovascular isquémico por disección', 'category', false, false, 'CIE-11'),
('8B11.5', 'Accidente cerebrovascular isquémico de causa desconocida', 'category', false, false, 'CIE-11'),
('8B11.50', 'Accidente cerebrovascular isquémico por oclusión o estenosis no especificada de arteria extracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.51', 'Accidente cerebrovascular isquémico por oclusión o estenosis no especificadas de arteria intracraneal de gran tamaño', 'category', false, false, 'CIE-11'),
('8B11.5Z', 'Accidente cerebrovascular isquémico, sin especificación', 'category', false, false, 'CIE-11'),
('8B1Y', 'Otra isquemia cerebral especificada', 'category', false, false, 'CIE-11'),
('8B1Z', 'Isquemia cerebral, sin especificación', 'category', false, false, 'CIE-11'),
('8B20', 'Accidente cerebrovascular y se desconoce si es isquémico o hemorrágico', 'category', false, false, 'CIE-11'),
('8B21', 'Enfermedad cerebrovascular sin síntomas cerebrales agudos', 'category', false, false, 'CIE-11'),
('8B21.0', 'Infarto cerebral silencioso', 'category', false, false, 'CIE-11'),
('8B21.1', 'Microhemorragia cerebral silenciosa', 'category', false, false, 'CIE-11'),
('8B21.Y', 'Otra enfermedad cerebrovascular especificada sin síntomas cerebrales agudos', 'category', false, false, 'CIE-11'),
('8B21.Z', 'Enfermedad cerebrovascular sin síntomas cerebrales agudos, sin especificación', 'category', false, false, 'CIE-11'),
('8B22', 'Algunas enfermedades cerebrovasculares especificadas', 'category', false, false, 'CIE-11'),
('8B22.0', 'Disección de una arteria cerebral', 'category', false, false, 'CIE-11'),
('8B22.1', 'Trombosis venosa cerebral', 'category', false, false, 'CIE-11'),
('8B22.2', 'Síndromes de vasoconstricción cerebral', 'category', false, false, 'CIE-11'),
('8B22.3', 'Angiopatía amiloide cerebral aislada', 'category', false, false, 'CIE-11'),
('8B22.4', 'Malformación vascular intracraneal', 'category', false, false, 'CIE-11'),
('8B22.40', 'Malformación arteriovenosa de los vasos cerebrales', 'category', false, false, 'CIE-11'),
('8B22.41', 'Malformación cavernosa cerebral', 'category', false, false, 'CIE-11'),
('8B22.42', 'Fístula arteriovenosa dural', 'category', false, false, 'CIE-11'),
('8B22.43', 'Fístula cavernoso-carotídea', 'category', false, false, 'CIE-11'),
('8B22.4Y', 'Otra malformación vascular intracraneal especificada', 'category', false, false, 'CIE-11'),
('8B22.4Z', 'Malformación vascular intracraneal, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.5', 'Aneurisma cerebral, sin ruptura', 'category', false, false, 'CIE-11'),
('8B22.6', 'Aneurisma sacular cerebral familiar', 'category', false, false, 'CIE-11'),
('8B22.7', 'Arteritis cerebral, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8B22.70', 'Arteritis cerebral primaria', 'category', false, false, 'CIE-11'),
('8B22.7Y', 'Otra arteritis cerebral especificada, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8B22.7Z', 'Arteritis cerebral, no clasificada en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.8', 'Encefalopatía hipertensiva', 'category', false, false, 'CIE-11'),
('8B22.9', 'Accidente cerebrovascular inducido por migraña', 'category', false, false, 'CIE-11'),
('8B22.A', 'Síndrome de oclusión subclavia con robo de sangre', 'category', false, false, 'CIE-11'),
('8B22.B', 'Síndrome de moyamoya', 'category', false, false, 'CIE-11'),
('8B22.C', 'Enfermedades cerebrovasculares hereditarias', 'category', false, false, 'CIE-11'),
('8B22.C0', 'Síndrome ACADISL (CADASIL)- [arteriopatía cerebral autosómica dominante con infartos subcorticales y leucoencefalopatía]', 'category', false, false, 'CIE-11'),
('8B22.C1', 'Síndrome ACARISL (CARASIL) [arteriopatía cerebral autosómica recesiva con infartos subcorticales y leucoencefalopatía]', 'category', false, false, 'CIE-11'),
('8B22.CY', 'Otras enfermedades cerebrovasculares hereditarias especificadas', 'category', false, false, 'CIE-11'),
('8B22.CZ', 'Enfermedades cerebrovasculares hereditarias, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.Y', 'Otra enfermedad cerebrovascular especificada', 'category', false, false, 'CIE-11'),
('8B23', 'Trastornos cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B24', 'Encefalopatía hipóxico-isquémica', 'category', false, false, 'CIE-11'),
('8B24.0', 'Encefalopatía anóxica isquémica', 'category', false, false, 'CIE-11'),
('8B24.Y', 'Otra encefalopatía hipóxico-isquémica especificada', 'category', false, false, 'CIE-11'),
('8B24.Z', 'Encefalopatía hipóxico-isquémica, sin especificación', 'category', false, false, 'CIE-11'),
('8B25', 'Efectos tardíos de la enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('8B25.0', 'Efectos tardíos de un accidente cerebrovascular isquémico', 'category', false, false, 'CIE-11'),
('8B25.1', 'Efectos tardíos de una hemorragia intracerebral', 'category', false, false, 'CIE-11'),
('8B25.2', 'Efectos tardíos de una hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B25.3', 'Efectos tardíos de otra hemorragia intracraneal sin causa traumática', 'category', false, false, 'CIE-11'),
('8B25.4', 'Efectos tardíos de un accidente cerebrovascular sin saberse si fue isquémico o hemorrágico', 'category', false, false, 'CIE-11'),
('8B25.Y', 'Otros efectos tardíos especificados de la enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('8B25.Z', 'Efectos tardíos de la enfermedad cerebrovascular, sin especificación', 'category', false, false, 'CIE-11'),
('8B26', 'Síndromes vasculares del encéfalo en las enfermedades cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B26.0', 'Síndrome apopléctico del tronco encefálico', 'category', false, false, 'CIE-11'),
('8B26.1', 'Síndrome apopléctico cerebeloso', 'category', false, false, 'CIE-11'),
('8B26.2', 'Síndrome de la arteria cerebral media', 'category', false, false, 'CIE-11'),
('8B26.3', 'Síndrome de la arteria cerebral anterior', 'category', false, false, 'CIE-11'),
('8B26.4', 'Síndrome de la arteria cerebral posterior', 'category', false, false, 'CIE-11'),
('8B26.5', 'Síndromes lacunares', 'category', false, false, 'CIE-11'),
('8B26.50', 'Síndrome lagunar motor puro', 'category', false, false, 'CIE-11'),
('8B26.51', 'Síndrome lagunar sensorial puro', 'category', false, false, 'CIE-11'),
('8B26.5Y', 'Otros síndromes lacunares especificados', 'category', false, false, 'CIE-11'),
('8B26.5Z', 'Síndromes lacunares, sin especificación', 'category', false, false, 'CIE-11'),
('8B26.Y', 'Otros síndromes vasculares especificados del encéfalo en las enfermedades cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B26.Z', 'Síndromes vasculares del encéfalo en enfermedades cerebrovasculares, sin especificación', 'category', false, false, 'CIE-11'),
('8B2Z', 'Enfermedades cerebrovasculares, sin especificación', 'category', false, false, 'CIE-11'),
('8B40', 'Síndrome de la cola de caballo', 'category', false, false, 'CIE-11'),
('8B41', 'Mielitis', 'category', false, false, 'CIE-11'),
('8B42', 'Mielopatía', 'category', false, false, 'CIE-11'),
('8B43', 'Mielopatías vasculares no compresivas', 'category', false, false, 'CIE-11'),
('8B43.0', 'Infarto arterial agudo de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.1', 'Infarto venoso agudo de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.2', 'Infarto venoso crónico de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.Y', 'Otra mielopatía vascular no compresiva especificada', 'category', false, false, 'CIE-11'),
('8B43.Z', 'Mielopatía vascular no compresiva, sin especificación', 'category', false, false, 'CIE-11'),
('8B44', 'Trastornos mielopáticos degenerativos', 'category', false, false, 'CIE-11'),
('8B44.0', 'Paraplejia espástica hereditaria', 'category', false, false, 'CIE-11'),
('8B44.00', 'Paraplejia espástica hereditaria autosómica dominante', 'category', false, false, 'CIE-11'),
('8B44.01', 'Paraplejia espástica hereditaria autosómica recesiva', 'category', false, false, 'CIE-11'),
('8B44.02', 'Paraplejia espástica hereditaria ligada a X', 'category', false, false, 'CIE-11'),
('8B44.0Y', 'Otra paraplejia espástica hereditaria especificada', 'category', false, false, 'CIE-11'),
('8B44.0Z', 'Paraplejia espástica hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8B44.Y', 'Otros trastornos mielopáticos degenerativos especificados', 'category', false, false, 'CIE-11'),
('8B44.Z', 'Trastornos mielopáticos degenerativos, sin especificación', 'category', false, false, 'CIE-11'),
('8B4Y', 'Otros trastornos de la médula espinal especificados excepto traumatismo', 'category', false, false, 'CIE-11'),
('8B4Z', 'Trastornos de la médula espinal excepto traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('8B60', 'Enfermedades de la motoneurona', 'category', false, false, 'CIE-11'),
('8B60.0', 'Esclerosis lateral amiotrófica', 'category', false, false, 'CIE-11'),
('8B60.1', 'Parálisis bulbar progresiva', 'category', false, false, 'CIE-11'),
('8B60.2', 'Parálisis seudobulbar progresiva', 'category', false, false, 'CIE-11'),
('8B60.3', 'Atrofia muscular progresiva', 'category', false, false, 'CIE-11'),
('8B60.4', 'Esclerosis lateral primaria', 'category', false, false, 'CIE-11'),
('8B60.5', 'Esclerosis lateral amiotrófica plus', 'category', false, false, 'CIE-11'),
('8B60.6', 'Amiotrofia monomélica', 'category', false, false, 'CIE-11'),
('8B60.7', 'Enfermedad de motoneurona de Madrás', 'category', false, false, 'CIE-11'),
('8B60.Y', 'Otras enfermedades especificadas de la motoneurona', 'category', false, false, 'CIE-11'),
('8B60.Z', 'Enfermedades de la motoneurona, sin especificación', 'category', false, false, 'CIE-11'),
('8B61', 'Atrofia muscular espinal', 'category', false, false, 'CIE-11'),
('8B61.0', 'Atrofia muscular espinal infantil de tipo I', 'category', false, false, 'CIE-11'),
('8B61.1', 'Atrofia muscular espinal infantil tardía de tipo II', 'category', false, false, 'CIE-11'),
('8B61.2', 'Distrofia muscular espinal juvenil de tipo III', 'category', false, false, 'CIE-11'),
('8B61.3', 'Atrofia muscular espinal de comienzo en la edad adulta, tipo IV', 'category', false, false, 'CIE-11'),
('8B61.4', 'Atrofia muscular espinal localizada', 'category', false, false, 'CIE-11'),
('8B61.Y', 'Otra atrofia muscular espinal especificada', 'category', false, false, 'CIE-11'),
('8B61.Z', 'Atrofia muscular espinal, sin especificación', 'category', false, false, 'CIE-11'),
('8B62', 'Atrofia muscular progresiva pospoliomielítica', 'category', false, false, 'CIE-11'),
('8B6Y', 'Otra enfermedad especificada de la neurona motora o trastornos afines', 'category', false, false, 'CIE-11'),
('8B6Z', 'Enfermedad de la neurona motora o trastornos afines, sin especificación', 'category', false, false, 'CIE-11'),
('8B80', 'Trastornos del nervio olfatorio', 'category', false, false, 'CIE-11'),
('8B81', 'Trastornos del nervio vestibulococlear', 'category', false, false, 'CIE-11'),
('8B81.0', 'Lesión del tronco encefálico', 'category', false, false, 'CIE-11'),
('8B81.Y', 'Otros trastornos del nervio vestibulococlear', 'category', false, false, 'CIE-11'),
('8B81.Z', 'Trastornos del nervio vestibulococlear, sin especificación', 'category', false, false, 'CIE-11'),
('8B82', 'Trastornos del nervio trigémino', 'category', false, false, 'CIE-11'),
('8B82.0', 'Neuralgia del trigémino', 'category', false, false, 'CIE-11'),
('8B82.Z', 'Trastornos del nervio trigémino, sin especificación', 'category', false, false, 'CIE-11'),
('8B83', 'Trastornos del nervio espinal accesorio', 'category', false, false, 'CIE-11'),
('8B84', 'Trastornos del nervio hipogloso', 'category', false, false, 'CIE-11'),
('8B85', 'Trastornos de múltiples pares craneales', 'category', false, false, 'CIE-11'),
('8B86', 'Trastornos del nervio vago', 'category', false, false, 'CIE-11'),
('8B87', 'Trastornos del nervio glosofaríngeo', 'category', false, false, 'CIE-11'),
('8B88', 'Trastornos del nervio facial', 'category', false, false, 'CIE-11'),
('8B88.0', 'Parálisis de Bell', 'category', false, false, 'CIE-11'),
('8B88.1', 'Mioquimia facial', 'category', false, false, 'CIE-11'),
('8B88.2', 'Espasmo hemifacial', 'category', false, false, 'CIE-11'),
('8B88.3', 'Neuritis facial', 'category', false, false, 'CIE-11'),
('8B88.Y', 'Otros trastornos especificados del nervio facial', 'category', false, false, 'CIE-11'),
('8B88.Z', 'Trastornos del nervio facial, sin especificación', 'category', false, false, 'CIE-11'),
('8B8Y', 'Otros trastornos especificados de los nervios craneales', 'category', false, false, 'CIE-11'),
('8B8Z', 'Trastornos de los nervios craneales, sin especificación', 'category', false, false, 'CIE-11'),
('8B90', 'Compresiones de plexos o de las raíces nerviosas', 'category', false, false, 'CIE-11'),
('8B91', 'Trastornos del plexo braquial', 'category', false, false, 'CIE-11'),
('8B91.0', 'Amiotrofia neurálgica del hombro', 'category', false, false, 'CIE-11'),
('8B91.1', 'Síndrome de la salida torácica debido a costilla cervical', 'category', false, false, 'CIE-11'),
('8B91.Y', 'Otros trastornos del plexo braquial especificados', 'category', false, false, 'CIE-11'),
('8B91.Z', 'Trastornos del plexo braquial, sin especificación', 'category', false, false, 'CIE-11'),
('8B92', 'Trastornos del plexo lumbosacro', 'category', false, false, 'CIE-11'),
('8B92.0', 'Plexopatía lumbosacra tras radiación', 'category', false, false, 'CIE-11'),
('8B92.1', 'Plexopatía vasculítica lumbosacra', 'category', false, false, 'CIE-11'),
('8B92.2', 'Plexopatía lumbosacra diabética', 'category', false, false, 'CIE-11'),
('8B92.3', 'Radiculoplexopatía lumbosacra', 'category', false, false, 'CIE-11'),
('8B92.Y', 'Otros trastornos especificados del plexo lumbosacro', 'category', false, false, 'CIE-11'),
('8B92.Z', 'Trastornos del plexo lumbosacro, sin especificación', 'category', false, false, 'CIE-11'),
('8B93', 'Radiculopatía', 'category', false, false, 'CIE-11'),
('8B93.0', 'Radiculopatía debida a compresión', 'category', false, false, 'CIE-11'),
('8B93.1', 'Radiculopatía por trastornos metabólicos', 'category', false, false, 'CIE-11'),
('8B93.2', 'Radiculopatía por corriente eléctrica o relámpago', 'category', false, false, 'CIE-11'),
('8B93.3', 'Radiculopatía por radiación', 'category', false, false, 'CIE-11'),
('8B93.4', 'Radiculopatía por deficiencias nutricionales', 'category', false, false, 'CIE-11'),
('8B93.5', 'Radiculopatía por toxicidad', 'category', false, false, 'CIE-11'),
('8B93.6', 'Radiculopatía por lesiones del disco intervertebral', 'category', false, false, 'CIE-11'),
('8B93.7', 'Radiculopatía por enfermedad neoplásica', 'category', false, false, 'CIE-11'),
('8B93.8', 'Radiculopatía por espondilosis', 'category', false, false, 'CIE-11'),
('8B93.Y', 'Otra radiculopatía especificada', 'category', false, false, 'CIE-11'),
('8B93.Z', 'Radiculopatía, sin especificación', 'category', false, false, 'CIE-11'),
('8B94', 'Radiculoplexoneuropatía diabética', 'category', false, false, 'CIE-11'),
('8B95', 'Lesión secundaria del plexo braquial debida a ciertos trastornos especificados', 'category', false, false, 'CIE-11'),
('8B9Y', 'Otros trastornos de los plexos o raíces nerviosas especificados', 'category', false, false, 'CIE-11'),
('8B9Z', 'Trastornos de los plexos o raíces nerviosas, sin especificación', 'category', false, false, 'CIE-11'),
('8C00', 'Neuropatía progresiva idiopática', 'category', false, false, 'CIE-11'),
('8C01', 'Polineuropatía inflamatoria', 'category', false, false, 'CIE-11'),
('8C01.0', 'Polineuropatía desmielinizante inflamatoria aguda', 'category', false, false, 'CIE-11'),
('8C01.1', 'Neuropatía posvacunal', 'category', false, false, 'CIE-11'),
('8C01.2', 'Polineuropatía desmielinizante inflamatoria subaguda', 'category', false, false, 'CIE-11'),
('8C01.3', 'Polineuropatía desmielinizante inflamatoria crónica', 'category', false, false, 'CIE-11'),
('8C01.Y', 'Otra polineuropatía inflamatoria especificada', 'category', false, false, 'CIE-11'),
('8C01.Z', 'Polineuropatía inflamatoria, sin especificación', 'category', false, false, 'CIE-11'),
('8C03', 'Otra polineuropatía secundaria', 'category', false, false, 'CIE-11'),
('8C03.0', 'Polineuropatía diabética', 'category', false, false, 'CIE-11'),
('8C03.1', 'Polineuropatía debida a enfermedades infecciosas', 'category', false, false, 'CIE-11'),
('8C03.2', 'Polineuropatía en las enfermedades neoplásicas', 'category', false, false, 'CIE-11'),
('8C03.3', 'Polineuropatía por deficiencia nutricional', 'category', false, false, 'CIE-11'),
('8C03.4', 'Polineuropatía en los trastornos sistémicos del tejido conectivo', 'category', false, false, 'CIE-11'),
('8C03.Y', 'Otra polineuropatía secundaria especificada', 'category', false, false, 'CIE-11'),
('8C03.Z', 'Otra polineuropatía secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8C0Y', 'Otra polineuropatía especificada', 'category', false, false, 'CIE-11'),
('8C0Z', 'Polineuropatía, sin especificación', 'category', false, false, 'CIE-11'),
('8C10', 'Mononeuropatías de extremidad superior', 'category', false, false, 'CIE-11'),
('8C10.0', 'Síndrome del túnel del carpo', 'category', false, false, 'CIE-11'),
('8C10.1', 'Lesión del nervio cubital', 'category', false, false, 'CIE-11'),
('8C10.2', 'Lesión del nervio radial', 'category', false, false, 'CIE-11'),
('8C10.Y', 'Otras mononeuropatías especificadas de extremidad superior', 'category', false, false, 'CIE-11'),
('8C10.Z', 'Mononeuropatías de extremidad superior, sin especificación', 'category', false, false, 'CIE-11'),
('8C11', 'Mononeuropatías de extremidad inferior', 'category', false, false, 'CIE-11'),
('8C11.0', 'Lesión del nervio ciático', 'category', false, false, 'CIE-11'),
('8C11.00', 'Síndrome piriforme del nervio ciático', 'category', false, false, 'CIE-11'),
('8C11.0Y', 'Otra lesión especificada del nervio ciático', 'category', false, false, 'CIE-11'),
('8C11.0Z', 'Lesión del nervio ciático, sin especificación', 'category', false, false, 'CIE-11'),
('8C11.1', 'Meralgia parestésica', 'category', false, false, 'CIE-11'),
('8C11.2', 'Lesión del nervio femoral', 'category', false, false, 'CIE-11'),
('8C11.3', 'Lesión del nervio peroneo común', 'category', false, false, 'CIE-11'),
('8C11.4', 'Lesión del nervio tibial', 'category', false, false, 'CIE-11'),
('8C11.5', 'Síndrome del túnel del tarso', 'category', false, false, 'CIE-11'),
('8C11.6', 'Lesión del nervio plantar', 'category', false, false, 'CIE-11'),
('8C11.Y', 'Otras mononeuropatías especificadas de extremidad inferior', 'category', false, false, 'CIE-11'),
('8C11.Z', 'Mononeuropatías de extremidad inferior, sin especificación', 'category', false, false, 'CIE-11'),
('8C12', 'Algunas mononeuropatías especificadas', 'category', false, false, 'CIE-11'),
('8C12.0', 'Neuropatía intercostal', 'category', false, false, 'CIE-11'),
('8C12.1', 'Mononeuritis múltiple', 'category', false, false, 'CIE-11'),
('8C12.2', 'Lesión del nervio supraescapular', 'category', false, false, 'CIE-11'),
('8C12.3', 'Lesión del nervio axilar', 'category', false, false, 'CIE-11'),
('8C12.4', 'Lesión del nervio torácico largo', 'category', false, false, 'CIE-11'),
('8C12.5', 'Neuroma traumático, no especificado en otra parte', 'category', false, false, 'CIE-11'),
('8C12.Y', 'Algunas otras mononeuropatías especificadas', 'category', false, false, 'CIE-11'),
('8C1Y', 'Mononeuropatía, de otro sitio especificado', 'category', false, false, 'CIE-11'),
('8C1Z', 'Mononeuropatía, de sitio no especificado', 'category', false, false, 'CIE-11'),
('8C20', 'Neuropatía motora y sensorial hereditaria', 'category', false, false, 'CIE-11'),
('8C20.0', 'Enfermedad de Charcot-Marie-Tooth de tipo 1 desmielinizante', 'category', false, false, 'CIE-11'),
('8C20.1', 'Enfermedad de Charcot-Marie-Tooth de tipo 2 axonal', 'category', false, false, 'CIE-11'),
('8C20.2', 'Enfermedad de Charcot-Marie-Tooth intermedia', 'category', false, false, 'CIE-11'),
('8C20.Y', 'Otra neuropatía motora o sensorial hereditaria especificada', 'category', false, false, 'CIE-11'),
('8C20.Z', 'Neuropatía motora o sensorial hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8C21', 'Neuropatía autonómica o sensorial hereditaria', 'category', false, false, 'CIE-11'),
('8C21.0', 'Neuropatía autonómica y sensorial hereditaria de tipo I', 'category', false, false, 'CIE-11'),
('8C21.1', 'Neuropatía autonómica y sensorial hereditaria de tipo III', 'category', false, false, 'CIE-11'),
('8C21.2', 'Neuropatía autonómica y sensorial hereditaria tipo IV', 'category', false, false, 'CIE-11'),
('8C21.3', 'Neuropatía autonómica y sensorial hereditaria tipo V', 'category', false, false, 'CIE-11'),
('8C21.Y', 'Otra neuropatía autonómica o sensorial hereditaria especificada', 'category', false, false, 'CIE-11'),
('8C21.Z', 'Neuropatía autonómica o sensorial hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8C2Y', 'Otra neuropatía hereditaria especificada', 'category', false, false, 'CIE-11'),
('8C2Z', 'Neuropatía hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8C4Y', 'Otros trastornos especificados de la raíz nerviosa, plexo o de los nervios periféricos', 'category', false, false, 'CIE-11'),
('8C4Z', 'Trastornos de la raiz nerviosa, plexo o de los nervios periféricos, sin especificación', 'category', false, false, 'CIE-11'),
('8C60', 'Miastenia grave', 'category', false, false, 'CIE-11'),
('8C60.0', 'Miastenia grave provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8C60.Y', 'Otra miastenia grave especificada', 'category', false, false, 'CIE-11'),
('8C60.Z', 'Miastenia grave, sin especificación', 'category', false, false, 'CIE-11'),
('8C61', 'Síndromes miasténicos congénitos', 'category', false, false, 'CIE-11'),
('8C62', 'Síndrome de Lambert-Eaton', 'category', false, false, 'CIE-11'),
('8C6Y', 'Otra miastenia grave y trastornos de la unión neuromuscular especificados', 'category', false, false, 'CIE-11'),
('8C6Z', 'Miastenia grave o trastornos de la unión neuromuscular, sin especificación', 'category', false, false, 'CIE-11'),
('8C70', 'Distrofia muscular', 'category', false, false, 'CIE-11'),
('8C70.0', 'Distrofia muscular de Becker', 'category', false, false, 'CIE-11'),
('8C70.1', 'Distrofia muscular de Duchènne', 'category', false, false, 'CIE-11'),
('8C70.2', 'Distrofia muscular de Emery-Dreifuss', 'category', false, false, 'CIE-11'),
('8C70.3', 'Distrofia muscular facioescapulohumeral', 'category', false, false, 'CIE-11'),
('8C70.4', 'Distrofia muscular de la cintura de los miembros escapular y pélvica', 'category', false, false, 'CIE-11'),
('8C70.40', 'Distrofia muscular de cinturas dominante', 'category', false, false, 'CIE-11'),
('8C70.41', 'Distrofia muscular de cinturas de los miembros recesiva', 'category', false, false, 'CIE-11'),
('8C70.4Y', 'Otra distrofia muscular especificada de las cinturas de los miembros', 'category', false, false, 'CIE-11'),
('8C70.4Z', 'Distrofia muscular de las cinturas de los miembros, sin especificación', 'category', false, false, 'CIE-11'),
('8C70.5', 'Distrofia muscular escapuloperonea', 'category', false, false, 'CIE-11'),
('8C70.6', 'Distrofia muscular congénita', 'category', false, false, 'CIE-11'),
('8C70.Y', 'Otra distrofia muscular especificada', 'category', false, false, 'CIE-11'),
('8C70.Z', 'Distrofia muscular, sin especificación', 'category', false, false, 'CIE-11'),
('8C71', 'Trastornos miotónicos', 'category', false, false, 'CIE-11'),
('8C71.0', 'Distrofia miotónica', 'category', false, false, 'CIE-11'),
('8C71.1', 'Miotonía condrodistrófica', 'category', false, false, 'CIE-11'),
('8C71.2', 'Miotonía congénita', 'category', false, false, 'CIE-11'),
('8C71.3', 'Miotonía provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8C71.4', 'Neuromiotonía', 'category', false, false, 'CIE-11'),
('8C71.5', 'Seudomiotonía', 'category', false, false, 'CIE-11'),
('8C71.Y', 'Otros trastornos miotónicos especificados', 'category', false, false, 'CIE-11'),
('8C71.Z', 'Trastornos miotónicos, sin especificación', 'category', false, false, 'CIE-11'),
('8C72', 'Miopatías congénitas', 'category', false, false, 'CIE-11'),
('8C72.0', 'Miopatía congénita con anomalías estructurales', 'category', false, false, 'CIE-11'),
('8C72.00', 'Miopatía nemalínica', 'category', false, false, 'CIE-11'),
('8C72.01', 'Miopatía centronuclear', 'category', false, false, 'CIE-11'),
('8C72.02', 'Enfermedad del núcleo central', 'category', false, false, 'CIE-11'),
('8C72.0Y', 'Otra miopatía congénita especificada con anomalías estructurales', 'category', false, false, 'CIE-11'),
('8C72.0Z', 'Miopatía congénita con anomalías estructurales, sin especificación', 'category', false, false, 'CIE-11'),
('8C72.1', 'Miopatía congénita sin anomalías estructurales', 'category', false, false, 'CIE-11'),
('8C72.Y', 'Otras miopatías congénitas especificadas', 'category', false, false, 'CIE-11'),
('8C72.Z', 'Miopatías congénitas, sin especificación', 'category', false, false, 'CIE-11'),
('8C73', 'Miopatías mitocondriales', 'category', false, false, 'CIE-11'),
('8C73.0', 'Miocardiopatía autosómica recesiva u oftalmoplejía', 'category', false, false, 'CIE-11'),
('8C73.1', 'Neuropatía, ataxia y retinosis pigmentaria', 'category', false, false, 'CIE-11'),
('8C73.Y', 'Otras miopatías mitocondriales especificadas', 'category', false, false, 'CIE-11'),
('8C73.Z', 'Miopatías mitocondriales, sin especificación', 'category', false, false, 'CIE-11'),
('8C74', 'Parálisis o trastornos periódicos de la excitabilidad de la membrana muscular', 'category', false, false, 'CIE-11'),
('8C74.0', 'Paramiotonía congénita', 'category', false, false, 'CIE-11'),
('8C74.1', 'Parálisis periódica', 'category', false, false, 'CIE-11'),
('8C74.10', 'Parálisis periódica hipocalémica', 'category', false, false, 'CIE-11'),
('8C74.11', 'Parálisis periódica hipercalémica', 'category', false, false, 'CIE-11'),
('8C74.1Y', 'Otra parálisis periódica especificada', 'category', false, false, 'CIE-11'),
('8C74.1Z', 'Parálisis periódica, sin especificación', 'category', false, false, 'CIE-11'),
('8C74.Y', 'Otra parálisis o trastorno periódico especificado de la excitabilidad de la membrana muscular', 'category', false, false, 'CIE-11'),
('8C74.Z', 'Parálisis o trastorno periódico de la excitabilidad de la membrana muscular, sin especificación', 'category', false, false, 'CIE-11'),
('8C75', 'Miopatías distales', 'category', false, false, 'CIE-11'),
('8C76', 'Miopatía miofibrilar', 'category', false, false, 'CIE-11'),
('8C77', 'Miopatía ocular', 'category', false, false, 'CIE-11'),
('8C78', 'Hiperpirexia o hipertermia maligna', 'category', false, false, 'CIE-11'),
('8C7Y', 'Otras miopatías primarias especificadas', 'category', false, false, 'CIE-11'),
('8C7Z', 'Miopatías primarias, sin especificación', 'category', false, false, 'CIE-11'),
('8C80', 'Miopatía provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8C81', 'Miopatía autoinmunitaria', 'category', false, false, 'CIE-11'),
('8C82', 'Miopatía en ciertas enfermedades infecciosas o parasitarias especificadas', 'category', false, false, 'CIE-11'),
('8C83', 'Miopatía en una enfermedad endocrina especificada', 'category', false, false, 'CIE-11'),
('8C84', 'Rabdomiólisis secundaria', 'category', false, false, 'CIE-11'),
('8C8Y', 'Otras miopatías secundarias especificadas', 'category', false, false, 'CIE-11'),
('8C8Z', 'Miopatías secundarias, sin especificación', 'category', false, false, 'CIE-11'),
('8D0Y', 'Otras enfermedades especificadas de la unión neuromuscular o muscular', 'category', false, false, 'CIE-11'),
('8D0Z', 'Enfermedades de la unión neuromuscular o muscular, sin especificación', 'category', false, false, 'CIE-11'),
('8D20', 'Parálisis cerebral espástica', 'category', false, false, 'CIE-11'),
('8D20.0', 'Parálisis cerebral espástica unilateral', 'category', false, false, 'CIE-11'),
('8D20.1', 'Parálisis cerebral espástica bilateral', 'category', false, false, 'CIE-11'),
('8D20.10', 'Parálisis cerebral espástica tetrapléjica', 'category', false, false, 'CIE-11'),
('8D20.11', 'Parálisis cerebral espástica dipléjica', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
