-- CIE11 Import Part 67
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XM2BL7', 'Adhesivo de polietileno', 'category', false, false, 'CIE-11'),
('XM6J14', 'Protector, de la piel', 'category', false, false, 'CIE-11'),
('XM9VE3', 'Piroxilina', 'category', false, false, 'CIE-11'),
('XM8293', 'Pomada de agua de rosas', 'category', false, false, 'CIE-11'),
('XM06Y2', 'Silicona medicinal', 'category', false, false, 'CIE-11'),
('XM9410', 'Loción protectora de la radiación solar', 'category', false, false, 'CIE-11'),
('XM4YA6', 'Sulisobenzona', 'category', false, false, 'CIE-11'),
('XM7YQ8', 'Aceite dulce (abedul)', 'category', false, false, 'CIE-11'),
('XM3599', 'Talco', 'category', false, false, 'CIE-11'),
('XM3MF9', 'Tiosinamina', 'category', false, false, 'CIE-11'),
('XM7Q94', 'Dióxido de titanio', 'category', false, false, 'CIE-11'),
('XM6WX7', 'Óxido de titanio', 'category', false, false, 'CIE-11'),
('XM5E39', 'Protector de la luz ultravioleta', 'category', false, false, 'CIE-11'),
('XM4D35', 'Éster hexílico del ácido 2- [4- (dietilamino) -2-hidroxibenzoil] benzoico', 'category', false, false, 'CIE-11'),
('XM8A13', 'Metileno bis-benzotriazolil tetrametilbutilfenol', 'category', false, false, 'CIE-11'),
('XM6UT3', 'Ácido 2-fenil-1H-benzo imidazol-5-sulfónico', 'category', false, false, 'CIE-11'),
('XM65Q8', '2,4,6-Tianilino-p-(carbo-2-etilhexil-1-oxi) -1,3,5-triazina', 'category', false, false, 'CIE-11'),
('XM5PP3', 'Bota de Unna', 'category', false, false, 'CIE-11'),
('XM8H46', 'Gelatina de zinc', 'category', false, false, 'CIE-11'),
('XM7RG9', 'Óxido de zinc', 'category', false, false, 'CIE-11'),
('XM4NT3', 'Estearato de zinc', 'category', false, false, 'CIE-11'),
('XM8YJ6', 'Colofonio', 'category', false, false, 'CIE-11'),
('XM1LY7', 'Sorbitan sesquioleate', 'category', false, false, 'CIE-11'),
('XM2M34', 'Octinoxato', 'category', false, false, 'CIE-11'),
('XM2F87', 'Ácido hialurónico tópico', 'category', false, false, 'CIE-11'),
('XM90Q0', 'Cetomacrogol', 'category', false, false, 'CIE-11'),
('XM8N69', 'Etofenamato', 'category', false, false, 'CIE-11'),
('XM85Z1', 'Uso dental medicinal con flúor', 'category', false, false, 'CIE-11'),
('XM9RB7', 'Flúor estañoso', 'category', false, false, 'CIE-11'),
('XM60N7', 'Sales de bismuto yoduro fórmico', 'category', false, false, 'CIE-11'),
('XM0DJ3', 'Cadexómero', 'category', false, false, 'CIE-11'),
('XM12P7', 'Diyodohidroxipropano', 'category', false, false, 'CIE-11'),
('XM8UZ7', 'Diyodohidroxiquina tópico', 'category', false, false, 'CIE-11'),
('XM0809', 'Yodo', 'category', false, false, 'CIE-11'),
('XM8C24', 'Yoduro de mercurio(ungüento)', 'category', false, false, 'CIE-11'),
('XM3Q63', 'Yoduro metilato', 'category', false, false, 'CIE-11'),
('XM6TG8', 'Yodoclorhidroxiquina tópico', 'category', false, false, 'CIE-11'),
('XM3X72', 'Iodoformo', 'category', false, false, 'CIE-11'),
('XM58X1', 'Iodato de potasio', 'category', false, false, 'CIE-11'),
('XM24J7', 'Yodo povidona', 'category', false, false, 'CIE-11'),
('XM9ZS1', 'Alantoina', 'category', false, false, 'CIE-11'),
('XM7H25', 'Alumbre (medicinal)', 'category', false, false, 'CIE-11'),
('XM2GV6', 'Ictiosulfonato de amonio', 'category', false, false, 'CIE-11'),
('XM8RR9', 'Persulfato de amonio', 'category', false, false, 'CIE-11'),
('XM8HL4', 'Antralina', 'category', false, false, 'CIE-11'),
('XM8SX1', 'Antiseborreicos', 'category', false, false, 'CIE-11'),
('XM8GU1', 'Butantrona', 'category', false, false, 'CIE-11'),
('XM4FV2', 'Aceite de Cade', 'category', false, false, 'CIE-11'),
('XM2ST0', 'Sulfuro de cadmio (medicinal)', 'category', false, false, 'CIE-11'),
('XM9TT3', 'Capsicum', 'category', false, false, 'CIE-11'),
('XM4AW0', 'Nieve de dióxido de carbono', 'category', false, false, 'CIE-11'),
('XM01Q7', 'Clorotimol', 'category', false, false, 'CIE-11'),
('XM92H5', 'Cloroxina', 'category', false, false, 'CIE-11'),
('XM7HY4', 'Crisarobina', 'category', false, false, 'CIE-11'),
('XM3P37', 'Alquitrán de hulla medicinal (ungüento)', 'category', false, false, 'CIE-11'),
('XM3LD7', 'Colagenasa tópica', 'category', false, false, 'CIE-11'),
('XM7PM1', 'Curas de maíz', 'category', false, false, 'CIE-11'),
('XM5W78', 'Depilatorio', 'category', false, false, 'CIE-11'),
('XM95C8', 'Yeso Diaquilon', 'category', false, false, 'CIE-11'),
('XM64V2', 'Dimetil sulfóxido medicinal', 'category', false, false, 'CIE-11'),
('XM26P0', 'Sulfato de dimetilamina', 'category', false, false, 'CIE-11'),
('XM8RS8', 'Ditranol', 'category', false, false, 'CIE-11'),
('XM17Y7', 'Enzima proteolítica', 'category', false, false, 'CIE-11'),
('XM3JC8', 'Cloruro de etilo local', 'category', false, false, 'CIE-11'),
('XM4P92', 'Fumarato de etilo', 'category', false, false, 'CIE-11'),
('XM7WC9', 'Euresol', 'category', false, false, 'CIE-11'),
('XM7VL9', 'Tinte para el cabello', 'category', false, false, 'CIE-11'),
('XM8GV4', 'Hemostiptico', 'category', false, false, 'CIE-11'),
('XM7KM8', 'Alcohol isopropilico medicinal', 'category', false, false, 'CIE-11'),
('XM6ES1', 'Antraceno medicamento queratolítico', 'category', false, false, 'CIE-11'),
('XM23V5', 'Droga queratolítica', 'category', false, false, 'CIE-11'),
('XM4KL1', 'Queratoplástico', 'category', false, false, 'CIE-11'),
('XM76E0', 'Pasta de Lassar', 'category', false, false, 'CIE-11'),
('XM1VX5', 'Nicotinato de metilo', 'category', false, false, 'CIE-11'),
('XM8N27', 'Monobenzona', 'category', false, false, 'CIE-11'),
('XM6YQ8', 'Piritionato de zinc', 'category', false, false, 'CIE-11'),
('XM4549', 'Resorcina, resorcinol medicinal', 'category', false, false, 'CIE-11'),
('XM5DQ2', 'Rubefaciente', 'category', false, false, 'CIE-11'),
('XM68B5', 'Ácido salicílico', 'category', false, false, 'CIE-11'),
('XM02N6', 'Savin (aceite)', 'category', false, false, 'CIE-11'),
('XM43T8', 'Sulfuro de selenio', 'category', false, false, 'CIE-11'),
('XM1UK4', 'Selsun', 'category', false, false, 'CIE-11'),
('XM3E07', 'Nitrato de plata endurecido (queratolítico)', 'category', false, false, 'CIE-11'),
('XM1FW6', 'Compuestos de azufre no clasificados en otra parte (medicinales)', 'category', false, false, 'CIE-11'),
('XM6ZA6', 'Ungüento queratolítico de azufre', 'category', false, false, 'CIE-11'),
('XM1W96', 'Tioglicolato', 'category', false, false, 'CIE-11'),
('XM7GY2', 'Tioxolona', 'category', false, false, 'CIE-11'),
('XM4ZP4', 'Triacetoxiantraceno', 'category', false, false, 'CIE-11'),
('XM6U21', 'Ácido tricloracético medicinal', 'category', false, false, 'CIE-11'),
('XM2V83', 'Solución de Vleminckx', 'category', false, false, 'CIE-11'),
('XM6T99', 'Loción blanca (queratolítica)', 'category', false, false, 'CIE-11'),
('XM25J6', 'Xenisalato', 'category', false, false, 'CIE-11'),
('XM7AM5', 'Monotioglicolato de glicerilo', 'category', false, false, 'CIE-11'),
('XM5L79', 'p Diaminotolueno', 'category', false, false, 'CIE-11'),
('XM75W8', 'Adrenal preparado oftálmico', 'category', false, false, 'CIE-11'),
('XM6H73', 'Tartrato ácido de amonio', 'category', false, false, 'CIE-11'),
('XM6G79', 'Preparación oftálmica anti infecciosa', 'category', false, false, 'CIE-11'),
('XM5568', 'Anticolinesterasa reversible oftalmológica', 'category', false, false, 'CIE-11'),
('XM5T83', 'Befunolol', 'category', false, false, 'CIE-11'),
('XM6NB7', 'Bibrocatol', 'category', false, false, 'CIE-11'),
('XM32H1', 'Preparado oftálmico Quimotripsina', 'category', false, false, 'CIE-11'),
('XM6E41', 'Colistina sulfato(preparación para ojos)', 'category', false, false, 'CIE-11'),
('XM1WZ1', 'Solución de lentes de contacto', 'category', false, false, 'CIE-11'),
('XM3X79', 'Sulfato de cobre cúprico medicinal para ojos', 'category', false, false, 'CIE-11'),
('XM3918', 'Droga ciclopléjica', 'category', false, false, 'CIE-11'),
('XM8S71', 'Bromuro de demecario', 'category', false, false, 'CIE-11'),
('XM1X30', 'Dendrid', 'category', false, false, 'CIE-11'),
('XM0L12', 'Dipivefrina', 'category', false, false, 'CIE-11'),
('XM17P1', 'Ecotiofato', 'category', false, false, 'CIE-11'),
('XM7K14', 'Yoduro de Ecotiofato', 'category', false, false, 'CIE-11'),
('XM09W6', 'Edoxudina', 'category', false, false, 'CIE-11'),
('XM8PJ6', 'Eucatropina', 'category', false, false, 'CIE-11'),
('XM45L3', 'Fluorfenilalanina', 'category', false, false, 'CIE-11'),
('XM1783', 'Herplex', 'category', false, false, 'CIE-11'),
('XM9EN3', 'Hidroxianfetamina', 'category', false, false, 'CIE-11'),
('XM9E72', 'Hipromelosa', 'category', false, false, 'CIE-11'),
('XM0PE3', 'Lachesina', 'category', false, false, 'CIE-11'),
('XM8098', 'Levobunolol', 'category', false, false, 'CIE-11'),
('XM4QZ9', 'Metilparabeno (oftálmico)', 'category', false, false, 'CIE-11'),
('XM0YH4', 'Metipranolol', 'category', false, false, 'CIE-11'),
('XM2JE0', 'Droga miótica', 'category', false, false, 'CIE-11'),
('XM4DY8', 'Preparado oftálmico Micitracina', 'category', false, false, 'CIE-11'),
('XM5PU9', 'Droga midriática', 'category', false, false, 'CIE-11'),
('XM28C3', 'Preparado oftálmico de neosporina', 'category', false, false, 'CIE-11'),
('XM4PY4', 'Fosfolina', 'category', false, false, 'CIE-11'),
('XM4605', 'Fisostigmina', 'category', false, false, 'CIE-11'),
('XM9N59', 'Polimixina E sulfato (preparado para ojos)', 'category', false, false, 'CIE-11'),
('XM2WK3', 'Propilparabeno (oftálmico)', 'category', false, false, 'CIE-11'),
('XM56H1', 'Proteína de plata', 'category', false, false, 'CIE-11'),
('XM7AV0', 'Limpiador de ojo Borato de sodio', 'category', false, false, 'CIE-11'),
('XM6Q18', 'Estoxil', 'category', false, false, 'CIE-11'),
('XM8A14', 'Preparado oftálmico de sulfisoxazol', 'category', false, false, 'CIE-11'),
('XM9PG5', 'Sulfonamida para ojos', 'category', false, false, 'CIE-11'),
('XM61C9', 'Solución Tear', 'category', false, false, 'CIE-11'),
('XM5RC2', 'Tetrahidrozolina', 'category', false, false, 'CIE-11'),
('XM31C8', 'Visine', 'category', false, false, 'CIE-11'),
('XM9X81', 'Acetazolamida', 'category', false, false, 'CIE-11'),
('XM4LU1', 'Diclorfenamida', 'category', false, false, 'CIE-11'),
('XM4DH5', 'Etoxzolamida', 'category', false, false, 'CIE-11'),
('XM8P33', 'Metazolamida', 'category', false, false, 'CIE-11'),
('XM3ZJ4', 'Pemirolast', 'category', false, false, 'CIE-11'),
('XM2JR8', 'Picloxidina', 'category', false, false, 'CIE-11'),
('XM6JB1', 'Fluostigmina', 'category', false, false, 'CIE-11'),
('XM3BT0', 'Dorzolamida', 'category', false, false, 'CIE-11'),
('XM9GB8', 'Brinzolamida', 'category', false, false, 'CIE-11'),
('XM5130', 'Latanoprost', 'category', false, false, 'CIE-11'),
('XM5ZG4', 'Unoprostona', 'category', false, false, 'CIE-11'),
('XM6E95', 'Bimatoprost', 'category', false, false, 'CIE-11'),
('XM9BS0', 'Travoprost', 'category', false, false, 'CIE-11'),
('XM3UC8', 'Tafluprost', 'category', false, false, 'CIE-11'),
('XM6PD6', 'Dapiprazol', 'category', false, false, 'CIE-11'),
('XM8469', 'Netarsudil', 'category', false, false, 'CIE-11'),
('XM0GK6', 'Pegaptanib', 'category', false, false, 'CIE-11'),
('XM95Y7', 'Ranibizumab', 'category', false, false, 'CIE-11'),
('XM42E0', 'Yodoheparinato', 'category', false, false, 'CIE-11'),
('XM67C4', 'Lifitegrast', 'category', false, false, 'CIE-11'),
('XM57P1', 'Cenegermina', 'category', false, false, 'CIE-11'),
('XM2RM5', 'Ocriplasmina', 'category', false, false, 'CIE-11'),
('XM0YQ8', 'Células madre autólogas del limbo', 'category', false, false, 'CIE-11'),
('XM2GK8', 'Lágrimas artificiales y otras preparaciones indiferentes.', 'category', false, false, 'CIE-11'),
('XM3PF8', 'Anecortave', 'category', false, false, 'CIE-11'),
('XM7CE4', 'Guaiazuleno', 'category', false, false, 'CIE-11'),
('XM0ST2', 'Olopatadina', 'category', false, false, 'CIE-11'),
('XM49V8', 'Azidamfenicol', 'category', false, false, 'CIE-11'),
('XM3G39', 'Sulfadicramida', 'category', false, false, 'CIE-11'),
('XM13T1', 'Sulfafenazol', 'category', false, false, 'CIE-11'),
('XM4F24', 'Preparación oftálmica de interferón', 'category', false, false, 'CIE-11'),
('XM0C71', 'Fomivirsen', 'category', false, false, 'CIE-11'),
('XM1A96', 'Besifloxacina', 'category', false, false, 'CIE-11'),
('XM7415', 'Compuestos de mercurio', 'category', false, false, 'CIE-11'),
('XM9KL6', 'Loteprednol', 'category', false, false, 'CIE-11'),
('XM6GF5', 'Formocortal', 'category', false, false, 'CIE-11'),
('XM9166', 'Pranoprofeno', 'category', false, false, 'CIE-11'),
('XM4GZ0', 'Nepafenaco', 'category', false, false, 'CIE-11'),
('XM0QS2', 'Bromfenaco', 'category', false, false, 'CIE-11'),
('XM14H0', 'Preparación oftálmica de brimonidina', 'category', false, false, 'CIE-11'),
('XM9KS5', 'Preparación oftálmica de acetilcolina', 'category', false, false, 'CIE-11'),
('XM32J7', 'Levocabastina', 'category', false, false, 'CIE-11'),
('XM9L65', 'Lodoxamida', 'category', false, false, 'CIE-11'),
('XM1CM1', 'Emedastina', 'category', false, false, 'CIE-11'),
('XM4JE3', 'Alcaftadina', 'category', false, false, 'CIE-11'),
('XM7SY2', 'Cloruro de sodio, hipertónico (oftálmico)', 'category', false, false, 'CIE-11'),
('XM2LQ4', 'Preparación oftálmica de edetato de sodio', 'category', false, false, 'CIE-11'),
('XM3ZG3', 'Preparación oftálmica de ciclosporina', 'category', false, false, 'CIE-11'),
('XM7UH0', 'Preparación oftálmica de nandrolona', 'category', false, false, 'CIE-11'),
('XM3XE4', 'Apraclonidina', 'category', false, false, 'CIE-11'),
('XM2Y24', 'Verteporfina', 'category', false, false, 'CIE-11'),
('XM63C9', 'Ácido espaglúmico', 'category', false, false, 'CIE-11'),
('XM3YZ7', 'Dentífrico', 'category', false, false, 'CIE-11'),
('XM1JW3', 'Cobertura, pulpa viva', 'category', false, false, 'CIE-11'),
('XM0PR1', 'Aceite de eucaliptos', 'category', false, false, 'CIE-11'),
('XM3XP7', 'Aceite de clavo de olor', 'category', false, false, 'CIE-11'),
('XM8PE1', 'Pasta desvitalizante de pulpa', 'category', false, false, 'CIE-11'),
('XM9023', 'Ácido acetilsalicílico tópico', 'category', false, false, 'CIE-11'),
('XM7K59', 'Olaflur', 'category', false, false, 'CIE-11'),
('XM5GY2', 'Monofluorofosfato de sodio tópico', 'category', false, false, 'CIE-11'),
('XM53X2', 'Tetraciclina tópica', 'category', false, false, 'CIE-11'),
('XM2FL0', 'Cloruro de acriflavina', 'category', false, false, 'CIE-11'),
('XM8K50', 'Acrinol', 'category', false, false, 'CIE-11'),
('XM5PD0', 'Acrisorcina', 'category', false, false, 'CIE-11'),
('XM7696', 'Adrenal tópico', 'category', false, false, 'CIE-11'),
('XM9B70', 'Aerosporina tópico', 'category', false, false, 'CIE-11'),
('XM2ET5', 'Alclometasona', 'category', false, false, 'CIE-11'),
('XM3NX2', 'Alconio (bromuro)', 'category', false, false, 'CIE-11'),
('XM7TF6', 'Aletrina', 'category', false, false, 'CIE-11'),
('XM0CC9', 'Solución de acetato de aluminio', 'category', false, false, 'CIE-11'),
('XM6JG7', 'Sulfato de aluminio', 'category', false, false, 'CIE-11'),
('XM18N0', 'Glutaraldehido medicinal', 'category', false, false, 'CIE-11'),
('XM7XA4', 'Triacetato de glicerilo tópico', 'category', false, false, 'CIE-11'),
('XM7Y78', 'Gramicidina', 'category', false, false, 'CIE-11'),
('XM5UQ0', 'Halcinolona', 'category', false, false, 'CIE-11'),
('XM9Q64', 'Haletazol', 'category', false, false, 'CIE-11'),
('XM0C80', 'Haloprogina', 'category', false, false, 'CIE-11'),
('XM3KW0', 'Halquinol', 'category', false, false, 'CIE-11'),
('XM6XH7', 'HCH medicinal', 'category', false, false, 'CIE-11'),
('XM8UW4', 'Hedaquinio', 'category', false, false, 'CIE-11'),
('XM95K6', 'Hexaclorofeno', 'category', false, false, 'CIE-11'),
('XM6RK6', 'Aminoacridina', 'category', false, false, 'CIE-11'),
('XM7RK5', 'Hexamidina', 'category', false, false, 'CIE-11'),
('XM19W1', 'Hidrargafen', 'category', false, false, 'CIE-11'),
('XM0JC1', 'Hidrargiro amino-cloro', 'category', false, false, 'CIE-11'),
('XM4AG2', 'Peróxido de Hidrógeno', 'category', false, false, 'CIE-11'),
('XM6E35', 'Hidroxitolueno medicinal', 'category', false, false, 'CIE-11'),
('XM02H1', 'Hipoclorito', 'category', false, false, 'CIE-11'),
('XM3PT9', 'Ictamol', 'category', false, false, 'CIE-11'),
('XM6BF8', 'Isoconazol', 'category', false, false, 'CIE-11'),
('XM07S0', 'Kwell antiinfeccioso (tópico)', 'category', false, false, 'CIE-11'),
('XM3U48', 'Laurolinium', 'category', false, false, 'CIE-11'),
('XM7CU1', 'Amfotericina B tópica', 'category', false, false, 'CIE-11'),
('XM8C45', 'Lidex', 'category', false, false, 'CIE-11'),
('XM8E58', 'Lindane medicinal', 'category', false, false, 'CIE-11'),
('XM7CM3', 'Locorten', 'category', false, false, 'CIE-11'),
('XM5MZ8', 'Mafenida', 'category', false, false, 'CIE-11'),
('XM6QD7', 'Malation (medicinal)', 'category', false, false, 'CIE-11'),
('XM6L15', 'Medrisona', 'category', false, false, 'CIE-11'),
('XM53R5', 'Aceite de melaleuca alternifolia', 'category', false, false, 'CIE-11'),
('XM35K3', 'Merbromina', 'category', false, false, 'CIE-11'),
('XM7FY5', 'Sales de mercaptobenzotiazol', 'category', false, false, 'CIE-11'),
('XM1B13', 'Mercurocromo', 'category', false, false, 'CIE-11'),
('XM8GN4', 'Bismuto antiinfeccioso, local', 'category', false, false, 'CIE-11'),
('XM2J64', 'Mercurio amoniacal', 'category', false, false, 'CIE-11'),
('XM9Z76', 'Mercurio antiinfeccioso tópico', 'category', false, false, 'CIE-11'),
('XM10V3', 'Cloruro de mercurio (amoniatado)', 'category', false, false, 'CIE-11'),
('XM6Q50', 'Óxido de mercurio, amarillo', 'category', false, false, 'CIE-11'),
('XM9613', 'Mertiolate', 'category', false, false, 'CIE-11'),
('XM2JH4', 'Mesulfeno', 'category', false, false, 'CIE-11'),
('XM2M00', 'Metactesilacetato', 'category', false, false, 'CIE-11'),
('XM0XV0', 'Metil parabeno', 'category', false, false, 'CIE-11'),
('XM1910', 'Metil prednisolona tópica', 'category', false, false, 'CIE-11'),
('XM5HR1', 'Cloruro de metilbencetonio', 'category', false, false, 'CIE-11'),
('XM1JC6', 'Desinfectante antimicótico, local', 'category', false, false, 'CIE-11'),
('XM7C91', 'Metilrosanilina', 'category', false, false, 'CIE-11'),
('XM2793', 'Cloruro de metilrosanilina', 'category', false, false, 'CIE-11'),
('XM0ZY9', 'Micatin', 'category', false, false, 'CIE-11'),
('XM9A06', 'Monistat', 'category', false, false, 'CIE-11'),
('XM23B6', 'Mupirocina', 'category', false, false, 'CIE-11'),
('XM43U9', 'Micifradina tópico', 'category', false, false, 'CIE-11'),
('XM14D6', 'Miralacto', 'category', false, false, 'CIE-11'),
('XM1HX1', 'Naftifina', 'category', false, false, 'CIE-11'),
('XM2BK7', 'Natamicina', 'category', false, false, 'CIE-11'),
('XM7D13', 'Neomicina tópica', 'category', false, false, 'CIE-11'),
('XM44R8', 'Argyrol', 'category', false, false, 'CIE-11'),
('XM51P6', 'Neomicina con bacitracina', 'category', false, false, 'CIE-11'),
('XM6YS1', 'Neosporina tópica', 'category', false, false, 'CIE-11'),
('XM5BH2', 'Nilstat tópica', 'category', false, false, 'CIE-11'),
('XM71W2', 'Nitrofurazona', 'category', false, false, 'CIE-11'),
('XM4T72', 'Nitromersol', 'category', false, false, 'CIE-11'),
('XM2HP9', 'Nitrozona', 'category', false, false, 'CIE-11'),
('XM1102', 'Noxitiolina', 'category', false, false, 'CIE-11'),
('XM70Z6', 'Ácido ortobórico', 'category', false, false, 'CIE-11'),
('XM63S9', 'Oxiconazol', 'category', false, false, 'CIE-11'),
('XM8610', 'Oxicloroseno', 'category', false, false, 'CIE-11'),
('XM7VP9', 'Asiaticoside', 'category', false, false, 'CIE-11'),
('XM7N08', 'Oxilona', 'category', false, false, 'CIE-11'),
('XM9LG4', 'Paraclorofenol (alcanforado)', 'category', false, false, 'CIE-11'),
('XM12F4', 'Acetato de parametasona', 'category', false, false, 'CIE-11'),
('XM0MS1', 'Bálsamo del Perú', 'category', false, false, 'CIE-11'),
('XM70C4', 'Fenoctida', 'category', false, false, 'CIE-11'),
('XM6L76', 'Fenol', 'category', false, false, 'CIE-11'),
('XM4H85', 'Fenotrina', 'category', false, false, 'CIE-11'),
('XM9D74', 'Fenoxietanol', 'category', false, false, 'CIE-11'),
('XM3R68', 'Acetato de fenilmercurio', 'category', false, false, 'CIE-11'),
('XM89P9', 'Borato de fenilmercurio', 'category', false, false, 'CIE-11'),
('XM0295', 'Clortetraciclina tópica', 'category', false, false, 'CIE-11'),
('XM0K18', 'Nitrato de fenilmercurio', 'category', false, false, 'CIE-11'),
('XM3DV8', 'Piketoprofeno', 'category', false, false, 'CIE-11'),
('XM7B69', 'Polimixina B tópica', 'category', false, false, 'CIE-11'),
('XM0J95', 'Polinoxilina', 'category', false, false, 'CIE-11'),
('XM2G74', 'Polioximetileneurea', 'category', false, false, 'CIE-11'),
('XM0XP0', 'Permanganato de potasio medicinal', 'category', false, false, 'CIE-11'),
('XM6YA5', 'Proflavina', 'category', false, false, 'CIE-11'),
('XM35Q1', 'Propamidina', 'category', false, false, 'CIE-11'),
('XM4TA7', 'Propiolactona', 'category', false, false, 'CIE-11'),
('XM3DH9', 'Propión gel', 'category', false, false, 'CIE-11'),
('XM6SG3', 'Ácido Azelaico', 'category', false, false, 'CIE-11'),
('XM77H8', 'Propionato (calcio) (sodio)', 'category', false, false, 'CIE-11'),
('XM03K3', 'Extracto de piretro', 'category', false, false, 'CIE-11'),
('XM2A13', 'Ácido pirogálico', 'category', false, false, 'CIE-11'),
('XM8BE0', 'Pirogalol', 'category', false, false, 'CIE-11'),
('XM97F8', 'Antiinfeccioso de amonio cuaternario', 'category', false, false, 'CIE-11'),
('XM2SR9', 'Ácido retinoico', 'category', false, false, 'CIE-11'),
('XM9773', 'Ácido salicilhidroxámico', 'category', false, false, 'CIE-11'),
('XM5GX7', 'Hipoclorito de sodio medicinal (anti infeccioso) (externo)', 'category', false, false, 'CIE-11'),
('XM5372', 'Hiposulfito de sodio', 'category', false, false, 'CIE-11'),
('XM7Z80', 'Perborato de sodio medicinal', 'category', false, false, 'CIE-11'),
('XM4PL5', 'Bacimicina', 'category', false, false, 'CIE-11'),
('XM7EV2', 'Propionato de sodio', 'category', false, false, 'CIE-11'),
('XM1VV3', 'Sporostacin', 'category', false, false, 'CIE-11'),
('XM38S1', 'Staphisagria o stavesacre (pediculicida)', 'category', false, false, 'CIE-11'),
('XM8HC5', 'Esteroide tópico', 'category', false, false, 'CIE-11'),
('XM2237', 'Sulbentina', 'category', false, false, 'CIE-11'),
('XM2CH0', 'Sulfacetamida', 'category', false, false, 'CIE-11'),
('XM06Y3', 'Sulfiram', 'category', false, false, 'CIE-11'),
('XM4XY4', 'Ungüento de azufre', 'category', false, false, 'CIE-11'),
('XM9ST9', 'Synalar', 'category', false, false, 'CIE-11'),
('XM33Y9', 'Terconazol', 'category', false, false, 'CIE-11'),
('XM00V5', 'Bacitracina zinc', 'category', false, false, 'CIE-11'),
('XM2GG6', 'Tetrametiltiuram medicinal', 'category', false, false, 'CIE-11'),
('XM9ZY9', 'Timerosal', 'category', false, false, 'CIE-11'),
('XM7W47', 'Timol', 'category', false, false, 'CIE-11'),
('XM3C36', 'Ticlaton', 'category', false, false, 'CIE-11'),
('XM9HG1', 'Tioconazol', 'category', false, false, 'CIE-11'),
('XM9SF6', 'Tolciclato', 'category', false, false, 'CIE-11'),
('XM23C3', 'Tolnaftato', 'category', false, false, 'CIE-11'),
('XM6848', 'Triacetín', 'category', false, false, 'CIE-11'),
('XM4873', 'Triamcinolona hexacetónido', 'category', false, false, 'CIE-11'),
('XM5KU0', 'Cloruro de triclobisonio', 'category', false, false, 'CIE-11'),
('XM6Y48', 'Bacitracina zinc con neomicina', 'category', false, false, 'CIE-11'),
('XM74T6', 'Triclocarban', 'category', false, false, 'CIE-11'),
('XM5WW5', 'Triclosán', 'category', false, false, 'CIE-11'),
('XM93J3', 'Tridesilon', 'category', false, false, 'CIE-11'),
('XM84C7', 'Ácido undecenoico', 'category', false, false, 'CIE-11'),
('XM5GQ1', 'Undecoilio', 'category', false, false, 'CIE-11'),
('XM1TP6', 'Ácido uncedilénico (derivados)', 'category', false, false, 'CIE-11'),
('XM81Z1', 'Peróxido de urea', 'category', false, false, 'CIE-11'),
('XM2VU7', 'Valisone', 'category', false, false, 'CIE-11'),
('XM0GR5', 'Vioformo tópico', 'category', false, false, 'CIE-11'),
('XM2B18', 'Antiinfecciosos de zinc', 'category', false, false, 'CIE-11'),
('XM7E88', 'Fucsina básica', 'category', false, false, 'CIE-11'),
('XM6KL1', 'Peróxido de Zinc', 'category', false, false, 'CIE-11'),
('XM8SM1', 'Sulfato de Zinc tópico', 'category', false, false, 'CIE-11'),
('XM5L28', 'Undecilinato de Zinc', 'category', false, false, 'CIE-11'),
('XM71H0', 'Cloponona', 'category', false, false, 'CIE-11'),
('XM0BF3', 'Acriflavina', 'category', false, false, 'CIE-11'),
('XM1KZ4', 'Nifuraldezona', 'category', false, false, 'CIE-11'),
('XM4DT4', 'Yoduro de tibezonio', 'category', false, false, 'CIE-11'),
('XM5U34', 'Eosina', 'category', false, false, 'CIE-11'),
('XM24W5', 'Propanol', 'category', false, false, 'CIE-11'),
('XM5DR7', 'Isopropanol', 'category', false, false, 'CIE-11'),
('XM2ZR2', 'Benisona', 'category', false, false, 'CIE-11'),
('XM2Q40', 'Pecilocina', 'category', false, false, 'CIE-11'),
('XM6UW2', 'Pirrolnitrina', 'category', false, false, 'CIE-11'),
('XM8S89', 'Polihexanida', 'category', false, false, 'CIE-11'),
('XM0SV3', 'Policresuleno', 'category', false, false, 'CIE-11'),
('XM80T0', 'Bifenilol', 'category', false, false, 'CIE-11'),
('XM68P2', 'Cloruro de didecil dimetilamonio', 'category', false, false, 'CIE-11'),
('XM5LX3', 'Mercurio, metálico', 'category', false, false, 'CIE-11'),
('XM53J8', 'Decametoxina', 'category', false, false, 'CIE-11'),
('XM2UH3', 'Euflavina', 'category', false, false, 'CIE-11'),
('XM7KH0', 'Clorito de sodio', 'category', false, false, 'CIE-11'),
('XM2VS1', 'Cloruro de benzalconio', 'category', false, false, 'CIE-11'),
('XM7022', 'Nadifloxacino', 'category', false, false, 'CIE-11'),
('XM8BY6', 'Clindamicina tópica', 'category', false, false, 'CIE-11'),
('XM6AC5', 'Clormidazol', 'category', false, false, 'CIE-11'),
('XM2NB3', 'Sulconazol', 'category', false, false, 'CIE-11'),
('XM8B91', 'Bifonazol', 'category', false, false, 'CIE-11'),
('XM4J78', 'Fenticonazol', 'category', false, false, 'CIE-11'),
('XM0072', 'Omoconazol', 'category', false, false, 'CIE-11'),
('XM9U15', 'Sertaconazol', 'category', false, false, 'CIE-11'),
('XM49Z6', 'Flutrimazol', 'category', false, false, 'CIE-11'),
('XM5XM5', 'Eberconazol', 'category', false, false, 'CIE-11'),
('XM1QH3', 'Cloruro bencetonio', 'category', false, false, 'CIE-11'),
('XM6H72', 'Luliconazol', 'category', false, false, 'CIE-11'),
('XM7CT0', 'Bromoclorosalicilanilida', 'category', false, false, 'CIE-11'),
('XM89W5', 'Tribromometacresol', 'category', false, false, 'CIE-11'),
('XM8JJ2', '2- (4-clorfenoxi) -etanol', 'category', false, false, 'CIE-11'),
('XM67B0', 'Hidroxibenzoato de etilo', 'category', false, false, 'CIE-11'),
('XM6474', 'Amorolfina', 'category', false, false, 'CIE-11'),
('XM2L70', 'Butenafina', 'category', false, false, 'CIE-11'),
('XM3PR6', 'Tavaborole', 'category', false, false, 'CIE-11'),
('XM20T9', 'Efinaconazol', 'category', false, false, 'CIE-11'),
('XM0CH6', 'Imiquimod', 'category', false, false, 'CIE-11'),
('XM7SQ2', 'Ácido benzoico con ácido salicílico', 'category', false, false, 'CIE-11'),
('XM8BH0', 'Inosina', 'category', false, false, 'CIE-11'),
('XM4BA3', 'Docosanol', 'category', false, false, 'CIE-11'),
('XM2CA6', 'Sinecatequinas', 'category', false, false, 'CIE-11'),
('XM0N01', 'Yoduro de mercurio', 'category', false, false, 'CIE-11'),
('XM4796', 'Benzododecinio', 'category', false, false, 'CIE-11'),
('XM2PS8', 'Acetotartrato de aluminio', 'category', false, false, 'CIE-11'),
('XM0P54', 'Bendazac', 'category', false, false, 'CIE-11'),
('XM3J77', 'Bioaletrina', 'category', false, false, 'CIE-11'),
('XM7MQ0', 'Oleinato de cobre', 'category', false, false, 'CIE-11'),
('XM73B3', 'Decametrina', 'category', false, false, 'CIE-11'),
('XM9JZ6', 'Ácido benzoico', 'category', false, false, 'CIE-11'),
('XM4KG9', 'Succinato de dibutilo', 'category', false, false, 'CIE-11'),
('XM84S5', 'Dibutilftalato', 'category', false, false, 'CIE-11'),
('XM1BB3', 'Dimetilcarbamato', 'category', false, false, 'CIE-11'),
('XM74X3', 'Dimetilftalato', 'category', false, false, 'CIE-11'),
('XM4UE1', 'Lactato de etacridina', 'category', false, false, 'CIE-11'),
('XM2Y03', 'Etohexadiol', 'category', false, false, 'CIE-11'),
('XM8XZ0', 'Felbinac', 'category', false, false, 'CIE-11'),
('XM6XJ9', 'Oxiquinolina', 'category', false, false, 'CIE-11'),
('XM4PX0', 'Polisulfuro de potasio', 'category', false, false, 'CIE-11'),
('XM9R96', 'Cuasia', 'category', false, false, 'CIE-11'),
('XM63Y9', 'Cloruro de benzoxonio', 'category', false, false, 'CIE-11'),
('XM0GR6', 'Tirotricina', 'category', false, false, 'CIE-11'),
('XM0FD5', 'Fidaxomicina', 'category', false, false, 'CIE-11'),
('XM1071', 'Nifuroxazida', 'category', false, false, 'CIE-11'),
('XM5BH0', 'Nifurzida', 'category', false, false, 'CIE-11'),
('XM7MF9', 'Balsalazida', 'category', false, false, 'CIE-11'),
('XM0JJ7', 'Dimeticona tópica', 'category', false, false, 'CIE-11'),
('XM6XD8', 'Estreptomicina tópica', 'category', false, false, 'CIE-11'),
('XM4KV4', 'Ácido acético medicinal', 'category', false, false, 'CIE-11'),
('XM7014', 'Terbinafina tópica', 'category', false, false, 'CIE-11'),
('XM0K16', 'Idoxuridina tópica', 'category', false, false, 'CIE-11'),
('XM43M3', 'Peróxido de benzoilo', 'category', false, false, 'CIE-11'),
('XM9X60', 'Penciclovir tópico', 'category', false, false, 'CIE-11'),
('XM3SK7', 'Famciclovir tópico', 'category', false, false, 'CIE-11'),
('XM7A63', 'Ganciclovir tópico', 'category', false, false, 'CIE-11'),
('XM1P27', 'Lomefloxacina tópica', 'category', false, false, 'CIE-11'),
('XM3CL3', 'Levofloxacina tópica', 'category', false, false, 'CIE-11'),
('XM92Q3', 'Gatifloxacina tópica', 'category', false, false, 'CIE-11'),
('XM6VX8', 'Moxifloxacino tópico', 'category', false, false, 'CIE-11'),
('XM1HU5', 'Loxoprofeno', 'category', false, false, 'CIE-11'),
('XM8TB9', 'Abametapir', 'category', false, false, 'CIE-11'),
('XM7QG0', 'Benzoato de bencilo', 'category', false, false, 'CIE-11'),
('XM0GX2', 'Ácido bencil benzoico', 'category', false, false, 'CIE-11'),
('XM9208', 'BHC (medicinal)', 'category', false, false, 'CIE-11'),
('XM7S48', 'Sales de bismuto glicolilarsenato', 'category', false, false, 'CIE-11'),
('XM5RT8', 'Ácido bórico', 'category', false, false, 'CIE-11'),
('XM84D8', 'Bromosalicilcloranitida', 'category', false, false, 'CIE-11'),
('XM0YT9', 'Buclosamida', 'category', false, false, 'CIE-11'),
('XM6862', 'Butoconazole (nitrato)', 'category', false, false, 'CIE-11'),
('XM7VA5', 'Calomel', 'category', false, false, 'CIE-11'),
('XM2AV1', 'Candicidin', 'category', false, false, 'CIE-11'),
('XM2V43', 'Peróxido de carbamida', 'category', false, false, 'CIE-11'),
('XM2ZX1', 'Carbol fucsina', 'category', false, false, 'CIE-11'),
('XM6C04', 'Carfusina', 'category', false, false, 'CIE-11'),
('XM9H69', 'Pintura de Castellani', 'category', false, false, 'CIE-11'),
('XM5ZY9', 'Cepryn', 'category', false, false, 'CIE-11'),
('XM9432', 'Cloruro de cetalconio', 'category', false, false, 'CIE-11'),
('XM1BP8', 'Cloruro de cetexonio', 'category', false, false, 'CIE-11'),
('XM62D0', 'Cetrimida', 'category', false, false, 'CIE-11'),
('XM6ZW9', 'Bromuro de cetrimonio', 'category', false, false, 'CIE-11'),
('XM94W4', 'Cloruro de cetilpiridinio', 'category', false, false, 'CIE-11'),
('XM7CX5', 'Camomil', 'category', false, false, 'CIE-11'),
('XM8HU1', 'Cloramina T', 'category', false, false, 'CIE-11'),
('XM72P5', 'Cloranfenicol tópico', 'category', false, false, 'CIE-11'),
('XM7DZ3', 'Clorhexidina', 'category', false, false, 'CIE-11'),
('XM2ZT2', 'Clorhidroxiquinolina', 'category', false, false, 'CIE-11'),
('XM5D99', 'Lima clorada y solución de ácido bórico', 'category', false, false, 'CIE-11'),
('XM0HL8', 'Solución de soda clorada', 'category', false, false, 'CIE-11'),
('XM8FE7', 'Clorocresol', 'category', false, false, 'CIE-11'),
('XM3XC5', 'Cloroxilenol', 'category', false, false, 'CIE-11'),
('XM93C6', 'Clorfenesina tópica (antifúngica)', 'category', false, false, 'CIE-11'),
('XM2CN0', 'Clorquinol', 'category', false, false, 'CIE-11'),
('XM0852', 'Ciclopirox (olamina)', 'category', false, false, 'CIE-11'),
('XM6MJ1', 'Clobetasona', 'category', false, false, 'CIE-11'),
('XM2WP5', 'Clodantoina', 'category', false, false, 'CIE-11'),
('XM8TG2', 'Clofenotano', 'category', false, false, 'CIE-11'),
('XM8W85', 'Clotrimazol', 'category', false, false, 'CIE-11'),
('XM6BT6', 'Cloxiquina', 'category', false, false, 'CIE-11'),
('XM4M83', 'Gluconato de cobre', 'category', false, false, 'CIE-11'),
('XM42L5', 'Creosol (compuesto)', 'category', false, false, 'CIE-11'),
('XM35M5', 'Creosota (alquitrán de hulla) (madera de haya)', 'category', false, false, 'CIE-11'),
('XM7ZK1', 'Cresol (es)', 'category', false, false, 'CIE-11'),
('XM0WM0', 'Crema y solución de jabón', 'category', false, false, 'CIE-11'),
('XM4YB3', 'Acetato de cresilo', 'category', false, false, 'CIE-11'),
('XM0348', 'Ácido cresílico', 'category', false, false, 'CIE-11'),
('XM3726', 'Crotamitón', 'category', false, false, 'CIE-11'),
('XM7YY8', 'Solución de Dakin', 'category', false, false, 'CIE-11'),
('XM8CF0', 'Cloruro de decualinio', 'category', false, false, 'CIE-11'),
('XM6LZ1', 'Desonida', 'category', false, false, 'CIE-11'),
('XM0PQ7', 'Dettol', 'category', false, false, 'CIE-11'),
('XM1RR7', 'Dibromopropamidina isetionato', 'category', false, false, 'CIE-11'),
('XM0UE0', 'Dibrompropamidina', 'category', false, false, 'CIE-11'),
('XM06U7', 'Dicofan', 'category', false, false, 'CIE-11'),
('XM2355', 'Dietiltoluamida', 'category', false, false, 'CIE-11'),
('XM4A13', 'Dimazol', 'category', false, false, 'CIE-11'),
('XM42D3', 'Dixantogeno', 'category', false, false, 'CIE-11'),
('XM3JL3', 'Dodicina', 'category', false, false, 'CIE-11'),
('XM7YF5', 'Cloruro de dofamio', 'category', false, false, 'CIE-11'),
('XM3TY6', 'Bromuro de domifeno', 'category', false, false, 'CIE-11'),
('XM5XH3', 'Econazol', 'category', false, false, 'CIE-11'),
('XM8E88', 'Eritromicina tópica', 'category', false, false, 'CIE-11'),
('XM5QE6', 'Etacridina', 'category', false, false, 'CIE-11'),
('XM09B1', 'Óxido de etileno medicinal', 'category', false, false, 'CIE-11'),
('XM91H3', 'Eurax', 'category', false, false, 'CIE-11'),
('XM2258', 'Exalamida', 'category', false, false, 'CIE-11'),
('XM9K22', 'Fenticlor', 'category', false, false, 'CIE-11'),
('XM2E99', 'Fluocinonida', 'category', false, false, 'CIE-11'),
('XM67C1', 'Flurobat', 'category', false, false, 'CIE-11'),
('XM6AZ9', 'Cloruro de furazolio', 'category', false, false, 'CIE-11'),
('XM5JA4', 'Gamma benceno hexacloruro (medicinal)', 'category', false, false, 'CIE-11'),
('XM0XR4', 'Gentamicina tópica', 'category', false, false, 'CIE-11'),
('XM3P38', 'Acetato de aluminio', 'category', false, false, 'CIE-11'),
('XM7FE1', 'Cloruro de aluminio', 'category', false, false, 'CIE-11'),
('XM2D21', 'Diacetato de aluminio', 'category', false, false, 'CIE-11'),
('XM2399', 'Subacetato de aluminio', 'category', false, false, 'CIE-11'),
('XM38V9', 'Preparación antihemorroidal', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
