-- CIE11 Import Part 39
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XN9X8', 'Staphylococcus schleiferi', 'category', false, false, 'CIE-11'),
('XN2HN', 'Staphylococcus sciuri', 'category', false, false, 'CIE-11'),
('XN7RE', 'Staphylococcus simulans', 'category', false, false, 'CIE-11'),
('XN4C9', 'Staphylococcus warneri', 'category', false, false, 'CIE-11'),
('XN7TQ', 'Staphylococcus xylosus', 'category', false, false, 'CIE-11'),
('XN567', 'Staphylococcus hominis', 'category', false, false, 'CIE-11'),
('XN3NM', 'Streptococcus', 'category', false, false, 'CIE-11'),
('XN1V3', 'Streptococcus alfa-hemolítico', 'category', false, false, 'CIE-11'),
('XN3PW', 'Streptococcus pneumoniae', 'category', false, false, 'CIE-11'),
('XN9LA', 'Streptococcus viridans', 'category', false, false, 'CIE-11'),
('XN1AF', 'Streptococcus beta-hemolítico', 'category', false, false, 'CIE-11'),
('XN2NS', 'Streptococcus gamma-hemolítico', 'category', false, false, 'CIE-11'),
('XN6LP', 'Streptococcus, grupo A', 'category', false, false, 'CIE-11'),
('XN7YG', 'Streptococcus pyogenes', 'category', false, false, 'CIE-11'),
('XN2M1', 'Streptococcus, grupo B', 'category', false, false, 'CIE-11'),
('XN0KC', 'Streptococcus agalactiae', 'category', false, false, 'CIE-11'),
('XN518', 'Streptococcus, grupo C', 'category', false, false, 'CIE-11'),
('XN0TY', 'Streptococcus zooepidemicus', 'category', false, false, 'CIE-11'),
('XN5KC', 'Streptococcus, grupo D', 'category', false, false, 'CIE-11'),
('XN6KJ', 'Streptococcus bovis', 'category', false, false, 'CIE-11'),
('XN625', 'Streptococcus equinus', 'category', false, false, 'CIE-11'),
('XN8BJ', 'Streptococcus, grupo E', 'category', false, false, 'CIE-11'),
('XN6BB', 'Streptococcus, grupo F', 'category', false, false, 'CIE-11'),
('XN84N', 'Streptococcus, grupo G', 'category', false, false, 'CIE-11'),
('XN8UN', 'Streptococcus dysgalactiae', 'category', false, false, 'CIE-11'),
('XN40Y', 'Streptococcus, grupo H', 'category', false, false, 'CIE-11'),
('XN39R', 'Streptococcus anginosus', 'category', false, false, 'CIE-11'),
('XN3L7', 'Streptococcus canis', 'category', false, false, 'CIE-11'),
('XN0FR', 'Streptococcus constellatus', 'category', false, false, 'CIE-11'),
('XN4PA', 'Streptococcus iniae', 'category', false, false, 'CIE-11'),
('XN67P', 'Streptococcus intermedius', 'category', false, false, 'CIE-11'),
('XN5BP', 'Streptococcus mitis', 'category', false, false, 'CIE-11'),
('XN2RH', 'Streptococcus mutans', 'category', false, false, 'CIE-11'),
('XN4B2', 'Streptococcus oralis', 'category', false, false, 'CIE-11'),
('XN18T', 'Streptococcus parasanguinis', 'category', false, false, 'CIE-11'),
('XN58W', 'Streptococcus peroris', 'category', false, false, 'CIE-11'),
('XN6KE', 'Streptococcus pseudopneumoniae', 'category', false, false, 'CIE-11'),
('XN5DB', 'Streptococcus ratti', 'category', false, false, 'CIE-11'),
('XN3BQ', 'Streptococcus salivarius', 'category', false, false, 'CIE-11'),
('XN9FP', 'Streptococcus sanguinis', 'category', false, false, 'CIE-11'),
('XN0XM', 'Streptococcus sobrinus', 'category', false, false, 'CIE-11'),
('XN5SE', 'Streptococcus suis', 'category', false, false, 'CIE-11'),
('XN4LM', 'Streptococcus thermophilus', 'category', false, false, 'CIE-11'),
('XN1TV', 'Streptococcus uberis', 'category', false, false, 'CIE-11'),
('XN0Z2', 'Streptococcus vestibularis', 'category', false, false, 'CIE-11'),
('XN7PP', 'Tropheryma', 'category', false, false, 'CIE-11'),
('XN5P4', 'Tropheryma whipplei', 'category', false, false, 'CIE-11'),
('XN0SE', 'Clostridioides difficile', 'category', false, false, 'CIE-11'),
('XN87X', 'Bacteria, ni gramnegativa ni grampositiva', 'category', false, false, 'CIE-11'),
('XN2DX', 'Borrelia', 'category', false, false, 'CIE-11'),
('XN7GL', 'Borrelia afzelii', 'category', false, false, 'CIE-11'),
('XN13C', 'Borrelia burgdorferi', 'category', false, false, 'CIE-11'),
('XN4VZ', 'Borrelia garinii', 'category', false, false, 'CIE-11'),
('XN3PD', 'Borrelia hermsii', 'category', false, false, 'CIE-11'),
('XN2P3', 'Borrelia miyamotoi', 'category', false, false, 'CIE-11'),
('XN6VH', 'Borrelia parkeri', 'category', false, false, 'CIE-11'),
('XN5R4', 'Borrelia recurrentis', 'category', false, false, 'CIE-11'),
('XN140', 'Borrelia vincentii', 'category', false, false, 'CIE-11'),
('XN2NR', 'Mycobacterium', 'category', false, false, 'CIE-11'),
('XN6YB', 'Mycobacterium africanum', 'category', false, false, 'CIE-11'),
('XN8AB', 'Mycobacterium bovis', 'category', false, false, 'CIE-11'),
('XN8N3', 'Mycobacterium canettii', 'category', false, false, 'CIE-11'),
('XN4MR', 'Mycobacterium caprae', 'category', false, false, 'CIE-11'),
('XN9H9', 'Mycobacterium colombiense', 'category', false, false, 'CIE-11'),
('XN8FC', 'Mycobacterium indicus pranii', 'category', false, false, 'CIE-11'),
('XN5TS', 'Mycobacterium leprae', 'category', false, false, 'CIE-11'),
('XN3T2', 'Mycobacterium microti', 'category', false, false, 'CIE-11'),
('XN7H2', 'Mycobacterium pinnipedii', 'category', false, false, 'CIE-11'),
('XN1N2', 'Mycobacterium tuberculosis', 'category', false, false, 'CIE-11'),
('XN96Q', 'Mycobacterium no tuberculosa', 'category', false, false, 'CIE-11'),
('XN3L9', 'Mycobacterium kansasii', 'category', false, false, 'CIE-11'),
('XN5C1', 'Mycobacterium malmoense', 'category', false, false, 'CIE-11'),
('XN53D', 'Mycobacterium xenopi', 'category', false, false, 'CIE-11'),
('XN6PL', 'Mycobacterium asiaticum', 'category', false, false, 'CIE-11'),
('XN4MW', 'Mycobacterium simiae', 'category', false, false, 'CIE-11'),
('XN975', 'Mycobacterium szulgai', 'category', false, false, 'CIE-11'),
('XN74T', 'Mycobacterium scrofulaceum', 'category', false, false, 'CIE-11'),
('XN7YR', 'Mycobacterium haemophilum', 'category', false, false, 'CIE-11'),
('XN8ZX', 'Mycobacterium fortuitum', 'category', false, false, 'CIE-11'),
('XN8RB', 'Mycobacterium marinum', 'category', false, false, 'CIE-11'),
('XN9M0', 'Mycobacterium ulcerans', 'category', false, false, 'CIE-11'),
('XN3D3', 'Mycobacterium chelonei', 'category', false, false, 'CIE-11'),
('XN97H', 'Mycobacterium avium complex', 'category', false, false, 'CIE-11'),
('XN5LZ', 'Mycobacterium avium', 'category', false, false, 'CIE-11'),
('XN8FF', 'Mycobacterium avium hominissuis', 'category', false, false, 'CIE-11'),
('XN5NW', 'Mycobacterium avium paratuberculosis', 'category', false, false, 'CIE-11'),
('XN145', 'Mycobacterium avium silvaticum', 'category', false, false, 'CIE-11'),
('XN3ZQ', 'Mycobacterium intracellulare', 'category', false, false, 'CIE-11'),
('XN077', 'Mycobacterium chimaera', 'category', false, false, 'CIE-11'),
('XN4TQ', 'Mycobacterium abscessus complex', 'category', false, false, 'CIE-11'),
('XN7V4', 'Mycobacterium abscessus subsp. abscessus', 'category', false, false, 'CIE-11'),
('XN5SW', 'Mycobacterium abscessus subsp. massiliense', 'category', false, false, 'CIE-11'),
('XN017', 'Mycobacterium abscessus subsp. bolletii', 'category', false, false, 'CIE-11'),
('XN44M', 'Mycobacterium chelonae', 'category', false, false, 'CIE-11'),
('XN3BH', 'Virus', 'category', false, false, 'CIE-11'),
('XN000', 'Adenovirus', 'category', false, false, 'CIE-11'),
('XN0R0', 'Atadenovirus', 'category', false, false, 'CIE-11'),
('XN05K', 'Aviadenovirus', 'category', false, false, 'CIE-11'),
('XN728', 'Ichtadenovirus', 'category', false, false, 'CIE-11'),
('XN93P', 'Mastadenovirus', 'category', false, false, 'CIE-11'),
('XN13L', 'Siadenovirus', 'category', false, false, 'CIE-11'),
('XN6ME', 'Alfavirus', 'category', false, false, 'CIE-11'),
('XN0SK', 'Virus Aura', 'category', false, false, 'CIE-11'),
('XN434', 'Virus Babanki', 'category', false, false, 'CIE-11'),
('XN5KQ', 'Virus de la selva de Barmah', 'category', false, false, 'CIE-11'),
('XN6XS', 'Virus Bebaru', 'category', false, false, 'CIE-11'),
('XN0UF', 'Virus Cabassou', 'category', false, false, 'CIE-11'),
('XN4ZB', 'Virus del chikungunya', 'category', false, false, 'CIE-11'),
('XN78T', 'Virus de la encefalitis equina del este', 'category', false, false, 'CIE-11'),
('XN26A', 'Virus de los Everglades', 'category', false, false, 'CIE-11'),
('XN87D', 'Virus Kyzylagach', 'category', false, false, 'CIE-11'),
('XN5ZC', 'Virus Mayaro', 'category', false, false, 'CIE-11'),
('XN1VS', 'Virus de Middelburg', 'category', false, false, 'CIE-11'),
('XN34P', 'Virus Mosso das Pedras', 'category', false, false, 'CIE-11'),
('XN7PD', 'Virus Mucambo', 'category', false, false, 'CIE-11'),
('XN0H9', 'Virus Ndumu', 'category', false, false, 'CIE-11'),
('XN9WS', 'Virus Ockelbo', 'category', false, false, 'CIE-11'),
('XN6AD', 'Virus o’nyong nyong', 'category', false, false, 'CIE-11'),
('XN240', 'Virus Paramana', 'category', false, false, 'CIE-11'),
('XN3YZ', 'Virus Pixuna', 'category', false, false, 'CIE-11'),
('XN79Q', 'Virus Río Negro', 'category', false, false, 'CIE-11'),
('XN49A', 'Virus del Río Ross', 'category', false, false, 'CIE-11'),
('XN4D3', 'Virus de la enfermedad pancreática del salmón', 'category', false, false, 'CIE-11'),
('XN3D4', 'Virus de la selva de Semliki', 'category', false, false, 'CIE-11'),
('XN0D6', 'Virus Sindbis', 'category', false, false, 'CIE-11'),
('XN132', 'Virus de la enfermedad del sueño', 'category', false, false, 'CIE-11'),
('XN5MK', 'Virus del elefante marino del sur', 'category', false, false, 'CIE-11'),
('XN4ER', 'Virus Tonate', 'category', false, false, 'CIE-11'),
('XN2B3', 'Virus Trocara', 'category', false, false, 'CIE-11'),
('XN445', 'Virus de la encefalitis equina venezolana', 'category', false, false, 'CIE-11'),
('XN8PC', 'Virus Whataroa', 'category', false, false, 'CIE-11'),
('XN2CK', 'Virus de la encefalitis equina del este', 'category', false, false, 'CIE-11'),
('XN1BE', 'Arbovirus', 'category', false, false, 'CIE-11'),
('XN5VQ', 'Virus La Crosse', 'category', false, false, 'CIE-11'),
('XN8AC', 'Arenavirus', 'category', false, false, 'CIE-11'),
('XN2WG', 'Virus Chapare', 'category', false, false, 'CIE-11'),
('XN56K', 'Virus Guaranito', 'category', false, false, 'CIE-11'),
('XN2ZL', 'Virus Junín', 'category', false, false, 'CIE-11'),
('XN0CU', 'Virus Lassa', 'category', false, false, 'CIE-11'),
('XN77P', 'Virus Lujo', 'category', false, false, 'CIE-11'),
('XN4ZL', 'Virus de la coriomeningitis linfocitica', 'category', false, false, 'CIE-11'),
('XN45B', 'Virus Machupo', 'category', false, false, 'CIE-11'),
('XN55S', 'Virus Sabiá', 'category', false, false, 'CIE-11'),
('XN5VM', 'Bornavirus', 'category', false, false, 'CIE-11'),
('XN395', 'Virus de la enfermedad de Borna 1', 'category', false, false, 'CIE-11'),
('XN125', 'Bornavirus de ardilla variegata 1', 'category', false, false, 'CIE-11'),
('XN7S5', 'Bunyavirus', 'category', false, false, 'CIE-11'),
('XN9UC', 'Virus Amur', 'category', false, false, 'CIE-11'),
('XN17V', 'Virus de la fiebre hemorragia Crimea-Congo', 'category', false, false, 'CIE-11'),
('XN16H', 'Virus Dobrava', 'category', false, false, 'CIE-11'),
('XN2QZ', 'Virus gōu', 'category', false, false, 'CIE-11'),
('XN3GW', 'Virus Hantaan', 'category', false, false, 'CIE-11'),
('XN8UR', 'Virus Kurkino', 'category', false, false, 'CIE-11'),
('XN8AF', 'Virus Muju', 'category', false, false, 'CIE-11'),
('XN4S8', 'Orthobunyavirus', 'category', false, false, 'CIE-11'),
('XN09U', 'Cristoli virus', 'category', false, false, 'CIE-11'),
('XN4U2', 'Oropouche orthobunyavirus', 'category', false, false, 'CIE-11'),
('XN28L', 'Virus Puumala', 'category', false, false, 'CIE-11'),
('XN9PD', 'Virus Saaremaa', 'category', false, false, 'CIE-11'),
('XN3PV', 'Virus Seoul', 'category', false, false, 'CIE-11'),
('XN95V', 'Virus Sochi', 'category', false, false, 'CIE-11'),
('XN0E0', 'Virus Soochong', 'category', false, false, 'CIE-11'),
('XN9G5', 'Virus Tula', 'category', false, false, 'CIE-11'),
('XN2VY', 'Virus Anajatuba', 'category', false, false, 'CIE-11'),
('XN4AP', 'Virus Andes', 'category', false, false, 'CIE-11'),
('XN2C8', 'Virus Araucaria', 'category', false, false, 'CIE-11'),
('XN2WJ', 'virus Bayou', 'category', false, false, 'CIE-11'),
('XN0A0', 'Virus Bermejo', 'category', false, false, 'CIE-11'),
('XN66E', 'Virus Black Creek Canal', 'category', false, false, 'CIE-11'),
('XN8LW', 'Virus Blue River', 'category', false, false, 'CIE-11'),
('XN18Y', 'Virus Castelo dos Sonhos', 'category', false, false, 'CIE-11'),
('XN6XF', 'Virus El Moro Canyon', 'category', false, false, 'CIE-11'),
('XN8G9', 'Virus Juquitiba', 'category', false, false, 'CIE-11'),
('XN6P0', 'Virus Laguna Negra', 'category', false, false, 'CIE-11'),
('XN2CJ', 'Virus Lechiguanas', 'category', false, false, 'CIE-11'),
('XN2BW', 'Virus Maciel', 'category', false, false, 'CIE-11'),
('XN3WK', 'Virus Monogahela', 'category', false, false, 'CIE-11'),
('XN5SF', 'Virus Muleshoe', 'category', false, false, 'CIE-11'),
('XN9VX', 'Virus Nueva York', 'category', false, false, 'CIE-11'),
('XN9BY', 'Virus Orán', 'category', false, false, 'CIE-11'),
('XN5JV', 'Virus Paranoá', 'category', false, false, 'CIE-11'),
('XN65X', 'Virus Pergamino', 'category', false, false, 'CIE-11'),
('XN2VC', 'Virus Río Mamoré', 'category', false, false, 'CIE-11'),
('XN7R1', 'Virus sin nombre', 'category', false, false, 'CIE-11'),
('XN057', 'Virus Tunaris', 'category', false, false, 'CIE-11'),
('XN8AQ', 'Virus Araraquara', 'category', false, false, 'CIE-11'),
('XN5VU', 'Phlebovirus', 'category', false, false, 'CIE-11'),
('XN2YW', 'Punta Toro virus', 'category', false, false, 'CIE-11'),
('XN7AS', 'Flebovirus de la fiebre del Valle del Rift', 'category', false, false, 'CIE-11'),
('XN72W', 'FFVS - [fiebre del flebótomo virus siciliano]', 'category', false, false, 'CIE-11'),
('XN7FG', 'Flebovirus de Nápoles', 'category', false, false, 'CIE-11'),
('XN3V9', 'Flebovirus Toscana', 'category', false, false, 'CIE-11'),
('XN3BT', 'Dabie bandavirus', 'category', false, false, 'CIE-11'),
('XN9RK', 'Calicivirus', 'category', false, false, 'CIE-11'),
('XN4EB', 'Lagovirus', 'category', false, false, 'CIE-11'),
('XN8L1', 'Nebovirus', 'category', false, false, 'CIE-11'),
('XN3Y2', 'Norovirus', 'category', false, false, 'CIE-11'),
('XN9EH', 'Sapovirus', 'category', false, false, 'CIE-11'),
('XN0R6', 'Vesivirus', 'category', false, false, 'CIE-11'),
('XN83D', 'Coronavirus', 'category', false, false, 'CIE-11'),
('XN0UA', 'Coronavirus humano 229E', 'category', false, false, 'CIE-11'),
('XN9KN', 'Coronavirus humano HKU1', 'category', false, false, 'CIE-11'),
('XN7CX', 'Coronavirus humano OCA43', 'category', false, false, 'CIE-11'),
('XN3BD', 'Coronavirus del síndrome respiratorio del Medio Este', 'category', false, false, 'CIE-11'),
('XN5V7', 'Coronavirus HKU5 del murciélago pipistrellus', 'category', false, false, 'CIE-11'),
('XN1N9', 'Coronavirus HKU9 murciélago Rousettus', 'category', false, false, 'CIE-11'),
('XN1V8', 'Coronavirus del síndrome respiratorio agudo severo', 'category', false, false, 'CIE-11'),
('XN1GJ', 'Coronavirus HKU4 del murciélago Tylonycteris', 'category', false, false, 'CIE-11'),
('XN109', 'SARS-CoV-2', 'category', false, false, 'CIE-11'),
('XN0HL', 'SARS-CoV-2 Alfa', 'category', false, false, 'CIE-11'),
('XN4Q7', 'SARS-CoV-2 Beta', 'category', false, false, 'CIE-11'),
('XN5BQ', 'SARS-CoV-2 Gamma', 'category', false, false, 'CIE-11'),
('XN8V6', 'SARS-CoV-2 Delta', 'category', false, false, 'CIE-11'),
('XN1GK', 'SARS-CoV-2 Epsilon', 'category', false, false, 'CIE-11'),
('XN3ZE', 'SARS-CoV-2 Zeta', 'category', false, false, 'CIE-11'),
('XN2V4', 'SARS-CoV-2 Eta', 'category', false, false, 'CIE-11'),
('XN4Q1', 'SARS-CoV-2 Theta', 'category', false, false, 'CIE-11'),
('XN3UD', 'SARS-CoV-2 Iota', 'category', false, false, 'CIE-11'),
('XN9LB', 'SARS-CoV-2 Kappa', 'category', false, false, 'CIE-11'),
('XN6AM', 'SARS-CoV-2 Lambda', 'category', false, false, 'CIE-11'),
('XN39J', 'SARS-CoV-2 Mu', 'category', false, false, 'CIE-11'),
('XN161', 'SARS-CoV-2 Omicron', 'category', false, false, 'CIE-11'),
('XN8Z4', 'BA.5', 'category', false, false, 'CIE-11'),
('XN4UD', 'BQ.1', 'category', false, false, 'CIE-11'),
('XN51Y', 'XBB', 'category', false, false, 'CIE-11'),
('XN72A', 'XBB.1.5', 'category', false, false, 'CIE-11'),
('XN201', 'XBB.1.16', 'category', false, false, 'CIE-11'),
('XN8RW', 'EG.5', 'category', false, false, 'CIE-11'),
('XN031', 'BA2.86', 'category', false, false, 'CIE-11'),
('XN3QV', 'BA.1', 'category', false, false, 'CIE-11'),
('XN53K', 'BA.2', 'category', false, false, 'CIE-11'),
('XN2P0', 'Enterovirus', 'category', false, false, 'CIE-11'),
('XN3MC', 'Virus Coxsackie', 'category', false, false, 'CIE-11'),
('XN2TU', 'Virus Echo', 'category', false, false, 'CIE-11'),
('XN3M0', 'Poliovirus', 'category', false, false, 'CIE-11'),
('XN6KZ', 'Poliovirus salvaje tipo 1', 'category', false, false, 'CIE-11'),
('XN9CF', 'Poliovirus salvaje tipo 2', 'category', false, false, 'CIE-11'),
('XN97R', 'Poliovirus salvaje tipo 3', 'category', false, false, 'CIE-11'),
('XN2T1', 'Poliovirus circulante de tipo 1 de origen vacunal', 'category', false, false, 'CIE-11'),
('XN1XN', 'Poliovirus circulante de tipo 2 de origen vacunal', 'category', false, false, 'CIE-11'),
('XN7UU', 'Poliovirus circulante de tipo 3 de origen vacunal', 'category', false, false, 'CIE-11'),
('XN19Z', 'Rhinovirus', 'category', false, false, 'CIE-11'),
('XN6R5', 'Filovirus', 'category', false, false, 'CIE-11'),
('XN2LW', 'Genus Ebolavirus', 'category', false, false, 'CIE-11'),
('XN1EN', 'Ebolavirus', 'category', false, false, 'CIE-11'),
('XN8JT', 'Virus Bundibugyo', 'category', false, false, 'CIE-11'),
('XN9QG', 'Virus Reston', 'category', false, false, 'CIE-11'),
('XN13U', 'Virus Sudán', 'category', false, false, 'CIE-11'),
('XN8TT', 'Virus de la selva de Tai', 'category', false, false, 'CIE-11'),
('XN12Y', 'Bombali virus', 'category', false, false, 'CIE-11'),
('XN4XZ', 'Genus Marburgvirus', 'category', false, false, 'CIE-11'),
('XN3F2', 'Virus de Marburg', 'category', false, false, 'CIE-11'),
('XN5M2', 'Virus Ravn', 'category', false, false, 'CIE-11'),
('XN0AC', 'Flavivirus', 'category', false, false, 'CIE-11'),
('XN4CA', 'Virus del dengue', 'category', false, false, 'CIE-11'),
('XN22Z', 'Virus del Dengue 1', 'category', false, false, 'CIE-11'),
('XN4RL', 'Virus del Dengue 2', 'category', false, false, 'CIE-11'),
('XN9XQ', 'Virus del Dengue 3', 'category', false, false, 'CIE-11'),
('XN2EQ', 'Virus del Dengue 4', 'category', false, false, 'CIE-11'),
('XN9ZK', 'Virus de la encefalitis japonesa', 'category', false, false, 'CIE-11'),
('XN5QW', 'Virus de la encefalitis de Saint Louis', 'category', false, false, 'CIE-11'),
('XN0L1', 'Virus de la encefalitis por garrapatas', 'category', false, false, 'CIE-11'),
('XN1MT', 'Virus de la encefalitis transmitida por garrapatas, subtipo europeo', 'category', false, false, 'CIE-11'),
('XN8WB', 'Virus de la encefalitis transmitida por garrapatas, subtipo del Lejano Oriente', 'category', false, false, 'CIE-11'),
('XN4LG', 'Virus de la encefalitis transmitida por garrapatas, subtipo siberiano', 'category', false, false, 'CIE-11'),
('XN4E1', 'Virus del Nilo Occidental', 'category', false, false, 'CIE-11'),
('XN9S3', 'Virus de la fiebre amarilla', 'category', false, false, 'CIE-11'),
('XN1H2', 'Virus de Zika', 'category', false, false, 'CIE-11'),
('XN7C2', 'Virus Rocio', 'category', false, false, 'CIE-11'),
('XN7W2', 'Virus de la fiebre hemorrágica de Alkhurma', 'category', false, false, 'CIE-11'),
('XN2JR', 'Virus de la enfermedad del bosque de Kyasanur', 'category', false, false, 'CIE-11'),
('XN41M', 'Virus de la hepatitis', 'category', false, false, 'CIE-11'),
('XN5XD', 'Virus GB-C', 'category', false, false, 'CIE-11'),
('XN40D', 'Virus de la hepatitis A', 'category', false, false, 'CIE-11'),
('XN0GA', 'Virus de la hepatitis B', 'category', false, false, 'CIE-11'),
('XN1EZ', 'Virus de la hepatitis C', 'category', false, false, 'CIE-11'),
('XN99N', 'Virus de la hepatitis D', 'category', false, false, 'CIE-11'),
('XN7TG', 'Virus de la hepatitis E', 'category', false, false, 'CIE-11'),
('XN6BW', 'Virus de la hepatitis F', 'category', false, false, 'CIE-11'),
('XN7V1', 'Herpesvirus humano', 'category', false, false, 'CIE-11'),
('XN6DH', 'Ictalurvirus', 'category', false, false, 'CIE-11'),
('XN9QL', 'Virus de la Pityriasis Rosea', 'category', false, false, 'CIE-11'),
('XN465', 'Alphaherpesvirinae', 'category', false, false, 'CIE-11'),
('XN42C', 'Mardivirus', 'category', false, false, 'CIE-11'),
('XN41T', 'Virus del herpes simple 1', 'category', false, false, 'CIE-11'),
('XN5V1', 'Virus del herpes simple 2', 'category', false, false, 'CIE-11'),
('XN0TA', 'Virus de la varicela-zóster', 'category', false, false, 'CIE-11'),
('XN4P4', 'Iltovirus', 'category', false, false, 'CIE-11'),
('XN8TA', 'Betaherpesvirinae', 'category', false, false, 'CIE-11'),
('XN3SQ', 'Citomegalovirus', 'category', false, false, 'CIE-11'),
('XN5FN', 'Muromegalovirus', 'category', false, false, 'CIE-11'),
('XN1GF', 'Roseolavirus', 'category', false, false, 'CIE-11'),
('XN9NM', 'Roseolavirus A', 'category', false, false, 'CIE-11'),
('XN8AM', 'Roseolavirus B', 'category', false, false, 'CIE-11'),
('XN2VN', 'Gammaherpesvirinae', 'category', false, false, 'CIE-11'),
('XN0R2', 'Virus de Epstein-Barr', 'category', false, false, 'CIE-11'),
('XN7NE', 'Rhadinovirus', 'category', false, false, 'CIE-11'),
('XN487', 'Virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('XN8LD', 'Virus de la inmunodeficiencia humana tipo 1', 'category', false, false, 'CIE-11'),
('XN71W', 'Virus de la inmunodeficiencia humana tipo 2', 'category', false, false, 'CIE-11'),
('XN8JY', 'Papilomavirus humano', 'category', false, false, 'CIE-11'),
('XN2KP', 'Papilomavirus humano 45', 'category', false, false, 'CIE-11'),
('XN6LA', 'Papilomavirus humano 1', 'category', false, false, 'CIE-11'),
('XN2FC', 'Papilomavirus humano 2', 'category', false, false, 'CIE-11'),
('XN7DE', 'Papilomavirus humano 6', 'category', false, false, 'CIE-11'),
('XN7T9', 'Papilomavirus humano 11', 'category', false, false, 'CIE-11'),
('XN2NK', 'Papilomavirus humano 16', 'category', false, false, 'CIE-11'),
('XN97Y', 'Papilomavirus humano 18', 'category', false, false, 'CIE-11'),
('XN3HA', 'Papilomavirus humano 31', 'category', false, false, 'CIE-11'),
('XN1WJ', 'Virus linfotrópico-células T humano', 'category', false, false, 'CIE-11'),
('XN5SG', 'Virus de la influenza', 'category', false, false, 'CIE-11'),
('XN8WJ', 'Virus de la Influenza A', 'category', false, false, 'CIE-11'),
('XN297', 'Virus de la Influenza A H1N1', 'category', false, false, 'CIE-11'),
('XN4TT', 'Virus de la Influenza A H5N1', 'category', false, false, 'CIE-11'),
('XN7JR', 'Virus de la Influenza A H5N6', 'category', false, false, 'CIE-11'),
('XN35G', 'Virus de la Influenza A H7N9', 'category', false, false, 'CIE-11'),
('XN2J2', 'Virus de la gripe A H1', 'category', false, false, 'CIE-11'),
('XN9Z9', 'Virus de la influenza A H1N1v', 'category', false, false, 'CIE-11'),
('XN3VG', 'Virus de la influenza A H1N1v', 'category', false, false, 'CIE-11'),
('XN9SG', 'Virus influenza A H1N1 pdm2009', 'category', false, false, 'CIE-11'),
('XN3UJ', 'Influenza A H1pdm09N2 2:6 virus de influenza reordenado', 'category', false, false, 'CIE-11'),
('XN02Z', 'Virus de la influenza porcina A H1N1', 'category', false, false, 'CIE-11'),
('XN16M', 'Variante de influenza A H1N2', 'category', false, false, 'CIE-11'),
('XN79W', 'Virus influenza A H2N2', 'category', false, false, 'CIE-11'),
('XN8WA', 'Virus influenza A H3', 'category', false, false, 'CIE-11'),
('XN6WE', 'Virus influenza A H3N2', 'category', false, false, 'CIE-11'),
('XN476', 'Virus de la influenza porcina A H3N2', 'category', false, false, 'CIE-11'),
('XN3UU', 'Virus Influenza A H3N2 Panamá/2007/99', 'category', false, false, 'CIE-11'),
('XN9HE', 'Virus de la gripe A H3N2 Moscú/10/99', 'category', false, false, 'CIE-11'),
('XN9FE', 'virus influenza A H3N2v', 'category', false, false, 'CIE-11'),
('XN81W', 'Virus de la influenza equina A H3N8', 'category', false, false, 'CIE-11'),
('XN6MR', 'Virus de la influenza A H5', 'category', false, false, 'CIE-11'),
('XN5DQ', 'Virus influenza A H5N2', 'category', false, false, 'CIE-11'),
('XN6MY', 'Virus influenza A H5N8', 'category', false, false, 'CIE-11'),
('XN0AS', 'Virus influenza A H6N1', 'category', false, false, 'CIE-11'),
('XN9GE', 'Virus influenza A H7N2', 'category', false, false, 'CIE-11'),
('XN2SA', 'Variante de influenza A H7N2', 'category', false, false, 'CIE-11'),
('XN8Q3', 'Virus influenza A H7N3', 'category', false, false, 'CIE-11'),
('XN5WA', 'Virus influenza A H7N4', 'category', false, false, 'CIE-11'),
('XN8YT', 'Virus influenza A H7N7', 'category', false, false, 'CIE-11'),
('XN71C', 'Virus influenza A H9', 'category', false, false, 'CIE-11'),
('XN412', 'Virus influenza A H9N2', 'category', false, false, 'CIE-11'),
('XN5SY', 'Virus influenza A H10N3', 'category', false, false, 'CIE-11'),
('XN66Y', 'Virus influenza A H10N7', 'category', false, false, 'CIE-11'),
('XN0MW', 'Virus influenza A H10N8', 'category', false, false, 'CIE-11'),
('XN8SG', 'Virus influenza B', 'category', false, false, 'CIE-11'),
('XN8U3', 'Virus influenza C', 'category', false, false, 'CIE-11'),
('XN67Q', 'Virus influenza D', 'category', false, false, 'CIE-11'),
('XN33B', 'Lyssavirus', 'category', false, false, 'CIE-11'),
('XN796', 'Virus de la rabia', 'category', false, false, 'CIE-11'),
('XN8R7', 'Orthopoliomavirus', 'category', false, false, 'CIE-11'),
('XN7UP', 'Virus John Cunningham', 'category', false, false, 'CIE-11'),
('XN82V', 'Paramyxovirus', 'category', false, false, 'CIE-11'),
('XN98T', 'Henipavirus', 'category', false, false, 'CIE-11'),
('XN5PM', 'Virus Cedar', 'category', false, false, 'CIE-11'),
('XN53N', 'Virus Hendra', 'category', false, false, 'CIE-11'),
('XN931', 'Virus Nipah', 'category', false, false, 'CIE-11'),
('XN513', 'Metapneumovirus humano', 'category', false, false, 'CIE-11'),
('XN186', 'Virus del sarampión', 'category', false, false, 'CIE-11'),
('XN22H', 'Virus de la parotiditis', 'category', false, false, 'CIE-11'),
('XN6CR', 'Virus de la parainfluenza', 'category', false, false, 'CIE-11'),
('XN4QJ', 'Rubulavirus', 'category', false, false, 'CIE-11'),
('XN7X8', 'Parvovirus', 'category', false, false, 'CIE-11'),
('XN8PS', 'Eritrovirus', 'category', false, false, 'CIE-11'),
('XN447', 'Bocaparvovirus', 'category', false, false, 'CIE-11'),
('XN8W9', 'Neumovirus', 'category', false, false, 'CIE-11'),
('XN275', 'Virus sincitial respiratorio humano', 'category', false, false, 'CIE-11'),
('XN9WH', 'Poliomavirus', 'category', false, false, 'CIE-11'),
('XN0TQ', 'Virus polioma BK', 'category', false, false, 'CIE-11'),
('XN7UC', 'Poxvirus', 'category', false, false, 'CIE-11'),
('XN32K', 'Virus Orthopox', 'category', false, false, 'CIE-11'),
('XN3Y3', 'Virus de la viruela del búfalo', 'category', false, false, 'CIE-11'),
('XN0AU', 'Virus de la viruela', 'category', false, false, 'CIE-11'),
('XN2GM', 'Virus Mpox', 'category', false, false, 'CIE-11'),
('XN4L3', 'Clado I del virus Mpox', 'category', false, false, 'CIE-11'),
('XN9XX', '', 'category', false, false, 'CIE-11'),
('XN8ZK', '', 'category', false, false, 'CIE-11'),
('XN1BH', 'Clado II del virus Mpox', 'category', false, false, 'CIE-11'),
('XN00B', 'Clado IIa del virus Mpox', 'category', false, false, 'CIE-11'),
('XN7VR', 'Clado IIb del virus Mpox', 'category', false, false, 'CIE-11'),
('XN4Q0', 'Virus Variola', 'category', false, false, 'CIE-11'),
('XN06N', 'virus vaccinia', 'category', false, false, 'CIE-11'),
('XN1M0', 'Parapox virus', 'category', false, false, 'CIE-11'),
('XN7JF', 'virus de la estomatitis papular bovina', 'category', false, false, 'CIE-11'),
('XN8E5', 'Virus Orf', 'category', false, false, 'CIE-11'),
('XN8JR', 'Virus de la pseudoviruela bovina', 'category', false, false, 'CIE-11'),
('XN0CV', 'Yatapox virus', 'category', false, false, 'CIE-11'),
('XN0K5', 'virus tanapox', 'category', false, false, 'CIE-11'),
('XN81C', 'virus del tumor del mono de Yaba', 'category', false, false, 'CIE-11'),
('XN5G8', 'Molluscipoxvirus', 'category', false, false, 'CIE-11'),
('XN7YE', 'Virus del molusco contagioso', 'category', false, false, 'CIE-11'),
('XN22T', 'Reovirus', 'category', false, false, 'CIE-11'),
('XN6FR', 'Retrovirus', 'category', false, false, 'CIE-11'),
('XN2R0', 'Alfaretrovirus', 'category', false, false, 'CIE-11'),
('XN0TH', 'Betaretrovirus', 'category', false, false, 'CIE-11'),
('XN787', 'Deltaretrovirus', 'category', false, false, 'CIE-11'),
('XN6HX', 'Epsilonretrovirus', 'category', false, false, 'CIE-11'),
('XN4K8', 'Gamaretrovirus', 'category', false, false, 'CIE-11'),
('XN5R7', 'Lentivirus', 'category', false, false, 'CIE-11'),
('XN6JB', 'Oncovirus', 'category', false, false, 'CIE-11'),
('XN6N7', 'Rotavirus', 'category', false, false, 'CIE-11'),
('XN6TN', 'Rotavirus A', 'category', false, false, 'CIE-11'),
('XN55H', 'Rotavirus B', 'category', false, false, 'CIE-11'),
('XN0F5', 'Rotavirus C', 'category', false, false, 'CIE-11'),
('XN29P', 'Rotavirus D', 'category', false, false, 'CIE-11'),
('XN71N', 'Rotavirus E', 'category', false, false, 'CIE-11'),
('XN2F7', 'Rubivirus', 'category', false, false, 'CIE-11'),
('XN2WE', 'Rubella virus', 'category', false, false, 'CIE-11'),
('XN7R4', 'Astrovirus', 'category', false, false, 'CIE-11'),
('XN6T9', 'Vesiculovirus', 'category', false, false, 'CIE-11'),
('XN2BR', 'Virus chandipura', 'category', false, false, 'CIE-11'),
('XN9XS', 'Virus de la estomatitis vesicular', 'category', false, false, 'CIE-11'),
('XN8AY', 'Hongos', 'category', false, false, 'CIE-11'),
('XN0WC', 'Aspergillus', 'category', false, false, 'CIE-11'),
('XN6Q9', 'Aspergillus clavatus', 'category', false, false, 'CIE-11'),
('XN6B8', 'Aspergillus flavus', 'category', false, false, 'CIE-11'),
('XN5Z7', 'Aspergillus fumigatus', 'category', false, false, 'CIE-11'),
('XN25K', 'Aspergillus terreus', 'category', false, false, 'CIE-11'),
('XN7Q2', 'Aspergillus niger', 'category', false, false, 'CIE-11'),
('XN4XX', 'Basidiobolus', 'category', false, false, 'CIE-11'),
('XN4RM', 'Basidiobolus ranarum', 'category', false, false, 'CIE-11'),
('XN08A', 'Blastomyces', 'category', false, false, 'CIE-11'),
('XN14F', 'Blastomyces dermatitidis', 'category', false, false, 'CIE-11'),
('XN3CL', 'Candida', 'category', false, false, 'CIE-11'),
('XN31P', 'Candida albicans', 'category', false, false, 'CIE-11'),
('XN72N', 'Candida auris', 'category', false, false, 'CIE-11'),
('XN0RY', 'Candida haemulonii', 'category', false, false, 'CIE-11'),
('XN066', 'Cromomicosis', 'category', false, false, 'CIE-11'),
('XN106', 'Chrysosporium', 'category', false, false, 'CIE-11'),
('XN8W1', 'Chrysosporium parvum', 'category', false, false, 'CIE-11'),
('XN7Q9', 'Coccidioides', 'category', false, false, 'CIE-11'),
('XN53F', 'Coccidioides immitis', 'category', false, false, 'CIE-11'),
('XN5TT', 'Coccidioides posadasii', 'category', false, false, 'CIE-11'),
('XN62A', 'Conidiobolus', 'category', false, false, 'CIE-11'),
('XN3KM', 'Conidiobolus coronatus', 'category', false, false, 'CIE-11'),
('XN4AQ', 'Conidiobolus incongruus', 'category', false, false, 'CIE-11'),
('XN69C', 'Cryptococcus', 'category', false, false, 'CIE-11'),
('XN0LE', 'Cryptococcus gattii', 'category', false, false, 'CIE-11'),
('XN3EH', 'Cryptococcus neoformans', 'category', false, false, 'CIE-11'),
('XN7WW', 'Hongos dermatofitos', 'category', false, false, 'CIE-11'),
('XN655', 'Dermatofitos antropofílicos', 'category', false, false, 'CIE-11'),
('XN2T0', 'Epidermophyton floccosum', 'category', false, false, 'CIE-11'),
('XN3YF', 'Microsporum audouinii', 'category', false, false, 'CIE-11'),
('XN2R2', 'Microsporum ferrugineum', 'category', false, false, 'CIE-11'),
('XN8M6', 'Trichophyton concentricum', 'category', false, false, 'CIE-11'),
('XN628', 'Trichophyton gourvilii', 'category', false, false, 'CIE-11'),
('XN8BW', 'Trichophyton interdigitale', 'category', false, false, 'CIE-11'),
('XN96H', 'Trichophyton megninii', 'category', false, false, 'CIE-11'),
('XN2JF', 'Trichophyton rubrum', 'category', false, false, 'CIE-11'),
('XN53A', 'Trichophyton schoenleinii', 'category', false, false, 'CIE-11'),
('XN135', 'Trichophyton soudanense', 'category', false, false, 'CIE-11'),
('XN1K6', 'Trichophyton tonsurans', 'category', false, false, 'CIE-11'),
('XN31R', 'Trichophyton violaceum', 'category', false, false, 'CIE-11'),
('XN8BF', 'Trichophyton yaoundei', 'category', false, false, 'CIE-11'),
('XN2SY', 'Dermatofitos zoofílicos', 'category', false, false, 'CIE-11'),
('XN5ER', 'Microsporum canis', 'category', false, false, 'CIE-11'),
('XN6NM', 'Microsporum equinum', 'category', false, false, 'CIE-11'),
('XN5GR', 'Microsporum gallinae', 'category', false, false, 'CIE-11'),
('XN3WX', 'Microsporum nanum', 'category', false, false, 'CIE-11'),
('XN7JK', 'Microsporum persicolor', 'category', false, false, 'CIE-11'),
('XN3YG', 'Trichophyton equinum', 'category', false, false, 'CIE-11'),
('XN4DQ', 'Trichophyton mentagrophytes', 'category', false, false, 'CIE-11'),
('XN4H4', 'Trichophyton simii', 'category', false, false, 'CIE-11'),
('XN69S', 'Trichophyton verrucosum', 'category', false, false, 'CIE-11'),
('XN1Z2', 'Dermatofitos geofílicos', 'category', false, false, 'CIE-11'),
('XN2VZ', 'Microsporum gypseum', 'category', false, false, 'CIE-11'),
('XN7TP', 'Microsporum praecox', 'category', false, false, 'CIE-11'),
('XN3AG', 'Geotrichum', 'category', false, false, 'CIE-11'),
('XN0ES', 'Geotrichum candidum', 'category', false, false, 'CIE-11'),
('XN9LU', 'Histoplasma', 'category', false, false, 'CIE-11'),
('XN8VH', 'Histoplasma capsulatum', 'category', false, false, 'CIE-11'),
('XN7YN', 'Histoplasma duboisii', 'category', false, false, 'CIE-11'),
('XN119', 'Hortaea', 'category', false, false, 'CIE-11'),
('XN0EF', 'Hortaea werneckii', 'category', false, false, 'CIE-11'),
('XN3CM', 'Lacazia', 'category', false, false, 'CIE-11'),
('XN3NU', 'Lacazia loboi', 'category', false, false, 'CIE-11'),
('XN9ZX', 'Loboa', 'category', false, false, 'CIE-11'),
('XN43L', 'Malassezia', 'category', false, false, 'CIE-11'),
('XN25C', 'Malassezia furfur', 'category', false, false, 'CIE-11'),
('XN0TE', 'Malassezia globosa', 'category', false, false, 'CIE-11'),
('XN9ZV', 'Microsporidia', 'category', false, false, 'CIE-11'),
('XN1NU', 'Mucor', 'category', false, false, 'CIE-11'),
('XN6QM', 'Rhizopus', 'category', false, false, 'CIE-11'),
('XN9KP', 'Rhizopus arrhizus', 'category', false, false, 'CIE-11'),
('XN7RH', 'Paracoccidioides', 'category', false, false, 'CIE-11'),
('XN5UX', 'Paracoccidioides brasiliensis', 'category', false, false, 'CIE-11'),
('XN79A', 'Talaromyces', 'category', false, false, 'CIE-11'),
('XN1ZF', 'Penicillium', 'category', false, false, 'CIE-11'),
('XN7JJ', 'Penicillium notatum', 'category', false, false, 'CIE-11'),
('XN0LD', 'Talaromyces marneffei', 'category', false, false, 'CIE-11'),
('XN4YW', 'Piedraia', 'category', false, false, 'CIE-11'),
('XN6H7', 'Piedrasia hortae', 'category', false, false, 'CIE-11'),
('XN5XK', 'Pneumocystidomycetes', 'category', false, false, 'CIE-11'),
('XN3NS', 'Pseudallescheria', 'category', false, false, 'CIE-11'),
('XN6BV', 'Pseudallescheria boydii', 'category', false, false, 'CIE-11'),
('XN720', 'Rhinosporidium', 'category', false, false, 'CIE-11'),
('XN18W', 'Rhinosporidium seeberi', 'category', false, false, 'CIE-11'),
('XN200', 'Sporothrix', 'category', false, false, 'CIE-11'),
('XN6GM', 'Sporothrix schenckii', 'category', false, false, 'CIE-11'),
('XN766', 'Trichosporon', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
