-- CIE11 Import Part 22
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('KA62.0', 'Infección congénita por el virus de Zika', 'category', false, false, 'CIE-11'),
('KA62.1', 'Infección congénita por el virus de Epstein-Barr', 'category', false, false, 'CIE-11'),
('KA62.2', 'Infección congénita por el virus de la varicela zóster', 'category', false, false, 'CIE-11'),
('KA62.3', 'Infección congénita por citomegalovirus', 'category', false, false, 'CIE-11'),
('KA62.4', 'Infección congénita por echovirus', 'category', false, false, 'CIE-11'),
('KA62.5', 'Infección congénita por enterovirus', 'category', false, false, 'CIE-11'),
('KA62.6', 'Infección congénita por el virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('KA62.7', 'Síndrome congénito por parvovirus', 'category', false, false, 'CIE-11'),
('KA62.8', 'Síndrome de rubéola congénita', 'category', false, false, 'CIE-11'),
('KA62.9', 'Hepatitis viral congénita', 'category', false, false, 'CIE-11'),
('KA62.A', 'Infección perinatal por herpes simple', 'category', false, false, 'CIE-11'),
('KA62.Y', 'Otra infección viral especificada del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA62.Z', 'Infección viral del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA63', 'Infección micótica del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA63.0', 'Infección neonatal por Malassezia', 'category', false, false, 'CIE-11'),
('KA63.1', 'Aspergilosis neonatal', 'category', false, false, 'CIE-11'),
('KA63.2', 'Candidiasis neonatal', 'category', false, false, 'CIE-11'),
('KA63.Y', 'Otra infección fúngica especificada del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA63.Z', 'Infección fúngica del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA64', 'Parasitosis del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA64.0', 'Toxoplasmosis congénita', 'category', false, false, 'CIE-11'),
('KA64.1', 'Paludismo congénito por Plasmodium falciparum', 'category', false, false, 'CIE-11'),
('KA64.Y', 'Otras parasitosis especificadas del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA64.Z', 'Parasitosis del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA65', 'Infecciones neonatales de algunos sitios especificados', 'category', false, false, 'CIE-11'),
('KA65.0', 'Conjuntivitis o dacriocistitis neonatal', 'category', false, false, 'CIE-11'),
('KA65.1', 'Onfalitis del recién nacido', 'category', false, false, 'CIE-11'),
('KA65.2', 'Infección neonatal de las vías urinarias', 'category', false, false, 'CIE-11'),
('KA65.3', 'Mastitis infecciosa neonatal', 'category', false, false, 'CIE-11'),
('KA65.4', 'Meningitis neonatal', 'category', false, false, 'CIE-11'),
('KA65.Y', 'Infecciones neonatales de otros sitios especificados', 'category', false, false, 'CIE-11'),
('KA6Y', 'Otras infecciones especificadas del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA6Z', 'Infecciones del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA80', 'Pérdida de sangre fetal', 'category', false, false, 'CIE-11'),
('KA80.0', 'Pérdida de sangre fetal por vasa previa', 'category', false, false, 'CIE-11'),
('KA80.1', 'Pérdida de sangre fetal por ruptura del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA80.2', 'Pérdida de sangre fetal por la placenta', 'category', false, false, 'CIE-11'),
('KA80.3', 'Hemorragia hacia el otro gemelo', 'category', false, false, 'CIE-11'),
('KA80.4', 'Hemorragia fetal hacia la circulación materna', 'category', false, false, 'CIE-11'),
('KA80.5', 'Pérdida de sangre fetal por el corte del cordón umbilical del otro gemelo', 'category', false, false, 'CIE-11'),
('KA80.Y', 'Otra pérdida de sangre fetal especificada', 'category', false, false, 'CIE-11'),
('KA80.Z', 'Pérdida de sangre fetal, sin especificación', 'category', false, false, 'CIE-11'),
('KA81', 'Hemorragia umbilical del recién nacido', 'category', false, false, 'CIE-11'),
('KA82', 'Hemorragia intracraneal no traumática del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA82.0', 'Hemorragia intraventricular no traumática del feto o del recién nacido, de grado 1', 'category', false, false, 'CIE-11'),
('KA82.1', 'Hemorragia intraventricular no traumática del feto o del recién nacido, de grado 2', 'category', false, false, 'CIE-11'),
('KA82.2', 'Hemorragia intraventricular no traumática del feto o del recién nacido, de grado 3', 'category', false, false, 'CIE-11'),
('KA82.3', 'Hemorragia intraventricular no traumática del feto o del recién nacido, de grado 4', 'category', false, false, 'CIE-11'),
('KA82.4', 'Hemorragia intracerebral no traumática del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA82.5', 'Hemorragia subaracnoidea no traumática del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA82.6', 'Hemorragia cerebelar no traumática de los hemisferios o del vermis o de la fosa posterior del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA82.7', 'Hemorragia subdural no traumática del feto o el recién nacido', 'category', false, false, 'CIE-11'),
('KA82.Z', 'Hemorragia intracraneal no traumática del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA83', 'Algunas hemorragias neonatales especificadas', 'category', false, false, 'CIE-11'),
('KA83.0', 'Sangrado neonatal originado en la boca, la nariz o la faringe', 'category', false, false, 'CIE-11'),
('KA83.00', 'Epistaxis neonatal', 'category', false, false, 'CIE-11'),
('KA83.0Y', 'Otro sangrado neonatal especificado originado en la boca, la nariz o la faringe', 'category', false, false, 'CIE-11'),
('KA83.0Z', 'Sangrado neonatal originado en la boca, la nariz o la faringe, sin especificación', 'category', false, false, 'CIE-11'),
('KA83.1', 'Sangrado neonatal que se origina en el esófago, el estómago, el intestino grueso o el intestino delgado', 'category', false, false, 'CIE-11'),
('KA83.2', 'Hemorragia rectal neonatal', 'category', false, false, 'CIE-11'),
('KA83.3', 'Hemorragia hepática neonatal', 'category', false, false, 'CIE-11'),
('KA83.4', 'Hemorragia neonatal que se origina en la glándula suprarrenal', 'category', false, false, 'CIE-11'),
('KA83.5', 'Hemorragia neonatal que se origina en el bazo', 'category', false, false, 'CIE-11'),
('KA83.6', 'Hemorragia neonatal que se origina en el riñón o la vejiga urinaria', 'category', false, false, 'CIE-11'),
('KA83.7', 'Hemorragia neonatal que se origina en la tráquea o el parénquima pulmonar', 'category', false, false, 'CIE-11'),
('KA83.8', 'Hemorragia cutánea neonatal', 'category', false, false, 'CIE-11'),
('KA83.9', 'Hemorragia vaginal o uterina neonatal', 'category', false, false, 'CIE-11'),
('KA84', 'Enfermedad hemolítica del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA84.0', 'Isoinmunización del feto o del recién nacido al factor Rh', 'category', false, false, 'CIE-11'),
('KA84.1', 'Isoinmunización por otros factores eritrocitarios', 'category', false, false, 'CIE-11'),
('KA84.2', 'Isoinmunización AB0 del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA84.3', 'Anemia hemolítica por otros anticuerpos no clasificados del feto y recién nacido', 'category', false, false, 'CIE-11'),
('KA84.4', 'Enfermedad hemolítica por enfermedad de otros órganos neonatales', 'category', false, false, 'CIE-11'),
('KA84.5', 'Hemólisis neonatal por infección bacteriana sistémica con o sin coagulación intravascular diseminada concomitante', 'category', false, false, 'CIE-11'),
('KA84.Z', 'Enfermedad hemolítica del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA85', 'Hidropesía fetal debida a enfermedad hemolítica', 'category', false, false, 'CIE-11'),
('KA85.0', 'Hidropesía fetal debida a incompatibilidad', 'category', false, false, 'CIE-11'),
('KA85.Y', 'Otra hidropesía fetal especificada debida a enfermedad hemolítica', 'category', false, false, 'CIE-11'),
('KA85.Z', 'Hidropesía fetal debida a enfermedad hemolítica, sin especificación', 'category', false, false, 'CIE-11'),
('KA86', 'Kernicterus neonatal', 'category', false, false, 'CIE-11'),
('KA87', 'Hiperbilirrubinemia neonatal', 'category', false, false, 'CIE-11'),
('KA87.0', 'Hiperbilirrubinemia neonatal por deglución de sangre materna', 'category', false, false, 'CIE-11'),
('KA87.1', 'Hiperbilirrubinemia debida a defecto enzimático en la degradación de la bilirrubina', 'category', false, false, 'CIE-11'),
('KA87.2', 'Hiperbilirrubinemia neonatal por inhibidor de la conjugación de bilirrubina en la leche materna', 'category', false, false, 'CIE-11'),
('KA87.3', 'Hiperbilirrubinemia neonatal por nutrición parenteral total', 'category', false, false, 'CIE-11'),
('KA87.4', 'Hiperbilirrubinemia neonatal por drogas o toxinas transmitidas por la madre', 'category', false, false, 'CIE-11'),
('KA87.5', 'Hiperbilirrubinemia neonatal debida a drogas o toxinas administradas al recién nacido', 'category', false, false, 'CIE-11'),
('KA87.6', 'Hiperbilirrubinemia neonatal por otro daño hepatocelular o daño no especificado', 'category', false, false, 'CIE-11'),
('KA87.Y', 'Otra hiperbilirrubinemia neonatal especificada', 'category', false, false, 'CIE-11'),
('KA87.Z', 'Hiperbilirrubinemia neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KA88', 'Coagulación intravascular diseminada del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA89', 'Trombocitopenia neonatal transitoria', 'category', false, false, 'CIE-11'),
('KA89.0', 'Trombocitopenia posterior a infección sistémica, que incluye coagulación intravascular difusa', 'category', false, false, 'CIE-11'),
('KA89.Y', 'Otra trombocitopenia neonatal transitoria especificada', 'category', false, false, 'CIE-11'),
('KA89.Z', 'Trombocitopenia neonatal transitoria, sin especificación', 'category', false, false, 'CIE-11'),
('KA8A', 'Policitemia neonatal', 'category', false, false, 'CIE-11'),
('KA8A.0', 'Policitemia neonatal por insuficiencia placentaria o restricción del crecimiento fetal intrauterino', 'category', false, false, 'CIE-11'),
('KA8A.1', 'Policitemia neonatal por transfusión de gemelo a gemelo', 'category', false, false, 'CIE-11'),
('KA8A.2', 'Policitemia neonatal por trastorno hereditario de la producción de eritropoyetina', 'category', false, false, 'CIE-11'),
('KA8A.3', 'Policitemia neonatal posterior a transfusión u ordeño del cordón umbilical en el parto', 'category', false, false, 'CIE-11'),
('KA8A.4', 'Policitemia neonatal por transfusión de sangre', 'category', false, false, 'CIE-11'),
('KA8A.Y', 'Otra policitemia neonatal especificada', 'category', false, false, 'CIE-11'),
('KA8A.Z', 'Policitemia neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KA8B', 'Anemia de la prematuridad', 'category', false, false, 'CIE-11'),
('KA8C', 'Anemia hipoplásica congénita', 'category', false, false, 'CIE-11'),
('KA8D', 'Neutropenia neonatal transitoria', 'category', false, false, 'CIE-11'),
('KA8E', 'Neutropenia aloinmune neonatal', 'category', false, false, 'CIE-11'),
('KA8F', 'Deficiencia de vitamina K neonatal', 'category', false, false, 'CIE-11'),
('KA8F.0', 'Diátesis hemorrágica difusa por enfermedad hemorrágica fetal o neonatal por deficiencia de vitamina K', 'category', false, false, 'CIE-11'),
('KA8F.Y', 'Otra deficiencia de vitamina K neonatal especificada', 'category', false, false, 'CIE-11'),
('KA8F.Z', 'Deficiencia de vitamina K neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KA8Y', 'Otros trastornos hemorrágicos o hematológicos especificados del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KA8Z', 'Trastornos hemorrágicos o hematológicos del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB00', 'Isquemia cerebral neonatal', 'category', false, false, 'CIE-11'),
('KB00.0', 'Accidente cerebrovascular arterial perinatal', 'category', false, false, 'CIE-11'),
('KB00.1', 'Trombosis de senos venosos cerebrales del recién nacido', 'category', false, false, 'CIE-11'),
('KB00.Y', 'Otra isquemia cerebral neonatal especificada', 'category', false, false, 'CIE-11'),
('KB00.Z', 'Isquemia cerebral neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB01', 'Quistes periventriculares en el recién nacido', 'category', false, false, 'CIE-11'),
('KB02', 'Leucomalacia cerebral neonatal', 'category', false, false, 'CIE-11'),
('KB03', 'Encefalopatía neonatal', 'category', false, false, 'CIE-11'),
('KB04', 'Encefalopatía hipóxico-isquémica en el recién nacido', 'category', false, false, 'CIE-11'),
('KB05', 'Hidrocefalia neonatal', 'category', false, false, 'CIE-11'),
('KB05.0', 'Hidrocefalia obstructiva neonatal', 'category', false, false, 'CIE-11'),
('KB05.Y', 'Otra hidrocefalia neonatal especificada', 'category', false, false, 'CIE-11'),
('KB05.Z', 'Hidrocefalia neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB06', 'Convulsiones neonatales', 'category', false, false, 'CIE-11'),
('KB07', 'Compresión del cerebro en el neonato', 'category', false, false, 'CIE-11'),
('KB08', 'Trastornos del tono muscular en el recién nacido', 'category', false, false, 'CIE-11'),
('KB08.0', 'Miastenia grave neonatal transitoria', 'category', false, false, 'CIE-11'),
('KB08.1', 'Hipertonía congénita', 'category', false, false, 'CIE-11'),
('KB08.2', 'Hipotonía congénita', 'category', false, false, 'CIE-11'),
('KB08.Y', 'Otros trastornos especificados del tono muscular en el recién nacido', 'category', false, false, 'CIE-11'),
('KB08.Z', 'Trastornos del tono muscular en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB0Y', 'Otros trastornos neurológicos específicos especificados del período perinatal o neonatal', 'category', false, false, 'CIE-11'),
('KB0Z', 'Trastornos neurológicos del período perinatal o neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB20', 'Hipoxia intrauterina', 'category', false, false, 'CIE-11'),
('KB20.0', 'Hipoxia intrauterina que se observa por primera vez antes del inicio del trabajo de parto', 'category', false, false, 'CIE-11'),
('KB20.1', 'Hipoxia intrauterina que se observa por primera vez durante el trabajo de parto o el período expulsivo', 'category', false, false, 'CIE-11'),
('KB20.Z', 'Hipoxia intrauterina, sin especificación', 'category', false, false, 'CIE-11'),
('KB21', 'Asfixia del nacimiento', 'category', false, false, 'CIE-11'),
('KB21.0', 'Asfixia del nacimiento, grave', 'category', false, false, 'CIE-11'),
('KB21.1', 'Asfixia del nacimiento, de leve a moderada', 'category', false, false, 'CIE-11'),
('KB21.Z', 'Asfixia del nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KB22', 'Acidemia metabólica en el recién nacido', 'category', false, false, 'CIE-11'),
('KB23', 'Dificultad respiratoria en el recién nacido', 'category', false, false, 'CIE-11'),
('KB23.0', 'Síndrome de dificultad respiratoria del recién nacido', 'category', false, false, 'CIE-11'),
('KB23.00', 'Síndrome de dificultad respiratoria del recién nacido, alterado por tratamiento materno con corticosteroides', 'category', false, false, 'CIE-11'),
('KB23.01', 'Síndrome de dificultad respiratoria del recién nacido, alterado por tratamiento de reemplazo de surfactante pulmonar', 'category', false, false, 'CIE-11'),
('KB23.02', 'Síndrome de dificultad respiratoria del recién nacido, alterado por tratamiento materno corticoesteroideo o tratamiento de reemplazo del surfactante pulmonar', 'category', false, false, 'CIE-11'),
('KB23.0Y', 'Otro síndrome de dificultad respiratoria especificada del recién nacido', 'category', false, false, 'CIE-11'),
('KB23.0Z', 'Síndrome de dificultad respiratoria del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB23.1', 'Taquipnea transitoria del recién nacido', 'category', false, false, 'CIE-11'),
('KB23.2', 'Inestabilidad respiratoria de la prematuridad', 'category', false, false, 'CIE-11'),
('KB23.Y', 'Otra dificultad respiratoria especificada en el recién nacido', 'category', false, false, 'CIE-11'),
('KB23.Z', 'Dificultad respiratoria en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB24', 'Neumonía congénita', 'category', false, false, 'CIE-11'),
('KB25', 'Traqueítis neonatal', 'category', false, false, 'CIE-11'),
('KB26', 'Síndromes de aspiración neonatal', 'category', false, false, 'CIE-11'),
('KB26.0', 'Aspiración neonatal de meconio', 'category', false, false, 'CIE-11'),
('KB26.1', 'Aspiración neonatal de líquido amniótico o moco', 'category', false, false, 'CIE-11'),
('KB26.2', 'Aspiración neonatal de sangre', 'category', false, false, 'CIE-11'),
('KB26.3', 'Aspiración neonatal de leche o alimento regurgitado', 'category', false, false, 'CIE-11'),
('KB26.Y', 'Otros síndromes especificados de aspiración neonatal', 'category', false, false, 'CIE-11'),
('KB26.Z', 'Síndromes de aspiración neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB27', 'Fuga de aire pulmonar o afecciones relacionadas que se originan en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.0', 'Enfisema intersticial que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.1', 'Neumotórax que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.2', 'Neumomediastino que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.3', 'Neumopericardio que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.4', 'Neumoperitoneo que se origina en el período perinatal causado por síndromes primarios de pérdida de aire pulmonar', 'category', false, false, 'CIE-11'),
('KB27.Y', 'Otra fuga especificada de aire pulmonar o afecciones relacionadas que se originan en el período perinatal', 'category', false, false, 'CIE-11'),
('KB27.Z', 'Fuga de aire pulmonar o afecciones relacionadas que se originan en el período perinatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB28', 'Hemorragia pulmonar que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB28.0', 'Hemorragia traqueobronquial que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB28.1', 'Hemorragia pulmonar traumática que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB28.Y', 'Otra hemorragia pulmonar especificada que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB28.Z', 'Hemorragia pulmonar que se origina en el período perinatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB29', 'Enfermedad respiratoria crónica que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB29.0', 'Displasia broncopulmonar que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB29.Y', 'Otra enfermedad respiratoria crónica especificada que se origina en el período perinatal', 'category', false, false, 'CIE-11'),
('KB29.Z', 'Enfermedad respiratoria crónica que se origina en el período perinatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB2A', 'Apnea en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2A.0', 'Apnea neonatal central', 'category', false, false, 'CIE-11'),
('KB2A.1', 'Apnea neonatal obstructiva', 'category', false, false, 'CIE-11'),
('KB2A.2', 'Apnea neonatal mixta', 'category', false, false, 'CIE-11'),
('KB2A.3', 'Apnea en el recién nacido debida a daño neurológico', 'category', false, false, 'CIE-11'),
('KB2A.Y', 'Otra apnea del recién nacido especificada', 'category', false, false, 'CIE-11'),
('KB2A.Z', 'Apnea del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB2B', 'Atelectasia primaria en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2C', 'Ataque cianótico en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2D', 'Insuficiencia respiratoria del recién nacido', 'category', false, false, 'CIE-11'),
('KB2E', 'Paro respiratorio del recién nacido', 'category', false, false, 'CIE-11'),
('KB2F', 'Atelectasia lobar o pulmonar congénita', 'category', false, false, 'CIE-11'),
('KB2G', 'Hemorragia traqueal del recién nacido debida a traumatismo de las vías respiratorias', 'category', false, false, 'CIE-11'),
('KB2H', 'Parálisis adquirida de las cuerdas vocales en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2J', 'Obstrucción respiratoria en el recién nacido debida a anormalidad en las vías respiratorias', 'category', false, false, 'CIE-11'),
('KB2J.0', 'Hipotonía de la hipofaringe en el neonato', 'category', false, false, 'CIE-11'),
('KB2J.1', 'Masa hipofaríngea en el neonato', 'category', false, false, 'CIE-11'),
('KB2J.2', 'Malacia traqueobronquial en el neonato', 'category', false, false, 'CIE-11'),
('KB2J.Y', 'Otra obstrucción respiratoria especificada en el recién nacido debida a anormalidad en las vías respiratorias', 'category', false, false, 'CIE-11'),
('KB2J.Z', 'Obstrucción respiratoria en el recién nacido debida a anormalidad en las vías respiratorias, sin especificación', 'category', false, false, 'CIE-11'),
('KB2K', 'Quiste pulmonar en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2K.0', 'Quiste pulmonar adquirido en el recién nacido', 'category', false, false, 'CIE-11'),
('KB2K.Z', 'Quiste pulmonar en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB2Y', 'Otros trastornos respiratorios específicos del período perinatal o neonatal especificados', 'category', false, false, 'CIE-11'),
('KB2Z', 'Trastornos respiratorios específicos del período perinatal o neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB40', 'Insuficiencia cardíaca neonatal', 'category', false, false, 'CIE-11'),
('KB40.0', 'Insuficiencia cardíaca neonatal debida a perfusión pulmonar excesiva', 'category', false, false, 'CIE-11'),
('KB40.1', 'Insuficiencia cardíaca neonatal debida a disminución de la presión de salida del ventrículo izquierdo', 'category', false, false, 'CIE-11'),
('KB40.Y', 'Insuficiencia cardíaca neonatal especificada', 'category', false, false, 'CIE-11'),
('KB40.Z', 'Insuficiencia cardíaca neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB41', 'Arritmia cardíaca neonatal', 'category', false, false, 'CIE-11'),
('KB42', 'Hipertensión pulmonar persistente del recién nacido', 'category', false, false, 'CIE-11'),
('KB44', 'Isquemia miocárdica transitoria en el recién nacido', 'category', false, false, 'CIE-11'),
('KB45', 'Hipertensión neonatal', 'category', false, false, 'CIE-11'),
('KB46', 'Hipotensión neonatal', 'category', false, false, 'CIE-11'),
('KB47', 'Soplo cardíaco inocente o benigno en el recién nacido', 'category', false, false, 'CIE-11'),
('KB48', 'Conducto arterial persistente del prematuro', 'category', false, false, 'CIE-11'),
('KB4Y', 'Otros trastornos cardiovasculares especificados presentes en el período perinatal o neonatal', 'category', false, false, 'CIE-11'),
('KB4Z', 'Trastornos cardiovasculares presentes en el período perinatal o neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB60', 'Trastornos transitorios del metabolismo de los carbohidratos específicos del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KB60.0', 'Síndrome del recién nacido de madre con diabetes gestacional', 'category', false, false, 'CIE-11'),
('KB60.1', 'Síndrome del recién nacido de madre diabética, tipo 1 o 2, no gestacional, dependiente de insulina', 'category', false, false, 'CIE-11'),
('KB60.2', 'Diabetes mellitus neonatal', 'category', false, false, 'CIE-11'),
('KB60.20', 'Diabetes mellitus neonatal transitoria', 'category', false, false, 'CIE-11'),
('KB60.2Y', 'Otra diabetes mellitus neonatal especificada', 'category', false, false, 'CIE-11'),
('KB60.2Z', 'Diabetes mellitus neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB60.3', 'Hiperglucemia neonatal', 'category', false, false, 'CIE-11'),
('KB60.30', 'Hiperglucemia neonatal debida a deficiencia de insulina', 'category', false, false, 'CIE-11'),
('KB60.31', 'Hiperglucemia neonatal debida a terapia yatrógena intravenosa', 'category', false, false, 'CIE-11'),
('KB60.3Y', 'Otra hiperglucemia neonatal especificada', 'category', false, false, 'CIE-11'),
('KB60.3Z', 'Hiperglucemia neonatal, no especificada', 'category', false, false, 'CIE-11'),
('KB60.4', 'Hipoglucemia neonatal', 'category', false, false, 'CIE-11'),
('KB60.40', 'Hipoglucemia transitoria neonatal por hiperinsulinismo', 'category', false, false, 'CIE-11'),
('KB60.41', 'Hipoglucemia yatrógena neonatal transitoria', 'category', false, false, 'CIE-11'),
('KB60.42', 'Otra hipoglucemia neonatal transitoria', 'category', false, false, 'CIE-11'),
('KB60.4Y', 'Otra hipoglucemia neonatal especificada', 'category', false, false, 'CIE-11'),
('KB60.4Z', 'Hipoglucemia neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB60.Y', 'Otros trastornos transitorios especificados del metabolismo de los carbohidratos que son específicos del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KB60.Z', 'Trastornos transitorios del metabolismo de los carbohidratos que son específicos del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB61', 'Trastornos neonatales transitorios del metabolismo del calcio o del magnesio', 'category', false, false, 'CIE-11'),
('KB61.0', 'Hipomagnesemia neonatal', 'category', false, false, 'CIE-11'),
('KB61.1', 'Tetania neonatal sin mención de deficiencia de calcio o de magnesio', 'category', false, false, 'CIE-11'),
('KB61.2', 'Hipocalcemia neonatal', 'category', false, false, 'CIE-11'),
('KB61.3', 'Osteopenia neonatal', 'category', false, false, 'CIE-11'),
('KB61.Y', 'Otros trastornos neonatales transitorios especificados del metabolismo del calcio o del magnesio', 'category', false, false, 'CIE-11'),
('KB61.Z', 'Trastornos neonatales transitorios del metabolismo del calcio o del magnesio, sin especificación', 'category', false, false, 'CIE-11'),
('KB62', 'Trastornos transitorios de la función tiroidea', 'category', false, false, 'CIE-11'),
('KB62.0', 'Hipertiroidismo neonatal transitorio', 'category', false, false, 'CIE-11'),
('KB62.1', 'Otros trastornos neonatales transitorios de la función tiroidea, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('KB62.2', 'Hipertirotropinemia transitoria', 'category', false, false, 'CIE-11'),
('KB62.3', 'Hipotiroxinemia transitoria', 'category', false, false, 'CIE-11'),
('KB62.Y', 'Otros trastornos transitorios especificados de la función tiroidea', 'category', false, false, 'CIE-11'),
('KB62.Z', 'Trastornos transitorios de la función tiroidea, sin especificar', 'category', false, false, 'CIE-11'),
('KB63', 'Algunos trastornos metabólicos o electrolíticos neonatales transitorios especificados', 'category', false, false, 'CIE-11'),
('KB63.0', 'Acidosis metabólica tardía del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.1', 'Deshidratación del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.2', 'Alteraciones del equilibrio del sodio en el recién nacido', 'category', false, false, 'CIE-11'),
('KB63.20', 'Hiponatremia del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.21', 'Hipernatremia del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.2Y', 'Otras alteraciones especificadas del equilibrio del sodio en el recién nacido', 'category', false, false, 'CIE-11'),
('KB63.2Z', 'Alteraciones del equilibrio del sodio en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB63.3', 'Alteraciones del equilibrio del potasio en el recién nacido', 'category', false, false, 'CIE-11'),
('KB63.30', 'Hipocalemia del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.31', 'Hipercalemia del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.3Y', 'Otras alteraciones especificadas del equilibrio del potasio en el recién nacido', 'category', false, false, 'CIE-11'),
('KB63.3Z', 'Alteraciones del equilibrio del potasio en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB63.4', 'Tirosinemia transitoria del recién nacido', 'category', false, false, 'CIE-11'),
('KB63.5', 'Enfermedad metabólica ósea de la prematuridad', 'category', false, false, 'CIE-11'),
('KB64', 'Hipoparatiroidismo neonatal transitorio', 'category', false, false, 'CIE-11'),
('KB6Z', 'Trastornos endocrinos o metabólicos transitorios específicos del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB80', 'Enfermedad por reflujo gastroesofágico en el recién nacido', 'category', false, false, 'CIE-11'),
('KB81', 'Esofagitis en el recién nacido', 'category', false, false, 'CIE-11'),
('KB81.0', 'Esofagitis eosinofílica neonatal', 'category', false, false, 'CIE-11'),
('KB81.Y', 'Otras esofagitis específicas en el recién nacido', 'category', false, false, 'CIE-11'),
('KB81.Z', 'Esofagitis en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB82', 'Perforación gástrica prenatal', 'category', false, false, 'CIE-11'),
('KB83', 'Perforación gástrica posnatal', 'category', false, false, 'CIE-11'),
('KB84', 'Perforación ileal posnatal aislada', 'category', false, false, 'CIE-11'),
('KB85', 'Perforación intestinal intrauterina prenatal', 'category', false, false, 'CIE-11'),
('KB85.0', 'Perforación intestinal intrauterina prenatal debida a vólvulo en el útero', 'category', false, false, 'CIE-11'),
('KB85.1', 'Perforación intestinal intrauterina prenatal debida a atresia o estenosis intestinal', 'category', false, false, 'CIE-11'),
('KB85.2', 'Perforación intestinal intrauterina prenatal debida a obstrucción intraluminal', 'category', false, false, 'CIE-11'),
('KB85.Y', 'Otra perforación intestinal intrauterina prenatal especificada', 'category', false, false, 'CIE-11'),
('KB85.Z', 'Perforación intestinal intrauterina prenatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB86', 'Perforación intestinal posnatal', 'category', false, false, 'CIE-11'),
('KB86.0', 'Perforación intestinal posnatal debida a medicamentos', 'category', false, false, 'CIE-11'),
('KB86.1', 'Perforación intestinal posnatal debida a vólvulo en el útero', 'category', false, false, 'CIE-11'),
('KB86.2', 'Perforación intestinal posnatal debida a atresia o estenosis intestinal', 'category', false, false, 'CIE-11'),
('KB86.3', 'Perforación intestinal posnatal debida a obstrucción intraluminal', 'category', false, false, 'CIE-11'),
('KB86.Y', 'Otra perforación intestinal posnatal especificada', 'category', false, false, 'CIE-11'),
('KB86.Z', 'Perforación intestinal postnatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB87', 'Obstrucción intestinal del recién nacido', 'category', false, false, 'CIE-11'),
('KB87.0', 'Obstrucción intestinal debida a la leche espesa', 'category', false, false, 'CIE-11'),
('KB87.1', 'obstrucción meconial en el feto o el recién nacido', 'category', false, false, 'CIE-11'),
('KB87.2', 'Íleo meconial sin perforación', 'category', false, false, 'CIE-11'),
('KB87.3', 'Íleo transitorio del recién nacido', 'category', false, false, 'CIE-11'),
('KB87.4', 'Íleo meconial con perforación', 'category', false, false, 'CIE-11'),
('KB87.Y', 'Otra obstrucción intestinal especificada del recién nacido', 'category', false, false, 'CIE-11'),
('KB87.Z', 'Obstrucción intestinal del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB88', 'Enterocolitis necrosante en el recién nacido', 'category', false, false, 'CIE-11'),
('KB88.0', 'Enterocolitis necrosante del recién nacido, estadio 1A y B', 'category', false, false, 'CIE-11'),
('KB88.1', 'Enterocolitis necrosante del recién nacido, estadio 2A y B', 'category', false, false, 'CIE-11'),
('KB88.2', 'Enterocolitis necrosante del recién nacido, estadio 3A', 'category', false, false, 'CIE-11'),
('KB88.3', 'Enterocolitis necrosante del recién nacido, estadio 3B', 'category', false, false, 'CIE-11'),
('KB88.Y', 'Otras enterocolitis necrosantes especificadas en el recién nacido', 'category', false, false, 'CIE-11'),
('KB88.Z', 'Enterocolitis necrosante en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KB89', 'Síndromes de malabsorción neonatal', 'category', false, false, 'CIE-11'),
('KB89.0', 'Malabsorción neonatal debida a tumor endocrino secretor', 'category', false, false, 'CIE-11'),
('KB89.1', 'Síndrome del intestino corto en el recién nacido', 'category', false, false, 'CIE-11'),
('KB89.Y', 'Otros síndromes de malabsorción neonatal especificados', 'category', false, false, 'CIE-11'),
('KB89.Z', 'Síndrome de malabsorción neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KB8A', 'Melena o hematemesis neonatal debida a la deglución de sangre materna', 'category', false, false, 'CIE-11'),
('KB8B', 'Peritonitis neonatal', 'category', false, false, 'CIE-11'),
('KB8C', 'Diarrea neonatal no infecciosa', 'category', false, false, 'CIE-11'),
('KB8Y', 'Otras enfermedades del sistema digestivo especificada del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KB8Z', 'Enfermedades del sistema digestivo del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KC00', 'Hidrocele congénito', 'category', false, false, 'CIE-11'),
('KC01', 'Insuficiencia renal congénita', 'category', false, false, 'CIE-11'),
('KC0Y', 'Otros trastornos especificados del sistema genitourinario específicos del período perinatal y neonatal', 'category', false, false, 'CIE-11'),
('KC0Z', 'Trastornos del sistema genitourinario específicos del período perinatal y neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('KC20', 'Condiciones que afectan el cordón umbilical', 'category', false, false, 'CIE-11'),
('KC20.0', 'Desprendimiento tardío del cordón umbilical', 'category', false, false, 'CIE-11'),
('KC20.1', 'Pólipo umbilical del recién nacido', 'category', false, false, 'CIE-11'),
('KC20.2', 'Granuloma umbilical en el recién nacido', 'category', false, false, 'CIE-11'),
('KC20.Y', 'Otras condiciones especificadas que afectan el cordón umbilical', 'category', false, false, 'CIE-11'),
('KC20.Z', 'Condiciones que afectan el cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('KC21', 'Dermatosis inflamatorias en el recién nacido', 'category', false, false, 'CIE-11'),
('KC21.0', 'Acné neonatal', 'category', false, false, 'CIE-11'),
('KC21.1', 'Eritema tóxico del neonato', 'category', false, false, 'CIE-11'),
('KC21.2', 'Dermatitis perianal en el recién nacido', 'category', false, false, 'CIE-11'),
('KC21.Y', 'Otras dermatosis inflamatorias especificadas en el recién nacido', 'category', false, false, 'CIE-11'),
('KC21.Z', 'Dermatosis inflamatorias en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KC22', 'Trastornos neonatales de la grasa subcutánea', 'category', false, false, 'CIE-11'),
('KC22.0', 'Necrosis de la grasa subcutánea del recién nacido', 'category', false, false, 'CIE-11'),
('KC22.1', 'Paniculitis en el recién nacido por frío', 'category', false, false, 'CIE-11'),
('KC22.2', 'Esclerema neonatal', 'category', false, false, 'CIE-11'),
('KC22.Y', 'Otros trastornos especificados neonatales de la grasa subcutánea', 'category', false, false, 'CIE-11'),
('KC22.Z', 'Trastornos neonatales de la grasa subcutánea, sin especificación', 'category', false, false, 'CIE-11'),
('KC23', 'Trastornos neonatales de la mucosa oral', 'category', false, false, 'CIE-11'),
('KC24', 'Trastornos nutricionales neonatales que afectan la piel', 'category', false, false, 'CIE-11'),
('KC30', 'Piel frágil de la prematuridad', 'category', false, false, 'CIE-11'),
('KC31', 'Dermatosis vesicular o erosiva congénita con cicatrización reticulada flexible', 'category', false, false, 'CIE-11'),
('KC3Y', 'Otros trastornos de la piel especificados asociados con la prematuridad', 'category', false, false, 'CIE-11'),
('KC40', 'Afecciones diversas de la piel en el recién nacido', 'category', false, false, 'CIE-11'),
('KC40.0', 'Ampollas de succión congénitas', 'category', false, false, 'CIE-11'),
('KC40.1', 'Milia neonatal', 'category', false, false, 'CIE-11'),
('KC40.Y', 'Otras afecciones diversas especificadas de la piel en el recién nacido', 'category', false, false, 'CIE-11'),
('KC41', 'Afecciones diversas especificadas de la piel o el tegumento en el feto o el recién nacido', 'category', false, false, 'CIE-11'),
('KC41.0', 'Ingurgitación mamaria del recién nacido', 'category', false, false, 'CIE-11'),
('KC41.1', 'Hidropesía fetal no debida a enfermedad hemolítica', 'category', false, false, 'CIE-11'),
('KC41.Y', 'Otras afecciones especificadas de la piel o el tegumento del feto o del recién nacido', 'category', false, false, 'CIE-11'),
('KC50', 'Quemadura neonatal por fototerapia', 'category', false, false, 'CIE-11'),
('KC5Y', 'Otra lesión iatrogénicaa posnatal especificada de la piel', 'category', false, false, 'CIE-11'),
('KC5Z', 'Lesión iatrogénica posnatal de la piel, sin especificación', 'category', false, false, 'CIE-11'),
('KC7Y', 'Otras lesiones iatrogénicas especificadas en la piel del neonato', 'category', false, false, 'CIE-11'),
('KC9Z', 'Trastornos que afectan la piel del feto o del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KD10', 'Hipertermia en el recién nacido inducida por condiciones ambientales', 'category', false, false, 'CIE-11'),
('KD11', 'Fiebre del recién nacido', 'category', false, false, 'CIE-11'),
('KD12', 'Hipotermia en el recién nacido', 'category', false, false, 'CIE-11'),
('KD12.0', 'Síndrome de lesión por frío en el recién nacido', 'category', false, false, 'CIE-11'),
('KD12.Y', 'Otra hipotermia especificada en el recién nacido', 'category', false, false, 'CIE-11'),
('KD12.Z', 'Hipotermia en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KD1Y', 'Otros trastornos especificados de la regulación de la temperatura en el recién nacido', 'category', false, false, 'CIE-11'),
('KD1Z', 'Trastornos de la regulación de la temperatura en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KD30', 'Depresión al nacimiento', 'category', false, false, 'CIE-11'),
('KD30.0', 'Depresión al nacimiento, con Apgar de 0-3', 'category', false, false, 'CIE-11'),
('KD30.1', 'Depresión al nacimiento, con Apgar de 4-6', 'category', false, false, 'CIE-11'),
('KD30.2', 'Depresión del nacimiento asociada con acidemia metabólica de la sangre del cordón umbilical', 'category', false, false, 'CIE-11'),
('KD30.Z', 'Depresión al nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KD31', 'Suturas craneales amplias en el recién nacido', 'category', false, false, 'CIE-11'),
('KD32', 'Problemas en la ingestión de alimentos en el recién nacido', 'category', false, false, 'CIE-11'),
('KD32.0', 'Lentitud en la ingestión de alimentos del recién nacido', 'category', false, false, 'CIE-11'),
('KD32.1', 'Hipoalimentación del recién nacido', 'category', false, false, 'CIE-11'),
('KD32.2', 'Hiperalimentación del recién nacido', 'category', false, false, 'CIE-11'),
('KD32.3', 'Dificultad neonatal en la lactancia materna', 'category', false, false, 'CIE-11'),
('KD32.4', 'Insuficiencia en el desarrollo del recién nacido', 'category', false, false, 'CIE-11'),
('KD32.Y', 'Otros problemas especificados en la ingestión de alimentos en el recién nacido', 'category', false, false, 'CIE-11'),
('KD32.Z', 'Problemas en la ingestión de alimentos en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KD33', 'Niño agitado, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('KD34', 'Reacciones o intoxicaciones debidas a medicamentos administrados al feto o recién nacido', 'category', false, false, 'CIE-11'),
('KD35', 'Síndrome de abstinencia neonatal por drogadicción materna', 'category', false, false, 'CIE-11'),
('KD36', 'Síntomas de abstinencia por el uso terapéutico de drogas en el recién nacido', 'category', false, false, 'CIE-11'),
('KD37', 'Exposición al humo del tabaco en el período perinatal', 'category', false, false, 'CIE-11'),
('KD38', 'Tinción por meconio', 'category', false, false, 'CIE-11'),
('KD39', 'Complicaciones de procedimientos intrauterinos, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('KD39.0', 'Feto o recién nacido afectado por amniocentesis', 'category', false, false, 'CIE-11'),
('KD39.1', 'Feto o recién nacido afectado por biopsia de vellosidades coriónicas', 'category', false, false, 'CIE-11'),
('KD39.2', 'Feto o recién nacido afectado por toma de muestra de sangre fetal', 'category', false, false, 'CIE-11'),
('KD39.3', 'Feto o recién nacido afectado por complicaciones de cirugía fetal', 'category', false, false, 'CIE-11'),
('KD39.4', 'Feto o recién nacido afectado por complicaciones de cirugía fetal intrauterina', 'category', false, false, 'CIE-11'),
('KD39.Y', 'Otras complicaciones especificadas de procedimientos intrauterinos, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('KD39.Z', 'Complicaciones de procedimientos intrauterinos, no clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('KD3A', 'Terminación del embarazo, que afecta la supervivencia del feto o recién nacido', 'category', false, false, 'CIE-11'),
('KD3B', 'Muerte fetal de causa no especificada', 'category', false, false, 'CIE-11'),
('KD3B.0', 'Muerte fetal antes del parto', 'category', false, false, 'CIE-11'),
('KD3B.1', 'Muerte fetal durante el parto', 'category', false, false, 'CIE-11'),
('KD3B.Z', 'Muerte fetal de causa y momento respecto al parto no especificados', 'category', false, false, 'CIE-11'),
('KD3C', 'Vómito en el recién nacido', 'category', false, false, 'CIE-11'),
('KD3C.0', 'Vómito bilioso del recién nacido', 'category', false, false, 'CIE-11'),
('KD3C.Y', 'Otro vómito especificado en el recién nacido', 'category', false, false, 'CIE-11'),
('KD3C.Z', 'Vómito en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KD3Y', 'Otros trastornos especificados que se originan en el período perinatal', 'category', false, false, 'CIE-11'),
('KD5Z', 'Afecciones que se originan en el período perinatal o neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('LA00', 'Anencefalia o anomalías afines', 'category', false, false, 'CIE-11'),
('LA00.0', 'Anencefalia', 'category', false, false, 'CIE-11'),
('LA00.00', 'Craneorraquisquisis', 'category', false, false, 'CIE-11'),
('LA00.0Y', 'Otra anencefalia especificada', 'category', false, false, 'CIE-11'),
('LA00.0Z', 'Anencefalia, sin especificación', 'category', false, false, 'CIE-11'),
('LA00.1', 'Iniencefalia', 'category', false, false, 'CIE-11'),
('LA00.2', 'Acefalia', 'category', false, false, 'CIE-11'),
('LA00.3', 'Amielencefalia', 'category', false, false, 'CIE-11'),
('LA00.Y', 'Otra anencefalia o anomalías afines especificadas', 'category', false, false, 'CIE-11'),
('LA00.Z', 'Anencefalia o anomalías afines, sin especificación', 'category', false, false, 'CIE-11'),
('LA01', 'Cefalocele', 'category', false, false, 'CIE-11'),
('LA02', 'Espina bífida', 'category', false, false, 'CIE-11'),
('LA02.0', 'Espina bífida quística', 'category', false, false, 'CIE-11'),
('LA02.00', 'Mielomeningocele con hidrocefalia', 'category', false, false, 'CIE-11'),
('LA02.01', 'Mielomeningocele sin hidrocefalia', 'category', false, false, 'CIE-11'),
('LA02.02', 'Mielocistocele', 'category', false, false, 'CIE-11'),
('LA02.0Y', 'Otra espina bífida quística especificada', 'category', false, false, 'CIE-11'),
('LA02.0Z', 'Espina bífida quística, sin especificación', 'category', false, false, 'CIE-11'),
('LA02.1', 'Espina bífida abierta', 'category', false, false, 'CIE-11'),
('LA02.Y', 'Otra espina bífida especificada', 'category', false, false, 'CIE-11'),
('LA02.Z', 'Espina bífida, sin especificación', 'category', false, false, 'CIE-11'),
('LA03', 'Malformación de Chiari de tipo II', 'category', false, false, 'CIE-11'),
('LA04', 'Hidrocefalia congénita', 'category', false, false, 'CIE-11'),
('LA04.0', 'Hidrocefalia con estenosis del acueducto de Silvio', 'category', false, false, 'CIE-11'),
('LA04.Y', 'Otra hidrocefalia congénita especificada', 'category', false, false, 'CIE-11'),
('LA04.Z', 'Hidrocefalia congénita, sin especificación', 'category', false, false, 'CIE-11'),
('LA05', 'Anomalías estructurales del desarrollo prenatal del cerebro', 'category', false, false, 'CIE-11'),
('LA05.0', 'Microcefalia', 'category', false, false, 'CIE-11'),
('LA05.1', 'Megaloencefalia', 'category', false, false, 'CIE-11'),
('LA05.2', 'Holoprosencefalia', 'category', false, false, 'CIE-11'),
('LA05.3', 'Agenesia de cuerpo calloso', 'category', false, false, 'CIE-11'),
('LA05.4', 'Arrinencefalia', 'category', false, false, 'CIE-11'),
('LA05.5', 'Migración neuronal anormal', 'category', false, false, 'CIE-11'),
('LA05.50', 'Polimicrogiria', 'category', false, false, 'CIE-11'),
('LA05.51', 'Displasia cortical', 'category', false, false, 'CIE-11'),
('LA05.5Y', 'Otra migración neuronal anormal especificada', 'category', false, false, 'CIE-11'),
('LA05.5Z', 'Migración neuronal anormal, sin especificación', 'category', false, false, 'CIE-11'),
('LA05.6', 'Trastornos encefaloclásticos', 'category', false, false, 'CIE-11'),
('LA05.60', 'Porencefalia', 'category', false, false, 'CIE-11'),
('LA05.61', 'Esquicencefalia', 'category', false, false, 'CIE-11'),
('LA05.62', 'Hidranencefalia', 'category', false, false, 'CIE-11'),
('LA05.6Y', 'Otros trastornos encefaloclásticos especificados', 'category', false, false, 'CIE-11'),
('LA05.6Z', 'Trastornos encefaloclásticos, sin especificación', 'category', false, false, 'CIE-11'),
('LA05.7', 'Malformaciones quísticas cerebrales', 'category', false, false, 'CIE-11'),
('LA05.8', 'Colpocefalia', 'category', false, false, 'CIE-11'),
('LA05.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del cerebro', 'category', false, false, 'CIE-11'),
('LA05.Z', 'Anomalías estructurales del desarrollo prenatal del cerebro, sin especificación', 'category', false, false, 'CIE-11'),
('LA06', 'Anomalías estructurales del desarrollo prenatal del cerebelo', 'category', false, false, 'CIE-11'),
('LA06.0', 'Malformación de Dandy-Walker', 'category', false, false, 'CIE-11'),
('LA06.1', 'Hipoplasia o agenesia de hemisferios cerebelosos', 'category', false, false, 'CIE-11'),
('LA06.2', 'Displasia cerebelosa focal', 'category', false, false, 'CIE-11'),
('LA06.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del cerebelo', 'category', false, false, 'CIE-11'),
('LA06.Z', 'estructurales del desarrollo prenatal del cerebelo, sin especificación', 'category', false, false, 'CIE-11'),
('LA07', 'Anomalías estructurales del desarrollo prenatal del conducto neuroentérico, la médula espinal o la columna vertebral', 'category', false, false, 'CIE-11'),
('LA07.0', 'Síndrome primario de médula anclada', 'category', false, false, 'CIE-11'),
('LA07.1', 'Diastematomielia', 'category', false, false, 'CIE-11'),
('LA07.2', 'Amielia', 'category', false, false, 'CIE-11'),
('LA07.3', 'Siringomielia o hidromielia primaria', 'category', false, false, 'CIE-11'),
('LA07.4', 'Malformación de Chiari de tipo I', 'category', false, false, 'CIE-11'),
('LA07.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del conducto neuroentérico, la médula espinal o la columna vertebral', 'category', false, false, 'CIE-11'),
('LA07.Z', 'Anomalías estructurales del desarrollo prenatal del conducto neuroentérico, la médula espinal o la columna vertebral, sin especificación', 'category', false, false, 'CIE-11'),
('LA0Y', 'Otras anomalías estructurales del desarrollo especificadas del sistema nervioso', 'category', false, false, 'CIE-11'),
('LA0Z', 'Anomalías estructurales del desarrollo del sistema nervioso, sin especificación', 'category', false, false, 'CIE-11'),
('LA10', 'Anomalías estructurales del desarrollo prenatal de los globos oculares', 'category', false, false, 'CIE-11'),
('LA10.0', 'Microftalmia', 'category', false, false, 'CIE-11'),
('LA10.1', 'Anoftalmía clínica', 'category', false, false, 'CIE-11'),
('LA10.2', 'Buftalmos', 'category', false, false, 'CIE-11'),
('LA10.3', 'Macroftalmos congénito', 'category', false, false, 'CIE-11'),
('LA10.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal de los globos oculares', 'category', false, false, 'CIE-11'),
('LA10.Z', 'anomalías estructurales del desarrollo prenatal de los globos oculares, sin especificación', 'category', false, false, 'CIE-11'),
('LA11', 'Anomalías estructurales del desarrollo prenatal del segmento anterior del ojo', 'category', false, false, 'CIE-11'),
('LA11.0', 'Esclerótica azul', 'category', false, false, 'CIE-11'),
('LA11.1', 'Anomalías estructurales del desarrollo prenatal de la córnea', 'category', false, false, 'CIE-11'),
('LA11.2', 'Disgenesia del segmento anterior', 'category', false, false, 'CIE-11'),
('LA11.3', 'Aniridia', 'category', false, false, 'CIE-11'),
('LA11.4', 'Coloboma del iris', 'category', false, false, 'CIE-11'),
('LA11.5', 'Opacidad corneal congénita', 'category', false, false, 'CIE-11'),
('LA11.6', 'Trastornos estructurales de la pupila', 'category', false, false, 'CIE-11'),
('LA11.60', 'Pupila irregular', 'category', false, false, 'CIE-11'),
('LA11.61', 'Iridosquisis', 'category', false, false, 'CIE-11'),
('LA11.62', 'Anomalías funcionales de la pupila', 'category', false, false, 'CIE-11'),
('LA11.6Y', 'Otros trastornos estructurales especificados de la pupila', 'category', false, false, 'CIE-11'),
('LA11.6Z', 'Trastornos estructurales de la pupila, sin especificación', 'category', false, false, 'CIE-11'),
('LA11.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del segmento anterior del ojo', 'category', false, false, 'CIE-11'),
('LA11.Z', 'Anomalías estructurales del desarrollo prenatal del segmento anterior del ojo, sin especificación', 'category', false, false, 'CIE-11'),
('LA12', 'Anomalías estructurales del desarrollo prenatal del cristalino o la zónula ciliar', 'category', false, false, 'CIE-11'),
('LA12.0', 'Coloboma del cristalino', 'category', false, false, 'CIE-11'),
('LA12.1', 'Catarata congénita', 'category', false, false, 'CIE-11'),
('LA12.2', 'Afaquia congénita', 'category', false, false, 'CIE-11'),
('LA12.3', 'Esferofaquia', 'category', false, false, 'CIE-11'),
('LA12.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del cristalino o la zónula ciliar', 'category', false, false, 'CIE-11'),
('LA12.Z', 'Anomalías estructurales del desarrollo prenatal del cristalino o la zónula ciliar, sin especificación', 'category', false, false, 'CIE-11'),
('LA13', 'Anomalías estructurales del desarrollo prenatal del segmento posterior del ojo', 'category', false, false, 'CIE-11'),
('LA13.0', 'Anomalías congénitas del vítreo', 'category', false, false, 'CIE-11'),
('LA13.1', 'Coloboma de coroides o retina', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
