-- CIE11 Import Part 48
BEGIN;
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
VALUES
('XH4JG0', 'Tumor carcinoide tubular', 'category', false, false, 'CIE-11'),
('XH4XL2', 'Tumor papilar agresivo', 'category', false, false, 'CIE-11'),
('XH9PN4', 'Tumor bien diferenciado de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH6SY0', 'Neoplasia folicular de tiroides no invasiva con características nucleares de tipo papilar (NFTNITP)', 'category', false, false, 'CIE-11'),
('XH1Y66', 'Tumor trabecular hialinizante', 'category', false, false, 'CIE-11'),
('XH27W5', 'Tumor folicular de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH9T60', 'Carcinoma renal de células papilares claras', 'category', false, false, 'CIE-11'),
('XH6CZ3', 'Tumor borderline de células claras', 'category', false, false, 'CIE-11'),
('XH6YZ9', 'Adenoma apócrino', 'category', false, false, 'CIE-11'),
('XH0AQ8', 'Hidradenoma de células claras', 'category', false, false, 'CIE-11'),
('XH46Z2', 'Acrospiroma ecrino', 'category', false, false, 'CIE-11'),
('XH42Z3', 'Adenoma papilar écrino', 'category', false, false, 'CIE-11'),
('XH25Z9', 'Poroma ecrino', 'category', false, false, 'CIE-11'),
('XH3AM1', 'Espiradenoma, SAI', 'category', false, false, 'CIE-11'),
('XH4YU8', 'Fibroma folicular', 'category', false, false, 'CIE-11'),
('XH7NR3', 'Hidrocistoma', 'category', false, false, 'CIE-11'),
('XH4MV7', 'Hidradenoma, SAI', 'category', false, false, 'CIE-11'),
('XH4DX4', 'Hidradenoma papilar', 'category', false, false, 'CIE-11'),
('XH1PY0', 'Siringoadenoma papilifero', 'category', false, false, 'CIE-11'),
('XH96Q5', 'Adenoma apendicular de la piel', 'category', false, false, 'CIE-11'),
('XH3U61', 'Adenoma de glándula sudorípara', 'category', false, false, 'CIE-11'),
('XH06Y5', 'Siringofibroadenoma', 'category', false, false, 'CIE-11'),
('XH6325', 'Siringoma, SAI', 'category', false, false, 'CIE-11'),
('XH9GB7', 'Tumor siringomatoso del pezón', 'category', false, false, 'CIE-11'),
('XH1NC5', 'Adenoma sebáceo', 'category', false, false, 'CIE-11'),
('XH0SH5', 'Epitelioma sebáceo', 'category', false, false, 'CIE-11'),
('XH7AL8', 'Adenoma ceruminoso', 'category', false, false, 'CIE-11'),
('XH8R55', 'Tricodiscoma de predominio de células fusiformes', 'category', false, false, 'CIE-11'),
('XH1A80', 'Poroma apocrino', 'category', false, false, 'CIE-11'),
('XH8N28', 'Poroma, SAI', 'category', false, false, 'CIE-11'),
('XH0QL4', 'Sebaceoma', 'category', false, false, 'CIE-11'),
('XH7WE6', 'Porocarcinoma in situ', 'category', false, false, 'CIE-11'),
('XH9L77', 'Adenocarcinoma apócrino', 'category', false, false, 'CIE-11'),
('XH6FB5', 'Adenocarcinoma papilar digital', 'category', false, false, 'CIE-11'),
('XH7VK4', 'Porocarcinoma SAI', 'category', false, false, 'CIE-11'),
('XH58E1', 'Espiradenoma ecrino maligno', 'category', false, false, 'CIE-11'),
('XH7NK9', 'Hidradenocarcinoma', 'category', false, false, 'CIE-11'),
('XH17P2', 'Carcinoma microquístico anexal', 'category', false, false, 'CIE-11'),
('XH89V4', 'Adenocarcinoma anexial, SAI', 'category', false, false, 'CIE-11'),
('XH5LY3', 'Adenocarcinoma de glándula sudorípara', 'category', false, false, 'CIE-11'),
('XH4VR2', 'Carcinoma sebáceo', 'category', false, false, 'CIE-11'),
('XH8NE4', 'Adenocarcinoma ecrino', 'category', false, false, 'CIE-11'),
('XH6Z69', 'Adenocarcinoma ceruminoso', 'category', false, false, 'CIE-11'),
('XH9C82', 'Neoplasia maligna que surge de un espiradenoma preexistente', 'category', false, false, 'CIE-11'),
('XH2ZK9', 'Neoplasia maligna que surge de un cilindroma preexistente', 'category', false, false, 'CIE-11'),
('XH9NW9', 'Neoplasia maligna que surge de un espiradenocilindroma preexistente', 'category', false, false, 'CIE-11'),
('XH65F9', 'Sialadenoma papilífero', 'category', false, false, 'CIE-11'),
('XH0BE5', 'Siringocistadenocarcinoma papilífero', 'category', false, false, 'CIE-11'),
('XH8BW1', 'Tumor de glándula sudorípara, SAI', 'category', false, false, 'CIE-11'),
('XH1PG0', 'Epitelioma intraepidérmico de Jadassohn', 'category', false, false, 'CIE-11'),
('XH5AU2', 'Triquilemoma', 'category', false, false, 'CIE-11'),
('XH6QT9', 'Tricoepitelioma', 'category', false, false, 'CIE-11'),
('XH0U05', 'Tricofoliculoma', 'category', false, false, 'CIE-11'),
('XH5L76', 'Tumor pilar', 'category', false, false, 'CIE-11'),
('XH9E37', 'Pilomatricoma, SAI', 'category', false, false, 'CIE-11'),
('XH05Z3', 'Tricogerminoma', 'category', false, false, 'CIE-11'),
('XH7CM2', 'Matricoma melanocítico', 'category', false, false, 'CIE-11'),
('XH3EY8', 'Acantoma de la vaina pilosa', 'category', false, false, 'CIE-11'),
('XH0489', 'Tumor de infundíbulo folicular', 'category', false, false, 'CIE-11'),
('XH2K97', 'Tricoblastoma', 'category', false, false, 'CIE-11'),
('XH70J2', 'Carcinoma basal adenoide', 'category', false, false, 'CIE-11'),
('XH45F3', 'Carcinoma de células basales, fibroepitelial', 'category', false, false, 'CIE-11'),
('XH4GJ2', 'Carcinoma de células basales, miconodular', 'category', false, false, 'CIE-11'),
('XH2CR0', 'Carcinoma basocelular, nodular', 'category', false, false, 'CIE-11'),
('XH2615', 'Carcinoma de células basales, SAI', 'category', false, false, 'CIE-11'),
('XH4C18', 'Carcinoma basoescamoso', 'category', false, false, 'CIE-11'),
('XH5VK4', 'Carcinoma basocelular infiltrante, SAI', 'category', false, false, 'CIE-11'),
('XH0T12', 'Carcinoma basocelular infiltrante, no esclerosante', 'category', false, false, 'CIE-11'),
('XH67Y4', 'Carcinoma basocelular infiltrante, esclerosante', 'category', false, false, 'CIE-11'),
('XH9E93', 'Carcinoma metatípico', 'category', false, false, 'CIE-11'),
('XH5NL6', 'Carcinoma basocelular superficial', 'category', false, false, 'CIE-11'),
('XH2HE7', 'Carcinoma basocelular pigmentado', 'category', false, false, 'CIE-11'),
('XH9K96', 'Triquilemocarcinoma', 'category', false, false, 'CIE-11'),
('XH9G49', 'Carcinoma pilomatrical', 'category', false, false, 'CIE-11'),
('XH6S67', 'Carcinoma basocelular con diferenciación anexial', 'category', false, false, 'CIE-11'),
('XH3DL9', 'Carcinoma tricoblástico', 'category', false, false, 'CIE-11'),
('XH8324', 'Carcinosarcoma tricoblástico', 'category', false, false, 'CIE-11'),
('XH1JH6', 'Carcinoma de células basales, sarcomatoide', 'category', false, false, 'CIE-11'),
('XH8189', 'Tumor de células basales', 'category', false, false, 'CIE-11'),
('XH7WJ7', 'Quiste triquilemal proliferante', 'category', false, false, 'CIE-11'),
('XH3U29', 'Hemangioma capilar', 'category', false, false, 'CIE-11'),
('XH1GU2', 'Hemangioma cavernoso', 'category', false, false, 'CIE-11'),
('XH10T4', 'Hemangioma epitelioide', 'category', false, false, 'CIE-11'),
('XH0LN3', 'Hemangioendotelioma, benigno', 'category', false, false, 'CIE-11'),
('XH0553', 'Hemangioma intramuscular', 'category', false, false, 'CIE-11'),
('XH2HR3', 'Hemangioma racimoso', 'category', false, false, 'CIE-11'),
('XH4NS3', 'Hemangioma venoso', 'category', false, false, 'CIE-11'),
('XH5AW4', 'Hemangioma, SAI', 'category', false, false, 'CIE-11'),
('XH37N4', 'Miointimoma', 'category', false, false, 'CIE-11'),
('XH1JJ2', 'Angiofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH23S6', 'Hemangioma queratósico verrugoso', 'category', false, false, 'CIE-11'),
('XH4E06', 'Angiofibroma celular', 'category', false, false, 'CIE-11'),
('XH73S9', 'Angiofibroma de células gigantes', 'category', false, false, 'CIE-11'),
('XH2EX4', 'Hemangioma en penacho adquirido', 'category', false, false, 'CIE-11'),
('XH4KP7', 'Angioqueratoma', 'category', false, false, 'CIE-11'),
('XH8SM9', 'Nódulo angiomatoide epitelioide cutáneo', 'category', false, false, 'CIE-11'),
('XH8KN7', 'Lesión vascular atípica', 'category', false, false, 'CIE-11'),
('XH9Q71', 'Hemangioma cereza', 'category', false, false, 'CIE-11'),
('XH88L5', 'Hemangioma sinusoidal', 'category', false, false, 'CIE-11'),
('XH9UU3', 'Hemangioma microvenular', 'category', false, false, 'CIE-11'),
('XH9NB0', 'Hemangioma glomeruloide', 'category', false, false, 'CIE-11'),
('XH6RP8', 'Hemangioma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH27G6', 'Hemangioma congénito, SAI', 'category', false, false, 'CIE-11'),
('XH6RC4', 'Hemangioma congénito, rápidamente involutivo', 'category', false, false, 'CIE-11'),
('XH5427', 'Hemangioma congénito, no involutivo', 'category', false, false, 'CIE-11'),
('XH8PD3', 'Hemangioma tachuela', 'category', false, false, 'CIE-11'),
('XH4LY5', 'Hemangioma lobular capilar', 'category', false, false, 'CIE-11'),
('XH4E71', 'Hemangioendotelioma , maligno', 'category', false, false, 'CIE-11'),
('XH6264', 'Hemangiosarcoma', 'category', false, false, 'CIE-11'),
('XH36A5', 'Sarcoma de Kaposi', 'category', false, false, 'CIE-11'),
('XH6FJ5', 'Sarcoma de células de Kupffer', 'category', false, false, 'CIE-11'),
('XH3C78', 'Tumor alveolar bronquial intravascular', 'category', false, false, 'CIE-11'),
('XH36H7', 'Sarcoma intimal', 'category', false, false, 'CIE-11'),
('XH9GF8', 'Hemangioendotelioma epitelioide, SAI', 'category', false, false, 'CIE-11'),
('XH4SY7', 'Angioendotelioma papilar intralinfático', 'category', false, false, 'CIE-11'),
('XH6PA4', 'Hemangioendotelioma kaposiforme', 'category', false, false, 'CIE-11'),
('XH2PS0', 'Hemangioendotelioma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH26F6', 'Hemangioendotelioma pseudomiogénico (tipo sarcoma epitelioide)', 'category', false, false, 'CIE-11'),
('XH64U8', 'Hemangioendotelioma retiforme', 'category', false, false, 'CIE-11'),
('XH8D24', 'Hemangioendotelioma compuesto', 'category', false, false, 'CIE-11'),
('XH2L98', 'Hemangioendotelioma, SAI', 'category', false, false, 'CIE-11'),
('XH6810', 'Hemangioblastoma', 'category', false, false, 'CIE-11'),
('XH9ZB2', 'Adenolinfoma', 'category', false, false, 'CIE-11'),
('XH1TX5', 'Papiloma glandular y de células escamosas mixtas', 'category', false, false, 'CIE-11'),
('XH7J33', 'Linfadenoma', 'category', false, false, 'CIE-11'),
('XH2PY4', 'Adenocarcinoma con metaplasia escamosa', 'category', false, false, 'CIE-11'),
('XH7873', 'Carcinoma adenoescamoso', 'category', false, false, 'CIE-11'),
('XH9JP2', 'Carcinoma epitelioma- mioepitelial', 'category', false, false, 'CIE-11'),
('XH7247', 'Adenocarcinoma con metaplasia cartilaginosa y ósea', 'category', false, false, 'CIE-11'),
('XH2QL8', 'Adenocarcinoma con metaplasia de células fusiformes', 'category', false, false, 'CIE-11'),
('XH6G98', 'Carcinoma metaplásico semejante a la fibromatosis', 'category', false, false, 'CIE-11'),
('XH4GA3', 'Adenocarcinoma con metaplasia apocrina', 'category', false, false, 'CIE-11'),
('XH4T39', 'Adenocarcinoma con diferenciación neuroendocrina', 'category', false, false, 'CIE-11'),
('XH0RD4', 'Carcinoma metaplásico, SAI', 'category', false, false, 'CIE-11'),
('XH7MV6', 'Adenocarcinoma hepatoide', 'category', false, false, 'CIE-11'),
('XH95Y6', 'Carcinoma ductal ecrino escamoide', 'category', false, false, 'CIE-11'),
('XH8XD1', 'Carcinoma endometrioide con diferenciación escamosa', 'category', false, false, 'CIE-11'),
('XH4ZH4', 'Adenomioma', 'category', false, false, 'CIE-11'),
('XH7ZB1', 'Adenomioma polipoide atípico', 'category', false, false, 'CIE-11'),
('XH6YS4', 'Nefroma quístico benigno', 'category', false, false, 'CIE-11'),
('XH70N8', 'Siringoma condroide', 'category', false, false, 'CIE-11'),
('XH8C13', 'Nódulo estromal endometrial', 'category', false, false, 'CIE-11'),
('XH3SR2', 'Tumor renal osificante', 'category', false, false, 'CIE-11'),
('XH2KC1', 'Adenoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH3470', 'Tumor renomedular de células intersticiales', 'category', false, false, 'CIE-11'),
('XH2E97', 'Tumor estromal benigno', 'category', false, false, 'CIE-11'),
('XH0533', 'Tumor estromal y epitelial mixto', 'category', false, false, 'CIE-11'),
('XH7TJ0', 'Nefroma quístico pediátrico', 'category', false, false, 'CIE-11'),
('XH5QU1', 'Adenomioepitelioma, SAI', 'category', false, false, 'CIE-11'),
('XH2V57', 'Adenomioepitelioma, benigno', 'category', false, false, 'CIE-11'),
('XH9T96', 'Tumor mesenquimal fosfatúrico, benigno', 'category', false, false, 'CIE-11'),
('XH3UD9', 'Hamartoma pulmonar', 'category', false, false, 'CIE-11'),
('XH3CQ8', 'Mioepitelioma', 'category', false, false, 'CIE-11'),
('XH7AA3', 'Mesenquimoma, benigno', 'category', false, false, 'CIE-11'),
('XH1SP3', 'Nefroma quístico del adulto', 'category', false, false, 'CIE-11'),
('XH2P15', 'Hamartoma mesenquimatoso', 'category', false, false, 'CIE-11'),
('XH1WZ6', 'Tumor condromixoide ectomesenquimatoso', 'category', false, false, 'CIE-11'),
('XH5544', 'Adenosarcoma', 'category', false, false, 'CIE-11'),
('XH1YV7', 'Carcinofibroma', 'category', false, false, 'CIE-11'),
('XH42V2', 'Carcinoma ex adenoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH2RK1', 'Carcinosarcoma, embrionario', 'category', false, false, 'CIE-11'),
('XH2CV3', 'Sarcoma del estroma endometrial de alto grado', 'category', false, false, 'CIE-11'),
('XH1S94', 'Sarcoma del estroma endometrial, de bajo grado', 'category', false, false, 'CIE-11'),
('XH9HQ1', 'Tumor estromal gastrointestinal', 'category', false, false, 'CIE-11'),
('XH2WE3', 'Hepatoblastoma', 'category', false, false, 'CIE-11'),
('XH0765', 'Sarcoma de células claras del riñón', 'category', false, false, 'CIE-11'),
('XH64D5', 'Siringoma condroide maligno', 'category', false, false, 'CIE-11'),
('XH9M31', 'Nefroma quístico maligno', 'category', false, false, 'CIE-11'),
('XH3RF3', 'Tumor rabdoide, SAI', 'category', false, false, 'CIE-11'),
('XH0Y65', 'Tumor mixto mesodérmico', 'category', false, false, 'CIE-11'),
('XH7ZJ9', 'Tumor Mülleriano mixto', 'category', false, false, 'CIE-11'),
('XH27L5', 'Pancreatoblastoma', 'category', false, false, 'CIE-11'),
('XH2FY9', 'Blastoma pleuropulmonar', 'category', false, false, 'CIE-11'),
('XH5VH1', 'Blastoma pulmonar', 'category', false, false, 'CIE-11'),
('XH1TK5', 'Sarcoma estromal endometrial, SAI', 'category', false, false, 'CIE-11'),
('XH49Y5', 'Sarcoma estromal, SAI', 'category', false, false, 'CIE-11'),
('XH0V86', 'Tumor maligno,mixto, SAI', 'category', false, false, 'CIE-11'),
('XH5QN3', 'Nefroblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH0H07', 'Hepatoblastoma, epitelioide', 'category', false, false, 'CIE-11'),
('XH33R5', 'Hepatoblastoma epitelial mesenquimal mixto', 'category', false, false, 'CIE-11'),
('XH2W45', 'Carcinosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH7TL5', 'Adenomioepitelioma con carcinoma', 'category', false, false, 'CIE-11'),
('XH3B27', 'Tumor mesenquimal fosfatúrico, maligno', 'category', false, false, 'CIE-11'),
('XH43E6', 'Carcinoma mioepitelial', 'category', false, false, 'CIE-11'),
('XH9N95', 'Mesenquimoma maligno', 'category', false, false, 'CIE-11'),
('XH42Q2', 'Sarcoma embrionario', 'category', false, false, 'CIE-11'),
('XH4VQ1', 'Gastroblastoma', 'category', false, false, 'CIE-11'),
('XH5CT2', 'Tumor del nervio autonómico gastrointestinal', 'category', false, false, 'CIE-11'),
('XH0712', 'Tumor de células del marcapaso gastrointestinal', 'category', false, false, 'CIE-11'),
('XH1JB4', 'Nefroblastoma quístico parcialmente diferenciado', 'category', false, false, 'CIE-11'),
('XH10F1', 'Nefroma mesoblástico', 'category', false, false, 'CIE-11'),
('XH0G00', 'Sialoblastoma', 'category', false, false, 'CIE-11'),
('XH6R49', 'Tumor estromal, SAI', 'category', false, false, 'CIE-11'),
('XH4N88', 'Tumor estromal metanéfrico', 'category', false, false, 'CIE-11'),
('XH8747', 'Tumor estromal de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH8X78', 'Tumor estromal epitelial anidado calcificante', 'category', false, false, 'CIE-11'),
('XH2AD1', 'Mesenquimoma, SAI', 'category', false, false, 'CIE-11'),
('XH5LL8', 'Tumor primitivo de células granulares no neurales', 'category', false, false, 'CIE-11'),
('XH6ZU1', 'Cistadenoma de células claras', 'category', false, false, 'CIE-11'),
('XH55F1', 'Tumor quístico del nódulo aurículo-ventricular', 'category', false, false, 'CIE-11'),
('XH5232', 'Adenoma mucinoso intraductal papilar', 'category', false, false, 'CIE-11'),
('XH4070', 'Tumor mucinoso intraductal papilar con displasia intermedia', 'category', false, false, 'CIE-11'),
('XH8MD2', 'Tumor mucinoso intraductal papilarcon displasia de bajo grado', 'category', false, false, 'CIE-11'),
('XH8ML6', 'Tumormucinoso intraductal papilar con displasia moderada', 'category', false, false, 'CIE-11'),
('XH0556', 'Adenoma microquístico seroso', 'category', false, false, 'CIE-11'),
('XH38C4', 'Papiloma seroso superficial', 'category', false, false, 'CIE-11'),
('XH5RJ2', 'Cistadenoma, SAI', 'category', false, false, 'CIE-11'),
('XH8TJ0', 'Cistadenoma seroso, SAI', 'category', false, false, 'CIE-11'),
('XH0FM6', 'Cistadenoma papilar, SAI', 'category', false, false, 'CIE-11'),
('XH6H73', 'Cistadenoma mucinoso, SAI', 'category', false, false, 'CIE-11'),
('XH8XL1', 'Neoplasia quística mucinosa con displasia de grado intermedio', 'category', false, false, 'CIE-11'),
('XH6NK7', 'Neoplasia quística mucinosa con displasia intraepitelial de bajo grado', 'category', false, false, 'CIE-11'),
('XH7K36', 'Tumor quístico mucinoso con displasia intermedia', 'category', false, false, 'CIE-11'),
('XH7834', 'Tumor quístico mucinoso con displasia moderada', 'category', false, false, 'CIE-11'),
('XH0EK3', 'Neoplasia quística mucinosa con displasia de bajo grado', 'category', false, false, 'CIE-11'),
('XH8EW6', 'Neoplasia quística mucinosa con neoplasia intraepitelial de grado intermedio', 'category', false, false, 'CIE-11'),
('XH9BE7', 'Cistadenoma seromucinoso', 'category', false, false, 'CIE-11'),
('XH2M29', 'Adenoma mucinoso', 'category', false, false, 'CIE-11'),
('XH5RX2', 'Adenoma de las glándulas mucosas', 'category', false, false, 'CIE-11'),
('XH9MS1', 'Cistadenofibroma papilar', 'category', false, false, 'CIE-11'),
('XH5E08', 'Carcinoma mucinoso papilar intraductal, no invasivo', 'category', false, false, 'CIE-11'),
('XH3MB3', 'Neoplasia mucinosa papilar intraductal con displasia de alto grado', 'category', false, false, 'CIE-11'),
('XH06M2', 'Cistoadenocarcinoma mucinoso, no invasivo', 'category', false, false, 'CIE-11'),
('XH81P3', 'Neoplasia quística mucinosa con displasia de alto grado', 'category', false, false, 'CIE-11'),
('XH8PZ6', 'Carcinoma intraepitelial seroso', 'category', false, false, 'CIE-11'),
('XH9DM1', 'Tumor borderline seroso, variante micropapilar', 'category', false, false, 'CIE-11'),
('XH8NV8', 'Carcinoma intraepitelial tubárico seroso (CITS)', 'category', false, false, 'CIE-11'),
('XH1YW4', 'Carcinoma intraepitelial endometrial seroso', 'category', false, false, 'CIE-11'),
('XH5WU3', 'Carcinoma intraductal papilar-mucinoso, invasivo', 'category', false, false, 'CIE-11'),
('XH2SE1', 'Neoplasia intraductal papilar-mucinoso, con carcinoma invasivo asociado', 'category', false, false, 'CIE-11'),
('XH0572', 'Carcinoma seroso micropapilar', 'category', false, false, 'CIE-11'),
('XH5P21', 'Carcinoma pseudopapilar sólido', 'category', false, false, 'CIE-11'),
('XH0219', 'Cistadenocarcinoma, SAI', 'category', false, false, 'CIE-11'),
('XH7A08', 'Carcinoma seroso, SAI', 'category', false, false, 'CIE-11'),
('XH6JU6', 'Cistadenocarcinoma papilar, SAI', 'category', false, false, 'CIE-11'),
('XH12V5', 'Carcinoma seroso de bajo grado', 'category', false, false, 'CIE-11'),
('XH24N6', 'Carcinoma seroso de alto grado', 'category', false, false, 'CIE-11'),
('XH1390', 'Cistoadenocarcinoma mucinoso, SAI', 'category', false, false, 'CIE-11'),
('XH1K19', 'Tumor quístico mucinoso con un carcinoma invasivo asociado', 'category', false, false, 'CIE-11'),
('XH4186', 'Carcinoma seromucinoso', 'category', false, false, 'CIE-11'),
('XH1S75', 'Adenocarcinoma mucinoso', 'category', false, false, 'CIE-11'),
('XH4U83', 'Pseudomixoma del peritoneo con sitio primario desconocido', 'category', false, false, 'CIE-11'),
('XH5EQ2', 'Carcinoma mucinoso tubular y de células fusiformes', 'category', false, false, 'CIE-11'),
('XH83J5', 'Pseudomixoma del peritoneo', 'category', false, false, 'CIE-11'),
('XH4KC5', 'Carcinoma mucinoso tipo gástrico', 'category', false, false, 'CIE-11'),
('XH56K0', 'Carcinoma de células de anillo de sello metastásico', 'category', false, false, 'CIE-11'),
('XH5AF5', 'Adenocarcinoma productor de mucina', 'category', false, false, 'CIE-11'),
('XH4546', 'Carcinoma de células en anillo de sello', 'category', false, false, 'CIE-11'),
('XH2KK0', 'Carcinoma poco cohesivo', 'category', false, false, 'CIE-11'),
('XH3RD4', 'Tumor de Krukenberg', 'category', false, false, 'CIE-11'),
('XH0XE5', 'Carcinoma de células en anillo de sello / histiocitoide', 'category', false, false, 'CIE-11'),
('XH3AE9', 'Neoplasia pseudopapilar sólido de páncreas', 'category', false, false, 'CIE-11'),
('XH2FF0', 'Tumor quístico mucinosos de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH1P30', 'Cistadenoma papilar, de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH0RB9', 'Tumor borderline seromucinoso', 'category', false, false, 'CIE-11'),
('XH3ZK9', 'Tumor seroso borderline, SAI', 'category', false, false, 'CIE-11'),
('XH3FD4', 'Tumor de ovario pseudopapilar sólido', 'category', false, false, 'CIE-11'),
('XH7BB4', 'Neoplasia mucinoso apendicular de bajo grado', 'category', false, false, 'CIE-11'),
('XH6RX1', 'Neoplasia papilar intraquística con neoplasia intraepitelial de bajo grado', 'category', false, false, 'CIE-11'),
('XH5ZH7', 'Neoplasia papilar intraductal con neoplasia intraepitelial de bajo grado', 'category', false, false, 'CIE-11'),
('XH4LZ4', 'Papiloma intraductal', 'category', false, false, 'CIE-11'),
('XH7QS7', 'Neoplasia intraductal tubular-papilar, bajo grado', 'category', false, false, 'CIE-11'),
('XH6HK2', 'Neoplasia papilar intraductal, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH60S7', 'Papiloma intraductal con hiperplasia ductal atípica', 'category', false, false, 'CIE-11'),
('XH7GN3', 'Adenoma del pezón', 'category', false, false, 'CIE-11'),
('XH9F80', 'Adenoma papilar intraquístico', 'category', false, false, 'CIE-11'),
('XH4JD3', 'Papilomatosis intraductal, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH8P86', 'Comedocarcinoma, no infiltrante', 'category', false, false, 'CIE-11'),
('XH6AH7', 'Neoplasia papilar intraductal con neoplasia intraepitelial de alto grado', 'category', false, false, 'CIE-11'),
('XH9VG0', 'Adenocarcinoma intraductal papilar no infiltrante', 'category', false, false, 'CIE-11'),
('XH1H31', 'Carcinoma intraductal no infiltrante, SAI', 'category', false, false, 'CIE-11'),
('XH4V32', 'Carcinoma ductal in situ, SAI', 'category', false, false, 'CIE-11'),
('XH11S9', 'Papiloma intraductal con CDIS', 'category', false, false, 'CIE-11'),
('XH64S7', 'Neoplasia papilar- tubular intraductal, de alto grado', 'category', false, false, 'CIE-11'),
('XH9XV2', 'Carcinoma intraquístico no infiltrante', 'category', false, false, 'CIE-11'),
('XH0134', 'Carcinoma papilar sólido in situ', 'category', false, false, 'CIE-11'),
('XH39X8', 'Carcinoma intraductal, adherido, de alto grado', 'category', false, false, 'CIE-11'),
('XH9SL6', 'Carcinoma hipersecretor quístico, intraductal', 'category', false, false, 'CIE-11'),
('XH0GQ3', 'Carcinoma micropapilar intraductal', 'category', false, false, 'CIE-11'),
('XH2HB2', 'Carcinoma lobular in situ, pleomórfico', 'category', false, false, 'CIE-11'),
('XH6EH0', 'Carcinoma lobular in situ, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH7XE0', 'Carcinoma intraductal y carcinoma lobular in situ', 'category', false, false, 'CIE-11'),
('XH3PE9', 'Neoplasia tubulopapilar intraductal', 'category', false, false, 'CIE-11'),
('XH8010', 'Carcinoma in situ de glándulas sudoríparas endocrino productor de mucina', 'category', false, false, 'CIE-11'),
('XH4US4', 'Papiloma intraductal con carcinoma lobulillar in situ', 'category', false, false, 'CIE-11'),
('XH44J4', 'Carcinoma secretor', 'category', false, false, 'CIE-11'),
('XH7KH3', 'Carcinoma infiltrante del conducto, SAI', 'category', false, false, 'CIE-11'),
('XH9FX2', 'Adenocarcinoma del tipo glándula mamaria', 'category', false, false, 'CIE-11'),
('XH1N58', 'Comedocarcinoma, SAI', 'category', false, false, 'CIE-11'),
('XH8MA7', 'Adenocarcinoma papilar intraductal con invasión', 'category', false, false, 'CIE-11'),
('XH8KR8', 'Carcinoma papilar de la mama', 'category', false, false, 'CIE-11'),
('XH90W1', 'Neoplasia papilar intraductal con carcinoma invasivo asociado', 'category', false, false, 'CIE-11'),
('XH0GT6', 'Carcinoma papilar encapsulado con invasión', 'category', false, false, 'CIE-11'),
('XH9C56', 'Carcinoma micropapilar invasivo de mama', 'category', false, false, 'CIE-11'),
('XH1XB5', 'Carcinoma papilar sólido con invasión', 'category', false, false, 'CIE-11'),
('XH2YP5', 'Carcinoma medular, SAI', 'category', false, false, 'CIE-11'),
('XH9B99', 'Carcinoma parecido al medular', 'category', false, false, 'CIE-11'),
('XH2XR3', 'Carcinoma lobular, SAI', 'category', false, false, 'CIE-11'),
('XH9620', 'Adenocarcinoma medular', 'category', false, false, 'CIE-11'),
('XH6KZ1', 'Carcinoma medular atípico', 'category', false, false, 'CIE-11'),
('XH6PY4', 'Carcinoma del conducto, tipo desmoplásico', 'category', false, false, 'CIE-11'),
('XH55H7', 'Carcinoma medular con estroma linfoide', 'category', false, false, 'CIE-11'),
('XH3RK9', 'Carcinoma tubulolobular', 'category', false, false, 'CIE-11'),
('XH0408', 'Carcinoma ductal infiltrante', 'category', false, false, 'CIE-11'),
('XH8RN5', 'Carcinoma infiltrante del conducto y lobular', 'category', false, false, 'CIE-11'),
('XH9Z29', 'Carcinoma lobular e intraductal', 'category', false, false, 'CIE-11'),
('XH6MH3', 'Carcinoma infiltrante ductal y carcinoma in situ lobular', 'category', false, false, 'CIE-11'),
('XH9551', 'Carcinoma infiltrante lobular y carcinoma ductal insitu', 'category', false, false, 'CIE-11'),
('XH8CS0', 'Carcinoma infiltrante ductal mezclado con otros tipos de carcinoma', 'category', false, false, 'CIE-11'),
('XH9GX4', 'Carcinoma infiltrante ductal carcinoma coloide', 'category', false, false, 'CIE-11'),
('XH2ST9', 'Carcinoma cribiforme y ductal infiltrante', 'category', false, false, 'CIE-11'),
('XH3969', 'Carcinoma ductal y mucinoso infiltrante', 'category', false, false, 'CIE-11'),
('XH1ND7', 'Carcinoma infiltrante ductal y tubular', 'category', false, false, 'CIE-11'),
('XH3CB4', 'Infiltración lobular mezclada con otros tipos de carcinoma', 'category', false, false, 'CIE-11'),
('XH5SD5', 'Adenocarcinoma polimorfo', 'category', false, false, 'CIE-11'),
('XH9G73', 'Carcinoma inflamatorio', 'category', false, false, 'CIE-11'),
('XH3E21', 'Enfermedad de Paget, mamaria', 'category', false, false, 'CIE-11'),
('XH47A6', 'Enfermedad de Paget y carcinoma infiltrante de conducto de mama', 'category', false, false, 'CIE-11'),
('XH70F8', 'Enfermedad de Paget , extramamaria', 'category', false, false, 'CIE-11'),
('XH0C76', 'Enfermedad de Paget y carcinoma intraductal de mama', 'category', false, false, 'CIE-11'),
('XH32K6', 'Carcinoma de mama similar al basal', 'category', false, false, 'CIE-11'),
('XH4ZU9', 'Adenocarcinoma de glándulas anogenitales similares a las mamarias', 'category', false, false, 'CIE-11'),
('XH5KW8', 'Carcinoma de mama masculino', 'category', false, false, 'CIE-11'),
('XH4EK4', 'Carcinoma endocrino de glándulas sudoríparas productor de mucina', 'category', false, false, 'CIE-11'),
('XH9HB7', 'Carcinoma lobular pleomórfico', 'category', false, false, 'CIE-11'),
('XH1146', 'Carcinoma juvenil de la mama', 'category', false, false, 'CIE-11'),
('XH8TH6', 'Carcinoma quístico hipersecretor', 'category', false, false, 'CIE-11'),
('XH9HV0', 'Tumor epitelial, benigno', 'category', false, false, 'CIE-11'),
('XH1TD2', 'Tumorlet, benigno', 'category', false, false, 'CIE-11'),
('XH65S3', 'Epitelioma, benigno', 'category', false, false, 'CIE-11'),
('XH0M86', 'Hiperplasia nodular focal', 'category', false, false, 'CIE-11'),
('XH5NV6', 'Carcinoma in situ, SAI', 'category', false, false, 'CIE-11'),
('XH56X7', 'Carcinoma con células gigantes como osteoclastos', 'category', false, false, 'CIE-11'),
('XH63D2', 'Carcinoma SAI', 'category', false, false, 'CIE-11'),
('XH3XZ6', 'Carcinoma de células gigantes y células fusiformes', 'category', false, false, 'CIE-11'),
('XH1JZ2', 'Carcinoma de células gigantes', 'category', false, false, 'CIE-11'),
('XH00N7', 'Carcinoma de células vítreas', 'category', false, false, 'CIE-11'),
('XH4QU2', 'Carcinoma de células grandes con fenotipo rabdoide', 'category', false, false, 'CIE-11'),
('XH0NL5', 'Carcinoma neuroendocrino de células grandes', 'category', false, false, 'CIE-11'),
('XH35G0', 'Carcinoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH92T7', 'Carcinoma de células poligonales', 'category', false, false, 'CIE-11'),
('XH35M3', 'Carcinoma pseudosarcomatoso', 'category', false, false, 'CIE-11'),
('XH1YN3', 'Carcinoma, metastásico, SAI', 'category', false, false, 'CIE-11'),
('XH8D74', 'Carcinomatosis', 'category', false, false, 'CIE-11'),
('XH4P61', 'Epitelioma maligno', 'category', false, false, 'CIE-11'),
('XH45J4', 'Carcinoma de células grandes, SAI', 'category', false, false, 'CIE-11'),
('XH1YY4', 'Carcinoma indiferenciado, SAI', 'category', false, false, 'CIE-11'),
('XH57U9', 'Carcinoma, anaplásico, SAI', 'category', false, false, 'CIE-11'),
('XH2855', 'Proteína nuclear en los testículos (NUT) asociada a carcinoma', 'category', false, false, 'CIE-11'),
('XH3RZ4', 'Carcinoma de células fusiformes, SAI', 'category', false, false, 'CIE-11'),
('XH0YB0', 'Carcinoma de células pequeñas, SAI', 'category', false, false, 'CIE-11'),
('XH9SY0', 'Carcinoma neuroendocrino de células pequeñas', 'category', false, false, 'CIE-11'),
('XH28J9', 'Carcinoma de células de avena', 'category', false, false, 'CIE-11'),
('XH3T00', 'Carcinoma de células pequeñas, células fusiformes', 'category', false, false, 'CIE-11'),
('XH6GK0', 'Carcinoma de células pequeñas, células intermedias', 'category', false, false, 'CIE-11'),
('XH8ZR8', 'Carcinoma de células pequeñas, tipo hipercalcémico', 'category', false, false, 'CIE-11'),
('XH7YE3', 'Carcinoma combinado de células pequeñas', 'category', false, false, 'CIE-11'),
('XH0793', 'Adenocarcinoma combinado de células pequeñas', 'category', false, false, 'CIE-11'),
('XH6FK9', 'Carcinoma combinado de células pequeñas y células grandes', 'category', false, false, 'CIE-11'),
('XH9ZD2', 'Carcinoma combinado de células pequeñas y escamosas', 'category', false, false, 'CIE-11'),
('XH1DU4', 'Carcinoma de células no pequeñas', 'category', false, false, 'CIE-11'),
('XH26N1', 'Carcinoma asociado a heterotopía', 'category', false, false, 'CIE-11'),
('XH90B3', 'Carcinoma combinado neuroendocrino de células grandes', 'category', false, false, 'CIE-11'),
('XH98Z7', 'Carcinoma anaplásico indiferenciado', 'category', false, false, 'CIE-11'),
('XH5R16', 'Carcinoma desdiferenciado', 'category', false, false, 'CIE-11'),
('XH2BS4', 'Carcinoma escamoso con células gigantes parecidas a osteoclastos', 'category', false, false, 'CIE-11'),
('XH2224', 'Carcinoma indiferenciado con células gigantes parecidas a osteoclastos', 'category', false, false, 'CIE-11'),
('XH1N44', 'Tumourlet, SAI', 'category', false, false, 'CIE-11'),
('XH5DX3', 'Tumor de Brenner, SAI', 'category', false, false, 'CIE-11'),
('XH4MA6', 'Fibroadenoma intracanalicular', 'category', false, false, 'CIE-11'),
('XH7JU0', 'Adenofibroma papilar', 'category', false, false, 'CIE-11'),
('XH0N11', 'Fibroadenoma pericanalicular', 'category', false, false, 'CIE-11'),
('XH9HE2', 'Fibroadenoma, SAI', 'category', false, false, 'CIE-11'),
('XH91Y8', 'Adenofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH5S99', 'Cistadenofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH5ZB5', 'Adenofibroma seroso, SAI', 'category', false, false, 'CIE-11'),
('XH6RL8', 'Cistadenofibroma seroso, SAI', 'category', false, false, 'CIE-11'),
('XH1VJ0', 'Adenofibroma seromucinoso', 'category', false, false, 'CIE-11'),
('XH59X8', 'Adenofibroma mucinoso, SAI', 'category', false, false, 'CIE-11'),
('XH9SM7', 'Cistadenofibroma mucinoso, SAI', 'category', false, false, 'CIE-11'),
('XH50P7', 'Tumor filoide, benigno', 'category', false, false, 'CIE-11'),
('XH4RU1', 'Fibroadenoma gigante', 'category', false, false, 'CIE-11'),
('XH70H4', 'Fibroadenoma juvenil', 'category', false, false, 'CIE-11'),
('XH5853', 'Lipofibroadenoma', 'category', false, false, 'CIE-11'),
('XH7ZU2', 'Adenofibroma metanéfrico', 'category', false, false, 'CIE-11'),
('XH6NJ7', 'Tumor de Brenner, maligno', 'category', false, false, 'CIE-11'),
('XH7284', 'Adenocarcinofibroma mucinoso', 'category', false, false, 'CIE-11'),
('XH75P5', 'Tumor estromal periductal, bajo grado', 'category', false, false, 'CIE-11'),
('XH9JC2', 'Adenocarcinofibroma seroso', 'category', false, false, 'CIE-11'),
('XH6PQ0', 'Cistadenocarcinofibroma seroso', 'category', false, false, 'CIE-11'),
('XH0WW5', 'Cistadenocarcinofibroma mucinoso', 'category', false, false, 'CIE-11'),
('XH8HJ7', 'Tumor filoides, maligno', 'category', false, false, 'CIE-11'),
('XH2CH8', 'Tumor de Brenner, malignidad borderline', 'category', false, false, 'CIE-11'),
('XH7AR7', 'Adenofibroma mucinoso de malignidad borferline', 'category', false, false, 'CIE-11'),
('XH2YZ1', 'Cistadenofibroma mucinoso de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH5NK4', 'Tumor filoides, borderline', 'category', false, false, 'CIE-11'),
('XH07C7', 'Adenofibroma seroso de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH2M30', 'Cistadenofibroma seroso de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH8A47', 'Angiomiofibroblastoma', 'category', false, false, 'CIE-11'),
('XH06N0', 'Histiocitoma fibroso benigno', 'category', false, false, 'CIE-11'),
('XH3BQ8', 'Elastofibroma', 'category', false, false, 'CIE-11'),
('XH2MW3', 'Fibroma fascial', 'category', false, false, 'CIE-11'),
('XH5XQ3', 'Fibromixoma', 'category', false, false, 'CIE-11'),
('XH3NQ0', 'Miofibroblastoma', 'category', false, false, 'CIE-11'),
('XH0953', 'Miofibroma', 'category', false, false, 'CIE-11'),
('XH7FV0', 'Fibroma periosteal', 'category', false, false, 'CIE-11'),
('XH8E66', 'Fibroma, SAI', 'category', false, false, 'CIE-11'),
('XH2ZF3', 'Fibroblastoma desmoplástica', 'category', false, false, 'CIE-11'),
('XH7GT0', 'Fibroma de Gardner', 'category', false, false, 'CIE-11'),
('XH0XH6', 'Fibroma Nuchal', 'category', false, false, 'CIE-11'),
('XH2WT6', 'Fibromixoma plexiforme', 'category', false, false, 'CIE-11'),
('XH0WB3', 'Fibroma de la vaina del tendón', 'category', false, false, 'CIE-11'),
('XH8Q71', 'Tumor fibroso solitario / Hemangiopericitoma, grado 1', 'category', false, false, 'CIE-11'),
('XH7TH6', 'Tumor fibroso calcificante', 'category', false, false, 'CIE-11'),
('XH5LM1', 'Facitis nodular', 'category', false, false, 'CIE-11'),
('XH1UJ5', 'Histiocitoma, SAI', 'category', false, false, 'CIE-11'),
('XH8B90', 'Dermatofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH7436', 'Neumocitoma esclerosante', 'category', false, false, 'CIE-11'),
('XH5DP4', 'Histiocitoma profundo', 'category', false, false, 'CIE-11'),
('XH9VG1', 'Histiocitoma juvenil', 'category', false, false, 'CIE-11'),
('XH33Q1', 'Reticulohistiocitoma', 'category', false, false, 'CIE-11'),
('XH8ZE3', 'Fibroma aponeurótico calcificante', 'category', false, false, 'CIE-11'),
('XH2874', 'Fibroma colagenoso', 'category', false, false, 'CIE-11'),
('XH3665', 'Fibroma dérmico como placa CD34 positivo', 'category', false, false, 'CIE-11'),
('XH8173', 'Fibromixoma acral', 'category', false, false, 'CIE-11'),
('XH5JG7', 'Fibroma esclerótico', 'category', false, false, 'CIE-11'),
('XH6JX7', 'Fascitis proliferativa', 'category', false, false, 'CIE-11'),
('XH87F9', 'Miositis proliferativa', 'category', false, false, 'CIE-11'),
('XH15M9', 'Histiocitoma fibroso epitelioide', 'category', false, false, 'CIE-11'),
('XH1BV2', 'Fibroma pleomorfo', 'category', false, false, 'CIE-11'),
('XH18K3', 'Dermatomiofibroma', 'category', false, false, 'CIE-11'),
('XH2HE9', 'Miopericitoma', 'category', false, false, 'CIE-11'),
('XH5FY2', 'Displasia fibrosa', 'category', false, false, 'CIE-11'),
('XH8EV4', 'Fibrosarcoma de la fascia', 'category', false, false, 'CIE-11'),
('XH6LT0', 'Fibromixosarcoma', 'category', false, false, 'CIE-11'),
('XH7BC6', 'Fibrosarcoma infantil', 'category', false, false, 'CIE-11'),
('XH3406', 'Fibrosarcoma periosteal', 'category', false, false, 'CIE-11'),
('XH56W2', 'Sarcoma periosteal, SAI', 'category', false, false, 'CIE-11'),
('XH1HP3', 'Tumor fibroso solitario, maligno', 'category', false, false, 'CIE-11'),
('XH4EP1', 'Fibrosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH1DA3', 'Tumor fibroso solitario / Haemangiopericitoma, grado 3', 'category', false, false, 'CIE-11'),
('XH2668', 'Sarcoma miofibroblástico', 'category', false, false, 'CIE-11'),
('XH0947', 'Histiocitoma fibroso maligno', 'category', false, false, 'CIE-11'),
('XH8WH0', 'Mixofibrosarcoma', 'category', false, false, 'CIE-11'),
('XH9V92', 'Dermatofibrosarcoma protuberans, fibrosarcomatoso', 'category', false, false, 'CIE-11'),
('XH6116', 'Fibromatosis abdominal', 'category', false, false, 'CIE-11'),
('XH13Z3', 'Fibromatosis agresiva', 'category', false, false, 'CIE-11'),
('XH1RM7', 'Histiocitoma fibroso atípico', 'category', false, false, 'CIE-11'),
('XH9HH5', 'Fibroma celular', 'category', false, false, 'CIE-11'),
('XH5MH2', 'Fibromatosis congénita generalizada', 'category', false, false, 'CIE-11'),
('XH85R1', 'Tumor miofibroblástico, peribronquial', 'category', false, false, 'CIE-11'),
('XH1N00', 'Miofibromatosis', 'category', false, false, 'CIE-11'),
('XH2D15', 'Sarcoma fibroblástico mixoinflamatorio', 'category', false, false, 'CIE-11'),
('XH0TA8', 'Tumor fibroblástico mixoinflamatorio atípico', 'category', false, false, 'CIE-11'),
('XH9526', 'Tumor fibrolipomatoso hemosiderótico', 'category', false, false, 'CIE-11'),
('XH75J5', 'Fibromatosis de tipo palmar / plantar', 'category', false, false, 'CIE-11'),
('XH7E62', 'Tumor fibroso solitario, SAI', 'category', false, false, 'CIE-11'),
('XH1EH1', 'Tumor fibroso solitario / Haemangiopericitoma, grado 2', 'category', false, false, 'CIE-11'),
('XH66Z0', 'Tumor miofibroblástico, SAI', 'category', false, false, 'CIE-11'),
('XH6YK5', 'Fibroma desmoplásico', 'category', false, false, 'CIE-11'),
('XH4QZ8', 'Dermatofibrosarcoma protuberante, SAI', 'category', false, false, 'CIE-11'),
('XH5CT4', 'Dermatofibrosarcoma protuberans pigmentado', 'category', false, false, 'CIE-11'),
('XH9AV8', 'Fibroblastoma de células gigantes', 'category', false, false, 'CIE-11'),
('XH4GL1', 'Tumor fibrohistiocítico plexiforme', 'category', false, false, 'CIE-11'),
('XH9362', 'Histiocitoma fibroso angiomatoso', 'category', false, false, 'CIE-11'),
('XH7050', 'Hemangiopericitoma meningioma', 'category', false, false, 'CIE-11'),
('XH3GV5', 'Teratoma, benigno', 'category', false, false, 'CIE-11'),
('XH9F67', 'Quiste dermoide, SAI', 'category', false, false, 'CIE-11'),
('XH52Q4', 'Teratoma, tipo prepuberal', 'category', false, false, 'CIE-11'),
('XH22M4', 'Struma del ovario, SAI', 'category', false, false, 'CIE-11'),
('XH8AD3', 'Células germinales malignas intratubulares', 'category', false, false, 'CIE-11'),
('XH24E0', 'Disgerminoma', 'category', false, false, 'CIE-11'),
('XH0A34', 'Tumor de células germinales, no seminomatoso', 'category', false, false, 'CIE-11'),
('XH1E13', 'Germinoma', 'category', false, false, 'CIE-11'),
('XH7SG5', 'Tumor hepatoide del saco vitelino', 'category', false, false, 'CIE-11'),
('XH0N49', 'Teratoma inmaduro, maligno', 'category', false, false, 'CIE-11'),
('XH2PP9', 'Teratoma maligno, indiferenciado', 'category', false, false, 'CIE-11'),
('XH9Z28', 'Poliembrioma', 'category', false, false, 'CIE-11'),
('XH6YQ4', 'Seminoma, anaplásico', 'category', false, false, 'CIE-11'),
('XH80D1', 'Seminoma espermatocítico', 'category', false, false, 'CIE-11'),
('XH56W1', 'Teratocarcinoma', 'category', false, false, 'CIE-11'),
('XH09W7', 'Tumor de saco vitelino', 'category', false, false, 'CIE-11'),
('XH9FM4', 'Seminoma, SAI', 'category', false, false, 'CIE-11'),
('XH8MB9', 'Carcinoma embrionario, SAI', 'category', false, false, 'CIE-11'),
('XH15X1', 'Tumor del saco vitelino, tipo pospúberal', 'category', false, false, 'CIE-11'),
('XH7YZ9', 'Teratoma maligno, SAI', 'category', false, false, 'CIE-11'),
('XH43T4', 'Teratoma maligno, intermedio', 'category', false, false, 'CIE-11'),
('XH33E8', 'Teratoma con transformación maligna', 'category', false, false, 'CIE-11'),
('XH2PS1', 'Tumor de células germinales mixtas', 'category', false, false, 'CIE-11'),
('XH9QP9', 'Tumor de células germinales asociado con malignidad hematológica', 'category', false, false, 'CIE-11'),
('XH5U02', 'Teratoma mixto y seminoma', 'category', false, false, 'CIE-11'),
('XH5PU7', 'Struma del ovario, maligno', 'category', false, false, 'CIE-11'),
('XH1P78', 'Teratocarcinosarcoma', 'category', false, false, 'CIE-11'),
('XH0K61', 'Gonadoblastoma', 'category', false, false, 'CIE-11'),
('XH83G5', 'Teratoma, SAI', 'category', false, false, 'CIE-11'),
('XH4NU1', 'Tumor de células germinales, regresivo', 'category', false, false, 'CIE-11'),
('XH5MG2', 'Teratoma inmaduro del pulmón', 'category', false, false, 'CIE-11'),
('XH2KP9', 'Teratoma inmaduro del timo', 'category', false, false, 'CIE-11'),
('XH2XW3', 'Carcinoma estromal', 'category', false, false, 'CIE-11'),
('XH5PC3', 'Teratoma inmaduro de tiroides', 'category', false, false, 'CIE-11')
ON CONFLICT (code) DO NOTHING;
COMMIT;
