-- DSM-5 IMPORT MIGRATION
BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('296.99', 'Trastorno de desregulación disruptiva del estado de ánimo', 'DSM-5'),
('DSM-___.__', 'Trastorno de depresión mayora', 'DSM-5'),
('DSM-___.__', 'Episodio único', 'DSM-5'),
('296.21', '296.22 (F32.1)', 'DSM-5'),
('296.23', '296.24 (F32.3)', 'DSM-5'),
('296.25', '296.26 (F32.5)', 'DSM-5'),
('296.20', 'Leve', 'DSM-5'),
('DSM-___.__', 'Episodio recurrente', 'DSM-5'),
('296.31', '296.32 (F33.1)', 'DSM-5'),
('296.33', '296.34 (F33.3)', 'DSM-5'),
('296.35', '296.36 (F33.42)', 'DSM-5'),
('296.30', 'Trastorno depresivo persistente (distimia)a', 'DSM-5'),
('300.4', 'Trastorno disfórico premenstrual', 'DSM-5'),
('625.4', '___.__ (___.__)', 'DSM-5'),
('293.83', 'Con características depresivas', 'DSM-5'),
('DSM-F06.31', '(F06.32)', 'DSM-5'),
('DSM-F06.34', 'Otro trastorno depresivo especificado', 'DSM-5'),
('DSM-F32.8', '311', 'DSM-5'),
('DSM-F32.9', 'Otro trastorno depresivo no especificado', 'DSM-5'),
('309.21', 'Mutismo selectivo', 'DSM-5'),
('313.23', 'Fobia específica', 'DSM-5'),
('300.29', 'Animal', 'DSM-5'),
('DSM-F40.218', 'Entorno natural', 'DSM-5'),
('DSM-F40.228', '(___.___)', 'DSM-5'),
('DSM-F40.230', '(F40.231)', 'DSM-5'),
('DSM-F40.232', '(F40.233)', 'DSM-5'),
('DSM-F40.248', 'Miedo a la sangre', 'DSM-5'),
('DSM-F40.298', 'Trastorno de ansiedad social (fobia social)', 'DSM-5'),
('300.23', 'Trastorno de pánico', 'DSM-5'),
('300.01', '___.__ (___.__)', 'DSM-5'),
('300.22', 'Trastorno de ansiedad generalizada', 'DSM-5'),
('300.02', '___.__ (___.__)', 'DSM-5'),
('293.84', '300.09 (F41.8)', 'DSM-5'),
('300.00', 'Otro trastorno de ansiedad no especificado', 'DSM-5'),
('300.3', 'Trastorno obsesivo-compulsivos', 'DSM-5'),
('300.7', 'Trastorno dismórfico corporala', 'DSM-5'),
('300.3', 'Trastorno de acumulación''', 'DSM-5'),
('312.39', 'Tricotilomanía (trastorno de arrancarse el cabello)', 'DSM-5'),
('698.4', 'Trastorno de excoriación (rascarse la piel)', 'DSM-5'),
('294.8', 'Trastorno obsesivo-compulsivo y trastornos relacionados debidos a otra', 'DSM-5'),
('300.3', 'Otros trastornos obsesivo-compulsivos y trastornos relacionados', 'DSM-5'),
('300.3', 'Trastorno obsesivo-compulsivo y trastornos relacionados no especificados', 'DSM-5'),
('313.89', 'Trastorno de apego reactivo', 'DSM-5'),
('313.89', 'Trastorno de relación social desinhibido', 'DSM-5'),
('309.81', 'Trastorno de estrés postraumático (incluye el trastorno de estrés postraumático', 'DSM-5'),
('308.3', '___.___(__.__)', 'DSM-5'),
('309.0', '309.24 (F43.22)', 'DSM-5'),
('309.28', '309.3 (F43.24)', 'DSM-5'),
('309.4', '309.9 (F43.20)', 'DSM-5'),
('309.89', 'Trastorno relacionado con traumas y factores de estrés no especificado', 'DSM-5'),
('309.9', 'Trastornos disociativos', 'DSM-5'),
('300.14', 'Trastorno de identidad disociativo', 'DSM-5'),
('300.12', 'Con fuga disociativa', 'DSM-5'),
('300.13', '300.6 (F48.1)', 'DSM-5'),
('300.15', 'Trastorno disociativo no especificado', 'DSM-5'),
('300.15', 'Trastornos de síntomas somáticos y trastornos', 'DSM-5'),
('300.82', 'Trastorno de síntomas somáticos', 'DSM-5'),
('300.7', '300.11 (___.__)', 'DSM-5'),
('DSM-F44.4', 'Con movimiento anómalo', 'DSM-5'),
('DSM-F44.4', 'Con síntomas de la deglución', 'DSM-5'),
('DSM-F44.4', 'Con síntomas del habla', 'DSM-5'),
('DSM-F44.4', '(F44.5)', 'DSM-5'),
('DSM-F44.6', 'Con síntoma sensitivo especial', 'DSM-5'),
('DSM-F44.6', 'Con síntomas mixtos', 'DSM-5'),
('DSM-F44.7', 'Especificar si: Episodio agudo, Persistente', 'DSM-5'),
('DSM-F54', 'Factores psicológicos que influyen en otras afecciones médicas', 'DSM-5'),
('300.19', 'Trastorno facticio (incluye trastorno facticio aplicado a uno mismo, trastorno', 'DSM-5'),
('300.89', 'Otro trastorno de síntomas somáticos y trastornos relacionados especificados', 'DSM-5'),
('300.82', 'Trastornos de la conducta alimentaria y de la ingesta', 'DSM-5'),
('DSM-F98.3', 'En niños', 'DSM-5'),
('DSM-F50.8', 'En adultos', 'DSM-5'),
('307.53', 'Trastorno de rumiacióna', 'DSM-5'),
('307.59', 'Trastorno de evitación/restricción de la ingesta de alimentos', 'DSM-5'),
('DSM-F50.01', 'Tipo restrictivo', 'DSM-5'),
('DSM-F50.02', 'Tipo con atracones/purgas', 'DSM-5'),
('307.51', 'Bulimia nerviosab,C', 'DSM-5'),
('307.51', 'Trastorno de atraconesb,c', 'DSM-5'),
('307.59', 'Otro trastorno de la conducta alimentaria o de la ingesta de alimentos', 'DSM-5'),
('307.50', 'Trastorno de la conducta alimentaria o de la ingesta de alimentos', 'DSM-5'),
('307.6', 'Enuresis', 'DSM-5'),
('307.7', 'Encopresis', 'DSM-5'),
('788.39', 'Con síntomas urinarios', 'DSM-5'),
('787.60', 'Con síntomas fecales', 'DSM-5'),
('DSM-___.__', 'Trastorno de la excreción no especificado', 'DSM-5'),
('788.30', 'Con síntomas urinarios', 'DSM-5'),
('307.42', 'Trastorno de insomnio''', 'DSM-5'),
('307.44', 'Trastorno por hipersomniab,  e', 'DSM-5'),
('DSM-___.__', 'Narcolepsiae', 'DSM-5'),
('347.00', 'Narcolepsia sin cataplejía pero con deficiencia de hipocretina', 'DSM-5'),
('347.01', 'Narcolepsia con cataplejía pero sin deficiencia de hipocretina', 'DSM-5'),
('347.00', 'Ataxia cerebelosa autosómica dominante, sordera y narcolepsia', 'DSM-5'),
('347.00', 'Narcolepsia autosómica dominante, obesidad y diabetes de tipo 2', 'DSM-5'),
('347.10', 'Narcolepsia secundaria a otra afección médica', 'DSM-5'),
('327.23', 'Apnea e hipopnea obstructiva del sueñoe', 'DSM-5'),
('DSM-___.__', 'Apnea central del sueño', 'DSM-5'),
('327.21', 'Apnea central del sueño idiopática', 'DSM-5'),
('786.04', 'Respiración de Cheyne-Stokes', 'DSM-5'),
('780.57', 'Apnea central del sueño con consumo concurrente de opiáceos', 'DSM-5'),
('DSM-___.__', 'Hipoventilación relacionada con el sueño', 'DSM-5'),
('327.24', 'Hipoventilación idiopática', 'DSM-5')
ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, classification) VALUES
('327.25', 'Hipoventilación alveolar central congénita', 'DSM-5'),
('327.26', 'Hipoventilación concurrente relacionada con el sueño', 'DSM-5'),
('DSM-___.__', 'Trastornos del ritmo circadiano de sueño-vigilias', 'DSM-5'),
('307.45', 'Tipo de fase de sueño retrasada', 'DSM-5'),
('307.45', 'Tipo de fases de sueño avanzadas', 'DSM-5'),
('307.45', 'Tipo de sueño-vigilia irregular', 'DSM-5'),
('307.45', 'Tipo de sueño-vigilia no ajustado a las 24 horas', 'DSM-5'),
('307.45', 'Tipo asociado a turnos laborales', 'DSM-5'),
('307.45', 'Tipo no especificado', 'DSM-5'),
('DSM-___.__', 'Trastornos del despertar del sueño no REM', 'DSM-5'),
('307.46', 'comportamiento sexual relacionado con el sueño (sexsomnia)', 'DSM-5'),
('307.46', 'Trastorno de pesadillas''",', 'DSM-5'),
('307.47', 'Trastorno del comportamiento del sueño REM', 'DSM-5'),
('327.42', 'Síndrome de las piernas inquietas', 'DSM-5'),
('333.94', '___.__ (___.__)', 'DSM-5'),
('780.52', 'Otro trastorno de insomnio especificado', 'DSM-5'),
('780.52', 'Trastorno de insomnio no especificado', 'DSM-5'),
('780.54', 'Otro trastorno de hipersomnia especificado', 'DSM-5'),
('780.54', 'Trastorno de hipersomnia no especificado', 'DSM-5'),
('780.59', 'Otro trastorno del sueño-vigilia especificado', 'DSM-5'),
('780.59', 'Trastorno del sueño-vigilia no especificado', 'DSM-5'),
('302.74', 'Eyaculación retardadas, b, c', 'DSM-5'),
('302.72', 'Trastorno eréctila,b'' c', 'DSM-5'),
('302.73', 'Trastorno orgásmico femeninoa,b''c', 'DSM-5'),
('302.72', 'Trastorno del interés/excitación sexual femeninoa,b,c', 'DSM-5'),
('302.76', 'Trastorno de dolor génito-pélvico/penetracióna,  c', 'DSM-5'),
('302.71', 'Trastorno de deseo sexual hipoactivo en el varóna,b,''', 'DSM-5'),
('302.75', 'Eyaculación prematura (precoz)a, c', 'DSM-5'),
('DSM-___.__', 'Disfunción sexual inducida por sustancias/medicamentos', 'DSM-5'),
('302.79', 'Otra disfunción sexual especificada', 'DSM-5'),
('302.70', 'Disfunción sexual no especificada', 'DSM-5'),
('302.6', 'Disforia de género en niños', 'DSM-5'),
('302.85', 'Disforia de género en adolescentes y adultos', 'DSM-5'),
('302.6', 'Otra disforia de género especificada', 'DSM-5'),
('302.6', 'Disforia de género no especificada', 'DSM-5'),
('313.81', 'Trastorno negativista desafiante', 'DSM-5'),
('312.34', 'Trastorno explosivo intermitente', 'DSM-5'),
('DSM-___.__', 'Trastorno de la conducta', 'DSM-5'),
('312.81', 'Tipo de inicio infantil', 'DSM-5'),
('312.82', 'Tipo de inicio adolescente', 'DSM-5'),
('312.89', 'Tipo de inicio no especificado', 'DSM-5'),
('301.7', 'Trastorno de la personalidad antisocial', 'DSM-5'),
('312.33', 'Piromanía', 'DSM-5'),
('312.32', 'Cleptomanía', 'DSM-5'),
('312.89', 'Otro trastorno disruptivo, del control de los impulsos y de la conducta', 'DSM-5'),
('312.9', 'Trastorno disruptivo, del control de los impulsos y de la conducta', 'DSM-5'),
('305.00', 'Leve', 'DSM-5'),
('303.90', 'Moderado', 'DSM-5'),
('303.90', 'Grave', 'DSM-5'),
('DSM-F10.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F10.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F10.929', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F10.239', 'Sin alteraciones de la percepción', 'DSM-5'),
('DSM-F10.232', 'Con alteraciones de la percepción', 'DSM-5'),
('DSM-___.__', 'Otros trastornos inducidos por el alcohol', 'DSM-5'),
('291.9', 'Trastorno relacionado con el alcohol no especificado', 'DSM-5'),
('305.90', 'Intoxicación por cafeína', 'DSM-5'),
('292.0', 'Abstinencia de cafeína', 'DSM-5'),
('DSM-___.__', 'Otro trastorno inducido por la cafeína', 'DSM-5'),
('292.9', 'Trastorno relacionado con la cafeína no especificado', 'DSM-5'),
('DSM-___:__', 'Trastorno por consumo de cannabisa (509)•', 'DSM-5'),
('305.20', 'Leve', 'DSM-5'),
('304.30', 'Moderado', 'DSM-5'),
('304.30', 'Grave', 'DSM-5'),
('DSM-F12.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F12.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F12.929', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F12.122', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F12.222', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F12.922', 'Sin trastorno por consumo', 'DSM-5'),
('292.0', 'Abstinencia de cannabisd', 'DSM-5'),
('292.9', 'Trastorno relacionado con el cannabis no especificado', 'DSM-5'),
('305.90', 'Leve', 'DSM-5'),
('304.60', 'Moderado', 'DSM-5'),
('304.60', 'Grave', 'DSM-5'),
('305.30', '304.50 (F16.20)', 'DSM-5'),
('304.50', 'Grave', 'DSM-5'),
('DSM-F16.129', '(F16.229)', 'DSM-5'),
('DSM-F16.929', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F16.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F16.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F16.929', 'Trastorno perceptivo persistente por alucinógenos', 'DSM-5'),
('292.89', 'Otros trastornos inducidos por fenciclidina', 'DSM-5'),
('292.9', 'Trastorno relacionado con los alucinógenos no especificado', 'DSM-5'),
('292.9', 'Trastornos relacionados con los inhalantes', 'DSM-5'),
('304.60', 'Intoxicación por inhalantes', 'DSM-5'),
('DSM-F18.129', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F18.229', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F18.929', 'Otros trastornos inducidos por inhalantes', 'DSM-5'),
('292.9', 'Trastornos relacio nados con los opiáceos', 'DSM-5'),
('305.50', 'Moderado', 'DSM-5'),
('304.00', 'Grave', 'DSM-5'),
('304.00', 'Intoxicación por opiáceos', 'DSM-5'),
('DSM-F11.129', '(F11.229)', 'DSM-5'),
('DSM-F11.929', 'Con alteraciones de la percepción', 'DSM-5'),
('DSM-F11.122', '(F11.222)', 'DSM-5'),
('DSM-F11.922', 'Abstinencia de opiáceosd', 'DSM-5'),
('292.0', 'Otros trastornos inducidos por opiáceos', 'DSM-5'),
('292.9', 'Trastornos relacionados con sedantes, hipnóticos o ansiolíticos', 'DSM-5'),
('305.40', 'Moderado', 'DSM-5')
ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, classification) VALUES
('304.10', 'Grave', 'DSM-5'),
('304.10', '292.89 (___.___)', 'DSM-5'),
('DSM-F13.129', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F13.229', '(F13.929)', 'DSM-5'),
('DSM-F13.239', 'Con alteraciones de la percepción', 'DSM-5'),
('DSM-F13.232', '___.__(___.__)       Otros trastornos inducidos por los sedantes, hipnóticos o ansiolíticos', 'DSM-5'),
('292.9', 'Trastorno relacionado con los sedantes, hipnóticos o ansiolíticos no', 'DSM-5'),
('305.70', 'Sustancia anfetamínica', 'DSM-5'),
('305.60', 'Cocaína', 'DSM-5'),
('305.70', 'Otro estimulante o un estimulante no especificado', 'DSM-5'),
('304.40', 'Sustancia anfetamínica', 'DSM-5'),
('304.20', 'Cocaína', 'DSM-5'),
('304.40', 'Otro estimulante o un estimulante no especificado', 'DSM-5'),
('DSM-F15.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F15.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F15.929', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F14.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F14.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F14.929', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F15.122', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F15.222', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F15.922', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F14.122', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F14.222', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F14.922', 'Sin trastorno por consumo', 'DSM-5'),
('DSM-F15.23', 'Anfetamina u otro estimulante', 'DSM-5'),
('DSM-F14.23', 'Cocaína', 'DSM-5'),
('DSM-F15.99', 'Anfetamina u otro estimulante', 'DSM-5'),
('DSM-F14.99', 'Cocaína', 'DSM-5'),
('305.1', 'Leve', 'DSM-5'),
('305.1', 'Moderado', 'DSM-5'),
('305.1', 'Grave', 'DSM-5'),
('292.0', 'Abstinencia de tabacos', 'DSM-5'),
('292.9', 'Trastorno relacionado con el tabaco no especificado', 'DSM-5'),
('304.90', 'Moderado', 'DSM-5'),
('304.90', 'Grave', 'DSM-5'),
('DSM-F19.129', 'Con trastorno por consumo, leve', 'DSM-5'),
('DSM-F19.229', 'Con trastorno por consumo, moderado o grave', 'DSM-5'),
('DSM-F19.929', 'Sin trastorno por consumo', 'DSM-5'),
('292.0', 'Abstinencia de otras sustancias (o sustancias desconocidas)''', 'DSM-5'),
('292.9', 'Trastorno relacionado con otras sustancias (o sustancias desconocidas) no', 'DSM-5'),
('312.31', 'Juego patológico''', 'DSM-5'),
('293.0', 'Delirium debido a otra afección médica', 'DSM-5'),
('293.0', 'Delirium debido a etiologías múltiples', 'DSM-5'),
('780.09', 'Otro delirium especificado', 'DSM-5'),
('780.09', 'Delirium no especificado', 'DSM-5'),
('331.0', 'enfermedad de Alzheimer.', 'DSM-5'),
('294.11', 'Con alteración del comportamiento', 'DSM-5'),
('294.10', 'Sin alteración del comportamiento', 'DSM-5'),
('331.0', 'la enfermedad de Alzheimer', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a la enfermedad de Alzheimera', 'DSM-5'),
('331.19', 'enfermedad', 'DSM-5'),
('DSM-G31.09', 'la enfermedad frontotemporal.', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a una degeneración del lóbulo', 'DSM-5'),
('331.82', 'la enfermedad por cuerpos de Lewy.', 'DSM-5'),
('294.11', 'Sin alteración del comportamiento', 'DSM-5'),
('294.10', 'Trastorno neurocognitivo mayor con cuerpos de Lewy posible"', 'DSM-5'),
('331.82', 'la enfermedad con cuerpos de Lewy.', 'DSM-5'),
('294.10', 'Trastorno neurocognitivo leve con cuerpos de Lewya', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo vascular mayor o leve', 'DSM-5'),
('290.40', '290.40 (F01.50)', 'DSM-5'),
('294.10', '331.83 (G31.84)', 'DSM-5'),
('294.11', '294.10 (F02.80)', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a un traumatismo cerebrala', 'DSM-5'),
('DSM-B20', 'la infección por VIH.', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a infección por VIHa', 'DSM-5'),
('DSM-___.__', 'Trastorno neurocognitivo mayor debido a enfermedad por prionesb', 'DSM-5'),
('046.79', 'enfermedad por priones.', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a enfermedad por prionesa', 'DSM-5'),
('332.0', 'enfermedad de Parkinson.', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a la enfermedad de Parkinsona', 'DSM-5'),
('333.4', 'enfermedad de Huntington.', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo leve debido a la enfermedad de Huntingtona', 'DSM-5'),
('294.10', 'Trastorno neurocognitivo leve debido a otra afección médica', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo mayor o leve debido a etiologías', 'DSM-5'),
('294.10', 'Trastorno neurocognitivo leve debido a etiologías múltiples''', 'DSM-5'),
('331.83', 'Trastorno neurocognitivo no especificado', 'DSM-5'),
('799.59', 'Trastorno neurocognitivo no especificado''', 'DSM-5'),
('301.0', 'Trastorno de la personalidad paranoide', 'DSM-5'),
('301.20', 'Trastorno de la personalidad esquízoide', 'DSM-5'),
('301.22', 'Trastorno de la personalidad esquizotípica', 'DSM-5'),
('301.83', 'Trastorno de la personalidad límite', 'DSM-5'),
('301.50', 'Trastorno de la personalidad histriónica', 'DSM-5'),
('301.81', 'Trastorno de la personalidad narcisista', 'DSM-5'),
('301.82', 'Trastorno de la personalidad evitativa', 'DSM-5'),
('301.6', 'Trastorno de la personalidad dependiente', 'DSM-5'),
('301.4', 'Trastorno de la personalidad obsesivo-compulsiva', 'DSM-5'),
('310.1', 'Cambio de la personalidad debido a otra afección médica', 'DSM-5'),
('301.89', 'Otro trastorno de la personalidad especificado', 'DSM-5'),
('301.9', 'Trastorno de la personalidad no especificado', 'DSM-5'),
('302.82', 'Trastorno de voyeurismoa', 'DSM-5'),
('302.4', 'Trastorno de exhibicionismo''', 'DSM-5'),
('302.89', 'Trastorno de frotteurismoa', 'DSM-5'),
('302.83', 'Trastorno de masoquismo sexual''', 'DSM-5'),
('302.84', 'Trastorno de sadismo sexual''', 'DSM-5'),
('302.2', 'Trastorno de pedofilia', 'DSM-5'),
('302.81', 'Trastorno de fetichismo''', 'DSM-5'),
('302.3', 'Trastorno de travestismoa', 'DSM-5'),
('302.89', 'Otro trastorno parafílico especificado', 'DSM-5'),
('302.9', 'Trastorno parafílico no especificado', 'DSM-5')
ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, classification) VALUES
('294.8', 'Otro trastorno mental especificado debido a otra afección médica', 'DSM-5'),
('294.9', 'Trastorno mental no especificado debido a otra afección médica', 'DSM-5'),
('300.9', 'Otro trastorno mental especificado', 'DSM-5'),
('300.9', 'Trastorno mental no especificado', 'DSM-5'),
('332.1', 'Parkinsonismo inducido por neurolépticos', 'DSM-5'),
('332.1', 'Parkinsonismo inducido por otros medicamentos', 'DSM-5'),
('333.92', 'Síndrome neuroléptico maligno', 'DSM-5'),
('333.72', 'Distonía aguda inducida por medicamentos', 'DSM-5'),
('333.99', 'Acatisia aguda inducida por medicamentos', 'DSM-5'),
('333.85', 'Discinesia tardía', 'DSM-5'),
('333.72', 'Distonía tardía', 'DSM-5'),
('333.99', 'Acatisia tardía', 'DSM-5'),
('333.1', 'Temblor postural inducido por medicamentos', 'DSM-5'),
('333.99', 'Otro trastorno motor inducido por medicamentos', 'DSM-5'),
('DSM-___.__', 'Síndrome de suspensión de antidepresivos', 'DSM-5'),
('DSM-Z62.820', 'Problema de relación entre padres e hijos', 'DSM-5'),
('DSM-Z62.891', 'Problema de relación con los hermanos', 'DSM-5'),
('DSM-Z62.29', 'Educación lejos de los padres', 'DSM-5'),
('DSM-Z62.898', 'Niño afectado por una relación parental conflictiva', 'DSM-5'),
('DSM-Z63.0', 'Relación conflictiva con el cónyuge o la pareja', 'DSM-5'),
('DSM-Z63.5', 'Ruptura familiar por separación o divorcio', 'DSM-5'),
('DSM-Z63.8', 'Nivel elevado de emoción expresada en la familia', 'DSM-5'),
('DSM-Z63.4', 'Duelo no complicado', 'DSM-5'),
('DSM-Z69.010', 'Visita de salud mental para la víctima de maltrato infantil por parte de los padres', 'DSM-5'),
('DSM-Z69.020', 'Visita de salud mental para la víctima de maltrato infantil no parental', 'DSM-5'),
('DSM-Z62.810', 'Historia personal (antecedentes) de maltrato físico infantil', 'DSM-5'),
('DSM-Z69.011', 'Visita de salud mental para el autor de maltrato infantil parental', 'DSM-5'),
('DSM-Z69.021', 'Visita de salud mental para el autor de maltrato infantil no parental', 'DSM-5'),
('DSM-Z69.010', 'Visita de salud mental para la víctima de abuso sexual infantil por parte de los', 'DSM-5'),
('DSM-Z69.020', 'Visita de salud mental para la víctima de abuso sexual infantil no parental', 'DSM-5'),
('DSM-Z62.810', 'Historia personal (antecedentes) de abuso sexual infantil', 'DSM-5'),
('DSM-Z69.011', 'Visita de salud mental para el autor de abuso sexual infantil parental', 'DSM-5'),
('DSM-Z69.021', 'Visita de salud mental para el autor de abuso sexual infantil no parental', 'DSM-5'),
('DSM-Z69.010', 'Visita de salud mental para la víctima de negligencia infantil no parental', 'DSM-5'),
('DSM-Z69.020', 'Historia personal (antecedentes) de negligencia infantil', 'DSM-5'),
('DSM-Z62.812', 'Visita de salud mental para el autor de negligencia infantil parental', 'DSM-5'),
('DSM-Z69.011', 'Visita de salud mental para el autor de negligencia infantil no parental', 'DSM-5'),
('DSM-Z69.021', 'Maltrato psicológico infantil', 'DSM-5'),
('DSM-Z69.010', 'Visita de salud mental para la víctima de maltrato psicológico infantil no', 'DSM-5'),
('DSM-Z69.020', 'V15.42 (Z62.811)', 'DSM-5'),
('DSM-Z69.011', 'Visita de salud mental para el autor de maltrato psicológico infantil parental', 'DSM-5'),
('DSM-Z69.021', 'Visita de salud mental para el autor de maltrato psicológico infantil no', 'DSM-5'),
('DSM-Z69.11', 'Visita de salud mental para la víctima de violencia física por parte del', 'DSM-5'),
('DSM-Z91.410', 'Historia personal (antecedentes) de violencia física por parte del cónyuge o la', 'DSM-5'),
('DSM-Z69.12', 'Visita de salud mental para el autor de violencia física hacia el cónyuge o la', 'DSM-5'),
('DSM-Z69.81', 'Visita de salud mental para la víctima de violencia sexual por parte del', 'DSM-5'),
('DSM-Z91.410', 'Historia personal (antecedentes) de violencia sexual por parte del cónyuge', 'DSM-5'),
('DSM-Z69.12', 'Visita de salud mental para el autor de violencia sexual por parte del cónyuge', 'DSM-5'),
('DSM-Z69.11', 'Visita de salud mental para la víctima de negligencia por parte del cónyuge', 'DSM-5'),
('DSM-Z91.412', 'Historia personal (antecedentes) de negligencia por parte del cónyuge o la', 'DSM-5'),
('DSM-Z69.12', 'Visita de salud mental para el autor de negligencia por parte del cónyuge', 'DSM-5')
ON CONFLICT (code) DO NOTHING;
COMMIT;
