BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('4A85.01', 'Nefropatía por hipersensibilidad provocada por medicamentos', 'category', false, false, 'CIE-11'),
('4A85.02', 'Citopenia provocada por medicamentos', 'category', false, false, 'CIE-11'),
('4A85.03', 'Vasculitis provocada por medicamentos', 'category', false, false, 'CIE-11'),
('4A85.04', 'Síndrome de hipersensibilidad a múltiples medicamentos', 'category', false, false, 'CIE-11'),
('4A85.0Y', 'Otra hipersensibilidad especificada a medicamentos o agentes farmacológicos', 'category', false, false, 'CIE-11'),
('4A85.0Z', 'Hipersensibilidad a medicamentos o agentes farmacológicos, sin especificación', 'category', false, false, 'CIE-11'),
('4A85.1', 'Hipersensibilidad a plantas medicinales y terapias médicas alternativas', 'category', false, false, 'CIE-11'),
('4A85.2', 'Hipersensibilidad alimentaria', 'category', false, false, 'CIE-11'),
('4A85.20', 'Hipersensibilidad gastrointestinal inducida por alimentos', 'category', false, false, 'CIE-11'),
('4A85.21', 'Urticaria o angioedema inducidos por alimentos', 'category', false, false, 'CIE-11'),
('4A85.22', 'Dermatitis de contacto alérgica por alérgenos alimentarios', 'category', false, false, 'CIE-11'),
('4A85.2Y', 'Otra hipersensibilidad alimentaria especificada', 'category', false, false, 'CIE-11'),
('4A85.2Z', 'Hipersensibilidad alimentaria, sin especificación', 'category', false, false, 'CIE-11'),
('4A85.3', 'Reacciones alérgicas o de hipersensibilidad a los artrópodos', 'category', false, false, 'CIE-11'),
('4A85.30', 'Reacción alérgica sistémica por veneno de himenópteros', 'category', false, false, 'CIE-11'),
('4A85.31', 'Reacciones cutáneas alérgicas o de hipersensibilidad al veneno de himenópteros', 'category', false, false, 'CIE-11'),
('4A85.32', 'Reacciones cutáneas alérgicas o de hipersensibilidad a los artrópodos', 'category', false, false, 'CIE-11'),
('4A85.Y', 'Otras trastornos alérgicos o de hipersensibilidad complejos especificados', 'category', false, false, 'CIE-11'),
('4A85.Z', 'Trastornos alérgicos o de hipersensibilidad complejos, sin especificación', 'category', false, false, 'CIE-11'),
('4A8Y', 'Otras afecciones alérgicas o de hipersensibilidad especificadas', 'category', false, false, 'CIE-11'),
('4A8Z', 'Afecciones alérgicas o de hipersensibilidad, sin especificación', 'category', false, false, 'CIE-11'),
('4B00', 'Trastornos del número de neutrófilos', 'category', false, false, 'CIE-11'),
('4B00.0', 'Neutropenia', 'category', false, false, 'CIE-11'),
('4B00.00', 'Neutropenia constitucional', 'category', false, false, 'CIE-11'),
('4B00.01', 'Neutropenia adquirida', 'category', false, false, 'CIE-11'),
('4B00.0Z', 'Neutropenia, sin especificación', 'category', false, false, 'CIE-11'),
('4B00.1', 'Neutrofilia', 'category', false, false, 'CIE-11'),
('4B00.10', 'Neutrofilia constitucional', 'category', false, false, 'CIE-11'),
('4B00.11', 'Neutrofilia adquirida', 'category', false, false, 'CIE-11'),
('4B00.1Z', 'Neutrofilia, sin especificación', 'category', false, false, 'CIE-11'),
('4B00.Y', 'Otros trastornos especificados del número de neutrófilos', 'category', false, false, 'CIE-11'),
('4B01', 'Trastornos de la función de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.0', 'Trastornos constitucionales de la función de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.00', 'Trastornos de la adhesión de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.01', 'Trastornos de la quimiotaxis de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.02', 'Trastornos de la formación o liberación de gránulos de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.03', 'Trastorno del metabolismo oxidativo de neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.0Y', 'Otros trastornos constitucionales especificados de la función de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.0Z', 'Trastornos constitucionales de la función de los neutrófilos, sin especificación', 'category', false, false, 'CIE-11'),
('4B01.1', 'Trastornos adquiridos de la función de los neutrófilos', 'category', false, false, 'CIE-11'),
('4B01.Z', 'Trastornos de la función de los neutrófilos, sin especificación', 'category', false, false, 'CIE-11'),
('4B02', 'Eosinopenia', 'category', false, false, 'CIE-11'),
('4B02.0', 'Disminución constitucional del número de eosinófilos', 'category', false, false, 'CIE-11'),
('4B02.1', 'Disminución adquirida del número de eosinófilos', 'category', false, false, 'CIE-11'),
('4B02.Z', 'Eosinopenia, sin especificación', 'category', false, false, 'CIE-11'),
('4B03', 'Eosinofilia', 'category', false, false, 'CIE-11'),
('4B03.0', 'Eosinofilia constitucional', 'category', false, false, 'CIE-11'),
('4B03.1', 'Eosinofilia adquirida', 'category', false, false, 'CIE-11'),
('4B03.Z', 'Eosinofilia, sin especificación', 'category', false, false, 'CIE-11'),
('4B04', 'Trastornos con disminución del número de monocitos', 'category', false, false, 'CIE-11'),
('4B05', 'Trastornos con aumento del número de monocitos', 'category', false, false, 'CIE-11'),
('4B06', 'Linfopenia adquirida', 'category', false, false, 'CIE-11'),
('4B07', 'Linfocitosis adquirida', 'category', false, false, 'CIE-11'),
('4B0Y', 'Otros trastornos especificados del sistema inmunitario con implicación de los linajes de leucocitos', 'category', false, false, 'CIE-11'),
('4B0Z', 'Trastornos del sistema inmunitario con implicación de los linajes de leucocitos, sin especificación', 'category', false, false, 'CIE-11'),
('4B20', 'Sarcoidosis', 'category', false, false, 'CIE-11'),
('4B20.0', 'sarcoidosis pulmonar', 'category', false, false, 'CIE-11'),
('4B20.1', 'Sarcoidosis de los ganglios linfáticos', 'category', false, false, 'CIE-11'),
('4B20.2', 'Sarcoidosis del aparato digestivo', 'category', false, false, 'CIE-11'),
('4B20.3', 'Neurosarcoidosis', 'category', false, false, 'CIE-11'),
('4B20.4', 'Sarcoidosis ocular', 'category', false, false, 'CIE-11'),
('4B20.5', 'Sarcoidosis cutánea', 'category', false, false, 'CIE-11'),
('4B20.Y', 'Otra sarcoidosis especificada', 'category', false, false, 'CIE-11'),
('4B20.Z', 'Sarcoidosis, sin especificación', 'category', false, false, 'CIE-11'),
('4B21', 'Hipergammaglobulinemia policlonal', 'category', false, false, 'CIE-11'),
('4B22', 'Crioglobulinemia', 'category', false, false, 'CIE-11'),
('4B23', 'Síndrome inflamatorio de reconstitución inmunitaria', 'category', false, false, 'CIE-11'),
('4B24', 'Enfermedad de injerto contra huésped', 'category', false, false, 'CIE-11'),
('4B24.0', 'Enfermedad aguda de injerto contra huésped', 'category', false, false, 'CIE-11'),
('4B24.1', 'Enfermedad crónica de injerto contra huésped', 'category', false, false, 'CIE-11'),
('4B24.Y', 'Otra enfermedad especificada de injerto contra huésped', 'category', false, false, 'CIE-11'),
('4B24.Z', 'Enfermedad de injerto contra huésped, sin especificación', 'category', false, false, 'CIE-11'),
('4B2Y', 'Otros trastornos especificados que afectan el sistema inmunitario', 'category', false, false, 'CIE-11'),
('4B40', 'Enfermedades del timo', 'category', false, false, 'CIE-11'),
('4B40.0', 'Hiperplasia persistente del timo', 'category', false, false, 'CIE-11'),
('4B40.1', 'Absceso del timo', 'category', false, false, 'CIE-11'),
('4B40.2', 'Síndrome de Good', 'category', false, false, 'CIE-11'),
('4B40.Y', 'Otras enfermedades especificadas del timo', 'category', false, false, 'CIE-11'),
('4B40.Z', 'Enfermedades del timo, sin especificación', 'category', false, false, 'CIE-11'),
('4B4Y', 'Otras enfermedades especificadas del sistema inmunitario', 'category', false, false, 'CIE-11'),
('4B4Z', 'Enfermedades del sistema inmunitario, sin especificación', 'category', false, false, 'CIE-11'),
('5A00', 'Hipotiroidismo', 'category', false, false, 'CIE-11'),
('5A00.0', 'Hipotiroidismo congénito', 'category', false, false, 'CIE-11'),
('5A00.00', 'Hipotiroidismo congénito permanente con bocio difuso', 'category', false, false, 'CIE-11'),
('5A00.01', 'Hipotiroidismo congénito permanente sin bocio', 'category', false, false, 'CIE-11'),
('5A00.02', 'Síndrome de Pendred', 'category', false, false, 'CIE-11'),
('5A00.03', 'Hipotiroidismo congénito transitorio', 'category', false, false, 'CIE-11'),
('5A00.04', 'Hipotiroidismo congénito por carencia de yodo', 'category', false, false, 'CIE-11'),
('5A00.0Y', 'Otro hipotiroidismo congénito especificado', 'category', false, false, 'CIE-11'),
('5A00.0Z', 'Hipotiroidismo congénito, sin especificación', 'category', false, false, 'CIE-11'),
('5A00.1', 'Trastornos tiroideos por carencia de yodo o problemas afines', 'category', false, false, 'CIE-11'),
('5A00.10', 'Bocio difuso por carencia de yodo', 'category', false, false, 'CIE-11'),
('5A00.11', 'Bocio multinodular por carencia de yodo', 'category', false, false, 'CIE-11'),
('5A00.1Z', 'Trastornos tiroideos relacionados con la carencia de yodo o con problemas afines, sin especificación', 'category', false, false, 'CIE-11'),
('5A00.2', 'Hipotiroidismo adquirido', 'category', false, false, 'CIE-11'),
('5A00.20', 'Hipotiroidismo por el uso de medicamentos o de otras sustancias exógenas', 'category', false, false, 'CIE-11'),
('5A00.21', 'Coma por mixedema', 'category', false, false, 'CIE-11'),
('5A00.22', 'Hipotiroidismo asintomático por carencia de yodo', 'category', false, false, 'CIE-11'),
('5A00.2Y', 'Otro hipotiroidismo adquirido especificado', 'category', false, false, 'CIE-11'),
('5A00.2Z', 'Hipotiroidismo adquirido, sin especificación', 'category', false, false, 'CIE-11'),
('5A00.Z', 'Hipotiroidismo, sin especificación', 'category', false, false, 'CIE-11'),
('5A01', 'Bocio atóxico', 'category', false, false, 'CIE-11'),
('5A01.0', 'Bocio difuso no tóxico', 'category', false, false, 'CIE-11'),
('5A01.1', 'Nódulo tiroideo solitario atóxico', 'category', false, false, 'CIE-11'),
('5A01.2', 'Bocio multinodular atóxico', 'category', false, false, 'CIE-11'),
('5A01.Z', 'Bocio atóxico, sin especificación', 'category', false, false, 'CIE-11'),
('5A02', 'Tirotoxicosis', 'category', false, false, 'CIE-11'),
('5A02.0', 'Tirotoxicosis con bocio difuso', 'category', false, false, 'CIE-11'),
('5A02.1', 'Tirotoxicosis con nódulo tiroideo único tóxico', 'category', false, false, 'CIE-11'),
('5A02.2', 'Tirotoxicosis con bocio multinodular tóxico', 'category', false, false, 'CIE-11'),
('5A02.3', 'Tirotoxicosis por tejido tiroideo ectópico', 'category', false, false, 'CIE-11'),
('5A02.4', 'Tirotoxicosis facticia', 'category', false, false, 'CIE-11'),
('5A02.5', 'Crisis tiroidea', 'category', false, false, 'CIE-11'),
('5A02.6', 'Hipertiroidismo secundario', 'category', false, false, 'CIE-11'),
('5A02.Y', 'Otra tirotoxicosis especificada', 'category', false, false, 'CIE-11'),
('5A02.Z', 'Tirotoxicosis, sin especificación', 'category', false, false, 'CIE-11'),
('5A03', 'Tiroiditis', 'category', false, false, 'CIE-11'),
('5A03.0', 'Tiroiditis aguda', 'category', false, false, 'CIE-11'),
('5A03.1', 'Tiroiditis subaguda', 'category', false, false, 'CIE-11'),
('5A03.2', 'Tiroiditis autoinmune', 'category', false, false, 'CIE-11'),
('5A03.20', 'Tiroiditis de Hashimoto', 'category', false, false, 'CIE-11'),
('5A03.21', 'Tiroiditis indolora', 'category', false, false, 'CIE-11'),
('5A03.2Y', 'Otra tiroiditis autoinmune especificada', 'category', false, false, 'CIE-11'),
('5A03.2Z', 'Tiroiditis autoinmune, sin especificación', 'category', false, false, 'CIE-11'),
('5A03.Y', 'Otra tiroiditis especificada', 'category', false, false, 'CIE-11'),
('5A03.Z', 'Tiroiditis, sin especificación', 'category', false, false, 'CIE-11'),
('5A04', 'Hipersecreción de calcitonina', 'category', false, false, 'CIE-11'),
('5A05', 'Resistencia generalizada a la hormona tiroidea', 'category', false, false, 'CIE-11'),
('5A06', 'Síndrome del enfermo eutiroideo', 'category', false, false, 'CIE-11'),
('5A0Y', 'Otros trastornos especificados de la glándula tiroides o del sistema de hormonas tiroideas', 'category', false, false, 'CIE-11'),
('5A0Z', 'Trastornos de la glándula tiroides o del sistema de hormonas tiroideas, sin especificación', 'category', false, false, 'CIE-11'),
('5A10', 'Diabetes mellitus tipo 1', 'category', false, false, 'CIE-11'),
('5A11', 'Diabetes mellitus tipo 2', 'category', false, false, 'CIE-11'),
('5A12', 'Diabetes mellitus por malnutrición', 'category', false, false, 'CIE-11'),
('5A13', 'Diabetes mellitus, otro tipo especificado', 'category', false, false, 'CIE-11'),
('5A13.0', 'Diabetes mellitus por defectos genéticos de la función de las células beta', 'category', false, false, 'CIE-11'),
('5A13.1', 'Diabetes mellitus por defectos genéticos de la actividad de la insulina', 'category', false, false, 'CIE-11'),
('5A13.2', 'Diabetes mellitus por enfermedades del páncreas exocrino', 'category', false, false, 'CIE-11'),
('5A13.3', 'Diabetes mellitus por endocrinopatías', 'category', false, false, 'CIE-11'),
('5A13.4', 'Diabetes mellitus por efecto de medicamentos o sustancias químicas', 'category', false, false, 'CIE-11'),
('5A13.5', 'Diabetes mellitus por tipos poco comunes de diabetes inmunomediada', 'category', false, false, 'CIE-11'),
('5A13.6', 'Diabetes mellitus por otros síndromes genéticos', 'category', false, false, 'CIE-11'),
('5A13.7', 'Diabetes mellitus debida a subtipos o síndromes con características clínicas definidas', 'category', false, false, 'CIE-11'),
('5A13.Y', 'Otra diabetes mellitus especificada, otro tipo especificado', 'category', false, false, 'CIE-11'),
('5A14', 'Diabetes mellitus, tipo no especificado', 'category', false, false, 'CIE-11'),
('5A20', 'Estado hiperglucémico hiperosmolar diabético', 'category', false, false, 'CIE-11'),
('5A20.0', 'Estado hiperglucémico hiperosmolar sin coma', 'category', false, false, 'CIE-11'),
('5A20.1', 'Estado hiperglucémico hiperosmolar con coma', 'category', false, false, 'CIE-11'),
('5A20.Z', 'Estado hiperglucémico hiperosmolar diabético, sin especificación', 'category', false, false, 'CIE-11'),
('5A21', 'Hipoglucemia en el contexto de la diabetes mellitus', 'category', false, false, 'CIE-11'),
('5A21.0', 'Hipoglucemia en el contexto de la diabetes mellitus sin coma', 'category', false, false, 'CIE-11'),
('5A21.1', 'Hipoglucemia en el contexto de la diabetes mellitus con coma', 'category', false, false, 'CIE-11'),
('5A21.Z', 'Hipoglucemia en el contexto de la diabetes mellitus, sin especificación', 'category', false, false, 'CIE-11'),
('5A22', 'Acidosis diabética', 'category', false, false, 'CIE-11'),
('5A22.0', 'Cetoacidosis diabética sin coma', 'category', false, false, 'CIE-11'),
('5A22.1', 'Acidosis láctica diabética', 'category', false, false, 'CIE-11'),
('5A22.2', 'Acidosis metabólica diabética', 'category', false, false, 'CIE-11'),
('5A22.3', 'Cetoacidosis diabética con coma', 'category', false, false, 'CIE-11'),
('5A22.Y', 'Otra acidosis diabética especificada', 'category', false, false, 'CIE-11'),
('5A22.Z', 'Acidosis diabética, sin especificación', 'category', false, false, 'CIE-11'),
('5A23', 'Coma diabético', 'category', false, false, 'CIE-11'),
('5A24', 'Diabetes mellitus no controlada o inestable', 'category', false, false, 'CIE-11'),
('5A2Y', 'Otras complicaciones agudas especificadas de la diabetes mellitus', 'category', false, false, 'CIE-11'),
('5A40', 'Hiperglucemia intermedia', 'category', false, false, 'CIE-11'),
('5A40.0', 'Alteración de la glucemia en ayunas', 'category', false, false, 'CIE-11'),
('5A40.1', 'Tolerancia alterada a la glucosa', 'category', false, false, 'CIE-11'),
('5A40.Y', 'Otra hiperglucemia intermedia especificada', 'category', false, false, 'CIE-11'),
('5A40.Z', 'Hiperglucemia intermedia, sin especificación', 'category', false, false, 'CIE-11'),
('5A41', 'Hipoglucemia sin diabetes asociada', 'category', false, false, 'CIE-11'),
('5A42', 'Aumento de la secreción de glucagón', 'category', false, false, 'CIE-11'),
('5A43', 'Secreción anormal de gastrina', 'category', false, false, 'CIE-11'),
('5A43.0', 'Hipergastrinemia provocada por medicamentos', 'category', false, false, 'CIE-11'),
('5A43.1', 'Síndrome de Zollinger-Ellison', 'category', false, false, 'CIE-11'),
('5A43.Y', 'Otra secreción anormal especificada de gastrina', 'category', false, false, 'CIE-11'),
('5A43.Z', 'Secreción anormal de gastrina, sin especificación', 'category', false, false, 'CIE-11'),
('5A44', 'Síndromes de resistencia a la insulina', 'category', false, false, 'CIE-11'),
('5A45', 'Hipoglucemia hiperinsulinémica persistente de la infancia', 'category', false, false, 'CIE-11'),
('5A4Y', 'Otros trastornos especificados de la regulación de la glucosa o de la secreción pancreática interna', 'category', false, false, 'CIE-11'),
('5A4Z', 'Otros trastornos de la regulación de la glucosa o de la secreción pancreática interna, sin especificación', 'category', false, false, 'CIE-11'),
('5A50', 'Hipoparatiroidismo', 'category', false, false, 'CIE-11'),
('5A50.0', 'Hipoparatiroidismo por alteración de la secreción de la hormona paratiroidea', 'category', false, false, 'CIE-11'),
('5A50.00', 'Hipoparatiroidismo idiopático', 'category', false, false, 'CIE-11'),
('5A50.01', 'Hipoparatiroidismo secundario', 'category', false, false, 'CIE-11'),
('5A50.02', 'Hipoparatiroidismo por destrucción de las glándulas paratiroides', 'category', false, false, 'CIE-11'),
('5A50.03', 'Hipoparatiroidismo autoinmunitario', 'category', false, false, 'CIE-11'),
('5A50.0Y', 'Otro hipoparatiroidismo especificado por alteración de la secreción de la hormona paratiroidea', 'category', false, false, 'CIE-11'),
('5A50.0Z', 'Hipoparatiroidismo por alteración de la secreción de hormona paratiroidea, sin especificación', 'category', false, false, 'CIE-11'),
('5A50.1', 'Seudohipoparatiroidismo', 'category', false, false, 'CIE-11'),
('5A50.Y', 'Otro hipoparatiroidismo especificado', 'category', false, false, 'CIE-11'),
('5A50.Z', 'Hipoparatiroidismo, sin especificación', 'category', false, false, 'CIE-11'),
('5A51', 'Hiperparatiroidismo', 'category', false, false, 'CIE-11'),
('5A51.0', 'Hiperparatiroidismo primario', 'category', false, false, 'CIE-11'),
('5A51.1', 'Hiperparatiroidismo secundario', 'category', false, false, 'CIE-11'),
('5A51.2', 'Hipercalcemia hipocalciúrica familiar', 'category', false, false, 'CIE-11'),
('5A51.Y', 'Otro hiperparatiroidismo especificado', 'category', false, false, 'CIE-11'),
('5A51.Z', 'Hiperparatiroidismo, sin especificación', 'category', false, false, 'CIE-11'),
('5A5Y', 'Otros trastornos especificados del sistema de la hormona paratiroidea o de la glándulas paratiroides', 'category', false, false, 'CIE-11'),
('5A5Z', 'Trastornos del sistema de la hormona paratiroidea o de la paratiroides, sin especificación', 'category', false, false, 'CIE-11'),
('5A60', 'Hiperfunción de la glándula hipofisaria', 'category', false, false, 'CIE-11'),
('5A60.0', 'Acromegalia o gigantismo hipofisario', 'category', false, false, 'CIE-11'),
('5A60.1', 'Hiperprolactinemia', 'category', false, false, 'CIE-11'),
('5A60.2', 'Síndrome de secreción inadecuada de hormona antidiurética', 'category', false, false, 'CIE-11'),
('5A60.20', 'Síndrome nefrógeno de antidiuresis inapropiada', 'category', false, false, 'CIE-11'),
('5A60.2Y', 'Otro síndrome especificado de secreción inadecuada de hormona antidiurética', 'category', false, false, 'CIE-11'),
('5A60.2Z', 'Síndrome de secreción inadecuada de hormona antidiurética, sin especificación', 'category', false, false, 'CIE-11'),
('5A60.3', 'Pubertad precoz central', 'category', false, false, 'CIE-11'),
('5A60.Y', 'Otra hiperfunción especificada de la glándula hipofisaria', 'category', false, false, 'CIE-11'),
('5A60.Z', 'Hiperfunción de la glándula hipofisaria, sin especificación', 'category', false, false, 'CIE-11'),
('5A61', 'Hipofunción o algunos otros trastornos especificados de la hipófisis', 'category', false, false, 'CIE-11'),
('5A61.0', 'Hipopituitarismo', 'category', false, false, 'CIE-11'),
('5A61.1', 'Insuficiencia de adrenocorticotrofina', 'category', false, false, 'CIE-11'),
('5A61.2', 'Insuficiencia de gonadotrofinas', 'category', false, false, 'CIE-11'),
('5A61.3', 'Insuficiencia de la hormona de crecimiento', 'category', false, false, 'CIE-11'),
('5A61.4', 'Deficiencia de la hormona estimulante de la tiroides', 'category', false, false, 'CIE-11'),
('5A61.40', 'Hipotiroidismo central adquirido', 'category', false, false, 'CIE-11'),
('5A61.41', 'Hipotiroidismo central congénito', 'category', false, false, 'CIE-11'),
('5A61.4Y', 'Otra deficiencia especificada de la hormona estimulante de la tiroides', 'category', false, false, 'CIE-11'),
('5A61.4Z', 'Deficiencia de la hormona estimulante de la tiroides, sin especificación', 'category', false, false, 'CIE-11'),
('5A61.5', 'Diabetes insípida central', 'category', false, false, 'CIE-11'),
('5A61.6', 'Insuficiencia de oxitocina', 'category', false, false, 'CIE-11'),
('5A61.Y', 'Otra hipofunción especificada u otros trastornos de la glándula hipófisis', 'category', false, false, 'CIE-11'),
('5A6Z', 'Trastornos del sistema de la hormona hipofisaria, sin especificación', 'category', false, false, 'CIE-11'),
('5A70', 'Síndrome de Cushing', 'category', false, false, 'CIE-11'),
('5A70.0', 'Enfermedad de Cushing dependiente de la hipófisis', 'category', false, false, 'CIE-11'),
('5A70.1', 'Síndrome de ACTH ectópica', 'category', false, false, 'CIE-11'),
('5A70.2', 'Síndrome de pseudo-Cushing', 'category', false, false, 'CIE-11'),
('5A70.3', 'Síndrome de Nelson', 'category', false, false, 'CIE-11'),
('5A70.Y', 'Otro síndrome de Cushing especificado', 'category', false, false, 'CIE-11'),
('5A70.Z', 'Síndrome de Cushing, sin especificación', 'category', false, false, 'CIE-11'),
('5A71', 'Trastornos adrenogenitales', 'category', false, false, 'CIE-11'),
('5A71.0', 'Trastornos del desarrollo sexual 46,XX provocados por andrógenos de origen fetal', 'category', false, false, 'CIE-11'),
('5A71.00', 'Resistencia a los glucocorticoides', 'category', false, false, 'CIE-11'),
('5A71.01', 'Hiperplasia suprarrenal congénita', 'category', false, false, 'CIE-11'),
('5A71.0Y', 'Otros trastornos especificados del desarrollo sexual 46,XX provocados por andrógenos de origen fetal', 'category', false, false, 'CIE-11'),
('5A71.0Z', 'Trastornos de 46,XX del desarrollo sexual provocados por andrógenos de origen fetal', 'category', false, false, 'CIE-11'),
('5A71.1', 'Trastornos del desarrollo sexual 46,XX provocados por andrógenos de origen materno', 'category', false, false, 'CIE-11'),
('5A71.Y', 'Otros trastornos adrenogenitales especificados', 'category', false, false, 'CIE-11'),
('5A71.Z', 'Trastornos adrenogenitales, sin especificación', 'category', false, false, 'CIE-11'),
('5A72', 'Hiperaldosteronismo', 'category', false, false, 'CIE-11'),
('5A72.0', 'Hiperaldosteronismo primario', 'category', false, false, 'CIE-11'),
('5A72.1', 'Hiperaldosteronismo secundario', 'category', false, false, 'CIE-11'),
('5A72.Z', 'Hiperaldosteronismo, sin especificación', 'category', false, false, 'CIE-11'),
('5A73', 'Hipoaldosteronismo', 'category', false, false, 'CIE-11'),
('5A74', 'Insuficiencia adrenocortical', 'category', false, false, 'CIE-11'),
('5A74.0', 'Insuficiencia adrenocortical adquirida', 'category', false, false, 'CIE-11'),
('5A74.1', 'Crisis adrenal', 'category', false, false, 'CIE-11'),
('5A74.Y', 'Otra insuficiencia adrenocortical especificada', 'category', false, false, 'CIE-11'),
('5A74.Z', 'Insuficiencia adrenocortical, sin especificación', 'category', false, false, 'CIE-11'),
('5A75', 'Hiperfunción medulosuprarrenal', 'category', false, false, 'CIE-11'),
('5A76', 'Algunos trastornos especificados de la glándula suprarrenal', 'category', false, false, 'CIE-11'),
('5A76.0', 'Adrenarquia prematura', 'category', false, false, 'CIE-11'),
('5A76.Y', 'Algunos otros trastornos especificados de la glándula suprarrenal', 'category', false, false, 'CIE-11'),
('5A7Z', 'Trastornos de las glándulas suprarrenales o del sistema hormona suprarrenal, sin especificación', 'category', false, false, 'CIE-11'),
('5A80', 'Disfunción ovárica', 'category', false, false, 'CIE-11'),
('5A80.0', 'Hiperandrogenismo clínico', 'category', false, false, 'CIE-11'),
('5A80.1', 'Síndrome del ovario poliquístico', 'category', false, false, 'CIE-11'),
('5A80.2', 'Ovario poliquístico', 'category', false, false, 'CIE-11'),
('5A80.3', 'Anovulación', 'category', false, false, 'CIE-11'),
('5A80.4', 'Oligoovulación', 'category', false, false, 'CIE-11'),
('5A80.5', 'Reserva ovárica disminuida', 'category', false, false, 'CIE-11'),
('5A80.Y', 'Otra disfunción ovárica especificada', 'category', false, false, 'CIE-11'),
('5A80.Z', 'Disfunción ovárica, sin especificación', 'category', false, false, 'CIE-11'),
('5A81', 'Disfunción testicular o trastornos de origen testosterónico', 'category', false, false, 'CIE-11'),
('5A81.0', 'Hiperfunción testicular', 'category', false, false, 'CIE-11'),
('5A81.1', 'Hipofunción testicular', 'category', false, false, 'CIE-11'),
('5A81.Y', 'Otra disfunción testicular especificada o trastornos relacionados con la testosterona', 'category', false, false, 'CIE-11'),
('5A81.Z', 'Disfunción testicular o trastornos relacionados con la testosterona, sin especificación', 'category', false, false, 'CIE-11'),
('5A8Z', 'Trastornos del sistema hormonal gonadal, sin especificación', 'category', false, false, 'CIE-11'),
('5A90', 'Trastorno de la pubertad por resistencia a los estrógenos', 'category', false, false, 'CIE-11'),
('5A91', 'Pubertad retrasada', 'category', false, false, 'CIE-11'),
('5A92', 'Pubertad precoz periférica', 'category', false, false, 'CIE-11'),
('5A9Y', 'Otros trastornos especificados de la pubertad', 'category', false, false, 'CIE-11'),
('5A9Z', 'Trastornos de la pubertad, sin especificación', 'category', false, false, 'CIE-11'),
('5B00', 'Poliendocrinopatía autoinmunitaria', 'category', false, false, 'CIE-11'),
('5B01', 'Hiperfunción poliglandular', 'category', false, false, 'CIE-11'),
('5B0Y', 'Otra disfunción poliglandular especificada', 'category', false, false, 'CIE-11'),
('5B0Z', 'Disfunción poliglandular, sin especificación', 'category', false, false, 'CIE-11'),
('5B10', 'Síndrome carcinoide', 'category', false, false, 'CIE-11'),
('5B11', 'Estatura baja, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('5B12', 'Estatura alta constitucional', 'category', false, false, 'CIE-11'),
('5B3Y', 'Otras enfermedades endocrinas especificadas', 'category', false, false, 'CIE-11'),
('5B3Z', 'Enfermedades endocrinas, sin especificación', 'category', false, false, 'CIE-11'),
('5B50', 'Bajo peso en lactantes, niños o adolescentes', 'category', false, false, 'CIE-11'),
('5B51', 'Consunción en lactantes, niños o adolescentes', 'category', false, false, 'CIE-11'),
('5B52', 'Desnutrición aguda en lactantes, niños o adolescentes', 'category', false, false, 'CIE-11'),
('5B53', 'Retraso del crecimiento en lactantes, niños o adolescentes', 'category', false, false, 'CIE-11'),
('5B54', 'Peso bajo en adultos', 'category', false, false, 'CIE-11'),
('5B55', 'Deficiencia de vitamina A', 'category', false, false, 'CIE-11'),
('5B55.0', 'Deficiencia de vitamina A con ceguera nocturna', 'category', false, false, 'CIE-11'),
('5B55.1', 'Deficiencia de vitamina A con xerosis conjuntival', 'category', false, false, 'CIE-11'),
('5B55.2', 'Deficiencia de vitamina A con xerosis conjuntival y manchas de Bitot', 'category', false, false, 'CIE-11'),
('5B55.3', 'Deficiencia de vitamina A con xerosis corneal', 'category', false, false, 'CIE-11'),
('5B55.4', 'Deficiencia de vitamina A con úlcera corneal o queratomalacia', 'category', false, false, 'CIE-11'),
('5B55.5', 'Deficiencia de vitamina A con cicatrices xeroftálmicas de la córnea o ceguera', 'category', false, false, 'CIE-11'),
('5B55.Y', 'Deficiencia de vitamina A con otras manifestaciones especificadas', 'category', false, false, 'CIE-11'),
('5B55.Z', 'Deficiencia de vitamina A, sin especificación', 'category', false, false, 'CIE-11'),
('5B56', 'Deficiencia de vitamina C', 'category', false, false, 'CIE-11'),
('5B56.0', 'Escorbuto', 'category', false, false, 'CIE-11'),
('5B56.Y', 'Otra deficiencia de vitamina C especificada', 'category', false, false, 'CIE-11'),
('5B56.Z', 'Deficiencia de vitamina C, sin especificación', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;