BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('NC57.40', 'Esguince o distensión de tendón, fascia o músculo intrínseco del pulgar a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.41', 'Desgarro de tendón, fascia o músculo intrínseco del pulgar a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.4Y', 'Otro traumatismo en tendón, fascia o músculo intrínseco del pulgar a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.4Z', 'Traumatismo en tendón, fascia o músculo intrínseco del pulgar a nivel de la muñeca o la mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC57.5', 'Traumatismo en tendón, fascia o músculo intrínseco de otro dedo a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.50', 'Esguince o distensión de tendón, fascia o músculo intrínseco de otro dedo a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.51', 'Laceración de músculo, fascia o tendón intrínseco de otro dedo, a nivel de muñeca o mano', 'category', false, false, 'CIE-11'),
('NC57.5Y', 'Otro traumatismo en tendón, fascia o músculo intrínseco de otro dedo a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.5Z', 'Traumatismo en tendón, fascia o músculo intrínseco de otro dedo a nivel de la muñeca o la mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC57.6', 'Traumatismo en múltiples tendones y músculos flexores a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.7', 'Traumatismo en múltiples tendones y músculos extensores a nivel de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC57.Y', 'Otro traumatismo especificado del músculo, fascia o tendón a nivel de muñeca o mano', 'category', false, false, 'CIE-11'),
('NC57.Z', 'Traumatismo del músculo, fascia o tendón a nivel de muñeca o mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC58', 'Traumatismo por aplastamiento de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC58.0', 'Traumatismo por aplastamiento del pulgar', 'category', false, false, 'CIE-11'),
('NC58.1', 'Traumatismo por aplastamiento de otro dedo de la mano', 'category', false, false, 'CIE-11'),
('NC58.2', 'Traumatismo por aplastamiento de la mano', 'category', false, false, 'CIE-11'),
('NC58.3', 'Traumatismo por aplastamiento de la muñeca', 'category', false, false, 'CIE-11'),
('NC58.Y', 'Traumatismo por aplastamiento de otra parte especificada de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC58.Z', 'Traumatismo por aplastamiento de la muñeca o la mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC59', 'Amputación traumática de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC59.0', 'Amputación traumática del pulgar', 'category', false, false, 'CIE-11'),
('NC59.00', 'Amputación traumática en la base del pulgar derecho o cerca de ella', 'category', false, false, 'CIE-11'),
('NC59.01', 'Amputación traumática en la base del pulgar izquierdo o cerca de ella', 'category', false, false, 'CIE-11'),
('NC59.02', 'Amputación traumática en la base del pulgar o cerca de ella, bilateral', 'category', false, false, 'CIE-11'),
('NC59.0Y', 'Otra amputación traumática especificada del pulgar', 'category', false, false, 'CIE-11'),
('NC59.0Z', 'Amputación traumática del pulgar, sin especificación', 'category', false, false, 'CIE-11'),
('NC59.1', 'Amputación traumática de otro dedo solamente', 'category', false, false, 'CIE-11'),
('NC59.2', 'Amputación traumática de dos o más dedos solamente', 'category', false, false, 'CIE-11'),
('NC59.20', 'Amputación traumática de dos o más dedos en la base o cerca de ella, mano derecha', 'category', false, false, 'CIE-11'),
('NC59.21', 'Amputación traumática de dos o más dedos en la base o cerca de ella, mano izquierda', 'category', false, false, 'CIE-11'),
('NC59.22', 'Amputación traumática de dos o más dedos en la base o cerca de ella, bilateral', 'category', false, false, 'CIE-11'),
('NC59.2Y', 'Otra amputación traumática especificada de dos o más dedos solos', 'category', false, false, 'CIE-11'),
('NC59.2Z', 'Amputación traumática de dos o más dedos solos, sin especificación', 'category', false, false, 'CIE-11'),
('NC59.3', 'Amputación traumática combinada de un dedo con otras partes de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC59.4', 'Amputación traumática de la mano a nivel metacarpiano', 'category', false, false, 'CIE-11'),
('NC59.Z', 'Amputación traumática de la muñeca o la mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC5A', 'Traumatismos múltiples de la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC5A.0', 'Traumatismo en múltiples sitios de la mano', 'category', false, false, 'CIE-11'),
('NC5A.1', 'Traumatismo en sitios múltiples de la muñeca', 'category', false, false, 'CIE-11'),
('NC5A.Y', 'Otros traumatismos múltiples especificados de la muñeca o mano', 'category', false, false, 'CIE-11'),
('NC5A.Z', 'Traumatismos múltiples de la muñeca o mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC5Y', 'Otros traumatismos especificados en la muñeca o la mano', 'category', false, false, 'CIE-11'),
('NC5Z', 'Traumatismos en la muñeca o la mano, sin especificación', 'category', false, false, 'CIE-11'),
('NC70', 'Traumatismo superficial en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC70.0', 'Excoriación en la cadera', 'category', false, false, 'CIE-11'),
('NC70.1', 'Contusión en la cadera', 'category', false, false, 'CIE-11'),
('NC70.2', 'Excoriación en el muslo', 'category', false, false, 'CIE-11'),
('NC70.3', 'Contusión en el muslo', 'category', false, false, 'CIE-11'),
('NC70.4', 'Traumatismos superficiales múltiples en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC70.Y', 'Otra lesión traumática superficial especificada de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC70.Z', 'Lesión traumática superficial de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC71', 'Herida abierta en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC71.0', 'Desgarro en la cadera o el muslo, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC71.1', 'Desgarro de la cadera o el muslo, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC71.2', 'Herida punzante en la cadera o el muslo, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC71.3', 'Herida punzante en la cadera o el muslo, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC71.4', 'Mordedura o picadura abierta en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC71.5', 'Heridas abiertas múltiples en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC71.Y', 'Otra herida abierta especificada en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC71.Z', 'Herida abierta en la cadera o el muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC72', 'Fractura de fémur', 'category', false, false, 'CIE-11'),
('NC72.0', 'Fractura de la cabeza del fémur', 'category', false, false, 'CIE-11'),
('NC72.1', 'Fractura de la epífisis superior del fémur', 'category', false, false, 'CIE-11'),
('NC72.2', 'Fractura del cuello del fémur', 'category', false, false, 'CIE-11'),
('NC72.20', 'Fractura del cuello del fémur, subcapital', 'category', false, false, 'CIE-11'),
('NC72.21', 'Fractura del cuello del fémur, mediocervical', 'category', false, false, 'CIE-11'),
('NC72.22', 'Fractura de la base del cuello del fémur', 'category', false, false, 'CIE-11'),
('NC72.23', 'Fractura intracapsular del fémur', 'category', false, false, 'CIE-11'),
('NC72.2Y', 'Otra fractura especificada del cuello del fémur', 'category', false, false, 'CIE-11'),
('NC72.2Z', 'Fractura del cuello del fémur, sin especificación', 'category', false, false, 'CIE-11'),
('NC72.3', 'Fractura de la sección trocantérica del fémur', 'category', false, false, 'CIE-11'),
('NC72.30', 'Fractura intertrocantérica del fémur', 'category', false, false, 'CIE-11'),
('NC72.31', 'Fractura pertrocantérica del fémur', 'category', false, false, 'CIE-11'),
('NC72.3Y', 'Otra fractura especificada de la sección trocantérica del fémur', 'category', false, false, 'CIE-11'),
('NC72.3Z', 'Fractura de la sección trocantérica del fémur, sin especificación', 'category', false, false, 'CIE-11'),
('NC72.4', 'Fractura subtrocantérea de fémur', 'category', false, false, 'CIE-11'),
('NC72.5', 'Fractura de la diáfisis del fémur', 'category', false, false, 'CIE-11'),
('NC72.6', 'Fractura de la epífisis distal del fémur', 'category', false, false, 'CIE-11'),
('NC72.60', 'Fractura de la epífisis distal del fémur, sin extensión intrarticular, simple', 'category', false, false, 'CIE-11'),
('NC72.61', 'Fractura de la epífisis distal del fémur, sin extensión intrarticular, en cuña', 'category', false, false, 'CIE-11'),
('NC72.62', 'Fractura de la epífisis distal del fémur, sin extensión intrarticular, compleja', 'category', false, false, 'CIE-11'),
('NC72.63', 'Fractura de la epífisis distal del fémur, con extensión intrarticular, cóndilo lateral', 'category', false, false, 'CIE-11'),
('NC72.64', 'Fractura de la epífisis distal del fémur, con extensión intrarticular, cóndilo medial', 'category', false, false, 'CIE-11'),
('NC72.65', 'Fractura de la epífisis distal del fémur, con extensión intrarticular, frontal', 'category', false, false, 'CIE-11'),
('NC72.66', 'Fractura de la epífisis distal del fémur, con extensión intrarticular, articulación completa', 'category', false, false, 'CIE-11'),
('NC72.6Y', 'Otra fractura de la epífisis distal especificada del fémur', 'category', false, false, 'CIE-11'),
('NC72.6Z', 'Fractura de la epífisis distal del fémur, sin especificación', 'category', false, false, 'CIE-11'),
('NC72.7', 'Fracturas múltiples del fémur', 'category', false, false, 'CIE-11'),
('NC72.8', 'Fractura de otras partes del fémur', 'category', false, false, 'CIE-11'),
('NC72.Y', 'Otra fractura especificada de fémur', 'category', false, false, 'CIE-11'),
('NC72.Z', 'Fractura de fémur, sin especificación', 'category', false, false, 'CIE-11'),
('NC73', 'Luxación, distensión o esguince de la articulación o de los ligamentos de la cadera', 'category', false, false, 'CIE-11'),
('NC73.0', 'Luxación de la cadera', 'category', false, false, 'CIE-11'),
('NC73.00', 'Luxación posterior de la cadera', 'category', false, false, 'CIE-11'),
('NC73.01', 'Luxación obturatriz de la cadera', 'category', false, false, 'CIE-11'),
('NC73.02', 'Otra luxación anterior de la cadera', 'category', false, false, 'CIE-11'),
('NC73.03', 'Luxación central de la cadera', 'category', false, false, 'CIE-11'),
('NC73.0Y', 'Otra luxación de la cadera', 'category', false, false, 'CIE-11'),
('NC73.0Z', 'Luxación de la cadera, sin especificación', 'category', false, false, 'CIE-11'),
('NC73.1', 'Distensión o esguince de la cadera', 'category', false, false, 'CIE-11'),
('NC73.10', 'Esguince o distensión del ligamento iliofemoral de la cadera', 'category', false, false, 'CIE-11'),
('NC73.11', 'Esguince o distensión del ligamento isquiocapsular de la cadera', 'category', false, false, 'CIE-11'),
('NC73.1Y', 'Otra distensión o esguince especificado de la cadera', 'category', false, false, 'CIE-11'),
('NC73.1Z', 'Distensión o esguince de la cadera, sin especificación', 'category', false, false, 'CIE-11'),
('NC74', 'Traumatismo en los nervios a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC74.0', 'Traumatismo en el nervio ciático a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC74.1', 'Traumatismo en el nervio femoral a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC74.2', 'Traumatismo en el nervio sensorio cutáneo a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC74.3', 'Traumatismo en múltiples nervios a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC74.Y', 'Traumatismo en otros nervios especificados a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC74.Z', 'Traumatismo en nervios a nivel de la cadera y el muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC75', 'Traumatismo en los vasos sanguíneos a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC75.0', 'Traumatismo en la arteria femoral', 'category', false, false, 'CIE-11'),
('NC75.00', 'Desgarro de la arteria femoral, menor', 'category', false, false, 'CIE-11'),
('NC75.01', 'Desgarro de la arteria femoral, mayor', 'category', false, false, 'CIE-11'),
('NC75.0Y', 'Otra lesión traumática especificada de la arteria femoral', 'category', false, false, 'CIE-11'),
('NC75.0Z', 'Lesión traumática de la arteria femoral, sin especificación', 'category', false, false, 'CIE-11'),
('NC75.1', 'Traumatismo en la vena femoral a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC75.10', 'Desgarro de la vena femoral a nivel de la cadera o del muslo, menor', 'category', false, false, 'CIE-11'),
('NC75.11', 'Desgarro de la vena femoral a nivel de la cadera o del muslo, mayor', 'category', false, false, 'CIE-11'),
('NC75.1Y', 'Otro traumatismo especificado de la vena femoral a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC75.1Z', 'Traumatismo de la vena femoral a nivel de la cadera o el muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC75.2', 'Traumatismo en la vena safena interna a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC75.20', 'Desgarro de la vena safena interna a nivel de la cadera o del muslo, menor', 'category', false, false, 'CIE-11'),
('NC75.21', 'Desgarro de la vena safena interna a nivel de la cadera o del muslo, mayor', 'category', false, false, 'CIE-11'),
('NC75.2Y', 'Otro traumatismo en la vena safena interna a nivel de la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC75.2Z', 'Traumatismo en la vena safena interna a nivel de la cadera o el muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC75.3', 'Traumatismo en múltiples vasos sanguíneos a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC75.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC75.Z', 'Traumatismo en los vasos sanguíneos a nivel de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC76', 'Traumatismo en tendón, fascia, músculo o bolsa articular a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC76.0', 'Traumatismo en tendón, fascia o músculo de la cadera', 'category', false, false, 'CIE-11'),
('NC76.00', 'Distensión o esguince de tendón, fascia o músculo de la cadera', 'category', false, false, 'CIE-11'),
('NC76.01', 'Desgarro de tendón, fascia o músculo de la cadera', 'category', false, false, 'CIE-11'),
('NC76.0Y', 'Otra lesión traumática del músculo, la fascia o el tendón especificada de la cadera', 'category', false, false, 'CIE-11'),
('NC76.0Z', 'Lesión traumática del músculo, la fascia o el tendón de la cadera, sin especificación', 'category', false, false, 'CIE-11'),
('NC76.1', 'Traumatismo en tendón o músculo cuádriceps', 'category', false, false, 'CIE-11'),
('NC76.10', 'Esguince o distensión del tendón o del músculo cuádriceps', 'category', false, false, 'CIE-11'),
('NC76.11', 'Desgarro del tendón o del músculo cuádriceps', 'category', false, false, 'CIE-11'),
('NC76.1Y', 'Otro traumatismo en tendón o músculo cuádriceps', 'category', false, false, 'CIE-11'),
('NC76.1Z', 'Traumatismo en tendón o músculo cuádriceps, sin especificación', 'category', false, false, 'CIE-11'),
('NC76.2', 'Traumatismo en tendón, fascia o músculo aductor del muslo', 'category', false, false, 'CIE-11'),
('NC76.20', 'Esguince o distensión de tendón, fascia o músculo aductor del muslo', 'category', false, false, 'CIE-11'),
('NC76.21', 'Desgarro de tendón, fascia o músculo abductor del muslo', 'category', false, false, 'CIE-11'),
('NC76.2Y', 'Otro traumatismo especificado en tendón, fascia o músculo aductor del muslo', 'category', false, false, 'CIE-11'),
('NC76.2Z', 'Traumatismo en tendón, fascia o músculo aductor del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC76.3', 'Traumatismo en tendón, fascia o músculo del grupo muscular posterior a nivel del muslo', 'category', false, false, 'CIE-11'),
('NC76.30', 'Esguince o distensión de tendón, fascia o músculo del grupo muscular posterior a nivel del muslo', 'category', false, false, 'CIE-11'),
('NC76.31', 'Desgarro de tendón, fascia o músculo del grupo muscular posterior a nivel del muslo', 'category', false, false, 'CIE-11'),
('NC76.3Y', 'Otro traumatismo especificado de tendón, fascia o músculo del grupo muscular posterior a nivel del muslo', 'category', false, false, 'CIE-11'),
('NC76.3Z', 'Traumatismo de tendón, fascia o músculo del grupo muscular posterior a nivel del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC76.4', 'Traumatismo en múltiples tendones o músculos a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC76.40', 'Traumatismo en la bolsa articular de la cadera', 'category', false, false, 'CIE-11'),
('NC76.4Y', 'Otro traumatismo especificado en múltiples músculos o tendones a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC76.4Z', 'Traumatismo en múltiples músculos o tendones a nivel de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC76.Y', 'Otra lesión traumática del músculo, la fascia o tendón especificada a nivel de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC76.Z', 'Lesión traumática del músculo, la fascia o tendón a nivel de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC77', 'Traumatismo por aplastamiento de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC77.0', 'Traumatismo por aplastamiento de la cadera', 'category', false, false, 'CIE-11'),
('NC77.1', 'Traumatismo por aplastamiento del muslo', 'category', false, false, 'CIE-11'),
('NC77.2', 'Traumatismo por aplastamiento de la cadera y del muslo', 'category', false, false, 'CIE-11'),
('NC77.Z', 'Traumatismo por aplastamiento de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC78', 'Amputación traumática de la cadera o del muslo', 'category', false, false, 'CIE-11'),
('NC78.0', 'Amputación traumática en la articulación de la cadera derecha', 'category', false, false, 'CIE-11'),
('NC78.1', 'Amputación traumática en la articulación de la cadera izquierda', 'category', false, false, 'CIE-11'),
('NC78.2', 'Amputación traumática a nivel de la articulación de la cadera, bilateral', 'category', false, false, 'CIE-11'),
('NC78.3', 'Amputación traumática entre la cadera y la rodilla derecha', 'category', false, false, 'CIE-11'),
('NC78.4', 'Amputación traumática entre la cadera y la rodilla izquierda', 'category', false, false, 'CIE-11'),
('NC78.5', 'Amputación traumática entre la cadera y la rodilla, bilateral', 'category', false, false, 'CIE-11'),
('NC78.Z', 'Amputación traumática de la cadera o del muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC79', 'Traumatismos múltiples en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC7Y', 'Otros traumatismos especificados en la cadera o el muslo', 'category', false, false, 'CIE-11'),
('NC7Z', 'Traumatismos en la cadera o el muslo, sin especificación', 'category', false, false, 'CIE-11'),
('NC90', 'Traumatismo superficial en la rodilla o la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC90.0', 'Excoriación en la rodilla', 'category', false, false, 'CIE-11'),
('NC90.1', 'Contusión en la rodilla', 'category', false, false, 'CIE-11'),
('NC90.2', 'Excoriación en otras partes o en partes no especificadas de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC90.3', 'Contusión en otras partes o en partes no especificadas de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC90.4', 'Traumatismos superficiales múltiples en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC90.Y', 'Otro traumatismo superficial especificado en la rodilla o la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC90.Z', 'Traumatismo superficial en la rodilla o la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC91', 'Herida abierta en la rodilla o la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC91.0', 'Desgarro en la parte inferior de la pierna, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC91.1', 'Desgarro en la parte inferior de la pierna, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC91.2', 'Herida punzante en la pierna, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC91.3', 'Herida punzante en la pierna, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('NC91.4', 'Mordedura o picadura abierta en la pierna', 'category', false, false, 'CIE-11'),
('NC91.5', 'Heridas abiertas múltiples en la pierna', 'category', false, false, 'CIE-11'),
('NC91.Y', 'Otra herida abierta especificada de la rodilla o de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC91.Z', 'Herida abierta de la rodilla o de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC92', 'Fractura de la pierna, incluido el tobillo', 'category', false, false, 'CIE-11'),
('NC92.0', 'Fractura de la rótula', 'category', false, false, 'CIE-11'),
('NC92.1', 'Fractura de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC92.10', 'Avulsión en la inserción del ligamento cruzado', 'category', false, false, 'CIE-11'),
('NC92.11', 'Avulsión de la tuberosidad de la tibia', 'category', false, false, 'CIE-11'),
('NC92.12', 'Fractura metafisaria de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC92.13', 'Fractura de la epífisis proximal de la tibia, cóndilo lateral', 'category', false, false, 'CIE-11'),
('NC92.14', 'Fractura de la epífisis proximal de la tibia, cóndilo medial', 'category', false, false, 'CIE-11'),
('NC92.1Y', 'Otra fractura especificada de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC92.1Z', 'Fractura de la epífisis proximal de la tibia, sin especificación', 'category', false, false, 'CIE-11'),
('NC92.2', 'Fractura de la diáfisis de la tibia', 'category', false, false, 'CIE-11'),
('NC92.3', 'Fractura del extremo inferior de la tibia', 'category', false, false, 'CIE-11'),
('NC92.4', 'Fractura del peroné', 'category', false, false, 'CIE-11'),
('NC92.40', 'Avulsión de la cabeza del peroné', 'category', false, false, 'CIE-11'),
('NC92.4Y', 'Otra fractura especificada del peroné solo', 'category', false, false, 'CIE-11'),
('NC92.4Z', 'Fractura del peroné solo, sin especificación', 'category', false, false, 'CIE-11'),
('NC92.5', 'Fractura del maléolo interno', 'category', false, false, 'CIE-11'),
('NC92.6', 'Fractura del maléolo lateral', 'category', false, false, 'CIE-11'),
('NC92.7', 'Fracturas complejas de tobillo', 'category', false, false, 'CIE-11'),
('NC92.70', 'Fractura, avulsión o rotura del ligamento colateral del maléolo lateral debajo de la sindesmosis con fractura, avulsión o rotura del ligamento medial del maléolo medial', 'category', false, false, 'CIE-11'),
('NC92.71', 'Fractura, avulsión o rotura del ligamento colateral del maléolo lateral debajo de la sindesmosis con fractura, avulsión o rotura del ligamento colateral del maléolo medial y fractura del borde posterior de la tibia distal', 'category', false, false, 'CIE-11'),
('NC92.72', 'Fractura del maléolo lateral a nivel de la articulación sindesmal con fractura, avulsión o rotura del ligamento colateral del maléolo medial', 'category', false, false, 'CIE-11'),
('NC92.73', 'Fractura del maléolo lateral a nivel de la articulación sindesmal con fractura, avulsión o rotura del ligamento colateral del maléolo medial y fractura del borde posterior de la tibia distal', 'category', false, false, 'CIE-11'),
('NC92.74', 'Fractura, avulsión o rotura del ligamento colateral del maléolo medial con fractura de peroné anterior a la articulación sindesmal', 'category', false, false, 'CIE-11'),
('NC92.75', 'Fractura, avulsión o rotura del ligamento colateral del maléolo medial con fractura de peroné anterior a la articulación sindesmal y fractura del borde posterior de la tibia distal', 'category', false, false, 'CIE-11'),
('NC92.76', 'Fractura bimaleolar del tobillo, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('NC92.77', 'Fractura trimaleolar del tobillo, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('NC92.7Y', 'Otras fracturas complejas especificadas de tobillo', 'category', false, false, 'CIE-11'),
('NC92.7Z', 'Fracturas complejas de tobillo, sin especificación', 'category', false, false, 'CIE-11'),
('NC92.8', 'Fracturas múltiples de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC92.Y', 'Fractura de otra parte especificada de la pierna, incluido el tobillo', 'category', false, false, 'CIE-11'),
('NC92.Z', 'Fractura de la pierna, incluido el tobillo, sin especificación', 'category', false, false, 'CIE-11'),
('NC93', 'Luxación, distensión o esguince de articulaciones o ligamentos de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.0', 'Daño interno agudo de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.1', 'Luxación de la rótula', 'category', false, false, 'CIE-11'),
('NC93.10', 'Luxación lateral de la rótula', 'category', false, false, 'CIE-11'),
('NC93.1Y', 'Otra luxación especificada de la rótula', 'category', false, false, 'CIE-11'),
('NC93.1Z', 'Luxación de la rótula, sin especificación', 'category', false, false, 'CIE-11'),
('NC93.2', 'Luxación de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.20', 'Luxación anterior de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC93.21', 'Luxación posterior de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC93.22', 'Luxación medial de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC93.23', 'Luxación lateral de la epífisis proximal de la tibia', 'category', false, false, 'CIE-11'),
('NC93.2Y', 'Otra luxación especificada de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.2Z', 'Luxación de la rodilla, sin especificación', 'category', false, false, 'CIE-11'),
('NC93.3', 'Desgarro de menisco, actual', 'category', false, false, 'CIE-11'),
('NC93.30', 'Desgarro del menisco medial', 'category', false, false, 'CIE-11'),
('NC93.31', 'Desgarro del menisco lateral', 'category', false, false, 'CIE-11'),
('NC93.3Y', 'Otro desgarro especificado de menisco, actual', 'category', false, false, 'CIE-11'),
('NC93.3Z', 'Desgarro de menisco, actual, sin especificación', 'category', false, false, 'CIE-11'),
('NC93.4', 'Desgarro del cartílago articular de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.5', 'Distensión o esguince muscular con afectación del ligamento colateral tibial o peroneo de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.50', 'Esguince o distensión del ligamento colateral medial de la rodilla, excluida la rotura', 'category', false, false, 'CIE-11'),
('NC93.51', 'Esguince o distensión del ligamento lateral de la rodilla, excluida la rotura', 'category', false, false, 'CIE-11'),
('NC93.52', 'Rotura del ligamento lateral medial de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.53', 'Rotura del ligamento colateral lateral de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.5Y', 'Otra distensión o esguince especificado con afectación del ligamento colateral tibial o peroneo de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.5Z', 'Distensión o esguince con afectación del ligamento colateral tibial o peroneo de la rodilla, sin especificación', 'category', false, false, 'CIE-11'),
('NC93.6', 'Distensión muscular o esguince con afectación del ligamento cruzado anterior o posterior de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.60', 'Distensión o esguince del ligamento cruzado anterior de la rodilla, sin rotura', 'category', false, false, 'CIE-11'),
('NC93.61', 'Distensión o esguince del ligamento cruzado posterior de la rodilla, sin rotura', 'category', false, false, 'CIE-11'),
('NC93.62', 'Rotura del ligamento cruzado anterior de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.63', 'Rotura del ligamento cruzado posterior de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.6Y', 'Otra distensión o esguince especificados con afectación del ligamento cruzado anterior o posterior de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.6Z', 'Distensión o esguince con afectación del ligamento cruzado anterior o posterior de la rodilla, sin especificación', 'category', false, false, 'CIE-11'),
('NC93.7', 'Distensión o esguince muscular de otras partes o de partes no especificadas de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.8', 'Traumatismo en múltiples estructuras de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.Y', 'Otra luxación, distensión o esguince especificado de articulaciones o ligamentos de la rodilla', 'category', false, false, 'CIE-11'),
('NC93.Z', 'Luxación, distensión o esguince de articulaciones o ligamentos de la rodilla, sin especificación', 'category', false, false, 'CIE-11'),
('NC94', 'Traumatismo en los nervios de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.0', 'Traumatismo en el nervio tibial en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.1', 'Traumatismo en el nervio peroneo en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.2', 'Traumatismo en el nervio sensorial cutáneo en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.3', 'Traumatismo en múltiples nervios en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.Y', 'Otro traumatismo especificado en los nervios a nivel de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC94.Z', 'Traumatismo en los nervios a nivel de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC95', 'Traumatismo en los vasos sanguíneos de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.0', 'Traumatismo en la arteria poplítea', 'category', false, false, 'CIE-11'),
('NC95.00', 'Desgarro de la arteria poplítea', 'category', false, false, 'CIE-11'),
('NC95.0Y', 'Otro traumatismo especificado en la arteria poplítea', 'category', false, false, 'CIE-11'),
('NC95.0Z', 'Traumatismo en la arteria poplítea, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.1', 'Traumatismo en la arteria tibial anterior', 'category', false, false, 'CIE-11'),
('NC95.10', 'Desgarro de la arteria tibial anterior', 'category', false, false, 'CIE-11'),
('NC95.1Y', 'Otra lesión traumática especificada de la arteria tibial anterior', 'category', false, false, 'CIE-11'),
('NC95.1Z', 'Lesión traumática de la arteria tibial anterior, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.2', 'Traumatismo en la arteria tibial posterior', 'category', false, false, 'CIE-11'),
('NC95.20', 'Desgarro de la arteria tibial posterior', 'category', false, false, 'CIE-11'),
('NC95.2Y', 'Otra lesión traumática especificada de la arteria tibial posterior', 'category', false, false, 'CIE-11'),
('NC95.2Z', 'Lesión traumática de la arteria tibial posterior, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.3', 'Traumatismo en la arteria peronea', 'category', false, false, 'CIE-11'),
('NC95.30', 'Desgarro de la arteria peroneal', 'category', false, false, 'CIE-11'),
('NC95.3Y', 'Otra lesión traumática especificada de la arteria peronea', 'category', false, false, 'CIE-11'),
('NC95.3Z', 'Lesión traumática de la arteria peronea, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.4', 'Traumatismo en la vena safena mayor en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.40', 'Desgarro de la vena safena interna a nivel de la pierna', 'category', false, false, 'CIE-11'),
('NC95.4Y', 'Otra lesión especificada de la vena safena mayor a nivel de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.4Z', 'Lesión de la vena safena mayor a nivel de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.5', 'Traumatismo en la vena safena menor en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.50', 'Desgarro de la vena safena externa a nivel de la pierna', 'category', false, false, 'CIE-11'),
('NC95.5Y', 'Otra lesión traumática especificada de la vena safena menor a nivel de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.5Z', 'Lesión traumática de la vena safena menor a nivel de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.6', 'Traumatismo en la vena poplítea', 'category', false, false, 'CIE-11'),
('NC95.60', 'Desgarro de la vena poplítea', 'category', false, false, 'CIE-11'),
('NC95.6Y', 'Otro traumatismo especificado de la vena poplítea', 'category', false, false, 'CIE-11'),
('NC95.6Z', 'Traumatismo de la vena poplítea, sin especificación', 'category', false, false, 'CIE-11'),
('NC95.7', 'Traumatismo en múltiples vasos sanguíneos a nivel de la pierna', 'category', false, false, 'CIE-11'),
('NC95.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC95.Z', 'Traumatismo en los vasos sanguíneos a nivel de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC96', 'Traumatismo en tendón, fascia, músculo o bolsa sinovial en la parte inferior de la pierna', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;