BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XH3QM0', 'Adenocarcinoma mínimamente invasivo, No mucinoso', 'category', false, false, 'CIE-11'),
('XH4302', 'Carcinoma quístico adenoide', 'category', false, false, 'CIE-11'),
('XH2098', 'Adenocarcinoma mínimamente invasivo, Mucinoso', 'category', false, false, 'CIE-11'),
('XH6LV9', 'Adenocarcinoma papilar, SAI', 'category', false, false, 'CIE-11'),
('XH95U1', 'Carcinoma villoglandular', 'category', false, false, 'CIE-11'),
('XH6QG3', 'Carcinoma micropapilar, SAI', 'category', false, false, 'CIE-11'),
('XH4MW7', 'Adenocarcinoma micropapilar', 'category', false, false, 'CIE-11'),
('XH7KL6', 'Carcinoma hipofisatio, SAI', 'category', false, false, 'CIE-11'),
('XH6L02', 'Adenocarcinoma de células claras, SAI', 'category', false, false, 'CIE-11'),
('XH5085', 'Leiomiomatosis hereditaria y carcinoma de células renales (LHCCR) síndrome asociado con carcinoma de células renales', 'category', false, false, 'CIE-11'),
('XH1442', 'Carcinomas de traslocación familiar MiT', 'category', false, false, 'CIE-11'),
('XH8EN1', 'Carcinoma de células renales deficiente en succinato deshidrogenasa', 'category', false, false, 'CIE-11'),
('XH07X3', 'Adenocarcinoma alveolar', 'category', false, false, 'CIE-11'),
('XH05V6', 'Carcinoma de células renales, SAI', 'category', false, false, 'CIE-11'),
('XH3Z08', 'Carcinoma de células renales, sin clasificar', 'category', false, false, 'CIE-11'),
('XH0RU3', 'Carcinoma de células renales asociada a enfermedad quística adquirida', 'category', false, false, 'CIE-11'),
('XH7K79', 'Carcinoma de células renales tubuloquística', 'category', false, false, 'CIE-11'),
('XH1VB1', 'Tumor cromófobo oncocítico híbrido', 'category', false, false, 'CIE-11'),
('XH3Z50', 'Carcinoma folicular, SAI', 'category', false, false, 'CIE-11'),
('XH9508', 'Adenocarcinoma endometrioide, variante de células ciliadas', 'category', false, false, 'CIE-11'),
('XH0718', 'Adenocarcinoma endometrioide, variante secretoria', 'category', false, false, 'CIE-11'),
('XH4KH2', 'Carcinoma cortical adrenal', 'category', false, false, 'CIE-11'),
('XH0SD2', 'Adenocarcinoma endometrioide, SAI', 'category', false, false, 'CIE-11'),
('XH51K1', 'Tumor neuroendocrino, grado 2', 'category', false, false, 'CIE-11'),
('XH09B7', 'Cistoadenocarcinoma endometrioide', 'category', false, false, 'CIE-11'),
('XH6KR7', 'Adenofibroma endometrioide, maligno', 'category', false, false, 'CIE-11'),
('XH0GS9', 'Adenocarcinoma, tipo endocervical', 'category', false, false, 'CIE-11'),
('XH8SF8', 'Adenomatosis de células de los islotes', 'category', false, false, 'CIE-11'),
('XH43E4', 'Colangiocarcinoma perihiliar', 'category', false, false, 'CIE-11'),
('XH4BY1', 'Adenoma de células del islote', 'category', false, false, 'CIE-11'),
('XH3CU4', 'Variante villoglandular del adenocarcinoma endometrioide', 'category', false, false, 'CIE-11'),
('XH5QV8', 'Blastoma pituitario', 'category', false, false, 'CIE-11'),
('XH0Y80', 'Carcinoma folicular, encapsulado, angioinvasivo', 'category', false, false, 'CIE-11'),
('XH46F1', 'Carcinoma renal de células claras, SAI', 'category', false, false, 'CIE-11'),
('XH9SA7', 'Adenocarcinoma de células basales', 'category', false, false, 'CIE-11'),
('XH85C2', 'Tumor del saco endolinfático', 'category', false, false, 'CIE-11'),
('XH4PB1', 'Adenocarcinoma acinar de próstata', 'category', false, false, 'CIE-11'),
('XH8E54', 'Neoplasia mixta neuroendocrina no neuroendocrina (MMiNEN)', 'category', false, false, 'CIE-11'),
('XH5QW8', 'Tumor neuroendocrino, grado 3', 'category', false, false, 'CIE-11'),
('XH1NL5', 'Nesidioblastoma', 'category', false, false, 'CIE-11'),
('XH5XB7', 'Carcinoma de células de los islotes', 'category', false, false, 'CIE-11'),
('XH2ST7', 'Tumor de células de los islotes, SAI', 'category', false, false, 'CIE-11'),
('XH4SH8', 'Insulinoma, SAI', 'category', false, false, 'CIE-11'),
('XH93H8', 'Gastrinoma', 'category', false, false, 'CIE-11'),
('XH7JQ0', 'Carcinoma de paratiroides', 'category', false, false, 'CIE-11'),
('XH9LV7', 'Carcinoma basófilo', 'category', false, false, 'CIE-11'),
('XH7152', 'Tumor productor de péptido similar al glucagón', 'category', false, false, 'CIE-11'),
('XH7LW9', 'Tumor de células -L', 'category', false, false, 'CIE-11'),
('XH9ZS8', 'Péptido pancreático y péptido similar al péptido pancreático dentro del tumor productor de tirosina amida terminal', 'category', false, false, 'CIE-11'),
('XH4NQ8', 'Glucagonoma', 'category', false, false, 'CIE-11'),
('XH2PF0', 'Enteroglucagonoma', 'category', false, false, 'CIE-11'),
('XH72E5', 'Vipoma', 'category', false, false, 'CIE-11'),
('XH5VH0', 'Somatostatinoma', 'category', false, false, 'CIE-11'),
('XH41P2', 'Tumor endocrino funcionante, SAI', 'category', false, false, 'CIE-11'),
('XH7AG8', 'Tumor productor de ACTH [hormona adrenocorticotrópica]', 'category', false, false, 'CIE-11'),
('XH60V1', 'Carcinoma medular de tiroides', 'category', false, false, 'CIE-11'),
('XH3BU6', 'Cistoadenocarcinoma del conducto biliar', 'category', false, false, 'CIE-11'),
('XH2MW1', 'Carcinoma medular con estroma amiloide', 'category', false, false, 'CIE-11'),
('XH8VU6', 'Carcinoma de tiroides pobremente diferenciado', 'category', false, false, 'CIE-11'),
('XH4NH4', 'Tumor neuroendocrino hipofisario', 'category', false, false, 'CIE-11'),
('XH2ZA2', 'Adenoma bronquial, carcinoide', 'category', false, false, 'CIE-11'),
('XH5TR7', 'Carcinoma de pulmón, mixto mucinoso y no- mucinoso', 'category', false, false, 'CIE-11'),
('XH7GY6', 'Adenocarcinoma de pulmón, mucinoso', 'category', false, false, 'CIE-11'),
('XH2035', 'Carcinoma bronquiolo-alveolar, no mucinoso', 'category', false, false, 'CIE-11'),
('XH6LF9', 'Carcinoma simple', 'category', false, false, 'CIE-11'),
('XH0XL5', 'Carcinoma, de tipo difuso', 'category', false, false, 'CIE-11'),
('XH7M15', 'Colangiocarcinoma', 'category', false, false, 'CIE-11'),
('XH7SS7', 'Carcinoma cromófobo', 'category', false, false, 'CIE-11'),
('XH2Q13', 'Adenocarcinofibroma de células claras', 'category', false, false, 'CIE-11'),
('XH6YS0', 'Adenocarcinoma de células claras, mesonefroide', 'category', false, false, 'CIE-11'),
('XH4SQ4', 'Carcinoma del ducto colector', 'category', false, false, 'CIE-11'),
('XH7QJ6', 'Carcinoma hepatocelular y colangiocarcinoma combinado', 'category', false, false, 'CIE-11'),
('XH4KK0', 'Quistes asociados con carcinoma de células renales', 'category', false, false, 'CIE-11'),
('XH0LH8', 'Tumor de células similares a enterocromafines', 'category', false, false, 'CIE-11'),
('XH5P16', 'Adenocarcinoma fetal', 'category', false, false, 'CIE-11'),
('XH7TE3', 'Adenocarcinoma folicular, moderadamente diferenciado', 'category', false, false, 'CIE-11'),
('XH0VD1', 'Adenocarcinoma folicular, trabecular', 'category', false, false, 'CIE-11'),
('XH8FK7', 'Adenocarcinoma folicular, bien diferenciado', 'category', false, false, 'CIE-11'),
('XH3DN7', 'Carcinoma folicular, mínimamente invasivo', 'category', false, false, 'CIE-11'),
('XH90N9', 'Carcinoma folicular, de células oxifílicas', 'category', false, false, 'CIE-11'),
('XH3XT5', 'Carcinoma rico en glicógeno', 'category', false, false, 'CIE-11'),
('XH4262', 'Tumor carcinoide de células caliciformes', 'category', false, false, 'CIE-11'),
('XH2EH4', 'Carcinoma de células granulares', 'category', false, false, 'CIE-11'),
('XH4T58', 'Carcinoma hepatocelular, tipo células claras', 'category', false, false, 'CIE-11'),
('XH9Q35', 'Carcinoma hepatocelular, fibrolamelar', 'category', false, false, 'CIE-11'),
('XH0G90', 'Hepatocellular carcinoma, tipo pleomórfico', 'category', false, false, 'CIE-11'),
('XH5761', 'Carcinoma hepatocelular, escirroso', 'category', false, false, 'CIE-11'),
('XH3T17', 'Carcinoma hepatocelular, variante de células fusiformes', 'category', false, false, 'CIE-11'),
('XH6YH5', 'Adenocarcinoma de células de Hürthle', 'category', false, false, 'CIE-11'),
('XH8MQ3', 'Carcinoma de células Hürthle', 'category', false, false, 'CIE-11'),
('XH8WM4', 'Linitis plástica', 'category', false, false, 'CIE-11'),
('XH6TK0', 'Carcinoma rico en lípidos', 'category', false, false, 'CIE-11'),
('XH81N8', 'Carcinoma de las células de Merkel', 'category', false, false, 'CIE-11'),
('XH7019', 'Carcinoma acidófilo-basófilo mixto', 'category', false, false, 'CIE-11'),
('XH8EZ3', 'Carcinoma mixto acinar-endocrino', 'category', false, false, 'CIE-11'),
('XH74Y9', 'Carcinoma acinar-endocrino-ductal mixto', 'category', false, false, 'CIE-11'),
('XH6H10', 'Carcinoma adenoneuroendocrino mixto', 'category', false, false, 'CIE-11'),
('XH2AM6', 'Adenocarcinoma de células mixtas', 'category', false, false, 'CIE-11'),
('XH7CY5', 'Carcinoma mixto ductal-endocrino', 'category', false, false, 'CIE-11'),
('XH6UP4', 'Adenocarcinoma exocrino y endocrino mixto', 'category', false, false, 'CIE-11'),
('XH7DG7', 'Carcinoma medular-folicular mixto', 'category', false, false, 'CIE-11'),
('XH3340', 'Carcinoma medular-papilar mixto', 'category', false, false, 'CIE-11'),
('XH9LZ7', 'Tumor mixto exocrino y endocrino pancreático , maligno', 'category', false, false, 'CIE-11'),
('XH1108', 'Carcinoma esclerosante no encapsulado', 'category', false, false, 'CIE-11'),
('XH09D6', 'Adenocarcinoma oxifílico', 'category', false, false, 'CIE-11'),
('XH3614', 'Adenocarcinoma de células de los islotes (Langerhans)', 'category', false, false, 'CIE-11'),
('XH3709', 'Tumor neuroendocrino pancreático, no funcional', 'category', false, false, 'CIE-11'),
('XH6XY9', 'Carcinoma tipo- pancreatobiliar', 'category', false, false, 'CIE-11'),
('XH1ND9', 'Carcinoma papilar de tiroides', 'category', false, false, 'CIE-11'),
('XH85E5', 'Carcinoma papilar, de células columnares', 'category', false, false, 'CIE-11'),
('XH0426', 'Carcinoma papilar, esclerosante difuso', 'category', false, false, 'CIE-11'),
('XH0Q59', 'Carcinoma papilar, encapsulado de tiroides', 'category', false, false, 'CIE-11'),
('XH29M4', 'Carcinoma papilar, variante folicular', 'category', false, false, 'CIE-11'),
('XH5YT2', 'Carcinoma papilar, variante oncocítico', 'category', false, false, 'CIE-11'),
('XH2AW7', 'Microcarcinoma papilar', 'category', false, false, 'CIE-11'),
('XH1D07', 'Carcinoma de células renales papilares', 'category', false, false, 'CIE-11'),
('XH4Q20', 'Adenocarcinoma papilar tubular', 'category', false, false, 'CIE-11'),
('XH1JZ0', 'Carcinoma de células parietales', 'category', false, false, 'CIE-11'),
('XH6153', 'Carcinoma de células renales, de tipo cromófobo', 'category', false, false, 'CIE-11'),
('XH9DH7', 'Carcinoma de células renales, sarcomatoides', 'category', false, false, 'CIE-11'),
('XH4FS4', 'Adenocarcinoma escirroso', 'category', false, false, 'CIE-11'),
('XH34G3', 'Carcinoma sólido con formación de mucina', 'category', false, false, 'CIE-11'),
('XH0JE3', 'Adenocarcinoma de extensión superficial', 'category', false, false, 'CIE-11'),
('XH7EX3', 'Adenocarcinoma trabecular', 'category', false, false, 'CIE-11'),
('XH4TA4', 'Adenocarcinoma tubular', 'category', false, false, 'CIE-11'),
('XH1Z69', 'Carcinoide típico', 'category', false, false, 'CIE-11'),
('XH22Z8', 'Carcinoma de glándulas de Skene, de Cowper y de Littre', 'category', false, false, 'CIE-11'),
('XH0X20', 'Adenocarcinoma velloso', 'category', false, false, 'CIE-11'),
('XH0A57', 'Adenocarcinoma de células claras del agua', 'category', false, false, 'CIE-11'),
('XH8UE4', 'Adenocarcinoma, metastático, SAI', 'category', false, false, 'CIE-11'),
('XH4ZC3', 'Carcinoma de células basales de la próstata', 'category', false, false, 'CIE-11'),
('XH4W48', 'Carcinoma hepatocelular, SAI', 'category', false, false, 'CIE-11'),
('XH81Q9', 'Adenoma bronquial, cilindroide', 'category', false, false, 'CIE-11'),
('XH92Y9', 'Carcinoma tímico con características de carcinoma adenoide quístico', 'category', false, false, 'CIE-11'),
('XH1YZ3', 'Carcinoma cribiforme, SAI', 'category', false, false, 'CIE-11'),
('XH4YG1', 'Carcinoma tipo comedo-cribiforme', 'category', false, false, 'CIE-11'),
('XH74B2', 'Adenocarcinoma serrado', 'category', false, false, 'CIE-11'),
('XH6770', 'Apudoma', 'category', false, false, 'CIE-11'),
('XH6VL9', 'Adenoma atípico', 'category', false, false, 'CIE-11'),
('XH3T38', 'Adenoma folicular atípico', 'category', false, false, 'CIE-11'),
('XH0S86', 'Adenofibroma de células claras de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH5DQ2', 'Adenoma endometroide, de malignidad borderline', 'category', false, false, 'CIE-11'),
('XH76W6', 'Adenomas endocrinos múltiples', 'category', false, false, 'CIE-11'),
('XH8468', 'Adenomatosis pulmonar', 'category', false, false, 'CIE-11'),
('XH54H3', 'Tumor hipernefroide', 'category', false, false, 'CIE-11'),
('XH7PR9', 'Neoplasia renal quística multilocular de bajo potencial de malignidad', 'category', false, false, 'CIE-11'),
('XH9DS4', 'Adenofibroma endometrioide, de malignidad borderline', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XH4JG0', 'Tumor carcinoide tubular', 'category', false, false, 'CIE-11'),
('XH4XL2', 'Tumor papilar agresivo', 'category', false, false, 'CIE-11'),
('XH9PN4', 'Tumor bien diferenciado de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH6SY0', 'Neoplasia folicular de tiroides no invasiva con características nucleares de tipo papilar (NFTNITP)', 'category', false, false, 'CIE-11'),
('XH1Y66', 'Tumor trabecular hialinizante', 'category', false, false, 'CIE-11'),
('XH27W5', 'Tumor folicular de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH9T60', 'Carcinoma renal de células papilares claras', 'category', false, false, 'CIE-11'),
('XH6CZ3', 'Tumor borderline de células claras', 'category', false, false, 'CIE-11'),
('XH6YZ9', 'Adenoma apócrino', 'category', false, false, 'CIE-11'),
('XH0AQ8', 'Hidradenoma de células claras', 'category', false, false, 'CIE-11'),
('XH46Z2', 'Acrospiroma ecrino', 'category', false, false, 'CIE-11'),
('XH42Z3', 'Adenoma papilar écrino', 'category', false, false, 'CIE-11'),
('XH25Z9', 'Poroma ecrino', 'category', false, false, 'CIE-11'),
('XH3AM1', 'Espiradenoma, SAI', 'category', false, false, 'CIE-11'),
('XH4YU8', 'Fibroma folicular', 'category', false, false, 'CIE-11'),
('XH7NR3', 'Hidrocistoma', 'category', false, false, 'CIE-11'),
('XH4MV7', 'Hidradenoma, SAI', 'category', false, false, 'CIE-11'),
('XH4DX4', 'Hidradenoma papilar', 'category', false, false, 'CIE-11'),
('XH1PY0', 'Siringoadenoma papilifero', 'category', false, false, 'CIE-11'),
('XH96Q5', 'Adenoma apendicular de la piel', 'category', false, false, 'CIE-11'),
('XH3U61', 'Adenoma de glándula sudorípara', 'category', false, false, 'CIE-11'),
('XH06Y5', 'Siringofibroadenoma', 'category', false, false, 'CIE-11'),
('XH6325', 'Siringoma, SAI', 'category', false, false, 'CIE-11'),
('XH9GB7', 'Tumor siringomatoso del pezón', 'category', false, false, 'CIE-11'),
('XH1NC5', 'Adenoma sebáceo', 'category', false, false, 'CIE-11'),
('XH0SH5', 'Epitelioma sebáceo', 'category', false, false, 'CIE-11'),
('XH7AL8', 'Adenoma ceruminoso', 'category', false, false, 'CIE-11'),
('XH8R55', 'Tricodiscoma de predominio de células fusiformes', 'category', false, false, 'CIE-11'),
('XH1A80', 'Poroma apocrino', 'category', false, false, 'CIE-11'),
('XH8N28', 'Poroma, SAI', 'category', false, false, 'CIE-11'),
('XH0QL4', 'Sebaceoma', 'category', false, false, 'CIE-11'),
('XH7WE6', 'Porocarcinoma in situ', 'category', false, false, 'CIE-11'),
('XH9L77', 'Adenocarcinoma apócrino', 'category', false, false, 'CIE-11'),
('XH6FB5', 'Adenocarcinoma papilar digital', 'category', false, false, 'CIE-11'),
('XH7VK4', 'Porocarcinoma SAI', 'category', false, false, 'CIE-11'),
('XH58E1', 'Espiradenoma ecrino maligno', 'category', false, false, 'CIE-11'),
('XH7NK9', 'Hidradenocarcinoma', 'category', false, false, 'CIE-11'),
('XH17P2', 'Carcinoma microquístico anexal', 'category', false, false, 'CIE-11'),
('XH89V4', 'Adenocarcinoma anexial, SAI', 'category', false, false, 'CIE-11'),
('XH5LY3', 'Adenocarcinoma de glándula sudorípara', 'category', false, false, 'CIE-11'),
('XH4VR2', 'Carcinoma sebáceo', 'category', false, false, 'CIE-11'),
('XH8NE4', 'Adenocarcinoma ecrino', 'category', false, false, 'CIE-11'),
('XH6Z69', 'Adenocarcinoma ceruminoso', 'category', false, false, 'CIE-11'),
('XH9C82', 'Neoplasia maligna que surge de un espiradenoma preexistente', 'category', false, false, 'CIE-11'),
('XH2ZK9', 'Neoplasia maligna que surge de un cilindroma preexistente', 'category', false, false, 'CIE-11'),
('XH9NW9', 'Neoplasia maligna que surge de un espiradenocilindroma preexistente', 'category', false, false, 'CIE-11'),
('XH65F9', 'Sialadenoma papilífero', 'category', false, false, 'CIE-11'),
('XH0BE5', 'Siringocistadenocarcinoma papilífero', 'category', false, false, 'CIE-11'),
('XH8BW1', 'Tumor de glándula sudorípara, SAI', 'category', false, false, 'CIE-11'),
('XH1PG0', 'Epitelioma intraepidérmico de Jadassohn', 'category', false, false, 'CIE-11'),
('XH5AU2', 'Triquilemoma', 'category', false, false, 'CIE-11'),
('XH6QT9', 'Tricoepitelioma', 'category', false, false, 'CIE-11'),
('XH0U05', 'Tricofoliculoma', 'category', false, false, 'CIE-11'),
('XH5L76', 'Tumor pilar', 'category', false, false, 'CIE-11'),
('XH9E37', 'Pilomatricoma, SAI', 'category', false, false, 'CIE-11'),
('XH05Z3', 'Tricogerminoma', 'category', false, false, 'CIE-11'),
('XH7CM2', 'Matricoma melanocítico', 'category', false, false, 'CIE-11'),
('XH3EY8', 'Acantoma de la vaina pilosa', 'category', false, false, 'CIE-11'),
('XH0489', 'Tumor de infundíbulo folicular', 'category', false, false, 'CIE-11'),
('XH2K97', 'Tricoblastoma', 'category', false, false, 'CIE-11'),
('XH70J2', 'Carcinoma basal adenoide', 'category', false, false, 'CIE-11'),
('XH45F3', 'Carcinoma de células basales, fibroepitelial', 'category', false, false, 'CIE-11'),
('XH4GJ2', 'Carcinoma de células basales, miconodular', 'category', false, false, 'CIE-11'),
('XH2CR0', 'Carcinoma basocelular, nodular', 'category', false, false, 'CIE-11'),
('XH2615', 'Carcinoma de células basales, SAI', 'category', false, false, 'CIE-11'),
('XH4C18', 'Carcinoma basoescamoso', 'category', false, false, 'CIE-11'),
('XH5VK4', 'Carcinoma basocelular infiltrante, SAI', 'category', false, false, 'CIE-11'),
('XH0T12', 'Carcinoma basocelular infiltrante, no esclerosante', 'category', false, false, 'CIE-11'),
('XH67Y4', 'Carcinoma basocelular infiltrante, esclerosante', 'category', false, false, 'CIE-11'),
('XH9E93', 'Carcinoma metatípico', 'category', false, false, 'CIE-11'),
('XH5NL6', 'Carcinoma basocelular superficial', 'category', false, false, 'CIE-11'),
('XH2HE7', 'Carcinoma basocelular pigmentado', 'category', false, false, 'CIE-11'),
('XH9K96', 'Triquilemocarcinoma', 'category', false, false, 'CIE-11'),
('XH9G49', 'Carcinoma pilomatrical', 'category', false, false, 'CIE-11'),
('XH6S67', 'Carcinoma basocelular con diferenciación anexial', 'category', false, false, 'CIE-11'),
('XH3DL9', 'Carcinoma tricoblástico', 'category', false, false, 'CIE-11'),
('XH8324', 'Carcinosarcoma tricoblástico', 'category', false, false, 'CIE-11'),
('XH1JH6', 'Carcinoma de células basales, sarcomatoide', 'category', false, false, 'CIE-11'),
('XH8189', 'Tumor de células basales', 'category', false, false, 'CIE-11'),
('XH7WJ7', 'Quiste triquilemal proliferante', 'category', false, false, 'CIE-11'),
('XH3U29', 'Hemangioma capilar', 'category', false, false, 'CIE-11'),
('XH1GU2', 'Hemangioma cavernoso', 'category', false, false, 'CIE-11'),
('XH10T4', 'Hemangioma epitelioide', 'category', false, false, 'CIE-11'),
('XH0LN3', 'Hemangioendotelioma, benigno', 'category', false, false, 'CIE-11'),
('XH0553', 'Hemangioma intramuscular', 'category', false, false, 'CIE-11'),
('XH2HR3', 'Hemangioma racimoso', 'category', false, false, 'CIE-11'),
('XH4NS3', 'Hemangioma venoso', 'category', false, false, 'CIE-11'),
('XH5AW4', 'Hemangioma, SAI', 'category', false, false, 'CIE-11'),
('XH37N4', 'Miointimoma', 'category', false, false, 'CIE-11'),
('XH1JJ2', 'Angiofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH23S6', 'Hemangioma queratósico verrugoso', 'category', false, false, 'CIE-11'),
('XH4E06', 'Angiofibroma celular', 'category', false, false, 'CIE-11'),
('XH73S9', 'Angiofibroma de células gigantes', 'category', false, false, 'CIE-11'),
('XH2EX4', 'Hemangioma en penacho adquirido', 'category', false, false, 'CIE-11'),
('XH4KP7', 'Angioqueratoma', 'category', false, false, 'CIE-11'),
('XH8SM9', 'Nódulo angiomatoide epitelioide cutáneo', 'category', false, false, 'CIE-11'),
('XH8KN7', 'Lesión vascular atípica', 'category', false, false, 'CIE-11'),
('XH9Q71', 'Hemangioma cereza', 'category', false, false, 'CIE-11'),
('XH88L5', 'Hemangioma sinusoidal', 'category', false, false, 'CIE-11'),
('XH9UU3', 'Hemangioma microvenular', 'category', false, false, 'CIE-11'),
('XH9NB0', 'Hemangioma glomeruloide', 'category', false, false, 'CIE-11'),
('XH6RP8', 'Hemangioma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH27G6', 'Hemangioma congénito, SAI', 'category', false, false, 'CIE-11'),
('XH6RC4', 'Hemangioma congénito, rápidamente involutivo', 'category', false, false, 'CIE-11'),
('XH5427', 'Hemangioma congénito, no involutivo', 'category', false, false, 'CIE-11'),
('XH8PD3', 'Hemangioma tachuela', 'category', false, false, 'CIE-11'),
('XH4LY5', 'Hemangioma lobular capilar', 'category', false, false, 'CIE-11'),
('XH4E71', 'Hemangioendotelioma , maligno', 'category', false, false, 'CIE-11'),
('XH6264', 'Hemangiosarcoma', 'category', false, false, 'CIE-11'),
('XH36A5', 'Sarcoma de Kaposi', 'category', false, false, 'CIE-11'),
('XH6FJ5', 'Sarcoma de células de Kupffer', 'category', false, false, 'CIE-11'),
('XH3C78', 'Tumor alveolar bronquial intravascular', 'category', false, false, 'CIE-11'),
('XH36H7', 'Sarcoma intimal', 'category', false, false, 'CIE-11'),
('XH9GF8', 'Hemangioendotelioma epitelioide, SAI', 'category', false, false, 'CIE-11'),
('XH4SY7', 'Angioendotelioma papilar intralinfático', 'category', false, false, 'CIE-11'),
('XH6PA4', 'Hemangioendotelioma kaposiforme', 'category', false, false, 'CIE-11'),
('XH2PS0', 'Hemangioendotelioma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH26F6', 'Hemangioendotelioma pseudomiogénico (tipo sarcoma epitelioide)', 'category', false, false, 'CIE-11'),
('XH64U8', 'Hemangioendotelioma retiforme', 'category', false, false, 'CIE-11'),
('XH8D24', 'Hemangioendotelioma compuesto', 'category', false, false, 'CIE-11'),
('XH2L98', 'Hemangioendotelioma, SAI', 'category', false, false, 'CIE-11'),
('XH6810', 'Hemangioblastoma', 'category', false, false, 'CIE-11'),
('XH9ZB2', 'Adenolinfoma', 'category', false, false, 'CIE-11'),
('XH1TX5', 'Papiloma glandular y de células escamosas mixtas', 'category', false, false, 'CIE-11'),
('XH7J33', 'Linfadenoma', 'category', false, false, 'CIE-11'),
('XH2PY4', 'Adenocarcinoma con metaplasia escamosa', 'category', false, false, 'CIE-11'),
('XH7873', 'Carcinoma adenoescamoso', 'category', false, false, 'CIE-11'),
('XH9JP2', 'Carcinoma epitelioma- mioepitelial', 'category', false, false, 'CIE-11'),
('XH7247', 'Adenocarcinoma con metaplasia cartilaginosa y ósea', 'category', false, false, 'CIE-11'),
('XH2QL8', 'Adenocarcinoma con metaplasia de células fusiformes', 'category', false, false, 'CIE-11'),
('XH6G98', 'Carcinoma metaplásico semejante a la fibromatosis', 'category', false, false, 'CIE-11'),
('XH4GA3', 'Adenocarcinoma con metaplasia apocrina', 'category', false, false, 'CIE-11'),
('XH4T39', 'Adenocarcinoma con diferenciación neuroendocrina', 'category', false, false, 'CIE-11'),
('XH0RD4', 'Carcinoma metaplásico, SAI', 'category', false, false, 'CIE-11'),
('XH7MV6', 'Adenocarcinoma hepatoide', 'category', false, false, 'CIE-11'),
('XH95Y6', 'Carcinoma ductal ecrino escamoide', 'category', false, false, 'CIE-11'),
('XH8XD1', 'Carcinoma endometrioide con diferenciación escamosa', 'category', false, false, 'CIE-11'),
('XH4ZH4', 'Adenomioma', 'category', false, false, 'CIE-11'),
('XH7ZB1', 'Adenomioma polipoide atípico', 'category', false, false, 'CIE-11'),
('XH6YS4', 'Nefroma quístico benigno', 'category', false, false, 'CIE-11'),
('XH70N8', 'Siringoma condroide', 'category', false, false, 'CIE-11'),
('XH8C13', 'Nódulo estromal endometrial', 'category', false, false, 'CIE-11'),
('XH3SR2', 'Tumor renal osificante', 'category', false, false, 'CIE-11'),
('XH2KC1', 'Adenoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH3470', 'Tumor renomedular de células intersticiales', 'category', false, false, 'CIE-11'),
('XH2E97', 'Tumor estromal benigno', 'category', false, false, 'CIE-11'),
('XH0533', 'Tumor estromal y epitelial mixto', 'category', false, false, 'CIE-11'),
('XH7TJ0', 'Nefroma quístico pediátrico', 'category', false, false, 'CIE-11'),
('XH5QU1', 'Adenomioepitelioma, SAI', 'category', false, false, 'CIE-11'),
('XH2V57', 'Adenomioepitelioma, benigno', 'category', false, false, 'CIE-11'),
('XH9T96', 'Tumor mesenquimal fosfatúrico, benigno', 'category', false, false, 'CIE-11'),
('XH3UD9', 'Hamartoma pulmonar', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;