BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('DC50.1Y', 'Otra peritonitis secundaria especificada', 'category', false, false, 'CIE-11'),
('DC50.1Z', 'Peritonitis secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('DC50.2', 'Absceso peritoneal', 'category', false, false, 'CIE-11'),
('DC50.Z', 'Peritonitis, sin especificación', 'category', false, false, 'CIE-11'),
('DC51', 'Algunos trastornos especificados del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('DC51.0', 'Ascitis quilosa', 'category', false, false, 'CIE-11'),
('DC51.1', 'Adherencias peritoneales', 'category', false, false, 'CIE-11'),
('DC51.2', 'Hemoperitoneo', 'category', false, false, 'CIE-11'),
('DC51.Y', 'Otros trastornos especificados del peritoneo o retroperitoneo', 'category', false, false, 'CIE-11'),
('DC5Z', 'Enfermedades del peritoneo, sin especificación', 'category', false, false, 'CIE-11'),
('DC70', 'Diverticulitis del intestino delgado', 'category', false, false, 'CIE-11'),
('DC70.0', 'Diverticulitis del intestino delgado con complicaciones', 'category', false, false, 'CIE-11'),
('DC70.00', 'Diverticulitis del intestino delgado con perforación o absceso', 'category', false, false, 'CIE-11'),
('DC70.0Y', 'Otra diverticulitis del intestino delgado con otra complicación especificada', 'category', false, false, 'CIE-11'),
('DC70.0Z', 'Diverticulitis del intestino delgado con complicaciones, sin especificación', 'category', false, false, 'CIE-11'),
('DC70.1', 'Diverticulitis del intestino delgado sin complicaciones', 'category', false, false, 'CIE-11'),
('DC70.Z', 'Diverticulitis del intestino delgado sin especificación de la presencia de complicaciones', 'category', false, false, 'CIE-11'),
('DC71', 'Diverticulosis del intestino delgado', 'category', false, false, 'CIE-11'),
('DC71.0', 'Diverticulosis del intestino delgado con hemorragia', 'category', false, false, 'CIE-11'),
('DC71.1', 'Diverticulosis del intestino delgado sin hemorragia', 'category', false, false, 'CIE-11'),
('DC71.Z', 'Diverticulosis del intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DC72', 'Divertículo del intestino delgado', 'category', false, false, 'CIE-11'),
('DC72.0', 'Divertículo del intestino delgado con hemorragia', 'category', false, false, 'CIE-11'),
('DC72.1', 'Divertículo del intestino delgado sin hemorragia', 'category', false, false, 'CIE-11'),
('DC72.Z', 'Divertículo de intestino delgado, sin especificación', 'category', false, false, 'CIE-11'),
('DC80', 'Diverticulitis del intestino grueso', 'category', false, false, 'CIE-11'),
('DC80.0', 'Diverticulitis del intestino grueso con complicación', 'category', false, false, 'CIE-11'),
('DC80.00', 'Diverticulitis del intestino grueso con perforación o absceso', 'category', false, false, 'CIE-11'),
('DC80.0Y', 'Otro(a)(s) diverticulitis del intestino grueso con complicación especificado(a)(s)', 'category', false, false, 'CIE-11'),
('DC80.0Z', 'Diverticulitis del intestino grueso con complicación, sin especificación', 'category', false, false, 'CIE-11'),
('DC80.1', 'Diverticulitis del intestino grueso sin complicación', 'category', false, false, 'CIE-11'),
('DC80.Z', 'Diverticulitis del intestino grueso, sin especificación', 'category', false, false, 'CIE-11'),
('DC81', 'Diverticulosis del intestino grueso', 'category', false, false, 'CIE-11'),
('DC81.0', 'Diverticulosis del intestino grueso con hemorragia', 'category', false, false, 'CIE-11'),
('DC81.1', 'Diverticulosis del intestino grueso sin hemorragia', 'category', false, false, 'CIE-11'),
('DC81.Z', 'Diverticulosis del intestino grueso, sin especificación', 'category', false, false, 'CIE-11'),
('DC82', 'Divertículo del intestino grueso', 'category', false, false, 'CIE-11'),
('DC82.0', 'Divertículo del intestino grueso con hemorragia', 'category', false, false, 'CIE-11'),
('DC82.1', 'Divertículo de intestino grueso sin hemorragia', 'category', false, false, 'CIE-11'),
('DC82.Z', 'Divertículo del intestino grueso, sin especificación', 'category', false, false, 'CIE-11'),
('DC90', 'Enfermedad diverticular del intestino delgado y del grueso', 'category', false, false, 'CIE-11'),
('DD00', 'Diverticulitis de parte no especificada del intestino', 'category', false, false, 'CIE-11'),
('DD00.0', 'Diverticulitis de parte no especificada del intestino con complicación', 'category', false, false, 'CIE-11'),
('DD00.00', 'Diverticulitis de una parte no especificada del intestino con perforación o absceso', 'category', false, false, 'CIE-11'),
('DD00.0Y', 'Otra diverticulitis especificada de parte no especificada del intestino con complicación', 'category', false, false, 'CIE-11'),
('DD00.0Z', 'Diverticulitis de parte no especificada del intestino con complicación, sin especificación', 'category', false, false, 'CIE-11'),
('DD00.1', 'Diverticulitis de una parte no especificada del intestino sin complicación', 'category', false, false, 'CIE-11'),
('DD00.Z', 'Diverticulitis de parte no especificada del intestino sin especificación de la presencia o ausencia de complicaciones', 'category', false, false, 'CIE-11'),
('DD01', 'Diverticulosis de una parte no especificada del intestino', 'category', false, false, 'CIE-11'),
('DD01.0', 'Diverticulosis de una parte no especificada del intestino, con hemorragia', 'category', false, false, 'CIE-11'),
('DD01.1', 'Diverticulosis de una parte no especificada del intestino, sin hemorragia', 'category', false, false, 'CIE-11'),
('DD01.Z', 'Diverticulosis de una parte no especificada del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD02', 'Divertículo de una parte no especificada del intestino', 'category', false, false, 'CIE-11'),
('DD02.0', 'Enfermedad diverticular de una parte no especificada del intestino, con hemorragia', 'category', false, false, 'CIE-11'),
('DD02.1', 'Divertículo de una parte no especificada del intestino, sin hemorragia', 'category', false, false, 'CIE-11'),
('DD02.Z', 'Divertículo de una parte no especificada del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD1Z', 'Enfermedad diverticular del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD30', 'Trastornos vasculares agudos del intestino', 'category', false, false, 'CIE-11'),
('DD30.0', 'Infarto arterial mesentérico agudo', 'category', false, false, 'CIE-11'),
('DD30.1', 'Isquemia arterial mesentérica aguda', 'category', false, false, 'CIE-11'),
('DD30.2', 'oclusión venosa mesentérica aguda', 'category', false, false, 'CIE-11'),
('DD30.Y', 'Otros trastornos vasculares agudos especificados del intestino', 'category', false, false, 'CIE-11'),
('DD30.Z', 'Trastornos vasculares agudos del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD31', 'Trastornos vasculares crónicos del intestino', 'category', false, false, 'CIE-11'),
('DD31.0', 'Isquemia mesentérica no oclusiva', 'category', false, false, 'CIE-11'),
('DD31.00', 'Colitis isquémica', 'category', false, false, 'CIE-11'),
('DD31.0Y', 'Otra isquemia mesentérica no oclusiva especificada', 'category', false, false, 'CIE-11'),
('DD31.0Z', 'Isquemia mesentérica no oclusiva, sin especificación', 'category', false, false, 'CIE-11'),
('DD31.Y', 'Otros trastornos vasculares crónicos del intestino especificados', 'category', false, false, 'CIE-11'),
('DD31.Z', 'Trastornos vasculares crónicos del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD3Y', 'Trastornos vasculares isquémicos del intestino especificados', 'category', false, false, 'CIE-11'),
('DD3Z', 'Trastornos vasculares isquémicos del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD50', 'Hernia, no de la pared abdominal', 'category', false, false, 'CIE-11'),
('DD50.0', 'Hernia diafragmática', 'category', false, false, 'CIE-11'),
('DD50.1', 'Hernia pélvica', 'category', false, false, 'CIE-11'),
('DD50.2', 'Hernia intraabdominal', 'category', false, false, 'CIE-11'),
('DD50.20', 'Hernia intraabdominal primaria', 'category', false, false, 'CIE-11'),
('DD50.21', 'Hernia intraabdominal secundaria', 'category', false, false, 'CIE-11'),
('DD50.2Y', 'Otra hernia intraabdominal especificada', 'category', false, false, 'CIE-11'),
('DD50.2Z', 'Hernia intraabdominal, sin especificación', 'category', false, false, 'CIE-11'),
('DD50.Y', 'Otra hernia especificada, no de la pared abdominal', 'category', false, false, 'CIE-11'),
('DD50.Z', 'Hernia, no de la pared abdominal, sin especificación', 'category', false, false, 'CIE-11'),
('DD51', 'Hernia inguinal', 'category', false, false, 'CIE-11'),
('DD52', 'Hernia femoral', 'category', false, false, 'CIE-11'),
('DD53', 'Hernia umbilical', 'category', false, false, 'CIE-11'),
('DD54', 'Hernia paraumbilical', 'category', false, false, 'CIE-11'),
('DD55', 'Hernia epigástrica', 'category', false, false, 'CIE-11'),
('DD56', 'Hernia incisional', 'category', false, false, 'CIE-11'),
('DD57', 'Hernia paraestomal', 'category', false, false, 'CIE-11'),
('DD5Y', 'Otras hernias especificadas', 'category', false, false, 'CIE-11'),
('DD5Z', 'Hernias, sin especificación', 'category', false, false, 'CIE-11'),
('DD70', 'Enfermedad de Crohn', 'category', false, false, 'CIE-11'),
('DD70.0', 'Enfermedad de Crohn de la porción alta del tubo digestivo', 'category', false, false, 'CIE-11'),
('DD70.1', 'Enfermedad de Crohn del intestino delgado', 'category', false, false, 'CIE-11'),
('DD70.2', 'Enfermedad de Crohn del apéndice', 'category', false, false, 'CIE-11'),
('DD70.3', 'Enfermedad de Crohn del intestino grueso', 'category', false, false, 'CIE-11'),
('DD70.4', 'Enfermedad de Crohn de la región anal', 'category', false, false, 'CIE-11'),
('DD70.5', 'Enfermedad de Crohn del intestino delgado y del intestino grueso', 'category', false, false, 'CIE-11'),
('DD70.6', 'Enfermedad de Crohn en sitio de anastomosis', 'category', false, false, 'CIE-11'),
('DD70.Y', 'Enfermedad de Crohn de otro sitio especificado', 'category', false, false, 'CIE-11'),
('DD70.Z', 'Enfermedad de Crohn, sitio sin especificación', 'category', false, false, 'CIE-11'),
('DD71', 'Colitis ulcerosa', 'category', false, false, 'CIE-11'),
('DD71.0', 'Pancolitis ulcerosa', 'category', false, false, 'CIE-11'),
('DD71.1', 'Colitis ulcerosa del lado izquierdo', 'category', false, false, 'CIE-11'),
('DD71.2', 'Rectosigmoiditis ulcerosa', 'category', false, false, 'CIE-11'),
('DD71.3', 'Proctitis ulcerosa', 'category', false, false, 'CIE-11'),
('DD71.Y', 'Otra colitis ulcerosa especificada', 'category', false, false, 'CIE-11'),
('DD71.Z', 'Otra colitis ulcerosa, sin especificación', 'category', false, false, 'CIE-11'),
('DD72', 'Colitis indeterminada', 'category', false, false, 'CIE-11'),
('DD7Y', 'Otras enfermedades inflamatorias del intestino especificadas', 'category', false, false, 'CIE-11'),
('DD7Z', 'Enfermedades inflamatorias del intestino, sin especificación', 'category', false, false, 'CIE-11'),
('DD90', 'Trastornos esofágicos o gastroduodenales funcionales', 'category', false, false, 'CIE-11'),
('DD90.0', 'Globo histérico', 'category', false, false, 'CIE-11'),
('DD90.1', 'Trastorno funcional de la deglución', 'category', false, false, 'CIE-11'),
('DD90.2', 'Pirosis funcional', 'category', false, false, 'CIE-11'),
('DD90.3', 'Dispepsia funcional', 'category', false, false, 'CIE-11'),
('DD90.4', 'Náuseas o vómitos funcionales', 'category', false, false, 'CIE-11'),
('DD90.5', 'Trastornos funcionales por eructo', 'category', false, false, 'CIE-11'),
('DD90.6', 'Síndrome de rumiación del adulto', 'category', false, false, 'CIE-11'),
('DD90.Y', 'Otros trastornos especificados esofágicos o gastroduodenales funcionales', 'category', false, false, 'CIE-11'),
('DD90.Z', 'Trastornos esofágicos o gastroduodenales funcionales, sin especificación', 'category', false, false, 'CIE-11'),
('DD91', 'Síndrome del intestino irritable o enteropatías funcionales especificadas', 'category', false, false, 'CIE-11'),
('DD91.0', 'Síndrome del intestino irritable', 'category', false, false, 'CIE-11'),
('DD91.00', 'Síndrome del intestino irritable con predominio de estreñimiento', 'category', false, false, 'CIE-11'),
('DD91.01', 'Síndrome del intestino irritable con predominio de diarrea', 'category', false, false, 'CIE-11'),
('DD91.02', 'Síndrome del intestino irritable de tipo mixto', 'category', false, false, 'CIE-11'),
('DD91.03', 'Síndrome del intestino irritable, sin especificación del subtipo', 'category', false, false, 'CIE-11'),
('DD91.0Z', 'Síndrome del intestino irritable, sin especificación', 'category', false, false, 'CIE-11'),
('DD91.1', 'Estreñimiento funcional', 'category', false, false, 'CIE-11'),
('DD91.2', 'Diarrea funcional', 'category', false, false, 'CIE-11'),
('DD91.3', 'Distensión abdominal funcional', 'category', false, false, 'CIE-11'),
('DD91.4', 'Síndrome de dolor abdominal funcional', 'category', false, false, 'CIE-11'),
('DD91.Y', 'Otro síndrome del intestino irritable o enteropatía funcional especificada', 'category', false, false, 'CIE-11'),
('DD91.Z', 'Síndrome del intestino irritable o enteropatía funcional, sin especificación', 'category', false, false, 'CIE-11'),
('DD92', 'Trastornos anorrectales funcionales', 'category', false, false, 'CIE-11'),
('DD92.0', 'Incontinencia fecal funcional', 'category', false, false, 'CIE-11'),
('DD92.1', 'Dolor anorrectal funcional', 'category', false, false, 'CIE-11'),
('DD92.2', 'Trastornos funcionales de la defecación', 'category', false, false, 'CIE-11'),
('DD92.Y', 'Otros trastornos anorrectales funcionales especificados', 'category', false, false, 'CIE-11'),
('DD92.Z', 'Trastornos anorrectales funcionales, sin especificación', 'category', false, false, 'CIE-11'),
('DD93', 'Trastornos digestivos funcionales de los lactantes, niños preescolares y niños mayores', 'category', false, false, 'CIE-11'),
('DD93.0', 'Regurgitación primoinfantil', 'category', false, false, 'CIE-11'),
('DD93.1', 'Cólico del lactante', 'category', false, false, 'CIE-11'),
('DD93.2', 'Disquecia primoinfantil', 'category', false, false, 'CIE-11'),
('DD93.Y', 'Otros trastornos digestivos funcionales de los lactantes, niños preescolares y niños mayores', 'category', false, false, 'CIE-11'),
('DD93.Z', 'Trastornos digestivos funcionales de los lactantes, niños preescolares y niños mayores, sin especificación', 'category', false, false, 'CIE-11'),
('DD94', 'Trastorno funcional de la vesícula biliar', 'category', false, false, 'CIE-11'),
('DD95', 'Trastorno funcional del esfínter de Oddi', 'category', false, false, 'CIE-11'),
('DD9Y', 'Otros trastornos gastrointestinales funcionales especificados', 'category', false, false, 'CIE-11'),
('DD9Z', 'Trastornos gastrointestinales funcionales, sin especificación', 'category', false, false, 'CIE-11'),
('DE10', 'Vómitos tras operación gástrica o intestinal', 'category', false, false, 'CIE-11'),
('DE11', 'Síndrome de vaciamiento yeyunal rápido', 'category', false, false, 'CIE-11'),
('DE12', 'Malfuncionamiento o complicación del estoma externo de un órgano digestivo', 'category', false, false, 'CIE-11'),
('DE12.0', 'Disfunción o complicación de la colostomía o enterostomía', 'category', false, false, 'CIE-11'),
('DE12.1', 'Mal funcionamiento de gastrostomía', 'category', false, false, 'CIE-11'),
('DE13', 'Malabsorción posquirúrgica, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('DE2Y', 'Otras enfermedades especificadas del sistema digestivo', 'category', false, false, 'CIE-11'),
('DE2Z', 'Enfermedades del sistema digestivo, sin especificación', 'category', false, false, 'CIE-11'),
('EA00', 'Exantema viral por virus desconocido o no especificado', 'category', false, false, 'CIE-11'),
('EA0Y', 'Otro exantema viral por especificado', 'category', false, false, 'CIE-11'),
('EA10', 'Pitiriasis rosada', 'category', false, false, 'CIE-11'),
('EA11', 'Síndrome papulopurpúrico en guante y calcetín', 'category', false, false, 'CIE-11'),
('EA12', 'Acrodermatitis papulosa infantil', 'category', false, false, 'CIE-11'),
('EA20', 'Eritema necrolítico acro', 'category', false, false, 'CIE-11'),
('EA3Z', 'Trastorno no especificado de la piel atribuible a infección viral', 'category', false, false, 'CIE-11'),
('EA40', 'Úlcera fagedénica tropical', 'category', false, false, 'CIE-11'),
('EA50', 'Reacciones cutáneas mediadas por toxinas a una infección bacteriana sistémica o a distancia', 'category', false, false, 'CIE-11'),
('EA50.0', 'Eritema marginado reumático', 'category', false, false, 'CIE-11'),
('EA50.1', 'Eritema perineal estreptocócico mediado por toxinas', 'category', false, false, 'CIE-11'),
('EA50.2', 'Síndrome estafilocócico de la piel escaldada', 'category', false, false, 'CIE-11'),
('EA50.3', 'Escarlatina estafilocócica', 'category', false, false, 'CIE-11'),
('EA50.Y', 'Otras reacciones cutáneas especificadas mediadas por toxinas a una infección bacteriana sistémica o a distancia', 'category', false, false, 'CIE-11'),
('EA50.Z', 'Reacciones cutáneas mediadas por toxinas a una infección bacteriana sistémica o a distancia, sin especificación', 'category', false, false, 'CIE-11'),
('EA51', 'Complicaciones cutáneas de la vacunación con BCG', 'category', false, false, 'CIE-11'),
('EA5Y', 'Afectación cutánea por otra infección bacteriana especificada', 'category', false, false, 'CIE-11'),
('EA5Z', 'Afectación cutánea por infección bacteriana, sin especificación', 'category', false, false, 'CIE-11'),
('EA60', 'Algunos trastornos de la piel atribuibles a infección micótica', 'category', false, false, 'CIE-11'),
('EA60.0', 'Micosis subcutáneas', 'category', false, false, 'CIE-11'),
('EA60.1', 'Micosis sistémicas con afectación cutánea', 'category', false, false, 'CIE-11'),
('EA60.Y', 'Afectación cutánea en otra infección micótica especificada', 'category', false, false, 'CIE-11'),
('EA60.Z', 'Infección micótica de la piel, sin especificación', 'category', false, false, 'CIE-11'),
('EA6Y', 'Otros trastornos especificados de la piel atribuibles a infección o infestación', 'category', false, false, 'CIE-11'),
('EA80', 'Eccema atópico', 'category', false, false, 'CIE-11'),
('EA80.0', 'Eccema atópico del lactante', 'category', false, false, 'CIE-11'),
('EA80.1', 'Eccema atópico infantil', 'category', false, false, 'CIE-11'),
('EA80.2', 'Eccema atópico del adulto', 'category', false, false, 'CIE-11'),
('EA80.Y', 'Otras formas especificadas de eccema atópico', 'category', false, false, 'CIE-11'),
('EA80.Z', 'Eccema atópico, sin especificación', 'category', false, false, 'CIE-11'),
('EA81', 'Dermatitis seborreica y afecciones relacionadas', 'category', false, false, 'CIE-11'),
('EA81.0', 'Dermatitis seborreica de la cara', 'category', false, false, 'CIE-11'),
('EA81.1', 'Dermatitis seborreica del cuero cabelludo', 'category', false, false, 'CIE-11'),
('EA81.Y', 'Dermatitis seborreica y afecciones relacionadas especificadas', 'category', false, false, 'CIE-11'),
('EA81.Z', 'Dermatitis seborreica y afecciones relacionadas, sin especificación', 'category', false, false, 'CIE-11'),
('EA82', 'Dermatitis numular', 'category', false, false, 'CIE-11'),
('EA83', 'Liquen simple o liquenificación', 'category', false, false, 'CIE-11'),
('EA83.0', 'Liquen simple', 'category', false, false, 'CIE-11'),
('EA83.00', 'Liquen simple de la vulva', 'category', false, false, 'CIE-11'),
('EA83.01', 'Liquen simple de los genitales masculinos', 'category', false, false, 'CIE-11'),
('EA83.02', 'Liquen simple perianal', 'category', false, false, 'CIE-11'),
('EA83.0Y', 'Otro liquen simple especificado', 'category', false, false, 'CIE-11'),
('EA83.0Z', 'Liquen simple, sin especificación', 'category', false, false, 'CIE-11'),
('EA83.1', 'Liquenización secundaria', 'category', false, false, 'CIE-11'),
('EA84', 'Eccema asteatósico', 'category', false, false, 'CIE-11'),
('EA85', 'Dermatitis o eczema de las manos o los pies', 'category', false, false, 'CIE-11'),
('EA85.0', 'Dermatitis vesicular de manos o pies', 'category', false, false, 'CIE-11'),
('EA85.1', 'Dermatitis hiperqueratósica de manos o pies', 'category', false, false, 'CIE-11'),
('EA85.2', 'Dermatitis de las manos', 'category', false, false, 'CIE-11'),
('EA85.20', 'Eccema atópico de las manos', 'category', false, false, 'CIE-11'),
('EA85.2Y', 'Otra dermatitis especificada de las manos', 'category', false, false, 'CIE-11'),
('EA85.2Z', 'Dermatitis de las manos, sin especificación', 'category', false, false, 'CIE-11'),
('EA85.3', 'Dermatitis de los pies', 'category', false, false, 'CIE-11'),
('EA86', 'Dermatitis o eccema de los miembros inferiores', 'category', false, false, 'CIE-11'),
('EA86.0', 'Dermatitis de las piernas por estasis', 'category', false, false, 'CIE-11'),
('EA86.Z', 'Dermatitis o eccema de los miembros inferiores, sin especificación', 'category', false, false, 'CIE-11'),
('EA87', 'Dermatitis o eccema de la región anogenital', 'category', false, false, 'CIE-11'),
('EA87.0', 'Dermatitis o eccema de los genitales masculinos', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('EA87.1', 'Dermatitis o eccema de los genitales femeninos', 'category', false, false, 'CIE-11'),
('EA87.2', 'Dermatitis o eccema de la región perianal', 'category', false, false, 'CIE-11'),
('EA87.Z', 'Dermatitis o eccema de la región anogenital, sin especificación', 'category', false, false, 'CIE-11'),
('EA88', 'Diversas dermatosis eccematosas especificadas', 'category', false, false, 'CIE-11'),
('EA88.0', 'Dermatitis infecciosa', 'category', false, false, 'CIE-11'),
('EA88.00', 'Dermatitis infecciosa infantil asociada al virus linfotrópico de células T humanas tipo 1', 'category', false, false, 'CIE-11'),
('EA88.0Y', 'Otra dermatitis infecciosa especificada', 'category', false, false, 'CIE-11'),
('EA88.0Z', 'Dermatitis infecciosa, sin especificación', 'category', false, false, 'CIE-11'),
('EA88.1', 'Eccema postraumático', 'category', false, false, 'CIE-11'),
('EA88.2', 'Eccema secundario diseminado', 'category', false, false, 'CIE-11'),
('EA88.3', 'Eccema secundario', 'category', false, false, 'CIE-11'),
('EA88.4', 'Pitiriasis alba', 'category', false, false, 'CIE-11'),
('EA89', 'Dermatitis eccematosa generalizada de tipo no especificado', 'category', false, false, 'CIE-11'),
('EA8Y', 'Otra dermatosis eccematosa especificada', 'category', false, false, 'CIE-11'),
('EA8Z', 'Dermatitis o eccema, sin especificación', 'category', false, false, 'CIE-11'),
('EA90', 'Psoriasis', 'category', false, false, 'CIE-11'),
('EA90.0', 'Psoriasis en placas', 'category', false, false, 'CIE-11'),
('EA90.1', 'Psoriasis gotular', 'category', false, false, 'CIE-11'),
('EA90.2', 'Psoriasis inestable', 'category', false, false, 'CIE-11'),
('EA90.3', 'Psoriasis eritrodérmica', 'category', false, false, 'CIE-11'),
('EA90.4', 'Psoriasis pustulosa', 'category', false, false, 'CIE-11'),
('EA90.40', 'Psoriasis pustular generalizada', 'category', false, false, 'CIE-11'),
('EA90.41', 'Acropustulosis de Hallopeau', 'category', false, false, 'CIE-11'),
('EA90.42', 'Pustulosis palmoplantar', 'category', false, false, 'CIE-11'),
('EA90.4Y', 'Otra psoriasis pustulosa especificada', 'category', false, false, 'CIE-11'),
('EA90.4Z', 'Psoriasis pustulosa, sin especificación', 'category', false, false, 'CIE-11'),
('EA90.5', 'Psoriasis de localización o distribución especificada', 'category', false, false, 'CIE-11'),
('EA90.50', 'Psoriasis de cuero cabelludo', 'category', false, false, 'CIE-11'),
('EA90.51', 'Psoriasis ungueal', 'category', false, false, 'CIE-11'),
('EA90.52', 'Psoriasis intertriginosa y de zonas de flexión', 'category', false, false, 'CIE-11'),
('EA90.53', 'Psoriasis anogenital', 'category', false, false, 'CIE-11'),
('EA90.5Y', 'Otra psoriasis especificada de localización o distribución especificada', 'category', false, false, 'CIE-11'),
('EA90.Y', 'Otras psoriasis especificada', 'category', false, false, 'CIE-11'),
('EA90.Z', 'Psoriasis sin especificación', 'category', false, false, 'CIE-11'),
('EA91', 'Liquen plano', 'category', false, false, 'CIE-11'),
('EA91.0', 'Liquen plano eruptivo agudo', 'category', false, false, 'CIE-11'),
('EA91.1', 'Liquen plano hipertrófico', 'category', false, false, 'CIE-11'),
('EA91.2', 'Liquen plano folicular', 'category', false, false, 'CIE-11'),
('EA91.3', 'Liquen plano de la piel y las mucosas genitales', 'category', false, false, 'CIE-11'),
('EA91.4', 'Liquen plano y reacciones liquenoides de la mucosa bucal', 'category', false, false, 'CIE-11'),
('EA91.40', 'Liquen plano bucal no erosivo', 'category', false, false, 'CIE-11'),
('EA91.41', 'Liquen plano bucal erosivo', 'category', false, false, 'CIE-11'),
('EA91.42', 'Liquen plano bucal no especificado', 'category', false, false, 'CIE-11'),
('EA91.43', 'Mucositis liquenoide bucal', 'category', false, false, 'CIE-11'),
('EA91.4Y', 'Otro liquen plano y reacciones liquenoides especificadas de la mucosa bucal', 'category', false, false, 'CIE-11'),
('EA91.5', 'Liquen plano de las uñas', 'category', false, false, 'CIE-11'),
('EA91.6', 'Liquen plano subagudo', 'category', false, false, 'CIE-11'),
('EA91.Y', 'Otro liquen plano especificado', 'category', false, false, 'CIE-11'),
('EA91.Z', 'Liquen plano, sin especificación', 'category', false, false, 'CIE-11'),
('EA92', 'Dermatosis liquenoides', 'category', false, false, 'CIE-11'),
('EA93', 'Pitiriasis liquenoide', 'category', false, false, 'CIE-11'),
('EA94', 'Pitiriasis rubra pilaris', 'category', false, false, 'CIE-11'),
('EA95', 'Parapsoriasis en placas pequeñas', 'category', false, false, 'CIE-11'),
('EB00', 'Urticaria espontánea', 'category', false, false, 'CIE-11'),
('EB00.0', 'Urticaria aguda', 'category', false, false, 'CIE-11'),
('EB00.1', 'Urticaria crónica', 'category', false, false, 'CIE-11'),
('EB00.Z', 'Urticaria espontánea, sin especificación', 'category', false, false, 'CIE-11'),
('EB01', 'Angioedema o urticaria inducible', 'category', false, false, 'CIE-11'),
('EB01.0', 'Dermografismo', 'category', false, false, 'CIE-11'),
('EB01.1', 'Urticaria por frío', 'category', false, false, 'CIE-11'),
('EB01.2', 'Urticaria de presión retardada', 'category', false, false, 'CIE-11'),
('EB01.3', 'Urticaria de contacto', 'category', false, false, 'CIE-11'),
('EB01.Y', 'Otra forma especificada de angioedema o urticaria inducible', 'category', false, false, 'CIE-11'),
('EB01.Z', 'Angioedema o urticaria inducible, sin especificación', 'category', false, false, 'CIE-11'),
('EB02', 'Urticaria colinérgica o enfermedades relacionadas', 'category', false, false, 'CIE-11'),
('EB02.0', 'Urticaria colinérgica', 'category', false, false, 'CIE-11'),
('EB02.Y', 'Otros trastornos mediados por activación colinérgica', 'category', false, false, 'CIE-11'),
('EB03', 'Síndromes con reacciones urticariales o angioedema', 'category', false, false, 'CIE-11'),
('EB04', 'Angioedema idiopático', 'category', false, false, 'CIE-11'),
('EB05', 'Urticaria de tipo no especificado', 'category', false, false, 'CIE-11'),
('EB0Y', 'Otros trastornos de urticaria especificados', 'category', false, false, 'CIE-11'),
('EB10', 'Eritemas inflamatorios difusos', 'category', false, false, 'CIE-11'),
('EB11', 'Eritema anular', 'category', false, false, 'CIE-11'),
('EB12', 'Eritema multiforme', 'category', false, false, 'CIE-11'),
('EB12.0', 'Eritema cutáneo multiforme', 'category', false, false, 'CIE-11'),
('EB12.1', 'Eritema multiforme mucocutáneo', 'category', false, false, 'CIE-11'),
('EB12.Y', 'Otro eritema multiforme especificado', 'category', false, false, 'CIE-11'),
('EB12.Z', 'Eritema multiforme, sin especificación', 'category', false, false, 'CIE-11'),
('EB13', 'Síndrome de Stevens-Johnson o necrólisis epidérmica tóxica', 'category', false, false, 'CIE-11'),
('EB13.0', 'Síndrome de Stevens-Johnson', 'category', false, false, 'CIE-11'),
('EB13.1', 'Necrólisis epidérmica tóxica', 'category', false, false, 'CIE-11'),
('EB13.2', 'Síndrome de solapamiento de Stevens-Johnson y necrólisis epidérmica tóxica', 'category', false, false, 'CIE-11'),
('EB20', 'Dermatosis neutrofílica febril aguda', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;