BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('1F66.32', 'Filariosis por Brugia timori', 'category', false, false, 'CIE-11'),
('1F66.3Z', 'Filariosis linfática, sin especificación', 'category', false, false, 'CIE-11'),
('1F66.4', 'Dirofilariosis subcutánea', 'category', false, false, 'CIE-11'),
('1F66.Y', 'Otras filariasis especificadas', 'category', false, false, 'CIE-11'),
('1F66.Z', 'Filariasis, sin especificación', 'category', false, false, 'CIE-11'),
('1F67', 'Gnatostomiasis', 'category', false, false, 'CIE-11'),
('1F68', 'Enfermedades por Ancylostoma', 'category', false, false, 'CIE-11'),
('1F68.0', 'Anquilostomiasis', 'category', false, false, 'CIE-11'),
('1F68.1', 'Necatoriasis', 'category', false, false, 'CIE-11'),
('1F68.2', 'Larva migratoria cutánea', 'category', false, false, 'CIE-11'),
('1F68.Y', 'Otro(a)(s) enfermedades por Ancylostoma especificado(a)(s)', 'category', false, false, 'CIE-11'),
('1F68.Z', 'Enfermedades por Ancylostoma, sin especificación', 'category', false, false, 'CIE-11'),
('1F69', 'Esofagostomiasis', 'category', false, false, 'CIE-11'),
('1F6A', 'Oncocercosis', 'category', false, false, 'CIE-11'),
('1F6A.0', 'Oncocercosis ocular', 'category', false, false, 'CIE-11'),
('1F6A.1', 'Oncocercosis de la piel', 'category', false, false, 'CIE-11'),
('1F6A.Y', 'Otra oncocercosis especificada', 'category', false, false, 'CIE-11'),
('1F6A.Z', 'Oncocercosis, sin especificación', 'category', false, false, 'CIE-11'),
('1F6B', 'Estrongiloidosis', 'category', false, false, 'CIE-11'),
('1F6C', 'Singamosis', 'category', false, false, 'CIE-11'),
('1F6D', 'Toxocariasis', 'category', false, false, 'CIE-11'),
('1F6E', 'Triquinosis', 'category', false, false, 'CIE-11'),
('1F6F', 'Tricostrongilosis', 'category', false, false, 'CIE-11'),
('1F6G', 'Trichuriasis', 'category', false, false, 'CIE-11'),
('1F6H', 'Uncinariosis', 'category', false, false, 'CIE-11'),
('1F6Y', 'Otras enfermedades especificadas por nematodos', 'category', false, false, 'CIE-11'),
('1F6Z', 'Enfermedades por nematodos, sin especificación', 'category', false, false, 'CIE-11'),
('1F70', 'Cisticercosis', 'category', false, false, 'CIE-11'),
('1F70.0', 'Cisticercosis del sistema nervioso central', 'category', false, false, 'CIE-11'),
('1F70.00', 'Meningitis por cisticercosis', 'category', false, false, 'CIE-11'),
('1F70.0Y', 'Otro(a)(s) cisticercosis del sistema nervioso central especificado(a)(s)', 'category', false, false, 'CIE-11'),
('1F70.0Z', 'Cisticercosis del sistema nervioso central, sin especificación', 'category', false, false, 'CIE-11'),
('1F70.1', 'Cisticercosis ocular', 'category', false, false, 'CIE-11'),
('1F70.Y', 'Otra cisticercosis especificada', 'category', false, false, 'CIE-11'),
('1F70.Z', 'Cisticercosis, sin especificación', 'category', false, false, 'CIE-11'),
('1F71', 'Difilobotriosis', 'category', false, false, 'CIE-11'),
('1F72', 'Dipilidiasis', 'category', false, false, 'CIE-11'),
('1F73', 'Equinococosis', 'category', false, false, 'CIE-11'),
('1F73.0', 'Equinococosis hepática', 'category', false, false, 'CIE-11'),
('1F73.1', 'Equinococosis pulmonar', 'category', false, false, 'CIE-11'),
('1F73.2', 'Equinococosis ósea', 'category', false, false, 'CIE-11'),
('1F73.3', 'Equinococosis del sistema nervioso central', 'category', false, false, 'CIE-11'),
('1F73.Y', 'Otra equinococosis especificada', 'category', false, false, 'CIE-11'),
('1F73.Z', 'Equinococosis, sin especificación', 'category', false, false, 'CIE-11'),
('1F74', 'Himenolepiasis', 'category', false, false, 'CIE-11'),
('1F75', 'Esparganosis', 'category', false, false, 'CIE-11'),
('1F76', 'Teniosis', 'category', false, false, 'CIE-11'),
('1F76.0', 'Teniosis por Taenia solium', 'category', false, false, 'CIE-11'),
('1F76.1', 'Teniosis por Taenia saginata', 'category', false, false, 'CIE-11'),
('1F76.Y', 'Otra teniosis especificada', 'category', false, false, 'CIE-11'),
('1F76.Z', 'Teniosis, sin especificación', 'category', false, false, 'CIE-11'),
('1F7Y', 'Otras enfermedades por cestodos especificadas', 'category', false, false, 'CIE-11'),
('1F7Z', 'Enfermedades por cestodos, sin especificación', 'category', false, false, 'CIE-11'),
('1F80', 'Clonorquiasis', 'category', false, false, 'CIE-11'),
('1F81', 'Dicroceliasis', 'category', false, false, 'CIE-11'),
('1F82', 'Fasciolosis', 'category', false, false, 'CIE-11'),
('1F83', 'Fasciolopsiasis', 'category', false, false, 'CIE-11'),
('1F84', 'Opistorquiasis', 'category', false, false, 'CIE-11'),
('1F85', 'Paragonimiasis', 'category', false, false, 'CIE-11'),
('1F86', 'Esquistosomiasis', 'category', false, false, 'CIE-11'),
('1F86.0', 'Esquistosomiasis por Schistosoma haematobium', 'category', false, false, 'CIE-11'),
('1F86.1', 'Esquistosomiasis por Schistosoma mansoni', 'category', false, false, 'CIE-11'),
('1F86.2', 'Esquistosomiasis por Schistosoma japonicum', 'category', false, false, 'CIE-11'),
('1F86.3', 'Otras esquistosomiasis', 'category', false, false, 'CIE-11'),
('1F86.4', 'Dermatitis por cercarias', 'category', false, false, 'CIE-11'),
('1F86.5', 'Neumonitis por Schistosoma', 'category', false, false, 'CIE-11'),
('1F86.Z', 'Esquistosomiasis, sin especificación', 'category', false, false, 'CIE-11'),
('1F8Y', 'Otras enfermedades por trematodos especificadas', 'category', false, false, 'CIE-11'),
('1F8Z', 'Enfermedades por trematodos, sin especificación', 'category', false, false, 'CIE-11'),
('1F90', 'Otra infestación o la no especificada por gusanos parásitos', 'category', false, false, 'CIE-11'),
('1F90.0', 'Helmintiasis intestinal mixta', 'category', false, false, 'CIE-11'),
('1F90.1', 'Infestación parasitaria intestinal no especificada en otra parte', 'category', false, false, 'CIE-11'),
('1F90.2', 'Helmintiasis intestinal, sin especificación', 'category', false, false, 'CIE-11'),
('1F90.Y', 'Otra infestación especificada por gusanos parásitos', 'category', false, false, 'CIE-11'),
('1F90.Z', 'Infestación por gusanos parásitos, sin especificación', 'category', false, false, 'CIE-11'),
('1F91', 'Difilobotriasis y esparganosis', 'category', false, false, 'CIE-11'),
('1F9Z', 'Helmintiasis, sin especificación', 'category', false, false, 'CIE-11'),
('1G00', 'Pediculosis', 'category', false, false, 'CIE-11'),
('1G00.0', 'Pediculosis de la cabeza', 'category', false, false, 'CIE-11'),
('1G00.1', 'Pediculosis del cuerpo', 'category', false, false, 'CIE-11'),
('1G00.Z', 'Pediculosis de sitio o tipo, sin especificación', 'category', false, false, 'CIE-11'),
('1G01', 'Miasis', 'category', false, false, 'CIE-11'),
('1G01.0', 'Miasis ocular', 'category', false, false, 'CIE-11'),
('1G01.1', 'Miasis nasofaríngea', 'category', false, false, 'CIE-11'),
('1G01.2', 'Miasis laríngea', 'category', false, false, 'CIE-11'),
('1G01.3', 'Miasis cutánea', 'category', false, false, 'CIE-11'),
('1G01.Y', 'Otra miasis especificada', 'category', false, false, 'CIE-11'),
('1G01.Z', 'Miasis, sin especificación', 'category', false, false, 'CIE-11'),
('1G02', 'Hirudiniasis externa', 'category', false, false, 'CIE-11'),
('1G03', 'Ptiriasis', 'category', false, false, 'CIE-11'),
('1G04', 'Sarna', 'category', false, false, 'CIE-11'),
('1G04.0', 'Sarna clásica', 'category', false, false, 'CIE-11'),
('1G04.1', 'Sarna costrosa', 'category', false, false, 'CIE-11'),
('1G04.Y', 'Otros tipos de sarna y sin especificación', 'category', false, false, 'CIE-11'),
('1G04.Z', 'Sarna, sin especificación', 'category', false, false, 'CIE-11'),
('1G05', 'Tungiasis', 'category', false, false, 'CIE-11'),
('1G06', 'Cimicosis', 'category', false, false, 'CIE-11'),
('1G07', 'Infestación por ácaros', 'category', false, false, 'CIE-11'),
('1G07.0', 'Infestación por Demodex', 'category', false, false, 'CIE-11'),
('1G07.Y', 'Otra infestación especificada por ácaros', 'category', false, false, 'CIE-11'),
('1G07.Z', 'Infestación por ácaros, sin especificación', 'category', false, false, 'CIE-11'),
('1G0Y', 'Otras infestaciones especificadas por ectoparásitos', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('1G0Z', 'Infestaciones por ectoparásitos, sin especificación', 'category', false, false, 'CIE-11'),
('1G2Y', 'Otras enfermedades parasitarias especificadas', 'category', false, false, 'CIE-11'),
('1G2Z', 'Enfermedades parasitarias, sin especificación', 'category', false, false, 'CIE-11'),
('1G40', 'Sepsis sin choque séptico', 'category', false, false, 'CIE-11'),
('1G41', 'Sepsis con choque séptico', 'category', false, false, 'CIE-11'),
('1G60', 'Algunos otros trastornos de origen infeccioso', 'category', false, false, 'CIE-11'),
('1G60.0', 'Micetoma de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('1G60.1', 'Pitiosis', 'category', false, false, 'CIE-11'),
('1G60.2', 'Prototecosis', 'category', false, false, 'CIE-11'),
('1G60.3', '', 'category', false, false, 'CIE-11'),
('1G60.Y', 'Algunos otros trastornos especificados de origen infeccioso no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('1G80', 'Secuelas de la tuberculosis', 'category', false, false, 'CIE-11'),
('1G81', 'Secuelas del tracoma', 'category', false, false, 'CIE-11'),
('1G82', 'Secuelas de la lepra', 'category', false, false, 'CIE-11'),
('1G83', 'Secuelas de la poliomielitis', 'category', false, false, 'CIE-11'),
('1G84', 'Secuelas de la encefalitis viral', 'category', false, false, 'CIE-11'),
('1G85', 'Secuelas de la difteria', 'category', false, false, 'CIE-11'),
('1G8Y', 'Secuelas de otras enfermedades infecciosas especificadas', 'category', false, false, 'CIE-11'),
('1G8Z', 'Secuelas de enfermedades infecciosas, sin especificación', 'category', false, false, 'CIE-11'),
('1H0Z', 'Algunas enfermedades infecciosas o parasitarias, sin especificación', 'category', false, false, 'CIE-11'),
('2A00', 'Neoplasias primarias de cerebro', 'category', false, false, 'CIE-11'),
('2A00.0', 'Gliomas de cerebro', 'category', false, false, 'CIE-11'),
('2A00.00', 'Glioblastoma de cerebro', 'category', false, false, 'CIE-11'),
('2A00.0Y', 'Otros gliomas especificados del cerebro', 'category', false, false, 'CIE-11'),
('2A00.0Z', 'Gliomas de cerebro, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.1', 'Tumores embrionarios del cerebro', 'category', false, false, 'CIE-11'),
('2A00.10', 'Meduloblastoma del cerebro', 'category', false, false, 'CIE-11'),
('2A00.11', 'Tumor neuroectodérmico primitivo central', 'category', false, false, 'CIE-11'),
('2A00.1Y', 'Otros tumores embrionarios especificados del cerebro', 'category', false, false, 'CIE-11'),
('2A00.1Z', 'Tumores embrionarios del cerebro, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.2', 'Tumores del tejido neuroepitelial del encéfalo', 'category', false, false, 'CIE-11'),
('2A00.20', 'Tumores de la glándula pineal o de la región pineal', 'category', false, false, 'CIE-11'),
('2A00.21', 'Tumores mixtos gliales-neuronales', 'category', false, false, 'CIE-11'),
('2A00.22', 'Tumores de los plexos coroideos', 'category', false, false, 'CIE-11'),
('2A00.2Y', 'Otros tumores especificados del tejido neuroepitelial del encéfalo', 'category', false, false, 'CIE-11'),
('2A00.2Z', 'Tumores del tejido neuroepitelial del encéfalo, sin especificación', 'category', false, false, 'CIE-11'),
('2A00.3', 'Neurocitoma central del cerebro', 'category', false, false, 'CIE-11'),
('2A00.4', 'Astroblastoma de cerebro', 'category', false, false, 'CIE-11'),
('2A00.5', 'Neoplasia primaria de cerebro de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A01', 'Neoplasias primarias de las meninges', 'category', false, false, 'CIE-11'),
('2A01.0', 'Meningiomas', 'category', false, false, 'CIE-11'),
('2A01.00', 'Meningioma primario maligno', 'category', false, false, 'CIE-11'),
('2A01.0Y', 'Otros meningeomas especificados', 'category', false, false, 'CIE-11'),
('2A01.0Z', 'Meningiomas, sin especificación', 'category', false, false, 'CIE-11'),
('2A01.1', 'Tumores mesenquimatosos de las meninges', 'category', false, false, 'CIE-11'),
('2A01.2', 'Neoplasia primaria de las meninges de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A02', 'Neoplasia primaria de la médula espinal, de los nervios craneales o de otras partes remanentes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A02.0', 'Gliomas de la médula espinal, de los pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.00', 'Glioblastoma de médula espinal, pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.0Y', 'Otros gliomas especificados de médula espinal, pares craneales o de nervios paraespinales', 'category', false, false, 'CIE-11'),
('2A02.0Z', 'Gliomas de médula espinal, pares craneales o de nervios paraespinales, sin especificación', 'category', false, false, 'CIE-11'),
('2A02.1', 'Tumores de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.10', 'Tumor maligno de la vaina del nervio periférico de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.11', 'Neuroblastoma paravertebral', 'category', false, false, 'CIE-11'),
('2A02.12', 'Neoplasia maligna del nervio óptico', 'category', false, false, 'CIE-11'),
('2A02.1Y', 'Otros tumores especificados de los nervios craneales o paraespinales', 'category', false, false, 'CIE-11'),
('2A02.1Z', 'Tumores de los nervios craneales o paraespinales, sin especificación', 'category', false, false, 'CIE-11'),
('2A02.2', 'Neoplasia primaria de médula espinal de tipo desconocido o no especificado', 'category', false, false, 'CIE-11'),
('2A02.3', 'Neoplasia benigna de los nervios craneales', 'category', false, false, 'CIE-11'),
('2A02.4', 'Neoplasia benigna de la médula espinal', 'category', false, false, 'CIE-11'),
('2A02.Z', 'Neoplasia primaria de la médula espinal, de los nervios craneales o de otras partes remanentes del sistema nervioso central, sin especificación', 'category', false, false, 'CIE-11'),
('2A0Z', 'Otras neoplasias y las no especificadas del cerebro o del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A20', 'Neoplasias mieloproliferativas no mastocíticas', 'category', false, false, 'CIE-11'),
('2A20.0', 'Leucemia mielógena crónica, BCR-ABL1 positivo', 'category', false, false, 'CIE-11'),
('2A20.00', 'Leucemia mielógena crónica con crisis blástica', 'category', false, false, 'CIE-11'),
('2A20.01', 'Leucemia mielógena crónica, positiva al cromosoma de Filadelfia (Ph1)', 'category', false, false, 'CIE-11'),
('2A20.02', 'Leucemia mielógena crónica, t(9:22)(q34;q11)', 'category', false, false, 'CIE-11'),
('2A20.03', 'Leucemia monocítica de tipo Naegeli', 'category', false, false, 'CIE-11'),
('2A20.0Y', 'Otra leucemia mielógena crónica especificada, BCR-ABL1 positivo', 'category', false, false, 'CIE-11'),
('2A20.0Z', 'Leucemia mielógena crónica BCR-ABL1 positivo, sin especificación', 'category', false, false, 'CIE-11'),
('2A20.1', 'Leucemia neutrofílica crónica', 'category', false, false, 'CIE-11'),
('2A20.2', 'Mielofibrosis primaria', 'category', false, false, 'CIE-11'),
('2A20.3', 'Leucemia eosinofílica crónica, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2A20.4', 'Policitemia vera', 'category', false, false, 'CIE-11'),
('2A20.5', 'Neoplasia mieloproliferativa no mastocítica, no clasificable', 'category', false, false, 'CIE-11'),
('2A20.Y', 'Otras neoplasias mieloproliferativas no mastocíticas especificadas', 'category', false, false, 'CIE-11'),
('2A20.Z', 'Neoplasias mieloproliferativas no mastocíticas, sin especificación', 'category', false, false, 'CIE-11'),
('2A21', 'Mastocitosis', 'category', false, false, 'CIE-11'),
('2A21.0', 'Mastocitosis sistémica', 'category', false, false, 'CIE-11'),
('2A21.00', 'Leucemia mastocítica', 'category', false, false, 'CIE-11'),
('2A21.0Y', 'Otra mastocitosis sistémica especificada', 'category', false, false, 'CIE-11'),
('2A21.0Z', 'Mastocitosis sistémica, sin especificación', 'category', false, false, 'CIE-11'),
('2A21.1', 'Mastocitosis cutánea', 'category', false, false, 'CIE-11'),
('2A21.10', 'Urticaria pigmentosa', 'category', false, false, 'CIE-11'),
('2A21.1Y', 'Otra mastocitosis cutánea especificada', 'category', false, false, 'CIE-11'),
('2A21.1Z', 'Mastocitosis cutánea, sin especificación', 'category', false, false, 'CIE-11'),
('2A21.2', 'Sarcoma de mastocitos', 'category', false, false, 'CIE-11'),
('2A21.3', 'Mastocitoma extracutáneo', 'category', false, false, 'CIE-11'),
('2A21.Y', 'Otra mastocitosis especificada', 'category', false, false, 'CIE-11'),
('2A21.Z', 'Mastocitosis, sin especificación', 'category', false, false, 'CIE-11'),
('2A2Y', 'Otro(a)(s) neoplasias mieloproliferativas especificado(a)(s)', 'category', false, false, 'CIE-11'),
('2A2Z', 'Neoplasias mieloproliferativas, sin especificación', 'category', false, false, 'CIE-11'),
('2A30', 'Anemia refractaria', 'category', false, false, 'CIE-11'),
('2A31', 'Neutropenia refractaria', 'category', false, false, 'CIE-11'),
('2A32', 'Trombocitopenia refractaria', 'category', false, false, 'CIE-11'),
('2A33', 'Anemia refractaria con sideroblastos en anillo', 'category', false, false, 'CIE-11'),
('2A34', 'Citopenia refractaria con displasia multilinaje', 'category', false, false, 'CIE-11'),
('2A35', 'Anemia refractaria con exceso de blastocitos', 'category', false, false, 'CIE-11'),
('2A36', 'Síndrome mielodisplásico con deletion (5q) aislada', 'category', false, false, 'CIE-11'),
('2A37', 'Síndrome mielodisplásico, no clasificable', 'category', false, false, 'CIE-11'),
('2A38', 'Citopenia refractaria de la infancia', 'category', false, false, 'CIE-11'),
('2A3Y', 'Otros síndromes mielodisplásicos especificados', 'category', false, false, 'CIE-11'),
('2A3Z', 'Síndromes mielodisplásicos, sin especificación', 'category', false, false, 'CIE-11'),
('2A40', 'Leucemia mielomonocítica crónica', 'category', false, false, 'CIE-11'),
('2A41', 'Leucemia mieloide crónica atípica, BCR-ABL1-negativo', 'category', false, false, 'CIE-11'),
('2A42', 'Leucemia mielomonocítica juvenil', 'category', false, false, 'CIE-11'),
('2A42.0', 'Leucemia mielomonocítica juvenil en remisión completa', 'category', false, false, 'CIE-11'),
('2A42.Y', 'Otra leucemia mielomonocítica juvenil especificada', 'category', false, false, 'CIE-11'),
('2A42.Z', 'Leucemia mielomonocítica juvenil, sin especificación', 'category', false, false, 'CIE-11'),
('2A43', 'Anemia resistente con sideroblastos en anillo y trombocitosis intensa', 'category', false, false, 'CIE-11'),
('2A44', 'Enfermedad mielodisplásica y mieloproliferativa, no clasificable', 'category', false, false, 'CIE-11'),
('2A4Y', 'Otras neoplasias mielodisplásicas y mieloproliferativas especificadas', 'category', false, false, 'CIE-11'),
('2A4Z', 'Neoplasias mielodisplásicas y mieloproliferativas, sin especificación', 'category', false, false, 'CIE-11'),
('2A50', 'Neoplasia mieloide/linfoide con reestructuración de PDGFRA', 'category', false, false, 'CIE-11'),
('2A51', 'Neoplasia mielógena asociada con reestructuración de PDGFRB', 'category', false, false, 'CIE-11'),
('2A52', 'Neoplasias linfoides y mieloides con anomalías de FGFR1', 'category', false, false, 'CIE-11'),
('2A5Z', 'Neoplasias linfocíticas y mielocíticas con eosinofilia y anomalías de PDGFRA, PDGFRB o FGFR1, sin especificación', 'category', false, false, 'CIE-11'),
('2A60', 'Leucemias mieloides agudas y neoplasias precursoras relacionadas', 'category', false, false, 'CIE-11'),
('2A60.0', 'Leucemia mielógena aguda con anomalías genéticas recurrentes', 'category', false, false, 'CIE-11'),
('2A60.1', 'Leucemia mielógena aguda con alteraciones mielodisplásicas', 'category', false, false, 'CIE-11'),
('2A60.2', 'Neoplasias mielógenas relacionadas con el tratamiento', 'category', false, false, 'CIE-11'),
('2A60.20', 'Leucemia mielógena aguda o síndrome mielodisplásico relacionados con el tratamiento', 'category', false, false, 'CIE-11'),
('2A60.2Y', 'Otras neoplasias mielógenas relacionadas con el tratamiento especificadas', 'category', false, false, 'CIE-11'),
('2A60.2Z', 'Neoplasias mielógenas relacionadas con el tratamiento, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.3', 'Leucemia mielógena aguda, no especificada en otra parte según los criterios de otros tipos', 'category', false, false, 'CIE-11'),
('2A60.30', 'Leucemia mieloide aguda con mínima diferenciación', 'category', false, false, 'CIE-11'),
('2A60.31', 'Leucemia mieloide aguda sin maduración', 'category', false, false, 'CIE-11'),
('2A60.32', 'Leucemia mieloide aguda con maduración', 'category', false, false, 'CIE-11'),
('2A60.33', 'Leucemia mielomonocítica aguda', 'category', false, false, 'CIE-11'),
('2A60.34', 'Leucemia monocítica o monoblástica aguda', 'category', false, false, 'CIE-11'),
('2A60.35', 'Leucemia eritroide aguda', 'category', false, false, 'CIE-11'),
('2A60.36', 'Leucemia megacarioblástica aguda', 'category', false, false, 'CIE-11'),
('2A60.37', 'Leucemia basofílica aguda', 'category', false, false, 'CIE-11'),
('2A60.38', 'Panmielosis aguda con mielofibrosis', 'category', false, false, 'CIE-11'),
('2A60.39', 'Sarcoma mieloide', 'category', false, false, 'CIE-11'),
('2A60.3Y', 'Otra leucemia mieloide aguda especificada, no clasificado en otra parte por criterios de otros tipos', 'category', false, false, 'CIE-11'),
('2A60.3Z', 'Leucemia mielógena aguda, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.4', 'Proliferación mieloide en el síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.40', 'Mielopoyesis anormal transitoria', 'category', false, false, 'CIE-11'),
('2A60.41', 'Leucemia mieloide asociada con síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.4Y', 'Otra proliferación mieloide especificada en el síndrome de Down', 'category', false, false, 'CIE-11'),
('2A60.4Z', 'Proliferación mieloide en el síndrome Down, sin especificación', 'category', false, false, 'CIE-11'),
('2A60.5', 'Neoplasia blástica de células dendríticas plasmacitoides', 'category', false, false, 'CIE-11'),
('2A60.Y', 'Otras leucemias mieloides agudas y neoplasias precursoras relacionadas especificadas', 'category', false, false, 'CIE-11'),
('2A60.Z', 'Leucemias mieloides agudas y neoplasias precursoras relacionadas, sin especificación', 'category', false, false, 'CIE-11'),
('2A61', 'Leucemias agudas de linaje ambiguo', 'category', false, false, 'CIE-11'),
('2A70', 'Neoplasias de precursores B linfoblásticas', 'category', false, false, 'CIE-11'),
('2A70.0', 'Linfoma o leucemia linfoblástica B, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('2A70.1', 'Linfoma o leucemia linfoblástica de precursores B con t(9:22) (q34;q11.2); BCR-ABL1', 'category', false, false, 'CIE-11'),
('2A70.Y', 'Otro linfoma o leucemia linfoblástica B con anomalías genéticas recurrentes', 'category', false, false, 'CIE-11'),
('2A71', 'Neoplasias linfoblásticas de precursores T', 'category', false, false, 'CIE-11'),
('2A7Z', 'Neoplasias de linfocitos precursores, sin especificación', 'category', false, false, 'CIE-11'),
('2A80', 'Linfoma folicular', 'category', false, false, 'CIE-11'),
('2A80.0', 'Linfoma folicular de grado 1', 'category', false, false, 'CIE-11'),
('2A80.1', 'Linfoma folicular de grado 2', 'category', false, false, 'CIE-11'),
('2A80.2', 'Linfoma folicular de grado 3', 'category', false, false, 'CIE-11'),
('2A80.3', 'Linfoma cutáneo primario centrofolicular', 'category', false, false, 'CIE-11'),
('2A80.4', 'Linfoma folicular de tipo pediátrico', 'category', false, false, 'CIE-11'),
('2A80.5', 'Linfoma folicular in situ', 'category', false, false, 'CIE-11'),
('2A80.6', 'Linfoma folicular del intestino delgado', 'category', false, false, 'CIE-11'),
('2A80.Y', 'Otro linfoma folicular especificado', 'category', false, false, 'CIE-11'),
('2A80.Z', 'Linfoma folicular, sin especificación', 'category', false, false, 'CIE-11'),
('2A81', 'Linfomas difusos de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.0', 'Linfoma mediastínico primario de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.1', 'Linfoma de linfocitos B grandes intravascular', 'category', false, false, 'CIE-11'),
('2A81.2', 'Linfoma plasmablástico', 'category', false, false, 'CIE-11'),
('2A81.3', 'Granulomatosis linfomatoide', 'category', false, false, 'CIE-11'),
('2A81.4', 'Linfoma de linfocitos B grandes rico en histocitos o linfocitos T', 'category', false, false, 'CIE-11'),
('2A81.5', 'Linfoma difuso primario de linfocitos B grandes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('2A81.6', 'Linfoma difuso de células B grandes positivo para el virus de Epstein-Barr en ancianos', 'category', false, false, 'CIE-11'),
('2A81.7', 'Linfoma difuso de linfocitos B grandes asociados a inflamación crónica', 'category', false, false, 'CIE-11'),
('2A81.8', 'Linfoma de linfocitos B grandes con positividad a ALK', 'category', false, false, 'CIE-11'),
('2A81.9', 'Linfoma primario con derrame', 'category', false, false, 'CIE-11'),
('2A81.A', 'Linfoma cutáneo primario difuso de linfocitos B grandes, tipo de la pierna', 'category', false, false, 'CIE-11'),
('2A81.Y', 'Otros linfomas difusos especificados de linfocitos B grandes', 'category', false, false, 'CIE-11'),
('2A81.Z', 'Linfoma difuso de linfocitos B grandes, sin otra especificación', 'category', false, false, 'CIE-11'),
('2A82', 'Neoplasia de linfocitos B maduros con comportamiento leucémico', 'category', false, false, 'CIE-11'),
('2A82.0', 'Leucemia linfocítica crónica o linfoma de linfocitos pequeños', 'category', false, false, 'CIE-11'),
('2A82.00', 'Leucemia linfocítica crónica de linfocitos B', 'category', false, false, 'CIE-11'),
('2A82.0Y', 'Leucemia linfocítica crónica o linfoma linfocítico pequeño especificado', 'category', false, false, 'CIE-11'),
('2A82.0Z', 'Leucemia linfocítica crónica o linfoma linfocítico pequeño, sin especificación', 'category', false, false, 'CIE-11'),
('2A82.1', 'Leucemia prolinfocítica de linfocitos B', 'category', false, false, 'CIE-11'),
('2A82.10', 'Leucemia prolinfocítica de linfocitos B en remisión completa', 'category', false, false, 'CIE-11'),
('2A82.1Y', 'Otra leucemia prolinfocítica de linfocitos B especificadas', 'category', false, false, 'CIE-11'),
('2A82.1Z', 'Leucemia prolinfocítica de linfocitos B, sin especificación', 'category', false, false, 'CIE-11'),
('2A82.2', 'Leucemia de células pilosas', 'category', false, false, 'CIE-11'),
('2A82.3', 'Leucemia o linfoma de linfocitos B esplénicos, no clasificable', 'category', false, false, 'CIE-11'),
('2A82.Y', 'Neoplasia de linfocitos B maduros especificada con comportamiento leucémico', 'category', false, false, 'CIE-11'),
('2A82.Z', 'Neoplasia de linfocitos B maduros con comportamiento leucémico, sin especificación', 'category', false, false, 'CIE-11'),
('2A83', 'Neoplasias de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.0', 'Gammapatía monoclonal de significado incierto', 'category', false, false, 'CIE-11'),
('2A83.1', 'Mieloma de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.2', 'Plasmocitoma solitario', 'category', false, false, 'CIE-11'),
('2A83.3', 'Plasmocitoma extraóseo', 'category', false, false, 'CIE-11'),
('2A83.4', 'Leucemia de células plasmáticas', 'category', false, false, 'CIE-11'),
('2A83.5', 'Enfermedad por depósito de inmunoglobulinas monoclonales', 'category', false, false, 'CIE-11'),
('2A83.50', 'Enfermedad por depósito de cadena pesada', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;