BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XM1Z58', 'Fenpropatrina', 'category', false, false, 'CIE-11'),
('XM9JZ0', 'Fenvalerato', 'category', false, false, 'CIE-11'),
('XM6H26', 'Flucitrinato', 'category', false, false, 'CIE-11'),
('XM7461', 'Permetrina', 'category', false, false, 'CIE-11'),
('XM4AC0', 'Praletrina', 'category', false, false, 'CIE-11'),
('XM5QE0', 'Teflutrina', 'category', false, false, 'CIE-11'),
('XM1MW0', 'Tetrametrina', 'category', false, false, 'CIE-11'),
('XM2H33', 'Tralometrina', 'category', false, false, 'CIE-11'),
('XM1S21', 'Rotenona', 'category', false, false, 'CIE-11'),
('XM95F1', 'Metaldehído', 'category', false, false, 'CIE-11'),
('XM0NK1', 'Bromuro de metilo', 'category', false, false, 'CIE-11'),
('XM6FE7', 'Butóxido de piperonilo', 'category', false, false, 'CIE-11'),
('XM2KK3', 'Rodenticida', 'category', false, false, 'CIE-11'),
('XM8UV3', 'Alfa clorhidrina', 'category', false, false, 'CIE-11'),
('XM4X40', 'Alfa naftiltiourea)', 'category', false, false, 'CIE-11'),
('XM7138', 'Brodifacoum.', 'category', false, false, 'CIE-11'),
('XM7RU0', 'Bromadiolona', 'category', false, false, 'CIE-11'),
('XM3QV7', 'Brometalina', 'category', false, false, 'CIE-11'),
('XM1GN8', 'Cloralosa', 'category', false, false, 'CIE-11'),
('XM1FD8', 'Clorofacinona', 'category', false, false, 'CIE-11'),
('XM0DK0', 'Cumatetralilo', 'category', false, false, 'CIE-11'),
('XM3KE1', 'Crimidina', 'category', false, false, 'CIE-11'),
('XM9VL9', 'Difenacoum', 'category', false, false, 'CIE-11'),
('XM6DL4', 'Difetialona', 'category', false, false, 'CIE-11'),
('XM4J38', 'Difacinona', 'category', false, false, 'CIE-11'),
('XM7HA0', 'Flocoumafen', 'category', false, false, 'CIE-11'),
('XM7P90', 'Fluoroacetamida', 'category', false, false, 'CIE-11'),
('XM2WD6', 'Norbormida', 'category', false, false, 'CIE-11'),
('XM4116', 'Pindona', 'category', false, false, 'CIE-11'),
('XM8QH8', 'Piriminil', 'category', false, false, 'CIE-11'),
('XM9LE1', 'Fluoroacetato de sodio', 'category', false, false, 'CIE-11'),
('XM8LJ0', 'Warfarina rodenticida', 'category', false, false, 'CIE-11'),
('XM6BS1', 'Tetradifón', 'category', false, false, 'CIE-11'),
('XM6372', 'Acaricida, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM8V89', 'Fumigante, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM0ZQ8', 'Molusquicida, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM5E09', 'Pesticida organoclorado, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM8HA3', 'Desinfectante de semilla, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM86Y5', 'Pesticida de azufre, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM0J68', 'Pesticida tiocarbamato, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM86L9', 'Preservador de la madera, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM55D5', 'Oleato de cobre', 'category', false, false, 'CIE-11'),
('XM6U34', 'Alcohol', 'category', false, false, 'CIE-11'),
('XM9BA5', 'Vapor de alcohol', 'category', false, false, 'CIE-11'),
('XM51N7', 'Alcohol alílico', 'category', false, false, 'CIE-11'),
('XM6K71', 'Ron de bahía', 'category', false, false, 'CIE-11'),
('XM0AD5', 'Alcohol bencílico no medicinal', 'category', false, false, 'CIE-11'),
('XM7VB3', 'Alcohol de cinamilo', 'category', false, false, 'CIE-11'),
('XM3XS0', 'Ciclohexanol', 'category', false, false, 'CIE-11'),
('XM8ZW3', 'Etanol', 'category', false, false, 'CIE-11'),
('XM1A61', 'Bebida alcohólica', 'category', false, false, 'CIE-11'),
('XM8HG4', 'Alcohol absoluto', 'category', false, false, 'CIE-11'),
('XM3094', 'Alcohol desnaturalizado', 'category', false, false, 'CIE-11'),
('XM6DN6', 'Desinfectante etanol', 'category', false, false, 'CIE-11'),
('XM8RP6', 'Etanol combustible de motor', 'category', false, false, 'CIE-11'),
('XM2VC0', 'Etil metil carbinol', 'category', false, false, 'CIE-11'),
('XM48D0', 'Alcohol de fusel', 'category', false, false, 'CIE-11'),
('XM88C8', 'Alcohol amílico', 'category', false, false, 'CIE-11'),
('XM5JW4', 'Hidrato de amileno', 'category', false, false, 'CIE-11'),
('XM49S0', 'Alcohol butílico', 'category', false, false, 'CIE-11'),
('XM6HQ5', 'Dietilcarbinol', 'category', false, false, 'CIE-11'),
('XM5SH0', 'Alcohol isoamílico', 'category', false, false, 'CIE-11'),
('XM5RS7', 'Alcohol propílico', 'category', false, false, 'CIE-11'),
('XM5M32', 'Trimetilcarbinol', 'category', false, false, 'CIE-11'),
('XM6C11', 'Hexahidrocresol', 'category', false, false, 'CIE-11'),
('XM4BN8', 'Hidroabietil alcohol', 'category', false, false, 'CIE-11'),
('XM5531', 'Alcohol isopropílico', 'category', false, false, 'CIE-11'),
('XM8YA1', 'Alcohol de frotamiento isopropílico', 'category', false, false, 'CIE-11'),
('XM80Q0', 'Jengibre de Jamaica', 'category', false, false, 'CIE-11'),
('XM7KD9', 'Metanol', 'category', false, false, 'CIE-11'),
('XM0ZA4', 'Metanol combustible para motor', 'category', false, false, 'CIE-11'),
('XM6VD7', 'Anticongelante, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM7XX5', 'Calor enlatado,no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM4S45', 'Geraniol', 'category', false, false, 'CIE-11'),
('XM7UN9', 'Hidroxicitronelal', 'category', false, false, 'CIE-11'),
('XM9TZ4', 'Toxinas de algas', 'category', false, false, 'CIE-11'),
('XM6F50', 'Cianotoxina', 'category', false, false, 'CIE-11'),
('XM38M2', 'Microcistina', 'category', false, false, 'CIE-11'),
('XM9RM0', 'Propionato de amilo', 'category', false, false, 'CIE-11'),
('XM26J2', 'Toxina de anfibios', 'category', false, false, 'CIE-11'),
('XM0KH6', 'Toxina de rana', 'category', false, false, 'CIE-11'),
('XM0CW7', 'Veneno de rana cabeza de Bruno', 'category', false, false, 'CIE-11'),
('XM8QW3', 'Veneno de la rana de Greening', 'category', false, false, 'CIE-11'),
('XM7JP5', 'Veneno de rana dardo venenoso', 'category', false, false, 'CIE-11'),
('XM4BD8', 'Veneno de rana venenosa dorada', 'category', false, false, 'CIE-11'),
('XM6K27', 'Veneno rana flecha del veneno de Anthony', 'category', false, false, 'CIE-11'),
('XM7JV0', 'Rana venenosa de dardo fresa', 'category', false, false, 'CIE-11'),
('XM9TX1', 'Rana venenosa Kokoe', 'category', false, false, 'CIE-11'),
('XM2698', 'Rana venenosa patas negras', 'category', false, false, 'CIE-11'),
('XM7P83', 'Toxina de salamandra', 'category', false, false, 'CIE-11'),
('XM93N2', 'Toxina de tritón', 'category', false, false, 'CIE-11'),
('XM7YQ1', 'Toxina de sapo', 'category', false, false, 'CIE-11'),
('XM8YT6', 'Toxina de sapo del Río Colorado', 'category', false, false, 'CIE-11'),
('XM54D9', 'Toxina del sapo marino', 'category', false, false, 'CIE-11'),
('XM7930', 'Veneno de artrópodo', 'category', false, false, 'CIE-11'),
('XM12G1', 'Veneno de arácnido', 'category', false, false, 'CIE-11'),
('XM9DM8', 'Veneno del escorpión', 'category', false, false, 'CIE-11'),
('XM0HC0', 'Veneno del escorpión negro de Asia', 'category', false, false, 'CIE-11'),
('XM8F59', 'Veneno del escorpión negro emperador', 'category', false, false, 'CIE-11'),
('XM52D7', 'Veneno del escorpión gigante de bosque', 'category', false, false, 'CIE-11'),
('XM72V7', 'Veneno del escorpión del bosque de Australia', 'category', false, false, 'CIE-11'),
('XM10T2', 'Veneno del escorpión urodacus de Australia', 'category', false, false, 'CIE-11'),
('XM48S4', 'Veneno del escorpión de roca negra de Australia', 'category', false, false, 'CIE-11'),
('XM10R0', 'Veneno del escorpión del desierto de Australia', 'category', false, false, 'CIE-11'),
('XM0YV3', 'Veneno del escorpión marmolado de Australia', 'category', false, false, 'CIE-11'),
('XM3HL0', 'Veneno del escorpión de corteza', 'category', false, false, 'CIE-11'),
('XM2HW7', 'Veneno del escorpión amarillo de Brasil', 'category', false, false, 'CIE-11'),
('XM12P5', 'Veneno de escorpión de China', 'category', false, false, 'CIE-11'),
('XM5QE7', 'Veneno de escorpión amarillo común', 'category', false, false, 'CIE-11'),
('XM0E23', 'Veneno de escorpión acosador de la muerte', 'category', false, false, 'CIE-11'),
('XM95A6', 'Veneno de escorpión de cola gorda', 'category', false, false, 'CIE-11'),
('XM91Z5', 'Veneno de escorpión de roca plana', 'category', false, false, 'CIE-11'),
('XM67X5', 'Veneno de escorpión rojo de la India', 'category', false, false, 'CIE-11'),
('XM11L8', 'Veneno de escorpión de Asia menor', 'category', false, false, 'CIE-11'),
('XM1WF9', 'Veneno de escorpión de cola gorda de Transvaal', 'category', false, false, 'CIE-11'),
('XM8XC7', 'Veneno de escorpión rastrero de patas amarillas', 'category', false, false, 'CIE-11'),
('XM6NN5', 'Veneno de araña', 'category', false, false, 'CIE-11'),
('XM2RM6', 'Veneno de araña reclusa parda', 'category', false, false, 'CIE-11'),
('XM6SD4', 'Veneno de araña falsa viuda', 'category', false, false, 'CIE-11'),
('XM3KD6', 'Veneno de araña de tela de embudo', 'category', false, false, 'CIE-11'),
('XM57S7', 'Veneno de araña vagabunda', 'category', false, false, 'CIE-11'),
('XM0C68', 'Veneno de araña saltadora', 'category', false, false, 'CIE-11'),
('XM1LF5', 'Veneno de araña ratón', 'category', false, false, 'CIE-11'),
('XM6QH2', 'Veneno de araña de arena de seis ojos', 'category', false, false, 'CIE-11'),
('XM8095', 'Veneno de la araña tarántula', 'category', false, false, 'CIE-11'),
('XM8FT7', 'Veneno de la araña errante', 'category', false, false, 'CIE-11'),
('XM7JS2', 'Veneno de la araña viuda', 'category', false, false, 'CIE-11'),
('XM7M21', 'Veneno de la araña viuda negra', 'category', false, false, 'CIE-11'),
('XM9Z42', 'Veneno de la araña viuda marrón', 'category', false, false, 'CIE-11'),
('XM1TF6', 'Veneno de la araña espalda roja', 'category', false, false, 'CIE-11'),
('XM2JA0', 'Veneno de la araña viuda roja', 'category', false, false, 'CIE-11'),
('XM2WM2', 'Veneno de la araña lobo', 'category', false, false, 'CIE-11'),
('XM3UW9', 'Veneno de la araña de saco amarillo', 'category', false, false, 'CIE-11'),
('XM94S4', 'Veneno de garrapata', 'category', false, false, 'CIE-11'),
('XM7WR0', 'Veneno de garrapata de perro americano', 'category', false, false, 'CIE-11'),
('XM51Y1', 'Veneno de garrapata australiana de la parálisis', 'category', false, false, 'CIE-11'),
('XM3J29', 'Veneno de garrapata marrón del perro', 'category', false, false, 'CIE-11'),
('XM77E1', 'Veneno de garrapata del ciervo', 'category', false, false, 'CIE-11'),
('XM5RS1', 'Veneno de garrapata estrella solitaria', 'category', false, false, 'CIE-11'),
('XM8YN1', 'Veneno de garrapata espinosa del oído', 'category', false, false, 'CIE-11'),
('XM6TD6', 'Veneno de ciempiés', 'category', false, false, 'CIE-11'),
('XM5LB1', 'Veneno de ciempiés gigante Amazónico', 'category', false, false, 'CIE-11'),
('XM52L4', 'Veneno de ciempiés gigante Australiano', 'category', false, false, 'CIE-11'),
('XM9FP1', 'Veneno de ciempiés pelirrojo de Texas', 'category', false, false, 'CIE-11'),
('XM2WU4', 'Veneno de ciempiés Vietnamita', 'category', false, false, 'CIE-11'),
('XM50Y9', 'Insecto, venenoso', 'category', false, false, 'CIE-11'),
('XM3Y95', 'Veneno de hormiga', 'category', false, false, 'CIE-11'),
('XM4CP1', 'Veneno de hormiga toro', 'category', false, false, 'CIE-11'),
('XM02L8', 'Veneno de hormiga bala', 'category', false, false, 'CIE-11'),
('XM3UK8', 'Veneno de hormiga de fuego', 'category', false, false, 'CIE-11'),
('XM1547', 'Veneno de hormiga cosechadora', 'category', false, false, 'CIE-11'),
('XM5ZS2', 'Veneno de hormiga Jack Jumper', 'category', false, false, 'CIE-11'),
('XM13H7', 'Veneno de abeja', 'category', false, false, 'CIE-11'),
('XM1GA3', 'Veneno de abeja de miel Africanizada', 'category', false, false, 'CIE-11'),
('XM0NK4', 'Veneno del abejorro', 'category', false, false, 'CIE-11'),
('XM42T0', 'Veneno de abeja de miel', 'category', false, false, 'CIE-11'),
('XM1142', 'Veneno de oruga', 'category', false, false, 'CIE-11'),
('XM2T44', 'Veneno de oruga polilla de la copa', 'category', false, false, 'CIE-11'),
('XM57P9', 'Veneno de oruga de puss', 'category', false, false, 'CIE-11'),
('XM7D92', 'Veneno de tábano', 'category', false, false, 'CIE-11'),
('XM2YA4', 'Veneno de avispa', 'category', false, false, 'CIE-11'),
('XM6D92', 'Veneno de las chaquetas amarillas', 'category', false, false, 'CIE-11'),
('XM1PF5', 'Veneno de la avispa de papel', 'category', false, false, 'CIE-11'),
('XM31U2', 'Veneno del avispón', 'category', false, false, 'CIE-11'),
('XM7CC3', 'Veneno del avispón gigante de Asia', 'category', false, false, 'CIE-11'),
('XM4C00', 'Toxina del milpies', 'category', false, false, 'CIE-11'),
('XM0HS8', 'Toxina de ave', 'category', false, false, 'CIE-11'),
('XM5V29', 'Toxina de ave ifrita', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XM5Y38', 'Toxina de ave Pitohui', 'category', false, false, 'CIE-11'),
('XM35H6', 'Toxina de mamífero', 'category', false, false, 'CIE-11'),
('XM27R8', 'Veneno de ornitorrinco', 'category', false, false, 'CIE-11'),
('XM8EC2', 'Veneno de musaraña', 'category', false, false, 'CIE-11'),
('XM9R52', 'Veneno de loris perezoso', 'category', false, false, 'CIE-11'),
('XM67Y0', 'Veneno de Solenodon', 'category', false, false, 'CIE-11'),
('XM6NB8', 'Veneno de murciélago vampiro', 'category', false, false, 'CIE-11'),
('XM2P96', 'Toxinas de animales marinos y de agua dulce', 'category', false, false, 'CIE-11'),
('XM99J1', 'Veneno de animales marinos y de agua dulce', 'category', false, false, 'CIE-11'),
('XM2GR5', 'Veneno de pulpo de anillos azules', 'category', false, false, 'CIE-11'),
('XM56D3', 'Veneno de estrella quebradiza', 'category', false, false, 'CIE-11'),
('XM0CW4', 'Veneno de coral', 'category', false, false, 'CIE-11'),
('XM65N5', 'Veneno de coral de fuego', 'category', false, false, 'CIE-11'),
('XM0R26', 'Veneno de coral blando', 'category', false, false, 'CIE-11'),
('XM05Z4', 'Veneno de pescado', 'category', false, false, 'CIE-11'),
('XM0UJ4', 'Veneno de pescado Cobbler', 'category', false, false, 'CIE-11'),
('XM6643', 'Veneno de tiburón cazón', 'category', false, false, 'CIE-11'),
('XM3DB5', 'Veneno de tiburón fantasma', 'category', false, false, 'CIE-11'),
('XM5FP5', 'Veneno de pescado duende', 'category', false, false, 'CIE-11'),
('XM4CL4', 'Veneno de pez león', 'category', false, false, 'CIE-11'),
('XM17D1', 'Veneno de pez conejo', 'category', false, false, 'CIE-11'),
('XM5V26', 'Veneno de pez escorpión', 'category', false, false, 'CIE-11'),
('XM73V9', 'Veneno del pez Stargazer', 'category', false, false, 'CIE-11'),
('XM7P10', 'Veneno de raya', 'category', false, false, 'CIE-11'),
('XM8P00', 'Veneno de pez piedra', 'category', false, false, 'CIE-11'),
('XM83T2', 'Veneno del pez blenny rayado', 'category', false, false, 'CIE-11'),
('XM0784', 'Veneno de bagre anguila rayado', 'category', false, false, 'CIE-11'),
('XM33N5', 'Veneno del pez sapo', 'category', false, false, 'CIE-11'),
('XM0U57', 'Veneno de pez avispa', 'category', false, false, 'CIE-11'),
('XM1VW1', 'Veneno de pez gordo', 'category', false, false, 'CIE-11'),
('XM9YA3', 'Veneno de medusa', 'category', false, false, 'CIE-11'),
('XM4057', 'Veneno de medusa de caja', 'category', false, false, 'CIE-11'),
('XM0ZB2', 'Veneno de medusa Irukandji', 'category', false, false, 'CIE-11'),
('XM87R6', 'Veneno de avispa marina', 'category', false, false, 'CIE-11'),
('XM6PY9', 'Veneno de medusa melena de león', 'category', false, false, 'CIE-11'),
('XM8EA9', 'Veneno de ortiga marina', 'category', false, false, 'CIE-11'),
('XM6S92', 'Veneno de guerra o de hombre Portugués', 'category', false, false, 'CIE-11'),
('XM41L4', 'Veneno de anémona de mar', 'category', false, false, 'CIE-11'),
('XM2HU5', 'Veneno de pepino de mar', 'category', false, false, 'CIE-11'),
('XM2M75', 'Veneno de erizo de mar', 'category', false, false, 'CIE-11'),
('XM48L3', 'Veneno de caracol', 'category', false, false, 'CIE-11'),
('XM7A02', 'Veneno de estrella de mar', 'category', false, false, 'CIE-11'),
('XM3X53', 'Veneno de estrella de mar corona de espinas', 'category', false, false, 'CIE-11'),
('XM3BZ7', 'Veneno de mariscos', 'category', false, false, 'CIE-11'),
('XM1KF5', 'Veneno de mariscos cangrejos', 'category', false, false, 'CIE-11'),
('XM7V29', 'Veneno de pescado de mar', 'category', false, false, 'CIE-11'),
('XM1DD9', 'Veneno de pez ciguatera', 'category', false, false, 'CIE-11'),
('XM7N43', 'Veneno de tiburón de Groenlandia', 'category', false, false, 'CIE-11'),
('XM33K2', 'Veneno de pez globo', 'category', false, false, 'CIE-11'),
('XM74Y6', 'Veneno del pez escombroide', 'category', false, false, 'CIE-11'),
('XM40D3', 'Veneno de pez sapo', 'category', false, false, 'CIE-11'),
('XM5QW5', 'Veneno del pez pepino de mar', 'category', false, false, 'CIE-11'),
('XM51R6', 'Veneno del caracol de mar', 'category', false, false, 'CIE-11'),
('XM7VB5', 'Veneno de mariscos', 'category', false, false, 'CIE-11'),
('XM3XQ0', 'Veneno de ostra', 'category', false, false, 'CIE-11'),
('XM3S96', 'Veneno de la almeja', 'category', false, false, 'CIE-11'),
('XM3KC2', 'Veneno de vieira', 'category', false, false, 'CIE-11'),
('XM41B9', 'Veneno de mejillón', 'category', false, false, 'CIE-11'),
('XM7DB8', 'Veneno de tortuga', 'category', false, false, 'CIE-11'),
('XM2YA1', 'Veneno de tortuga de caja', 'category', false, false, 'CIE-11'),
('XM1C12', 'Veneno de tortuga verde marina', 'category', false, false, 'CIE-11'),
('XM0RH0', 'Veneno de tortuga de carey marina', 'category', false, false, 'CIE-11'),
('XM2X61', 'Veneno de reptil', 'category', false, false, 'CIE-11'),
('XM4RP9', 'Veneno de lagarto', 'category', false, false, 'CIE-11'),
('XM5HY6', 'Veneno de lagarto de cuentas', 'category', false, false, 'CIE-11'),
('XM7HD4', 'Veneno de lagarto monstruo de Gila', 'category', false, false, 'CIE-11'),
('XM4KN1', 'Veneno de serpiente', 'category', false, false, 'CIE-11'),
('XM6UB3', 'Veneno de serpiente de mar', 'category', false, false, 'CIE-11'),
('XM8DS9', 'Veneno de serpiente terrestre', 'category', false, false, 'CIE-11'),
('XM9034', 'Veneno de serpiente víbora', 'category', false, false, 'CIE-11'),
('XM4R63', 'Veneno de serpiente víbora sopladora', 'category', false, false, 'CIE-11'),
('XM8DE0', 'Veneno de serpiente víbora de la muerte', 'category', false, false, 'CIE-11'),
('XM2J41', 'Veneno de serpiente víbora europea', 'category', false, false, 'CIE-11'),
('XM6CL7', 'Veneno de serpiente cabeza de cobre', 'category', false, false, 'CIE-11'),
('XM5UK6', 'Veneno de serpiente víbora áspid', 'category', false, false, 'CIE-11'),
('XM3DZ2', 'Veneno de serpiente negra australasiana', 'category', false, false, 'CIE-11'),
('XM9E44', 'Veneno de serpiente mulga', 'category', false, false, 'CIE-11'),
('XM5MD7', 'Veneno de serpiente marrón australiana', 'category', false, false, 'CIE-11'),
('XM2UN5', 'Veneno de serpiente marrón común', 'category', false, false, 'CIE-11'),
('XM1FY9', 'Veneno de serpiente de cabeza de cobre australiana', 'category', false, false, 'CIE-11'),
('XM0RN4', 'Veneno de serpiente boomslang', 'category', false, false, 'CIE-11'),
('XM26Z0', 'Veneno de serpiente víbora de los arbustos', 'category', false, false, 'CIE-11'),
('XM2650', 'Veneno de serpiente Bushmaster', 'category', false, false, 'CIE-11'),
('XM6HP1', 'Veneno de serpiente víbora de la alfombra', 'category', false, false, 'CIE-11'),
('XM1R49', 'Veneno de serpiente cobra', 'category', false, false, 'CIE-11'),
('XM45D4', 'Veneno de serpiente cobra china', 'category', false, false, 'CIE-11'),
('XM4760', 'Veneno de serpiente cobra Egipcia', 'category', false, false, 'CIE-11'),
('XM6052', 'Veneno de serpiente cobra India', 'category', false, false, 'CIE-11'),
('XM0W24', 'Veneno de serpiente cobra rey', 'category', false, false, 'CIE-11'),
('XM1UH2', 'Veneno de serpiente cobra del norte de Filipinas', 'category', false, false, 'CIE-11'),
('XM5F28', 'Veneno de serpiente cobra escupidora', 'category', false, false, 'CIE-11'),
('XM7LZ0', 'Veneno de serpiente cobra escupidora de cuello negro', 'category', false, false, 'CIE-11'),
('XM69M0', 'Veneno de serpiente cobra escupidora de Java', 'category', false, false, 'CIE-11'),
('XM6U92', 'Veneno de cobra escupidora de Mozambique', 'category', false, false, 'CIE-11'),
('XM2B16', 'Veneno de serpiente cobra escupidora roja', 'category', false, false, 'CIE-11'),
('XM7BF9', 'Veneno de cobra escupida marrón africana occidental', 'category', false, false, 'CIE-11'),
('XM7P11', 'Veneno de serpiente cobra de árbol', 'category', false, false, 'CIE-11'),
('XM4WV8', 'Veneno de serpiente de coral', 'category', false, false, 'CIE-11'),
('XM2PM7', 'Veneno de serpiente de coral arlequín', 'category', false, false, 'CIE-11'),
('XM0EN5', 'Veneno de serpiente de coral de Texas', 'category', false, false, 'CIE-11'),
('XM5A72', 'Veneno de serpiente víbora del desierto', 'category', false, false, 'CIE-11'),
('XM2RJ2', 'Veneno de serpiente de la víbora de Gabón', 'category', false, false, 'CIE-11'),
('XM6LU5', 'Veneno de serpiente viperina cornuda', 'category', false, false, 'CIE-11'),
('XM7WL0', 'Veneno de serpiente víbora de nariz jorobada', 'category', false, false, 'CIE-11'),
('XM7TD0', 'Veneno de serpiente krait', 'category', false, false, 'CIE-11'),
('XM2RD0', 'Veneno de serpiente krait con bandas', 'category', false, false, 'CIE-11'),
('XM5J22', 'Veneno de serpiente krait India', 'category', false, false, 'CIE-11'),
('XM78S0', 'Veneno de serpiente krait Malaya', 'category', false, false, 'CIE-11'),
('XM7JF1', 'Veneno de serpiente cabeza de lanza', 'category', false, false, 'CIE-11'),
('XM2267', 'Veneno de serpiente común cabeza de lanza', 'category', false, false, 'CIE-11'),
('XM9Y58', 'Veneno de serpiente cabeza de lanza', 'category', false, false, 'CIE-11'),
('XM40A2', 'Veneno de serpiente víbora de Levante', 'category', false, false, 'CIE-11'),
('XM9JL4', 'Veneno de serpiente mamba', 'category', false, false, 'CIE-11'),
('XM2SH0', 'Veneno de serpiente mamba negra', 'category', false, false, 'CIE-11'),
('XM1RM0', 'Veneno de serpiente mamba verde.', 'category', false, false, 'CIE-11'),
('XM8E53', 'Veneno de serpiente mamba de Jameson', 'category', false, false, 'CIE-11'),
('XM1GY6', 'Veneno de serpiente mamba verde occidental', 'category', false, false, 'CIE-11'),
('XM81Z8', 'Veneno de serpiente víbora topo', 'category', false, false, 'CIE-11'),
('XM3G20', 'Veneno de serpiente víbora morisca', 'category', false, false, 'CIE-11'),
('XM2A66', 'Veneno de serpiente víbora otomana', 'category', false, false, 'CIE-11'),
('XM88F6', 'Veneno de serpiente víbora palestina', 'category', false, false, 'CIE-11'),
('XM1504', 'Veneno de serpiente de cascabel', 'category', false, false, 'CIE-11'),
('XM3RE1', 'Veneno de serpiente de cascabel de espalda de diamante del este', 'category', false, false, 'CIE-11'),
('XM1RY2', 'Veneno de serpiente de cascabel de Mojave', 'category', false, false, 'CIE-11'),
('XM8MU5', 'Veneno de serpiente de cascabel de pradera', 'category', false, false, 'CIE-11'),
('XM2P01', 'Veneno de cascabel de madera', 'category', false, false, 'CIE-11'),
('XM5JD1', 'Veneno de serpiente de cascabel de espalda de diamante occidental', 'category', false, false, 'CIE-11'),
('XM8JD0', 'Veneno de serpiente de la víbora russell', 'category', false, false, 'CIE-11'),
('XM4SM0', 'Veneno de la serpiente taipan', 'category', false, false, 'CIE-11'),
('XM5T51', 'Veneno de la serpiente taipan de la costa', 'category', false, false, 'CIE-11'),
('XM7NG4', 'Veneno de la serpiente taipan del interior', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;