BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('QA0A.Y', 'Otro examen de detección especial especificado para otras enfermedades o trastornos', 'category', false, false, 'CIE-11'),
('QA0A.Z', 'Examen de detección especial para otras enfermedades o trastornos, sin especificación', 'category', false, false, 'CIE-11'),
('QA0B', 'Examen previo a un procedimiento', 'category', false, false, 'CIE-11'),
('QA0Y', 'Otro contacto especificado con los servicios de salud con el propósito de hacer un examen o una investigación', 'category', false, false, 'CIE-11'),
('QA0Z', 'Contacto con los servicios de salud con el propósito de hacer un examen o una investigación, sin especificación', 'category', false, false, 'CIE-11'),
('QA10', 'Contacto con los servicios de salud para vigilancia o asesoramiento dietético', 'category', false, false, 'CIE-11'),
('QA11', 'Contacto con los servicios de salud para vigilancia o asesoramiento por el consumo de alcohol', 'category', false, false, 'CIE-11'),
('QA12', 'Contacto con los servicios de salud para vigilancia o asesoramiento por uso de drogas', 'category', false, false, 'CIE-11'),
('QA13', 'Contacto con los servicios de salud para asesoramiento por uso de tabaco', 'category', false, false, 'CIE-11'),
('QA14', 'Contacto con los servicios de salud para asesoramiento sobre el virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('QA15', 'Asesoramiento relacionado con la sexualidad', 'category', false, false, 'CIE-11'),
('QA15.0', 'Asesoramiento relacionado con las actitudes sexuales', 'category', false, false, 'CIE-11'),
('QA15.1', 'Asesoramiento relacionado con el comportamiento y la orientación sexuales o las relaciones sexuales de la persona', 'category', false, false, 'CIE-11'),
('QA15.2', 'Asesoramiento relacionado con el comportamiento y la orientación sexuales o las relaciones sexuales de terceros', 'category', false, false, 'CIE-11'),
('QA15.3', 'Asesoramiento relacionado con las actitudes, el comportamiento y las relaciones sexuales combinados', 'category', false, false, 'CIE-11'),
('QA15.Y', 'Otro asesoramiento especificado relacionado con la sexualidad', 'category', false, false, 'CIE-11'),
('QA15.Z', 'Asesoramiento relacionado con la sexualidad, sin especificación', 'category', false, false, 'CIE-11'),
('QA16', 'Asesoramiento psicológico o comportamental de tipo individual', 'category', false, false, 'CIE-11'),
('QA17', 'Asesoramiento de pareja o conyugal', 'category', false, false, 'CIE-11'),
('QA18', 'Asesoramiento familiar', 'category', false, false, 'CIE-11'),
('QA19', 'Asesoramiento grupal', 'category', false, false, 'CIE-11'),
('QA1A', 'Consideración de temas relacionados con la muerte inminente', 'category', false, false, 'CIE-11'),
('QA1B', 'Preocupación o temor por tratamiento médico', 'category', false, false, 'CIE-11'),
('QA1C', 'Persona sin diagnóstico que teme presentar síntomas', 'category', false, false, 'CIE-11'),
('QA1Y', 'Otros contactos especificados con los servicios de salud para asesoramiento', 'category', false, false, 'CIE-11'),
('QA1Z', 'Contacto con los servicios de salud para asesoramiento, sin especificación', 'category', false, false, 'CIE-11'),
('QA20', 'Contacto con los servicios de salud por preocupaciones acerca del embarazo', 'category', false, false, 'CIE-11'),
('QA21', 'Contacto con los servicios de salud para atención relativa a la anticoncepción', 'category', false, false, 'CIE-11'),
('QA21.0', 'Contacto con los servicios de salud para anticoncepción poscoital', 'category', false, false, 'CIE-11'),
('QA21.1', 'Contacto con los servicios de salud para asesoramiento o consejo general sobre anticoncepción', 'category', false, false, 'CIE-11'),
('QA21.2', 'Contacto con los servicios de salud para inserción de dispositivo anticonceptivo', 'category', false, false, 'CIE-11'),
('QA21.3', 'Contacto con los servicios de salud para esterilización', 'category', false, false, 'CIE-11'),
('QA21.4', 'Contacto con los servicios de salud para extracción menstrual', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('QA21.5', 'Vigilancia de medicamentos anticonceptivos', 'category', false, false, 'CIE-11'),
('QA21.6', 'Vigilancia de dispositivo anticonceptivo', 'category', false, false, 'CIE-11'),
('QA21.60', 'Retención de dispositivo intrauterino sin lesión ni daño en útero no gestante', 'category', false, false, 'CIE-11'),
('QA21.6Y', 'Otra vigilancia especificada del dispositivo anticonceptivo', 'category', false, false, 'CIE-11'),
('QA21.6Z', 'Vigilancia del dispositivo anticonceptivo, sin especificación', 'category', false, false, 'CIE-11'),
('QA21.Y', 'Otro contacto especificado con los servicios de salud para el manejo de la anticoncepción', 'category', false, false, 'CIE-11'),
('QA21.Z', 'Contacto con los servicios de salud para el manejo de la anticoncepción, sin especificación', 'category', false, false, 'CIE-11'),
('QA30', 'Contacto con los servicios de salud para la reproducción médicamente asistida', 'category', false, false, 'CIE-11'),
('QA30.0', 'Contacto con los servicios de salud para la inseminación artificial', 'category', false, false, 'CIE-11'),
('QA30.00', 'Contacto con los servicios de salud para la transferencia de gametos intratubárica', 'category', false, false, 'CIE-11'),
('QA30.01', 'Contacto con los servicios de salud para la procreación mediante inseminación artificial', 'category', false, false, 'CIE-11'),
('QA30.02', 'Contacto con los servicios de salud para la inseminación de esperma médicamente asistida', 'category', false, false, 'CIE-11'),
('QA30.0Y', 'Contacto con los servicios de salud para otra inseminación asistida especificada', 'category', false, false, 'CIE-11'),
('QA30.0Z', 'Contacto con los servicios de salud para inseminación asistida, sin especificación', 'category', false, false, 'CIE-11'),
('QA30.1', 'Contacto con los servicios de salud para tecnología de reproducción asistida', 'category', false, false, 'CIE-11'),
('QA30.10', 'Contacto con los servicios de salud para la fertilización in vitro', 'category', false, false, 'CIE-11'),
('QA30.11', 'recuperación de óvulos', 'category', false, false, 'CIE-11'),
('QA30.12', 'Contacto con los servicios de salud para la transferencia de embriones', 'category', false, false, 'CIE-11'),
('QA30.13', 'Contacto con los servicios de salud para la implantación de óvulos', 'category', false, false, 'CIE-11'),
('QA30.14', 'Contacto con los servicios de salud para la extracción de óvulos para la fertilización in vitro', 'category', false, false, 'CIE-11'),
('QA30.15', 'Contacto con los servicios de salud para la extracción o implantación de óvulos', 'category', false, false, 'CIE-11'),
('QA30.1Y', 'Otro contacto con los servicios de salud para tecnología reproductiva asistida especificada', 'category', false, false, 'CIE-11'),
('QA30.1Z', 'Contacto con los servicios de salud para tecnología reproductiva asistida, sin especificación', 'category', false, false, 'CIE-11'),
('QA30.2', 'Contacto con los servicios de salud para otros métodos de fertilización asistida', 'category', false, false, 'CIE-11'),
('QA30.20', 'Contacto con los servicios de salud a fin de realizar estimulación ovárica controlada para tecnología reproductiva asistida', 'category', false, false, 'CIE-11'),
('QA30.21', 'Contacto con los servicios de salud a fin de realizar estimulación ovárica controlada para ciclos que no requieren tecnología reproductiva asistida', 'category', false, false, 'CIE-11'),
('QA30.22', 'Contacto con servicios de salud para inducir la ovulación', 'category', false, false, 'CIE-11'),
('QA30.2Y', 'Contacto con los servicios de salud para otros métodos específicos de fertilización asistida', 'category', false, false, 'CIE-11'),
('QA30.2Z', 'Contacto con los servicios de salud para otros métodos de fertilización asistida, sin especificación', 'category', false, false, 'CIE-11'),
('QA30.Y', 'Otro contacto especificado con los servicios de salud para la reproducción médicamente asistida', 'category', false, false, 'CIE-11'),
('QA30.Z', 'Contacto con los servicios de salud para la reproducción médicamente asistida, sin especificación', 'category', false, false, 'CIE-11'),
('QA31', 'Contacto con los servicios de salud para asesoramiento genético', 'category', false, false, 'CIE-11'),
('QA32', 'Contacto con los servicios de salud para tuboplastia o vasoplastia posterior a esterilización', 'category', false, false, 'CIE-11'),
('QA33', 'Contacto con los servicios de salud para asesoramiento preconcepcional', 'category', false, false, 'CIE-11'),
('QA34', 'Contacto con los servicios de salud para asesoramiento en cuanto a la preservación de la fertilidad', 'category', false, false, 'CIE-11'),
('QA35', 'Contacto con los servicios de salud por parte de portadora gestacional', 'category', false, false, 'CIE-11'),
('QA3Y', 'Otro contacto especificado con los servicios de salud para el manejo de la procreación', 'category', false, false, 'CIE-11'),
('QA3Z', 'Contacto con los servicios de salud para el manejo de la procreación, sin especificación', 'category', false, false, 'CIE-11'),
('QA40', 'Examen o prueba de embarazo', 'category', false, false, 'CIE-11'),
('QA41', 'Estado de embarazo', 'category', false, false, 'CIE-11'),
('QA42', 'Supervisión de embarazo normal', 'category', false, false, 'CIE-11'),
('QA42.0', 'Vigilancia de primer embarazo normal', 'category', false, false, 'CIE-11'),
('QA42.Y', 'Supervisión de otro embarazo normal especificado', 'category', false, false, 'CIE-11'),
('QA42.Z', 'Supervisión de embarazo normal, sin especificación', 'category', false, false, 'CIE-11'),
('QA43', 'Supervisión de embarazo de alto riesgo', 'category', false, false, 'CIE-11'),
('QA43.0', 'Supervisión de embarazo con antecedente de esterilidad', 'category', false, false, 'CIE-11'),
('QA43.1', 'Supervisión de embarazo con antecedente de aborto', 'category', false, false, 'CIE-11'),
('QA43.2', 'Supervisión de embarazo con antecedentes de otros problemas reproductivos u obstétricos', 'category', false, false, 'CIE-11'),
('QA43.3', 'Supervisión de embarazo con antecedente de cuidado prenatal insuficiente', 'category', false, false, 'CIE-11'),
('QA43.30', 'Embarazo oculto', 'category', false, false, 'CIE-11'),
('QA43.3Y', 'Otra supervisión especificada de embarazo con antecedente de cuidado prenatal insuficiente', 'category', false, false, 'CIE-11'),
('QA43.3Z', 'Supervisión de embarazo con antecedente de cuidado prenatal insuficiente, sin especificación', 'category', false, false, 'CIE-11'),
('QA43.4', 'Supervisión de primigrávida tardía', 'category', false, false, 'CIE-11'),
('QA43.5', 'Supervisión de primigesta muy joven', 'category', false, false, 'CIE-11'),
('QA43.6', 'Supervisión de embarazo de alto riesgo debido a problemas sociales', 'category', false, false, 'CIE-11'),
('QA43.Y', 'Otra supervisión especificada de embarazo de alto riesgo', 'category', false, false, 'CIE-11'),
('QA43.Z', 'Supervisión de embarazo de alto riesgo, sin especificación', 'category', false, false, 'CIE-11'),
('QA44', 'Consulta de los futuros padres antes del nacimiento', 'category', false, false, 'CIE-11'),
('QA45', 'Evaluación prenatal', 'category', false, false, 'CIE-11'),
('QA45.0', 'Detección prenatal de anomalías cromosómicas', 'category', false, false, 'CIE-11'),
('QA45.1', 'Examen prenatal debido a nivel elevado de alfafetoproteínas', 'category', false, false, 'CIE-11'),
('QA45.Y', 'Otra evaluación prenatal especificada', 'category', false, false, 'CIE-11'),
('QA45.Z', 'Evaluación prenatal, sin especificación', 'category', false, false, 'CIE-11'),
('QA46', 'Resultado del parto', 'category', false, false, 'CIE-11'),
('QA46.0', 'Nacido vivo, único', 'category', false, false, 'CIE-11'),
('QA46.1', 'Mortinato, único', 'category', false, false, 'CIE-11'),
('QA46.2', 'Gemelos, ambos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.3', 'Gemelos, uno nacido vivo y uno nacido muerto', 'category', false, false, 'CIE-11'),
('QA46.4', 'Gemelos, ambos mortinatos', 'category', false, false, 'CIE-11'),
('QA46.5', 'Trillizos, todos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.6', 'Trillizos, algunos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.7', 'Trillizos, todos morrtinatos', 'category', false, false, 'CIE-11'),
('QA46.8', 'Cuatrillizos, todos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.9', 'Cuatrillizos, algunos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.A', 'Cuatrillizos, todos morrtinatos', 'category', false, false, 'CIE-11'),
('QA46.B', 'Quintillizos, todos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.C', 'Quintillizos, algunos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.D', 'Quintillizos, todos mortinatos', 'category', false, false, 'CIE-11'),
('QA46.E', 'Sextillizos, todos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.F', 'Sextillizos, algunos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.G', 'Sextillizos, todos mortinatos', 'category', false, false, 'CIE-11'),
('QA46.H', 'otro parto múltiple, todos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.J', 'Otros partos múltiples, algunos nacidos vivos', 'category', false, false, 'CIE-11'),
('QA46.K', 'Otros partos múltiples, todos mortinatos', 'category', false, false, 'CIE-11'),
('QA46.Z', 'Resultado del parto, sin especificación', 'category', false, false, 'CIE-11'),
('QA47', 'Nacidos vivos según lugar de nacimiento', 'category', false, false, 'CIE-11'),
('QA47.0', 'Producto único, nacido en hospital', 'category', false, false, 'CIE-11'),
('QA47.00', 'Nacido vivo único, por parto vaginal', 'category', false, false, 'CIE-11'),
('QA47.01', 'Nacido vivo único, por cesárea', 'category', false, false, 'CIE-11'),
('QA47.0Y', 'Otro producto único, nacido en hospital', 'category', false, false, 'CIE-11'),
('QA47.0Z', 'Producto único, nacido en hospital, sin especificación', 'category', false, false, 'CIE-11'),
('QA47.1', 'Producto único, nacido fuera de hospital', 'category', false, false, 'CIE-11'),
('QA47.2', 'Producto único, lugar de nacimiento no especificado', 'category', false, false, 'CIE-11'),
('QA47.3', 'Gemelo, nacido en hospital', 'category', false, false, 'CIE-11'),
('QA47.30', 'Gemelo nacido vivo por parto vaginal', 'category', false, false, 'CIE-11'),
('QA47.31', 'Gemelo nacido vivo por cesárea', 'category', false, false, 'CIE-11'),
('QA47.3Y', 'Otro gemelo especificado, nacido en hospital', 'category', false, false, 'CIE-11'),
('QA47.3Z', 'Gemelo, nacido en hospital, sin especificación', 'category', false, false, 'CIE-11'),
('QA47.4', 'Gemelo, nacido fuera de hospital', 'category', false, false, 'CIE-11'),
('QA47.5', 'Gemelo, lugar de nacimiento no especificado', 'category', false, false, 'CIE-11'),
('QA47.6', '', 'category', false, false, 'CIE-11'),
('QA47.60', 'Nacido vivo de parto múltiple salvo gemelar, nacido por parto vaginal', 'category', false, false, 'CIE-11'),
('QA47.61', 'Nacido vivo de parto múltiple salvo gemelar, nacido por cesárea', 'category', false, false, 'CIE-11'),
('QA47.6Y', 'Nacido vivo especificado de parto múltiple salvo gemelar, nacido en el hospital', 'category', false, false, 'CIE-11'),
('QA47.6Z', 'Nacido vivo de parto múltiple salvo gemelar, nacido en el hospital, sin especificación', 'category', false, false, 'CIE-11'),
('QA47.7', '', 'category', false, false, 'CIE-11'),
('QA47.8', 'Nacido vivo de embarazo múltiple, lugar de nacimiento no especificado', 'category', false, false, 'CIE-11'),
('QA47.Z', 'Nacidos vivos según lugar de nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('QA48', 'Atención o examen en el posparto', 'category', false, false, 'CIE-11'),
('QA48.0', 'Atención o examen inmediatamente después del parto', 'category', false, false, 'CIE-11'),
('QA48.1', 'Atención o examen de la madre lactante', 'category', false, false, 'CIE-11'),
('QA48.2', 'Seguimiento de rutina del posparto', 'category', false, false, 'CIE-11'),
('QA48.Y', 'Otra atención o examen especificado en el posparto', 'category', false, false, 'CIE-11'),
('QA48.Z', 'Atención o examen en el posparto, sin especificación', 'category', false, false, 'CIE-11'),
('QA49', 'Problemas relacionados con embarazo no deseado', 'category', false, false, 'CIE-11'),
('QA4A', 'Problemas relacionados con la multiparidad', 'category', false, false, 'CIE-11'),
('QA4B', 'Contacto con los servicios de salud para consejo sobre menopausia', 'category', false, false, 'CIE-11'),
('QA4Y', 'Otros contactos especificados con los servicios de salud por razones asociadas con la reproducción', 'category', false, false, 'CIE-11'),
('QA4Z', 'Contacto con los servicios de salud por razones asociadas con la reproducción, sin especificación', 'category', false, false, 'CIE-11'),
('QA50', 'Embolización, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA51', 'Cuerpo extraño accidentalmente dejado en el cuerpo, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA52', 'Falla de las precauciones de esterilización, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA53', 'Presión como posible modo de lesión, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA5Y', 'Otros eventos especificados asociados con un procedimiento quirúrgico u otro procedimiento médico que influyen en el episodio de atención, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA5Z', 'Eventos asociados con un procedimiento quirúrgico u otro procedimiento médico que influyen en el episodio de atención, sin daño o lesión, sin especificación', 'category', false, false, 'CIE-11'),
('QA60', 'Falla estructural de un dispositivo, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA61', 'Falla funcional de un dispositivo, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA62', 'Desplazamiento, mala conexión o desconexión de un dispositivo médico o quirúrgico, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA63', 'Obstrucción de un dispositivo, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA64', 'Error del operador, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA65', 'Combinación o interacción de un error del operador y una falla del dispositivo, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA6Y', 'Otras circunstancias especificadas asociadas con un dispositivo quirúrgico u otro dispositivo médico que influye en el episodio de la atención, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA6Z', 'Circunstancias asociadas con un dispositivo quirúrgico u otro dispositivo médico que influyen en el episodio de atención, sin daño o lesión, sin especificación', 'category', false, false, 'CIE-11'),
('QA70', 'Sobredosis de sustancia, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA71', 'Dosificación menor, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA72', 'Sustancia incorrecta, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA73', 'Vía de administración incorrecta, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA74', 'Dosificación o vía de administración sin especificación de su idoneidad, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA75', 'Duración incorrecta de la administración o del curso de tratamiento, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA76', 'Medicamento o sustancia que se sabe que es un alérgeno, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA77', 'Medicamento o sustancia que se sabe que está contraindicada para el paciente, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA78', 'Medicamento o sustancia vencida o deteriorada, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA79', 'Interacciones con fármacos o sustancias, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA7A', 'Interrupción o discontinuación inapropiados de un fármaco, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA7Y', 'Otros eventos asociados especificados con la exposición a una droga, medicamento o sustancia biológica que influyen en el episodio de atención, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA7Z', 'Eventos asociados con la exposición a una droga, medicamento o sustancia biológica que influyen en el episodio de atención, sin daño o lesión, sin especificación', 'category', false, false, 'CIE-11'),
('QA80', 'No se administró un medicamento necesario, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA81', 'No se proporcionó el procedimiento necesario, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA82', 'Problema asociado con la transferencia física del paciente, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA83', 'Tipo de sangre incorrecto usado en una transfusión, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA84', 'Otro problema con una transfusión, sin lesión o daño', 'category', false, false, 'CIE-11'),
('QA85', 'Problema con las restricciones físicas, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA86', 'Problema con el protocolo de aislamiento, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA87', 'Problema con la documentación clínica, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA88', 'Problema con el software clínico, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA89', 'Diagnóstico incorrecto, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8A', 'Retraso en el diagnóstico, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8B', 'Retraso en el tratamiento, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8C', 'Problemas con las transiciones en el cuidado, los pasos de turno o de guardia, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8D', 'Paciente que recibió una prueba de diagnóstico o tratamiento destinado a otro paciente, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8E', 'Caída durante la atención médica, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8F', 'Pinchadura de aguja, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8Y', 'Otras circunstancias especificadas asociadas con otros aspectos de la atención que influyen en el episodio de atención, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QA8Z', 'Circunstancias asociadas con otros aspectos de la atención que influyen en el episodio de atención sin daño o lesión, sin especificación', 'category', false, false, 'CIE-11'),
('QB0Y', 'Otras circunstancias relacionadas con la atención médica especificadas que influyen en el episodio de atención, sin daño o lesión', 'category', false, false, 'CIE-11'),
('QB0Z', 'Circunstancias relacionados con la atención médica que influyen en el episodio de atención, sin daño o lesión, sin especificación', 'category', false, false, 'CIE-11'),
('QB10', 'Servicios médicos no disponibles en el domicilio', 'category', false, false, 'CIE-11'),
('QB11', 'Persona en espera de ser admitida en un centro adecuado en otro lugar', 'category', false, false, 'CIE-11'),
('QB12', 'Período de espera para investigación o tratamiento que no sea esperar la admisión a un centro adecuado en otro lugar', 'category', false, false, 'CIE-11'),
('QB12.0', 'Candidato a un trasplante de órganos', 'category', false, false, 'CIE-11'),
('QB12.Y', 'Otro período de espera especificado para la investigación o tratamiento que no sea la espera de la admisión a un centro adecuado en otro lugar', 'category', false, false, 'CIE-11'),
('QB12.Z', 'Período de espera para investigación o tratamiento que no sea esperar la admisión a un centro adecuado en otro lugar, sin especificación', 'category', false, false, 'CIE-11'),
('QB13', 'Falta de disponibilidad o inaccesibilidad para ayudar a las entidades que no sean establecimientos de atención de salud', 'category', false, false, 'CIE-11'),
('QB14', 'Falta de disponibilidad o inaccesibilidad de los establecimientos de atención de salud', 'category', false, false, 'CIE-11'),
('QB15', 'Servicios médicos no disponibles en los establecimientos médicos actuales', 'category', false, false, 'CIE-11'),
('QB16', 'Cuidado de descanso', 'category', false, false, 'CIE-11'),
('QB1Y', 'Otros factores relacionados especificados con los servicios médicos u otros servicios de salud', 'category', false, false, 'CIE-11'),
('QB1Z', 'Factores relacionados con los servicios médicos u otros servicios de salud, sin especificación', 'category', false, false, 'CIE-11'),
('QB20', 'Donante de sangre', 'category', false, false, 'CIE-11'),
('QB21', 'Donante de médula ósea', 'category', false, false, 'CIE-11'),
('QB22', 'Donante de riñón', 'category', false, false, 'CIE-11'),
('QB23', 'Donante de córnea', 'category', false, false, 'CIE-11'),
('QB24', 'Donante de hígado', 'category', false, false, 'CIE-11'),
('QB25', 'Donante de corazón', 'category', false, false, 'CIE-11'),
('QB2Y', 'Otros donantes especificados de órganos o tejidos', 'category', false, false, 'CIE-11'),
('QB2Z', 'Donantes de órganos o tejidos, sin especificación', 'category', false, false, 'CIE-11'),
('QB30', 'Ajuste o manejo de dispositivos implantados', 'category', false, false, 'CIE-11'),
('QB30.0', 'Ajuste o manejo de un dispositivo auditivo implantado', 'category', false, false, 'CIE-11'),
('QB30.00', 'Ajuste o manejo de un dispositivo de conducción ósea', 'category', false, false, 'CIE-11'),
('QB30.01', 'Ajuste o manejo de un dispositivo coclear', 'category', false, false, 'CIE-11'),
('QB30.0Y', 'Otro ajuste o manejo de un dispositivo auditivo implantado especificado', 'category', false, false, 'CIE-11'),
('QB30.0Z', 'Ajuste o manejo de un dispositivo auditivo implantado, sin especificación', 'category', false, false, 'CIE-11'),
('QB30.1', 'Ajuste o manejo de una bomba de infusión', 'category', false, false, 'CIE-11'),
('QB30.2', 'Ajuste o manejo de dispositivos cardíacos', 'category', false, false, 'CIE-11'),
('QB30.20', 'Ajuste o manejo de un marcapasos cardíaco', 'category', false, false, 'CIE-11'),
('QB30.21', 'Ajuste o manejo del desfibrilador en la terapia de resincronización cardíaca', 'category', false, false, 'CIE-11'),
('QB30.22', 'Ajuste o manejo del marcapasos en la terapia de resincronización cardíaca', 'category', false, false, 'CIE-11'),
('QB30.23', 'Ajuste o manejo de un desfibrilador cardioversor', 'category', false, false, 'CIE-11'),
('QB30.2Y', 'Otro ajuste o manejo especificado de dispositivos cardíacos', 'category', false, false, 'CIE-11'),
('QB30.2Z', 'Ajuste o manejo de dispositivos cardíacos, sin especificación', 'category', false, false, 'CIE-11'),
('QB30.3', 'Ajuste o manejo de un dispositivo de acceso vascular', 'category', false, false, 'CIE-11'),
('QB30.4', 'Ajuste o manejo de un dispositivo gástrico implantado', 'category', false, false, 'CIE-11'),
('QB30.5', 'Colocación o ajuste de un dispositivo urinario', 'category', false, false, 'CIE-11'),
('QB30.6', 'Ajuste o manejo de implantes mamarios', 'category', false, false, 'CIE-11'),
('QB30.7', 'Ajuste o extracción del stent o tubo de miringotomía', 'category', false, false, 'CIE-11'),
('QB30.8', 'Ajuste y manejo de un neuroestimulador', 'category', false, false, 'CIE-11'),
('QB30.9', 'Colocación o ajuste de un dispositivo de drenaje de líquido cefalorraquídeo', 'category', false, false, 'CIE-11'),
('QB30.A', 'Colocación o ajuste de un marcapasos neurológico', 'category', false, false, 'CIE-11'),
('QB30.Y', 'Otro ajuste o manejo especificado de dispositivos implantados', 'category', false, false, 'CIE-11'),
('QB30.Z', 'Ajuste o manejo de dispositivos implantados, sin especificación', 'category', false, false, 'CIE-11'),
('QB31', 'Colocación, ajuste o manejo de dispositivos externos', 'category', false, false, 'CIE-11'),
('QB31.0', 'Colocación o ajuste de una prótesis externa', 'category', false, false, 'CIE-11'),
('QB31.00', 'Colocación o ajuste de brazo artificial', 'category', false, false, 'CIE-11'),
('QB31.01', 'Colocación o ajuste de pierna artificial', 'category', false, false, 'CIE-11'),
('QB31.02', 'Colocación o ajuste de un ojo artificial', 'category', false, false, 'CIE-11'),
('QB31.03', 'Colocación o ajuste de prótesis mamaria externa', 'category', false, false, 'CIE-11'),
('QB31.0Y', 'Otra colocación o ajuste especificada de prótesis externa', 'category', false, false, 'CIE-11'),
('QB31.0Z', 'Colocación o ajuste de prótesis externa, sin especificación', 'category', false, false, 'CIE-11'),
('QB31.1', 'Colocación o ajuste de dispositivo ortopédico', 'category', false, false, 'CIE-11'),
('QB31.2', 'Colocación o ajuste de aparato de ortodoncia', 'category', false, false, 'CIE-11'),
('QB31.3', 'Colocación o ajuste de prótesis dental', 'category', false, false, 'CIE-11'),
('QB31.4', 'Colocación o ajuste de audífono', 'category', false, false, 'CIE-11'),
('QB31.5', 'Colocación o ajuste de anteojos o lentes de contacto', 'category', false, false, 'CIE-11'),
('QB31.Y', 'Colocación, ajuste o manejo de otros dispositivos externos especificados', 'category', false, false, 'CIE-11'),
('QB31.Z', 'Colocación, ajuste o manejo de dispositivos externos, sin especificación', 'category', false, false, 'CIE-11'),
('QB3Z', 'Colocación, ajuste o manejo de dispositivos, sin especificación', 'category', false, false, 'CIE-11'),
('QB40', 'Dependencia de aspirador', 'category', false, false, 'CIE-11'),
('QB41', 'Dependencia de respirador', 'category', false, false, 'CIE-11'),
('QB42', 'Dependencia de la diálisis renal', 'category', false, false, 'CIE-11'),
('QB43', 'Dependencia de corazón artificial', 'category', false, false, 'CIE-11'),
('QB44', 'Dependencia de silla de ruedas', 'category', false, false, 'CIE-11'),
('QB4Y', 'Otra dependencia especificada de máquinas o dispositivos habilitadores', 'category', false, false, 'CIE-11'),
('QB4Z', 'Dependencia de máquinas o dispositivos habilitadores, sin especificación', 'category', false, false, 'CIE-11'),
('QB50', 'Presencia de implantes o injertos cardíacos o vasculares', 'category', false, false, 'CIE-11'),
('QB50.0', 'Presencia de dispositivos cardíacos electrónicos', 'category', false, false, 'CIE-11'),
('QB50.00', 'Presencia de marcapasos cardíaco', 'category', false, false, 'CIE-11'),
('QB50.01', 'Presencia de desfibrilador de terapia de resincronización cardíaca', 'category', false, false, 'CIE-11'),
('QB50.02', 'Presencia de marcapasos de terapia de resincronización cardíaca', 'category', false, false, 'CIE-11'),
('QB50.03', 'Presencia de desfibrilador cardioversor', 'category', false, false, 'CIE-11'),
('QB50.0Y', 'Otra presencia especificada de dispositivos cardíacos electrónicos', 'category', false, false, 'CIE-11'),
('QB50.0Z', 'Presencia de dispositivos cardíacos electrónicos, sin especificación', 'category', false, false, 'CIE-11'),
('QB50.1', 'Presencia de injerto por bypass aortocoronario', 'category', false, false, 'CIE-11'),
('QB50.2', 'Presencia de válvula cardíaca protésica', 'category', false, false, 'CIE-11'),
('QB50.21', 'Presencia de válvula cardíaca mecánica', 'category', false, false, 'CIE-11'),
('QB50.24', 'Presencia de válvula cardíaca bioprostética', 'category', false, false, 'CIE-11'),
('QB50.2Y', 'Otro(a)(s) presencia de válvula cardíaca protésica especificado(a)(s)', 'category', false, false, 'CIE-11'),
('QB50.2Z', 'Presencia de válvula cardíaca protésica, sin especificación', 'category', false, false, 'CIE-11'),
('QB50.4', 'Presencia de implante o injerto por angioplastia coronaria', 'category', false, false, 'CIE-11'),
('QB50.Y', 'Otra presencia de implantes o injertos cardíacos o vasculares especificados', 'category', false, false, 'CIE-11'),
('QB50.Z', 'Presencia de implantes o injertos cardíacos o vasculares, sin especificación', 'category', false, false, 'CIE-11'),
('QB51', 'Presencia de otros dispositivos que no sean implantes cardíacos o vasculares', 'category', false, false, 'CIE-11'),
('QB51.0', 'Presencia de un neuroestimulador', 'category', false, false, 'CIE-11'),
('QB51.1', 'Presencia de implantes urogenitales', 'category', false, false, 'CIE-11'),
('QB51.2', 'Presencia de lente intraocular', 'category', false, false, 'CIE-11'),
('QB51.3', 'Presencia de implantes óticos y auditivos', 'category', false, false, 'CIE-11'),
('QB51.4', 'Presencia de laringe artificial', 'category', false, false, 'CIE-11'),
('QB51.5', 'Presencia de implantes endocrinos', 'category', false, false, 'CIE-11'),
('QB51.6', 'Presencia de implantes de raíz de diente y de mandíbula', 'category', false, false, 'CIE-11'),
('QB51.7', 'Presencia de implantes articulares ortopédicos', 'category', false, false, 'CIE-11'),
('QB51.8', 'Presencia de ojo artificial', 'category', false, false, 'CIE-11'),
('QB51.9', 'Presencia de un miembro artificial', 'category', false, false, 'CIE-11'),
('QB51.A', 'Presencia de prótesis dental', 'category', false, false, 'CIE-11'),
('QB51.B', 'Presencia de audífono externo', 'category', false, false, 'CIE-11'),
('QB51.C', 'Presencia de dispositivo anticonceptivo', 'category', false, false, 'CIE-11'),
('QB51.D', 'Presencia de dispositivo para drenaje de líquido cefalorraquídeo', 'category', false, false, 'CIE-11'),
('QB51.Y', 'Otra presencia especificada de otros dispositivos que no sean implantes cardíacos o vasculares', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;