BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XE94F', 'Hisopo de algodón, torunda de algodón, Q-tip®', 'category', false, false, 'CIE-11'),
('XE1H5', 'Jabón', 'category', false, false, 'CIE-11'),
('XE1B1', 'Desodorante', 'category', false, false, 'CIE-11'),
('XE5DV', 'Perfume, colonia', 'category', false, false, 'CIE-11'),
('XE8PE', 'Preparación para la coloración del cabello', 'category', false, false, 'CIE-11'),
('XE1T3', 'Preparación para la depilación, depilatorio', 'category', false, false, 'CIE-11'),
('XE8EH', 'Otro producto para el cuidado del cabello', 'category', false, false, 'CIE-11'),
('XE3EV', 'Esmalte para uñas', 'category', false, false, 'CIE-11'),
('XE7DF', 'Crema o loción corporal o facial', 'category', false, false, 'CIE-11'),
('XE8W8', 'Polvo corporal, talco', 'category', false, false, 'CIE-11'),
('XE79N', 'Cosméticos, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('XE8NY', 'Productos bronceadores o protectores solares, productos autobronceadores', 'category', false, false, 'CIE-11'),
('XE4KX', 'Aceites esenciales, aceites usados en aromaterapia', 'category', false, false, 'CIE-11'),
('XE3AM', 'Comunicación o utensilio o accesorio relacionado', 'category', false, false, 'CIE-11'),
('XE2A3', 'Teléfono, teléfono móvil, teléfono celular', 'category', false, false, 'CIE-11'),
('XE9K5', 'Computadora personal o accesorio relacionado', 'category', false, false, 'CIE-11'),
('XE38S', 'Máquina de fax y otro equipamiento relacionado', 'category', false, false, 'CIE-11'),
('XE5V8', 'Líquido de corrección de máquina de escribir', 'category', false, false, 'CIE-11'),
('XE38A', 'Pluma, lapiz', 'category', false, false, 'CIE-11'),
('XE1RG', 'Otros artículos de papelería', 'category', false, false, 'CIE-11'),
('XE58R', 'Artes y suministros artesanales', 'category', false, false, 'CIE-11'),
('XE0NW', 'Pintura de artista', 'category', false, false, 'CIE-11'),
('XE2EN', 'Tiza, crayón', 'category', false, false, 'CIE-11'),
('XE6E6', 'Esmaltes', 'category', false, false, 'CIE-11'),
('XE8ZP', 'Lienzo', 'category', false, false, 'CIE-11'),
('XE0X7', 'Ayuda personal', 'category', false, false, 'CIE-11'),
('XE5EM', 'Gafas', 'category', false, false, 'CIE-11'),
('XE293', 'Silla de ruedas', 'category', false, false, 'CIE-11'),
('XE90Y', 'Bastón, andador, barra para caminar,marco para caminar', 'category', false, false, 'CIE-11'),
('XE5W4', 'Prótesis', 'category', false, false, 'CIE-11'),
('XE6ZS', 'Estera de bañera de goma', 'category', false, false, 'CIE-11'),
('XE7P9', 'Tabaco o producto relacionado', 'category', false, false, 'CIE-11'),
('XE01N', 'Cigarrillo, cigarro, pipa', 'category', false, false, 'CIE-11'),
('XE4U8', 'Encendedor, cerilla', 'category', false, false, 'CIE-11'),
('XE0Q7', 'Ayudas para dejar de fumar', 'category', false, false, 'CIE-11'),
('XE2H2', 'Cierto artículo de uso personal especificado', 'category', false, false, 'CIE-11'),
('XE1NP', 'Vaporizador humidificador', 'category', false, false, 'CIE-11'),
('XE1PV', 'Quemador de aceite', 'category', false, false, 'CIE-11'),
('XE7S6', 'Preservativo u otro dispositivo anticonceptivo', 'category', false, false, 'CIE-11'),
('XE9GS', 'Ayudas sexuales', 'category', false, false, 'CIE-11'),
('XE030', 'Despertador, reloj', 'category', false, false, 'CIE-11'),
('XE9R0', 'Paraguas', 'category', false, false, 'CIE-11'),
('XE3T5', 'Monedas', 'category', false, false, 'CIE-11'),
('XE6N6', 'Ventilador de mano', 'category', false, false, 'CIE-11'),
('XE5BJ', 'Pelotas usadas en deporte', 'category', false, false, 'CIE-11'),
('XE9X9', 'Pelota blanda', 'category', false, false, 'CIE-11'),
('XE7M5', 'Disco, pelota dura', 'category', false, false, 'CIE-11'),
('XE68L', 'Equipamiento deportivo portátil', 'category', false, false, 'CIE-11'),
('XE3H8', 'Lanza , jabalina, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE9CT', 'Arco, flecha , perno de ballesta, ballesta, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE557', 'Otro proyectil deportivo especificado', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XE23P', 'Bate, palo de hockey', 'category', false, false, 'CIE-11'),
('XE9MP', 'Raqueta', 'category', false, false, 'CIE-11'),
('XE1HX', 'Picahielo', 'category', false, false, 'CIE-11'),
('XE0AQ', 'Equipamiento o estructura para practicar deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE2EM', 'Red para deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE9R3', 'Poste de rugby, poste de red, poste de meta (arco)', 'category', false, false, 'CIE-11'),
('XE6HE', 'Trampolín para practicar deportes o ejercicios', 'category', false, false, 'CIE-11'),
('XE8C0', 'Equipamiento de gimnasia', 'category', false, false, 'CIE-11'),
('XE76Q', 'Colchoneta de deportes para jugar deportes o ejercicio,', 'category', false, false, 'CIE-11'),
('XE9TW', 'Tabla de buceo, plataforma', 'category', false, false, 'CIE-11'),
('XE1EH', 'Ejercicio, equipamiento de fitness - móvil', 'category', false, false, 'CIE-11'),
('XE6G9', 'Aparatos de gimnasia, ejercicios - fijos (portátiles)', 'category', false, false, 'CIE-11'),
('XE70Q', 'Equipamiento con ruedas o diseñados para movimiento, principalmente para uso en deportes o actividad recreativa', 'category', false, false, 'CIE-11'),
('XE38Q', 'Patines de ruedas, esquís de rodillos, patines en línea, patines de cuchilla', 'category', false, false, 'CIE-11'),
('XE7TJ', 'Monopatín', 'category', false, false, 'CIE-11'),
('XE06X', 'Scooter plegable', 'category', false, false, 'CIE-11'),
('XE9XZ', 'Esquí acuático', 'category', false, false, 'CIE-11'),
('XE5W5', 'Esquí de nieve', 'category', false, false, 'CIE-11'),
('XE6DZ', 'Tabla de nieve', 'category', false, false, 'CIE-11'),
('XE2AY', 'Patín de hielo', 'category', false, false, 'CIE-11'),
('XE0AR', 'Deslizador, tobogán, trineo, disco de nieve, gomón de nieve', 'category', false, false, 'CIE-11'),
('XE9TA', 'Equipo de submarinismo', 'category', false, false, 'CIE-11'),
('XE1WX', 'Escafandra autónoma', 'category', false, false, 'CIE-11'),
('XE85D', 'Cinturón de buceo, pesa', 'category', false, false, 'CIE-11'),
('XE8X8', 'Traje de neopreno', 'category', false, false, 'CIE-11'),
('XE3NW', 'Gafas o máscara, ala o aleta, tubo respirador', 'category', false, false, 'CIE-11'),
('XE8FX', 'Ciertos equipamiento especificado para deportes o actividad recreacional', 'category', false, false, 'CIE-11'),
('XE92X', 'Equipo de protección personal (EPP) diseñado para el uso en deportes', 'category', false, false, 'CIE-11'),
('XE0P3', 'Herramienta, máquina, aparatos usados principalmente para trabajos relacionados con la actividad', 'category', false, false, 'CIE-11'),
('XE6TZ', 'Maquinaria o planta fija', 'category', false, false, 'CIE-11'),
('XE43P', 'Maquina cortadora o rebanadora o planta fija', 'category', false, false, 'CIE-11'),
('XE0VT', 'Máquinaria trituradora o de prensado o planta fija', 'category', false, false, 'CIE-11'),
('XE1WC', 'Maquinaria de calefacción o cocción o planta fija', 'category', false, false, 'CIE-11'),
('XE76C', 'Planta fija o maquinaria de refrigeración', 'category', false, false, 'CIE-11'),
('XE14G', 'Maquinaria de elevación', 'category', false, false, 'CIE-11'),
('XE77A', 'Maquinaria para izar', 'category', false, false, 'CIE-11'),
('XE3BT', 'Maquinaria grúa o planta fija', 'category', false, false, 'CIE-11'),
('XE9U1', 'Plataforma de trabajo elevada', 'category', false, false, 'CIE-11'),
('XE6T6', 'Transportadoras', 'category', false, false, 'CIE-11'),
('XE99N', 'Redes-gas, agua, alcantarillado, vapor, agua caliente,|electricidad', 'category', false, false, 'CIE-11'),
('XE8FD', 'Planta de cizallamiento', 'category', false, false, 'CIE-11'),
('XE6VH', 'Lechería o planta de ordeño', 'category', false, false, 'CIE-11'),
('XE6AF', 'Prensa', 'category', false, false, 'CIE-11'),
('XE0JX', 'Compactador de basura', 'category', false, false, 'CIE-11'),
('XE02Q', 'Máquina trilladora', 'category', false, false, 'CIE-11'),
('XE8KN', 'Cortadora de bagazo, cortadora de forraje', 'category', false, false, 'CIE-11'),
('XE5WX', 'Equipamiento o herramienta manual motorizada', 'category', false, false, 'CIE-11'),
('XE88U', 'Taladro', 'category', false, false, 'CIE-11'),
('XE8MJ', 'Motosierra', 'category', false, false, 'CIE-11'),
('XE66P', 'Otra sierra eléctrica', 'category', false, false, 'CIE-11'),
('XE0TD', 'Soldador, equipo de soldadura', 'category', false, false, 'CIE-11'),
('XE3E3', 'Pistola de clavos, remachador', 'category', false, false, 'CIE-11'),
('XE3UP', 'Amoladora, amortiguador, pulidor, lijadora', 'category', false, false, 'CIE-11'),
('XE8T6', 'Herramienta de jardín motorizada', 'category', false, false, 'CIE-11'),
('XE89A', 'Cortacésped con empuje motorizado', 'category', false, false, 'CIE-11'),
('XE0N1', 'Aspiradora industrial', 'category', false, false, 'CIE-11'),
('XE16F', 'Equipamiento o herramienta manual sin motor', 'category', false, false, 'CIE-11'),
('XE8P1', 'Cortadora de césped de empuje sin motor', 'category', false, false, 'CIE-11'),
('XE0VV', 'Martillo, maza', 'category', false, false, 'CIE-11'),
('XE56E', 'Herramienta de corte', 'category', false, false, 'CIE-11'),
('XE9CU', 'Herramientas de corte', 'category', false, false, 'CIE-11'),
('XE9GT', 'Herramienta para labrar o excavar', 'category', false, false, 'CIE-11'),
('XE3KL', 'Herramienta de elevación', 'category', false, false, 'CIE-11'),
('XE7VR', 'Clavo, tornillo, tachuela', 'category', false, false, 'CIE-11'),
('XE3W7', 'Anzuelo utilizado para actividades relacionadas con el trabajo', 'category', false, false, 'CIE-11'),
('XE8KL', 'Trampa de rata o ratón utilizada para actividades relacionadas con el trabajo', 'category', false, false, 'CIE-11'),
('XE9N7', 'Equipo basado en la presión', 'category', false, false, 'CIE-11'),
('XE5VQ', 'Cilindro de gas', 'category', false, false, 'CIE-11'),
('XE974', 'Manguera presurizada, tubería', 'category', false, false, 'CIE-11'),
('XE3RZ', 'Cierto equipamiento sin motor', 'category', false, false, 'CIE-11'),
('XE9P7', 'Escalera, paso movible', 'category', false, false, 'CIE-11'),
('XE7RK', 'Andamio', 'category', false, false, 'CIE-11'),
('XE5F6', 'Casco', 'category', false, false, 'CIE-11'),
('XE67K', 'Tapones para los aídos', 'category', false, false, 'CIE-11'),
('XE2PS', 'Máscara de soldadura', 'category', false, false, 'CIE-11'),
('XE7RJ', 'Equipo de protección personal, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XE7HB', 'Extintor de incendios', 'category', false, false, 'CIE-11'),
('XE505', 'Dispositivo de transmisión mecánica de potencia', 'category', false, false, 'CIE-11'),
('XE4BU', 'Objeto punzante', 'category', false, false, 'CIE-11'),
('XE3KV', 'Lanza, jabalina diseñada como arma', 'category', false, false, 'CIE-11'),
('XE9PM', 'Flecha o perno diseñado como arma', 'category', false, false, 'CIE-11'),
('XE174', 'Cuchillo diseñado como arma', 'category', false, false, 'CIE-11'),
('XE598', 'Espada, daga, bayoneta, machete, panga, cutlass', 'category', false, false, 'CIE-11'),
('XE04A', 'Arma de fuego o elemento relacionado', 'category', false, false, 'CIE-11'),
('XE4KC', 'Bala, perdigón', 'category', false, false, 'CIE-11'),
('XE72J', 'Pistola', 'category', false, false, 'CIE-11'),
('XE0Q9', 'Rifle', 'category', false, false, 'CIE-11'),
('XE32H', 'Escopeta', 'category', false, false, 'CIE-11'),
('XE6YZ', 'Pistola de aire', 'category', false, false, 'CIE-11'),
('XE1XM', 'Cierta arma especificada', 'category', false, false, 'CIE-11'),
('XE61H', 'Mazo, garrote, barra, mazo africano', 'category', false, false, 'CIE-11'),
('XE9F9', 'Productos eléctricos, pistola paralizante', 'category', false, false, 'CIE-11'),
('XE203', 'Aerosol de capsicum, mazo, aerosol de pimienta', 'category', false, false, 'CIE-11'),
('XE3C1', 'Planta', 'category', false, false, 'CIE-11'),
('XE9CV', 'Arbol, planta', 'category', false, false, 'CIE-11'),
('XE2ZX', 'Hojas, flores', 'category', false, false, 'CIE-11'),
('XE4DN', 'Setas, setas venenosas, hongos', 'category', false, false, 'CIE-11'),
('XE8XA', 'Semilla de planta', 'category', false, false, 'CIE-11'),
('XE4KB', 'Fruta de la planta', 'category', false, false, 'CIE-11'),
('XE8SV', 'Planta espinosa', 'category', false, false, 'CIE-11'),
('XE50M', 'Rama o palo separado de la rama o árbol', 'category', false, false, 'CIE-11'),
('XE2PR', 'Planta venenosa o tóxica no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE6L5', 'Ave', 'category', false, false, 'CIE-11'),
('XE99A', 'Avestruz, emú', 'category', false, false, 'CIE-11'),
('XE69N', 'Loro, perico, cacatúa', 'category', false, false, 'CIE-11'),
('XE1Q3', 'Cuervo, grajo, urraca', 'category', false, false, 'CIE-11'),
('XE6UV', 'Insecto, invertebrado', 'category', false, false, 'CIE-11'),
('XE4D9', 'Abeja', 'category', false, false, 'CIE-11'),
('XE6LT', 'Avispa', 'category', false, false, 'CIE-11'),
('XE322', 'Avispón', 'category', false, false, 'CIE-11'),
('XE7WQ', 'Avispón amarillo', 'category', false, false, 'CIE-11'),
('XE7TV', 'Avispón cara blanca', 'category', false, false, 'CIE-11'),
('XE4YS', 'Hormiga', 'category', false, false, 'CIE-11'),
('XE75L', 'Araña', 'category', false, false, 'CIE-11'),
('XE2EP', 'Escorpión', 'category', false, false, 'CIE-11'),
('XE779', 'garrapata', 'category', false, false, 'CIE-11'),
('XE11M', 'Cienpies, milpies', 'category', false, false, 'CIE-11'),
('XM6QA5', 'Cochinilla', 'category', false, false, 'CIE-11'),
('XE813', 'Mamífero terrestre', 'category', false, false, 'CIE-11'),
('XE33Q', 'Perro', 'category', false, false, 'CIE-11'),
('XE0W5', 'Caspa de perro', 'category', false, false, 'CIE-11'),
('XE3GM', 'Epitelio del perro', 'category', false, false, 'CIE-11'),
('XE4V0', 'Gato', 'category', false, false, 'CIE-11'),
('XE896', 'Caspa de gato', 'category', false, false, 'CIE-11'),
('XE8X3', 'Rata, conejillo de indias, ratón', 'category', false, false, 'CIE-11'),
('XE3UD', 'Cerdo, jabalí', 'category', false, false, 'CIE-11'),
('XE25P', 'Oveja, cabra', 'category', false, false, 'CIE-11'),
('XE257', 'Vaca, toro, animales bovinos', 'category', false, false, 'CIE-11'),
('XE1LR', 'Carne de res', 'category', false, false, 'CIE-11'),
('XE5NG', 'Caspa de vaca', 'category', false, false, 'CIE-11'),
('XE5VC', 'Caballo, poni, burro, mula,asno', 'category', false, false, 'CIE-11'),
('XE7NS', 'Babuino, mono, chimpancé, gorila', 'category', false, false, 'CIE-11'),
('XE4TZ', 'Marsupiales', 'category', false, false, 'CIE-11'),
('XE1MH', 'Ciervo, alce, antílope, cebra, ñu', 'category', false, false, 'CIE-11'),
('XE37L', 'Hipopótamo', 'category', false, false, 'CIE-11'),
('XE82S', 'León, pantera, puma, león de montaña, tigre', 'category', false, false, 'CIE-11'),
('XE7UA', 'Oso, oso pardo, oso polar', 'category', false, false, 'CIE-11'),
('XE2Q6', 'Elefante', 'category', false, false, 'CIE-11'),
('XE96F', 'Búfalo, , bisonte, búfalo Africano', 'category', false, false, 'CIE-11'),
('XE08V', 'Epitelio de hámster', 'category', false, false, 'CIE-11'),
('XE09T', 'Caspa de caballo', 'category', false, false, 'CIE-11'),
('XE7CQ', 'Epitelio de raton', 'category', false, false, 'CIE-11'),
('XE43Q', 'Proteínas de orina de ratón', 'category', false, false, 'CIE-11'),
('XE7TQ', 'Epitelio de conejo', 'category', false, false, 'CIE-11'),
('XE9BL', 'Cerdo', 'category', false, false, 'CIE-11'),
('XE6T4', 'Mejillón azul', 'category', false, false, 'CIE-11'),
('XE6WA', 'Callo de hacha', 'category', false, false, 'CIE-11'),
('XE5ZB', 'Epitelio de cobaya', 'category', false, false, 'CIE-11'),
('XE2AH', 'Animal marino', 'category', false, false, 'CIE-11'),
('XE765', 'Tiburón', 'category', false, false, 'CIE-11'),
('XE71F', 'Otros peces', 'category', false, false, 'CIE-11'),
('XE48L', 'Serpiente de mar', 'category', false, false, 'CIE-11'),
('XE3UQ', 'Mamífero marino', 'category', false, false, 'CIE-11'),
('XE8BW', 'Medusa', 'category', false, false, 'CIE-11'),
('XE40R', 'Nematocistos', 'category', false, false, 'CIE-11'),
('XE75E', 'Coral', 'category', false, false, 'CIE-11'),
('XE6ZA', 'Erizo de mar', 'category', false, false, 'CIE-11'),
('XE45C', 'Anemona de mar', 'category', false, false, 'CIE-11'),
('XE43L', 'Pepino de mar', 'category', false, false, 'CIE-11'),
('XE1PT', 'Reptil o anfibio', 'category', false, false, 'CIE-11'),
('XE44L', 'Víbora no venenosa', 'category', false, false, 'CIE-11'),
('XE9H6', 'Serpiente venenosa', 'category', false, false, 'CIE-11'),
('XE9X2', 'Cobra', 'category', false, false, 'CIE-11'),
('XE5N3', 'Serpiente de terciopelo', 'category', false, false, 'CIE-11'),
('XE2RM', 'Serpiente de cascabel', 'category', false, false, 'CIE-11'),
('XE8LD', 'Víbora', 'category', false, false, 'CIE-11'),
('XE2UZ', 'Bungaro', 'category', false, false, 'CIE-11'),
('XE11V', 'Serpiente no especificada si es venenosa o no', 'category', false, false, 'CIE-11'),
('XE6A7', 'Lagarto, geco, iguana', 'category', false, false, 'CIE-11'),
('XE65X', 'Monstruo de Gila', 'category', false, false, 'CIE-11'),
('XE4YK', 'Sapo, rana', 'category', false, false, 'CIE-11'),
('XE4FD', 'Cocodrilo, caimán', 'category', false, false, 'CIE-11'),
('XE653', 'Persona', 'category', false, false, 'CIE-11'),
('XE70B', 'Persona, sí mismo', 'category', false, false, 'CIE-11'),
('XE0TZ', 'Multitud de personas', 'category', false, false, 'CIE-11'),
('XE1P6', 'Edificio adecuado', 'category', false, false, 'CIE-11'),
('XE766', 'Inodoro', 'category', false, false, 'CIE-11'),
('XE429', 'Letrina de pozo', 'category', false, false, 'CIE-11'),
('XE2C6', 'Bañera, bañera de hidromasaje, cubículo de ducha', 'category', false, false, 'CIE-11'),
('XE78X', 'Bañera', 'category', false, false, 'CIE-11'),
('XE5T1', 'Bañera de hidromasaje', 'category', false, false, 'CIE-11'),
('XE5RW', 'Cabina con regadera', 'category', false, false, 'CIE-11'),
('XE31Q', 'Ducha', 'category', false, false, 'CIE-11'),
('XE8P0', 'Mostrador empotrado, encimera, encimera de cocina', 'category', false, false, 'CIE-11'),
('XE2AC', 'Puerta, ventana, característica o propósito relacionado', 'category', false, false, 'CIE-11'),
('XE68A', 'Puerta, alfeizar de la puerta', 'category', false, false, 'CIE-11'),
('XE4YT', 'Puerta de vidrio', 'category', false, false, 'CIE-11'),
('XE4NX', 'Puerta o salida de seguridad, puerta de escape', 'category', false, false, 'CIE-11'),
('XE6FE', 'Barras en las ventanas', 'category', false, false, 'CIE-11'),
('XE4BD', 'Ventana', 'category', false, false, 'CIE-11'),
('XE5B1', 'Contraventanas (postigos) exteriores', 'category', false, false, 'CIE-11'),
('XE7SG', 'Piso o accesorio o característica relacionada', 'category', false, false, 'CIE-11'),
('XE0SK', 'Piso - alfombrado', 'category', false, false, 'CIE-11'),
('XE19Z', 'Piso - azulejo, ladrillo, hormigón', 'category', false, false, 'CIE-11'),
('XE6M6', 'Piso - de madera', 'category', false, false, 'CIE-11'),
('XE6ZE', 'Piso - adobe, arcilla, estiércol de animal', 'category', false, false, 'CIE-11'),
('XE4ZE', 'Pared o accesorio o característica relacionada', 'category', false, false, 'CIE-11'),
('XE19W', 'Chimenea', 'category', false, false, 'CIE-11'),
('XE1B2', 'Parrilla incorporada', 'category', false, false, 'CIE-11'),
('XE0WS', 'Pared - ladrillo, hormigón, azulejo', 'category', false, false, 'CIE-11'),
('XE7CH', 'Pared - madera', 'category', false, false, 'CIE-11'),
('XE3GJ', 'Wall - mud, clay, animal dung', 'category', false, false, 'CIE-11'),
('XE3PF', 'Cierto edificio específico, componente de construcción o accesorio', 'category', false, false, 'CIE-11'),
('XE39L', 'Piscina en terreno', 'category', false, false, 'CIE-11'),
('XE4PB', 'Piscina sobre el suelo, spa externo o bañera de hidromasaje', 'category', false, false, 'CIE-11'),
('XE5PL', 'Piscina sobre el suelo', 'category', false, false, 'CIE-11'),
('XE3PX', 'spa externo', 'category', false, false, 'CIE-11'),
('XE8AX', 'Jacuzzi externo', 'category', false, false, 'CIE-11'),
('XE7FP', 'Puerta de la cerca', 'category', false, false, 'CIE-11'),
('XE3BP', 'Cerca', 'category', false, false, 'CIE-11'),
('XE3GT', 'Puerta', 'category', false, false, 'CIE-11'),
('XE9QW', 'Rampa móvil, escalera mecánica', 'category', false, false, 'CIE-11'),
('XE0KF', 'Rampa móvil', 'category', false, false, 'CIE-11'),
('XE73T', 'Escalera mecánica', 'category', false, false, 'CIE-11'),
('XE8PC', 'Ascensor, elevador', 'category', false, false, 'CIE-11'),
('XE3HC', 'Escaleras, escalones', 'category', false, false, 'CIE-11'),
('XE2VG', 'Pasamano, baranda, barandilla', 'category', false, false, 'CIE-11'),
('XE6T1', 'Línea de transmisión eléctrica dentro o alrededor del edificio', 'category', false, false, 'CIE-11'),
('XE7UU', 'Accesorios o tuberías para gas, vapor o agua caliente', 'category', false, false, 'CIE-11'),
('XE171', 'Racores o tuberías para gas', 'category', false, false, 'CIE-11'),
('XE2BH', 'Racores o tuberías para vapor', 'category', false, false, 'CIE-11'),
('XE48P', 'Racores o tuberías para agua caliente', 'category', false, false, 'CIE-11'),
('XE871', 'Accesorio eléctrico', 'category', false, false, 'CIE-11'),
('XE9HH', 'Unidad de aire acondicionado con conductos o accesorios relacionados', 'category', false, false, 'CIE-11'),
('XE58F', 'Superficie del terreno', 'category', false, false, 'CIE-11'),
('XE1AK', 'Acantilado', 'category', false, false, 'CIE-11'),
('XE94G', 'Pendiente, rampa', 'category', false, false, 'CIE-11'),
('XE3EC', 'Trinchera, zanja, foso', 'category', false, false, 'CIE-11'),
('XE5Y0', 'alcantarilla', 'category', false, false, 'CIE-11'),
('XE2G4', 'Desagüe abierto, canal', 'category', false, false, 'CIE-11'),
('XE7K9', 'Masa de agua', 'category', false, false, 'CIE-11'),
('XE9TJ', 'Masa de agua, bien hecha por el hombre, bien cavado para aguas subterráneas', 'category', false, false, 'CIE-11'),
('XE40U', 'Masa de agua, reservorio de agua', 'category', false, false, 'CIE-11'),
('XE64D', 'Masa de agua, charco', 'category', false, false, 'CIE-11'),
('XE285', 'Masa de agua, represa, lago', 'category', false, false, 'CIE-11'),
('XE1CZ', 'Masa de agua, río , arroyo', 'category', false, false, 'CIE-11'),
('XE57J', 'Masa de agua, pantano, ciénaga, estuario', 'category', false, false, 'CIE-11'),
('XE636', 'Masa de agua, playa, costa', 'category', false, false, 'CIE-11'),
('XE5N4', 'Masa de agua, mar abierto', 'category', false, false, 'CIE-11'),
('XE0CX', 'Masa de agua, agua de inundación', 'category', false, false, 'CIE-11'),
('XE2QX', 'Masa de agua, canal, o canal de irrigación', 'category', false, false, 'CIE-11'),
('XE7CY', 'Cierta conformación de superficie especificada', 'category', false, false, 'CIE-11'),
('XE45P', 'Superficie inclinada, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE9CC', 'Superficie uniforme, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE1DA', 'Superficie irregular, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XE4BY', 'Material natural', 'category', false, false, 'CIE-11'),
('XE3LV', 'Nieve, hielo,', 'category', false, false, 'CIE-11'),
('XE233', 'Hierba natural', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;