BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XA4C02', 'Córnea', 'category', false, false, 'CIE-11'),
('XA1DA5', 'Limbo de la córnea', 'category', false, false, 'CIE-11'),
('XA4MT3', 'Uvea', 'category', false, false, 'CIE-11'),
('XA03X9', 'Cuerpo ciliar', 'category', false, false, 'CIE-11'),
('XA9SH1', 'Músculo ciliar', 'category', false, false, 'CIE-11'),
('XA1S43', 'Procesos ciliares', 'category', false, false, 'CIE-11'),
('XA96A7', 'Coroides', 'category', false, false, 'CIE-11'),
('XA3GW7', 'Iris', 'category', false, false, 'CIE-11'),
('XA0B15', 'Pupila', 'category', false, false, 'CIE-11'),
('XA0571', 'Membrana pupilar', 'category', false, false, 'CIE-11'),
('XA13U9', 'Lente cristalino', 'category', false, false, 'CIE-11'),
('XA6U53', 'Ligamento suspensorio del cristalino', 'category', false, false, 'CIE-11'),
('XA8WV8', 'Retina', 'category', false, false, 'CIE-11'),
('XA9V06', 'Mácula lútea', 'category', false, false, 'CIE-11'),
('XA2U02', 'Fovea', 'category', false, false, 'CIE-11'),
('XA4A75', 'Disco óptico', 'category', false, false, 'CIE-11'),
('XA4YS8', 'Retina periférica', 'category', false, false, 'CIE-11'),
('XA0BB2', 'Cámara del ojo', 'category', false, false, 'CIE-11'),
('XA0N58', 'Cámara posterior del ojo', 'category', false, false, 'CIE-11'),
('XA4HU2', 'Humor vítreo', 'category', false, false, 'CIE-11'),
('XA4MZ4', 'Cámara anterior del ojo', 'category', false, false, 'CIE-11'),
('XA3518', 'Humor acuoso', 'category', false, false, 'CIE-11'),
('XA1TF9', 'Líquido ocular', 'category', false, false, 'CIE-11'),
('XA0096', 'Aparato lagrimal', 'category', false, false, 'CIE-11'),
('XA75Y9', 'Glándula lagrimal', 'category', false, false, 'CIE-11'),
('XA2PA4', 'Conductos de la glándula lagrimal', 'category', false, false, 'CIE-11'),
('XA9D80', 'Glándula de Meibomio', 'category', false, false, 'CIE-11'),
('XA8EM9', 'Puntos lagrimales', 'category', false, false, 'CIE-11'),
('XA2VR4', 'Punto lagrimal superior', 'category', false, false, 'CIE-11'),
('XA99D0', 'Punto lagrimal inferior', 'category', false, false, 'CIE-11'),
('XA6C35', 'Canalículo lagrimal', 'category', false, false, 'CIE-11'),
('XA5SW9', 'Conducto nasolacrimal', 'category', false, false, 'CIE-11'),
('XA2WJ9', 'Órbita', 'category', false, false, 'CIE-11'),
('XA9WT4', 'Tejido conectivo y otros tejidos blandos de la órbita', 'category', false, false, 'CIE-11'),
('XA8GT2', 'Vena nasofrontal', 'category', false, false, 'CIE-11'),
('XA7LQ0', 'Vena supraorbitaria', 'category', false, false, 'CIE-11'),
('XA01U5', 'Oído', 'category', false, false, 'CIE-11'),
('XA57R3', 'Oído interno', 'category', false, false, 'CIE-11'),
('XA3MS6', 'Canales semicirculares', 'category', false, false, 'CIE-11'),
('XA0JV0', 'Coclea', 'category', false, false, 'CIE-11'),
('XA6ZY7', 'Conducto auditivo interno', 'category', false, false, 'CIE-11'),
('XA0L54', 'Laberinto', 'category', false, false, 'CIE-11'),
('XA44P4', 'Vestíbulo auditivo', 'category', false, false, 'CIE-11'),
('XA0G74', 'Oído medio', 'category', false, false, 'CIE-11'),
('XA7XY6', 'Trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('XA16S6', 'Ventana oval', 'category', false, false, 'CIE-11'),
('XA9RH9', 'Antro mastoideo', 'category', false, false, 'CIE-11'),
('XA3KB2', 'Cavidad timpánica', 'category', false, false, 'CIE-11'),
('XA3UT7', 'Tejido conectivo y otros tejidos blandos del oído medio', 'category', false, false, 'CIE-11'),
('XA08X4', 'Membrana timpánica', 'category', false, false, 'CIE-11'),
('XA6ZY6', 'Oído externo', 'category', false, false, 'CIE-11'),
('XA4E71', 'Pabellón de la oreja', 'category', false, false, 'CIE-11'),
('XA6B58', 'Hélix del pabellón auricular', 'category', false, false, 'CIE-11'),
('XA9A86', 'Raíz del hélix', 'category', false, false, 'CIE-11'),
('XA9M10', 'Vértice del hélix', 'category', false, false, 'CIE-11'),
('XA7AB8', 'Espina del hélix', 'category', false, false, 'CIE-11'),
('XA1BZ8', 'Cola del hélix', 'category', false, false, 'CIE-11'),
('XA7V14', 'Antehélix', 'category', false, false, 'CIE-11'),
('XA96Q7', 'Pilares del antehélix', 'category', false, false, 'CIE-11'),
('XA5LW2', 'Fosa escafoidea del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('XA8W55', 'Concha de pinna', 'category', false, false, 'CIE-11'),
('XA5KM5', 'Cimba de la concha', 'category', false, false, 'CIE-11'),
('XA8D58', 'Cuenca conchal de la oreja', 'category', false, false, 'CIE-11'),
('XA3RC6', 'Fosa triangular de la oreja', 'category', false, false, 'CIE-11'),
('XA2N71', 'Trago del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('XA5VK5', 'Escotadura intertrágica del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('XA0TW7', 'Lóbulo de la oreja', 'category', false, false, 'CIE-11'),
('XA7RR9', 'Antitrago del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('XA3S47', 'Superficie posterior del pabellón auricular', 'category', false, false, 'CIE-11'),
('XA6NU1', 'Fosa antihelical', 'category', false, false, 'CIE-11'),
('XA6KW8', 'Eminencia de la concha', 'category', false, false, 'CIE-11'),
('XA0H47', 'Eminencia de la escafa', 'category', false, false, 'CIE-11'),
('XA8VK6', 'Eminencia de la fosa triangular', 'category', false, false, 'CIE-11'),
('XA4DV9', 'Surco retroauricular', 'category', false, false, 'CIE-11'),
('XA3UC1', 'Conducto auditivo externo', 'category', false, false, 'CIE-11'),
('XA5GS5', 'Meato auditivo externo', 'category', false, false, 'CIE-11'),
('XA5K66', 'Glándula cerosa', 'category', false, false, 'CIE-11'),
('XA9E26', 'Piel de la oreja', 'category', false, false, 'CIE-11'),
('XA4PM9', 'Sistema cardiovascular', 'category', false, false, 'CIE-11'),
('XA5999', 'Arterias', 'category', false, false, 'CIE-11'),
('XA4TS7', 'Arteria de la cabeza, la cara y el cuello', 'category', false, false, 'CIE-11'),
('XA2B10', 'Arteria comunicante anterior', 'category', false, false, 'CIE-11'),
('XA2QF4', 'Arteria etmoidal anterior', 'category', false, false, 'CIE-11'),
('XA53D3', 'Ramas nasales de la arteria etmoidal anterior', 'category', false, false, 'CIE-11'),
('XA00K1', 'Arteria meníngea anterior', 'category', false, false, 'CIE-11'),
('XA1GU9', 'Arteria alveolar superior anterior', 'category', false, false, 'CIE-11'),
('XA2505', 'Arteria del canal de pterigoideo', 'category', false, false, 'CIE-11'),
('XA9AD7', 'Arteria carótida', 'category', false, false, 'CIE-11'),
('XA0F61', 'Cuerpo carotídeo', 'category', false, false, 'CIE-11'),
('XA1V84', 'Arteria carótida común', 'category', false, false, 'CIE-11'),
('XA78C0', 'Arteria carótida interna', 'category', false, false, 'CIE-11'),
('XA1CW5', 'Arteria oftálmica', 'category', false, false, 'CIE-11'),
('XA9EK2', 'Arteria carótida externa', 'category', false, false, 'CIE-11'),
('XA5SN3', 'Arteria cerebelosa', 'category', false, false, 'CIE-11'),
('XA13S2', 'Arteria cerebral', 'category', false, false, 'CIE-11'),
('XA1VB0', 'Arteria cerebral anterior', 'category', false, false, 'CIE-11'),
('XA2K99', 'Arteria basilar', 'category', false, false, 'CIE-11'),
('XA3185', 'Ramas pontinas de la arteria basilar', 'category', false, false, 'CIE-11'),
('XA2JH8', 'Arteria cerebral media', 'category', false, false, 'CIE-11'),
('XA4WT4', 'Arteria central anterolateral', 'category', false, false, 'CIE-11'),
('XA7C50', 'Arteria cerebral posterior', 'category', false, false, 'CIE-11'),
('XA2UK9', 'Tronco costocervical', 'category', false, false, 'CIE-11'),
('XA7SK1', 'Arteria auricular profunda', 'category', false, false, 'CIE-11'),
('XA1NY7', 'Arteria cervical profunda', 'category', false, false, 'CIE-11'),
('XA18D8', 'Arteria nasal dorsal', 'category', false, false, 'CIE-11'),
('XA56R8', 'Arteria nasal dorsal que irriga la raíz de la nariz', 'category', false, false, 'CIE-11'),
('XA0PF0', 'Arteria nasal dorsal que irriga el dorso de la nariz', 'category', false, false, 'CIE-11'),
('XA4QF0', 'Arteria estriada externa de la arteria central anterolateral', 'category', false, false, 'CIE-11'),
('XA3FL3', 'Arteria facial', 'category', false, false, 'CIE-11'),
('XA7YP8', 'Arteria palatina ascendente', 'category', false, false, 'CIE-11'),
('XA4UT8', 'Arteria labial superior', 'category', false, false, 'CIE-11'),
('XA2ZM0', 'Arteria labial inferior', 'category', false, false, 'CIE-11'),
('XA36S6', 'Arteria angular', 'category', false, false, 'CIE-11'),
('XA9QG7', 'Arteria cervical', 'category', false, false, 'CIE-11'),
('XA85T4', 'Rama profunda de la arteria submentoniana', 'category', false, false, 'CIE-11'),
('XA83M8', 'Ramas glandulares de la arteria cervical', 'category', false, false, 'CIE-11'),
('XA2626', 'Arteria palatina mayor', 'category', false, false, 'CIE-11'),
('XA4H29', 'Arteria hioidea', 'category', false, false, 'CIE-11'),
('XA4VH9', 'Arteria del arco palpebral inferior', 'category', false, false, 'CIE-11'),
('XA5VX8', 'Arteria estriada interna de la arteria central anterolateral', 'category', false, false, 'CIE-11'),
('XA85W7', 'Arteria intracraneal', 'category', false, false, 'CIE-11'),
('XA16L7', 'Rama lateral de la arteria cerebelosa inferior posterior', 'category', false, false, 'CIE-11'),
('XA3N26', 'Arteria facial de la rama nasal lateral', 'category', false, false, 'CIE-11'),
('XA5Z38', 'Arteria palatina menor', 'category', false, false, 'CIE-11'),
('XA5TR9', 'Rama lingual de la arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA18M5', 'Arteria maxilar', 'category', false, false, 'CIE-11'),
('XA49F5', 'Primera porción de la arteria maxilar', 'category', false, false, 'CIE-11'),
('XA0BD0', 'Arteria temporal profunda (anterior y posterior)', 'category', false, false, 'CIE-11'),
('XA7SV5', 'Arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA3W87', 'Rama incisiva de la arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA7AG7', 'Rama mentoniana de la arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA49F4', 'Arteria masetérica', 'category', false, false, 'CIE-11'),
('XA55G2', 'Arteria palatina descendente', 'category', false, false, 'CIE-11'),
('XA9XM3', 'Arteria faríngea', 'category', false, false, 'CIE-11'),
('XA3WA5', 'Arteria alveolar superior posterior', 'category', false, false, 'CIE-11'),
('XA0LK0', 'Arteria bucal', 'category', false, false, 'CIE-11'),
('XA9MM1', 'Arteria timpánica anterior', 'category', false, false, 'CIE-11'),
('XA8YX3', 'Arteria meníngea accesoria', 'category', false, false, 'CIE-11'),
('XA5RM1', 'Arteria meningea media', 'category', false, false, 'CIE-11'),
('XA2WS5', 'Arteria lingual', 'category', false, false, 'CIE-11'),
('XA9EU7', 'Arteria occipital', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XA13U3', 'Arteria auricular posterior', 'category', false, false, 'CIE-11'),
('XA0SB1', 'Arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7WG0', 'Rama frontal de la arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7K29', 'Arteria tiroidea superior', 'category', false, false, 'CIE-11'),
('XA0FT7', 'Arteria cricotiroidea', 'category', false, false, 'CIE-11'),
('XA2V10', 'Arteria tiroidea inferior', 'category', false, false, 'CIE-11'),
('XA77C5', 'Arteria esternocleidomastoidea', 'category', false, false, 'CIE-11'),
('XA00E5', 'Arteria faríngea ascendente', 'category', false, false, 'CIE-11'),
('XA53A8', 'Arteria carótida común derecha', 'category', false, false, 'CIE-11'),
('XA6X36', 'Arteria temporal media', 'category', false, false, 'CIE-11'),
('XA3TE9', 'Arteria milohioidea de la arteria alveolar inferior', 'category', false, false, 'CIE-11'),
('XA6XV2', 'Rama parietal de la arteria temporal superficial', 'category', false, false, 'CIE-11'),
('XA7U73', 'Arteria comunicante posterior', 'category', false, false, 'CIE-11'),
('XA5881', 'Arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA7561', 'Ramas nasales de la arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA7945', 'Rama meningeas de la arteria etmoidal posterior', 'category', false, false, 'CIE-11'),
('XA8RM9', 'Arteria cerebelosa inferior posterior', 'category', false, false, 'CIE-11'),
('XA9VV0', 'Ramas nasales laterales posteriores de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA8FA1', 'Arteria meningea posterior', 'category', false, false, 'CIE-11'),
('XA4Q78', 'Ramas septales posteriores de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA1K74', 'Ramas pterigoideas', 'category', false, false, 'CIE-11'),
('XA1BZ0', 'Rama terminal de la arteria esfenopalatina', 'category', false, false, 'CIE-11'),
('XA90T0', 'Arteria submentoniana de la arteria cervical', 'category', false, false, 'CIE-11'),
('XA6FR0', 'Rama superficial de la arteria submentoniana', 'category', false, false, 'CIE-11'),
('XA0898', 'Rama superficial de la arteria cervical transversa', 'category', false, false, 'CIE-11'),
('XA82P9', 'Rama petrosa superficial de la arteria meningea posterior y anterior', 'category', false, false, 'CIE-11'),
('XA7423', 'Arteria cerebelosa superior', 'category', false, false, 'CIE-11'),
('XA9GU1', 'Arteria laríngea superior', 'category', false, false, 'CIE-11'),
('XA50Q9', 'Arteria timpánica superior', 'category', false, false, 'CIE-11'),
('XA6W31', 'Arteria supratroclear', 'category', false, false, 'CIE-11'),
('XA65G3', 'Ramas temporales de la arteria meningea anterior y posterior', 'category', false, false, 'CIE-11'),
('XA9XH0', 'Tronco tirocervical', 'category', false, false, 'CIE-11'),
('XA2E78', 'Rama tonsilar de la arteria cervical', 'category', false, false, 'CIE-11'),
('XA6142', 'Arteria cervical transversa', 'category', false, false, 'CIE-11'),
('XA9M59', 'Arteria facial transversa', 'category', false, false, 'CIE-11'),
('XA5D86', 'Rama pequeña a la parte superior del saco lagrimal de la arteria nasal dorsal', 'category', false, false, 'CIE-11'),
('XA1XP6', 'Arteria vertebral', 'category', false, false, 'CIE-11'),
('XA3NW4', 'Ramas meníngeas de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA6TE8', 'Rama ascendente de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA3R20', 'Rama descendente de la arteria vertebral', 'category', false, false, 'CIE-11'),
('XA1C15', 'Arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA6503', 'Rama superficial de la arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA8BL5', 'Rama profunda de la arteria supraorbitaria', 'category', false, false, 'CIE-11'),
('XA34H5', 'Ramas orbitarias de la arteria meníngea anterior y posterior', 'category', false, false, 'CIE-11'),
('XA5C33', 'Arteria infraorbitaria', 'category', false, false, 'CIE-11'),
('XA05E9', 'Ramas orbitarias de la arteria infraorbitaria', 'category', false, false, 'CIE-11'),
('XA9RA2', 'Arteria ciliar posterior larga', 'category', false, false, 'CIE-11'),
('XA04E2', 'Arteria ciliar posterior corta', 'category', false, false, 'CIE-11'),
('XA94Y6', 'Arteria ciliar anterior', 'category', false, false, 'CIE-11'),
('XA5RB0', 'Arteria central de la retina', 'category', false, false, 'CIE-11'),
('XA22D8', 'Círculo arterioso de la arteria mayor', 'category', false, false, 'CIE-11'),
('XA8T70', 'Círculo arterioso de la arteria menor', 'category', false, false, 'CIE-11'),
('XA5P69', 'Arteria lagrimal', 'category', false, false, 'CIE-11'),
('XA00Q9', 'Arteria palpebral lateral', 'category', false, false, 'CIE-11'),
('XA8VA1', 'Arteria palpebral media', 'category', false, false, 'CIE-11'),
('XA35L5', 'Arteria del arco palpebral superior', 'category', false, false, 'CIE-11'),
('XA1Q49', 'Ramas cigomáticas de la arteria lagrimal', 'category', false, false, 'CIE-11'),
('XA4KE1', 'Ramas a la encía', 'category', false, false, 'CIE-11'),
('XA9UT1', 'Arteria del tórax', 'category', false, false, 'CIE-11'),
('XA4TH8', 'Ramas al diafragma de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA1PX4', 'Ramas a la parte inferior del pericardio de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA2KA0', 'Tronco braquiocefálico', 'category', false, false, 'CIE-11'),
('XA3M86', 'Rama profunda de la arteria escapular dorsal', 'category', false, false, 'CIE-11'),
('XA7KK5', 'Arteria intercostal', 'category', false, false, 'CIE-11'),
('XA0T62', 'Ramas intercostales de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA9S49', 'Arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA4XE2', 'Arteria mediastínica', 'category', false, false, 'CIE-11'),
('XA3DE1', 'Arteria torácica lateral', 'category', false, false, 'CIE-11'),
('XA09J9', 'Arteria pulmonar', 'category', false, false, 'CIE-11'),
('XA1EE3', 'Arteria intercostal posterior inferior (de la III a la XI)', 'category', false, false, 'CIE-11'),
('XA0QG6', 'Ramas inferiores de las anastomosis espaciales de las seis ramas intercostales anteriores de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA7EC2', 'Arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA1190', 'Ramas perforantes de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA0WT1', 'Arteria intercostal posterior', 'category', false, false, 'CIE-11'),
('XA14K0', 'Seis ramas intercostales anteriores de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA6UQ6', 'Ramos esternales de la arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA3311', 'Arteria subcostal', 'category', false, false, 'CIE-11'),
('XA9J15', 'Arteria frénica superior', 'category', false, false, 'CIE-11'),
('XA8M67', 'Arteria torácica superior', 'category', false, false, 'CIE-11'),
('XA7TT5', 'Arteria intercostal suprema', 'category', false, false, 'CIE-11'),
('XA79X5', 'Arteria toracoacromial', 'category', false, false, 'CIE-11'),
('XA99C2', 'Ramas anteriores de las seis ramas intercostales anteriores de arteria torácica interna', 'category', false, false, 'CIE-11'),
('XA8ES3', 'Arteria esófagica', 'category', false, false, 'CIE-11'),
('XA8K52', 'Aorta del tórax', 'category', false, false, 'CIE-11'),
('XA75Z8', 'Arco de la aorta', 'category', false, false, 'CIE-11'),
('XA01A6', 'Aorta ascendente', 'category', false, false, 'CIE-11'),
('XA5H34', 'Aorta descendente', 'category', false, false, 'CIE-11'),
('XA6E07', 'Arteria bronquial', 'category', false, false, 'CIE-11'),
('XA5D68', 'Arteria subclavia', 'category', false, false, 'CIE-11'),
('XA9JK8', 'Arteria del abdomen', 'category', false, false, 'CIE-11'),
('XA7TZ1', 'Arteria suprarrenal anterior', 'category', false, false, 'CIE-11'),
('XA82R7', 'Rama ascendente de la arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA8BY2', 'Ramas a los músculos abdominales de la arteria musculofrénica', 'category', false, false, 'CIE-11'),
('XA8577', 'Arteria celíaca', 'category', false, false, 'CIE-11'),
('XA26R6', 'Arteria hepática común', 'category', false, false, 'CIE-11'),
('XA0JE4', 'Arteria cística', 'category', false, false, 'CIE-11'),
('XA6NY6', 'Rama descendente de la arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA1VJ7', 'Vasos rectos descendentes', 'category', false, false, 'CIE-11'),
('XA1QB0', 'Arteria pancreática dorsal', 'category', false, false, 'CIE-11'),
('XA0NN4', 'Arteria gastroduodenal', 'category', false, false, 'CIE-11'),
('XA5AP2', 'Arteria hepática', 'category', false, false, 'CIE-11'),
('XA2LQ8', 'Rama hepática de la arteria gástrica izquierda', 'category', false, false, 'CIE-11'),
('XA2Z43', 'Arteria ileocólica', 'category', false, false, 'CIE-11'),
('XA3F13', 'Arteria epigástrica inferior', 'category', false, false, 'CIE-11'),
('XA2N15', 'Arteria mesentérica inferior', 'category', false, false, 'CIE-11'),
('XA6358', 'Arteria pancreaticoduodenal inferior', 'category', false, false, 'CIE-11'),
('XA2LL9', 'Arteria frénica inferior', 'category', false, false, 'CIE-11'),
('XA68L7', 'Arteria intestinal', 'category', false, false, 'CIE-11'),
('XA6WR7', 'Arteria cólica izquierda', 'category', false, false, 'CIE-11'),
('XA0LL0', 'Arteria gástrica izquierda', 'category', false, false, 'CIE-11'),
('XA9AQ6', 'Arteria gastroepiploica izquierda', 'category', false, false, 'CIE-11'),
('XA4UK9', 'Arteria lumbar', 'category', false, false, 'CIE-11'),
('XA6CA5', 'Arteria mesentérica', 'category', false, false, 'CIE-11'),
('XA1Z62', 'Arteria cólica media', 'category', false, false, 'CIE-11'),
('XA1GQ7', 'Arteria suprarrenal media', 'category', false, false, 'CIE-11'),
('XA00T1', 'Arteria suprarrenal posterior', 'category', false, false, 'CIE-11'),
('XA8C72', 'Arteria hepática propia', 'category', false, false, 'CIE-11'),
('XA69V9', 'Arteria renal', 'category', false, false, 'CIE-11'),
('XA6GC2', 'Arteria cólica derecha', 'category', false, false, 'CIE-11'),
('XA9HE0', 'Arteria gástrica derecha', 'category', false, false, 'CIE-11'),
('XA8V02', 'Arteria gastroepiploica derecha', 'category', false, false, 'CIE-11'),
('XA02A2', 'Arteria sigmoidea', 'category', false, false, 'CIE-11'),
('XA0R02', 'Arteria esplénica', 'category', false, false, 'CIE-11'),
('XA2870', 'Arteria pancreatoduodenal superior', 'category', false, false, 'CIE-11'),
('XA51U4', 'Ramas terminales de la arteria hepática propia', 'category', false, false, 'CIE-11'),
('XA0VZ0', 'Arteria umbilical', 'category', false, false, 'CIE-11'),
('XA3VR0', 'Arteria mesentérica superior', 'category', false, false, 'CIE-11'),
('XA4GP1', 'Arteria de la pelvis', 'category', false, false, 'CIE-11'),
('XA5PV1', 'Arteria del bulbo del pene', 'category', false, false, 'CIE-11'),
('XA30X9', 'Arteria del bulbo del vestíbulo', 'category', false, false, 'CIE-11'),
('XA4XP0', 'Arteria profunda del clítoris', 'category', false, false, 'CIE-11'),
('XA7AM0', 'Arteria profunda del pene', 'category', false, false, 'CIE-11'),
('XA14N2', 'Rama profunda de la arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA4AP3', 'Arteria pudenda externa profunda', 'category', false, false, 'CIE-11'),
('XA27B8', 'Arteria del conducto deferente', 'category', false, false, 'CIE-11'),
('XA4FK8', 'Arteria dorsal del clítoris', 'category', false, false, 'CIE-11'),
('XA4X54', 'Arteria dorsal del pene', 'category', false, false, 'CIE-11'),
('XA5GV0', 'Rama ilíaca de la arteria iliolumbar', 'category', false, false, 'CIE-11'),
('XA7D46', 'Arteria iliolumbar', 'category', false, false, 'CIE-11'),
('XA3XS2', 'Rama inferior de la arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA0G82', 'Arteria glútea inferior', 'category', false, false, 'CIE-11'),
('XA2QX3', 'Arteria vesical inferior', 'category', false, false, 'CIE-11'),
('XA7FK7', 'Arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA5Y50', 'Arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA82V4', 'Arteria sacra mediana', 'category', false, false, 'CIE-11'),
('XA8X93', 'Arteria rectal media', 'category', false, false, 'CIE-11'),
('XA69V8', 'Arteria obturatriz', 'category', false, false, 'CIE-11'),
('XA1MF5', 'Arteria ovárica en las mujeres', 'category', false, false, 'CIE-11'),
('XA5MN1', 'Arteria perineal', 'category', false, false, 'CIE-11'),
('XA34Z7', 'Ramas labiales posteriores de la arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA2025', 'Ramas escrotales posteriores de la arteria pudenda interna', 'category', false, false, 'CIE-11'),
('XA2TT0', 'Rama superficial de la arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA0AZ8', 'Rama superior de la arteria sacra lateral', 'category', false, false, 'CIE-11'),
('XA26E6', 'Arteria glútea superior', 'category', false, false, 'CIE-11'),
('XA1426', 'Arteria vesical superior', 'category', false, false, 'CIE-11'),
('XA0UK9', 'Arteria testicular en varones', 'category', false, false, 'CIE-11'),
('XA85K8', 'Arteria uretral', 'category', false, false, 'CIE-11'),
('XA0610', 'Arteria uterina', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;