BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('SS3H', '', 'category', false, false, 'CIE-11'),
('SS3J', '', 'category', false, false, 'CIE-11'),
('SS3Y', '', 'category', false, false, 'CIE-11'),
('SS3Z', '', 'category', false, false, 'CIE-11'),
('SS4Y', '', 'category', false, false, 'CIE-11'),
('SS4Z', '', 'category', false, false, 'CIE-11'),
('SS50', '', 'category', false, false, 'CIE-11'),
('SS51', '', 'category', false, false, 'CIE-11'),
('SS52', '', 'category', false, false, 'CIE-11'),
('SS53', '', 'category', false, false, 'CIE-11'),
('SS54', '', 'category', false, false, 'CIE-11'),
('SS55', '', 'category', false, false, 'CIE-11'),
('SS56', '', 'category', false, false, 'CIE-11'),
('SS57', '', 'category', false, false, 'CIE-11'),
('SS58', '', 'category', false, false, 'CIE-11'),
('SS59', '', 'category', false, false, 'CIE-11'),
('SS5A', '', 'category', false, false, 'CIE-11'),
('SS5B', '', 'category', false, false, 'CIE-11'),
('SS5C', '', 'category', false, false, 'CIE-11'),
('SS5D', '', 'category', false, false, 'CIE-11'),
('SS5E', '', 'category', false, false, 'CIE-11'),
('SS5F', '', 'category', false, false, 'CIE-11'),
('SS5Y', '', 'category', false, false, 'CIE-11'),
('SS5Z', '', 'category', false, false, 'CIE-11'),
('SS60', '', 'category', false, false, 'CIE-11'),
('SS61', '', 'category', false, false, 'CIE-11'),
('SS62', '', 'category', false, false, 'CIE-11'),
('SS6Y', '', 'category', false, false, 'CIE-11'),
('SS6Z', '', 'category', false, false, 'CIE-11'),
('SS70', '', 'category', false, false, 'CIE-11'),
('SS71', '', 'category', false, false, 'CIE-11'),
('SS72', '', 'category', false, false, 'CIE-11'),
('SS73', '', 'category', false, false, 'CIE-11'),
('SS74', '', 'category', false, false, 'CIE-11'),
('SS75', '', 'category', false, false, 'CIE-11'),
('SS7Y', '', 'category', false, false, 'CIE-11'),
('SS7Z', '', 'category', false, false, 'CIE-11'),
('SS80', '', 'category', false, false, 'CIE-11'),
('SS81', '', 'category', false, false, 'CIE-11'),
('SS82', '', 'category', false, false, 'CIE-11'),
('SS83', '', 'category', false, false, 'CIE-11'),
('SS84', '', 'category', false, false, 'CIE-11'),
('SS85', '', 'category', false, false, 'CIE-11'),
('SS86', '', 'category', false, false, 'CIE-11'),
('SS87', '', 'category', false, false, 'CIE-11'),
('SS88', '', 'category', false, false, 'CIE-11'),
('SS89', '', 'category', false, false, 'CIE-11'),
('SS8Y', '', 'category', false, false, 'CIE-11'),
('SS8Z', '', 'category', false, false, 'CIE-11'),
('ST00', '', 'category', false, false, 'CIE-11'),
('ST01', '', 'category', false, false, 'CIE-11'),
('ST02', '', 'category', false, false, 'CIE-11'),
('ST03', '', 'category', false, false, 'CIE-11'),
('ST04', '', 'category', false, false, 'CIE-11'),
('ST05', '', 'category', false, false, 'CIE-11'),
('ST06', '', 'category', false, false, 'CIE-11'),
('ST07', '', 'category', false, false, 'CIE-11'),
('ST08', '', 'category', false, false, 'CIE-11'),
('ST09', '', 'category', false, false, 'CIE-11'),
('ST0A', '', 'category', false, false, 'CIE-11'),
('ST0B', '', 'category', false, false, 'CIE-11'),
('ST0C', '', 'category', false, false, 'CIE-11'),
('ST0D', '', 'category', false, false, 'CIE-11'),
('ST0E', '', 'category', false, false, 'CIE-11'),
('ST0F', '', 'category', false, false, 'CIE-11'),
('ST0G', '', 'category', false, false, 'CIE-11'),
('ST0H', '', 'category', false, false, 'CIE-11'),
('ST0J', '', 'category', false, false, 'CIE-11'),
('ST0K', '', 'category', false, false, 'CIE-11'),
('ST0L', '', 'category', false, false, 'CIE-11'),
('ST0M', '', 'category', false, false, 'CIE-11'),
('ST0N', '', 'category', false, false, 'CIE-11'),
('ST0P', '', 'category', false, false, 'CIE-11'),
('ST0Q', '', 'category', false, false, 'CIE-11'),
('ST0R', '', 'category', false, false, 'CIE-11'),
('ST0S', '', 'category', false, false, 'CIE-11'),
('ST0T', '', 'category', false, false, 'CIE-11'),
('ST0U', '', 'category', false, false, 'CIE-11'),
('ST0V', '', 'category', false, false, 'CIE-11'),
('ST0W', '', 'category', false, false, 'CIE-11'),
('ST0X', '', 'category', false, false, 'CIE-11'),
('ST10', '', 'category', false, false, 'CIE-11'),
('ST11', '', 'category', false, false, 'CIE-11'),
('ST1Y', '', 'category', false, false, 'CIE-11'),
('ST1Z', '', 'category', false, false, 'CIE-11'),
('ST20', '', 'category', false, false, 'CIE-11'),
('ST2Y', '', 'category', false, false, 'CIE-11'),
('ST2Z', '', 'category', false, false, 'CIE-11'),
('VD00', 'Funciones de atención [WHODAS]', 'category', false, false, 'CIE-11'),
('VD01', 'Funciones de la memoria [WHODAS]', 'category', false, false, 'CIE-11'),
('VD02', 'Solución de problemas [WHODAS]', 'category', false, false, 'CIE-11'),
('VD03', 'Aprendizaje básico [WHODAS]', 'category', false, false, 'CIE-11'),
('VD04', 'Comunicarse con - recibir - mensajes hablados [WHODAS]', 'category', false, false, 'CIE-11'),
('VD05', 'Conversación [WHODAS]', 'category', false, false, 'CIE-11'),
('VD10', 'Mantener una posición de pie [WHODAS]', 'category', false, false, 'CIE-11'),
('VD11', 'Cambiar la posición del cuerpo: ponerse de pie [WHODAS]', 'category', false, false, 'CIE-11'),
('VD12', 'Moverse dentro de la casa [WHODAS]', 'category', false, false, 'CIE-11'),
('VD13', 'Moverse alrededor fuera de la casa y de otras edificaciones', 'category', false, false, 'CIE-11'),
('VD14', 'Caminar [WHODAS]', 'category', false, false, 'CIE-11'),
('VD20', 'Lavarse uno mismo [WHODAS]', 'category', false, false, 'CIE-11'),
('VD21', 'Vestirse uno mismo [WHODAS]', 'category', false, false, 'CIE-11'),
('VD22', 'Comer uno mismo [WHODAS]', 'category', false, false, 'CIE-11'),
('VD23', 'Llevar a cabo la rutina diaria [WHODAS]', 'category', false, false, 'CIE-11'),
('VD30', 'Relacionándose con personas extrañas [WHODAS]', 'category', false, false, 'CIE-11'),
('VD31', 'Mantener una relación informal con amigos [WHODAS]', 'category', false, false, 'CIE-11'),
('VD32', 'Relaciones familiares [WHODAS]', 'category', false, false, 'CIE-11'),
('VD33', 'Relación informal con amigos: hacer nuevos amigos [WHODAS]', 'category', false, false, 'CIE-11'),
('VD34', 'Relaciones íntimas [WHODAS]', 'category', false, false, 'CIE-11'),
('VD40', 'Cumplir con las responsabilidades del hogar [WHODAS]', 'category', false, false, 'CIE-11'),
('VD41', 'Hacer los quehaceres de la casa más importantes [WHODAS]', 'category', false, false, 'CIE-11'),
('VD42', 'Hacer los quehaceres domésticos [WHODAS]', 'category', false, false, 'CIE-11'),
('VD42.0', 'Hacer todo el trabajo necesario en la casa [WHODAS]', 'category', false, false, 'CIE-11'),
('VD42.1', 'Hacer el trabajo de la casa rapidamente [WHODAS]', 'category', false, false, 'CIE-11'),
('VD42.Y', 'Otro quehacer doméstico especificado [WHODAS]', 'category', false, false, 'CIE-11'),
('VD42.Z', 'Hacer el quehacer doméstico [WHODAS], sin especificación', 'category', false, false, 'CIE-11'),
('VD43', 'Empleo remunerado [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.0', 'Dificultades en el trabajo cotidiano o las actividades escolares [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.1', 'Hacer las tareas más importantes del trabajo o de la escuela [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.2', 'Hacer todas las tareas necesarias en el trabajo o la escuela [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.3', 'Hacer el trabajo remunerado o las tareas escolares con rapidez [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.Y', 'Otro empleo remunerado especificado [WHODAS]', 'category', false, false, 'CIE-11'),
('VD43.Z', 'Empleo remunerado [WHODAS], sin especificación', 'category', false, false, 'CIE-11'),
('VD50', 'Recreación y ocio [WHODAS]', 'category', false, false, 'CIE-11'),
('VD51', 'Problemas por barreras [WHODAS]', 'category', false, false, 'CIE-11'),
('VD52', 'Derechos humanos [WHODAS]', 'category', false, false, 'CIE-11'),
('VD53', 'Tiempo dedicado a la condición de salud [WHODAS]', 'category', false, false, 'CIE-11'),
('VD54', 'Efecto emocional de la condición de salud [WHODAS]', 'category', false, false, 'CIE-11'),
('VD55', 'Gasto de recursos financieros en salud [WHODAS]', 'category', false, false, 'CIE-11'),
('VD56', 'Problemas de salud que causan dificultades familiares [WHODAS]', 'category', false, false, 'CIE-11'),
('VD57', 'Problemas para relajarse o sentir placer [WHODAS]', 'category', false, false, 'CIE-11'),
('VE00', 'Ver y funciones relacionadas [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE01', 'Funciones auditivas y vestibulares [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE10', 'Funciones de energía y conducción [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE11', 'Funciones del sueño [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE12', 'Funciones emocionales [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE13', 'Funciones de atención [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE14', 'Funciones de la memoria [EMDcorta]', 'category', false, false, 'CIE-11'),
('VE20', 'Sensación de dolor [EMDcorta]', 'category', false, false, 'CIE-11'),
('VV00', 'Funciones de la energía y de los impulsos', 'category', false, false, 'CIE-11'),
('VV01', 'Funciones del sueño', 'category', false, false, 'CIE-11'),
('VV02', 'Funciones de la atención', 'category', false, false, 'CIE-11'),
('VV03', 'Funciones de la memoria', 'category', false, false, 'CIE-11'),
('VV04', 'Funciones emocionales', 'category', false, false, 'CIE-11'),
('VV0Y', 'Otras funciones mentales especificadas', 'category', false, false, 'CIE-11'),
('VV0Z', 'Funciones mentales, sin especificación', 'category', false, false, 'CIE-11'),
('VV10', 'Visión y funciones relacionadas', 'category', false, false, 'CIE-11'),
('VV11', 'Funciones auditivas y vestibulares', 'category', false, false, 'CIE-11'),
('VV12', 'Sensación de dolor', 'category', false, false, 'CIE-11'),
('VV1Y', 'Otras funciones sensoriales y dolor especificadas', 'category', false, false, 'CIE-11'),
('VV1Z', 'Funciones sensoriales y dolor, sin especificación', 'category', false, false, 'CIE-11'),
('VV20', 'Funciones de la voz', 'category', false, false, 'CIE-11'),
('VV2Y', 'Otras funciones de la voz y del habla especificadas', 'category', false, false, 'CIE-11'),
('VV2Z', 'Funciones de la voz y del habla sin especificación', 'category', false, false, 'CIE-11'),
('VV30', 'Funciones de tolerancia al ejercicio', 'category', false, false, 'CIE-11'),
('VV3Y', 'Otras funciones de los sistemas cardiovascular, hematológico, inmunológico y respiratorio especificadas', 'category', false, false, 'CIE-11'),
('VV3Z', 'Funciones de los sistemas cardiovascular, hematológico, inmunológico y respiratorio, sin especificación', 'category', false, false, 'CIE-11'),
('VV40', 'Funciones relacionadas con el sistema digestivo', 'category', false, false, 'CIE-11'),
('VV4Y', 'Otras funciones de los sistemas digestivo, metabólico y endocrino especificadas', 'category', false, false, 'CIE-11'),
('VV4Z', 'Funciones de los sistemas digestivo, metabólico y endocrino, sin especificación', 'category', false, false, 'CIE-11'),
('VV50', 'Funciones urinarias', 'category', false, false, 'CIE-11'),
('VV51', 'Funciones sexuales', 'category', false, false, 'CIE-11'),
('VV5Y', 'Otras funciones genitourinarias y reproductoras especificadas', 'category', false, false, 'CIE-11'),
('VV5Z', 'Funciones genitourinarias y reproductoras, sin especificación', 'category', false, false, 'CIE-11'),
('VV60', 'Funciones relacionadas con la movilidad articular', 'category', false, false, 'CIE-11'),
('VV61', 'Funciones relacionadas con la fuerza muscular', 'category', false, false, 'CIE-11'),
('VV6Y', 'Otras funciones neuromusculoesqueléticas y relacionadas con el movimiento', 'category', false, false, 'CIE-11'),
('VV6Z', 'Funciones neuromusculoesqueléticas y relacionadas con el movimiento, sin especificación', 'category', false, false, 'CIE-11'),
('VV70', 'Funciones de la piel', 'category', false, false, 'CIE-11'),
('VV7Y', 'Otras funciones de la piel y estructuras relacionadas', 'category', false, false, 'CIE-11'),
('VV7Z', 'Funciones de la piel y estructuras relacionadas, sin especificación', 'category', false, false, 'CIE-11'),
('VV80', 'Aprendizaje básico', 'category', false, false, 'CIE-11'),
('VV81', 'Resolver problemas', 'category', false, false, 'CIE-11'),
('VV8Y', 'Otro aprendizaje y aplicación del conocimiento especificado', 'category', false, false, 'CIE-11'),
('VV8Z', 'Aprendizaje y aplicación del conocimiento, sin especificación', 'category', false, false, 'CIE-11'),
('VV90', 'Llevar a cabo la rutina diaria', 'category', false, false, 'CIE-11'),
('VV91', 'Manejo del estrés y otras demandas psicológicas', 'category', false, false, 'CIE-11'),
('VV9Y', 'Otras tareas y demandas generales especificadas', 'category', false, false, 'CIE-11'),
('VV9Z', 'Tareas y demandas generales, sin especificación', 'category', false, false, 'CIE-11'),
('VW00', 'Comunicación- recepción de mensajes hablados', 'category', false, false, 'CIE-11'),
('VW01', 'Conversación', 'category', false, false, 'CIE-11'),
('VW0Y', 'Otra comunicación especificada', 'category', false, false, 'CIE-11'),
('VW0Z', 'Comunicación, sin especificación', 'category', false, false, 'CIE-11'),
('VW10', 'Permanecer de pie', 'category', false, false, 'CIE-11'),
('VW11', 'Transferir el propio cuerpo', 'category', false, false, 'CIE-11'),
('VW12', 'Llevar, mover y manipular objetos', 'category', false, false, 'CIE-11'),
('VW13', 'Andar', 'category', false, false, 'CIE-11'),
('VW14', 'Desplazarse dentro de la casa', 'category', false, false, 'CIE-11'),
('VW15', 'Desplazarse usando equipamiento', 'category', false, false, 'CIE-11'),
('VW16', 'Desplazarse utilizando medios de transporte', 'category', false, false, 'CIE-11'),
('VW1Y', 'Otra movilidad especificada', 'category', false, false, 'CIE-11'),
('VW1Z', 'Movilidad, sin especificación', 'category', false, false, 'CIE-11'),
('VW20', 'Lavarse uno mismo', 'category', false, false, 'CIE-11'),
('VW21', 'Cuidado de partes del cuerpo', 'category', false, false, 'CIE-11'),
('VW22', 'Higiene personal relacionada con los procesos de excreción', 'category', false, false, 'CIE-11'),
('VW23', 'Vestirse', 'category', false, false, 'CIE-11'),
('VW24', 'Comer', 'category', false, false, 'CIE-11'),
('VW25', 'Cuidado de la propia salud', 'category', false, false, 'CIE-11'),
('VW2Y', 'Otro autocuidado especificado', 'category', false, false, 'CIE-11'),
('VW2Z', 'Autocuidado, sin especificación', 'category', false, false, 'CIE-11'),
('VW30', 'Preparar comidas', 'category', false, false, 'CIE-11'),
('VW31', 'Realizar los quehaceres de la casa', 'category', false, false, 'CIE-11'),
('VW32', 'Ayudar a los demás', 'category', false, false, 'CIE-11'),
('VW3Y', 'Otra vida doméstica especificada', 'category', false, false, 'CIE-11'),
('VW3Z', 'Vida doméstica, sin especificación', 'category', false, false, 'CIE-11'),
('VW40', 'Interacciones interpersonales básicas', 'category', false, false, 'CIE-11'),
('VW41', 'Relacionarse con extraños', 'category', false, false, 'CIE-11'),
('VW42', 'Relaciones íntimas', 'category', false, false, 'CIE-11'),
('VW4Y', 'Otras interacciones y relaciones interpersonales especificadas', 'category', false, false, 'CIE-11'),
('VW4Z', 'Interacciones y relaciones interpersonales, sin especificación', 'category', false, false, 'CIE-11'),
('VW50', 'Trabajo remunerado', 'category', false, false, 'CIE-11'),
('VW5Y', 'Otras áreas principales de la vida especificadas', 'category', false, false, 'CIE-11'),
('VW5Z', 'Áreas principales de la vida, sin especificación', 'category', false, false, 'CIE-11'),
('VW60', 'Recreación y ocio', 'category', false, false, 'CIE-11'),
('VW61', 'Derechos humanos', 'category', false, false, 'CIE-11'),
('VW6Y', 'Otra vida comunitaria, social y cívica especificada', 'category', false, false, 'CIE-11'),
('VW6Z', 'Vida comunitaria, social y cívica, sin especificación', 'category', false, false, 'CIE-11'),
('VW8Y', 'Otros dominios genéricos de funcionamiento especificados', 'category', false, false, 'CIE-11'),
('VW8Z', 'Dominios genéricos de funcionamiento, sin especificación', 'category', false, false, 'CIE-11'),
('XS8H', 'Ninguno', 'category', false, false, 'CIE-11'),
('XS5W', 'Leve', 'category', false, false, 'CIE-11'),
('XS0T', 'Moderado', 'category', false, false, 'CIE-11'),
('XS25', 'Grave', 'category', false, false, 'CIE-11'),
('XS2R', 'Profundo', 'category', false, false, 'CIE-11'),
('XS7A', 'Estadio 1', 'category', false, false, 'CIE-11'),
('XS5S', 'Estadio 2', 'category', false, false, 'CIE-11'),
('XS4D', 'Estadio 2a', 'category', false, false, 'CIE-11'),
('XS6D', 'Estadio 2b', 'category', false, false, 'CIE-11'),
('XS00', 'Estadio 3', 'category', false, false, 'CIE-11'),
('XS3T', 'Estadio 3a', 'category', false, false, 'CIE-11'),
('XS90', 'Estadio 3b', 'category', false, false, 'CIE-11'),
('XS6G', 'Estadio 4', 'category', false, false, 'CIE-11'),
('XS9N', 'Estadio 5', 'category', false, false, 'CIE-11'),
('XS88', 'Estadio 6', 'category', false, false, 'CIE-11'),
('XS52', 'Estadio 7', 'category', false, false, 'CIE-11'),
('XS0G', 'Estadio 8', 'category', false, false, 'CIE-11'),
('XS2C', 'Estadio 9', 'category', false, false, 'CIE-11'),
('XS2X', 'Estadio 10', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XS24', 'Grado 0', 'category', false, false, 'CIE-11'),
('XS6P', 'Grado 1', 'category', false, false, 'CIE-11'),
('XS31', 'Grado 2', 'category', false, false, 'CIE-11'),
('XS6F', 'Grado 3', 'category', false, false, 'CIE-11'),
('XS0K', 'Grado 4', 'category', false, false, 'CIE-11'),
('XS87', 'Grado 5', 'category', false, false, 'CIE-11'),
('XS9M', 'Grado 6', 'category', false, false, 'CIE-11'),
('XS5M', 'Grado 7', 'category', false, false, 'CIE-11'),
('XS7F', 'Grado 8', 'category', false, false, 'CIE-11'),
('XS8J', 'Grado 9', 'category', false, false, 'CIE-11'),
('XS57', 'Grado 10', 'category', false, false, 'CIE-11'),
('XS4A', 'Fase 0', 'category', false, false, 'CIE-11'),
('XS3K', 'Fase 1', 'category', false, false, 'CIE-11'),
('XS4M', 'Fase 2', 'category', false, false, 'CIE-11'),
('XS8V', 'Fase 3', 'category', false, false, 'CIE-11'),
('XS21', 'Fase 4', 'category', false, false, 'CIE-11'),
('XS8Z', 'Fase 5', 'category', false, false, 'CIE-11'),
('XS41', 'Fase 6', 'category', false, false, 'CIE-11'),
('XS73', 'Fase 7', 'category', false, false, 'CIE-11'),
('XS9Z', 'Fase 8', 'category', false, false, 'CIE-11'),
('XS83', 'Fase 9', 'category', false, false, 'CIE-11'),
('XS47', 'Fase 10', 'category', false, false, 'CIE-11'),
('XS5C', '0 Sin problema', 'category', false, false, 'CIE-11'),
('XS6Y', '1 Problema leve', 'category', false, false, 'CIE-11'),
('XS8T', '2 Problema moderado', 'category', false, false, 'CIE-11'),
('XS9D', '3 Problema grave', 'category', false, false, 'CIE-11'),
('XS91', '4 Problema completo', 'category', false, false, 'CIE-11'),
('XS5P', '9 No aplicable', 'category', false, false, 'CIE-11'),
('XS0J', 'Remisión/Libre de enfermedad', 'category', false, false, 'CIE-11'),
('XS05', 'B Enfermedad local', 'category', false, false, 'CIE-11'),
('XS0E', 'Local limitado', 'category', false, false, 'CIE-11'),
('XS67', 'Localmente avanzado', 'category', false, false, 'CIE-11'),
('XS9S', 'C Enfermedad regional', 'category', false, false, 'CIE-11'),
('XS4Z', 'D Enfermedad a distancia', 'category', false, false, 'CIE-11'),
('XS76', 'Etapa 0', 'category', false, false, 'CIE-11'),
('XS1G', 'Etapa I', 'category', false, false, 'CIE-11'),
('XS4P', 'Etapa II', 'category', false, false, 'CIE-11'),
('XS6H', 'Etapa III', 'category', false, false, 'CIE-11'),
('XS9R', 'Etapa IV', 'category', false, false, 'CIE-11'),
('XS56', 'Grado I', 'category', false, false, 'CIE-11'),
('XS58', 'Grado II', 'category', false, false, 'CIE-11'),
('XS7Z', 'Grado III', 'category', false, false, 'CIE-11'),
('XS7M', 'Grado IV', 'category', false, false, 'CIE-11'),
('XS7H', 'Grado indeterminado', 'category', false, false, 'CIE-11'),
('XS3A', 'Clase I de la NYHA: sin limitación de actividad física', 'category', false, false, 'CIE-11'),
('XS6B', 'Clase II de la NYHA: leve limitación de la actividad física', 'category', false, false, 'CIE-11'),
('XS9T', 'Clase III de la NYHA: limitación marcada de la actividad física', 'category', false, false, 'CIE-11'),
('XS9F', 'Clase IV de la NYHA: no se puede realizar ninguna actividad física sin sentir molestias', 'category', false, false, 'CIE-11'),
('XS80', 'GOLD 1 - leve: FEV1 ≥ 80% previsto', 'category', false, false, 'CIE-11'),
('XS7U', 'GOLD 2 - moderado: 50% ≤FEV1 <80% previsto', 'category', false, false, 'CIE-11'),
('XS8K', 'GOLD 3 - grave: 30% ≤FEV1 <50% previsto', 'category', false, false, 'CIE-11'),
('XS50', 'GOLD 4 - muy severo: FEV1 <30% previsto', 'category', false, false, 'CIE-11'),
('XS1Y', 'Estadio I: obstrucción incompleta de los vasos sanguíneos asintomática', 'category', false, false, 'CIE-11'),
('XS5L', 'Estadio II: dolor leve de claudicación en la extremidad', 'category', false, false, 'CIE-11'),
('XS5V', 'Estadio IIA: claudicación a una distancia > 200 metros', 'category', false, false, 'CIE-11'),
('XS6C', 'Estadio IIB: claudicación a una distancia < 200 metros', 'category', false, false, 'CIE-11'),
('XS9L', 'Etapa III: dolor en reposo, principalmente en los pies', 'category', false, false, 'CIE-11'),
('XS2J', 'Estadio IV: necrosis y / o gangrena de la extremidad', 'category', false, false, 'CIE-11'),
('XS3V', 'No hay endometriosis', 'category', false, false, 'CIE-11'),
('XS5N', 'Endometriosis delgada', 'category', false, false, 'CIE-11'),
('XS55', 'Endometriosis densa', 'category', false, false, 'CIE-11'),
('XS1H', 'Parálisis incompleta de las cuerdas vocales', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;