BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XA3FR4', 'Estroma endometrial', 'category', false, false, 'CIE-11'),
('XA2LU5', 'Miometrio', 'category', false, false, 'CIE-11'),
('XA9HG1', 'Parametrio', 'category', false, false, 'CIE-11'),
('XA3QZ2', 'Cavidad uterina', 'category', false, false, 'CIE-11'),
('XA7F09', 'Istmo del útero', 'category', false, false, 'CIE-11'),
('XA5WW1', 'Cuello del útero', 'category', false, false, 'CIE-11'),
('XA3Z33', 'Orificio interno', 'category', false, false, 'CIE-11'),
('XA7Z73', 'Canal cervical', 'category', false, false, 'CIE-11'),
('XA0KR7', 'Tejidos conectivo y otros tejidos blandos del útero', 'category', false, false, 'CIE-11'),
('XA1QK0', 'Ovario', 'category', false, false, 'CIE-11'),
('XA6FA5', 'Corteza del ovario', 'category', false, false, 'CIE-11'),
('XA44X6', 'Médula del ovario', 'category', false, false, 'CIE-11'),
('XA7E69', 'Anexos uterinos', 'category', false, false, 'CIE-11'),
('XA3EF0', 'Trompa de Falopio', 'category', false, false, 'CIE-11'),
('XA1MQ5', 'Estructuras embriológicas', 'category', false, false, 'CIE-11'),
('XA7A99', 'Tejido de desarrollo', 'category', false, false, 'CIE-11'),
('XA7TJ5', 'Ectodermo', 'category', false, false, 'CIE-11'),
('XA3HM5', 'Endodermo', 'category', false, false, 'CIE-11'),
('XA3D33', 'Mesodermo', 'category', false, false, 'CIE-11'),
('XA3NA0', 'Embrión', 'category', false, false, 'CIE-11'),
('XA23B0', 'Feto', 'category', false, false, 'CIE-11'),
('XA85H6', 'Membranas fetales', 'category', false, false, 'CIE-11'),
('XA7MU1', 'Saco amniótico', 'category', false, false, 'CIE-11'),
('XA8XR0', 'Amnios', 'category', false, false, 'CIE-11'),
('XA66R5', 'Corion', 'category', false, false, 'CIE-11'),
('XA33K4', 'Líquido amniótico', 'category', false, false, 'CIE-11'),
('XA9YJ5', 'Alantoides', 'category', false, false, 'CIE-11'),
('XA0SH3', 'Conducto tirogloso', 'category', false, false, 'CIE-11'),
('XA1NC2', 'Uraco', 'category', false, false, 'CIE-11'),
('XA3L42', 'Cordón umbilical', 'category', false, false, 'CIE-11'),
('XA90F8', 'Placenta', 'category', false, false, 'CIE-11'),
('XA1RS6', 'Cabeza y cuello', 'category', false, false, 'CIE-11'),
('XA20Q1', 'Cabeza', 'category', false, false, 'CIE-11'),
('XA6CW5', 'Cuero cabelludo', 'category', false, false, 'CIE-11'),
('XA0WK0', 'Cuero cabelludo frontal', 'category', false, false, 'CIE-11'),
('XA0WG9', 'Margen del cuero cabelludo frontal', 'category', false, false, 'CIE-11'),
('XA9DZ0', 'Cuero cabelludo temporal', 'category', false, false, 'CIE-11'),
('XA26C1', 'Margen del cuero cabelludo temporal', 'category', false, false, 'CIE-11'),
('XA4W34', 'Cuero cabelludo parietal', 'category', false, false, 'CIE-11'),
('XA7JE5', 'Cuero cabelludo occipital', 'category', false, false, 'CIE-11'),
('XA3EK3', 'Margen del cuero cabelludo occipital', 'category', false, false, 'CIE-11'),
('XA5BY6', 'Vértice del cuero cabelludo', 'category', false, false, 'CIE-11'),
('XA6AL1', 'Margen del cuero cabelludo', 'category', false, false, 'CIE-11'),
('XA93S9', 'Margen del cuero cabelludo parietal', 'category', false, false, 'CIE-11'),
('XA86S4', 'Cara', 'category', false, false, 'CIE-11'),
('XA6TR8', 'Frente', 'category', false, false, 'CIE-11'),
('XA9SG2', 'Frente central', 'category', false, false, 'CIE-11'),
('XA1UW4', 'Frente paramediana', 'category', false, false, 'CIE-11'),
('XA1Z38', 'Frente lateral', 'category', false, false, 'CIE-11'),
('XA90D8', 'Glabela', 'category', false, false, 'CIE-11'),
('XA9T94', 'Sien', 'category', false, false, 'CIE-11'),
('XA29E7', 'Región orbitaria', 'category', false, false, 'CIE-11'),
('XA0SB3', 'Región periorbitaria', 'category', false, false, 'CIE-11'),
('XA5WP1', 'Región supraorbitaria', 'category', false, false, 'CIE-11'),
('XA1LZ5', 'Ceja', 'category', false, false, 'CIE-11'),
('XA6TV2', 'Región infraorbitaria', 'category', false, false, 'CIE-11'),
('XA7MK8', 'Mejilla', 'category', false, false, 'CIE-11'),
('XA5KE9', 'Mejilla superior', 'category', false, false, 'CIE-11'),
('XA0M67', 'Región malar', 'category', false, false, 'CIE-11'),
('XA57N0', 'Eminencia malar', 'category', false, false, 'CIE-11'),
('XA6C41', 'Mejilla central', 'category', false, false, 'CIE-11'),
('XA3ZL3', 'Región paranasal', 'category', false, false, 'CIE-11'),
('XA7207', 'Mejilla inferior', 'category', false, false, 'CIE-11'),
('XA0SU2', 'Región preauricular', 'category', false, false, 'CIE-11'),
('XA8KA2', 'Región mandibular', 'category', false, false, 'CIE-11'),
('XA3H13', 'Nariz', 'category', false, false, 'CIE-11'),
('XA0LR7', 'Raíz de la nariz', 'category', false, false, 'CIE-11'),
('XA5YP3', 'Dorso de la nariz', 'category', false, false, 'CIE-11'),
('XA3057', 'Sobre la punta de la nariz', 'category', false, false, 'CIE-11'),
('XA9JN5', 'Pared lateral de la nariz', 'category', false, false, 'CIE-11'),
('XA56T3', 'Punta de la nariz', 'category', false, false, 'CIE-11'),
('XA3ZG3', 'Lóbulo debajo de la punta de la nariz', 'category', false, false, 'CIE-11'),
('XA32Q9', 'Alas de la nariz', 'category', false, false, 'CIE-11'),
('XA5ED7', 'Surco alar', 'category', false, false, 'CIE-11'),
('XA7LG9', 'Borde alar', 'category', false, false, 'CIE-11'),
('XA2TK5', 'Pared lateral del ala nasal', 'category', false, false, 'CIE-11'),
('XA1B05', 'Fosa nasal', 'category', false, false, 'CIE-11'),
('XA4S17', 'Columela', 'category', false, false, 'CIE-11'),
('XA9YZ7', 'Umbral de la fosa nasal', 'category', false, false, 'CIE-11'),
('XA5A87', 'Región oral', 'category', false, false, 'CIE-11'),
('XA1A48', 'Región perioral', 'category', false, false, 'CIE-11'),
('XA8JD4', 'Labio', 'category', false, false, 'CIE-11'),
('XA7VQ4', 'Labio superior', 'category', false, false, 'CIE-11'),
('XA0K68', 'Cara anterior del labio superior', 'category', false, false, 'CIE-11'),
('XA5LY8', 'Surco nasolabial', 'category', false, false, 'CIE-11'),
('XA5163', 'Pliegue nasolabial', 'category', false, false, 'CIE-11'),
('XA8RK1', 'Borde bermellón del labio superior', 'category', false, false, 'CIE-11'),
('XA75S0', 'Bermellón del labio superior', 'category', false, false, 'CIE-11'),
('XA1EF8', 'Comisura labial', 'category', false, false, 'CIE-11'),
('XA15W6', 'Labio inferior', 'category', false, false, 'CIE-11'),
('XA5VD0', 'Cara anterior del labio inferior', 'category', false, false, 'CIE-11'),
('XA9TK2', 'Borde bermellón del labio inferior', 'category', false, false, 'CIE-11'),
('XA7H02', 'Bermellón del labio inferior', 'category', false, false, 'CIE-11'),
('XA1BP2', 'Cara interna del labio', 'category', false, false, 'CIE-11'),
('XA3141', 'Frenillo del labio', 'category', false, false, 'CIE-11'),
('XA3K27', 'Labio externo', 'category', false, false, 'CIE-11'),
('XA2C62', 'Barbilla', 'category', false, false, 'CIE-11'),
('XA04T9', 'Piel de la nariz', 'category', false, false, 'CIE-11'),
('XA7AA6', 'Cuello', 'category', false, false, 'CIE-11'),
('XA4QS6', 'Parte delantera del cuello', 'category', false, false, 'CIE-11'),
('XA1NS6', 'Triángulo anterior del cuello', 'category', false, false, 'CIE-11'),
('XA5TZ1', 'Región submentoniana', 'category', false, false, 'CIE-11'),
('XA0MP5', 'Región submandibular', 'category', false, false, 'CIE-11'),
('XA8RA2', 'Muesca supraesternal', 'category', false, false, 'CIE-11'),
('XA9DQ5', 'Región supraclavicular supraclavicular', 'category', false, false, 'CIE-11'),
('XA2ZF0', 'Lateral del cuello', 'category', false, false, 'CIE-11'),
('XA45K8', 'Triángulo posterior del cuello', 'category', false, false, 'CIE-11'),
('XA1M78', 'Nuca del cuello', 'category', false, false, 'CIE-11'),
('XA3FR3', 'Tronco', 'category', false, false, 'CIE-11'),
('XA4QH7', 'Tronco superior', 'category', false, false, 'CIE-11'),
('XA5D93', 'Tórax', 'category', false, false, 'CIE-11'),
('XA55T2', 'Pared torácica', 'category', false, false, 'CIE-11'),
('XA00R3', 'Región torácica anterior', 'category', false, false, 'CIE-11'),
('XA8ML7', 'Región torácica anterior alta', 'category', false, false, 'CIE-11'),
('XA4MN6', 'Región clavicular', 'category', false, false, 'CIE-11'),
('XA6M63', 'Región infraclavicular', 'category', false, false, 'CIE-11'),
('XA5MS8', 'Región preesternal', 'category', false, false, 'CIE-11'),
('XA7GU3', 'Región torácica anterior baja', 'category', false, false, 'CIE-11'),
('XA7884', 'Región torácica lateral', 'category', false, false, 'CIE-11'),
('XA9RL9', 'Región torácica lateral alta', 'category', false, false, 'CIE-11'),
('XA0XL3', 'Región torácica anterolateral alta', 'category', false, false, 'CIE-11'),
('XA5C28', 'Región torácica posterolateral alta', 'category', false, false, 'CIE-11'),
('XA9MN4', 'Región torácica lateral baja', 'category', false, false, 'CIE-11'),
('XA3266', 'Región torácica anterolateral baja', 'category', false, false, 'CIE-11'),
('XA7MS4', 'Región torácica posterolateral baja', 'category', false, false, 'CIE-11'),
('XA10L7', 'Parte superior de la espalda', 'category', false, false, 'CIE-11'),
('XA3PG8', 'Región supraescapular', 'category', false, false, 'CIE-11'),
('XA3WD7', 'Región escapular', 'category', false, false, 'CIE-11'),
('XA9LN5', 'Región interescapular', 'category', false, false, 'CIE-11'),
('XA8NK1', 'Región infraescapular', 'category', false, false, 'CIE-11'),
('XA6RF2', 'Región paraespinal torácica baja', 'category', false, false, 'CIE-11'),
('XA8EK1', 'Piel del tórax', 'category', false, false, 'CIE-11'),
('XA12C1', 'Mama', 'category', false, false, 'CIE-11'),
('XA1NS5', 'Mitad superior de la mama', 'category', false, false, 'CIE-11'),
('XA3LS6', 'Cuadrante superior interno de la mama', 'category', false, false, 'CIE-11'),
('XA2Q54', 'Cuadrante superior externo de la mama', 'category', false, false, 'CIE-11'),
('XA3PG5', 'Cola axilar de la mama', 'category', false, false, 'CIE-11'),
('XA0US1', 'Porción central de la mama', 'category', false, false, 'CIE-11'),
('XA2JK3', 'Areola', 'category', false, false, 'CIE-11'),
('XA85A1', 'Conductos galactóforo', 'category', false, false, 'CIE-11'),
('XA5MC5', 'Pezón', 'category', false, false, 'CIE-11'),
('XA3UY3', 'Mitad inferior de la mama', 'category', false, false, 'CIE-11'),
('XA0VX8', 'Cuadrante inferior interno de mama', 'category', false, false, 'CIE-11'),
('XA94U2', 'Cuadrante inferior externo de la mama', 'category', false, false, 'CIE-11'),
('XA9CM2', 'Mitad lateral de la mama', 'category', false, false, 'CIE-11'),
('XA3JH6', 'Mitad medial de la mama', 'category', false, false, 'CIE-11'),
('XA0T50', 'Flexión inframamaria', 'category', false, false, 'CIE-11'),
('XA6CY1', 'Tronco inferior', 'category', false, false, 'CIE-11'),
('XA6GV0', 'Abdomen', 'category', false, false, 'CIE-11'),
('XA0U66', 'Abdomen superior', 'category', false, false, 'CIE-11'),
('XA8ZL8', 'Epigastrio', 'category', false, false, 'CIE-11'),
('XA3TD4', 'Hipocondrio', 'category', false, false, 'CIE-11'),
('XA1LM1', 'Región periumbilical', 'category', false, false, 'CIE-11'),
('XA3MT8', 'Ombligo', 'category', false, false, 'CIE-11'),
('XA1DN2', 'región lumbar lateral', 'category', false, false, 'CIE-11'),
('XA4TC0', 'Abdomen inferior', 'category', false, false, 'CIE-11'),
('XA6N20', 'Hipogastrio', 'category', false, false, 'CIE-11'),
('XA0NH8', 'Región ilíaca', 'category', false, false, 'CIE-11'),
('XA3KX0', 'Pared abdominal', 'category', false, false, 'CIE-11'),
('XA4SN6', 'Pared abdominal anterior', 'category', false, false, 'CIE-11'),
('XA25R8', 'Región lumbosacra', 'category', false, false, 'CIE-11'),
('XA6ZR2', 'Espalda media', 'category', false, false, 'CIE-11'),
('XA7ZW8', 'Región paraespinal lumbar', 'category', false, false, 'CIE-11'),
('XA8FK6', 'Región lumbar posterior', 'category', false, false, 'CIE-11'),
('XA9ET2', 'Espalda baja', 'category', false, false, 'CIE-11'),
('XA6DS1', 'Área coccígea', 'category', false, false, 'CIE-11'),
('XA2UC8', 'Región sacra', 'category', false, false, 'CIE-11'),
('XA4L23', 'Región sacroccígea', 'category', false, false, 'CIE-11'),
('XA2P90', 'Espalda', 'category', false, false, 'CIE-11'),
('XA8HA7', 'Región anogenital', 'category', false, false, 'CIE-11'),
('XA5FG3', 'Región genital', 'category', false, false, 'CIE-11'),
('XA9PG6', 'Genitales femeninos externos', 'category', false, false, 'CIE-11'),
('XA1AK8', 'Genitales masculinos externos', 'category', false, false, 'CIE-11'),
('XA8MT4', 'Escroto', 'category', false, false, 'CIE-11'),
('XA9PX3', 'Región perigenital', 'category', false, false, 'CIE-11'),
('XA0LF4', 'Área suprapúbica', 'category', false, false, 'CIE-11'),
('XA10Z0', 'Monte del pubis', 'category', false, false, 'CIE-11'),
('XA2XG2', 'Pliegue inguinocrural', 'category', false, false, 'CIE-11'),
('XA00B4', 'Conducto inguinal', 'category', false, false, 'CIE-11'),
('XA4B34', 'Región perianal', 'category', false, false, 'CIE-11'),
('XA53N9', 'Perineo', 'category', false, false, 'CIE-11'),
('XA2F27', 'Hendidura interglútea', 'category', false, false, 'CIE-11'),
('XA6AS2', 'Extremidades', 'category', false, false, 'CIE-11'),
('XA4BA8', 'Extremidad superior', 'category', false, false, 'CIE-11'),
('XA2ND5', 'Hombro', 'category', false, false, 'CIE-11'),
('XA3PZ3', 'Superficie anterior del hombro', 'category', false, false, 'CIE-11'),
('XA5BU5', 'Ápice de hombro', 'category', false, false, 'CIE-11'),
('XA34G7', 'Superficie posterior del hombro', 'category', false, false, 'CIE-11'),
('XA17J1', 'Axila', 'category', false, false, 'CIE-11'),
('XA41A1', 'Pliegue axilar anterior', 'category', false, false, 'CIE-11'),
('XA86E8', 'Ápice de la axila', 'category', false, false, 'CIE-11'),
('XA2RY5', 'Pliegue axilar posterior', 'category', false, false, 'CIE-11'),
('XA6809', 'Parte superior del brazo', 'category', false, false, 'CIE-11'),
('XA22Q1', 'Superficie anterior del brazo', 'category', false, false, 'CIE-11'),
('XA2W33', 'Superficie lateral del brazo', 'category', false, false, 'CIE-11'),
('XA5TK8', 'Superficie posterior del brazo', 'category', false, false, 'CIE-11'),
('XA3J41', 'Superficie medial del brazo', 'category', false, false, 'CIE-11'),
('XA9FF8', 'Codo', 'category', false, false, 'CIE-11'),
('XA9NE6', 'Fosa antecubital', 'category', false, false, 'CIE-11'),
('XA6599', 'Superficie condilar lateral del codo', 'category', false, false, 'CIE-11'),
('XA3RT8', 'Punta del codo', 'category', false, false, 'CIE-11'),
('XA4983', 'Superficie condilar medial del codo', 'category', false, false, 'CIE-11'),
('XA7WB0', 'Antebrazo', 'category', false, false, 'CIE-11'),
('XA8ZL6', 'Superficie palmar del antebrazo', 'category', false, false, 'CIE-11'),
('XA1VA2', 'Superficie lateral del antebrazo', 'category', false, false, 'CIE-11'),
('XA8WH0', 'Superficie dorsal del antebrazo', 'category', false, false, 'CIE-11'),
('XA2Q46', 'Superficie medial del antebrazo', 'category', false, false, 'CIE-11'),
('XA2J63', 'Muñeca', 'category', false, false, 'CIE-11'),
('XA6AR5', 'Superficie palmar de la muñeca', 'category', false, false, 'CIE-11'),
('XA3LK1', 'Superficie radial de la muñeca', 'category', false, false, 'CIE-11'),
('XA0SH5', 'Superficie dorsal de la muñeca', 'category', false, false, 'CIE-11'),
('XA0J47', 'Borde cubital de la muñeca', 'category', false, false, 'CIE-11'),
('XA5R12', 'Mano', 'category', false, false, 'CIE-11'),
('XA30Z6', 'Dorso de la mano', 'category', false, false, 'CIE-11'),
('XA3T43', 'Nudillos', 'category', false, false, 'CIE-11'),
('XA65Z3', 'Espacio membranoso interdigital de la mano', 'category', false, false, 'CIE-11'),
('XA1BR6', 'Primer espacio membranoso interdigital de la mano', 'category', false, false, 'CIE-11'),
('XA5PY9', 'Segundo espacio membranoso interdigital de la mano', 'category', false, false, 'CIE-11'),
('XA4012', 'Tercer espacio membranoso interdigital de la mano', 'category', false, false, 'CIE-11'),
('XA3WG2', 'Cuarto espacio membranoso interdigital de la mano', 'category', false, false, 'CIE-11'),
('XA3NY8', 'Palma de la mano', 'category', false, false, 'CIE-11'),
('XA3FJ0', 'Palma proximal', 'category', false, false, 'CIE-11'),
('XA2JN4', 'Eminencia tenar', 'category', false, false, 'CIE-11'),
('XA5TQ4', 'Eminencia hipotenar', 'category', false, false, 'CIE-11'),
('XA50E4', 'Palma central', 'category', false, false, 'CIE-11'),
('XA00D7', 'Palma distal', 'category', false, false, 'CIE-11'),
('XA2593', 'Dedos', 'category', false, false, 'CIE-11'),
('XA8DJ6', 'Pulgar', 'category', false, false, 'CIE-11'),
('XA0RL8', 'Perioniquio del pulgar', 'category', false, false, 'CIE-11'),
('XA13E9', 'Pliegue ungueal proximal del pulgar', 'category', false, false, 'CIE-11'),
('XA20L7', 'Eponiquio del pulgar', 'category', false, false, 'CIE-11'),
('XA4GD7', 'Pliegue ungueal lateral del pulgar', 'category', false, false, 'CIE-11'),
('XA63L0', 'Hiponiquio del pulgar', 'category', false, false, 'CIE-11'),
('XA5PD5', 'Uña del pulgar', 'category', false, false, 'CIE-11'),
('XA6DM1', 'Lúnula del pulgar', 'category', false, false, 'CIE-11'),
('XA9N39', 'Matriz de la uña del pulgar', 'category', false, false, 'CIE-11'),
('XA5V24', 'Lámina ungueal del pulgar', 'category', false, false, 'CIE-11'),
('XA5ZV0', 'Almohadilla del pulgar', 'category', false, false, 'CIE-11'),
('XA76N2', 'Dorso del pulgar', 'category', false, false, 'CIE-11'),
('XA6NZ0', 'Dedo índice', 'category', false, false, 'CIE-11'),
('XA6YH1', 'Perioniquio del dedo índice', 'category', false, false, 'CIE-11'),
('XA90K8', 'Eponiquio del dedo índice', 'category', false, false, 'CIE-11'),
('XA2UG0', 'Hiponiquio del dedo índice', 'category', false, false, 'CIE-11'),
('XA40D9', 'Uña del dedo índice', 'category', false, false, 'CIE-11'),
('XA1GS3', 'Lúnula del dedo índice', 'category', false, false, 'CIE-11'),
('XA1SB3', 'Lecho ungueal del dedo índice', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XA2XE0', 'Lámina ungueal del dedo índice', 'category', false, false, 'CIE-11'),
('XA6TA9', 'Yema del dedo índice', 'category', false, false, 'CIE-11'),
('XA0Y38', 'Dedo medio', 'category', false, false, 'CIE-11'),
('XA1FY2', 'Perioniquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA8YE5', 'Pliegue ungueal proximal del dedo medio', 'category', false, false, 'CIE-11'),
('XA13L6', 'Eponiquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA2N38', 'Pliegue ungueal lateral del dedo medio', 'category', false, false, 'CIE-11'),
('XA8KX8', 'Hiponiquio del dedo medio', 'category', false, false, 'CIE-11'),
('XA9YZ9', 'Uña del dedo medio', 'category', false, false, 'CIE-11'),
('XA8VS0', 'Lúnula del dedo medio', 'category', false, false, 'CIE-11'),
('XA2A53', 'Matriz del dedo medio', 'category', false, false, 'CIE-11'),
('XA10T8', 'Lámina ungueal del dedo medio', 'category', false, false, 'CIE-11'),
('XA79X0', 'Yema del dedo medio', 'category', false, false, 'CIE-11'),
('XA06X8', 'Dedo anular', 'category', false, false, 'CIE-11'),
('XA7K11', 'Perioniquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA1F61', 'Pliegue ungueal proximal del dedo anular', 'category', false, false, 'CIE-11'),
('XA8L06', 'Eponiquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA3HG9', 'Pliegue ungueal lateral del dedo anular', 'category', false, false, 'CIE-11'),
('XA1W89', 'Hiponiquio del dedo anular', 'category', false, false, 'CIE-11'),
('XA6Y59', 'Uña del anular', 'category', false, false, 'CIE-11'),
('XA4P58', 'Lúnula del dedo anular', 'category', false, false, 'CIE-11'),
('XA3MW5', 'Matriz de la uña del dedo anular', 'category', false, false, 'CIE-11'),
('XA3PS0', 'Lámina ungueal del dedo anular', 'category', false, false, 'CIE-11'),
('XA6C72', 'Yema del dedo anular', 'category', false, false, 'CIE-11'),
('XA5EN3', 'Dedo meñique', 'category', false, false, 'CIE-11'),
('XA89P0', 'Perioniquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4KU5', 'Pliegue ungueal proximal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA2AV8', 'Eponiquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA3LC5', 'Pliegue ungueal lateral del dedo meñique', 'category', false, false, 'CIE-11'),
('XA1C10', 'Hiponiquio del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4WN3', 'Yema del dedo meñique', 'category', false, false, 'CIE-11'),
('XA29K9', 'Uña del dedo meñique', 'category', false, false, 'CIE-11'),
('XA3R66', 'Lúnula del dedo meñique', 'category', false, false, 'CIE-11'),
('XA6HB9', 'Lecho de la uña del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4A79', 'Lámina ungueal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA4HZ3', 'Lateral del dedo', 'category', false, false, 'CIE-11'),
('XA7GT9', 'Puntas de los dedos', 'category', false, false, 'CIE-11'),
('XA41X5', 'Punta del dedo índice', 'category', false, false, 'CIE-11'),
('XA9Y99', 'Punta del dedo medio', 'category', false, false, 'CIE-11'),
('XA91S7', 'Punta del dedo anular', 'category', false, false, 'CIE-11'),
('XA8QW7', 'Punta del dedo meñique', 'category', false, false, 'CIE-11'),
('XA0EH9', 'Uñas', 'category', false, false, 'CIE-11'),
('XA66R9', 'Piel del codo', 'category', false, false, 'CIE-11'),
('XA45A6', 'Extremidad inferior', 'category', false, false, 'CIE-11'),
('XA3VA7', 'Nalga', 'category', false, false, 'CIE-11'),
('XA5UE3', 'Pliegue glúteo', 'category', false, false, 'CIE-11'),
('XA5S78', 'Muslo', 'category', false, false, 'CIE-11'),
('XA98B3', 'Superficie anterior del muslo', 'category', false, false, 'CIE-11'),
('XA8RH9', 'Superficie lateral del muslo', 'category', false, false, 'CIE-11'),
('XA4TQ2', 'Región trocantérica', 'category', false, false, 'CIE-11'),
('XA0183', 'Superficie posterior del muslo', 'category', false, false, 'CIE-11'),
('XA1YQ6', 'Superficie medial del muslo', 'category', false, false, 'CIE-11'),
('XA9ZB4', 'Superficie medial superior del muslo', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;