BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('QD90', 'Problemas asociados con el analfabetismo o el nivel bajo de alfabetización', 'category', false, false, 'CIE-11'),
('QD91', 'Problemas asociados con la educación no disponible o inaccesible', 'category', false, false, 'CIE-11'),
('QD92', 'Problemas con el progreso educativo', 'category', false, false, 'CIE-11'),
('QD9Y', 'Otros problemas especificados asociados con la educación', 'category', false, false, 'CIE-11'),
('QD9Z', 'Problemas asociados con la educación, sin especificación', 'category', false, false, 'CIE-11'),
('QE00', 'Dificultad de aculturación', 'category', false, false, 'CIE-11'),
('QE01', 'Estrés, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('QE02', 'Conflicto con los roles sociales', 'category', false, false, 'CIE-11'),
('QE03', 'Exclusión social o rechazo', 'category', false, false, 'CIE-11'),
('QE04', 'Objetivo de discriminación adversa o persecución percibida', 'category', false, false, 'CIE-11'),
('QE0Y', 'Otros problemas especificados asociados con el entorno social o cultural', 'category', false, false, 'CIE-11'),
('QE0Z', 'Problemas asociados con el entorno social o cultural, sin especificación', 'category', false, false, 'CIE-11'),
('QE10', 'Uso peligroso de alcohol', 'category', false, false, 'CIE-11'),
('QE11', 'Uso de drogas peligrosas', 'category', false, false, 'CIE-11'),
('QE11.0', 'Uso peligroso de opioides', 'category', false, false, 'CIE-11'),
('QE11.1', 'Uso peligroso de cannabis', 'category', false, false, 'CIE-11'),
('QE11.2', 'Uso peligroso de sedantes, hipnóticos o ansiolíticos', 'category', false, false, 'CIE-11'),
('QE11.3', 'Uso peligroso de cocaína', 'category', false, false, 'CIE-11'),
('QE11.4', 'Uso peligroso de estimulantes, incluidas las anfetaminas y las metanfetaminas', 'category', false, false, 'CIE-11'),
('QE11.5', 'Uso peligroso de cafeína', 'category', false, false, 'CIE-11'),
('QE11.6', 'Uso peligroso de MDMA u otras drogas relacionadas', 'category', false, false, 'CIE-11'),
('QE11.7', 'Uso peligroso de drogas disociativas como la ketamina o la fenciclidina', 'category', false, false, 'CIE-11'),
('QE11.8', 'Uso peligroso de otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('QE11.9', 'Uso peligroso de sustancias psicoactivas desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('QE11.Y', 'Otro uso de drogas peligrosas especificadas', 'category', false, false, 'CIE-11'),
('QE11.Z', 'Uso de drogas peligrosas, sin especificación', 'category', false, false, 'CIE-11'),
('QE12', 'Uso peligroso de nicotina', 'category', false, false, 'CIE-11'),
('QE13', 'Uso de tabaco', 'category', false, false, 'CIE-11'),
('QE1Y', 'Otro uso de sustancias peligrosas especificadas', 'category', false, false, 'CIE-11'),
('QE1Z', 'Uso de sustancias peligrosas, sin especificación', 'category', false, false, 'CIE-11'),
('QE20', 'Falta de ejercicio físico', 'category', false, false, 'CIE-11'),
('QE21', 'Juego de apuestas peligroso', 'category', false, false, 'CIE-11'),
('QE22', 'Uso de videojuegos peligroso', 'category', false, false, 'CIE-11'),
('QE23', 'Problemas por alimentación o hábitos alimenticios inadecuados', 'category', false, false, 'CIE-11'),
('QE24', 'Problemas con los comportamientos relativos a la higiene', 'category', false, false, 'CIE-11'),
('QE25', 'Problemas con los comportamientos relativos de la salud bucal', 'category', false, false, 'CIE-11'),
('QE26', 'Problemas con los comportamientos relativos a la exposición al sol', 'category', false, false, 'CIE-11'),
('QE27', 'Problemas con los comportamientos relativos a la salud psicológica o el bienestar', 'category', false, false, 'CIE-11'),
('QE28', 'Problemas relativos a los conocimientos sobre la salud', 'category', false, false, 'CIE-11'),
('QE2Y', 'Otros problemas especificados asociados con los comportamientos de salud', 'category', false, false, 'CIE-11'),
('QE2Z', 'Problemas asociados con los comportamientos de salud, sin especificación', 'category', false, false, 'CIE-11'),
('QE30', 'Apoyo insuficiente del seguro social', 'category', false, false, 'CIE-11'),
('QE30.0', 'Apoyo insuficiente del seguro social, personas ancianas', 'category', false, false, 'CIE-11'),
('QE30.1', 'Apoyo insuficiente del seguro social, discapacidad', 'category', false, false, 'CIE-11'),
('QE30.2', 'Apoyo insuficiente del seguro social, desempleo', 'category', false, false, 'CIE-11'),
('QE30.3', 'Apoyo insuficiente del seguro social, apoyo a la familia', 'category', false, false, 'CIE-11'),
('QE30.Z', 'Apoyo insuficiente del seguro social, sin especificación', 'category', false, false, 'CIE-11'),
('QE31', 'Apoyo insuficiente de la asistencia social', 'category', false, false, 'CIE-11'),
('QE31.0', 'Apoyo insuficiente de la asistencia social, protección infantil', 'category', false, false, 'CIE-11'),
('QE31.1', 'Apoyo insuficiente de la asistencia social, protección contra la violencia doméstica', 'category', false, false, 'CIE-11'),
('QE31.2', 'Apoyo insuficiente de la asistencia social, protección contra la falta de vivienda', 'category', false, false, 'CIE-11'),
('QE31.3', 'Apoyo insuficiente de la asistencia social, servicios posteriores a la reclusión en prisión', 'category', false, false, 'CIE-11'),
('QE31.Z', 'Apoyo insuficiente de la asistencia social, sin especificación', 'category', false, false, 'CIE-11'),
('QE3Y', 'Otros problemas especificados asociados con la asistencia o el seguro social', 'category', false, false, 'CIE-11'),
('QE3Z', 'Problemas asociados con la asistencia o el seguro social, sin especificación', 'category', false, false, 'CIE-11'),
('QE40', 'Problemas asociados con la condena en procesos civiles o penales sin encarcelamiento', 'category', false, false, 'CIE-11'),
('QE41', 'Problemas asociados con la detención y otro tipo de encarcelamiento', 'category', false, false, 'CIE-11'),
('QE42', 'Problemas asociados con la liberación de la prisión', 'category', false, false, 'CIE-11'),
('QE4Y', 'Otros problemas especificados asociados con el sistema de justicia', 'category', false, false, 'CIE-11'),
('QE4Z', 'Problemas asociados con el sistema de justicia, sin especificación', 'category', false, false, 'CIE-11'),
('QE50', 'Problemas asociados con las interacciones interpersonales', 'category', false, false, 'CIE-11'),
('QE50.0', 'Problemas asociados con una relación de amistad', 'category', false, false, 'CIE-11'),
('QE50.1', 'Problemas asociados con la relación con maestros o compañeros de clase', 'category', false, false, 'CIE-11'),
('QE50.10', 'Insatisfacción con el ambiente escolar', 'category', false, false, 'CIE-11'),
('QE50.1Y', 'Otras relaciones especificadas con maestros o compañeros de clase', 'category', false, false, 'CIE-11'),
('QE50.1Z', 'Relaciones con maestros o compañeros de clase, sin especificación', 'category', false, false, 'CIE-11'),
('QE50.2', 'Problemas asociados con las relaciones con las personas en el trabajo', 'category', false, false, 'CIE-11'),
('QE50.3', 'Relaciones con vecinos, inquilinos o propietarios', 'category', false, false, 'CIE-11'),
('QE50.4', 'Relación con los padres, los suegros u otros miembros de la familia', 'category', false, false, 'CIE-11'),
('QE50.5', 'Desavenencias o discordia con consejeros', 'category', false, false, 'CIE-11'),
('QE50.6', 'Habilidades sociales inadecuadas', 'category', false, false, 'CIE-11'),
('QE50.7', 'Dificultades de la personalidad', 'category', false, false, 'CIE-11'),
('QE50.Y', 'Otro problema especificado asociado con las interacciones interpersonales', 'category', false, false, 'CIE-11'),
('QE51', 'Problemas asociados con la interacción con el cónyuge o la pareja', 'category', false, false, 'CIE-11'),
('QE51.0', 'Malestar en la relación con el cónyuge o la pareja', 'category', false, false, 'CIE-11'),
('QE51.1', 'Antecedentes de violencia del cónyuge o la pareja', 'category', false, false, 'CIE-11'),
('QE51.Y', 'Otro(a)(s) problemas asociados con la interacción con el cónyuge o la pareja especificado(a)(s)', 'category', false, false, 'CIE-11'),
('QE51.Z', 'Problemas asociados con la interacción con el cónyuge o la pareja, sin especificación', 'category', false, false, 'CIE-11'),
('QE52', 'Problemas asociados con las interacciones interpersonales en la infancia', 'category', false, false, 'CIE-11'),
('QE52.0', 'Problemas de la relación entre el cuidador y el niño', 'category', false, false, 'CIE-11'),
('QE52.1', 'Pérdida de una relación afectiva en la infancia', 'category', false, false, 'CIE-11'),
('QE52.Y', 'Otro(a)(s) problemas asociados con las interacciones interpersonales en la infancia especificado(a)(s)', 'category', false, false, 'CIE-11'),
('QE52.Z', 'Problemas asociados con las interacciones interpersonales en la infancia, sin especificación', 'category', false, false, 'CIE-11'),
('QE5Y', 'Otros problemas especificados asociados con las relaciones entre las personas', 'category', false, false, 'CIE-11'),
('QE5Z', 'Problemas asociados con las relaciones entre las personas, sin especificación', 'category', false, false, 'CIE-11'),
('QE60', 'Problemas relacionados con la ausencia de un miembro de la familia', 'category', false, false, 'CIE-11'),
('QE61', 'Desaparición o muerte de un miembro de la familia', 'category', false, false, 'CIE-11'),
('QE61.0', 'Pérdida o muerte de un hijo', 'category', false, false, 'CIE-11'),
('QE61.Y', 'Desaparición o muerte de otro miembro de la familia', 'category', false, false, 'CIE-11'),
('QE62', 'Duelo sin complicaciones', 'category', false, false, 'CIE-11'),
('QE6Y', 'Otros problemas especificados asociados con la ausencia, la pérdida o la muerte de otra persona', 'category', false, false, 'CIE-11'),
('QE6Z', 'Problemas asociados con la ausencia, la pérdida o la muerte de otra persona, sin especificación', 'category', false, false, 'CIE-11'),
('QE70', 'Problemas relacionados con el grupo de apoyo primario, incluidas las circunstancias familiares', 'category', false, false, 'CIE-11'),
('QE70.0', 'Apoyo familiar inadecuado', 'category', false, false, 'CIE-11'),
('QE70.1', 'Perturbación familiar por separación o divorcio', 'category', false, false, 'CIE-11'),
('QE70.2', 'Problemas relacionados con un familiar dependiente que necesita cuidado en el hogar', 'category', false, false, 'CIE-11'),
('QE70.Z', 'Problemas relacionados con el grupo de apoyo primario, incluidas las circunstancias familiares, sin especificación', 'category', false, false, 'CIE-11'),
('QE80', 'Víctima de un crimen o acto de terrorismo', 'category', false, false, 'CIE-11'),
('QE81', 'Exposición a desastre, guerra u otras hostilidades', 'category', false, false, 'CIE-11'),
('QE82', 'Antecedentes personales de maltrato', 'category', false, false, 'CIE-11'),
('QE82.0', 'Antecedentes personales de abuso físico', 'category', false, false, 'CIE-11'),
('QE82.1', 'Antecedentes personales de abuso sexual', 'category', false, false, 'CIE-11'),
('QE82.2', 'Antecedentes personales de abuso psicológico', 'category', false, false, 'CIE-11'),
('QE82.3', 'Antecedentes personales de descuido o negligencia', 'category', false, false, 'CIE-11'),
('QE82.Y', 'Otros antecedentes personales especificados de maltrato', 'category', false, false, 'CIE-11'),
('QE82.Z', 'Antecedentes personales de maltrato, sin especificación', 'category', false, false, 'CIE-11'),
('QE83', 'Experiencia personal aterradora en la infancia', 'category', false, false, 'CIE-11'),
('QE84', 'Reacción aguda al estrés', 'category', false, false, 'CIE-11'),
('QE8Y', 'Otros problemas especificados asociados con eventos traumáticos o perjudiciales', 'category', false, false, 'CIE-11'),
('QE8Z', 'Problemas asociados con eventos traumáticos o perjudiciales, sin especificación', 'category', false, false, 'CIE-11'),
('QE90', 'Supervisión o control parental inadecuado', 'category', false, false, 'CIE-11'),
('QE91', 'Sobreprotección de los padres', 'category', false, false, 'CIE-11'),
('QE92', 'Alteración de las relaciones familiares en la infancia', 'category', false, false, 'CIE-11'),
('QE93', 'Retiro del hogar en la infancia', 'category', false, false, 'CIE-11'),
('QE94', 'Crianza institucional', 'category', false, false, 'CIE-11'),
('QE95', 'Presión inapropiada de los padres y otras anormalidades en la calidad de la crianza', 'category', false, false, 'CIE-11'),
('QE96', 'Eventos en la infancia que llevan a la pérdida de la autoestima', 'category', false, false, 'CIE-11'),
('QE9Y', 'Otros problemas especificados asociados con la crianza', 'category', false, false, 'CIE-11'),
('QE9Z', 'Problemas asociados con la crianza, sin especificación', 'category', false, false, 'CIE-11'),
('QF00', 'Ausencia adquirida de miembro', 'category', false, false, 'CIE-11'),
('QF01', 'Ausencia adquirida de órganos', 'category', false, false, 'CIE-11'),
('QF01.0', 'Ausencia adquirida de mama', 'category', false, false, 'CIE-11'),
('QF01.1', 'Ausencia adquirida de órganos genitales', 'category', false, false, 'CIE-11'),
('QF01.10', 'Ausencia adquirida de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('QF01.11', 'Ausencia adquirida de órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('QF01.Y', 'Otra ausencia adquirida especificada de órganos', 'category', false, false, 'CIE-11'),
('QF01.Z', 'Ausencia adquirida de órganos, sin especificación', 'category', false, false, 'CIE-11'),
('QF0Y', 'Otra ausencia adquirida especificada de una estructura corporal', 'category', false, false, 'CIE-11'),
('QF0Z', 'Ausencia adquirida de una estructura corporal, sin especificación', 'category', false, false, 'CIE-11'),
('QF10', 'Función limitada o discapacidad de un órgano o sistema del cuerpo', 'category', false, false, 'CIE-11'),
('QF20', 'Dificultad o necesidad de asistencia con el aprendizaje', 'category', false, false, 'CIE-11'),
('QF21', 'Dificultad o necesidad de asistencia con tareas de la vida general o con el manejo de la vida', 'category', false, false, 'CIE-11'),
('QF22', 'Dificultad o necesidad de asistencia con la comunicación', 'category', false, false, 'CIE-11'),
('QF23', 'Dificultad o necesidad de asistencia con la movilidad', 'category', false, false, 'CIE-11'),
('QF24', 'Dificultad o necesidad de asistencia para el cuidado personal', 'category', false, false, 'CIE-11'),
('QF25', 'Dificultad o necesidad de asistencia con las relaciones interpersonales', 'category', false, false, 'CIE-11'),
('QF26', 'Dificultad o necesidad de asistencia con las tareas del hogar', 'category', false, false, 'CIE-11'),
('QF27', 'Dificultad o necesidad de asistencia en el hogar cuando no hay otro miembro del hogar que pueda brindar cuidados', 'category', false, false, 'CIE-11'),
('QF28', 'Dificultad o necesidad de asistencia con las actividades laborales', 'category', false, false, 'CIE-11'),
('QF29', 'Dificultad o necesidad de asistencia con las áreas principales de la vida', 'category', false, false, 'CIE-11'),
('QF2A', 'Dificultad o necesidad de asistencia para participar en la comunidad', 'category', false, false, 'CIE-11'),
('QF2B', 'Problemas relacionados con la necesidad de supervisión continua', 'category', false, false, 'CIE-11'),
('QF2Y', 'Otra dificultad o necesidad de asistencia especificada con las actividades', 'category', false, false, 'CIE-11'),
('QF2Z', 'Dificultad o necesidad de asistencia con las actividades, sin especificación', 'category', false, false, 'CIE-11'),
('QF4Y', 'Otros factores especificados que influyen en el estado de salud o el contacto con los servicios de salud', 'category', false, false, 'CIE-11'),
('QF4Z', 'Factores que influyen en el estado de salud o el contacto con los servicios de salud, sin especificación', 'category', false, false, 'CIE-11'),
('RA00', 'Afecciones de etiología incierta y de uso emergente', 'category', false, false, 'CIE-11'),
('RA00.0', 'Trastorno relacionado con el vapeo', 'category', false, false, 'CIE-11'),
('RA01', 'COVID-19', 'category', false, false, 'CIE-11'),
('RA01.0', 'COVID-19, virus identificado', 'category', false, false, 'CIE-11'),
('RA01.1', 'COVID-19, virus no identificado', 'category', false, false, 'CIE-11'),
('RA02', 'Afección posterior a la COVID-19', 'category', false, false, 'CIE-11'),
('RA03', 'Síndrome inflamatorio multisistémico asociado con COVID-19', 'category', false, false, 'CIE-11'),
('RA04', 'Código de emergencia internacional 05', 'category', false, false, 'CIE-11'),
('RA05', 'Código de emergencia internacional 06', 'category', false, false, 'CIE-11'),
('RA06', 'Código de emergencia internacional 07', 'category', false, false, 'CIE-11'),
('RA07', 'Código de emergencia internacional 08', 'category', false, false, 'CIE-11'),
('RA08', 'Código de emergencia internacional 09', 'category', false, false, 'CIE-11'),
('RA09', 'Código de emergencia internacional 10', 'category', false, false, 'CIE-11'),
('RA20', 'Código de emergencia nacional 01', 'category', false, false, 'CIE-11'),
('RA21', 'Código de emergencia nacional 02', 'category', false, false, 'CIE-11'),
('RA22', 'Código de emergencia nacional 03', 'category', false, false, 'CIE-11'),
('RA23', 'Código de emergencia nacional 04', 'category', false, false, 'CIE-11'),
('RA24', 'Código de emergencia nacional 05', 'category', false, false, 'CIE-11'),
('RA25', 'Código de emergencia nacional 06', 'category', false, false, 'CIE-11'),
('RA26', 'Código de emergencia nacional 07', 'category', false, false, 'CIE-11'),
('SA00', 'Trastorno de dolor en el hipocondrio (MT1)', 'category', false, false, 'CIE-11'),
('SA01', 'Trastorno de ictericia (MT1)', 'category', false, false, 'CIE-11'),
('SA02', 'Trastorno de distensión del hígado (MT1)', 'category', false, false, 'CIE-11'),
('SA03', 'Hinchazón abdominal (MT1)', 'category', false, false, 'CIE-11'),
('SA04', 'Trastorno de absceso del hígado (MT1)', 'category', false, false, 'CIE-11'),
('SA05', 'Trastorno de distensión de la vesícula biliar (MT1)', 'category', false, false, 'CIE-11'),
('SA0Y', 'Otros trastornos especificados del sistema del hígado (MT1)', 'category', false, false, 'CIE-11'),
('SA0Z', 'Trastornos del sistema del hígado (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA10', 'Trastorno de palpitación inducible (MT1)', 'category', false, false, 'CIE-11'),
('SA11', 'Trastorno de palpitación espontánea (MT1)', 'category', false, false, 'CIE-11'),
('SA1Y', 'Otras palpitaciones especificadas (MT1)', 'category', false, false, 'CIE-11'),
('SA1Z', 'Palpitaciones (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA20', 'Trastorno de dolor verdadero de corazón (MT1)', 'category', false, false, 'CIE-11'),
('SA2Y', 'Otra opresión del pecho especificada (MT1)', 'category', false, false, 'CIE-11'),
('SA2Z', 'Opresión del pecho (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA4Y', 'Otros trastornos especificados del sistema del corazón (MT1)', 'category', false, false, 'CIE-11'),
('SA4Z', 'Trastornos del sistema del corazón (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA50', 'Trastorno de disfagia (MT1)', 'category', false, false, 'CIE-11'),
('SA51', 'Trastorno de dolor de estómago (MT1)', 'category', false, false, 'CIE-11'),
('SA52', 'Trastorno de distensión epigástrica (MT1)', 'category', false, false, 'CIE-11'),
('SA53', 'Trastorno de malestar epigástrico (MT1)', 'category', false, false, 'CIE-11'),
('SA54', 'Trastorno de retención de alimentos (MT1)', 'category', false, false, 'CIE-11'),
('SA55', 'Trastorno de diarrea (MT1)', 'category', false, false, 'CIE-11'),
('SA56', 'Trastorno de disentería (MT1)', 'category', false, false, 'CIE-11'),
('SA57', 'Trastorno de constipación (MT1)', 'category', false, false, 'CIE-11'),
('SA58', 'Trastorno de dolor abdominal (MT1)', 'category', false, false, 'CIE-11'),
('SA59', 'Trastorno del absceso intestinal (MT1)', 'category', false, false, 'CIE-11'),
('SA5Y', 'Otros trastornos especificados del sistema del bazo (MT1)', 'category', false, false, 'CIE-11'),
('SA5Z', 'Trastornos del sistema del bazo (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA60', 'Trastorno del resfriado común (MT1)', 'category', false, false, 'CIE-11'),
('SA70', 'Trastorno de tos con disnea (MT1)', 'category', false, false, 'CIE-11'),
('SA7Y', 'Otros trastornos especificados de tos (MT1)', 'category', false, false, 'CIE-11'),
('SA7Z', 'Trastornos de tos (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA80', 'Trastorno de disnea (MT1)', 'category', false, false, 'CIE-11'),
('SA81', 'Trastorno de sibilancia (MT1)', 'category', false, false, 'CIE-11'),
('SA82', 'Trastorno de distensión del pulmón (MT1)', 'category', false, false, 'CIE-11'),
('SA83', 'Trastorno de retención de líquido pleural (MT1)', 'category', false, false, 'CIE-11'),
('SA84', 'Trastorno de calor del pulmón (MT1)', 'category', false, false, 'CIE-11'),
('SA85', 'Trastorno de sequedad del pulmón (MT1)', 'category', false, false, 'CIE-11'),
('SA86', 'Trastorno de aprisionamiento del tórax (MT1)', 'category', false, false, 'CIE-11'),
('SA8Y', 'Otros trastornos especificados del sistema del pulmón (MT1)', 'category', false, false, 'CIE-11'),
('SA8Z', 'Trastornos del sistema del pulmón (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SA90', 'Trastorno de disuria por cálculos (MT1)', 'category', false, false, 'CIE-11'),
('SA91', 'trastorno de estranguria por calor (MT1)', 'category', false, false, 'CIE-11'),
('SA9Y', 'Otros trastornos especificados de disuria (MT1)', 'category', false, false, 'CIE-11'),
('SA9Z', 'Trastornos de disuria (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB00', 'Trastorno del estancamiento del riñón (MT1)', 'category', false, false, 'CIE-11'),
('SB01', 'Trastorno de inundación de orina (MT1)', 'category', false, false, 'CIE-11'),
('SB02', 'Trastorno de enuresis (MT1)', 'category', false, false, 'CIE-11'),
('SB03', 'Trastorno de la orina turbia (MT1)', 'category', false, false, 'CIE-11'),
('SB04', 'Trastorno de bloqueo urinario con goteo (MT1)', 'category', false, false, 'CIE-11'),
('SB05', 'Trastorno de vómito frecuente y disuria (MT1)', 'category', false, false, 'CIE-11'),
('SB06', 'Trastornos de edema (MT1)', 'category', false, false, 'CIE-11'),
('SB06.0', 'Trastorno de edema del riñón (MT1)', 'category', false, false, 'CIE-11'),
('SB06.1', 'Trastorno de edema de viento (MT1)', 'category', false, false, 'CIE-11'),
('SB06.Y', 'Otros trastornos especificados de edema (MT1)', 'category', false, false, 'CIE-11'),
('SB06.Z', 'Trastornos de edema (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB07', 'Trastorno de cólico abdominal bajo (MT1)', 'category', false, false, 'CIE-11'),
('SB08', 'Trastorno de eyaculación precoz (MT1)', 'category', false, false, 'CIE-11'),
('SB09', 'Trastorno de eyaculación involuntaria (MT1)', 'category', false, false, 'CIE-11'),
('SB0A', 'Trastorno de erección persistente (MT1)', 'category', false, false, 'CIE-11'),
('SB0B', 'Trastorno de impotencia (MT1)', 'category', false, false, 'CIE-11'),
('SB0C', 'Trastorno de infertilidad masculina (MT1)', 'category', false, false, 'CIE-11'),
('SB0Y', 'Otros trastornos especificados del sistema del riñón (MT1)', 'category', false, false, 'CIE-11'),
('SB0Z', 'Trastornos del sistema del riñón (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB2Y', 'Otros trastornos especificados de los órganos (MT1)', 'category', false, false, 'CIE-11'),
('SB2Z', 'Trastornos de los órganos (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB30', 'Trastorno de úlceras húmedas (MT1)', 'category', false, false, 'CIE-11'),
('SB31', 'Trastorno del impétigo (MT1)', 'category', false, false, 'CIE-11'),
('SB40', 'Septicemia por forunculosis (MT1)', 'category', false, false, 'CIE-11'),
('SB4Y', 'Otros trastornos especificados de forúnculos (MT1)', 'category', false, false, 'CIE-11'),
('SB4Z', 'Trastornos de forúnculo (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB50', 'Trastorno de úlcera de apoyo (MT1)', 'category', false, false, 'CIE-11'),
('SB60', 'Trastorno de abscesos profundos múltiples (MT1)', 'category', false, false, 'CIE-11'),
('SB61', 'Trastorno de abscesos anales (MT1)', 'category', false, false, 'CIE-11'),
('SB6Y', 'Otros trastornos especificados de abscesos (MT1)', 'category', false, false, 'CIE-11'),
('SB6Z', 'Trastornos de abscesos (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB70', 'Trastorno de carbunclo (MT1)', 'category', false, false, 'CIE-11'),
('SB71', 'Trastorno de picazón del pie por humedad (MT1)', 'category', false, false, 'CIE-11'),
('SB72', 'Trastorno de tiña circinada (MT1)', 'category', false, false, 'CIE-11'),
('SB73', 'Trastorno de piel escamosa (MT1)', 'category', false, false, 'CIE-11'),
('SB74', 'Trastorno de gangrena (MT1)', 'category', false, false, 'CIE-11'),
('SB75', 'Trastorno de verruga (MT1)', 'category', false, false, 'CIE-11'),
('SB76', 'Trastorno de humedad de las manos con picazón (MT1)', 'category', false, false, 'CIE-11'),
('SB77', 'Trastorno de erisipela (MT1)', 'category', false, false, 'CIE-11'),
('SB78', 'Trastorno de celulitis (MT1)', 'category', false, false, 'CIE-11'),
('SB79', 'Trastorno de aftas (MT1)', 'category', false, false, 'CIE-11'),
('SB7A', 'Trastorno por herpes zóster (MT1)', 'category', false, false, 'CIE-11'),
('SB7B', 'Trastorno de hemorroides internas (MT1)', 'category', false, false, 'CIE-11'),
('SB7C', 'Trastorno de fisura anal (MT1)', 'category', false, false, 'CIE-11'),
('SB7Y', 'Otros trastornos especificados de la piel y las mucosas (MT1)', 'category', false, false, 'CIE-11'),
('SB7Z', 'Trastornos de la piel y las mucosas (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB80', 'Trastorno de la menstruación adelantada (MT1)', 'category', false, false, 'CIE-11'),
('SB81', 'Trastorno de la menstruación retrasada (MT1)', 'category', false, false, 'CIE-11'),
('SB82', 'Trastornos de la menstruación irregular (MT1)', 'category', false, false, 'CIE-11'),
('SB8Y', 'Otros trastornos especificados del ciclo menstrual (MT1)', 'category', false, false, 'CIE-11'),
('SB8Z', 'Trastornos del ciclo menstrual (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SB90', 'Trastorno de menorragia (MT1)', 'category', false, false, 'CIE-11'),
('SB91', 'Trastorno de la menstruación disminuida (MT1)', 'category', false, false, 'CIE-11'),
('SB92', 'Trastorno de menstruación prolongada (MT1)', 'category', false, false, 'CIE-11'),
('SB93', 'Trastorno de metrorragia (MT1)', 'category', false, false, 'CIE-11'),
('SB94', 'Trastorno de amenorrea (MT1)', 'category', false, false, 'CIE-11'),
('SB95', 'Trastorno menopáusico (MT1)', 'category', false, false, 'CIE-11'),
('SB96', 'Trastorno de dismenorrea (MT1)', 'category', false, false, 'CIE-11'),
('SB9Y', 'Otros trastornos especificados asociados con la menstruación (MT1)', 'category', false, false, 'CIE-11'),
('SB9Z', 'Trastornos asociados con la menstruación (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SC00', 'Malestar matinal (MT1)', 'category', false, false, 'CIE-11'),
('SC01', 'Trastorno del feto inestable (MT1)', 'category', false, false, 'CIE-11'),
('SC02', 'Aumento de la presión vesical durante el embarazo (MT1)', 'category', false, false, 'CIE-11'),
('SC03', 'Trastorno de eclampsia (MT1)', 'category', false, false, 'CIE-11'),
('SC04', 'Trastorno de dificultad respiratoria en el embarazo (MT1)', 'category', false, false, 'CIE-11'),
('SC0Y', 'Otros trastornos especificados asociados con el embarazo (MT1)', 'category', false, false, 'CIE-11'),
('SC0Z', 'Trastornos asociados con el embarazo (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SC10', 'Trastorno de dolor abdominal puerperal (MT1)', 'category', false, false, 'CIE-11'),
('SC11', 'Trastorno del viento puerperal (MT1)', 'category', false, false, 'CIE-11'),
('SC12', 'Trastorno de hipogalactia (MT1)', 'category', false, false, 'CIE-11'),
('SC13', 'Trastorno de loquiorrea postparto (MT1)', 'category', false, false, 'CIE-11'),
('SC1Y', 'Otros trastornos especificados asociados con el puerperio (MT1)', 'category', false, false, 'CIE-11'),
('SC1Z', 'Trastornos asociados con el puerperio (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SC20', 'Trastorno de leucorrea (MT1)', 'category', false, false, 'CIE-11'),
('SC21', 'Trastorno de flato vaginal (MT1)', 'category', false, false, 'CIE-11'),
('SC22', 'Trastorno de infertilidad (MT1)', 'category', false, false, 'CIE-11'),
('SC23', 'Trastorno de masa uterina (MT1)', 'category', false, false, 'CIE-11'),
('SC24', 'Trastorno de nódulo mamario (MT1)', 'category', false, false, 'CIE-11'),
('SC2Y', 'Otros trastornos especificados asociados con el sistema reproductor femenino (MT1)', 'category', false, false, 'CIE-11'),
('SC2Z', 'Otros trastornos asociados con el sistema reproductor femenino (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SC4Y', 'Otros trastornos especificados del sistema reproductor femenino (incluido el parto) (MT1)', 'category', false, false, 'CIE-11'),
('SC4Z', 'Trastornos del sistema reproductor femenino (MT1) (incluido el parto), sin especificación', 'category', false, false, 'CIE-11'),
('SC50', 'Trastorno de impedimento del frío (MT1)', 'category', false, false, 'CIE-11'),
('SC51', 'Trastorno de impedimento del viento (MT1)', 'category', false, false, 'CIE-11'),
('SC52', 'Trastorno de impedimento de la humedad (MT1)', 'category', false, false, 'CIE-11'),
('SC5Y', 'Otros trastornos especificados de impedimento articular (MT1)', 'category', false, false, 'CIE-11'),
('SC5Z', 'Trastornos de impedimento articular (MT1), sin especificación', 'category', false, false, 'CIE-11'),
('SC60', 'Trastorno de espasmo muscular (MT1)', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;