BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('8A40.Z', 'Esclerosis múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('8A41', 'Síndromes desmielinizantes del sistema nervioso central aislados', 'category', false, false, 'CIE-11'),
('8A41.0', 'Mielitis transversa', 'category', false, false, 'CIE-11'),
('8A41.1', 'Neuromielitis óptica con positividad a anticuerpos contra la glicoproteína oligodentrocitaria de mielina', 'category', false, false, 'CIE-11'),
('8A41.Y', 'Otros síndromes desmielinizantes aislados especificados del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A41.Z', 'Síndromes desmielinizantes aislados del sistema nervioso central, sin especificación', 'category', false, false, 'CIE-11'),
('8A42', 'Encefalomielitis aguda diseminada', 'category', false, false, 'CIE-11'),
('8A42.0', 'Leucoencefalitis hemorrágica aguda', 'category', false, false, 'CIE-11'),
('8A42.Y', 'Otra encefalomielitis diseminada aguda especificada', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('8A42.Z', 'Otra encefalomielitis diseminada aguda, sin especificación', 'category', false, false, 'CIE-11'),
('8A43', 'Neuromielitis óptica', 'category', false, false, 'CIE-11'),
('8A43.0', 'Neuromielitis óptica positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.1', 'Neuromielitis óptica negativa a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.2', 'Mielitis transversa única positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.3', 'Mielitis transversa recurrente positiva a anticuerpos contra la acuaporina 4', 'category', false, false, 'CIE-11'),
('8A43.4', 'Neuritis óptica única positiva para anticuerpos contra acuaporina-4', 'category', false, false, 'CIE-11'),
('8A43.5', 'Neuritis óptica recurrente positiva para anticuerpos contra acuaporina-4', 'category', false, false, 'CIE-11'),
('8A43.Y', 'Otra neuromielitis óptica especificada', 'category', false, false, 'CIE-11'),
('8A43.Z', 'Neuromielitis óptica, sin especificación', 'category', false, false, 'CIE-11'),
('8A44', 'Leucodistrofias', 'category', false, false, 'CIE-11'),
('8A44.0', 'Enfermedad de Pelizaeus-Merzbacher', 'category', false, false, 'CIE-11'),
('8A44.1', 'Adrenoleucodistrofia', 'category', false, false, 'CIE-11'),
('8A44.2', 'Enfermedad de Alexander', 'category', false, false, 'CIE-11'),
('8A44.3', 'Algunas leucodistrofias especificadas', 'category', false, false, 'CIE-11'),
('8A44.4', 'Enfermedad de Krabbe', 'category', false, false, 'CIE-11'),
('8A44.Z', 'Leucodistrofias, sin especificación', 'category', false, false, 'CIE-11'),
('8A45', 'Trastornos secundarios de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A45.0', 'Trastornos de la sustancia blanca debidos a infecciones', 'category', false, false, 'CIE-11'),
('8A45.00', 'Mielopatía debida al virus linfotrópico de linfocitos T humanos', 'category', false, false, 'CIE-11'),
('8A45.01', 'Panencefalitis esclerosante subaguda', 'category', false, false, 'CIE-11'),
('8A45.02', 'Leucoencefalopatía progresiva multifocal', 'category', false, false, 'CIE-11'),
('8A45.0Y', 'Otros trastornos de la sustancia blanca especificados debidos a infecciones', 'category', false, false, 'CIE-11'),
('8A45.0Z', 'Trastornos de la sustancia blanca debidos a infecciones, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.1', 'Trastornos de la sustancia blanca por toxicidad', 'category', false, false, 'CIE-11'),
('8A45.2', 'Trastornos de la sustancia blanca debidos a anomalías vasculares o isquemia', 'category', false, false, 'CIE-11'),
('8A45.20', 'Trastorno de la sustancia blanca debido a arteriopatía cerebral autosómica dominante con infartos subcorticales y leucoencefalopatía', 'category', false, false, 'CIE-11'),
('8A45.21', 'Mielitis necrosante subaguda', 'category', false, false, 'CIE-11'),
('8A45.2Y', 'Otros trastornos de la sustancia blanca especificados debidos a anomalías vasculares o isquemia', 'category', false, false, 'CIE-11'),
('8A45.2Z', 'Trastornos de la sustancia blanca debidos a anomalías vasculares o isquemia, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.3', 'Trastornos de la sustancia blanca por deficiencia nutricional', 'category', false, false, 'CIE-11'),
('8A45.30', 'Trastorno de la sustancia blanca por deficiencia de vitamina B12', 'category', false, false, 'CIE-11'),
('8A45.31', 'Mielinólisis central pontina', 'category', false, false, 'CIE-11'),
('8A45.3Y', 'Otros trastornos de la sustancia blanca especificados por deficiencia nutricional', 'category', false, false, 'CIE-11'),
('8A45.3Z', 'Trastornos de la sustancia blanca por deficiencia nutricional, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.4', 'Trastornos de la sustancia blanca debidos a una enfermedad sistémica especificada', 'category', false, false, 'CIE-11'),
('8A45.40', 'Desmielinización por sarcoidosis', 'category', false, false, 'CIE-11'),
('8A45.41', 'Desmielinización por lupus eritematoso sistémico', 'category', false, false, 'CIE-11'),
('8A45.42', 'Desmielinización debida a la enfermedad de Sjögren', 'category', false, false, 'CIE-11'),
('8A45.43', 'Desmielinización debida a la enfermedad de Behçet', 'category', false, false, 'CIE-11'),
('8A45.44', 'Desmielinización por vasculitis sistémica', 'category', false, false, 'CIE-11'),
('8A45.45', 'Desmielinización por enfermedad mitocondrial', 'category', false, false, 'CIE-11'),
('8A45.4Z', 'Trastornos de la sustancia blanca debidos a una enfermedad sistémica, sin especificación', 'category', false, false, 'CIE-11'),
('8A45.Y', 'Otros trastornos secundarios especificados de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A45.Z', 'Trastornos secundarios de la sustancia blanca, sin especificación', 'category', false, false, 'CIE-11'),
('8A46', 'Desmielinización central del cuerpo calloso', 'category', false, false, 'CIE-11'),
('8A4Y', 'Otra esclerosis múltiple especificada u otros trastornos de la sustancia blanca', 'category', false, false, 'CIE-11'),
('8A4Z', 'Esclerosis múltiple u otros trastornos de la sustancia blanca, sin especificación', 'category', false, false, 'CIE-11'),
('8A60', 'Epilepsia debida a enfermedades o afecciones metabólicas o estructurales', 'category', false, false, 'CIE-11'),
('8A60.0', 'Epilepsia por daño cerebral prenatal o perinatal', 'category', false, false, 'CIE-11'),
('8A60.00', 'Epilepsia debida a las lesiones vasculares prenatales o perinatales', 'category', false, false, 'CIE-11'),
('8A60.01', 'Epilepsia por encefalopatía isquémica hipóxica neonatal', 'category', false, false, 'CIE-11'),
('8A60.0Y', 'Epilepsia por otros daños cerebrales prenatales o perinatales', 'category', false, false, 'CIE-11'),
('8A60.0Z', 'Epilepsia por daño cerebral prenatal o perinatal, sin especificación', 'category', false, false, 'CIE-11'),
('8A60.1', 'Epilepsia por trastornos cerebrovasculares', 'category', false, false, 'CIE-11'),
('8A60.2', 'Epilepsia por trastornos cerebrales degenerativos', 'category', false, false, 'CIE-11'),
('8A60.3', 'Epilepsia por demencia', 'category', false, false, 'CIE-11'),
('8A60.4', 'Epilepsia por infección o infestación del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A60.5', 'Epilepsia por traumatismo encefálico', 'category', false, false, 'CIE-11'),
('8A60.6', 'Epilepsia por tumor del sistema nervioso', 'category', false, false, 'CIE-11'),
('8A60.7', 'Epilepsia con esclerosis temporal mesial', 'category', false, false, 'CIE-11'),
('8A60.8', 'Epilepsia por trastornos inmunitarios', 'category', false, false, 'CIE-11'),
('8A60.9', 'Epilepsia por anomalías del desarrollo encefálico', 'category', false, false, 'CIE-11'),
('8A60.A', 'Epilepsia debida a síndromes genéticos con efectos generalizados o progresivos', 'category', false, false, 'CIE-11'),
('8A60.B', 'Epilepsia por esclerosis múltiple u otros trastornos desmielinizantes', 'category', false, false, 'CIE-11'),
('8A60.Y', 'Epilepsia debida a otra enfermedad o afección metabólica o estructural', 'category', false, false, 'CIE-11'),
('8A60.Z', 'Epilepsia debida a una enfermedad o afección metabólica o estructural, sin especificación', 'category', false, false, 'CIE-11'),
('8A61', 'Síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A61.0', 'Síndromes epilépticos genéticos de comienzo en el período neonatal', 'category', false, false, 'CIE-11'),
('8A61.00', 'Epilepsia dependiente del piridoxal', 'category', false, false, 'CIE-11'),
('8A61.0Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en el período neonatal', 'category', false, false, 'CIE-11'),
('8A61.0Z', 'Síndromes epilépticos genéticos especificados de comienzo en el período neonatal, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.1', 'Síndromes epilépticos genéticos de comienzo en la primera infancia', 'category', false, false, 'CIE-11'),
('8A61.10', 'Epilepsia primoinfantil familiar benigna', 'category', false, false, 'CIE-11'),
('8A61.11', 'Síndrome de Dravet', 'category', false, false, 'CIE-11'),
('8A61.12', 'Epilepsia de la primera infancia con convulsiones focales migratorias', 'category', false, false, 'CIE-11'),
('8A61.1Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en la primera infancia', 'category', false, false, 'CIE-11'),
('8A61.1Z', 'Síndromes epilépticos genéticos de comienzo en la primera infancia, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.2', 'Síndromes epilépticos genéticos de comienzo en la niñez', 'category', false, false, 'CIE-11'),
('8A61.20', 'Epilepsia benigna de la niñez con puntas centrotemporales', 'category', false, false, 'CIE-11'),
('8A61.21', 'Epilepsia del tipo ausencia de la niñez', 'category', false, false, 'CIE-11'),
('8A61.22', 'Epilepsia con convulsiones mioclónicas astáticas', 'category', false, false, 'CIE-11'),
('8A61.23', 'Ausencias mioclónicas o ausencias con mioclonías', 'category', false, false, 'CIE-11'),
('8A61.2Y', 'Otros síndromes epilépticos genéticos especificados de comienzo en la niñez', 'category', false, false, 'CIE-11'),
('8A61.2Z', 'Síndromes epilépticos genéticos especificados de comienzo en la niñez, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.3', 'Síndrome epiléptico genético de comienzo en la adolescencia o en la edad adulta', 'category', false, false, 'CIE-11'),
('8A61.30', 'Epilepsia mioclónica juvenil', 'category', false, false, 'CIE-11'),
('8A61.31', 'Epilepsia familiar con ausencias', 'category', false, false, 'CIE-11'),
('8A61.32', 'Epilepsia mioclónica familiar benigna del adulto', 'category', false, false, 'CIE-11'),
('8A61.3Y', 'Otro síndrome epiléptico genético especificado de comienzo en la adolescencia o en la edad adulta', 'category', false, false, 'CIE-11'),
('8A61.3Z', 'Síndrome epiléptico genético de comienzo en el adolescente o el adulto, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.4', 'Síndromes epilépticos genéticos de comienzo a distintas edades', 'category', false, false, 'CIE-11'),
('8A61.40', 'Epilepsias reflejas', 'category', false, false, 'CIE-11'),
('8A61.41', 'Epilepsia mioclónica progresiva', 'category', false, false, 'CIE-11'),
('8A61.4Y', 'Otros síndromes epilépticos genéticos especificados de comienzo a distintas edades', 'category', false, false, 'CIE-11'),
('8A61.4Z', 'Síndromes epilépticos genéticos de comienzo a distintas edades, sin especificación', 'category', false, false, 'CIE-11'),
('8A61.Y', 'Otros síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A61.Z', 'Síndromes genéticos o presuntamente genéticos que se expresan sobre todo en forma de convulsiones', 'category', false, false, 'CIE-11'),
('8A62', 'Encefalopatías epilépticas', 'category', false, false, 'CIE-11'),
('8A62.0', 'Espasmos infantiles', 'category', false, false, 'CIE-11'),
('8A62.1', 'Síndrome de Lennox-Gastaut', 'category', false, false, 'CIE-11'),
('8A62.2', 'Afasia epiléptica adquirida', 'category', false, false, 'CIE-11'),
('8A62.Y', 'Otras encefalopatías epilépticas especificadas', 'category', false, false, 'CIE-11'),
('8A62.Z', 'Encefalopatías epilépticas, sin especificación', 'category', false, false, 'CIE-11'),
('8A63', 'Convulsión de causa aguda', 'category', false, false, 'CIE-11'),
('8A63.0', 'Convulsiones febriles', 'category', false, false, 'CIE-11'),
('8A63.00', 'Convulsiones febriles simples', 'category', false, false, 'CIE-11'),
('8A63.01', 'Convulsiones febriles complejas', 'category', false, false, 'CIE-11'),
('8A63.0Y', 'Otras convulsiones febriles especificadas', 'category', false, false, 'CIE-11'),
('8A63.0Z', 'Convulsiones febriles, sin especificación', 'category', false, false, 'CIE-11'),
('8A63.Y', 'Otra convulsión especificada por causas agudas', 'category', false, false, 'CIE-11'),
('8A63.Z', 'Convulsión por causas agudas, sin especificación', 'category', false, false, 'CIE-11'),
('8A64', 'Convulsión aislada debida a una causa remota', 'category', false, false, 'CIE-11'),
('8A65', 'Convulsión única no provocada', 'category', false, false, 'CIE-11'),
('8A66', 'Estado epiléptico', 'category', false, false, 'CIE-11'),
('8A66.0', 'Estado epiléptico convulsivo', 'category', false, false, 'CIE-11'),
('8A66.1', 'Estado epiléptico no convulsivo', 'category', false, false, 'CIE-11'),
('8A66.10', 'Estado epiléptico de ausencia', 'category', false, false, 'CIE-11'),
('8A66.1Y', 'Otro estado epiléptico no convulsivo especificado', 'category', false, false, 'CIE-11'),
('8A66.1Z', 'Estado epiléptico no convulsivo, sin especificación', 'category', false, false, 'CIE-11'),
('8A66.Y', 'Otro estado epiléptico especificado', 'category', false, false, 'CIE-11'),
('8A66.Z', 'Estado epiléptico, sin especificación', 'category', false, false, 'CIE-11'),
('8A67', 'Convulsiones agudas repetitivas', 'category', false, false, 'CIE-11'),
('8A68', 'Tipos de convulsiones', 'category', false, false, 'CIE-11'),
('8A68.0', 'Convulsión inconsciente focal', 'category', false, false, 'CIE-11'),
('8A68.1', 'Ausencias, atípicas', 'category', false, false, 'CIE-11'),
('8A68.2', 'Ausencias, típicas', 'category', false, false, 'CIE-11'),
('8A68.3', 'Convulsión focal sin pérdida del conocimiento', 'category', false, false, 'CIE-11'),
('8A68.4', 'Convulsión tonicoclónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.5', 'Convulsión mioclónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.6', 'Convulsión tónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.7', 'Convulsión atónica generalizada', 'category', false, false, 'CIE-11'),
('8A68.Y', 'Otro tipo especificado de convulsión', 'category', false, false, 'CIE-11'),
('8A68.Z', 'Tipo de convulsión, sin especificación', 'category', false, false, 'CIE-11'),
('8A6Y', 'Otra epilepsia o convulsiones especificadas', 'category', false, false, 'CIE-11'),
('8A6Z', 'Epilepsia o convulsiones, sin especificación', 'category', false, false, 'CIE-11'),
('8A80', 'Migraña', 'category', false, false, 'CIE-11'),
('8A80.0', 'Migraña sin aura', 'category', false, false, 'CIE-11'),
('8A80.1', 'Migraña con aura', 'category', false, false, 'CIE-11'),
('8A80.10', 'Migraña hemipléjica', 'category', false, false, 'CIE-11'),
('8A80.1Y', 'Otra migraña especificada con aura', 'category', false, false, 'CIE-11'),
('8A80.1Z', 'Migraña con aura, sin especificación', 'category', false, false, 'CIE-11'),
('8A80.2', 'Migraña crónica', 'category', false, false, 'CIE-11'),
('8A80.3', 'Complicaciones relacionadas con la migraña', 'category', false, false, 'CIE-11'),
('8A80.30', 'Estado migrañoso', 'category', false, false, 'CIE-11'),
('8A80.3Y', 'Otras complicaciones especificadas relacionadas con la migraña', 'category', false, false, 'CIE-11'),
('8A80.3Z', 'Complicaciones relacionadas con la migraña, sin especificación', 'category', false, false, 'CIE-11'),
('8A80.4', 'Síndrome de vómitos cíclicos', 'category', false, false, 'CIE-11'),
('8A80.Y', 'Otra migraña especificada', 'category', false, false, 'CIE-11'),
('8A80.Z', 'Migraña, sin especificación', 'category', false, false, 'CIE-11'),
('8A81', 'Cefalea tensional', 'category', false, false, 'CIE-11'),
('8A81.0', 'Cefalea tensional episódica infrecuente', 'category', false, false, 'CIE-11'),
('8A81.1', 'Cefalea tensional episódica frecuente', 'category', false, false, 'CIE-11'),
('8A81.2', 'Cefalea tensional crónica', 'category', false, false, 'CIE-11'),
('8A81.Y', 'Otra cefalea tensional especificada', 'category', false, false, 'CIE-11'),
('8A81.Z', 'Cefalea tensional, sin especificación', 'category', false, false, 'CIE-11'),
('8A82', 'Cefaleas autonómicas del trigémino', 'category', false, false, 'CIE-11'),
('8A83', 'Otro trastorno de cefalea primaria', 'category', false, false, 'CIE-11'),
('8A84', 'Cefalea secundaria', 'category', false, false, 'CIE-11'),
('8A84.0', 'Cefalea aguda asociada con un traumatismo cefálico', 'category', false, false, 'CIE-11'),
('8A84.1', 'Cefalea persistente asociada con un traumatismo cefálico', 'category', false, false, 'CIE-11'),
('8A84.Y', 'Otra cefalea secundaria especificada', 'category', false, false, 'CIE-11'),
('8A84.Z', 'Cefalea secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A85', 'Neuropatías craneanas dolorosas u otros dolores faciales', 'category', false, false, 'CIE-11'),
('8A8Y', 'Otros trastornos especificados de cefalea', 'category', false, false, 'CIE-11'),
('8A8Z', 'Trastornos de cefalea, sin especificación', 'category', false, false, 'CIE-11'),
('8B00', 'Hemorragia intracerebral', 'category', false, false, 'CIE-11'),
('8B00.0', 'Hemorragia hemisférica profunda', 'category', false, false, 'CIE-11'),
('8B00.1', 'Hemorragia lobular', 'category', false, false, 'CIE-11'),
('8B00.2', 'Hemorragia troncoencefálica', 'category', false, false, 'CIE-11'),
('8B00.3', 'Hemorragia cerebelosa', 'category', false, false, 'CIE-11'),
('8B00.4', 'Hemorragia intraventricular sin hemorragia parenquimatosa', 'category', false, false, 'CIE-11'),
('8B00.5', 'hemorragia cerebral en varias localizaciones', 'category', false, false, 'CIE-11'),
('8B00.Z', 'Hemorragia intracerebral, sin especificación', 'category', false, false, 'CIE-11'),
('8B01', 'Hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B01.0', 'Hemorragia subaracnoidea aneurismática', 'category', false, false, 'CIE-11'),
('8B01.1', 'Hemorragia subaracnoidea no aneurismática', 'category', false, false, 'CIE-11'),
('8B01.2', 'Hemorragia subaracnoidea, sin saber si es aneurismática o no', 'category', false, false, 'CIE-11'),
('8B02', 'Hemorragia subdural sin causa traumática', 'category', false, false, 'CIE-11'),
('8B03', 'Hemorragia epidural no traumática', 'category', false, false, 'CIE-11'),
('8B0Z', 'Hemorragia intracraneal, sin especificación', 'category', false, false, 'CIE-11'),
('8B10', 'Accidente cerebral isquémico transitorio', 'category', false, false, 'CIE-11'),
('8B10.0', 'Amaurosis fugaz', 'category', false, false, 'CIE-11'),
('8B10.Y', 'Otro accidente cerebral isquémico transitorio especificado', 'category', false, false, 'CIE-11'),
('8B10.Z', 'Accidente cerebral isquémico transitorio, sin especificación', 'category', false, false, 'CIE-11'),
('8B11', 'Accidente cerebrovascular isquémico', 'category', false, false, 'CIE-11'),
('8B11.0', 'Accidente cerebrovascular isquémico debido a ateroesclerosis de arteria extracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.1', 'Accidente cerebrovascular isquémico por ateroesclerosis de arteria intracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.2', 'Accidente cerebrovascular isquémico por oclusión embólica', 'category', false, false, 'CIE-11'),
('8B11.20', 'Accidente cerebrovascular isquémico por embolia cardíaca', 'category', false, false, 'CIE-11'),
('8B11.21', 'Accidente cerebrovascular isquémico por embolia del cayado aórtico', 'category', false, false, 'CIE-11'),
('8B11.22', 'Accidente cerebrovascular isquémico por embolismo paradójico', 'category', false, false, 'CIE-11'),
('8B11.2Y', 'Otro accidente cerebrovascular isquémico especificado por oclusión embólica', 'category', false, false, 'CIE-11'),
('8B11.2Z', 'Accidente cerebrovascular isquémico por oclusión embólica, sin especificación', 'category', false, false, 'CIE-11'),
('8B11.3', 'Accidente cerebrovascular isquémico por oclusión de una arteria pequeña', 'category', false, false, 'CIE-11'),
('8B11.4', 'Accidente cerebrovascular isquémico por otra causa conocida', 'category', false, false, 'CIE-11'),
('8B11.40', 'Accidente cerebrovascular isquémico por hipoperfusión general debida a un infarto de la zona marginal', 'category', false, false, 'CIE-11'),
('8B11.41', 'Accidente cerebrovascular isquémico por otra arteriopatía no ateroesclerótica', 'category', false, false, 'CIE-11'),
('8B11.42', 'Accidente cerebrovascular isquémico por hipercoagulabilidad sanguínea', 'category', false, false, 'CIE-11'),
('8B11.43', 'Accidente cerebrovascular isquémico asociado a hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B11.44', 'Accidente cerebrovascular isquémico por disección', 'category', false, false, 'CIE-11'),
('8B11.5', 'Accidente cerebrovascular isquémico de causa desconocida', 'category', false, false, 'CIE-11'),
('8B11.50', 'Accidente cerebrovascular isquémico por oclusión o estenosis no especificada de arteria extracraneal de gran calibre', 'category', false, false, 'CIE-11'),
('8B11.51', 'Accidente cerebrovascular isquémico por oclusión o estenosis no especificadas de arteria intracraneal de gran tamaño', 'category', false, false, 'CIE-11'),
('8B11.5Z', 'Accidente cerebrovascular isquémico, sin especificación', 'category', false, false, 'CIE-11'),
('8B1Y', 'Otra isquemia cerebral especificada', 'category', false, false, 'CIE-11'),
('8B1Z', 'Isquemia cerebral, sin especificación', 'category', false, false, 'CIE-11'),
('8B20', 'Accidente cerebrovascular y se desconoce si es isquémico o hemorrágico', 'category', false, false, 'CIE-11'),
('8B21', 'Enfermedad cerebrovascular sin síntomas cerebrales agudos', 'category', false, false, 'CIE-11'),
('8B21.0', 'Infarto cerebral silencioso', 'category', false, false, 'CIE-11'),
('8B21.1', 'Microhemorragia cerebral silenciosa', 'category', false, false, 'CIE-11'),
('8B21.Y', 'Otra enfermedad cerebrovascular especificada sin síntomas cerebrales agudos', 'category', false, false, 'CIE-11'),
('8B21.Z', 'Enfermedad cerebrovascular sin síntomas cerebrales agudos, sin especificación', 'category', false, false, 'CIE-11'),
('8B22', 'Algunas enfermedades cerebrovasculares especificadas', 'category', false, false, 'CIE-11'),
('8B22.0', 'Disección de una arteria cerebral', 'category', false, false, 'CIE-11'),
('8B22.1', 'Trombosis venosa cerebral', 'category', false, false, 'CIE-11'),
('8B22.2', 'Síndromes de vasoconstricción cerebral', 'category', false, false, 'CIE-11'),
('8B22.3', 'Angiopatía amiloide cerebral aislada', 'category', false, false, 'CIE-11'),
('8B22.4', 'Malformación vascular intracraneal', 'category', false, false, 'CIE-11'),
('8B22.40', 'Malformación arteriovenosa de los vasos cerebrales', 'category', false, false, 'CIE-11'),
('8B22.41', 'Malformación cavernosa cerebral', 'category', false, false, 'CIE-11'),
('8B22.42', 'Fístula arteriovenosa dural', 'category', false, false, 'CIE-11'),
('8B22.43', 'Fístula cavernoso-carotídea', 'category', false, false, 'CIE-11'),
('8B22.4Y', 'Otra malformación vascular intracraneal especificada', 'category', false, false, 'CIE-11'),
('8B22.4Z', 'Malformación vascular intracraneal, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.5', 'Aneurisma cerebral, sin ruptura', 'category', false, false, 'CIE-11'),
('8B22.6', 'Aneurisma sacular cerebral familiar', 'category', false, false, 'CIE-11'),
('8B22.7', 'Arteritis cerebral, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8B22.70', 'Arteritis cerebral primaria', 'category', false, false, 'CIE-11'),
('8B22.7Y', 'Otra arteritis cerebral especificada, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8B22.7Z', 'Arteritis cerebral, no clasificada en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.8', 'Encefalopatía hipertensiva', 'category', false, false, 'CIE-11'),
('8B22.9', 'Accidente cerebrovascular inducido por migraña', 'category', false, false, 'CIE-11'),
('8B22.A', 'Síndrome de oclusión subclavia con robo de sangre', 'category', false, false, 'CIE-11'),
('8B22.B', 'Síndrome de moyamoya', 'category', false, false, 'CIE-11'),
('8B22.C', 'Enfermedades cerebrovasculares hereditarias', 'category', false, false, 'CIE-11'),
('8B22.C0', 'Síndrome ACADISL (CADASIL)- [arteriopatía cerebral autosómica dominante con infartos subcorticales y leucoencefalopatía]', 'category', false, false, 'CIE-11'),
('8B22.C1', 'Síndrome ACARISL (CARASIL) [arteriopatía cerebral autosómica recesiva con infartos subcorticales y leucoencefalopatía]', 'category', false, false, 'CIE-11'),
('8B22.CY', 'Otras enfermedades cerebrovasculares hereditarias especificadas', 'category', false, false, 'CIE-11'),
('8B22.CZ', 'Enfermedades cerebrovasculares hereditarias, sin especificación', 'category', false, false, 'CIE-11'),
('8B22.Y', 'Otra enfermedad cerebrovascular especificada', 'category', false, false, 'CIE-11'),
('8B23', 'Trastornos cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B24', 'Encefalopatía hipóxico-isquémica', 'category', false, false, 'CIE-11'),
('8B24.0', 'Encefalopatía anóxica isquémica', 'category', false, false, 'CIE-11'),
('8B24.Y', 'Otra encefalopatía hipóxico-isquémica especificada', 'category', false, false, 'CIE-11'),
('8B24.Z', 'Encefalopatía hipóxico-isquémica, sin especificación', 'category', false, false, 'CIE-11'),
('8B25', 'Efectos tardíos de la enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('8B25.0', 'Efectos tardíos de un accidente cerebrovascular isquémico', 'category', false, false, 'CIE-11'),
('8B25.1', 'Efectos tardíos de una hemorragia intracerebral', 'category', false, false, 'CIE-11'),
('8B25.2', 'Efectos tardíos de una hemorragia subaracnoidea', 'category', false, false, 'CIE-11'),
('8B25.3', 'Efectos tardíos de otra hemorragia intracraneal sin causa traumática', 'category', false, false, 'CIE-11'),
('8B25.4', 'Efectos tardíos de un accidente cerebrovascular sin saberse si fue isquémico o hemorrágico', 'category', false, false, 'CIE-11'),
('8B25.Y', 'Otros efectos tardíos especificados de la enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('8B25.Z', 'Efectos tardíos de la enfermedad cerebrovascular, sin especificación', 'category', false, false, 'CIE-11'),
('8B26', 'Síndromes vasculares del encéfalo en las enfermedades cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B26.0', 'Síndrome apopléctico del tronco encefálico', 'category', false, false, 'CIE-11'),
('8B26.1', 'Síndrome apopléctico cerebeloso', 'category', false, false, 'CIE-11'),
('8B26.2', 'Síndrome de la arteria cerebral media', 'category', false, false, 'CIE-11'),
('8B26.3', 'Síndrome de la arteria cerebral anterior', 'category', false, false, 'CIE-11'),
('8B26.4', 'Síndrome de la arteria cerebral posterior', 'category', false, false, 'CIE-11'),
('8B26.5', 'Síndromes lacunares', 'category', false, false, 'CIE-11'),
('8B26.50', 'Síndrome lagunar motor puro', 'category', false, false, 'CIE-11'),
('8B26.51', 'Síndrome lagunar sensorial puro', 'category', false, false, 'CIE-11'),
('8B26.5Y', 'Otros síndromes lacunares especificados', 'category', false, false, 'CIE-11'),
('8B26.5Z', 'Síndromes lacunares, sin especificación', 'category', false, false, 'CIE-11'),
('8B26.Y', 'Otros síndromes vasculares especificados del encéfalo en las enfermedades cerebrovasculares', 'category', false, false, 'CIE-11'),
('8B26.Z', 'Síndromes vasculares del encéfalo en enfermedades cerebrovasculares, sin especificación', 'category', false, false, 'CIE-11'),
('8B2Z', 'Enfermedades cerebrovasculares, sin especificación', 'category', false, false, 'CIE-11'),
('8B40', 'Síndrome de la cola de caballo', 'category', false, false, 'CIE-11'),
('8B41', 'Mielitis', 'category', false, false, 'CIE-11'),
('8B42', 'Mielopatía', 'category', false, false, 'CIE-11'),
('8B43', 'Mielopatías vasculares no compresivas', 'category', false, false, 'CIE-11'),
('8B43.0', 'Infarto arterial agudo de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.1', 'Infarto venoso agudo de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.2', 'Infarto venoso crónico de la médula espinal', 'category', false, false, 'CIE-11'),
('8B43.Y', 'Otra mielopatía vascular no compresiva especificada', 'category', false, false, 'CIE-11'),
('8B43.Z', 'Mielopatía vascular no compresiva, sin especificación', 'category', false, false, 'CIE-11'),
('8B44', 'Trastornos mielopáticos degenerativos', 'category', false, false, 'CIE-11'),
('8B44.0', 'Paraplejia espástica hereditaria', 'category', false, false, 'CIE-11'),
('8B44.00', 'Paraplejia espástica hereditaria autosómica dominante', 'category', false, false, 'CIE-11'),
('8B44.01', 'Paraplejia espástica hereditaria autosómica recesiva', 'category', false, false, 'CIE-11'),
('8B44.02', 'Paraplejia espástica hereditaria ligada a X', 'category', false, false, 'CIE-11'),
('8B44.0Y', 'Otra paraplejia espástica hereditaria especificada', 'category', false, false, 'CIE-11'),
('8B44.0Z', 'Paraplejia espástica hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8B44.Y', 'Otros trastornos mielopáticos degenerativos especificados', 'category', false, false, 'CIE-11'),
('8B44.Z', 'Trastornos mielopáticos degenerativos, sin especificación', 'category', false, false, 'CIE-11'),
('8B4Y', 'Otros trastornos de la médula espinal especificados excepto traumatismo', 'category', false, false, 'CIE-11'),
('8B4Z', 'Trastornos de la médula espinal excepto traumatismo, sin especificación', 'category', false, false, 'CIE-11'),
('8B60', 'Enfermedades de la motoneurona', 'category', false, false, 'CIE-11'),
('8B60.0', 'Esclerosis lateral amiotrófica', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;