BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('NC96.0', 'Traumatismo en el tendón de Aquiles', 'category', false, false, 'CIE-11'),
('NC96.00', 'Esguince o distensión del tendón de Aquiles', 'category', false, false, 'CIE-11'),
('NC96.01', 'Laceración del tendón de Aquiles', 'category', false, false, 'CIE-11'),
('NC96.02', 'Ruptura del tendón de Aquiles', 'category', false, false, 'CIE-11'),
('NC96.0Y', 'Otra lesión traumática especificada del tendón de Aquiles', 'category', false, false, 'CIE-11'),
('NC96.0Z', 'Lesión traumática del tendón de Aquiles, sin especificación', 'category', false, false, 'CIE-11'),
('NC96.1', 'Traumatismo en tendón, fascia o músculo del grupo muscular posterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.10', 'Esguince o distensión de otro tendón, fascia o músculo del grupo muscular posterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.11', 'Desgarro de otro tendón, fascia o músculo del grupo muscular posterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.1Y', 'Otra lesión traumática especificada de otro músculo, fascia o tendón, del grupo muscular posterior, a nivel distal de la pierna', 'category', false, false, 'CIE-11'),
('NC96.1Z', 'Lesión traumática de otro músculo, fascia o tendón, del grupo muscular posterior, a nivel distal de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC96.2', 'Traumatismo en tendón, fascia o músculo del grupo muscular anterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.20', 'Esguince o distensión de tendón, fascia o músculo del grupo muscular anterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.21', 'Desgarro de tendón, fascia o músculo del grupo muscular anterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.2Y', 'Otro traumatismo especificado en tendón, fascia o músculo del grupo muscular anterior en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.2Z', 'Traumatismo en tendón, fascia o músculo del grupo muscular anterior en la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC96.3', 'Traumatismo en tendón, fascia o músculo del grupo muscular peroneo en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.30', 'Esguince o distensión de tendón, fascia o músculo del grupo muscular peroneo en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.31', 'Desgarro de tendón, fascia o músculo del grupo muscular peroneal en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.3Y', 'Otra lesión traumática especificada del músculo, fascia o tendón, del grupo muscular peroneo a nivel distal de la pierna', 'category', false, false, 'CIE-11'),
('NC96.3Z', 'Lesión traumática del músculo, fascia o tendón, del grupo muscular peroneo a nivel distal de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC96.4', 'Traumatismo en múltiples tendones, fascias o músculos en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.5', 'Traumatismo en la bolsa sinovial de la rodilla', 'category', false, false, 'CIE-11'),
('NC96.Y', 'Traumatismo en otro tendón, fascia, músculo o bolsa sinovial especificado en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC96.Z', 'Traumatismo en tendón, fascia, músculo o bolsa sinovial en la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC97', 'Traumatismo por aplastamiento de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC97.0', 'Traumatismo por aplastamiento de la rodilla', 'category', false, false, 'CIE-11'),
('NC97.Y', 'Traumatismo por aplastamiento de otra parte especificada de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC97.Z', 'Traumatismo por aplastamiento de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC98', 'Amputación traumática de la parte inferior de la pierna', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('NC98.0', 'Amputación traumática de la parte inferior de la pierna derecha a nivel de la rodilla', 'category', false, false, 'CIE-11'),
('NC98.1', 'Amputación traumática de la parte inferior de la pierna izquierda a nivel de la rodilla', 'category', false, false, 'CIE-11'),
('NC98.2', 'Amputación traumática a nivel de rodilla, bilateral', 'category', false, false, 'CIE-11'),
('NC98.3', 'Amputación traumática entre la rodilla y el tobillo derechos', 'category', false, false, 'CIE-11'),
('NC98.4', 'Amputación traumática entre la rodilla y el tobillo izquierdos', 'category', false, false, 'CIE-11'),
('NC98.5', 'Amputación traumática entre la rodilla y el tobillo, bilateral', 'category', false, false, 'CIE-11'),
('NC98.Y', 'Otra amputación traumática especificada de la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC98.Z', 'Amputación traumática de la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('NC99', 'Traumatismos múltiples en la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC9Y', 'Otros traumatismos especificados en la rodilla o la parte inferior de la pierna', 'category', false, false, 'CIE-11'),
('NC9Z', 'Traumatismos en la rodilla o la parte inferior de la pierna, sin especificación', 'category', false, false, 'CIE-11'),
('ND10', 'Traumatismo en las uñas de los dedos del pie', 'category', false, false, 'CIE-11'),
('ND11', 'Traumatismo superficial en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND11.0', 'Excoriación en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.1', 'Contusión en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.2', 'Ampolla por razones no térmicas en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.3', 'Picadura de insecto no venenoso en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.4', 'Cuerpo extraño superficial en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.40', 'Astilla en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.4Y', 'Otro cuerpo extraño superficial especificado en el tobillo', 'category', false, false, 'CIE-11'),
('ND11.4Z', 'Cuerpo extraño superficial en el tobillo, sin especificación', 'category', false, false, 'CIE-11'),
('ND11.5', 'Excoriación en dedo del pie', 'category', false, false, 'CIE-11'),
('ND11.6', 'Contusión de dedo del pie', 'category', false, false, 'CIE-11'),
('ND11.7', 'Abrasión de otras partes o de partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.8', 'Contusión en otras partes o partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.9', 'Ampolla por razones no térmicas en otras partes o en partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.A', 'Mordedura o picadura de insecto no venenoso en otras partes o en partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.B', 'Cuerpo extraño superficial en otras partes o en partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.B0', 'Astilla en otras partes o en partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.BY', 'Otro cuerpo extraño superficial especificado en otras partes o en partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND11.BZ', 'Cuerpo extraño superficial en otras partes o en partes no especificadas del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND11.C', 'Traumatismos superficiales múltiples en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND11.Y', 'Otro traumatismo superficial especificado en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND11.Z', 'Traumatismo superficial en el tobillo o el pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND12', 'Herida abierta del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND12.0', 'Desgarro en el tobillo o el pie, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('ND12.1', 'Desgarro en el tobillo o el pie, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('ND12.2', 'Herida punzante en el tobillo o el pie, con cuerpo extraño', 'category', false, false, 'CIE-11'),
('ND12.3', 'Herida punzante en el tobillo o el pie, sin cuerpo extraño', 'category', false, false, 'CIE-11'),
('ND12.4', 'Mordedura o picadura en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND12.5', 'Heridas abiertas múltiples en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND12.6', 'Herida abierta en dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.60', 'Desgarro sin cuerpo extraño de dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.61', 'Desgarro con cuerpo extraño de dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.62', 'Herida punzante sin cuerpo extraño en dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.63', 'Herida punzante con cuerpo extraño en dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.64', 'Mordedura o picadura abierta en dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.6Y', 'Otra herida abierta especificada de un dedo del pie', 'category', false, false, 'CIE-11'),
('ND12.6Z', 'Herida abierta de dedo del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND12.Y', 'Otra herida abierta especificada del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND12.Z', 'Herida abierta del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND13', 'Fractura del pie, excepto el tobillo', 'category', false, false, 'CIE-11'),
('ND13.0', 'Fractura del calcáneo', 'category', false, false, 'CIE-11'),
('ND13.1', 'Fractura del astrágalo', 'category', false, false, 'CIE-11'),
('ND13.2', 'Fractura de hueso no especificado del tarso', 'category', false, false, 'CIE-11'),
('ND13.3', 'Fractura de hueso del metatarso', 'category', false, false, 'CIE-11'),
('ND13.4', 'Fractura de falange del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND13.5', 'Fractura de falange de otro dedo del pie', 'category', false, false, 'CIE-11'),
('ND13.6', 'Fracturas múltiples del pie', 'category', false, false, 'CIE-11'),
('ND13.7', 'Fractura del hueso cuboides', 'category', false, false, 'CIE-11'),
('ND13.8', 'Fractura del hueso cuneiforme lateral', 'category', false, false, 'CIE-11'),
('ND13.9', 'Fractura del hueso cuneiforme intermedio', 'category', false, false, 'CIE-11'),
('ND13.A', 'Fractura del hueso cuneiforme medial', 'category', false, false, 'CIE-11'),
('ND13.B', 'Fractura del hueso navicular del pie', 'category', false, false, 'CIE-11'),
('ND13.Y', 'Otra fractura especificada del pie, excepto el tobillo', 'category', false, false, 'CIE-11'),
('ND13.Z', 'Fractura del pie, excepto el tobillo, sin especificación', 'category', false, false, 'CIE-11'),
('ND14', 'Luxación, distensión o esguince de articulaciones o ligamentos a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND14.0', 'Luxación de la articulación del tobillo', 'category', false, false, 'CIE-11'),
('ND14.1', 'Luxación del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.10', 'Luxación de la articulación metatarsofalángica del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.11', 'Luxación de la articulación interfalángica del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.1Z', 'Luxación del primer dedo del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND14.2', 'Luxación de otro dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.20', 'Luxación de la articulación metatarsofalángica de dedo menor del pie', 'category', false, false, 'CIE-11'),
('ND14.21', 'Luxación de la articulación interfalángica de dedo menor del pie', 'category', false, false, 'CIE-11'),
('ND14.2Y', 'Luxación de otro dedo especificado del pie', 'category', false, false, 'CIE-11'),
('ND14.2Z', 'Luxación de otro dedo del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND14.3', 'Luxación de la articulación del tarso', 'category', false, false, 'CIE-11'),
('ND14.4', 'Luxación de la articulación tarsometatarsiana', 'category', false, false, 'CIE-11'),
('ND14.5', 'Rotura de ligamentos a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND14.6', 'Luxación de otras partes o de partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND14.7', 'Distensión o esguince del tobillo', 'category', false, false, 'CIE-11'),
('ND14.70', 'Distensión o esguince del ligamento calcaneoperoneo', 'category', false, false, 'CIE-11'),
('ND14.71', 'Distensión o esguince del ligamento deltoideo', 'category', false, false, 'CIE-11'),
('ND14.72', 'Distensión o esguince del ligamento tibioperoneo', 'category', false, false, 'CIE-11'),
('ND14.73', 'Distensión o esguince de otros ligamentos del tobillo', 'category', false, false, 'CIE-11'),
('ND14.7Z', 'Distensión o esguince de tobillo, sin especificación', 'category', false, false, 'CIE-11'),
('ND14.8', 'Distensión o esguince de otro dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.80', 'Esguince o distensión de la articulación metatarsofalángica de un dedo menor del pie', 'category', false, false, 'CIE-11'),
('ND14.81', 'Esguince o distensión de la articulación interfalángica de un dedo menor del pie', 'category', false, false, 'CIE-11'),
('ND14.8Y', 'Otra distensión o esguince especificado de dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.8Z', 'Distensión o esguince de otro dedo del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND14.9', 'Distensión o esguince del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.90', 'Esguince o distensión de la articulación metatarsofalángica del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.91', 'Esguince o distensión de la articulación interfalángica del primer dedo del pie', 'category', false, false, 'CIE-11'),
('ND14.9Z', 'Distensión o esguince del primer dedo del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND14.A', 'Distensión o esguince de otras partes o de partes no especificadas del pie', 'category', false, false, 'CIE-11'),
('ND14.Y', 'Otra luxación, distensión o esguince especificado de articulaciones o ligamentos a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND14.Z', 'Luxación, distensión o esguince de articulaciones o ligamentos a nivel del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND15', 'Traumatismo en los nervios a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND15.0', 'Traumatismo en el nervio plantar lateral', 'category', false, false, 'CIE-11'),
('ND15.1', 'Traumatismo en el nervio plantar interno', 'category', false, false, 'CIE-11'),
('ND15.2', 'Traumatismo en el nervio peroneo profundo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND15.3', 'Traumatismo en el nervio sensorial cutáneo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND15.4', 'Traumatismo en múltiples nervios a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND15.Y', 'Otro traumatismo especificado en los nervios a nivel del tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND15.Z', 'Traumatismo en los nervios a nivel del tobillo o el pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND16', 'Traumatismo en los vasos sanguíneos a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND16.0', 'Traumatismo en la arteria dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.00', 'Desgarro en la arteria dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.0Y', 'Otro traumatismo especificado en la arteria dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.0Z', 'Traumatismo en la arteria dorsal del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND16.1', 'Traumatismo en la arteria plantar del pie', 'category', false, false, 'CIE-11'),
('ND16.10', 'Desgarro de la arteria plantar del pie', 'category', false, false, 'CIE-11'),
('ND16.1Y', 'Otro traumatismo especificado en la arteria plantar del pie', 'category', false, false, 'CIE-11'),
('ND16.1Z', 'Traumatismo en la arteria plantar del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND16.2', 'Lesión en la vena dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.20', 'Desgarro de la vena dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.2Y', 'Otra lesión especificada en la vena dorsal del pie', 'category', false, false, 'CIE-11'),
('ND16.2Z', 'Lesión en la vena dorsal del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND16.3', 'Traumatismo en múltiples vasos sanguíneos a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND16.Y', 'Traumatismo en otros vasos sanguíneos especificados a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND16.Z', 'Traumatismo en los vasos sanguíneos a nivel del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND17', 'Traumatismo en tendón, fascia o músculo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.0', 'Traumatismo en tendón, fascia o músculo flexor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.00', 'Distensión o esguince de tendón, fascia o músculo flexor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.01', 'Desgarro de tendón, fascia o músculo flexor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.0Y', 'Otro traumatismo especificado en tendón, fascia o músculo flexor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.0Z', 'Traumatismo en tendón, fascia o músculo flexor largo del dedo a nivel del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND17.1', 'Traumatismo en tendón, fascia o músculo extensor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.10', 'Esguince o distensión de tendón, fascia o músculo extensor largo del dedo del pie a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.11', 'Desgarro de tendón, fascia o músculo extensor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.1Y', 'Otro traumatismo en tendón, fascia o músculo extensor largo del dedo a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.1Z', 'Traumatismo en tendón, fascia o músculo extensor largo del dedo a nivel del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND17.2', 'Traumatismo en tendón, fascia o músculo intrínseco a nivel del tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND17.20', 'Distensión o esguince de músculo intrínseco, tendón, o fascia a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.21', 'Desgarro de tendón, fascia o músculo intrínseco a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.2Y', 'Otro traumatismo especificado en tendón, fascia o músculo intrínseco a nivel del tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND17.2Z', 'Traumatismo en tendón, fascia o músculo intrínseco a nivel del tobillo o el pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND17.3', 'Traumatismo en múltiples músculos o tendones a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.Y', 'Traumatismo en otro tendón, fascia o músculo especificado a nivel del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND17.Z', 'Traumatismo en tendón, fascia o músculo a nivel del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND18', 'Traumatismo por aplastamiento del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND18.0', 'Traumatismo por aplastamiento del tobillo', 'category', false, false, 'CIE-11'),
('ND18.1', 'Traumatismo por aplastamiento de dedo del pie', 'category', false, false, 'CIE-11'),
('ND18.2', 'Traumatismo por aplastamiento de otra parte del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND18.Z', 'Traumatismo por aplastamiento del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND19', 'Amputación traumática del tobillo o del pie', 'category', false, false, 'CIE-11'),
('ND19.0', 'Amputación traumática del pie derecho a nivel del tobillo', 'category', false, false, 'CIE-11'),
('ND19.1', 'Amputación traumática del pie izquierdo a nivel del tobillo', 'category', false, false, 'CIE-11'),
('ND19.2', 'Amputación traumática del pie a nivel del tobillo, bilateral', 'category', false, false, 'CIE-11'),
('ND19.3', 'Amputación traumática del pie derecho a nivel del metatarso', 'category', false, false, 'CIE-11'),
('ND19.4', 'Amputación traumática del pie izquierdo a nivel del metatarso', 'category', false, false, 'CIE-11'),
('ND19.5', 'Amputación traumática del pie a nivel metatarsiano, bilateral', 'category', false, false, 'CIE-11'),
('ND19.6', 'Amputación traumática de un dedo del pie', 'category', false, false, 'CIE-11'),
('ND19.7', 'Amputación traumática de dos o varios dedos del pie', 'category', false, false, 'CIE-11'),
('ND19.8', 'Amputación traumática de otras partes del pie', 'category', false, false, 'CIE-11'),
('ND19.Z', 'Amputación traumática del tobillo o del pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND1A', 'Traumatismos múltiples en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND1Y', 'Otros traumatismos especificados en el tobillo o el pie', 'category', false, false, 'CIE-11'),
('ND1Z', 'Traumatismos en el tobillo o el pie, sin especificación', 'category', false, false, 'CIE-11'),
('ND30', 'Traumatismos superficiales que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND31', 'Heridas abiertas que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND32', 'Fracturas que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND33', 'Luxaciones, distensiones o esguinces que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND34', 'Traumatismos por aplastamiento que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND35', 'Amputaciones traumáticas que afectan múltiples regiones del cuerpo', 'category', false, false, 'CIE-11'),
('ND36', 'Otros traumatismos que afectan múltiples regiones del cuerpo, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('ND37', 'Traumatismos múltiples no especificados', 'category', false, false, 'CIE-11'),
('ND50', 'Fractura de la columna vertebral, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND51', 'Otros traumatismos en la columna o el tronco, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND51.0', 'Luxación, esguince o distensión de ligamento o articulación no especificada del tronco', 'category', false, false, 'CIE-11'),
('ND51.1', 'Traumatismo en nervio, raíz de nervio espinal o plexo del tronco no especificado', 'category', false, false, 'CIE-11'),
('ND51.2', 'Traumatismo en la médula espinal, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND51.3', 'Traumatismo en tendón, fascia o músculo no especificado del tronco', 'category', false, false, 'CIE-11'),
('ND51.4', 'Traumatismo por aplastamiento de la columna vertebral o del tronco, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND51.Y', 'Otros traumatismos especificados en la columna o el tronco, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND51.Z', 'Traumatismos en la columna o el tronco, sin especificación, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND52', 'Fractura de brazo, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND53', 'Otros traumatismos en el brazo, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND53.0', 'Traumatismo por aplastamiento del brazo, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND53.Y', 'Otras lesiones especificadas del brazo, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND54', 'Fractura de pierna, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND55', 'Otros traumatismos en la pierna, nivel no especificado', 'category', false, false, 'CIE-11'),
('ND56', 'Traumatismo en región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.0', 'Traumatismo superficial en región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.1', 'Herida abierta de región del cuerpo no especificada', 'category', false, false, 'CIE-11'),
('ND56.2', 'Fractura de región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.3', 'Luxación, distensión o esguince de parte del cuerpo no especificada', 'category', false, false, 'CIE-11'),
('ND56.4', 'Traumatismo en un nervio de región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.5', 'Traumatismo en vaso sanguíneo de región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.6', 'Traumatismo en tendones o músculos de región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.7', 'Traumatismo por aplastamiento de región del cuerpo no especificada', 'category', false, false, 'CIE-11'),
('ND56.8', 'Amputación traumática de parte no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.9', 'Traumatismo que complica el embarazo', 'category', false, false, 'CIE-11'),
('ND56.Y', 'Otro traumatismo especificado de región no especificada del cuerpo', 'category', false, false, 'CIE-11'),
('ND56.Z', 'Traumatismo no especificado de parte del tronco, extremidad o región del cuerpo', 'category', false, false, 'CIE-11'),
('ND57', 'Efecto secundario de trauma', 'category', false, false, 'CIE-11'),
('ND5Y', 'Otros traumatismos especificados de una parte no especificada del tronco, miembro o región del cuerpo', 'category', false, false, 'CIE-11'),
('ND5Z', 'Traumatismos de una parte no especificada del tronco, miembro o región del cuerpo, sin especificación', 'category', false, false, 'CIE-11'),
('ND70', 'Cuerpo extraño en la parte externa del ojo', 'category', false, false, 'CIE-11'),
('ND70.0', 'Cuerpo extraño en la córnea', 'category', false, false, 'CIE-11'),
('ND70.1', 'Cuerpo extraño en el saco conjuntival', 'category', false, false, 'CIE-11'),
('ND70.2', 'Cuerpo extraño en múltiples partes de la parte externa del ojo', 'category', false, false, 'CIE-11'),
('ND70.Y', 'Cuerpo extraño en otra parte externa especificada del ojo', 'category', false, false, 'CIE-11'),
('ND70.Z', 'Cuerpo extraño en parte externa del ojo, sin especificación', 'category', false, false, 'CIE-11'),
('ND71', 'Cuerpo extraño en el oído', 'category', false, false, 'CIE-11'),
('ND72', 'Cuerpo extraño en las vías respiratorias', 'category', false, false, 'CIE-11'),
('ND72.0', 'Cuerpo extraño en seno paranasal', 'category', false, false, 'CIE-11'),
('ND72.1', 'Cuerpo extraño en orificio nasal', 'category', false, false, 'CIE-11'),
('ND72.2', 'Cuerpo extraño en la faringe', 'category', false, false, 'CIE-11'),
('ND72.20', 'Asfixia por moco en la nasofaringe', 'category', false, false, 'CIE-11'),
('ND72.2Y', 'Otro cuerpo extraño especificado en la faringe', 'category', false, false, 'CIE-11'),
('ND72.2Z', 'Cuerpo extraño en la faringe, sin especificación', 'category', false, false, 'CIE-11'),
('ND72.3', 'Cuerpo extraño en la laringe', 'category', false, false, 'CIE-11'),
('ND72.4', 'Cuerpo extraño en la tráquea', 'category', false, false, 'CIE-11'),
('ND72.5', 'Cuerpo extraño en bronquio', 'category', false, false, 'CIE-11'),
('ND72.6', 'Cuerpo extraño en múltiples partes de las vías respiratorias', 'category', false, false, 'CIE-11'),
('ND72.Y', 'Cuerpo extraño en otras partes de las vías respiratorias', 'category', false, false, 'CIE-11'),
('ND72.Z', 'Cuerpo extraño en las vías respiratorias, no especificado', 'category', false, false, 'CIE-11'),
('ND73', 'Cuerpo extraño en el tubo digestivo', 'category', false, false, 'CIE-11'),
('ND73.0', 'Cuerpo extraño en la boca', 'category', false, false, 'CIE-11'),
('ND73.1', 'Cuerpo extraño en el esófago', 'category', false, false, 'CIE-11'),
('ND73.2', 'Cuerpo extraño en el estómago', 'category', false, false, 'CIE-11'),
('ND73.20', 'Tricobezoar', 'category', false, false, 'CIE-11'),
('ND73.2Y', 'Otro cuerpo extraño especificado en el estómago', 'category', false, false, 'CIE-11'),
('ND73.2Z', 'Cuerpo extraño en el estómago, sin especificación', 'category', false, false, 'CIE-11'),
('ND73.3', 'Cuerpo extraño en el intestino delgado', 'category', false, false, 'CIE-11'),
('ND73.4', 'Cuerpo extraño en el colon', 'category', false, false, 'CIE-11'),
('ND73.5', 'Cuerpo extraño en el ano o el recto', 'category', false, false, 'CIE-11'),
('ND73.Y', 'Cuerpo extraño en otra parte especificada del tubo digestivo', 'category', false, false, 'CIE-11'),
('ND73.Z', 'Cuerpo extraño en el tubo digestivo, sin especificación', 'category', false, false, 'CIE-11'),
('ND74', 'Cuerpo extraño en el aparato genitourinario', 'category', false, false, 'CIE-11'),
('ND74.0', 'Cuerpo extraño en la uretra', 'category', false, false, 'CIE-11'),
('ND74.1', 'Cuerpo extraño en la vejiga', 'category', false, false, 'CIE-11'),
('ND74.2', 'Cuerpo extraño en la vulva o la vagina', 'category', false, false, 'CIE-11'),
('ND74.3', 'Cuerpo extraño en el útero, cualquier parte', 'category', false, false, 'CIE-11'),
('ND74.Y', 'Otro cuerpo extraño especificado en el aparato genitourinario', 'category', false, false, 'CIE-11'),
('ND74.Z', 'Cuerpo extraño en el aparato genitourinario, sin especificación', 'category', false, false, 'CIE-11'),
('ND7Z', 'Efectos de cuerpo extraño que penetra por orificio natural, sin especificación', 'category', false, false, 'CIE-11'),
('ND90', 'Quemadura en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.0', 'Quemadura epidérmica en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.1', 'Quemadura superficial de espesor parcial en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.2', 'Quemadura profunda de espesor parcial en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.3', 'Quemadura de espesor total en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.4', 'Quemadura profunda o compleja de espesor total en la cabeza o el cuello, excepto la cara', 'category', false, false, 'CIE-11'),
('ND90.Z', 'Quemadura en la cabeza o el cuello, excepto la cara, sin especificación', 'category', false, false, 'CIE-11'),
('ND91', 'Quemadura en la cara excepto el ojo o los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.0', 'Quemadura epidérmica en la cara, excepto el ojo y los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.1', 'Quemadura superficial de espesor parcial en la cara, excepto el ojo y los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.2', 'Quemadura parcial de espesor profundo en la cara, excepto el ojo y los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.3', 'Quemadura de espesor total en la cara, excepto el ojo y los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.4', 'Quemadura profunda o compleja de espesor total en la cara, excepto el ojo y los anexos oculares', 'category', false, false, 'CIE-11'),
('ND91.Z', 'Quemadura de la cara excepto el ojo o los anexos oculares, sin especificación', 'category', false, false, 'CIE-11'),
('ND92', 'Quemadura en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.0', 'Quemadura epidérmica en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.00', 'Quemadura epidérmica en la mama', 'category', false, false, 'CIE-11'),
('ND92.01', 'Quemadura epidérmica en la pared torácica', 'category', false, false, 'CIE-11'),
('ND92.02', 'Quemadura epidérmica en la pared abdominal', 'category', false, false, 'CIE-11'),
('ND92.03', 'Quemadura epidérmica en la espalda, cualquier parte', 'category', false, false, 'CIE-11'),
('ND92.0Y', 'Otra quemadura epidérmica especificada en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.0Z', 'Quemadura epidérmica en el tronco, excepto el perineo o los genitales, sin especificación', 'category', false, false, 'CIE-11'),
('ND92.1', 'Quemadura superficial de espesor parcial en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.2', 'Quemadura profunda de espesor parcial en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.3', 'Quemadura de espesor total en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.4', 'Quemadura profunda o compleja de espesor total en el tronco, excepto el perineo o los genitales', 'category', false, false, 'CIE-11'),
('ND92.Z', 'Quemadura en el tronco, excepto el perineo o los genitales, sin especificación', 'category', false, false, 'CIE-11'),
('ND93', 'Quemadura del perineo o de los genitales', 'category', false, false, 'CIE-11'),
('ND93.0', 'Quemadura epidérmica en el perineo o los genitales', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;