BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('6D72.12', 'Trastorno amnésico debido a otra sustancia psicoactiva especificada, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D72.13', 'Trastorno amnésico por uso de inhalantes volátiles', 'category', false, false, 'CIE-11'),
('6D72.Y', 'Trastorno amnésico, otra causa especificada', 'category', false, false, 'CIE-11'),
('6D72.Z', 'Trastorno amnésico, causa desconocida o no especificada', 'category', false, false, 'CIE-11'),
('6D80', 'Demencia debida a la enfermedad de Alzheimer', 'category', false, false, 'CIE-11'),
('6D80.0', 'Demencia debida a la enfermedad de Alzheimer de inicio temprano', 'category', false, false, 'CIE-11'),
('6D80.1', 'Demencia debida a la enfermedad de Alzheimer de inicio tardío', 'category', false, false, 'CIE-11'),
('6D80.2', 'Demencia debida a la enfermedad de Alzheimer, de tipo mixto, con enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('6D80.3', 'Demencia debida a la enfermedad de Alzheimer, de tipo mixto, con otras etiologías no vasculares', 'category', false, false, 'CIE-11'),
('6D80.Z', 'Demencia debida a la enfermedad de Alzheimer, inicio desconocido o no especificado', 'category', false, false, 'CIE-11'),
('6D81', 'Demencia debida a una enfermedad cerebrovascular', 'category', false, false, 'CIE-11'),
('6D82', 'Demencia debida a la enfermedad por cuerpos de Lewy', 'category', false, false, 'CIE-11'),
('6D83', 'Demencia frontotemporal', 'category', false, false, 'CIE-11'),
('6D84', 'Demencia por sustancias psicoactivas, incluidos los medicamentos', 'category', false, false, 'CIE-11'),
('6D84.0', 'Demencia por uso de alcohol', 'category', false, false, 'CIE-11'),
('6D84.1', 'Demencia por uso de sedantes, hipnóticos o ansiolíticos', 'category', false, false, 'CIE-11'),
('6D84.2', 'Demencia por uso de inhalantes volátiles', 'category', false, false, 'CIE-11'),
('6D84.Y', 'Demencia debida otras sustancias psicoactivas especificadas', 'category', false, false, 'CIE-11'),
('6D85', 'Demencia debida a enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('6D85.0', 'Demencia debida a la enfermedad de Parkinson', 'category', false, false, 'CIE-11'),
('6D85.1', 'Demencia debida a la enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('6D85.2', 'Demencia por exposición a metales pesados y otras toxinas', 'category', false, false, 'CIE-11'),
('6D85.3', 'Demencia por el virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('6D85.4', 'Demencia debida a esclerosis múltiple', 'category', false, false, 'CIE-11'),
('6D85.5', 'Demencia debida a enfermedades priónicas', 'category', false, false, 'CIE-11'),
('6D85.6', 'Demencia debida a hidrocefalia de presión normal', 'category', false, false, 'CIE-11'),
('6D85.7', 'Demencia debida a un traumatismo en la cabeza', 'category', false, false, 'CIE-11'),
('6D85.8', 'Demencia debida a pelagra', 'category', false, false, 'CIE-11'),
('6D85.9', 'Demencia debida al síndrome de Down', 'category', false, false, 'CIE-11'),
('6D85.Y', 'Demencia debida a otras enfermedades especificadas clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('6D86', 'Trastornos psicológicos o del comportamiento en la demencia', 'category', false, false, 'CIE-11'),
('6D86.0', 'Síntomas psicóticos en la demencia', 'category', false, false, 'CIE-11'),
('6D86.1', 'Síntomas del estado de ánimo en la demencia', 'category', false, false, 'CIE-11'),
('6D86.2', 'Síntomas de ansiedad en la demencia', 'category', false, false, 'CIE-11'),
('6D86.3', 'Apatía en la demencia', 'category', false, false, 'CIE-11'),
('6D86.4', 'Agitación o agresión en la demencia', 'category', false, false, 'CIE-11'),
('6D86.5', 'Desinhibición en la demencia', 'category', false, false, 'CIE-11'),
('6D86.6', 'Persona vagabunda con demencia', 'category', false, false, 'CIE-11'),
('6D86.Y', 'Otros trastornos psicológicos o del comportamiento especificados en la demencia', 'category', false, false, 'CIE-11'),
('6D86.Z', 'Trastornos psicológicos o del comportamiento en la demencia, sin especificación', 'category', false, false, 'CIE-11'),
('6D8Y', 'Demencia, otra causa especificada', 'category', false, false, 'CIE-11'),
('6D8Z', 'Demencia, causa desconocida o sin especificación', 'category', false, false, 'CIE-11'),
('6E0Y', 'Otros trastornos neurocognitivos especificados', 'category', false, false, 'CIE-11'),
('6E0Z', 'Trastornos neurocognitivos, sin especificación', 'category', false, false, 'CIE-11'),
('6E20', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, sin síntomas psicóticos', 'category', false, false, 'CIE-11'),
('6E21', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, con síntomas psicóticos', 'category', false, false, 'CIE-11'),
('6E2Z', 'Trastornos mentales o del comportamiento asociados con el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('6E40', 'Factores psicológicos o del comportamiento que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.0', 'Trastorno mental que afecta a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.1', 'Síntomas psicológicos que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.2', 'Rasgos de personalidad o estilo de afrontamiento que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.3', 'Comportamientos de salud inadaptados que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.4', 'Respuesta fisiológica relacionada con el estrés que afecta a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.Y', 'Otros factores psicológicos o del comportamiento especificados que afectan a enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E40.Z', 'Factores psicológicos o del comportamiento que afectan a enfermedades o trastornos clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('6E60', 'Síndrome de neurodesarrollo secundario', 'category', false, false, 'CIE-11'),
('6E60.0', 'Síndrome secundario del habla o lenguaje', 'category', false, false, 'CIE-11'),
('6E60.Y', 'Otro síndrome secundario del neurodesarrollo especificado', 'category', false, false, 'CIE-11'),
('6E60.Z', 'Síndrome secundario del neurodesarrollo, sin especificación', 'category', false, false, 'CIE-11'),
('6E61', 'Síndrome psicótico secundario', 'category', false, false, 'CIE-11'),
('6E61.0', 'Síndrome psicótico secundario, con alucinaciones', 'category', false, false, 'CIE-11'),
('6E61.1', 'Síndrome psicótico secundario, con delirios', 'category', false, false, 'CIE-11'),
('6E61.2', 'Síndrome psicótico secundario, con alucinaciones y delirios', 'category', false, false, 'CIE-11'),
('6E61.3', 'Síndrome psicótico secundario, con síntomas no especificados', 'category', false, false, 'CIE-11'),
('6E62', 'Síndrome secundario del estado del ánimo', 'category', false, false, 'CIE-11'),
('6E62.0', 'Síndrome secundario del estado del ánimo, con síntomas depresivos', 'category', false, false, 'CIE-11'),
('6E62.1', 'Síndrome secundario afectivo, con síntomas maníacos', 'category', false, false, 'CIE-11'),
('6E62.2', 'Síndrome secundario del estado del ánimo, con síntomas mixtos', 'category', false, false, 'CIE-11'),
('6E62.3', 'Síndrome secundario del estado del ánimo, con síntomas no especificados', 'category', false, false, 'CIE-11'),
('6E63', 'Síndrome de ansiedad secundario', 'category', false, false, 'CIE-11'),
('6E64', 'Síndrome secundario obsesivo-compulsivo o relacionado', 'category', false, false, 'CIE-11'),
('6E65', 'Síndrome disociativo secundario', 'category', false, false, 'CIE-11'),
('6E66', 'Síndrome secundario de control de los impulsos', 'category', false, false, 'CIE-11'),
('6E67', 'Síndrome neurocognitivo secundario', 'category', false, false, 'CIE-11'),
('6E68', 'Cambio secundario de la personalidad', 'category', false, false, 'CIE-11'),
('6E69', 'Síndrome de catatonia secundaria', 'category', false, false, 'CIE-11'),
('6E6Y', 'Síndromes secundarios mentales o del comportamiento especificados asociados con enfermedades o trastornos clasificados en otra parte', 'category', false, false, 'CIE-11'),
('6E6Z', 'Síndromes secundarios mentales o del comportamiento asociados con enfermedades o trastornos clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('6E8Y', 'Otros trastornos mentales, del comportamiento o del neurodesarrollo especificados', 'category', false, false, 'CIE-11'),
('6E8Z', 'Trastornos mentales, del comportamiento o del neurodesarrollo, sin especificación', 'category', false, false, 'CIE-11'),
('7A00', 'Insomnio crónico', 'category', false, false, 'CIE-11'),
('7A01', 'Insomnio de corta duración', 'category', false, false, 'CIE-11'),
('7A0Z', 'Trastornos de insomnio, sin especificación', 'category', false, false, 'CIE-11'),
('7A20', 'Narcolepsia', 'category', false, false, 'CIE-11'),
('7A20.0', 'Narcolepsia, tipo 1', 'category', false, false, 'CIE-11'),
('7A20.1', 'Narcolepsia, tipo 2', 'category', false, false, 'CIE-11'),
('7A20.Z', 'Narcolepsia, sin especificación', 'category', false, false, 'CIE-11'),
('7A21', 'Hipersomnia idiopática', 'category', false, false, 'CIE-11'),
('7A22', 'Síndrome de Kleine-Levin', 'category', false, false, 'CIE-11'),
('7A23', 'Hipersomnia debida a un problema médico', 'category', false, false, 'CIE-11'),
('7A24', 'Hipersomnia debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A25', 'Hipersomnia asociada con un trastorno mental', 'category', false, false, 'CIE-11'),
('7A26', 'Síndrome de sueño insuficiente', 'category', false, false, 'CIE-11'),
('7A2Y', 'Otros trastornos de hipersomnolencia especificados', 'category', false, false, 'CIE-11'),
('7A2Z', 'Trastornos de hipersomnolencia, sin especificación', 'category', false, false, 'CIE-11'),
('7A40', 'Apneas centrales del sueño', 'category', false, false, 'CIE-11'),
('7A40.0', 'Apnea central primaria del sueño', 'category', false, false, 'CIE-11'),
('7A40.1', 'Apnea central del sueño primaria de la infancia', 'category', false, false, 'CIE-11'),
('7A40.2', 'Apnea central del sueño primaria de la prematuridad', 'category', false, false, 'CIE-11'),
('7A40.3', 'Apnea central del sueño debida a respiración de Cheyne-Stokes', 'category', false, false, 'CIE-11'),
('7A40.4', 'Apnea central del sueño debida a un problema médico sin respiración de Cheyne-Stokes', 'category', false, false, 'CIE-11'),
('7A40.5', 'Apnea central del sueño debida a respiración periódica a grandes alturas', 'category', false, false, 'CIE-11'),
('7A40.6', 'Apnea central del sueño debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A40.7', 'Apnea central del sueño que aparece durante un tratamiento', 'category', false, false, 'CIE-11'),
('7A40.Y', 'Otras apneas centrales del sueño especificadas', 'category', false, false, 'CIE-11'),
('7A40.Z', 'Apneas centrales del sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A41', 'Apnea obstructiva del sueño', 'category', false, false, 'CIE-11'),
('7A42', 'Trastornos de hipoventilación o hipoxemia relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A42.0', 'Síndrome de hipoventilación en la obesidad', 'category', false, false, 'CIE-11'),
('7A42.1', 'Hipoventilación central alveolar congénita relacionada con el sueño', 'category', false, false, 'CIE-11'),
('7A42.2', 'Hipoventilación central no congénita con anomalías hipotalámicas', 'category', false, false, 'CIE-11'),
('7A42.3', 'Hipoventilación alveolar central idiopática', 'category', false, false, 'CIE-11'),
('7A42.4', 'Hipoventilación relacionada con el sueño debida a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A42.5', 'Hipoventilación durante el sueño debida a un problema médico', 'category', false, false, 'CIE-11'),
('7A42.6', 'Hipoxemia relacionada con el sueño debida a una afección médica', 'category', false, false, 'CIE-11'),
('7A42.Y', 'Otros trastornos especificados de hipoventilación o hipoxemia relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A42.Z', 'Trastornos de hipoventilación o hipoxemia relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A4Y', 'Otros trastornos respiratorios especificados relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A4Z', 'Trastornos respiratorios relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7A60', 'Trastorno por retraso de la fase del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A61', 'Trastorno por adelanto de la fase del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A62', 'Trastorno por ritmo irregular del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7A63', 'Trastorno por ritmo del sueño y la vigilia distinto de 24 horas', 'category', false, false, 'CIE-11'),
('7A64', 'Trastorno del ritmo circadiano del sueño y la vigilia debido al trabajo por turnos', 'category', false, false, 'CIE-11'),
('7A65', 'Trastorno del ritmo circadiano del sueño y la vigilia, del tipo por cambio de zona horaria', 'category', false, false, 'CIE-11'),
('7A6Z', 'Trastornos del ciclo circadiano del sueño y la vigilia, sin especificación', 'category', false, false, 'CIE-11'),
('7A80', 'Síndrome de las piernas inquietas', 'category', false, false, 'CIE-11'),
('7A81', 'Trastorno por movimientos periódicos de las extremidades', 'category', false, false, 'CIE-11'),
('7A82', 'Calambres en las piernas durante el sueño', 'category', false, false, 'CIE-11'),
('7A83', 'Bruxismo durante el sueño', 'category', false, false, 'CIE-11'),
('7A84', 'Movimientos rítmicos durante el sueño', 'category', false, false, 'CIE-11'),
('7A85', 'Mioclonías benignas del sueño en la lactancia', 'category', false, false, 'CIE-11'),
('7A86', 'Mioclonía propioespinal al inicio del sueño', 'category', false, false, 'CIE-11'),
('7A87', 'Movimientos anormales durante el sueño debido a un problema médico', 'category', false, false, 'CIE-11'),
('7A88', 'Trastorno del movimiento relacionado con el sueño debido a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7A8Y', 'Otros trastornos especificados del movimiento relacionados con el sueño', 'category', false, false, 'CIE-11'),
('7A8Z', 'Trastornos del movimiento relacionados con el sueño, sin especificación', 'category', false, false, 'CIE-11'),
('7B00', 'Trastornos del despertar del sueño no REM', 'category', false, false, 'CIE-11'),
('7B00.0', 'Despertares confusionales', 'category', false, false, 'CIE-11'),
('7B00.1', 'Trastorno de sonambulismo', 'category', false, false, 'CIE-11'),
('7B00.2', 'Terror del sueño', 'category', false, false, 'CIE-11'),
('7B00.3', 'Trastorno de la conducta alimentaria relacionado con el sueño', 'category', false, false, 'CIE-11'),
('7B00.Y', 'Otros trastornos del despertar del sueño no REM', 'category', false, false, 'CIE-11'),
('7B00.Z', 'Trastornos del despertar del sueño no REM, sin especificación', 'category', false, false, 'CIE-11'),
('7B01', 'Parasomnias relacionadas con el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.0', 'Trastorno del comportamiento durante el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.1', 'Parálisis del sueño aislada recurrente', 'category', false, false, 'CIE-11'),
('7B01.2', 'Pesadillas', 'category', false, false, 'CIE-11'),
('7B01.Y', 'Otras parasomnias especificadas relacionadas con el sueño REM', 'category', false, false, 'CIE-11'),
('7B01.Z', 'Parasomnias relacionadas con el sueño REM, sin especificación', 'category', false, false, 'CIE-11'),
('7B02', 'Otras parasomnias', 'category', false, false, 'CIE-11'),
('7B02.0', 'Síndrome hipnagógico de la cabeza explosiva', 'category', false, false, 'CIE-11'),
('7B02.1', 'Alucinaciones durante el sueño', 'category', false, false, 'CIE-11'),
('7B02.2', 'Trastorno de parasomnia debido a un problema médico', 'category', false, false, 'CIE-11'),
('7B02.3', 'Trastorno de parasomnia debido a un medicamento o sustancia', 'category', false, false, 'CIE-11'),
('7B0Y', 'Otros trastornos especificados de parasomnia', 'category', false, false, 'CIE-11'),
('7B0Z', 'Trastornos de parasomnia, sin especificación', 'category', false, false, 'CIE-11'),
('7B2Y', 'Otros trastornos especificados del sueño y la vigilia', 'category', false, false, 'CIE-11'),
('7B2Z', 'Trastornos del sueño y la vigilia, sin especificación', 'category', false, false, 'CIE-11'),
('8A00', 'Parkinsonismo', 'category', false, false, 'CIE-11'),
('8A00.0', 'Enfermedad de Parkinson', 'category', false, false, 'CIE-11'),
('8A00.00', 'Enfermedad de Parkinson esporádica', 'category', false, false, 'CIE-11'),
('8A00.01', 'Enfermedad de Parkinson familiar', 'category', false, false, 'CIE-11'),
('8A00.0Y', 'Otra enfermedad de Parkinson especificada', 'category', false, false, 'CIE-11'),
('8A00.0Z', 'Enfermedad de Parkinson, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.1', 'Parkinsonismo atípico', 'category', false, false, 'CIE-11'),
('8A00.10', 'Parálisis supranuclear progresiva', 'category', false, false, 'CIE-11'),
('8A00.1Y', 'Otro parkinsonismo atípico especificado', 'category', false, false, 'CIE-11'),
('8A00.1Z', 'Parkinsonismo atípico, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.2', 'Parkinsonismo secundario', 'category', false, false, 'CIE-11'),
('8A00.20', 'Parkinsonismo debido a trastornos degenerativos hereditarios', 'category', false, false, 'CIE-11'),
('8A00.21', 'Síndrome de hemiatrofia con hemiparkinsonismo', 'category', false, false, 'CIE-11'),
('8A00.22', 'Parkinsonismo infeccioso o post infeccioso', 'category', false, false, 'CIE-11'),
('8A00.23', 'Parkinsonismo vascular', 'category', false, false, 'CIE-11'),
('8A00.24', 'Parkinsonismo provocado por medicamentos', 'category', false, false, 'CIE-11'),
('8A00.25', 'Parkinsonismo postraumático', 'category', false, false, 'CIE-11'),
('8A00.26', 'Parkinsonismo por lesiones estructurales', 'category', false, false, 'CIE-11'),
('8A00.2Y', 'Otro parkinsonismo secundario especificado', 'category', false, false, 'CIE-11'),
('8A00.2Z', 'Parkinsonismo secundario, sin especificación', 'category', false, false, 'CIE-11'),
('8A00.3', 'Parkinsonismo funcional', 'category', false, false, 'CIE-11'),
('8A00.Y', 'Otro parkinsonismo especificado', 'category', false, false, 'CIE-11'),
('8A00.Z', 'Parkinsonismo, sin especificación', 'category', false, false, 'CIE-11'),
('8A01', 'Trastornos coreiformes', 'category', false, false, 'CIE-11'),
('8A01.0', 'Corea hereditaria benigna', 'category', false, false, 'CIE-11'),
('8A01.1', 'Corea secundaria', 'category', false, false, 'CIE-11'),
('8A01.10', 'Enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('8A01.11', 'Corea por afecciones similares a la enfermedad de Huntington', 'category', false, false, 'CIE-11'),
('8A01.12', 'Corea debida a atrofia dentato-rubro-pálido-luisiana', 'category', false, false, 'CIE-11'),
('8A01.13', 'Corea por enfermedad de Wilson', 'category', false, false, 'CIE-11'),
('8A01.14', 'Corea por causas infecciosas o parainfecciosas', 'category', false, false, 'CIE-11'),
('8A01.15', 'Corea por lupus eritematoso sistémico', 'category', false, false, 'CIE-11'),
('8A01.16', 'Corea provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8A01.1Y', 'Otra corea secundaria especificada', 'category', false, false, 'CIE-11'),
('8A01.1Z', 'Corea secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A01.2', 'Hemicorea o hemibalismo', 'category', false, false, 'CIE-11'),
('8A01.20', 'Hemicorea', 'category', false, false, 'CIE-11'),
('8A01.21', 'Balismo', 'category', false, false, 'CIE-11'),
('8A01.22', 'Hemibalismo', 'category', false, false, 'CIE-11'),
('8A01.Y', 'Otros trastornos coreiformes especificados', 'category', false, false, 'CIE-11'),
('8A01.Z', 'Trastornos coreiformes, sin especificación', 'category', false, false, 'CIE-11'),
('8A02', 'Distonías', 'category', false, false, 'CIE-11'),
('8A02.0', 'Distonía primaria', 'category', false, false, 'CIE-11'),
('8A02.00', 'Blefaroespasmo esencial benigno', 'category', false, false, 'CIE-11'),
('8A02.0Y', 'Otra distonía primaria especificada', 'category', false, false, 'CIE-11'),
('8A02.0Z', 'Distonía primaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A02.1', 'Distonía secundaria', 'category', false, false, 'CIE-11'),
('8A02.10', 'Distonía provocada por medicamentos', 'category', false, false, 'CIE-11'),
('8A02.11', 'Distonía combinada', 'category', false, false, 'CIE-11'),
('8A02.12', 'Distonía asociada a trastornos degenerativos hereditarios', 'category', false, false, 'CIE-11'),
('8A02.1Y', 'Otra distonía secundaria especificada', 'category', false, false, 'CIE-11'),
('8A02.1Z', 'Distonía secundaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A02.2', 'Distonía paroxística', 'category', false, false, 'CIE-11'),
('8A02.3', 'Distonía o espasmos funcionales', 'category', false, false, 'CIE-11'),
('8A02.Y', 'Otros trastornos distónicos especificados', 'category', false, false, 'CIE-11'),
('8A02.Z', 'Trastornos distónicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A03', 'Trastornos atáxicos', 'category', false, false, 'CIE-11'),
('8A03.0', 'Ataxia congénita', 'category', false, false, 'CIE-11'),
('8A03.1', 'Ataxia hereditaria', 'category', false, false, 'CIE-11'),
('8A03.10', 'Ataxia de Friedreich', 'category', false, false, 'CIE-11'),
('8A03.11', 'Ataxia por xantomatosis cerebrotendinosa', 'category', false, false, 'CIE-11'),
('8A03.12', 'Ataxia por enfermedad de Refsum', 'category', false, false, 'CIE-11'),
('8A03.13', 'Ataxia por abetalipoproteinemia', 'category', false, false, 'CIE-11'),
('8A03.14', 'Ataxia episódica hereditaria', 'category', false, false, 'CIE-11'),
('8A03.15', 'Ataxia debido a mutaciones mitocondriales', 'category', false, false, 'CIE-11'),
('8A03.16', 'Ataxia espinocerebelosa', 'category', false, false, 'CIE-11'),
('8A03.1Y', 'Otra ataxia hereditaria especificada', 'category', false, false, 'CIE-11'),
('8A03.1Z', 'Ataxia hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.2', 'Ataxia degenerativa no hereditaria', 'category', false, false, 'CIE-11'),
('8A03.20', 'atrofia corticocerebelosa de aparición tardía', 'category', false, false, 'CIE-11'),
('8A03.2Y', 'Otra ataxia degenerativa no hereditaria especificada', 'category', false, false, 'CIE-11'),
('8A03.2Z', 'Ataxia degenerativa no hereditaria, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.3', 'Ataxia adquirida', 'category', false, false, 'CIE-11'),
('8A03.30', 'Ataxia por degeneración cerebelosa alcohólica', 'category', false, false, 'CIE-11'),
('8A03.3Y', 'Otra ataxia adquirida especificada', 'category', false, false, 'CIE-11'),
('8A03.3Z', 'Ataxia adquirida, sin especificación', 'category', false, false, 'CIE-11'),
('8A03.Y', 'Otros trastornos atáxicos especificados', 'category', false, false, 'CIE-11'),
('8A03.Z', 'Trastornos atáxicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A04', 'Trastornos asociados con temblor', 'category', false, false, 'CIE-11'),
('8A04.0', 'Temblor fisiológico intensificado', 'category', false, false, 'CIE-11'),
('8A04.1', 'Temblor esencial o temblores afines', 'category', false, false, 'CIE-11'),
('8A04.2', 'Temblor de reposo', 'category', false, false, 'CIE-11'),
('8A04.3', 'Temblor secundario', 'category', false, false, 'CIE-11'),
('8A04.30', 'Temblor por trastornos metabólicos', 'category', false, false, 'CIE-11'),
('8A04.31', 'Temblor debido al uso agudo o crónico de sustancias psicoactivas', 'category', false, false, 'CIE-11'),
('8A04.32', 'Temblor por abstinencia de drogas', 'category', false, false, 'CIE-11'),
('8A04.33', 'Temblor debido a ciertas enfermedades especificadas del sistema nervioso central', 'category', false, false, 'CIE-11'),
('8A04.3Y', 'Otro temblor secundario especificado', 'category', false, false, 'CIE-11'),
('8A04.3Z', 'Temblor secundario, sin especificación', 'category', false, false, 'CIE-11'),
('8A04.4', 'Temblor funcional', 'category', false, false, 'CIE-11'),
('8A04.Y', 'Otros trastornos asociados con temblor especificados', 'category', false, false, 'CIE-11'),
('8A04.Z', 'Trastornos asociados con temblor, sin especificación', 'category', false, false, 'CIE-11'),
('8A05', 'Trastornos por tics', 'category', false, false, 'CIE-11'),
('8A05.0', 'Tics o trastornos por tics primarios', 'category', false, false, 'CIE-11'),
('8A05.00', 'Síndrome de Tourette', 'category', false, false, 'CIE-11'),
('8A05.01', 'Trastorno por tic motor crónico', 'category', false, false, 'CIE-11'),
('8A05.02', 'Trastorno por tic fónico crónico', 'category', false, false, 'CIE-11'),
('8A05.03', 'Tics motores transitorios', 'category', false, false, 'CIE-11'),
('8A05.0Y', 'Otros tics o trastornos por tics primarios especificados', 'category', false, false, 'CIE-11'),
('8A05.0Z', 'Tics o trastornos por tics primarios, sin especificación', 'category', false, false, 'CIE-11'),
('8A05.1', 'Tics nerviosos secundarios', 'category', false, false, 'CIE-11'),
('8A05.10', 'Tics infecciosos o postinfecciosos', 'category', false, false, 'CIE-11'),
('8A05.11', 'Tics debidos a trastornos del desarrollo', 'category', false, false, 'CIE-11'),
('8A05.1Y', 'Otros tics nerviosos secundarios especificados', 'category', false, false, 'CIE-11'),
('8A05.1Z', 'Tics nerviosos secundarios, sin especificación', 'category', false, false, 'CIE-11'),
('8A05.Y', 'Otros trastornos especificados por tics', 'category', false, false, 'CIE-11'),
('8A05.Z', 'Trastornos por tics, sin especificación', 'category', false, false, 'CIE-11'),
('8A06', 'Trastornos mioclónicos', 'category', false, false, 'CIE-11'),
('8A06.0', 'Mioclono esencial', 'category', false, false, 'CIE-11'),
('8A06.1', 'Mioclono segmentario', 'category', false, false, 'CIE-11'),
('8A06.2', 'Mioclono focal', 'category', false, false, 'CIE-11'),
('8A06.20', 'Mioclono del paladar', 'category', false, false, 'CIE-11'),
('8A06.21', 'Hipo crónico', 'category', false, false, 'CIE-11'),
('8A06.2Y', 'Otro mioclono focal especificado', 'category', false, false, 'CIE-11'),
('8A06.2Z', 'Mioclono focal, sin especificación', 'category', false, false, 'CIE-11'),
('8A06.Y', 'Otros trastornos mioclónicos especificados', 'category', false, false, 'CIE-11'),
('8A06.Z', 'Trastornos mioclónicos, sin especificación', 'category', false, false, 'CIE-11'),
('8A07', 'Algunos trastornos del movimiento especificados', 'category', false, false, 'CIE-11'),
('8A07.0', 'Estereotipias', 'category', false, false, 'CIE-11'),
('8A07.00', 'Estereotipia primaria', 'category', false, false, 'CIE-11'),
('8A07.01', 'Estereotipia secundaria', 'category', false, false, 'CIE-11'),
('8A07.0Y', 'Otras estereotipias especificadas', 'category', false, false, 'CIE-11'),
('8A07.0Z', 'Estereotipias, sin especificación', 'category', false, false, 'CIE-11'),
('8A07.1', 'Acatisia', 'category', false, false, 'CIE-11'),
('8A07.2', 'Reflejo de sobresalto excesivo', 'category', false, false, 'CIE-11'),
('8A0Y', 'Otro trastorno especificado del movimiento', 'category', false, false, 'CIE-11'),
('8A0Z', 'Trastornos del movimiento, sin especificación', 'category', false, false, 'CIE-11'),
('8A20', 'Enfermedad de Alzheimer', 'category', false, false, 'CIE-11'),
('8A21', 'Atrofias corticales focales progresivas', 'category', false, false, 'CIE-11'),
('8A21.0', 'Atrofia cortical posterior', 'category', false, false, 'CIE-11'),
('8A21.Y', 'Otras atrofias corticales focales progresivas especificadas', 'category', false, false, 'CIE-11'),
('8A21.Z', 'Atrofias corticales focales progresivas, sin especificación', 'category', false, false, 'CIE-11'),
('8A22', 'Enfermedad de cuerpos de Lewy', 'category', false, false, 'CIE-11'),
('8A23', 'Degeneración lobular frontotemporal', 'category', false, false, 'CIE-11'),
('8A2Y', 'Otros trastornos especificados con deterioro neurocognitivo como característica destacada', 'category', false, false, 'CIE-11'),
('8A2Z', 'Trastornos con deterioro neurocognitivo como característica destacada, sin especificación', 'category', false, false, 'CIE-11'),
('8A40', 'Esclerosis múltiple', 'category', false, false, 'CIE-11'),
('8A40.0', 'Esclerosis múltiple recurrente- remitente', 'category', false, false, 'CIE-11'),
('8A40.1', 'Esclerosis múltiple progresiva primaria', 'category', false, false, 'CIE-11'),
('8A40.2', 'Esclerosis múltiple progresiva secundaria', 'category', false, false, 'CIE-11'),
('8A40.Y', 'Otra esclerosis múltiple especificada', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;