BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('9A72', 'Queratitis traumática', 'category', false, false, 'CIE-11'),
('9A73', 'Queratitis de exposición', 'category', false, false, 'CIE-11'),
('9A74', 'Queratitis neurotrófica', 'category', false, false, 'CIE-11'),
('9A75', 'Queratitis autoinmunitaria', 'category', false, false, 'CIE-11'),
('9A76', 'Úlcera corneal', 'category', false, false, 'CIE-11'),
('9A77', 'Cicatrices u opacidades corneales', 'category', false, false, 'CIE-11'),
('9A77.0', 'Infiltrados corneales asociados a lentes de contacto', 'category', false, false, 'CIE-11'),
('9A77.1', 'Leucoma adherente', 'category', false, false, 'CIE-11'),
('9A77.Y', 'Otras cicatrices u opacidades corneales especificadas', 'category', false, false, 'CIE-11'),
('9A77.Z', 'Cicatrices u opacidades corneales, sin especificación', 'category', false, false, 'CIE-11'),
('9A78', 'Algunos trastornos especificados de la córnea', 'category', false, false, 'CIE-11'),
('9A78.0', 'Neovascularización corneal', 'category', false, false, 'CIE-11'),
('9A78.1', 'Pigmentaciones o depósitos corneales', 'category', false, false, 'CIE-11'),
('9A78.2', 'Edema corneal', 'category', false, false, 'CIE-11'),
('9A78.20', 'Queratopatía vesicular', 'category', false, false, 'CIE-11'),
('9A78.21', 'Edema corneal secundario', 'category', false, false, 'CIE-11'),
('9A78.2Y', 'Otro edema corneal especificado', 'category', false, false, 'CIE-11'),
('9A78.2Z', 'Edema corneal, sin especificación', 'category', false, false, 'CIE-11'),
('9A78.3', 'Cambios en las membranas de la córnea', 'category', false, false, 'CIE-11'),
('9A78.4', 'Degeneración corneal', 'category', false, false, 'CIE-11'),
('9A78.5', 'Deformidades corneales', 'category', false, false, 'CIE-11'),
('9A78.50', 'Queratocono', 'category', false, false, 'CIE-11'),
('9A78.51', 'Estafiloma corneal', 'category', false, false, 'CIE-11'),
('9A78.5Y', 'Otras deformidades corneales especificadas', 'category', false, false, 'CIE-11'),
('9A78.5Z', 'Deformidades corneales, sin especificación', 'category', false, false, 'CIE-11'),
('9A78.6', 'Anestesia de la córnea', 'category', false, false, 'CIE-11'),
('9A78.7', 'Hipoestesia de la córnea', 'category', false, false, 'CIE-11'),
('9A78.8', 'Erosión recurrente de la córnea', 'category', false, false, 'CIE-11'),
('9A79', 'Queratoconjuntivitis seca', 'category', false, false, 'CIE-11'),
('9A7A', 'Absceso corneal', 'category', false, false, 'CIE-11'),
('9A7B', 'Queratitis esclerosante', 'category', false, false, 'CIE-11'),
('9A7Y', 'Otros trastornos especificados de la córnea', 'category', false, false, 'CIE-11'),
('9A7Z', 'Trastornos de la córnea, sin especificación', 'category', false, false, 'CIE-11'),
('9A80', 'Hipema', 'category', false, false, 'CIE-11'),
('9A81', 'Parásitos en la cámara anterior del ojo', 'category', false, false, 'CIE-11'),
('9A82', 'Quiste en la cámara anterior del ojo', 'category', false, false, 'CIE-11'),
('9A83', 'Hipotonía del ojo de la cámara anterior plana', 'category', false, false, 'CIE-11'),
('9A8Y', 'Otros trastornos especificados de la cámara anterior', 'category', false, false, 'CIE-11'),
('9A8Z', 'Trastornos de la cámara anterior, sin especificación', 'category', false, false, 'CIE-11'),
('9A90', 'Degeneración del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A90.0', 'Trastornos del ángulo de la cámara', 'category', false, false, 'CIE-11'),
('9A90.1', 'Degeneración del iris', 'category', false, false, 'CIE-11'),
('9A90.2', 'Atrofia del iris', 'category', false, false, 'CIE-11'),
('9A90.Y', 'Otra degeneración especificada del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A90.Z', 'Degeneración del iris o del cuerpo ciliar, sin especificación', 'category', false, false, 'CIE-11'),
('9A91', 'Quiste del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A92', 'Membranas pupilares persistentes', 'category', false, false, 'CIE-11'),
('9A93', 'Adherencias o interrupciones del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A94', 'Algunos trastornos especificados del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A94.0', 'Rubeosis del iris', 'category', false, false, 'CIE-11'),
('9A94.1', 'Síndrome del iris flácido', 'category', false, false, 'CIE-11'),
('9A94.2', 'Síndrome del iris en meseta', 'category', false, false, 'CIE-11'),
('9A94.Y', 'Otros trastornos especificados del iris o del cuerpo ciliar', 'category', false, false, 'CIE-11'),
('9A96', 'Uveítis anterior', 'category', false, false, 'CIE-11'),
('9A96.0', 'Uveítis anterior no asociada a enfermedades sistémicas', 'category', false, false, 'CIE-11'),
('9A96.1', 'Uveítis anterior asociada a enfermedades sistémicas', 'category', false, false, 'CIE-11'),
('9A96.2', 'Uveítis anterior asociada a infección', 'category', false, false, 'CIE-11'),
('9A96.3', 'Uveítis anterior primaria', 'category', false, false, 'CIE-11'),
('9A96.Y', 'Otra uveítis anterior especificada', 'category', false, false, 'CIE-11'),
('9A96.Z', 'Uveítis anterior, sin especificación', 'category', false, false, 'CIE-11'),
('9A9Y', 'Otros trastornos especificados de la úvea anterior', 'category', false, false, 'CIE-11'),
('9A9Z', 'Trastornos de la úvea anterior, sin especificación', 'category', false, false, 'CIE-11'),
('9B00', 'Trastornos del sistema pupilar aferente', 'category', false, false, 'CIE-11'),
('9B00.0', 'Defectos pupilares aferentes relativos', 'category', false, false, 'CIE-11'),
('9B00.1', 'Reacción pupilar amaurótica', 'category', false, false, 'CIE-11'),
('9B00.2', 'Reacción pupilar paradójica a la luz o a la oscuridad', 'category', false, false, 'CIE-11'),
('9B00.3', 'Pupilas de Wernicke', 'category', false, false, 'CIE-11'),
('9B00.Y', 'Otros trastornos especificados del sistema pupilar aferente', 'category', false, false, 'CIE-11'),
('9B00.Z', 'Trastornos del sistema pupilar aferente, sin especificación', 'category', false, false, 'CIE-11'),
('9B01', 'Trastornos del sistema pupilar eferente', 'category', false, false, 'CIE-11'),
('9B01.0', 'Anisocoria fisiológica', 'category', false, false, 'CIE-11'),
('9B01.1', 'Pupilas parasimpaticoparéticas', 'category', false, false, 'CIE-11'),
('9B01.2', 'Inhibición farmacológica de la vía parasimpática', 'category', false, false, 'CIE-11'),
('9B01.3', 'Trastornos del esfínter del iris', 'category', false, false, 'CIE-11'),
('9B01.4', 'Pupilas parasimpaticotónicas farmacológicas', 'category', false, false, 'CIE-11'),
('9B01.5', 'Pupilas simpaticoparéticas farmacológicas', 'category', false, false, 'CIE-11'),
('9B01.6', 'Pupilas simpaticotónicas', 'category', false, false, 'CIE-11'),
('9B01.7', 'Midriasis unilateral episódica', 'category', false, false, 'CIE-11'),
('9B01.Y', 'Otros trastornos especificados del sistema pupilar eferente', 'category', false, false, 'CIE-11'),
('9B01.Z', 'Trastornos del sistema pupilar eferente, sin especificación', 'category', false, false, 'CIE-11'),
('9B02', 'Disociaciones de luz y acomodación', 'category', false, false, 'CIE-11'),
('9B02.0', 'Pupila de Argyll Robertson', 'category', false, false, 'CIE-11'),
('9B02.1', 'Disociaciones pregeniculadas de luz y acomodación', 'category', false, false, 'CIE-11'),
('9B02.2', 'Disociaciones mesencefálicas de luz y acomodación', 'category', false, false, 'CIE-11'),
('9B02.Y', 'Otras disociaciones de luz y acomodación especificadas', 'category', false, false, 'CIE-11'),
('9B02.Z', 'Disociaciones de luz y acomodación, sin especificación', 'category', false, false, 'CIE-11'),
('9B0Y', 'Otros trastornos funcionales especificados de la pupila', 'category', false, false, 'CIE-11'),
('9B0Z', 'Trastornos funcionales de la pupila, sin especificación', 'category', false, false, 'CIE-11'),
('9B10', 'Catarata', 'category', false, false, 'CIE-11'),
('9B10.0', 'Catarata relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B10.00', 'Catarata coronaria relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B10.01', 'Catarata punteada relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B10.02', 'Catarata madura relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B10.0Y', 'Otra catarata especificada relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B10.0Z', 'Catarata relacionada con la edad, sin especificación', 'category', false, false, 'CIE-11'),
('9B10.1', 'Catarata infantil o juvenil', 'category', false, false, 'CIE-11'),
('9B10.10', 'Formas combinadas de catarata infantil o juvenil', 'category', false, false, 'CIE-11'),
('9B10.1Y', 'Otra catarata especificada infantil o juvenil', 'category', false, false, 'CIE-11'),
('9B10.1Z', 'Catarata infantil o juvenil, sin especificación', 'category', false, false, 'CIE-11'),
('9B10.2', 'Algunas cataratas especificadas', 'category', false, false, 'CIE-11'),
('9B10.20', 'Catarata traumática', 'category', false, false, 'CIE-11'),
('9B10.21', 'Catarata diabética', 'category', false, false, 'CIE-11'),
('9B10.22', 'Catarata secundaria', 'category', false, false, 'CIE-11'),
('9B10.23', 'Manchas glaucomatosas subcapsulares', 'category', false, false, 'CIE-11'),
('9B10.2Y', 'Otras cataratas especificadas', 'category', false, false, 'CIE-11'),
('9B10.Z', 'Catarata, sin especificación', 'category', false, false, 'CIE-11'),
('9B11', 'Algunos trastornos especificados del cristalino', 'category', false, false, 'CIE-11'),
('9B11.0', 'Afaquia', 'category', false, false, 'CIE-11'),
('9B11.1', 'Luxación del cristalino', 'category', false, false, 'CIE-11'),
('9B11.Y', 'Otro(a)(s) algunos trastornos especificados del cristalino especificado(a)(s)', 'category', false, false, 'CIE-11'),
('9B1Z', 'Trastornos del cristalino, sin especificación', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('9B3Y', 'Otros trastornos especificados del segmento anterior del globo ocular', 'category', false, false, 'CIE-11'),
('9B3Z', 'Trastornos del segmento anterior del globo ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9B50', 'Epiescleritis', 'category', false, false, 'CIE-11'),
('9B51', 'Escleritis', 'category', false, false, 'CIE-11'),
('9B52', 'Estafiloma escleral', 'category', false, false, 'CIE-11'),
('9B5Y', 'Otros trastornos especificados de la esclerótica', 'category', false, false, 'CIE-11'),
('9B5Z', 'Trastornos de la esclerótica, sin especificación', 'category', false, false, 'CIE-11'),
('9B60', 'Degeneración coroidea', 'category', false, false, 'CIE-11'),
('9B61', 'Distrofia coroidal', 'category', false, false, 'CIE-11'),
('9B62', 'Cicatrices coriorretinianas', 'category', false, false, 'CIE-11'),
('9B63', 'Hemorragia o ruptura coroidea', 'category', false, false, 'CIE-11'),
('9B64', 'Desprendimiento coroideo', 'category', false, false, 'CIE-11'),
('9B65', 'Coroiditis', 'category', false, false, 'CIE-11'),
('9B65.0', 'Coroiditis no infecciosa', 'category', false, false, 'CIE-11'),
('9B65.1', 'coroiditis infecciosa', 'category', false, false, 'CIE-11'),
('9B65.Z', 'Coroiditis, sin especificación', 'category', false, false, 'CIE-11'),
('9B66', '', 'category', false, false, 'CIE-11'),
('9B66.0', 'Uveítis intermedia no infecciosa [possible translation]', 'category', false, false, 'CIE-11'),
('9B66.1', '', 'category', false, false, 'CIE-11'),
('9B66.Z', 'Coroiditis intermedia, sin especificación', 'category', false, false, 'CIE-11'),
('9B6Y', 'Otros trastornos especificados de la coroides', 'category', false, false, 'CIE-11'),
('9B6Z', 'Trastornos de la coroides, sin especificación', 'category', false, false, 'CIE-11'),
('9B70', 'Distrofia retiniana hereditaria', 'category', false, false, 'CIE-11'),
('9B71', 'Retinopatía', 'category', false, false, 'CIE-11'),
('9B71.0', 'Retinopatía diabética', 'category', false, false, 'CIE-11'),
('9B71.00', 'Retinopatía diabética no proliferativa', 'category', false, false, 'CIE-11'),
('9B71.01', 'Retinopatía diabética proliferativa', 'category', false, false, 'CIE-11'),
('9B71.02', 'Edema macular diabético', 'category', false, false, 'CIE-11'),
('9B71.0Z', 'Retinopatía diabética, sin especificación', 'category', false, false, 'CIE-11'),
('9B71.1', 'Retinopatía hipertensiva', 'category', false, false, 'CIE-11'),
('9B71.2', 'Retinopatía por radiación', 'category', false, false, 'CIE-11'),
('9B71.3', 'Retinopatía del prematuro', 'category', false, false, 'CIE-11'),
('9B71.4', 'Retinopatía paraneoplásica', 'category', false, false, 'CIE-11'),
('9B71.40', 'Retinopatía asociada a melanoma', 'category', false, false, 'CIE-11'),
('9B71.4Y', 'Otra retinopatía paraneoplásica especificada', 'category', false, false, 'CIE-11'),
('9B71.4Z', 'Retinopatía paraneoplásica, sin especificación', 'category', false, false, 'CIE-11'),
('9B71.5', 'Retinopatía autoinmunitaria', 'category', false, false, 'CIE-11'),
('9B71.Y', 'Otra retinopatía especificada', 'category', false, false, 'CIE-11'),
('9B71.Z', 'Retinopatía, sin especificación', 'category', false, false, 'CIE-11'),
('9B72', 'Enfermedades inflamatorias de la retina', 'category', false, false, 'CIE-11'),
('9B72.0', 'Retinitis viral', 'category', false, false, 'CIE-11'),
('9B72.00', 'Retinitis por citomegalovirus', 'category', false, false, 'CIE-11'),
('9B72.01', 'Retinitis por VIH', 'category', false, false, 'CIE-11'),
('9B72.0Y', 'Otra retinitis viral especificada', 'category', false, false, 'CIE-11'),
('9B72.0Z', 'Retinitis viral, sin especificación', 'category', false, false, 'CIE-11'),
('9B72.Y', 'Otras enfermedades inflamatorias especificadas de la retina', 'category', false, false, 'CIE-11'),
('9B72.Z', 'Enfermedades inflamatorias de la retina, sin especificación', 'category', false, false, 'CIE-11'),
('9B73', 'Desprendimientos o roturas de la retina', 'category', false, false, 'CIE-11'),
('9B73.0', 'Desprendimiento de retina con desgarro', 'category', false, false, 'CIE-11'),
('9B73.1', 'Retinosquisis', 'category', false, false, 'CIE-11'),
('9B73.10', 'Retinosquisis del adulto', 'category', false, false, 'CIE-11'),
('9B73.11', 'Retinosquisis juvenil', 'category', false, false, 'CIE-11'),
('9B73.1Y', 'Otra retinosquisis especificada', 'category', false, false, 'CIE-11'),
('9B73.1Z', 'Retinosquisis, sin especificación', 'category', false, false, 'CIE-11'),
('9B73.2', 'Quiste de la retina', 'category', false, false, 'CIE-11'),
('9B73.3', 'Desprendimiento seroso de retina', 'category', false, false, 'CIE-11'),
('9B73.4', 'Roturas retinianas sin desprendimiento', 'category', false, false, 'CIE-11'),
('9B73.Y', 'Otros desprendimientos o roturas especificados de la retina', 'category', false, false, 'CIE-11'),
('9B73.Z', 'Desprendimientos o roturas de la retina, sin especificación', 'category', false, false, 'CIE-11'),
('9B74', 'Oclusión vascular retiniana', 'category', false, false, 'CIE-11'),
('9B74.0', 'Oclusión arterial retiniana', 'category', false, false, 'CIE-11'),
('9B74.1', 'Oclusión venosa retiniana', 'category', false, false, 'CIE-11'),
('9B74.2', 'Oclusión de arteria y vena retiniana combinada', 'category', false, false, 'CIE-11'),
('9B74.Y', 'Otra oclusión vascular retiniana especificada', 'category', false, false, 'CIE-11'),
('9B74.Z', 'Oclusión vascular retiniana, sin especificación', 'category', false, false, 'CIE-11'),
('9B75', 'Trastornos maculares', 'category', false, false, 'CIE-11'),
('9B75.0', 'Degeneración macular relacionada con la edad avanzada', 'category', false, false, 'CIE-11'),
('9B75.00', 'Degeneración macular incipiente relacionada con la edad.', 'category', false, false, 'CIE-11'),
('9B75.01', 'Degeneración macular intermedia relacionada con la edad.', 'category', false, false, 'CIE-11'),
('9B75.03', 'Degeneración macular atrófica relacionada con la edad en etapa tardía', 'category', false, false, 'CIE-11'),
('9B75.04', 'Degeneración macular neovascular tardía relacionada con la edad', 'category', false, false, 'CIE-11'),
('9B75.0Y', 'Otra degeneración macular especificada relacionada con la edad avanzada', 'category', false, false, 'CIE-11'),
('9B75.0Z', 'Degeneración macular relacionada con la edad avanzada, sin especificación', 'category', false, false, 'CIE-11'),
('9B75.1', 'Agujero macular no traumático', 'category', false, false, 'CIE-11'),
('9B75.2', 'Coriorretinopatía serosa central', 'category', false, false, 'CIE-11'),
('9B75.3', 'Telangiectasia macular', 'category', false, false, 'CIE-11'),
('9B75.Y', 'Otros trastornos maculares especificados', 'category', false, false, 'CIE-11'),
('9B75.Z', 'Trastornos maculares, sin especificación', 'category', false, false, 'CIE-11'),
('9B76', 'Miopía degenerativa alta', 'category', false, false, 'CIE-11'),
('9B77', 'Enfermedad de Eales', 'category', false, false, 'CIE-11'),
('9B78', 'Algunos trastornos retinianos especificados', 'category', false, false, 'CIE-11'),
('9B78.0', 'Vasculopatía retiniana y leucodistrofia cerebral', 'category', false, false, 'CIE-11'),
('9B78.1', 'Retinopatía de fondo y cambios vasculares retinianos', 'category', false, false, 'CIE-11'),
('9B78.10', 'Cambios en la apariencia vascular retiniana', 'category', false, false, 'CIE-11'),
('9B78.11', 'Retinopatía exudativa', 'category', false, false, 'CIE-11'),
('9B78.12', 'Vasculitis retiniana', 'category', false, false, 'CIE-11'),
('9B78.13', 'Telangiectasia retiniana', 'category', false, false, 'CIE-11'),
('9B78.1Y', 'Otra retinopatía de fondo especificada y cambios vasculares retinianos', 'category', false, false, 'CIE-11'),
('9B78.1Z', 'Retinopatía de fondo y cambios vasculares retinianos, sin especificación', 'category', false, false, 'CIE-11'),
('9B78.2', 'Otras retinopatías proliferativas', 'category', false, false, 'CIE-11'),
('9B78.3', 'Degeneración de la mácula o del polo posterior', 'category', false, false, 'CIE-11'),
('9B78.30', 'Seudodrusas reticulares', 'category', false, false, 'CIE-11'),
('9B78.3Y', 'Otra degeneración especificada de la mácula o del polo posterior', 'category', false, false, 'CIE-11'),
('9B78.3Z', 'Degeneración de la mácula o del polo posterior, sin especificación', 'category', false, false, 'CIE-11'),
('9B78.4', 'Degeneración periférica de la retina', 'category', false, false, 'CIE-11'),
('9B78.5', 'Hemorragia retiniana', 'category', false, false, 'CIE-11'),
('9B78.6', 'Separación de las capas de la retina', 'category', false, false, 'CIE-11'),
('9B78.60', 'Desprendimiento seroso del epitelio pigmentario de la retina', 'category', false, false, 'CIE-11'),
('9B78.61', 'Desprendimiento hemorrágico del epitelio pigmentario de la retina', 'category', false, false, 'CIE-11'),
('9B78.6Y', 'Otra separación especificada de las capas de la retina', 'category', false, false, 'CIE-11'),
('9B78.6Z', 'Separación de las capas de la retina, sin especificación', 'category', false, false, 'CIE-11'),
('9B78.7', 'Edema retiniano', 'category', false, false, 'CIE-11'),
('9B78.8', 'Isquemia retiniana', 'category', false, false, 'CIE-11'),
('9B78.9', 'Atrofia retiniana', 'category', false, false, 'CIE-11'),
('9B7Y', 'Otros trastornos especificados de la retina', 'category', false, false, 'CIE-11'),
('9B7Z', 'Trastornos de la retina, sin especificación', 'category', false, false, 'CIE-11'),
('9B80', 'Trastornos vitreorretinianos hereditarios', 'category', false, false, 'CIE-11'),
('9B81', 'Desprendimiento de vítreo posterior', 'category', false, false, 'CIE-11'),
('9B82', 'Prolapso del cuerpo vítreo', 'category', false, false, 'CIE-11'),
('9B83', 'Hemorragia vítrea', 'category', false, false, 'CIE-11'),
('9B84', 'Opacidades, membranas o hebras vítreas', 'category', false, false, 'CIE-11'),
('9B8Y', 'Otros trastornos especificados del cuerpo vítreo', 'category', false, false, 'CIE-11'),
('9B8Z', 'Trastornos del cuerpo vítreo, sin especificación', 'category', false, false, 'CIE-11'),
('9C0Y', 'Otros trastornos especificados del segmento posterior del globo ocular', 'category', false, false, 'CIE-11'),
('9C0Z', 'Trastornos del segmento posterior del globo ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9C20', 'Panuveítis', 'category', false, false, 'CIE-11'),
('9C20.0', 'Panuveítis no infecciosa', 'category', false, false, 'CIE-11'),
('9C20.1', 'Panuveítis infecciosa', 'category', false, false, 'CIE-11'),
('9C20.2', 'Endoftalmitis purulenta', 'category', false, false, 'CIE-11'),
('9C20.Y', 'Otra panuveítis especificada', 'category', false, false, 'CIE-11'),
('9C20.Z', 'Panuveítis, sin especificación', 'category', false, false, 'CIE-11'),
('9C21', 'Endoftalmitis', 'category', false, false, 'CIE-11'),
('9C21.0', 'Uveítis simpática', 'category', false, false, 'CIE-11'),
('9C21.Y', 'Otra endoftalmitis especificada', 'category', false, false, 'CIE-11'),
('9C21.Z', 'Endoftalmitis, sin especificación', 'category', false, false, 'CIE-11'),
('9C22', 'Deformidad del globo ocular', 'category', false, false, 'CIE-11'),
('9C22.0', 'Globo ocular atrófico', 'category', false, false, 'CIE-11'),
('9C22.1', 'Subatrofia del globo ocular', 'category', false, false, 'CIE-11'),
('9C22.Y', 'Otra deformidad del globo ocular especificada', 'category', false, false, 'CIE-11'),
('9C22.Z', 'Deformidad del globo ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9C2Y', 'Otros trastornos especificados del globo ocular que afectan los segmentos anterior y posterior', 'category', false, false, 'CIE-11'),
('9C2Z', 'Trastornos del globo ocular que afectan los segmentos anterior y posterior, sin especificación', 'category', false, false, 'CIE-11'),
('9C40', 'Trastorno del nervio óptico', 'category', false, false, 'CIE-11'),
('9C40.0', 'Neuropatía óptica infecciosa', 'category', false, false, 'CIE-11'),
('9C40.1', 'Neuritis óptica', 'category', false, false, 'CIE-11'),
('9C40.10', 'Neuritis retrobulbar', 'category', false, false, 'CIE-11'),
('9C40.1Y', 'Otra neuritis óptica especificada', 'category', false, false, 'CIE-11'),
('9C40.1Z', 'Neuritis óptica, sin especificación', 'category', false, false, 'CIE-11'),
('9C40.2', 'Neurorretinitis', 'category', false, false, 'CIE-11'),
('9C40.3', 'Perineuritis óptica', 'category', false, false, 'CIE-11'),
('9C40.4', 'Neuropatía óptica isquémica', 'category', false, false, 'CIE-11'),
('9C40.40', 'Neuropatía óptica isquémica anterior', 'category', false, false, 'CIE-11'),
('9C40.41', 'Neuropatía óptica isquémica posterior', 'category', false, false, 'CIE-11'),
('9C40.4Y', 'Otra neuropatía óptica isquémica especificada', 'category', false, false, 'CIE-11'),
('9C40.4Z', 'Neuropatía óptica isquémica, sin especificación', 'category', false, false, 'CIE-11'),
('9C40.5', 'Neuropatía óptica compresiva', 'category', false, false, 'CIE-11'),
('9C40.6', 'Neuropatía óptica infiltrativa', 'category', false, false, 'CIE-11'),
('9C40.7', 'Neuropatía óptica traumática', 'category', false, false, 'CIE-11'),
('9C40.8', 'Neuropatía óptica hereditaria', 'category', false, false, 'CIE-11'),
('9C40.9', 'Neuropatía óptica glaucomatosa', 'category', false, false, 'CIE-11'),
('9C40.A', 'Tumefacción del disco óptico', 'category', false, false, 'CIE-11'),
('9C40.A0', 'Papiledema', 'category', false, false, 'CIE-11'),
('9C40.A1', 'Tumefacción de la papila óptica asociada a uveítis', 'category', false, false, 'CIE-11'),
('9C40.AY', 'Otra tumefacción especificada del disco óptico', 'category', false, false, 'CIE-11'),
('9C40.AZ', 'Tumefacción del disco óptico, sin especificación', 'category', false, false, 'CIE-11'),
('9C40.B', 'Atrofia óptica', 'category', false, false, 'CIE-11'),
('9C40.B0', 'Atrofia óptica congénita', 'category', false, false, 'CIE-11'),
('9C40.B1', 'Atrofia óptica adquirida', 'category', false, false, 'CIE-11'),
('9C40.BZ', 'Atrofia óptica, sin especificación', 'category', false, false, 'CIE-11'),
('9C40.Y', 'Otro trastorno especificado del nervio óptico', 'category', false, false, 'CIE-11'),
('9C40.Z', 'Trastorno del nervio óptico, sin especificación', 'category', false, false, 'CIE-11'),
('9C41', 'Trastorno del quiasma óptico', 'category', false, false, 'CIE-11'),
('9C42', 'Trastorno de las vías ópticas posquiasmáticas', 'category', false, false, 'CIE-11'),
('9C43', 'Trastorno de la corteza visual', 'category', false, false, 'CIE-11'),
('9C44', 'Trastorno de los centros visuales superiores', 'category', false, false, 'CIE-11'),
('9C4Y', 'Otros trastornos especificados de las vías o centros ópticos', 'category', false, false, 'CIE-11'),
('9C4Z', 'Trastornos de las vías o centros ópticos, sin especificación', 'category', false, false, 'CIE-11'),
('9C60', 'Sospecha de glaucoma', 'category', false, false, 'CIE-11'),
('9C61', 'Glaucoma', 'category', false, false, 'CIE-11'),
('9C61.0', 'Glaucoma primario de ángulo abierto', 'category', false, false, 'CIE-11'),
('9C61.00', 'Glaucoma normotensivo', 'category', false, false, 'CIE-11'),
('9C61.01', 'Hipertensión ocular', 'category', false, false, 'CIE-11'),
('9C61.02', 'Glaucoma primario de ángulo abierto con presión alta', 'category', false, false, 'CIE-11'),
('9C61.0Y', 'Otra glaucoma primario especificado de ángulo abierto', 'category', false, false, 'CIE-11'),
('9C61.0Z', 'Glaucoma primario de ángulo abierto, sin especificación', 'category', false, false, 'CIE-11'),
('9C61.1', 'Cierre de ángulo primario y glaucoma de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.10', 'Sospecha de cierre de ángulo primario o ángulo anatómico estrecho', 'category', false, false, 'CIE-11'),
('9C61.11', 'Cierre de ángulo primario', 'category', false, false, 'CIE-11'),
('9C61.12', 'Glaucoma primario de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.13', 'Cierre de ángulo primario sin bloqueo pupilar', 'category', false, false, 'CIE-11'),
('9C61.14', 'Cierre de ángulo agudo con bloqueo pupilar', 'category', false, false, 'CIE-11'),
('9C61.15', 'Cierre de ángulo intermitente', 'category', false, false, 'CIE-11'),
('9C61.16', 'Ángulo cerrado crónico', 'category', false, false, 'CIE-11'),
('9C61.17', 'Afección tras un episodio agudo de glaucoma de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.1Y', 'Otro cierre de ángulo primario y glaucoma de ángulo cerrado especificado', 'category', false, false, 'CIE-11'),
('9C61.1Z', 'Cierre de ángulo primario y glaucoma de ángulo cerrado, sin especificación', 'category', false, false, 'CIE-11'),
('9C61.2', 'Glaucoma secundario - ángulo abierto', 'category', false, false, 'CIE-11'),
('9C61.20', 'Glaucoma seudoexfoliativo de ángulo abierto', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;