BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XH2GD5', 'Neurofibroma melanótico', 'category', false, false, 'CIE-11'),
('XH87J5', 'Neurofibroma, SAI', 'category', false, false, 'CIE-11'),
('XH2MJ4', 'Neurofibroma plexiforme', 'category', false, false, 'CIE-11'),
('XH9XT2', 'Schwannoma plexiforme', 'category', false, false, 'CIE-11'),
('XH9MN2', 'Schwannoma psamomatoso', 'category', false, false, 'CIE-11'),
('XH98Z3', 'Schwanoma SAI', 'category', false, false, 'CIE-11'),
('XH27Y1', 'Tumor de la vaina nerviosa, SAI', 'category', false, false, 'CIE-11'),
('XH01G0', 'Tumor híbrido de la vaina del nervio', 'category', false, false, 'CIE-11'),
('XH4UE6', 'Neuroma, SAI', 'category', false, false, 'CIE-11'),
('XH90Y8', 'Neuroma circunscrito solitario', 'category', false, false, 'CIE-11'),
('XH0XF7', 'Perineurioma, SAI', 'category', false, false, 'CIE-11'),
('XH3L35', 'Mixoma de la vaina del nervio', 'category', false, false, 'CIE-11'),
('XH9QH2', 'Perineurioma de tejido blando', 'category', false, false, 'CIE-11'),
('XH4BQ8', 'Perineurioma intraneural', 'category', false, false, 'CIE-11'),
('XH1UZ6', 'Neurotecoma celular', 'category', false, false, 'CIE-11'),
('XH9J01', 'Tumor triton benigno', 'category', false, false, 'CIE-11'),
('XH2XP8', 'Tumor de la vaina del nervio periférico maligno', 'category', false, false, 'CIE-11'),
('XH5C30', 'TMVNP melanótico', 'category', false, false, 'CIE-11'),
('XH3NT0', 'TMVNP melanótico psamomatoso', 'category', false, false, 'CIE-11'),
('XH8HF5', 'TMVNP con diferenciación glandular', 'category', false, false, 'CIE-11'),
('XH7HR8', 'TMVNP con diferenciación mesenquimatosa', 'category', false, false, 'CIE-11'),
('XH3W53', 'TMVNP con diferenciación perineural', 'category', false, false, 'CIE-11'),
('XH4V81', 'Tumor maligno de vaina de nervio periférico, epitelioide', 'category', false, false, 'CIE-11'),
('XH88C2', 'Neurilemoma, maligno', 'category', false, false, 'CIE-11'),
('XH2VV8', 'Tumor de la vaina del nervio periférico maligno con diferenciación rabdomioblástica', 'category', false, false, 'CIE-11'),
('XH31C8', 'Perineurioma, maligno', 'category', false, false, 'CIE-11'),
('XH2637', 'Schwanoma melanótico', 'category', false, false, 'CIE-11'),
('XH6K00', 'Gangliocitoma displásico de cerebelo (Lhermitte-Duclos)', 'category', false, false, 'CIE-11'),
('XH6KA6', 'Gangliocitoma', 'category', false, false, 'CIE-11'),
('XH03L9', 'Ganglioneuroma', 'category', false, false, 'CIE-11'),
('XH6LR5', 'Ganglioneuromatosis', 'category', false, false, 'CIE-11'),
('XH28W9', 'Meduloepitelioma, benigno', 'category', false, false, 'CIE-11'),
('XH8NQ6', 'Tumor de Pacini', 'category', false, false, 'CIE-11'),
('XH5AV1', 'Retinocitoma', 'category', false, false, 'CIE-11'),
('XH5NR7', 'Meduloepitelioma teratoide, benigno', 'category', false, false, 'CIE-11'),
('XH7ZQ4', 'Tumor teratoide / rabdoide atípico', 'category', false, false, 'CIE-11'),
('XH2GG3', 'Ganglioglioma, anaplásico', 'category', false, false, 'CIE-11'),
('XH77W7', 'Ganglioneuroblastoma', 'category', false, false, 'CIE-11'),
('XH0RB7', 'Ganglioneuroblastoma, entremezclado', 'category', false, false, 'CIE-11'),
('XH6JM6', 'Retinoblastoma, diferenciado', 'category', false, false, 'CIE-11'),
('XH49K9', 'Espongioneuroblastoma', 'category', false, false, 'CIE-11'),
('XH0AM8', 'Meduloepitelioma teratoide', 'category', false, false, 'CIE-11'),
('XH70S0', 'Ganglioneuroblastoma del SNC', 'category', false, false, 'CIE-11'),
('XH85Z0', 'Neuroblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH2WK5', 'Meduloepitelioma, SAI', 'category', false, false, 'CIE-11'),
('XH9FP2', 'Neuroepitelioma, SAI', 'category', false, false, 'CIE-11'),
('XH8WC7', 'Retinoblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH7KP6', 'Retinoblastoma, indeferenciado', 'category', false, false, 'CIE-11'),
('XH1YZ7', 'Retinoblastoma, difuso', 'category', false, false, 'CIE-11'),
('XH09A4', 'Tumor neurogénico olfatorio', 'category', false, false, 'CIE-11'),
('XH7QE0', 'Neurocitoma olfatorio', 'category', false, false, 'CIE-11'),
('XH2Y49', 'Neuroepitelioma olfatorio', 'category', false, false, 'CIE-11'),
('XH50L1', 'Neuroblastoma olfatorio', 'category', false, false, 'CIE-11'),
('XH3AV2', 'Tumor embrionario del Sistema Nervioso Central con características rabdoides', 'category', false, false, 'CIE-11'),
('XH0C11', 'Neurocitoma central', 'category', false, false, 'CIE-11'),
('XH2GB0', 'Liponeurocitoma cerebeloso', 'category', false, false, 'CIE-11'),
('XH5FJ3', 'Ganglioglioma,SAI', 'category', false, false, 'CIE-11'),
('XH2HS1', 'Neurocitoma extraventricular', 'category', false, false, 'CIE-11'),
('XH3XU4', 'Tumor glioneuronal papilar', 'category', false, false, 'CIE-11'),
('XH2JU8', 'Tumor glioneuronal formador de rosetas', 'category', false, false, 'CIE-11'),
('XH2F27', 'Retinoblastoma con regresión espontánea.', 'category', false, false, 'CIE-11'),
('XH8RN4', 'Nevo de células en balón', 'category', false, false, 'CIE-11'),
('XH27A6', 'Nevo compuesto', 'category', false, false, 'CIE-11'),
('XH8WP0', 'Nevo conjuntival juvenil inflamado', 'category', false, false, 'CIE-11'),
('XH6DN3', 'Melanocitosis difusa', 'category', false, false, 'CIE-11'),
('XH9035', 'Nevo displásico', 'category', false, false, 'CIE-11'),
('XH2HG8', 'Nevo de células epitelioides y fusiformes', 'category', false, false, 'CIE-11'),
('XH8ZB4', 'Nevo velloso', 'category', false, false, 'CIE-11'),
('XH5971', 'Nevo con halo', 'category', false, false, 'CIE-11'),
('XH2MQ5', 'Nevo dérmico', 'category', false, false, 'CIE-11'),
('XH1BE4', 'Nevo magnocelular', 'category', false, false, 'CIE-11'),
('XH8CU4', 'Neuronevo', 'category', false, false, 'CIE-11'),
('XH0XH2', 'Nevo no pigmentado', 'category', false, false, 'CIE-11'),
('XH4L78', 'Nevo pigmentado SAI', 'category', false, false, 'CIE-11'),
('XH02Z5', 'Melanocitoma,SAI', 'category', false, false, 'CIE-11'),
('XH8974', 'Melanocitosis meningea', 'category', false, false, 'CIE-11'),
('XH1M79', 'Nevo de unión, SAI', 'category', false, false, 'CIE-11'),
('XH9QV1', 'Nevo de células fusiformes, SAI', 'category', false, false, 'CIE-11'),
('XH7QJ7', 'Nevo azul, SAI', 'category', false, false, 'CIE-11'),
('XH2P88', 'Nevus de células fusiformes pigmentadas de Reed', 'category', false, false, 'CIE-11'),
('XH79G6', 'Nevo de células epitelioides', 'category', false, false, 'CIE-11'),
('XH3X84', 'Nevo celular azul', 'category', false, false, 'CIE-11'),
('XH40S8', 'Nevo manchado', 'category', false, false, 'CIE-11'),
('XH81Y1', 'Nevo penetrante profundo', 'category', false, false, 'CIE-11'),
('XH0DU8', 'Nevo combinado', 'category', false, false, 'CIE-11'),
('XH5EL4', 'Nevo genital', 'category', false, false, 'CIE-11'),
('XH8FS8', 'Nevo conjuntival', 'category', false, false, 'CIE-11'),
('XH9QC8', 'Nevus melanocítico lentiginoso', 'category', false, false, 'CIE-11'),
('XH88L0', 'Lentigo simple', 'category', false, false, 'CIE-11'),
('XH9DB2', 'Nevo acral', 'category', false, false, 'CIE-11'),
('XH8NP4', 'Nevo de Meyerson', 'category', false, false, 'CIE-11'),
('XH5YN0', 'Nevo melanocítico congénito, SAI', 'category', false, false, 'CIE-11'),
('XH9WF4', 'Nevo de Spitz, atípico', 'category', false, false, 'CIE-11'),
('XH9KY6', 'Léntigo maligno', 'category', false, false, 'CIE-11'),
('XH3XX3', 'Melanoma in situ', 'category', false, false, 'CIE-11'),
('XH41F9', 'Melanosis precancerosa, SAI', 'category', false, false, 'CIE-11'),
('XH9L11', 'Melanoma acral', 'category', false, false, 'CIE-11'),
('XH3TK1', 'Melanoma amelanótico', 'category', false, false, 'CIE-11'),
('XH8TE3', 'Melanoma de células en balón', 'category', false, false, 'CIE-11'),
('XH1P36', 'Melanoma desmoplástico, amelanótico', 'category', false, false, 'CIE-11'),
('XH1Z15', 'Melanoma desmoplástico, SAI', 'category', false, false, 'CIE-11'),
('XH9NL4', 'Lentigo maligno melanoma', 'category', false, false, 'CIE-11'),
('XH5L25', 'Melanoma maligno que surge en un nevo gigante congénito', 'category', false, false, 'CIE-11'),
('XH23B1', 'Melanoma maligno en nevo de unión.', 'category', false, false, 'CIE-11'),
('XH7L76', 'Melanoma maligno en melanosis precancerosa', 'category', false, false, 'CIE-11'),
('XH6XP3', 'Melanoma maligno en regresión', 'category', false, false, 'CIE-11'),
('XH1BP7', 'Melanomatosis meníngea', 'category', false, false, 'CIE-11'),
('XH5QP3', 'Melanoma lentiginoso mucoso', 'category', false, false, 'CIE-11'),
('XH5F94', 'Melanoma neurotrópico, maligno', 'category', false, false, 'CIE-11'),
('XH4QG5', 'Melanoma nodular', 'category', false, false, 'CIE-11'),
('XH08X7', 'Melanoma de extensión superficial', 'category', false, false, 'CIE-11'),
('XH4846', 'Melanoma maligno, SAI', 'category', false, false, 'CIE-11'),
('XH25M1', 'Melanoma de células fusiformes, SAI', 'category', false, false, 'CIE-11'),
('XH8HA2', 'Melanoma mixto de células epitelioides y fusiformes', 'category', false, false, 'CIE-11'),
('XH0QL5', 'Melanoma de células epitelioides', 'category', false, false, 'CIE-11'),
('XH5KW3', 'Melanoma fusocelular, tipo A', 'category', false, false, 'CIE-11'),
('XH5YE7', 'Melanoma fusocelular, tipo B', 'category', false, false, 'CIE-11'),
('XH1G74', 'Nevus azul maligno', 'category', false, false, 'CIE-11'),
('XH7JW1', 'Melanoma por daño solar acumulativo bajo', 'category', false, false, 'CIE-11'),
('XH8DS3', 'Tumor maligno de Spitz', 'category', false, false, 'CIE-11'),
('XH3DN1', 'Melanoma, meníngeo', 'category', false, false, 'CIE-11'),
('XH8681', 'Melanoma nevoide', 'category', false, false, 'CIE-11'),
('XH2C28', 'Nevo pigmentado gigante, SAI', 'category', false, false, 'CIE-11'),
('XH1XJ3', 'Nevo congénito intermedio y gigante', 'category', false, false, 'CIE-11'),
('XH2RY7', 'Melanocitoma meníngeo', 'category', false, false, 'CIE-11'),
('XH6AH3', 'Lesión dérmica proliferativa en nevus congénito', 'category', false, false, 'CIE-11'),
('XH4VD0', 'Melanocitoma epitelioide pigmentado', 'category', false, false, 'CIE-11'),
('XH2SD0', 'Tumor odontogénico adenomatoide', 'category', false, false, 'CIE-11'),
('XH44W7', 'Fibro-odontoma ameloblástico', 'category', false, false, 'CIE-11'),
('XH0964', 'Fibrodentinoma ameloblástico', 'category', false, false, 'CIE-11'),
('XH3R33', 'Quiste odontogénico calcificante', 'category', false, false, 'CIE-11'),
('XH5Y46', 'Fibroma cementificante', 'category', false, false, 'CIE-11'),
('XH52T0', 'Fibroma cemento-osificante', 'category', false, false, 'CIE-11'),
('XH4VL1', 'Cementoblastoma, benigno', 'category', false, false, 'CIE-11'),
('XH1MT3', 'Fibroma odontogénico, SAI', 'category', false, false, 'CIE-11'),
('XH7H47', 'Odontoma complejo', 'category', false, false, 'CIE-11'),
('XH57B1', 'Odontoma compuesto', 'category', false, false, 'CIE-11'),
('XH6W94', 'Cementoma gigantiforme', 'category', false, false, 'CIE-11'),
('XH06N8', 'Odontoameloblastoma', 'category', false, false, 'CIE-11'),
('XH12N4', 'Tumor de células fantasmas dentinogénicas', 'category', false, false, 'CIE-11'),
('XH48L4', 'Mixoma odontogénico', 'category', false, false, 'CIE-11'),
('XH43L1', 'Tumor odontogénico, benigno', 'category', false, false, 'CIE-11'),
('XH4PV9', 'Tumor odontogénico escamoso', 'category', false, false, 'CIE-11'),
('XH8FX0', 'Cementoma, SAI', 'category', false, false, 'CIE-11'),
('XH4QJ8', 'Odontoma, SAI', 'category', false, false, 'CIE-11'),
('XH1SV4', 'Ameloblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH2M31', 'Fibroma odontogénico periférico', 'category', false, false, 'CIE-11'),
('XH06Y3', 'Fibroma ameloblástico', 'category', false, false, 'CIE-11'),
('XH4PT4', 'Tumor odontogénico epitelial calcificante', 'category', false, false, 'CIE-11'),
('XH39C5', 'Ameloblastoma sinonasal', 'category', false, false, 'CIE-11'),
('XH5ZZ6', 'Ameloblastoma, tipo uniquístico', 'category', false, false, 'CIE-11'),
('XH4KQ4', 'Ameloblastoma, tipo extraóseo/periférico', 'category', false, false, 'CIE-11'),
('XH1MW0', 'Odontosarcoma ameloblástico', 'category', false, false, 'CIE-11'),
('XH96J9', 'Ameloblastoma, metastásico', 'category', false, false, 'CIE-11'),
('XH4M89', 'Tumor odontogénico, maligno', 'category', false, false, 'CIE-11'),
('XH0XD5', 'Fibrosarcoma ameloblástico', 'category', false, false, 'CIE-11'),
('XH4LP1', 'Carcinosarcoma odontogénico', 'category', false, false, 'CIE-11'),
('XH2BX2', 'Carcinoma odontogénico de células fantasma', 'category', false, false, 'CIE-11'),
('XH5DZ4', 'Carcinoma odontogénico de células claras', 'category', false, false, 'CIE-11'),
('XH1P03', 'Tumor odontogénico, SAI', 'category', false, false, 'CIE-11'),
('XH9SY5', 'Encondroma', 'category', false, false, 'CIE-11'),
('XH5Y87', 'Osteocondroma', 'category', false, false, 'CIE-11'),
('XH4818', 'Osteoma, SAI', 'category', false, false, 'CIE-11'),
('XH61J9', 'Osteoma osteoide, SAI', 'category', false, false, 'CIE-11'),
('XH4316', 'Osteoblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH6KR3', 'Osteocondromixoma', 'category', false, false, 'CIE-11'),
('XH23J5', 'Proliferación osteocondromatosa parostal rara', 'category', false, false, 'CIE-11'),
('XH0NS4', 'Condroma, SAI', 'category', false, false, 'CIE-11'),
('XH49G1', 'Condroma yuxtacortical', 'category', false, false, 'CIE-11'),
('XH3BC3', 'Condroma periosteal', 'category', false, false, 'CIE-11'),
('XH89S0', 'Fibroma condromixoide', 'category', false, false, 'CIE-11'),
('XH1XL9', 'Exostosis subungueal', 'category', false, false, 'CIE-11'),
('XH1Y90', 'Osteosarcoma central', 'category', false, false, 'CIE-11'),
('XH3T03', 'Osteosarcoma condroblástico', 'category', false, false, 'CIE-11'),
('XH23T4', 'Osteosarcoma fibroblástico', 'category', false, false, 'CIE-11'),
('XH29N8', 'Fibrocondrosarcoma', 'category', false, false, 'CIE-11'),
('XH6TL0', 'Osteosarcoma de superficie de alto grado', 'category', false, false, 'CIE-11'),
('XH9LS2', 'Osteosarcoma intracortical', 'category', false, false, 'CIE-11'),
('XH9119', 'Osteosarcoma bien diferenciado intraóseo', 'category', false, false, 'CIE-11'),
('XH06W9', 'Osteosarcoma en la enfermedad de Paget del hueso', 'category', false, false, 'CIE-11'),
('XH8HG5', 'Osteosarcoma parosteal', 'category', false, false, 'CIE-11'),
('XH48A9', 'Osteosarcoma perióstico', 'category', false, false, 'CIE-11'),
('XH4EZ4', 'Osteosarcoma de células pequeñas', 'category', false, false, 'CIE-11'),
('XH5CL5', 'Osteosarcoma telangiectásico', 'category', false, false, 'CIE-11'),
('XH1XF3', 'Osteosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH2CD6', 'Osteosarcoma extraesquelético', 'category', false, false, 'CIE-11'),
('XH7N84', 'Osteosarcoma central de bajo grado', 'category', false, false, 'CIE-11'),
('XH8J23', 'Condrosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH6LT5', 'Condrosarcoma, grado 2', 'category', false, false, 'CIE-11'),
('XH0Y34', 'Condrosarcoma, grado 3', 'category', false, false, 'CIE-11'),
('XH5FH4', 'Condrosarcoma juxtacortical', 'category', false, false, 'CIE-11'),
('XH1S32', 'Condresarcoma perióstico', 'category', false, false, 'CIE-11'),
('XH6W00', 'Condroblastoma maligno', 'category', false, false, 'CIE-11'),
('XH9344', 'Condrosarcoma mixoide', 'category', false, false, 'CIE-11'),
('XH8X47', 'Condrosarcoma mesenquimal', 'category', false, false, 'CIE-11'),
('XH7XB9', 'Condrosarcoma de células claras', 'category', false, false, 'CIE-11'),
('XH6E77', 'Condrosarcoma desdiferenciado', 'category', false, false, 'CIE-11'),
('XH2RD1', 'Osteoblastoma agresivo', 'category', false, false, 'CIE-11'),
('XH70W8', 'Osteocondromatosis, SAI', 'category', false, false, 'CIE-11'),
('XH5BT0', 'Condromatosis, SAI', 'category', false, false, 'CIE-11'),
('XH0FY0', 'Tumor cartilaginoso atípico', 'category', false, false, 'CIE-11'),
('XH4NK2', 'Condroblastoma,SAI', 'category', false, false, 'CIE-11'),
('XH2012', 'Paraganglioma gangliocítico', 'category', false, false, 'CIE-11'),
('XH47J2', 'Tumor glómico, SAI', 'category', false, false, 'CIE-11'),
('XH4CC6', 'Tumor epitelioide perivascular, benigno', 'category', false, false, 'CIE-11'),
('XH3RX1', 'Glomangioma', 'category', false, false, 'CIE-11'),
('XH2702', 'Glomangiomioma', 'category', false, false, 'CIE-11'),
('XH9WD1', 'Tumor epitelioide perivascular, maligno', 'category', false, false, 'CIE-11'),
('XH1UN6', 'Paraganglioma extra-adrenal', 'category', false, false, 'CIE-11'),
('XH8GG7', 'Paraganglioma no cromafín', 'category', false, false, 'CIE-11'),
('XH05Y1', 'Glomangiosarcoma', 'category', false, false, 'CIE-11'),
('XH21E6', 'Tumor glómico maligno', 'category', false, false, 'CIE-11'),
('XH9YX6', 'Paraganglioma del oído medio', 'category', false, false, 'CIE-11'),
('XH5521', 'Paraganglioma laríngeo', 'category', false, false, 'CIE-11'),
('XH1493', 'Paraganglioma vagal', 'category', false, false, 'CIE-11'),
('XH3JF3', 'Paraganglioma compuesto', 'category', false, false, 'CIE-11'),
('XH9K97', 'Feocromocitoma compuesto', 'category', false, false, 'CIE-11'),
('XH0EW6', 'Paraganglioma, SAI', 'category', false, false, 'CIE-11'),
('XH4G21', 'Paraganglioma simpático', 'category', false, false, 'CIE-11'),
('XH5LK3', 'Paraganglioma parasimpático', 'category', false, false, 'CIE-11'),
('XH7YU4', 'Tumor del cuerpo aórtico', 'category', false, false, 'CIE-11'),
('XH3FS7', 'Paraganglioma del cuerpo carotídeo', 'category', false, false, 'CIE-11'),
('XH20B4', 'Quemodectoma', 'category', false, false, 'CIE-11'),
('XH3854', 'Feocromocitoma, SAI', 'category', false, false, 'CIE-11'),
('XH7CP7', 'Glomangiomatosis', 'category', false, false, 'CIE-11'),
('XH5D10', 'Tumor glómico de comportamiento maligno incierto', 'category', false, false, 'CIE-11'),
('XH67T7', 'Tumor de tejido blando, benigno', 'category', false, false, 'CIE-11'),
('XH4UM7', 'Sarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH7Y17', 'Sarcomatosis, SAI', 'category', false, false, 'CIE-11'),
('XH7AN8', 'Sarcoma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH73J4', 'Sarcoma de células gigantes', 'category', false, false, 'CIE-11'),
('XH85G7', 'Sarcoma de células pequeñas', 'category', false, false, 'CIE-11'),
('XH4F96', 'Sarcoma epitelioide', 'category', false, false, 'CIE-11'),
('XH6HY6', 'Sarcoma indiferenciado', 'category', false, false, 'CIE-11'),
('XH5SN6', 'Tumor de células redondas pequeñas desmoplásico', 'category', false, false, 'CIE-11'),
('XH7XH3', 'Sarcoma dérmico pleomórfico', 'category', false, false, 'CIE-11'),
('XH92Y0', 'Sarcoma epitelioide, indiferenciado', 'category', false, false, 'CIE-11'),
('XH2193', 'Tumor angiectásico hialinizante pleomórfico', 'category', false, false, 'CIE-11'),
('XH52J1', 'Tumor de tejido blando epitelioide alterado por GLI1', 'category', false, false, 'CIE-11'),
('XH7H87', 'Androblastoma, benigno', 'category', false, false, 'CIE-11'),
('XH6NZ8', 'Tumor estromal esclerosante', 'category', false, false, 'CIE-11'),
('XH0BG7', 'Tumor de células de Sertoli con almacenamiento de lípidos', 'category', false, false, 'CIE-11'),
('XH7E53', 'Tumor de células de Sertoli-Leydig, bien diferenciado', 'category', false, false, 'CIE-11'),
('XH0Z30', 'Tecoma, luteinizado', 'category', false, false, 'CIE-11'),
('XH3C14', 'Tumor del cordón sexual estromal, benigno', 'category', false, false, 'CIE-11'),
('XH69N5', 'Tumor estromal de anillo de sello', 'category', false, false, 'CIE-11'),
('XH35B3', 'Tumor estromal microquístico', 'category', false, false, 'CIE-11'),
('XH34A0', 'Tecoma, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH40J2', 'Luteoma, sin otra especificación', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XH2U25', 'Tumor de células granulosas del testículo, juvenil', 'category', false, false, 'CIE-11'),
('XH5XQ2', 'Tumor de células de Leydig del ovario, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH9LH4', 'Tumor de células del hilio', 'category', false, false, 'CIE-11'),
('XH9XY1', 'Tumor de las células lipídicas del ovario', 'category', false, false, 'CIE-11'),
('XH1PE9', 'Masculinovoblastoma', 'category', false, false, 'CIE-11'),
('XH9RV1', 'Tumor de restos suprarrenales', 'category', false, false, 'CIE-11'),
('XH44E8', 'Androblastoma, maligno', 'category', false, false, 'CIE-11'),
('XH1QG7', 'Carcinoma de células de la granulosa', 'category', false, false, 'CIE-11'),
('XH97Z8', 'Carcinoma de células de la granulosa, sarcomatoide', 'category', false, false, 'CIE-11'),
('XH29E0', 'Tumor de células de Sertoli-Leydig, poco diferenciado', 'category', false, false, 'CIE-11'),
('XH3BT2', 'Tumor de células de Sertoli-Leydig, poco diferenciado, con elementos heterólogos', 'category', false, false, 'CIE-11'),
('XH4KB9', 'Tumor de células de Sertoli-Leydig, sarcomatoide', 'category', false, false, 'CIE-11'),
('XH1JS6', 'Tecoma, maligno', 'category', false, false, 'CIE-11'),
('XH0GA5', 'Tumor de ovario de células granulosas del adulto', 'category', false, false, 'CIE-11'),
('XH7DV5', 'Tumor de células granulosas, tipo adulto', 'category', false, false, 'CIE-11'),
('XH9G68', 'Tumor de células de Leydig, maligno', 'category', false, false, 'CIE-11'),
('XH4L39', 'Tumor de células esteroideas, maligno', 'category', false, false, 'CIE-11'),
('XH7051', 'Carcinoma de células de Sertoli', 'category', false, false, 'CIE-11'),
('XH2KH2', 'Tumor de células granulosas, juvenil', 'category', false, false, 'CIE-11'),
('XH37K7', 'Tumor de células de la teca Granulosa', 'category', false, false, 'CIE-11'),
('XH0Q64', 'Ginandroblastoma', 'category', false, false, 'CIE-11'),
('XH9E02', 'Tumor de células de Sertoli de células grandes calcificantes', 'category', false, false, 'CIE-11'),
('XH0UP7', 'Tumor de células de Sertoli-Leydig de diferenciación intermedia', 'category', false, false, 'CIE-11'),
('XH6FQ9', 'Tumor de células de Sertoli-Leydig, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH8U56', 'Tumor de células de Sertoli-Leydig, diferenciación intermedia, con elementos heterólogos', 'category', false, false, 'CIE-11'),
('XH6XB6', 'Tumor de células Sertoli-Leydig, retiforme', 'category', false, false, 'CIE-11'),
('XH3PN1', 'Tumor de células Sertoli-Leydig, retiforme, con elementos heterólogos', 'category', false, false, 'CIE-11'),
('XH5BV8', 'Tumor de cordón sexual con túbulos anulares', 'category', false, false, 'CIE-11'),
('XH5PC7', 'Tumor estromal del cordón sexual-gonadal, incompletamente diferenciado', 'category', false, false, 'CIE-11'),
('XH19F9', 'Tumor estromal del cordón sexual-gonadal, formas mixtas', 'category', false, false, 'CIE-11'),
('XH9G57', 'Tumores del estroma gonadal de cordón sexual', 'category', false, false, 'CIE-11'),
('XH8033', 'Tumor estromal con elementos menores del cordón sexual', 'category', false, false, 'CIE-11'),
('XH8CW8', 'Tumor uterino que se asemeja al tumor del cordón sexual ovárico', 'category', false, false, 'CIE-11'),
('XH0667', 'Tumor estromal del cordón sexual, no clasificado', 'category', false, false, 'CIE-11'),
('XH0U48', 'Tumores mixto de células germinales y del estroma de los cordones sexuales, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH27A8', 'Tumores mixto de células germinales y del estroma de los cordones sexuales, no clasificado', 'category', false, false, 'CIE-11'),
('XH5BN5', 'Tumor de células de la granulosa del testículo tipo adulto', 'category', false, false, 'CIE-11'),
('XH0GT2', 'Androblastoma, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH4H24', 'Tumor de células de Sertoli, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH7RD2', 'Neoplasia de células de Sertoli grandes, hialinizantes, intratubulares', 'category', false, false, 'CIE-11'),
('XH51L7', 'Tumor de células de Leydig del testículo, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH17Q9', 'Papiloma, SAI', 'category', false, false, 'CIE-11'),
('XH7YQ5', 'Papiloma de células escamosas, invertido', 'category', false, false, 'CIE-11'),
('XH50T2', 'Papiloma de células escamosas,SAI', 'category', false, false, 'CIE-11'),
('XH4611', 'Neoplasia intraepitelial escamosa, bajo grado', 'category', false, false, 'CIE-11'),
('XH50N3', 'Papilomatosis escamosa', 'category', false, false, 'CIE-11'),
('XH2Y10', 'Papiloma verrugoso', 'category', false, false, 'CIE-11'),
('XH9S34', 'Neoplasia anal intraepitelial, de bajo grado', 'category', false, false, 'CIE-11'),
('XH1W63', 'Neoplasia cervical intraepitelial, de bajo grado', 'category', false, false, 'CIE-11'),
('XH3Y37', 'Neoplasia esofágica intraepitelial escamosa (displasia), de bajo grado', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;