BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XE8TZ', 'Emisión involuntaria del dispositivo', 'category', false, false, 'CIE-11'),
('XE1LT', 'Interferencia de radiofrecuencia con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE02N', 'Problema de interoperabilidad con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE6C8', 'Problema de comunicación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE22K', 'Problema de comunicación por cable con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1PD', 'Problema de comunicación inalámbrica con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5NA', 'Problema de comunicación de red con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1SP', 'Componente o accesorio incompatible del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1YT', 'Etiquetado e instrucciones de uso o mantenimiento como problema del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3PV', 'Etiquetado inadecuado o instrucciones para el uso del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4MR', 'Etiquetado o instrucciones incorrectas de uso del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE7Y7', 'Instrucciones inadecuadas o incorrectas para el mantenimiento del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3RW', 'Problema material o químico con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2H0', 'Problema de degradación identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE2WT', 'Material inapropiado identificado en el dispositivo', 'category', false, false, 'CIE-11'),
('XE60T', 'Propiedades fisicoquímicas inadecuadas identificadas en el dispositivo', 'category', false, false, 'CIE-11'),
('XE4EB', 'Material incompatible identificado en el dispositivo', 'category', false, false, 'CIE-11'),
('XE25Z', 'Problema de reactividad identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE6U0', 'Problema de tolerancia del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE640', 'Problema mecánico con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8RU', 'Migración de dispositivo identificada', 'category', false, false, 'CIE-11'),
('XE3HZ', 'Problema de fricción identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE1P8', 'Problema de fuga o sellado identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE6UT', 'Problema de lubricación identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE69Q', 'Problema de rigidez identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE8V5', 'Problema de estrés con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE0WG', 'Problema de deformación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3Y4', 'Problema de fatiga con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1ZP', 'Problema de fractura con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1UJ', 'Problema de choque mecánico con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1H3', 'Problema de vibración con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1ZQ', 'Problema de desgaste con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1EJ', 'Dimensión incorrecta del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4KN', 'Problema óptico con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE42B', 'Problema de transmisión óptica con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8XT', 'Problema de fuente de luz identificado con el dispositivo', 'category', false, false, 'CIE-11'),
('XE05W', 'Problema de imagen clínica con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE15N', 'Problema de campo inducido por gradiente con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1HK', 'Artefacto de imagen identificado en el dispositivo', 'category', false, false, 'CIE-11'),
('XE6YW', 'Movimiento inducido magnéticamente del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9Y9', 'Sobrecalentamiento inducido por radiofrecuencia del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE6TE', 'Problemas del software con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE77W', 'Problema de configuración del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE6DT', 'Error de diseño (software) del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE006', 'Error de compresión de datos en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE62E', 'Algoritmo incorrecto en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1X4', 'Definición de datos incorrecta en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2FL', 'Error de diseño de interfaz del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE85U', 'Defecto no funcional en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3RD', 'Problema de sincronización del software en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9JR', 'Problema de mantenimiento de software con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE688', 'Problema de instalación de software con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4SV', 'Error de requisito del software con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE51Q', 'Error de tiempo de ejecución del software en el dispositivo identificado', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XE9W2', 'Vulnerabilidad de la seguridad del software del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1KR', 'Transferencia errónea de datos en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2A7', 'Problema de almacenamiento de datos o pérdida de datos en el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8XM', 'Problema térmico con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE62G', 'Sobrecalentamiento del problema del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9HT', 'Problema de calentamiento excesivo del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE7A1', 'Problema de enfriamiento inadecuado del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5HU', 'Problema del sistema de protección con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE0WJ', 'Problema de prueba de fallas con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4JQ', 'Problema del sistema de alarma con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE7ZT', 'Problema para la autocomprobación del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1JG', 'Problema para detener automáticamente el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9AV', 'Problema con el restablecimiento del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2FY', 'Problema con el indicador de activación prematura identificado', 'category', false, false, 'CIE-11'),
('XE3BG', 'Problema de blindaje con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE0M6', 'Medidas de seguridad faltantes o inadecuadas del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE82X', 'Problema operativo con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5RS', 'Dispositivo reprocesado incorrectamente', 'category', false, false, 'CIE-11'),
('XE2RQ', 'Dispositivo limpiado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE63T', 'Dispositivo desinfectado o esterilizado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE0TU', 'Dispositivo ensamblado incorrectamente durante el reprocesamiento identificado', 'category', false, false, 'CIE-11'),
('XE15Q', 'Problema de error al calibrar identificado', 'category', false, false, 'CIE-11'),
('XE3W1', 'Problema de dificultad para operar el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2QD', 'Interpretación incorrecta de resultados o problema de datos identificado', 'category', false, false, 'CIE-11'),
('XE2YD', 'Problema de la muestra del paciente con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8DL', 'Problema de interferencia nuevo o desconocido con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9C0', 'Problema de interferencia conocido con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE83B', 'Problema de manipulación preanalítica con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3AL', 'Problema ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5K2', 'Problema de temperatura ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9HK', 'Problema de polvo o suciedad con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE2VF', 'Contaminación del medio ambiente por el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE6QW', 'Problema de presión ambiental con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE5SF', 'Problema de luz ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE4V1', 'Problema de humedad ambiental con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE205', 'Problema del proceso de fabricación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE3NF', 'Problema de montaje con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE00F', 'Problema de esterilización con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE1PG', 'Problema de instalación con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE843', 'Problema de mantenimiento de maquinaria de fabricación con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE278', 'Problema de empaquetado con dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9F7', 'Problema con el empaquetado del dispositivo comprometido identificado', 'category', false, false, 'CIE-11'),
('XE0KG', 'Problema con los materiales de embalaje del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE8S1', 'Problema con el embalaje del dispositivo que contiene un material no deseado identificado', 'category', false, false, 'CIE-11'),
('XE8TA', 'Problema porque el paquete contiene un dispositivo incorrecto identificado', 'category', false, false, 'CIE-11'),
('XE6LZ', 'Problema de mantenimiento con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE9VK', 'Problema de transporte o almacenamiento con el dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE32G', 'Problema de almacenamiento del dispositivo identificado', 'category', false, false, 'CIE-11'),
('XE41R', 'No se encontró problema en el dispositivo', 'category', false, false, 'CIE-11'),
('XE587', 'Ningún hallazgo disponible', 'category', false, false, 'CIE-11'),
('XE3PA', 'Resultados pendientes de completar en la investigación', 'category', false, false, 'CIE-11'),
('XE3WR', 'Término o código apropiado para la investigación de dispositivo no disponible', 'category', false, false, 'CIE-11'),
('XE9HD', 'Prueba de dispositivo real o sospechoso', 'category', false, false, 'CIE-11'),
('XE7XH', 'Prueba del dispositivo del mismo lote o lote retenido por el fabricante', 'category', false, false, 'CIE-11'),
('XE4S0', 'Prueba del dispositivo del mismo lote devuelto por el usuario', 'category', false, false, 'CIE-11'),
('XE2ZR', 'Prueba del dispositivo de otro lote retenido por el fabricante', 'category', false, false, 'CIE-11'),
('XE4X1', 'Prueba de dispositivo de otro lote o lote devuelto por el usuario', 'category', false, false, 'CIE-11'),
('XE1XT', 'Prueba de variante del modelo', 'category', false, false, 'CIE-11'),
('XE8XV', 'Pruebas de materias primas o de partida', 'category', false, false, 'CIE-11'),
('XE6FS', 'Prueba de muestra del paciente o material de referencia utilizando el dispositivo del fabricante', 'category', false, false, 'CIE-11'),
('XE9MY', 'Prueba de la muestra del paciente o material de referencia utilizando el método de referencia', 'category', false, false, 'CIE-11'),
('XE89L', 'Prueba de la muestra del paciente o material de referencia utilizando un dispositivo de la competencia', 'category', false, false, 'CIE-11'),
('XE8UH', 'Análisis de datos históricos', 'category', false, false, 'CIE-11'),
('XE8BM', 'Análisis de tendencia', 'category', false, false, 'CIE-11'),
('XE7GK', 'Comunicación o entrevistas', 'category', false, false, 'CIE-11'),
('XE4KV', 'Análisis de registros de producción', 'category', false, false, 'CIE-11'),
('XE59M', 'Análisis de datos proporcionados por el usuario o terceras partes', 'category', false, false, 'CIE-11'),
('XE8FB', 'Dispositivo no fabricado por el fabricante reportado', 'category', false, false, 'CIE-11'),
('XE970', 'Dispositivo no devuelto', 'category', false, false, 'CIE-11'),
('XE18W', 'Dispositivo descartado', 'category', false, false, 'CIE-11'),
('XE5AN', 'Dispositivo devuelto pero incompleto', 'category', false, false, 'CIE-11'),
('XE53L', 'Dispositivo no accesible para pruebas', 'category', false, false, 'CIE-11'),
('XE6Q2', 'Tipo de investigación aún no determinado', 'category', false, false, 'CIE-11'),
('XE3TW', 'Información disponible insuficiente', 'category', false, false, 'CIE-11'),
('XE8XD', 'Componente absorbente de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6Z7', 'Componente de punta del cauterio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7JR', 'Ingrediente del dispositivo o componente reactivo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8HT', 'Componente de captación de gases del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4VK', 'Componente monómero líquido de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE68H', 'Componente de la tira reactiva del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7WP', 'Componente de polvo de polímero de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE321', 'Componente de antena del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3WM', 'Componente de batería del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE80Z', 'Componente cargador de batería del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7JQ', 'Cable, componente eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE77B', 'Componente de agarre de cable del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2BS', 'Componente de funda (aislante) de cable de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2WY', 'Componente de la placa de circuito del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5BT', 'Componente del interruptor eléctrico automático del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2ZE', 'Componente de hardware informático del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3Q8', 'Componente procesador de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1JS', 'Componente de memoria o almacenamiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2YC', 'Componente de interfaz de red del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8UU', 'Componente de software de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE59Z', 'Componente de controlador de software de computadora del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2JQ', 'Componente de interfaz de software del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8V6', 'Componente de interfaz de usuario del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7P0', 'Componente del módulo de enfriamiento del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8UV', 'Componente programador de dispositivo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE033', 'Componente lector de dispositivo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6UE', 'Componente eléctrico discreto del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE845', 'Componente de condensador eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE38E', 'Componente fusible eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1UQ', 'Componente inductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2AJ', 'Componente de resistencia eléctrica del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4VJ', 'Componente de solenoide eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE018', 'Componente transductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE27R', 'Componente semiconductor eléctrico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9ZW', 'Componente de chip de circuito integrado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8GY', 'Componente de visualización del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4YD', 'Componente indicador de pantalla del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2JV', 'Componente de pantalla de visualización del dispositivo médico.', 'category', false, false, 'CIE-11'),
('XE59E', 'Cable eléctrico o componente de cable del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5U9', 'Componente de electrodo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE561', 'Cable o componente de alambre para conexión a tierra del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE753', 'Componente del arnés de cableado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6S4', 'Componente de mezclador eléctrico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0Y5', 'Componente de puerto eléctrico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2PX', 'Componente emisor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5GC', 'Componente de auriculares o cascos de un dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9TB', 'Componente calefactor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE713', 'Componente central del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8JV', 'Componente inversor de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BN', 'Componente magnético del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7YS', 'Componente oscilador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE525', 'Componente cable conductor del paciente a un dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7F1', 'Componente cable conductor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE25C', 'Componente de electrodo de dispositivo médico para el paciente', 'category', false, false, 'CIE-11'),
('XE4XJ', 'Componente del cable de alimentación del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4Q4', 'Componente de fuente de alimentación del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7EJ', 'Componente de la sonda del transductor de presión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE062', 'Componente de impresión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2KA', 'Componente receptor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6SG', 'Componente de la unidad del estimulador del receptor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4TH', 'Componente de escáner de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0ST', 'Altavoz o componente acústico del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5R5', 'Interruptor o componente de relé del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1EF', 'Componente del interruptor de encendido del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4QR', 'Componente de relé (interruptor) de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE884', 'Componente de telemetría del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE30P', 'Componente compensador de temperatura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE56F', 'Componente del termostato del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE256', 'Componente transformador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE579', 'Componente transmisor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5A0', 'Componente de dispositivo de entrada de usuario del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9TZ', 'Componente de control (joystick) de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6CN', 'Teclado o componente de teclado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9FY', 'Componente de micrófono de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9ZJ', 'Componente de pantalla táctil del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE37A', 'Componente analizador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0A7', 'Componente analizador de oxígeno del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6E8', 'Componente de apertura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE34X', 'Componente calibrador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE06B', 'Componente de reloj del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9NB', 'Componente contador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE20X', 'Componente Curvette (frasco o tubo de ensayo transparente) del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00B', 'Medidor o componentes de medidores de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE1WJ', 'Componente de fluxómetro de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6V2', 'Componente de manómetro del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE019', 'Componente termómetro del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8RD', 'Componente marcador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7MS', 'Componente de pipeta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5UB', 'Componente puntero del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2MH', 'Componente de escala del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8GP', 'Componente sensor de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5Q2', 'Componente del sensor de burbujas del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5ZD', 'Componente del sensor de oxígeno del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9G5', 'Componente fotodetector del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5WR', 'Componente sensor de presión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7Q4', 'Componente de la sonda del sensor del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3W9', 'Componente del sensor de temperatura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3R3', 'Componente temporizador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3UX', 'Componente del puerto de acceso del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0WZ', 'Componente actuador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0SV', 'Componente adaptador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6D6', 'Componente eliminador de aire del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4F2', 'Componente de anclaje del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE94Y', 'Componente aplicador de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE968', 'Componente del sistema de inyección automática del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7E4', 'Componente de bolsa de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0HN', 'Componente esférico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5AV', 'Componente de globo de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1G8', 'Componente de cojinetes de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0Y2', 'Componente de encapsulado de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE46S', 'Componente de sonda del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE23M', 'Componente procesador (de material) del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9DJ', 'Componente de polea de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0K1', 'Componente de bomba del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8RF', 'Componente empujador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE76K', 'Componente de trinquete del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4JZ', 'Componente de carril del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0KN', 'Componente de riel lateral del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6YN', 'Componente regulador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE65T', 'Componente depósito del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1XK', 'Componente de fuelle de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7DG', 'Componente de anillo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE017', 'Componente de varilla o eje del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4BJ', 'Componente de sellado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7N2', 'Componente amortiguador de dispositivos médicos', 'category', false, false, 'CIE-11'),
('XE7ZG', 'Componente de manga de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6VJ', 'Componente laminilla de vidrio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE740', 'Componente de enchufe del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4DU', 'Componente espaciador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7QZ', 'Componente de resorte del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4K0', 'Componente de soporte del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9CF', 'Componente de cinturón de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE82E', 'Componente del cable de dirección del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7UE', 'Componente stent de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8M4', 'Componente de la llave de paso del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00C', 'Componente de tapón del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4E4', 'Componente de alivio de tensión del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3GN', 'Componente de estilete del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE05P', 'Componente de jeringa de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3ED', 'Componente de mesa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE06W', 'Componente de punta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6GE', 'Componente de herramienta del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE7G4', 'Componente de botella de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0UG', 'Componente de movimiento traslacional del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2FM', 'Componente de trampa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4M3', 'Componente de trocar del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8TY', 'Componente de tubo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2PZ', 'Componente del tubo capilar del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE01P', 'Componente de válvula de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3YJ', 'Componente de la válvula de control del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE229', 'Componente de la válvula conector Luer del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2LS', 'Componente de válvula unidireccional de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6MT', 'Componente vaporizador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0FP', 'Componente vibrador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE83A', 'Componente de arandela de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1PW', 'Componente de soldadura del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE6HA', 'Componente de rueda de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0C3', 'Componente del circuito respiratorio del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE99Z', 'Componente de ventana del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2Q3', 'Componente del obturador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE5YT', 'Componente de cepillo del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE0AX', 'Componente de cepillado del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE4NU', 'Cable, componente estructural mecánico de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE2UB', 'Componente de cánula del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE9FK', 'Componente del cubo de la cánula del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE44H', 'Componente de tapa del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE00E', 'Componente transportador del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE3K0', 'Componente de rueda de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE088', 'Componente catéter de dispositivo médico', 'category', false, false, 'CIE-11'),
('XE8NS', 'Componente del conector de catéter del dispositivo médico', 'category', false, false, 'CIE-11'),
('XE1TF', 'Componente celular del dispositivo médico', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;