BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XM3WL0', 'Ornidazol', 'category', false, false, 'CIE-11'),
('XM3E43', 'Oxofenarsina', 'category', false, false, 'CIE-11'),
('XM45H6', 'Estibogluconato', 'category', false, false, 'CIE-11'),
('XM0CL7', 'Isetionato de estilbamidina', 'category', false, false, 'CIE-11'),
('XM05U5', 'Teclozan', 'category', false, false, 'CIE-11'),
('XM6XS3', 'Tricomonacidas', 'category', false, false, 'CIE-11'),
('XM5R30', 'Triparsamida', 'category', false, false, 'CIE-11'),
('XM7BM9', 'Derivados de nitroimidazol', 'category', false, false, 'CIE-11'),
('XM4HZ1', 'Azanidazol', 'category', false, false, 'CIE-11'),
('XM5LH9', 'Nimorazol', 'category', false, false, 'CIE-11'),
('XM98K0', 'Secnidazol', 'category', false, false, 'CIE-11'),
('XM0JG6', 'Benznidazol', 'category', false, false, 'CIE-11'),
('XM61Z9', 'Propenidazole', 'category', false, false, 'CIE-11'),
('XM5VX1', 'Fexinidazol', 'category', false, false, 'CIE-11'),
('XM4RW6', 'Derivados de dicloroacetamida', 'category', false, false, 'CIE-11'),
('XM7AM3', 'Diloxanida', 'category', false, false, 'CIE-11'),
('XM9H76', 'Clefamida', 'category', false, false, 'CIE-11'),
('XM3PL8', 'Etofamida', 'category', false, false, 'CIE-11'),
('XM4787', 'Compuestos de arsénico', 'category', false, false, 'CIE-11'),
('XM09B5', 'Arstinol', 'category', false, false, 'CIE-11'),
('XM0A09', 'Difetarsona', 'category', false, false, 'CIE-11'),
('XM6V40', 'Glicobiarsol', 'category', false, false, 'CIE-11'),
('XM64G7', 'Compuestos de antimonio', 'category', false, false, 'CIE-11'),
('XM2TP0', 'Antimoniato de meglumina', 'category', false, false, 'CIE-11'),
('XM2284', 'Estibogluconato de sodio', 'category', false, false, 'CIE-11'),
('XM3E78', 'Akritoin', 'category', false, false, 'CIE-11'),
('XM8LB8', 'Arsenical anti infeccioso', 'category', false, false, 'CIE-11'),
('XM44A9', 'Metales pesados anti infecciosos', 'category', false, false, 'CIE-11'),
('XM8CX5', 'Anti infecciosos de antimonio', 'category', false, false, 'CIE-11'),
('XM69W3', 'Tartrato de antimonio y potasio (sodio)', 'category', false, false, 'CIE-11'),
('XM2AH2', 'Tartrato de antimonio', 'category', false, false, 'CIE-11'),
('XM1Z32', 'Medicamentos antiparasitarios especificados', 'category', false, false, 'CIE-11'),
('XM0L93', 'Arsfenamina (plata)', 'category', false, false, 'CIE-11'),
('XM12U8', 'Sales de bismuto antiinfecciosas.', 'category', false, false, 'CIE-11'),
('XM7A39', 'Sales de bismuto subsalicilato', 'category', false, false, 'CIE-11'),
('XM8SJ3', 'Bitionol', 'category', false, false, 'CIE-11'),
('XM7PV2', 'Chiniofon', 'category', false, false, 'CIE-11'),
('XM6DH1', 'Cinoxacina', 'category', false, false, 'CIE-11'),
('XM0402', 'Croconazol', 'category', false, false, 'CIE-11'),
('XM1YN6', 'Diclorohidroxiquinolina', 'category', false, false, 'CIE-11'),
('XM59A1', 'Desinfectante intestinal', 'category', false, false, 'CIE-11'),
('XM4923', 'Flumequina', 'category', false, false, 'CIE-11'),
('XM7BY8', 'Flunidazol', 'category', false, false, 'CIE-11'),
('XM4XE9', 'Fluorocitosina', 'category', false, false, 'CIE-11'),
('XM6UT2', 'Hexetidina', 'category', false, false, 'CIE-11'),
('XM74Y8', 'Yodobismitol', 'category', false, false, 'CIE-11'),
('XM80M5', 'Yodoquinol', 'category', false, false, 'CIE-11'),
('XM7T64', 'Anti infecciosos de plomo', 'category', false, false, 'CIE-11'),
('XM0FS9', 'Mafarsen', 'category', false, false, 'CIE-11'),
('XM0RW4', 'Mercurio, mercurial, mercúrico, mercurioso anti infeccioso sistémico', 'category', false, false, 'CIE-11'),
('XM08P3', 'Neoarsfenamina', 'category', false, false, 'CIE-11'),
('XM0M05', 'Neosilversalvarsan', 'category', false, false, 'CIE-11'),
('XM39N3', 'Nifuratel', 'category', false, false, 'CIE-11'),
('XM70Q8', 'Ácido oxolínico', 'category', false, false, 'CIE-11'),
('XM10R8', 'Tartrato de antimonio y potasio', 'category', false, false, 'CIE-11'),
('XM8WV6', 'Quiniobina', 'category', false, false, 'CIE-11'),
('XM8U22', 'Quinolina (derivados)', 'category', false, false, 'CIE-11'),
('XM3VB9', 'Salvarsan 606 (neosilver) (plata)', 'category', false, false, 'CIE-11'),
('XM6260', 'Plata salvarsan', 'category', false, false, 'CIE-11'),
('XM3DB2', 'Cacodilato de sodio antiinfeccioso', 'category', false, false, 'CIE-11'),
('XM9L57', 'Estovarsal', 'category', false, false, 'CIE-11'),
('XM80F6', 'Sulfarsfenamina', 'category', false, false, 'CIE-11'),
('XM96Q1', 'Tártaro emético', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XM6A32', 'Tartrato de antimonio (anti infeccioso)', 'category', false, false, 'CIE-11'),
('XM9KU4', 'Tiobismol', 'category', false, false, 'CIE-11'),
('XM9UP9', 'Tiocarbarsona', 'category', false, false, 'CIE-11'),
('XM5VM3', 'Tin anti-infecciosos', 'category', false, false, 'CIE-11'),
('XM2SB0', 'Antiinfeccioso urinario', 'category', false, false, 'CIE-11'),
('XM2HD6', 'Emetina', 'category', false, false, 'CIE-11'),
('XM5GF4', 'Fanquinona', 'category', false, false, 'CIE-11'),
('XM9VB9', 'Mepacrina', 'category', false, false, 'CIE-11'),
('XM5RX3', 'Tenonitrozol', 'category', false, false, 'CIE-11'),
('XM28N6', 'Dehidroemetina', 'category', false, false, 'CIE-11'),
('XM5WJ8', 'Fumagilina', 'category', false, false, 'CIE-11'),
('XM84S6', 'Nitazoxanida', 'category', false, false, 'CIE-11'),
('XM9JL2', 'Eflornitina', 'category', false, false, 'CIE-11'),
('XM2NT3', 'Alantolactona', 'category', false, false, 'CIE-11'),
('XM1PP4', 'Anfotalida', 'category', false, false, 'CIE-11'),
('XM8LU8', 'Antiolimina', 'category', false, false, 'CIE-11'),
('XM95R7', 'Antihelmíntico antiinfeccioso', 'category', false, false, 'CIE-11'),
('XM43K9', 'Medicamento antifilaria', 'category', false, false, 'CIE-11'),
('XM4EC0', 'Antihelmínticos', 'category', false, false, 'CIE-11'),
('XM9637', 'Medicamento anti anquilostoma', 'category', false, false, 'CIE-11'),
('XM16G5', 'Medicamento anti nematodes', 'category', false, false, 'CIE-11'),
('XM2078', 'Medicamento anti platelmintos', 'category', false, false, 'CIE-11'),
('XM60W7', 'Medicamento anti esquistosomas', 'category', false, false, 'CIE-11'),
('XM6500', 'Medicamento anti tenias', 'category', false, false, 'CIE-11'),
('XM5273', 'Medicamento anti gusanos látigo', 'category', false, false, 'CIE-11'),
('XM7QL4', 'Ascaridol', 'category', false, false, 'CIE-11'),
('XM9GK4', 'Aspidio (oleorresina)', 'category', false, false, 'CIE-11'),
('XM3JR4', 'Derivados de bencimidazol', 'category', false, false, 'CIE-11'),
('XM3GX0', 'Mebendazol', 'category', false, false, 'CIE-11'),
('XM0CU8', 'Tiabendazol', 'category', false, false, 'CIE-11'),
('XM79J1', 'Albendazol', 'category', false, false, 'CIE-11'),
('XM8RG6', 'Flubendazol', 'category', false, false, 'CIE-11'),
('XM5XC2', 'Fenbendazol', 'category', false, false, 'CIE-11'),
('XM7982', 'Ciclobendazol', 'category', false, false, 'CIE-11'),
('XM3667', 'Befenio', 'category', false, false, 'CIE-11'),
('XM6FY4', 'Bitionol antihelmíntico', 'category', false, false, 'CIE-11'),
('XM5L27', 'Bitoscanato', 'category', false, false, 'CIE-11'),
('XM4WY5', 'Chenopodium', 'category', false, false, 'CIE-11'),
('XM0ZD3', 'Diclorofeno', 'category', false, false, 'CIE-11'),
('XM8C12', 'Yoduro de ditiazanina', 'category', false, false, 'CIE-11'),
('XM2RX7', 'Filix mas', 'category', false, false, 'CIE-11'),
('XM05F2', 'Ivermectina', 'category', false, false, 'CIE-11'),
('XM5W42', 'Levamisol', 'category', false, false, 'CIE-11'),
('XM9Z70', 'Lucantona', 'category', false, false, 'CIE-11'),
('XM4SZ4', 'Extracto de helecho macho', 'category', false, false, 'CIE-11'),
('XM2034', 'Niclosamida', 'category', false, false, 'CIE-11'),
('XM2WY0', 'Niridazol', 'category', false, false, 'CIE-11'),
('XM7NR1', 'Nitrotiazol', 'category', false, false, 'CIE-11'),
('XM5JZ6', 'Oxamniquina', 'category', false, false, 'CIE-11'),
('XM9FH0', 'Tanato de peletierina', 'category', false, false, 'CIE-11'),
('XM5ZH0', 'Percloroetileno medicinal', 'category', false, false, 'CIE-11'),
('XM3T27', 'Pink root', 'category', false, false, 'CIE-11'),
('XM8205', 'Pracicuantel', 'category', false, false, 'CIE-11'),
('XM7SZ5', 'Extracto de semilla de calabaza', 'category', false, false, 'CIE-11'),
('XM5PX0', 'Pirvinio', 'category', false, false, 'CIE-11'),
('XM9KL1', 'Santonina', 'category', false, false, 'CIE-11'),
('XM3FE9', 'Spigelia (raíz)', 'category', false, false, 'CIE-11'),
('XM5VV1', 'Estibofeno', 'category', false, false, 'CIE-11'),
('XM4GA8', 'Teroxaleno', 'category', false, false, 'CIE-11'),
('XM7PN4', 'Tetracloroetileno medicinal', 'category', false, false, 'CIE-11'),
('XM93X2', 'Tetramisol', 'category', false, false, 'CIE-11'),
('XM2621', 'Estibamina de urea', 'category', false, false, 'CIE-11'),
('XM5C18', 'Veroxil', 'category', false, false, 'CIE-11'),
('XM3AT4', 'Viprinio', 'category', false, false, 'CIE-11'),
('XM4555', 'Epazote, americana', 'category', false, false, 'CIE-11'),
('XM6U56', 'Derivados de tetrahidropirimidina', 'category', false, false, 'CIE-11'),
('XM90N4', 'Pirantel', 'category', false, false, 'CIE-11'),
('XM05V2', 'Oxantel', 'category', false, false, 'CIE-11'),
('XM9H59', 'Metrifonato', 'category', false, false, 'CIE-11'),
('XM7VW8', 'Triclabendazol', 'category', false, false, 'CIE-11'),
('XM7F99', 'Moxidectina', 'category', false, false, 'CIE-11'),
('XM0399', 'Desaspidina', 'category', false, false, 'CIE-11'),
('XM9DZ4', 'Tetrabenacina', 'category', false, false, 'CIE-11'),
('XM3BR4', 'Memantina', 'category', false, false, 'CIE-11'),
('XM1CG4', 'Hoja de Ginkgo', 'category', false, false, 'CIE-11'),
('XM9VG8', 'Tirilazad', 'category', false, false, 'CIE-11'),
('XM9Z74', 'Riluzol', 'category', false, false, 'CIE-11'),
('XM4ER7', 'Xaliproden', 'category', false, false, 'CIE-11'),
('XM5PS1', 'Fampridina', 'category', false, false, 'CIE-11'),
('XM2AL2', 'Tafamidis', 'category', false, false, 'CIE-11'),
('XM1LU9', 'Laquinimod', 'category', false, false, 'CIE-11'),
('XM3QR7', 'Pitolisant', 'category', false, false, 'CIE-11'),
('XM3FT2', 'Patisiran', 'category', false, false, 'CIE-11'),
('XM1KZ8', 'Edaravone', 'category', false, false, 'CIE-11'),
('XM7DT3', 'Inotersen', 'category', false, false, 'CIE-11'),
('XM8MX8', 'Valbenazina', 'category', false, false, 'CIE-11'),
('XM87M0', 'Aducanumab', 'category', false, false, 'CIE-11'),
('XM5UK9', 'Deutetrabenazina', 'category', false, false, 'CIE-11'),
('XM4F26', 'Arimoclomol', 'category', false, false, 'CIE-11'),
('XM4KS4', 'Agentes antiinflamatorios y antirreumáticos no esteroides', 'category', false, false, 'CIE-11'),
('XM7W23', 'Butilpirazolidinas', 'category', false, false, 'CIE-11'),
('XM8HN0', 'Fenilbutazona', 'category', false, false, 'CIE-11'),
('XM8P27', 'Mofebutazonea', 'category', false, false, 'CIE-11'),
('XM12M5', 'Oxifenbutazona', 'category', false, false, 'CIE-11'),
('XM8X86', 'Clofezona', 'category', false, false, 'CIE-11'),
('XM4H41', 'Kebuzona', 'category', false, false, 'CIE-11'),
('XM74U4', 'Derivados del ácido acético y sustancias afines', 'category', false, false, 'CIE-11'),
('XM7497', 'Indometacina', 'category', false, false, 'CIE-11'),
('XM24W2', 'Sulindac', 'category', false, false, 'CIE-11'),
('XM97N5', 'Tolmetina', 'category', false, false, 'CIE-11'),
('XM92G8', 'Zomepirac', 'category', false, false, 'CIE-11'),
('XM2AU1', 'Diclofenac', 'category', false, false, 'CIE-11'),
('XM2186', 'Etodolac', 'category', false, false, 'CIE-11'),
('XM8M52', 'Ketorolac', 'category', false, false, 'CIE-11'),
('XM6KJ8', 'Bumadizona', 'category', false, false, 'CIE-11'),
('XM12Q6', 'Lonazolac', 'category', false, false, 'CIE-11'),
('XM2AX1', 'Fentiazaco', 'category', false, false, 'CIE-11'),
('XM3458', 'Acemetacina', 'category', false, false, 'CIE-11'),
('XM7K80', 'Difenpiramida', 'category', false, false, 'CIE-11'),
('XM7CA3', 'Oxametacina', 'category', false, false, 'CIE-11'),
('XM2P51', 'Proglumetacina', 'category', false, false, 'CIE-11'),
('XM5W40', 'Aceclofenaco', 'category', false, false, 'CIE-11'),
('XM7AB1', 'Bufexamac', 'category', false, false, 'CIE-11'),
('XM9S89', 'Alclofenaco', 'category', false, false, 'CIE-11'),
('XM8G95', 'Ibufenac', 'category', false, false, 'CIE-11'),
('XM0UL8', 'Oxicams', 'category', false, false, 'CIE-11'),
('XM9MD6', 'Piroxican', 'category', false, false, 'CIE-11'),
('XM7WP9', 'Droxicam', 'category', false, false, 'CIE-11'),
('XM3X14', 'Lornoxicam', 'category', false, false, 'CIE-11'),
('XM1XY0', 'Meloxicam', 'category', false, false, 'CIE-11'),
('XM83U4', 'Isoxicam', 'category', false, false, 'CIE-11'),
('XM1867', 'Tenoxicam', 'category', false, false, 'CIE-11'),
('XM2S54', 'Derivados del ácido propiónico', 'category', false, false, 'CIE-11'),
('XM2RR6', 'Ibuprofeno', 'category', false, false, 'CIE-11'),
('XM1KL8', 'Naproxeno', 'category', false, false, 'CIE-11'),
('XM63J5', 'Ketoprofeno', 'category', false, false, 'CIE-11'),
('XM7BS7', 'Fenoprofeno', 'category', false, false, 'CIE-11'),
('XM2N63', 'Suprofeno', 'category', false, false, 'CIE-11'),
('XM8VP8', 'Flurbiprofeno', 'category', false, false, 'CIE-11'),
('XM0WQ1', 'Ácido tiaprofénico', 'category', false, false, 'CIE-11'),
('XM9694', 'Oxaprozina', 'category', false, false, 'CIE-11'),
('XM1918', 'Ibuproxam', 'category', false, false, 'CIE-11'),
('XM4W51', 'Fenbufeno', 'category', false, false, 'CIE-11'),
('XM7F06', 'Benoxaprofeno', 'category', false, false, 'CIE-11'),
('XM4KX7', 'Pirprofeno', 'category', false, false, 'CIE-11'),
('XM3G14', 'Indoprofeno', 'category', false, false, 'CIE-11'),
('XM32V2', 'Dexibuprofeno', 'category', false, false, 'CIE-11'),
('XM4FK3', 'Flunoxaprofeno', 'category', false, false, 'CIE-11'),
('XM1W06', 'Alminoprofeno', 'category', false, false, 'CIE-11'),
('XM1ZF2', 'Dexketoprofeno', 'category', false, false, 'CIE-11'),
('XM9ES5', 'Naproxcinod', 'category', false, false, 'CIE-11'),
('XM8GM3', 'Carprofeno', 'category', false, false, 'CIE-11'),
('XM9DC7', 'Fenamatos', 'category', false, false, 'CIE-11'),
('XM6Q83', 'Ácido mefenámico', 'category', false, false, 'CIE-11'),
('XM31G8', 'Ácido flufenámico', 'category', false, false, 'CIE-11'),
('XM3W40', 'Ácido meclofenámico', 'category', false, false, 'CIE-11'),
('XM9WQ9', 'Ácido tolfenámico', 'category', false, false, 'CIE-11'),
('XM16D6', 'Coxibs', 'category', false, false, 'CIE-11'),
('XM63D2', 'Celecoxib', 'category', false, false, 'CIE-11'),
('XM70K9', 'Rofecoxib', 'category', false, false, 'CIE-11'),
('XM4SK9', 'Valdecoxib', 'category', false, false, 'CIE-11'),
('XM96Q4', 'Parecoxib', 'category', false, false, 'CIE-11'),
('XM2W58', 'Etoricoxib', 'category', false, false, 'CIE-11'),
('XM0BC7', 'Lumiracoxib', 'category', false, false, 'CIE-11'),
('XM1N20', 'Polmacoxib', 'category', false, false, 'CIE-11'),
('XM7AM9', 'Glafenina', 'category', false, false, 'CIE-11'),
('XM3WB0', 'Floctafenina', 'category', false, false, 'CIE-11'),
('XM8WS4', 'Nabumetona', 'category', false, false, 'CIE-11'),
('XM6SW5', 'Azapropazona', 'category', false, false, 'CIE-11'),
('XM6SR1', 'Glucosamina', 'category', false, false, 'CIE-11'),
('XM73Q0', 'Benzidamina', 'category', false, false, 'CIE-11'),
('XM8GX7', 'Proquazona', 'category', false, false, 'CIE-11'),
('XM5C49', 'Nimesulida', 'category', false, false, 'CIE-11'),
('XM37T1', 'Feprazona', 'category', false, false, 'CIE-11'),
('XM4KV5', 'Ácido niflúmico', 'category', false, false, 'CIE-11'),
('XM5Z51', 'Polisulfato de glucosaminoglicano', 'category', false, false, 'CIE-11'),
('XM9Z19', 'Orgoteína', 'category', false, false, 'CIE-11'),
('XM51H0', 'Diacereína', 'category', false, false, 'CIE-11'),
('XM1019', 'Morniflumato', 'category', false, false, 'CIE-11'),
('XM7Z95', 'Tenidap', 'category', false, false, 'CIE-11'),
('XM4L54', 'Oxaceprol', 'category', false, false, 'CIE-11'),
('XM9352', 'Sulfato de condroitina', 'category', false, false, 'CIE-11'),
('XM0H27', 'Aguacate y aceite de soya, insaponificables', 'category', false, false, 'CIE-11'),
('XM9C36', 'Etoxazeno', 'category', false, false, 'CIE-11'),
('XM85Z4', 'Fenflumizol', 'category', false, false, 'CIE-11'),
('XM46B3', 'Antirreumático analgésico', 'category', false, false, 'CIE-11'),
('XM8DE1', 'Antiflogístico', 'category', false, false, 'CIE-11'),
('XM95N2', 'Antireumáticos', 'category', false, false, 'CIE-11'),
('XM8526', 'Aurotioglicanida', 'category', false, false, 'CIE-11'),
('XM4XH9', 'Farnesil', 'category', false, false, 'CIE-11'),
('XM4DJ6', 'Aurotiosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM3LE3', 'Preparaciones de oro', 'category', false, false, 'CIE-11'),
('XM9ZC2', 'Aurotiomalato de sodio', 'category', false, false, 'CIE-11'),
('XM5HT1', 'Auranofin', 'category', false, false, 'CIE-11'),
('XM1MX1', 'Aurotioglucosa', 'category', false, false, 'CIE-11'),
('XM28Y9', 'Aurotioprol', 'category', false, false, 'CIE-11'),
('XM8CF5', 'Aurotiosulfato de sodio', 'category', false, false, 'CIE-11'),
('XM0VQ7', 'Bucilamina', 'category', false, false, 'CIE-11'),
('XM5L52', 'Oxicincofeno', 'category', false, false, 'CIE-11'),
('XM1QA0', 'Penicillamina', 'category', false, false, 'CIE-11'),
('XM4G06', 'Acido acetilsalicílico', 'category', false, false, 'CIE-11'),
('XM0XT0', 'Carbaspirina', 'category', false, false, 'CIE-11'),
('XM0GX7', 'Salicilato de colina', 'category', false, false, 'CIE-11'),
('XM72N6', 'Fiorinal', 'category', false, false, 'CIE-11'),
('XM6PW4', 'Salicilato de sodio', 'category', false, false, 'CIE-11'),
('XM4WV7', 'Salicilamida', 'category', false, false, 'CIE-11'),
('XM68K3', 'Salsalato', 'category', false, false, 'CIE-11'),
('XM5UX6', 'Diflunisal', 'category', false, false, 'CIE-11'),
('XM2JA1', 'Aloxiprina', 'category', false, false, 'CIE-11'),
('XM3ZP5', 'Etenzamida', 'category', false, false, 'CIE-11'),
('XM49Y6', 'Salicilato de morfolina', 'category', false, false, 'CIE-11'),
('XM9TC0', 'Dipirocetilo', 'category', false, false, 'CIE-11'),
('XM1UA7', 'Benorilato', 'category', false, false, 'CIE-11'),
('XM2CV1', 'Salicilato de potasio', 'category', false, false, 'CIE-11'),
('XM1DD2', 'Guacetisal', 'category', false, false, 'CIE-11'),
('XM4TV1', 'Carbasalato de calcio', 'category', false, false, 'CIE-11'),
('XM5UF9', 'Salicilato de imidazol', 'category', false, false, 'CIE-11'),
('XM8F16', 'Salicilato de calcio', 'category', false, false, 'CIE-11'),
('XM5X48', 'Salicilato de carbetilo', 'category', false, false, 'CIE-11'),
('XM6M40', 'Salicilato de magnesio', 'category', false, false, 'CIE-11'),
('XM8FA6', 'Tiosalicilato de sodio', 'category', false, false, 'CIE-11'),
('XM7045', 'Aminofenazona', 'category', false, false, 'CIE-11'),
('XM7840', 'Pirosol analgésico', 'category', false, false, 'CIE-11'),
('XM22E9', 'Antipirina', 'category', false, false, 'CIE-11'),
('XM60M2', 'Analgésicos medicinales de alquitrán de hulla', 'category', false, false, 'CIE-11'),
('XM4T98', 'Dipirona', 'category', false, false, 'CIE-11'),
('XM2FJ5', 'Isopropil aminofenazona', 'category', false, false, 'CIE-11'),
('XM8762', 'Miocrisina', 'category', false, false, 'CIE-11'),
('XM4YB4', 'Nifenazona', 'category', false, false, 'CIE-11'),
('XM53Q3', 'Noramidopirina', 'category', false, false, 'CIE-11'),
('XM6GV7', 'Propifenazona', 'category', false, false, 'CIE-11'),
('XM5H28', 'Derivados de la pirazolona', 'category', false, false, 'CIE-11'),
('XM5L33', 'Pirazolona analgesico', 'category', false, false, 'CIE-11'),
('XM0K68', 'Ramifenazona', 'category', false, false, 'CIE-11'),
('XM1SG0', 'Sulfamidopirina', 'category', false, false, 'CIE-11'),
('XM9CV5', 'Suxibuzona', 'category', false, false, 'CIE-11'),
('XM5DJ7', 'Acetaminofeno', 'category', false, false, 'CIE-11'),
('XM75Y5', 'Derivados del para-aminofenol', 'category', false, false, 'CIE-11'),
('XM43A6', 'Fenacetina', 'category', false, false, 'CIE-11'),
('XM7HP8', 'Bucetina', 'category', false, false, 'CIE-11'),
('XM8QF6', 'Propacetamol', 'category', false, false, 'CIE-11'),
('XM24R8', 'Acetaminosalol', 'category', false, false, 'CIE-11'),
('XM45S5', 'Acetanilida', 'category', false, false, 'CIE-11'),
('XM4T97', 'Bromo-seltzer', 'category', false, false, 'CIE-11'),
('XM2XD8', 'Acetilfenilhidrazina', 'category', false, false, 'CIE-11'),
('XM3J63', 'Clonixina', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;