BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('JB24.3', 'Parto múltiple mediante una combinación de métodos, con cesárea', 'category', false, false, 'CIE-11'),
('JB24.Y', 'Otro parto múltiple especificado', 'category', false, false, 'CIE-11'),
('JB24.Z', 'Parto múltiple, sin especificación', 'category', false, false, 'CIE-11'),
('JB2Z', 'Parto, sin especificación', 'category', false, false, 'CIE-11'),
('JB40', 'Infecciones en el puerperio', 'category', false, false, 'CIE-11'),
('JB40.0', 'Sepsis puerperal', 'category', false, false, 'CIE-11'),
('JB40.1', 'Infección de herida quirúrgica obstétrica', 'category', false, false, 'CIE-11'),
('JB40.2', 'Otra infección del aparato genital después del parto', 'category', false, false, 'CIE-11'),
('JB40.3', 'Infección del aparato urinario después del parto', 'category', false, false, 'CIE-11'),
('JB40.4', 'Pirexia de origen desconocido después del parto', 'category', false, false, 'CIE-11'),
('JB40.Y', 'Otras infecciones especificadas en el puerperio', 'category', false, false, 'CIE-11'),
('JB40.Z', 'Infecciones en el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB41', 'Complicaciones venosas en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.0', 'Tromboflebitis superficial en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.1', 'Flebotrombosis profunda en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.2', 'Hemorroides en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.3', 'Trombosis venosa cerebral en el puerperio', 'category', false, false, 'CIE-11'),
('JB41.Y', 'Otras complicaciones venosas en el puerperio especificadas', 'category', false, false, 'CIE-11'),
('JB41.Z', 'Complicaciones venosas en el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB42', 'Embolia obstétrica', 'category', false, false, 'CIE-11'),
('JB42.0', 'Embolia gaseosa obstétrica', 'category', false, false, 'CIE-11'),
('JB42.1', 'Embolia de líquido amniótico', 'category', false, false, 'CIE-11'),
('JB42.2', 'Tromboembolia obstétrica', 'category', false, false, 'CIE-11'),
('JB42.3', 'Embolia piémica o séptica obstétrica', 'category', false, false, 'CIE-11'),
('JB42.Y', 'Otra embolia obstétrica especificada', 'category', false, false, 'CIE-11'),
('JB42.Z', 'Embolia obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('JB43', 'Complicaciones de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.0', 'Complicaciones pulmonares de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.1', 'Complicaciones cardíacas de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.2', 'Complicaciones del sistema nervioso central durante el puerperio debidas a la anestesia', 'category', false, false, 'CIE-11'),
('JB43.3', 'Cefalea inducida por la anestesia raquídea o epidural durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.4', 'Otras complicaciones de la anestesia raquídea o epidural durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.5', 'Intubación fallida o difícil durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.50', 'Intubación fallida durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.51', 'Intubación difícil durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.5Y', 'Otro(a)(s) intubación fallida o difícil durante el puerperio especificado(a)(s)', 'category', false, false, 'CIE-11'),
('JB43.5Z', 'Intubación fallida o difícil durante el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB43.6', 'Conciencia bajo anestesia general durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.Y', 'Otras complicaciones especificadas de la anestesia durante el puerperio', 'category', false, false, 'CIE-11'),
('JB43.Z', 'Complicaciones de la anestesia durante el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB44', 'Algunas complicaciones del puerperio especificadas', 'category', false, false, 'CIE-11'),
('JB44.0', 'Deshiscencia de la herida de la cesárea', 'category', false, false, 'CIE-11'),
('JB44.1', 'Dehiscencia de la herida obstétrica perineal', 'category', false, false, 'CIE-11'),
('JB44.2', 'Hematoma de herida obstétrica', 'category', false, false, 'CIE-11'),
('JB44.3', 'Cardiomiopatía en el puerperio', 'category', false, false, 'CIE-11'),
('JB44.4', 'Insuficiencia renal aguda postparto', 'category', false, false, 'CIE-11'),
('JB44.5', 'Tiroiditis posparto', 'category', false, false, 'CIE-11'),
('JB44.6', 'Osteomalacia puerperal', 'category', false, false, 'CIE-11'),
('JB44.Y', 'Otras complicaciones especificadas del puerperio', 'category', false, false, 'CIE-11'),
('JB44.Z', 'Complicaciones del puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB45', 'Infecciones de la mama asociadas con el parto', 'category', false, false, 'CIE-11'),
('JB45.0', 'Absceso de la mama asociado con el parto', 'category', false, false, 'CIE-11'),
('JB45.1', 'Mastitis no purulenta asociada con el parto', 'category', false, false, 'CIE-11'),
('JB45.Y', 'Otras infecciones de la mama especificadas asociadas con la maternidad', 'category', false, false, 'CIE-11'),
('JB45.Z', 'Infecciones de la mama asociadas con la maternidad, sin especificación', 'category', false, false, 'CIE-11'),
('JB46', 'Algunos trastornos especificados de la mama o la lactancia asociados con el parto', 'category', false, false, 'CIE-11'),
('JB46.0', 'Retracción del pezón asociada con el parto', 'category', false, false, 'CIE-11'),
('JB46.1', 'Pezón agrietado asociado con el parto', 'category', false, false, 'CIE-11'),
('JB46.2', 'Trastornos mamarios de otro tipo o no especificados asociados con el parto', 'category', false, false, 'CIE-11'),
('JB46.3', 'Agalactia', 'category', false, false, 'CIE-11'),
('JB46.4', 'Hipogalactia', 'category', false, false, 'CIE-11'),
('JB46.5', 'Lactancia suprimida', 'category', false, false, 'CIE-11'),
('JB46.6', 'Galactorrea', 'category', false, false, 'CIE-11'),
('JB46.7', 'Otros trastornos de la lactancia o los no especificados', 'category', false, false, 'CIE-11'),
('JB4Z', 'Complicaciones principalmente relacionadas con el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB60', 'Muerte obstétrica de causa no especificada', 'category', false, false, 'CIE-11'),
('JB61', 'Muerte materna debida a cualquier causa obstétrica que ocurre más de 42 días pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.0', 'Muerte por causa obstétrica directa que ocurre más de 42 días, pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.1', 'Muerte por causa obstétrica indirecta que ocurre más de 42 días, pero menos de un año después del parto.', 'category', false, false, 'CIE-11'),
('JB61.Z', 'Muerte por cualquier causa obstétrica que tiene lugar después de 42 días pero no más de un año después del parto o aborto, sin especificación', 'category', false, false, 'CIE-11'),
('JB62', 'Muerte debida a las secuelas de causas obstétricas', 'category', false, false, 'CIE-11'),
('JB62.0', 'Muerte por secuelas de causas obstétricas directas', 'category', false, false, 'CIE-11'),
('JB62.1', 'Muerte por secuelas de causas obstétricas indirectas', 'category', false, false, 'CIE-11'),
('JB62.Z', 'Muerte debida a las secuelas de una causa obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('JB63', 'Enfermedades infecciosas maternas clasificables en otra parte que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.0', 'Tuberculosis que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.00', 'Tuberculosis de la placenta', 'category', false, false, 'CIE-11'),
('JB63.0Y', 'Otra tuberculosis especificada que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.0Z', 'Tuberculosis que complica el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB63.1', 'Sífilis que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.2', 'Gonorrea que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.3', 'Otras infecciones con modo de transmisión predominantemente sexual que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.4', 'Hepatitis viral que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.5', 'Otras enfermedades virales que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6', 'Enfermedades causadas por protozoarios que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.60', 'Paludismo que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6Y', 'Otras enfermedades especificadas causadas por protozoarios que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.6Z', 'Enfermedades causadas por protozoarios que complican el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB63.7', 'Enfermedad por virus de la inmunodeficiencia humana que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.Y', 'Otras enfermedades infecciosas maternas especificadas clasificables en otra parte que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB63.Z', 'Enfermedades infecciosas maternas clasificables en otra parte que complican el embarazo, el parto o el puerperio, sin especificación', 'category', false, false, 'CIE-11'),
('JB64', 'Algunas enfermedades maternas clasificables en otra parte pero que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.0', 'Anemia que complica el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.1', 'Otras enfermedades de la sangre o de los órganos hematopoyéticos, o algunos trastornos de la función inmunitaria, que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.2', 'Enfermedades endocrinas, nutricionales o metabólicas que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.3', 'Enfermedades del sistema nervioso que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.4', 'Enfermedades del aparato circulatorio que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.5', 'Enfermedades del aparato respiratorio que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.6', 'Enfermedades del aparato digestivo que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.7', 'Enfermedades de la piel que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB64.8', 'Anomalía congénita que complica el embarazo', 'category', false, false, 'CIE-11'),
('JB64.Y', 'Otras enfermedades maternas especificadas clasificables en otra parte pero que complican el embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB65', 'Secuelas de complicación del embarazo, el parto o el puerperio', 'category', false, false, 'CIE-11'),
('JB6Y', 'Algunas otras condiciones obstétricas especificadas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('JB6Z', 'Condición obstétrica, sin especificación', 'category', false, false, 'CIE-11'),
('KA00', 'Feto o recién nacido afectado por condiciones de la madre que pueden no estar relacionadas con el embarazo en curso', 'category', false, false, 'CIE-11'),
('KA00.0', 'Feto o recién nacido afectado por trastornos hipertensivos de la madre', 'category', false, false, 'CIE-11'),
('KA00.1', 'Feto o recién nacido afectado por edema o proteinuria gestacional sin hipertensión', 'category', false, false, 'CIE-11'),
('KA00.2', 'Feto o recién nacido afectado por enfermedades del riñón o las vías urinarias en la madre', 'category', false, false, 'CIE-11'),
('KA00.3', 'Feto o recién nacido afectado por enfermedades |infecciosas de la madre', 'category', false, false, 'CIE-11'),
('KA00.4', 'Feto o recién nacido afectado por una enfermedad periodontal de la madre', 'category', false, false, 'CIE-11'),
('KA00.5', 'Feto o recién nacido afectado por una enfermedad respiratoria en la madre', 'category', false, false, 'CIE-11'),
('KA00.6', 'Feto o recién nacido afectado por un trastorno nutricional en la madre', 'category', false, false, 'CIE-11'),
('KA00.60', 'Feto o recién nacido afectado por desnutrición materna', 'category', false, false, 'CIE-11'),
('KA00.61', 'Feto o recién nacido afectado por sobrepeso u obesidad materna', 'category', false, false, 'CIE-11'),
('KA00.6Y', 'Feto o recién nacido afectado por otro trastorno nutricional especificado en la madre', 'category', false, false, 'CIE-11'),
('KA00.6Z', 'Feto o recién nacido afectado por un trastorno nutricional en la madre, sin especificación', 'category', false, false, 'CIE-11'),
('KA00.7', 'Feto o recién nacido afectado por un trastorno en la madre detectado en el análisis bioquímico de la sangre', 'category', false, false, 'CIE-11'),
('KA00.8', 'Feto o recién nacido afectado por una lesión traumática en la madre', 'category', false, false, 'CIE-11'),
('KA00.9', 'Feto o recién nacido afectado por quimioterapia de la madre', 'category', false, false, 'CIE-11'),
('KA00.A', 'Feto o recién nacido afectado por un procedimiento quirúrgico en la madre', 'category', false, false, 'CIE-11'),
('KA00.B', 'Feto o recién nacido afectado por anemia materna', 'category', false, false, 'CIE-11'),
('KA00.Y', 'Feto o recién nacido afectado por otros trastornos especificados de la madre que pueden no estar relacionados con el embarazo en curso', 'category', false, false, 'CIE-11'),
('KA00.Z', 'Feto o recién nacido afectado por trastornos de la madre que pueden no estar relacionados con el embarazo en curso, sin especificación', 'category', false, false, 'CIE-11'),
('KA01', 'Feto o recién nacido afectado por complicaciones maternas del embarazo', 'category', false, false, 'CIE-11'),
('KA01.0', 'Feto o recién nacido afectado por incompetencia del cuello uterino', 'category', false, false, 'CIE-11'),
('KA01.1', 'Feto o recién nacido afectado por ruptura prematura de membranas', 'category', false, false, 'CIE-11'),
('KA01.2', 'Feto o recién nacido afectado por oligohidramnios', 'category', false, false, 'CIE-11'),
('KA01.3', 'Feto o recién nacido afectado por polihidramnios', 'category', false, false, 'CIE-11'),
('KA01.4', 'Feto o recién nacido afectado por embarazo ectópico', 'category', false, false, 'CIE-11'),
('KA01.5', 'Feto o recién nacido afectado por un embarazo múltiple', 'category', false, false, 'CIE-11'),
('KA01.6', 'Feto o recién nacido afectado por la muerte de la madre', 'category', false, false, 'CIE-11'),
('KA01.7', 'Feto o recién nacido afectado por una presentación anormal antes del parto', 'category', false, false, 'CIE-11'),
('KA01.8', 'Feto o recién nacido afectado por pérdida de sangre materna', 'category', false, false, 'CIE-11'),
('KA01.Y', 'Feto o recién nacido afectado por otra complicación materna especificada del embarazo', 'category', false, false, 'CIE-11'),
('KA01.Z', 'Feto o recién nacido afectado por complicación materna del embarazo, sin especificación', 'category', false, false, 'CIE-11'),
('KA02', 'Feto o recién nacido afectado por complicaciones de la placenta', 'category', false, false, 'CIE-11'),
('KA02.0', 'Feto o recién nacido afectado por placenta previa', 'category', false, false, 'CIE-11'),
('KA02.1', 'Feto o recién nacido afectado por edema placentario o una placenta grande', 'category', false, false, 'CIE-11'),
('KA02.2', 'Feto o recién nacido afectado por infarto placentario', 'category', false, false, 'CIE-11'),
('KA02.3', 'Feto o recién nacido afectado por insuficiencia placentaria o placenta pequeña', 'category', false, false, 'CIE-11'),
('KA02.4', 'Feto o recién nacido afectado por síndromes de transfusión placentaria', 'category', false, false, 'CIE-11'),
('KA02.Y', 'Feto o recién nacido afectado por otra complicación especificada de la placenta', 'category', false, false, 'CIE-11'),
('KA02.Z', 'Feto o recién nacido afectado por complicación de la placenta, sin especificación', 'category', false, false, 'CIE-11'),
('KA03', 'Feto o recién nacido afectado por complicaciones del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.0', 'Feto o recién nacido afectado por prolapso del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.1', 'Feto o recién nacido afectado por otro tipo de compresión del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.2', 'Feto o recién nacido afectado por una anomalía de la longitud del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.20', 'Feto o recién nacido afectado por cordón umbilical corto', 'category', false, false, 'CIE-11'),
('KA03.21', 'Feto o recién nacido afectado por cordón umbilical largo', 'category', false, false, 'CIE-11'),
('KA03.2Y', 'Feto o recién nacido afectado por otra anomalía especificada de la longitud del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.2Z', 'Feto y recién nacido afectado por una anomalía de la longitud del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('KA03.3', 'Feto o recién nacido afectado por vasa previa', 'category', false, false, 'CIE-11'),
('KA03.4', 'Feto o recién nacido afectado por una lesión traumática del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.Y', 'Feto o recién nacido afectado por otra complicación especificada del cordón umbilical', 'category', false, false, 'CIE-11'),
('KA03.Z', 'Feto y recién nacido afectado por complicación del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('KA04', 'Feto o recién nacido afectado por otras anormalidades de las membranas', 'category', false, false, 'CIE-11'),
('KA04.0', 'Feto o recién nacido afectado por corioamnionitis', 'category', false, false, 'CIE-11'),
('KA04.1', 'Feto o recién nacido afectado por el síndrome de banda amniótica', 'category', false, false, 'CIE-11'),
('KA04.Y', 'Feto o recién nacido afectado por otras anormalidades especificadas de las membranas', 'category', false, false, 'CIE-11'),
('KA04.Z', 'Feto o recién nacido afectado por otras anormalidades de las membranas, sin especificación', 'category', false, false, 'CIE-11'),
('KA05', 'Feto o recién nacido afectado por ciertas complicaciones del trabajo de parto y el período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.0', 'Feto o recién nacido afectado por un parto o una extracción de nalgas', 'category', false, false, 'CIE-11'),
('KA05.1', 'Feto o recién nacido afectado por otra mala presentación, mala posición o desproporción durante el trabajo de parto y el período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.2', 'Feto o recién nacido afectado por parto con fórceps', 'category', false, false, 'CIE-11'),
('KA05.3', 'Feto o recién nacido afectado por parto asistido con extractor al vacío', 'category', false, false, 'CIE-11'),
('KA05.4', 'Feto o recién nacido afectado por cesárea', 'category', false, false, 'CIE-11'),
('KA05.5', 'Feto o recién nacido afectado por un parto precipitado', 'category', false, false, 'CIE-11'),
('KA05.6', 'Feto o recién nacido afectado por contracciones uterinas anormales', 'category', false, false, 'CIE-11'),
('KA05.7', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino', 'category', false, false, 'CIE-11'),
('KA05.70', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino antes del parto', 'category', false, false, 'CIE-11'),
('KA05.71', 'Feto o recién nacido afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino durante el parto', 'category', false, false, 'CIE-11'),
('KA05.7Z', 'Feto o recién nacido que está afectado por una anomalía de la frecuencia o el ritmo cardíaco fetal intrauterino, sin especificación', 'category', false, false, 'CIE-11'),
('KA05.8', 'Expulsión de meconio durante el parto', 'category', false, false, 'CIE-11'),
('KA05.Y', 'Feto o recién nacido que efectiva o presuntamente está afectado por otras complicaciones especificadas durante el trabajo de parto y período expulsivo', 'category', false, false, 'CIE-11'),
('KA05.Z', 'Feto y recién nacido que efectiva o presuntamente está afectado por otras complicaciones durante el trabajo de parto y período expulsivo, sin especificación', 'category', false, false, 'CIE-11'),
('KA06', 'Feto o recién nacido afectado por sustancias nocivas transmitidas por la placenta o la leche materna', 'category', false, false, 'CIE-11'),
('KA06.0', 'Feto o recién nacido afectado por anestesia o analgesia materna durante el embarazo, el trabajo de parto o el período expulsivo', 'category', false, false, 'CIE-11'),
('KA06.1', 'Feto o recién nacido afectado por el tabaquismo de la madre', 'category', false, false, 'CIE-11'),
('KA06.2', 'Feto o recién nacido afectado por el consumo de alcohol de la madre', 'category', false, false, 'CIE-11'),
('KA06.3', 'Feto o recién nacido afectado por el consumo de drogas de la madre', 'category', false, false, 'CIE-11'),
('KA06.4', 'Feto o recién nacido afectado por el consumo materno de nutrientes químicos', 'category', false, false, 'CIE-11'),
('KA06.5', 'Feto o recién nacido afectado por la exposición materna a sustancias químicas ambientales', 'category', false, false, 'CIE-11'),
('KA06.Y', 'Feto o recién nacido afectado por otro efecto nocivo transmitido a través de la placenta o de la leche materna', 'category', false, false, 'CIE-11'),
('KA06.Z', 'Feto o recién nacido afectado por un efecto nocivo transmitido a través de la placenta o de la leche materna, sin especificación', 'category', false, false, 'CIE-11'),
('KA07', 'Dermatosis neonatal debida a anticuerpos maternos', 'category', false, false, 'CIE-11'),
('KA07.0', 'Lupus eritematoso neonatal', 'category', false, false, 'CIE-11'),
('KA07.1', 'Pénfigo neonatal', 'category', false, false, 'CIE-11'),
('KA07.Y', 'Otra dermatosis neonatal especificada debida a anticuerpos maternos', 'category', false, false, 'CIE-11'),
('KA0Z', 'Feto o recién nacido afectado por factores maternos o por complicaciones del embarazo, el trabajo de parto o el parto, no especificados', 'category', false, false, 'CIE-11'),
('KA20', 'Trastornos del recién nacido relacionados con el retraso del crecimiento o desnutrición fetal', 'category', false, false, 'CIE-11'),
('KA20.0', 'Pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.00', 'Pequeño para la edad gestacional, simétrico', 'category', false, false, 'CIE-11'),
('KA20.01', 'Pequeño para la edad gestacional, con asimetría', 'category', false, false, 'CIE-11'),
('KA20.0Z', 'Pequeño para la edad gestacional, sin especificación', 'category', false, false, 'CIE-11'),
('KA20.1', 'Restricción del crecimiento intrauterino', 'category', false, false, 'CIE-11'),
('KA20.10', 'Retraso del crecimiento intrauterino asimétrico', 'category', false, false, 'CIE-11'),
('KA20.11', 'Retraso del crecimiento intrauterino simétrico', 'category', false, false, 'CIE-11'),
('KA20.12', 'Niño con retraso del crecimiento intrauterino y pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.1Y', 'Otro retraso del crecimiento intrauterino especificado', 'category', false, false, 'CIE-11'),
('KA20.1Z', 'Retraso del crecimiento intrauterino, sin especificación', 'category', false, false, 'CIE-11'),
('KA20.2', 'Desnutrición fetal intrauterina, sin mención de pequeño para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA20.Y', 'Otros trastornos especificados del recién nacido relacionados con el retraso del crecimiento o desnutrición del feto', 'category', false, false, 'CIE-11'),
('KA20.Z', 'Trastornos del recién nacido relacionados con el retraso del crecimiento o desnutrición del feto, sin especificación', 'category', false, false, 'CIE-11'),
('KA21', 'Trastornos del recién nacido relacionados con gestación corta o con bajo peso al nacer, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('KA21.0', 'Recién nacido con un peso al nacer extremadamente bajo', 'category', false, false, 'CIE-11'),
('KA21.00', 'Recién nacido con un peso al nacer extremadamente bajo, de 499 gramos o menos', 'category', false, false, 'CIE-11'),
('KA21.01', 'Recién nacido con un peso al nacer extremadamente bajo, de 500 a 749 gramos', 'category', false, false, 'CIE-11'),
('KA21.02', 'Recién nacido con un peso al nacer extremadamente bajo, de 750 a 999 gramos.', 'category', false, false, 'CIE-11'),
('KA21.0Z', 'Recién nacido con un peso al nacer extremadamente bajo, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.1', 'Recién nacido con un peso muy bajo al nacer', 'category', false, false, 'CIE-11'),
('KA21.10', 'Recién nacido con peso muy bajo al nacer, de 1000 a 1249 gramos', 'category', false, false, 'CIE-11'),
('KA21.11', 'Recién nacido con peso muy bajo al nacer, de 1250 a 1499 gramos', 'category', false, false, 'CIE-11'),
('KA21.1Z', 'Recién nacido con un peso muy bajo al nacer, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.2', 'Recién nacido con peso bajo al nacer', 'category', false, false, 'CIE-11'),
('KA21.20', 'Recién nacido con peso bajo al nacer, de 1500 a 1999 gramos', 'category', false, false, 'CIE-11'),
('KA21.21', 'Recién nacido con peso bajo al nacer, de 2000 a 2499 gramos', 'category', false, false, 'CIE-11'),
('KA21.2Z', 'Recién nacido con peso bajo al nacer, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.3', 'Prematuridad extrema del recién nacido', 'category', false, false, 'CIE-11'),
('KA21.30', 'Prematuridad extrema del recién nacido, edad gestacional de menos de 22 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.31', 'Prematuridad extrema del recién nacido, edad gestacional de 22 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.32', 'Prematuridad extrema del recién nacido, 23 semanas de gestación completas', 'category', false, false, 'CIE-11'),
('KA21.33', 'Prematuridad extrema del recién nacido, edad gestacional de 24 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.34', 'Prematuridad extrema del recién nacido, edad gestacional de 25 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.35', 'Prematuridad extrema del recién nacido, edad gestacional de 26 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.36', 'Prematuridad extrema del recién nacido, edad gestacional de 27 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.3Z', 'Prematuridad extrema del recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA21.4', 'Recién nacido prematuro', 'category', false, false, 'CIE-11'),
('KA21.40', 'Recién nacido prematuro, edad gestacional de 28 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.41', 'Recién nacido prematuro, edad gestacional de 29 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.42', 'Recién nacido prematuro, edad gestacional de 30 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.43', 'Recién nacido prematuro, edad gestacional de 31 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.44', 'Recién nacido prematuro, edad gestacional de 32 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.45', 'Recién nacido prematuro, edad gestacional de 33 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.46', 'Recién nacido prematuro, edad gestacional de 34 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.47', 'Recién nacido prematuro, edad gestacional de 35 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.48', 'Recién nacido prematuro, edad gestacional de 36 semanas completas', 'category', false, false, 'CIE-11'),
('KA21.4Z', 'Recién nacido prematuro, sin especificación', 'category', false, false, 'CIE-11'),
('KA22', 'Trastornos del recién nacido relacionados con una gestación prolongada o peso elevado al nacer', 'category', false, false, 'CIE-11'),
('KA22.0', 'Recién nacido excepcionalmente grande', 'category', false, false, 'CIE-11'),
('KA22.1', 'Recién nacido grande para la edad gestacional', 'category', false, false, 'CIE-11'),
('KA22.2', 'Recién nacido posmaduro', 'category', false, false, 'CIE-11'),
('KA22.3', 'Síndrome de posmadurez', 'category', false, false, 'CIE-11'),
('KA2Y', 'Otros trastornos especificados en el recién nacido relacionados con la duración de la gestación y el crecimiento fetal', 'category', false, false, 'CIE-11'),
('KA2Z', 'Trastornos en el recién nacido relacionados con la duración de la gestación y el crecimiento fetal, sin especificación', 'category', false, false, 'CIE-11'),
('KA40', 'Lesión traumática del sistema nervioso central durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0', 'Hemorragia o laceración intracraneal por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.00', 'Hemorragia subdural por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.01', 'Hemorragia cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.02', 'Hemorragia cerebelosa por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.03', 'Hemorragia intraventricular por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.04', 'Hemorragia subaracnoidea por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.05', 'Desgarro tentorial por traumatismo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.06', 'Contusión cerebelosa por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.07', 'Contusión cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.08', 'Hemorragia extradural o epidural por lesión traumática durante el durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0Y', 'Otra hemorragia o laceración intracraneal especificada por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.0Z', 'Hemorragia o laceración intracraneal por lesión traumática durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA40.1', 'Edema cerebral por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.2', 'Lesión traumática de la columna vertebral o médula espinal durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.3', 'Lesión traumática del tronco encefálico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.Y', 'Otra lesión traumática especificada del sistema nervioso central durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA40.Z', 'Lesión traumática del sistema nervioso central durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA41', 'Lesión traumática en el ojo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42', 'Lesión traumática del cuero cabelludo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.0', 'Equimosis del cuero cabelludo por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.1', 'Cefalohematoma por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.2', 'Chichón del recién nacido por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.3', 'Traumatismo en el cuero cabelludo por monitoreo del recién nacido', 'category', false, false, 'CIE-11'),
('KA42.4', 'Hemorragia subaponeurótica epicraneal subgaleal por lesión durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.Y', 'Otra lesión traumática especificada del cuero cabelludo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA42.Z', 'Lesión traumática del cuero cabelludo durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA43', 'Lesión traumática de la piel o de los tejidos blandos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.0', 'Lesión traumática del músculo esternocleidomastoideo durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.1', 'Lesión traumática de los genitales externos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.2', 'Necrosis de la grasa subcutánea del recién nacido por lesión traumática durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.3', 'Lesión traumática en la cara del neonato durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.Y', 'Otra lesión traumática especificada de la piel o de los tejidos blandos durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA43.Z', 'Lesión traumática de la piel o de los tejidos blandos durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA44', 'Lesión traumática del sistema nervioso periférico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.0', 'Traumatismo de los pares craneales durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.00', 'Lesión del nervio facial durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.0Y', 'Traumatismo durante el nacimiento de otro par craneal especificado', 'category', false, false, 'CIE-11'),
('KA44.0Z', 'Traumatismo durante el nacimiento de un par craneal, sin especificación', 'category', false, false, 'CIE-11'),
('KA44.1', 'Parálisis del plexo braquial en el recién nacido', 'category', false, false, 'CIE-11'),
('KA44.10', 'Parálisis de Erb', 'category', false, false, 'CIE-11'),
('KA44.11', 'Parálisis de Klumpke', 'category', false, false, 'CIE-11'),
('KA44.1Z', 'Parálisis del plexo braquial en el recién nacido, sin especificación', 'category', false, false, 'CIE-11'),
('KA44.2', 'Parálisis del nervio frénico debido a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA44.Y', 'Otra lesión traumática especificada del sistema nervioso periférico durante el nacimiento', 'category', false, false, 'CIE-11'),
('KA44.Z', 'Lesión traumática del sistema nervioso periférico durante el nacimiento, sin especificación', 'category', false, false, 'CIE-11'),
('KA45', 'Lesión traumática del esqueleto durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0', 'Fractura de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.00', 'Fractura lineal de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.01', 'Fractura deprimida de cráneo debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0Y', 'Otra fractura de cráneo especificada debida a traumatismo durante el parto', 'category', false, false, 'CIE-11'),
('KA45.0Z', 'Fractura del cráneo debida a traumatismo durante el parto, sin especificación', 'category', false, false, 'CIE-11'),
('KA45.1', 'Osteodiastasis occipital debido a lesión traumática durante el parto', 'category', false, false, 'CIE-11'),
('KA45.2', 'Lesión traumática de los huesos faciales durante el parto', 'category', false, false, 'CIE-11'),
('KA45.20', 'Fractura del hueso mandibular debida a lesión traumática durante el parto', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;