BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XM9XW5', 'Sulfuro antimónico', 'category', false, false, 'CIE-11'),
('XM8Z31', 'Coloide de ferrihidróxido de itrio (90Y)', 'category', false, false, 'CIE-11'),
('XM0JJ4', 'Coloide de hidroxiapatita de samario (153Sm)', 'category', false, false, 'CIE-11'),
('XM56F9', 'Disprosio coloidal (165Dy)', 'category', false, false, 'CIE-11'),
('XM10B1', 'Coloide de citrato de itrio (90Y)', 'category', false, false, 'CIE-11'),
('XM3MD6', 'Coloide de citrato de erbio (169Er)', 'category', false, false, 'CIE-11'),
('XM5ZE8', 'Dicloruro de amileno', 'category', false, false, 'CIE-11'),
('XM1WG6', 'Aceite etiodizado (i131)', 'category', false, false, 'CIE-11'),
('XM7MV3', 'Yodo (131I) omburtamab', 'category', false, false, 'CIE-11'),
('XM32B6', 'b-eucaina', 'category', false, false, 'CIE-11'),
('XM79Q0', 'Lactato de benzamina', 'category', false, false, 'CIE-11'),
('XM8MM9', 'Alquitrán de hulla', 'category', false, false, 'CIE-11'),
('XM96H7', 'Destilado de alquitrán soluble en éter', 'category', false, false, 'CIE-11'),
('XM6PP6', 'Alquitrán de enebro', 'category', false, false, 'CIE-11'),
('XM8YS8', 'Fenol medicinal', 'category', false, false, 'CIE-11'),
('XM96T6', 'Preparación fenólica', 'category', false, false, 'CIE-11'),
('XM8485', 'Pramoxina', 'category', false, false, 'CIE-11'),
('XM6A20', 'Quinisocaina', 'category', false, false, 'CIE-11'),
('XM8W74', 'Destilado de alquitrán', 'category', false, false, 'CIE-11'),
('XM8WM2', 'Pomada de alquitrán', 'category', false, false, 'CIE-11'),
('XM4543', 'Tolpropamina', 'category', false, false, 'CIE-11'),
('XM2833', 'Mepiramina tópica', 'category', false, false, 'CIE-11'),
('XM29P8', 'Metilbromuro de difenhidramina', 'category', false, false, 'CIE-11'),
('XM9UN5', 'Thonzylamine tópico', 'category', false, false, 'CIE-11'),
('XM7JY5', 'Thenalidine tópico', 'category', false, false, 'CIE-11'),
('XM6WM2', 'Prometazina tópica', 'category', false, false, 'CIE-11'),
('XM4B01', 'Ácido acético con acetato de sodio (ungüento)', 'category', false, false, 'CIE-11'),
('XM7MV6', 'Resina acrílica', 'category', false, false, 'CIE-11'),
('XM8U60', 'Aliltiourea', 'category', false, false, 'CIE-11'),
('XM06X6', 'Aluminio, ungüento de aluminio (quirúrgico) (tópico)', 'category', false, false, 'CIE-11'),
('XM1S82', 'Ácido aminobenzoico (-p)', 'category', false, false, 'CIE-11'),
('XM3VB3', 'Aceite de arachis', 'category', false, false, 'CIE-11'),
('XM8SU9', 'Crema protectora', 'category', false, false, 'CIE-11'),
('XM5L08', 'Bentonita', 'category', false, false, 'CIE-11'),
('XM7D95', 'Benzofenonas', 'category', false, false, 'CIE-11'),
('XM6F99', 'Benzofenona-3', 'category', false, false, 'CIE-11'),
('XM4DT5', 'Benzofenona-4', 'category', false, false, 'CIE-11'),
('XM08U7', 'Aceite Betula', 'category', false, false, 'CIE-11'),
('XM7K00', 'Calamina (loción)', 'category', false, false, 'CIE-11'),
('XM2EP3', 'Nitratos de celulosa (tópico)', 'category', false, false, 'CIE-11'),
('XM9ZA9', 'Clorodietil benzamida', 'category', false, false, 'CIE-11'),
('XM88R8', 'Cold cream', 'category', false, false, 'CIE-11'),
('XM7033', 'Maicena', 'category', false, false, 'CIE-11'),
('XM38M3', 'Loción de corn husker', 'category', false, false, 'CIE-11'),
('XM8P34', 'Aceite de algodón', 'category', false, false, 'CIE-11'),
('XM5PK1', 'Demulcente (externo)', 'category', false, false, 'CIE-11'),
('XM0XB3', 'Dietil toluamida medicinal', 'category', false, false, 'CIE-11'),
('XM9U76', 'Ftalato de dimetilo', 'category', false, false, 'CIE-11'),
('XM8KY4', 'Linaza (medicinal)', 'category', false, false, 'CIE-11'),
('XM6694', 'Homosalato', 'category', false, false, 'CIE-11'),
('XM8M74', 'Loción hidrofílica', 'category', false, false, 'CIE-11'),
('XM8WH4', 'Lanolina', 'category', false, false, 'CIE-11'),
('XM4HE0', 'Alcohol de lanolina', 'category', false, false, 'CIE-11'),
('XM7TK2', 'Mecrilato', 'category', false, false, 'CIE-11'),
('XM7VP7', 'Agentes melanizantes', 'category', false, false, 'CIE-11'),
('XM8EY7', 'Mexenona', 'category', false, false, 'CIE-11'),
('XM9TZ7', 'Aceite mineral tópico', 'category', false, false, 'CIE-11'),
('XM3214', 'Cloruro de octafonio', 'category', false, false, 'CIE-11'),
('XM66S8', 'Aceite de gaulteria (amargo)', 'category', false, false, 'CIE-11'),
('XM9CQ4', 'Metoxsalen tópico', 'category', false, false, 'CIE-11'),
('XM0VT0', 'Padimato', 'category', false, false, 'CIE-11'),
('XM9AG3', 'Ácido para- amino benzoico', 'category', false, false, 'CIE-11'),
('XM1U48', 'Tópico de aceite de maní', 'category', false, false, 'CIE-11'),
('XM8PB6', 'Petrolato', 'category', false, false, 'CIE-11'),
('XM8J96', 'Vendaje de yeso', 'category', false, false, 'CIE-11'),
('XM9V04', 'Vendaje plástico', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XM2BL7', 'Adhesivo de polietileno', 'category', false, false, 'CIE-11'),
('XM6J14', 'Protector, de la piel', 'category', false, false, 'CIE-11'),
('XM9VE3', 'Piroxilina', 'category', false, false, 'CIE-11'),
('XM8293', 'Pomada de agua de rosas', 'category', false, false, 'CIE-11'),
('XM06Y2', 'Silicona medicinal', 'category', false, false, 'CIE-11'),
('XM9410', 'Loción protectora de la radiación solar', 'category', false, false, 'CIE-11'),
('XM4YA6', 'Sulisobenzona', 'category', false, false, 'CIE-11'),
('XM7YQ8', 'Aceite dulce (abedul)', 'category', false, false, 'CIE-11'),
('XM3599', 'Talco', 'category', false, false, 'CIE-11'),
('XM3MF9', 'Tiosinamina', 'category', false, false, 'CIE-11'),
('XM7Q94', 'Dióxido de titanio', 'category', false, false, 'CIE-11'),
('XM6WX7', 'Óxido de titanio', 'category', false, false, 'CIE-11'),
('XM5E39', 'Protector de la luz ultravioleta', 'category', false, false, 'CIE-11'),
('XM4D35', 'Éster hexílico del ácido 2- [4- (dietilamino) -2-hidroxibenzoil] benzoico', 'category', false, false, 'CIE-11'),
('XM8A13', 'Metileno bis-benzotriazolil tetrametilbutilfenol', 'category', false, false, 'CIE-11'),
('XM6UT3', 'Ácido 2-fenil-1H-benzo imidazol-5-sulfónico', 'category', false, false, 'CIE-11'),
('XM65Q8', '2,4,6-Tianilino-p-(carbo-2-etilhexil-1-oxi) -1,3,5-triazina', 'category', false, false, 'CIE-11'),
('XM5PP3', 'Bota de Unna', 'category', false, false, 'CIE-11'),
('XM8H46', 'Gelatina de zinc', 'category', false, false, 'CIE-11'),
('XM7RG9', 'Óxido de zinc', 'category', false, false, 'CIE-11'),
('XM4NT3', 'Estearato de zinc', 'category', false, false, 'CIE-11'),
('XM8YJ6', 'Colofonio', 'category', false, false, 'CIE-11'),
('XM1LY7', 'Sorbitan sesquioleate', 'category', false, false, 'CIE-11'),
('XM2M34', 'Octinoxato', 'category', false, false, 'CIE-11'),
('XM2F87', 'Ácido hialurónico tópico', 'category', false, false, 'CIE-11'),
('XM90Q0', 'Cetomacrogol', 'category', false, false, 'CIE-11'),
('XM8N69', 'Etofenamato', 'category', false, false, 'CIE-11'),
('XM85Z1', 'Uso dental medicinal con flúor', 'category', false, false, 'CIE-11'),
('XM9RB7', 'Flúor estañoso', 'category', false, false, 'CIE-11'),
('XM60N7', 'Sales de bismuto yoduro fórmico', 'category', false, false, 'CIE-11'),
('XM0DJ3', 'Cadexómero', 'category', false, false, 'CIE-11'),
('XM12P7', 'Diyodohidroxipropano', 'category', false, false, 'CIE-11'),
('XM8UZ7', 'Diyodohidroxiquina tópico', 'category', false, false, 'CIE-11'),
('XM0809', 'Yodo', 'category', false, false, 'CIE-11'),
('XM8C24', 'Yoduro de mercurio(ungüento)', 'category', false, false, 'CIE-11'),
('XM3Q63', 'Yoduro metilato', 'category', false, false, 'CIE-11'),
('XM6TG8', 'Yodoclorhidroxiquina tópico', 'category', false, false, 'CIE-11'),
('XM3X72', 'Iodoformo', 'category', false, false, 'CIE-11'),
('XM58X1', 'Iodato de potasio', 'category', false, false, 'CIE-11'),
('XM24J7', 'Yodo povidona', 'category', false, false, 'CIE-11'),
('XM9ZS1', 'Alantoina', 'category', false, false, 'CIE-11'),
('XM7H25', 'Alumbre (medicinal)', 'category', false, false, 'CIE-11'),
('XM2GV6', 'Ictiosulfonato de amonio', 'category', false, false, 'CIE-11'),
('XM8RR9', 'Persulfato de amonio', 'category', false, false, 'CIE-11'),
('XM8HL4', 'Antralina', 'category', false, false, 'CIE-11'),
('XM8SX1', 'Antiseborreicos', 'category', false, false, 'CIE-11'),
('XM8GU1', 'Butantrona', 'category', false, false, 'CIE-11'),
('XM4FV2', 'Aceite de Cade', 'category', false, false, 'CIE-11'),
('XM2ST0', 'Sulfuro de cadmio (medicinal)', 'category', false, false, 'CIE-11'),
('XM9TT3', 'Capsicum', 'category', false, false, 'CIE-11'),
('XM4AW0', 'Nieve de dióxido de carbono', 'category', false, false, 'CIE-11'),
('XM01Q7', 'Clorotimol', 'category', false, false, 'CIE-11'),
('XM92H5', 'Cloroxina', 'category', false, false, 'CIE-11'),
('XM7HY4', 'Crisarobina', 'category', false, false, 'CIE-11'),
('XM3P37', 'Alquitrán de hulla medicinal (ungüento)', 'category', false, false, 'CIE-11'),
('XM3LD7', 'Colagenasa tópica', 'category', false, false, 'CIE-11'),
('XM7PM1', 'Curas de maíz', 'category', false, false, 'CIE-11'),
('XM5W78', 'Depilatorio', 'category', false, false, 'CIE-11'),
('XM95C8', 'Yeso Diaquilon', 'category', false, false, 'CIE-11'),
('XM64V2', 'Dimetil sulfóxido medicinal', 'category', false, false, 'CIE-11'),
('XM26P0', 'Sulfato de dimetilamina', 'category', false, false, 'CIE-11'),
('XM8RS8', 'Ditranol', 'category', false, false, 'CIE-11'),
('XM17Y7', 'Enzima proteolítica', 'category', false, false, 'CIE-11'),
('XM3JC8', 'Cloruro de etilo local', 'category', false, false, 'CIE-11'),
('XM4P92', 'Fumarato de etilo', 'category', false, false, 'CIE-11'),
('XM7WC9', 'Euresol', 'category', false, false, 'CIE-11'),
('XM7VL9', 'Tinte para el cabello', 'category', false, false, 'CIE-11'),
('XM8GV4', 'Hemostiptico', 'category', false, false, 'CIE-11'),
('XM7KM8', 'Alcohol isopropilico medicinal', 'category', false, false, 'CIE-11'),
('XM6ES1', 'Antraceno medicamento queratolítico', 'category', false, false, 'CIE-11'),
('XM23V5', 'Droga queratolítica', 'category', false, false, 'CIE-11'),
('XM4KL1', 'Queratoplástico', 'category', false, false, 'CIE-11'),
('XM76E0', 'Pasta de Lassar', 'category', false, false, 'CIE-11'),
('XM1VX5', 'Nicotinato de metilo', 'category', false, false, 'CIE-11'),
('XM8N27', 'Monobenzona', 'category', false, false, 'CIE-11'),
('XM6YQ8', 'Piritionato de zinc', 'category', false, false, 'CIE-11'),
('XM4549', 'Resorcina, resorcinol medicinal', 'category', false, false, 'CIE-11'),
('XM5DQ2', 'Rubefaciente', 'category', false, false, 'CIE-11'),
('XM68B5', 'Ácido salicílico', 'category', false, false, 'CIE-11'),
('XM02N6', 'Savin (aceite)', 'category', false, false, 'CIE-11'),
('XM43T8', 'Sulfuro de selenio', 'category', false, false, 'CIE-11'),
('XM1UK4', 'Selsun', 'category', false, false, 'CIE-11'),
('XM3E07', 'Nitrato de plata endurecido (queratolítico)', 'category', false, false, 'CIE-11'),
('XM1FW6', 'Compuestos de azufre no clasificados en otra parte (medicinales)', 'category', false, false, 'CIE-11'),
('XM6ZA6', 'Ungüento queratolítico de azufre', 'category', false, false, 'CIE-11'),
('XM1W96', 'Tioglicolato', 'category', false, false, 'CIE-11'),
('XM7GY2', 'Tioxolona', 'category', false, false, 'CIE-11'),
('XM4ZP4', 'Triacetoxiantraceno', 'category', false, false, 'CIE-11'),
('XM6U21', 'Ácido tricloracético medicinal', 'category', false, false, 'CIE-11'),
('XM2V83', 'Solución de Vleminckx', 'category', false, false, 'CIE-11'),
('XM6T99', 'Loción blanca (queratolítica)', 'category', false, false, 'CIE-11'),
('XM25J6', 'Xenisalato', 'category', false, false, 'CIE-11'),
('XM7AM5', 'Monotioglicolato de glicerilo', 'category', false, false, 'CIE-11'),
('XM5L79', 'p Diaminotolueno', 'category', false, false, 'CIE-11'),
('XM75W8', 'Adrenal preparado oftálmico', 'category', false, false, 'CIE-11'),
('XM6H73', 'Tartrato ácido de amonio', 'category', false, false, 'CIE-11'),
('XM6G79', 'Preparación oftálmica anti infecciosa', 'category', false, false, 'CIE-11'),
('XM5568', 'Anticolinesterasa reversible oftalmológica', 'category', false, false, 'CIE-11'),
('XM5T83', 'Befunolol', 'category', false, false, 'CIE-11'),
('XM6NB7', 'Bibrocatol', 'category', false, false, 'CIE-11'),
('XM32H1', 'Preparado oftálmico Quimotripsina', 'category', false, false, 'CIE-11'),
('XM6E41', 'Colistina sulfato(preparación para ojos)', 'category', false, false, 'CIE-11'),
('XM1WZ1', 'Solución de lentes de contacto', 'category', false, false, 'CIE-11'),
('XM3X79', 'Sulfato de cobre cúprico medicinal para ojos', 'category', false, false, 'CIE-11'),
('XM3918', 'Droga ciclopléjica', 'category', false, false, 'CIE-11'),
('XM8S71', 'Bromuro de demecario', 'category', false, false, 'CIE-11'),
('XM1X30', 'Dendrid', 'category', false, false, 'CIE-11'),
('XM0L12', 'Dipivefrina', 'category', false, false, 'CIE-11'),
('XM17P1', 'Ecotiofato', 'category', false, false, 'CIE-11'),
('XM7K14', 'Yoduro de Ecotiofato', 'category', false, false, 'CIE-11'),
('XM09W6', 'Edoxudina', 'category', false, false, 'CIE-11'),
('XM8PJ6', 'Eucatropina', 'category', false, false, 'CIE-11'),
('XM45L3', 'Fluorfenilalanina', 'category', false, false, 'CIE-11'),
('XM1783', 'Herplex', 'category', false, false, 'CIE-11'),
('XM9EN3', 'Hidroxianfetamina', 'category', false, false, 'CIE-11'),
('XM9E72', 'Hipromelosa', 'category', false, false, 'CIE-11'),
('XM0PE3', 'Lachesina', 'category', false, false, 'CIE-11'),
('XM8098', 'Levobunolol', 'category', false, false, 'CIE-11'),
('XM4QZ9', 'Metilparabeno (oftálmico)', 'category', false, false, 'CIE-11'),
('XM0YH4', 'Metipranolol', 'category', false, false, 'CIE-11'),
('XM2JE0', 'Droga miótica', 'category', false, false, 'CIE-11'),
('XM4DY8', 'Preparado oftálmico Micitracina', 'category', false, false, 'CIE-11'),
('XM5PU9', 'Droga midriática', 'category', false, false, 'CIE-11'),
('XM28C3', 'Preparado oftálmico de neosporina', 'category', false, false, 'CIE-11'),
('XM4PY4', 'Fosfolina', 'category', false, false, 'CIE-11'),
('XM4605', 'Fisostigmina', 'category', false, false, 'CIE-11'),
('XM9N59', 'Polimixina E sulfato (preparado para ojos)', 'category', false, false, 'CIE-11'),
('XM2WK3', 'Propilparabeno (oftálmico)', 'category', false, false, 'CIE-11'),
('XM56H1', 'Proteína de plata', 'category', false, false, 'CIE-11'),
('XM7AV0', 'Limpiador de ojo Borato de sodio', 'category', false, false, 'CIE-11'),
('XM6Q18', 'Estoxil', 'category', false, false, 'CIE-11'),
('XM8A14', 'Preparado oftálmico de sulfisoxazol', 'category', false, false, 'CIE-11'),
('XM9PG5', 'Sulfonamida para ojos', 'category', false, false, 'CIE-11'),
('XM61C9', 'Solución Tear', 'category', false, false, 'CIE-11'),
('XM5RC2', 'Tetrahidrozolina', 'category', false, false, 'CIE-11'),
('XM31C8', 'Visine', 'category', false, false, 'CIE-11'),
('XM9X81', 'Acetazolamida', 'category', false, false, 'CIE-11'),
('XM4LU1', 'Diclorfenamida', 'category', false, false, 'CIE-11'),
('XM4DH5', 'Etoxzolamida', 'category', false, false, 'CIE-11'),
('XM8P33', 'Metazolamida', 'category', false, false, 'CIE-11'),
('XM3ZJ4', 'Pemirolast', 'category', false, false, 'CIE-11'),
('XM2JR8', 'Picloxidina', 'category', false, false, 'CIE-11'),
('XM6JB1', 'Fluostigmina', 'category', false, false, 'CIE-11'),
('XM3BT0', 'Dorzolamida', 'category', false, false, 'CIE-11'),
('XM9GB8', 'Brinzolamida', 'category', false, false, 'CIE-11'),
('XM5130', 'Latanoprost', 'category', false, false, 'CIE-11'),
('XM5ZG4', 'Unoprostona', 'category', false, false, 'CIE-11'),
('XM6E95', 'Bimatoprost', 'category', false, false, 'CIE-11'),
('XM9BS0', 'Travoprost', 'category', false, false, 'CIE-11'),
('XM3UC8', 'Tafluprost', 'category', false, false, 'CIE-11'),
('XM6PD6', 'Dapiprazol', 'category', false, false, 'CIE-11'),
('XM8469', 'Netarsudil', 'category', false, false, 'CIE-11'),
('XM0GK6', 'Pegaptanib', 'category', false, false, 'CIE-11'),
('XM95Y7', 'Ranibizumab', 'category', false, false, 'CIE-11'),
('XM42E0', 'Yodoheparinato', 'category', false, false, 'CIE-11'),
('XM67C4', 'Lifitegrast', 'category', false, false, 'CIE-11'),
('XM57P1', 'Cenegermina', 'category', false, false, 'CIE-11'),
('XM2RM5', 'Ocriplasmina', 'category', false, false, 'CIE-11'),
('XM0YQ8', 'Células madre autólogas del limbo', 'category', false, false, 'CIE-11'),
('XM2GK8', 'Lágrimas artificiales y otras preparaciones indiferentes.', 'category', false, false, 'CIE-11'),
('XM3PF8', 'Anecortave', 'category', false, false, 'CIE-11'),
('XM7CE4', 'Guaiazuleno', 'category', false, false, 'CIE-11'),
('XM0ST2', 'Olopatadina', 'category', false, false, 'CIE-11'),
('XM49V8', 'Azidamfenicol', 'category', false, false, 'CIE-11'),
('XM3G39', 'Sulfadicramida', 'category', false, false, 'CIE-11'),
('XM13T1', 'Sulfafenazol', 'category', false, false, 'CIE-11'),
('XM4F24', 'Preparación oftálmica de interferón', 'category', false, false, 'CIE-11'),
('XM0C71', 'Fomivirsen', 'category', false, false, 'CIE-11'),
('XM1A96', 'Besifloxacina', 'category', false, false, 'CIE-11'),
('XM7415', 'Compuestos de mercurio', 'category', false, false, 'CIE-11'),
('XM9KL6', 'Loteprednol', 'category', false, false, 'CIE-11'),
('XM6GF5', 'Formocortal', 'category', false, false, 'CIE-11'),
('XM9166', 'Pranoprofeno', 'category', false, false, 'CIE-11'),
('XM4GZ0', 'Nepafenaco', 'category', false, false, 'CIE-11'),
('XM0QS2', 'Bromfenaco', 'category', false, false, 'CIE-11'),
('XM14H0', 'Preparación oftálmica de brimonidina', 'category', false, false, 'CIE-11'),
('XM9KS5', 'Preparación oftálmica de acetilcolina', 'category', false, false, 'CIE-11'),
('XM32J7', 'Levocabastina', 'category', false, false, 'CIE-11'),
('XM9L65', 'Lodoxamida', 'category', false, false, 'CIE-11'),
('XM1CM1', 'Emedastina', 'category', false, false, 'CIE-11'),
('XM4JE3', 'Alcaftadina', 'category', false, false, 'CIE-11'),
('XM7SY2', 'Cloruro de sodio, hipertónico (oftálmico)', 'category', false, false, 'CIE-11'),
('XM2LQ4', 'Preparación oftálmica de edetato de sodio', 'category', false, false, 'CIE-11'),
('XM3ZG3', 'Preparación oftálmica de ciclosporina', 'category', false, false, 'CIE-11'),
('XM7UH0', 'Preparación oftálmica de nandrolona', 'category', false, false, 'CIE-11'),
('XM3XE4', 'Apraclonidina', 'category', false, false, 'CIE-11'),
('XM2Y24', 'Verteporfina', 'category', false, false, 'CIE-11'),
('XM63C9', 'Ácido espaglúmico', 'category', false, false, 'CIE-11'),
('XM3YZ7', 'Dentífrico', 'category', false, false, 'CIE-11'),
('XM1JW3', 'Cobertura, pulpa viva', 'category', false, false, 'CIE-11'),
('XM0PR1', 'Aceite de eucaliptos', 'category', false, false, 'CIE-11'),
('XM3XP7', 'Aceite de clavo de olor', 'category', false, false, 'CIE-11'),
('XM8PE1', 'Pasta desvitalizante de pulpa', 'category', false, false, 'CIE-11'),
('XM9023', 'Ácido acetilsalicílico tópico', 'category', false, false, 'CIE-11'),
('XM7K59', 'Olaflur', 'category', false, false, 'CIE-11'),
('XM5GY2', 'Monofluorofosfato de sodio tópico', 'category', false, false, 'CIE-11'),
('XM53X2', 'Tetraciclina tópica', 'category', false, false, 'CIE-11'),
('XM2FL0', 'Cloruro de acriflavina', 'category', false, false, 'CIE-11'),
('XM8K50', 'Acrinol', 'category', false, false, 'CIE-11'),
('XM5PD0', 'Acrisorcina', 'category', false, false, 'CIE-11'),
('XM7696', 'Adrenal tópico', 'category', false, false, 'CIE-11'),
('XM9B70', 'Aerosporina tópico', 'category', false, false, 'CIE-11'),
('XM2ET5', 'Alclometasona', 'category', false, false, 'CIE-11'),
('XM3NX2', 'Alconio (bromuro)', 'category', false, false, 'CIE-11'),
('XM7TF6', 'Aletrina', 'category', false, false, 'CIE-11'),
('XM0CC9', 'Solución de acetato de aluminio', 'category', false, false, 'CIE-11'),
('XM6JG7', 'Sulfato de aluminio', 'category', false, false, 'CIE-11'),
('XM18N0', 'Glutaraldehido medicinal', 'category', false, false, 'CIE-11'),
('XM7XA4', 'Triacetato de glicerilo tópico', 'category', false, false, 'CIE-11'),
('XM7Y78', 'Gramicidina', 'category', false, false, 'CIE-11'),
('XM5UQ0', 'Halcinolona', 'category', false, false, 'CIE-11'),
('XM9Q64', 'Haletazol', 'category', false, false, 'CIE-11'),
('XM0C80', 'Haloprogina', 'category', false, false, 'CIE-11'),
('XM3KW0', 'Halquinol', 'category', false, false, 'CIE-11'),
('XM6XH7', 'HCH medicinal', 'category', false, false, 'CIE-11'),
('XM8UW4', 'Hedaquinio', 'category', false, false, 'CIE-11'),
('XM95K6', 'Hexaclorofeno', 'category', false, false, 'CIE-11'),
('XM6RK6', 'Aminoacridina', 'category', false, false, 'CIE-11'),
('XM7RK5', 'Hexamidina', 'category', false, false, 'CIE-11'),
('XM19W1', 'Hidrargafen', 'category', false, false, 'CIE-11'),
('XM0JC1', 'Hidrargiro amino-cloro', 'category', false, false, 'CIE-11'),
('XM4AG2', 'Peróxido de Hidrógeno', 'category', false, false, 'CIE-11'),
('XM6E35', 'Hidroxitolueno medicinal', 'category', false, false, 'CIE-11'),
('XM02H1', 'Hipoclorito', 'category', false, false, 'CIE-11'),
('XM3PT9', 'Ictamol', 'category', false, false, 'CIE-11'),
('XM6BF8', 'Isoconazol', 'category', false, false, 'CIE-11'),
('XM07S0', 'Kwell antiinfeccioso (tópico)', 'category', false, false, 'CIE-11'),
('XM3U48', 'Laurolinium', 'category', false, false, 'CIE-11'),
('XM7CU1', 'Amfotericina B tópica', 'category', false, false, 'CIE-11'),
('XM8C45', 'Lidex', 'category', false, false, 'CIE-11'),
('XM8E58', 'Lindane medicinal', 'category', false, false, 'CIE-11'),
('XM7CM3', 'Locorten', 'category', false, false, 'CIE-11'),
('XM5MZ8', 'Mafenida', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;