BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XH2D15', 'Sarcoma fibroblástico mixoinflamatorio', 'category', false, false, 'CIE-11'),
('XH0TA8', 'Tumor fibroblástico mixoinflamatorio atípico', 'category', false, false, 'CIE-11'),
('XH9526', 'Tumor fibrolipomatoso hemosiderótico', 'category', false, false, 'CIE-11'),
('XH75J5', 'Fibromatosis de tipo palmar / plantar', 'category', false, false, 'CIE-11'),
('XH7E62', 'Tumor fibroso solitario, SAI', 'category', false, false, 'CIE-11'),
('XH1EH1', 'Tumor fibroso solitario / Haemangiopericitoma, grado 2', 'category', false, false, 'CIE-11'),
('XH66Z0', 'Tumor miofibroblástico, SAI', 'category', false, false, 'CIE-11'),
('XH6YK5', 'Fibroma desmoplásico', 'category', false, false, 'CIE-11'),
('XH4QZ8', 'Dermatofibrosarcoma protuberante, SAI', 'category', false, false, 'CIE-11'),
('XH5CT4', 'Dermatofibrosarcoma protuberans pigmentado', 'category', false, false, 'CIE-11'),
('XH9AV8', 'Fibroblastoma de células gigantes', 'category', false, false, 'CIE-11'),
('XH4GL1', 'Tumor fibrohistiocítico plexiforme', 'category', false, false, 'CIE-11'),
('XH9362', 'Histiocitoma fibroso angiomatoso', 'category', false, false, 'CIE-11'),
('XH7050', 'Hemangiopericitoma meningioma', 'category', false, false, 'CIE-11'),
('XH3GV5', 'Teratoma, benigno', 'category', false, false, 'CIE-11'),
('XH9F67', 'Quiste dermoide, SAI', 'category', false, false, 'CIE-11'),
('XH52Q4', 'Teratoma, tipo prepuberal', 'category', false, false, 'CIE-11'),
('XH22M4', 'Struma del ovario, SAI', 'category', false, false, 'CIE-11'),
('XH8AD3', 'Células germinales malignas intratubulares', 'category', false, false, 'CIE-11'),
('XH24E0', 'Disgerminoma', 'category', false, false, 'CIE-11'),
('XH0A34', 'Tumor de células germinales, no seminomatoso', 'category', false, false, 'CIE-11'),
('XH1E13', 'Germinoma', 'category', false, false, 'CIE-11'),
('XH7SG5', 'Tumor hepatoide del saco vitelino', 'category', false, false, 'CIE-11'),
('XH0N49', 'Teratoma inmaduro, maligno', 'category', false, false, 'CIE-11'),
('XH2PP9', 'Teratoma maligno, indiferenciado', 'category', false, false, 'CIE-11'),
('XH9Z28', 'Poliembrioma', 'category', false, false, 'CIE-11'),
('XH6YQ4', 'Seminoma, anaplásico', 'category', false, false, 'CIE-11'),
('XH80D1', 'Seminoma espermatocítico', 'category', false, false, 'CIE-11'),
('XH56W1', 'Teratocarcinoma', 'category', false, false, 'CIE-11'),
('XH09W7', 'Tumor de saco vitelino', 'category', false, false, 'CIE-11'),
('XH9FM4', 'Seminoma, SAI', 'category', false, false, 'CIE-11'),
('XH8MB9', 'Carcinoma embrionario, SAI', 'category', false, false, 'CIE-11'),
('XH15X1', 'Tumor del saco vitelino, tipo pospúberal', 'category', false, false, 'CIE-11'),
('XH7YZ9', 'Teratoma maligno, SAI', 'category', false, false, 'CIE-11'),
('XH43T4', 'Teratoma maligno, intermedio', 'category', false, false, 'CIE-11'),
('XH33E8', 'Teratoma con transformación maligna', 'category', false, false, 'CIE-11'),
('XH2PS1', 'Tumor de células germinales mixtas', 'category', false, false, 'CIE-11'),
('XH9QP9', 'Tumor de células germinales asociado con malignidad hematológica', 'category', false, false, 'CIE-11'),
('XH5U02', 'Teratoma mixto y seminoma', 'category', false, false, 'CIE-11'),
('XH5PU7', 'Struma del ovario, maligno', 'category', false, false, 'CIE-11'),
('XH1P78', 'Teratocarcinosarcoma', 'category', false, false, 'CIE-11'),
('XH0K61', 'Gonadoblastoma', 'category', false, false, 'CIE-11'),
('XH83G5', 'Teratoma, SAI', 'category', false, false, 'CIE-11'),
('XH4NU1', 'Tumor de células germinales, regresivo', 'category', false, false, 'CIE-11'),
('XH5MG2', 'Teratoma inmaduro del pulmón', 'category', false, false, 'CIE-11'),
('XH2KP9', 'Teratoma inmaduro del timo', 'category', false, false, 'CIE-11'),
('XH2XW3', 'Carcinoma estromal', 'category', false, false, 'CIE-11'),
('XH5PC3', 'Teratoma inmaduro de tiroides', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XH6911', 'Tumor de células gigantes tenosinoviales, localizado', 'category', false, false, 'CIE-11'),
('XH0HZ1', 'Tumor de células gigantes tenosinoviales, SAI', 'category', false, false, 'CIE-11'),
('XH0492', 'Tumor de hueso de células gigantes, maligno', 'category', false, false, 'CIE-11'),
('XH84X1', 'Tumor maligno de células gigantes de partes blandas', 'category', false, false, 'CIE-11'),
('XH4TC2', 'Tumor de células gigantes de hueso, SAI', 'category', false, false, 'CIE-11'),
('XH81M1', 'Tumor de células gigantes de partes blandas, SAI', 'category', false, false, 'CIE-11'),
('XH52J9', 'Tumor de células gigantes tenosinovial, difuso', 'category', false, false, 'CIE-11'),
('XH5AQ9', 'Tumor de células gigantes tenosinoviales malignas', 'category', false, false, 'CIE-11'),
('XH0RF9', 'Papiloma de plexo coroideo, SAI', 'category', false, false, 'CIE-11'),
('XH0H76', 'Tumor neuroepitelial disembrioplásico.', 'category', false, false, 'CIE-11'),
('XH1Q28', 'Ependimoma selar', 'category', false, false, 'CIE-11'),
('XH1DC5', 'Astroblastoma', 'category', false, false, 'CIE-11'),
('XH96C7', 'Astrocitoma, anaplásico', 'category', false, false, 'CIE-11'),
('XH1S63', 'Astrocitoma, de bajo grado', 'category', false, false, 'CIE-11'),
('XH54D9', 'Ependimoma celular', 'category', false, false, 'CIE-11'),
('XH3M77', 'Carcinoma de plexos coroides', 'category', false, false, 'CIE-11'),
('XH6E51', 'Ependimoma de células claras', 'category', false, false, 'CIE-11'),
('XH8W32', 'Astrocitoma difuso', 'category', false, false, 'CIE-11'),
('XH6UY7', 'Astrocitoma difuso, de bajo grado', 'category', false, false, 'CIE-11'),
('XH6922', 'Ependimoma anaplásico', 'category', false, false, 'CIE-11'),
('XH6C35', 'Astrocitoma fibrilar', 'category', false, false, 'CIE-11'),
('XH5Y81', 'Astrocitoma gemistocítico', 'category', false, false, 'CIE-11'),
('XH4RQ3', 'Glioma, maligno', 'category', false, false, 'CIE-11'),
('XH6ZH4', 'Gliomatosis cerebral', 'category', false, false, 'CIE-11'),
('XH9RC8', 'Gliosarcoma', 'category', false, false, 'CIE-11'),
('XH6F49', 'Oligoastrocitoma, SAI', 'category', false, false, 'CIE-11'),
('XH9J28', 'Ependimoma papilar', 'category', false, false, 'CIE-11'),
('XH99U2', 'Xantoastrocitoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH6UV4', 'Astrocitoma protoplásmico', 'category', false, false, 'CIE-11'),
('XH4BJ4', 'Ependimoma tanicítico', 'category', false, false, 'CIE-11'),
('XH7692', 'Glioma difuso de la línea media, mutante H3 K27M', 'category', false, false, 'CIE-11'),
('XH9YU2', 'Gliomas pontino intrínseco difuso, mutante H3 K27M', 'category', false, false, 'CIE-11'),
('XH1511', 'Ependimoma, SAI', 'category', false, false, 'CIE-11'),
('XH2AY7', 'Ependimoma RELA fusión positiva', 'category', false, false, 'CIE-11'),
('XH6PH6', 'Astrocitoma, SAI', 'category', false, false, 'CIE-11'),
('XH36Y8', 'Astrocitoma quístico', 'category', false, false, 'CIE-11'),
('XH2HK4', 'Astrocitoma difuso, IDH mutante', 'category', false, false, 'CIE-11'),
('XH7HQ6', 'Astrocitoma anaplásico, IDH mutante', 'category', false, false, 'CIE-11'),
('XH83Y5', 'Espongioblastoma polar', 'category', false, false, 'CIE-11'),
('XH8BK8', 'Xantoastrocitoma pleomórfico anaplásico', 'category', false, false, 'CIE-11'),
('XH7F82', 'Glioblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH5571', 'Glioblastoma, IDH- de tipo salvaje', 'category', false, false, 'CIE-11'),
('XH0MB1', 'Glioblastoma, primario SAI', 'category', false, false, 'CIE-11'),
('XH3N49', 'Glioma difuso de la línea media, SAI', 'category', false, false, 'CIE-11'),
('XH61Y5', 'Glioma pontino intrínseco difuso', 'category', false, false, 'CIE-11'),
('XH4FN3', 'Glioblastoma, IDH mutante', 'category', false, false, 'CIE-11'),
('XH17J4', 'Glioblastoma, secundario, SAI', 'category', false, false, 'CIE-11'),
('XH7W59', 'Oligodendroglioma, SAI', 'category', false, false, 'CIE-11'),
('XH7K31', 'Oligodendroglioma, IDH mutante y co deleción 1p/19q', 'category', false, false, 'CIE-11'),
('XH9QF3', 'Oligodendroglioma, anaplásico IDH mutante y co deleción 1p/19q', 'category', false, false, 'CIE-11'),
('XH7CX7', 'Oligodendroblastoma', 'category', false, false, 'CIE-11'),
('XH8P29', 'Meduloblastoma, SAI', 'category', false, false, 'CIE-11'),
('XH9M38', 'Meduloblastoma, SHH-activado y TP53 tipo salvaje', 'category', false, false, 'CIE-11'),
('XH8844', 'Oligodendroglioma, anaplásico', 'category', false, false, 'CIE-11'),
('XH4B47', 'Meduloblastoma melanótico', 'category', false, false, 'CIE-11'),
('XH6JN6', 'Meduloblastoma con nodularidad extensa', 'category', false, false, 'CIE-11'),
('XH85M7', 'Meduloblastoma, SHH activado, SAI', 'category', false, false, 'CIE-11'),
('XH8SH6', 'Tumor embrionario del Sistema nervioso central, SAI', 'category', false, false, 'CIE-11'),
('XH89C3', 'Tumor neuroectodérmico primitivo central', 'category', false, false, 'CIE-11'),
('XH3EX1', 'Meduloblastoma, WNT activado, clásico', 'category', false, false, 'CIE-11'),
('XH5163', 'Meduloblastoma, WNT activado, tipo células grandes', 'category', false, false, 'CIE-11'),
('XH2FW8', 'Meduloblastoma, WNT activado, tipo Anaplásico', 'category', false, false, 'CIE-11'),
('XH1SH4', 'Meduloblastoma, SHH-activado y TP53- mutante', 'category', false, false, 'CIE-11'),
('XH87Q5', 'Meduloblastoma, no WNT/ no SHH', 'category', false, false, 'CIE-11'),
('XH51C5', 'Tumores embrionarios con rosetones de múltiples capas con alteración C19MC', 'category', false, false, 'CIE-11'),
('XH0KZ2', 'Tumor embrionario con rosetas de múltiples capas, SAI', 'category', false, false, 'CIE-11'),
('XH5538', 'Sarcoma cerebeloso, SAI', 'category', false, false, 'CIE-11'),
('XH8R14', 'Medulomioblastoma', 'category', false, false, 'CIE-11'),
('XH7Y86', 'TNEP Supratentorial', 'category', false, false, 'CIE-11'),
('XH5PR7', 'Meduloblastoma de células grandes', 'category', false, false, 'CIE-11'),
('XH0H95', 'Meduloblastoma anaplásico', 'category', false, false, 'CIE-11'),
('XH8UC5', 'Glioblastoma de células gigantes', 'category', false, false, 'CIE-11'),
('XH0RY1', 'Meduloblastoma clásico', 'category', false, false, 'CIE-11'),
('XH7PN5', 'Meduloblastoma desmoplásico/nodular', 'category', false, false, 'CIE-11'),
('XH3904', 'Tumor papilar de la región pineal', 'category', false, false, 'CIE-11'),
('XH2C49', 'Astrocitoma difuso, tipo salvaje-IDH', 'category', false, false, 'CIE-11'),
('XH2BA5', 'Glioblastoma epitelioide', 'category', false, false, 'CIE-11'),
('XH0ZP6', 'Meduloblastoma, WNT activado, SAI', 'category', false, false, 'CIE-11'),
('XH5XD3', 'Meduloblastoma, grupo 3', 'category', false, false, 'CIE-11'),
('XH25R4', 'Meduloblastoma, grupo 4', 'category', false, false, 'CIE-11'),
('XH39Z7', 'Astrocitoma, anaplásico, tipo salvaje IDH', 'category', false, false, 'CIE-11'),
('XH17F8', 'Glioma difuso de bajo grado, vía MAPK alterada', 'category', false, false, 'CIE-11'),
('XH2SS9', 'Glioma hemisférico difuso, mutante H3 G34', 'category', false, false, 'CIE-11'),
('XH4Q01', 'Glioma difuso de alto grado de tipo pediátrico, tipo salvaje H3 y tipo salvaje IDH', 'category', false, false, 'CIE-11'),
('XH4ZM8', 'Glioma hemisférico de tipo infantil', 'category', false, false, 'CIE-11'),
('XH12D2', 'Astrocitoma pilocítico', 'category', false, false, 'CIE-11'),
('XH29Q5', 'Astrocitoma pilomixoide', 'category', false, false, 'CIE-11'),
('XH41C5', 'Glioma angiocéntrico', 'category', false, false, 'CIE-11'),
('XH3Y57', 'Papiloma de plexos coroides atípico', 'category', false, false, 'CIE-11'),
('XH7M44', 'Astrocitoma infantil desmoplásico', 'category', false, false, 'CIE-11'),
('XH6TQ7', 'Ganglioglioma infantil desmoplástico', 'category', false, false, 'CIE-11'),
('XH0B58', 'Gliofibroma', 'category', false, false, 'CIE-11'),
('XH6738', 'Ependimoma- subependimoma mixto', 'category', false, false, 'CIE-11'),
('XH15U1', 'Ependimoma mixopapilar', 'category', false, false, 'CIE-11'),
('XH1L48', 'Astrocitoma de células gigantes subepedimales', 'category', false, false, 'CIE-11'),
('XH8FZ9', 'Subependimoma', 'category', false, false, 'CIE-11'),
('XH59V4', 'Pituicitoma', 'category', false, false, 'CIE-11'),
('XH9HV1', 'Glioma cordoide', 'category', false, false, 'CIE-11'),
('XH4101', 'Glioma cordoide del tercer ventrículo', 'category', false, false, 'CIE-11'),
('XH09A9', 'Tumor de células granulares, SAI', 'category', false, false, 'CIE-11'),
('XH2XW8', 'Tumor de células granulares de la región selar', 'category', false, false, 'CIE-11'),
('XH8V95', 'Sarcoma alveolar de partes blandas', 'category', false, false, 'CIE-11'),
('XH90D3', 'Tumor de células granulares, maligno', 'category', false, false, 'CIE-11'),
('XH2SJ1', 'Fibrolipoma', 'category', false, false, 'CIE-11'),
('XH0PH8', 'Fibromixolipoma', 'category', false, false, 'CIE-11'),
('XH7TB0', 'Angiolipoma infiltrante', 'category', false, false, 'CIE-11'),
('XH5GN5', 'Lipoma infiltrante', 'category', false, false, 'CIE-11'),
('XH3TE0', 'Lipoma intramuscular', 'category', false, false, 'CIE-11'),
('XH30M7', 'Lipoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH4E98', 'Lipoma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH1PL8', 'Lipoma, SAI', 'category', false, false, 'CIE-11'),
('XH4G31', 'Timolipoma', 'category', false, false, 'CIE-11'),
('XH3C77', 'Angiolipoma, SAI', 'category', false, false, 'CIE-11'),
('XH4VB4', 'Angiomiolipoma', 'category', false, false, 'CIE-11'),
('XH7WX8', 'Lipoma condroide', 'category', false, false, 'CIE-11'),
('XH17C5', 'Mielolipoma', 'category', false, false, 'CIE-11'),
('XH1054', 'Hibernoma', 'category', false, false, 'CIE-11'),
('XH8L55', 'Lipoblastomatosis', 'category', false, false, 'CIE-11'),
('XH1C03', 'Liposarcoma desdiferenciado', 'category', false, false, 'CIE-11'),
('XH6R46', 'Liposarcoma fibroblastico', 'category', false, false, 'CIE-11'),
('XH7PE7', 'Liposarcoma inflamatorio', 'category', false, false, 'CIE-11'),
('XH7Y61', 'Liposarcoma bien diferenciado', 'category', false, false, 'CIE-11'),
('XH8VG3', 'Liposarcoma mixto', 'category', false, false, 'CIE-11'),
('XH3EL0', 'Liposarcoma mixoide', 'category', false, false, 'CIE-11'),
('XH25R1', 'Liposarcoma pleomórfico', 'category', false, false, 'CIE-11'),
('XH8D43', 'Liposarcoma esclerosante', 'category', false, false, 'CIE-11'),
('XH2J05', 'Liposarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH0RW4', 'Tumor lipomatoso atípico', 'category', false, false, 'CIE-11'),
('XH4QB6', 'Lipofibromatosis', 'category', false, false, 'CIE-11'),
('XH0QR3', 'Angiomiolipoma, Epitelioide', 'category', false, false, 'CIE-11'),
('XH9MR8', 'Linfangioma, SAI', 'category', false, false, 'CIE-11'),
('XH6LF7', 'Linfangioma capilar', 'category', false, false, 'CIE-11'),
('XH2EU7', 'Linfangioma cavernoso', 'category', false, false, 'CIE-11'),
('XH8G00', 'Linfangioma quístico', 'category', false, false, 'CIE-11'),
('XH2DS9', 'Linfangiomioma', 'category', false, false, 'CIE-11'),
('XH62A3', 'Hemolinfangioma', 'category', false, false, 'CIE-11'),
('XH10U6', 'Linfangiosarcoma', 'category', false, false, 'CIE-11'),
('XH10K6', 'Linfangiomiomatosis', 'category', false, false, 'CIE-11'),
('XH5ZC7', 'Meningioma fibroso', 'category', false, false, 'CIE-11'),
('XH0R11', 'Meningioma rico en linfoplasmacitos', 'category', false, false, 'CIE-11'),
('XH11P5', 'Meningioma, SAI', 'category', false, false, 'CIE-11'),
('XH40T5', 'Meningioma meningotelial', 'category', false, false, 'CIE-11'),
('XH7N06', 'Meningioma metaplásico', 'category', false, false, 'CIE-11'),
('XH1F70', 'Meningioma microcístico', 'category', false, false, 'CIE-11'),
('XH6Z51', 'Meningioma', 'category', false, false, 'CIE-11'),
('XH3L73', 'Meningioma, hemangioblástico', 'category', false, false, 'CIE-11'),
('XH4ZM7', 'Meningioma psammomatoso', 'category', false, false, 'CIE-11'),
('XH6L68', 'Meningioma, angiomatoso', 'category', false, false, 'CIE-11'),
('XH4EX5', 'Meningioma, transicional', 'category', false, false, 'CIE-11'),
('XH0324', 'Meningioma, maligno', 'category', false, false, 'CIE-11'),
('XH2NY9', 'Meningioma papilar', 'category', false, false, 'CIE-11'),
('XH6QS9', 'Meningioma rabdoide', 'category', false, false, 'CIE-11'),
('XH5976', 'Sarcomatosis meningea', 'category', false, false, 'CIE-11'),
('XH71V9', 'Meningioma de células claras', 'category', false, false, 'CIE-11'),
('XH2LS4', 'Meningioma coroideo', 'category', false, false, 'CIE-11'),
('XH1PF6', 'Meningioma atípico', 'category', false, false, 'CIE-11'),
('XH3SX7', 'Adenoma de ovario neto', 'category', false, false, 'CIE-11'),
('XH5AH3', 'Mesonefroma, benigno', 'category', false, false, 'CIE-11'),
('XH71B5', 'Adenocarcinoma de ovario neto', 'category', false, false, 'CIE-11'),
('XH5WG5', 'Mesonefroma, maligno', 'category', false, false, 'CIE-11'),
('XH2WJ5', 'Tumor Wolffiano', 'category', false, false, 'CIE-11'),
('XH2VV6', 'Mesotelioma fibroso, benigno', 'category', false, false, 'CIE-11'),
('XH1SS1', 'Mesotelioma benigno', 'category', false, false, 'CIE-11'),
('XH0KC4', 'Mesotelioma epitelioide benigno', 'category', false, false, 'CIE-11'),
('XH67N8', 'Mesotelioma papilar bien diferenciado', 'category', false, false, 'CIE-11'),
('XH8U12', 'Quistes de inclusión peritoneales', 'category', false, false, 'CIE-11'),
('XH6BY3', 'Tumor adenomatoide, SAI', 'category', false, false, 'CIE-11'),
('XH54S8', 'Mesotelioma fibroso, maligno', 'category', false, false, 'CIE-11'),
('XH0XV0', 'Mesotelioma, maligno', 'category', false, false, 'CIE-11'),
('XH1DX8', 'Mesotelioma, bifásico, maligno', 'category', false, false, 'CIE-11'),
('XH0VP5', 'Mesotelioma epitelioide, maligno', 'category', false, false, 'CIE-11'),
('XH85T6', 'Mesotelioma papilar bien diferenciado de la pleura', 'category', false, false, 'CIE-11'),
('XH6M86', 'Fibroma osificante', 'category', false, false, 'CIE-11'),
('XH23E0', 'Quiste óseo aneurismático', 'category', false, false, 'CIE-11'),
('XH8F52', 'Adamantinoma de los huesos largos', 'category', false, false, 'CIE-11'),
('XH6C72', 'Tumor neuroectodérmico melanótico', 'category', false, false, 'CIE-11'),
('XH7MT7', 'Tumor de células de la notocorda benigno', 'category', false, false, 'CIE-11'),
('XH0S20', 'Paracordoma', 'category', false, false, 'CIE-11'),
('XH2S71', 'Tumor pineal mixto', 'category', false, false, 'CIE-11'),
('XH1S48', 'Tumor parenquimatoso pineal de diferenciación intermedia', 'category', false, false, 'CIE-11'),
('XH1ZH1', 'Pineoblastoma', 'category', false, false, 'CIE-11'),
('XH3D20', 'Tumor pineal de transición', 'category', false, false, 'CIE-11'),
('XH7K24', 'Tumor neuroectodérmico, SAI', 'category', false, false, 'CIE-11'),
('XH6P76', 'Tumor neuroectodérmico primitivo periférico', 'category', false, false, 'CIE-11'),
('XH9GH0', 'Cordoma, SAI', 'category', false, false, 'CIE-11'),
('XH8KJ8', 'Sarcoma de Ewing', 'category', false, false, 'CIE-11'),
('XH0FH0', 'Tumor de Askin', 'category', false, false, 'CIE-11'),
('XH17D8', 'Cordoma condroide', 'category', false, false, 'CIE-11'),
('XH7303', 'Cordoma diferenciado', 'category', false, false, 'CIE-11'),
('XH1AZ2', 'Craneofaringioma', 'category', false, false, 'CIE-11'),
('XH15X9', 'Craneofaringioma, adamantinomatoso', 'category', false, false, 'CIE-11'),
('XH2BF0', 'Craneofaringioma, papilar', 'category', false, false, 'CIE-11'),
('XH8QA9', 'Pinealoma', 'category', false, false, 'CIE-11'),
('XH1K94', 'Pineocitoma', 'category', false, false, 'CIE-11'),
('XH1J36', 'Carcinoma mucoepidermoide', 'category', false, false, 'CIE-11'),
('XH80V3', 'Tumor mucoepidermoide', 'category', false, false, 'CIE-11'),
('XH7CL0', 'Angiomioma', 'category', false, false, 'CIE-11'),
('XH9824', 'Leiomioma extraño', 'category', false, false, 'CIE-11'),
('XH9662', 'Leiomioma celular', 'category', false, false, 'CIE-11'),
('XH8S79', 'Leiomioma epitelioide', 'category', false, false, 'CIE-11'),
('XH4729', 'Rabdomioma fetal', 'category', false, false, 'CIE-11'),
('XH4FS5', 'Lipoleiomioma', 'category', false, false, 'CIE-11'),
('XH1CZ1', 'Mioma', 'category', false, false, 'CIE-11'),
('XH4EP9', 'Leiomioma plexiforme', 'category', false, false, 'CIE-11'),
('XH4CY6', 'Leiomioma, SAI', 'category', false, false, 'CIE-11'),
('XH9CC7', 'Leiomioma mixoide', 'category', false, false, 'CIE-11'),
('XH8WG9', 'Rabdomioma, SAI', 'category', false, false, 'CIE-11'),
('XH4BG5', 'Rabdomioma celular adulto', 'category', false, false, 'CIE-11'),
('XH2736', 'Rabdomioma glicogénico', 'category', false, false, 'CIE-11'),
('XH5AF2', 'Rabdomioma genital', 'category', false, false, 'CIE-11'),
('XH8B88', 'Leiomioma apoplético', 'category', false, false, 'CIE-11'),
('XH5Z76', 'Leiomioma hidrópico', 'category', false, false, 'CIE-11'),
('XH5G84', 'Leiomioma cotiledonoide', 'category', false, false, 'CIE-11'),
('XH6GV7', 'Miolipoma', 'category', false, false, 'CIE-11'),
('XH27W3', 'Angiomiosarcoma', 'category', false, false, 'CIE-11'),
('XH13Z5', 'Leiomisarcoma epitelioide', 'category', false, false, 'CIE-11'),
('XH7ED4', 'Leiomiosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH08B3', 'Rabdomiosarcoma embrionario mixto y rabdomiosarcoma alveolar', 'category', false, false, 'CIE-11'),
('XH6YL0', 'Rabdomiosarcoma de tipo mixto', 'category', false, false, 'CIE-11'),
('XH8H07', 'Miosarcoma', 'category', false, false, 'CIE-11'),
('XH3122', 'Leiomiosarcoma mixoide', 'category', false, false, 'CIE-11'),
('XH5SX9', 'Rabdomiosarcoma pleomórfico, SAI', 'category', false, false, 'CIE-11'),
('XH4VB5', 'Rabdomiosarcoma pleomórfico, tipo adulto', 'category', false, false, 'CIE-11'),
('XH0GA1', 'Rabdomiosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH83G1', 'Rabdomiosarcoma embrionario, SAI', 'category', false, false, 'CIE-11'),
('XH4749', 'Rabdomiosarcoma pleomórfico, pleomórfico', 'category', false, false, 'CIE-11'),
('XH7V57', 'Sarcoma botrioides', 'category', false, false, 'CIE-11'),
('XH7NM2', 'Rabdomiosarcoma de células fusiformes', 'category', false, false, 'CIE-11'),
('XH7099', 'Rabdomiosarcoma alveolar', 'category', false, false, 'CIE-11'),
('XH0S12', 'Ectomesenquimoma', 'category', false, false, 'CIE-11'),
('XH60C2', 'Leiomiomatosis intravascular', 'category', false, false, 'CIE-11'),
('XH2L80', 'Leiomiomatosis, SAI', 'category', false, false, 'CIE-11'),
('XH1EX8', 'Leiomioma metastásico', 'category', false, false, 'CIE-11'),
('XH1EN1', 'Tumor de músculo liso de potencial maligno incierto', 'category', false, false, 'CIE-11'),
('XH00B4', 'Tumor de músculo liso ,SAI', 'category', false, false, 'CIE-11'),
('XH8MR2', 'Leiomiomatosis, peritoneal diseminada', 'category', false, false, 'CIE-11'),
('XH22N2', 'Leiomiosarcoma cutáneo', 'category', false, false, 'CIE-11'),
('XH6Q84', 'Mixoma, SAI', 'category', false, false, 'CIE-11'),
('XH9HK9', 'Angiomixoma', 'category', false, false, 'CIE-11'),
('XH1DA7', 'Tumor fibromixoide osificante', 'category', false, false, 'CIE-11'),
('XH4V74', 'Angiomixoma profundo', 'category', false, false, 'CIE-11'),
('XH58A9', 'Angiomixoma superficial', 'category', false, false, 'CIE-11'),
('XH4V76', 'Sarcoma fibromixoide de bajo grado', 'category', false, false, 'CIE-11'),
('XH4BT2', 'Fibrosarcoma epitelioide esclerosante', 'category', false, false, 'CIE-11'),
('XH3TB0', 'Tumor fibromixoide osificante, maligno', 'category', false, false, 'CIE-11'),
('XH51Y9', 'Sarcoma mixoide pulmonar con translocación EWSR1-CREB1', 'category', false, false, 'CIE-11'),
('XH5WF6', 'Mixosarcoma', 'category', false, false, 'CIE-11'),
('XH5T39', 'Neuroma acústico', 'category', false, false, 'CIE-11'),
('XH0U07', 'Schwannoma antiguo', 'category', false, false, 'CIE-11'),
('XH8WW8', 'Schwannoma celular', 'category', false, false, 'CIE-11'),
('XH75P8', 'Schwannoma degenerado', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;