BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('9C61.21', 'Glaucoma pigmentario de ángulo abierto', 'category', false, false, 'CIE-11'),
('9C61.22', 'Glaucoma secundario de ángulo abierto inducido por el cristalino', 'category', false, false, 'CIE-11'),
('9C61.23', 'Glaucoma asociado a hemorragia intraocular', 'category', false, false, 'CIE-11'),
('9C61.24', 'Glaucoma por inflamación ocular', 'category', false, false, 'CIE-11'),
('9C61.25', 'Crisis glaucomatociclítica', 'category', false, false, 'CIE-11'),
('9C61.26', 'Glaucoma secundario - ángulo abierto por parasitosis ocular', 'category', false, false, 'CIE-11'),
('9C61.27', 'Glaucoma por tumor intraocular', 'category', false, false, 'CIE-11'),
('9C61.28', 'Glaucoma asociado a desprendimiento de retina', 'category', false, false, 'CIE-11'),
('9C61.29', 'Glaucoma por traumatismo ocular', 'category', false, false, 'CIE-11'),
('9C61.2A', 'Glaucoma por medicamentos', 'category', false, false, 'CIE-11'),
('9C61.2B', 'Glaucoma por aumento de la presión venosa epiescleral', 'category', false, false, 'CIE-11'),
('9C61.2C', 'Glaucoma secundario por masa extraocular', 'category', false, false, 'CIE-11'),
('9C61.2Y', 'Otro glaucoma secundario especificado de ángulo abierto', 'category', false, false, 'CIE-11'),
('9C61.2Z', 'Glaucoma secundario de ángulo abierto, sin especificación', 'category', false, false, 'CIE-11'),
('9C61.3', 'Glaucoma secundario de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.30', 'Glaucoma secundario de ángulo cerrado con bloqueo pupilar', 'category', false, false, 'CIE-11'),
('9C61.31', 'Glaucoma secundario de ángulo cerrado sin bloqueo pupilar', 'category', false, false, 'CIE-11'),
('9C61.32', 'Glaucoma secundario neovascular de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.33', 'Glaucoma secundario de ángulo cerrado por proliferación endotelial', 'category', false, false, 'CIE-11'),
('9C61.34', 'Glaucoma secundario de ángulo cerrado por penetración epitelial', 'category', false, false, 'CIE-11'),
('9C61.35', 'Glaucoma por bloqueo ciliar', 'category', false, false, 'CIE-11'),
('9C61.36', 'Glaucoma secundario de ángulo cerrado por otro desplazamiento anterior del diafragma iridocristaliniano', 'category', false, false, 'CIE-11'),
('9C61.3Y', 'Otro glaucoma secundario especificado de ángulo cerrado', 'category', false, false, 'CIE-11'),
('9C61.3Z', 'Glaucoma secundario de ángulo cerrado, sin especificación', 'category', false, false, 'CIE-11'),
('9C61.4', 'Glaucoma del desarrollo', 'category', false, false, 'CIE-11'),
('9C61.40', 'Glaucoma congénito primario', 'category', false, false, 'CIE-11'),
('9C61.41', 'Glaucoma infantil primario', 'category', false, false, 'CIE-11'),
('9C61.42', 'Glaucoma infantil secundario', 'category', false, false, 'CIE-11'),
('9C61.4Y', 'Otro glaucoma del desarrollo especificado', 'category', false, false, 'CIE-11'),
('9C61.4Z', 'Glaucoma del desarrollo, sin especificación', 'category', false, false, 'CIE-11'),
('9C61.Z', 'Glaucoma, sin especificación', 'category', false, false, 'CIE-11'),
('9C6Y', 'Otro glaucoma o sospecha de glaucoma especificados', 'category', false, false, 'CIE-11'),
('9C6Z', 'Glaucoma o sospecha de glaucoma, sin especificación', 'category', false, false, 'CIE-11'),
('9C80', 'Estrabismo no paralítico', 'category', false, false, 'CIE-11'),
('9C80.0', 'Estrabismo convergente', 'category', false, false, 'CIE-11'),
('9C80.1', 'estrabismo divergente', 'category', false, false, 'CIE-11'),
('9C80.2', 'Estrabismo vertical o de torsión', 'category', false, false, 'CIE-11'),
('9C80.3', 'Estrabismo intermitente', 'category', false, false, 'CIE-11'),
('9C80.30', 'Exotropía divergente intermitente', 'category', false, false, 'CIE-11'),
('9C80.31', 'Esotropía convergente intermitente', 'category', false, false, 'CIE-11'),
('9C80.3Y', 'Otro estrabismo intermitente especificado', 'category', false, false, 'CIE-11'),
('9C80.3Z', 'Estrabismo intermitente, sin especificación', 'category', false, false, 'CIE-11'),
('9C80.4', 'Heteroforia', 'category', false, false, 'CIE-11'),
('9C80.5', 'Estrabismo mecánico', 'category', false, false, 'CIE-11'),
('9C80.Y', 'Otro estrabismo no paralítico especificado', 'category', false, false, 'CIE-11'),
('9C80.Z', 'Estrabismo no paralítico, sin especificación', 'category', false, false, 'CIE-11'),
('9C81', 'Parálisis del nervio motor ocular', 'category', false, false, 'CIE-11'),
('9C81.0', 'Parálisis del tercer par', 'category', false, false, 'CIE-11'),
('9C81.00', 'Parálisis bilateral externa del nervio motor ocular común', 'category', false, false, 'CIE-11'),
('9C81.0Y', 'Otra parálisis especificada del tercer par', 'category', false, false, 'CIE-11'),
('9C81.0Z', 'Parálisis del tercer par, sin especificación', 'category', false, false, 'CIE-11'),
('9C81.1', 'Parálisis del cuarto par', 'category', false, false, 'CIE-11'),
('9C81.2', 'Parálisis del sexto par', 'category', false, false, 'CIE-11'),
('9C81.3', 'Oftalmoplejia externa total', 'category', false, false, 'CIE-11'),
('9C81.4', 'Síndrome del seno cavernoso', 'category', false, false, 'CIE-11'),
('9C81.Y', 'Otras parálisis del nervio motor ocular especificadas', 'category', false, false, 'CIE-11'),
('9C81.Z', 'Parálisis del nervio motor ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9C82', 'Trastornos de los músculos extraoculares', 'category', false, false, 'CIE-11'),
('9C82.0', 'Oftalmoplejia externa progresiva', 'category', false, false, 'CIE-11'),
('9C82.1', 'Distrofia muscular con afectación de músculo extraocular', 'category', false, false, 'CIE-11'),
('9C82.2', 'Síndrome de disinervación craneal congénita', 'category', false, false, 'CIE-11'),
('9C82.3', 'Oftalmopatía restrictiva', 'category', false, false, 'CIE-11'),
('9C82.4', 'Apraxia oculomotora', 'category', false, false, 'CIE-11'),
('9C82.Y', 'Otros trastornos especificados de los músculos extraoculares', 'category', false, false, 'CIE-11'),
('9C82.Z', 'Trastornos de los músculos extraoculares, sin especificación', 'category', false, false, 'CIE-11'),
('9C83', 'Trastornos del movimiento binocular', 'category', false, false, 'CIE-11'),
('9C83.0', 'Parálisis de la mirada conjugada', 'category', false, false, 'CIE-11'),
('9C83.00', 'Parálisis de la mirada horizontal', 'category', false, false, 'CIE-11'),
('9C83.01', 'Parálisis de la mirada vertical', 'category', false, false, 'CIE-11'),
('9C83.02', 'Parálisis monocular de los elevadores', 'category', false, false, 'CIE-11'),
('9C83.0Y', 'Otra parálisis especificada de la mirada conjugada', 'category', false, false, 'CIE-11'),
('9C83.0Z', 'Parálisis de la mirada conjugada, sin especificación', 'category', false, false, 'CIE-11'),
('9C83.1', 'Espasmo de la mirada conjugada', 'category', false, false, 'CIE-11'),
('9C83.10', 'Desviación conjugada de la mirada horizontal', 'category', false, false, 'CIE-11'),
('9C83.11', 'Desviación de la mirada hacia arriba', 'category', false, false, 'CIE-11'),
('9C83.12', 'Desviación de la mirada hacia abajo', 'category', false, false, 'CIE-11'),
('9C83.13', 'Crisis oculógiras', 'category', false, false, 'CIE-11'),
('9C83.1Y', 'Otro espasmo especificado de la mirada conjugada', 'category', false, false, 'CIE-11'),
('9C83.1Z', 'Espasmo de la mirada conjugada, sin especificación', 'category', false, false, 'CIE-11'),
('9C83.2', 'Insuficiencia de convergencia', 'category', false, false, 'CIE-11'),
('9C83.3', 'Exceso de convergencia', 'category', false, false, 'CIE-11'),
('9C83.4', 'Espasmo del reflejo cercano', 'category', false, false, 'CIE-11'),
('9C83.5', 'Oftalmoplejia internuclear', 'category', false, false, 'CIE-11'),
('9C83.6', 'Anomalías de divergencia o desviación del movimiento ocular', 'category', false, false, 'CIE-11'),
('9C83.60', 'Insuficiencia de divergencia', 'category', false, false, 'CIE-11'),
('9C83.61', 'Parálisis de la divergencia', 'category', false, false, 'CIE-11'),
('9C83.62', 'Exceso de divergencia', 'category', false, false, 'CIE-11'),
('9C83.63', 'Divergencia sinérgica', 'category', false, false, 'CIE-11'),
('9C83.64', 'Desviación oblicua', 'category', false, false, 'CIE-11'),
('9C83.65', 'Reacción ocular de inclinación', 'category', false, false, 'CIE-11'),
('9C83.66', 'Desviación oblicua alternante', 'category', false, false, 'CIE-11'),
('9C83.67', 'Divergencia vertical disociativa', 'category', false, false, 'CIE-11'),
('9C83.6Y', 'Otras anomalías especificadas de divergencia o desviación del movimiento ocular', 'category', false, false, 'CIE-11'),
('9C83.6Z', 'Anomalías de divergencia o desviación del movimiento ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9C83.Y', 'Otros trastornos especificados del movimiento binocular', 'category', false, false, 'CIE-11'),
('9C83.Z', 'Trastornos del movimiento binocular, sin especificación', 'category', false, false, 'CIE-11'),
('9C84', 'Nistagmo', 'category', false, false, 'CIE-11'),
('9C84.0', 'Nistagmo fisiológico', 'category', false, false, 'CIE-11'),
('9C84.1', 'Formas congénitas de nistagmo', 'category', false, false, 'CIE-11'),
('9C84.2', 'Nistagmo vestibular', 'category', false, false, 'CIE-11'),
('9C84.20', 'Nistagmo hacia abajo', 'category', false, false, 'CIE-11'),
('9C84.21', 'Nistagmo hacia arriba', 'category', false, false, 'CIE-11'),
('9C84.22', 'Nistagmo de torsión', 'category', false, false, 'CIE-11'),
('9C84.23', 'Nistagmo pervertido', 'category', false, false, 'CIE-11'),
('9C84.2Y', 'Otro nistagmo vestibular especificado', 'category', false, false, 'CIE-11'),
('9C84.2Z', 'Nistagmo vestibular, sin especificación', 'category', false, false, 'CIE-11'),
('9C84.3', 'Nistagmo en balancín', 'category', false, false, 'CIE-11'),
('9C84.4', 'Nistagmo provocado por la mirada', 'category', false, false, 'CIE-11'),
('9C84.5', 'Nistagmo en trastornos del sistema visual', 'category', false, false, 'CIE-11'),
('9C84.50', 'Nistagmo por privación visual', 'category', false, false, 'CIE-11'),
('9C84.51', 'Nistagmo divergente', 'category', false, false, 'CIE-11'),
('9C84.52', 'Nistagmo de retracción convergente', 'category', false, false, 'CIE-11'),
('9C84.5Y', 'Otro nistagmo especificado en trastornos del sistema visual', 'category', false, false, 'CIE-11'),
('9C84.5Z', 'Nistagmo en trastornos del sistema visual, sin especificación', 'category', false, false, 'CIE-11'),
('9C84.6', 'Nistagmo palpebral', 'category', false, false, 'CIE-11'),
('9C84.Y', 'Otro nistagmo especificado', 'category', false, false, 'CIE-11'),
('9C84.Z', 'Nistagmo, sin especificación', 'category', false, false, 'CIE-11'),
('9C85', 'Algunos movimientos oculares irregulares especificados', 'category', false, false, 'CIE-11'),
('9C85.0', 'Anomalías de los movimientos oculares sacádicos', 'category', false, false, 'CIE-11'),
('9C85.00', 'Trastornos de pulso sacádico', 'category', false, false, 'CIE-11'),
('9C85.01', 'Trastornos del intervalo sacádico', 'category', false, false, 'CIE-11'),
('9C85.02', 'Movimientos sacádicos inadecuados', 'category', false, false, 'CIE-11'),
('9C85.0Y', 'Otras anomalías especificadas de los movimientos oculares sacádicos', 'category', false, false, 'CIE-11'),
('9C85.0Z', 'Anomalías de los movimientos oculares sacádicos, sin especificación', 'category', false, false, 'CIE-11'),
('9C85.1', 'Anomalías de los movimientos de seguimiento lento', 'category', false, false, 'CIE-11'),
('9C85.2', 'Trastornos no orgánicos de los movimientos oculares', 'category', false, false, 'CIE-11'),
('9C85.Y', 'Otros movimientos oculares irregulares especificados', 'category', false, false, 'CIE-11'),
('9C85.Z', 'Algunos movimientos oculares irregulares especificados, sin especificación', 'category', false, false, 'CIE-11'),
('9C8Y', 'Otro estrabismo o trastorno especificado de la movilidad ocular', 'category', false, false, 'CIE-11'),
('9C8Z', 'Estrabismo o trastorno de la movilidad ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9D00', 'Trastornos de la refracción', 'category', false, false, 'CIE-11'),
('9D00.0', 'Miopía', 'category', false, false, 'CIE-11'),
('9D00.1', 'Hipermetropía', 'category', false, false, 'CIE-11'),
('9D00.2', 'Astigmatismo', 'category', false, false, 'CIE-11'),
('9D00.3', 'Presbicia', 'category', false, false, 'CIE-11'),
('9D00.4', 'Anisometropía', 'category', false, false, 'CIE-11'),
('9D00.5', 'Aniseiconia', 'category', false, false, 'CIE-11'),
('9D00.6', 'Cambio refractivo transitorio', 'category', false, false, 'CIE-11'),
('9D00.Y', 'Otros trastornos especificados de la refracción', 'category', false, false, 'CIE-11'),
('9D00.Z', 'Trastornos de la refracción, sin especificación', 'category', false, false, 'CIE-11'),
('9D01', 'Trastornos de la acomodación', 'category', false, false, 'CIE-11'),
('9D01.0', 'Oftalmoplejia interna', 'category', false, false, 'CIE-11'),
('9D01.1', 'Paresia de acomodación', 'category', false, false, 'CIE-11'),
('9D01.2', 'Espasmo de acomodación', 'category', false, false, 'CIE-11'),
('9D01.Y', 'Otros trastornos especificados de la acomodación', 'category', false, false, 'CIE-11'),
('9D01.Z', 'Trastornos de la acomodación, sin especificación', 'category', false, false, 'CIE-11'),
('9D0Y', 'Otros trastornos especificados de refracción o acomodación', 'category', false, false, 'CIE-11'),
('9D0Z', 'Trastornos de refracción o acomodación, sin especificación', 'category', false, false, 'CIE-11'),
('9D20', 'Queratopatía ampollosa afáquica tras cirugía de catarata', 'category', false, false, 'CIE-11'),
('9D21', 'Fragmentos de catarata en el ojo tras cirugía de catarata', 'category', false, false, 'CIE-11'),
('9D22', 'Cicatrices coriorretinianas tras cirugía por desprendimiento', 'category', false, false, 'CIE-11'),
('9D23', 'Ampulitis conjuntival tras cirugía de glaucoma', 'category', false, false, 'CIE-11'),
('9D24', 'Complicaciones con dispositivos de drenaje para glaucoma.', 'category', false, false, 'CIE-11'),
('9D25', 'Glaucoma por láser o cirugía ocular', 'category', false, false, 'CIE-11'),
('9D41', 'Deficiencia del campo visual', 'category', false, false, 'CIE-11'),
('9D42', 'Patrones de deficiencia del campo visual', 'category', false, false, 'CIE-11'),
('9D42.2', 'Déficit de campo periférico', 'category', false, false, 'CIE-11'),
('9D42.20', 'Ampliación de la mancha ciega', 'category', false, false, 'CIE-11'),
('9D42.21', 'Escotoma arqueado', 'category', false, false, 'CIE-11'),
('9D42.22', 'Escalón nasal', 'category', false, false, 'CIE-11'),
('9D42.23', 'Escotoma anular', 'category', false, false, 'CIE-11'),
('9D42.24', 'Escotoma periférico aislado', 'category', false, false, 'CIE-11'),
('9D42.2Y', 'Otro déficit de campo periférico especificado', 'category', false, false, 'CIE-11'),
('9D42.2Z', 'Déficit de campo periférico, sin especificación', 'category', false, false, 'CIE-11'),
('9D42.3', 'Defecto hemianópico o cuadrantanópico', 'category', false, false, 'CIE-11'),
('9D42.4', 'Escotoma central', 'category', false, false, 'CIE-11'),
('9D42.5', 'Escotoma paracentral', 'category', false, false, 'CIE-11'),
('9D42.6', 'Hemianopsia o cuadrantanopsia homónimas', 'category', false, false, 'CIE-11'),
('9D42.60', 'Hemianopsia o cuadrantanopsia homónimas del hemicampo derecho', 'category', false, false, 'CIE-11'),
('9D42.61', 'Hemianopsia o cuadrantanopsia homónimas del hemicampo izquierdo', 'category', false, false, 'CIE-11'),
('9D42.6Y', 'Otra hemianopsia o cuadrantanopsia homónimas especificadas', 'category', false, false, 'CIE-11'),
('9D42.6Z', 'Hemianopsia o cuadrantanopsia homónimas, sin especificación', 'category', false, false, 'CIE-11'),
('9D42.7', 'Hemianopsia o cuadrantanopsia heterónimas', 'category', false, false, 'CIE-11'),
('9D42.70', 'Hemianopsia o cuadrantanopsia heterónimas binasales', 'category', false, false, 'CIE-11'),
('9D42.71', 'Hemianopsia o cuadrantanopsia heterónimas bitemporales', 'category', false, false, 'CIE-11'),
('9D42.7Y', 'Otra hemianopsia o cuadrantanopsia heterónimas especificadas', 'category', false, false, 'CIE-11'),
('9D42.7Z', 'Hemianopsia o cuadrantanopsia heterónimas, sin especificación', 'category', false, false, 'CIE-11'),
('9D42.Y', 'Otros patrones especificados de deficiencia del campo visual', 'category', false, false, 'CIE-11'),
('9D42.Z', 'Patrones de deficiencia del campo visual, sin especificación', 'category', false, false, 'CIE-11'),
('9D43', 'Deficiencia de la visión de contraste', 'category', false, false, 'CIE-11'),
('9D44', 'Deficiencia de la visión cromática', 'category', false, false, 'CIE-11'),
('9D45', 'Deficiencia de la sensibilidad a la luz', 'category', false, false, 'CIE-11'),
('9D46', 'Deficiencia de las funciones binoculares', 'category', false, false, 'CIE-11'),
('9D50', 'Fatiga ocular', 'category', false, false, 'CIE-11'),
('9D51', 'Pérdida visual transitoria', 'category', false, false, 'CIE-11'),
('9D52', 'Pérdidas de hemicampo', 'category', false, false, 'CIE-11'),
('9D53', 'Fenómenos entópticos', 'category', false, false, 'CIE-11'),
('9D54', 'Ilusiones visuales', 'category', false, false, 'CIE-11'),
('9D55', 'Pérdida visual no orgánica', 'category', false, false, 'CIE-11'),
('9D56', 'Síndrome de Charles Bonnet', 'category', false, false, 'CIE-11'),
('9D5Y', 'Otras experiencias visuales subjetivas especificadas', 'category', false, false, 'CIE-11'),
('9D5Z', 'Experiencias visuales subjetivas, sin especificación', 'category', false, false, 'CIE-11'),
('9D7Y', 'Otra deficiencia especificada de las funciones visuales', 'category', false, false, 'CIE-11'),
('9D7Z', 'Deficiencia de las funciones visuales, sin especificación', 'category', false, false, 'CIE-11'),
('9D90', 'Deficiencia visual, incluida la ceguera', 'category', false, false, 'CIE-11'),
('9D90.1', 'Deficiencia leve de la visión', 'category', false, false, 'CIE-11'),
('9D90.2', 'Deficiencia moderada de la visión', 'category', false, false, 'CIE-11'),
('9D90.3', 'Deficiencia grave de la visión', 'category', false, false, 'CIE-11'),
('9D90.6', 'Ceguera', 'category', false, false, 'CIE-11'),
('9D90.7', 'Deficiencia de visión cercana', 'category', false, false, 'CIE-11'),
('9D92', 'Disfunciones visuales específicas', 'category', false, false, 'CIE-11'),
('9D93', 'Disfunciones complejas relacionadas con la visión', 'category', false, false, 'CIE-11'),
('9D94', 'Deficiencia de la agudeza visual actual', 'category', false, false, 'CIE-11'),
('9D95', 'Deficiencia de la agudeza visual mejor corregida', 'category', false, false, 'CIE-11'),
('9D96', 'Deficiencia de la agudeza visual no corregida', 'category', false, false, 'CIE-11'),
('9D9Y', 'Otra deficiencia especificada de la visión', 'category', false, false, 'CIE-11'),
('9D9Z', 'Deficiencia de la visión, sin especificación', 'category', false, false, 'CIE-11'),
('9E1Y', 'Otras enfermedades especificadas del sistema visual', 'category', false, false, 'CIE-11'),
('9E1Z', 'Enfermedades del sistema visual, sin especificación', 'category', false, false, 'CIE-11'),
('AA00', 'Absceso del oído externo', 'category', false, false, 'CIE-11'),
('AA01', 'Celulitis del oído externo', 'category', false, false, 'CIE-11'),
('AA02', 'Otitis externa maligna', 'category', false, false, 'CIE-11'),
('AA03', 'Otomicosis', 'category', false, false, 'CIE-11'),
('AA04', 'Pericondritis del oído externo', 'category', false, false, 'CIE-11'),
('AA0Y', 'Otras enfermedades infecciosas especificadas del oído externo', 'category', false, false, 'CIE-11'),
('AA0Z', 'Enfermedades infecciosas del oído externo, sin especificación', 'category', false, false, 'CIE-11'),
('AA10', 'Otitis seborreica externa', 'category', false, false, 'CIE-11'),
('AA11', 'Otitis externa aguda no infecciosa', 'category', false, false, 'CIE-11'),
('AA12', 'Condrodermatitis nodular', 'category', false, false, 'CIE-11'),
('AA13', 'Otitis externa crónica', 'category', false, false, 'CIE-11'),
('AA1Y', 'Otra inflamación no infecciosa especificada del oído externo', 'category', false, false, 'CIE-11'),
('AA1Z', 'Inflamación no infecciosa del oído externo, sin especificación', 'category', false, false, 'CIE-11'),
('AA3Y', 'Otro(a)(s) otitis externa especificado(a)(s)', 'category', false, false, 'CIE-11'),
('AA3Z', 'Otitis externa, sin especificación', 'category', false, false, 'CIE-11'),
('AA40', 'Deformidad adquirida del conducto auditivo externo', 'category', false, false, 'CIE-11'),
('AA40.0', 'Exostosis del conducto auditivo externo', 'category', false, false, 'CIE-11'),
('AA40.1', 'Estenosis adquirida del conducto auditivo externo', 'category', false, false, 'CIE-11'),
('AA40.2', 'Colesteatoma del conducto auditivo externo', 'category', false, false, 'CIE-11'),
('AA40.Y', 'Otra deformidad adquirida especificada del conducto auditivo externo', 'category', false, false, 'CIE-11'),
('AA40.Z', 'Deformidad adquirida del conducto auditivo externo, sin especificación', 'category', false, false, 'CIE-11'),
('AA41', 'Deformidad adquirida del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('AA41.0', 'Oreja en coliflor', 'category', false, false, 'CIE-11'),
('AA41.Y', 'Otra deformidad adquirida especificada del pabellón de la oreja', 'category', false, false, 'CIE-11'),
('AA41.Z', 'Deformidad adquirida del pabellón de la oreja, sin especificación', 'category', false, false, 'CIE-11'),
('AA42', 'Tapón de cerumen en el oído', 'category', false, false, 'CIE-11'),
('AA4Y', 'Otros trastornos no inflamatorios especificados del oído externo', 'category', false, false, 'CIE-11'),
('AA4Z', 'Trastornos no inflamatorios del oído externo, sin especificación', 'category', false, false, 'CIE-11'),
('AA6Z', 'Enfermedades del oído externo, sin especificación', 'category', false, false, 'CIE-11'),
('AA80', 'Otitis media aguda mucosa o serosa', 'category', false, false, 'CIE-11'),
('AA81', 'Otitis media no supurativa, no serosa aguda', 'category', false, false, 'CIE-11'),
('AA82', 'Otitis media mucoide o serosa crónica', 'category', false, false, 'CIE-11'),
('AA83', 'Otitis media no infectada con derrame', 'category', false, false, 'CIE-11'),
('AA8Z', 'Otitis media no supurativa, sin especificación', 'category', false, false, 'CIE-11'),
('AA90', 'Otitis media supurativa aguda', 'category', false, false, 'CIE-11'),
('AA91', 'Otitis media supurativa crónica', 'category', false, false, 'CIE-11'),
('AA91.0', 'Otitis media supurativa tubo timpánica crónica', 'category', false, false, 'CIE-11'),
('AA91.1', 'Otitis media supurativa aticoantral crónica', 'category', false, false, 'CIE-11'),
('AA91.2', 'Otra otitis media supurativa crónica', 'category', false, false, 'CIE-11'),
('AA91.Z', 'Otitis media supurativa crónica, sin especificación', 'category', false, false, 'CIE-11'),
('AA9Z', 'Otitis media supurativa, sin especificación', 'category', false, false, 'CIE-11'),
('AB00', 'Otitis media aguda', 'category', false, false, 'CIE-11'),
('AB01', 'Otitis media crónica', 'category', false, false, 'CIE-11'),
('AB0Y', 'Otra otitis media especificada', 'category', false, false, 'CIE-11'),
('AB0Z', 'Otitis media, sin especificación', 'category', false, false, 'CIE-11'),
('AB10', 'Trastornos de la trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('AB10.0', 'Divertículo de la trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('AB10.1', 'Trompa de Eustaquio distendida', 'category', false, false, 'CIE-11'),
('AB10.2', 'Inflamación de la trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('AB10.3', 'Obstrucción de la trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('AB10.Y', 'Otros trastornos especificados de la trompa de Eustaquio', 'category', false, false, 'CIE-11'),
('AB10.Z', 'Trastornos de la trompa de Eustaquio, sin especificación', 'category', false, false, 'CIE-11'),
('AB11', 'Mastoiditis y afecciones relacionadas', 'category', false, false, 'CIE-11'),
('AB11.0', 'Mastoiditis aguda', 'category', false, false, 'CIE-11'),
('AB11.1', 'Mastoiditis crónica', 'category', false, false, 'CIE-11'),
('AB11.2', 'Petrositis', 'category', false, false, 'CIE-11'),
('AB11.3', 'Mastoiditis, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('AB11.Y', 'Otras mastoiditis y afecciones relacionadas especificadas', 'category', false, false, 'CIE-11'),
('AB12', 'Colesteatoma del oído medio', 'category', false, false, 'CIE-11'),
('AB13', 'Perforación de la membrana timpánica', 'category', false, false, 'CIE-11'),
('AB13.0', 'Perforación central de la membrana timpánica', 'category', false, false, 'CIE-11'),
('AB13.1', 'Perforación del ático de la membrana timpánica', 'category', false, false, 'CIE-11'),
('AB13.2', 'Otras perforaciones marginales de la membrana timpánica', 'category', false, false, 'CIE-11'),
('AB13.Y', 'Otra perforación especificada de la membrana timpánica', 'category', false, false, 'CIE-11'),
('AB13.Z', 'Perforación de la membrana timpánica, sin especificación', 'category', false, false, 'CIE-11'),
('AB14', 'Miringitis aguda', 'category', false, false, 'CIE-11'),
('AB15', 'Miringitis crónica', 'category', false, false, 'CIE-11'),
('AB16', 'Timpanoesclerosis', 'category', false, false, 'CIE-11'),
('AB17', 'Enfermedad adhesiva del oído medio', 'category', false, false, 'CIE-11'),
('AB18', 'Discontinuidad o luxación de los huesecillos del oído', 'category', false, false, 'CIE-11'),
('AB19', 'Anomalías adquiridas de los huesecillos del oído que no están relacionados con la discontinuidad o la dislocación', 'category', false, false, 'CIE-11'),
('AB1A', 'Pólipo del oído medio', 'category', false, false, 'CIE-11'),
('AB1A.0', 'Pólipo auricular', 'category', false, false, 'CIE-11'),
('AB1A.Y', 'Otro pólipo especificado del oído medio', 'category', false, false, 'CIE-11'),
('AB1A.Z', 'Pólipo del oído medio, sin especificación', 'category', false, false, 'CIE-11'),
('AB1B', 'Cicatriz del oído medio', 'category', false, false, 'CIE-11'),
('AB1Y', 'Otras enfermedades especificadas del oído medio o de la apófisis mastoides', 'category', false, false, 'CIE-11'),
('AB1Z', 'Enfermedades del oído medio o de la apófisis mastoides, sin especificación', 'category', false, false, 'CIE-11'),
('AB30', 'Síndrome vestibular agudo', 'category', false, false, 'CIE-11'),
('AB30.0', 'Neuritis vestibular', 'category', false, false, 'CIE-11'),
('AB30.1', 'Laberintitis', 'category', false, false, 'CIE-11'),
('AB30.Y', 'Otro síndrome vestibular agudo especificado', 'category', false, false, 'CIE-11'),
('AB30.Z', 'Síndrome vestibular agudo, sin especificación', 'category', false, false, 'CIE-11'),
('AB31', 'Síndrome vestibular episódico', 'category', false, false, 'CIE-11'),
('AB31.0', 'Enfermedad de Ménière', 'category', false, false, 'CIE-11'),
('AB31.1', 'Migraña vestibular', 'category', false, false, 'CIE-11'),
('AB31.2', 'Vértigo postural paroxístico benigno', 'category', false, false, 'CIE-11'),
('AB31.3', 'Síndrome de dehiscencia del canal superior', 'category', false, false, 'CIE-11'),
('AB31.4', 'Síndrome del desembarco', 'category', false, false, 'CIE-11'),
('AB31.5', 'Enfermedad del oído interno autoinmunitaria', 'category', false, false, 'CIE-11'),
('AB31.6', 'Paroxismia vestibular', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;