BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XM0B62', 'Seta panaeolus sphinctrinu', 'category', false, false, 'CIE-11'),
('XM27Y3', 'Seta panaeolus subbalteatus', 'category', false, false, 'CIE-11'),
('XM44P3', 'Seta pleurocybella porrigens', 'category', false, false, 'CIE-11'),
('XM3CK7', 'Seta podostroma cornu-damae', 'category', false, false, 'CIE-11'),
('XM4321', 'Seta psilocybe semilanceata', 'category', false, false, 'CIE-11'),
('XM36C7', 'Seta russula subnigricans', 'category', false, false, 'CIE-11'),
('XM0QR2', 'Seta tricholoma equestre', 'category', false, false, 'CIE-11'),
('XM9KE6', 'Silicona', 'category', false, false, 'CIE-11'),
('XM3DP9', 'Dióxido de silicio', 'category', false, false, 'CIE-11'),
('XM98Y1', 'Planta abrus precatorius', 'category', false, false, 'CIE-11'),
('XM99Y1', 'Planta acónito', 'category', false, false, 'CIE-11'),
('XM2WR7', 'Aconitina', 'category', false, false, 'CIE-11'),
('XM3VB6', 'Planta acónito ferox', 'category', false, false, 'CIE-11'),
('XM7BA0', 'Planta actaea', 'category', false, false, 'CIE-11'),
('XM3QE1', 'Actaea spicata', 'category', false, false, 'CIE-11'),
('XM55K4', 'Planta aethusa cynapium', 'category', false, false, 'CIE-11'),
('XM3AF3', 'Planta anamirta cocculus', 'category', false, false, 'CIE-11'),
('XM6KR6', 'Picrotoxina', 'category', false, false, 'CIE-11'),
('XM8SE2', 'Planta toxicaria Antiaris', 'category', false, false, 'CIE-11'),
('XM2X16', 'Planta maculatum arum', 'category', false, false, 'CIE-11'),
('XM1EY0', 'Planta atropa belladonna', 'category', false, false, 'CIE-11'),
('XM17F2', 'Planta azadirachta', 'category', false, false, 'CIE-11'),
('XM5W16', 'Aceite de bergamota', 'category', false, false, 'CIE-11'),
('XM1GJ1', 'Almendras amargas', 'category', false, false, 'CIE-11'),
('XM4XS8', 'Disulfuro de dialilo', 'category', false, false, 'CIE-11'),
('XM6A31', 'Sesquiterpeno lactonas', 'category', false, false, 'CIE-11'),
('XM4W45', 'Citronelol', 'category', false, false, 'CIE-11'),
('XM9CQ1', 'Citral', 'category', false, false, 'CIE-11'),
('XM6CP3', 'Eugenol', 'category', false, false, 'CIE-11'),
('XM9CZ8', 'Extracto de evernia prunastri', 'category', false, false, 'CIE-11'),
('XM5AM5', 'Isoeugenol', 'category', false, false, 'CIE-11'),
('XM88U7', 'Ácido abietico', 'category', false, false, 'CIE-11'),
('XM9L39', 'Aceite de turpetina', 'category', false, false, 'CIE-11'),
('XM3B42', 'Atranorina', 'category', false, false, 'CIE-11'),
('XM4BW2', 'Planta blighia sapida', 'category', false, false, 'CIE-11'),
('XM6635', 'Ácido evernico', 'category', false, false, 'CIE-11'),
('XM26G6', 'Ácido úsnico', 'category', false, false, 'CIE-11'),
('XM3XH8', 'Granos y harinas', 'category', false, false, 'CIE-11'),
('XM21W4', 'Compuestos extraídos de plantas o hierbas', 'category', false, false, 'CIE-11'),
('XM7CA8', 'Hoja de estramonio', 'category', false, false, 'CIE-11'),
('XM1D48', 'Efedra', 'category', false, false, 'CIE-11'),
('XM82G2', 'Benjuí (tintura)', 'category', false, false, 'CIE-11'),
('XM9GX9', 'Mentol', 'category', false, false, 'CIE-11'),
('XM8UA9', 'Cianidanol', 'category', false, false, 'CIE-11'),
('XM4Y73', 'Gelsemina', 'category', false, false, 'CIE-11'),
('XM2YX0', 'Aceite de semilla de palma', 'category', false, false, 'CIE-11'),
('XM1PQ5', 'Tragacanto', 'category', false, false, 'CIE-11'),
('XM8VJ2', 'Planta datura stramonium', 'category', false, false, 'CIE-11'),
('XM8MB5', 'Goma', 'category', false, false, 'CIE-11'),
('XM0XN7', 'Planta de algodón', 'category', false, false, 'CIE-11'),
('XM1KF1', 'Sisal', 'category', false, false, 'CIE-11'),
('XM2BX6', 'Planta brucea javánica', 'category', false, false, 'CIE-11'),
('XM9B82', 'Planta caladium', 'category', false, false, 'CIE-11'),
('XM1021', 'Caladium bicolor', 'category', false, false, 'CIE-11'),
('XM0BS2', 'Caladium seguinum', 'category', false, false, 'CIE-11'),
('XM9S25', 'Cannabis (natural; fitotocannabinoides)', 'category', false, false, 'CIE-11'),
('XM08L6', 'Afganistán negro', 'category', false, false, 'CIE-11'),
('XM5WR8', 'Cáñamo indio', 'category', false, false, 'CIE-11'),
('XM3R78', 'Rojo libanés', 'category', false, false, 'CIE-11'),
('XM8PV1', 'Marijuana', 'category', false, false, 'CIE-11'),
('XM0WA6', 'Planta celastrus scandens', 'category', false, false, 'CIE-11'),
('XM5L03', 'Planta cerbera', 'category', false, false, 'CIE-11'),
('XM2KR7', 'Planta cerbera odollam', 'category', false, false, 'CIE-11'),
('XM1FN8', 'Planta cerbera manghas', 'category', false, false, 'CIE-11'),
('XM8AZ9', 'Planta Cerbera venenifera', 'category', false, false, 'CIE-11'),
('XM9DJ3', 'Planta chelidonium majus', 'category', false, false, 'CIE-11'),
('XM49V0', 'Planta crisantemo cinerariifolium', 'category', false, false, 'CIE-11'),
('XM5HR7', 'Piretrina no medicinal', 'category', false, false, 'CIE-11'),
('XM6709', 'Planta cicuta maculata', 'category', false, false, 'CIE-11'),
('XM1S86', 'Cicutoxina', 'category', false, false, 'CIE-11'),
('XM6YA3', 'Planta alcanforera', 'category', false, false, 'CIE-11'),
('XM5804', 'Planta clematis', 'category', false, false, 'CIE-11'),
('XM5D25', 'Planta clematis vitalba', 'category', false, false, 'CIE-11'),
('XM9KW2', 'Café', 'category', false, false, 'CIE-11'),
('XM7TP8', 'Planta colchicum', 'category', false, false, 'CIE-11'),
('XM3Q99', 'Colchicina', 'category', false, false, 'CIE-11'),
('XM9Z51', 'Planta conium maculatum', 'category', false, false, 'CIE-11'),
('XM3FY5', 'Coniina', 'category', false, false, 'CIE-11'),
('XM9T69', 'Planta convallaria majalis', 'category', false, false, 'CIE-11'),
('XM72P9', 'Planta ciclamen', 'category', false, false, 'CIE-11'),
('XM56R9', 'Planta cyclamen europaeum', 'category', false, false, 'CIE-11'),
('XM5174', 'Planta Cyclamen persicum', 'category', false, false, 'CIE-11'),
('XM5ZF9', 'Planta cytisus laburnum', 'category', false, false, 'CIE-11'),
('XM2YN7', 'Planta cytisus scoparius', 'category', false, false, 'CIE-11'),
('XM4TF9', 'Planta daphne', 'category', false, false, 'CIE-11'),
('XM8YH8', 'Planta delphinium', 'category', false, false, 'CIE-11'),
('XM3KT4', 'Planta elíptica derris', 'category', false, false, 'CIE-11'),
('XM46Y1', 'Planta digitalis purpurea', 'category', false, false, 'CIE-11'),
('XM1LE7', 'Planta erythroxylum coca lam', 'category', false, false, 'CIE-11'),
('XM7UN8', 'Cocaína', 'category', false, false, 'CIE-11'),
('XM0BC6', 'Cocaína anestésico tópico', 'category', false, false, 'CIE-11'),
('XM0XS0', 'Planta equisetum', 'category', false, false, 'CIE-11'),
('XM0EC2', 'Equisetum diurético', 'category', false, false, 'CIE-11'),
('XM4TJ7', 'Planta Euphorbia', 'category', false, false, 'CIE-11'),
('XM91T0', 'Planta Gaultheria procumbens', 'category', false, false, 'CIE-11'),
('XM5P41', 'Aceite vegetal de Gaultheria procumbens', 'category', false, false, 'CIE-11'),
('XM1VX3', 'Planta gelsemium sempervirens', 'category', false, false, 'CIE-11'),
('XM66Z7', 'Planta gloriosa superba', 'category', false, false, 'CIE-11'),
('XM5EL7', 'Planta graciola officinalis', 'category', false, false, 'CIE-11'),
('XM3QP5', 'Planta Helleborus niger', 'category', false, false, 'CIE-11'),
('XM0SF4', 'Planta heléboro viridis', 'category', false, false, 'CIE-11'),
('XM4UC8', 'Planta hyoscyamus niger', 'category', false, false, 'CIE-11'),
('XM3EA9', 'Planta ilex', 'category', false, false, 'CIE-11'),
('XM7ED8', 'Planta jatropha', 'category', false, false, 'CIE-11'),
('XM8QC3', 'Planta jatropha curcas', 'category', false, false, 'CIE-11'),
('XM7CZ8', 'Planta Jatropha gossypiifolia', 'category', false, false, 'CIE-11'),
('XM2C70', 'Planta jatropha hastata', 'category', false, false, 'CIE-11'),
('XM4R06', 'Planta Jatropha macrorhiza', 'category', false, false, 'CIE-11'),
('XM84E3', 'Planta Jatropha multifida', 'category', false, false, 'CIE-11'),
('XM04B0', 'Planta Jatropha podagrica', 'category', false, false, 'CIE-11'),
('XM7762', 'Látex', 'category', false, false, 'CIE-11'),
('XM5EH9', 'Planta lathyrus sativus', 'category', false, false, 'CIE-11'),
('XM5F38', 'Planta Ligustrum', 'category', false, false, 'CIE-11'),
('XM1WT1', 'Planta ligustrum lucidum', 'category', false, false, 'CIE-11'),
('XM4CK0', 'Planta ligustrum sinense', 'category', false, false, 'CIE-11'),
('XM23X8', 'Planta ligustrum vulgare', 'category', false, false, 'CIE-11'),
('XM2BQ5', 'Planta lobelia', 'category', false, false, 'CIE-11'),
('XM76G6', 'Planta lolium temulentum', 'category', false, false, 'CIE-11'),
('XM6LL4', 'Planta Manihot esculenta', 'category', false, false, 'CIE-11'),
('XM1TB2', 'Planta de melia azedarach', 'category', false, false, 'CIE-11'),
('XM3M91', 'Planta myristica fragrans', 'category', false, false, 'CIE-11'),
('XM6FE5', 'Aceite de nuez moscada', 'category', false, false, 'CIE-11'),
('XM31J1', 'Miristicina', 'category', false, false, 'CIE-11'),
('XM14Y1', 'Planta myrsine africana', 'category', false, false, 'CIE-11'),
('XM3XT1', 'Planta Nerium oleander', 'category', false, false, 'CIE-11'),
('XM2VY1', 'Planta nicotiana', 'category', false, false, 'CIE-11'),
('XM88J8', 'Tabaco', 'category', false, false, 'CIE-11'),
('XM33X3', 'Planta nuez vómica', 'category', false, false, 'CIE-11'),
('XM7134', 'Brucina', 'category', false, false, 'CIE-11'),
('XM5421', 'Estricnina', 'category', false, false, 'CIE-11'),
('XM9JS2', 'Estricnina rodenticida', 'category', false, false, 'CIE-11'),
('XM7JG0', 'Planta Physostigma venenosum', 'category', false, false, 'CIE-11'),
('XM61M4', 'Planta Phyitolaca decandra', 'category', false, false, 'CIE-11'),
('XM19G9', 'Aceite de pino', 'category', false, false, 'CIE-11'),
('XM1XZ4', 'Planta pimienta cubeba', 'category', false, false, 'CIE-11'),
('XM21J6', 'Planta roble venenoso', 'category', false, false, 'CIE-11'),
('XM4882', 'Planta zumaque venenoso', 'category', false, false, 'CIE-11'),
('XM95D5', 'Planta Prímula', 'category', false, false, 'CIE-11'),
('XM9HN7', 'Planta prímula obcónica', 'category', false, false, 'CIE-11'),
('XM07P7', 'Primin', 'category', false, false, 'CIE-11'),
('XM4TX6', 'Planta prímula officinalis', 'category', false, false, 'CIE-11'),
('XM19S7', 'Planta prímula veris', 'category', false, false, 'CIE-11'),
('XM3QL7', 'Planta prunus', 'category', false, false, 'CIE-11'),
('XM01R5', 'Amigdalina', 'category', false, false, 'CIE-11'),
('XM0PX4', 'Carozo de albaricoque', 'category', false, false, 'CIE-11'),
('XM5MK6', 'Hueso de cereza', 'category', false, false, 'CIE-11'),
('XM7B39', 'Carozo de Durazno', 'category', false, false, 'CIE-11'),
('XM52C3', 'Carozo de ciruela', 'category', false, false, 'CIE-11'),
('XM6Z57', 'Planta psoralea corilifolia', 'category', false, false, 'CIE-11'),
('XM1MV4', 'Psoraleno no medicinal', 'category', false, false, 'CIE-11'),
('XM03C0', 'Planta pulsatilla', 'category', false, false, 'CIE-11'),
('XM3PV6', 'Alcaloides de pirrolizidina', 'category', false, false, 'CIE-11'),
('XM0NB5', 'Planta Ranunculus', 'category', false, false, 'CIE-11'),
('XM0PR3', 'Planta ricinus communis', 'category', false, false, 'CIE-11'),
('XM2VG9', 'Ricino', 'category', false, false, 'CIE-11'),
('XM4AC2', 'Planta de ruda graveolens', 'category', false, false, 'CIE-11'),
('XM7BE0', 'Planta Sambucus', 'category', false, false, 'CIE-11'),
('XM9W70', 'Planta sanguinaria canadensis', 'category', false, false, 'CIE-11'),
('XM0EH6', 'Planta Schoenocaulon officinale', 'category', false, false, 'CIE-11'),
('XM4BY7', 'Insecticidas sabadilla', 'category', false, false, 'CIE-11'),
('XM8YX9', 'Planta senecio vulgaris', 'category', false, false, 'CIE-11'),
('XM4TE3', 'Planta solanum', 'category', false, false, 'CIE-11'),
('XM56G1', 'Planta solanum dulcamara', 'category', false, false, 'CIE-11'),
('XM1AE1', 'Planta solanum nigrum', 'category', false, false, 'CIE-11'),
('XM0QV6', 'Planta solanum pseudocapsicum', 'category', false, false, 'CIE-11'),
('XM9588', 'Solanina', 'category', false, false, 'CIE-11'),
('XM4UE4', 'Planta Spartium junceum', 'category', false, false, 'CIE-11'),
('XM9834', 'Planta strophanthus gratus', 'category', false, false, 'CIE-11'),
('XM9QZ9', 'Estrofantina - k', 'category', false, false, 'CIE-11'),
('XM58G8', 'Planta tanacetum', 'category', false, false, 'CIE-11'),
('XM7EL5', 'Ácido tartárico', 'category', false, false, 'CIE-11'),
('XM5YT6', 'Planta taxus', 'category', false, false, 'CIE-11'),
('XM6WF4', 'Planta tevetia peruana', 'category', false, false, 'CIE-11'),
('XM40N4', 'Planta toxicodendron radicans', 'category', false, false, 'CIE-11'),
('XM46N0', 'Planta urginea marina', 'category', false, false, 'CIE-11'),
('XM0SG7', 'Escilirosida', 'category', false, false, 'CIE-11'),
('XM84R4', 'Planta de ortiga', 'category', false, false, 'CIE-11'),
('XM5KR7', 'Planta veratrum', 'category', false, false, 'CIE-11'),
('XM86L8', 'Planta veratrum album', 'category', false, false, 'CIE-11'),
('XM9Z08', 'Planta veratrum viride', 'category', false, false, 'CIE-11'),
('XM43H5', 'Planta glicina', 'category', false, false, 'CIE-11'),
('XM29R2', 'Planta glicina floribunda', 'category', false, false, 'CIE-11'),
('XM8ZH3', 'Planta glicina sinensis', 'category', false, false, 'CIE-11'),
('XM6076', 'Planta Zigadenus', 'category', false, false, 'CIE-11'),
('XM8PU3', 'Pesticida derivados de plantas, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM98M9', 'Bayas de plantas venenosas, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM7MT6', 'Flores de plantas venenosas, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM6LL5', 'Frutos de plantas venenosas, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM2BH3', 'Hojas de plantas venenosas, no clasificada en otra parte.', 'category', false, false, 'CIE-11'),
('XM0GB3', 'Raíces de plantas venenosas, no clasificada en otra parte.', 'category', false, false, 'CIE-11'),
('XM2CE0', 'Savia de plantas venenosas, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM7JK8', 'Semillas de planta venenosa, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('XM7KY1', 'Tallo de plantas venenosas, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM56V2', 'Espinas de plantas venenosas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('XM5NH2', 'Sustancia de planta de origen marino, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XM8A62', 'Proteína vegetal', 'category', false, false, 'CIE-11'),
('XM7A46', 'Polvo de madera de haya americana', 'category', false, false, 'CIE-11'),
('XM4M03', 'Ppolvo de madera de roble', 'category', false, false, 'CIE-11'),
('XM6VG6', 'Polvo de madera de fresno europeo', 'category', false, false, 'CIE-11'),
('XM1K52', 'Manzana', 'category', false, false, 'CIE-11'),
('XM07U6', 'Plátano', 'category', false, false, 'CIE-11'),
('XM77D3', 'Uva', 'category', false, false, 'CIE-11'),
('XM4TY6', 'Kiwi', 'category', false, false, 'CIE-11'),
('XM6AW1', 'Mango', 'category', false, false, 'CIE-11'),
('XM0DF7', 'Melón', 'category', false, false, 'CIE-11'),
('XM2Q13', 'Aceituna', 'category', false, false, 'CIE-11'),
('XM2XN1', 'Naranja', 'category', false, false, 'CIE-11'),
('XM9UT8', 'Pimentón', 'category', false, false, 'CIE-11'),
('XM7S13', 'Repollo', 'category', false, false, 'CIE-11'),
('XM5J64', 'Pomelo', 'category', false, false, 'CIE-11'),
('XM5733', 'Pimienta negra', 'category', false, false, 'CIE-11'),
('XM9BG0', 'Judía verde', 'category', false, false, 'CIE-11'),
('XM25M2', 'Espinaca', 'category', false, false, 'CIE-11'),
('XM3EW6', 'Zarza mexicana', 'category', false, false, 'CIE-11'),
('XM3XQ1', 'Arroz', 'category', false, false, 'CIE-11'),
('XM9135', 'nuez pecana o nogal americano', 'category', false, false, 'CIE-11'),
('XM5S85', 'Durazno', 'category', false, false, 'CIE-11'),
('XM4GG6', 'Pera', 'category', false, false, 'CIE-11'),
('XM5ZK9', 'Fresa', 'category', false, false, 'CIE-11'),
('XM6E89', 'Piña', 'category', false, false, 'CIE-11'),
('XM9MB5', 'Cebada', 'category', false, false, 'CIE-11'),
('XM47Z9', 'Pasto Bahía', 'category', false, false, 'CIE-11'),
('XM5ZN2', 'Pasto Bermuda', 'category', false, false, 'CIE-11'),
('XM13D1', 'Alforfón', 'category', false, false, 'CIE-11'),
('XM3GC8', 'Maíz', 'category', false, false, 'CIE-11'),
('XM56U7', 'Gluten', 'category', false, false, 'CIE-11'),
('XM9898', 'Lúpulo japonés', 'category', false, false, 'CIE-11'),
('XM39Y3', 'Pasto Johnson', 'category', false, false, 'CIE-11'),
('XM0D79', 'Pasto azul Kentucky', 'category', false, false, 'CIE-11'),
('XM8X04', 'Avena', 'category', false, false, 'CIE-11'),
('XM6JA2', 'Centeno', 'category', false, false, 'CIE-11'),
('XM01D6', 'Ballico perenne', 'category', false, false, 'CIE-11'),
('XM8M82', 'Centeno cultivado', 'category', false, false, 'CIE-11'),
('XM4BW3', 'Hierba salada', 'category', false, false, 'CIE-11'),
('XM13U2', 'Hierba primaveral dulce', 'category', false, false, 'CIE-11'),
('XM94M9', 'Timoteo', 'category', false, false, 'CIE-11'),
('XM63G5', 'Aguacate', 'category', false, false, 'CIE-11'),
('XM1E00', 'Levadura de panadería', 'category', false, false, 'CIE-11'),
('XM9S46', 'Zanahoria', 'category', false, false, 'CIE-11'),
('XM1PN2', 'Apio', 'category', false, false, 'CIE-11'),
('XM5TW0', 'Pata de gallo', 'category', false, false, 'CIE-11'),
('XM9SJ1', 'Cacao', 'category', false, false, 'CIE-11'),
('XM9DZ5', 'Cenizo común', 'category', false, false, 'CIE-11'),
('XM5V61', 'Ambrosía común', 'category', false, false, 'CIE-11'),
('XM3KE2', 'Plátano inglés', 'category', false, false, 'CIE-11'),
('XM40Y5', 'Ajo', 'category', false, false, 'CIE-11'),
('XM4GX7', 'Pata de ganso', 'category', false, false, 'CIE-11'),
('XM1X29', 'Ambrosía gigante', 'category', false, false, 'CIE-11'),
('XM45L6', 'Lentejas', 'category', false, false, 'CIE-11'),
('XM6798', 'Lechuga', 'category', false, false, 'CIE-11'),
('XM0L96', 'Artemisa', 'category', false, false, 'CIE-11'),
('XM7GY3', 'Mostaza', 'category', false, false, 'CIE-11'),
('XM8F26', 'Ortiga', 'category', false, false, 'CIE-11'),
('XM9KB5', 'Cebolla', 'category', false, false, 'CIE-11'),
('XM56E2', 'Chícharo', 'category', false, false, 'CIE-11'),
('XM9J59', 'Papa', 'category', false, false, 'CIE-11'),
('XM3VS0', 'Amaranto', 'category', false, false, 'CIE-11'),
('XM72E8', 'Acedera de oveja', 'category', false, false, 'CIE-11'),
('XM3TW1', 'Soja', 'category', false, false, 'CIE-11'),
('XM72C5', 'Jitomate', 'category', false, false, 'CIE-11'),
('XM3LL8', 'Pelitorio de pared', 'category', false, false, 'CIE-11'),
('XM42C5', 'Ambrosía occidental', 'category', false, false, 'CIE-11'),
('XM0GA2', 'Alubia blanca', 'category', false, false, 'CIE-11'),
('XM9S45', 'Ajenjo', 'category', false, false, 'CIE-11'),
('XM60Q8', 'Almendra', 'category', false, false, 'CIE-11'),
('XM1304', 'Haya americana', 'category', false, false, 'CIE-11'),
('XM5TH6', 'Ciprés de Arizona', 'category', false, false, 'CIE-11'),
('XM3ES3', 'Nuez de Brasil', 'category', false, false, 'CIE-11'),
('XM9GG3', 'Cedro Olmo', 'category', false, false, 'CIE-11'),
('XM36B2', 'Arce costero', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XM6MF9', 'Coco', 'category', false, false, 'CIE-11'),
('XM9JG2', 'Álamo', 'category', false, false, 'CIE-11'),
('XM2044', 'Polen de nuez inglesa', 'category', false, false, 'CIE-11'),
('XM2EQ3', 'Anacardo', 'category', false, false, 'CIE-11'),
('XM7QD6', 'Aliso gris', 'category', false, false, 'CIE-11'),
('XM7L19', 'Avellana', 'category', false, false, 'CIE-11'),
('XM4WW3', 'Ciprés italiano', 'category', false, false, 'CIE-11'),
('XM3940', 'Cedro japonés', 'category', false, false, 'CIE-11'),
('XM8QG1', 'Ciprés japonés', 'category', false, false, 'CIE-11'),
('XM9AZ7', 'Macadamia', 'category', false, false, 'CIE-11'),
('XM0QL5', 'Mezquite', 'category', false, false, 'CIE-11'),
('XM7G21', 'Enebro de montaña', 'category', false, false, 'CIE-11'),
('XM8K37', 'Morera de papel', 'category', false, false, 'CIE-11'),
('XM6Q82', 'Maní', 'category', false, false, 'CIE-11'),
('XM1QN3', 'árbol de nuez o nogal', 'category', false, false, 'CIE-11'),
('XM7833', 'Piñón', 'category', false, false, 'CIE-11'),
('XM2B46', 'Pistache', 'category', false, false, 'CIE-11'),
('XM34T8', 'Arce rojo', 'category', false, false, 'CIE-11'),
('XM03B3', 'Morera roja', 'category', false, false, 'CIE-11'),
('XM1L09', 'Semillas de sésamo', 'category', false, false, 'CIE-11'),
('XM30J5', 'Abedul plateado', 'category', false, false, 'CIE-11'),
('XM3DB3', 'Nogal', 'category', false, false, 'CIE-11'),
('XM5VB3', 'Acacia', 'category', false, false, 'CIE-11'),
('XM3ZG1', 'Pino blanco occidental', 'category', false, false, 'CIE-11'),
('XM3DL1', 'Ceniza blanca', 'category', false, false, 'CIE-11'),
('XM3VX2', 'Abedul blanco', 'category', false, false, 'CIE-11'),
('XM6V15', 'Nogal blanco', 'category', false, false, 'CIE-11'),
('XM5AD4', 'Morera blanca', 'category', false, false, 'CIE-11'),
('XM4YR5', 'Sauce', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;