BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('ME24.3Y', 'Otra perforación en el aparato digestivo especificada', 'category', false, false, 'CIE-11'),
('ME24.3Z', 'Perforación en el aparato digestivo, sin especificación', 'category', false, false, 'CIE-11'),
('ME24.4', 'Estenosis en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME24.5', 'Úlcera en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME24.6', 'Dilatación en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME24.7', 'Encarcelación en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME24.8', 'Estrangulación o gangrena en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME24.9', 'Hemorragia gastrointestinal', 'category', false, false, 'CIE-11'),
('ME24.90', 'Sangrado gastrointestinal agudo, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('ME24.91', 'Sangrado gastrointestinal crónico, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('ME24.9Z', 'Hemorragia gastrointestinal, sin especificación', 'category', false, false, 'CIE-11'),
('ME24.A', 'Otras hemorragias del aparato digestivo, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('ME24.A0', 'hemorragia gastrointestinal inexplicable', 'category', false, false, 'CIE-11'),
('ME24.A1', 'Hemorragia del ano y del recto', 'category', false, false, 'CIE-11'),
('ME24.A2', 'Hemorragia esofágica', 'category', false, false, 'CIE-11'),
('ME24.A3', 'Rectorragia', 'category', false, false, 'CIE-11'),
('ME24.A4', 'Melena', 'category', false, false, 'CIE-11'),
('ME24.A5', 'Hematemesis', 'category', false, false, 'CIE-11'),
('ME24.A6', 'Prueba de sangre oculta en heces positiva', 'category', false, false, 'CIE-11'),
('ME24.Y', 'Otras manifestaciones clínicas especificadas del aparato digestivo', 'category', false, false, 'CIE-11'),
('ME2Y', 'Otros resultados clínicos especificados en el aparato digestivo', 'category', false, false, 'CIE-11'),
('ME4Y', 'Otros síntomas, signos, o resultados clínicos anormales especificados relativos al aparato digestivo o el abdomen', 'category', false, false, 'CIE-11'),
('ME60', 'Lesión de la piel de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME60.0', 'Neoplasia de la piel de naturaleza incierta', 'category', false, false, 'CIE-11'),
('ME60.1', 'Lesión pigmentada de la piel de naturaleza incierta', 'category', false, false, 'CIE-11'),
('ME60.2', 'Úlcera de piel de naturaleza incierta', 'category', false, false, 'CIE-11'),
('ME60.3', 'Queratosis de piel de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME60.Z', 'Lesión de la piel de naturaleza incierta o no especificada, sin especificación', 'category', false, false, 'CIE-11'),
('ME61', 'Hinchazón subcutánea, masa o bulto de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME62', 'Erupción cutánea aguda de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME62.0', 'Erupción cutánea eritematosa aguda', 'category', false, false, 'CIE-11'),
('ME62.1', 'Erupción cutánea purpúrica aguda', 'category', false, false, 'CIE-11'),
('ME62.2', 'Erupción cutánea urticarial aguda', 'category', false, false, 'CIE-11'),
('ME62.3', 'Erupción cutánea maculopapulosa aguda', 'category', false, false, 'CIE-11'),
('ME62.4', 'Erupción cutánea papulosa aguda', 'category', false, false, 'CIE-11'),
('ME62.5', 'Erupción cutánea exudativa aguda', 'category', false, false, 'CIE-11'),
('ME62.6', 'Erupción vesicular aguda de la piel', 'category', false, false, 'CIE-11'),
('ME62.7', 'Erupción cutánea descamativa aguda', 'category', false, false, 'CIE-11'),
('ME62.8', 'Erupción cutánea anular o discoide aguda', 'category', false, false, 'CIE-11'),
('ME62.9', 'Escoriación aguda de la piel', 'category', false, false, 'CIE-11'),
('ME62.Y', 'Otra erupción cutánea aguda especificada de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME63', 'Dermatosis crónica de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME63.0', 'Dermatosis eritematosa crónica', 'category', false, false, 'CIE-11'),
('ME63.1', 'Dermatosis urticarial crónica', 'category', false, false, 'CIE-11'),
('ME63.2', 'Dermatosis papulosa crónica', 'category', false, false, 'CIE-11'),
('ME63.3', 'Dermatosis vesicular crónica', 'category', false, false, 'CIE-11'),
('ME63.4', 'Dermatosis descamativa o hiperqueratósica crónica', 'category', false, false, 'CIE-11'),
('ME63.5', 'Dermatosis liquenificada crónica', 'category', false, false, 'CIE-11'),
('ME63.6', 'Dermatosis discoide o anular crónica', 'category', false, false, 'CIE-11'),
('ME63.7', 'Excoriación crónica de la piel', 'category', false, false, 'CIE-11'),
('ME64', 'Signos vasculares cutáneos inespecíficos', 'category', false, false, 'CIE-11'),
('ME64.0', 'Eritema', 'category', false, false, 'CIE-11'),
('ME64.1', 'Cianosis', 'category', false, false, 'CIE-11'),
('ME64.2', 'Palidez', 'category', false, false, 'CIE-11'),
('ME64.3', 'Petequias', 'category', false, false, 'CIE-11'),
('ME64.4', 'Rubor', 'category', false, false, 'CIE-11'),
('ME65', 'Alteraciones de la sensibilidad cutánea de causa no especificada', 'category', false, false, 'CIE-11'),
('ME65.0', 'Ardor en la piel', 'category', false, false, 'CIE-11'),
('ME65.1', 'Picazón en la piel', 'category', false, false, 'CIE-11'),
('ME65.2', 'Dolor o sensibilidad de la piel', 'category', false, false, 'CIE-11'),
('ME65.3', 'Escozor', 'category', false, false, 'CIE-11'),
('ME65.4', 'Hormigueo en la piel', 'category', false, false, 'CIE-11'),
('ME65.Y', 'Otras alteraciones de la sensibilidad cutánea de causa no especificada', 'category', false, false, 'CIE-11'),
('ME66', 'Otros síntomas y signos misceláneos e inespecíficos relativos a la piel', 'category', false, false, 'CIE-11'),
('ME66.0', 'Sensibilidad anormal a la luz o a los rayos ultravioleta de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME66.1', 'Cambios en la textura de la piel', 'category', false, false, 'CIE-11'),
('ME66.2', 'Piel excesiva y redundante', 'category', false, false, 'CIE-11'),
('ME66.3', 'Problema en el pelo o cuero cabelludo', 'category', false, false, 'CIE-11'),
('ME66.4', 'Problema o molestia en las uñas', 'category', false, false, 'CIE-11'),
('ME66.5', 'Síntomas de sudación anormal', 'category', false, false, 'CIE-11'),
('ME66.6', 'Erupción cutánea', 'category', false, false, 'CIE-11'),
('ME66.60', 'Erupción cutánea localizada', 'category', false, false, 'CIE-11'),
('ME66.61', 'Erupción generalizada', 'category', false, false, 'CIE-11'),
('ME66.6Y', 'Otra erupción especificada', 'category', false, false, 'CIE-11'),
('ME66.6Z', 'Erupción, sin especificación', 'category', false, false, 'CIE-11'),
('ME66.Y', 'Otras alteraciones cutáneas especificadas', 'category', false, false, 'CIE-11'),
('ME67', 'Trastorno de naturaleza incierta o no especificada', 'category', false, false, 'CIE-11'),
('ME6Y', 'Otros síntomas o signos especificados que involucran a la piel', 'category', false, false, 'CIE-11'),
('ME80', 'Chasquido de la cadera', 'category', false, false, 'CIE-11'),
('ME81', 'Dolor torácico de origen musculoesquelético', 'category', false, false, 'CIE-11'),
('ME81.0', 'Dolor intercostal', 'category', false, false, 'CIE-11'),
('ME81.Y', 'Otro dolor torácico de origen musculoesquelético especificado', 'category', false, false, 'CIE-11'),
('ME81.Z', 'Dolor torácico de origen musculoesquelético, sin especificación', 'category', false, false, 'CIE-11'),
('ME82', 'Dolor articular', 'category', false, false, 'CIE-11'),
('ME83', 'Reumatismo, no especificado', 'category', false, false, 'CIE-11'),
('ME84', 'Dolor vertebral', 'category', false, false, 'CIE-11'),
('ME84.0', 'Dolor de la columna cervical', 'category', false, false, 'CIE-11'),
('ME84.1', 'Dolor de la columna torácica', 'category', false, false, 'CIE-11'),
('ME84.2', 'Dolor lumbar', 'category', false, false, 'CIE-11'),
('ME84.20', 'Lumbago con ciática', 'category', false, false, 'CIE-11'),
('ME84.2Y', 'Otro dolor lumbar especificado', 'category', false, false, 'CIE-11'),
('ME84.2Z', 'Dolor lumbar, sin especificación', 'category', false, false, 'CIE-11'),
('ME84.3', 'Ciática', 'category', false, false, 'CIE-11'),
('ME84.Z', 'Dolor vertebral, sin especificación', 'category', false, false, 'CIE-11'),
('ME85', 'Rigidez articular', 'category', false, false, 'CIE-11'),
('ME86', 'Síntoma o molestia relativa a una parte del cuerpo', 'category', false, false, 'CIE-11'),
('ME86.0', 'Síntoma o molestia del tobillo', 'category', false, false, 'CIE-11'),
('ME86.1', 'Síntoma o molestia del brazo', 'category', false, false, 'CIE-11'),
('ME86.2', 'Síntoma o molestia de la espalda', 'category', false, false, 'CIE-11'),
('ME86.20', 'Síndrome dorsal sin dolor irradiado', 'category', false, false, 'CIE-11'),
('ME86.21', 'Síndrome dorsal con dolor irradiado', 'category', false, false, 'CIE-11'),
('ME86.22', 'Síntoma o molestia de la región lumbar', 'category', false, false, 'CIE-11'),
('ME86.2Y', 'Otro síntoma o molestia especificada de la espalda', 'category', false, false, 'CIE-11'),
('ME86.2Z', 'Síntoma o molestia de la espalda, sin especificación', 'category', false, false, 'CIE-11'),
('ME86.3', 'Síntoma o molestia en el pecho', 'category', false, false, 'CIE-11'),
('ME86.4', 'Síntoma o molestia del codo', 'category', false, false, 'CIE-11'),
('ME86.5', 'Síntoma o molestia del flanco o la axila', 'category', false, false, 'CIE-11'),
('ME86.6', 'Síntoma o molestia del pie o del dedo del pie', 'category', false, false, 'CIE-11'),
('ME86.7', 'Síntoma o molestia de la mano o de dedo de la mano', 'category', false, false, 'CIE-11'),
('ME86.8', 'Síntoma o molestia de la cadera', 'category', false, false, 'CIE-11'),
('ME86.9', 'Síntoma o molestia de la mandíbula', 'category', false, false, 'CIE-11'),
('ME86.A', 'Síntoma o molestia de la rodilla', 'category', false, false, 'CIE-11'),
('ME86.B', 'Síntoma o molestia de la pierna o el muslo', 'category', false, false, 'CIE-11'),
('ME86.C', 'Síntoma o molestia del cuello', 'category', false, false, 'CIE-11'),
('ME86.D', 'Síntoma o molestia del hombro', 'category', false, false, 'CIE-11'),
('ME86.D0', 'Síndrome del hombro', 'category', false, false, 'CIE-11'),
('ME86.DY', 'Otro síntoma o molestia del hombro especificada', 'category', false, false, 'CIE-11'),
('ME86.DZ', 'Síntoma o molestia del hombro, sin especificación', 'category', false, false, 'CIE-11'),
('ME86.E', 'Síntoma o molestia de la muñeca', 'category', false, false, 'CIE-11'),
('ME86.F', 'Síntoma o molestia de la articulación, sin otra especificación', 'category', false, false, 'CIE-11'),
('ME86.G', 'Síntoma o molestia del músculo, sin otra especificación', 'category', false, false, 'CIE-11'),
('ME86.Y', 'Otro síntoma o molestia relativa a una parte del cuerpo especificada', 'category', false, false, 'CIE-11'),
('ME86.Z', 'Síntoma o molestia de una parte del cuerpo, sin especificación', 'category', false, false, 'CIE-11'),
('ME8Y', 'Otros síntomas o signos especificados del sistema musculoesquelético', 'category', false, false, 'CIE-11'),
('ME90', 'Resultado clínicos anormales en una prueba de diagnóstico por neuroimagen del cráneo y la cabeza', 'category', false, false, 'CIE-11'),
('ME91', 'Resultados clínicos anormales en una prueba de diagnóstico por la imagen de las extremidades', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('ME92', 'Resultados clínicos anormales en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor', 'category', false, false, 'CIE-11'),
('ME92.0', 'Acuñamiento vertebral', 'category', false, false, 'CIE-11'),
('ME92.1', 'Erosión ósea', 'category', false, false, 'CIE-11'),
('ME92.Y', 'Otros resultados clínicos anormales especificados en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor', 'category', false, false, 'CIE-11'),
('ME92.Z', 'Resultados clínicos anormales en una prueba de diagnóstico por la imagen de otras partes del aparato locomotor, sin especificación', 'category', false, false, 'CIE-11'),
('ME93', 'Lesiones biomecánicas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('ME93.0', 'Disfunción segmentaria y somática', 'category', false, false, 'CIE-11'),
('ME93.1', 'Estenosis del conducto vertebral por subluxación', 'category', false, false, 'CIE-11'),
('ME93.2', 'Estenosis ósea del canal neural', 'category', false, false, 'CIE-11'),
('ME93.3', 'Estenosis del conducto vertebral por tejido conjuntivo', 'category', false, false, 'CIE-11'),
('ME93.4', 'Estenosis del conducto vertebral por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.40', 'Estenosis del conducto vertebral por disco intervertebral, región de la cabeza', 'category', false, false, 'CIE-11'),
('ME93.41', 'Estenosis del conducto vertebral por disco intervertebral, región cervical', 'category', false, false, 'CIE-11'),
('ME93.42', 'Estenosis del conducto vertebral por disco intervertebral, región torácica', 'category', false, false, 'CIE-11'),
('ME93.43', 'Estenosis del conducto vertebral por disco intervertebral, región lumbar', 'category', false, false, 'CIE-11'),
('ME93.44', 'Estenosis del conducto vertebral por disco intervertebral, región sacra', 'category', false, false, 'CIE-11'),
('ME93.4Y', 'Otra estenosis especificada del conducto vertebral por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.4Z', 'Estenosis del conducto vertebral por disco intervertebral, sin especificación', 'category', false, false, 'CIE-11'),
('ME93.5', 'Estenosis ósea y subluxación de los agujeros intervertebrales', 'category', false, false, 'CIE-11'),
('ME93.6', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral', 'category', false, false, 'CIE-11'),
('ME93.Y', 'Otras lesiones biomecánicas especificadas, no clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('ME93.Z', 'Lesiones biomecánicas, no clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('ME9Y', 'Otros hallazgos clínicos especificados en el sistema músculo esquelético', 'category', false, false, 'CIE-11'),
('MF1Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al aparato locomotor', 'category', false, false, 'CIE-11'),
('MF30', 'Tumor o masa en el seno femenino', 'category', false, false, 'CIE-11'),
('MF31', 'Síntoma o molestia relativa a la mama o la lactancia materna', 'category', false, false, 'CIE-11'),
('MF32', 'Síntoma o molestia relativa a la menopausia', 'category', false, false, 'CIE-11'),
('MF33', 'Síntoma o molestia premenstrual', 'category', false, false, 'CIE-11'),
('MF34', 'Síntoma o molestia relativa al embarazo', 'category', false, false, 'CIE-11'),
('MF35', 'Síntoma o molestia puerperal', 'category', false, false, 'CIE-11'),
('MF36', 'Otro síntoma o molestia relativa a la vagina', 'category', false, false, 'CIE-11'),
('MF37', 'Síntoma o molestia relativa al pezón femenino', 'category', false, false, 'CIE-11'),
('MF38', 'Síntoma o molestia relativa a los órganos pélvicos femeninos', 'category', false, false, 'CIE-11'),
('MF39', 'Síntoma o molestia de la vulva', 'category', false, false, 'CIE-11'),
('MF3A', 'Flujo vaginal', 'category', false, false, 'CIE-11'),
('MF3Y', 'Otros síntomas, signos o resultados clínicos anormales del aparato genital femenino', 'category', false, false, 'CIE-11'),
('MF40', 'Problemas de los órganos genitales masculinos en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.0', 'Síntoma o molestia en el pene', 'category', false, false, 'CIE-11'),
('MF40.00', 'Dolor en el pene', 'category', false, false, 'CIE-11'),
('MF40.0Y', 'Síntoma o molestia especificada del pene', 'category', false, false, 'CIE-11'),
('MF40.0Z', 'Síntoma o molestia del pene, sin especificación', 'category', false, false, 'CIE-11'),
('MF40.1', 'Trastornos de la próstata en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.2', 'Síntoma o molestia del escroto o testículo', 'category', false, false, 'CIE-11'),
('MF40.20', 'Dolor escrotal agudo', 'category', false, false, 'CIE-11'),
('MF40.21', 'Dolor testicular', 'category', false, false, 'CIE-11'),
('MF40.2Y', 'Otro síntoma o molestia especificada del escroto o testículo', 'category', false, false, 'CIE-11'),
('MF40.2Z', 'Síntoma o molestia del escroto o testículo, sin especificación', 'category', false, false, 'CIE-11'),
('MF40.3', 'Eyaculación retrógrada', 'category', false, false, 'CIE-11'),
('MF40.Y', 'Otros problemas especificados de los órganos genitales masculinos en enfermedades clasificadas en otra parte', 'category', false, false, 'CIE-11'),
('MF40.Z', 'Problemas de los órganos genitales masculinos en enfermedades clasificadas en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MF41', 'Síntoma o molestia relativa a la función sexual masculina', 'category', false, false, 'CIE-11'),
('MF42', 'Testículo migratorio retráctil', 'category', false, false, 'CIE-11'),
('MF4Y', 'Otros síntomas, signos o resultados clínicos anormales relativos al aparato genital masculino', 'category', false, false, 'CIE-11'),
('MF50', 'Anomalía de la micción', 'category', false, false, 'CIE-11'),
('MF50.0', 'Micción frecuente', 'category', false, false, 'CIE-11'),
('MF50.1', 'Polaquiuria', 'category', false, false, 'CIE-11'),
('MF50.2', 'Incontinencia urinaria', 'category', false, false, 'CIE-11'),
('MF50.20', 'Incontinencia urinaria de esfuerzo', 'category', false, false, 'CIE-11'),
('MF50.21', 'Incontinencia de urgencia', 'category', false, false, 'CIE-11'),
('MF50.22', 'Incontinencia mixta', 'category', false, false, 'CIE-11'),
('MF50.23', 'Incontinencia urinaria funcional', 'category', false, false, 'CIE-11'),
('MF50.24', 'Incontinencia refleja', 'category', false, false, 'CIE-11'),
('MF50.2Y', 'Otra incontinencia urinaria especificada', 'category', false, false, 'CIE-11'),
('MF50.2Z', 'Incontinencia urinaria, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.3', 'Retención de orina', 'category', false, false, 'CIE-11'),
('MF50.4', 'Hematuria', 'category', false, false, 'CIE-11'),
('MF50.40', 'Hematuria macroscópica', 'category', false, false, 'CIE-11'),
('MF50.41', 'Hematuria microscópica', 'category', false, false, 'CIE-11'),
('MF50.4Z', 'Hematuria, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.5', 'Extravasación de la orina', 'category', false, false, 'CIE-11'),
('MF50.6', 'Otras dificultades con la micción', 'category', false, false, 'CIE-11'),
('MF50.60', 'Retardo miccional', 'category', false, false, 'CIE-11'),
('MF50.61', 'Chorro de orina pobre', 'category', false, false, 'CIE-11'),
('MF50.62', 'División del chorro urinario', 'category', false, false, 'CIE-11'),
('MF50.63', 'Necesidad urgente de orinar', 'category', false, false, 'CIE-11'),
('MF50.64', 'Sensación de vaciamiento incompleto de la vejiga', 'category', false, false, 'CIE-11'),
('MF50.65', 'Micción con esfuerzo', 'category', false, false, 'CIE-11'),
('MF50.6Y', 'Otras dificultades con la micción especificadas', 'category', false, false, 'CIE-11'),
('MF50.6Z', 'Otras dificultades con la micción, sin especificación', 'category', false, false, 'CIE-11'),
('MF50.7', 'Disuria', 'category', false, false, 'CIE-11'),
('MF50.8', 'Tenesmo vesical', 'category', false, false, 'CIE-11'),
('MF50.Y', 'Otra anomalía especificada de la micción', 'category', false, false, 'CIE-11'),
('MF50.Z', 'Anomalía de la micción, sin especificación', 'category', false, false, 'CIE-11'),
('MF51', 'Anuria u oliguria', 'category', false, false, 'CIE-11'),
('MF52', 'Dolor de la vejiga', 'category', false, false, 'CIE-11'),
('MF53', 'Uremia extrarrenal', 'category', false, false, 'CIE-11'),
('MF54', 'Cambios macroscópicos del tamaño del riñón', 'category', false, false, 'CIE-11'),
('MF54.0', 'Riñón contraído y liso', 'category', false, false, 'CIE-11'),
('MF54.1', 'Riñón contraído de forma irregular', 'category', false, false, 'CIE-11'),
('MF54.2', 'Riñón pequeño', 'category', false, false, 'CIE-11'),
('MF54.Y', 'Otros cambios macroscópicos especificados del tamaño del riñón', 'category', false, false, 'CIE-11'),
('MF54.Z', 'Cambios macroscópicos del tamaño del riñón, sin especificación', 'category', false, false, 'CIE-11'),
('MF55', 'Poliuria', 'category', false, false, 'CIE-11'),
('MF56', 'Cólico nefrítico', 'category', false, false, 'CIE-11'),
('MF57', 'Síntoma o molestia de la vejiga urinaria', 'category', false, false, 'CIE-11'),
('MF58', 'Secreción uretral', 'category', false, false, 'CIE-11'),
('MF59', 'Síntoma o molestia urinaria', 'category', false, false, 'CIE-11'),
('MF5Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al aparato urinario', 'category', false, false, 'CIE-11'),
('MF60', 'Concentración anormal de enzimas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF61', 'Concentración anormal de hormonas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF62', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF63', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF64', 'Resultados inmunológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF65', 'Resultados microbiológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66', 'Resultados citopatológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66.0', 'Frotis de cuello uterino anormal', 'category', false, false, 'CIE-11'),
('MF66.Y', 'Resultados citopatológicos anormales especificados en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF66.Z', 'Resultados citopatológicos anormales en muestras de los órganos genitales femeninos, sin especificación', 'category', false, false, 'CIE-11'),
('MF67', 'Resultados histopatológicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF68', 'Resultados cromosómicos anormales en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF6Y', 'Otros resultados clínicos especificados en muestras de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MF6Z', 'Resultados clínicos en muestras de los órganos genitales femeninos, sin especificación', 'category', false, false, 'CIE-11'),
('MF70', 'Concentración anormal de enzimas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF71', 'Concentración anormal de hormonas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF72', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF73', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF74', 'Resultados inmunológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF75', 'Resultados microbiológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF76', 'Resultados citopatológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF77', 'Resultados histopatológicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF78', 'Resultados cromosómicos anormales en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF7Y', 'Resultados clínicos anormales especificados en muestras de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MF7Z', 'Resultados clínicos anormales en muestras de los órganos genitales masculinos, sin especificación', 'category', false, false, 'CIE-11'),
('MF80', 'Esclerosis mesangial difusa', 'category', false, false, 'CIE-11'),
('MF81', 'Glomerulopatía por fibronectina', 'category', false, false, 'CIE-11'),
('MF82', 'Glomerulopatía lipoproteínica', 'category', false, false, 'CIE-11'),
('MF83', 'Alteraciones glomerulares diabéticas', 'category', false, false, 'CIE-11'),
('MF84', 'Glomerulonefritis proliferativa pauciinmunitaria', 'category', false, false, 'CIE-11'),
('MF85', 'Enfermedad mediada por anticuerpos contra la membrana basal glomerular', 'category', false, false, 'CIE-11'),
('MF8Y', 'Resultados clínicos anormales especificados en muestras obtenidas del aparato urinario', 'category', false, false, 'CIE-11'),
('MF8Z', 'Resultados clínicos anormales en muestras obtenidas del aparato urinario, sin especificación', 'category', false, false, 'CIE-11'),
('MF90', 'Cetonuria', 'category', false, false, 'CIE-11'),
('MF91', 'Bilirrubinuria', 'category', false, false, 'CIE-11'),
('MF92', 'Quiluria', 'category', false, false, 'CIE-11'),
('MF93', 'Glucosuria', 'category', false, false, 'CIE-11'),
('MF94', 'Hemoglobinuria', 'category', false, false, 'CIE-11'),
('MF95', 'Mioglobinuria', 'category', false, false, 'CIE-11'),
('MF96', 'Proteinuria', 'category', false, false, 'CIE-11'),
('MF96.0', 'Proteinuria ortostática', 'category', false, false, 'CIE-11'),
('MF96.1', 'Proteinuria de Bence Jones', 'category', false, false, 'CIE-11'),
('MF96.Y', 'Otra proteinuria especificada', 'category', false, false, 'CIE-11'),
('MF96.Z', 'Proteinuria, sin especificación', 'category', false, false, 'CIE-11'),
('MF97', 'Piuria', 'category', false, false, 'CIE-11'),
('MF98', 'Concentraciones anormales de electrolitos séricos en la orina', 'category', false, false, 'CIE-11'),
('MF98.0', 'Hipercalciuria', 'category', false, false, 'CIE-11'),
('MF98.1', 'Hipercaliuria', 'category', false, false, 'CIE-11'),
('MF98.2', 'Hipermagnesuria', 'category', false, false, 'CIE-11'),
('MF98.3', 'Hipocalciuria', 'category', false, false, 'CIE-11'),
('MF98.4', 'Hipocaliuria', 'category', false, false, 'CIE-11'),
('MF98.5', 'Hipomagnesuria', 'category', false, false, 'CIE-11'),
('MF98.6', 'Hipofosfaturia', 'category', false, false, 'CIE-11'),
('MF98.Y', 'Concentraciones anormales especificados de electrolitos séricos en la orina', 'category', false, false, 'CIE-11'),
('MF98.Z', 'Concentraciones anormales de electrolitos séricos en la orina, sin especificación', 'category', false, false, 'CIE-11'),
('MF99', 'Concentraciones elevadas de drogas, medicamentos y sustancias biológicas en la orina', 'category', false, false, 'CIE-11'),
('MF9A', 'Niveles anormales en orina de sustancias principalmente no medicinales según la fuente', 'category', false, false, 'CIE-11'),
('MF9B', 'Resultados anormales en el análisis microbiológico de la orina', 'category', false, false, 'CIE-11'),
('MF9C', 'Resultados anormales en el estudio citopatológico e histopatológico de la orina', 'category', false, false, 'CIE-11'),
('MF9Y', 'Otros resultados anormales especificados en análisis de orina, sin diagnóstico', 'category', false, false, 'CIE-11'),
('MG00', 'Resultados anormales en las pruebas de diagnóstico por la imagen de la mama', 'category', false, false, 'CIE-11'),
('MG01', 'Resultados anormales en las pruebas de diagnóstico por la imagen de los órganos urinarios', 'category', false, false, 'CIE-11'),
('MG02', 'Resultados de pruebas funcionales renales', 'category', false, false, 'CIE-11'),
('MG0Y', 'Otros síntomas, signos o resultados clínicos anormales especificados relativos al sistema genitourinario', 'category', false, false, 'CIE-11'),
('MG20', 'Caquexia', 'category', false, false, 'CIE-11'),
('MG20.0', 'Caquexia maligna', 'category', false, false, 'CIE-11'),
('MG20.Z', 'Caquexia, sin especificación', 'category', false, false, 'CIE-11'),
('MG21', 'Escalofríos', 'category', false, false, 'CIE-11'),
('MG22', 'Cansancio', 'category', false, false, 'CIE-11'),
('MG23', 'Miedo a la muerte o a morir', 'category', false, false, 'CIE-11'),
('MG24', 'Temor a la enfermedad', 'category', false, false, 'CIE-11'),
('MG24.0', 'Temor al cáncer', 'category', false, false, 'CIE-11'),
('MG24.00', 'Temor a los cánceres del aparato digestivo', 'category', false, false, 'CIE-11'),
('MG24.01', 'Temor al cáncer de mama femenino', 'category', false, false, 'CIE-11'),
('MG24.02', 'Temor al cáncer de los genitales masculinos', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;