BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XA8N10', 'tendón del músculo hipogloso', 'category', false, false, 'CIE-11'),
('XA7EE6', 'tendón del músculo hioideo', 'category', false, false, 'CIE-11'),
('XA3ZA2', 'tendón oblicuo inferior', 'category', false, false, 'CIE-11'),
('XA7HT8', 'tendón recto inferior', 'category', false, false, 'CIE-11'),
('XA1394', 'tendón cricoaritenoide lateral', 'category', false, false, 'CIE-11'),
('XA6PK4', 'Tendón pterigoideo lateral', 'category', false, false, 'CIE-11'),
('XA3LT8', 'tendón recto lateral', 'category', false, false, 'CIE-11'),
('XA7653', 'tendón elevador del ángulo de la boca', 'category', false, false, 'CIE-11'),
('XA0YK7', 'tendón del elevador del labio superior', 'category', false, false, 'CIE-11'),
('XA61C9', 'tendón elevador del párpado superior', 'category', false, false, 'CIE-11'),
('XA7VD7', 'tendón elevador del velo del paladar', 'category', false, false, 'CIE-11'),
('XA1FR7', 'tendón del largo de la cabeza', 'category', false, false, 'CIE-11'),
('XA0UD3', 'tendón largo del cuello', 'category', false, false, 'CIE-11'),
('XA1FB3', 'tendón del masetero', 'category', false, false, 'CIE-11'),
('XA8F95', 'tendón pterigoide medial', 'category', false, false, 'CIE-11'),
('XA6SG3', 'tendón del recto medial', 'category', false, false, 'CIE-11'),
('XA7JW2', 'tendón del mentón', 'category', false, false, 'CIE-11'),
('XA7ZZ8', 'tendón milohioideo', 'category', false, false, 'CIE-11'),
('XA7NU6', 'tendón nasal', 'category', false, false, 'CIE-11'),
('XA5Q22', 'tendón aritenoide oblicuo', 'category', false, false, 'CIE-11'),
('XA8AT8', 'tendón inferior oblicuo de la cabeza', 'category', false, false, 'CIE-11'),
('XA39M0', 'tendón superior oblicuo de la cabeza', 'category', false, false, 'CIE-11'),
('XA2JY6', 'tendón omoioide', 'category', false, false, 'CIE-11'),
('XA65X4', 'tendón orbicular de los ojos', 'category', false, false, 'CIE-11'),
('XA0W74', 'tendón orbicular de la boca', 'category', false, false, 'CIE-11'),
('XA6SX4', 'tendón palatogloso', 'category', false, false, 'CIE-11'),
('XA6LA2', 'tendón palatofaringeo', 'category', false, false, 'CIE-11'),
('XA4758', 'tendón platisma', 'category', false, false, 'CIE-11'),
('XA0AE2', 'ligamento cricoaritenoide posterior', 'category', false, false, 'CIE-11'),
('XA5HD8', 'tendón del procerus', 'category', false, false, 'CIE-11'),
('XA8CQ6', 'tendón del recto anterior de la cabeza', 'category', false, false, 'CIE-11'),
('XA4RG2', 'tendón del recto lateral de la cabeza', 'category', false, false, 'CIE-11'),
('XA6WL6', 'tendón del recto posterior mayor de la cabeza', 'category', false, false, 'CIE-11'),
('XA1XH8', 'tendón del recto posterior menor de la cabeza', 'category', false, false, 'CIE-11'),
('XA9450', 'tendón del risorio', 'category', false, false, 'CIE-11'),
('XA0SH8', 'tendón del salpingofaríngeo', 'category', false, false, 'CIE-11'),
('XA3XC1', 'tendón del escaleno', 'category', false, false, 'CIE-11'),
('XA45L1', 'tendón del escaleno anterior', 'category', false, false, 'CIE-11'),
('XA7XV7', 'tendón del escaleno medio', 'category', false, false, 'CIE-11'),
('XA7NL5', 'tendón del escaleno menor', 'category', false, false, 'CIE-11'),
('XA9HH7', 'tendón del escaleno posterior', 'category', false, false, 'CIE-11'),
('XA39C9', 'tendón del esplenio de la cabeza', 'category', false, false, 'CIE-11'),
('XA2HL1', 'tendón del esplenio del cuello', 'category', false, false, 'CIE-11'),
('XA8W69', 'tendón del estribo', 'category', false, false, 'CIE-11'),
('XA70V9', 'tendón del esternocleidomastoideo', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XA6S11', 'tendón del esternohioideo', 'category', false, false, 'CIE-11'),
('XA4VX2', 'tendón del esternotiroideo', 'category', false, false, 'CIE-11'),
('XA90J0', 'tendón del estilogloso', 'category', false, false, 'CIE-11'),
('XA20E0', 'tendón del estilohioideo', 'category', false, false, 'CIE-11'),
('XA7GV2', 'tendón del estilofaríngeo', 'category', false, false, 'CIE-11'),
('XA5ES8', 'tendón del oblicuo superior', 'category', false, false, 'CIE-11'),
('XA3ZN4', 'tendón del recto superior', 'category', false, false, 'CIE-11'),
('XA7D16', 'tendón temporal', 'category', false, false, 'CIE-11'),
('XA8BT2', 'Tendón temporoparietal', 'category', false, false, 'CIE-11'),
('XA5956', 'tendón tensor del tímpano', 'category', false, false, 'CIE-11'),
('XA2W44', 'tendón tensor del velo del paladar', 'category', false, false, 'CIE-11'),
('XA4ME3', 'tendón tiroaritenoideo', 'category', false, false, 'CIE-11'),
('XA0CT5', 'tendón tiroepiglótico', 'category', false, false, 'CIE-11'),
('XA9YC3', 'tendón aritenoideo transverso', 'category', false, false, 'CIE-11'),
('XA4CN7', 'tendón de las cuerdas vocales', 'category', false, false, 'CIE-11'),
('XA0XQ7', 'tendón zigomático mayor', 'category', false, false, 'CIE-11'),
('XA0SZ1', 'tendón zigomático menor', 'category', false, false, 'CIE-11'),
('XA3SA1', 'Tendón del tórax', 'category', false, false, 'CIE-11'),
('XA01T0', 'Cuerdas tendinosas', 'category', false, false, 'CIE-11'),
('XA9N29', 'tendón del diafragma', 'category', false, false, 'CIE-11'),
('XA5WL5', 'tendones intercostales externos', 'category', false, false, 'CIE-11'),
('XA8FV0', 'Tendón más interno de los intercostales', 'category', false, false, 'CIE-11'),
('XA92E2', 'tendón interno de los intercostales', 'category', false, false, 'CIE-11'),
('XA5R18', 'tendón elevador de las costillas', 'category', false, false, 'CIE-11'),
('XA3C70', 'tendón pectoral mayor', 'category', false, false, 'CIE-11'),
('XA40K0', 'tendón pectoral menor', 'category', false, false, 'CIE-11'),
('XA91D0', 'tendón serrato anterior', 'category', false, false, 'CIE-11'),
('XA7J14', 'tendón serrato posterior inferior', 'category', false, false, 'CIE-11'),
('XA0MH0', 'tendón serrato posterior superior', 'category', false, false, 'CIE-11'),
('XA8WS6', 'tendón subcostal', 'category', false, false, 'CIE-11'),
('XA3XC9', 'Tendón de Todaro', 'category', false, false, 'CIE-11'),
('XA1HX3', 'tendón torácico transverso', 'category', false, false, 'CIE-11'),
('XA4797', 'Tendón del abdomen', 'category', false, false, 'CIE-11'),
('XA0101', 'tendón oblicuo externo del abdómen', 'category', false, false, 'CIE-11'),
('XA45G1', 'tendón oblicuo interno del abdómen', 'category', false, false, 'CIE-11'),
('XA3045', 'tendón del psoas meyor', 'category', false, false, 'CIE-11'),
('XA7V41', 'tendón del psoas menor', 'category', false, false, 'CIE-11'),
('XA49W5', 'tendón piramidal', 'category', false, false, 'CIE-11'),
('XA34K5', 'tendón del cuadrado lumbar', 'category', false, false, 'CIE-11'),
('XA1HT1', 'tendón recto abdominal', 'category', false, false, 'CIE-11'),
('XA0V25', 'tendón transverso abdominal', 'category', false, false, 'CIE-11'),
('XA9Z26', 'Tendón de la espalda', 'category', false, false, 'CIE-11'),
('XA48X7', 'tendón iliocostal', 'category', false, false, 'CIE-11'),
('XA2MX3', 'tendón infraespinoso', 'category', false, false, 'CIE-11'),
('XA2E69', 'tendones interespinales', 'category', false, false, 'CIE-11'),
('XA8UU5', 'tendones intertransversos', 'category', false, false, 'CIE-11'),
('XA8467', 'tendón dorsal ancho', 'category', false, false, 'CIE-11'),
('XA3TD7', 'tendón longísimo', 'category', false, false, 'CIE-11'),
('XA33T4', 'tendón multífido del raquis', 'category', false, false, 'CIE-11'),
('XA3P63', 'tendón romboide mayor', 'category', false, false, 'CIE-11'),
('XA8918', 'tendón romboide menor', 'category', false, false, 'CIE-11'),
('XA16J2', 'tendones rotadores', 'category', false, false, 'CIE-11'),
('XA3D42', 'tendón semiespinal', 'category', false, false, 'CIE-11'),
('XA28J9', 'tendón espinal', 'category', false, false, 'CIE-11'),
('XA09K4', 'tendón redondo mayor', 'category', false, false, 'CIE-11'),
('XA42P8', 'tendón redondo menor', 'category', false, false, 'CIE-11'),
('XA9PV0', 'tendón del trapecio', 'category', false, false, 'CIE-11'),
('XA1SN1', 'Tendón de la pelvis y el perineo', 'category', false, false, 'CIE-11'),
('XA15H4', 'tendón bulbocavernoso', 'category', false, false, 'CIE-11'),
('XA45X9', 'tendón coccígeo', 'category', false, false, 'CIE-11'),
('XA4755', 'tendón del cremáster', 'category', false, false, 'CIE-11'),
('XA2BV5', 'tendón del dartos', 'category', false, false, 'CIE-11'),
('XA2TD5', 'tendón transverso profundo del perineo', 'category', false, false, 'CIE-11'),
('XA6QW7', 'tendón iliococcígeo', 'category', false, false, 'CIE-11'),
('XA7YP5', 'tendón isquiocavernoso', 'category', false, false, 'CIE-11'),
('XA5JV1', 'tendón pubococcígeo', 'category', false, false, 'CIE-11'),
('XA66F5', 'tendón puborectal', 'category', false, false, 'CIE-11'),
('XA32R3', 'tendón pubovaginal', 'category', false, false, 'CIE-11'),
('XA0WU6', 'Tendón de la extremidad superior', 'category', false, false, 'CIE-11'),
('XA5AY5', 'tendón abductor del dedo meñique', 'category', false, false, 'CIE-11'),
('XA7YE1', 'tendón Abductor Corto del Pulgar', 'category', false, false, 'CIE-11'),
('XA0UY5', 'tendón Abductor Largo del Pulgar', 'category', false, false, 'CIE-11'),
('XA9749', 'tendón Adductor del Pulgar', 'category', false, false, 'CIE-11'),
('XA4HK3', 'tendón del Anconeo', 'category', false, false, 'CIE-11'),
('XA8AM4', 'tendón de Biceps Braquial', 'category', false, false, 'CIE-11'),
('XA2UD9', 'Porción larga del tendón del Bíceps Braquial', 'category', false, false, 'CIE-11'),
('XA0FB1', 'Porción corta del tendón del Bíceps Braquial', 'category', false, false, 'CIE-11'),
('XA9G06', 'Tendón braquial', 'category', false, false, 'CIE-11'),
('XA3YY6', 'Tendón braquioradial', 'category', false, false, 'CIE-11'),
('XA83R8', 'Tendón coracobraquial', 'category', false, false, 'CIE-11'),
('XA0942', 'Tendón deltoideo', 'category', false, false, 'CIE-11'),
('XA24P4', 'Tendón Interóseo Dorsal', 'category', false, false, 'CIE-11'),
('XA18F0', 'Tendón del Extensor Radial Corto del Carpo', 'category', false, false, 'CIE-11'),
('XA1T90', 'Tendón del Extensor Radial Largo del Carpo', 'category', false, false, 'CIE-11'),
('XA4PY2', 'Tendón del Extensor Cubital del Carpo', 'category', false, false, 'CIE-11'),
('XA4WU2', 'Tendón Extensor del dedo meñique', 'category', false, false, 'CIE-11'),
('XA5H06', 'Tendón Extensor Común de los Dedos', 'category', false, false, 'CIE-11'),
('XA4EE2', 'Tendón extensor del Índice', 'category', false, false, 'CIE-11'),
('XA5KN6', 'Tendón Extensor Corto del Pulgar', 'category', false, false, 'CIE-11'),
('XA4CG6', 'Tendón Extensor Largo del Pulgar', 'category', false, false, 'CIE-11'),
('XA8U10', 'Tendón extensor', 'category', false, false, 'CIE-11'),
('XA8H50', 'Tendón Flexor Radial del Carpo', 'category', false, false, 'CIE-11'),
('XA5CE2', 'Tendón Flexor Cubital del Carpo', 'category', false, false, 'CIE-11'),
('XA23D8', 'Tendón Flexor del Dedo Meñique', 'category', false, false, 'CIE-11'),
('XA0GQ6', 'Tendón Flexor Común Profundo de los Dedos', 'category', false, false, 'CIE-11'),
('XA9526', 'Tendón Flexor Común Superficial de los Dedos', 'category', false, false, 'CIE-11'),
('XA9Q34', 'Tendón Flexor común de los dedos', 'category', false, false, 'CIE-11'),
('XA1Q82', 'Tendón Flexor Corto del Pulgar', 'category', false, false, 'CIE-11'),
('XA92F7', 'Tendón Flexor Largo del Pulgar', 'category', false, false, 'CIE-11'),
('XA5YQ2', 'Tendón flexor', 'category', false, false, 'CIE-11'),
('XA4M25', 'Tendón Interóseo', 'category', false, false, 'CIE-11'),
('XA1X89', 'Tendón elevador de la escápula', 'category', false, false, 'CIE-11'),
('XA8TQ1', 'Tendón lumbrical', 'category', false, false, 'CIE-11'),
('XA9KM7', 'Tendón Oponente del Dedo Meñique', 'category', false, false, 'CIE-11'),
('XA3W45', 'Tendón Oponente del Pulgar', 'category', false, false, 'CIE-11'),
('XA82E6', 'Tendón Interóseo Palmar', 'category', false, false, 'CIE-11'),
('XA7B73', 'Tendón Corto Palmar', 'category', false, false, 'CIE-11'),
('XA41L1', 'Tendón Largo Palmar', 'category', false, false, 'CIE-11'),
('XA41Z5', 'Tendón Pronador Cuadrado', 'category', false, false, 'CIE-11'),
('XA7EK5', 'Tendón del Pronador Redondo', 'category', false, false, 'CIE-11'),
('XA7V30', 'Tendón subclavio', 'category', false, false, 'CIE-11'),
('XA54N6', 'Tendón subescapular', 'category', false, false, 'CIE-11'),
('XA5EJ6', 'tendón Supinador', 'category', false, false, 'CIE-11'),
('XA5VZ4', 'Tendón Supraespinoso', 'category', false, false, 'CIE-11'),
('XA5RS6', 'tendón del Tríceps Braquial', 'category', false, false, 'CIE-11'),
('XA5L93', 'Tendón de la extremidad inferior', 'category', false, false, 'CIE-11'),
('XA5ZK0', 'tendón abductor del dedo pequeño (pie)', 'category', false, false, 'CIE-11'),
('XA14Z8', 'tendón abductor del hallux', 'category', false, false, 'CIE-11'),
('XA8BK1', 'Tendón de Aquiles', 'category', false, false, 'CIE-11'),
('XA4HF0', 'tendón aductor corto', 'category', false, false, 'CIE-11'),
('XA8B14', 'tendón aductor del hallux', 'category', false, false, 'CIE-11'),
('XA1TK8', 'tendón aductor largo', 'category', false, false, 'CIE-11'),
('XA8746', 'tendón aductor mayor', 'category', false, false, 'CIE-11'),
('XA9381', 'Ligamento Anterior de la extremidad inferior', 'category', false, false, 'CIE-11'),
('XA7MT0', 'tendón articular de la rodilla', 'category', false, false, 'CIE-11'),
('XA1MF8', 'tendón del biceps femoral', 'category', false, false, 'CIE-11'),
('XA86H9', 'tendón de los interóseos dorsales del pie', 'category', false, false, 'CIE-11'),
('XA6230', 'tendón extensor corto de los dedos (pie)', 'category', false, false, 'CIE-11'),
('XA1ZF4', 'tendón extensor largo de los dedos (pie)', 'category', false, false, 'CIE-11'),
('XA4NZ0', 'tendón corto del extensor del hallux', 'category', false, false, 'CIE-11'),
('XA5L26', 'tendón largo del extensor del hallux', 'category', false, false, 'CIE-11'),
('XA8X38', 'tendón flexor corto del quinto dedo (pie)', 'category', false, false, 'CIE-11'),
('XA8GD0', 'tendón flexor corto de los dedos', 'category', false, false, 'CIE-11'),
('XA3MK8', 'tendón flexor largo de los dedos (pie)', 'category', false, false, 'CIE-11'),
('XA00Z8', 'tendón flexor corto del hallux', 'category', false, false, 'CIE-11'),
('XA1MF0', 'tendón flexor largo del hallux', 'category', false, false, 'CIE-11'),
('XA5LZ0', 'tendón gastrocnemio', 'category', false, false, 'CIE-11'),
('XA2HX4', 'tendón del gemelo inferior', 'category', false, false, 'CIE-11'),
('XA5M18', 'tendón del gemelo superior', 'category', false, false, 'CIE-11'),
('XA1JL3', 'tendón del glúteo mayor', 'category', false, false, 'CIE-11'),
('XA1387', 'tendón del glúteo medio', 'category', false, false, 'CIE-11'),
('XA4HK9', 'tendón del glúteo menor', 'category', false, false, 'CIE-11'),
('XA12U3', 'tendón gracilis', 'category', false, false, 'CIE-11'),
('XA8FT1', 'tendón ilíaco', 'category', false, false, 'CIE-11'),
('XA5DE3', 'tendón del lumbrical del pie', 'category', false, false, 'CIE-11'),
('XA3EE9', 'tendón del obturador externo', 'category', false, false, 'CIE-11'),
('XA2469', 'tendón del obturador interno', 'category', false, false, 'CIE-11'),
('XA07E4', 'tendón pectineo', 'category', false, false, 'CIE-11'),
('XA3AN0', 'tendón corto peroneo', 'category', false, false, 'CIE-11'),
('XA7VY0', 'tendón largo peroneo', 'category', false, false, 'CIE-11'),
('XA3D16', 'Tendón del tercer peroneo', 'category', false, false, 'CIE-11'),
('XA3EU4', 'tendón piriforme', 'category', false, false, 'CIE-11'),
('XA7L19', 'tendón interóseo plantar del pie', 'category', false, false, 'CIE-11'),
('XA6BZ6', 'tendón plantar', 'category', false, false, 'CIE-11'),
('XA4V24', 'tendón popliteo', 'category', false, false, 'CIE-11'),
('XA1L44', 'tendón cuadrado plantar', 'category', false, false, 'CIE-11'),
('XA9420', 'tendón cuádriceps femoral', 'category', false, false, 'CIE-11'),
('XA4ZG0', 'tendón recto femoral', 'category', false, false, 'CIE-11'),
('XA0981', 'tendón de sartorio', 'category', false, false, 'CIE-11'),
('XA4AL5', 'tendón semimembranoso', 'category', false, false, 'CIE-11'),
('XA7DY9', 'tendón semitendinoso', 'category', false, false, 'CIE-11'),
('XA7E05', 'tendón del soleo', 'category', false, false, 'CIE-11'),
('XA33Q1', 'tendón del tensor de la fascia lata', 'category', false, false, 'CIE-11'),
('XA8SN1', 'tendón tibial anterior', 'category', false, false, 'CIE-11'),
('XA7FR7', 'tendón tibial posterior', 'category', false, false, 'CIE-11'),
('XA8ST5', 'tendón vasto intermedio', 'category', false, false, 'CIE-11'),
('XA8CQ5', 'tendón vasto externo', 'category', false, false, 'CIE-11'),
('XA6RK3', 'tendón vasto medio', 'category', false, false, 'CIE-11'),
('XA2C51', 'Entesis', 'category', false, false, 'CIE-11'),
('XA16K5', 'Bursa', 'category', false, false, 'CIE-11'),
('XA12U7', 'Bolsa sinovial del olécranon', 'category', false, false, 'CIE-11'),
('XA7P88', 'Bursa prepatelar', 'category', false, false, 'CIE-11'),
('XA6KU8', 'Riñón', 'category', false, false, 'CIE-11'),
('XA5EP6', 'Cápsula renal', 'category', false, false, 'CIE-11'),
('XA35W4', 'Corteza renal', 'category', false, false, 'CIE-11'),
('XA91E4', 'Médula renal', 'category', false, false, 'CIE-11'),
('XA9Q52', 'Pirámide renal', 'category', false, false, 'CIE-11'),
('XA21J4', 'Pelvis renal', 'category', false, false, 'CIE-11'),
('XA0AC1', 'Cálices renales', 'category', false, false, 'CIE-11'),
('XA6N83', 'Cáliz mayor', 'category', false, false, 'CIE-11'),
('XA8XL0', 'Cáliz menor', 'category', false, false, 'CIE-11'),
('XA7NQ9', 'Unión ureteropélvica', 'category', false, false, 'CIE-11'),
('XA4UD2', 'Hilio renal', 'category', false, false, 'CIE-11'),
('XA40R2', 'Glomérulo', 'category', false, false, 'CIE-11'),
('XA8AN8', 'Nefrón', 'category', false, false, 'CIE-11'),
('XA2364', 'Túbulo renal', 'category', false, false, 'CIE-11'),
('XA7156', 'Uréter', 'category', false, false, 'CIE-11'),
('XA9L57', 'Orificio ureterovesical', 'category', false, false, 'CIE-11'),
('XA77K2', 'Vejiga urinaria', 'category', false, false, 'CIE-11'),
('XA2PT2', 'Cúpula de la vejiga', 'category', false, false, 'CIE-11'),
('XA0R03', 'Pared de la vejiga', 'category', false, false, 'CIE-11'),
('XA3JA5', 'Pared lateral de la vejiga', 'category', false, false, 'CIE-11'),
('XA4UM5', 'Pared anterior de la vejiga', 'category', false, false, 'CIE-11'),
('XA2562', 'Pared posterior de la vejiga', 'category', false, false, 'CIE-11'),
('XA6SR9', 'pared superior de la vejiga', 'category', false, false, 'CIE-11'),
('XA6KF2', 'Trígono vesical', 'category', false, false, 'CIE-11'),
('XA4P63', 'Orificio uretérico', 'category', false, false, 'CIE-11'),
('XA8KN5', 'Orificio uretral interno', 'category', false, false, 'CIE-11'),
('XA0VZ5', 'Cuello de la vejiga', 'category', false, false, 'CIE-11'),
('XA5TA5', 'Uretra', 'category', false, false, 'CIE-11'),
('XA33M0', 'Esfinter uretral interno', 'category', false, false, 'CIE-11'),
('XA75T3', 'Uretra membranosa', 'category', false, false, 'CIE-11'),
('XA7869', 'Uretra prostática', 'category', false, false, 'CIE-11'),
('XA4DF2', 'Esfinter uretral externo', 'category', false, false, 'CIE-11'),
('XA8EW9', 'Uretra peneana', 'category', false, false, 'CIE-11'),
('XA4NU9', 'Meato uretral externo', 'category', false, false, 'CIE-11'),
('XA4V93', 'Aparato urinario, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA34X0', 'Tracto urinario inferior', 'category', false, false, 'CIE-11'),
('XA6RS6', 'Tracto urinario superior', 'category', false, false, 'CIE-11'),
('XA75A2', 'Órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('XA7QV2', 'Pene', 'category', false, false, 'CIE-11'),
('XA0970', 'Raíz del pene', 'category', false, false, 'CIE-11'),
('XA9A26', 'Cuerpo del pene', 'category', false, false, 'CIE-11'),
('XA03Y8', 'Superficie dorsal del pene', 'category', false, false, 'CIE-11'),
('XA3D56', 'Superficie ventral del pene', 'category', false, false, 'CIE-11'),
('XA0MH6', 'Glande', 'category', false, false, 'CIE-11'),
('XA3Q76', 'Meato uretral peneano', 'category', false, false, 'CIE-11'),
('XA3KB3', 'Glándula parauretral', 'category', false, false, 'CIE-11'),
('XA71S4', 'Prepucio', 'category', false, false, 'CIE-11'),
('XA2BL8', 'Superficie externa del prepucio', 'category', false, false, 'CIE-11'),
('XA1CP6', 'Superficie mucosa del prepucio', 'category', false, false, 'CIE-11'),
('XA54U4', 'Surco coronal del pene', 'category', false, false, 'CIE-11'),
('XA7V24', 'Frenillo del pene', 'category', false, false, 'CIE-11'),
('XA4947', 'Testículo', 'category', false, false, 'CIE-11'),
('XA1FS5', 'Túnica vaginal', 'category', false, false, 'CIE-11'),
('XA07W9', 'Túnica albugínea', 'category', false, false, 'CIE-11'),
('XA9636', 'Túbulos seminíferos', 'category', false, false, 'CIE-11'),
('XA13Z7', 'Testículo descendido', 'category', false, false, 'CIE-11'),
('XA14M8', 'Apéndice testicular', 'category', false, false, 'CIE-11'),
('XA4D25', 'Epidídimo', 'category', false, false, 'CIE-11'),
('XA9235', 'Cordón espermático', 'category', false, false, 'CIE-11'),
('XA8PQ1', 'Conducto deferente', 'category', false, false, 'CIE-11'),
('XA0MJ1', 'Vesícula seminal', 'category', false, false, 'CIE-11'),
('XA63E5', 'Glándula prostática', 'category', false, false, 'CIE-11'),
('XA2GU7', 'Órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('XA78U5', 'Vulva', 'category', false, false, 'CIE-11'),
('XA11L9', 'Labios de la vulva', 'category', false, false, 'CIE-11'),
('XA59G9', 'Labio mayor', 'category', false, false, 'CIE-11'),
('XA0MU9', 'Labio menor', 'category', false, false, 'CIE-11'),
('XA4851', 'Clítoris', 'category', false, false, 'CIE-11'),
('XA3C45', 'Capuchón del clítoris', 'category', false, false, 'CIE-11'),
('XA1A52', 'Vestíbulo vulvar', 'category', false, false, 'CIE-11'),
('XA27K9', 'Glándula de Bartholin', 'category', false, false, 'CIE-11'),
('XA0565', 'Horquilla posterior de la vulva', 'category', false, false, 'CIE-11'),
('XA1LK7', 'Vagina', 'category', false, false, 'CIE-11'),
('XA4AH3', 'Introito vaginal', 'category', false, false, 'CIE-11'),
('XA3A69', 'Himen', 'category', false, false, 'CIE-11'),
('XA9BM1', 'Conducto de Gartner', 'category', false, false, 'CIE-11'),
('XA46V2', 'Bóveda vaginal', 'category', false, false, 'CIE-11'),
('XA99N3', 'Útero', 'category', false, false, 'CIE-11'),
('XA3V49', 'Fondo del útero', 'category', false, false, 'CIE-11'),
('XA5229', 'Cuerpo del útero', 'category', false, false, 'CIE-11'),
('XA8QA8', 'Endometrio', 'category', false, false, 'CIE-11'),
('XA9DM0', 'Glándula endometrial', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;