BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XH0S03', 'Queratosis benigna, SAI', 'category', false, false, 'CIE-11'),
('XH63L8', 'Queratosis similar a la del liquen plano', 'category', false, false, 'CIE-11'),
('XH7AQ2', 'Acantoma de células grandes', 'category', false, false, 'CIE-11'),
('XH36H6', 'Queratosis actínica', 'category', false, false, 'CIE-11'),
('XH8MN8', 'Queratosis PUVA (exposición al psoraleno más luz ultravioleta A)', 'category', false, false, 'CIE-11'),
('XH5NG4', 'Queratosis arsenical', 'category', false, false, 'CIE-11'),
('XH13L5', 'Acantoma de células claras', 'category', false, false, 'CIE-11'),
('XH65S7', 'Disqueratoma verrugoso', 'category', false, false, 'CIE-11'),
('XH0949', 'Queratosis seborreica', 'category', false, false, 'CIE-11'),
('XH7B58', 'Lentigo solar', 'category', false, false, 'CIE-11'),
('XH2NM8', 'Enfermedad de Bowen', 'category', false, false, 'CIE-11'),
('XH9CL8', 'Neoplasia vulvar intraepitelial (NVI) diferenciada', 'category', false, false, 'CIE-11'),
('XH6824', 'Neoplasia intraepitelial del pene diferenciada (NIPe)', 'category', false, false, 'CIE-11'),
('XH4JA4', 'Carcinoma papilar in situ', 'category', false, false, 'CIE-11'),
('XH8YK9', 'Carcinoma papilar de células escamosas, no invasivo', 'category', false, false, 'CIE-11'),
('XH1U36', 'Carcinoma de células escamosas in situ con invasión estromal cuestionable', 'category', false, false, 'CIE-11'),
('XH7WM7', 'Carcinoma de células escamosas in situ, SAI', 'category', false, false, 'CIE-11'),
('XH3EA2', 'Neoplasia escamosa intraepitelial, de alto grado', 'category', false, false, 'CIE-11'),
('XH7SX5', 'Neoplasia anal intraepitelial, grado III', 'category', false, false, 'CIE-11'),
('XH62N8', 'Neoplasia cervical intraepitelial, grado III', 'category', false, false, 'CIE-11'),
('XH9ND8', 'Neoplasia esofágica escamosa intraepitelial (displasia), alto grado', 'category', false, false, 'CIE-11'),
('XH6F63', 'Neoplasia intraepitelial vaginal, grado III', 'category', false, false, 'CIE-11'),
('XH5FT2', 'Neoplasia intraepitelial vulvar, grado III', 'category', false, false, 'CIE-11'),
('XH2H04', 'Eritroplasia de Queyrat', 'category', false, false, 'CIE-11'),
('XH6RW7', 'Neoplasia intraepitelial diferenciada', 'category', false, false, 'CIE-11'),
('XH3GS1', 'Carcinoma de células escamosas basaloide', 'category', false, false, 'CIE-11'),
('XH0UU4', 'Carcinoma papilar,SAI', 'category', false, false, 'CIE-11'),
('XH6S97', 'Carcinoma papilar de células escamosas', 'category', false, false, 'CIE-11'),
('XH7LH0', 'Carcinoma de células escamosas, adenoide', 'category', false, false, 'CIE-11'),
('XH9DC1', 'Carcinoma de células escamosas, tipo células claras', 'category', false, false, 'CIE-11'),
('XH4CR9', 'Carcinoma de células escamosas, queratinizante, SAI', 'category', false, false, 'CIE-11'),
('XH84Q4', 'Carcinoma de células escamosas, metastásico, SAI', 'category', false, false, 'CIE-11'),
('XH90Y3', 'Carcinoma de células escamosas, microinvasor', 'category', false, false, 'CIE-11'),
('XH0945', 'Carcinoma de células escamosas, SAI', 'category', false, false, 'CIE-11'),
('XH2435', 'Carcinoma de células escamosas, células pequeñas, no queratinizante', 'category', false, false, 'CIE-11'),
('XH6D80', 'Carcinoma de células escamosas, células fusiformes', 'category', false, false, 'CIE-11'),
('XH5PM0', 'Carcinoma verrugoso, SAI', 'category', false, false, 'CIE-11'),
('XH7UR7', 'Carcinoma verrugoso', 'category', false, false, 'CIE-11'),
('XH6705', 'Carcinoma de células escamosas, células grandes, no queratinizante, SAI', 'category', false, false, 'CIE-11'),
('XH2JN3', 'Carcinoma de células escamosas con formación de cuerno', 'category', false, false, 'CIE-11'),
('XH1E40', 'Carcinoma linfoepitelial', 'category', false, false, 'CIE-11'),
('XH4GV2', 'Tumor de Schmincke', 'category', false, false, 'CIE-11'),
('XH0Z16', 'Carcinoma de células escamosas pseudovascular', 'category', false, false, 'CIE-11'),
('XH24M0', 'Carcinoma papilar-basaloide', 'category', false, false, 'CIE-11'),
('XH0EJ7', 'Carcinoma de células escamosas, VPH positivo', 'category', false, false, 'CIE-11'),
('XH2137', 'Carcinoma de células escamosas, VPH negativo', 'category', false, false, 'CIE-11'),
('XH6FU0', 'Carcinoma verrugoso-basaloide', 'category', false, false, 'CIE-11'),
('XH9XR8', 'Queratoacantoma', 'category', false, false, 'CIE-11'),
('XH2AW8', 'Sinovioma, benigno', 'category', false, false, 'CIE-11'),
('XH9B22', 'Sarcoma sinovial, SAI', 'category', false, false, 'CIE-11'),
('XH77N6', 'Sarcoma de células claras, SAI', 'category', false, false, 'CIE-11'),
('XH9346', 'Sarcoma sinovial de células fusiformes', 'category', false, false, 'CIE-11'),
('XH06L8', 'Sarcoma sinovial de células epitelioides', 'category', false, false, 'CIE-11'),
('XH1J28', 'Sarcoma sinovial bifásico', 'category', false, false, 'CIE-11'),
('XH3797', 'Sarcoma nasosinusal bifenotípico', 'category', false, false, 'CIE-11'),
('XH5854', 'Melanoma maligno de partes blandas', 'category', false, false, 'CIE-11'),
('XH9QW0', 'Timoma microscópico', 'category', false, false, 'CIE-11'),
('XH4341', 'Timoma benigno', 'category', false, false, 'CIE-11'),
('XH0707', 'Timoma hamartomatoso ectópico', 'category', false, false, 'CIE-11'),
('XH6WN9', 'Timoma, tipo A', 'category', false, false, 'CIE-11'),
('XH0JH0', 'Timoma, tipo AB', 'category', false, false, 'CIE-11'),
('XH66U8', 'Timoma, tipo B1', 'category', false, false, 'CIE-11'),
('XH2G89', 'Timoma, tipo B2', 'category', false, false, 'CIE-11'),
('XH4EW9', 'Timoma, tipo B3', 'category', false, false, 'CIE-11'),
('XH3734', 'Timoma, SAI', 'category', false, false, 'CIE-11'),
('XH1GA4', 'Timoma intrapulmonar', 'category', false, false, 'CIE-11'),
('XH6QN6', 'Timoma esclerosante', 'category', false, false, 'CIE-11'),
('XH3DX0', 'Timoma metaplásico', 'category', false, false, 'CIE-11'),
('XH6AK2', 'Carcinoma tímico, SAI', 'category', false, false, 'CIE-11'),
('XH6ZG8', 'Tumor epitelial fusiforme con elemento similar al timo', 'category', false, false, 'CIE-11'),
('XH33N4', 'Carcinoma tímico intratiroideo', 'category', false, false, 'CIE-11'),
('XH56K5', 'Timoma micronodular con estroma linfoide', 'category', false, false, 'CIE-11'),
('XH0TP8', 'Papiloma sinonasal, exofítico', 'category', false, false, 'CIE-11'),
('XH3HQ8', 'Papiloma transicional, invertido, SAI', 'category', false, false, 'CIE-11'),
('XH5A08', 'Papiloma urotelial invertido', 'category', false, false, 'CIE-11'),
('XH5M82', 'Papiloma urotelial, SAI', 'category', false, false, 'CIE-11'),
('XH12F0', 'Carcinoma papilar urotelial, no invasivo', 'category', false, false, 'CIE-11'),
('XH5GH8', 'Carcinoma urotelial in situ', 'category', false, false, 'CIE-11'),
('XH4UA2', 'Carcinoma de células cilíndricas', 'category', false, false, 'CIE-11'),
('XH35M0', 'Carcinoma Schneideriano', 'category', false, false, 'CIE-11'),
('XH8EH1', 'Carcinoma de células transicionales, SAI', 'category', false, false, 'CIE-11'),
('XH7TL4', 'Carcinoma transicional', 'category', false, false, 'CIE-11'),
('XH5P27', 'Carcinoma sarcomatoide urotelial', 'category', false, false, 'CIE-11'),
('XH0NZ4', 'Carcinoma papilar urotelial', 'category', false, false, 'CIE-11'),
('XH08S6', 'Carcinoma de células transicionales, micropapilar', 'category', false, false, 'CIE-11'),
('XH3UJ1', 'Carcinoma cloacogénico', 'category', false, false, 'CIE-11'),
('XH2V80', 'Carcinoma basaloide', 'category', false, false, 'CIE-11'),
('XH4W76', 'Carcinoma urotelial micropapilar', 'category', false, false, 'CIE-11'),
('XH7R01', 'Papiloma de células cilíndricas', 'category', false, false, 'CIE-11'),
('XH4PB5', 'Papiloma Schneideriano, invertido', 'category', false, false, 'CIE-11'),
('XH5UU5', 'Neoplasia papilar urotelial de bajo potencial maligno', 'category', false, false, 'CIE-11'),
('XH8FH7', 'Papiloma nasosinusal, invertido', 'category', false, false, 'CIE-11'),
('XH8CD4', 'Papiloma nasosinusal, oncocítico', 'category', false, false, 'CIE-11'),
('XH8CX2', 'Mola hidatiforme, SAI', 'category', false, false, 'CIE-11'),
('XH5325', 'Mola hidatiforme parcial', 'category', false, false, 'CIE-11'),
('XH3WM1', 'Coriocarcinoma combinado con otros elementos de células germinales', 'category', false, false, 'CIE-11'),
('XH0774', 'Teratoma trofoblástico maligno', 'category', false, false, 'CIE-11'),
('XH8PK7', 'Coriocarcinoma, SAI', 'category', false, false, 'CIE-11'),
('XH8FW3', 'Tumor trofoblástico, epitelioide', 'category', false, false, 'CIE-11'),
('XH46G2', 'Mola hidatiforme invasiva', 'category', false, false, 'CIE-11'),
('XH1RM5', 'Tumor trofoblástico del sitio placentario', 'category', false, false, 'CIE-11'),
('XH2N45', 'Síndrome mielodisplásico con displasia de linaje único', 'category', false, false, 'CIE-11'),
('XH5B21', 'Síndrome mielodisplásico con sideroblastos en anillo y displasia de linaje único', 'category', false, false, 'CIE-11'),
('XH79X8', 'Síndrome mielodisplásico con exceso de blastos', 'category', false, false, 'CIE-11'),
('XH1D20', 'Anemia refractaria con exceso de blastos en transformación', 'category', false, false, 'CIE-11'),
('XH5DA2', 'Síndrome mielodisplásico con displasia multinaje', 'category', false, false, 'CIE-11'),
('XH3T02', 'Síndrome mielodisplásico con deleción del (5q)', 'category', false, false, 'CIE-11'),
('XH0L58', 'Síndrome mielodisplásico debido a un tratamiento, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH7PK9', 'Síndrome mielodisplásico, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH8BA8', 'Síndrome mielodisplásico con sideroblastos en anillo y displasia multilinaje', 'category', false, false, 'CIE-11'),
('XH3EJ1', 'Neoplasia mieloproliferativa, no clasificable', 'category', false, false, 'CIE-11'),
('XH28M3', 'Neoplasia mielodisplásica o mieloproliferativa, no clasificable', 'category', false, false, 'CIE-11'),
('XH2LK2', 'Trastorno linfoproliferativo, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH2R75', 'Trastorno linfoproliferativo postransplante, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH74K1', 'Trastorno linfoproliferativo polimorfo postransplante', 'category', false, false, 'CIE-11'),
('XH0453', 'Policitemia vera', 'category', false, false, 'CIE-11'),
('XH5HH7', 'Neoplasia mieloproliferativa, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH7GG7', 'Mielofibrosis primaria', 'category', false, false, 'CIE-11'),
('XH4ZM5', 'Trombocitemia esencial', 'category', false, false, 'CIE-11'),
('XH5NQ7', 'Leucemia neutrofílica crónica', 'category', false, false, 'CIE-11'),
('XH51D2', 'Leucemia eosinofílica crónica', 'category', false, false, 'CIE-11'),
('XH07H5', 'Neoplasias mieloides y linfoides con reordenamiento de PDGFRA', 'category', false, false, 'CIE-11'),
('XH6QD4', 'Neoplasias mieloides con reordenamiento de PDGFRA', 'category', false, false, 'CIE-11'),
('XH1WR8', 'Neoplasias mieloides y linfoides con anomalías de FGFR1', 'category', false, false, 'CIE-11'),
('XH2WB4', 'Neoplasia mieloide o linfoide con PCM1-JAK2', 'category', false, false, 'CIE-11'),
('XH4S92', 'leucemia, SAI', 'category', false, false, 'CIE-11'),
('XH29P0', 'Leucemia aleucémica, SAI', 'category', false, false, 'CIE-11'),
('XH80C3', 'Leucemia crónica, SAI', 'category', false, false, 'CIE-11'),
('XH6QV5', 'Leucemia subaguda, SAI', 'category', false, false, 'CIE-11'),
('XH1B20', 'Leucemia aguda, SAI', 'category', false, false, 'CIE-11'),
('XH37U0', 'Leucemia bifenotípica aguda', 'category', false, false, 'CIE-11'),
('XH2H98', 'Leucemia bilineal aguda', 'category', false, false, 'CIE-11'),
('XH3VV7', 'Leucemia aguda de linaje mixto', 'category', false, false, 'CIE-11'),
('XH97B7', 'Leucemia aguda de fenotipo mixto con t(9;22)(q34;q11.2); BCR-ABL1', 'category', false, false, 'CIE-11'),
('XH2S51', 'Leucemia aguda de fenotipo mixto con t(v;11q23); reordenamiento de MLL', 'category', false, false, 'CIE-11'),
('XH1928', 'Leucemia aguda de fenotipo mixto, mieloide y linfoide B, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH4YB5', 'Leucemia aguda de fenotipo mixto, mieloide/ T, SAI', 'category', false, false, 'CIE-11'),
('XH81V3', 'Linfoma o leucemia linfoblástica de linaje celular B, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH73L9', 'Leucemia o linfoma linfoblástico de linfocitos B con t(9;22) (q34;q11.2); BCR-ABL1', 'category', false, false, 'CIE-11'),
('XH8GG0', 'Linfoma o leucemia linfoblástica de linfocitos B con t(V;11q23); MLL reordenado', 'category', false, false, 'CIE-11'),
('XH4KA2', 'Leucemia o linfoma linfoblástico de linfocitos B con t(12;21)(p13;q22); TEL-AML1 (ETV6-RUNX1)', 'category', false, false, 'CIE-11'),
('XH24C7', 'Leucemia o linfoma linfoblástico de linfocitos B con hiperdiploidia', 'category', false, false, 'CIE-11'),
('XH2MD9', 'Leucemia o linfoma linfoblástico de linfocitos B con hipodiploidia (LLA con hipodiploidia) hipodiplode ALL', 'category', false, false, 'CIE-11'),
('XH4ZL2', 'Leucemia o linfoma linfoblástico de linfocitos B con (5;14) (q31;q32); IL3-IGH', 'category', false, false, 'CIE-11'),
('XH3GU8', 'Leucemia o linfoma linfoblástico de linfocitos B con t(1;19)(q23;p13.3); E2A-PBX1 (TCF3-PBX1)', 'category', false, false, 'CIE-11'),
('XH7Q12', 'Leucemia linfoide, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH1GQ1', 'Leucemia linfática, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH7PW5', 'Leucemia linfocítica, sin otra especificación', 'category', false, false, 'CIE-11'),
('XH4KS4', 'Leucemia linfoide aleucémica', 'category', false, false, 'CIE-11'),
('XH5BA6', 'Leucemia de células linfosarcomatosas', 'category', false, false, 'CIE-11'),
('XH8GQ0', 'Leucemia linfoide subaguda', 'category', false, false, 'CIE-11'),
('XH15T2', 'Leucemia linfocítica crónica de linfocitos B o linfoma de linfocitos pequeños', 'category', false, false, 'CIE-11'),
('XH6TE2', 'Leucemia o linfoma de linfocitos T adultos (con positividad al VLTH-1)', 'category', false, false, 'CIE-11'),
('XH6687', 'Leucemia linfocítica granular de células-T grandes', 'category', false, false, 'CIE-11'),
('XH5EN4', 'Trastorno linfoproliferativo crónico de células NK', 'category', false, false, 'CIE-11'),
('XH8TD6', 'Leucemia prolinfocítica, SAI', 'category', false, false, 'CIE-11'),
('XH95H2', 'Leucemia prolinfocítica, de tipo células-B', 'category', false, false, 'CIE-11'),
('XH0DU4', 'Leucemia prolinfocítica, de tipo células-T', 'category', false, false, 'CIE-11'),
('XH5J37', 'Leucemia linfoblástica de células precursoras, SAI', 'category', false, false, 'CIE-11'),
('XH7T28', 'Leucemia linfoblástica de células- T precursoras', 'category', false, false, 'CIE-11'),
('XH50W7', 'Linfoma / leucemia linfoblástica T', 'category', false, false, 'CIE-11'),
('XH1D04', 'Leucemia / linfoma linfoblástico B, tipo BCR-ABL1', 'category', false, false, 'CIE-11'),
('XH0KD4', 'Leucemia / linfoma linfoblástico B con iAMP21', 'category', false, false, 'CIE-11'),
('XH8F29', 'Leucemia linfoblástica aguda precursora temprana de células T', 'category', false, false, 'CIE-11'),
('XH43N4', 'Leucemia eritroide aguda', 'category', false, false, 'CIE-11'),
('XH7S21', 'Leucemia mieloide, SAI', 'category', false, false, 'CIE-11'),
('XH7LG8', 'Leucemia mieloide aleucémica', 'category', false, false, 'CIE-11'),
('XH5DV4', 'Leucemia monocítica aleucémica', 'category', false, false, 'CIE-11'),
('XH0E35', 'Leucemia monocítica crónica', 'category', false, false, 'CIE-11'),
('XH6JX2', 'Leucemia eosinofílica', 'category', false, false, 'CIE-11'),
('XH5JT8', 'Leucemia monocítica, SAI', 'category', false, false, 'CIE-11'),
('XH1S60', 'Leucemia monocítica subaguda', 'category', false, false, 'CIE-11'),
('XH7DF6', 'Leucemia mieloide subaguda', 'category', false, false, 'CIE-11'),
('XH8AA5', 'Leucemia mieloide aguda, SAI', 'category', false, false, 'CIE-11'),
('XH4M02', 'Leucemia mieloide aguda con mutación bialélica de CEBPA', 'category', false, false, 'CIE-11'),
('XH74W8', 'Leucemia mieloide aguda con NPM1 mutado', 'category', false, false, 'CIE-11'),
('XH4XG8', 'Leucemia mieloide crónica, SAI', 'category', false, false, 'CIE-11'),
('XH9Y46', 'Leucemia mieloide aguda con t(6;9)(p23;q34); DEK-NUP214', 'category', false, false, 'CIE-11'),
('XH1A50', 'Leucemia promielocítica aguda, t(15;17)(q22;q11-12)', 'category', false, false, 'CIE-11'),
('XH78Y4', 'Leucemia mielomonocítica aguda', 'category', false, false, 'CIE-11'),
('XH2KE3', 'Leucemia mieloide aguda con Inv (3) (q21; q26,2) ó t (3,3) (q21; q26,2); RPN1-EVI1', 'category', false, false, 'CIE-11'),
('XH7MR1', 'Leucemia basofílica aguda', 'category', false, false, 'CIE-11'),
('XH3PA4', 'Leucemia mieloide aguda con eosinófilos de médula anormal', 'category', false, false, 'CIE-11'),
('XH90G0', 'Leucemia mieloide aguda, diferenciación mínima', 'category', false, false, 'CIE-11'),
('XH5AH8', 'Leucemia mieloide aguda sin maduración', 'category', false, false, 'CIE-11'),
('XH1XJ9', 'Leucemia mieloide aguda con maduración', 'category', false, false, 'CIE-11'),
('XH2AB7', 'Leucemia mielógena crónica, BCR / ABL positiva', 'category', false, false, 'CIE-11'),
('XH21X5', 'Leucemia mieloide crónica atípica, BCR / ABL negativa', 'category', false, false, 'CIE-11'),
('XH26U9', 'Leucemia mieloide crónica atípica cromosoma Filadelfia (Ph1) negativo', 'category', false, false, 'CIE-11'),
('XH9NE2', 'Leucemia monocítica aguda', 'category', false, false, 'CIE-11'),
('XH1K97', 'Leucemia monocítica y monoblástica aguda', 'category', false, false, 'CIE-11'),
('XH64R4', 'Leucemia mieloide aguda con cambios relacionados con mielodisplasia', 'category', false, false, 'CIE-11'),
('XH3CX5', 'Leucemia mieloide aguda, t(8;21)(q22;q22)', 'category', false, false, 'CIE-11'),
('XH1E41', 'Leucemia mieloide aguda, anomalías 11q23', 'category', false, false, 'CIE-11'),
('XH6AQ7', 'Leucemia mieloide en el Síndrome de Down', 'category', false, false, 'CIE-11'),
('XH4750', 'Leucemia megacarioblástica aguda', 'category', false, false, 'CIE-11'),
('XH16K4', 'Leucemia mieloide aguda (megacarioblástica) con t(1;22)(p13;q13); RBM15-MKL1', 'category', false, false, 'CIE-11'),
('XH7045', 'Neoplasia mieloide relacionada con la terapia', 'category', false, false, 'CIE-11'),
('XH6Z50', 'Leucemia mieloide aguda relacionada con la terapia, relacionada con agente de alquilación', 'category', false, false, 'CIE-11'),
('XH4EJ0', 'Leucemia mieloide aguda relacionada con la terapia, relacionada con epipodofilotoxina', 'category', false, false, 'CIE-11'),
('XH3L40', 'Sarcoma mieloide', 'category', false, false, 'CIE-11'),
('XH1075', 'Panmielosis aguda con mielofibrosis', 'category', false, false, 'CIE-11'),
('XH6FZ7', 'Leucemia mieloide aguda con BCR-ABL1', 'category', false, false, 'CIE-11'),
('XH1EK4', 'Leucemia mieloide aguda con RUNX1 mutado', 'category', false, false, 'CIE-11'),
('XH67W4', 'Mielopoyesis anormal transitoria', 'category', false, false, 'CIE-11'),
('XH86N4', 'Leucemia mielomonocítica crónica, SAI', 'category', false, false, 'CIE-11'),
('XH0FC4', 'Leucemia mielomonocítica crónica,Tipo I', 'category', false, false, 'CIE-11'),
('XH7HJ7', 'Leucemia mielomonocítica crónica, Tipo II', 'category', false, false, 'CIE-11'),
('XH4QZ1', 'Leucemia mielomonocítica juvenil', 'category', false, false, 'CIE-11'),
('XH9MA0', 'Leucemia de células NK agresiva', 'category', false, false, 'CIE-11'),
('XH5J10', 'Leucemia de células pilosas', 'category', false, false, 'CIE-11'),
('XH5FJ5', 'Linfoma maligno, SAI', 'category', false, false, 'CIE-11'),
('XH50P3', 'Linfoma maligno, no Hodgkin, SAI', 'category', false, false, 'CIE-11'),
('XH5RG7', 'Linfoma de células B, SAI', 'category', false, false, 'CIE-11'),
('XH9MU1', 'Linfosarcoma, SAI', 'category', false, false, 'CIE-11'),
('XH8226', 'Linfoma maligno, difuso,SAI', 'category', false, false, 'CIE-11'),
('XH5WX8', 'Linfoma maligno, de células no escindidas, SAI', 'category', false, false, 'CIE-11'),
('XH51A9', 'Sarcoma de células reticulares, SAI', 'category', false, false, 'CIE-11'),
('XH9E18', 'Variante de leucemia de células vellosas', 'category', false, false, 'CIE-11'),
('XH1SK1', 'Linfoma maligno, linfocítico, diferenciación intermedia, nodular', 'category', false, false, 'CIE-11'),
('XH06Q4', 'Linfoma maligno, linfocítico, poco diferenciado, difuso', 'category', false, false, 'CIE-11'),
('XH9PT6', 'Linfoma maligno, de células pequeñas, no escindidas, difusas', 'category', false, false, 'CIE-11'),
('XH2TN1', 'Linfoma maligno, de células pequeñas escindidas, difusas', 'category', false, false, 'CIE-11'),
('XH75T5', 'Linfoma / leucemia de células B esplénicas, inclasificable', 'category', false, false, 'CIE-11'),
('XH99V9', 'Linfoma de células pequeñas- B de la pulpa roja difusa esplénica', 'category', false, false, 'CIE-11'),
('XH3BP6', 'Linfoma no Hodgkin y Hodgkin compuesto', 'category', false, false, 'CIE-11'),
('XH04Y1', 'Linfoma de células B, inclasificable, con características intermedias entre el linfoma difuso de células B grandes y el linfoma de Hodgkin clásico', 'category', false, false, 'CIE-11'),
('XH1FZ7', 'Linfoma cutáneo primario del centro folicular', 'category', false, false, 'CIE-11'),
('XH73D5', 'Linfocitosis monoclonal de células B, SAI', 'category', false, false, 'CIE-11'),
('XH5M35', 'Linfocitosis monoclonal no del tipo de células B', 'category', false, false, 'CIE-11'),
('XH94F7', 'Linfoma de Hodgkin, SAI', 'category', false, false, 'CIE-11'),
('XH22K3', 'Enfermedad linfoproliferativa postrasplante linfoma de Hodgkin clásico', 'category', false, false, 'CIE-11'),
('XH8CB2', 'Linfoma de Hodgkin, rico en linfocitos', 'category', false, false, 'CIE-11'),
('XH7KX4', 'Enfermedad de Hodgkin, de predominio de linfocitos, SAI', 'category', false, false, 'CIE-11'),
('XH9NJ5', 'Linfoma de Hodgkin, celularidad mixta, SAI', 'category', false, false, 'CIE-11'),
('XH7RN9', 'Linfoma de Hodgkin, agotamiento de linfocitos, SAI', 'category', false, false, 'CIE-11'),
('XH7299', 'Linfoma de Hodgkin, depleción de linfocitos, fibrosis difusa', 'category', false, false, 'CIE-11'),
('XH4E19', 'Linfoma de Hodgkin, depleción de linfocitos, reticular', 'category', false, false, 'CIE-11'),
('XH2FG7', 'Linfoma de Hodgkin, con linfocitos nodulares predominantes', 'category', false, false, 'CIE-11'),
('XH13B0', 'Granuloma de Hodgkin', 'category', false, false, 'CIE-11'),
('XH11Y2', 'Sarcoma de Hodgkin', 'category', false, false, 'CIE-11'),
('XH6SC5', 'Linfoma de Hodgkin, esclerosis nodular, SAI', 'category', false, false, 'CIE-11'),
('XH51K7', 'Linfoma de Hodgkin, esclerosis nodular, fase celular', 'category', false, false, 'CIE-11'),
('XH62T3', 'Linfoma de Hodgkin, esclerosis nodular, de grado 1', 'category', false, false, 'CIE-11'),
('XH8K28', 'Linfoma de Hodgkin, esclerosis nodular, de grado 2', 'category', false, false, 'CIE-11'),
('XH3FE9', 'Linfomas de células- B maduras', 'category', false, false, 'CIE-11'),
('XH0QZ9', 'Linfoma linfoplasmocítico', 'category', false, false, 'CIE-11'),
('XH43K4', 'Inmunocitoma', 'category', false, false, 'CIE-11'),
('XH9TT4', 'Linfoma maligno, plasmocitoide', 'category', false, false, 'CIE-11'),
('XH3KQ3', 'Linfoma plasmocítico', 'category', false, false, 'CIE-11'),
('XH1VV1', 'Linfoma de células del manto', 'category', false, false, 'CIE-11'),
('XH1J80', 'Linfoma maligno, de células pequeñas y grandes mixtas , difuso', 'category', false, false, 'CIE-11'),
('XH2LN1', 'Linfoma primario con derrames', 'category', false, false, 'CIE-11'),
('XH8U09', 'Linfoma mediastinico de células B grandes', 'category', false, false, 'CIE-11'),
('XH9B17', 'Linfoma de células B grandes difuso, SAI', 'category', false, false, 'CIE-11'),
('XH0RM6', 'Linfoma difuso de células B grandes + Virus de Epstein Bar fibrina asociado', 'category', false, false, 'CIE-11'),
('XH1VQ1', 'Linfoma maligno, centroblástico, SAI', 'category', false, false, 'CIE-11'),
('XH9JY8', 'Linfoma maligno, centroblástico, difuso', 'category', false, false, 'CIE-11'),
('XH78W3', 'Linfoma anaplásico de células B grandes', 'category', false, false, 'CIE-11'),
('XH9L43', 'Linfoma de células B, inclasificable, con características intermedias entre el linfoma difuso de células B grandes y el de Burkitt', 'category', false, false, 'CIE-11'),
('XH3N15', 'Linfoma difuso de células grandes B asociado con inflamación crónica', 'category', false, false, 'CIE-11'),
('XH1QK0', 'Linfoma de células B grandes difuso del virus Epstein-Barr (VEB) positivo', 'category', false, false, 'CIE-11'),
('XH8657', 'Linfoma cutáneo primario, del tipo de la pierna (LDCGB )', 'category', false, false, 'CIE-11'),
('XH2MP0', 'Linfoma primario de células B grandes difuso del (SNC)', 'category', false, false, 'CIE-11'),
('XH2WM7', 'Linfoma de células B de alto grado, SAI', 'category', false, false, 'CIE-11'),
('XH23Z3', 'Linfoma de células B de alto grado con reordenamientos MYC y BCL2 y / o BCL6', 'category', false, false, 'CIE-11'),
('XH86B5', 'Linfoma vitreorretiniano', 'category', false, false, 'CIE-11'),
('XH7Z25', 'Linfoma maligno, células B grandes , difuso, inmunoblástico, SAI', 'category', false, false, 'CIE-11'),
('XH4KA9', 'Linfoma de Burkitt, SAI', 'category', false, false, 'CIE-11'),
('XH0H23', 'Linfoma similar al de Burkitt', 'category', false, false, 'CIE-11'),
('XH8NN2', 'Linfoma similar al de Burkitt con aberración 11q', 'category', false, false, 'CIE-11'),
('XH6B12', 'Leucemia de células de Burkitt', 'category', false, false, 'CIE-11'),
('XH0WP6', 'Linfoma de grandes células B rico en histocitos y células T', 'category', false, false, 'CIE-11'),
('XH0MV1', 'Linfoma de la zona marginal esplénico de células B', 'category', false, false, 'CIE-11'),
('XH0LK1', 'Linfoma folicular, SAI', 'category', false, false, 'CIE-11'),
('XH9RH9', 'Linfoma folicular, tipo pediátrico', 'category', false, false, 'CIE-11'),
('XH79L3', 'Linfoma folicular, de grado 2', 'category', false, false, 'CIE-11'),
('XH6Y69', 'Linfoma folicular, grado 1', 'category', false, false, 'CIE-11'),
('XH9L76', 'Linfoma folicular tipo duodenal', 'category', false, false, 'CIE-11'),
('XH6RN1', 'Linfoma folicular, grado 3', 'category', false, false, 'CIE-11'),
('XH6SU8', 'Linfoma de células B grandes con reordenamiento de IRF4', 'category', false, false, 'CIE-11'),
('XH1X21', 'Linfoma de células B de zona marginal, SAI', 'category', false, false, 'CIE-11'),
('XH1V99', 'Linfoma de la zona marginal extranodal de tejido linfoide asociado a la mucosa', 'category', false, false, 'CIE-11'),
('XH6JB5', 'Linfoma coroideo primario', 'category', false, false, 'CIE-11'),
('XH8EM2', 'Neoplasia de células del manto in situ', 'category', false, false, 'CIE-11'),
('XH3SG2', 'Úlcera mucocutánea positiva a Virus de Epstein Bar', 'category', false, false, 'CIE-11'),
('XH4L38', 'Neoplasia folicular in situ', 'category', false, false, 'CIE-11'),
('XH3400', 'Linfomas de células T maduras y NK', 'category', false, false, 'CIE-11'),
('XH8R56', 'Micosis fungoide', 'category', false, false, 'CIE-11'),
('XH0EH1', 'Piel laxa granulomatosa', 'category', false, false, 'CIE-11'),
('XH8HN3', 'Síndrome de Sezary', 'category', false, false, 'CIE-11'),
('XH3HJ2', 'Linfoma de células T maduras, SAI', 'category', false, false, 'CIE-11'),
('XH92G2', 'Linfoma linfoepitelioide', 'category', false, false, 'CIE-11'),
('XH14S3', 'Linfoma folicular de células T', 'category', false, false, 'CIE-11'),
('XH6SR1', 'Linfoma nodal periférico de células T con fenotipo folicular auxiliar T', 'category', false, false, 'CIE-11'),
('XH1J86', 'Linfoma de células T-angioinmunoblástico', 'category', false, false, 'CIE-11'),
('XH3NV1', 'Linfoma de células- T similar a la paniculitis subcutánea', 'category', false, false, 'CIE-11'),
('XH1951', 'Linfoma cutáneo de células T, SAI', 'category', false, false, 'CIE-11'),
('XH2513', 'Linfoma citotóxico de células T epidérmotrópico cutáneo primario CD8-positivo agresivo', 'category', false, false, 'CIE-11'),
('XH7S84', 'Linfoma cutáneo primario de células T acral CD8 positivo', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;