BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('EB21', 'Piodermia gangrenosa', 'category', false, false, 'CIE-11'),
('EB2Y', 'Otras dermatosis neutrofílica especificada', 'category', false, false, 'CIE-11'),
('EB30', 'Celulitis eosinofílica', 'category', false, false, 'CIE-11'),
('EB31', 'Eritema nodoso', 'category', false, false, 'CIE-11'),
('EB40', 'Pénfigo', 'category', false, false, 'CIE-11'),
('EB40.0', 'Pénfigo vulgar', 'category', false, false, 'CIE-11'),
('EB40.00', 'Pénfigo bucal', 'category', false, false, 'CIE-11'),
('EB40.0Y', 'Otro pénfigo vulgar especificado', 'category', false, false, 'CIE-11'),
('EB40.0Z', 'Pénfigo vulgar, sin especificación', 'category', false, false, 'CIE-11'),
('EB40.1', 'Pénfigo foliáceo', 'category', false, false, 'CIE-11'),
('EB40.2', 'Pénfigo paraneoplásico', 'category', false, false, 'CIE-11'),
('EB40.Y', 'Otro pénfigo especificado', 'category', false, false, 'CIE-11'),
('EB40.Z', 'Pénfigo, sin especificación', 'category', false, false, 'CIE-11'),
('EB41', 'Penfigoide', 'category', false, false, 'CIE-11'),
('EB41.0', 'Penfigoide ampolloso', 'category', false, false, 'CIE-11'),
('EB41.1', 'Penfigoide de la membrana mucosa', 'category', false, false, 'CIE-11'),
('EB41.Y', 'Otro penfigoide especificado', 'category', false, false, 'CIE-11'),
('EB41.Z', 'Penfigoide, sin especificación', 'category', false, false, 'CIE-11'),
('EB42', 'Dermatosis ampollosa por IgA lineal', 'category', false, false, 'CIE-11'),
('EB43', 'Epidermólisis ampollosa adquirida', 'category', false, false, 'CIE-11'),
('EB44', 'Dermatitis herpetiforme', 'category', false, false, 'CIE-11'),
('EB4Y', 'Otro trastorno inmunoampolloso especificado', 'category', false, false, 'CIE-11'),
('EB50', 'Lupus eritematoso cutáneo subagudo', 'category', false, false, 'CIE-11'),
('EB51', 'Lupus eritematoso cutáneo crónico', 'category', false, false, 'CIE-11'),
('EB51.0', 'Lupus eritematoso discoide', 'category', false, false, 'CIE-11'),
('EB51.Y', 'Otro lupus eritematoso cutáneo crónico especificado', 'category', false, false, 'CIE-11'),
('EB51.Z', 'Lupus eritematoso cutáneo crónico, sin especificación', 'category', false, false, 'CIE-11'),
('EB5Z', 'Lupus eritematoso cutáneo sin especificación', 'category', false, false, 'CIE-11'),
('EB60', 'Liquen escleroso', 'category', false, false, 'CIE-11'),
('EB60.0', 'Liquen escleroso de la vulva', 'category', false, false, 'CIE-11'),
('EB60.1', 'Liquen escleroso del pene', 'category', false, false, 'CIE-11'),
('EB60.Y', 'Liquen escleroso en otras localizaciones especificadas', 'category', false, false, 'CIE-11'),
('EB60.Z', 'Liquen escleroso, sin especificación', 'category', false, false, 'CIE-11'),
('EB61', 'Morfea', 'category', false, false, 'CIE-11'),
('EB61.0', 'Morfea en placas', 'category', false, false, 'CIE-11'),
('EB61.1', 'Morfea lineal', 'category', false, false, 'CIE-11'),
('EB61.Y', 'Otras formas especificadas de morfea', 'category', false, false, 'CIE-11'),
('EB61.Z', 'Morfea, sin especificación', 'category', false, false, 'CIE-11'),
('EB7Y', 'Otras dermatosis inflamatorias especificadas', 'category', false, false, 'CIE-11'),
('EB90', 'Dermatosis por trastornos metabólicos alterados', 'category', false, false, 'CIE-11'),
('EB90.0', 'Lesiones cutáneas diabéticas', 'category', false, false, 'CIE-11'),
('EB90.1', 'Mucinosis cutánea', 'category', false, false, 'CIE-11'),
('EB90.10', 'Mixedema pretibial', 'category', false, false, 'CIE-11'),
('EB90.11', 'Liquen mixedematoso', 'category', false, false, 'CIE-11'),
('EB90.12', 'Mucinosis eritematosa reticular', 'category', false, false, 'CIE-11'),
('EB90.1Y', 'Otras formas especificadas de mucinosis cutánea', 'category', false, false, 'CIE-11'),
('EB90.2', 'Xantomas cutáneos o subcutáneos', 'category', false, false, 'CIE-11'),
('EB90.20', 'Xantoma plano', 'category', false, false, 'CIE-11'),
('EB90.21', 'Xantoma tuberoso', 'category', false, false, 'CIE-11'),
('EB90.22', 'Xantoma eruptivo', 'category', false, false, 'CIE-11'),
('EB90.23', 'Xantoma tendinoso', 'category', false, false, 'CIE-11'),
('EB90.2Z', 'Xantomas cutáneos o subcutáneos, sin especificación', 'category', false, false, 'CIE-11'),
('EB90.3', 'Porfiria o seudoporfiria que afecta la piel', 'category', false, false, 'CIE-11'),
('EB90.30', 'Seudoporfiria', 'category', false, false, 'CIE-11'),
('EB90.3Y', 'Otra porfiria o seudoporfiria especificada que afecta la piel', 'category', false, false, 'CIE-11'),
('EB90.4', 'Calcificación de la piel o del tejido subcutáneo', 'category', false, false, 'CIE-11'),
('EB90.40', 'Calcificación distrófica de la piel de causa desconocida o no especificada', 'category', false, false, 'CIE-11'),
('EB90.41', 'Paniculitis calcificada', 'category', false, false, 'CIE-11'),
('EB90.42', 'Arteriolopatía calcificada', 'category', false, false, 'CIE-11'),
('EB90.4Y', 'Otra calcificación especificada de la piel o del tejido subcutáneo', 'category', false, false, 'CIE-11'),
('EB9Y', 'Otros trastornos metabólicos o nutricionales especificados que afectan la piel', 'category', false, false, 'CIE-11'),
('EC10', 'Síndromes genéticos con poiquilodermia', 'category', false, false, 'CIE-11'),
('EC1Y', 'Otros síndromes genéticos especificados con afectación de la piel', 'category', false, false, 'CIE-11'),
('EC20', 'Trastornos genéticos de la queratinización', 'category', false, false, 'CIE-11'),
('EC20.0', 'Ictiosis no sindrómica', 'category', false, false, 'CIE-11'),
('EC20.00', 'Ictiosis vulgar', 'category', false, false, 'CIE-11'),
('EC20.01', 'Ictiosis ligada al cromosoma X', 'category', false, false, 'CIE-11'),
('EC20.02', 'Ictiosis congénita autosómica recesiva', 'category', false, false, 'CIE-11'),
('EC20.03', 'Ictiosis queratinopáticas', 'category', false, false, 'CIE-11'),
('EC20.0Y', 'Otra ictiosis no sindrómica especificada o inclasificable', 'category', false, false, 'CIE-11'),
('EC20.1', 'Descamación cutánea hereditaria', 'category', false, false, 'CIE-11'),
('EC20.2', 'Dermatosis acantolíticas hereditarias', 'category', false, false, 'CIE-11'),
('EC20.3', 'Queratodermia palmoplantar hereditaria', 'category', false, false, 'CIE-11'),
('EC20.30', 'Queratodermia palmoplantar difusa', 'category', false, false, 'CIE-11'),
('EC20.31', 'Queratodermia palmoplantar focal', 'category', false, false, 'CIE-11'),
('EC20.32', 'Queratodermia palmoplantar papulosa', 'category', false, false, 'CIE-11'),
('EC20.3Z', 'Queratodermia palmoplantar hereditaria de tipo no especificado', 'category', false, false, 'CIE-11'),
('EC20.Y', 'Otros trastornos genéticos especificados de la queratinización', 'category', false, false, 'CIE-11'),
('EC21', 'Defectos genéticos del pelo o del crecimiento del pelo', 'category', false, false, 'CIE-11'),
('EC21.0', 'Defectos genéticos del tallo del pelo', 'category', false, false, 'CIE-11'),
('EC21.1', 'Síndromes genéticos con alteraciones del tallo del pelo', 'category', false, false, 'CIE-11'),
('EC21.2', 'Alopecia o hipotricosis hereditarias', 'category', false, false, 'CIE-11'),
('EC21.3', 'Síndromes genéticos con alopecia o hipotricosis', 'category', false, false, 'CIE-11'),
('EC21.4', 'Hipertricosis genética', 'category', false, false, 'CIE-11'),
('EC21.Y', 'Otros defectos genéticos especificados del pelo o del crecimiento del pelo', 'category', false, false, 'CIE-11'),
('EC21.Z', 'Defectos genéticos del pelo o del crecimiento del pelo, sin especificación', 'category', false, false, 'CIE-11'),
('EC22', 'Defectos genéticos de las uñas o del crecimiento de las uñas', 'category', false, false, 'CIE-11'),
('EC22.0', 'Deformidades hereditarias de las uñas', 'category', false, false, 'CIE-11'),
('EC23', 'Trastornos genéticos de la pigmentación de la piel', 'category', false, false, 'CIE-11'),
('EC23.0', 'Hipermelanosis o lentiginosis genética no sindrómica', 'category', false, false, 'CIE-11'),
('EC23.1', 'Hipermelanosis o lentiginosis genética sindrómica', 'category', false, false, 'CIE-11'),
('EC23.2', 'Albinismo u otros trastornos hipomelanóticos genéticos especificados', 'category', false, false, 'CIE-11'),
('EC23.20', 'Albinismo oculocutáneo', 'category', false, false, 'CIE-11'),
('EC23.2Y', 'Otros trastornos hipomelanóticos genéticos especificados', 'category', false, false, 'CIE-11'),
('EC23.Y', 'Otros trastornos genéticos especificados de la pigmentación de la piel', 'category', false, false, 'CIE-11'),
('EC23.Z', 'Trastornos genéticos de la pigmentación de la piel, sin especificación', 'category', false, false, 'CIE-11'),
('EC30', 'Epidermólisis ampollosa simple', 'category', false, false, 'CIE-11'),
('EC31', 'Epidermólisis ampollosa de la unión', 'category', false, false, 'CIE-11'),
('EC32', 'Epidermólisis ampollosa distrófica', 'category', false, false, 'CIE-11'),
('EC33', 'Epidermólisis ampollosa sindrómica', 'category', false, false, 'CIE-11'),
('EC3Z', 'Epidermólisis ampollosas genéticamente determinada, sin especificación', 'category', false, false, 'CIE-11'),
('EC40', 'Seudoxantoma elástico', 'category', false, false, 'CIE-11'),
('EC4Y', 'Otros trastornos genéticos especificados por alteración de proteínas de la matriz extracelular de la dermis', 'category', false, false, 'CIE-11'),
('EC50', 'Alteraciones del desarrollo del ombligo', 'category', false, false, 'CIE-11'),
('EC5Y', 'Otras anomalías especificadas del desarrollo con afectación de la piel', 'category', false, false, 'CIE-11'),
('EC7Y', 'Otros trastornos genéticos o del desarrollo especificados con afectación de la piel', 'category', false, false, 'CIE-11'),
('EC90', 'Prurito', 'category', false, false, 'CIE-11'),
('EC90.0', 'Prurito por enfermedad de la piel', 'category', false, false, 'CIE-11'),
('EC90.1', 'Prurito por enfermedad sistémica', 'category', false, false, 'CIE-11'),
('EC90.10', 'Prurito por enfermedad renal crónica', 'category', false, false, 'CIE-11'),
('EC90.11', 'Prurito colestásico', 'category', false, false, 'CIE-11'),
('EC90.12', 'Prurito asociado a hemodiálisis', 'category', false, false, 'CIE-11'),
('EC90.1Y', 'Prurito por otra enfermedad sistémica especificada', 'category', false, false, 'CIE-11'),
('EC90.2', 'Prurito provocado por medicamentos', 'category', false, false, 'CIE-11'),
('EC90.3', 'Prurito por trastorno neurológico', 'category', false, false, 'CIE-11'),
('EC90.4', 'Prurito psicógeno', 'category', false, false, 'CIE-11'),
('EC90.5', 'Prurito anogenital', 'category', false, false, 'CIE-11'),
('EC90.6', 'Prurito de causa desconocida', 'category', false, false, 'CIE-11'),
('EC90.Y', 'Prurito de otro tipo u otra causa especificados', 'category', false, false, 'CIE-11'),
('EC90.Z', 'Prurito, sin especificación', 'category', false, false, 'CIE-11'),
('EC91', 'Prurigo', 'category', false, false, 'CIE-11'),
('EC91.0', 'Prurigo nodular', 'category', false, false, 'CIE-11'),
('EC91.1', 'Prurigo atópico', 'category', false, false, 'CIE-11'),
('EC91.Z', 'Prurigo, sin especificación', 'category', false, false, 'CIE-11'),
('EC92', 'Síndromes dolorosos cutáneos o mucocutáneos', 'category', false, false, 'CIE-11'),
('EC92.0', 'dolor disestésico escrotal y peneano', 'category', false, false, 'CIE-11'),
('EC92.1', 'Disestesia del cuero cabelludo', 'category', false, false, 'CIE-11'),
('EC9Y', 'Otras alteraciones especificadas de la sensibilidad cutánea', 'category', false, false, 'CIE-11'),
('ED00', 'Trastorno cutáneo artefactual', 'category', false, false, 'CIE-11'),
('ED01', 'Enfermedad cutánea simulada', 'category', false, false, 'CIE-11'),
('ED02', 'Síndrome de Gardner-Diamond', 'category', false, false, 'CIE-11'),
('ED0Y', 'Otros trastornos cutáneos autoinfligidos especificados', 'category', false, false, 'CIE-11'),
('ED2Y', 'Otras condiciones psicológicas o psiquiátricas especificadas con afectación de la piel', 'category', false, false, 'CIE-11'),
('ED30', 'Daño cutáneo neuropático', 'category', false, false, 'CIE-11'),
('ED30.0', 'Úlcera neuropática', 'category', false, false, 'CIE-11'),
('ED30.Y', 'Otro daño cutáneo neuropático especificado', 'category', false, false, 'CIE-11'),
('ED31', 'Síndrome de los pies ardientes', 'category', false, false, 'CIE-11'),
('ED3Y', 'Otras enfermedades neurológicas especificadas con afectación de la piel', 'category', false, false, 'CIE-11'),
('ED50', 'Ictiosis', 'category', false, false, 'CIE-11'),
('ED50.0', 'Ictiosis adquirida', 'category', false, false, 'CIE-11'),
('ED50.Z', 'Ictiosis de tipo no especificado', 'category', false, false, 'CIE-11'),
('ED51', 'Hiperqueratosis o acantosis epidérmicas difusas', 'category', false, false, 'CIE-11'),
('ED51.0', 'Acantosis nigricans', 'category', false, false, 'CIE-11'),
('ED51.00', 'Acantosis nigricans benigna', 'category', false, false, 'CIE-11'),
('ED51.0Y', 'Otra acantosis nigricans especificada', 'category', false, false, 'CIE-11'),
('ED51.0Z', 'Acantosis nigricans, sin especificación', 'category', false, false, 'CIE-11'),
('ED51.Y', 'Otra hiperqueratosis o acantosis epidérmicas difusas', 'category', false, false, 'CIE-11'),
('ED51.Z', 'Hiperqueratosis o acantosis epidérmicas difusas, sin especificación', 'category', false, false, 'CIE-11'),
('ED52', 'Poroqueratosis', 'category', false, false, 'CIE-11'),
('ED53', 'Descamación de la piel', 'category', false, false, 'CIE-11'),
('ED54', 'Xerosis cutánea o asteatosis', 'category', false, false, 'CIE-11'),
('ED55', 'Queratodermias palmoplantares', 'category', false, false, 'CIE-11'),
('ED55.0', 'Queratodermias palmoplantares adquiridas', 'category', false, false, 'CIE-11'),
('ED55.Z', 'Queratodermia palmoplantar, sin especificación', 'category', false, false, 'CIE-11'),
('ED56', 'Queratosis pilaris', 'category', false, false, 'CIE-11'),
('ED5Y', 'Otros trastornos especificados de la queratinización epidérmica', 'category', false, false, 'CIE-11'),
('ED60', 'Hipermelanosis adquirida', 'category', false, false, 'CIE-11'),
('ED60.0', 'Hipermelanosis fisiológica', 'category', false, false, 'CIE-11'),
('ED60.00', 'Bronceado natural', 'category', false, false, 'CIE-11'),
('ED60.01', 'Bronceado por exposición a fuentes artificiales de radiación ultravioleta', 'category', false, false, 'CIE-11'),
('ED60.1', 'Melasma', 'category', false, false, 'CIE-11'),
('ED60.2', 'Hipermelanosis postinflamatoria', 'category', false, false, 'CIE-11'),
('ED60.Y', 'Otra hipermelanosis adquirida de causa especificada', 'category', false, false, 'CIE-11'),
('ED60.Z', 'Hipermelanosis de causa no especificada', 'category', false, false, 'CIE-11'),
('ED61', 'Máculas o léntigos melanóticos adquiridas', 'category', false, false, 'CIE-11'),
('ED61.0', 'efélides', 'category', false, false, 'CIE-11'),
('ED61.1', 'Melanosis mucosa', 'category', false, false, 'CIE-11'),
('ED61.10', 'Mácula melanótica del pene', 'category', false, false, 'CIE-11'),
('ED61.11', 'Mácula melanótica vulvar', 'category', false, false, 'CIE-11'),
('ED61.1Y', 'Otra melanosis mucosa especificada', 'category', false, false, 'CIE-11'),
('ED61.Y', 'Otras máculas o léntigos melanóticos adquiridos especificados', 'category', false, false, 'CIE-11'),
('ED62', 'Pigmentación endógena no melánica', 'category', false, false, 'CIE-11'),
('ED62.0', 'Pigmentación de la piel por hemosiderina', 'category', false, false, 'CIE-11'),
('ED62.Y', 'Otra pigmentación endógena no melánica especificada', 'category', false, false, 'CIE-11'),
('ED63', 'Trastornos hipomelanóticos adquiridos', 'category', false, false, 'CIE-11'),
('ED63.0', 'Vitiligo', 'category', false, false, 'CIE-11'),
('ED63.1', 'Hipomelanosis por exposición a sustancias químicas', 'category', false, false, 'CIE-11'),
('ED63.2', 'Hipomelanosis postinflamatoria', 'category', false, false, 'CIE-11'),
('ED63.3', 'Síndrome de Vogt-Koyanagi-Harada', 'category', false, false, 'CIE-11'),
('ED63.Y', 'Otros trastornos hipomelanóticos adquiridos especificados', 'category', false, false, 'CIE-11'),
('ED63.Z', 'Trastornos hipomelanóticos adquiridos, sin especificación', 'category', false, false, 'CIE-11'),
('ED64', 'Pigmentación anormal de la piel', 'category', false, false, 'CIE-11'),
('ED6Y', 'Otros trastornos especificados del color de la piel', 'category', false, false, 'CIE-11'),
('ED70', 'Alopecia o caída del pelo', 'category', false, false, 'CIE-11'),
('ED70.0', 'Alopecia de patrón masculino', 'category', false, false, 'CIE-11'),
('ED70.1', 'Alopecia de patrón femenino', 'category', false, false, 'CIE-11'),
('ED70.2', 'Alopecia areata', 'category', false, false, 'CIE-11'),
('ED70.20', 'Alopecia areata en placas del cuero cabelludo', 'category', false, false, 'CIE-11'),
('ED70.21', 'alopecia total', 'category', false, false, 'CIE-11'),
('ED70.2Y', 'Otras formas especificadas de alopecia areata', 'category', false, false, 'CIE-11'),
('ED70.2Z', 'Alopecia areata, sin especificación', 'category', false, false, 'CIE-11'),
('ED70.3', 'Efluvio telógeno', 'category', false, false, 'CIE-11'),
('ED70.30', 'Efluvio telógeno agudo', 'category', false, false, 'CIE-11'),
('ED70.31', 'Efluvio telógeno posparto', 'category', false, false, 'CIE-11'),
('ED70.3Y', 'Telógeno muda de pelo debido a otra causa especificada', 'category', false, false, 'CIE-11'),
('ED70.3Z', 'Efluvio telógeno, sin especificación', 'category', false, false, 'CIE-11'),
('ED70.4', 'Efluvio anágeno', 'category', false, false, 'CIE-11'),
('ED70.5', 'Alopecia cicatricial', 'category', false, false, 'CIE-11'),
('ED70.50', 'Foliculitis decalvante', 'category', false, false, 'CIE-11'),
('ED70.51', 'Celulitis disecante', 'category', false, false, 'CIE-11'),
('ED70.5Y', 'Alopecia cicatricial por otra causa especificada', 'category', false, false, 'CIE-11'),
('ED70.5Z', 'Alopecia cicatricial, sin especificación', 'category', false, false, 'CIE-11'),
('ED70.Y', 'Otra alopecia o caída del pelo especificada', 'category', false, false, 'CIE-11'),
('ED70.Z', 'Alopecia o caída del pelo, sin especificación', 'category', false, false, 'CIE-11'),
('ED71', 'Hipertricosis', 'category', false, false, 'CIE-11'),
('ED72', 'Hirsutismo o síndromes con hirsutismo', 'category', false, false, 'CIE-11'),
('ED72.0', 'Hirsutismo idiopático', 'category', false, false, 'CIE-11'),
('ED72.1', 'Hirsutismo con hiperandrogenemia', 'category', false, false, 'CIE-11'),
('ED72.Z', 'Hirsutismo, sin especificación', 'category', false, false, 'CIE-11'),
('ED73', 'Trastornos adquiridos del tallo del pelo', 'category', false, false, 'CIE-11'),
('ED73.0', 'Pelo desgastado', 'category', false, false, 'CIE-11'),
('ED73.1', 'Cambios adquiridos en el color del cabello', 'category', false, false, 'CIE-11'),
('ED73.10', 'Canicie prematura', 'category', false, false, 'CIE-11'),
('ED73.11', 'Poliosis adquirida', 'category', false, false, 'CIE-11'),
('ED73.Y', 'Otros trastornos adquiridos especificadas del tallo del pelo', 'category', false, false, 'CIE-11'),
('ED7Y', 'Otros trastornos especificados del pelo', 'category', false, false, 'CIE-11'),
('ED80', 'Acné', 'category', false, false, 'CIE-11'),
('ED80.0', 'Acné comedononiano', 'category', false, false, 'CIE-11'),
('ED80.1', 'Acné mixto superficial comedoniano y papulopustuloso', 'category', false, false, 'CIE-11'),
('ED80.2', 'Acné papulopustuloso', 'category', false, false, 'CIE-11'),
('ED80.3', 'Acné nodular', 'category', false, false, 'CIE-11'),
('ED80.4', 'Acné inflamatorio severo', 'category', false, false, 'CIE-11'),
('ED80.40', 'Acné fulminante', 'category', false, false, 'CIE-11'),
('ED80.41', 'Acné conglobata', 'category', false, false, 'CIE-11'),
('ED80.4Y', 'Otro acné inflamatorio severo especificado', 'category', false, false, 'CIE-11'),
('ED80.4Z', 'Acné inflamatorio severo, sin especificación', 'category', false, false, 'CIE-11'),
('ED80.5', 'Cicatrices del acné', 'category', false, false, 'CIE-11'),
('ED80.6', 'Acné del lactante', 'category', false, false, 'CIE-11'),
('ED80.Y', 'Otro acné especificado', 'category', false, false, 'CIE-11'),
('ED80.Z', 'Acné, sin especificación', 'category', false, false, 'CIE-11'),
('ED81', 'Trastornos inflamatorios acneiformes', 'category', false, false, 'CIE-11'),
('ED81.0', 'Foliculitis crural pustulosa y atrófica', 'category', false, false, 'CIE-11'),
('ED81.1', 'Reacciones acneiformes a los hidrocarburos aromáticos halogenados', 'category', false, false, 'CIE-11'),
('ED81.Y', 'Otros trastornos inflamatorios acneiformes especificados', 'category', false, false, 'CIE-11'),
('ED81.Z', 'Trastornos inflamatorios acneiformes, sin especificación', 'category', false, false, 'CIE-11'),
('ED90', 'Rosácea y trastornos relacionados', 'category', false, false, 'CIE-11'),
('ED90.0', 'Rosácea', 'category', false, false, 'CIE-11'),
('ED90.00', 'Rosácea eritematotelangiectásica', 'category', false, false, 'CIE-11'),
('ED90.01', 'Rosácea papulopustulosa', 'category', false, false, 'CIE-11'),
('ED90.02', 'Rosácea fimatosa', 'category', false, false, 'CIE-11'),
('ED90.0Y', 'Otra rosácea especificada', 'category', false, false, 'CIE-11'),
('ED90.0Z', 'Rosácea, sin especificación', 'category', false, false, 'CIE-11'),
('ED90.1', 'Dermatitis periorificial', 'category', false, false, 'CIE-11'),
('ED90.Y', 'Otros trastornos especificados parecidos a la rosácea', 'category', false, false, 'CIE-11'),
('ED90.Z', 'Rosácea y trastornos relacionados, sin especificación', 'category', false, false, 'CIE-11'),
('ED91', 'Trastornos de las glándulas sebáceas', 'category', false, false, 'CIE-11'),
('ED91.0', 'Glándulas sebáceas heterotópicas', 'category', false, false, 'CIE-11'),
('ED91.1', 'Hiperplasia de las glándulas sebáceas', 'category', false, false, 'CIE-11'),
('ED91.2', 'Seborrea', 'category', false, false, 'CIE-11'),
('ED91.Y', 'Otro(a)(s) trastornos de las glándulas sebáceas especificado(a)(s)', 'category', false, false, 'CIE-11'),
('ED91.Z', 'Trastornos de las glándulas sebáceas, sin especificación', 'category', false, false, 'CIE-11'),
('ED92', 'Trastornos de la unidad folicular apocrina', 'category', false, false, 'CIE-11'),
('ED92.0', 'Hidradenitis supurativa', 'category', false, false, 'CIE-11'),
('ED92.1', 'Trastornos sudoríparos apocrinos', 'category', false, false, 'CIE-11'),
('ED92.Y', 'Otro(a)(s) trastornos de la unidad folicular apocrina especificado(a)(s)', 'category', false, false, 'CIE-11'),
('ED92.Z', 'Trastornos de la unidad folicular apocrina, sin especificación', 'category', false, false, 'CIE-11'),
('ED9Y', 'Otros trastornos especificados del folículo piloso', 'category', false, false, 'CIE-11'),
('EE00', 'Hiperhidrosis', 'category', false, false, 'CIE-11'),
('EE00.0', 'Hiperhidrosis localizada', 'category', false, false, 'CIE-11'),
('EE00.00', 'Hiperhidrosis palmoplantar', 'category', false, false, 'CIE-11'),
('EE00.01', 'Hiperhidrosis axilar', 'category', false, false, 'CIE-11'),
('EE00.02', 'Hiperhidrosis craneofacial', 'category', false, false, 'CIE-11'),
('EE00.0Y', 'Otra hiperhidrosis localizada especificada', 'category', false, false, 'CIE-11'),
('EE00.0Z', 'Hiperhidrosis localizada, sin especificación', 'category', false, false, 'CIE-11'),
('EE00.1', 'Hiperhidrosis generalizada primaria', 'category', false, false, 'CIE-11'),
('EE00.Z', 'Hiperhidrosis, sin especificación', 'category', false, false, 'CIE-11'),
('EE01', 'Hipohidrosis', 'category', false, false, 'CIE-11'),
('EE01.0', 'Hipohidrosis atribuible a inervación o función sudomotoras defectuosas', 'category', false, false, 'CIE-11'),
('EE01.1', 'Hipohidrosis por anomalías genéticas estructurales o funcionales de las glándulas ecrinas', 'category', false, false, 'CIE-11'),
('EE01.2', 'Hipohidrosis de causa indeterminada', 'category', false, false, 'CIE-11'),
('EE01.Y', 'Otras formas especificadas de hipohidrosis', 'category', false, false, 'CIE-11'),
('EE01.Z', 'Hipohidrosis, sin especificación', 'category', false, false, 'CIE-11'),
('EE02', 'Miliaria', 'category', false, false, 'CIE-11'),
('EE02.0', 'Miliaria neonatal', 'category', false, false, 'CIE-11'),
('EE02.Y', 'Otras formas especificadas de miliaria', 'category', false, false, 'CIE-11'),
('EE02.Z', 'Miliaria, sin especificación', 'category', false, false, 'CIE-11'),
('EE0Y', 'Otros trastornos especificados de las glándulas sudoríparas ecrinas o de la sudación', 'category', false, false, 'CIE-11'),
('EE10', 'Deformidades adquiridas de la lámina ungueal', 'category', false, false, 'CIE-11'),
('EE10.0', 'Alteración de la forma de la uña', 'category', false, false, 'CIE-11'),
('EE10.1', 'Alteración de la superficie de la uña', 'category', false, false, 'CIE-11'),
('EE10.10', 'Lesiones punteadas en las uñas', 'category', false, false, 'CIE-11'),
('EE10.1Y', 'Otra alteración especificada de la superficie de la uña', 'category', false, false, 'CIE-11'),
('EE10.1Z', 'Alteración de la superficie de la uña, sin especificación', 'category', false, false, 'CIE-11'),
('EE10.2', 'Onicólisis', 'category', false, false, 'CIE-11'),
('EE10.3', 'Hipertrofia de las uñas', 'category', false, false, 'CIE-11'),
('EE10.4', 'Atrofia de las uñas', 'category', false, false, 'CIE-11'),
('EE10.5', 'Distrofia ungueal SAI', 'category', false, false, 'CIE-11'),
('EE10.Y', 'Otras deformidades adquiridas especificadas de la lámina ungueal', 'category', false, false, 'CIE-11'),
('EE10.Z', 'Deformidades adquiridas de la lámina ungueal, sin especificación', 'category', false, false, 'CIE-11'),
('EE11', 'Alteraciones adquiridas del color de las uñas', 'category', false, false, 'CIE-11'),
('EE11.0', 'Melanoniquia', 'category', false, false, 'CIE-11'),
('EE11.1', 'Síndrome de las uñas amarillas', 'category', false, false, 'CIE-11'),
('EE11.Y', 'Otras alteraciones adquiridas especificadas del color de las uñas', 'category', false, false, 'CIE-11'),
('EE11.Z', 'Alteraciones adquiridas del color de las uñas, sin especificación', 'category', false, false, 'CIE-11'),
('EE12', 'Infecciones de la uña o del perioniquio', 'category', false, false, 'CIE-11'),
('EE12.0', 'Paroniquia bacteriana aguda', 'category', false, false, 'CIE-11'),
('EE12.1', 'Onicomicosis', 'category', false, false, 'CIE-11'),
('EE12.Y', 'Otras infecciones especificadas de la uña o del perioniquio', 'category', false, false, 'CIE-11'),
('EE12.Z', 'Infecciones de la uña o del perioniquio, sin especificación', 'category', false, false, 'CIE-11'),
('EE13', 'Algunos trastornos de las uñas o del perioniquio', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;