BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('LA30.Y', 'Otras anomalías estructurales especificadas del desarrollo de los dientes y de los tejidos periodontales', 'category', false, false, 'CIE-11'),
('LA30.Z', 'Anomalías estructurales del desarrollo de los dientes y de los tejidos periodontales, sin especificación', 'category', false, false, 'CIE-11'),
('LA31', 'Anomalías estructurales del desarrollo de la boca o de la lengua', 'category', false, false, 'CIE-11'),
('LA31.0', 'Macroglosia congénita', 'category', false, false, 'CIE-11'),
('LA31.1', 'Hipoglosia o aglosia', 'category', false, false, 'CIE-11'),
('LA31.2', 'Anquiloglosia', 'category', false, false, 'CIE-11'),
('LA31.3', 'Macrostomía', 'category', false, false, 'CIE-11'),
('LA31.4', 'Microstomía', 'category', false, false, 'CIE-11'),
('LA31.Y', 'Otras anomalías estructurales especificadas del desarrollo de la boca o de la lengua', 'category', false, false, 'CIE-11'),
('LA31.Z', 'Anomalías estructurales del desarrollo de la boca o de la lengua, sin especificación', 'category', false, false, 'CIE-11'),
('LA40', 'Fisura labial', 'category', false, false, 'CIE-11'),
('LA40.0', 'Fisura labial unilateral', 'category', false, false, 'CIE-11'),
('LA40.1', 'Fisura labial bilateral', 'category', false, false, 'CIE-11'),
('LA40.2', 'Fisura labial en la línea media', 'category', false, false, 'CIE-11'),
('LA40.Z', 'Fisura labial, sin especificación', 'category', false, false, 'CIE-11'),
('LA41', 'Fisura labial y alveolar', 'category', false, false, 'CIE-11'),
('LA41.0', 'Fisura labial y alveolar unilateral', 'category', false, false, 'CIE-11'),
('LA41.1', 'Fisura labial y alveolar bilateral', 'category', false, false, 'CIE-11'),
('LA41.Z', 'Fisura labial y alveolar, sin especificación', 'category', false, false, 'CIE-11'),
('LA42', 'Fisura del paladar', 'category', false, false, 'CIE-11'),
('LA42.0', 'Fisura de la bóveda del paladar', 'category', false, false, 'CIE-11'),
('LA42.1', 'Fisura del velo del paladar', 'category', false, false, 'CIE-11'),
('LA42.2', 'Fisura de la úvula', 'category', false, false, 'CIE-11'),
('LA42.Z', 'Fisura del paladar, sin especificación', 'category', false, false, 'CIE-11'),
('LA4Y', 'Otras fisuras labiales, alveolares o palatinas especificadas', 'category', false, false, 'CIE-11'),
('LA4Z', 'Fisuras labiales, alveolares o palatinas, sin especificación', 'category', false, false, 'CIE-11'),
('LA50', 'Insuficiencia velofaríngea congénita', 'category', false, false, 'CIE-11'),
('LA51', 'Fisuras faciales', 'category', false, false, 'CIE-11'),
('LA52', 'Asimetría facial', 'category', false, false, 'CIE-11'),
('LA53', 'Macroqueilia', 'category', false, false, 'CIE-11'),
('LA54', 'Microqueilia', 'category', false, false, 'CIE-11'),
('LA55', 'Facies comprimida', 'category', false, false, 'CIE-11'),
('LA56', 'Síndrome de Pierre Robin', 'category', false, false, 'CIE-11'),
('LA5Y', 'Otras anomalías estructurales del desarrollo especificadas de la cara, la boca o los dientes.', 'category', false, false, 'CIE-11'),
('LA5Z', 'Anomalías estructurales del desarrollo de la cara, la boca o los dientes, sin especificación', 'category', false, false, 'CIE-11'),
('LA60', 'Cuello alado', 'category', false, false, 'CIE-11'),
('LA61', 'Tumor esternocleidomastoideo congénito', 'category', false, false, 'CIE-11'),
('LA62', 'Tortícolis congénita', 'category', false, false, 'CIE-11'),
('LA6Y', 'Otras anomalías estructurales del desarrollo especificadas del cuello', 'category', false, false, 'CIE-11'),
('LA6Z', 'Anomalías estructurales del desarrollo del cuello, sin especificación', 'category', false, false, 'CIE-11'),
('LA70', 'Anomalías estructurales del desarrollo prenatal de la nariz o la nasofaringe', 'category', false, false, 'CIE-11'),
('LA70.0', 'Arrinia', 'category', false, false, 'CIE-11'),
('LA70.1', 'Nariz bífida', 'category', false, false, 'CIE-11'),
('LA70.2', 'Atresia de coanas', 'category', false, false, 'CIE-11'),
('LA70.3', 'Tabique nasal perforado congénito', 'category', false, false, 'CIE-11'),
('LA70.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal de la nariz o la nasofaringe', 'category', false, false, 'CIE-11'),
('LA70.Z', 'Anomalías estructurales del desarrollo prenatal de la nariz o la nasofaringe, sin especificación', 'category', false, false, 'CIE-11'),
('LA71', 'Anomalías estructurales del desarrollo prenatal de la laringe', 'category', false, false, 'CIE-11'),
('LA71.0', 'Laringomalacia congénita', 'category', false, false, 'CIE-11'),
('LA71.1', 'Laringocele', 'category', false, false, 'CIE-11'),
('LA71.2', 'Hipoplasia laríngea', 'category', false, false, 'CIE-11'),
('LA71.3', 'Estenosis subglótica congénita', 'category', false, false, 'CIE-11'),
('LA71.Y', 'Otras anomalías estructurales congénitas del desarrollo prenatal de la laringe', 'category', false, false, 'CIE-11'),
('LA71.Z', 'Anomalías estructurales del desarrollo prenatal de la laringe, sin especificación', 'category', false, false, 'CIE-11'),
('LA72', 'Fisura laringotraqueoesofágica', 'category', false, false, 'CIE-11'),
('LA73', 'Anomalías estructurales del desarrollo prenatal de la tráquea', 'category', false, false, 'CIE-11'),
('LA73.0', 'Estenosis congénita de la tráquea', 'category', false, false, 'CIE-11'),
('LA73.1', 'Traqueomalacia congénita', 'category', false, false, 'CIE-11'),
('LA73.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal de la tráquea', 'category', false, false, 'CIE-11'),
('LA73.Z', 'Anomalías estructurales del desarrollo prenatal de la tráquea, sin especificación', 'category', false, false, 'CIE-11'),
('LA74', 'Anomalías estructurales del desarrollo prenatal de los bronquios', 'category', false, false, 'CIE-11'),
('LA74.0', 'Estenosis o atresia congénita de los bronquios', 'category', false, false, 'CIE-11'),
('LA74.1', 'Broncomalacia congénita', 'category', false, false, 'CIE-11'),
('LA74.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal de los bronquios', 'category', false, false, 'CIE-11'),
('LA74.Z', 'Anomalías estructurales del desarrollo prenatal de los bronquios, sin especificación', 'category', false, false, 'CIE-11'),
('LA75', 'Anomalías estructurales del desarrollo prenatal de los pulmones', 'category', false, false, 'CIE-11'),
('LA75.0', 'Lóbulo accesorio de pulmón', 'category', false, false, 'CIE-11'),
('LA75.1', 'Agenesia de pulmón', 'category', false, false, 'CIE-11'),
('LA75.2', 'Hipoplasia congénita del pulmón', 'category', false, false, 'CIE-11'),
('LA75.3', 'Hiperplasia congénita del pulmón', 'category', false, false, 'CIE-11'),
('LA75.4', 'Malformaciones congénitas de vías respiratorias pulmonares', 'category', false, false, 'CIE-11'),
('LA75.5', 'Enfisema lobular congénito', 'category', false, false, 'CIE-11'),
('LA75.6', 'Secuestro pulmonar congénito', 'category', false, false, 'CIE-11'),
('LA75.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal de los pulmones', 'category', false, false, 'CIE-11'),
('LA75.Z', 'Anomalías estructurales del desarrollo prenatal de los pulmones, sin especificación', 'category', false, false, 'CIE-11'),
('LA76', 'Anomalías estructurales del desarrollo prenatal de la pleura', 'category', false, false, 'CIE-11'),
('LA77', 'Quiste congénito del mediastino', 'category', false, false, 'CIE-11'),
('LA7Y', 'Otras anomalías estructurales del desarrollo especificadas del sistema respiratorio', 'category', false, false, 'CIE-11'),
('LA7Z', 'Anomalías estructurales del desarrollo del sistema respiratorio, sin especificación', 'category', false, false, 'CIE-11'),
('LA80', 'Posición u orientación anómala del corazón', 'category', false, false, 'CIE-11'),
('LA80.0', 'Levocardia', 'category', false, false, 'CIE-11'),
('LA80.1', 'Dextrocardia', 'category', false, false, 'CIE-11'),
('LA80.2', 'Mesocardia', 'category', false, false, 'CIE-11'),
('LA80.3', 'Corazón extratorácico', 'category', false, false, 'CIE-11'),
('LA80.Y', 'Otra posición u orientación anómala especificada del corazón', 'category', false, false, 'CIE-11'),
('LA80.Z', 'Posición u orientación anómala del corazón, sin especificación', 'category', false, false, 'CIE-11'),
('LA81', 'Relaciones ventriculares anormales', 'category', false, false, 'CIE-11'),
('LA82', 'Situs inversus total', 'category', false, false, 'CIE-11'),
('LA83', 'Isomerismo derecho', 'category', false, false, 'CIE-11'),
('LA84', 'Isomerismo izquierdo', 'category', false, false, 'CIE-11'),
('LA85', 'Anomalía congénita de una conexión auriculoventricular o ventriculoarterial', 'category', false, false, 'CIE-11'),
('LA85.0', 'Conexiones auriculoventriculares discordantes', 'category', false, false, 'CIE-11'),
('LA85.00', 'Transposición congénitamente corregida de las grandes arterias', 'category', false, false, 'CIE-11'),
('LA85.0Y', 'Otras conexiones auriculoventriculares discordantes especificadas', 'category', false, false, 'CIE-11'),
('LA85.0Z', 'Conexiones auriculoventriculares discordantes, sin especificar', 'category', false, false, 'CIE-11'),
('LA85.1', 'Transposición de las grandes arterias', 'category', false, false, 'CIE-11'),
('LA85.2', 'Ventrículo derecho con doble salida', 'category', false, false, 'CIE-11'),
('LA85.20', 'Ventrículo derecho de doble salida con comunicación interventricular subpulmonar, tipo transposición', 'category', false, false, 'CIE-11'),
('LA85.21', 'Ventrículo derecho de doble salida con comunicación interventricular no comprometida', 'category', false, false, 'CIE-11'),
('LA85.22', 'Ventrículo derecho de doble salida con comunicación interventricular subaórtica o doblemente comprometida sin estenosis pulmonar, tipo comunicación interventricular', 'category', false, false, 'CIE-11'),
('LA85.23', 'Doble salida ventricular derecha|con defecto septal ventricular subaórtica o doblemente comprometida| y estenosis pulmonar, tipo Fallot', 'category', false, false, 'CIE-11'),
('LA85.2Y', 'Otro ventrículo derecho con doble salida especificado', 'category', false, false, 'CIE-11'),
('LA85.2Z', 'Ventrículo derecho con doble salida, sin especificación', 'category', false, false, 'CIE-11'),
('LA85.3', 'Ventrículo izquierdo con doble salida', 'category', false, false, 'CIE-11'),
('LA85.4', 'Tronco arterioso común', 'category', false, false, 'CIE-11'),
('LA85.40', 'Tronco arterioso común con dominancia aórtica', 'category', false, false, 'CIE-11'),
('LA85.41', 'Tronco arterioso común con dominancia pulmonar e interrupción del cayado aórtico', 'category', false, false, 'CIE-11'),
('LA85.4Y', 'Otro tronco arterioso común especificado', 'category', false, false, 'CIE-11'),
('LA85.4Z', 'Tronco arterioso común, sin especificación', 'category', false, false, 'CIE-11'),
('LA85.Y', 'Otra anomalía congénita especificada de una conexión auriculoventricular o ventriculoarterial', 'category', false, false, 'CIE-11'),
('LA85.Z', 'Anomalía congénita de una conexión auriculoventricular o ventriculoarterial, sin especificación', 'category', false, false, 'CIE-11'),
('LA86', 'Anomalía congénita de vena mediastínica', 'category', false, false, 'CIE-11'),
('LA86.0', 'Vena cava superior izquierda', 'category', false, false, 'CIE-11'),
('LA86.1', 'Seno coronario fenestrado', 'category', false, false, 'CIE-11'),
('LA86.2', 'Conexión anómala de venas pulmonares', 'category', false, false, 'CIE-11'),
('LA86.20', 'Conexión anómala total de venas pulmonares', 'category', false, false, 'CIE-11'),
('LA86.21', 'Conexión anómala parcial de venas pulmonares', 'category', false, false, 'CIE-11'),
('LA86.22', 'Síndrome de la cimitarra', 'category', false, false, 'CIE-11'),
('LA86.2Y', 'Otra conexión anómala especificada de venas pulmonares', 'category', false, false, 'CIE-11'),
('LA86.2Z', 'Conexión anómala de venas pulmonares, sin especificación', 'category', false, false, 'CIE-11'),
('LA86.3', 'Estenosis o hipoplasia congénita de vena pulmonar', 'category', false, false, 'CIE-11'),
('LA86.Y', 'Otra anomalía congénita especificada de vena mediastínica', 'category', false, false, 'CIE-11'),
('LA86.Z', 'Anomalía congénita de vena mediastínica, sin especificación', 'category', false, false, 'CIE-11'),
('LA87', 'Anomalía congénita de una válvula auriculoventricular o tabique auriculoventricular', 'category', false, false, 'CIE-11'),
('LA87.0', 'Anomalía congénita de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('LA87.00', 'Insuficiencia tricuspídea congénita', 'category', false, false, 'CIE-11'),
('LA87.01', 'Estenosis congénita de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('LA87.02', 'Displasia de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('LA87.03', 'Malformación de Ebstein de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('LA87.0Y', 'Otra anomalía congénita especificada de la válvula tricúspide', 'category', false, false, 'CIE-11'),
('LA87.0Z', 'Anomalía congénita de la válvula tricúspide, sin especificación', 'category', false, false, 'CIE-11'),
('LA87.1', 'Anomalía congénita de la válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.10', 'Insuficiencia congénita de la válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.11', 'Estenosis congénita de válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.12', 'Displasia de la válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.13', 'Anomalía congénita del aparato subvalvular de la válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.1Y', 'Otra anomalía congénita especificada de la válvula mitral', 'category', false, false, 'CIE-11'),
('LA87.1Z', 'Anomalía congénita de la válvula mitral, sin especificación', 'category', false, false, 'CIE-11'),
('LA87.3', 'Unión común aurículoventricular sin defecto septal aurículoventricular', 'category', false, false, 'CIE-11'),
('LA87.4', 'Unión auriculoventricular común con defecto del tabique auriculoventricular', 'category', false, false, 'CIE-11'),
('LA87.40', 'Defecto septal aurículoventricular parcial con comunicación solo a nivel auricular', 'category', false, false, 'CIE-11'),
('LA87.41', 'Defecto septal aurículoventricular con comunicación a nivel ventricular solamente', 'category', false, false, 'CIE-11'),
('LA87.42', 'Defecto septal aurículoventricular con comunicación a nivel auricular y comunicación restrictiva a nivel ventricular', 'category', false, false, 'CIE-11'),
('LA87.43', 'Defecto septal aurículoventricular con comunicación a nivel auricular y comunicación no restrictiva a nivel ventricular', 'category', false, false, 'CIE-11'),
('LA87.44', 'Defecto del septo aurículoventricular con desequilibrio ventricular', 'category', false, false, 'CIE-11'),
('LA87.45', 'Defecto septal aurículoventricular y tetralogía de Fallot', 'category', false, false, 'CIE-11'),
('LA87.4Y', 'Otro(a)(s) unión auriculoventricular común con defecto del tabique auriculoventricular especificado(a)(s)', 'category', false, false, 'CIE-11'),
('LA87.4Z', 'Unión auriculoventricular común con defecto del tabique auriculoventricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA87.Y', 'Otra anomalía congénita de una válvula auriculoventricular o tabique auriculoventricular', 'category', false, false, 'CIE-11'),
('LA87.Z', 'Anomalía congénita de una válvula auriculoventricular o tabique auriculoventricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA88', 'Anomalía congénita de un ventrículo o el tabique interventricular', 'category', false, false, 'CIE-11'),
('LA88.0', 'Obstrucción congénita del infundíbulo ventricular derecho', 'category', false, false, 'CIE-11'),
('LA88.1', 'Ventrículo derecho bicameral', 'category', false, false, 'CIE-11'),
('LA88.2', 'Tetralogía de Fallot', 'category', false, false, 'CIE-11'),
('LA88.20', 'Tetralogía de Fallot con síndrome de válvula pulmonar ausente', 'category', false, false, 'CIE-11'),
('LA88.21', 'Tetralogía de Fallot con atresia pulmonar', 'category', false, false, 'CIE-11'),
('LA88.22', 'Tetralogía de Fallot con atresia pulmonar y arterias colaterales sistémico-pulmonares', 'category', false, false, 'CIE-11'),
('LA88.2Y', 'Otra tetralogía de Fallot especificada', 'category', false, false, 'CIE-11'),
('LA88.2Z', 'Tetralogía de Fallot, sin especificación', 'category', false, false, 'CIE-11'),
('LA88.3', 'Obstrucción congénita del infundíbulo ventricular izquierdo', 'category', false, false, 'CIE-11'),
('LA88.4', 'Comunicación interventricular', 'category', false, false, 'CIE-11'),
('LA88.40', 'Comunicación interventricular en el músculo trabecular', 'category', false, false, 'CIE-11'),
('LA88.41', 'Comunicación interventricular perimembranosa', 'category', false, false, 'CIE-11'),
('LA88.42', 'Comunicación interventricular sin trascendencia hemodinámica', 'category', false, false, 'CIE-11'),
('LA88.4Y', 'Otra comunicación interventricular especificada', 'category', false, false, 'CIE-11'),
('LA88.4Z', 'Comunicación interventricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA88.Y', 'Otra anomalía congénita especificada de un ventrículo o el tabique interventricular', 'category', false, false, 'CIE-11'),
('LA88.Z', 'Anomalía congénita de un ventrículo o el tabique interventricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA89', 'Corazón funcionalmente univentricular', 'category', false, false, 'CIE-11'),
('LA89.0', 'Conexión auriculoventricular con doble entrada', 'category', false, false, 'CIE-11'),
('LA89.1', 'Atresia tricuspídea', 'category', false, false, 'CIE-11'),
('LA89.2', 'Atresia mitral', 'category', false, false, 'CIE-11'),
('LA89.3', 'Síndrome de hemicardio izquierdo hipoplásico', 'category', false, false, 'CIE-11'),
('LA89.Y', 'Otro corazón funcionalmente univentricular especificado', 'category', false, false, 'CIE-11'),
('LA89.Z', 'Corazón funcionalmente univentricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA8A', 'Anomalía congénita de una válvula ventriculoarterial o las regiones adyacentes', 'category', false, false, 'CIE-11'),
('LA8A.0', 'Anomalía congénita de la válvula pulmonar', 'category', false, false, 'CIE-11'),
('LA8A.00', 'Estenosis congénita de la válvula pulmonar', 'category', false, false, 'CIE-11'),
('LA8A.01', 'Insuficiencia congénita de la válvula pulmonar', 'category', false, false, 'CIE-11'),
('LA8A.0Y', 'Otra anomalía congénita especificada de la válvula pulmonar', 'category', false, false, 'CIE-11'),
('LA8A.0Z', 'Anomalía congénita de la válvula pulmonar, sin especificación', 'category', false, false, 'CIE-11'),
('LA8A.1', 'Atresia pulmonar congénita', 'category', false, false, 'CIE-11'),
('LA8A.10', 'Atresia de la válvula pulmonar con tabique ventricular intacto', 'category', false, false, 'CIE-11'),
('LA8A.1Y', 'Otra atresia pulmonar congénita especificada', 'category', false, false, 'CIE-11'),
('LA8A.1Z', 'Atresia pulmonar congénita, sin especificación', 'category', false, false, 'CIE-11'),
('LA8A.2', 'Anomalía congénita de la válvula aórtica', 'category', false, false, 'CIE-11'),
('LA8A.20', 'Estenosis congénita de la válvula aórtica', 'category', false, false, 'CIE-11'),
('LA8A.21', 'Insuficiencia congénita de la válvula aórtica', 'category', false, false, 'CIE-11'),
('LA8A.22', 'Válvula aórtica bicúspide', 'category', false, false, 'CIE-11'),
('LA8A.23', 'Atresia valvular aórtica', 'category', false, false, 'CIE-11'),
('LA8A.24', 'Válvula aórtica unicúspide', 'category', false, false, 'CIE-11'),
('LA8A.2Y', 'Otra anomalía congénita especificada de la válvula aórtica', 'category', false, false, 'CIE-11'),
('LA8A.2Z', 'Anomalía congénita de la válvula aórtica, sin especificación', 'category', false, false, 'CIE-11'),
('LA8A.3', 'Estenosis aórtica supravalvular congénita', 'category', false, false, 'CIE-11'),
('LA8A.4', 'Aneurisma de seno aórtico de Valsalva', 'category', false, false, 'CIE-11'),
('LA8A.5', 'Estenosis subaórtica congénita', 'category', false, false, 'CIE-11'),
('LA8A.6', 'Estenosis subpulmonar congénita', 'category', false, false, 'CIE-11'),
('LA8A.Y', 'Otra anomalía congénita especificada de una válvula ventriculoarterial o las regiones adyacentes', 'category', false, false, 'CIE-11'),
('LA8A.Z', 'Anomalía congénita de una válvula ventriculoarterial o las regiones adyacentes, sin especificación', 'category', false, false, 'CIE-11'),
('LA8B', 'Anomalía congénita de las grandes arterias, incluido el conducto arterioso', 'category', false, false, 'CIE-11'),
('LA8B.0', 'Ventana aortopulmonar congénita', 'category', false, false, 'CIE-11'),
('LA8B.1', 'Anomalía congénita del árbol arterial pulmonar', 'category', false, false, 'CIE-11'),
('LA8B.2', 'Anomalía congénita de la aorta o de sus ramas', 'category', false, false, 'CIE-11'),
('LA8B.21', 'Coartación aórtica', 'category', false, false, 'CIE-11'),
('LA8B.22', 'Cayado aórtico interrumpido', 'category', false, false, 'CIE-11'),
('LA8B.23', 'Anomalía congénita de la aorta torácica descendente o de la aorta abdominal', 'category', false, false, 'CIE-11'),
('LA8B.24', 'Anomalía congénita de la rama del arco aórtico', 'category', false, false, 'CIE-11'),
('LA8B.2Y', 'Otra anomalía congénita especificada de la aorta o de sus ramas', 'category', false, false, 'CIE-11'),
('LA8B.2Z', 'Anomalía congénita de la aorta o de sus ramas, sin especificación', 'category', false, false, 'CIE-11'),
('LA8B.3', 'Síndrome compresivo traqueoesofágico', 'category', false, false, 'CIE-11'),
('LA8B.4', 'Conducto arterioso persistente', 'category', false, false, 'CIE-11'),
('LA8B.Y', 'Otra anomalía congénita especificada de las grandes arterias, incluido el conducto arterioso', 'category', false, false, 'CIE-11'),
('LA8B.Z', 'Anomalía congénita de las grandes arterias, incluido el conducto arterioso, sin especificación', 'category', false, false, 'CIE-11'),
('LA8C', 'Anomalía congénita de arteria coronaria', 'category', false, false, 'CIE-11'),
('LA8C.0', 'Origen anómalo de arteria coronaria en el árbol arterial pulmonar', 'category', false, false, 'CIE-11'),
('LA8C.1', 'Origen aórtico anómalo o trayectoria anómala de una arteria coronaria', 'category', false, false, 'CIE-11'),
('LA8C.2', 'Fístula congénita de arteria coronaria', 'category', false, false, 'CIE-11'),
('LA8C.Y', 'Otra anomalía congénita especificada de las arterias coronarias', 'category', false, false, 'CIE-11'),
('LA8C.Z', 'Anomalía congénita de las arterias coronarias, sin especificación', 'category', false, false, 'CIE-11'),
('LA8D', 'Anomalía pericárdica congénita', 'category', false, false, 'CIE-11'),
('LA8E', 'Anomalía congénita del tabique interauricular', 'category', false, false, 'CIE-11'),
('LA8E.0', 'Agujero oval persistente', 'category', false, false, 'CIE-11'),
('LA8E.1', 'Comunicación interauricular en la fosa oval', 'category', false, false, 'CIE-11'),
('LA8E.2', 'Defecto del seno venoso', 'category', false, false, 'CIE-11'),
('LA8E.3', 'Comunicación interauricular a través del orificio del seno coronario', 'category', false, false, 'CIE-11'),
('LA8E.Y', 'Otra anomalía congénita especificada del tabique interauricular', 'category', false, false, 'CIE-11'),
('LA8E.Z', 'Anomalía congénita del tabique interauricular, sin especificación', 'category', false, false, 'CIE-11'),
('LA8F', 'Anomalía congénita de la aurícula derecha', 'category', false, false, 'CIE-11'),
('LA8G', 'Anomalía congénita de la aurícula izquierda', 'category', false, false, 'CIE-11'),
('LA8G.0', 'Aurícula izquierda dividida', 'category', false, false, 'CIE-11'),
('LA8G.Y', 'Otra anomalía congénita especificada de la aurícula izquierda', 'category', false, false, 'CIE-11'),
('LA8G.Z', 'Anomalía congénita de la aurícula izquierda, sin especificación', 'category', false, false, 'CIE-11'),
('LA8Y', 'Otra anomalía del desarrollo estructural especificada del corazón o de los grandes vasos', 'category', false, false, 'CIE-11'),
('LA8Z', 'Anomalía del desarrollo estructural del corazón o de los grandes vasos, sin especificación', 'category', false, false, 'CIE-11'),
('LA90', 'Anomalías estructurales del desarrollo del sistema vascular periférico', 'category', false, false, 'CIE-11'),
('LA90.0', 'Malformaciones capilares', 'category', false, false, 'CIE-11'),
('LA90.00', 'Telangiectasia hemorrágica hereditaria', 'category', false, false, 'CIE-11'),
('LA90.0Y', 'Otras malformaciones capilares especificadas', 'category', false, false, 'CIE-11'),
('LA90.0Z', 'Malformaciones capilares, sin especificación', 'category', false, false, 'CIE-11'),
('LA90.1', 'Malformaciones linfáticas', 'category', false, false, 'CIE-11'),
('LA90.10', 'Malformación linfática macroquística', 'category', false, false, 'CIE-11'),
('LA90.11', 'Malformación linfática microquística', 'category', false, false, 'CIE-11'),
('LA90.12', 'Malformaciones linfáticas en algunos sitios especificados', 'category', false, false, 'CIE-11'),
('LA90.13', 'Higroma quístico fetal', 'category', false, false, 'CIE-11'),
('LA90.1Y', 'Otras malformaciones linfáticas especificadas', 'category', false, false, 'CIE-11'),
('LA90.1Z', 'Malformaciones linfáticas, sin especificación', 'category', false, false, 'CIE-11'),
('LA90.2', 'Malformaciones venosas periféricas', 'category', false, false, 'CIE-11'),
('LA90.20', 'Aneurisma de la vena de Galeno', 'category', false, false, 'CIE-11'),
('LA90.21', 'Derivación portosistémica congénita', 'category', false, false, 'CIE-11'),
('LA90.2Y', 'Otras malformaciones venosas periféricas especificadas', 'category', false, false, 'CIE-11'),
('LA90.2Z', 'Malformaciones venosas periféricas, sin especificación', 'category', false, false, 'CIE-11'),
('LA90.3', 'Malformaciones arteriovenosas periféricas', 'category', false, false, 'CIE-11'),
('LA90.30', 'Fístula entre arteria hepática y vena porta', 'category', false, false, 'CIE-11'),
('LA90.31', 'Malformación arteriovenosa de vasos precerebrales', 'category', false, false, 'CIE-11'),
('LA90.32', 'Malformaciones arteriovenosas uterinas', 'category', false, false, 'CIE-11'),
('LA90.3Y', 'Otras malformaciones arteriovenosas periféricas especificadas', 'category', false, false, 'CIE-11'),
('LA90.3Z', 'Malformaciones arteriovenosas periféricas, sin especificación', 'category', false, false, 'CIE-11'),
('LA90.4', 'Malformaciones arteriales periféricas', 'category', false, false, 'CIE-11'),
('LA90.40', 'Estenosis congénita de la arteria renal', 'category', false, false, 'CIE-11'),
('LA90.41', 'Aneurisma precerebral congénito sin rotura', 'category', false, false, 'CIE-11'),
('LA90.42', 'Aneurisma cerebral congénito sin rotura', 'category', false, false, 'CIE-11'),
('LA90.4Y', 'Otras malformaciones arteriales periféricas especificadas', 'category', false, false, 'CIE-11'),
('LA90.4Z', 'Malformaciones arteriales periféricas, sin especificación', 'category', false, false, 'CIE-11'),
('LA90.5', 'Fístula arteriovenosa pulmonar', 'category', false, false, 'CIE-11'),
('LA90.Y', 'Otras anomalías especificadas del desarrollo estructural del sistema vascular periférico', 'category', false, false, 'CIE-11'),
('LA90.Z', 'Anomalías del desarrollo estructural del sistema vascular periférico, sin especificación', 'category', false, false, 'CIE-11'),
('LA9Y', 'Otras anomalías estructurales del desarrollo especificadas del sistema circulatorio', 'category', false, false, 'CIE-11'),
('LA9Z', 'Anomalías estructurales del desarrollo del sistema circulatorio, sin especificación', 'category', false, false, 'CIE-11'),
('LB00', 'Anomalías estructurales del desarrollo prenatal del diafragma', 'category', false, false, 'CIE-11'),
('LB00.0', 'Hernia diafragmática congénita', 'category', false, false, 'CIE-11'),
('LB00.1', 'Ausencia de diafragma', 'category', false, false, 'CIE-11'),
('LB00.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del diafragma', 'category', false, false, 'CIE-11'),
('LB00.Z', 'Anomalías estructurales del desarrollo prenatal del diafragma, sin especificación', 'category', false, false, 'CIE-11'),
('LB01', 'Onfalocele', 'category', false, false, 'CIE-11'),
('LB02', 'Gastrosquisis', 'category', false, false, 'CIE-11'),
('LB03', 'Anomalías estructurales del desarrollo prenatal del cordón umbilical', 'category', false, false, 'CIE-11'),
('LB03.0', 'Restos o quistes de conducto alantoideo', 'category', false, false, 'CIE-11'),
('LB03.1', 'arteria umbilical única', 'category', false, false, 'CIE-11'),
('LB03.Y', 'Otras anomalías estructurales especificadas del desarrollo prenatal del cordón umbilical', 'category', false, false, 'CIE-11'),
('LB03.Z', 'Anomalías estructurales del desarrollo prenatal del cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('LB0Y', 'Otras anomalías estructurales del desarrollo especificadas del diafragma, la pared abdominal o el cordón umbilical', 'category', false, false, 'CIE-11'),
('LB0Z', 'Anomalías estructurales del desarrollo del diafragma, la pared abdominal o el cordón umbilical, sin especificación', 'category', false, false, 'CIE-11'),
('LB10', 'Anomalías estructurales del desarrollo prenatal de las glándulas y conductos salivales', 'category', false, false, 'CIE-11'),
('LB11', 'Divertículo congénito de faringe', 'category', false, false, 'CIE-11'),
('LB12', 'Anomalías estructurales del desarrollo del esófago', 'category', false, false, 'CIE-11'),
('LB12.0', 'Membranas o anillos esofágicos congénitos', 'category', false, false, 'CIE-11'),
('LB12.1', 'Atresia del esófago', 'category', false, false, 'CIE-11'),
('LB12.10', 'Atresia de esófago con fístula esofagobronquial', 'category', false, false, 'CIE-11'),
('LB12.1Y', 'Otra atresia de esófago especificada', 'category', false, false, 'CIE-11'),
('LB12.1Z', 'Atresia del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('LB12.2', 'Fístula esofágica sin atresia', 'category', false, false, 'CIE-11'),
('LB12.3', 'Estenosis congénita de esófago', 'category', false, false, 'CIE-11'),
('LB12.4', 'Divertículo esofágico congénito.', 'category', false, false, 'CIE-11'),
('LB12.5', 'Dilatación congénita de esófago', 'category', false, false, 'CIE-11'),
('LB12.Y', 'Otras anomalías estructurales especificadas del desarrollo del esófago', 'category', false, false, 'CIE-11'),
('LB12.Z', 'Anomalías estructurales del desarrollo del esófago, sin especificación', 'category', false, false, 'CIE-11'),
('LB13', 'Anomalías estructurales del desarrollo del estómago', 'category', false, false, 'CIE-11'),
('LB13.0', 'Estenosis hipertrófica congénita del píloro', 'category', false, false, 'CIE-11'),
('LB13.1', 'Hernia hiatal congénita', 'category', false, false, 'CIE-11'),
('LB13.2', 'Membrana antral congénita', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;