BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XA5U78', 'Fosa posterior', 'category', false, false, 'CIE-11'),
('XA2SR4', 'Hueso etmoides', 'category', false, false, 'CIE-11'),
('XA6ZM9', 'Hueso frontal', 'category', false, false, 'CIE-11'),
('XA5JA2', 'Hueso occipital', 'category', false, false, 'CIE-11'),
('XA4RS9', 'Cóndilo occipital', 'category', false, false, 'CIE-11'),
('XA33W1', 'Occipucio', 'category', false, false, 'CIE-11'),
('XA2J87', 'Hueso parietal', 'category', false, false, 'CIE-11'),
('XA63R0', 'Hueso esfenoides', 'category', false, false, 'CIE-11'),
('XA9N34', 'Fosa pituitaria', 'category', false, false, 'CIE-11'),
('XA2P19', 'Hueso temporal', 'category', false, false, 'CIE-11'),
('XA1E15', 'Hueso petroso', 'category', false, false, 'CIE-11'),
('XA68N3', 'Mastoides', 'category', false, false, 'CIE-11'),
('XA8E69', 'Hueso orbital', 'category', false, false, 'CIE-11'),
('XA9XW3', 'Techo orbital', 'category', false, false, 'CIE-11'),
('XA7MW9', 'Piso orbital', 'category', false, false, 'CIE-11'),
('XA3Y16', 'Huesos faciales', 'category', false, false, 'CIE-11'),
('XA5CQ0', 'Hueso hioides', 'category', false, false, 'CIE-11'),
('XA6UV6', 'Cornete nasal inferior', 'category', false, false, 'CIE-11'),
('XA9GZ6', 'Hueso lagrimal', 'category', false, false, 'CIE-11'),
('XA4319', 'Hueso palatino', 'category', false, false, 'CIE-11'),
('XA14T2', 'Hueso vómer', 'category', false, false, 'CIE-11'),
('XA8N32', 'Hueso cigomático', 'category', false, false, 'CIE-11'),
('XA51B7', 'Mandíbula', 'category', false, false, 'CIE-11'),
('XA3B77', 'Borde alveolar del cuerpo de la mandíbula', 'category', false, false, 'CIE-11'),
('XA0M61', 'Ángulo de la mandíbula', 'category', false, false, 'CIE-11'),
('XA98M7', 'Proceso condilar de la mandíbula', 'category', false, false, 'CIE-11'),
('XA7919', 'Proceso subcondilar de la mandíbula', 'category', false, false, 'CIE-11'),
('XA24B3', 'Proceso coronoide de la mandíbula', 'category', false, false, 'CIE-11'),
('XA5969', 'Ramas de la mandíbula', 'category', false, false, 'CIE-11'),
('XA8JR9', 'Sínfisis mandibular', 'category', false, false, 'CIE-11'),
('XA0NC8', 'Maxilar inferior', 'category', false, false, 'CIE-11'),
('XA7VK5', 'Maxilar', 'category', false, false, 'CIE-11'),
('XA8E16', 'Hueso nasal', 'category', false, false, 'CIE-11'),
('XA88P5', 'Mandíbula, no especificada', 'category', false, false, 'CIE-11'),
('XA6EQ1', 'Huesos del oído medio', 'category', false, false, 'CIE-11'),
('XA4D04', 'Yunque', 'category', false, false, 'CIE-11'),
('XA5DS8', 'Martillo', 'category', false, false, 'CIE-11'),
('XA3WA4', 'Estribo', 'category', false, false, 'CIE-11'),
('XA5J55', 'Columna vertebral', 'category', false, false, 'CIE-11'),
('XA7MS2', 'Vértebra', 'category', false, false, 'CIE-11'),
('XA9ZW8', 'Vértebra cervical', 'category', false, false, 'CIE-11'),
('XA2XE8', 'Atlas', 'category', false, false, 'CIE-11'),
('XA0KQ4', 'Arco posterior de la primera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA1304', 'Masa lateral de la primera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA17N0', 'Axis', 'category', false, false, 'CIE-11'),
('XA5W02', 'Apófisis odontoides', 'category', false, false, 'CIE-11'),
('XA2W05', 'Tercera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA51V4', 'Arco de la tercera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA4UV1', 'Cuerpo de la tercera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA8CG0', 'Apófisis de la tercera vértebra cervical', 'category', false, false, 'CIE-11'),
('XA3RE9', 'Cuarta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA24X7', 'Arco de la cuarta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA3GT0', 'Cuerpo de la cuarta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA75V3', 'Apófisis de la cuarta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA9C12', 'Quinta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA1PJ5', 'Arco de la quinta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA1BS2', 'Cuerpo de la quinta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA2FY7', 'Apófisis de la quinta vértebra cervical', 'category', false, false, 'CIE-11'),
('XA5S79', 'Sexta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA8W16', 'Arco de la sexta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA9Q12', 'Cuerpo de la sexta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA60Z0', 'Apófisis de la sexta vertebra cervical', 'category', false, false, 'CIE-11'),
('XA34U8', 'Séptima vertebra cervical', 'category', false, false, 'CIE-11'),
('XA05M5', 'Arco de la séptima vertebra cervical', 'category', false, false, 'CIE-11'),
('XA1JS3', 'Cuerpo de la séptima vertebra cervical', 'category', false, false, 'CIE-11'),
('XA91D7', 'Apófisis de la séptima vértebra cervical', 'category', false, false, 'CIE-11'),
('XA6E88', 'vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3F93', 'Primera vertebra torácica', 'category', false, false, 'CIE-11'),
('XA7UP5', 'arco de la primera vertebra torácica', 'category', false, false, 'CIE-11'),
('XA8PH0', 'cuerpo de la primera vertebra torácica', 'category', false, false, 'CIE-11'),
('XA1AX4', 'apófisis de la primera vértebra torácica', 'category', false, false, 'CIE-11'),
('XA8QS0', 'Segunda vértebra torácica', 'category', false, false, 'CIE-11'),
('XA2VV9', 'arco de la segunda vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3Z42', 'cuerpo de la segunda vértebra torácica', 'category', false, false, 'CIE-11'),
('XA6T61', 'apófisis de la segunda vértebra torácica', 'category', false, false, 'CIE-11'),
('XA1Z15', 'Tercera vértebra torácica', 'category', false, false, 'CIE-11'),
('XA2SM3', 'arco de la tercera vértebra torácica', 'category', false, false, 'CIE-11'),
('XA35A0', 'cuerpo de la tercera vértebra torácica', 'category', false, false, 'CIE-11'),
('XA41U9', 'Apófisis de la tercera vértebra torácica', 'category', false, false, 'CIE-11'),
('XA0C31', 'Cuarta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA22W3', 'arco de la cuarta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3J42', 'cuerpo de la cuarta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA1WL4', 'apófisis de la cuarta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3PH5', 'Quinta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA28A7', 'arco de la quinta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA8W59', 'cuerpo de la quinta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA0449', 'apófisis de la quinta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA45S2', 'Sexta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA29X2', 'arco de la sexta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA0YY2', 'cuerpo de la sexta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA1R53', 'apófisis de la sexta vértebra torácica', 'category', false, false, 'CIE-11'),
('XA59Y3', 'Septima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA54G1', 'arco de la septima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA62Y3', 'cuerpode la septima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA1CQ7', 'apófisis de la septima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA8NQ5', 'Octava vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3PL7', 'arco de la octava vértebra torácica', 'category', false, false, 'CIE-11'),
('XA5JX9', 'cuerpo de la octava vértebra torácica', 'category', false, false, 'CIE-11'),
('XA1SD8', 'apófisis de la octava vértebra torácica', 'category', false, false, 'CIE-11'),
('XA3E70', 'Novena vértebra torácica', 'category', false, false, 'CIE-11'),
('XA9N69', 'arco de la novena vértebra torácica', 'category', false, false, 'CIE-11'),
('XA2X21', 'cuerpo de la novena vértebra torácica', 'category', false, false, 'CIE-11'),
('XA5SW1', 'apófisis de la novena vértebra torácica', 'category', false, false, 'CIE-11'),
('XA0AV7', 'Decima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA7LF7', 'arco de la décima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA6VP6', 'cuerpo de la décima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA7122', 'apófisis de la décima vértebra torácica', 'category', false, false, 'CIE-11'),
('XA7T69', 'Undécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA98R9', 'arco de la undécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA91J0', 'cuerpo de la undécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA92Q6', 'apófisis de la undécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA69W5', 'Duodécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA15N3', 'arco de la duodécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA1401', 'cuerpo de la duodécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA2D62', 'apófisis de la duodécima vertebra torácica', 'category', false, false, 'CIE-11'),
('XA0D60', 'vértebra lumbar', 'category', false, false, 'CIE-11'),
('XA3291', 'Primera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA8AX7', 'arco de la primera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA9E61', 'cuerpo de la primera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA4U01', 'apófisis de la primera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA2GH9', 'Segunda vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA24M1', 'arco de la segunda vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA5079', 'cuerpo de la segunda vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA52T1', 'apófisis de la segunda vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA3N97', 'Tercera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA3G24', 'arco de la tercera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA0TL0', 'cuerpo de la tercera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA80X7', 'apófisis de la tercera vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA9A53', 'Cuarta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA7CH7', 'arco de la cuarta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA4145', 'cuerpo de la cuarta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA38A4', 'apófisis de la cuarta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA9641', 'Quinta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA2JV2', 'arco de la quinta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA5886', 'cuerpo de la quinta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA4PS3', 'apófisis de la quinta vertebra lumbar', 'category', false, false, 'CIE-11'),
('XA14W3', 'Sacro', 'category', false, false, 'CIE-11'),
('XA4V28', 'coxis', 'category', false, false, 'CIE-11'),
('XA02R1', 'Disco intervertebral o espacio', 'category', false, false, 'CIE-11'),
('XA8D30', 'Discos o espacios cervicales', 'category', false, false, 'CIE-11'),
('XA9Z06', 'Disco o espacio intervertebral cervical C1-C2', 'category', false, false, 'CIE-11'),
('XA18M2', 'Disco o espacio intervertebral cervical C2-C3', 'category', false, false, 'CIE-11'),
('XA94K2', 'Disco o espacio intervertebral cervical C3-C4', 'category', false, false, 'CIE-11'),
('XA3623', 'Disco o espacio intervertebral cervical C4-C5', 'category', false, false, 'CIE-11'),
('XA1X49', 'Disco o espacio intervertebral cervical C5-C6', 'category', false, false, 'CIE-11'),
('XA16L1', 'Disco o espacio intervertebral cervical C6-C7', 'category', false, false, 'CIE-11'),
('XA2SG0', 'Disco cervicotorácico o espacio C7-T1', 'category', false, false, 'CIE-11'),
('XA1N54', 'Disco o espacio torácico', 'category', false, false, 'CIE-11'),
('XA4722', 'Disco o espacio intervertebral torácico T1-T2', 'category', false, false, 'CIE-11'),
('XA6KQ8', 'Disco o espacio intervertebral torácico T2-T3', 'category', false, false, 'CIE-11'),
('XA6CX2', 'Disco o espacio intervertebral torácico T3-T4', 'category', false, false, 'CIE-11'),
('XA0NE8', 'Disco o espacio intervertebral torácico T4-T5', 'category', false, false, 'CIE-11'),
('XA7PD1', 'Disco o espacio intervertebral torácico T5-T6', 'category', false, false, 'CIE-11'),
('XA4TP2', 'Disco o espacio intervertebral torácico T6-T7', 'category', false, false, 'CIE-11'),
('XA7117', 'Disco o espacio intervertebral torácico T7-T8', 'category', false, false, 'CIE-11'),
('XA9PW9', 'Disco o espacio intervertebral torácico T8-T9', 'category', false, false, 'CIE-11'),
('XA8E13', 'Disco o espacio intervertebral torácico T9-T10', 'category', false, false, 'CIE-11'),
('XA6HY9', 'Disco o espacio intervertebral torácico T10-T11', 'category', false, false, 'CIE-11'),
('XA5LG2', 'Disco o espacio intervertebral torácico T11-T12', 'category', false, false, 'CIE-11'),
('XA97A4', 'Disco o espacio intervertebral torácolumbar T12-L1', 'category', false, false, 'CIE-11'),
('XA54S5', 'Discos o espacios lumbares', 'category', false, false, 'CIE-11'),
('XA7RD5', 'Disco o espacio intervertebral lumbar L1-L2', 'category', false, false, 'CIE-11'),
('XA8DG2', 'Disco o espacio intervertebral lumbar L2-L3', 'category', false, false, 'CIE-11'),
('XA1F44', 'Disco o espacio intervertebral lumbar L3-L4', 'category', false, false, 'CIE-11'),
('XA2N96', 'Disco o espacio intervertebral lumbar L4-L5', 'category', false, false, 'CIE-11'),
('XA54R2', 'Disco o espacio intervertebral lumbosacro L5-S1', 'category', false, false, 'CIE-11'),
('XA2Y58', 'Disco intervertebral', 'category', false, false, 'CIE-11'),
('XA8WM9', 'Núcleo pulposo', 'category', false, false, 'CIE-11'),
('XA10M1', 'Anillo fibroso', 'category', false, false, 'CIE-11'),
('XA5VB6', 'Huesos del tórax', 'category', false, false, 'CIE-11'),
('XA5TK7', 'Costilla', 'category', false, false, 'CIE-11'),
('XA98Q1', 'Primera costilla', 'category', false, false, 'CIE-11'),
('XA7XY2', 'Segunda costilla', 'category', false, false, 'CIE-11'),
('XA2U21', 'Tercera costilla', 'category', false, false, 'CIE-11'),
('XA4SQ6', 'Cuarta costilla', 'category', false, false, 'CIE-11'),
('XA31L8', 'Quinta costilla', 'category', false, false, 'CIE-11'),
('XA63Z2', 'Sexta costilla', 'category', false, false, 'CIE-11'),
('XA2WC3', 'Séptima costilla', 'category', false, false, 'CIE-11'),
('XA9WQ3', 'Octava costilla', 'category', false, false, 'CIE-11'),
('XA31V8', 'Novena costilla', 'category', false, false, 'CIE-11'),
('XA54R4', 'Décima costilla', 'category', false, false, 'CIE-11'),
('XA3VH4', 'Undécima costilla', 'category', false, false, 'CIE-11'),
('XA6W52', 'Duodécima costilla', 'category', false, false, 'CIE-11'),
('XA6NB3', 'esternón', 'category', false, false, 'CIE-11'),
('XA3M45', 'cuerpo del esternón', 'category', false, false, 'CIE-11'),
('XA0K13', 'manubrio', 'category', false, false, 'CIE-11'),
('XA2RB7', 'Xifoides', 'category', false, false, 'CIE-11'),
('XA4N47', 'Huesos de la Pelvis', 'category', false, false, 'CIE-11'),
('XA8Y23', 'Pelvis', 'category', false, false, 'CIE-11'),
('XA5FT5', 'Ilión', 'category', false, false, 'CIE-11'),
('XA4743', 'Cresta ilíaca', 'category', false, false, 'CIE-11'),
('XA5L47', 'Isquión', 'category', false, false, 'CIE-11'),
('XA82W3', 'Pubis', 'category', false, false, 'CIE-11'),
('XA1XZ3', 'Rama púbica superior', 'category', false, false, 'CIE-11'),
('XA4VB9', 'Rama púbica inferior', 'category', false, false, 'CIE-11'),
('XA6Z32', 'Acetábulo', 'category', false, false, 'CIE-11'),
('XA4TM1', 'Esqueleto periférico', 'category', false, false, 'CIE-11'),
('XA7R53', 'Huesos de la Extremidad Superior', 'category', false, false, 'CIE-11'),
('XA2AL0', 'Huesos de la cintura escapular', 'category', false, false, 'CIE-11'),
('XA6384', 'clavícula', 'category', false, false, 'CIE-11'),
('XA76N8', 'extremo esternal de la clavícula', 'category', false, false, 'CIE-11'),
('XA4PT6', 'Eje de la clavícula', 'category', false, false, 'CIE-11'),
('XA09P2', 'extremo acromial de la clavícula', 'category', false, false, 'CIE-11'),
('XA53X6', 'escápula', 'category', false, false, 'CIE-11'),
('XA2HS8', 'cuello de la escápula', 'category', false, false, 'CIE-11'),
('XA1216', 'cavidad glenoidea de la escápula', 'category', false, false, 'CIE-11'),
('XA2Y48', 'Apófisis coracoides de la escápula', 'category', false, false, 'CIE-11'),
('XA3664', 'Acromion', 'category', false, false, 'CIE-11'),
('XA2XL4', 'Húmero', 'category', false, false, 'CIE-11'),
('XA4VY5', 'cabeza del húmero', 'category', false, false, 'CIE-11'),
('XA0XN0', 'cuello anatómico del húmero', 'category', false, false, 'CIE-11'),
('XA6FR2', 'cuello quirúrgico del húmero', 'category', false, false, 'CIE-11'),
('XA7144', 'tuberosidad mayor del húmero', 'category', false, false, 'CIE-11'),
('XA72X2', 'tuberosidad menor del húmero', 'category', false, false, 'CIE-11'),
('XA4RN8', 'eje del húmero', 'category', false, false, 'CIE-11'),
('XA3RE0', 'Cóndilo del húmero', 'category', false, false, 'CIE-11'),
('XA11M8', 'Cóndilo del húmero', 'category', false, false, 'CIE-11'),
('XA9LK4', 'Troclea del húmero', 'category', false, false, 'CIE-11'),
('XA6EF8', 'Epicóndilo lateral del humero', 'category', false, false, 'CIE-11'),
('XA4097', 'Epicóndilo medial del humero', 'category', false, false, 'CIE-11'),
('XA3WG1', 'Radio', 'category', false, false, 'CIE-11'),
('XA2N25', 'Cabeza radial', 'category', false, false, 'CIE-11'),
('XA0ZF7', 'Cuello radial', 'category', false, false, 'CIE-11'),
('XA35U4', 'eje del radio', 'category', false, false, 'CIE-11'),
('XA6YE5', 'Surco radial', 'category', false, false, 'CIE-11'),
('XA3MH2', 'apófisis estiloides del radio', 'category', false, false, 'CIE-11'),
('XA4X32', 'Extremo inferior del radio no especificado de otra manera', 'category', false, false, 'CIE-11'),
('XA76U7', 'Epífisis superior del radio no especificada en otra parte', 'category', false, false, 'CIE-11'),
('XA5007', 'Cúbito', 'category', false, false, 'CIE-11'),
('XA0NS5', 'apófisis coronoides del cúbito', 'category', false, false, 'CIE-11'),
('XA0725', 'Epífisis inferior del cúbito no especificada en otra parte', 'category', false, false, 'CIE-11'),
('XA5VA1', 'Proceso olécranon del cúbito', 'category', false, false, 'CIE-11'),
('XA8U33', 'Diáfisis del cúbito', 'category', false, false, 'CIE-11'),
('XA05C5', 'apófisis estiloides del cúbito', 'category', false, false, 'CIE-11'),
('XA6SV9', 'Epífisis proximal del cúbito no especificada en otra parte', 'category', false, false, 'CIE-11'),
('XA09H2', 'Huesos del carpo', 'category', false, false, 'CIE-11'),
('XA7480', 'hueso escafoide', 'category', false, false, 'CIE-11'),
('XA8E71', 'Polo distal del escafoides', 'category', false, false, 'CIE-11'),
('XA1GV4', 'tercio distal del hueso escafoides', 'category', false, false, 'CIE-11'),
('XA3ZG5', 'tercio medio del hueso escafoides', 'category', false, false, 'CIE-11'),
('XA5ZE5', 'tercio proximal del hueso escafoides', 'category', false, false, 'CIE-11'),
('XA30C8', 'hueso semilunar', 'category', false, false, 'CIE-11'),
('XA4A64', 'hueso piramidal', 'category', false, false, 'CIE-11'),
('XA8SZ6', 'hueso pisiforme', 'category', false, false, 'CIE-11'),
('XA7XM2', 'hueso trapecio', 'category', false, false, 'CIE-11'),
('XA9DH2', 'hueso trapezoide', 'category', false, false, 'CIE-11'),
('XA06T2', 'hueso grande', 'category', false, false, 'CIE-11'),
('XA8488', 'Hueso ganchoso', 'category', false, false, 'CIE-11'),
('XA97A0', 'Gancho del hueso ganchoso', 'category', false, false, 'CIE-11'),
('XA0GJ4', 'Túnel carpiano', 'category', false, false, 'CIE-11'),
('XA22M5', 'Base de otro hueso carpiano', 'category', false, false, 'CIE-11'),
('XA9640', 'Cuello de otro hueso carpiano', 'category', false, false, 'CIE-11'),
('XA5TX9', 'Eje de otro hueso carpiano', 'category', false, false, 'CIE-11'),
('XA3YX4', 'Hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA58X4', 'Primer metacarpiano', 'category', false, false, 'CIE-11'),
('XA12D2', 'Cabeza del primer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA8J87', 'Cuello del primer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA5N95', 'Eje del primer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA2P67', 'Base del primer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA5HE0', 'Segundo metacarpiano', 'category', false, false, 'CIE-11'),
('XA93C5', 'Cabeza del segundo hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA8KU0', 'Cuello del segundo hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA4RC8', 'Eje del segundo hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA37V2', 'Base del segundo hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA7J93', 'Tercer metacarpiano', 'category', false, false, 'CIE-11'),
('XA6442', 'Cabeza de tercer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA50H4', 'Cuello del tercer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA8BP2', 'Eje del tercer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA8NK6', 'Base del tercer hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA9KB7', 'Cuarto metacarpiano', 'category', false, false, 'CIE-11'),
('XA8X42', 'Cabeza del cuarto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA9NT7', 'Cuello del cuarto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA4CP7', 'Eje del cuarto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA3ZF8', 'Base del cuarto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA88S1', 'Quinto metacarpiano', 'category', false, false, 'CIE-11'),
('XA3Z46', 'Cabeza del quinto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA16Y6', 'Cuello del quinto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA92G8', 'Eje del quinto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA65Y7', 'Base del quinto hueso metacarpiano', 'category', false, false, 'CIE-11'),
('XA3PA7', 'Falanges de la mano', 'category', false, false, 'CIE-11'),
('XA0HH1', 'falange proximal de la mano', 'category', false, false, 'CIE-11'),
('XA25U2', 'Falange proximal del dedo índice', 'category', false, false, 'CIE-11'),
('XA6ET0', 'Falange proximal del dedo medio', 'category', false, false, 'CIE-11'),
('XA9MR0', 'Falange proximal del dedo anular', 'category', false, false, 'CIE-11'),
('XA73Q6', 'Falange proximal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA0903', 'Falange proximal del pulgar', 'category', false, false, 'CIE-11'),
('XA89G7', 'Falange media de la mano', 'category', false, false, 'CIE-11'),
('XA3JL6', 'Falange media del dedo índice', 'category', false, false, 'CIE-11'),
('XA5910', 'Falange media del dedo medio', 'category', false, false, 'CIE-11'),
('XA8N14', 'Falange media del dedo anular', 'category', false, false, 'CIE-11'),
('XA6HX0', 'Falange media del dedo meñique', 'category', false, false, 'CIE-11'),
('XA7LS3', 'falange distal de la mano', 'category', false, false, 'CIE-11'),
('XA54X0', 'Falange distal del dedo índice', 'category', false, false, 'CIE-11'),
('XA8NR0', 'Falange distal del dedo medio', 'category', false, false, 'CIE-11'),
('XA51S6', 'Falange distal del dedo anular', 'category', false, false, 'CIE-11'),
('XA32G6', 'Falange distal del dedo meñique', 'category', false, false, 'CIE-11'),
('XA70H5', 'Falange distal del pulgar', 'category', false, false, 'CIE-11'),
('XA5D87', 'Hueso del dedo, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA95Q5', 'Hueso del pulgar, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('XA2T04', 'Huesos de la extremidad inferior', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;