BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('MG24.0Y', 'Otro temor especificado al cáncer', 'category', false, false, 'CIE-11'),
('MG24.0Z', 'Temor al cáncer, sin especificación', 'category', false, false, 'CIE-11'),
('MG24.1', 'Temor al virus de la inmunodeficiencia humana', 'category', false, false, 'CIE-11'),
('MG24.2', 'Temor a una enfermedad hematológica', 'category', false, false, 'CIE-11'),
('MG24.3', 'Temor a la enfermedad digestiva', 'category', false, false, 'CIE-11'),
('MG24.4', 'Temor a la enfermedad de los ojos', 'category', false, false, 'CIE-11'),
('MG24.5', 'Temor a la enfermedad cardíaca', 'category', false, false, 'CIE-11'),
('MG24.6', 'Temor a la hipertensión arterial', 'category', false, false, 'CIE-11'),
('MG24.7', 'Miedo a la enfermedad cardiovascular', 'category', false, false, 'CIE-11'),
('MG24.8', 'Temor a la enfermedad del aparato locomotor', 'category', false, false, 'CIE-11'),
('MG24.9', 'Temor a la enfermedad neurológica', 'category', false, false, 'CIE-11'),
('MG24.A', 'Temor a la enfermedad respiratoria', 'category', false, false, 'CIE-11'),
('MG24.B', 'Temor a la enfermedad endocrina, metabólica o nutricional', 'category', false, false, 'CIE-11'),
('MG24.C', 'Temor a la enfermedad urinaria', 'category', false, false, 'CIE-11'),
('MG24.D', 'Temor a las complicaciones del embarazo', 'category', false, false, 'CIE-11'),
('MG24.E', 'Temor a la enfermedad de transmisión sexual femenina', 'category', false, false, 'CIE-11'),
('MG24.F', 'Temor a la enfermedad de la mama o de los órganos genitales femeninos', 'category', false, false, 'CIE-11'),
('MG24.G', 'Temor a la enfermedad de transmisión sexual masculina', 'category', false, false, 'CIE-11'),
('MG24.H', 'Temor a la enfermedad de los órganos genitales masculinos', 'category', false, false, 'CIE-11'),
('MG24.J', 'Temor a la enfermedad mental', 'category', false, false, 'CIE-11'),
('MG24.Y', 'Temor de otra enfermedad especificada', 'category', false, false, 'CIE-11'),
('MG24.Z', 'Temor a la enfermedad, sin especificación', 'category', false, false, 'CIE-11'),
('MG25', 'Sentirse enfermo', 'category', false, false, 'CIE-11'),
('MG26', 'Fiebre de otro origen o de origen desconocido', 'category', false, false, 'CIE-11'),
('MG27', 'Hemorragia, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG28', 'Hipotermia, no asociada a una temperatura ambiental baja', 'category', false, false, 'CIE-11'),
('MG29', 'Edema', 'category', false, false, 'CIE-11'),
('MG29.0', 'Edema localizado', 'category', false, false, 'CIE-11'),
('MG29.00', 'Edema del tobillo', 'category', false, false, 'CIE-11'),
('MG29.01', 'Edema de las piernas', 'category', false, false, 'CIE-11'),
('MG29.02', 'Fosas en el labio', 'category', false, false, 'CIE-11'),
('MG29.0Y', 'Otro edema localizado especificado', 'category', false, false, 'CIE-11'),
('MG29.1', 'Edema generalizado', 'category', false, false, 'CIE-11'),
('MG29.10', 'Edema por aumento de la presión capilar', 'category', false, false, 'CIE-11'),
('MG29.1Y', 'Otro edema generalizado especificado', 'category', false, false, 'CIE-11'),
('MG29.2', 'Edema infeccioso', 'category', false, false, 'CIE-11'),
('MG29.3', 'Edema con fóvea', 'category', false, false, 'CIE-11'),
('MG29.Z', 'Edema, sin especificación', 'category', false, false, 'CIE-11'),
('MG2A', 'Disminución de la capacidad intrínseca asociada al envejecimiento', 'category', false, false, 'CIE-11'),
('MG30', 'Dolor crónico', 'category', false, false, 'CIE-11'),
('MG30.0', 'Dolor crónico primario', 'category', false, false, 'CIE-11'),
('MG30.00', 'Dolor visceral crónico primario', 'category', false, false, 'CIE-11'),
('MG30.01', 'Dolor generalizado crónico', 'category', false, false, 'CIE-11'),
('MG30.02', 'Dolor músculo esquelético crónico primario', 'category', false, false, 'CIE-11'),
('MG30.03', 'Cefalea crónica o dolor bucofacial crónico primario', 'category', false, false, 'CIE-11'),
('MG30.04', 'Síndrome de dolor regional complejo', 'category', false, false, 'CIE-11'),
('MG30.0Y', 'Otro dolor crónico primario especificado', 'category', false, false, 'CIE-11'),
('MG30.0Z', 'Dolor crónico primario, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.1', 'Dolor crónico por cáncer', 'category', false, false, 'CIE-11'),
('MG30.10', 'Dolor crónico del cáncer', 'category', false, false, 'CIE-11'),
('MG30.11', 'Dolor crónico posterior al tratamiento de cáncer', 'category', false, false, 'CIE-11'),
('MG30.1Y', 'Otro dolor crónico especificado por cáncer', 'category', false, false, 'CIE-11'),
('MG30.1Z', 'Dolor crónico por cáncer, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.2', 'Dolor crónico posquirúrgico o postraumático', 'category', false, false, 'CIE-11'),
('MG30.20', 'Dolor crónico postraumático', 'category', false, false, 'CIE-11'),
('MG30.21', 'Dolor posquirúrgico crónico', 'category', false, false, 'CIE-11'),
('MG30.2Y', 'Otro dolor crónico especificado posquirúrgico o postraumático', 'category', false, false, 'CIE-11'),
('MG30.2Z', 'Dolor crónico posquirúrgico o postraumatico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.3', 'Dolor musculoesquelético secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.30', 'Dolor musculoesquelético secundario crónico por inflamación persistente', 'category', false, false, 'CIE-11'),
('MG30.31', 'Dolor musculoesquelético secundario crónico asociado a alteraciones estructurales', 'category', false, false, 'CIE-11'),
('MG30.32', 'Dolor musculoesquelético secundario crónico por enfermedad del sistema nervioso', 'category', false, false, 'CIE-11'),
('MG30.3Y', 'Otro dolor musculoesquelético secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.3Z', 'Dolor musculoesquelético secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.4', 'Dolor visceral secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.40', 'Dolor visceral crónico por factores mecánicos', 'category', false, false, 'CIE-11'),
('MG30.41', 'Dolor visceral crónico por mecanismos vasculares', 'category', false, false, 'CIE-11'),
('MG30.42', 'Dolor visceral crónico por inflamación persistente', 'category', false, false, 'CIE-11'),
('MG30.4Y', 'Otro dolor visceral secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.4Z', 'Dolor visceral secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.5', 'Dolor neuropático crónico', 'category', false, false, 'CIE-11'),
('MG30.50', 'Dolor neuropático central crónico', 'category', false, false, 'CIE-11'),
('MG30.51', 'Dolor neuropático periférico crónico', 'category', false, false, 'CIE-11'),
('MG30.5Y', 'Otro dolor neuropático crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.5Z', 'Dolor neuropático crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.6', 'Cefalea o dolor bucofacial secundario crónico', 'category', false, false, 'CIE-11'),
('MG30.61', 'Dolor dental crónico', 'category', false, false, 'CIE-11'),
('MG30.62', 'Dolor orofacial neuropático crónico', 'category', false, false, 'CIE-11'),
('MG30.63', 'Dolor de cabeza u orofacial asociado con trastornos temporomandibulares secundarios crónicos', 'category', false, false, 'CIE-11'),
('MG30.64', 'Cefalea crónica o dolor orofacial asociado a trastornos de la homeostasis o su tratamiento no farmacológico', 'category', false, false, 'CIE-11'),
('MG30.65', 'Cefalea crónica o dolor orofacial asociado con trastorno vascular craneal o cervical', 'category', false, false, 'CIE-11'),
('MG30.66', 'Cefalea crónica o dolor orofacial asociado a trastorno intracraneal no vascular', 'category', false, false, 'CIE-11'),
('MG30.67', 'Cefalea crónica asociada a una sustancia o a su abstinencia', 'category', false, false, 'CIE-11'),
('MG30.6Y', 'Otra cefalea o dolor bucofacial secundario crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.6Z', 'Cefalea o dolor bucofacial secundario crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG30.Y', 'Otro dolor crónico especificado', 'category', false, false, 'CIE-11'),
('MG30.Z', 'Dolor crónico, sin especificación', 'category', false, false, 'CIE-11'),
('MG31', 'Dolor agudo', 'category', false, false, 'CIE-11'),
('MG31.0', 'Dolor agudo en la cara, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG31.1', 'Cefalea aguda, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG31.2', 'Dolor postoperatorio agudo, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG31.Y', 'Otro dolor agudo especificado', 'category', false, false, 'CIE-11'),
('MG31.Z', 'Dolor agudo, sin especificación', 'category', false, false, 'CIE-11'),
('MG3Z', 'Dolor, sin especificación', 'category', false, false, 'CIE-11'),
('MG40', 'Choque', 'category', false, false, 'CIE-11'),
('MG40.0', 'Choque cardiogénico', 'category', false, false, 'CIE-11'),
('MG40.1', 'Choque hipovolémico', 'category', false, false, 'CIE-11'),
('MG40.Y', 'Otro choque especificado', 'category', false, false, 'CIE-11'),
('MG40.Z', 'Choque, sin especificación', 'category', false, false, 'CIE-11'),
('MG41', 'Trastornos del sueño', 'category', false, false, 'CIE-11'),
('MG42', 'Somnolencia, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('MG43', 'Síntomas y signos relativos a la ingesta de alimentos o líquidos', 'category', false, false, 'CIE-11'),
('MG43.0', 'Polidipsia', 'category', false, false, 'CIE-11'),
('MG43.1', 'Hiperfagia', 'category', false, false, 'CIE-11'),
('MG43.2', 'Abulia', 'category', false, false, 'CIE-11'),
('MG43.3', 'Dificultades de la alimentación', 'category', false, false, 'CIE-11'),
('MG43.30', 'Problema con la alimentación del lactante', 'category', false, false, 'CIE-11'),
('MG43.31', 'Problema de alimentación del niño', 'category', false, false, 'CIE-11'),
('MG43.32', 'Problema con la alimentación del adulto', 'category', false, false, 'CIE-11'),
('MG43.3Z', 'Dificultades de la alimentación, sin especificación', 'category', false, false, 'CIE-11'),
('MG43.4', 'Ingesta insuficiente de alimentos o de agua por negligencia personal', 'category', false, false, 'CIE-11'),
('MG43.40', 'Rechazo al alimento, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG43.41', 'Rechazo de líquidos, no clasificado en otra parte', 'category', false, false, 'CIE-11'),
('MG43.4Y', 'Otra ingesta insuficiente de alimentos o de agua especificada, por negligencia personal', 'category', false, false, 'CIE-11'),
('MG43.4Z', 'Ingesta insuficiente de alimentos o de agua por negligencia personal, sin especificación', 'category', false, false, 'CIE-11'),
('MG43.5', 'Adelgazamiento excesivo', 'category', false, false, 'CIE-11'),
('MG43.6', 'Aumento de peso excesivo', 'category', false, false, 'CIE-11'),
('MG43.7', 'Anorexia', 'category', false, false, 'CIE-11'),
('MG43.8', 'Disminución del apetito', 'category', false, false, 'CIE-11'),
('MG43.9', 'Aumento del apetito', 'category', false, false, 'CIE-11'),
('MG43.Y', 'Otros síntomas y signos especificados relativos a la alimentación e ingesta de líquidos', 'category', false, false, 'CIE-11'),
('MG44', 'Síntomas propios del lactante', 'category', false, false, 'CIE-11'),
('MG44.0', 'Llanto excesivo en el lactante', 'category', false, false, 'CIE-11'),
('MG44.1', 'Falta del desarrollo fisiológico normal esperado', 'category', false, false, 'CIE-11'),
('MG44.10', 'Retraso del desarrollo del niño', 'category', false, false, 'CIE-11'),
('MG44.11', 'Retraso ponderal en un lactante o niño', 'category', false, false, 'CIE-11'),
('MG44.12', 'Niño de talla baja', 'category', false, false, 'CIE-11'),
('MG44.13', 'Retraso constitucional del crecimiento y la pubertad', 'category', false, false, 'CIE-11'),
('MG44.14', 'Estatura baja familiar', 'category', false, false, 'CIE-11'),
('MG44.1Y', 'Otra falta del desarrollo fisiológico normal esperado especificado', 'category', false, false, 'CIE-11'),
('MG44.1Z', 'Falta del desarrollo fisiológico normal esperado, sin especificación', 'category', false, false, 'CIE-11'),
('MG44.Y', 'Otros síntomas propios del lactante especificados', 'category', false, false, 'CIE-11'),
('MG44.Z', 'Síntomas propios del lactante, sin especificación', 'category', false, false, 'CIE-11'),
('MG45', 'Síncope y colapso', 'category', false, false, 'CIE-11'),
('MG45.0', 'Síncope cardíaco', 'category', false, false, 'CIE-11'),
('MG45.Y', 'Otro síncope y colapso especificado', 'category', false, false, 'CIE-11'),
('MG45.Z', 'Síncope y colapso, sin especificación', 'category', false, false, 'CIE-11'),
('MG46', 'Síndrome de respuesta inflamatoria sistémica de origen no infeccioso', 'category', false, false, 'CIE-11'),
('MG47', 'Toxicosis sin otra especificación', 'category', false, false, 'CIE-11'),
('MG48', 'Causas de enfermedad desconocidas o no especificadas', 'category', false, false, 'CIE-11'),
('MG49', 'Resaca', 'category', false, false, 'CIE-11'),
('MG4A', 'Insuficiencia multiorgánica', 'category', false, false, 'CIE-11'),
('MG4Y', 'Otros síntomas generales especificados', 'category', false, false, 'CIE-11'),
('MG50', 'Detección de bacterias gramnegativas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG50.0', 'Acinetobacter baumannii resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.00', 'Acinetobacter baumannii resistente a las tetraciclinas', 'category', false, false, 'CIE-11'),
('MG50.01', 'Acinetobacter baumannii resistente a los aminoglucósidos', 'category', false, false, 'CIE-11'),
('MG50.02', 'Acinetobacter baumannii resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.03', 'Acinetobacter baumannii resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.0Y', 'Acinetobacter baumannii resistente a otro antibiótico', 'category', false, false, 'CIE-11'),
('MG50.0Z', 'Acinetobacter baumannii resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.1', 'Campylobacter resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.10', 'Campylobacter resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.1Y', 'Campylobacter resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.1Z', 'Campylobacter resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.2', 'Escherichia coli resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.20', 'Escherichia coli resistente a las sulfonamidas o al trimetoprim', 'category', false, false, 'CIE-11'),
('MG50.21', 'Escherichia coli resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.22', 'Escherichia coli resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.23', 'Escherichia coli resistente a las cefalosporinas de cuarta generación', 'category', false, false, 'CIE-11'),
('MG50.24', 'Escherichia coli resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.25', 'Escherichia coli resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.26', 'Escherichia coli resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG50.27', 'Escherichia coli productora de betalactamasas de espectro extendido', 'category', false, false, 'CIE-11'),
('MG50.2Y', 'Escherichia coli resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.2Z', 'Escherichia coli resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.3', 'Haemophilus influenzae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.30', 'Haemophilus influenzae resistente a la ampicilina', 'category', false, false, 'CIE-11'),
('MG50.3Y', 'Haemophilus influenza resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.3Z', 'Haemophilus influenzae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.4', 'Helicobacter pylori resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.40', 'Helicobacter pylori resistente a la claritromicina', 'category', false, false, 'CIE-11'),
('MG50.4Y', 'Helicobacter pylori resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.4Z', 'Helicobacter pylori resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.5', 'Klebsiella pneumoniae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.50', 'Klebsiella pneumoniae resistente a las sulfonamidas o al trimetoprim', 'category', false, false, 'CIE-11'),
('MG50.51', 'Klebsiella pneumoniae resistente a las fluoroquinonas', 'category', false, false, 'CIE-11'),
('MG50.52', 'Klebsiella pneumoniae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.53', 'Klebsiella pneumoniae resistente a las cefalosporinas de cuarta generación', 'category', false, false, 'CIE-11'),
('MG50.54', 'Klebsiella pneumoniae resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.55', 'Klebsiella pneumoniae resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.56', 'Klebsiella pneumoniae productora de betalactamasas de espectro extendido', 'category', false, false, 'CIE-11'),
('MG50.5Y', 'Klebsiella pneumoniae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.5Z', 'Klebsiella pneumoniae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.6', 'Neisseria gonorrhoeae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.60', 'Neisseria gonorrhoeae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.61', 'Neisseria gonorrhoeae resistente a los macrólidos', 'category', false, false, 'CIE-11'),
('MG50.62', 'Neisseria gonorrhoeae resistente al aminociclitol', 'category', false, false, 'CIE-11'),
('MG50.63', 'Neisseria gonorrhoeae resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.64', 'Neisseria gonorrhoeae resistente a los aminoglucósidos', 'category', false, false, 'CIE-11'),
('MG50.6Y', 'Neisseria gonorrhoeae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.6Z', 'Neisseria gonorrhoeae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.7', 'Neisseria meningitidis resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.70', 'Neisseria meningitidis resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG50.7Y', 'Neisseria meningitidis resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.7Z', 'Neisseria meningitidis resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.8', 'Pseudomonas aeruginosa resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.80', 'Pseudomonas aeruginosa resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.81', 'Pseudomonas aeruginosa resistente a las polimixinas', 'category', false, false, 'CIE-11'),
('MG50.8Y', 'Pseudomonas aeruginosa resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.8Z', 'Pseudomonas aeruginosa resistente a os antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.9', 'Salmonella resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.90', 'Salmonella resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.91', 'Salmonella resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.92', 'Salmonella resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.9Y', 'Salmonella resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.9Z', 'Salmonella resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.A', 'Shigella resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.A0', 'Shigella resistente a los carbapenémicos', 'category', false, false, 'CIE-11'),
('MG50.A1', 'Shigella resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.A2', 'Shigella resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.A3', 'Shigella resistente a los macrólidos', 'category', false, false, 'CIE-11'),
('MG50.AY', 'Shigella resistente a otro antibiótico', 'category', false, false, 'CIE-11'),
('MG50.AZ', 'Shigella resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.B', 'Vibrio resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG50.B0', 'Vibrio resistente a las fluoroquinolonas', 'category', false, false, 'CIE-11'),
('MG50.BY', 'Vibrio resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.BZ', 'Vibrio resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.C', 'Otras enterobacterias resistentes a antibióticos', 'category', false, false, 'CIE-11'),
('MG50.C0', 'Otras enterobacterias resistentes a carbapenem', 'category', false, false, 'CIE-11'),
('MG50.C1', 'Otras enterobacterias resistentes a cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG50.CY', 'Enterobacteriaceae resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG50.CZ', 'Enterobacteriaceae resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG50.Y', 'Otra detección de bacterias gramnegativas resistentes a los antimicrobianos especificada', 'category', false, false, 'CIE-11'),
('MG50.Z', 'Detección de bacterias gramnegativas resistente a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51', 'Detección de bacterias grampositivas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG51.0', 'Staphylococcus aureus resistente a antibióticos', 'category', false, false, 'CIE-11'),
('MG51.00', 'Staphylococcus aureus resistente a la meticilina', 'category', false, false, 'CIE-11'),
('MG51.01', 'Staphylococcus aureus resistente a la vancomicina', 'category', false, false, 'CIE-11'),
('MG51.02', 'Staphylococcus aureus resistente a los betalactámicos estables frente a las penicilinasas', 'category', false, false, 'CIE-11'),
('MG51.0Y', 'Staphylococcus aureus resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG51.0Z', 'Staphylococcus aureus resistente a antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51.1', 'Streptococcus pneumoniae resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG51.10', 'Streptococcus pneumoniae resistente a las penicilinas', 'category', false, false, 'CIE-11'),
('MG51.11', 'Streptococcus pneumoniae resistente a la sulfonamida y la trimetoprima', 'category', false, false, 'CIE-11'),
('MG51.12', 'Streptococcus pneumoniae resistente a las cefalosporinas de tercera generación', 'category', false, false, 'CIE-11'),
('MG51.1Y', 'Streptococcus pneumoniae resistente a otros antibióticos', 'category', false, false, 'CIE-11'),
('MG51.1Z', 'Streptococcus pneumoniae resistente a antibiótico no especificado', 'category', false, false, 'CIE-11'),
('MG51.2', 'Enterococcus resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG51.20', 'Enterococcus resistente a la vancomicina', 'category', false, false, 'CIE-11'),
('MG51.2Y', 'Enterococcus resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG51.2Z', 'Enterococcus resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG51.Y', 'Otra detección de bacterias grampositivas especificadas resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG51.Z', 'Detección de bacterias grampositivas resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG52', 'Detección de bacterias, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG52.0', 'Mycobacterium resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG52.00', 'Mycobacterium tuberculosis multirresistente a farmacos', 'category', false, false, 'CIE-11'),
('MG52.01', 'Mycobacterium no tuberculoso resistente a los antibióticos', 'category', false, false, 'CIE-11'),
('MG52.02', 'Mycobacterium tuberculosis extensamente resistente a los medicamentos', 'category', false, false, 'CIE-11'),
('MG52.0Y', 'Mycobacterium resistente a otro antibiótico especificado', 'category', false, false, 'CIE-11'),
('MG52.0Z', 'Mycobacterium resistente a los antibióticos, sin especificación', 'category', false, false, 'CIE-11'),
('MG52.Y', 'Otra detección de bacterias especificadas, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG52.Z', 'Detección de bacterias, ni gramnegativas ni grampositivas, resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG53', 'Detección de virus resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG53.0', 'Virus de la inmunodeficiencia humana resistente al tratamiento antirretroviral', 'category', false, false, 'CIE-11'),
('MG53.Y', 'Detección de otro virus especificado resistente a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG53.Z', 'Detección de virus resistente a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG54', 'Detección de hongos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55', 'Detección de parásitos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55.0', 'Plasmodium falciparum resistente a la artemisinina', 'category', false, false, 'CIE-11'),
('MG55.Y', 'Otra detección especificada de parásitos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG55.Z', 'Detección de parásitos resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG56', 'Detección de microorganismo resistente a varios antimicrobianos de otro tipo', 'category', false, false, 'CIE-11'),
('MG5Y', 'Detección de otros microorganismos resistentes a los antimicrobianos', 'category', false, false, 'CIE-11'),
('MG5Z', 'Detección de microorganismos resistentes a los antimicrobianos, sin especificación', 'category', false, false, 'CIE-11'),
('MG60', 'Concentración anormal de enzimas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG61', 'Concentración anormal de hormonas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG62', 'Concentración anormal de drogas, medicamentos y sustancias biológicas en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG63', 'Concentración anormal de sustancias de procedencia principalmente no medicinal en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG64', 'Resultados inmunológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG65', 'Resultado microbiológico anormal en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG66', 'Resultados citopatológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG67', 'Resultados histopatológicos anormales en muestras de otros órganos, aparatos y tejidos', 'category', false, false, 'CIE-11'),
('MG6Y', 'Otros resultados anormales especificados en muestras de otros órganos, aparatos y tejidos especificados', 'category', false, false, 'CIE-11'),
('MG70', 'Resultados anormales en pruebas de diagnóstico por la imagen, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71', 'Resultados de laboratorio anormales, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71.0', 'Resultados anormales en el cribado neonatal', 'category', false, false, 'CIE-11'),
('MG71.Y', 'Otros resultados de laboratorio anormales especificados, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG71.Z', 'Resultados de laboratorio anormales, no clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MG72', 'Resultados anormales en estudios funcionales de otros órganos y aparatos', 'category', false, false, 'CIE-11'),
('MG7Y', 'Otros resultados anormales especificados, no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('MG7Z', 'Resultados anormales, no clasificados en otra parte, sin especificación', 'category', false, false, 'CIE-11'),
('MH10', 'Muerte cerebral', 'category', false, false, 'CIE-11'),
('MH11', 'Síndrome de muerte súbita del lactante', 'category', false, false, 'CIE-11'),
('MH11.0', 'Síndrome de muerte súbita del lactante con mención de una autopsia', 'category', false, false, 'CIE-11'),
('MH11.1', 'Síndrome de muerte súbita del lactante sin autopsia', 'category', false, false, 'CIE-11'),
('MH11.Z', 'Síndrome de muerte súbita del lactante, sin especificación', 'category', false, false, 'CIE-11'),
('MH12', 'Otra muerte súbita, de causa desconocida', 'category', false, false, 'CIE-11'),
('MH12.0', 'Muerte instantánea', 'category', false, false, 'CIE-11'),
('MH12.1', 'Muerte que ocurre menos de 24 horas después del comienzo de los síntomas, sin otra explicación', 'category', false, false, 'CIE-11'),
('MH12.Y', 'Otra muerte repentina especificada, de causa desconocida', 'category', false, false, 'CIE-11'),
('MH13', 'Muerte sin asistencia', 'category', false, false, 'CIE-11'),
('MH14', 'Otras causas de muerte mal definidas o no especificadas', 'category', false, false, 'CIE-11'),
('MH15', 'Muerte súbita inesperada en paciente con epilepsia', 'category', false, false, 'CIE-11'),
('MH2Y', 'Otros síntomas, signos o hallazgos clínicos especificados no clasificados en otra parte', 'category', false, false, 'CIE-11'),
('NA00', 'Traumatismo superficial en la cabeza', 'category', false, false, 'CIE-11'),
('NA00.0', 'Traumatismo superficial en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.00', 'Excoriación en el cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.01', 'Contusión de cuero cabelludo', 'category', false, false, 'CIE-11'),
('NA00.02', 'Cuerpo extraño superficial en el cuero cabelludo', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;