BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('8D86', 'Hiperactividad del sistema nervioso autónomo', 'category', false, false, 'CIE-11'),
('8D87', 'Disautonomía por un trastorno neurodegenerativo especificado', 'category', false, false, 'CIE-11'),
('8D87.0', 'Atrofia multisistémica', 'category', false, false, 'CIE-11'),
('8D87.00', 'Atrofia multisistémica de tipo cerebeloso', 'category', false, false, 'CIE-11'),
('8D87.01', 'Atrofia multisistémica de tipo parkinsoniano', 'category', false, false, 'CIE-11'),
('8D87.0Y', 'Otra atrofia multisistémica especificada', 'category', false, false, 'CIE-11'),
('8D87.0Z', 'Atrofia multiosistémica, sin especificación', 'category', false, false, 'CIE-11'),
('8D87.Y', 'Otra disautonomía especificada por un trastorno neurodegenerativo especificado', 'category', false, false, 'CIE-11'),
('8D88', 'Neuropatías autonómicas', 'category', false, false, 'CIE-11'),
('8D88.0', 'Neuropatía autónoma por alteraciones de los canales de sodio', 'category', false, false, 'CIE-11'),
('8D88.1', 'Neuropatía autonómica por diabetes mellitus', 'category', false, false, 'CIE-11'),
('8D88.2', 'Neuropatía autonómica inmunomediada', 'category', false, false, 'CIE-11'),
('8D88.3', 'Disautonomía provocada por sustancias tóxicas', 'category', false, false, 'CIE-11'),
('8D88.4', 'Neuropatía autonómica en las enfermedades metabólicas y endocrinas', 'category', false, false, 'CIE-11'),
('8D88.Y', 'Otras neuropatías autonómicas especificadas', 'category', false, false, 'CIE-11'),
('8D88.Z', 'Neuropatías autonómicas, sin especificación', 'category', false, false, 'CIE-11'),
('8D89', 'Intolerancia ortostática', 'category', false, false, 'CIE-11'),
('8D89.0', 'Síncope reflejo', 'category', false, false, 'CIE-11'),
('8D89.1', 'Síncope por insuficiencia autónoma', 'category', false, false, 'CIE-11'),
('8D89.2', 'Síndrome de taquicardia ortostática postural', 'category', false, false, 'CIE-11'),
('8D89.3', 'Insuficiencia barorrefleja', 'category', false, false, 'CIE-11'),
('8D89.Y', 'Otra intolerancia ortostática especificada', 'category', false, false, 'CIE-11'),
('8D89.Z', 'Intolerancia ortostática, sin especificación', 'category', false, false, 'CIE-11'),
('8D8A', 'Disautonomías segmentarias o focales', 'category', false, false, 'CIE-11'),
('8D8A.1', 'Síndrome de Horner', 'category', false, false, 'CIE-11'),
('8D8A.2', 'Anisocoria episódica', 'category', false, false, 'CIE-11'),
('8D8A.Y', 'Otras disautonomías segmentarias o focales especificadas', 'category', false, false, 'CIE-11'),
('8D8A.Z', 'Disautonomías segmentarias o focales, sin especificación', 'category', false, false, 'CIE-11'),
('8D8B', 'Trastornos de la neurotransmisión sináptica autónoma', 'category', false, false, 'CIE-11'),
('8D8C', 'Disreflexia autónoma', 'category', false, false, 'CIE-11'),
('8D8D', 'hipoglucemia inconsciente', 'category', false, false, 'CIE-11'),
('8D8Y', 'Otros trastornos especificados del sistema nervioso autónomo', 'category', false, false, 'CIE-11'),
('8D8Z', 'Trastornos del sistema nervioso autónomo, sin especificación', 'category', false, false, 'CIE-11'),
('8E00', 'Enfermedad de Creutzfeldt-Jakob esporádica', 'category', false, false, 'CIE-11'),
('8E01', 'Enfermedad adquirida por priones', 'category', false, false, 'CIE-11'),
('8E01.0', 'Enfermedad de Creutzfeldt-Jakob adquirida iatrogénicamente', 'category', false, false, 'CIE-11'),
('8E01.1', 'Kuru', 'category', false, false, 'CIE-11'),
('8E01.2', 'Enfermedad de Creutzfeldt-Jakob variante', 'category', false, false, 'CIE-11'),
('8E01.3', 'Otra enfermedad de Creutzfeldt-Jakob adquirida', 'category', false, false, 'CIE-11'),
('8E01.Z', 'Enfermedad adquirida por priones, sin especificación', 'category', false, false, 'CIE-11'),
('8E02', 'Enfermedades genéticas por priones', 'category', false, false, 'CIE-11'),
('8E02.0', 'Enfermedad de Creutzfeldt-Jakob genética', 'category', false, false, 'CIE-11'),
('8E02.1', 'Síndrome de Gerstmann-Sträussler-Scheinker', 'category', false, false, 'CIE-11'),
('8E02.2', 'Insomnio familiar letal', 'category', false, false, 'CIE-11'),
('8E02.3', 'Otras enfermedades genéticas por priones', 'category', false, false, 'CIE-11'),
('8E02.Y', 'Otras enfermedades genéticas por priones especificadas', 'category', false, false, 'CIE-11'),
('8E02.Z', 'Enfermedades genéticas por priones, sin especificación', 'category', false, false, 'CIE-11'),
('8E03', 'Prionopatía con sensibilidad variable a las proteasas', 'category', false, false, 'CIE-11'),
('8E0Y', 'Otras enfermedades humanas por priones especificadas', 'category', false, false, 'CIE-11'),
('8E0Z', 'Enfermedades humanas por priones, sin especificación', 'category', false, false, 'CIE-11'),
('8E20', 'Estado vegetativo persistente', 'category', false, false, 'CIE-11'),
('8E21', 'Estado vegetativo permanente', 'category', false, false, 'CIE-11'),
('8E22', 'Estado de conciencia mínima', 'category', false, false, 'CIE-11'),
('8E22.0', 'Estado de conciencia mínima plus', 'category', false, false, 'CIE-11'),
('8E22.1', 'Estado de conciencia mínima sin reactividad a estímulos verbales', 'category', false, false, 'CIE-11'),
('8E22.Y', 'Otro estado de conciencia mínima especificado', 'category', false, false, 'CIE-11'),
('8E22.Z', 'Estado de conciencia mínima, sin especificación', 'category', false, false, 'CIE-11'),
('8E2Y', 'Otros trastornos especificados de la conciencia', 'category', false, false, 'CIE-11'),
('8E2Z', 'Trastornos de la conciencia, sin especificación', 'category', false, false, 'CIE-11'),
('8E40', 'Trastornos de las meninges excepto las infecciones', 'category', false, false, 'CIE-11'),
('8E40.0', 'Meningitis neoplásica', 'category', false, false, 'CIE-11'),
('8E40.1', 'Meningitis química', 'category', false, false, 'CIE-11'),
('8E40.2', 'Meningitis inflamatoria', 'category', false, false, 'CIE-11'),
('8E40.3', 'Aracnoiditis', 'category', false, false, 'CIE-11'),
('8E40.Y', 'Otros trastornos especificados de las meninges excepto las infecciones', 'category', false, false, 'CIE-11'),
('8E40.Z', 'Trastornos de las meninges excepto las infecciones, sin especificación', 'category', false, false, 'CIE-11'),
('8E41', 'Paquimeningitis', 'category', false, false, 'CIE-11'),
('8E41.0', 'Paquimeningitis por infección', 'category', false, false, 'CIE-11'),
('8E41.1', 'Paquimeningitis hipertrófica idiopática', 'category', false, false, 'CIE-11'),
('8E41.Y', 'Otra paquimeningitis especificada', 'category', false, false, 'CIE-11'),
('8E41.Z', 'Paquimeningitis, sin especificación', 'category', false, false, 'CIE-11'),
('8E42', 'Siderosis superficial del sistema nervioso', 'category', false, false, 'CIE-11'),
('8E43', 'Trastornos del dolor', 'category', false, false, 'CIE-11'),
('8E43.0', 'Dolor neuropático', 'category', false, false, 'CIE-11'),
('8E43.00', 'Síndrome del miembro fantasma', 'category', false, false, 'CIE-11'),
('8E43.0Y', 'Otro dolor neuropático especificado', 'category', false, false, 'CIE-11'),
('8E43.0Z', 'Dolor neuropático, sin especificación', 'category', false, false, 'CIE-11'),
('8E43.Y', 'Otros trastornos del dolor especificados', 'category', false, false, 'CIE-11'),
('8E43.Z', 'Trastornos del dolor, sin especificación', 'category', false, false, 'CIE-11'),
('8E44', 'Daño cerebral postanóxico', 'category', false, false, 'CIE-11'),
('8E45', 'Síndrome de enclaustramiento', 'category', false, false, 'CIE-11'),
('8E46', 'Síndrome de Reye', 'category', false, false, 'CIE-11'),
('8E47', 'Encefalopatía, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8E48', 'Encefalitis, no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('8E49', 'Síndrome de fatiga posviral', 'category', false, false, 'CIE-11'),
('8E4A', 'Neuropatías paraneoplásicas o autoinmunitarias', 'category', false, false, 'CIE-11'),
('8E4A.0', 'Trastornos paraneoplásicos o autoinmunitarios del sistema nervioso central, el encéfalo o la médula espinal', 'category', false, false, 'CIE-11'),
('8E4A.1', 'Trastornos autoinmunitarios o paraneoplásicos del sistema nervioso autónomo o periférico', 'category', false, false, 'CIE-11'),
('8E4A.2', 'Trastornos paraneoplásicos o autoinmunitarios de la transmisión neuromuscular', 'category', false, false, 'CIE-11'),
('8E4A.3', 'Trastornos autoinmunitarios o paraneoplásicos del músculo', 'category', false, false, 'CIE-11'),
('8E4A.Y', 'Otras neuropatías paraneoplásicas o autoinmunitarias especificadas', 'category', false, false, 'CIE-11'),
('8E4A.Z', 'Neuropatías paraneoplásicas o autoinmunitarias, sin especificación', 'category', false, false, 'CIE-11'),
('8E60', 'Fuga tras una derivación ventricular', 'category', false, false, 'CIE-11'),
('8E61', 'Lesión del sistema nervioso tras irradiación', 'category', false, false, 'CIE-11'),
('8E61.0', 'Lesión cerebral inducida por radiación', 'category', false, false, 'CIE-11'),
('8E61.1', 'Irradiación de la médula espinal', 'category', false, false, 'CIE-11'),
('8E61.Z', 'Lesión del sistema nervioso tras irradiación, sin especificación', 'category', false, false, 'CIE-11'),
('8E62', 'Meningitis tras un procedimiento', 'category', false, false, 'CIE-11'),
('8E63', 'Encefalopatía tras bombeo', 'category', false, false, 'CIE-11'),
('8E64', 'Infartos cerebrales multifocales', 'category', false, false, 'CIE-11'),
('8E66', 'Hipotensión intracraneana debida a punción lumbar', 'category', false, false, 'CIE-11'),
('8E7Y', 'Otras enfermedades especificadas del sistema nervioso', 'category', false, false, 'CIE-11'),
('8E7Z', 'Enfermedades del sistema nervioso, sin especificación', 'category', false, false, 'CIE-11'),
('9A00', 'Posición anómala congénita de los párpados', 'category', false, false, 'CIE-11'),
('9A00.0', 'Distopia cantal', 'category', false, false, 'CIE-11'),
('9A00.1', 'Telecanto', 'category', false, false, 'CIE-11'),
('9A00.Y', 'Otra posición anómala congénita especificada de los párpados', 'category', false, false, 'CIE-11'),
('9A00.Z', 'Posición anómala congénita de los párpados, sin especificación', 'category', false, false, 'CIE-11'),
('9A01', 'Trastornos infecciosos del párpado', 'category', false, false, 'CIE-11'),
('9A01.0', 'Celulitis preseptal', 'category', false, false, 'CIE-11'),
('9A01.1', 'Absceso del párpado', 'category', false, false, 'CIE-11'),
('9A01.2', 'Orzuelo', 'category', false, false, 'CIE-11'),
('9A01.20', 'Orzuelo externo', 'category', false, false, 'CIE-11'),
('9A01.21', 'Orzuelo interno', 'category', false, false, 'CIE-11'),
('9A01.2Z', 'Orzuelo, sin especificación', 'category', false, false, 'CIE-11'),
('9A01.3', 'Blefaritis infecciosa', 'category', false, false, 'CIE-11'),
('9A01.4', 'Infestación del párpado', 'category', false, false, 'CIE-11'),
('9A01.Y', 'Otros trastornos infecciosos especificados del párpado', 'category', false, false, 'CIE-11'),
('9A01.Z', 'Trastornos infecciosos del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A02', 'Trastornos inflamatorios del párpado', 'category', false, false, 'CIE-11'),
('9A02.0', 'Chalación', 'category', false, false, 'CIE-11'),
('9A02.00', 'Chalación externo', 'category', false, false, 'CIE-11'),
('9A02.01', 'Chalación interno', 'category', false, false, 'CIE-11'),
('9A02.0Z', 'Chalación, sin especificación', 'category', false, false, 'CIE-11'),
('9A02.1', 'Blefaritis posterior', 'category', false, false, 'CIE-11'),
('9A02.2', 'Conjuntivitis leñosa', 'category', false, false, 'CIE-11'),
('9A02.4', 'Disfunción de las glándulas de Meibomio', 'category', false, false, 'CIE-11'),
('9A02.Y', 'Otros trastornos inflamatorios especificados del párpado', 'category', false, false, 'CIE-11'),
('9A02.Z', 'Trastornos inflamatorios del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A03', 'Posición anómala adquirida del párpado', 'category', false, false, 'CIE-11'),
('9A03.0', 'Blefaroptosis', 'category', false, false, 'CIE-11'),
('9A03.00', 'Síndrome de Marcus-Gunn', 'category', false, false, 'CIE-11'),
('9A03.01', 'Blefaroptosis mecánica', 'category', false, false, 'CIE-11'),
('9A03.02', 'Blefaroptosis miógena', 'category', false, false, 'CIE-11'),
('9A03.03', 'Blefaroptosis paralítica', 'category', false, false, 'CIE-11'),
('9A03.0Y', 'Otra blefaroptosis especificada', 'category', false, false, 'CIE-11'),
('9A03.0Z', 'Blefaroptosis, sin especificación', 'category', false, false, 'CIE-11'),
('9A03.1', 'Entropión del párpado', 'category', false, false, 'CIE-11'),
('9A03.10', 'Entropión cicatricial del párpado', 'category', false, false, 'CIE-11'),
('9A03.11', 'Entropión mecánico del párpado', 'category', false, false, 'CIE-11'),
('9A03.12', 'Entropión senil del párpado', 'category', false, false, 'CIE-11'),
('9A03.13', 'Entropión espástico del párpado', 'category', false, false, 'CIE-11'),
('9A03.1Y', 'Otro entropión especificado del párpado', 'category', false, false, 'CIE-11'),
('9A03.1Z', 'Entropión del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A03.2', 'Ectropión del párpado', 'category', false, false, 'CIE-11'),
('9A03.20', 'Ectropión cicatricial del párpado', 'category', false, false, 'CIE-11'),
('9A03.21', 'Ectropión mecánico del párpado', 'category', false, false, 'CIE-11'),
('9A03.22', 'Ectropión senil del párpado', 'category', false, false, 'CIE-11'),
('9A03.23', 'Ectropión espástico del párpado', 'category', false, false, 'CIE-11'),
('9A03.24', 'Síndrome del párpado laxo', 'category', false, false, 'CIE-11'),
('9A03.2Y', 'Otro ectropión especificado del párpado', 'category', false, false, 'CIE-11'),
('9A03.2Z', 'Ectropión del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A03.3', 'Retracción parpebral', 'category', false, false, 'CIE-11'),
('9A03.4', 'Lagoftalmos', 'category', false, false, 'CIE-11'),
('9A03.40', 'Lagoftalmos cicatricial', 'category', false, false, 'CIE-11'),
('9A03.41', 'Lagoftalmos mecánico', 'category', false, false, 'CIE-11'),
('9A03.42', 'Lagoftalmos paralítico', 'category', false, false, 'CIE-11'),
('9A03.4Y', 'Otro lagoftalmos especificado', 'category', false, false, 'CIE-11'),
('9A03.4Z', 'Lagoftalmos, sin especificación', 'category', false, false, 'CIE-11'),
('9A03.5', 'Dermatocalasia del párpado', 'category', false, false, 'CIE-11'),
('9A03.Y', 'Otra posición anómala adquirida especificada del párpado', 'category', false, false, 'CIE-11'),
('9A03.Z', 'Posición anómala adquirida del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A04', 'Trastornos adquiridos de las pestañas', 'category', false, false, 'CIE-11'),
('9A04.0', 'Triquiasis sin entropión', 'category', false, false, 'CIE-11'),
('9A04.1', 'Madarosis del párpado o de la zona periocular', 'category', false, false, 'CIE-11'),
('9A04.Y', 'Otros trastornos adquiridos especificados de las pestañas', 'category', false, false, 'CIE-11'),
('9A04.Z', 'Trastornos adquiridos de las pestañas, sin especificación', 'category', false, false, 'CIE-11'),
('9A05', 'Trastornos del movimiento del párpado', 'category', false, false, 'CIE-11'),
('9A05.0', 'Mioquimia del párpado', 'category', false, false, 'CIE-11'),
('9A05.1', 'Apraxia del párpado', 'category', false, false, 'CIE-11'),
('9A05.Y', 'Otros trastornos del movimiento especificados del párpado', 'category', false, false, 'CIE-11'),
('9A05.Z', 'Trastornos del movimiento del párpado, sin especificación', 'category', false, false, 'CIE-11'),
('9A06', 'Algunos trastornos especificados del párpado', 'category', false, false, 'CIE-11'),
('9A06.0', 'Afectación del párpado por dermatosis no clasificada en otra parte', 'category', false, false, 'CIE-11'),
('9A06.1', 'Vitiligo del párpado o de la zona periocular', 'category', false, false, 'CIE-11'),
('9A06.2', 'Simbléfaron adquirido', 'category', false, false, 'CIE-11'),
('9A06.3', 'Cicatriz traumática del párpado', 'category', false, false, 'CIE-11'),
('9A06.4', 'Xantelasma del párpado', 'category', false, false, 'CIE-11'),
('9A06.5', 'Deformidad del surco lagrimal', 'category', false, false, 'CIE-11'),
('9A06.6', 'Deformidad de surco hundido', 'category', false, false, 'CIE-11'),
('9A06.7', 'Dermatitis o eccema de los párpados', 'category', false, false, 'CIE-11'),
('9A06.70', 'Eccema atópico de los párpados', 'category', false, false, 'CIE-11'),
('9A06.71', 'Dermatitis seborreica de los párpados', 'category', false, false, 'CIE-11'),
('9A06.72', 'Blefaroconjuntivitis de contacto alérgica', 'category', false, false, 'CIE-11'),
('9A06.7Y', 'Otra dermatitis especificada o eccema de los párpados', 'category', false, false, 'CIE-11'),
('9A06.7Z', 'Dermatitis o eccema de los párpados, sin especificación', 'category', false, false, 'CIE-11'),
('9A06.8', 'Blefarocalasia', 'category', false, false, 'CIE-11'),
('9A06.Y', 'Otros trastornos especificados del párpado', 'category', false, false, 'CIE-11'),
('9A0Y', 'Otros trastornos especificados del párpado o de la zona periocular', 'category', false, false, 'CIE-11'),
('9A0Z', 'Trastornos del párpado o de la zona periocular, sin especificación', 'category', false, false, 'CIE-11'),
('9A10', 'Trastornos de la glándula lagrimal', 'category', false, false, 'CIE-11'),
('9A10.0', 'Infecciones de glándula lagrimal', 'category', false, false, 'CIE-11'),
('9A10.1', 'Síndrome inflamatorio orbitario', 'category', false, false, 'CIE-11'),
('9A10.2', 'Lesión linfoepitelial benigna de glándula lagrimal', 'category', false, false, 'CIE-11'),
('9A10.3', 'Hiperlagrimación', 'category', false, false, 'CIE-11'),
('9A10.4', 'Hipolagrimación', 'category', false, false, 'CIE-11'),
('9A10.Y', 'Otros trastornos especificados de la glándula lagrimal', 'category', false, false, 'CIE-11'),
('9A10.Z', 'Trastornos de la glándula lagrimal, sin especificación', 'category', false, false, 'CIE-11'),
('9A11', 'Trastornos del sistema de drenaje lagrimal', 'category', false, false, 'CIE-11'),
('9A11.0', 'Eversión del punto lagrimal', 'category', false, false, 'CIE-11'),
('9A11.1', 'Canaliculitis', 'category', false, false, 'CIE-11'),
('9A11.2', 'Dacriocistitis', 'category', false, false, 'CIE-11'),
('9A11.3', 'Conjuntivocalasia', 'category', false, false, 'CIE-11'),
('9A11.4', 'Estenosis del punto lagrimal', 'category', false, false, 'CIE-11'),
('9A11.5', 'Estenosis canalicular nasolagrimal', 'category', false, false, 'CIE-11'),
('9A11.6', 'Dacriolito', 'category', false, false, 'CIE-11'),
('9A11.7', 'Estenosis del saco nasolagrimal', 'category', false, false, 'CIE-11'),
('9A11.8', 'Obstrucción del conducto nasolagrimal', 'category', false, false, 'CIE-11'),
('9A11.Y', 'Otros trastornos especificados del sistema de drenaje lagrimal', 'category', false, false, 'CIE-11'),
('9A11.Z', 'Trastornos del sistema de drenaje lagrimal, sin especificación', 'category', false, false, 'CIE-11'),
('9A1Y', 'Otros trastornos especificados del aparato lagrimal', 'category', false, false, 'CIE-11'),
('9A1Z', 'Trastornos del aparato lagrimal, sin especificación', 'category', false, false, 'CIE-11'),
('9A20', 'Desplazamiento del globo ocular', 'category', false, false, 'CIE-11'),
('9A20.0', 'Desplazamiento axial del globo ocular', 'category', false, false, 'CIE-11'),
('9A20.00', 'Desplazamiento del globo ocular hacia fuera', 'category', false, false, 'CIE-11'),
('9A20.01', 'Desplazamiento del globo ocular hacia dentro', 'category', false, false, 'CIE-11'),
('9A20.0Y', 'Otro desplazamiento axial especificado del globo ocular', 'category', false, false, 'CIE-11'),
('9A20.0Z', 'Desplazamiento axial del globo ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9A20.1', 'Desplazamiento no axial del globo ocular', 'category', false, false, 'CIE-11'),
('9A20.Y', 'Otro desplazamiento especificado del globo ocular', 'category', false, false, 'CIE-11'),
('9A20.Z', 'Desplazamiento del globo ocular, sin especificación', 'category', false, false, 'CIE-11'),
('9A21', 'Infección orbitaria', 'category', false, false, 'CIE-11'),
('9A21.0', 'Celulitis orbitaria', 'category', false, false, 'CIE-11'),
('9A21.1', 'Absceso subperióstico orbitario', 'category', false, false, 'CIE-11'),
('9A21.2', 'Absceso orbitario', 'category', false, false, 'CIE-11'),
('9A21.3', 'Periostitis de la órbita', 'category', false, false, 'CIE-11'),
('9A21.Y', 'Otra infección orbitaria especificada', 'category', false, false, 'CIE-11'),
('9A21.Z', 'Infección orbitaria, sin especificación', 'category', false, false, 'CIE-11'),
('9A22', 'Inflamación orbitaria', 'category', false, false, 'CIE-11'),
('9A22.0', 'Orbitopatía distiroidea', 'category', false, false, 'CIE-11'),
('9A22.1', 'Inflamación orbitaria difusa', 'category', false, false, 'CIE-11'),
('9A22.2', 'Inflamación granulomatosa orbitaria', 'category', false, false, 'CIE-11'),
('9A22.Y', 'Otra inflamación orbitaria especificada', 'category', false, false, 'CIE-11'),
('9A22.Z', 'Inflamación orbitaria, sin especificación', 'category', false, false, 'CIE-11'),
('9A23', 'Quiste orbitario', 'category', false, false, 'CIE-11'),
('9A23.0', 'Quiste orbitario congénito', 'category', false, false, 'CIE-11'),
('9A23.1', 'Quiste orbitario adquirido', 'category', false, false, 'CIE-11'),
('9A23.Z', 'Quiste orbitario, sin especificación', 'category', false, false, 'CIE-11'),
('9A24', 'Deformidad ósea de la órbita', 'category', false, false, 'CIE-11'),
('9A24.0', 'Contracción de la órbita', 'category', false, false, 'CIE-11'),
('9A24.1', 'Expansión de la órbita', 'category', false, false, 'CIE-11'),
('9A24.3', 'Ampliación de la órbita ósea', 'category', false, false, 'CIE-11'),
('9A24.4', 'Exostosis de la órbita', 'category', false, false, 'CIE-11'),
('9A24.Y', 'Otra deformidad ósea especificada de la órbita', 'category', false, false, 'CIE-11'),
('9A24.Z', 'Deformidad ósea de la órbita, sin especificación', 'category', false, false, 'CIE-11'),
('9A25', 'Deformidad de partes blandas de la órbita', 'category', false, false, 'CIE-11'),
('9A25.0', 'Órbita anoftálmica', 'category', false, false, 'CIE-11'),
('9A25.1', 'Órbita microftálmica', 'category', false, false, 'CIE-11'),
('9A25.2', 'Órbita contraída', 'category', false, false, 'CIE-11'),
('9A25.3', 'Edema de la órbita', 'category', false, false, 'CIE-11'),
('9A25.4', 'Hemorragia de la órbita', 'category', false, false, 'CIE-11'),
('9A25.5', 'Atrofia de partes blandas de la órbita', 'category', false, false, 'CIE-11'),
('9A25.Y', 'Otra deformidad especificada de partes blandas de la órbita', 'category', false, false, 'CIE-11'),
('9A25.Z', 'Deformidad de partes blandas de la órbita, sin especificación', 'category', false, false, 'CIE-11'),
('9A26', 'Deformidad combinada de la órbita (ósea y de partes blandas)', 'category', false, false, 'CIE-11'),
('9A2Y', 'Otros trastornos especificados de la órbita', 'category', false, false, 'CIE-11'),
('9A2Z', 'Trastornos de la órbita, sin especificación', 'category', false, false, 'CIE-11'),
('9A4Y', 'Otros trastornos especificados de los anexos oculares o de la órbita', 'category', false, false, 'CIE-11'),
('9A4Z', 'Trastornos anexos oculares o de la órbita, sin especificación', 'category', false, false, 'CIE-11'),
('9A60', 'Conjuntivitis', 'category', false, false, 'CIE-11'),
('9A60.0', 'Conjuntivitis papilar', 'category', false, false, 'CIE-11'),
('9A60.00', 'Conjuntivitis papilar gigante', 'category', false, false, 'CIE-11'),
('9A60.01', 'Conjuntivitis atópica aguda', 'category', false, false, 'CIE-11'),
('9A60.02', 'Conjuntivitis alérgica', 'category', false, false, 'CIE-11'),
('9A60.0Y', 'Otra conjuntivitis papilar especificada', 'category', false, false, 'CIE-11'),
('9A60.0Z', 'Conjuntivitis papilar, sin especificación', 'category', false, false, 'CIE-11'),
('9A60.1', 'Conjuntivitis folicular', 'category', false, false, 'CIE-11'),
('9A60.2', 'Conjuntivitis cicatrizante', 'category', false, false, 'CIE-11'),
('9A60.3', 'Conjuntivitis mucopurulenta', 'category', false, false, 'CIE-11'),
('9A60.30', 'Ulceración de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A60.31', 'Absceso de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A60.32', 'Conjuntivitis por bacilo de Koch-Weeks', 'category', false, false, 'CIE-11'),
('9A60.33', 'Conjuntivitis epidémica aguda', 'category', false, false, 'CIE-11'),
('9A60.3Y', 'Otra conjuntivitis mucopurulenta especificada', 'category', false, false, 'CIE-11'),
('9A60.3Z', 'Conjuntivitis mucopurulenta, sin especificación', 'category', false, false, 'CIE-11'),
('9A60.4', 'Blefaroconjuntivitis', 'category', false, false, 'CIE-11'),
('9A60.5', 'Queratoconjuntivitis vernal', 'category', false, false, 'CIE-11'),
('9A60.6', 'Conjuntivitis serosa no viral', 'category', false, false, 'CIE-11'),
('9A60.Y', 'Otra conjuntivitis especificada', 'category', false, false, 'CIE-11'),
('9A60.Z', 'Conjuntivitis, sin especificación', 'category', false, false, 'CIE-11'),
('9A61', 'Algunos trastornos especificados de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A61.0', 'Pinguécula', 'category', false, false, 'CIE-11'),
('9A61.1', 'Pterigion', 'category', false, false, 'CIE-11'),
('9A61.2', 'Seudopterigion de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A61.3', 'Cicatrices conjuntivales', 'category', false, false, 'CIE-11'),
('9A61.4', 'Trastornos vasculares de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A61.40', 'Anomalías vasculares de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A61.4Y', 'Otros trastornos vasculares especificados de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A61.4Z', 'Trastornos vasculares de la conjuntiva, sin especificación', 'category', false, false, 'CIE-11'),
('9A61.5', 'Hemorragia conjuntival o subconjuntival', 'category', false, false, 'CIE-11'),
('9A61.6', 'Degeneraciones o depósitos conjuntivales o subconjuntivales', 'category', false, false, 'CIE-11'),
('9A61.Z', 'Otros trastornos especificados de la conjuntiva, sin especificación', 'category', false, false, 'CIE-11'),
('9A62', 'Penfigoide de la membrana mucosa con compromiso ocular', 'category', false, false, 'CIE-11'),
('9A6Y', 'Otros trastornos especificados de la conjuntiva', 'category', false, false, 'CIE-11'),
('9A6Z', 'Trastornos de la conjuntiva, sin especificación', 'category', false, false, 'CIE-11'),
('9A70', 'Distrofias corneales hereditarias', 'category', false, false, 'CIE-11'),
('9A70.0', 'Distrofia corneal endotelial', 'category', false, false, 'CIE-11'),
('9A70.Y', 'Otras distrofias corneales hereditarias especificadas', 'category', false, false, 'CIE-11'),
('9A70.Z', 'Distrofias corneales hereditarias, sin especificación', 'category', false, false, 'CIE-11'),
('9A71', 'Queratitis infecciosa', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;