BEGIN;
INSERT INTO diseases (code, name, classification) VALUES
('XM3KM3', 'Estiramato', 'category', false, false, 'CIE-11'),
('XM2339', 'Febarbamato', 'category', false, false, 'CIE-11'),
('XM09D8', 'Derivados de oxazol, tiazina y triazina', 'category', false, false, 'CIE-11'),
('XM8MD5', 'Clormezanona', 'category', false, false, 'CIE-11'),
('XM7Q44', 'Clorzoxazona', 'category', false, false, 'CIE-11'),
('XM7ZQ9', 'Zoxazolamina', 'category', false, false, 'CIE-11'),
('XM5PZ1', 'Metaxalona', 'category', false, false, 'CIE-11'),
('XM09Y8', 'Suxametonio', 'category', false, false, 'CIE-11'),
('XM5CB4', 'Pancuronio', 'category', false, false, 'CIE-11'),
('XM9416', 'Galamina', 'category', false, false, 'CIE-11'),
('XM7S28', 'Vecuronio', 'category', false, false, 'CIE-11'),
('XM6X03', 'Citrato de orfenadrina', 'category', false, false, 'CIE-11'),
('XM5US2', 'Baclofen', 'category', false, false, 'CIE-11'),
('XM1BK1', 'Tizanidina', 'category', false, false, 'CIE-11'),
('XM26R3', 'Pridinol', 'category', false, false, 'CIE-11'),
('XM4MA5', 'Tolperisona', 'category', false, false, 'CIE-11'),
('XM1HD7', 'Mefenesina', 'category', false, false, 'CIE-11'),
('XM2RH8', 'Tetrazepam', 'category', false, false, 'CIE-11'),
('XM7LP5', 'Ciclobenzaprina', 'category', false, false, 'CIE-11'),
('XM52Y2', 'Tiocolchicósido', 'category', false, false, 'CIE-11'),
('XM9UU4', 'Eperisona', 'category', false, false, 'CIE-11'),
('XM7995', 'Feniramidol', 'category', false, false, 'CIE-11'),
('XM0W80', 'Aflocualona', 'category', false, false, 'CIE-11'),
('XM3V06', 'Napadisilato de aclatonio', 'category', false, false, 'CIE-11'),
('XM9RW1', 'Relajación muscular Anestesia', 'category', false, false, 'CIE-11'),
('XM5GC4', 'Besilato de atracurio', 'category', false, false, 'CIE-11'),
('XM8PU1', 'Carbolonio (bromuro)', 'category', false, false, 'CIE-11'),
('XM7DG2', 'Bromuro de decametonio', 'category', false, false, 'CIE-11'),
('XM6XS1', 'Cloruro de Dimetiltubocurarinio', 'category', false, false, 'CIE-11'),
('XM8A87', 'Flaxedil', 'category', false, false, 'CIE-11'),
('XM9QC2', 'Bromuro de Hexafluorenio', 'category', false, false, 'CIE-11'),
('XM9WH2', 'Hexanuorenium', 'category', false, false, 'CIE-11'),
('XM82Z5', 'Bromuro de hexcarbacolina', 'category', false, false, 'CIE-11'),
('XM3676', 'Laudexio', 'category', false, false, 'CIE-11'),
('XM3RJ7', 'Metocarbamol relajante musculoesquelético', 'category', false, false, 'CIE-11'),
('XM4W78', 'Agentes relajantes musculares afectando al esqueleto', 'category', false, false, 'CIE-11'),
('XM3SC6', 'Agentes bloqueadores mioneurales', 'category', false, false, 'CIE-11'),
('XM2UG5', 'Medicamento bloqueante neuromuscular', 'category', false, false, 'CIE-11'),
('XM8QC2', 'Relajantes musculares esqueléticos', 'category', false, false, 'CIE-11'),
('XM91M0', 'Espasmolítico del músculo esquelético', 'category', false, false, 'CIE-11'),
('XM7142', 'Cloruro de suxetonio', 'category', false, false, 'CIE-11'),
('XM9502', 'Woorali (curare)', 'category', false, false, 'CIE-11'),
('XM5ZN8', 'Dantroleno', 'category', false, false, 'CIE-11'),
('XM0WW2', 'Bruceine', 'category', false, false, 'CIE-11'),
('XM7E87', 'Hidrastina', 'category', false, false, 'CIE-11'),
('XM7C89', 'Lututrina', 'category', false, false, 'CIE-11'),
('XM20G5', 'Estricnina medicinal', 'category', false, false, 'CIE-11'),
('XM8NV1', 'Terapia para la distrofia muscular de Duchenne', 'category', false, false, 'CIE-11'),
('XM1CL7', 'Ataluren', 'category', false, false, 'CIE-11'),
('XM7H79', 'Drisapersen', 'category', false, false, 'CIE-11'),
('XM0BM1', 'Eteplirsen', 'category', false, false, 'CIE-11'),
('XM6TG6', 'Hidroquinina', 'category', false, false, 'CIE-11'),
('XM0TQ8', 'Ácido aceneurámico', 'category', false, false, 'CIE-11'),
('XM90G7', 'Nusinersen', 'category', false, false, 'CIE-11'),
('XM0U21', 'Viltolarsen', 'category', false, false, 'CIE-11'),
('XM4VE2', 'Casimersen', 'category', false, false, 'CIE-11'),
('XM2501', 'Toxina B de rimabotulinum', 'category', false, false, 'CIE-11'),
('XM0BF0', 'Toxina A de Abobotulinum', 'category', false, false, 'CIE-11'),
('XM21V3', 'Toxina incobotulínico tipo A', 'category', false, false, 'CIE-11'),
('XM5JZ1', 'Toxina Daxibotulinum A', 'category', false, false, 'CIE-11'),
('XM2L71', 'Toxina letibotulinum A', 'category', false, false, 'CIE-11'),
('XM9P78', 'Medicamentos para las enfermedades obstructivas de las vías respiratorias.', 'category', false, false, 'CIE-11'),
('XM3R34', 'Ácido cromoglícico', 'category', false, false, 'CIE-11'),
('XM4TP3', 'Nedocromil', 'category', false, false, 'CIE-11'),
('XM0B09', 'Antileucotrienos', 'category', false, false, 'CIE-11'),
('XM9BZ0', 'Zafirlukast', 'category', false, false, 'CIE-11'),
('XM1C43', 'Pranlukast', 'category', false, false, 'CIE-11'),
('XM10P5', 'Montelukast', 'category', false, false, 'CIE-11'),
('XM12R0', 'Ibudilast', 'category', false, false, 'CIE-11'),
('XM4U85', 'Anticuerpos monoclonales utilizados en enfermedades de las vías respiratorias.', 'category', false, false, 'CIE-11'),
('XM4LH9', 'Omalizumab', 'category', false, false, 'CIE-11'),
('XM6VB5', 'Reslizumab', 'category', false, false, 'CIE-11'),
('XM0KT0', 'Benralizumab', 'category', false, false, 'CIE-11'),
('XM82N7', 'Amlexanox', 'category', false, false, 'CIE-11'),
('XM5SD1', 'Acefilina piperazina', 'category', false, false, 'CIE-11'),
('XM1719', 'Acepifilina', 'category', false, false, 'CIE-11'),
('XM6493', 'Ambufilina', 'category', false, false, 'CIE-11'),
('XM5XJ1', 'Aminofilina', 'category', false, false, 'CIE-11'),
('XM5Y44', 'Bamifilina', 'category', false, false, 'CIE-11'),
('XM1QL3', 'Bufilina', 'category', false, false, 'CIE-11'),
('XM31P6', 'Emprofilina', 'category', false, false, 'CIE-11'),
('XM1W21', 'Etamifilina.', 'category', false, false, 'CIE-11'),
('XM3ZP6', 'Levoproxifilina', 'category', false, false, 'CIE-11'),
('XM81W0', 'Oxtrifilina', 'category', false, false, 'CIE-11'),
('XM5YJ3', 'Proxifilina', 'category', false, false, 'CIE-11'),
('XM4L37', 'Teobromina', 'category', false, false, 'CIE-11'),
('XM1FP4', 'Teofilina', 'category', false, false, 'CIE-11'),
('XM07L0', 'Ácido aminobenzoico teofilina', 'category', false, false, 'CIE-11'),
('XM07F4', 'Teofilina piperazina p-amino-benzoato', 'category', false, false, 'CIE-11'),
('XM9608', 'Doxofilina', 'category', false, false, 'CIE-11'),
('XM7X44', 'Teofilinacetato de mepiramina', 'category', false, false, 'CIE-11'),
('XM42T9', 'Fenspirida', 'category', false, false, 'CIE-11'),
('XM40T5', 'Eprozinol', 'category', false, false, 'CIE-11'),
('XM8DS8', 'Seratrodast', 'category', false, false, 'CIE-11'),
('XM53U2', 'Roflumilast', 'category', false, false, 'CIE-11'),
('XM5Y33', 'Tranilast', 'category', false, false, 'CIE-11'),
('XM2351', 'Bufrolin', 'category', false, false, 'CIE-11'),
('XM9Y50', 'Tezepelumab', 'category', false, false, 'CIE-11'),
('XM6JV7', 'Ambroxol', 'category', false, false, 'CIE-11'),
('XM4A47', 'Cloruro de amonio expectorante', 'category', false, false, 'CIE-11'),
('XM8CT0', 'Bromhexina', 'category', false, false, 'CIE-11'),
('XM9FP2', 'Yoduro de calcio', 'category', false, false, 'CIE-11'),
('XM3XU8', 'Carbocisteína', 'category', false, false, 'CIE-11'),
('XM2NU9', 'Mezcla para la tos (jarabe)', 'category', false, false, 'CIE-11'),
('XM1MJ1', 'Mezcla para la tos (expectorante)', 'category', false, false, 'CIE-11'),
('XM81Q9', 'Creosota', 'category', false, false, 'CIE-11'),
('XM4C87', 'Jarabe de creosota', 'category', false, false, 'CIE-11'),
('XM68U4', 'Extracto de regaliz deglicirrizado', 'category', false, false, 'CIE-11'),
('XM1KM0', 'Domiodol', 'category', false, false, 'CIE-11'),
('XM28N4', 'Dornasa', 'category', false, false, 'CIE-11'),
('XM71N5', 'Eprazinona', 'category', false, false, 'CIE-11'),
('XM7QX2', 'Guayacolato de glicerilo', 'category', false, false, 'CIE-11'),
('XM86G0', 'Extracto de Glicirriza', 'category', false, false, 'CIE-11'),
('XM3CL2', 'Ácido de Glicirrícico', 'category', false, false, 'CIE-11'),
('XM8EW0', 'Glicirricinato de potasio', 'category', false, false, 'CIE-11'),
('XM0G60', 'Derivados de Guayacol', 'category', false, false, 'CIE-11'),
('XM48K1', 'Guaimesal', 'category', false, false, 'CIE-11'),
('XM8GY5', 'Guaifenesin', 'category', false, false, 'CIE-11'),
('XM31Y1', 'Ácido hidriódico', 'category', false, false, 'CIE-11'),
('XM3E62', 'Yoduro de potasio (expectorante)', 'category', false, false, 'CIE-11'),
('XM60L0', 'Glicerol yodado', 'category', false, false, 'CIE-11'),
('XM8BL3', 'Ipecacuana', 'category', false, false, 'CIE-11'),
('XM2K57', 'Letosteína', 'category', false, false, 'CIE-11'),
('XM9Q09', 'Regaliz', 'category', false, false, 'CIE-11'),
('XM6MB5', 'Mecisteína', 'category', false, false, 'CIE-11'),
('XM4DQ1', 'Droga mucolítica', 'category', false, false, 'CIE-11'),
('XM4KG8', 'Organidina', 'category', false, false, 'CIE-11'),
('XM8A78', 'Extracto de quillaja', 'category', false, false, 'CIE-11'),
('XM44A1', 'Droga respiratoria expectorante', 'category', false, false, 'CIE-11'),
('XM4Y94', 'S-Carboximetil-cisteína', 'category', false, false, 'CIE-11'),
('XM1Y62', 'Senega', 'category', false, false, 'CIE-11'),
('XM92P8', 'Sobrerol', 'category', false, false, 'CIE-11'),
('XM06E7', 'Dibunato de sodio', 'category', false, false, 'CIE-11'),
('XM2BM5', 'Droga reductora de la viscosidad del esputo', 'category', false, false, 'CIE-11'),
('XM7BF1', 'Estepronina', 'category', false, false, 'CIE-11'),
('XM1PU5', 'Sulfogayacol', 'category', false, false, 'CIE-11'),
('XM6JE5', 'Superinona', 'category', false, false, 'CIE-11'),
('XM1CP3', 'Tenoglicina', 'category', false, false, 'CIE-11'),
('XM0ES0', 'Hidrato de terpina (cis)', 'category', false, false, 'CIE-11'),
('XM1F74', 'Tiloxapol', 'category', false, false, 'CIE-11'),
('XM1KG9', 'Pentasulfuro de antimonio', 'category', false, false, 'CIE-11'),
('XM61F4', 'Dornasa alfa', 'category', false, false, 'CIE-11'),
('XM48C4', 'Raíz de Althaeae', 'category', false, false, 'CIE-11'),
('XM8983', 'Guaiacolsulfonato', 'category', false, false, 'CIE-11'),
('XM5QU8', 'Levoverbenona', 'category', false, false, 'CIE-11'),
('XM48W4', 'Hederae helicis folium', 'category', false, false, 'CIE-11'),
('XM7Q79', 'Cineol', 'category', false, false, 'CIE-11'),
('XM66E3', 'Neltenexina', 'category', false, false, 'CIE-11'),
('XM7Y66', 'Erdosteína', 'category', false, false, 'CIE-11'),
('XM6NJ7', 'Benproperina', 'category', false, false, 'CIE-11'),
('XM8G23', 'Benzonatato', 'category', false, false, 'CIE-11'),
('XM1U36', 'Bromuro de Bibenzonio', 'category', false, false, 'CIE-11'),
('XM8WM3', 'Butamirato', 'category', false, false, 'CIE-11'),
('XM4D27', 'Clobutinol', 'category', false, false, 'CIE-11'),
('XM9DL9', 'Clofedianol', 'category', false, false, 'CIE-11'),
('XM80M9', 'Cloperastina', 'category', false, false, 'CIE-11'),
('XM9KL2', 'Dimetoxanato', 'category', false, false, 'CIE-11'),
('XM6995', 'Dropropizina', 'category', false, false, 'CIE-11'),
('XM61F3', 'Dibunato de etilo', 'category', false, false, 'CIE-11'),
('XM0SA9', 'Fedrilato', 'category', false, false, 'CIE-11'),
('XM5BB1', 'Fominoben', 'category', false, false, 'CIE-11'),
('XM8300', 'Isoaminilo', 'category', false, false, 'CIE-11'),
('XM97D0', 'Levodropropizina', 'category', false, false, 'CIE-11'),
('XM3WX2', 'Metorato', 'category', false, false, 'CIE-11'),
('XM2ET3', 'Oxeladina', 'category', false, false, 'CIE-11'),
('XM9FU3', 'Oxolamina', 'category', false, false, 'CIE-11'),
('XM4331', 'Pentoxiverina', 'category', false, false, 'CIE-11'),
('XM7G25', 'Picoperina', 'category', false, false, 'CIE-11'),
('XM84C4', 'Pipazetato', 'category', false, false, 'CIE-11'),
('XM0HR9', 'Piperidiona', 'category', false, false, 'CIE-11'),
('XM8JR1', 'Prenoxdiazina', 'category', false, false, 'CIE-11'),
('XM9KN8', 'Zipeprol', 'category', false, false, 'CIE-11'),
('XM6SJ0', 'Dibunate', 'category', false, false, 'CIE-11'),
('XM1G75', 'Meprotixol', 'category', false, false, 'CIE-11'),
('XM2W89', 'Morclofona', 'category', false, false, 'CIE-11'),
('XM7UA5', 'Nepinalona', 'category', false, false, 'CIE-11'),
('XM06F9', 'Butetamato', 'category', false, false, 'CIE-11'),
('XM4SL3', 'Gefapixant', 'category', false, false, 'CIE-11'),
('XM4J58', 'Antihistamínicos', 'category', false, false, 'CIE-11'),
('XM2JE5', 'Antihistamínicos de primera generación', 'category', false, false, 'CIE-11'),
('XM8MV2', 'Éteres de aminoalquilo', 'category', false, false, 'CIE-11'),
('XM1TL5', 'Bromazina', 'category', false, false, 'CIE-11'),
('XM6KY0', 'Difenhidramina', 'category', false, false, 'CIE-11'),
('XM3DL4', 'Clemastina', 'category', false, false, 'CIE-11'),
('XM4QD7', 'Clorfenoxamina', 'category', false, false, 'CIE-11'),
('XM7GV4', 'Difenilpiralina', 'category', false, false, 'CIE-11'),
('XM9KZ9', 'Carbinoxamina', 'category', false, false, 'CIE-11'),
('XM77K6', 'Doxilamina', 'category', false, false, 'CIE-11'),
('XM7180', 'Piprinhidrinato', 'category', false, false, 'CIE-11'),
('XM3FN3', 'Rotoxamina', 'category', false, false, 'CIE-11'),
('XM5YE8', 'Alquilaminas sustituidas', 'category', false, false, 'CIE-11'),
('XM5PK9', 'Bromfeniramina', 'category', false, false, 'CIE-11'),
('XM6CF9', 'Dexclorfeniramina', 'category', false, false, 'CIE-11'),
('XM74S1', 'Dimetindeno', 'category', false, false, 'CIE-11'),
('XM9VG3', 'Clorfeniramina', 'category', false, false, 'CIE-11'),
('XM4UU4', 'Feniramina', 'category', false, false, 'CIE-11'),
('XM1107', 'Dexbromfeniramina', 'category', false, false, 'CIE-11'),
('XM4AA0', 'Talastina', 'category', false, false, 'CIE-11'),
('XM9MB0', 'Etilendiaminas sustituidas', 'category', false, false, 'CIE-11'),
('XM54R1', 'Pirilamina', 'category', false, false, 'CIE-11'),
('XM9CM1', 'Cloropiramina', 'category', false, false, 'CIE-11'),
('XM0N55', 'Tripelenamina', 'category', false, false, 'CIE-11'),
('XM7TD1', 'Metapirileno', 'category', false, false, 'CIE-11'),
('XM6NM2', 'Tonzilamina', 'category', false, false, 'CIE-11'),
('XM4NS9', 'Histapyrrodine', 'category', false, false, 'CIE-11'),
('XM52P9', 'Derivados de la fenotiazina', 'category', false, false, 'CIE-11'),
('XM1N75', 'Alimemazina', 'category', false, false, 'CIE-11'),
('XM0605', 'Prometazina', 'category', false, false, 'CIE-11'),
('XM9QY1', 'Tietilperazina', 'category', false, false, 'CIE-11'),
('XM5E89', 'Metdilazina', 'category', false, false, 'CIE-11'),
('XM5EB9', 'Mequitazina', 'category', false, false, 'CIE-11'),
('XM5DB5', 'Oxomemazina', 'category', false, false, 'CIE-11'),
('XM4Z91', 'Isotipendilo', 'category', false, false, 'CIE-11'),
('XM5QG6', 'Hidroxietilprometazina', 'category', false, false, 'CIE-11'),
('XM29Q8', 'Thiazinam', 'category', false, false, 'CIE-11'),
('XM9NA0', 'Derivados de piperazina de agentes antihistamínicos de primera generación', 'category', false, false, 'CIE-11'),
('XM8GH2', 'Buclizina', 'category', false, false, 'CIE-11'),
('XM0S26', 'Ciclizina', 'category', false, false, 'CIE-11'),
('XM9SK3', 'Clorciclizina', 'category', false, false, 'CIE-11'),
('XM1A78', 'Meclizina', 'category', false, false, 'CIE-11'),
('XM6AV1', 'Oxatomida', 'category', false, false, 'CIE-11'),
('XM0QD9', 'Cetirizina', 'category', false, false, 'CIE-11'),
('XM07V7', 'Piperazina', 'category', false, false, 'CIE-11'),
('XM1VF1', 'Dietilcarbamazina', 'category', false, false, 'CIE-11'),
('XM5AC9', 'Levocetirizina', 'category', false, false, 'CIE-11'),
('XM4GX4', 'Bamipina', 'category', false, false, 'CIE-11'),
('XM11C5', 'Ciproheptadina', 'category', false, false, 'CIE-11'),
('XM9BD4', 'Fenindamina', 'category', false, false, 'CIE-11'),
('XM5Q41', 'Antazolin', 'category', false, false, 'CIE-11'),
('XM8RT2', 'Triprolidina', 'category', false, false, 'CIE-11'),
('XM6Z93', 'Azatadina', 'category', false, false, 'CIE-11'),
('XM4280', 'Mebhidrolina', 'category', false, false, 'CIE-11'),
('XM7ZS2', 'Tenalidina', 'category', false, false, 'CIE-11'),
('XM0404', 'Pipoxizina', 'category', false, false, 'CIE-11'),
('XM5463', 'Setastina', 'category', false, false, 'CIE-11'),
('XM3B95', 'Antihistamínicos de segunda generación', 'category', false, false, 'CIE-11'),
('XM6G21', 'Derivados de piperazina de agentes antihistamínicos de segunda generación', 'category', false, false, 'CIE-11'),
('XM7S59', 'Astemizol', 'category', false, false, 'CIE-11'),
('XM2S36', 'Terfenadina', 'category', false, false, 'CIE-11'),
('XM4PE5', 'Loratadina', 'category', false, false, 'CIE-11'),
('XM4F63', 'Ketotifeno', 'category', false, false, 'CIE-11'),
('XM4GA2', 'Acrivastina', 'category', false, false, 'CIE-11'),
('XM9VB8', 'Azelastina', 'category', false, false, 'CIE-11'),
('XM9EU0', 'Ebastina', 'category', false, false, 'CIE-11'),
('XM7J45', 'Mizolastina', 'category', false, false, 'CIE-11'),
('XM1586', 'Fexofenadina', 'category', false, false, 'CIE-11'),
('XM2656', 'Desloratadina', 'category', false, false, 'CIE-11'),
('XM3E25', 'Rupatadina', 'category', false, false, 'CIE-11'),
('XM1WZ8', 'Bilastina', 'category', false, false, 'CIE-11'),
('XM3YG8', 'Quifenadina', 'category', false, false, 'CIE-11'),
('XM57C9', 'Pirrobutamina', 'category', false, false, 'CIE-11'),
('XM8ZS4', 'Deptropina', 'category', false, false, 'CIE-11'),
('XM0J21', 'Tritocualina', 'category', false, false, 'CIE-11'),
('XM70F3', 'Pimetixeno', 'category', false, false, 'CIE-11'),
('XM5BJ5', 'Epinastina', 'category', false, false, 'CIE-11'),
('XM40P7', 'Sequifenadina', 'category', false, false, 'CIE-11'),
('XM9L77', 'Doxantrazole', 'category', false, false, 'CIE-11'),
('XM0AP5', 'Almitrina', 'category', false, false, 'CIE-11'),
('XM9QA2', 'Amifenasole', 'category', false, false, 'CIE-11'),
('XM0WB3', 'Bemegride', 'category', false, false, 'CIE-11'),
('XM5T65', 'Bicuculina', 'category', false, false, 'CIE-11')
INSERT INTO diseases (code, name, level, is_chronic, requires_authorization, classification)
('XM7BN2', 'Analépticos estimulantes del sistema nervioso central', 'category', false, false, 'CIE-11'),
('XM6938', 'Estimulantes del sistema nervioso central antagonistas de los opiaceos', 'category', false, false, 'CIE-11'),
('XM3465', 'Crotetamida con cropropamida', 'category', false, false, 'CIE-11'),
('XM0A24', 'Dimefline', 'category', false, false, 'CIE-11'),
('XM2ZT4', 'Dimorfolamina', 'category', false, false, 'CIE-11'),
('XM3FP9', 'Doxapram', 'category', false, false, 'CIE-11'),
('XM6D72', 'Etamivan', 'category', false, false, 'CIE-11'),
('XM6YR1', 'Leptazol', 'category', false, false, 'CIE-11'),
('XM4CU0', 'Lobelina', 'category', false, false, 'CIE-11'),
('XM0001', 'Niketamida', 'category', false, false, 'CIE-11'),
('XM0Q86', 'Pentetrazol', 'category', false, false, 'CIE-11'),
('XM5VY2', 'Pimeclone', 'category', false, false, 'CIE-11'),
('XM4901', 'Pretcamida', 'category', false, false, 'CIE-11'),
('XM1D17', 'Mepixanox', 'category', false, false, 'CIE-11'),
('XM04S2', 'Otros productos del sistema respiratorio', 'category', false, false, 'CIE-11'),
('XM4HQ2', 'Óxido nítrico', 'category', false, false, 'CIE-11'),
('XM3CW0', 'Ivacaftor', 'category', false, false, 'CIE-11'),
('XM15G5', 'Ivacaftor y lumacaftor', 'category', false, false, 'CIE-11'),
('XM2QZ5', 'Ivacaftor y tezacaftor', 'category', false, false, 'CIE-11'),
('XM0MG9', 'Anfenicoles', 'category', false, false, 'CIE-11'),
('XM2TE7', 'Cloranfenicol', 'category', false, false, 'CIE-11'),
('XM40F4', 'Tiiamfenicol', 'category', false, false, 'CIE-11'),
('XM1JY8', 'Adicilina', 'category', false, false, 'CIE-11'),
('XM1LV7', 'Ancilina', 'category', false, false, 'CIE-11'),
('XM0JT4', 'Apalcilina', 'category', false, false, 'CIE-11'),
('XM46K9', 'Bacampicilina', 'category', false, false, 'CIE-11'),
('XM94E1', 'Penicilina Benetamina', 'category', false, false, 'CIE-11'),
('XM2SP1', 'Carfecilina', 'category', false, false, 'CIE-11'),
('XM9MK4', 'Cefalosporinas N (adicilina)', 'category', false, false, 'CIE-11'),
('XM4YY1', 'Clemizol penicilina', 'category', false, false, 'CIE-11'),
('XM2361', 'Ciclacilina', 'category', false, false, 'CIE-11'),
('XM9VG2', 'Hidrabamina penicilina', 'category', false, false, 'CIE-11'),
('XM7LA4', 'Imipenem', 'category', false, false, 'CIE-11'),
('XM0V84', 'Isoxazolil penicilina', 'category', false, false, 'CIE-11'),
('XM00H2', 'Metoxi bencil penicilina', 'category', false, false, 'CIE-11'),
('XM9XB6', 'Penetamato', 'category', false, false, 'CIE-11'),
('XM7Q57', 'Penicilina (cualquiera)', 'category', false, false, 'CIE-11'),
('XM71L1', 'Fenbenicilin', 'category', false, false, 'CIE-11');
ON CONFLICT (code) DO NOTHING;
COMMIT;